### ISSUE TITLE
Add Gson-like annotation to class fields

### ISSUE THREAD

**Issue by Gyld** [libgdx/libgdx#1004]
Can you add support for a gson equivalent of the @SerializedName annotation for json so you can call your class fields whatever you like and the object to json to object still works?

Eg.
<code>
@SerializedName("user_id");
public int userId;
</code>
So that user_id value from the json always go into userId and vice versa.

Thanks :)

**Comment by rohitgoyal** [comment]
Has it even been done?

**Comment by xGnoSiSx** [comment]
I hate how this can't be linked somehow to proguard obfuscation.

I have all json data classes added as exceptions to proguard, but i would like the code to translate json field names to obfuscated JVM classes and fields automagicaly with reflection and some tooling.

Yeah I know, I dream big!!!

**Comment by NathanSweet** [comment]
2013 was a long time ago. I don't know if GWT has access to all annotations? If it does, this wouldn't be too hard. We already use `@Deprecated`.
