### ISSUE TITLE
TiledMapPacker: multiple  TMX tilemaps input generate wrong results

### ISSUE THREAD

**Issue by hneuer** [libgdx/libgdx#1087]
In TiledMapPacker I see two issues:
- when filling the tilesetsToPack the name of the tilesets have to be unique across all the maps. This not not necessarily true as the names can be set by the user.
- The packTilesets method treats the gids of the tiles as if they were unique across all maps but they are only unique inside a single map. Because the gids are then used as index in the atlas file the texture regions get mixed up.

**Comment by badlogic** [comment]
@MobiDevelop is this still a thing?
