### ISSUE TITLE
dispose() never called on Android

### ISSUE THREAD

**Issue by mrgame64** [libgdx/libgdx#1187]
When I close the app with Gdx.app.exit(); (Android backend) the dispose() method of my ApplicationListener isn't called.

EDIT:
This was confirmed both via debugging in Eclipse (placed a breakpoint on the first method call in dispose()) and via logcat (System.out.println("Begin disposal") in dispose() is never called)

dispose() is however called in the LWJGL backend (confirmed both via debugging and console output)

EDIT2:
Device: Samsung Galaxy S3
OS: Android 4.1.2

**Comment by NoahGels** [comment]
Hi, 
if there is somebody else here who has this problem like me and doesn't use continuousRendering .
I just fixed the problem by overrdiding onDestroy in AndroidLauncher and call dispose there
