### ISSUE TITLE
Large delta after pause/resume (Android)

### ISSUE THREAD

**Issue by terryhau** [libgdx/libgdx#1196]
If a game (or in my case a live wallpaper) is paused for a long time, after resuming, Gdx.graphics.getDeltaTime() will give the delta of the entire pause duration. This causes  freeze/stutter on resume as the game tries to process possibly hours worth of delta.

Adding this to onDrawFrame before the delta calculation in AndroidGraphics/AndroidGraphicsDayDream/AndroidGraphicsLiveWallpaper should fix this I believe.

```
if (lresume)
    lastFrameTime = System.nanoTime()
```

I'm currently using this workaround

```
private boolean resuming;

    public void render()
    {
        float delta;
        if(resuming)
        {
            delta = 0f;
            resuming = false;
        }
        else
        {
            delta = Gdx.graphics.getRawDeltaTime();
        }

        ...
    }

    public void resume()
    {
        resuming = true;
    }
```

However, now I can't use the smoothed delta because it includes the large delta from the pause.

**Comment by ingoem** [comment]
Isn't the behavior now inconsistent across backends? If this is the way to go, shouldn't it be changed for the ios backend as well?

**Comment by chandujr** [comment]
This bug still exists in iOS. I'm porting my game using Intel MOE and the delta value adds up when paused and resumed. I have a countdown in my game depending on the delta time and this bug is causing problems.
