### ISSUE TITLE
[RoboVM]Textures with MipMaps not drawn

### ISSUE THREAD

**Issue by ghost** [libgdx/libgdx#1296]
It seems like using a MipMap TextureFilter with the RoboVM backend on IOS prevents the textures from being drawn on the screen. Instead black squares get rendered. Switching the filter to Linear or Nearest fixes the problem. I can only test this in the IPhoneSimulator on OS X, maybe its no issue with real devices.
![iphonemipmap](https://f.cloud.github.com/assets/468951/2090161/558dc094-8e90-11e3-98f7-52dfd213ce45.png)

I took the demo project supplied with the gdx-setup and added the TextureFilter to create a minimal example of the bug. [You can download it here](http://www.mediafire.com/download/81lsz75nszks1o3/iosmipmaps.zip)

**Comment by voidstarfire** [comment]
How would we implement this if we are loading these with the asset manager (like suppose to load textures)? 

The config option of specifying a mipmap doesn't work.

Example that works, but iOS is still blurry as hell.

  param.genMipMaps = true;

        if(Gdx.app.getType() == com.badlogic.gdx.Application.ApplicationType.iOS){
            param.minFilter = Texture.TextureFilter.Linear;
            param.magFilter = Texture.TextureFilter.Linear;
        }
        else{
            param.minFilter = Texture.TextureFilter.MipMapLinearNearest;
            param.magFilter = Texture.TextureFilter.Nearest;
        }


        for(String eachTextureName : this.listOfTextureNames){
            this.assetManager.load(eachTextureName, Texture.class, param);
        }
