### ISSUE TITLE
slf4j integration with desktop libgdx

### ISSUE THREAD

**Issue by eropple** [libgdx/libgdx#1311]
Was just using libgdx for a smallish project and was really hoping to be able to store logs in a little more flexible of a way than perling stdout. Replacing the stdout backend that's currently used with slf4j/logback wouldn't be a huge change and would allow for more flexibility (i.e., logging to a RollingFileAppender, being able to use a logback.xml to configure it) and probably slightly better performance (it logs on a separate thread).

If there's any interest in this I can hack it together tomorrow or Monday.

**Comment by shatterblast** [comment]
Can we close this, please?
