### ISSUE TITLE
List directory on desktop

### ISSUE THREAD

**Issue by saltares** [libgdx/libgdx#1375]
It'd be nice if we made `public FileHandle#FileHandle[] list ()` work on the desktop backend as well. Speaking from ignorance, could we use something like this? I'm happy to implement it myself.

http://stackoverflow.com/questions/1429172/how-do-i-list-the-files-inside-a-jar-file/1429275#1429275

**Comment by Metaphore** [comment]
Any news on it guys? Seems game preloader that loads all assets automatically is still hard to maintain to achieve full compatibility. Actually I have problems not only with jar's classpath assets, but with GWT too. By some reason, FileHandle#list() can't grab my audio(.ogg/.wav) and particles(.p) files (other files loads fine). It looks even strange cuz all these files contain inside symlink file that generates by HTML build.

**Comment by billy1380** [comment]
I found out on desktop (linux) doing a readString of a folder of type internal returns a line feed delimited string of the folder/filenames inside. If you really need to use a folder structure where you know whether the entries are going to be files or folders ahead of time or if you have left metadata/clues in the names, then you can easily use the combination to get to or copy file contents that way.

**Comment by badlogic** [comment]
Sorry, there's simply not good solution to this. If you test on the desktop, start your app in the assets directory, don't package them in the classpath. When deploying your desktop app, don't package your assets, but keep them next to your jar.

**Comment by Zvezdin** [comment]
How does one list and save the filenames in the directory during compile time as a workaround to the issue? I'm loading many resources from my assets directory and don't want to hardcode all their filenames.
