### ISSUE TITLE
ProgressBar knobBefore & knobAfter ignore background NinePatch paddning

### ISSUE THREAD

**Issue by Swiftwork** [libgdx/libgdx#1419]
Found a small issue where the ProgressBar renders both knobBefore and knobAfter outside the specified NinePatch backgrounds padding. I believe a simple change to the draw should fix this.
![capture](https://f.cloud.github.com/assets/455178/2305808/76acd8d6-a26e-11e3-9aa5-c0bafd89cf67.PNG)

Origional:

``` java
if (knobBefore != null) {
    knobBefore.draw(batch, x, y + (int)((height - knobBefore.getMinHeight()) * 0.5f), (int)(position + knobWidthHalf), knobBefore.getMinHeight());
}
if (knobAfter != null) {
    knobAfter.draw(batch, x + (int)(position + knobWidthHalf), y + (int)((height - knobAfter.getMinHeight()) * 0.5f), width - (int)(position + knobWidthHalf), knobAfter.getMinHeight());
}
```

Change:

``` java
if (knobBefore != null) {
    knobBefore.draw(batch, x + bg.getLeftWidth(), y + (int)((height - knobBefore.getMinHeight()) * 0.5f), (int)(position + knobWidthHalf), knobBefore.getMinHeight());
}
if (knobAfter != null) {
    knobAfter.draw(batch, x + (int)(position + knobWidthHalf), y + (int)((height - knobAfter.getMinHeight()) * 0.5f), width - (int)(position + knobWidthHalf) - bg.getRightWidth(), knobAfter.getMinHeight());
}
```

Add bg.getLeftWidth() to x on knobBefore and subtract bg.getRightWidth() from width on knobAfter.

**_Might be worth checking vertical bar aswell.**_

Kind Regards
Swiftwork

**Comment by WinterAlexander** [comment]
That resolved the knobBefore issue but the knobAfter is not correct. Similar change to what was done in the PR should be made to support proper padding in knobAfter.
