### ISSUE TITLE
3D Api: textures changes randomly

### ISSUE THREAD

**Issue by bosoni** [libgdx/libgdx#1472]
I tested xoppa's newest tutorial (frustum culling), it works fine with desktop and bluestacks emu, but when I test it in my phone (galaxy mini), models' textures changed when rotating/moving. It's like it doesnt always bind right texture. My test works like that too (textures changing), even I dont use frustum culling.
Using newest libgdx from git.

http://i58.tinypic.com/2lt5w5v.png
(you can see there are some invaders with ship's texture, and when rotating, other object's will change texture too)

**Comment by xoppa** [comment]
If anyone is experiencing this problem then please add this class to your project (make sure to update the package name): https://gist.github.com/xoppa/2a1e1adfa3f4764f17f2 and add `GL20Adreno20X.enable();` to your `create()` method. This will rebind the current shader everytime a texture is bound, which is basically the work-a-round proposed in the first link of @crazysaem. I wouldn't suggest doing this by default, you probably only want to do this when the device has an Adreno 20x gpu and is experiencing this issue.

I'm not sure how widely used the Adreno 20x is. We could (conditionally, based on the gpu?) integrate this fix in the android backend. Although I'm personally leaning in favor of not fixing this in core.
