### ISSUE TITLE
Timer thread dies on android an is not resurrected

### ISSUE THREAD

**Issue by suluke** [libgdx/libgdx#1548]
I am working with the Timer utility on an android application. LibGdx version is 0.9.9 (latest stable).
The issue is caused (again) by android's weird policy with keeping static objects over app restarts.
The following is a description what causes the problem to occur:
- The app launches for the first time 
- `Timer` is creating its `TimerThread`
- The thread registers itself as a `LifecycleListener`
- The app is left (works best for me when I turn off the screen and wait for the device to be pattern-locked)
- When the app is entered again, `onCreate` is called, leading to a new `initialize()ation`=> `Gdx.app` is new, with a new list of LifecycleListeners
- `Timer.thread` is not null, for it "statically survived" => It is not being created in `Timer.instance.start` (the method itself probably isn't even called, because `instance` survived, too)
- The timer's LifecycleListener methods are not invoked either, because the listener is not registered any more  

=> The thread remains dead

For fixing the problem, I suggest setting `Timer.thread` to null in `Timer.TimerThread.pause`. If you are concerned about increased unnecessary `TimerThread` instantiations, one might as well keep a reference to the actual `Thread` which is created in `TimerThread.resume`, allowing to poll the thread's state in `Timer.instance`

**Additional information:**
Strangely, I was not able to reproduce this issue when being connected to the pc (i.e. a power source). So I suggest using adb over network when debugging 
The problem occurred with all of our team members, which is 6 persons with at least 3 different device types.

**Comment by asherbar** [comment]
Using libgdx 1.5.4 I'm running into the exact [issue](http://stackoverflow.com/questions/30536260/timer-not-resuming-after-game-loosing-focus?noredirect=1#comment49147254_30536260) mentioned by @skunktrading [above me](https://github.com/libgdx/libgdx/issues/1548#issuecomment-45044377). Are there any plans to solve this soon?

**Comment by MobiDevelop** [comment]
@asherbar, the proposed solution has already been integrated. If you are still having a problem, open a new issue with an example showing the issue.

**Comment by asherbar** [comment]
[Done](https://github.com/libgdx/libgdx/issues/3181).

**Comment by calanti** [comment]
I'm still struggling with this on libgdx 1.9.8. We use gdx-pay, and when the google play native overlay is closed, my game resumes but my timers are dead. The same happens when the screen is locked then unlocked, or navigating to a different app etc.
