### ISSUE TITLE
iOS backend getDensity() doesn't match other backends

### ISSUE THREAD

**Issue by alexander-mironov** [libgdx/libgdx#1597]
Graphics interface's Javadoc says:
> This is a scaling factor for the Density Independent Pixel unit, following the same conventions as android.util.DisplayMetrics#density, where one DIP is one pixel on an approximately 160 dpi screen. Thus on a 160dpi screen this density value will be 1; on a 120 dpi screen it would be .75; etc.

But on iOS backend it says:
> Returns the display density. @return 1.0f for non-retina devices, 2.0f for retina devices.

Usually programmer works with `Graphics` interface (via `Gdx.graphics`), so without explicit cast to `IOGraphics` he can't see appropriate Javadoc for this method in his IDE. 
I think there are two ways to fix this situation: add iOS-specific note to main Javadoc (not so cool) or to unify behavior of `getDensity()`, so this code running on iPad 2 will return 0.825 etc.

**Comment by Tom-Ski** [comment]
dpi should be correct for each device now, would it just be a case of setting the value for density as dpi/160?

**Comment by alexander-mironov** [comment]
I think it should be dpi/160 for non generic devices. If device type is unknown density should be equal to scale.
