### ISSUE TITLE
Gradle with intellij problem evaluating root project: Seems to be RoboVM

### ISSUE THREAD

**Issue by Mmarzex** [libgdx/libgdx#1603]
So I've tested this on a couple different project setups and have noticed that it happens everytime that no matter what platform I try to compile for I receive this error,

```
Error:(82, 0) Gradle: A problem occurred evaluating root project 'beta_runner'.
> com/github/jtakakura/gradle/plugins/robovm/RoboVMPlugin : Unsupported major.minor version 51.0

It appears to be an issue with RoboVMPlugin, I have no idea if this is widespread or an isolated case though.
```

**Comment by HimanshuSShephertz** [comment]
Could you please help me? I am also facing the same issue when building an application for iOS & Desktop App. 
Thanks in advance.

**Comment by Tom-Ski** [comment]
Please use the forum if you need help.

**Comment by orubel** [comment]
I get this with the latest version of Android SDK as well right now.

**Comment by siner01** [comment]
Error:(1, 1) A problem occurred evaluating root project 'app'.
> Plugin with id 'com.android.application' not found.
