### ISSUE TITLE
LWJGL renders incorrect size/resolution on Retina displays in Fullscreen

### ISSUE THREAD

**Issue by matteblair** [libgdx/libgdx#1623]
When running a project with the LWJGL backend on a Retina Macbook Pro and using fullscreen mode, the lower left-hand quarter of the correct viewing area fills the entire screen. 

I am unable to confirm whether this is a general issue for all Hi-DPI displays or just the RMBP.

To reproduce the issue, run the default LWJGL application with the following Main method on a Retina Macbook Pro:

``` java
import com.badlogic.gdx.Graphics.DisplayMode;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration;

public class Main {
    public static void main(String[] args) {
        LwjglApplicationConfiguration cfg = new LwjglApplicationConfiguration();
        DisplayMode dm = LwjglApplicationConfiguration.getDesktopDisplayMode();
        cfg.title = "my-gdx-game";
        cfg.width = dm.width;
        cfg.height = dm.height;
        cfg.fullscreen = true;

        new LwjglApplication(new MyGdxGame(), cfg);
    }
}
```

**Comment by voidstarfire** [comment]
Havn't had a chance to test yet cause I don't know an easy way to upgrade my current project into one of the nightlies. Will come back to you when I figure that out!

**Comment by voidstarfire** [comment]
I assume it's 1.5.3-SNAPSHOT? I'm getting No.Class Def of application listener.

**Comment by postpunkpl** [comment]
when you set a fullscreen (or change a window size with fitVieport) touch coordinates are still wrong

**Comment by badlogic** [comment]
Can you supply test code? I tested this and it works as expected.

**Comment by postpunkpl** [comment]
desktopLauncher:

	        config.width = 1024;
		config.height = 768;
		config.fullscreen = true;
		config.vSyncEnabled = true;
		config.useHDPI = true;

resize method:

Gdx.graphics.setDisplayMode(Gdx.graphics.getDesktopDisplayMode().width,Gdx.graphics.getDesktopDisplayMode().height, true);
		renderer.getViewport().update(width, height);
		renderer.getCamera().update();
		renderer.getCamera().position.set(
				renderer.getCamera().viewportWidth / 2,
				renderer.getCamera().viewportHeight / 2, 0);
		renderer.getStage().getViewport().update(width, height, false);

**Comment by badlogic** [comment]
Apart from this not showing any issues with mouse coords via code, why are
you setting the display mode in resize?

**Comment by postpunkpl** [comment]
setting a display mode at resize is junk, but i have no idea how to show you this issue :/

when i set a config width to 640, config height to 320 (it is a base resolution of my game) and play my game at window everything works fine, after a changing window size or playing fullscreen i have a problem with coordinates

**Comment by badlogic** [comment]
Can you provide a compiling applicationlistener that shows the issue? I
don't know what your renderer does or how you work with the mouse
coordinates from the code you provided.

**Comment by postpunkpl** [comment]
here you have two versions:

windowed version:
https://drive.google.com/file/d/0B2jjkU385I63MGMwcG9nNzJMUm8/view?usp=sharing

fullscreen version:
https://drive.google.com/file/d/0B2jjkU385I63MHdtNWFhMUNJdHM/view?usp=sharing

windowed.jar - everything works fine, you can drag a "tower-monster" form imageButton to any free cell on grid (not a path) BUT - after resizing a window there is a bug with checking a mouse coordinates

fullscreen.jar - the same bug as resized windowed version

I work with mouse with Gdx.input.getX() and getY()/

**Comment by badlogic** [comment]
I'm sorry, i can't do anything with the JARs. I need a minimal
ApplicationListener that lets me reproduce your issue. I tested the output
of Inout.getX()/getY() on Mac OS X in windowed/fullscreen mode with and
without hdpi and can not see any issues.

**Comment by postpunkpl** [comment]
you can clone my project from:

https://github.com/postpunkpl/fearsGIT

**Comment by badlogic** [comment]
I really don't want come off as a dick, but you can't expect me to import,
read & understand and debug your whole project for you. I asked for a
simple, compiling ApplicationListener that allows me to reproduce the
issue. For the third time already :(

**Comment by postpunkpl** [comment]
i understand you :) but i am a beginner and i don't know how to prepare a simple project with all that stuff

**Comment by badlogic** [comment]
Well, then we have a problem :) Maybe someone on IRC or the forums is
willing to check your whole code base. It is a bit peculiar that you
managed to write a TD game but can't create a simple app that demonstrates
your issue :)

**Comment by postpunkpl** [comment]
hehe, it is not certain that I can finish my TD ;) but i will try :)

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/Getting-help#executable-example-code
http://sscce.org/
http://stackoverflow.com/help/mcve

**Comment by voidstarfire** [comment]
Didn't know where to contact you badlogic; RoboVM version 4 is released!

**Comment by badlogic** [comment]
Thanks, i work on RoboVM. You can reach me om Twitter @badlogicgames :)

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://ozanakyol.com/rest.php?air>

 

loogie@basicelementdesign.com
