### ISSUE TITLE
GWT HttpRequest.setContent(InputStream, long) doesn't work

### ISSUE THREAD

**Issue by DanielCloudCredo** [libgdx/libgdx#1639]
Apologies if this is a known thing, but setting content of a request using an input stream (ByteArrayInputStream for example) doesn't work in GWT. 

```
String foo = "foo";
byte[] bytes = foo.getBytes();

HttpRequest request = new HttpRequest(HttpMethods.POST);
request.setContent(foo);
request.getContent(); //returns "foo"

request.setContent(new ByteArrayInputStream(bytes), bytes.length);
request.getContent()' //returns "undefined"
```

**Comment by JFixby** [comment]
Jesus Christ, please put this "Unfortunately, GWT only supports sending String content." on the first page of the LibGDX Networking wiki-page. That will save in sum like years of unnecessary suffering.

**Comment by MobiDevelop** [comment]
Well, when you put it like that, we have to just jump right on it.

**Comment by badlogic** [comment]
Totally agreed. Is there something else that needs our immediate attention?
After all, you are our best customer!

**Comment by JFixby** [comment]
The goal was to connect to a server from the GWT backend and to exchange some data.

KEY-ASSUMPTION: GDX's documentation says that networking in gdx-gwt works only through HTTP calls. Let's take this path.

1) At first we need to replace all other gdx-network calls in game's code taking into account that:
- HttpResponse arrives after the GDX-engine makes a cycle. So the call need to be implemented accordingly.
- HttpRequest in GDX does not support streams. We have to wrap all our byte stream-arrays in Base64 and send/receive strings instead. 

2) There is this issue with the GWT backend, HttpRequest drops exception: "Access-Control-Allow-Origin is not allowed." 
- https://github.com/libgdx/libgdx/issues/1433
- http://www.badlogicgames.com/forum/viewtopic.php?t=18069&p=76067

That means that we have to fix our server and to force it to return Access-Control-Allow-Origin="*"
For a Glassfish server, for example, we need to create a simple filter:
```
public class Sample implements Filter {
    @Override
    public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse,
            FilterChain chain) throws IOException, ServletException {
        HttpServletResponse resp = (HttpServletResponse)servletResponse;
        resp.setHeader("Access-Control-Allow-Origin", "*");
        chain.doFilter(servletRequest, servletResponse);
    }
}
```
And to install it to web.xml:
```
    <filter>
        <filter-name>SampleFilter</filter-name>
        <filter-class>com.jfixby.picfight.webproxy.glassfish.Sample</filter-class>
    </filter>
    <filter-mapping>
        <filter-name>SampleFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>
```

3) However then GWT backend will drop the next exception saying: "Request header field Access-Control-Allow-Origin is not allowed by Access-Control-Allow-Headers." Here we just need to edit the filter above and to add:
```
        resp.setHeader("Access-Control-Allow-Headers", "Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With, Access-Control-Allow-Origin");
```

4) There could be some more security issues.  For example the gwt backend can forbid retiving "Set-Cookie HTTP Header" through getHeader() method.

5) Anyway, let's say weeks later the http call was successfully executed, data submitted to the server from the GWT backend and the code "200 OK" received back.

At this point we will find that HttpResponse instance methods return null headers, null content and some other nulls. Debug shows that received HttpResponse instance contains no information except the code "200 OK". 

So passing all these 1-2-3-4-5 steps finally brings us to the conclusion that http call on gwt only supports sending data and not receiving back anything but HTTP result code. Dead end.

**Comment by MobiDevelop** [comment]
Your conclusion is incorrect, you can receive response bodies in the GWT backend.

If you are reporting a new issue, please open a new issue for yourself and include code to reproduce it.

**Comment by JFixby** [comment]
So when you said "Unfortunately, GWT only supports sending String content" you didn't mean that GWT only supports sending (and no receiving). And this is actually a bug that receiving doesn't work.

**Comment by MobiDevelop** [comment]
Receiving does work. I have used it.
