### ISSUE TITLE
Low framerate (25 instead of 60) on Android 2.3.6 (maybe other versions too)

### ISSUE THREAD

**Issue by lukKowalski** [libgdx/libgdx#1651]
Wher i start or pause/resume every app which is using libgdx its starting often at 25fps instead of 60fps. Im not sure how often it is but i guess its just random so ill just say 50/50. I have created a thread on StackOverflow here: http://stackoverflow.com/questions/22913391/libgdx-often-low-fps-after-android-device-resume so you can check other details of this problem there. I've also created a movie which is showing this issue really well https://www.youtube.com/watch?v=YjMr9fBYhHA&feature=youtu.be

**Comment by shdwfghtr** [comment]
I am having the same issue on Galaxy j7 sky pro, Android 6.0.1.  This is not device specific.  I request the issue be re-opened.  I don't want to get 1-star reviews because I chose to use libGDX.
