### ISSUE TITLE
Using Viewport forces a call to Gdx.gl.glViewport

### ISSUE THREAD

**Issue by zairon** [libgdx/libgdx#1661]
When using a Stage, the usage of Viewport forces a call to Gdx.gl.glViewport due to the update() method. This unnecessarily couples the OpenGL actual rendering surface to the Stage's virtual camera. With 0.9.9 and earlier versions, it was possible to use multiple stages without their updates causing the glViewport to change.

**Comment by doit-ceo** [comment]
Man, I spent like a week in this, finally I found this thread, calling Viewpont.update() (before drawing each stage) was what missing. Can we have this automatically, before in the Stage.draw()  ? if libGdx, tracks the calling to all viewports updates, it can call the update() in case the viewport changed 

I'm suggesting to have com.badlogic.gdx.math.Rectangle as static variable and one as local variable for each Viewport, then any call to  viewpont.update(), should change those, then just a matter of comparing this is  Stage.draw() , if there are different just call the Viewpont.update()

What you guys think ?

**Comment by NathanSweet** [comment]
You only need `Viewport#apply` to set `glViewport`, which does slightly less work than `update`.

Application code is in control of the viewport, eg any code can just call `glViewport`. If that happens, Stage/Viewport cannot detect the change, so it is up to application code to call `apply`. There is lots of other GL state you could change which would wreck stage rendering. Trying to monitor all that state and reset it to what stage needs isn't good.

The last applied viewport could be stored statically as you suggest, but this would only solve the problem when you have two stages (or two viewports). If you have a stage or viewport and something else that changes the viewport, Stage won't know `glViewport` changed and you still need `Viewport#apply`. It's probably better not to hide what is going on. Users should understand when `glViewport` is being changed.

It would be nice if it were easier to debug when the problem occurs, but I'm not sure how we could do that.

**Comment by nooone** [comment]
I think adding a paragraph about multiple (different) Viewports in the wiki and how to handle it, might already avoid a lot of people from doing it wrong.

A small code snippet to might be enough to let people know that additional steps are required in this case:

    viewportOne.apply();
    stageOne.draw();
    viewportTwo.apply();
    stageTwo.draw();

**Comment by doit-ceo** [comment]
I'm missing Viewport#apply (I guess because I'm in 1.2) , back to the tracking, I think it's still possible to track the changes at the glViewport#update level (not sure where is the implementation, is it native? ) , if not can we can print a warning of some sort or at least have this in an article somewhere, because I was so confused having two viewports,  most info in the net led me to batch.setProjectionMatrix(camera.combined); which wasn't the reason of the problem.

At least lets add a note into https://github.com/libgdx/libgdx/wiki/Viewports as this is a very reachable page. (i.e. Multiple Stages/Viewports)

**Comment by doit-ceo** [comment]
I totally agree with nooone, but lets also mention update() for people running 1.2 

My final question that I want to ask, how this would effect performance ?! I mean the whole idea of having two or more viewports and OpenGL viewports adjustments ? is it bad practice ?

**Comment by NathanSweet** [comment]
Added to wiki:
https://github.com/libgdx/libgdx/wiki/Viewports#multiple-viewports
The wiki is for the latest libgdx so I only mention apply.

If users cannot notice "bad" performance then you don't have a performance problem.
