### ISSUE TITLE
FragmentApplication never disposed

### ISSUE THREAD

**Issue by VinceAngel** [libgdx/libgdx#1677]
@bartolkaruza (and maybe other Fragment contributors)
The dispose() is never called when a fragment is detached, do we need to explicitly call something else than the initializeForView in the AndroidFragmentApplication ?

Thanks !

**Comment by domsu** [comment]
I still see this issue in 1.6.0 version

**Comment by MobiDevelop** [comment]
@domsu, you'd have to provide an example showing the issue for us to be able to look into it for you.

**Comment by domsu** [comment]
I will try to reproducte this error in sample project.

My AndroidFragmentApplication is attached into another fragment - not directly to Activity.
Maybe this is the cause.

**Comment by MobiDevelop** [comment]
Child fragments are a mess, even without involving libgdx. I would not be surprised if that the the cause.

**Comment by domsu** [comment]
I have created pull-request https://github.com/libgdx/libgdx/pull/3150
