### ISSUE TITLE
Fix please deadlock race condition with quick resume/pause in com.badlogic.gdx.backends.android.AndroidGraphics

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [libgdx/libgdx#1754]
In android graphics source code https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGraphics.java there is workaround that is not work in my case. 

void pause () {
        synchronized (synch) {
            if (!running) return;
            running = false;
            pause = true;
            while (pause) {
                try {
                    // TODO: fix deadlock race condition with quick resume/pause.
                    // Temporary workaround:
                    // Android ANR time is 5 seconds, so wait up to 4 seconds before assuming
                    // deadlock and killing process. This can easily be triggered by opening the
                    // Recent Apps list and then double-tapping the Recent Apps button with
                    // ~500ms between taps.
                    synch.wait(4000);
                    if (pause) {
                        Gdx.app.error("AndroidGraphics", "waiting for pause synchronization took too "
                            + "long; assuming deadlock and killing");
                        android.os.Process.killProcess(android.os.Process.myPid());
                    }
                } catch (InterruptedException ignored) {
                    Gdx.app.log("AndroidGraphics", "waiting for pause synchronization failed!");
                }
            }
        }
    }

I mean I always get

E/AndroidGraphics﹕ waiting for pause synchronization took too long; assuming deadlock and killing

Could you please provide better workaround or fix? 

Thanks in advance, Dmitry

**Comment by tpnet** [comment]
@dmitrykolesnikovich  Have you solved it? If I lock the screen on Android8.1 and unlock it, I will have this problem.

**Comment by Darkyenus** [comment]
@tpnet We cannot solve it without a repro case. Create a new issue, with proper reproduction steps + **full reproduction code**, ideally one that works inside an emulator, so that someone can look into it.
