### ISSUE TITLE
Fix iOS Todos

### ISSUE THREAD

**Issue by badlogic** [libgdx/libgdx#1828]
**General**
- [ ] see issue tracker, RoboVM specific issues are marked with [RoboVM]
- [ ] OGG is currently not supported by ObjectAL
- [x] Update: Vibration is not really supported on iOS. (Very Basic support added)

**IOSApplicationConfiguration**
- [ ] add compass

**IOSGraphics**
- [ ] need to store current device orientation for Input#getOrienation and consorts

**IOSInput** 
- [ ] getAzimuth(), getPitch(), getRoll(), getRotationMatrix() need to be implemented and output the same as android  **CoreMotion was misbehaving here, check issues resolved before re-implementing** 
- [ ] add compass support, fix up isPeripheralAvailable()

**IOSAudio**
- [ ] newAudioDevice(), new AudioRecorder() not implemented

**IOSSound**
- [x] add support for manipulating an already playing sound instance, seems to work through ALSource (see https://github.com/libgdx/libgdx/commit/c2f5bff128d7029aa87789ab7bde41c6af199d73)
- [x] add support for pitch shifting, not sure ObjectAL can do that (see https://github.com/libgdx/libgdx/commit/c2f5bff128d7029aa87789ab7bde41c6af199d73)

**Comment by hermith** [comment]
Isn't OGG support kind of crucial? MP3s are horrible for looping (and isn't really free to use) and WAVs are giant.

**Comment by WillCalderwood** [comment]
I'm with hermith on this one. I believe this is more than just a nice to have. I'll vote for this to be worked on asap. I may look at how to do it myself if I get time. That wont be for a good many months though.

**Comment by badlogic** [comment]
I'm afraid since everybody working on libGDX does it for free, there's no
feature voting. That being said, the iOS backend should get some fixes soon.

**Comment by BlueRiverInteractive** [comment]
Hacking in proper OGG support is quite a tough task. It can be split into the following 3 steps though:

1. Generating the ogg libraries for iOS: http://iosdeveloperzone.com/2012/09/29/tutorial-open-source-on-ios-part-2-compiling-libogg-on-ios/
2. Creating an objc wrapper for the ogg decoder. Something like: https://github.com/iosdevzone/IDZAQAudioPlayer/blob/master/IDZAQAudioPlayer/IDZOggVorbisFileDecoder.mm
3. Hacking the decoder wrapper into ObjectAL. Perhaps a custom ALBuffer can be used?

**Comment by schmoofer** [comment]
I was able to implement audio recording for IOS using bindings to native Audio Units. Are static libraries allowed or do we have to wait for RoboVM's implementation of Audio Units? If static libraries are allowed, where are static libraries included in the IOS libgdx backend? All the necessary files can be found here: https://github.com/schmoofer/RecorderLibrary

**Comment by denisk20** [comment]
A question about possible implementation of`getAzimuth()`, `getPitch()`, `getRoll()` and `getRotationMatrix()` of `IOSInput`: is it possible to use CoreLocation instead of CoreMotion to implement those? In particular, is it possible to use [CLHeading](https://github.com/robovm/robovm/blob/master/cocoatouch/src/main/java/org/robovm/apple/corelocation/CLHeading.java)'s properties (except `trueHeading`, which requires to physically track user's location)? According to this [StackOverflow post](http://stackoverflow.com/a/15470571/369317), CLHeading seems to be more accurate than CMDeviceMotion in providing compass-related data.

**Comment by MrStahlfelge** [comment]
Closing this as for some there are already other issues open (Sound), outdated and PRs in progress (vibration) or there was apparently no need for it so far.
