### ISSUE TITLE
Detecting enter pressed on iOS software keyboard.

### ISSUE THREAD

**Issue by mkorman9** [libgdx/libgdx#1868]
Pressing "Done" button while RoboVM software keyboard is up should trigger keyDown() or keyTyped() event. Currently most of custom textfields (just like the one from flixel-gdx) don't work because "Done" button just closes virtual keyboard without triggering any event. Invoking keyTyped for '\n' keycode would be a nice idea.

**Comment by mcolombo** [comment]
Hi Everyone,

I have a regular text field in my code, and im trying to capture the "done" key in the listener of my textfield for the iOS keyboard but it doesn't work. For android i just compare it to '\n' and it does work.

Does anyone know if this has been implemented for iOS?

Thanks!!

```javascript
mTextField = new TextField("", styleTextField);
mTextField.setTextFieldListener(new TextFieldListener() {
			@Override
			public void keyTyped(TextField textField, char key) {
				 
				boolean enterKey = key == '\n';
				LogUtil.i("enterKey: " + enterKey);
			
			}
		});
```

**Comment by Tom-Ski** [comment]
The char 13 is fired as a keyTyped event, also a keyDown event is fired with the key: Keys.ENTER

**Comment by mcolombo** [comment]
Im sorry, i didn't get it quite well...

the keyDown event is not fired when clicking the 'done' button of the ios keyboard.
And how do i compare it to a 13 char? The keyTyped after hitting the done button is empty...

Thanks in advance Tom!

**Comment by Tom-Ski** [comment]
This is where these events are fired https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSInput.java#L415

You should be able to do `if (key == '13')` (done/enter has been pressed)

**Comment by mcolombo** [comment]
Oh perfect! It worked!

thank you very much!

**Comment by dhex-** [comment]
Thank you tom-sky for finally merging the thing, never got the chanse to thank you
