### ISSUE TITLE
Drawing stages in frame buffers results in improper rendering

### ISSUE THREAD

**Issue by erodozer** [libgdx/libgdx#1926]
In the process of creating my frame buffers, so I may use GLSL shaders to perform blur behind UI elements, I've encountered a problem where transparent actors in a stage(s) end up overlapping when rendering to a frame buffer.  

For some reason, the actors will completely crop away what's behind them instead of multiplying properly when they're rendered within a frame buffer, like in this image

![screenshot - 06022014 - 12 21 01 am](https://cloud.githubusercontent.com/assets/316728/3143886/7a015c72-ea0e-11e3-9132-bd31dc610bfc.png)

When rendering without being wrapped into a frame buffer, the ui renders as expected.

![screenshot - 06022014 - 12 20 22 am](https://cloud.githubusercontent.com/assets/316728/3143887/7b9c4466-ea0e-11e3-83a1-dd1a5c142c56.png)

From what I see here in my testing, it only appears to be happening with stacked Table elements with backgrounds set to a Drawable.

**Comment by JFixby** [comment]
Thanx @NathanSweet your code helped a lot!
