### ISSUE TITLE
Allow customizing view of elements in SelectBox/List

### ISSUE THREAD

**Issue by vlaaad** [libgdx/libgdx#1937]
Current implementation forces vizualization of elements to look like labels with `toString()`'s of that elements (for performance reasons, i believe). That's too restrictive, it would be better to provide ability to use custom views (like it is implemented in tree's node actors).
Something like `setElementVisualizer(IElementVisualizer<T> visualizer)` with api `Actor createActor(T element)` would do the trick. It can also default to LabelVisualizer, which just creates labels using `toString()`, so behaviour and existing api will survive.

**Comment by badlogic** [comment]
@NathanSweet close this or implement it :D

**Comment by NathanSweet** [comment]
Would be nice to do something better, but I won't be able to get to this any time soon.
