### ISSUE TITLE
Actor's clipBegin() clips the entire screen.

### ISSUE THREAD

**Issue by antoni-alvarez** [libgdx/libgdx#1947]
I'm trying to clip an Actor with clipBegin(x, y, width, height) method, but for some reason the entire screen is clipped, even the Sprites I draw directly on the screen without using Scene2D. This is my code:

```
public GameScreen(Game game) {
    this.game = game;

    myActor = new Group();
    myActor.setSize(128, 128);
    myActor.setPosition(150, screenHeight / 1.8f);

    stage = new Stage(new FitViewport(screenWidth, screenHeight, cam), batch);
    stage.addActor(target);

    myActor.clipBegin(0, myActor.getY(), screenWidth, 128);
}
```

Maybe this bug is related in some way to another bug I encountered a couple of days ago. For some reason if I change the color or the alpha of the last of the Actors added to the Scene, the entire screen is tinted to that color, even the sprites that are not handled by Scene2D. For example:

```
    tintedActor.setColor(Color.RED);
    stage.addActor(actor1);
    stage.addActor(actor2);
    stage.addActor(tintedActor);
```

But if I change the order in which I add the Actors to the Scene all is drawn correctly:

```
    tintedActor.setColor(Color.RED);
    stage.addActor(tintedActor);
    stage.addActor(actor1);
    stage.addActor(actor2);
```

**Comment by jodik** [comment]
Reset: when you call clipEnd() it is fine, however before clipBegin() you should call batch.flush(); so the clip will not affect any drawing saved in batch stack. Hope help.
