### ISSUE TITLE
Add setRotation and setScale to ParticleEffect

### ISSUE THREAD

**Issue by alexprey** [libgdx/libgdx#1974]
Hello,
Can you implement additional methods for ParticleEffect class - setRotation and setScale. This methods needs for attaching effects for Actor in Scene2D. At current time ParticleEffect class contain one method - setPosition, it is not enough for attaching particle effects for actors in scene2d.

**Comment by gereonf** [comment]
Hi,
I have the same problem, I just want to rotate the particle effect.
Tried to set the batch transformation matrix:
```
m.setToRotation(0f, 0f, 1f, angle);
batch.setTransformMatrix(m);
effect.draw(batch);
```
But the particles just disappeared. What's wrong?
By the way, wouldn't it be good to have a ParticleEmitter.setRotation() method (corresponding to setPosition())?
