### ISSUE TITLE
AssetManager does not dispose of unloaded sounds properly on iOS

### ISSUE THREAD

**Issue by dgmp88** [libgdx/libgdx#1986]
Calling AssetManager.unload() doesn't seem to remove Sounds from memory on iOS (iPad Air, iOS 7.1.1). As far as I can tell, this is working fine on both Desktop and Android. Calling Sound.dispose() on the sound directly seems to be fine. The leak is visible in Instruments, use a large file (e.g. "8.12.mp3" in gdx-tests) to make this as obvious as possible.

Apologies if I'm just misunderstanding the AssetManager.

Demo code: 
```java
package com.mygdx.game;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.assets.AssetManager;
import com.badlogic.gdx.audio.Sound;


public class MyGdxTests extends ApplicationAdapter {
	public AssetManager manager = new AssetManager();
	int counter = 1;
	
	@Override
	public void create () {
	}

	@Override
	public void render () {
		if (counter == 1) {
			// Load up the sound
			manager.load("8.12.mp3",Sound.class);
			manager.finishLoading();
			System.out.println("loaded");
		}
		
		if (counter == 100) {
			// Check it's there 
			for (String s : manager.getAssetNames()) {
				System.out.println("before: " + s);
			}
			// Unload the sound
			manager.unload("8.12.mp3");
			
			// Check it's gone 
			for (String s : manager.getAssetNames()) {
				System.out.println("after: " + s); // Should never be seen (and isn't)
			}
			counter = 0;
			System.out.println("unloaded");
		}
		counter ++;
	}
}
```

Instruments output: 
![screen shot 2014-06-17 at 14 33 52](https://cloud.githubusercontent.com/assets/6919834/3300926/f641d1fe-f625-11e3-9693-83c054a84ae9.png)

**Comment by cjuillard** [comment]
This looks related to [#2906](https://github.com/libgdx/libgdx/issues/2906) which was just fixed.

**Comment by Tom-Ski** [comment]
Yup this should be resolved. Please re-open if it is still happening with the latest.
