### ISSUE TITLE
Controller Vibration

### ISSUE THREAD

**Issue by ChetRippo** [libgdx/libgdx#2057]
I'd like to add gamepad vibration to my game. It appears to not currently exist in the controller extension. If OIS supports it, what are the chances of this being added sometime soon?

**Comment by JuKu** [comment]
@badlogic @ChetRippo LWJGL has already implemented rumble for that, or?
http://legacy.lwjgl.org/javadoc/org/lwjgl/input/Controller.html

So there are only a few things to add.

**Comment by JuKu** [comment]
On android we can solve this with simple vibration:
https://stackoverflow.com/questions/13950338/how-to-make-an-android-device-vibrate

**Comment by GrantOjanen** [comment]
It'd be nice to see this reopened.

The Android APIs has had this since 4.1, but I don't think you could control how strong the vibration is. On Android 8 they added the ability to change the amplitude of the vibration.

**Comment by MrStahlfelge** [comment]
Better make a new issue because this one is for controllers.

**Comment by GrantOjanen** [comment]
@MrStahlfelge I was referring to controllers. I've got this working and will try a pull request later, but someone else will need to do lwjgl.

**Comment by MrStahlfelge** [comment]
Interesting, last time when I checked there was no vibration support for controllers on Android. Can you link the documentation? Thanks!

**Comment by GrantOjanen** [comment]
InputDevice.getVibrator()
https://developer.android.com/reference/android/view/InputDevice.html#getVibrator()

I haven't tried it with all my controllers yet, but it does work with an Xbox 360 controller.

**Comment by MrStahlfelge** [comment]
Nice! libGDX' default controller interface doesn't support vibration, so I invite you to make a PR to my fork. [Its vibration methods](https://github.com/MrStahlfelge/gdx-controllerutils/wiki/Advanced-Controller-interface#vibration) are probably not fitting for this, but feel free to change them to vibrate(long duration) or something similar. Jamepad implementation has to be changed then.

**Comment by GrantOjanen** [comment]
I already wrote the code for it, so I did a pull request #5738 on libGDX. Is Jamepad lightweight? I read some where once that SDL2 takes up a lot of space when bundled.

**Comment by MrStahlfelge** [comment]
The jamepad jar file is 3 MB for me. Okay, I grabbed your code and added it to my lib. Thank you.
