### ISSUE TITLE
Lwjgl backend doesn't support OpenGL ES 3.2+

### ISSUE THREAD

**Issue by bradzeis** [libgdx/libgdx#2087]
Creating a LwjglApplication with useGL30 set to true still doesn't create an OpenGL ES 3 context. Additionally, Gdx.gl30 is null.

The issue seems to be [here](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGraphics.java#L166). context should be passed in to Display.create along with the PixelFormat.

[This line](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGraphics.java#L241) should also check whether the major version is 3 and set gl30 accordingly.

**Comment by dns2utf8** [comment]
It would be great if the pull request were integrated because on Linux it is currently (libgdx 1.5.2) not possible to see fonts when you switch the GL30 Flag to true.

**Comment by xoppa** [comment]
Guess we can close this now. Although we still need to think of a fix for the shaders (while maintaining backward compatibility), you can specify your own shader and it should work without problems.
