### ISSUE TITLE
iOS  real device fullscreen (hided status bar )returns  incorrect touch coordinates 

### ISSUE THREAD

**Issue by radekkierner** [libgdx/libgdx#2105]
On real iOS devices ex iPhone 5 with screen resolution 640x1136 in my app I got touch values returned from range 1-620 (app fullscreen) it happens also on iPads and touches range is alway smaller about 20-40 pixels. When statusbar is showed everything looks ok. I have checked on my project and also on demo-invaders and defalut gdx app on Libgdx 1.0 and 1.2 Robovm 0.11 and 0.14 . On simulator raported touch coordinates are OK.

Edit: the range of touches is 0 - 620  !!!

**Comment by badlogic** [comment]
This should be fixed via #3590
