### ISSUE TITLE
ResolutionFileResolver best match policy is incorrect

### ISSUE THREAD

**Issue by leonardo7** [libgdx/libgdx#2161]
[ResolutionFileResolver](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/assets/loaders/resolvers/ResolutionFileResolver.java#L71) chooses the largest descriptor that is smaller than the current screen size

```java
Resolution other = descriptors[i];
if (w >= other.portraitWidth && other.portraitWidth >= best.portraitWidth 
    && h >= other.portraitHeight && other.portraitHeight >= best.portraitHeight) 
        best = descriptors[i];
```
For example I'm providing 3 descriptors `480x800`, `800x1280`, and `1200x1920`. If the target device is Nexus 4 `768x1200` it's matched to `480x800`. I think it should be matched to `800x1280`. 

I think a good fix would be choosing the descriptor that have the smallest normalized difference form the target screen.

**Comment by badlogic** [comment]
Closing this out as there was no further activity and the PR was rejected.
