### ISSUE TITLE
Can't turn off Stage debug rendering

### ISSUE THREAD

**Issue by JesseTG** [libgdx/libgdx#2162]
I can turn it on just fine.  But when I try to turn it off (via `stage.setDebugAll(false)`), nothing happens.  It looks like the `stage.debug` field is never set to `false` anywhere.

**Comment by jiff88** [comment]
Hi!
Turning debug off is not working for me yet, i did some research and found out method in Actor:

```java
public void setDebug (boolean enabled) {
    debug = enabled;
    if (enabled) Stage.debug = true;
}
```

but what if enabled is false?
maybe this need to be updated?
anyway, even if i am wrong, after calling setDebugAll(false); on my stage, debug is still on for my actors..
thanks!

**Comment by NathanSweet** [comment]
Show code for the problem if there is a problem. `Stage.debug` is true if any actor has even had debug enabled.
https://github.com/libgdx/libgdx/wiki/Getting-help

**Comment by jiff88** [comment]
I am very sorry that i didn't do deeper research first.. it seems my problem is quite more specific.. when i override drawDebug() in my actor, turning off the debug is no working for it.. i understand i can override it freely to express my way of debugging presentation.. i hope i am not wrong..

My Test Screen:

```java
public class Test implements Screen {

	private Stage stage;
	private Skin skin;

	@Override
	public void show() {
		
		skin = new Skin(Gdx.files.internal("skin/uiskin.json"));
		
		stage = new Stage();
		stage.setDebugAll(true);
		
		stage.addActor(new MyLabel("someText", skin));
	}

	@Override
	public void render(float delta) {

		Gdx.gl.glClearColor(0, 0, 0, 0);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

		stage.setDebugAll(false);
		
		stage.act(delta);
		stage.draw();
	}
	// ...
}
```

And My Actor:

```java
public class MyLabel extends Label {

	public MyLabel(CharSequence text, Skin skin) {
		super(text, skin);
	}

	@Override
	public void drawDebug(ShapeRenderer sr) {
		super.drawDebug(sr);
		sr.setColor(Color.RED);
		sr.rect(getX(), getY(), getWidth(), getHeight());
	}
}
```

The RED rectangle around my actor won't disappear when debugging is turned off..
Hope i am doing it right!

Thanks for your time!
Josef

**Comment by NathanSweet** [comment]
Your code cannot be run. I added `stage.setDebugAll(...);` to UITest and it works fine.

**Comment by jiff88** [comment]
It seems it won't turn off only if that actor is providing it's own drawDebug() method, as in my example.. sorry it's not perfectly runnable, tried to do it simple..

**Comment by NathanSweet** [comment]
Ok, after I created a runnable example I see the issue. Someone had to create a runnable example which is why I asked for it, and if it were you then it would have [saved time](https://github.com/libgdx/libgdx/wiki/Getting-help#executable-example-code). At any rate, I've committed a fix, thanks.

**Comment by jiff88** [comment]
Oh i understand now.. ok man, thx for this, my first post, will improve next time..

**Comment by NathanSweet** [comment]
No worries, at least you had a real issue in the end. Imagine that almost no one creates executable example code and very often also don't actually have a real issue. :)

**Comment by jiff88** [comment]
I admire your work and efforts with us mortals :)) thanks for it, thanks to people like you i can realize my child dream and code a game :))
