### ISSUE TITLE
iOS hardware keyboard isn't working

### ISSUE THREAD

**Issue by mikemee** [libgdx/libgdx#2169]
I'm wondering if there is any special trick needed to enable an iOS bluetooth keyboard? My app works fine with a keyboard in the Android emulator, and fine on the Desktop.  

I have a customer reporting that their iPad plus bluetooth keyboard is not working. I don't have a keyboard for my iPad, but if if I:
1. start the iOS Simulator
2. choose Hardware -> Simulate Hardware Keyboard from the menu
3. type on the keyboard in my app

Nothing happens.   Doing the same thing on Android or the Desktop works as expected.

I'm using TouchUp/Down with GestureListener.

Let me know if I can provide more info. Thanks!

**Comment by MrStahlfelge** [comment]
It was caused by iOS not sending any keyevents. iOS 13.5 solved this and PR #6132 added the feature.
