### ISSUE TITLE
Window title bar doesn't scale to the height of the font

### ISSUE THREAD

**Issue by Robitx** [libgdx/libgdx#2232]
Dear Nathan,
would it be possible to make the height of title bar in window class automatically scalable according to the height of the titlefont? (One would expect such behavior).

**Comment by badlogic** [comment]
@NathanSweet please fix or close this :p

**Comment by NathanSweet** [comment]
Window is a pretty old class, one of the original widgets. It could use a rewrite, though this could impact existing code. It could be replaced by a new class, but I won't be able to get to this any time soon. For now people could set the title height as noted above, or copy/paste Window and make it use a label (it's just a table after all).
