### ISSUE TITLE
playbackDevice.writeSamples eating CPU

### ISSUE THREAD

**Issue by tnelsond** [libgdx/libgdx#2252]
On my system which is a 64-bit Linux box using Alsa for sound, the call to writeSamples on a AudioDevice maxes out a CPU core if the samplerate is 30khz (30000) or higher; however hardly any at all ( < 10% CPU) is used when the samplerate is 20khz (20000) or lower. 44.1khz and 48khz also maxes out a CPU.

Android seems to have no problem whatsoever.

**Comment by mgsx-dev** [comment]
Issue is not related to audio driver but to java code (see my PR that fix it)
