### ISSUE TITLE
"Tilde" or "Caret" key missing

### ISSUE THREAD

**Issue by BSVogler** [libgdx/libgdx#2263]
Hi devs!

In "com.badlogic.gdx.Input.Keys" I can not find the key which is located over the "Tab" key. On German keyboards it's the "Caret" and on English ones it's the "Tilde". Both are missing.

In the source I see that the line for Tilde is commented:
// public static final int TILDE = 0;

Is there a way to check if this key is pressed or how I can find out which int it needs so I can make a pull request after implementing it?

Cheers,
Benedikt

**Comment by badlogic** [comment]
Obsolete due to new LWJGL 3 backend. Comes with its own set of keycode issues, as GLFW reports scan codes. However, character events seem to work as intended on my german keyboard.
