### ISSUE TITLE
glTexImage2D and glTexSubImage2D in GwtGL20

### ISSUE THREAD

**Issue by Kjos** [libgdx/libgdx#2282]
At the moment glTexImage2D and glTexSubImage2D work by fetching a Pixmap by the id found in the given IntBuffer (by parameter). I was wondering if it is possible, and if so I'd like to propose it, to make it use the IntBuffer in a similar manner as with glReadPixels.

There could be a check that if the IntBuffer is bigger than one, the actual contents of the IntBuffer is read to WebGL, instead of fetching the Pixmap and using the backing Canvas.

This allows to upload larger quantities of pixel data much faster than with the backing Canvas, while still having the option to use the backing Canvas if needed (by using Pixmap).

If I'm not mistaken this should be possible, but I'm hoping I'm not off on this one, as it would be a huge benefit for me.

**Comment by MobiDevelop** [comment]
Going to close this. If it is still important to you and can be shown to improve performance, please submit a PR.
