### ISSUE TITLE
iOS occasionally resumes to no meshes, only clear color

### ISSUE THREAD

**Issue by cypherdare** [libgdx/libgdx#2396]
I encountered this in my game prototype, so I created a new LibGDX project to test it. It happens sporadically, but I couldn't reproduce it until adding a frame buffer to the game. That could be a coincidence though, because I cannot reliably reproduce the issue.

It's maddening that this happens sporadically, but the best way I've found to reproduce it is to open the game, turn off the phone, and reopen the game about three hours later. When I do this, the blank clear color screen shows up about 30% of the time. I have been doing this with my personal phone, so its possible that my occasional use of the Chrome browser is contributing to whatever RAM or GPU condition triggers it.

However, I once encountered the issue by opening the game, hitting the power button, hitting the power button again to turn on the screen, and unlocking the lock screen. The game returned to the clear color screen. However, since then I have tried turning the screen on and off many times and couldn't get this to happen again.

There are no black rectangles where the textures were, so I don't think the problem is them getting disposed. I am also setting the projection matrix to identity on each frame, so I don't think the resize method is confounding this.

I set it to show a different color for the clear color depending on phone orientation. Rotating the screen changes the clear color back and forth, but the textures do not reappear.

I realize you might not be able to make progress on this without being able to reproduce it. If so, I would appreciate some tips on how I might get started tracking it down. Maybe someone has some idea what could cause meshes not to draw at all, while the clear color still shows. Could some of the gl settings be getting changed somehow, like face culling turned on? I'm not familiar with the iOS backend.

Gradle version: 2.1
Robovm plugin version 0.0.10
Robovm version 0.0.14
Gdx version 1.3.1
Device: iPhone 5
iOS version: 7.1.2
Using Android Studio

I updated the above in the various Gradle files. You can copy and paste the bottom into the MyGdxGame in a new project:

~~~java
public class MyGdxGame extends ApplicationAdapter {
	SpriteBatch batch;
	Texture img;
    FrameBuffer frameBuffer;

    final Matrix4 matrix4 = new Matrix4();
    int screenWidth;
    int screenHeight;
    float doubleInitialWidth, doubleInitialHeight;
	
	@Override
	public void create () {
		batch = new SpriteBatch();
		img = new Texture("badlogic.jpg");
        doubleInitialWidth = Gdx.graphics.getWidth()*2;
        doubleInitialHeight = Gdx.graphics.getHeight()*2;
	}

    @Override
    public void resize (int width, int height){
        screenWidth = width;
        screenHeight = height;

        if (frameBuffer!=null)
            frameBuffer.dispose();
        frameBuffer = new FrameBuffer(Pixmap.Format.RGBA4444, width, height, false);
    }

	@Override
	public void render () {
		Gdx.gl.glClearColor(screenWidth/ doubleInitialWidth, screenHeight/ doubleInitialHeight, (screenWidth<=0 || screenHeight<=0)? 0.5f : 1, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

        frameBuffer.begin();
        Gdx.gl.glClearColor(0, 0, 1, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        matrix4.setToOrtho2D(0, 0, screenWidth, screenHeight);
        batch.setProjectionMatrix(matrix4);
        batch.begin();
        batch.draw(img, 0, 0);
        batch.end();
        frameBuffer.end();

        matrix4.idt();
        batch.setProjectionMatrix(matrix4);
		batch.begin();
		batch.draw(frameBuffer.getColorBufferTexture(), -.8f, .8f, 1.6f, -1.6f);

        matrix4.setToOrtho2D(0, 0, screenWidth, screenHeight);
        batch.setProjectionMatrix(matrix4);
        batch.draw(img, screenWidth-img.getWidth(), 0);
		batch.end();
	}

    @Override
    public void dispose(){
        batch.dispose();
        img.dispose();
    }

}
~~~

I might be encountering the issue mentioned here: https://github.com/libgdx/libgdx/issues/1794

However, I can confirm that if I change the clear color, the screen shows the clear color.

**Comment by btd-f-lago** [comment]
I don't know if I can be of any help, but I have had a similar problem.
I my application, just the following code inside resume() method of Screen implementation
caused the app to only show clear color after pause/resume (by pressing the home button).

```java
@Override
public void resume() {
      somefbo.begin();
      somefbo.end();
}
```


This happened 100% of the time.
I was re-drawing some pre-renderable static stuff onto a texture because somehow the framebuffer would not properly preserve its contents on some particular android devices...

Eventually I had to have the re-drawing being done only on android, since in ios the only-clear-color problem showed up.
Maybe this might help to reproduce the issue..

**Comment by xoppa** [comment]
Is this still an issue? If so, then please verify it while [GLProfiler](https://github.com/libgdx/libgdx/wiki/Profiling#opengl) is enabled.

**Comment by badlogic** [comment]
I can't reproduce this anymore. Please create a new issue if this is still a problem for you.
