### ISSUE TITLE
Android 4.4 SD changes

### ISSUE THREAD

**Issue by Unkn0wn0ne** [libgdx/libgdx#2426]
So starting in KitKat, https://developer.android.com/about/versions/android-4.4.html#UserContent, Google is restricting SD access more and more so that applications can only access Public Directories (i.e. Photos, Documents) and a special folder created for them on the file system. Currently the libGDX APIs have not adapted to this change, so I propose one of the 2 following things.

- Option #1 = Switch over to the new APIs completely for all versions of Android.
- Option #2 = Switch over to the new APIs on API Levels >= 19, so this will maintain backwards compatibility on < API Level 19, and introduce the new function to API Levels >= 19. 

I can send a PR, if you'd like.

**Comment by badlogic** [comment]
Let's keep this going in the PR.
