### ISSUE TITLE
Spritebatch and Shaders disordering.

### ISSUE THREAD

**Issue by Oyatsumi** [libgdx/libgdx#2432]
Hello, I've opened the following issue: https://github.com/libgdx/libgdx/issues/2367
It was then closed and I reposted and got no response from it.
I don't know exactly if I was supposed to create a new issue or not, sorry if wasn't. So, could someone clarify these points?
I would be very glad.
Thank you.

The actual comment I posted on the previous issue ->

I think there is something pretty strange with the behavior of the framebuffer. I tried to boil it down for testing and I apparently found a new issue.

The blending functions here are the same I used on my game (http://www.mediafire.com/download/x7qqa3z5h4ilbsu/jogo37_frameskip=10-shadow=true.jar), which is running fine on windows.

The code went like that:
	
	
	final static String VERT =  
			"attribute vec4 "+ShaderProgram.POSITION_ATTRIBUTE+";\n" +
			"attribute vec4 "+ShaderProgram.COLOR_ATTRIBUTE+";\n" +
			"attribute vec2 "+ShaderProgram.TEXCOORD_ATTRIBUTE+"0;\n" +
			
			"uniform mat4 u_projTrans;\n" + 
			" \n" + 
			"varying vec4 vColor;\n" +
			"varying vec2 vTexCoord;\n" +
			
			"void main() {\n" +  
			"	vColor = "+ShaderProgram.COLOR_ATTRIBUTE+";\n" +
			"	vTexCoord = "+ShaderProgram.TEXCOORD_ATTRIBUTE+"0;\n" +
			"	gl_Position =  u_projTrans * " + ShaderProgram.POSITION_ATTRIBUTE + ";\n" +
			"}";
	
	final static String FRAG = 
			//GL ES specific stuff
			  "#ifdef GL_ES\n" //
			+ "#define LOWP lowp\n" //
			+ "precision mediump float;\n" //
			+ "#else\n" //
			+ "#define LOWP \n" //
			+ "#endif\n" + //
			"//texture 0\n" + 
			"uniform sampler2D u_texture;\n" + 
			"\n" + 
			"//our screen resolution, set from Java whenever the display is resized\n" + 
			"uniform vec2 resolution;\n" + 
			"\n" + 
			"//screen color RGB(Intensity)\n" + 
			"uniform LOWP vec4 ambient; \n" + 
			"\n" + 
			"//\"in\" attributes from our vertex shader\n" + 
			"varying LOWP vec4 vColor;\n" +
			"varying vec2 vTexCoord;\n" + 
			"\n" + 
			"//RADIUS of our vignette, where 0.5 results in a circle fitting the screen\n" + 
			"const float RADIUS = 0.75;\n" + 
			"\n" + 
			"//softness of our vignette, between 0.0 and 1.0\n" + 
			"const float SOFTNESS = 0.75;\n" + 
			"\n" + 
			"void main() {\n" + 
			"	//sample our texture\n" + 
			"	vec4 texColor = texture2D(u_texture, vTexCoord);\n" + 
			"		\n" + 
			"	//1. VIGNETTE\n" + 
			"	\n" + 
			"	//determine center position\n" + 
			"	vec2 position = (gl_FragCoord.xy / resolution.xy) - vec2(0.5);\n" + 
			"	\n" + 
			"	//determine the vector length of the center position\n" + 
			"	float len = length(position);\n" + 
			"	\n" + 
			"	//use smoothstep to create a smooth vignette\n" + 
			"	float vignette = smoothstep(RADIUS, RADIUS-SOFTNESS, len);\n" + 
			"	\n" + 
			"	//apply the vignette with 60% opacity\n" + 
			"	texColor.rgb = mix(texColor.rgb, texColor.rgb * vignette, 0.6);\n" + 
			"		\n" + 
			"	//2. GRAYSCALE\n" + 
			"	\n" +
			"	//convert to grayscale using NTSC conversion weights\n" + 
			"	float gray = dot(texColor.rgb, vec3(0.299, 0.587, 0.114));\n" + 
			"	\n" + 
			"	//create our sepia tone from some constant value\n" + 
			"	vec3 sepiaColor = vec3(gray) * ambient.rgb;\n" + 
			"		\n" + 
			"	//again we'll use mix so that the sepia effect is at somewhere\n" + 
			"	texColor.rgb = mix(texColor.rgb, sepiaColor, ambient.a);\n" + 
			"		\n" + 
			"	//final colour, multiplied by vertex colour\n" + 
			"	gl_FragColor = texColor * vColor;\n" + 
			"}";
	
	@Override
	public void resize(int width, int height) {
		oc.setToOrtho(false, width, height);
		batch.setProjectionMatrix(oc.combined);
	}
	@Override
	public void create(){
		shader = new ShaderProgram(VERT, FRAG);
		batch = new SpriteBatch();
		frameBuffer = new FrameBuffer(Format.RGBA8888, Gdx.graphics.getWidth(), Gdx.graphics.getHeight(), false);
		oc = new OrthographicCamera();  
		oc.setToOrtho(false, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
	}
	public ShaderProgram shader = null;
	public SpriteBatch batch = null;
	public FrameBuffer frameBuffer = null;
	OrthographicCamera oc = null;
	@Override
	public void render() {
		Gdx.gl.glClearColor(0f, 0f, 0f, 0f);
	    Gdx.gl.glClear(Gdx.gl.GL_COLOR_BUFFER_BIT);
	    
	    Texture mario1 = new Texture(Gdx.files.internal("data/mario.png")),
	    		mario2 = new Texture(Gdx.files.internal("data/mario.png")),
	    		mario3 = new Texture(Gdx.files.internal("data/mario.png")),
	    		mario4 = new Texture(Gdx.files.internal("data/mario.png")),
	    		mario5 = new Texture(Gdx.files.internal("data/mario.png")),
	    		mario6 = new Texture(Gdx.files.internal("data/mario.png"));
	    
	    shader.begin();
		shader.setUniformf("ambient", 1.2f, 1.0f, 0.8f, 1.0f);
		
	
		
		batch.setBlendFunction(GL20.GL_SRC_ALPHA,
                GL20.GL_ONE_MINUS_SRC_ALPHA);
		Gdx.gl20.glBlendFuncSeparate(GL20.GL_SRC_ALPHA,
                GL20.GL_ONE_MINUS_SRC_ALPHA, GL20.GL_SRC_ALPHA, GL20.GL_ONE_MINUS_SRC_ALPHA);
		
		
		batch.setProjectionMatrix(oc.combined);
		
		
		batch.begin();

		//1
	    batch.draw(mario1, 0, 0);
	    
	    frameBuffer.begin();
	    
	    
	    //2
	    batch.draw(mario2, mario1.getWidth(), 0);
	    
	    batch.setShader(shader);
	    
	    //3
	    batch.draw(mario3, mario1.getWidth()*2, 0);
	    
        batch.setBlendFunction(GL20.GL_SRC_ALPHA,
                GL20.GL_ONE); //ignore the batch blend function
        Gdx.gl20.glBlendFuncSeparate(GL20.GL_SRC_ALPHA,
                GL20.GL_ONE, GL20.GL_SRC_ALPHA, GL20.GL_ONE_MINUS_SRC_ALPHA);
        
        //4
        batch.draw(mario4, 0, mario1.getHeight());
        
        batch.setBlendFunction(GL20.GL_SRC_ALPHA,
                GL20.GL_ONE_MINUS_SRC_ALPHA); //ignore the batch blend function
        Gdx.gl20.glBlendFuncSeparate(GL20.GL_SRC_ALPHA,
                GL20.GL_ONE_MINUS_SRC_ALPHA, GL20.GL_SRC_ALPHA, GL20.GL_ONE_MINUS_SRC_ALPHA);

        Sprite fB = new Sprite(frameBuffer.getColorBufferTexture());
        fB.flip(false, true);
        batch.draw(fB, 0, 0, frameBuffer.getColorBufferTexture().getWidth(), frameBuffer.getColorBufferTexture().getHeight());
        frameBuffer.end();
       
        
        //5
        batch.draw(mario5, mario3.getWidth(), mario1.getHeight());
        
        batch.setShader(null);
        
        //6
        batch.draw(mario5, mario3.getWidth()*2, mario1.getHeight());

        batch.end();
		
		mario1.dispose(); mario2.dispose(); mario3.dispose(); mario4.dispose(); mario5.dispose(); mario6.dispose();
	}

	@Override
	public void pause() {
		
	}

	@Override
	public void resume() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void dispose() {
		// TODO Auto-generated method stub
		
	}

And I get this (look, only the mario 5 and 6 are being "rendered").
http://s15.postimg.org/qifzzor23/mario1.png

when I take the frameBuffer.begin() and frameBuffer.end() lines and remove them, I get this:
http://s28.postimg.org/6dtbws1yl/mario1.png
Where all marios appear on the screen.

By removing the blendfunctions, all of them, and also keeping the frameBuffer.begin() and frameBuffer.end(). I get this:
http://s21.postimg.org/q71ziamsn/mario1.png
Mario 1, 2 and 3 do not appear.
Is this supposed to happen?

If I shift the frameBuffer.being() priorly to the batch.being(), I also get the same previous screen.

If I keep the blendfunctions deleted and the lines frameBuffer.begin() and frameBuffer.end() intact and I dont use the shader, then I get the following result:
http://s29.postimg.org/nb5aaub5z/mario1.png

My question is: Is that supposed to happen? Mario 1, 2, 3 and also 4 not being rendered? If so, why that?

Thank you in advance.
PS.: I was running on a windows 8 for now.
Heres the mario png if necessary: http://s30.postimg.org/qvhwvvt35/novo.png
PS2.: Libgdx 1.3.1

**Comment by badlogic** [comment]
Closing this out as there's no further activity.
