### ISSUE TITLE
PropertyChangeSupport for Scene2D

### ISSUE THREAD

**Issue by levelcrossing** [libgdx/libgdx#2440]
The Scene2D package is great, it is easy to use and easy to extend. However, what is holding it back from being used for more complex UI applications is the fact that there currently is no way to easily bind the existing components to a controller or model (if you are following the MVC pattern, but it is the same for other patterns like MVVM or MVP) using an existing binding library. Almost all of them rely on the use of the PropertyChangeSupport class in the java.beans package, which is available on Android too (sadly GWT doesnt support it out of the box, but it is emulated using the gwtx library). 
The only requirement for implementing it is adding a few methods (register and remove PropertyChangeListeners, firing PropertyChangeEvents) to a base class (preferably Actor, or Widget and WidgetGroup). Then the Widgets like a TextField only have to fire an Event when their fields change. The widgets' functionality would be left untouched and should not cause breaking changes.
I am currently working on it myself, but I want to know if anyone else is interested in including it into libgdx. The addition would make libgdx much more attractive for cross-platform app development.

**Comment by badlogic** [comment]
Closing this as there was no follow up.
