### ISSUE TITLE
Add 64-bit support for Android x86 and arm targets

### ISSUE THREAD

**Issue by badlogic** [libgdx/libgdx#2445]
Requires update of SDK/NDK on build server.

**Comment by intrigus** [comment]
Is this already done?

**Comment by badlogic** [comment]
Nope, this hasn't been done it. It's rather simple to add.

1. Modify Application.mk.template in jnigen
2. Modify the pom's of all sub projects that package Android native code (gdx/, gdx-box2d/, gdx-bullet/, gdx-freetype/) to include the new native libs 
3. Modify the build.gradle template file for the Android project and copy the new binaries as well.

All that being said, there are simply not enough 64-bit phones out yet, neither ARM not X86. All we'd do is bloat the APK for 90% of players.

**Comment by mars3142** [comment]
"All that being said, there are simply not enough 64-bit phones out yet, neither ARM not X86. All we'd do is bloat the APK for 90% of players." - This is only partial true, because you can split your APK into ARM, x86 and 64-bit.

**Comment by badlogic** [comment]
Read the 1.9.0 change log.

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://demo5.pofitechnologies.com/edit.php?i>

 

loogie@basicelementdesign.com

**Comment by mridhroid** [comment]
When liggdx will add the support for 64-bit ? Google play has released the note that they will not accept the 34-bit in future and the apps will be removed. Any temporary workaround to be  complaint with google 64-bit requirement ?
https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html

**Comment by DavidPDev** [comment]
I think that since version 1.9.0 libgdx already supports 64 bits in Android. Al least inside the .apk file you can find in the \libs folder the arm64-v8a and x86_64 versions of the libraries.

**Comment by mridhroid** [comment]
Thanks for the clarity.

When this version came ?

**Comment by MobiDevelop** [comment]
Approximately three years ago - https://www.badlogicgames.com/wordpress/?p=3892

**Comment by mridhroid** [comment]
Thanks Agian !
