### ISSUE TITLE
PopBackStack impossible with AndroidFragmentApplication

### ISSUE THREAD

**Issue by avianey** [libgdx/libgdx#2461]
I can't figure out how I can pop the FragmentManager back stack using AndroidFragmentApplication backend... the defaut behaviour of the back key using this backend is to kill the Android app. So previous fragments added to the back stack are not pushed back. 

If I use :

``` java
initializeForView(new ApplicationListenerImpl() {
            @Override
            public void create() {
                Gdx.input.setCatchBackKey(true);
                super.create();
            }
        }, config);
```

Then the app is not killed but the default back button behaviour for fragment stack is not applied... the back button input is simply ignored...

**Comment by tpnet** [comment]
@avianey    If I lock the screen on Android8.1 and unlock it, I will have this problem.  version  1.9.8

**Comment by chongbo2013** [comment]
@tpnet Especially when multiple libgdx SurfaceViews are easy to appear, fast onPause/onResume
