### ISSUE TITLE
GDX Setup Is Blank

### ISSUE THREAD

**Issue by naortega** [libgdx/libgdx#2475]
I used libGDX 1.3.1 in previous projects of mine, and it did not have the problem that follows. When I open the gdx-setup.jar file for the newer version of libGDX (v1.4.1) I get this: [[YouTube link](http://youtu.be/pfxU73QhMuo)]. Could this have anything to do with my using openjdk instead of Oracle? I tested this on openjdk 6 and 7, and it had the same results on both. I also tried compiling myself from the source-code but I got the same thing (which makes me doubt that it's openjdk if I compiled it with openjdk).

I'm currently running Debian 8 (Jessie).

Thanks a ton!

**Comment by Ben1980** [comment]
I experience the same problem after upgrading to Fedora 21. Neither JDK8 nor JDK7 nor openJDK does solve the problem. I guess it could be some sort of dependencie problem.  On Fedora 20 everything was fine.

**Comment by Deathsbreed** [comment]
Well, at least there's a commandline version.

**Comment by Sindisil** [comment]
Please  reopen this PR.

I'm seeing this on Fedora 21, as well. Brand new install, running NVIDIA driver version 343.36 on an x86_64 system. Oracle Java 8u25. 

I find that I can "paint" some of the controls by slowly hovering my pointer over the dialog. I assume because the buttons get repainted on mouse enter. This is further supported by the fact that, if browse and select a destination, the destination text box is then painted. Likewise, if I click where any text box is located, I can "paint" it by selecting the characters.

I'll try it tonight on my laptop, which is also x86_64 Fedora 21, but with the Intel integrated GPU.

**Comment by Deathsbreed** [comment]
For those of us having these issues, what Java are we running (Oracle, OpenJDK)? Then, what version are we running?

In my case I'm running OpenJDK 1.6.0_32
```
$ java -version
java version "1.6.0_32"
OpenJDK Runtime Environment (IcedTea6 1.13.4) (6b32-1.13.4-1~deb7u1)
OpenJDK Server VM (build 23.25-b01, mixed mode)
```

**Comment by badlogic** [comment]
I'm not quite sure what we can do about this. The setup app is just a Swing
app. Do other Swing apps work as expected?

**Comment by Ben1980** [comment]
I have the issue with openjdk, Oracle JFK 7 and 8.
Seems jdk independe

Am Freitag, 16. Januar 2015 schrieb Mario Zechner :

**Comment by Sindisil** [comment]
OK, now I've reproduced the issue on my laptop, so it's not GPU driver specific.

Fedora 21 again, Intel integrated GPU, Oracle Java 8u25.

Other Swing apps run fine -- I tried IDEA 14.1, NetBeans 8, the GUI I develop for my day job, and Vuze. All are Swing apps, all display correctly. I run all with light themes normally, but I also tried IDEA with Darcula, and that still displays fine. 

So far, it's just gdxsetup.jar that's busted.

**Comment by Sindisil** [comment]
It's something to do with the displaying an undecorated dialog.

If I change the code in GdxSetupUI to not setUndecorated(true), then everything displays clearly. One alternative would be to remove the fancy schmancy self drawn "title bar" and use the OS title bar. If I can't figure out why the heck the dialog isn't painting properly when undecorated (or if no one else does) soon, I'm going to put that patch together in my fork, so I can at least use the setup tool for now.

Right now, though, I need to go AFK to take my wife out to dinner for her birthday. Priorities, you know! ;P

**Comment by Tom-Ski** [comment]
If you could give forcing a repaint after the JFrame has been set to visible, maybe revalidate also.

**Comment by Sindisil** [comment]
I've submitted a pull request for a simple fix to this issue: if the JFrame is pack()ed before setting visible, it is no longer blank. I notice a few other paint issues (e.g., some labels and controls paint the wrong color until moused over), but those are likely separate issues, and they don't affect functionality. I'll try to look into those issues in the next couple days, time permitting.

**Comment by Tom-Ski** [comment]
@Sindisil Thanks for the PR, fixed it up so the log displayed correctly.  If you could give the other changes a test too that would be great.

**Comment by Deathsbreed** [comment]
I've just pulled and compiled the libgdx source code and it seems to be working.

**Comment by Sindisil** [comment]
I concur with Deathsbreed - looks good to me now. Sorry for the half baked PR last night - I should have waited until I had time to test more fully. Thanks for completing the fix, Tom-Ski!

**Comment by SoniEx2** [comment]
Relevant? https://bugzilla.gnome.org/show_bug.cgi?id=741133
