### ISSUE TITLE
HTML games' keyboard input problem in iframe.

### ISSUE THREAD

**Issue by RaviCake** [libgdx/libgdx#2479]
HTML games' keyboard input isn't working (but mouse input is working.) in iframe and when I play the game without iframe then keyboard input working.

here is my game in which I have tested ( many others games tested too ) : http://ravicake.itch.io/pong-simple

**Comment by ajayyy** [comment]
For me it worked better when just putting it outside of the function, so it runs right at the beginning.

**Comment by BartolomeoItaliano** [comment]
@RaviCake instead of making iframe a little bigger you can check if there are some default styles on html or body element of inner page.
