### ISSUE TITLE
[Android] TextField and OnScreenKeyBoard error ! 

### ISSUE THREAD

**Issue by saruno** [libgdx/libgdx#2491]
Hi,
I using TextField to input string. When i use SamSung (Samsung Galaxy S3) keyboard, the keyboard always pop. But when I type anything, it don't display any letters. The problems seems to appear only when "predictive text" is enabled. Please, fix it. It is really uncomfortable :(

**Comment by bachtrong43** [comment]
I guess it's the same issue as https://github.com/libgdx/libgdx/issues/2604
That is really uncomfortable

**Comment by badlogic** [comment]
Duplicate of #2604, closing this out.
