### ISSUE TITLE
Building a version besides the very top of tree fails because of RoboVM

### ISSUE THREAD

**Issue by PaulMaxime** [libgdx/libgdx#2493]
Hi-

I was trying to build version 1.4.1 today, but it fetches the top of RoboVM tree which has an incompatible change with release 1.4.1.

LibGDX should either include the correct version of robovm in its releases, or fetch a specific SHA1 which is known to be compatible.

The error in this case was UITouch.getLocation being changed to UITouch.getLocationInView in RoboVM.

**Comment by badlogic** [comment]
Closing this out. The Ant build using the latest from master is a way for us to catch API changes in the RoboVM bindings.

**Comment by PaulMaxime** [comment]
That's great, but older versions should have the correct version of RoboVM
baked in. Not everyone can work from top of tree all the time, and some of
us have private patches to LibGDX.

**Comment by PaulMaxime** [comment]
Correct. But we need to check out an older version as source, apply some
patches to it, and then build. This involves commenting out the part of the
build that fetches the latest RoboVM so we can put the right version in
place. It would be nice if we could rely on version 1.0 (or whatever) being
self-contained.

**Comment by badlogic** [comment]
I'm not sure i follow. Say you check out libGDX 1.4.1 sources. Next you apply your patches. Finally you build your patched versiom via Maven. That should work without any problems as the Maven dependencies are hardwired to a compatible RoboVM version.

Or do you invoke the Ant build?

**Comment by PaulMaxime** [comment]
Yeah. we are using Ant at the moment.

**Comment by Tom-Ski** [comment]
Perhaps the best solution would be for you to adapt your Ant script to pull in a certain version.  There is no real need for us to have this in our script as we only use the ant build to build bleeding.  Although I guess a PR that would include such a feature might be accepted if it wasn't intrusive. 

As this compatible Robovm version deceleration only exists in the maven scripts, you'd have to parse those, but it should help you build all previous versions of LibGDX via Ant.
