### ISSUE TITLE
LwjglInput numeric keyboard keycode mismatches

### ISSUE THREAD

**Issue by ghost** [libgdx/libgdx#2524]
Current implementation has one serious flaw: while it allows to easily recognize numpad 0-9, and + \* keys, as well as NumLock (named Num in Keys class for some reason), it makes it completely impossible to distinguish numpad Enter, slash, minus and period from regular one - and this distinction is quite important in many games. It wouldn't be a problem for KeyTyped, but it certainly is bad for KeyDown, as it breaks the "one key, one keycode" principle - I know it's not the case in 100%, but at least POLA requires to try to stick to it, and it _does_ work for every other key on my keyboard, with exception of those unlucky two.

LWJGL offers this possibility natively, and since desktop is IMO actually the only platform that should get this correction, I reckon it shouldn't break any compatibility whatsoever. The outline of my proposal is as follows:

_com.badlogic.gdx.Input.java_, _Keys_ class

``` java
        public static final int NUMPAD_9 = 153;
```

changed to 

``` java
        public static final int NUMPAD_9 = 153;

        public static final int NUMPAD_DIVIDE = 154;
        public static final int NUMPAD_MULTIPLY = 155;
        public static final int NUMPAD_SUBTRACT= 156;
        public static final int NUMPAD_ADD = 157;
        public static final int NUMPAD_DOT = 158;
        public static final int NUMPAD_COMMA= 159;
        public static final int NUMPAD_ENTER = 160;

        public static final int NUMLOCK = NUM; // to keep the backward compatibility but offer a more "regular" name, as per http://en.wikipedia.org/wiki/Num_lock
```

and to _com.badlogic.gdx.backends.lwjgl.LwjglInput.java_
in _getGdxKeyCode()_

``` java
case Keyboard.KEY_NUMLOCK:
return Input.Keys.NUMLOCK;
case Keyboard.KEY_DECIMAL:
return Input.Keys.NUMPAD_DOT;
case Keyboard.KEY_DIVIDE:
return Input.Keys.SLASH;
case Keyboard.KEY_LMETA:
return Input.Keys.SYM;
case Keyboard.KEY_RMETA:
return Input.Keys.SYM;
case Keyboard.KEY_NUMPADEQUALS:
return Input.Keys.EQUALS;
case Keyboard.KEY_AT:
return Input.Keys.AT;
case Keyboard.KEY_EQUALS:
return Input.Keys.EQUALS;
case Keyboard.KEY_NUMPADCOMMA:
return Input.Keys.COMMA;
case Keyboard.KEY_NUMPADENTER:
return Input.Keys.ENTER;
```

to

``` java
case Keyboard.KEY_NUMLOCK:
return Input.Keys.NUMLOCK;
case Keyboard.KEY_DECIMAL:
return Input.Keys.NUMPAD_DOT;
case Keyboard.KEY_DIVIDE:
return Input.Keys.SLASH;
case Keyboard.KEY_LMETA:
return Input.Keys.SYM;
case Keyboard.KEY_RMETA:
return Input.Keys.SYM;
case Keyboard.KEY_NUMPADEQUALS:
return Input.Keys.EQUALS;
case Keyboard.KEY_AT:
return Input.Keys.AT;
case Keyboard.KEY_EQUALS:
return Input.Keys.EQUALS;
case Keyboard.KEY_NUMPADCOMMA:
return Input.Keys.NUMPAD_COMMA;
case Keyboard.KEY_NUMPADENTER:
return Input.Keys.NUMPAD_ENTER;
```

and (in _getLwjglKeyCode()_)

``` java
case Input.Keys.NUMPAD_9:
return Keyboard.KEY_NUMPAD9;
```

to

``` java
case Input.Keys.NUMPAD_9:
return Keyboard.KEY_NUMPAD9;
case Input.Keys.NUMPAD_ENTER:
return Keyboard.KEY_NUMPADENTER;
case Input.Keys.NUMPAD_DOT:
return Keyboard.KEY_DECIMAL;
case Input.Keys.NUMPAD_COMMA:
return Keyboard.KEY_NUMPADCOMMA;
```

and so on for other numpad keys (/ and, possibly, + - *)

PS. Is changing current case-based key matching to map-based one sensible? AFAIK Java does that internally for big switch/case blocks in newest versions, but counting on that for Java 6 is a bit far-fetched IMO (and I don't know if Delvik is doing that at all); I use LwjglInput changed to map-based keycode translation myself, so if you consider this change sensible I'll gladly contribute the code. It shortens the keycode translation code in half, BTW.

**Comment by CreamyCookie** [comment]
Isn't this fixed?

**Comment by NathanSweet** [comment]
@CreamyCookie did you test if it was fixed? I'll assume so, also since no one else has complained and it's been years.

**Comment by FyiurAmron** [comment]
@NathanSweet actually: no, it wasn't. See https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/Input.java for yourself. The relevant PR is https://github.com/libgdx/libgdx/pull/2592 ; 4 years later, nothing changed in libGDX.

**Comment by CreamyCookie** [comment]
@NathanSweet Sorry, I thought this was fixed because the pull request #2592 was closed, but looking at it now, it apparently wasn't merged for reason, only closed. Again, I want to apologize for any inconvenience I may have caused. Please re-open this issue.

@Tom-Ski Do you know why #2592 was closed at the time? There was no explanation given on that pull request.

**Comment by Tom-Ski** [comment]
It was closed because the user that submitted the PR deleted their account before it was reviewed.

**Comment by CreamyCookie** [comment]
Ah.. that means the patch can't be used because of legal reasons ¹, right?

¹ [Contributor License Agreement](https://github.com/libgdx/libgdx/wiki/Contributing) needs to be signed

**Comment by FyiurAmron** [comment]
@CreamyCookie no. The CLA has been signed and submitted. It wasn't revoked. It just means that there were not a single person interested in this patch enough to continue its development.

**Comment by NathanSweet** [comment]
If this isn't fixed we can reopen. I don't trust PR #2592. Someone else who wants this fixed is welcome to submit a new PR.

**Comment by yousiftouma** [comment]
@NathanSweet I wouldn't mind fixing this, can you help me understand what needs to be done? 
Is it only https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/Input.java that needs the missing numpad keys added or does https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglInput.java also need updating? Any other files?

**Comment by NathanSweet** [comment]
@yousiftouma It looks like new constants need to be added, following what Android does:
https://github.com/libgdx/libgdx/issues/2524#issuecomment-61111493

After that, *every* backend needs to be updated to translate from the backend constant to the libgdx constant, and from the libgdx constant to the backend constant.

**Comment by FyiurAmron** [comment]
@yousiftouma exactly as Nathan said (see https://github.com/libgdx/libgdx/issues/2524#issuecomment-63221000); although, in all honesty and IMVHO, the problem with #2592 is not "trust"; the problem with it is that the files in question changed a bit since when the PR was done and that without a review by someone up-to-date on libgdx it could probably break badly.

I'd suggest you to:

1. update Input.java to include all the keycodes from #2592 and possibly other missing ones you may find (maybe cleaning up the const section a bit, like I've done by then),
2. (maybe) write a proper test to make sure that BC is not broken by accident,
3. update the backend you personally know best (e.g. LWJGL) to handle those new keycodes properly,
4. again, test if the BC is not broken,
5. goto 3, for any other backend out there (LWJGL3/GWT/whatever else is there)
