### ISSUE TITLE
Music getPosition() on Desktop doesn't give accurate position.

### ISSUE THREAD

**Issue by haikami** [libgdx/libgdx#2545]
Using gdx version 1.4.2-SNAPSHOT

Loaded a Music instance and played it. On each frame, I added the delta value to a variable in order to get the real position. Some of the values obtained along the music being played, where pos :

``` java
getPosition(): 0.04063492 deltaPos: 0.03333036
getPosition(): 0.06095238 deltaPos: 0.05006868
getPosition(): 0.08126984 deltaPos: 0.06693603
getPosition(): 0.1015873 deltaPos: 0.083865695
getPosition(): 0.12190476 deltaPos: 0.10047909
.....
getPosition(): 10.019415 deltaPos: 8.997233
getPosition(): 10.019415 deltaPos: 9.0081835
getPosition(): 10.039732 deltaPos: 9.024423
......
getPosition(): 15.923091 deltaPos: 14.329101
getPosition(): 15.943409 deltaPos: 14.346734
getPosition(): 15.963726 deltaPos: 14.363102
....
getPosition(): 24.769863 deltaPos: 22.286882
getPosition(): 24.79018 deltaPos: 22.307085
getPosition(): 24.79018 deltaPos: 22.320536
getPosition(): 24.8105 deltaPos: 22.336187

```

The song had a duration of 22.622seg, so it was actually impossible to get a 24.8105 seg position

**Comment by bloodsign** [comment]
Hmm.. I seem to be having this same problem. 
Printing the music.getPosition() gives me a different duration than the actual duration of the music file. (Even though they actually played at the same time when played side by side)

(Actual Playtime: 68 secs)
(What I'm getting: 61 secs)

![SS](https://user-images.githubusercontent.com/12083007/59979720-ced82300-961d-11e9-8d43-327a6cb377d1.png)
