### ISSUE TITLE
Quaterion.getAngleAround returns wrong angle in range 240°-360° for y-Axis

### ISSUE THREAD

**Issue by Doev** [libgdx/libgdx#2547]
Maybe there are problems with other Axises too.

Example:

Matrix4 m4 = new Matrix4();
        Quaternion q = new Quaternion();

```
    for (int degrees = 0; degrees < 360; degrees += 40) {
        System.out.println("degrees: " + degrees + " - getAngleAround: " + m4.idt().rotate(0, 1, 0, degrees).getRotation(q).getAngleAround(0, 1, 0));
    }
```

Output:

degrees: 0 - getAngleAround: 0.0
degrees: 40 - getAngleAround: 40.0
degrees: 80 - getAngleAround: 79.99999
degrees: 120 - getAngleAround: 120.0
degrees: 160 - getAngleAround: 159.99998
degrees: 200 - getAngleAround: 199.99998
degrees: 240 - getAngleAround: 120.0                           (_wrong)
degrees: 280 - getAngleAround: 79.99999                     (_wrong)
degrees: 320 - getAngleAround: 40.0                             (*wrong)

**Comment by ssebastian** [comment]
It does not seem to be fixed for me.

The following line still returns 89.999 instead of -90 resp. 270 degrees.

```java
new Matrix4().idt().rotate(0, 1, 0, -90).getRotation(new Quaternion()).getAngleAround(0, 1, 0);
```

Even more interesting is that:

```java
new Matrix4().idt().rotate(0, 1, 0, -120).getRotation(new Quaternion()).getAngleAroundRad(0, 1, 0)
== new Matrix4().idt().rotate(0, 1, 0, 120).getRotation(new Quaternion()).getAngleAroundRad(0, 1, 0);
```

returns true

I am using gdxVersion 1.5.5. According to the source code the patch from commit 240aa45 seems to be already applied since the setFromAxisRad method looks like this:

```java
	public Quaternion setFromAxisRad (final float x, final float y, final float z, final float radians) {
		float d = Vector3.len(x, y, z);
		if (d == 0f) return idt();
		d = 1f / d;
		float l_ang = radians < 0 ? MathUtils.PI2 - (-radians % MathUtils.PI2) : radians % MathUtils.PI2;
		float l_sin = (float)Math.sin(l_ang / 2);
		float l_cos = (float)Math.cos(l_ang / 2);
		return this.set(d * x * l_sin, d * y * l_sin, d * z * l_sin, l_cos).nor();
	}
```
