### ISSUE TITLE
'HttpResponseListener.failed' triggered from 'handleHttpResponse'

### ISSUE THREAD

**Issue by yanixon** [libgdx/libgdx#2548]
Versions: 1.3.2, 1.4.2
In the desktop app, any exceptions thrown inside 'handleHttpResponse' get caught and passed to 'failed'. Not sure if this is the intended behavior or not, but it is arguably very unintuitive (one would expect 'failed' to be called only when the request itself fails, not when it succeeds but the response is mishandled). It also hinders debugging, as exceptions thrown by the response handling code remain silent and without a stack trace.

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://catfishrods.com/debate.php?2h>

 

loogie@basicelementdesign.com

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://abcorpackaging.com/script.php?hcg>

 

loogie@basicelementdesign.com
