### ISSUE TITLE
proposed math util API enhancement

### ISSUE THREAD

**Issue by vaxquis** [libgdx/libgdx#2562]
Currently we have a quite inconsistent naming in math API, making deciphering some operations quite tedious. Take, for example, `Matrix4` `.tra()` & `.trn()` (I never know which one to use without checking the param signatures in the docs) - and it's not an isolated case. While I'm in favor of short, 3-4 letter names of operations and the chaining rule here, providing a more descriptive (or even JLS-compliant) naming variant would be helpful here IMO. I'm not saying "change the names", because current names are OK in many cases and changing them would obviously break current implementations - I'm rather in favour of, for example
```java
/** @see #trn() */
Matrix4 transpose() {
    return trn();
}
```
-ish set of methods, complementing what's already there. Also, providing JLS-standard naming of getXXX/setXXX would also reduce the brain overhead for programmers with Java background.

Note we already have many methods named that way, `setToXXX`, `setAsXXX``` etc - making the naming more consistent with standard one would be a great improvement and would reduce learning curve for libGDX a lot IMO. It would also make possible for a user (or even libGDX team) to create immutable (or other) variants of those classes for further use - for a programmer using a direct field access is bound to a single implementation of object's data access. Allowing the programmer to choose the scheme himself (either direct field for brevity and speed or set/get to allow abstraction and implementation substitution) would be certainly a Good Thing.

**Comment by badlogic** [comment]
Closing this out.
