### ISSUE TITLE
iOS8 AVAudioSession SetActive Error

### ISSUE THREAD

**Issue by wdcmlds** [libgdx/libgdx#2570]
We build our app using libgdx, it works perfectly well in ios7 or before, even ios8 stimulator.
But find an issue with AVAudioSession in iOS8.

I get the following error message:

AVAudioSession.mm:646: -[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.

Same problem occurs in ios8 to others, they fixed as followed:
http://stackoverflow.com/questions/24114323/ios8-avaudiosession-setactive-error

It is very urgent, waiting for the solution eagerly.

**Comment by Tom-Ski** [comment]
Will reopen if a test case that reproduces is provided.
