### ISSUE TITLE
GWT Export does not Prevent Default Key Presses

### ISSUE THREAD

**Issue by naortega** [libgdx/libgdx#2584]
When I compile my libGDX project to target `html` there are scripts to prevent default mouse operations, but not keyboard. This can be somewhat of a hassle for games where normally people use arrow keys.

I've been looking around and I tried multiple things (none of which worked) such as follows:

``` javascript
window.focus();
```

or

``` javascript
window.addEventListener("keydown", handleKeyDown(evt) {
        // Prevent space and arrow keys:
        if([32, 37, 38, 39, 40].indexOf(evt.keyCode) > -1) { evt.preventDefault(); }
});
```

or

``` javascript
handleKeyDown(evt) {
        evt.preventDefault();
}
document.getElementById('embed-html').addEventListener("keydown", handleKeyDown(evt), false);
```

etc.

But it doesn't seem to change anything. Any suggestions on what I may be doing wrong?

If you need to see my code it's [here](https://github.com/DeathsbreedGames/deathsbreedgames.github.io/blob/master/_layouts/default.html). Basically everything within that `{% if page.type == "libgdx" %}` statement is where my code is. And if you need the game page source-code is [here](https://github.com/DeathsbreedGames/deathsbreedgames.github.io/blob/master/games/GNP2/index.html), and the actual page is [here](http://deathsbreedgames.github.io/games/GNP2/).

Thanks!

**Comment by MDeiml** [comment]
@Deathsbreed I have the same problem, but couldn't solve it with maximojr's slution. Could you give me your full index.html source code?

**Comment by MDeiml** [comment]
@admund I don't know if that's the problem, but you use `onkeyup` instead of `onkeydown`

**Comment by MDeiml** [comment]
Ok, found a solution myself: I had a typo in the code that went up fixing the problem(despite it throwing an error), but I don't know why. So my full script looks like this:


       <script>
              function handleMouseDown(evt) {
                evt.preventDefault();
                evt.stopPropagation();
                evt.target.style.cursor = 'default';
              }

              function handleMouseUp(evt) {
                evt.preventDefault();
                evt.stopPropagation();
                evt.target.style.cursor = '';
              }
			  
			  function avoidLoseFocus(event){
			  alert('a);
					if (event.keyCode == 65){
						event.preventDefault();
					}
				}
				
              document.getElementById('embed-html').addEventListener('mousedown', handleMouseDown, false);
              document.getElementById('embed-html').addEventListener('mouseup', handleMouseUp, false);
              document.getElementsByTagName('body')[0].addEventListener('keydown', avoidLoseFocus, false);
       </script>
