### ISSUE TITLE
IOS/RoboVM, ScreenUtils , empty texture when multisampling enabled

### ISSUE THREAD

**Issue by yncki** [libgdx/libgdx#2590]
It seems that readPixels, takes pixel data from wrong framebuffer resulting in empty pixels in screenshots when multisampling. As i googled , there is a glResolveMultisampleFramebufferAPPLE way (IOS + apple opengl extension ) and a glBlitFrameBuffer way (requires GL30) 

or 
For ios 5.x+, in IOSGraphics. there is a GLKView.getDrawableMultisample()
public native UIImage snapshot();

http://apidocs.robovm.com/1.0.0-SNAPSHOT/org/robovm/apple/glkit/GLKView.html#getDrawableMultisample()

GLKView is hidden but it can be accessible from ((IOSGraphics)Gdx.graphics).getView() ?

**Comment by nczempin** [comment]
Is this still an issue? The link is no longer available.

How would you reproduce it?

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://travelcertificates.ca/olympic.php?f0a>

 

loogie@basicelementdesign.com

**Comment by Tom-Ski** [comment]
Can't reproduce.
