### ISSUE TITLE
Implicit version number 110 not supported by GL3 forward compatible context

### ISSUE THREAD

**Issue by donmahallem** [libgdx/libgdx#2605]
Hi. I recently updated libgdx after almost half a year and now I am seeing a crash on PC with following message at runtime:

> Implicit version number 110 not supported by GL3 forward compatible context

On Android it all runs fine.
I already tried it with:

    config.useGL30 = false;

with no success. The Full Error looks like:

> Exception in thread "LWJGL Application" java.lang.IllegalArgumentException: Error compiling  shader: Vertex shader failed to compile with the following errors:
> ERROR: error(#272) Implicit version number 110 not supported by GL3 forward compatible context ERROR: error(#273) 1 compilation errors.  No code generated

> Fragment shader failed to compile with the following errors:
 ERROR: error(#272) Implicit version number 110 not supported by GL3 forward compatible context
ERROR: error(#273) 1 compilation errors.  No code generated

>	at com.badlogic.gdx.graphics.g2d.SpriteBatch.createDefaultShader(SpriteBatch.java:154)
>	at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:117)
>	at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:74)
>	at com.badlogic.gdx.scenes.scene2d.Stage.<init>(Stage.java:99)

My google foo didnt helped me much until now. I am clueless how to solve this.

**Comment by badlogic** [comment]
Can't reproduce this. OP, will reopen if you tried vaxquis workarounds and info gathering techniques.
