### ISSUE TITLE
Model and ModelInstance produce significant lag during loading

### ISSUE THREAD

**Issue by niyaro** [libgdx/libgdx#2610]
I have a bunch of models that have 4000-6000 triangles, 15-30 bones each as well as 4 animations couple seconds long each. When one of these models is loaded with AssetManager and then instantiated with two ModelInstances on Sony Xperia U it causes very noticeable half second lag.

After profiling I found several reasons for this. First of all majority of loading time is spent in Sync method of ModelLoader with main culprit being loadAnimations of Model class (spends lots of time making NodeKeyframes from ModelNodeKeyframes). Secondly when this model is instantiated with ModelInstance all the animation keyframes as well as MeshParts are needlessly copied all over again.
For my app I was able to eliminate lag completely by making very intrusive changes for old version of libgdx a year ago and by removing needles copying mentioned above, and by removing ModelNodeKeyframe class completely and changing NodeKeyframe class slightly to accommodate for a change.

You should look whether such changes can be implemented without breaking libgdx design and whether preserving current design is worth current loading time.

**Comment by badlogic** [comment]
I guess there was no follow up on this, closing it out.
