### ISSUE TITLE
add normalized `.path()` to FileHandle

### ISSUE THREAD

**Issue by vaxquis** [libgdx/libgdx#2617]
It's a feature present both in core Java 7 lib (which is currently unsupported neither in libGDX nor on Android) [https://docs.oracle.com/javase/7/docs/api/java/nio/file/Path.html#normalize%28%29] and in Apache Commons IO [http://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/FilenameUtils.html#normalize%28java.lang.String%29], and is a quite nice & simple feature. It makes the path more "canonical" by getting rid of e.g. `.` & `..` and it's required in some cases, e.g. if the dotted paths point to internal JAR content (happened to me with relative texture paths provided from .MTL file); using an non-normalized path results in "file not found", using a normalized one works as expected.

Currently we have to either convert the `FileHandle.path()` by means of `URI` or include an additional library just for the sake of it, both being ugly & kludgy. Porting either Java 7's or Apache IO's normalizer (both are Open Source AFAIK) and exporting it as `.pathNormalized()` would be IMO the best solution here.

**Comment by badlogic** [comment]
I welcome a PR, i don't think we'll implement this otherwise.
