### ISSUE TITLE
Sound issue with iOS 8.1

### ISSUE THREAD

**Issue by argallo** [libgdx/libgdx#2624]
I have tested my application on various different devices for both android and iOS and it seems that when an iOS device is running 8.1 when a sound file is played using the Music class, The sound will begin at a lower volume and then jump to a high volume a few seconds in. Here's what it sounds like https://drive.google.com/file/d/0ByfvjZBeiV6qTnJhZ3Vja01KM0ZsZF9rZTQ4SmFkRlQzX24w/view?usp=sharing I have tried other audio formats and still the same problem.

**Comment by Tom-Ski** [comment]
Please provide a self contained executable example that reproduces this issue. Feel free to reopen when done so.
