### ISSUE TITLE
RoboVM - ScreenUtils.getFrameBufferPixmap not working

### ISSUE THREAD

**Issue by AzmiTerato** [libgdx/libgdx#2632]
Hi!,

ScreenUtils.getFrameBufferPixmap seems to result in a white Pixmap on iPad Mini. 

I also tried not clearing the frame buffer by removing glClear(GL_COLOR_BUFFER_BIT), but still results in a white screenshot.

Any workarounds would be helpful!

**Comment by FrankNT** [comment]
I got same issue

**Comment by nemo808** [comment]
I get a blank image on iPod, works fine on simulator.

**Comment by Darkyenus** [comment]
This seems to be present only for default frame buffer due to some optimisation magic in iOS. (Separate FB works well) See [these](http://stackoverflow.com/questions/12528365/why-is-glreadpixels-failing-in-this-code-in-ios-6-0) [two](http://stackoverflow.com/questions/22393687/glreadpixels-gives-a-black-image-only-on-ios-7-device) SO questions.

If that assumption is correct, this could be worked around by rendering to FB, capturing that and then rendering that FB to default FB.

**Comment by fkrstevski** [comment]
Has anyone been able to find a solution or a workaround to this issue?

**Comment by mickmuzac** [comment]
I ran into the same issue with my game. I decided it would be easier to simply write iOS specific code to take the screenshot. Here's my snippet:

```java
public byte[] takeScreenshot(){
    UIImage newImage;
    UIGraphics.beginImageContext(new CGSize(Gdx.graphics.getWidth(), Gdx.graphics.getHeight()));
    application.getUIViewController().getView().drawViewHierarchy(
          new CGRect(0, 0, Gdx.graphics.getWidth(), Gdx.graphics.getHeight()) , true);
    newImage = UIGraphics.getImageFromCurrentImageContext();
    UIGraphics.endImageContext();  

    NSData data = newImage.toJPEGData(.6);
    newImage.dispose();

    return data.getBytes();
}
```

Here, `application` is a reference to your `IOSApplication`. Let me know if this works for you.

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://avrasyakurye.com/secretary.php?fao>

 

loogie@basicelementdesign.com

**Comment by VinceAngel** [comment]
Hi, it was 6 months ago, still no fix for having the ScreenUtils.getFrameBufferPixmap() works with iOs directly ?
(Because iOs specific code can not do the same, particularly on a capture during render loop)
Thanks

**Comment by vinou31** [comment]
Hi, is there any news around this issue???

**Comment by Tom-Ski** [comment]
The consistent workaround is to just use a FrameBuffer. When taking a screenshot, render your scene to an FBO, then save read back the texture using a routine similar to this: https://gist.github.com/Tom-Ski/d8b0be1c8b19cc735e5404c93c2e70a6
