### ISSUE TITLE
Android Fragment not well destroyed in particular case

### ISSUE THREAD

**Issue by VinceAngel** [libgdx/libgdx#2639]
Here is the issue : 

We have a fragment with a gdx 3D viewer rendering. User tap the home button to display the "desktop" of the device.
Android can now decide to kill the activity if memory is required (you can simulate this setting Android debug options to keep no activities in background ). So if the option is checked, android destroy it.
Then the user displays all the running activities, and click on the gdx 3D viewer : the 3D view runs but the assets have issues (the 3D model is not renderend in my case)

With a little debug I saw that the dispose() have not been called, so the view is created again, but not well due to the missing dispose() call on leave...

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://naturalhypothyroidismcure.com/globe.php?8f>

 

loogie@basicelementdesign.com
