### ISSUE TITLE
typed arrays not supported

### ISSUE THREAD

**Issue by marcguilera** [libgdx/libgdx#2640]
I am getting an error while running firefox.

uncaught exception: java.lang.UnsupportedOperationException: typed arrays not supported

Due to this error nothing else will load. It's working fine in Chrome, Safari and Firefox in Debug mode in Eclipse but when I compile it it won't work in Firefox. I don't remember changing everything critical but I went back in time through git and if I recompile and old version that used to work on Firefox it won't now so it might be some GWT compiler configuration in that is in the gitignore that it's causing the problem but I have not clue of what is going on.

**Comment by FredGithub** [comment]
Seems like the problem is back using Libgdx 1.6.0, GWT 2.6.0 and latest Firefox (38.0.1) :(

**Comment by Tom-Ski** [comment]
Looks like a firefox issue. Nothing we can do.

**Comment by FredGithub** [comment]
Ah okay, I was reporting in case it was a libgdx issue like last time. On your previous comment you said you resolved it, so I thought it might be resolvable as well. 

@Tom-Ski thank you for taking the time to test and make sure it wasn't a libgdx problem, which I'm sure you did.

**Comment by matthybrid** [comment]
I have the same problem recently

**Comment by smelc** [comment]
I'm having this issue too, with libgdx 1.7.0, gwt 2.6, and firefox 41.0.2, on Ubuntu. I confirm this is a firefox issue, since it works with google-chrome (after [enabling WebGL support](http://helpdeskgeek.com/how-to/enable-webgl-support-for-google-chrome-in-linux/)).

**Comment by TeNNoX** [comment]
I ran it one time - worked fine. (in firefox!)
Stopped the server, and a few minutes later, started it again (via _'gradlew.bat html:superDev'_)
And then the error occured. (a _'gradlew.bat html:clean'_ did not help)

Here's the build log, if it helps:
http://pastebin.com/raw/YV1qLjii

I don't have any custom code, either - I'm running the example project generated by gdx-setup.jar

**Comment by intrigus** [comment]
Please provide more information, which os, browser and gwt version.

Do you get any other errors/messages in the console of your browser? If so, please provide them.

**Comment by np511** [comment]
Iceweasel (Debian GNU/Linux version of Firefox) - unknown version, I'll check later
LibGDX 1.9.2
GWT 2.6.0

In case it helps, here are the root and html build.gradle files:

Root build.gradle:

```
buildscript {
    repositories {
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        jcenter()
    }
    dependencies {
        classpath 'de.richsource.gradle.plugins:gwt-gradle-plugin:0.6'
    }
}

allprojects {
    apply plugin: "eclipse"
    apply plugin: "idea"

    version = '0.0.1'
    ext {
        appName = "AppName"
        gdxVersion = '1.9.2'
    }

    repositories {
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url "https://oss.sonatype.org/content/repositories/releases/" }
    }
}

project(":core") {
    apply plugin: "java"


    dependencies {
        compile "com.badlogicgames.gdx:gdx:$gdxVersion"
    }
}

project(":desktop") {
    apply plugin: "java"


    dependencies {
        compile project(":core")
        compile "com.badlogicgames.gdx:gdx-backend-lwjgl:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
    }
}

project(":html") {
    apply plugin: "gwt"
    apply plugin: "war"


    dependencies {
        compile project(":core")
        compile "com.badlogicgames.gdx:gdx-backend-gwt:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx:$gdxVersion:sources"
        compile "com.badlogicgames.gdx:gdx-backend-gwt:$gdxVersion:sources"
    }
}

tasks.eclipse.doLast {
    delete ".project"
}
```
html/build.gradle:
```
apply plugin: "java"
apply plugin: "jetty"

gwt {
    gwtVersion='2.6.0' // Should match the gwt version used for building the gwt backend
    maxHeapSize="1G" // Default 256m is not enough for gwt compiler. GWT is HUNGRY
    minHeapSize="1G"

    src = files(file("src/")) // Needs to be in front of "modules" below.
    modules 'pixeldev.games.detenesc.GdxDefinition'
    devModules 'pixeldev.games.detenesc.GdxDefinitionSuperdev'
    project.webAppDirName = 'webapp'

    compiler {
        strict = true;
        enableClosureCompiler = true;
        disableCastChecking = true;
    }
}

task draftRun(type: JettyRunWar) {
    dependsOn draftWar
    dependsOn.remove('war')
    webApp=draftWar.archivePath
    daemon=true
}

task superDev(type: de.richsource.gradle.plugins.gwt.GwtSuperDev) {
    dependsOn draftRun
    doFirst {
    	gwt.modules = gwt.devModules
    }
}

task dist(dependsOn: [clean, compileGwt]) {
    doLast {
        file("build/dist").mkdirs()
        copy {
            from "build/gwt/out"
            into "build/dist"
        }
        copy {
            from "webapp"
            into "build/dist"
            }
        copy {
            from "war"
            into "build/dist"
        }
    }
}

draftWar {
   from "war"
}

task addSource << {
	sourceSets.main.compileClasspath += files(project(':core').sourceSets.main.allJava.srcDirs)
}

tasks.compileGwt.dependsOn(addSource)
tasks.draftCompileGwt.dependsOn(addSource)

sourceCompatibility = 1.6
sourceSets.main.java.srcDirs = [ "src/" ]


eclipse.project {
    name = appName + "-html"
}

```

Browser console log:
```

"SoundManager V2.97a.20130512 (AS3/Flash 9) + HTML5 audio + preferFlash" soundmanager2-jsmin.js:32:356
"SoundManager 2 HTML5 support: mp3 = true (preferring flash), mp4 = true (preferring flash), ogg = true, opus = true, wav = true" soundmanager2-jsmin.js:32:356
"soundManager: No Flash response within expected time. Likely causes: Flash blocked or JS-Flash security error." soundmanager2-jsmin.js:32:356
"soundManager: useFlashBlock is false, 100% HTML5 mode is possible. Rebooting with preferFlash: false..." soundmanager2-jsmin.js:81:226
"soundManager: Rebooting..." soundmanager2-jsmin.js:32:379
"SoundManager V2.97a.20130512 (HTML5-only mode)" soundmanager2-jsmin.js:32:356
"SoundManager 2 HTML5 support: mp3 = true, mp4 = true, ogg = true, opus = true, wav = true" soundmanager2-jsmin.js:32:356
"SoundManager 2: Ready." soundmanager2-jsmin.js:32:379
uncaught exception: java.lang.UnsupportedOperationException: typed arrays not supported <unknown>
syntax error particles.fragment.glsl:1:1
syntax error particles.vertex.glsl:1:1
syntax error default.fragment.glsl:1:1
syntax error default.vertex.glsl:1:1
syntax error depth.fragment.glsl:1:1
syntax error depth.vertex.glsl:1:1
syntax error arial-15.fnt:1:1
uncaught exception: java.lang.UnsupportedOperationException: typed arrays not supported <unknown>
```

The sound manager log is obviously irrelevant, I just didn't see a reason not to include it.

**Comment by intrigus** [comment]
Does your browser support WebGL at all?

**Comment by np511** [comment]
According to the [Get WebGL site](http://get.webgl.org):

> Hmm. While your browser seems to support WebGL, it is disabled or unavailable. If possible, please ensure that you are running the latest drivers for your video card.

**Comment by np511** [comment]
Looking through the GWT backend shows that it requires OpenGL 2, so it makes sense that it stops working. However, in Chromium, it loaded and said, "It appears that WebGL is unavailable or disabled," or some such.

**Comment by np511** [comment]
On a newer computer, WebGL is supported, and the error still occurs.

GDX: 1.9.4-SNAPSHOT
GWT: 1.6.0
Firefox: 45.1.1 ESR

**Comment by intrigus** [comment]
Are you really using GWT: 1.6.0 ? Or did you mean 2.6.0?
On which os is this?

Please create a [www.sscce.org](http://www.sscee.org).
If you share it on github, I should be able to look into it.

**Comment by np511** [comment]
Debian Linux 8.5
GWT: 2.6.0
GDX: 1.9.4
Iceweasel: 38.8.0

I created a default project with the "tools" extension enabled. Without and modification (except for some slight refactoring and the resulting edits in the GWT Definition files), I ran superDev, added the bookmarklets, and went to the page.

In the JS console: 

```
"SoundManager V2.97a.20130512 (AS3/Flash 9) + HTML5 audio + preferFlash" soundmanager2-jsmin.js:32:356
"SoundManager 2 HTML5 support: mp3 = true (preferring flash), mp4 = true (preferring flash), ogg = true, opus = true, wav = true" soundmanager2-jsmin.js:32:356
"SoundManager 2 loaded (OK)" soundmanager2-jsmin.js:32:356
uncaught exception: java.lang.UnsupportedOperationException: typed arrays not supported <unknown>
syntax error particles.fragment.glsl:1:1
syntax error particles.vertex.glsl:1:1
syntax error default.fragment.glsl:1:1
syntax error default.vertex.glsl:1:1
syntax error depth.fragment.glsl:1:1
syntax error depth.vertex.glsl:1:1
syntax error arial-15.fnt:1:1
uncaught exception: java.lang.UnsupportedOperationException: typed arrays not supported <unknown>

```

Initially, it was compiled with ```user.agent=safari```, and the error occured.

However, after compiled through the embedded refresh button (superDev mode), it used ```user.agent=gecko1_8```, and it worked fine (with some messages as shown). The problem appears to be when compiled for safari.

The console when it successfully displayed:
```
"SoundManager V2.97a.20130512 (AS3/Flash 9) + HTML5 audio + preferFlash" soundmanager2-jsmin.js:32:356
"SoundManager 2 HTML5 support: mp3 = true (preferring flash), mp4 = true (preferring flash), ogg = true, opus = true, wav = true" soundmanager2-jsmin.js:32:356
"SoundManager 2 loaded (OK)" soundmanager2-jsmin.js:32:356
syntax error particles.fragment.glsl:1:1
syntax error particles.vertex.glsl:1:1
syntax error default.fragment.glsl:1:1
syntax error default.vertex.glsl:1:1
syntax error depth.fragment.glsl:1:1
syntax error depth.vertex.glsl:1:1
syntax error arial-15.fnt:1:1
Error: WebGL: A texture is going to be rendered as if it were black, as per the OpenGL ES 2.0.24 spec section 3.8.2, because it is a 2D texture, with a minification filter requiring a mipmap, and is not mipmap complete (as defined in section 3.7.10).
```
