### ISSUE TITLE
BitmapFont markup language shouldn't crash if there is an invalid color code.

### ISSUE THREAD

**Issue by vedi0boy** [libgdx/libgdx#2644]
This is not so much a bug as a suggestion. I would like to use LibGDX's markup language to use in an ingame chat but the issue with this is that if a user uses a color code incorrectly, all the clients will crash. I thought it might be a good idea to instead of crashing the program when it encounters an invalid color code it could instead just remove the color code and print the error in the console. Thanks!

**Comment by badlogic** [comment]
@davebaol any chance you could make this code path more robust? I feel very uncomfortable with the markup parser just crashing on invalid input.

**Comment by vaxquis** [comment]
^ this.

**Comment by badlogic** [comment]
I think that's a good idea, considering it can be reused to check and
potentially throw a proper exception in other places.

**Comment by NathanSweet** [comment]
@vaxquis http://tvtropes.org/pmwiki/pmwiki.php/Main/MeToo

**Comment by vaxquis** [comment]
hell, I would just cast my vote on this... *if there was a voting system on GitHub*...

https://github.com/isaacs/github/issues/9
https://github.com/isaacs/github/issues/209
http://stackoverflow.com/questions/11381893/how-to-simulate-voting-in-githubs-issues-2-0-tracker

etc. ; that's why I still think that voicing a support of an idea even by posting a "+1" or "^this" is a viable way of communicating that the idea is worth implementing, discussing or fixing.

**Comment by NathanSweet** [comment]
"+1" doesn't bring anything to the discussion, it's spam. When you post
here, emails go out to many people. If everyone posted "me too", it would
be chaos.

This project is OSS, if you really want something, it's best to show it by
just implementing it.

**Comment by davebaol** [comment]
> @davebaol any chance you could make this code path more robust? I feel very uncomfortable with the markup parser just crashing on invalid input.

@badlogic, sure I'll look into it asap. Just moved into the new house, you know, my life is a bit of a mess right now. :smile: 
Do you prefer specialized exception or wrong colors silently ignored?

**Comment by mk1x86** [comment]
I vote for optional. override setMarkupEnabled to have a second parameter which decides whether to throw an exception or silently ignore wrong colors. IMO throwing exceptions should be default.

**Comment by NathanSweet** [comment]
I'd lean toward not throwing an exception, just render the invalid markup without changing colors. After all, invalid markup is just text. What is the use case for wanting to know the markup is invalid?

**Comment by vedi0boy** [comment]
I think it should silently remove the bad markups. But maybe some option to throw an exception if you want to. Anyways, I would just like to say thank you everyone for supporting my suggetion. I thought it would be a nice idea and it seems that peope agree! By the way, to the LibGDX devs, take your time adding this, its no rush for me right now.

**Comment by MobiDevelop** [comment]
I would say you shouldn't "remove" bad markup - just don't crash, and
display it as normal text.

**Comment by vedi0boy** [comment]
Even better, for me at least, keep the bad markup in the text just make it have no effect. So no exceptions thrown and if a bad markup is there, it is easy to debug and tell where the markup is bad. If you need an example of what I mean just ask.

**Comment by davebaol** [comment]
Done!
Now unknown markup colors are silently ignored and considered as normal text.

**Comment by davebaol** [comment]
Wiki page updated
