### ISSUE TITLE
App not resume after press home button iOS 8.1.2 (black screen) 

### ISSUE THREAD

**Issue by dungelin** [libgdx/libgdx#2655]
I have posted this in robovm but this seem libgdx issue.

I use robovm 1.0 beta 1 and libgdx 1.5.0. After press home button my iPad Mini 2 iOS 8.1.2 it can not resume (press home button and then click app icon), it just show black screen. This not occur with robovm 1.0 alpha 4 and libgdx 1.4.1

**Comment by fechy** [comment]
I have this issue now. 

It only happen when the app goes to the background. When this happen it fires the pause method, but never call resume.

I have the latest LibGdx snapshot (1.5.3-SNAPSHOT) and Robovm 1.0.0-beta-01 (beta 02 and snapshots doesn't work with IOS Bindings so I haven't use them), and robovm-gradle-plugin 1.0.0-beta-01.

Also plain IOS app (meaning no ext module like IOS Bindings from @blueRiverInteractive) when leaving the app in the background and then coming back, gives the black screen, resume() is not called.
