### ISSUE TITLE
Gradle gdx-setup not compatible with IntelliJ 14.0.2+

### ISSUE THREAD

**Issue by Disk1of5** [libgdx/libgdx#2661]
Hi, The generated build.gradle is not compatible with the intelliJ 14.0.2 and 14.0.3 it would seem that the Gradle plugin that the latest (and early release) versions that intelliJ uses is not the same as Android Studio.

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://ezbazar.co.in/right.php?w9pgd>

 

loogie@basicelementdesign.com
