### ISSUE TITLE
Crash on newMusic using RoboVM Gradle 1.0.0-SNAPSHOT plugin

### ISSUE THREAD

**Issue by marcinjakubowski** [libgdx/libgdx#2669]
When using RoboVM Gradle 1.0.0-SNAPSHOT plugin, the app crashes during async music loading according to crash log: http://pastebin.com/deQwHcqL

More information on the possible cause in the RoboVM tracker: https://github.com/robovm/robovm/issues/664#issuecomment-67854385

**Comment by ChristophMinnameier** [comment]
hey guys, me too having this issue, but for both robovm gradle plugin: 1.0.0-SNAPSHOT as well as 1.0.0-beta-01 (or beta-02 for that matter).

**Comment by BlueRiverInteractive** [comment]
Can also confirm that this is still an issue with the latest versions. I don't think this is a LibGDX issue but rather a RoboVM issue with threading. The app should definitely not crash when a native method with strong references is called on a Java worker thread.
For now there is a simple fix to prevent the app from crashing. Just wrap the `setDelegate` call in a call to `DispatchQueue.getMainQueue().sync();`  
```Java
      DispatchQueue.getMainQueue().sync(new Runnable() {
            @Override
            public void run () {
                IOSMusic.this.track.setDelegate(new AVAudioPlayerDelegateAdapter() {
                    @Override
                    public void didFinishPlaying (NSObject player, boolean success) {
                        final OnCompletionListener listener = onCompletionListener;
                        if (listener != null) {
                            Gdx.app.postRunnable(new Runnable() {
                                @Override
                                public void run () {
                                    listener.onCompletion(IOSMusic.this);
                                }
                            });
                        }
                    }
                });
            }
        });
```
This will ensure that the native method is called on a native thread.

**Comment by BlueRiverInteractive** [comment]
Just noticed that the workaround seems to only work when asynchronously loading music. When you load it on the main thread the workaround above will freeze your app.
So we will have to wait for a proper fix on the RoboVM side.

**Comment by Tom-Ski** [comment]
Right, do you know if this has been reported in RoboVM land yet @BlueRiverInteractive ?

**Comment by Tom-Ski** [comment]
I guess we could use the hotfix if we check if we are loading async or not?

**Comment by BlueRiverInteractive** [comment]
As of yet there's no corresponding issue on RoboVM land.

Yes, checking for async loading should make that hotfix safe. Is there a simple way to know if we are loading asynchronously or synchronously?

**Comment by Tom-Ski** [comment]
`NSThread.getCurrentThread().isMainThread()` should be sufficient?

**Comment by BlueRiverInteractive** [comment]
I tried that but that doesn't seem to make any difference. In both cases (sync and async) it did return false for me. Not sure why though.

BTW I could make a simple test case for the issue and added it to RoboVM: https://github.com/robovm/robovm/issues/687

**Comment by Tom-Ski** [comment]
Using the NSThread check I can run both sync and async now.  Strange that in both cases you get false...

**Comment by BlueRiverInteractive** [comment]
I really don't know. I am using `AssetManager.finishLoading()` on the render thread.

**Comment by Tom-Ski** [comment]
Ah, I wasn't blocking, just calling `assetManager.update()`.

**Comment by Tom-Ski** [comment]
So all is good apart from if you want to call `finishLoading()`, in which case NSThread doesn't return the *correct?* value for `isMainThread()` (true), and we get nice and locked up.

**Comment by BlueRiverInteractive** [comment]
Yes, it's seems so. Don't know if there's a way around that hangup, other than not using finishLoading() for the time being. It would be very interesting what @ntherning can say about the issue https://github.com/robovm/robovm/issues/687. Perhaps it's a simple fix and we won't need a hotfix here, just the latest robovm nightly?

**Comment by Tom-Ski** [comment]
Hopefully! I guess we'll see what they say and if it's a tough one think about adding the hotfix then.

**Comment by ntherning** [comment]
This has been fixed now in RoboVM: robovm/robovm#687. It will be in the next nightly (1.0.0-SNAPSHOT) and in the next beta release. Please try your code with the next nightly and close this libGDX issue if it works.

**Comment by Tom-Ski** [comment]
All fixed. Thanks @ntherning!

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://miglas.valsts.lv/this.php?i8zd7>

 

loogie@basicelementdesign.com
