### ISSUE TITLE
Crash in native code with Pixmap

### ISSUE THREAD

**Issue by DarthCreationist** [libgdx/libgdx#2675]
I was debugging an issue in my application and found that I was creating too many Pixmaps for my phone to handle. It was however difficult to get this information, because the app simply closes, there is no error message and nothing in LogCat. The same happens on the Desktop, if you push it to its limit.

The following code reproduces the issue (just put it in any app's initialization code):

```java
ArrayList<Pixmap> list = new ArrayList<Pixmap>();

while(true) {
    list.add(new Pixmap(file));
    System.out.println("List size:    " + list.size());
}
```

Please improve error handling for this condition, so that an app can at least display a meaningful error message. Preferably an exception should be thrown on the Java side.

**Comment by DarthCreationist** [comment]
Is there any idea, when this may be fixed?

I don't mean to sound demanding ;D However, it is imho not just an optional enhancement. It is impossible to stop one's own app from crashing if the target phone has not enough memory. There is no way to check for the memory up-front. In my opinion, it's a considerable problem that you cannot do anything, not even a workaround.

**Comment by badlogic** [comment]
Looking through the native and Java side code of Pixmap and Gdx2DPixmap, we already throw an exception in case any kind of allocation failed. 

* [gdx2d_load](https://github.com/libgdx/libgdx/blob/master/gdx/jni/gdx2d/gdx2d.c#L223) will return 0 in case loading the image failed (including memory allocation) or in case allocating the backing bytes failed.
* `gdx2d_load` is called by `Gdx2dPixmap#load` which checks the return value of `gdx2d_load` it too will return 0 in case something failed.
* `Pixmap` calls `Gdx2dPixmap#load` and will throw an exception if the call failed.

If the OS decides to kill the app without us getting a chance to evaluate what's happening, there's nothing we can do.

**Comment by NathanSweet** [comment]
Weee I was right! :D ;)
