### ISSUE TITLE
DestructionListener (box2d extension)

### ISSUE THREAD

**Issue by dario-zubovic** [libgdx/libgdx#2678]
How comes that DestructionListener interface is empty?

**Comment by nooone** [comment]
In http://box2d.org/manual.pdf chapter 11.2, the manual says there is a DestructionListener interface with a callback `void SayGoodbye(b2Joint* joint)`.

`World.setDestructionListener(...)` is also not implemented btw: https://github.com/libgdx/libgdx/blob/master/extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d/World.java#L257

**Comment by badlogic** [comment]
We don't support listening on destructions as that incures a callback from native code.

**Comment by JesseTG** [comment]
Why not just remove it, then?

**Comment by badlogic** [comment]
Good point, so it shall be.
