### ISSUE TITLE
Robovm doesnt properly work with g3d particles

### ISSUE THREAD

**Issue by ASneakyFox** [libgdx/libgdx#2683]
when running to an ios simulator with the gradle task, the game will crash with an error about needing to force link some classes related to the g3d particle emitter when trying to load a .pfx file with the asset manager.

To fix this i've added < pattern >com.badlogic.gdx.graphics.g3d.particles.**< /pattern > inside of the < forceLinkClasses > tags in robovm.xml and was then able to run the game just fine.

I think it would be a good idea to add this to the xml file by default so others wouldnt have to figure this out the hard way too. I'd make a pull request for this but I'm not sure where the robovm.xml file is created.

**Comment by Tom-Ski** [comment]
Could you paste a self contained test that reproduces this along with the full stacktrace, I can't replicate using this test on device and with simulator: https://github.com/libgdx/libgdx/blob/master/tests/gdx-tests/src/com/badlogic/gdx/tests/g3d/ParticleControllerTest.java

**Comment by Tom-Ski** [comment]
Will reopen if provided code that reproduces.

**Comment by ASneakyFox** [comment]
Hey sorry i missed your first response. Ive created an example project. I'm using osx yomesite, xcode 6.1, and intellij 14

You see the error when running the ios ipad simulator when it loads the pfx asset (pfx file was created with flame). It can be fixed by doing what the error message suggests and add the pattern tag to the xml file. (example test case does not yet have this line added)

download link here: https://www.mediafire.com/?nj4dv7s7tu8v73u

**Comment by Tom-Ski** [comment]
Thanks @ASneakyFox
