### ISSUE TITLE
"Pixmap.setBlending(Pixmap.Blending.None)" don't work on GWT

### ISSUE THREAD

**Issue by admund** [libgdx/libgdx#2686]
Hi all,

One more bug in Pixmap on GWT from me :)

When we set ```Pixmap.setBlending(Pixmap.Blending.None)```, only last shape which we draw on texture will be showed. 

We can reproduce this bug by adding 
```
pixmap = new Pixmap(800, 480, Pixmap.Format.RGBA8888); // Pixmap.Format.RGBA8888);
Pixmap.setBlending(Pixmap.Blending.None);
// Create a texture to contain the pixmap
texture = new Texture(1024, 1024, Pixmap.Format.RGBA8888); // Pixmap.Format.RGBA8888);
```

in PixmapTest:

https://github.com/libgdx/libgdx/blob/master/tests/gdx-tests/src/com/badlogic/gdx/tests/PixmapTest.java

**Comment by MobiDevelop** [comment]
Indeed "copy" is not the correct composite mode for this, but I don't think any of the composite modes are. I'm not sure what is the best way to get the desired behavior here... I've been able to accomplish it by drawing twice, the first time with "clear" mode, to blow away the existing pixels, the second time with "source-over" mode, to draw the new data. This is obviously not super efficient.

In other news, I think that there is something wrong with fillCircle on the normal (non-GWT) Pixmap when the color is not opaque and blending mode is SourceOver.

![image](https://cloud.githubusercontent.com/assets/1095464/5603257/af01b7e4-9339-11e4-9c15-df374148947a.png)
