### ISSUE TITLE
Issue on OSX after upgrading to 1.5.1 (Desktop version)

### ISSUE THREAD

**Issue by edesdan** [libgdx/libgdx#2688]
Hi,
I got this issue when try to run my Desktop project on eclipse (OS
![screen shot 2014-12-30 at 00 10 20](https://cloud.githubusercontent.com/assets/5745049/5574154/539c6ce8-8fb8-11e4-8663-1ad56165e0f3.png)
X) after upgrading to libgdx 1.5.1:

com.badlogic.gdx.utils.GdxRuntimeException: Unable to read file for extraction: liblwjgl.jnilib

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://www.westsidecouncilofchambers.com/translate.php?ru>

 

loogie@basicelementdesign.com
