### ISSUE TITLE
Android loop broken on sound instances

### ISSUE THREAD

**Issue by voidstarfire** [libgdx/libgdx#2689]
Scenario: loop a sound and get the id. Use the ID to alter the volume of the sound. Play other sounds.
When playing other sounds, the loop stops.

This works fine on desktop (MAC). Cannot test on iOS/iPhone as the current LibGDX (1.5.0) crashes on startup.

**Comment by MobiDevelop** [comment]
By default, only 16 sounds can be played simultaneously on Android. The SoundPool will determine which sound(s) to stop if you exceed that amount. If you are playing fewer than 16 sounds, please provide an example which reproduces the issue.

**Comment by voidstarfire** [comment]
I'm moving with steps (a few a second at top speed) and I've got a rotating object that repeats it's sound until it's fired. Problem is, yes the repeating sound instance is cleared. Is there any way of checking that it still exists? So I can instantiate it again?

**Comment by badlogic** [comment]
There's no way to check if a sound instance has been cleared and reused by another sound instance. You could try artificially limiting the #sounds you play in your own code.
