### ISSUE TITLE
"Windowed" window becomes unresizable after changing dimensions programatically

### ISSUE THREAD

**Issue by Zalewa** [libgdx/libgdx#2702]
I've run into a problem where the game window becomes unresizable when the window is in "windowed" mode and I change resolution of this window through Gdx.graphics.setDisplayMode() but keep it in "windowed" mode.

Here's a video showing what's going on: https://www.youtube.com/watch?v=fPSJdaKNimY

It doesn't matter where I place the call to resize to 845, 454. The window becomes resizable again only if I switch to fullscreen and then back to windowed.

libgdx 1.5.2.

**Comment by MobiDevelop** [comment]
This looks like a regression in LWJGL. I can replicate this with a pure LWJGL application on LWJGL 2.9.2.
