### ISSUE TITLE
Wiki needs updating

### ISSUE THREAD

**Issue by MitchZinck** [libgdx/libgdx#2703]
It seems like the update to gradle changed some things that are not documented on the wiki. The biggest thing I saw was the Admob in libgdx page https://github.com/libgdx/libgdx/wiki/Admob-in-libgdx

For example google updated adView so that instead of:

    AdView adView = new AdView(this, AdSize.BANNER, "xxxxxxxx"); // Put in your secret key here
      
It has to be this:

    adView = new AdView(this);
    adView.setAdSize(AdSize.BANNER);
    adView.setAdUnitId(AD_UNIT_ID);

Also for the control section to work you now need to add the android project to the core projects build path and then make circular dependancies just a warning in eclipse. There are various other problems with the page but I am to busy myself to go through and change them (maybe if no one else can I will next month). Even though they are trivial problems beginner coders may not understand how to get past them.

Thanks,
Mitchell

**Comment by MobiDevelop** [comment]
You should not be adding a reference to the Android project in the corr
project. If you need to do that, you have done something wrong.

That said, anybody with a GitHub account can update the wiki, we don't need
issues opened for it.

**Comment by MitchZinck** [comment]
To access the Android activity from the core project yes you need to add it to the build path or else you cannot access it. 

Example: https://github.com/MitchZinck/BlockJump/tree/master/android/src/com/mzinck/blockjump/android

I could not access AndroidLauncher.java without linking the Android project to the Core project as a build path.

**Comment by MobiDevelop** [comment]
You don't need to access the Android activity if you did it right.

**Comment by MitchZinck** [comment]
Look, on the wiki it says specifically to add a handler and then access the handler through an interface. If you understand java, you will know that for me to access any class through an interface, I must create a new interface object such as:

    Interface i = new classNameHereThatImplementsSaidInterface();

Without adding AndroidLauncher.java to the build path I could not access the import and therefore could not create a new interface, leading me to not being able to change the AdMobView to visible and invisible. I am reporting this to you **_AS A USER_** of your framework. Instead of being condescending and telling me that I am wrong, try to read past your elitism and fix your projects problem.

**Comment by MobiDevelop** [comment]
I am telling you that you are doing something wrong because you are.

See [this repo](https://github.com/MobiDevelop/libgdx-ads-sample) for an example of how to implement ads with libgdx, using an interface and without having any reference to the Android project in the core.

**Comment by MitchZinck** [comment]
Sorry, I guess I was wrong. I was up late and wasn't cluing into the fact that you can pass the androidactivity to the core as an interface.
