### ISSUE TITLE
rendering a picture with ImageTextButton and newest libgdx 1.5.2

### ISSUE THREAD

**Issue by postpunkpl** [libgdx/libgdx#2706]
I think there is a problem with rendering a picture (just image - not background or label) with ImageTextButton and newest libgdx 1.5.2. Image doesn't show. With libgdx 1.3.1 it works fine.
A problem i saw with Desktop(running as java application on MacOSX Yosemite) and RoboVM-iOS backends (iPad and iPhone simulators).

**Comment by MobiDevelop** [comment]
Not enough information, ImageTextButton works as expected for me. If you can provide an example which reproduces the issue you are reporting, we will consider reopening this.
