### ISSUE TITLE
[Req]Sound.setVolume without ID

### ISSUE THREAD

**Issue by PojahnM** [libgdx/libgdx#2711]
We got stop, pause and resume functions that does not require an ID.
I would like to request similar for setVolume.
I could implement this myself, but I would have to reimplement this every time a nightly build is released.

**Comment by davebaol** [comment]
> I could implement this myself, but I would have to reimplement this every time a nightly build is released.

You can submit a pull request instead.

**Comment by MobiDevelop** [comment]
Not important enough to submit a PR I guess, so we'll close this out as no-longer wanted.
