### ISSUE TITLE
ScrollPane layout problem with ontop scrollbars and content smaller than scrollpane area

### ISSUE THREAD

**Issue by vbousquet** [libgdx/libgdx#2713]
When using on top scroll bar for a scroll pane with a content widget smaller than the display area, the layout seems incorrect to me since the content widget won't get extended to the complete scrollpane area (this is a followup to PR #2709).

If we take, the [ScrollPaneScrollBarsTest](https://github.com/libgdx/libgdx/blob/master/tests/gdx-tests/src/com/badlogic/gdx/tests/ScrollPaneScrollBarsTest.java) test and just change the displayed text by a rect (to clearly see the bounds) with this simple modification ;
```java
// vertOnlyLeftTable.add(new Label("VERT-ONLY-LEFT", skin));
// vertOnlyRightTable.add(new Label("VERT-ONLY-RIGHT", skin));
vertOnlyLeftTable.add(new Image(skin.getDrawable("default-rect"))).height(20).expandX().fill();
vertOnlyRightTable.add(new Image(skin.getDrawable("default-rect"))).height(20).expandX().fill();
```
You get the following result :
![2015-01-05 17_34_34-scrollpanescrollbarstest](https://cloud.githubusercontent.com/assets/2796036/5616073/47926256-9501-11e4-8b8a-978516219378.png)

and when scrolling:
![2015-01-05 17_35_14-scrollpanescrollbarstest](https://cloud.githubusercontent.com/assets/2796036/5616076/50114384-9501-11e4-9cce-99d35a1ee9d8.png)

I would think that the correct behavior would be to have the content widget expands to the complete scrollpane area.

Looking at the code, this seems to be due to the fact that the size of the widget is set after adjusting the display area of the content pane:
```java
		if (fade) {
			// Make sure widget is drawn under fading scrollbars.
			if (scrollX) areaHeight -= scrollbarHeight;
			if (scrollY) areaWidth -= scrollbarWidth;
		} else {
			if (scrollbarsOnTop) {
				// Make sure widget is drawn under non-fading scrollbars.
				if (scrollX) widgetAreaBounds.height += scrollbarHeight;
				if (scrollY) widgetAreaBounds.width += scrollbarWidth;
			} else {
				// Offset widget area y for horizontal scrollbar at bottom.
				if (scrollX && hScrollOnBottom) widgetAreaBounds.y += scrollbarHeight;
				// Offset widget area x for vertical scrollbar at left.
				if (scrollY && !vScrollOnRight) widgetAreaBounds.x += scrollbarWidth;
			}
		}

		// If the widget is smaller than the available space, make it take up the available space.
		widgetWidth = disableX ? areaWidth : Math.max(areaWidth, widgetWidth);
		widgetHeight = disableY ? areaHeight : Math.max(areaHeight, widgetHeight);
```

A way to make it better would be to extend the size of the content widget when scrollbars are on top before adjusting the size of the display area (if you agree, I will prepare a proper PR):
```java
		if (scrollbarsOnTop) {
			// If the widget is smaller than the available space, make it take up the available space.
			widgetWidth = disableX ? areaWidth : Math.max(areaWidth, widgetWidth);
			widgetHeight = disableY ? areaHeight : Math.max(areaHeight, widgetHeight);
			
			if (fade) {
				// Make sure widget is drawn under fading scrollbars.
				if (scrollX) areaHeight -= scrollbarHeight;
				if (scrollY) areaWidth -= scrollbarWidth;
			} else {
				// Make sure widget is drawn under non-fading scrollbars.
				if (scrollX) widgetAreaBounds.height += scrollbarHeight;
				if (scrollY) widgetAreaBounds.width += scrollbarWidth;
			}
		} else {
			if (fade) {
				// Make sure widget is drawn under fading scrollbars.
				if (scrollX) areaHeight -= scrollbarHeight;
				if (scrollY) areaWidth -= scrollbarWidth;
			} 
			// Offset widget area y for horizontal scrollbar at bottom.
			if (scrollX && hScrollOnBottom) widgetAreaBounds.y += scrollbarHeight;
			// Offset widget area x for vertical scrollbar at left.
			if (scrollY && !vScrollOnRight) widgetAreaBounds.x += scrollbarWidth;
			
			// If the widget is smaller than the available space, make it take up the available space.
			widgetWidth = disableX ? areaWidth : Math.max(areaWidth, widgetWidth);
			widgetHeight = disableY ? areaHeight : Math.max(areaHeight, widgetHeight);
		}
```

Using this little modification, I made the following test situations ;
- content smaller/bigger than scrollpane, ontop = true, fade = true, => Ok
- content smaller/bigger than scrollpane, ontop = true, fade = false, => Ok
- content smaller/bigger than scrollpane, ontop = false, fade = false, => Ok
- content smaller/bigger than scrollpane, ontop = false, fade = true, => somewhat wrong (view area clipped where the scrollbar would be) => but is there any use case for this ?

What do you think ?

NB : On a side note, I think there is a tiny little bug in [ScrollPaneScrollBarsTest](https://github.com/libgdx/libgdx/blob/master/tests/gdx-tests/src/com/badlogic/gdx/tests/ScrollPaneScrollBarsTest.java), the initial state of scrollpane flags are not set. You need to add this at the end of the constructor to get correct result (I will do a proper PR when discussion is ok):
```java
		for (ScrollPane pane : scrollPanes) {
			pane.setFadeScrollBars(doFade);
			pane.setScrollbarsOnTop(doOnTop);
		}
```

**Comment by NathanSweet** [comment]
Well, my commit fixes scrollbars on top with scrollbars at left or top edge, but doesn't address that the widget doesn't fill the size of the scrollpane. Hmm.

**Comment by vbousquet** [comment]
Yep, I was checking it at the moment. Needs to adjust when extending the content widget.

**Comment by NathanSweet** [comment]
Think I got it!

**Comment by vbousquet** [comment]
Nice ! thanks. Just added a little PR for the remaining bug in the test (ontop is supposed to be to true but it is not set to the scrollpanes)
