### ISSUE TITLE
Game running slowly on external Graphics Card

### ISSUE THREAD

**Issue by jt100xu** [libgdx/libgdx#2716]
My game is too slow when running on PC with external Graphics Card and set to 2 display screens. On normal PC with onboard Graphics card it is ok.

Here's my application config:
appConfig = new LwjglApplicationConfiguration();
appConfig.stencil = 8;
appConfig.width = w;
appConfig.height = h;

Please explain me why?

Thanks.

**Comment by nooone** [comment]
This is not the right place to ask this kind of questions and the information provided is not enough to help you, unfortunately.

Please read [Getting Help](https://github.com/libgdx/libgdx/wiki/Getting-help) and post your question either in the forums or visit the IRC channel.
