### ISSUE TITLE
Loading TMX Tileset Collections - Lacks Tileset Name

### ISSUE THREAD

**Issue by CypherEA** [libgdx/libgdx#2717]
In the TMX file xml, the <tileset> tag has a 'name' property.
It loads fine in regular single image Tilesets, but in Collection Tilesets (collection of images) the name property of the Tileset is not loaded.

The line tileset.setName(name); is missing from the code block following the else clause in line 359 of TmxMapLoader.java

**Comment by nooone** [comment]
@MobiDevelop I think this can be closed now.

**Comment by CypherEA** [comment]
Yeap
