### ISSUE TITLE
.setRotation() or .rotateBy() on ProgressBar does not work.

### ISSUE THREAD

**Issue by penandlim** [libgdx/libgdx#2720]
public void create() {

    stage = new Stage(new ScreenViewport());
    Gdx.input.setInputProcessor(stage);
    skin = new Skin();
    Pixmap pixmap = new Pixmap(10, 10, Pixmap.Format.RGBA8888);
    pixmap.setColor(Color.WHITE);
    pixmap.fill();
    skin.add("white", new Texture(pixmap));

    TextureRegionDrawable textureBar = new TextureRegionDrawable(new TextureRegion(new Texture(Gdx.files.internal("blue.jpg")))); // Just a blue square
    ProgressBar.ProgressBarStyle barStyle = new ProgressBar.ProgressBarStyle(skin.newDrawable("white", Color.DARK_GRAY), textureBar);
    progressBar = new ProgressBar(0,10,0.5f,false, barStyle);
    progressBar.setPosition(10, 10);
    progressBar.setSize(290, progressBar.getPrefHeight());
    progressBar.setAnimateDuration(2);
    progressBar.setValue(5);
    progressBar.setRotation(45); // Should rotate the bar

    stage.addActor(progressBar);
    }

![image]
(https://i.stack.imgur.com/JitgY.png)

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/Scene2d.ui#rotation-and-scale

**Comment by BonBonSlick** [comment]
And? No salvation? 
This does not work either.

```
     energyBar = new EnergyBar((int)screenWidth / 2, 25);
        energyBar.setPosition(55, Gdx.graphics.getHeight() - 55);

        Container wrapper = new Container(energyBar);
        wrapper.setTransform(true);
        wrapper.setOrigin(wrapper.getPrefWidth() / 2, wrapper.getPrefHeight() / 2);
        wrapper.setRotation(45);
        wrapper.setScaleX(1.5f);

```
