### ISSUE TITLE
useHDPI breaks 'real sizes'

### ISSUE THREAD

**Issue by voidstarfire** [libgdx/libgdx#2723]
There's an issue in 1.5.3 and I know what is it, should be an easy fix.

Basically you've suppled the option to "config.useHDPI = true;" which works perfect except it returns the wrong real dimension sizes.

For example: If I used 'Gdx.graphics.getPpcY()'  (One centimeter in height) it breaks with HDPI on. With HDPI off its working good.

**Comment by badlogic** [comment]
PPI/PPC is really just a constant on the desktop as there's no OS API that gives us the correct values. I don't believe this is fixable i'm afraid.

**Comment by voidstarfire** [comment]
It's been fixed in version 1.5.4

**Comment by badlogic** [comment]
Hah, shows how much i know :)

**Comment by voidstarfire** [comment]
Any idea when version 1.5.4 will be official?

**Comment by badlogic** [comment]
a week or two, want to tie it to the next robovm release

**Comment by voidstarfire** [comment]
Ahh yes the whole important 64bit support. My app just got approved with 32 bit though.
