### ISSUE TITLE
IntelliJ: Gradle sync failing after editing build.gradle

### ISSUE THREAD

**Issue by Fringale** [libgdx/libgdx#2726]
After making edits to the *build.gradle* file under IntelliJ IDEA 14.0.2 and libGDX 1.5.2, IntelliJ fails to sync the project and displays the error message `Gradle project sync failed. Basic functionality (e.g. editing, debugging) will not work properly`. The `Try Again` button appears to do nothing - actually, the logs show that any attempted sync crashes instantly:
```java
2015-01-10 19:09:47,782 [2266406]  ERROR - ellij.project.impl.ProjectImpl - com.android.tools.idea.gradle.project.AndroidGradleProjectComponent@72a56960 
java.lang.AssertionError
	at com.android.tools.idea.gradle.project.PreSyncChecks.attemptToUpdateGradleVersionInWrapper(PreSyncChecks.java:175)
	at com.android.tools.idea.gradle.project.PreSyncChecks.ensureCorrectGradleSettings(PreSyncChecks.java:72)
...
```

[An IntelliJ issue](https://youtrack.jetbrains.com/issue/IDEA-134118) exists about this problem: it seems that IntelliJ 14.0.2  still ships with an old Android Gradle tool (0.14.2?), not the new and shiny 1.0.0. From the comments there and the issue status, it appears to be fixed in the yet-to-be IntelliJ 14.0.3.

I could work around this problem by changing the version of the Android Gradle tool in *build.gradle* from `1.0.0` to `0.14.4` (the sync then proceed to download / downgrade to Gradle 2.1).

I'm not sure this is worth a quick fix in libGDX, since a workaround exists and IntelliJ 14.0.3 is on its way, but I'll let you guys see what's best.  : )

**Comment by Tom-Ski** [comment]
Going to wait for 14.0.3, making a quick fix for this will *probably* break AS or eclipse, so as its such an easy work around for us IDEA 14.0.2 users, we'll have to just cope with it :)
