### ISSUE TITLE
Dialog constructor doesn't call setSkin() on Table superclass

### ISSUE THREAD

**Issue by outofcoffee** [libgdx/libgdx#2727]
One of the Dialog constructors doesn't call `setSkin()` on the Table superclass, resulting in the Table's `skin` property being `null`. Without this fix, the following test fails:

```
final Dialog window = new Dialog("Example title", skin);

// this line throws an Exception as the Table skin is null
window.add("Example label");
```

Exception:
```
java.lang.IllegalStateException: Table must have a skin set to use this method.
	at com.badlogic.gdx.scenes.scene2d.ui.Table.add(Table.java:252)
```

Here's the PR to fix it:
https://github.com/libgdx/libgdx/issues/2728

Here's a work-around:

```
final Dialog window = new Dialog("Example title", skin);

// there is a bug in Dialog that doesn't set 'skin' on the Table
window.setSkin(skin);

// this line no longer throws an Exception as the Table skin is not null
window.add("Example label");
```

**Comment by outofcoffee** [comment]
@badlogic it might be better to remove the ``skin`` field from ``Dialog`` and change the access modifier of the one in ``Table`` to ``protected``. That way we can remove the calls to ``setSkin`` and use the same variable in both superclass (``Table``) and subclass (``Dialog``).

**Comment by NathanSweet** [comment]
`dialog.setSkin(skin)` could also be used.

It's not a big deal for Dialog to have its own skin field.

**Comment by outofcoffee** [comment]
OK, cheers @NathanSweet ! Thanks for all the great work :)
