### ISSUE TITLE
Box2d Occasionally Crashes on CreateFixture Method

### ISSUE THREAD

**Issue by littletinman** [libgdx/libgdx#2730]
The error is as follows: 

/data/data/com.game.android/lib/libgdx-box2d.so (Java_com_badlogic_gdx_physics_box2d_Body_jniCreateFixture__JJF+16)
/system/lib/libdvm.so (dvmPlatformInvoke+112)

This happens when I iterate through a small array (around 8-16 objects) setting up some bodies/enemies in my world.

Here's the code being run:

        shape = new CircleShape();  
		shape.setRadius(3 * width);
		
		body = world.createBody(bodyDef);
		
	    body.createFixture(shape, 0);  // Randomly Crashes here

        shape.dispose();

		swarm.addEnemy(this);

**Comment by just4phil** [comment]
Are you calling this during world.step?
( collision callback?)
Am 10.01.2015 21:40 schrieb "Phil Royer" <notifications@github.com>:

**Comment by littletinman** [comment]
This is a possibility for sure. 

The scenario in which it's happening goes as follows:

1. A level is loaded and the first wave is selected 
2. The first wave is 8 enemies, so it creates 8 enemy objects
3. Now each enemy object has a box2D body and their creation is staggered by 2 seconds so that there is a delay just like the following started when a new enemy is created:

        new java.util.Timer().schedule( 
		        new java.util.TimerTask() {
		            @Override
		            public void run() {
		            	addToSwarm();
		            }
		        }, 
		        delay
		);
4. In the addToSwarm() function, that enemy gets a shape and the CreateFixture method is called.

Also note this is all while the game is being rendered so that you see the enemies "pop in" every 2 seconds. I have a feeling, somewhere in my description is going to be the big red flag of "Well there's your problem."

**Comment by just4phil** [comment]
as far as i know Timer creates an asyncTask in another thread.
that means that your enemies sometimes are created in a moment where box2d doesnt allow that (during physics provessing and collision callback)
thats why it crashes.
you better write the timer yourself and dont use an async Task for it

in the future better use the forum first for this kind of issues. use this issue tracker if all other possible reasons (bugs on your side) are out of question ;)

bye
phil
p.s. if you make a thread in the forum i will post my implementation of a spawnManager there

**Comment by just4phil** [comment]
@admins: this can be closed
