### ISSUE TITLE
drawPixmap(): resizing not correct

### ISSUE THREAD

**Issue by DarthCreationist** [libgdx/libgdx#2732]
The drawPixmap() overload that resizes the src rect does not yield the correct result. I use the following code to make a pixmap half the original resolution:

Pixmap temp = new Pixmap(pixmap.getWidth() / 2, pixmap.getHeight() / 2, pixmap.getFormat());
temp.drawPixmap(pixmap, 0, 0, pixmap.getWidth(), pixmap.getHeight(), 0, 0, temp.getWidth(), temp.getHeight());

This is the scene with the original images: 
![high](https://cloud.githubusercontent.com/assets/10283290/5693796/ef527d88-992e-11e4-89d4-b326ca2c89cc.png)

If I resize the images with the code above, the result is the following:
![low](https://cloud.githubusercontent.com/assets/10283290/5693798/00c9fda2-992f-11e4-9acc-2f2fac4d19a1.png)

If you download both images and switch between them in any image viewer, you can see that the resized objects are moving towards the lower-right corner of the screen. With my sprite sheet animation, the effect is clearly visible, with every animation step, the character moves more to the right.

**Comment by nooone** [comment]
Could you try the following:

`Pixmap temp = new Pixmap(pixmap.getWidth() / 2, pixmap.getHeight() / 2, pixmap.getFormat());
temp.drawPixmap(pixmap, 0, 0, pixmap.getWidth(), pixmap.getHeight(), 0, 0, temp.getWidth() - 1, temp.getHeight() - 1);`

Pixmap coords origin is in the top left so providing a target rectangle that is too big would result in everything being slightly shifted to the bottom right.

**Comment by DarthCreationist** [comment]
That made it a little better, some grass tiles still move, some don't move anymore (they are all in the same texture). But is it logical? Why is the result not the same like when I resize the image with GIMP?

Also, I noted that the smaller image is darker. I think this may have to do with that the background is black alpha and that it creeps into the borders when resizing.

**Comment by MobiDevelop** [comment]
You shouldn't have to subtract 1 from the width and height of the destination. That suggests that there is something wrong in the scaling code.

**Comment by badlogic** [comment]
Please provide a compiling ApplicationListener that illustrates the problem. Will reopen in that case.

**Comment by DarthCreationist** [comment]
Here you are:

```
import com.badlogic.gdx.ApplicationListener;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.Pixmap;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;




public class MyApplication implements ApplicationListener {
    @Override
    public void create() {
        sprite = new SpriteBatch();
        test = new Texture("test.png");

        Pixmap src = new Pixmap(Gdx.files.internal("test.png"));
        Pixmap dest = new Pixmap(src.getWidth() / 2, src.getHeight() / 2, src.getFormat());
        dest.drawPixmap(src, 0, 0, src.getWidth(), src.getHeight(), 0, 0, dest.getWidth(), dest.getHeight());
        test_resized = new Texture(dest);
    }


    @Override
    public void dispose() {
    }


    @Override
    public void resize(int width, int height) {
        this.width = width;
        this.height = height;
    }


    @Override
    public void pause() {
    }


    @Override
    public void resume() {
    }


    @Override
    public void render() {
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

        sprite.begin();
        sprite.draw(test, 0, 0, width / 2, height);
        sprite.draw(test_resized, width / 2, 0, width / 2, height);
        sprite.end();
    }


    private SpriteBatch sprite;
    private Texture test;
    private Texture test_resized;
    private int width;
    private int height;
}
```


This is what the application displays:
![scale_error](https://cloud.githubusercontent.com/assets/10283290/6177151/6df28356-b304-11e4-96e0-6d61d85a5b9b.png)

The left half of the screen is the original texture and the right one is the scaled version. You can clearly see that the right half is shifted to the lower right corner.

Here is the texture "test.png" so that you can try it for yourself (put to android/assets):
![test](https://cloud.githubusercontent.com/assets/10283290/6177184/acf0123a-b304-11e4-8402-69e9638469cf.png)

Let me know if I can help more. I would have actually fixed it myself, if the bug were on the Java side.

**Comment by jwehrle** [comment]
I might have a work around for this problem.

Instead of rendering with a SpriteBatch, use a Sprite and it's scale function.

So, that would look something like this:

Sprite sprite = new Sprite(new Texture(src));
sprite.setScale(0.5f);
// set position and whatnot

then in render:

sprite.draw(yourSpriteBatch);

I have tested this solution in my own application with a scale down to 0.1f
