### ISSUE TITLE
build.gradle for Android - AAR with native libs not getting in the APK

### ISSUE THREAD

**Issue by MonsterOfCookie** [libgdx/libgdx#2733]
Hi,

I was adding an AAR which had it's own native lib (.so file), I found this file was getting deleted when Gradle goes through and copies the libgdx native libs. What I found (using Gradle 0.14.4) is that in the android Gradle file is these lines were the cause.  

```
tasks.withType(com.android.build.gradle.tasks.PackageApplication) { pkgTask ->
    pkgTask.jniFolders = new HashSet<File>()
    pkgTask.jniFolders.add(new File(projectDir, 'libs'))
}
```

But following on from that found that if I changed this file so that the native libs are copied to "jni" folder in the project. 

```
task copyAndroidNatives() { 
    file("jni/armeabi/").mkdirs();
    file("jni/armeabi-v7a/").mkdirs();
    file("jni/x86/").mkdirs();

    configurations.natives.files.each { jar ->
        def outputDir = null
        if(jar.name.endsWith("natives-armeabi-v7a.jar")) outputDir = file("jni/armeabi-v7a")
        if(jar.name.endsWith("natives-armeabi.jar")) outputDir = file("jni/armeabi")
        if(jar.name.endsWith("natives-x86.jar")) outputDir = file("jni/x86")
        if(outputDir != null) {
            copy {
                from zipTree(jar)
                into outputDir
                include "*.so"
            }
        }
    }
}
```

Once I made these changes and removed the previous lines, the APK contained all the correct native libraries

Apologizes if there is a reason for it being this way currently. I just thought I would raise this in case any one was interested in importing an AAR with native libs

Cheers

**Comment by MobiDevelop** [comment]
I believe the reason for the current structure is due to Eclipse ADT requiring it to be this way. Perhaps you could create a note on the wiki for this.
