### ISSUE TITLE
iOS 8 reports wrong real dimensional sizes.

### ISSUE THREAD

**Issue by voidstarfire** [libgdx/libgdx#2736]
I've created a game using your framework (can find it here) 
https://play.google.com/store/apps/details?id=com.polygonattraction.shorb.android&hl=en

I'm doing the iOS release, everything is working fine apart from a few things. It's extremely blurry on an iPhone 6 and on iPhone 6 & 5 the screen dimensions are reported are wrong, example using Gdx.graphics.getPpcx() returns a size way bigger than a CM which I use for everything (button sizes, characters etc).

On a side note:
the desktop version & the iOS version reports the wrong size for CM's. It only effects the desktop version for 1.5.2

Any ideas?

**Comment by BlueRiverInteractive** [comment]
Yes the calculation of ppi and ppc for iOS is wrong, see https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java#L247

A few notes:
* The density should be just `density = scale` to be future proof.
* The ppi values should be defined for each iDevice individually using Wikipedia as a reference.

Existing values:
iPhone: 163, 326, 401
iPod: 163, 326
iPad: 132, 264
iPad Mini: 163, 326

It should be possible to find out the device model and type via `int uname(struct utsname *)` of `sys/utsname.h` and then correctly map those ppi values to the device model.

**Comment by voidstarfire** [comment]
Any idea when this would be implemented? I've got around the issue with some manual scaling function, but I've still got the blurry issue.

**Comment by badlogic** [comment]
ASAP, but i won't be able to fix it in the next 2 weeks. Maybe someone else
can step in and help.
