### ISSUE TITLE
Imagelayer in TiledMaps

### ISSUE THREAD

**Issue by Kaito23** [libgdx/libgdx#2741]
Hey,

I would like to add a Imagelayer to my tiled Map (.tmx) but currently it isn't shown.
See also:
gamedev.stackexchange.com/questions/90218/draw-image-layer-in-tmx-map-libgdx

**Comment by siondream** [comment]
This is a new feature in Tiled that has currently no support in Libgdx, I'll be working on adding this during the following days.

**Comment by siondream** [comment]
This has now been implemented. c5196e600d18d5ec3ff1bd0380605c532c3e739c

**Comment by MobiDevelop** [comment]
Cool, thanks @siondream.
