### ISSUE TITLE
migrate from Eclipse/maven to IntelliJ/gradle

### ISSUE THREAD

**Issue by mars3142** [libgdx/libgdx#2744]
It would be nice, if the project could be moved to IntelliJ with gradle. It's because of the Android Studio final release and now Eclipse is obsolete for Android development.

**Comment by badlogic** [comment]
This is not going to happen i'm afraid.

**Comment by Tom-Ski** [comment]
You can also convert the pom to gradle scripts using the gradle init plugin.  Never tried it, but might be worth a go.
