### ISSUE TITLE
Audio/Music Errors

### ISSUE THREAD

**Issue by rustanacexd** [libgdx/libgdx#2752]
I followed the a simple game tutorial from wiki  and this line of code doesn't work

dropSound = Gdx.audio.newSound(Gdx.files.internal("drop.wav"));
 rainMusic = Gdx.audio.newMusic(Gdx.files.internal("rain.mp3"));

is this outdated?

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/Getting-help

**Comment by ifwx** [comment]
1.Make sure the path is correct
2.Make sure the play sound files are correct
3.Make sure the volume is normal
