### ISSUE TITLE
Type top ... is not assignable to reference type

### ISSUE THREAD

**Issue by kutoman** [libgdx/libgdx#2754]
Hi, I'm using Kotlin as programming language in libgdx (current version: 1.5.2). By doing so I also want to reference functions / properties as abstraction (in order to avoid code duplication) of course. But I get this error during runtime when a method is called which uses references for class properties (it's similiar when it comes to class functions): 

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    de/lmgt/quiz/view/screens/LeaderboardScreen.retrieveEntriesAndRedraw(Lcom/badlogic/gdx/scenes/scene2d/ui/TextButton;)V @127: aload_3
  Reason:
    Type top (current frame, locals[3]) is not assignable to reference type
  Current Frame:
    bci: @127
    flags: { }
    locals: { 'de/lmgt/quiz/view/screens/LeaderboardScreen', 'com/badlogic/gdx/scenes/scene2d/ui/TextButton', top, top, top, top, 'com/badlogic/gdx/scenes/scene2d/ui/TextButton' }
    stack: { }
  Bytecode:
    0000000: 2b3a 0619 062a b400 a2b8 00a8 9900 32b2
    0000010: 00aa 12ac b600 b24d b200 aa12 b4b6 00b2
    0000020: 4ebb 00b6 592a b700 bac0 00bc 3a04 bb00
    0000030: be59 2ab7 00bf c000 bc3a 05a7 0044 1906
    0000040: 2ab4 00c1 b800 a899 0032 b200 aa12 c3b6
    0000050: 00b2 4db2 00aa 12c5 b600 b24e bb00 c759
    0000060: 2ab7 00c8 c000 bc3a 04bb 00ca 592a b700
    0000070: cbc0 00bc 3a05 a700 0912 cdb8 00d3 572d
    0000080: 2ab9 00d8 0200 c000 56c6 0007 03a7 0004
    0000090: 0499 0015 1904 bb00 da59 2a2d 2bb7 00dd
    00000a0: b900 e002 0057 2c2a b900 d802 00c0 006a
    00000b0: c600 0703 a700 0404 9900 1719 05bb 00e2
    00000c0: 592a 2cb7 00e5 b900 e002 0057 a700 1e2a
    00000d0: 2c2a b900 d802 00c0 006a 59c7 0006 b800
    00000e0: e8c0 00ea b600 eeb7 00f2 b1            
  Stackmap Table:
    full_frame(@62,{Object[#2],Object[#157],Top,Top,Top,Top,Object[#157]},{})
    same_frame(@121)
    same_frame(@127)
    same_frame(@144)
    same_locals_1_stack_item_frame(@145,Integer)
    same_frame(@166)
    same_frame(@183)
    same_locals_1_stack_item_frame(@184,Integer)
    same_frame(@207)
    full_frame(@225,{Object[#2],Object[#157],Top,Top,Top,Top,Object[#157]},{Object[#2],Object[#106]})
    same_frame(@234)

	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

The corresponding code of that method is:

    private fun retrieveEntriesAndRedraw(correspondingTab : TextButton) {

        val cachedCount : KMutableMemberProperty<LeaderboardScreen, Int?>
        val cache : KMutableMemberProperty<LeaderboardScreen, Pair<Int, List<LeaderboardEntry>>?>

        val serviceActionGetEntries : ((Int, List<LeaderboardEntry>?, Exception?) -> Unit) -> Unit
        val serviceActionGetCount : ((Int?, Exception?) -> Unit) -> Unit

        when (correspondingTab) {
            globalTab -> {

                cachedCount = ::cachedGlobalsCount
                cache = ::cachedGlobals
                serviceActionGetEntries = {game.onlineService().getGlobalTop5withOwn(ownName, it)}
                serviceActionGetCount = {game.onlineService().getGlobalLeaderBoardEntriesCount(it)}
            }
            todaysTab -> {

                cachedCount = ::cachedTodaysCount
                cache = ::cachedTodays

                serviceActionGetEntries = {game.onlineService().getTodaysTop5withOwn(ownName, it)}
                serviceActionGetCount = {game.onlineService().getTodaysLeaderBoardEntriesCount(it)}
            }
            else -> error("unspecified tab")
        }

        if (cache.get(this) == null) {
            serviceActionGetEntries { (ownPos, entries, e) ->
                when (e) {
                    null -> {
                        cache.set(this, Pair(ownPos, entries!!.sortBy { it.pos }))
                    }
                    else -> {
                        if (e.causedByNoEntries()) {
                            cache.set(this, Pair(-1, listOf()))
                        } else if (isTabActive(correspondingTab)) {
                            changeNoEntriesMessage(Strings.CONNECTION_FAILURE)
                        }
                    }
                }
            }
        }

        if (cachedCount.get(this) == null) {
            serviceActionGetCount { (total, e) ->
                if (e == null) cachedCount.set(this, total)
            }
        } else {
            changeFootprint(cachedCount.get(this)!!)
        }
    }

Is there no way to avoid this without having to pass on these features of Kotlin?

**Comment by MobiDevelop** [comment]
Please use the forum or irc for questions.

**Comment by max-kammerer** [comment]
It's bug in kotlin see https://youtrack.jetbrains.com/issue/KT-6646 for workaround

**Comment by kutoman** [comment]
ok thanks for the help. I recently thought it's a bug related to libgdx (at least in conjunction with kotlin)
