### ISSUE TITLE
Mipmap specification doesn't work with asset manager in iOS.

### ISSUE THREAD

**Issue by voidstarfire** [libgdx/libgdx#2759]
Related to #1296

Example that works below but iOS is still blurry. If it take this out, iOS renders as black blocks.

       com.badlogic.gdx.assets.loaders.TextureLoader.TextureParameter param = new         com.badlogic.gdx.assets.loaders.TextureLoader.TextureParameter();

        param.genMipMaps = true;

        if(Gdx.app.getType() == com.badlogic.gdx.Application.ApplicationType.iOS){
            param.minFilter = Texture.TextureFilter.Linear;
            param.magFilter = Texture.TextureFilter.Nearest;
        }
        else{
            param.minFilter = Texture.TextureFilter.MipMapLinearNearest;
            param.magFilter = Texture.TextureFilter.Nearest;
        }

        for(String eachTextureName : this.listOfTextureNames){
            this.assetManager.load(eachTextureName, Texture.class, param);
        }

**Comment by badlogic** [comment]
Can't reproduce this. What does blurry mean? Please provide a compiling ApplicationListener that demonstrates the issue.
