### ISSUE TITLE
Freetype font is blurry on iPhone 6 - iOS8

### ISSUE THREAD

**Issue by voidstarfire** [libgdx/libgdx#2760]
Example of free type font loading that works on everything except iOS devices / simulator.
I've tried with no scaling and it's worse.
I really think there's an issue with iOS and blurriness with libGDX.

    public BitmapFont getFont(String font, float size)
    {
        return this.fetchFontAlreadyExist(size, font);
    }

    private BitmapFont fetchFontAlreadyExist(float size, String fileName)
    {
        if(this.bitmapFontOpificio == null)
        {
            this.bitmapFontOpificio = TextureLoader.getInstance().getAssetManager().get(OPIFICIO);
        }

        this.bitmapFontOpificio.setScale((size / FONT_SIZE_LARGE_CM) / FONT_MAGNIFICATION);

        return this.bitmapFontOpificio;
    }

    public void loadFonts() {
        //This is called at the load of the game. (Before Splash finishes loading)

        //Font settings
        FreetypeFontLoader.FreeTypeFontLoaderParameter fontParams = new FreetypeFontLoader.FreeTypeFontLoaderParameter();

        //Use font magnification because FreeType creates blurry font if you doing resolution independent stuff.
        fontParams.fontParameters.size = Math.round(FONT_SIZE_LARGE_CM * FONT_MAGNIFICATION);
        fontParams.fontFileName = OPIFICIO;
        fontParams.fontParameters.genMipMaps = true;
        fontParams.fontParameters.magFilter = Texture.TextureFilter.MipMapLinearNearest;
        fontParams.fontParameters.minFilter = Texture.TextureFilter.MipMapLinearNearest;

        //Load the font.
        TextureLoader.getInstance().getAssetManager().load(OPIFICIO, BitmapFont.class, fontParams);
    }

**Comment by rinold** [comment]
I'm not an expert and all this is only my hamble opinion :) but...

Just to clarify what is FONT_SIZE_LARGE_CM and FONT_MAGNIFICATION?
And what resolution is set on iOS/emulator? I mean the ```fontParameters.size``` AFAIK is pixel-sized value, that means the font with size 30 pixels might look different on retina screen with quite high resolution.

**Comment by voidstarfire** [comment]
FONT_SIZE_LARGE_CM = 1CM * 0.65f.
FONT_MAGNIFICATION = 2f. In order to get fonts to look sharp on Android, you need to double the size then scale down otherwise it looks blurry.

**Comment by voidstarfire** [comment]
FONT_SIZE_LARGE_CM = 1CM * 0.65f.
FONT_MAGNIFICATION = 2f. In order to get fonts to look sharp on Android, you need to double the size then scale down otherwise it looks blurry.

**Comment by badlogic** [comment]
Please provide an ApplicationListener that compiles and reproduces the issue. Can't reproduce this issue locally. Will reopen if you provide new info.
