### ISSUE TITLE
Gdx.input.getTextInput window is hidden by the main app windows on Windows 7.

### ISSUE THREAD

**Issue by titovmaxim** [libgdx/libgdx#2762]
Test case. The app is windowed, the window covers most of the screen space. There is the button to call Gdx.input.getTextInput. No input window appear after pressing the button. If the user press Alt-Tab the input window appears (so it was existing, but just covered by the main window). After that one can close the input window and open it again, works like expected. The problem arise again after fresh app start. The problem appears for me only on Window 7. Mac OS X work like expected.

Another problem is when the user accidentally clicks outside the input window and activated main app window. The input window disappears again without any clear indication that it is still working and how to bring it back.

Probably the best option would be to make it modal and to force it to front.

**Comment by titovmaxim** [comment]
Quick & dirty solution which works is to place dialog.setAlwaysOnTop(true) right before dialog.setVisible. However it makes the dialog system-wide always on top and does not solve the modality issue. dialog.setModalityType(?) does not work. Probably because it has no Swing parent. I have completely no experience in Swing so can not prepare PR with better solution.

**Comment by badlogic** [comment]
I'm afraid this can't be fixed, as a modal dialog needs a parent frame for it to be made modal. Since we use LWJGL, we don't have that luxury.

The getTextInput methods on the desktop are really just a kludge. In a real application i'd highly suggest to implement text input via scene2d.

**Comment by titovmaxim** [comment]
I've come to the same conclusion. However just adding one line
    dialog.setAlwaysOnTop(true);
right before
    dialog.setVisible(true);

makes the problem much less apparent. It's not the best, but it is simple and it works in the case.
