### ISSUE TITLE
Touch coordinates are wrong on iOS if UIStatusBarHidden is false

### ISSUE THREAD

**Issue by dgmp88** [libgdx/libgdx#2766]
I previously posted [this](https://groups.google.com/forum/#!topic/robovm/8Q_crAlkxYw) on the RoboVM forums, but Niklas directed me this way. 

I noticed my touches are reported as being half a centimeter or so lower than where I'm really pressing. This happens with a app on iOS when UIStatusBarHidden is set to false. When the status bar is hidden, touch coordinates are correct. The offset is about the size of the status bar, so I think this isn't being taken into account somehow? Test case [here](http://pastebin.com/CG5SDVKi). 

It's barely noticeable most of the time, but, for instance, if you hit the bottom of buttons in a stage they don't respond. Easy fix by hiding it anyway.

Everything else is glorious, keep it up! :D

**Comment by rinold** [comment]
Not an iOS expert, so everything below is only my humble opinion :) but looking at robovm backend code - it seems you might be correct about status bar not taken into account. Unfortunately, I have no iOS devices/development tools, but it seems something like following code is missing and might fix this issue:
```java
    if (!uiApp.isStatusBarHidden()) {
        CGRect statusBarRect = uiApp.getStatusBarFrame();
        switch(uiApp.getStatusBarOrientation()) {
        //set correct touch offset basing on status bar frame size and orientation
        }
    }
```

**Comment by Tom-Ski** [comment]
Had a look into this, but couldn't actually get the status bar to show correctly. Anyone have the config for RoboVM that shows the status bar?  (For LibGDX 1.6.0 and RoboVM 1.2 that is)

**Comment by badlogic** [comment]
This has been fixed.
