### ISSUE TITLE
add stop method into AudioRecorder interface

### ISSUE THREAD

**Issue by bill-lin** [libgdx/libgdx#2768]
should be able to stop AudioRecorder recording.

**Comment by badlogic** [comment]
That's what the close method is for.

**Comment by badlogic** [comment]
Erm, dispose...

**Comment by bill-lin** [comment]
Sorry, as I tried:
On android, dispose will not stop current recording 
On desktop, dispose will stop current recording but nothing recorded/saved.

IMO, behaviour of  Stop should be:
1, stop current recording
2, save what already has been recorded

**Comment by badlogic** [comment]
Please read the docs. AudioRecorder does not save anything, that's the
users responsibility. And dispose definitely stops the recorder on Android.

**Comment by bill-lin** [comment]
sorry, I mean save into short[] samples which passed into read method.

The problem I am trying to solve at the moment is:
when user touch down, start to record a 10 seconds audio sample, in another thread. If user touch up within this 10 seconds, to stop recording. 

As I used dispose method to stop recording within 10 seconds:
On android, dispose will not stop current recording. It will still record the full 10 seconds. This is due to the  synchronized(mRecordingStateLock) in AudioRecord class.

On desktop, dispose will stop current recording but nothing recorded into short[] samples.

**Comment by NathanSweet** [comment]
Are you using a giant short[]? Don't.

**Comment by bill-lin** [comment]
thanks Nathan, what's your suggestion?

**Comment by NathanSweet** [comment]
Use a small buffer and copy it into a large one.

**Comment by bill-lin** [comment]
thanks! it's a very useful suggestion! 
I will give it a go. Hopefully, would not get any gap between recordings
