### ISSUE TITLE
Gdx.net.sendHttpRequest not work after  Package for App Store/Ad-Hoc distribution...

### ISSUE THREAD

**Issue by ldthai** [libgdx/libgdx#2773]
Gdx.net.sendHttpRequest working (eclipse choose): run as ios Simulator, run as ios device.
but when i Package for App Store/Ad-Hoc distribution, run on device and Gdx.net.sendHttpRequest  does not working.
libgdx version 1.5.3
RoboVM 1.0.0 beta 3
this is my code:
public void F_GetMoreApp() {
		try {
			HttpResponseListener httpResponseListener = new HttpResponseListener() {

				@Override
				public void handleHttpResponse(HttpResponse httpResponse) {
					// TODO Auto-generated method stub

					if (httpResponse.getStatus().getStatusCode() == HttpStatus.SC_OK) {
						try {

							String str = httpResponse.getResultAsString();
							Element root = new XmlReader().parse(str);
							try {
								Array<Element> array = root.getChildByName(
										"MOREAPP").getChildrenByName("APP");
								if (array != null && array.size > 0) {

									F_ShowMoreApp(array);

								}

								else
									F_LoadFail();
							} catch (Exception e) {
								F_LoadFail();
							}
						} catch (Exception e) {
							F_LoadFail();
						}
					} else {
						F_LoadFail();
					}
				}

				@Override
				public void failed(Throwable t) {
					// TODO Auto-generated method stub

					F_LoadFail();
				}

				@Override
				public void cancelled() {
					// TODO Auto-generated method stub

					F_LoadFail();
				}
			};

			String linkmoreapp = "http://www.huesoft.com.vn/huesoftmobile/hsmoreapp";
			if (mGame.mOSType == MyOSType.ANDROID)
				linkmoreapp = "http://www.huesoft.com.vn/huesoftmobile/moreapp/android";
			if (mGame.mOSType == MyOSType.IOS)
				linkmoreapp = "http://www.huesoft.com.vn/huesoftmobile/moreapp/ios";

			HttpRequest mHttpRequest = new HttpRequest(HttpMethods.GET);
			mHttpRequest.setHeader("Content-Type",
					"application/xml;charset='UTF-8'");
			mHttpRequest.setUrl(linkmoreapp);

			Gdx.net.sendHttpRequest(mHttpRequest, httpResponseListener);
		} catch (Exception e) {
			F_LoadFail();
		}
	}
Former: I use libgdx 1.4.1 and robovm 1.0.0-alpha-04. it does working all

**Comment by Tom-Ski** [comment]
Duplicate #2761

**Comment by ldthai** [comment]
thank you!
