### ISSUE TITLE
ParticleEffect bug

### ISSUE THREAD

**Issue by SerafimArts** [libgdx/libgdx#2775]
Screenshot: http://docs.rudev.org/stream/672c19dafdce3dba2af194a335ea1a55

First emitter (index 0) contents '- Image Path -' image directory, but not real path. This problem can be corrected if remove "premultipliedAlpha" line, but... this is wrong.

I was looking for a long time error, so I think it should be added try\catch inside loadEmitterImages method.

Sorry for bad English =)

**Comment by Tom-Ski** [comment]
This is pitfall of loading 2d particles as we do, you must use the same version of LibGDX as the one that is used in the Particle Editor.  If you mismatch these versions, and in this case we add an option for premultipliedalpha to particles, your old particle effect will no longer work with a newer version of LibGDX.

This probably won't be resolved until the whole 2D particles API is refactored. See https://github.com/libgdx/libgdx/issues/909

**Comment by SerafimArts** [comment]
Metadata may be necessary to add to the file Particle? Namely the version of the editor and display an error when it does not coincide.
