### ISSUE TITLE
Missing asin() function in StrictMath/Math for GWT

### ISSUE THREAD

**Issue by JFixby** [libgdx/libgdx#2778]
Hi
I'm having this GWT-compilation error:
 [ERROR] Errors in 'file:/D:/red-triplane-fokker-gradle/core/fishing/com/jfixby/red/triplane/api/FloatMath.java'
      [ERROR] Line 114: The method asin(double) is undefined for the type StrictMath

Seems like the StrictMath emulation is missing asin function.

Can you please add it?

Thank you.

**Comment by MobiDevelop** [comment]
StrictMath is only emulated for GWT via the inclusion of JBox2D in the Box2D extension. All it does is call the corresponding normal Math methods. Honestly, I'd probably favor not emulating StrictMath at all as you really lose the spirit of the class when you take the "Strict" out of it.

**Comment by JFixby** [comment]
Well, the core game project shouldn't care about GWT-backend's issues. If core project wants to use StrictMath - it must use it. If GWT-backend can't implement StricMath than it his problem. Currently GWT-backend uses emulation hack to handle the issue.

I'm fine with it because it means that I no need to fix my core project removing StrictMath calls just for the sake of compatibility with GWT. Which is exactly the whole libGDX's cross platform concept is about.

**Comment by MobiDevelop** [comment]
The libgdx core gwt backend doesn't emulate StrictMath at all (among other
things that would be nice to have, but are not GWT compatible). If your
goal is to release html, you have to play in that sandbox, I'm afraid.

**Comment by xoppa** [comment]
I'd agree with MobiDevelop. If you don't care that math isn't strict for gwt then don't use the StrictMath class for gwt. It would be unacceptable for an emulation of a strict math class to not be strict math.

**Comment by MobiDevelop** [comment]
Going to close this one out. If you want to use StrictMath and don't mind if it is not actually strict, you may include the emulation in your own project.

**Comment by JFixby** [comment]
Ok, guys. I really don't understand what you are trying to say.

I'm just pointing out that this class: https://github.com/libgdx/libgdx/blob/master/extensions/gdx-box2d/gdx-box2d-gwt/src/com/badlogic/gdx/physics/box2d/gwt/emu/java/lang/StrictMath.java is missing the asin() function. 

To resolve the issue I guess someone should add the function.

From what we discuss here I have a feeling like you are trying to persuade me to delete the class from the libGDX project. Well I can't do so, and I don't really want to. Because I think it is better to add the missing two lines of code and close the subject.

These two missing lines of code would be exactly:
public static double asin(double a){
    return Math.asin(a);}

Can someone just add them to the file?

**Comment by MobiDevelop** [comment]
The only reason that is there is because JBox2D needs them. Only those methods which JBox2D needed were added (by the JBox2D maintainer).

If you need more methods and don't mind that they are not strict, then add them to your project.

**Comment by JFixby** [comment]
Ok. Got it.
