### ISSUE TITLE
Add javadoc to Bullet wrapper

### ISSUE THREAD

**Issue by Matsemann** [libgdx/libgdx#2781]
Thanks for a great wrapper. However, I often find myself having to look up documentation for most of the functions directly in Bullet. This often leads me to [this site](http://bulletphysics.org/Bullet/BulletFull/classbtGeneric6DofSpringConstraint.html#details) which has generated this from the comments, for instance from [this file](https://github.com/svn2github/bullet/blob/master/tags/bullet-2.82/src/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.h#L34)

Would it be possible to add these kind of comments as Javadoc to the generated Java-files for the wrapper?

**Comment by Matsemann** [comment]
For instance, this code

    public class btGeneric6DofSpringConstraint extends btGeneric6DofConstraint {

could end up looking like

```
/**
 * Generic 6 DOF constraint that allows to set spring motors to any translational and rotational DOF
 *
 * DOF index used in enableSpring() and setStiffness() means:
 * etc...
*/
public class btGeneric6DofSpringConstraint extends btGeneric6DofConstraint {
```

which would make it much easier to work with.

**Comment by xoppa** [comment]
No, [swig](http://www.swig.org/) doesn't support javadocs (yet).

**Comment by Matsemann** [comment]
Ahh, that's too bad. Keep this in mind when/if it is included. :)

The Bullet source code is not commented in a consistent manner, so not sure how easy it would be to extract all this information anyway.
