### ISSUE TITLE
use optimized code for inverting OpenGL 4x4 matrices

### ISSUE THREAD

**Issue by vaxquis** [libgdx/libgdx#2783]
[ENHANCEMENT]
for generic
[ux vx wx tx]
[uy vy wy ty]
[uz vz wz tz]
[ 0  0  0  1 ]
matrices with common rot/trans/scaling components, an optimized formula can still be derived, both for det and inv:
```java
public float det () {
return ( val[M30] == 0 && val[M31] == 0 && val[M32] == 0 && val[M33] == 1 ) ? det3x3() : detGeneric();
}
public float det3x3() { // common OpenGL matrix
        return val[M00] * ( val[M11] * val[M22] - val[M21] * val[M12] )
                + val[M01] * ( val[M12] * val[M20] - val[M10] * val[M22] )
                + val[M02] * ( val[M10] * val[M21] - val[M20] * val[M11] );
	}

    public Matrix4 inv() {
return ( val[M30] == 0 && val[M31] == 0 && val[M32] == 0 && val[M33] == 1 ) ? invRST() : invGeneric();
}

    private Matrix4 invRST() {
        float t00_11 = val[M00] * val[M11],
                t00_12 = val[M00] * val[M12],
                t01_10 = val[M01] * val[M10],
                t01_12 = val[M01] * val[M12],
                t02_10 = val[M02] * val[M10],
                t02_11 = val[M02] * val[M11];

        float det = val[M20] * ( t01_12 - t02_11 )
                + val[M21] * ( t02_10 - t00_12 )
                + val[M22] * ( t00_11 - t01_10 );
        if ( det == 0f ) {
            throw new IllegalArgumentException( "det() = 0, non-invertible matrix" );
        }
        float inv_det = 1.0f / det;

        tmp[M00] = val[M11] * val[M22] - val[M12] * val[M21];
        tmp[M01] = val[M02] * val[M21] - val[M01] * val[M22];
        tmp[M02] = t01_12 - t02_11;

        tmp[M10] = val[M12] * val[M20] - val[M10] * val[M22];
        tmp[M11] = val[M00] * val[M22] - val[M02] * val[M20];
        tmp[M12] = t02_10 - t00_12;

        tmp[M20] = val[M10] * val[M21] - val[M11] * val[M20];
        tmp[M21] = val[M01] * val[M20] - val[M00] * val[M21];
        tmp[M22] = t00_11 - t01_10;

        tmp[M30] = -( val[M30] * tmp[M00]
                + val[M31] * tmp[M10]
                + val[M32] * tmp[M20] );
        tmp[M31] = -( val[M30] * tmp[M01]
                + val[M31] * tmp[M11]
                + val[M32] * tmp[M21] );
        tmp[M32] = -( val[M30] * tmp[M02]
                + val[M31] * tmp[M12]
                + val[M32] * tmp[M22] );

        val[M00] = tmp[M00] * inv_det;
        val[M01] = tmp[M01] * inv_det;
        val[M02] = tmp[M02] * inv_det;

        val[M10] = tmp[M10] * inv_det;
        val[M11] = tmp[M11] * inv_det;
        val[M12] = tmp[M12] * inv_det;

        val[M20] = tmp[M20] * inv_det;
        val[M21] = tmp[M21] * inv_det;
        val[M22] = tmp[M22] * inv_det;

        val[M30] = tmp[M30] * inv_det;
        val[M31] = tmp[M31] * inv_det;
        val[M32] = tmp[M32] * inv_det;

        return this;
    }
```
And yeah, those are minor dets there, BTW.

Also, there's a better generic algo, using caching of some of the multiplications for the general case [i.e. "old", generic inv()] - this exact c# code was stolen from http://stackoverflow.com/questions/2624422/efficient-4x4-matrix-inverse-affine-transform, but I use almost identical code myself in my codebase

    public static double[,] GetInverse(double[,] a)
    {
    var s0 = a[0, 0] * a[1, 1] - a[1, 0] * a[0, 1];
    var s1 = a[0, 0] * a[1, 2] - a[1, 0] * a[0, 2];
    var s2 = a[0, 0] * a[1, 3] - a[1, 0] * a[0, 3];
    var s3 = a[0, 1] * a[1, 2] - a[1, 1] * a[0, 2];
    var s4 = a[0, 1] * a[1, 3] - a[1, 1] * a[0, 3];
    var s5 = a[0, 2] * a[1, 3] - a[1, 2] * a[0, 3];

    var c5 = a[2, 2] * a[3, 3] - a[3, 2] * a[2, 3];
    var c4 = a[2, 1] * a[3, 3] - a[3, 1] * a[2, 3];
    var c3 = a[2, 1] * a[3, 2] - a[3, 1] * a[2, 2];
    var c2 = a[2, 0] * a[3, 3] - a[3, 0] * a[2, 3];
    var c1 = a[2, 0] * a[3, 2] - a[3, 0] * a[2, 2];
    var c0 = a[2, 0] * a[3, 1] - a[3, 0] * a[2, 1];

    // Should check for 0 determinant
    var invdet = 1.0 / (s0 * c5 - s1 * c4 + s2 * c3 + s3 * c2 - s4 * c1 + s5 * c0);

    var b = new double[4, 4];

    b[0, 0] = ( a[1, 1] * c5 - a[1, 2] * c4 + a[1, 3] * c3) * invdet;
    b[0, 1] = (-a[0, 1] * c5 + a[0, 2] * c4 - a[0, 3] * c3) * invdet;
    b[0, 2] = ( a[3, 1] * s5 - a[3, 2] * s4 + a[3, 3] * s3) * invdet;
    b[0, 3] = (-a[2, 1] * s5 + a[2, 2] * s4 - a[2, 3] * s3) * invdet;

    b[1, 0] = (-a[1, 0] * c5 + a[1, 2] * c2 - a[1, 3] * c1) * invdet;
    b[1, 1] = ( a[0, 0] * c5 - a[0, 2] * c2 + a[0, 3] * c1) * invdet;
    b[1, 2] = (-a[3, 0] * s5 + a[3, 2] * s2 - a[3, 3] * s1) * invdet;
    b[1, 3] = ( a[2, 0] * s5 - a[2, 2] * s2 + a[2, 3] * s1) * invdet;

    b[2, 0] = ( a[1, 0] * c4 - a[1, 1] * c2 + a[1, 3] * c0) * invdet;
    b[2, 1] = (-a[0, 0] * c4 + a[0, 1] * c2 - a[0, 3] * c0) * invdet;
    b[2, 2] = ( a[3, 0] * s4 - a[3, 1] * s2 + a[3, 3] * s0) * invdet;
    b[2, 3] = (-a[2, 0] * s4 + a[2, 1] * s2 - a[2, 3] * s0) * invdet;

    b[3, 0] = (-a[1, 0] * c3 + a[1, 1] * c1 - a[1, 2] * c0) * invdet;
    b[3, 1] = ( a[0, 0] * c3 - a[0, 1] * c1 + a[0, 2] * c0) * invdet;
    b[3, 2] = (-a[3, 0] * s3 + a[3, 1] * s1 - a[3, 2] * s0) * invdet;
    b[3, 3] = ( a[2, 0] * s3 - a[2, 1] * s1 + a[2, 2] * s0) * invdet;

    return b;
    }

Using those codes leads up to about 2-5 faster det/inv calculations. detGeneric() (i.e. the old one) can be cleaned similarily too.

Looking how newest MESA does it, it strikes me as very similar - the only this is that they store flags to know if they can skip some of the calculations ; http://cgit.freedesktop.org/mesa/mesa/tree/src/mesa/math/m_matrix.c?h=10.0  - still, even without flags we can make the code much more efficient, as shown above.

What do you think, guys? Should we bother with making `Matrix4` faster? Should I bother with crafting a PR for this?

**Comment by badlogic** [comment]
I'd generally appreciate a PR, however that needs to be tested as heavily as possible. The code in Matrix is heavily battle tested and i'd be a bit cautious changing it up.

Closing this out in favor of a PR.

**Comment by vaxquis** [comment]
It's just that a) most OpenGL matrices have ( val[M30] == 0 && val[M31] == 0 && val[M32] == 0 && val[M33] == 1 ), and that makes it clearly possible to b) use simplified constant expressions instead of multiplying those values by hand. I haven't "invented" those equations, they are results of simple math done on the existing equations for det/inv.

I'll try patching a PR with a test case to prove that, as I see no other way to make existing classes run faster with respect to OpenGL rendering internals without editing every GDX's release by hand...

**Comment by badlogic** [comment]
Method overrides...

**Comment by vaxquis** [comment]
that doesn't make internal `final Matrix4` fields in all the relevant OpenGL classes initializable to anything other than the basic `Matrix4` type, don't you think?

**Comment by badlogic** [comment]
no, but interfaces wouldn't either...

On Feb 3, 2015 12:25 AM, "vaxquis" <notifications@github.com> wrote:
>
> that doesn't make internal final Matrix4 fields in all the relevant
OpenGL classes initializable to anything other than the basic Matrix4 type,
don't you think?

**Comment by vaxquis** [comment]
with `final` fields - yes, you're right, they wouldn't allow it. with a provider & factory code pattern - they would.

**Comment by badlogic** [comment]
Please fork gdx and do whatever makes sense to you.
