### ISSUE TITLE
Set label background color , not background drawable

### ISSUE THREAD

**Issue by ifwx** [libgdx/libgdx#2785]
static public class LabelStyle {
		public BitmapFont font;
		/** Optional. */
		public Color fontColor;
		/** Optional. */
		public Drawable background;

		public LabelStyle () {
		}

		public LabelStyle (BitmapFont font, Color fontColor) {
			this.font = font;
			this.fontColor = fontColor;
		}

		public LabelStyle (LabelStyle style) {
			this.font = style.font;
			if (style.fontColor != null) fontColor = new Color(style.fontColor);
			background = style.background;
		}
	}

How I can set background color of a label widget, not set background drawable?

**Comment by NathanSweet** [comment]
This is an issue tracker. Please use the forum for such questions.
https://github.com/libgdx/libgdx/wiki/Getting-help

I shouldn't answer here, but: you can't, use a 1px white region that you tint.
