### ISSUE TITLE
PixmapPacker.updateTextureAtlas can return prematurely

### ISSUE THREAD

**Issue by RobRendell** [libgdx/libgdx#2786]
If many pixmaps are packed into a PixmapPacker and then updateTextureAtlas is called, the code can return prematurely.

	public synchronized void updateTextureAtlas (TextureAtlas atlas, TextureFilter minFilter, TextureFilter magFilter,
		boolean useMipMaps) {
		for (Page page : pages) {
			if (page.texture == null) {
				...
			} else {
				if (page.addedRects.size > 0) {
					...
					return;
				}
			}
		}
	}

The return statement at the end of the code snippet above (line 386 in the current version of the file) will cause the method to return if there exists a page with a texture and added rects, even if subsequent pages in the pages array have not yet been processed.

This can be reproduced by adding a single Pixmap to the packer, calling updateTextureAtlas() to pack that one image, adding another Pixmap that fits on the same page, and then adding enough additional Pixmaps (or one very large Pixmap) that causes the packer to overflow to a new page.  When updateTextureAtlas is called again, the first page completes its packing, but the second page does not.

**Comment by badlogic** [comment]
Thanks, fixed!
