### ISSUE TITLE
Click event after parent touchable disabled

### ISSUE THREAD

**Issue by Metaphore** [libgdx/libgdx#2789]
Assume we have scene with next actors:
* WidgetGroup root;
* Button button.

Where button is a child of root. 

Now just look at next steps:
1. Touch down on button;
2. Set root touchable to disabled;
3. Touch up on button;
4. Button click event happens.

In my opinion, it looks pretty wrong. Of course TouchListener has cancel() method and we can just call it for button to fix it, but what if root consist of dozen of touchable actors...

So, did I miss something or what is a proper way to disable touch for whole group?

**Comment by NathanSweet** [comment]
Disabling touch isn't the problem, it seems you want to disable touch during a touchdown event and have touchup never happen. Listeners rely on touchdown being paired with a touchup because this simplifies most listeners. To do what you want, after you set root touchable to disabled, call `Stage#cancelTouchFocus()`. I don't think this should happen automatically.

**Comment by Metaphore** [comment]
Oh yeah, it solves the problem.Thanks!

But I aware of case when I want to cancel touch focus only for specific group of actors. In this situation calling `Stage#cancelTouchFocus()` can break touch cycle of some other actor, that should not be bothered. Here is `Stage#cancelTouchFocus(Actor actor)` which cancel touch events for specific actor, but it works only for itself and despite children.
There is no way to check which actors got touch focus, so I can't just find everyone from hierarchy and cancel focus for each. So, perhaps it would be useful to add method like `Stage#cancelTouchFocusForGroup(Group group)`?

**Comment by NathanSweet** [comment]
I don't think that would be needed very often, if ever. You would only worry about disrupting the touch focus of another actor if you were supporting multi touch.

Possibly a better solution is to do the touch disable in a capture listener and cancel the event so none of the children ever see the touch down.

**Comment by Metaphore** [comment]
It's problem even for a single-touch stage, because I will call `Stage#cancelTouchFocus()` right after disabling touches for group just for avoiding described situation, but it doesn't exclude possibility of touching another stage actor at this moment.

As I understand you correct you talking about this:
```java
    addCaptureListener(new EventListener() {
            @Override
            public boolean handle(Event event) {
                if (getTouchable() == Touchable.disabled && event instanceof InputEvent) {
                    event.cancel();
                    return true;
                }
                return false;
            }
        });
```

But it's not working, button still get `touchUp` somehow/ I assume it's because stage keeps track of touch focus on button.

**Comment by NathanSweet** [comment]
>
> ​​
> It's problem even for a single-touch stage, because I will call
> Stage#cancelTouchFocus() right after disabling touches for group just for
> avoiding described situation, but it doesn't exclude possibility of
> touching another stage actor at this moment.
>
> ​If a stage has a single touch and you are doing something in touch down,
there is no other touch.​


> As I understand you correct you talking about this:
>
>     addCaptureListener(new EventListener() {
>             @Override
>             public boolean handle(Event event) {
>                 if (getTouchable() == Touchable.disabled && event instanceof InputEvent) {
>                     event.cancel();
>                     return true;
>                 }
>                 return false;
>             }
>         });
>
> But it's not working, button still get touchUp somehow/ I assume it's
> because stage keeps track of touch focus on button.
>

​No, step #1 in your first post in this issue should be done by a capture
listener. The listener disables touch on the root and cancels the event.

**Comment by Metaphore** [comment]
> ​If a stage has a single touch and you are doing something in touch down, there is no other touch.​

It's correct, but I don't say that I disable root touchable somewhere inside button touch listener. Just hiding group of actors and want to avoid of click event on some child actor if it been pressed.

So, is Stage#cancelTouchFocus() still best workaround?

**Comment by NathanSweet** [comment]
Ah, the scenario was unclear.

By design, if a touch down has occurred then the listener will always
receive a touch up at some point. I don't want to change this because it
complicates common use cases. Given that, canceling all touch focus when
you disable something should be fine if your app doesn't care about multi
touch.

Another option is to check if the actor has touch disabled in the listener
when touch up occurs and do nothing. This would require checking all the
parents to make sure touch is enabled from the root to the actor. This
could be done in ClickListener to avoid calling `clicked`.

**Comment by Metaphore** [comment]
Yep. Well, thank you for discussion. I decided to write utility method 'cancelTouchFocusForGroup(Group group)' which calls `Stage#cancelTouchFocus(Actor actor)` for whole hierarchy. Perhaps this is a slow one, but it executes pretty rare and does exactly what I want.

Assume issue may be closed.
