### ISSUE TITLE
Crash iOS app with NullPointerException in IOSSound.play

### ISSUE THREAD

**Issue by titovmaxim** [libgdx/libgdx#2790]
I've just published the game build with libGDX & roboVM for iOS devices. I've tested the game locally on simulator and iPhone-5s - everything works fine. However I've got plenty (several hundreds) of crash reports by Flurry from the game in the field:

<pre><code>*** Terminating app due to uncaught exception 'NullPointerException: null', reason: 'NullPointerException: null
com.badlogic.gdx.backends.iosrobovm.IOSSound.play(IOSSound.java:66)
com.badlogic.gdx.backends.iosrobovm.IOSSound.play(IOSSound.java:56)
com.mmxgames.engine.audio.RandomSound.playAtIndex(RandomSound.java:47)
com.mmxgames.engine.audio.RandomSound.play(RandomSound.java:36)
com.mmxgames.engine.audio.SoundPack.play(SoundPack.java:53)
com.mmxgames.engine.audio.SoundPack.play(SoundPack.java:37)
com.mmxgames.engine.ResMan$RSoundPack.play(ResMan.java:205)
com.mmxgames.ttj.themes.GameView3D.onMove(GameView3D.java:360)
com.mmxgames.ttj.play.ALevelScene.processAction(ALevelScene.java:356)
com.mmxgames.ttj.play.ALevelScene.__update(ALevelScene.java:186)
com.mmxgames.ttj.play.StoryLevelScene.__update(StoryLevelScene.java:144)
com.mmxgames.engine.components.Host.__update(Host.java:235)
com.mmxgames.engine.AGame.render(AGame.java:282)
com.badlogic.gdx.backends.iosrobovm.IOSGraphics.draw(IOSGraphics.java:330)
com.badlogic.gdx.backends.iosrobovm.IOSGraphics$1.draw(IOSGraphics.java:200)
org.robovm.apple.uikit.UIView.$cb$drawRect$(UIView.java)
org.robovm.apple.uikit.UIApplication.main(Native Method)
org.robovm.apple.uikit.UIApplication.main(UIApplication.java:334)
com.bulkypix.tedthejumper.ios.Launcher.main(Launcher.java:182)
</code></pre>

So the exception raise for more or less any device type (iPhone 6 Plus, iPhone 6, iPhone 5s, iPhone 4s, iPads, etc.). The source code line is:
<pre><code>
ALSource soundSource = OALSimpleAudio.sharedInstance().playEffect(soundPath, volume, pitch, pan, loop);</code></pre>

Only the possibility I see is that  OALSimpleAudio.sharedInstance() returns null.

What could be the problem for that?

**Comment by badlogic** [comment]
That's going to be a tough one to crack without a reproduction case :(

**Comment by titovmaxim** [comment]
I guess. But this is the error from the field. Actually a lot of (more than 300 reports!). But it is not reproducible on my device...

**Comment by badlogic** [comment]
Maybe you have a friend with a different device to test on? I'm afraid i'm
not sure how to reproduce it.

**Comment by titovmaxim** [comment]
Unfortunately I have used all available devices to test prior release. Everything was fine. Last day the game start to go in China (about 5000 users) and I've got about 500 (now it is even more than 300) of such error reports by Flurry. No idea what to do except just to wrap Sound.play in try/catch with reporting to prevent fatal crashes at least.

**Comment by titovmaxim** [comment]
At the moment there is about 2000 crashes with this issue. But all of them are "in the field". Is it possible to look inside OALSimpleAudio and try to understand under circumstances .sharedInstance() could return null? I'm not sure where the sources are.

**Comment by Tom-Ski** [comment]
We bind here https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/objectal/OALSimpleAudio.java#L38

Which calls the native method sharedInstance, which is generated by 
https://github.com/kstenerud/ObjectAL-for-iPhone/blob/master/ObjectAL/ObjectAL/OALSimpleAudio.h#L210

**Comment by titovmaxim** [comment]
I've look at the files. I'm not good in Objective C. But I see quite some possibilities when .sharedInstance() could return nil (which is converted to null then, I suppose). If _sharedInstance becomes nil (not only for first run, for whatever reason) the SynthesizeSingleton.h macros will try to create new instance by
https://github.com/kstenerud/ObjectAL-for-iPhone/blob/01c375c0803dc3c0d8aa604bc1311c8807bce3a9/ObjectAL/ObjectAL/Support/SynthesizeSingleton.h#L117

which will lead to
https://github.com/kstenerud/ObjectAL-for-iPhone/blob/master/ObjectAL/ObjectAL/OALSimpleAudio.m#L144

And this method do has several paths to return nil (with logging or without). So, as I see in the field, OALSimpleAudio.sharedInstance() could return null which leads to a crash. I could not go deeper and understand WHY it can fail (ALDevice, ALContext, etc. are out of my knowledge), but it will be at least good to:

1. Either check if sharedInstance is null and, fox example, throw the exception (not Runtime) and mark the method as throws. So one will must to wrap the calls in try/catch and to process error. 

2. Check if sharedInstance is null, ignore sound without crashing return false from the .play method and set some kind field like "lastError" in order to give the user chance to understand what happens.

Otherwise the usage is not crash-prone. The second option is better in my opinion.

Even better would not to report (sharedInstance == null), but to grab the reason from inside OALSimpleAudio.m to understand better what happens. It loggin is not enough when the crash happens remotely - one can not see it in crash reports.

**Comment by Tom-Ski** [comment]
Anything above and including warning level should be logged by default.

**Comment by titovmaxim** [comment]
You are right. I'm sure it is logged. And it is great when you can see the logs. But the crash happens by the user side. And you get just null pointer exception. Without information which was logged.

**Comment by badlogic** [comment]
This just shouldn't fail at all. Maybe we should bring it up with the
ObjectAL guy.

**Comment by Tom-Ski** [comment]
Are we 100% that the shared instance is null?

**Comment by titovmaxim** [comment]
No. But I do not have any other idea why this line could lead to null pointer exception.

**Comment by Tom-Ski** [comment]
If only we could replicate :/ Do you have the device details for the crash reports you have received?

**Comment by titovmaxim** [comment]
Yes. Here is the list of devices with the number of crashes (and percentage):
Apple iPhone 5s (GSM+CDMA),224.0,13.145539906103286%,
Apple iPhone 6,208.0,12.206572769953052%,
Apple iPhone 6 Plus,197.0,11.561032863849766%,
Apple iPhone 4s,152.0,8.92018779342723%,
Apple iPhone 5 (CDMA),144.0,8.450704225352112%,
Apple iPad Air (Wi-Fi Only),112.0,6.572769953051643%,
"Apple iPad Mini with Retina display (iPad4,4)",88.0,5.164319248826291%,
Apple iPad Mini (Wi-Fi Only),84.0,4.929577464788732%,
Apple iPhone 4 (GSM),65.0,3.8145539906103285%,
Apple iPad 2,61.0,3.57981220657277%,
Apple iPad Air 2 - Wi-fi,55.0,3.227699530516432%,
Apple iPad 4th Gen (Wi-Fi Only),53.0,3.1103286384976525%,
Apple iPhone 5s (GSM),44.0,2.5821596244131455%,
Apple iPad 3rd Gen (Wi-Fi/4G LTE Verizon/GPS),27.0,1.5845070422535212%,
"Apple iPad Air (iPad4,2)",20.0,1.1737089201877935%,
Apple iPad Air 2 - Cellular,20.0,1.1737089201877935%,
Apple iPhone 5 (GSM),19.0,1.1150234741784038%,
Apple iPad 3rd Gen (Wi-Fi Only),19.0,1.1150234741784038%,
Apple iPhone 5c (CDMA),18.0,1.056338028169014%,
Apple iPad 2 (GSM/A-GPS),18.0,1.056338028169014%,
Apple iPad 4th Gen (Wi-Fi/4G LTE Verizon/GPS),16.0,0.9389671361502347%,
Apple iPhone 5c (GSM),15.0,0.8802816901408451%,
Apple iPhone 4,12.0,0.704225352112676%,
"Apple iPad Mini with Retina display (iPad4,5)",10.0,0.5868544600938967%,
Apple iPad Mini (Wi-Fi/4G LTE Verizon/GPS),5.0,0.2934272300469484%,
Apple iPhone 4 (CDMA),5.0,0.2934272300469484%,
Apple iPad Mini 3 - Wifi,4.0,0.2347417840375587%,
Apple iPod Touch 5G,3.0,0.176056338028169%,
Apple iPod Touch 4G,3.0,0.176056338028169%,
Apple iPhone 3GS,2.0,0.11737089201877934%,
Apple iPad 4th Gen (Wi-Fi/4G LTE AT&T/GPS),1.0,< 0.1%,

Crashes by firmware (firmware, percentage of crashes):
iPhone 8.1.2,329.0,17.32490784623486%,
iPhone 8.1.3,259.0,13.638757240652975%,
iPhone 7.1.2,193.0,10.163243812532912%,
iPad 8.1.3,164.0,8.636124275934703%,
iPad 8.1.2,158.0,8.32016850974197%,
iPad 7.1.2,109.0,5.73986308583465%,
iPhone 7.1.1,95.0,5.002632964718273%,
iPhone 8.1.1,76.0,4.002106371774619%,
iPhone 7.0.4,69.0,3.6334913112164298%,
iPad 7.1.1,48.0,2.527646129541864%,
iPad 8.1.1,41.0,2.159031068983676%,
iPad 7.0.4,37.0,1.9483938915218537%,
iPhone 6.0.1,35.0,1.8430753027909426%,
iPhone 8.1,34.0,1.7904160084254872%,
iPhone 8.0.2,32.0,1.685097419694576%,
iPhone 6.1.3,29.0,1.5271195365982095%,
iPhone 6.1.2,20.0,1.05318588730911%,
iPad 7.0.3,18.0,0.9478672985781991%,
iPhone 7.1,18.0,0.9478672985781991%,
iPhone 7.0.6,17.0,0.8952080042127436%,
iPad 8.1,15.0,0.7898894154818326%,
iPad 8.0.2,14.0,0.7372301211163771%,
iPad 6.1.2,12.0,0.631911532385466%,
iPad 7.1,11.0,0.5792522380200106%,
iPhone 6.1,10.0,0.526592943654555%,
iPhone 6.1.6,6.0,0.315955766192733%,
iPad 6.1.3,6.0,0.315955766192733%,
iPad 6.1,6.0,0.315955766192733%,
iPad 7.0.6,6.0,0.315955766192733%,
iPhone 6.0.2,5.0,0.2632964718272775%,
iPhone 7.0.3,5.0,0.2632964718272775%,
iPhone 7.0.5,4.0,0.210637177461822%,
iPad 7.0.2,4.0,0.210637177461822%,
iPhone 8.0,4.0,0.210637177461822%,
iPhone 7.0.2,3.0,0.1579778830963665%,
iPhone 6.0,3.0,0.1579778830963665%,
iPhone 6.1.4,2.0,0.105318588730911%,
iPad 6.0.1,1.0,< 0.1%,
iPad 7.0,1.0,< 0.1%,:

**Comment by Tom-Ski** [comment]
Cool. So how often are you playing sounds?

**Comment by titovmaxim** [comment]
It's just a puzzle game. The sound plays every time the hero jump or the rain drops. So I'd say from several times per second to once per several second. I could not say that it is often. You can estimate it by looking video:
http://www.youtube.com/watch?v=j3sFVAGFQqo&spfreload=10

**Comment by Tom-Ski** [comment]
Great, thanks @titovmaxim . I'm pretty sure that ALSource is null. Not sure why you are getting an error on that line though.

**Comment by Tom-Ski** [comment]
This should resolve this issue, if not we can re-open.

**Comment by badlogic** [comment]
Thanks Tomski!

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://phongly.com/relieve.php?2qj>

 

loogie@basicelementdesign.com

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://edis-info.com/risky.php?r>

 

loogie@basicelementdesign.com
