### ISSUE TITLE
Vector2 dst probably ruins vector's coordinates

### ISSUE THREAD

**Issue by LittleLightCz** [libgdx/libgdx#2792]
Hello there.

Maybe I have found a bug in Vector2. I have these 2 lines of code. First one evaluates vec to [0.18428853:-0.9828722], but after evaluating the second line, vec turns into [0.0:-78.0]. I guess there is something going wrong inside dst(), because I would expect this method not to affect the inner coordinates in any way.

```java
  Vector2 vec = sheep_body.getPosition().sub(wolf.getPosition()).nor();
  float alphaSpeed = Math.abs(wolf.getPosition().dst(sheep_body.getPosition()) / CAMERA_HEIGHT);
```

Hope it helps :-), 
Cheers

**Comment by MobiDevelop** [comment]
If you look at the source of that method, it does not modify the vector's values.

**Comment by LittleLightCz** [comment]
Well maybe it's not the dst method itself, but the second line of this code does it. I don't know why ... Anyway, when I tried to recreate it using:
```java
        Vector2 v1 = new Vector2(1,2);
        Vector2 v2 = new Vector2(3,4);
        Vector2 vec = v1.sub(v2).nor();
        float value = Math.abs(v2.dst(v1)) / 160;
```
then it is alright. It changes the coordinates only in my previous code. Or maybe it could also be a Box2D problem, it's hard to tell. To test this, I guess I would need to send you my whole project :-). Anyway I fixed my problem by adding this right after first line with vec:

```java
        vec = new Vector2(vec);
```

**Comment by NathanSweet** [comment]
`sheep_body.getPosition().sub(wolf.getPosition())` modifies `sheep_body.getPosition()`.

**Comment by MobiDevelop** [comment]
The `nor` and `sub` methods you are calling in the first line modify the vector returned by sheep_body.getPosition(). Then you assign the same vector to vec. That probably isn't what you want.

**Comment by LittleLightCz** [comment]
Aaahhh so that is the cause! Thanks alot guys, I supposed all those methods return a new instance of Vector2, so there I made it wrong.
