### ISSUE TITLE
Avoid frequent object allocation

### ISSUE THREAD

**Issue by schleinzer** [libgdx/libgdx#2794]
Profiling my game, I found a frequent, unnecessary allocation of char[] objects (on in the desktop):

In "OisControllers#getWindowHandle", the following expression is being checked:

```java
System.getProperty("os.name").toLowerCase().contains("mac")
```

As "getWindowHandle" is called very frequently, so is that expression.

Problem with that expression is, that "toLowerCase" allocates new memory to do its job.

Furthermore, it is trivial to check this whole expression just once in a static initializer, store the result in a static boolean variable, both making that frequent expression much faster to check and not producing any garbage.

**Comment by NathanSweet** [comment]
Can you make a PR? Could also use equalsIgnoreCase.
