### ISSUE TITLE
Better integration for Controllers

### ISSUE THREAD

**Issue by Nodragem** [libgdx/libgdx#2797]
Hi,

I have mainly three questions about the Controllers API.

1) are the connection and disconnection events for Controllers still not available for Desktop? and if not, why? is it complicated to sort out?

2) I think it would be simple to make the scene2dUI API compatible out-of-the-box with Controllers (and Keyboard) navigation. Basically, each actors would have an index, and to press "down" or "up" would just make the selection going through the index table. (libGDX would set up a default button/axis for up/down, select, cancel, but the user would be free to change it)

3) A last question, the mapping for the OUYA is integrated out-of-the-box in libGDX. The mapping for the Xbox360 is out there: 
http://www.gamefromscratch.com/post/2014/09/22/LibGDX-Tutorial-Part-14-Gamepad-support.aspx
But it is not integrated out-of-the-box in libGDX. Why?

More out-of-the-box things may attract more developers?

**Comment by Tom-Ski** [comment]
1) They aren't, not sure.

2) There are lots of ways to do this, using a ButtonGroup with a simple listener would achieve the simple "up and down" control.  Anything more complicated than up and down should probably be implemented by the user instead.

3) Not sure if anyone would be against it including it, I personally wouldn't mind bundling 360 as its one of the most popular controllers to use on PC.  Not everything should be bundled though, LibGDX is very much a framework over an Engine where every possibility is already built for you.

**Comment by just4phil** [comment]
i implemented a menuNavigationManager that works like you said.... you can take a look here and get some inspirations:
https://bitbucket.org/just4phil/philengine/src/fb64edf38a4a250d3892a2f52423155155804e26/core/src/de/philweb/philengine/screensmenus/MgrMenuNavigationManager.java?at=master

but be aware that you cant copy and paste this into your game. it depends on a lot of stuff in my engine and the engine itself is not self-explanatory....

so just to get some inspirations
bye
phil
