### ISSUE TITLE
ShaderProgram class is NOT throwing exceptions in case it is not called in between a .begin() and a .end()

### ISSUE THREAD

**Issue by edesdan** [libgdx/libgdx#2798]
Hi All,
I recently had a lot of trouble using some features of ShaderProgram class.
According to the javadoc: 

```java
/** Sets the uniform with the given name. Throws an IllegalArgumentException in case it is not called in between a
	 * {@link #begin()}/{@link #end()} block.
	 * 
	 * @param name the name of the uniform
	 * @param values x and y as the first and second values respectively */
	public void setUniformf (String name, Vector2 values) {
		setUniformf(name, values.x, values.y);
	}

```

But if I try to execute the following code:

```java
@Override
	public void render() {
		Gdx.gl.glClearColor(0.8f, 0.8f, 0.8f, 1.0f);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		
		viewport.update(Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
		batch.setProjectionMatrix(camera.combined);
		
		fontShader.setUniformf("u_glow", GLOW);
		fontShader.setUniformf("u_outline", OUTLINE);
		
		batch.begin();
		
	
		
		fontShader.setUniformf("u_glowColor", GLOW_COLOR);
		fontShader.setUniformf("u_outlineColor", OUTLINE_COLOR);
		
		fontShader.setUniformi("u_enableGlow", 0);
		fontShader.setUniformi("u_enableOutline", 0);
		font.draw(batch, " No effects", 20.0f, VIRTUAL_HEIGHT - 50.0f);
		batch.flush();
		
		fontShader.setUniformi("u_enableGlow", 0);
		fontShader.setUniformi("u_enableOutline", 1);
		font.draw(batch, "Just outline", 20.0f, VIRTUAL_HEIGHT - 200.0f);
		batch.flush();
		
		fontShader.setUniformi("u_enableGlow", 1);
		fontShader.setUniformi("u_enableOutline", 0);
		font.draw(batch, "Just glow", 20.0f, VIRTUAL_HEIGHT - 350.0f);
		batch.flush();
		
		fontShader.setUniformi("u_enableGlow", 1);
		fontShader.setUniformi("u_enableOutline", 1);
		font.draw(batch, "Outline and glow", 20.0f, VIRTUAL_HEIGHT - 500.0f);
		batch.flush();
		
		batch.end();
	}

```

no exception is thrown!! I have spent a lot of time looking at that trying to understand why the shader didn't works. 

I think it's a bug, let me know your view.

Thanks!
Daniele.

**Comment by badlogic** [comment]
It's not a bug, it's bad interaction with SpriteBatch. The Javadoc
references ShaderProgram#begin/end. You code assumes SpriteBatch#begin/end
calls the shader begin/end.

SpriteBatch calls the shaders begin/end in SpriteBatch#end. Before that, it
will batch up as many drawcalls as possible and not do any rendering (and
hence not call shader#begin/end)

To set your uniforms, call shader#begin, set your uniforms, then call
shader#end.

**Comment by badlogic** [comment]
Erm, it's late. The reason your code works is because SpriteBatch is
calling shader#begin in SpriteBatch#begin, and it will call shader#end in
SpriteBatch#flush/end.

**Comment by edesdan** [comment]
OK, but I'm still not getting where/when the exception should be thrown. I mean for example if I have this:

```java
@Override
	public void render() {
		Gdx.gl.glClearColor(0.8f, 0.8f, 0.8f, 1.0f);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		
		viewport.update(Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
		batch.setProjectionMatrix(camera.combined);
		
		fontShader.setUniformf("u_glow", GLOW);
		fontShader.setUniformf("u_outline", OUTLINE);
		

	}
```
I'm not calling fontShader.begin() neither batch.begin().
Should the exception be thrown?

**Comment by badlogic** [comment]
Yes, it should be, guess someone ripped out that code path during a
refactoring. It's a bug.

**Comment by edesdan** [comment]
Ok good, thanks for your time, for now I have a Post-it on my desk that reminds me to call fontShader.begin() before doing anything else!!!!  :+1:   :-)

**Comment by badlogic** [comment]
OK, after much consideration, i opted to remove the incorrect Javadocs instead of throwing an exception. The reason being that this might have consequences in existing code that binds the program manually via the OpenGL header. It also adds additional (albeit neglible) overhead runtime wise to perform a check.
