### ISSUE TITLE
iOS app crashes on device with latest nightly 01.02.2015 (was working before)

### ISSUE THREAD

**Issue by titovmaxim** [libgdx/libgdx#2800]
The game which was successfully working crash on the real device (iPhone 5s) with the latest nightly 01.02.2015 right at the start. At the same time it works fine in simulator of the same device. Here is the simbolication of crash report:

<pre><code>11: [J]org.robovm.apple.foundation.Foundation.log(Ljava/lang/String;Lorg/robovm/apple/foundation/NSObject;)V (in Ted the Jumper) + 180
12: [j]org.robovm.apple.foundation.Foundation.log(Ljava/lang/String;Lorg/robovm/apple/foundation/NSObject;)V[clinit] (in Ted the Jumper) + 84
13: [J]com.badlogic.gdx.backends.iosrobovm.IOSApplication.debug(Ljava/lang/String;Ljava/lang/String;)V (in Ted the Jumper) (/IOSApplication.java:348)
14: [J]com.badlogic.gdx.backends.iosrobovm.IOSApplication.didFinishLaunching(Lorg/robovm/apple/uikit/UIApplication;Lorg/robovm/apple/uikit/UIApplicationLaunchOptions;)Z (in Ted the Jumper) (/IOSApplication.java:123)
15: [J]com.badlogic.gdx.backends.iosrobovm.IOSApplication$Delegate.didFinishLaunching(Lorg/robovm/apple/uikit/UIApplication;Lorg/robovm/apple/uikit/UIApplicationLaunchOptions;)Z (in Ted the Jumper) + 112
16: [J]org.robovm.apple.uikit.UIApplicationDelegate$ObjCProxy.$cb$application$didFinishLaunchingWithOptions$(Lorg/robovm/apple/uikit/UIApplicationDelegate;Lorg/robovm/objc/Selector;Lorg/robovm/apple/uikit/UIApplication;Lorg/robovm/apple/uikit/UIApplicationLaunchOptions;)Z (in Ted the Jumper) (/Unknown source:1048629)
17: [j]org.robovm.apple.uikit.UIApplicationDelegate$ObjCProxy.$cb$application$didFinishLaunchingWithOptions$(Lorg/robovm/apple/uikit/UIApplicationDelegate;Lorg/robovm/objc/Selector;Lorg/robovm/apple/uikit/UIApplication;Lorg/robovm/apple/uikit/UIApplicationLaunchOptions;)Z[callback] (in Ted the Jumper) + 236
</code></pre>

The issue was got using last libGDX and roboVM snapshot. From the history It is probably that the problem is exactly in the commit 2 days ago: 41708a5. It do the opposite to what it is named :) libGDX 1.5.3 with roboVM beta-03 works just fine. Latest SNAPSHOTS (libGDX & roboVM) fail with this issue.

This is connected to roboVM issue #737

**Comment by badlogic** [comment]
What's the device?

**Comment by Tom-Ski** [comment]
This should be reproducible with a blank application too, no?

**Comment by titovmaxim** [comment]
It is iPhone 5s.
02 февр. 2015 г. 6:28 пользователь "Mario Zechner" <notifications@github.com>
написал:

> What's the device?

**Comment by badlogic** [comment]
iOS 7 or 8? :)

**Comment by titovmaxim** [comment]
The latest. 8.1 I suppose. I'm in the plain now and do not have device with
me...
02 февр. 2015 г. 6:41 пользователь "Mario Zechner" <notifications@github.com>
написал:

> iOS 7 or 8? :)

**Comment by titovmaxim** [comment]
P.S. The build is 64 bit if it matters.
02 февр. 2015 г. 6:41 пользователь "Mario Zechner" <notifications@github.com>
написал:

> iOS 7 or 8? :)

**Comment by Tom-Ski** [comment]
If it is log, why doesn't this crash on 120 of IOSApplication?

**Comment by badlogic** [comment]
Yeah, that's a really good question :/ I have no idea. I'll try to reproduce this. If someone else could reproduce it with a plain RoboVM app that just does logging, please let me know.

**Comment by titovmaxim** [comment]
I'll try to reproduce it with a blank app or to avoid it by disable
logging. But I can do it only on weekend when I'll be back...
03 февр. 2015 г. 2:11 пользователь "Mario Zechner" <notifications@github.com>
написал:

**Comment by badlogic** [comment]
That would be awesome. No stress :)

**Comment by titovmaxim** [comment]
I'm back and have done a simple test. The test device is iPhone 5s, firmware: 8.1.3 (12B466).

I have used the simple empty app with test logging at the very beginning of the launcher:

<pre><code>@Override
protected IOSApplication createApplication()
{
	Foundation.log("BEGIN");
	Foundation.log("%@", new NSString("test1"));
	Foundation.log("END");
	...
}
</code></pre>

This code works fine when compiled to 32 bit IPA. However, it DOES CRASH at the second logging line (with "%@") when compiled to 64 bit IPA. So only "BEGIN" is logged before crash.

As a last test I have disabled the logging in my app at the early step like this:
<pre><code>@Override
protected IOSApplication createApplication()
{
	...
	final IOSApplication app = new IOSApplication(Game.instance, cfg);
	app.setLogLevel(Application.LOG_NONE);
	return app;
}
</code></pre>

And now it also works in both 32 & 64 bit IPAs (but without logging).

The conclusion is that Foundation.log with formatting string IS BROKEN in 64 bit mode. This is a question to roboVM and not libGDX, I suppose. Should we reopen the issue report on roboVM side?

**Comment by badlogic** [comment]
great job boiling it down! Yeah, i guess we can close this and opn one on
the RoboVM tracker.

**Comment by titovmaxim** [comment]
Moved to roboVM tracker (#748)

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://como-funciona.es/choice.php?tpha>

 

loogie@basicelementdesign.com
