### ISSUE TITLE
Texture packer with grayscale image give strange result

### ISSUE THREAD

**Issue by acatinon** [libgdx/libgdx#2804]
I'm using TexturePacker with some grayscale images like this one :
![hidegrayscale](https://cloud.githubusercontent.com/assets/3535019/6030201/2aee7a52-abf6-11e4-90a9-0273d9c7396a.png)
When I run TexturePacker command line, with the input folder as parameter, with only the image above in it (no pack.json), I get this result :
![pack](https://cloud.githubusercontent.com/assets/3535019/6030263/82e0d610-abf6-11e4-98a0-c52bcc8b3ef7.png)
As you can see, the packed texture is too bright.

There is below the `pack.atlas` file :
```js

pack.png
size: 128,128
format: RGBA8888
filter: Nearest,Nearest
repeat: none
HideGrayscale
  rotate: false
  xy: 2, 2
  size: 72, 72
  orig: 72, 72
  offset: 0, 0
  index: -1

```
I use the latest snapshot.

**Comment by NathanSweet** [comment]
Not sure what is happening. It uses AWT, so if that can't read/write it
then there may not be anything we can do.

**Comment by tilmanginzel** [comment]
I could solve this by saving the original image as a PNG-24 file. Your image file has a 32 bit color depth. As I understand, the last 8 bits are used for transparency. Maybe the file contained some misinformation or could not be read properly? I am no expert on this topic, so I cannot tell you exactly what happend there.

**Comment by NathanSweet** [comment]
Looks like that solves it, thanks!
