### ISSUE TITLE
[Feature Request] AnimatedTiledMapTile.getCurrentFrameIndex()

### ISSUE THREAD

**Issue by haimat** [libgdx/libgdx#2805]
I need to sync the animations of my tiled map tiles with other objects in the game. Thus I need to know which animated frame is currently drawn per tile.

There is already a (private) method `getCurrentFrame()`, which could be used for that. I think all that is necessary is to add a new property to the class, something like `int currentFrameIndex`, which would be set to `i` in the first line of the `for` loop, like this:

	private TiledMapTile getCurrentFrame() {
		int currentTime = (int)(lastTiledMapRenderTime % loopDuration);
		for (int i = 0; i < animationIntervals.length; ++i){
			currentFrameIndex = i;  // <-- added new line here
			int animationInterval = animationIntervals[i];
			if (currentTime<=animationInterval) return frameTiles[i];
			currentTime -= animationInterval;
		}
		throw new GdxRuntimeException("Could not determine current animation frame in AnimatedTiledMapTile. This should never happen.");
	}

Now the new method `public int getCurrentFrameIndex()` could simply return `currentFrameIndex`.

Thanks!

**Comment by MobiDevelop** [comment]
Seems like a reasonable request. Could also make the getCurrentFrame public, really.

**Comment by haimat** [comment]
Yes, fine with that too (beside my original request).
All I personally need would be the current frame index.

**Comment by MobiDevelop** [comment]
Right, I was mostly just indicating there really isn't any reason that getCurrentFrame needs to be private. I think we should probably not have getCurrentFrameIndex rely on getCurrentFrame but rather have that loop in getCurrentFrameIndex, and have getCurrentFrame call that.

**Comment by haimat** [comment]
Yes, sounds great, thanks!
