### ISSUE TITLE
ActorGestureListener zoom distance

### ISSUE THREAD

**Issue by kirushapojar** [libgdx/libgdx#2806]
After a while when i'm zooming and stop moving my fingers on the screen, but not releasing it, the distance variable is getting some random values. Tested on two android phones, gdx version 1.5.3

**Comment by MobiDevelop** [comment]
Small variations on touch pressure and position are detected by the touchscreen and sent to the application. Assuming this is what you were seeing since you didn't give any sample or example of the random values.
