### ISSUE TITLE
ApplicationListener.resize after .dispose on Android

### ISSUE THREAD

**Issue by titovmaxim** [libgdx/libgdx#2808]
From the field analytics it seems that on Android sometimes ApplicationListener.resize (through AndroidGraphics.onSurfaceChanged) could be called after ApplicationListener.dispose. Usually it leads to crash since everything was already properly disposed.

**Comment by Tom-Ski** [comment]
As much as we love issues reported, there isn't much we can do without more details.

Just to mention some details that should be provided:
* A self contained reproducible test case (if possible), or at least steps to reproduce.
* Versions of everything,  LibGDX, Android, or whatever the platform it is.
* What device this is running on.

Issues like this just tend to just sit here, cluttering up the issue tracker, which is important to keep as clean as possible so we can manage issues efficiently.

I'm going to close this issue out, feel free to reopen if you can supply details for us to reproduce or at least start to investigate from.
