### ISSUE TITLE
Skin WindowStyle and ImageTextButtonStyle font problem

### ISSUE THREAD

**Issue by nemo9955** [libgdx/libgdx#2812]
I upgraded after a sort of long time to the latest libgdx 1.5.4-SNAPSHOT and there was a problem in my skinset.json loading my font, after a few tweaks and modifications to how i load fonts and how i use them i realised the problem was in the WindowStyle and ImageTextButtonStyle section .
I removed them and everything loaded and worked (it loaded the menu with a textButton so i am sure both fonts loaded).

The skinset.json : ttps://github.com/nemo9955/StartingFire/blob/master/android/assets/img/skinset.json

**Comment by davebaol** [comment]
Sounds like your old json is not compatible with current libgdx.
Please use the forum or the irc channel.
