### ISSUE TITLE
How for Wiki Download on Zip File??

### ISSUE THREAD

**Issue by esbxp2013** [libgdx/libgdx#2814]
Hola : Cual es el Enlace para descargar la Documentacion del Wiki, en un formato Zip, o chm, para lectura en offline.

Profavor: Podrían poner un enlace, para aquella descarga, ???

Gracias !!!

**Comment by NathanSweet** [comment]
You need to use English here. You can download the wiki from GitHub.

**Comment by esbxp2013** [comment]
hmm ... I see ,,, Okey Thanks !!!
