### ISSUE TITLE
AfterAction run parallelly with other Actions.

### ISSUE THREAD

**Issue by jt100xu** [libgdx/libgdx#2815]
Hi, after update libgdx to the latest nightly, the problem's occurred with this simple code:
actor.addAction(Actions.moveBy(100, 0, 2));
actor.addAction(Actions.after(Actions.scaleTo(2, 2, 2)));
2 actions act at the same time (such us I added parallel action). The problem doesn't occur with nightly version on Oct 2014. Please fix this bug as soon as possible.
Thanks

**Comment by NathanSweet** [comment]
Can't repro using latest source.

```
public class ActionTest extends GdxTest {
	Stage stage;
	Texture texture;

	@Override
	public void create () {
		stage = new Stage();
		texture = new Texture(Gdx.files.internal("data/badlogic.jpg"), false);
		texture.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		final Image img = new Image(new TextureRegion(texture));
		img.setSize(100, 100);
		img.setOrigin(50, 50);
		img.setPosition(100, 100);

		img.addAction(Actions.moveBy(100, 0, 2));
		img.addAction(Actions.after(Actions.scaleTo(2, 2, 2)));

		stage.addActor(img);
	}

	@Override
	public void render () {
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		stage.act(Math.min(Gdx.graphics.getDeltaTime(), 1 / 30f));
		stage.draw();
	}

	@Override
	public void dispose () {
		stage.dispose();
		texture.dispose();
	}
}
```

**Comment by jt100xu** [comment]
I don't understand what you're saying ?? :smile: 
I've just reverted to the libgdx-nightly-20141014, maybe this issue come from the API change for v1.5.1 : "Added concept of target actor, separate from the actor the action is added to."
My game use complex multi screens and many ui on screen. And this issue make my game run wrong, with older version it's ok.
So please check it out.

By the way, i found an issue more about Box2D, i'll post it in another thread.
Thanks

**Comment by NathanSweet** [comment]
My code shows it works fine. Post code if you want to show it doesn't work.
https://github.com/libgdx/libgdx/wiki/Getting-help#executable-example-code

**Comment by MobiDevelop** [comment]
Assuming not an issue that @jt100xu cares about anymore. If that's not the case, please provide the requested info... if an actual issue exists, we can re-open.
