### ISSUE TITLE
parsing \t in .fnt files

### ISSUE THREAD

**Issue by Vineg** [libgdx/libgdx#2817]
https://www.glyphite.com/ uses \t as delimiter. Your parser can't handle it. Not sure if it libgdx issue or glyphite. https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g2d/BitmapFont.java#L915-L920

**Comment by davebaol** [comment]
Provide a .fnt generated by glyphite and maybe someone will look into it. :wink:

**Comment by Vineg** [comment]
Here is the default one https://www.dropbox.com/s/g6z5ftqe3pt3nxr/Untitled%20Scene.fnt?dl=0

**Comment by cobolfoo** [comment]
I can confirm this issue. I used atom to replace \t with one spacebar and it was enough to load the font in libgdx.

**Comment by MobiDevelop** [comment]
I still wonder if glyphite is simply taking liberties with the format.

**Comment by xoppa** [comment]
See #2960
