### ISSUE TITLE
ProgressBar Knob optional rounding?

### ISSUE THREAD

**Issue by Mirre** [libgdx/libgdx#2820]
I am not 100% sure if it is already possible to disable rounding on the Knob of the ProgressBar.

Doesn't seem so since it gets cast into a int when it it is drawn. 

https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ProgressBar.java#L157

https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ProgressBar.java#L186

The problem with the rounding is if you are gonna have a moving camera it rounds the position and so the knob "lags"/looks hacky.

For other classes like BitmapFont you can do:

font.setUseIntegerPositions(false);

And for some others I think there exists setRounding(boolean).

It is not a problem if it can't be added, Just that I spent some time trying fix the "hacky" looking knob before checking the source.

**Comment by NathanSweet** [comment]
Most people don't move the UI camera around, so this probably hasn't been
needed yet.

Maybe you could make a PR to add a `setRound` method? It should round
everywhere that is appropriate for both horizontal and vertical progress
bars (and sliders!).

`setRounding` would have been a better name, but a number of scene2d.ui
classes already use `setRound`. At least it is still better than
`setUseIntegerPositions`! :D

**Comment by NathanSweet** [comment]
Merged PR, thanks!
