### ISSUE TITLE
Sound looping too early when setPitch() is called on Android

### ISSUE THREAD

**Issue by Baxtalou** [libgdx/libgdx#2829]
Hi ! 
I know there are a lot of subject with Android and the audio accuracy. But I can not find any solution.
I want to pitch a little Music during its use (like the game Timbeman). So i have reduced a lot its quality and used it as a Sound played in loop. 
Now i can play the sound and pitch it on the fly. It works on the Desktop, Android and iOS but on the Android there is an issue : 
The sound ends earlier and loops to early.
Notice that in my code I am pitching the sound 2 times for the moment with 4 seconds between.

(ps : I tried to chain different small shunks of the music but there is this well known gap between the shunks on Android so this is impossible this way).

**Comment by MobiDevelop** [comment]
Android's SoundPool controls the sound so there probably isn't anything we can do. Also, you didn't include any code/sound for us to try to reproduce.

If you provide necessary information, we can take a look but we'll close this for now.
