### ISSUE TITLE
Environment don't support more than 5 PointLight

### ISSUE THREAD

**Issue by lavia-ale** [libgdx/libgdx#2832]
As the title says, when adding six or more PointLight in the environment, the new ones won't work like the others instead the whole model batch gets colored

**Comment by xoppa** [comment]
This is an issue tracker. Please use the forum or irc if you need help. https://github.com/libgdx/libgdx/wiki/Getting-Help

**Comment by lavia-ale** [comment]
I don't get why this isn't an issue, it's a libgdx bug.

**Comment by Darkyenus** [comment]
It is not a bug it is configured like that by default, see https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g3d/shaders/DefaultShader.java#L58

**Comment by lavia-ale** [comment]
My bad, I was looking the Environment documentation and I didn't see nothing about max PointLights, since it was failling in all platforms tought it was libgdx bug.
