### ISSUE TITLE
Using `List<String>.getItems().add("...");`

### ISSUE THREAD

**Issue by Zomis** [libgdx/libgdx#2834]
When using a `List<String>` Widget, using `list.getItems().add("some string");` causes the item to display, but not be selectable.

        final List<String> list = new List<String>(game.skin);
        list.getItems().add("Abc");
        list.getItems().add("Def");
        list.getItems().add("GHI");
        list.getItems().add("JKL");
        list.getItems().add("MNO");
        list.addListener(new ChangeListener() {
            @Override
            public void changed(ChangeEvent event, Actor actor) {
                Gdx.app.log("Menu", list.getSelected());
            }
        });
        table.add(list);

Using `setItems` however, works as expected:

        final List<String> list = new List<String>(skin);
        list.setItems("Abc", "Def", "GHI", "JKL");
        list.addListener(new ChangeListener() {
            @Override
            public void changed(ChangeEvent event, Actor actor) {
                Gdx.app.log("Menu", list.getSelected());
            }
        });
        table.add(list);

Is this a bug, or is it not intended to be able to add items dynamically in this way? (If it is not, then why does it display them?)

I'm using libGDX 1.5.3

**Comment by Darkyenus** [comment]
Selection needs to be validated upon changing items. See [relevant code](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/List.java#L224). You can try emulating that yourself or calling something like list.setItems(list.getItems()), which should do the job, but is not very robust. I don't think this is a bug, getItems() like methods rarely support modification of returned collection, unless explicitly stated.

**Comment by NathanSweet** [comment]
Yep. Call `setItems` after modifying the items.

**Comment by Zomis** [comment]
Ok, thanks. May I suggest improving the JavaDoc of `public Array<T> getItems ()` to make this clearer? At the moment, there is no JavaDoc on `getItems()` at all.
