### ISSUE TITLE
Cursor randomly disappear when using Gdx.input.setCursorImage on desktop/Windows

### ISSUE THREAD

**Issue by haedri** [libgdx/libgdx#2839]
When using Gdx.input.setCursorImage the cursor can randomly disappear forever (the application needs to be closed, another call to Gdx.input.setCursorImage doesn't solve the problem)

It doesn't seem to happen at all under my Linux environment, just under Windows

Tested on:
- Windows 64bits, jre 8 64 bits : ko
- Windows 64bits, jre 7 64 bits : ko
- Ubuntu 64bits, jre 7 64 bits : ok

To reproduce create a new project (tested with LibGdx 1.5.2), and change the main class content to:

	Pixmap		pixmap	= null;

	@Override
	public void create()
	{
		pixmap = new Pixmap(32, 32, Format.RGBA8888);
		pixmap.setColor(Color.GREEN);
		pixmap.drawCircle(15, 15, 10);
	}

	@Override
	public void render()
	{
		Gdx.gl.glClearColor(1, 0, 0, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		for (int i = 0; i < 1000; i++)
			Gdx.input.setCursorImage(pixmap, 16, 16);
	}

Launch the application and just move the mouse around
Of course this code is a bit overkill but this will force the bug to appear quite quickly (usually under 10 seconds on my test environement)

**Comment by essaic** [comment]
Out of curiosity, when do you need to set that many time in every render ? I tried your code and I have the same bug but if I try with 10 as the loop boundary I don't have any problem.

**Comment by haedri** [comment]
This test is just for the bug to come quicker, of course it's not a real life example.

In my game the cursor changes to indicate weapon is reloading or ready to fire, basically it changes maybe 10 times per minute. The bug appear after about 1 hour of gameplay, and makes the game unplayble then.

As I don't want to wait one hour to reproduce this bug I just made it quicker in this test, but the idea is the same.

**Comment by haedri** [comment]
After digging a bit into the code it seems to me that the problem is that every time setCursorImage is called it creates a new lwjgl Cursor object.
And if I create lots of Cursor objects manually the cursor will disappear.

So it's either a bug in 
- lwjgl: it should be able to handle multiple Cursor creation, but it might be a system limitation
- or in Libgdx implementation: there should be only one cursor per pixmap, maybe Libgdx shouldn't create a Cursor object every time (usiong a cache system or something).

So I'm now creating the Cursor objects myself and call lwjgl functions directly. Everything fine for me doing that.

**Comment by NathanSweet** [comment]
Can you make a PR?

**Comment by MobiDevelop** [comment]
Assumed fixed by referenced PR.
