### ISSUE TITLE
Update to GWT 2.7.0

### ISSUE THREAD

**Issue by badlogic** [libgdx/libgdx#2845]

**Comment by badlogic** [comment]
There seem to be issues with GWT 2.7.0: https://code.google.com/p/google-web-toolkit/issues/detail?id=9006&sort=-id&colspec=ID%20Type%20Status%20Owner%20Milestone%20Summary%20Stars

**Comment by vbousquet** [comment]
Just to share ; I have performed a few test with GWT 2.7.0. The results are the following ;
- I run the gdx tests samples (not all but quite a few at random, testing sound, rendering,...) and everything worked smoothly,
- super dev mode worked like a charm, really better than dev setup with 2.6.0 (perhaps, I did not know how to use it efficiently, though), still need to really experiment with it,
- the compile time is not that long (did not encountered the issue pointed in previous post), it is really fast with incremental compiling,
- you need to add `<set-configuration-property name='xsiframe.failIfScriptTag' value='FALSE' />` in your own module gwt defintion file to bypass a blocking error regarding js script for sound (which are injected anyway, so sound works fine)
- you get a really better jdk emulation for String for example, which is nice

I will continue developing with it and report any failure if any.

**Comment by MobiDevelop** [comment]
The compile times are pretty good with the Eclipse plugin. The Gradle
builds, on the other hand, are very very slow.

**Comment by Namek** [comment]
@vbousquet How are your tests on this update? Have you maybe tried `2.8.0-beta1`?

**Comment by vbousquet** [comment]
I moved my setup to gradle and therefore moved back to 2.6 so no more testing on this issue on my side. Sorry.

**Comment by Namek** [comment]
@vbousquet Could you provide me with some guide on how to update to 2.7?

**Comment by tnttrent** [comment]
How did you set up your project for Gwt 2.7.0? Did you have to rebuild the gwt backend? Many thanks.

**Comment by vbousquet** [comment]
By the time, I posted here, I was using Eclipse IDE. In Eclipse, it is fairly straight forward to switch to 2.7 : you just select it in the option.

For Gradle build, this is specified in the build.gradle in: `gwtVersion='2.7.0'`

I do not have any runnable setup for testing this. So I can not provide that much help. Sorry

**Comment by aliasaila** [comment]
FWIW, I've found that with gradle only the optimized build is considerably slower. draftCompile is about the same.

**Comment by czyzby** [comment]
`2.6.1` compilation time seems normal, I don't know why `2.6.0` is used over `2.6.1` in `gdx-setup`. When using `2.7.0` `superDev` task is still OK, the compilation speed seems to be about the same as older versions (or - at the very least - it's not that noticeable). `dist` task does take longer to finish, though.

`2.8.0-beta1` fails to compile using current GWT backend libs - one would have to build `gdx-backend-gwt` using `2.8.0-beta1` to check if it works, I'm afraid. (There might be some GWT classes refactored here and there, as the compiler seems to complain about unknown types.)
