### ISSUE TITLE
BitmapFont.markupEnabled not read from skin json file

### ISSUE THREAD

**Issue by guillaume-alvarez** [libgdx/libgdx#2848]
In my project I want some labels only to accept the color markup format (not to both with it when not required). So I defined a specific `BitmapFont` to be used in a specific `LabelStyle`:

```
	com.badlogic.gdx.graphics.g2d.BitmapFont: {
		default-font: { file: irisUPC.fnt },
		// setting markupEnabled does not work here
		colored-font: { file: irisUPC.fnt, markupEnabled: true },
	},
```

The issue is `markupEnabled: true` is ignored.

It guess the issue happens because in `Skin` class the json<->`BitmapFont` serializer is replaced by a specific one that reads a few some hard-coded fields. Would it be possible to keep usual serializer behavior for other fields such as markupEnabled?

I encountered the issue only with markupEnabled but it could also happen to other future fields.

**Comment by davebaol** [comment]
It works now :smile:
