### ISSUE TITLE
allow creating AssetManager without default loaders

### ISSUE THREAD

**Issue by FyiurAmron** [libgdx/libgdx#2855]
currently both of the base class constructors available forcibly set the loaders, as a result API doesn't allow any way of creating AssetManager without the default set of loaders.

proposed solution:
```java
	/** Creates a new AssetManager with all default loaders. */
	public AssetManager () {
		this(new InternalFileHandleResolver());
	}

	/** Creates a new AssetManager with with all or no default loaders. */
	public AssetManager (boolean setDefaultLoaders) {
		if ( setDefaultLoaders )
			setDefaultLoaders(new InternalFileHandleResolver());
		executor = new AsyncExecutor(1);
	}

	/** Creates a new AssetManager with all default loaders. */
	public AssetManager (FileHandleResolver resolver) {
		setDefaultLoaders(resolver);
		executor = new AsyncExecutor(1);
	}

	private void setDefaultLoaders (FileHandleResolver resolver) {
		setLoader(BitmapFont.class, new BitmapFontLoader(resolver));
		setLoader(Music.class, new MusicLoader(resolver));
		setLoader(Pixmap.class, new PixmapLoader(resolver));
		setLoader(Sound.class, new SoundLoader(resolver));
		setLoader(TextureAtlas.class, new TextureAtlasLoader(resolver));
		setLoader(Texture.class, new TextureLoader(resolver));
		setLoader(Skin.class, new SkinLoader(resolver));
		setLoader(ParticleEffect.class, new ParticleEffectLoader(resolver));
		setLoader(PolygonRegion.class, new PolygonRegionLoader(resolver));
		setLoader(I18NBundle.class, new I18NBundleLoader(resolver));
		setLoader(Model.class, ".g3dj", new G3dModelLoader(new JsonReader(), resolver));
		setLoader(Model.class, ".g3db", new G3dModelLoader(new UBJsonReader(), resolver));
		setLoader(Model.class, ".obj", new ObjLoader(resolver));
	}
```

**Comment by NathanSweet** [comment]
Setting your own and overriding the defaults isn't enough?

**Comment by FyiurAmron** [comment]
In current implementation, the loaders still have to be created, which forces the programmer to have about 50 objects created, including `JsonReader` & objects allocated by it, to spend both CPU & memory on them, regardless of the fact if he will use them or not. I seriously doubt if many people use more than about of half of them, by the way. Forcing an API user to do things he doesn't want to when there is no real need to do so is hardly a good idea IMO.

Also, I see no possible downside in creating a constructor allowing creation with no defaults.

On the other hand, existing coupling between AssetManager and related classes prevents solving this by reimplementing the manager.

**Comment by nooone** [comment]
I'd say that most people actually use more than half ot the loaders. And I think that 99.9% of the libgdx devs don't want to use their own loaders for the "default" classes or care about setting them themselves.

I doubt that the creation of about 15 loaders is really noticable, neither via CPU, nor memory, but that one additional constructor also won't hurt anyone.

Maybe if you create a PR to this, it will have higher chances. :)

**Comment by NathanSweet** [comment]
What would be needed so GWT's tree shaking discards all the loader classes (and all the classes they use)? Is it enough to move them into a constructor that is never called?

**Comment by xoppa** [comment]
We'd have to test it for GWT. But afaik at least proguard and robovm (agressive) do remove code/classes based on the actual (constructor) call.
