### ISSUE TITLE
Sound doesn't loop on Android

### ISSUE THREAD

**Issue by arg0d** [libgdx/libgdx#2860]
Sound sound = Gdx.audio.newSound("Sounds/sound.wav");
long soundId = sound.play();
sound.setLooping(soundId, true);

This code works fine on desktop, but the sound doesn't loop on Android.

**Comment by MobiDevelop** [comment]
Needs more information...

What version of libgdx?
What version of Android?

Please provide a sample file which doesn't loop.

**Comment by gamingchris3** [comment]
Gdx version: 1.2.0
Android version: 4.2.2
Sound file (400kb): https://www.mediafire.com/?b80ee4zpovxxexl

**Comment by Tom-Ski** [comment]
This is an Android issue afaik.  I think @badlogic looked into this before, but I don't think there is much we can do while still using SoundPool.  You should have better luck setting the loop boolean in the play method though.

**Comment by StanDem** [comment]
I can confirm it doesn't work on some devices. Gdx version 1.5.6.
Android 4.3, sound.loop() plays only once.

**Comment by Tom-Ski** [comment]
Can't do much about this our side, closing it out.
