### ISSUE TITLE
FileHandleResolver for model asset loaders

### ISSUE THREAD

**Issue by mk1x86** [libgdx/libgdx#2861]
The G3dModelLoaders use JsonReader/UBJsonReader. I wrote my own FileHandleResolver and now the Modelloaders search in the wrong place. I guess the json readers need the resolvers as well? At least they get files passed to in the loader and look at the wrong place.

**Comment by xoppa** [comment]
No, the json readers don't need to resolve any files. Please include enough information to reproduce the issue you're reporting. https://github.com/libgdx/libgdx/wiki/Getting-Help

**Comment by xoppa** [comment]
Closing this. If you still think that this is an issue then please provide the requested information and we'll reopen.

**Comment by mk1x86** [comment]
will do. for now I've found another solution. :)
