### ISSUE TITLE
GLSurfaceView20API18 seems to be used only on api level <= 10

### ISSUE THREAD

**Issue by jwisniewski** [libgdx/libgdx#2862]
AndroidGraphics.createGLSurfaceView, line near: 131
`if (sdkVersion <= 10 && config.useGLSurfaceView20API18) {
	GLSurfaceView20API18 view = new GLSurfaceView20API18(application.getContext(), resolutionStrategy);`

Shouldn't be `sdkVersion >= 18 && config.useGLSurfaceView20API18`? I think we don't need API18 implementation of surface view on device with sdk version <= 10:) 

Moreover, if I understand this piece of code correctly and if currently everything work well, it seems we don't need GLSurfaceView20API18 at all, currently it is not used. Am I correct?

libGDX version: up to 1.5.4
Affected classes: AndroidGraphics, AndroidGraphicsLiveWallpaper

**Comment by davebaol** [comment]
If you have to move the gl surface view to different layouts you gets weird system errors on Android 2.2 and 2.3 unless you use GLSurfaceView20API18.

**Comment by jwisniewski** [comment]
Yeah, GLSurfaceView20API18 means: based on original GLSurfaceView from android API18. Initially I got is as a GLSurfaceView which should be used on devices with API18 and newer.

Everything is OK!! I'm closing the issue.
