### ISSUE TITLE
NoSuchMethodError: java.nio.xxxBuffer.rewind() on iOS [RoboVM bug?]

### ISSUE THREAD

**Issue by FyiurAmron** [libgdx/libgdx#2865]
On bleeding-edge libGDX 1.5.5-SNAPSHOT + RoboVM 1.0.0-SNAPSHOT trying to e.g. use `.rewind()` or `limit()` on *any* of the java.nio.Buffer subclass objects causes a `java.lang.NoSuchMethodError: java.nio.xxxBuffer.rewind()Ljava/nio/xxxBuffer;` - on my setup I'm able to replicate the the issue with a libGDX app stub with by simply creating any buffer any trying to rewind it.
```java
IntBuffer ib = BufferUtils.newIntBuffer(16);
ib.rewind(); // killer line
FloatBuffer fb = FloatBuffer.allocate(16);
fb.limit(0); // ditto
```
Tests were done on iOS Simulator - iPhone 4s / iOS 8.3; I haven't a provisioned iOS device available currently to verify this on real iOS.

RoboVM docs clearly show that those Buffer classes should be present, as well as the `.rewind()` method. Note that this also happened when trying RoboVM 1.0.0-alpha-01, 0.0.14.1, 0.0.8.1, libGDX 1.5.4, 1.0.0 etc., so it seems it's not a regression of any kind.

Since using FloatBuffer.allocate(16) is causing the same bevahiour, it's probably RoboVM related and not directly concerning libGDX - yet can anyone verify/check if he's able to repro it too and/or have any insight why does this happen?

**Comment by Tom-Ski** [comment]
Cant reproduce on simulator or device. Try wiping your robovm cache.

**Comment by FyiurAmron** [comment]
Issue was caused by compiling with EA JDK 1.9; using it made the code *not* runnable on pre-1.9 JRE's even with source/target set to 1.6; I wonder if it's just a EA 1.9 quirk, or a behaviour that will persist in the release channel.
