### ISSUE TITLE
Change Image's region size does not affect the Image's dimensions.

### ISSUE THREAD

**Issue by Omegas7** [libgdx/libgdx#2866]
Have this image

![square](https://cloud.githubusercontent.com/assets/4350848/6309075/43ca0c14-b90f-11e4-90c2-5d17726072e6.png)

Create an `Image` object using a `TextureRegion` that is `200x200`. This image is displayed properly.

Now I only want to display the red square. In other words, I should change the `Image`'s `TextureRegion`'s width and height to 100.

    ((TextureRegionDrawable)image.getDrawable()).getRegion().setRegion(0, 0, 100, 100);

This is what I get:

![screen shot 2015-02-20 at 11 26 22 am](https://cloud.githubusercontent.com/assets/4350848/6309081/57257b72-b90f-11e4-9408-8587b3492a0e.png)

Clearly, the region **DID** change as expected. However, the `Image` still thinks it is 200x200, so it is scaling up the red square to fill the space.

According to https://code.google.com/p/libgdx/issues/detail?id=789, you have to call `pack()` afterwards:

    image.pack();

But nothing changes.

The image still thinks it is 200x200.

-----

A solution is to create a brand **new** `TextureRegionDrawable` object and use `setDrawable()`. However, I'd rather not create a new drawable if I could simply modify its properties instead.

**Comment by NathanSweet** [comment]
Image stores its width/height separately from the drawable, so you can just size the image to 100,100. `pack` will size the image to its pref width/height, which uses the min width/height from the TextureRegionDrawable. TextureRegionDrawable stores its min width/height when created, so you need to set that to 100,100 if you want to use `pack`.
Change the size of the Image to 100x100.

**Comment by xoppa** [comment]
Looks like mixing potato's with asset size pixels (http://blog.xoppa.com/pixels). Anyways, this is an issue tracker, use the forum or irc if you need help how to do things: https://github.com/libgdx/libgdx/wiki/Getting-Help

**Comment by Omegas7** [comment]
I did change the image's size.

`image.setWidth(100)` and `image.setHeight(100)` were called before `pack()`.

**Comment by NathanSweet** [comment]
`pack` set it back to 200,200. See my previous message (and also xoppa's message :) ).

**Comment by Omegas7** [comment]
Ah, yes. Sorry. Thanks for the reply.
