### ISSUE TITLE
Match Object Ids between Tiled and libgd

### ISSUE THREAD

**Issue by Kuhmaus** [libgdx/libgdx#2873]
In the latest Tiled Version(11.0) unique Ids got added to objects.
These Ids however are not the ones you get when you use
"map.getObjects().get(id)"
For example
map.getObjects().get(1)
returns the object with the unique tiled Id of 35 in my case.

It would be nice if these ids would be consitent between libgdx and tiled

**Comment by MobiDevelop** [comment]
Pull Requests welcome. Otherwise, it will take us time to evaluate and inplement support for new features in Tiled.

**Comment by MobiDevelop** [comment]
Alrighty, after having a look, I don't think we will implement as you propose where `MapObjects#get(int)` takes the MapObject id. We can certainly grab that id from the elements in the tmx file and put it into the properties.
