### ISSUE TITLE
Modify networking API to return promise

### ISSUE THREAD

**Issue by avianey** [libgdx/libgdx#2874]
Would it be possible to change networking API to return something like promise (like Future<T> in java) so we can better control requests lifecycle.

```
Promise<HttpResponse> Gdx.net.sendHttpRequest(httpRequest, httpResponseListener)
```

instead of void ???
What do you think ?

**Comment by nooone** [comment]
API-wise I think this would be a weird approach since now there will suddenly be two different ways to retrieve the response.

Only having a `Future` though that one needs to/can poll via `isDone()` might be useful in some cases, but in others a callback would be better.

I think if you want to work with a Future, you might create a `HttpResponseListenerFuture` class that you pass in as usual, but that can also be used as a Future afterwards?

**Comment by avianey** [comment]
HttpResponseListenerFuture is a good idea, I will give it a try. But Is Future working on all platform ? IOS, GWT ? Should we provide a Gdx implementation of that ?

**Comment by MobiDevelop** [comment]
Java's Future is not available in GWT, due to no threading.

**Comment by avianey** [comment]
That's why we might need a Gdx wrapping to have a unified API for Future ? what do you think ?
GWT future won't be blocking on get() as they will be already done!

**Comment by MobiDevelop** [comment]
Well, you are certainly able to emulate Future in your project if you are going to make a `HttpResponseListenerFuture` class. If we aren't going to be adding that, there is no need for us to emulate it in the backend. I'd rather not lie about supporting threading things when possible - so would favor not adding it to the standard emulation.

**Comment by avianey** [comment]
for those interrested, it works well :
```java
public class HttpResponseListenerFuture implements Net.HttpResponseListener, Future<Boolean> {

    private final Net.HttpResponseListener listener;
    private volatile Boolean result;

    public HttpResponseListenerFuture(Net.HttpResponseListener listener) {
        this.listener = listener;
    }

    @Override
    public boolean cancel(boolean mayInterruptIfRunning) {
        return false;
    }

    @Override
    public boolean isCancelled() {
        throw new UnsupportedOperationException();
    }

    @Override
    public boolean isDone() {
        return result != null;
    }

    @Override
    public synchronized Boolean get() throws InterruptedException, ExecutionException {
        try {
            wait();
        } catch (InterruptedException e) {}
        return result;
    }

    @Override
    public Boolean get(long timeout, TimeUnit unit) throws InterruptedException, ExecutionException, TimeoutException {
        throw new UnsupportedOperationException();
    }

    @Override
    public synchronized void handleHttpResponse(Net.HttpResponse httpResponse) {
        if (listener != null) {
            listener.handleHttpResponse(httpResponse);
        }
        result = true;
        notifyAll();
    }

    @Override
    public synchronized void failed(Throwable t) {
        if (listener != null) {
            listener.failed(t);
        }
        result = false;
        notifyAll();
    }

    @Override
    public synchronized void cancelled() {
        if (listener != null) {
            listener.cancelled();
        }
        result = false;
        notifyAll();
    }
}
```

**Comment by nooone** [comment]
Didn't you want it to be a `Future<HttpResponse>` instead? Plus, if you add the `HttpRequest` as a parameter you would also be able to implement `cancel()` and `isCancelled()`.
