### ISSUE TITLE
JsonReader does not process strings with simple quotes and forward slashes

### ISSUE THREAD

**Issue by anserran** [libgdx/libgdx#2876]
Found a little bug in JsonReader. Code reproducing the issue (tested in master branch):

```java
    public static void main(String args[]){
        JsonReader json = new JsonReader();
        json.parse("{a: 'hello'}"); // OK
        json.parse("{a: 'http://www.google.es'}"); // Exception
    }
```
Exception launched:
```java
Exception in thread "main" com.badlogic.gdx.utils.SerializationException: Error parsing JSON, unmatched brace.
```

**Comment by NathanSweet** [comment]
Single quotes are not valid JSON. Even with JsonReader, which is quite liberal parsing, single quotes are not for quoting string values.

See `JsonWriter#OutputType#minimal`. Your value contains `//` so it needs to be double quoted. I will update the javadoc to say "double quote" instead of just "quote".

**Comment by anserran** [comment]
I found the issue because I had a file with this value and this used to work in 1.4.1. Or so I thought, because after checking, it seems that the parsed string contained the simple quotes, which is wrong. Sorry about that. For sure, it is more consistent always use double quotes.

By the way, I think you committed my test to Json to FileWriter :)

**Comment by NathanSweet** [comment]
Aye, fixed.

Yeah, the single quotes get included in the value due to JsonReader's ability to parse values without quotes. Maybe a strict JSON mode would be nice, but it hasn't been needed so far.
