### ISSUE TITLE
TimSort verification from run length

### ISSUE THREAD

**Issue by cdomville** [libgdx/libgdx#2877]
See https://bugs.openjdk.java.net/browse/JDK-8072909 and http://envisage-project.eu/proving-android-java-and-python-sorting-algorithm-is-broken-and-how-to-fix-it/ for more details, but the OpenJDK implementation has changed TimSort, as noted at http://hg.openjdk.java.net/jdk9/jdk9/jdk/rev/e276aa5b8a4b to fix an ArrayIndexOutOfBoundsException with worst case long arrays that relates to the number of invariants. I know this is minor, but so we're consistent with the JVM, this should probably be updated for consistency reasons as well.

**Comment by NathanSweet** [comment]
Very interesting! Any chance you can send a PR? Keep in mind that OpenJDK is GPL, so it must not be used as a reference to copy the fix or any other code from. Code can be written yourself of course, come from Android (Apache 2, same as libgdx), or other compatible sources.

**Comment by cdomville** [comment]
The Java TimSort bug repo linked in the blog post has Apache licensing, so I'm assuming the quoted fix in the blog post (to mergeCollapse()) is licensed in the same manner because of this change, so that's what I'll implement.
