### ISSUE TITLE
No glUniform*iv in ShaderProgram

### ISSUE THREAD

**Issue by mujjingun** [libgdx/libgdx#2878]
Cannot set data of int arrays in shader.
Also, why is the shader handle private? If I can't use glUniform*iv in ShaderProgram, I have to make direct calls. Making the shader handle private doesn't help that.

If this sounded rude, I'm sorry. I'm not good at making English sound polite, since I'm not a native speaker.

**Comment by xoppa** [comment]
I guess that adding a getter for the handle doesn't harm if you can provide a valid use-case. But afaik you don't need the handle to set uniforms using direct gl calls.

Also, I don't see why you can't set data of int arrays in shader.

Please provide enough information required to reproduce the issue you're reporting. See also https://github.com/libgdx/libgdx/wiki/Getting-Help

**Comment by xoppa** [comment]
Closing this. If you still think that this is an issue then please provide the requested information and we'll reopen.
