### ISSUE TITLE
size accessor for PooledLinkedList

### ISSUE THREAD

**Issue by Metaphore** [libgdx/libgdx#2879]
Seems there is no way to know PooledLinkedList size or check existence of next element.
So why not to add such methods?

**Comment by GreenLightning** [comment]
A size method seems useful.

The list can be iterated using this pattern, making the check for a next element not necessary:

    iter();
    T element = null;
    while ((element = next()) != null) {}

However, this idiom does not support null elements in the list. Therefore either the add method should throw an IllegalArgumentException if passed a null element or the iteration process should be replaced.
