### ISSUE TITLE
FreeTypeFontGenerator padding support?

### ISSUE THREAD

**Issue by manabreak** [libgdx/libgdx#2882]
Correct me if I'm wrong, but I couldn't find any padding parameters for FreeTypeFontGenerator. As it currently is, the textures bleed from glyph to glyph, causing artifacts in light-colored text.

**Comment by nooone** [comment]
`FreeTypeFontGenerator.generateFont(...)` takes a `FreeTypeFontParameter` as well. That has an optional `PixmapPacker` which has a setting `int padding` that will probably solve your problem.

**Comment by manabreak** [comment]
@nooone Thanks for the suggestion. I tried that, but it causes the `FreeTypeFontGenerator` to not create the texture regions, which in turn leads to `NullPointerException`.

**Comment by MobiDevelop** [comment]
By default, FreeTypeFontGenerator uses padding of 2 pixels around glyphs. If you need something else, you should provide the packer. If it didn't work when you provided the packer, you must have done something incorrectly.

**Comment by nooone** [comment]
@manabreak Please post a full stacktrace for that `NullPointerException` that you've encountered.

As @MobiDevelop already said, there should be padding by default and it is configurable. Either please post a working code example of your problem, or we won't be able to help you here and have to close this issue.

**Comment by NathanSweet** [comment]
#2980 seems to be the same issue but with a better description and example code, so we'll continue discussion there.
