### ISSUE TITLE
TexturePacker.isModified() always returns true when called by TexturePacker.processIfModified()

### ISSUE THREAD

**Issue by voidburn** [libgdx/libgdx#2883]
At https://github.com/libgdx/libgdx/blob/90ce4b6f19c4e1960786544b81f779541eb5d4da/extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/TexturePacker.java#L628 the method checks whether the file exists, and then tries to establish if it's actually outdated. It never accomplishes its task since it tries to look in the filesystem for:

`packFullFileName += packFileName;`

Problem is, the packFileName passed to the method `processIfModified` is not meant to contain either the `.atlas` or `.png` extension but the name with which the various files will be generated (for example, a string "tiles" will produce two files: tiles.atlas and tiles.png with default settings).

Since a packaged resource will always generate a `.atlas` file (settings might dictate a different image format maybe?) I would suggest to append such extension to the `packFileName` string before concatenating it with the full path, unless this is used somewhere else, in which case I'd say we need a specialized method to satisfy `TexturePacker.processIfModified()`

**Comment by NathanSweet** [comment]
Hmm. I didn't add the `processIfModified` methods and don't personally use them. Want to submit a PR to fix this? Maybe just add a parameter that is the atlas suffix.

**Comment by voidburn** [comment]
Hi Nate, no need to add a parameter, there's a handy "settings.atlasExtension" that I see used all across that class that could be simply added to that filename, putting in a parameter would split the variable in two places if someone does use a custom extension.

I don't have the sources at hand, but I will look into it later tonight.
