### ISSUE TITLE
BitmapFont markup crashes if String is just "["

### ISSUE THREAD

**Issue by AzmiTerato** [libgdx/libgdx#2886]
Im using latest nightlies,

BitmapFont.drawWrappedText crashes if I just pass "[" as the string to draw.

Exception in thread "LWJGL Application" java.lang.StringIndexOutOfBoundsException: String index out of range: 2
	at java.lang.String.charAt(Unknown Source)
	at com.badlogic.gdx.graphics.g2d.TextMarkup.parseColorTag(TextMarkup.java:75)
	at com.badlogic.gdx.graphics.g2d.BitmapFontCache.addToCache(BitmapFontCache.java:421)
	at com.badlogic.gdx.graphics.g2d.BitmapFontCache.addWrappedText(BitmapFontCache.java:737)
	at com.badlogic.gdx.graphics.g2d.BitmapFont.drawWrapped(BitmapFont.java:307)
.....

**Comment by davebaol** [comment]
It works for me. Please, provide a [SSCCE](http://sscce.org/) reproducing your issue.

**Comment by MobiDevelop** [comment]
It does crash for me... Here's a modified BitmapFontTest.

```java
package com.badlogic.gdx.tests;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.tests.utils.GdxTest;

public class BitmapFontTest extends GdxTest {
	private SpriteBatch spriteBatch;
	private BitmapFont font;

	@Override
	public void create () {
		spriteBatch = new SpriteBatch();
		font = new BitmapFont(Gdx.files.internal("data/verdana39.fnt"), false);
		font.setMarkupEnabled(true);
		font.setColor(Color.RED);
	}

	@Override
	public void render () {
		Gdx.gl.glClearColor(1, 1, 1, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		
		spriteBatch.begin();
		font.drawWrapped(spriteBatch, "[", 100, 100, 100);
		spriteBatch.end();
		
	}

	@Override
	public void dispose () {
		font.dispose();
		spriteBatch.dispose();
	}
}
```

That said, if markup is enabled, technically you are supposed to escape the '[' as '[['. When not drawwing wrapped, you can not escape and it doesn't crash.

The problem looks to be in the BitmapFont#computeVisibleGlyphs method which doesn't correctly handle this case because it overshoots the end of the string (see line 519, where it increments index whether we've hit the end of the string or not).

**Comment by davebaol** [comment]
Oh right, I missed the part where the OP mentioned `drawWrappedText`.
So I've tested "[" in a `TextField` and it just worked. My bad, sorry. 

That said, I'll look into @NathanSweet 's PR to see how color markup implementation has changed and how to fix this issue. Thanks for your analysis, @MobiDevelop .

**Comment by davebaol** [comment]
Thanks Nate
