### ISSUE TITLE
Model created from mesh does not correctly use texcoords from the mesh it contains

### ISSUE THREAD

**Issue by crehop** [libgdx/libgdx#2887]
Why would a mesh render something different then a model..here is the code used to Call the render of each object. One calling the model, the other the mesh.

[code]	        		
modelBatch.render(terrain.getTerrainChunk(x, y).getModelInstance(),env);
terrain.getTerrainChunk(x, y).getModelInstance().model.meshes.get(0).render(Lighting.getShader(), GL20.GL_TRIANGLES);
[/code]

Expected output = The same thing since they are the same mesh
Actual output =
[img]
http://static.dyp.im/0bp089Ycx1/36c64a7a11e5622609098b97318970c8.png
[/img]

As we can see, the same mesh does not produce the same texture. the models are exactly the same except the top is 9 stacked on top of eachother and the bottom is 9 spread out. (didnt want to waste time positioning them, just testing the shader)

Here is an image of the texture used.
http://static.dyp.im/5kbpk8OY5n/5c8ae6ca7283da3e953b5a0252646b23.png

Oddly the erroneous model is using the 1,1 texcoord leading me to believe there is maybe a math error when creating the texcoords, resulting in a coord over 1 or 1?

Almost forgot the mesh creation code

Mesh mesh = new Mesh(true, chunk.vertices.length / 9, chunk.indices.length,
	    			        new VertexAttribute(VertexAttributes.Usage.Position, 3, ShaderProgram.POSITION_ATTRIBUTE), 
	    			        new VertexAttribute(VertexAttributes.Usage.Normal, 3, ShaderProgram.NORMAL_ATTRIBUTE),
	    			        new VertexAttribute(VertexAttributes.Usage.ColorPacked, 4, ShaderProgram.COLOR_ATTRIBUTE), 
	    			        new VertexAttribute(VertexAttributes.Usage.TextureCoordinates, 2,  ShaderProgram.TEXCOORD_ATTRIBUTE));
	    			mesh.setVertices(chunk.vertices);
	    			mesh.setIndices(chunk.indices);
	    			Model result = ModelBuilder.createFromMesh(mesh, GL20.GL_TRIANGLES, material);

**Comment by xoppa** [comment]
This is a issue tracker, please use the forum or irc if you need help, see: https://github.com/libgdx/libgdx/wiki/Getting-Help.

**Comment by crehop** [comment]
but this is an issue? the mesh and model for some reason don't share the same texcoords its an issue with the Model class

**Comment by xoppa** [comment]
The Model class doesn't care about texture coordinates. What exactly is the issue you are reporting? Please include the information required to reproduce the issue, see http://sscce.org/.

**Comment by xoppa** [comment]
Although it's probably unrelated, the `ModelBuilder.createFromMesh` method is deprecated and should not be used.

**Comment by crehop** [comment]
Sorry xoppa, don't mean to waste anyones time, im new to reporting coding issues. 

Steps to reproduce,

1.Create a mesh with texcoords
2.Create a model with that mesh (I actually put in nodes, nodeparts, and meshparts together before using the createFromMesh as a hope to fix the issue.
3.Render the mesh
4.Render the model

Outcome, and the bug
Model texture will only be to bottom right pixel of the supplied texture
Mesh texture will work as intended.


Creating consice code to do this will be several hundered lines long as you have to construct the mesh and input all the cords, but I have supplied my code you can just run at the bottom, Terrain and TerrainChunk.java are where the terrain is assembled and zomtasia is the main class where it is render called.

Heres some code you can just import and run  as desktop launcher to see the issue firsthand
https://github.com/crehop/core

Lastly, where does the model pull texcoords from? It cant be the mesh, because I debugged and it is listing all the texcoords correctly.

**Comment by xoppa** [comment]
Please include the information required to reproduce the issue, see http://sscce.org/.

**Comment by crehop** [comment]
Alright, but in the mean time can you take a look at how texcoords are assigned to a model from a mesh, there is an error in it somewhere! creating a model from a mesh and rendering both results in 2 different things... one with a correctly applied texture and one with an erroneous texture EVEN THOUGH the mesh is the same. its in the render pipeline somewhere. Ill try to put some code together for you, will take me a few hours.

**Comment by xoppa** [comment]
Like said, model doesn't care about texture coordinates. There's nothing to assign. Whatever mesh you provide to it is what it will contain.

**Comment by crehop** [comment]
material = new Material(TextureAttribute.createDiffuse(grass));
		float[] verticies = new float[]{
				// Front face
				//X    ,  Y     ,   Z    ,  U , V
				-100.0f, -100.0f,  -100.0f, 0f, 0f,
				 100.0f, -100.0f,  -100.0f, 0f, 1f,
				 100.0f,  100.0f,  -100.0f, 1f, 1f,
				-100.0f,  100.0f,  -100.0f, 1f, 0f,
		 };
		 short[] indices = new short[]{
				 0,  1,  2,     0,  2,  3,
		 };
		Mesh mesh = new Mesh(true, verticies.length / 5, indices.length,
				new VertexAttribute(VertexAttributes.Usage.Position, 3, ShaderProgram.POSITION_ATTRIBUTE),
		        new VertexAttribute(VertexAttributes.Usage.TextureCoordinates, 2,  ShaderProgram.TEXCOORD_ATTRIBUTE));
		mesh.setVertices(verticies);
		mesh.setIndices(indices);
		
		result = ModelBuilder.createFromMesh(mesh, GL20.GL_TRIANGLES, material);
		modelInstance = new ModelInstance(result, 0,0,-140);


Create this model  and render it It's only 1 side of a cube for simplicity's sake.
Rendering this, it will only use texcoord 0,0 even though the coords supplied are correct for the whole texture. If you change the top left pixel of your texture, it will also change on the model..

**Comment by xoppa** [comment]
Please include the information required to reproduce the issue, see http://sscce.org. That includes a runnable test (single class) and any assets needed if applicable.

Did you actually test this code? Without specifying the unit for the texture coordinate it won't render at all with the default shader. Apart from that (and using very large units for the coordinates) it runs fine for me.

**Comment by crehop** [comment]
"Without specifying the unit for the texture coordinate it won't render at all with the default shader."
can you explain what you mean here the texcoord is the last 2 in those correct??
 (0,0 0,1 1,1 and 1,0 in the vertex array)

I tested this, and it works for me but the texture is a single pixel worth of color not the actual texture
I am rendering it in a modelBatch 

modelBatch.render(modelInstance);

Ill try to put together a single runnable class asap, but I don't know how long it will take.
Im really sorry for being a noob about this.

**Comment by xoppa** [comment]
It means that you should specify the unit, like:

    new VertexAttribute(VertexAttributes.Usage.TextureCoordinates, 2,  ShaderProgram.TEXCOORD_ATTRIBUTE + "0", 0));

**Comment by crehop** [comment]
wow... that fixed it... where does it specify that that is how it needs to be done? I'm really sorry about this, I have been trying a while and asking around... ever pointed that out

**Comment by crehop** [comment]
Can we maybe have the VertexAttribute default to that if nothing is supplied?

**Comment by xoppa** [comment]
VertexAttribute doesn't do anything. Apparently you *did* supply an alias which isn't used by your shader (it isn't possible to supply nothing). VertexAttribute contains a helper construct method for each attribute type, including a default alias. It is assumed that if you choose to supply an alias that you want to use that alias (you must have had a reason to use it that way). Anyways, this is not an issue of libgdx, closing this.
