### ISSUE TITLE
How to zoom camera to a tile map

### ISSUE THREAD

**Issue by 60noypearl** [libgdx/libgdx#2890]
I have a tile map which I drew but I see that like as if a view from top. I want to zoom the map and give the impression like you are walking on the tile map - like on the games Gunz,  Counter Strike, BattleField and all the rest that there is a man walking on the map. So how can I zoom to this range?

**Comment by MobiDevelop** [comment]
Please use the forum or irc for questions. This tracker is for reporting issues in libgdx.
