### ISSUE TITLE
Gdx.app.exit() does't work on ios!

### ISSUE THREAD

**Issue by panli32811** [libgdx/libgdx#2896]

**Comment by BlueRiverInteractive** [comment]
You never ever exit an app on ios!

But just for completeness the implementation of exit is wrong on iOS. 
It should probably call `[[NSThread mainThread] exit]`.

**Comment by Tom-Ski** [comment]
Looking into this it looks like Apple really doesn't want you to force close your application.  This may result in application rejections from the App Store, so we should probably do nothing and follow the guide from Apple. I'll change the implementation to exit, but this should really only be used during testing (even then abort is probably better).
