### ISSUE TITLE
ParticleEmitter copy constructor does not copy premultiplied alpha attribute

### ISSUE THREAD

**Issue by cypherdare** [libgdx/libgdx#2900]
I discovered this while trying to use a ParticleEffect that has ParticleEmitters with premultiplied alpha with a ParticleEffectPool.

Not sure why the comment "Backwards compatibility" is used in reference to loading premultiplied alpha state in the `load (BufferedReader reader)`. Is premultiplied alpha not really supported? Premultiplied alpha is super helpful for particle effects. It opens up a lot of possibilities that alpha blending and additive blending don't offer.

**Comment by MobiDevelop** [comment]
This was already fixed:
https://github.com/libgdx/libgdx/commit/80b37dfe893cef4aada205828669cdaad74a55cc

The backwards compatibility note was so files created prior to the addition of premultipliedAlpha could still be loaded.

**Comment by cypherdare** [comment]
Oops! Didn't turn up in my search.
