### ISSUE TITLE
DragAndDrop not working if DragActor is the Source Actor

### ISSUE THREAD

**Issue by bachtrong43** [libgdx/libgdx#2901]
I don't know this is an issue or not, but it's uncomfortable when use DragAndDrop with DragActor set to the Source Actor. At the moment, I have to clone the Source Actor and set it as the DragActor, when DragStart set source actor invisible and visible when DragStop.
```javascript
DragAndDrop dr = new DragAndDrop();
		dr.addSource(new Source(imgCross) {

			@Override
			public Payload dragStart(InputEvent event, float x, float y,
					int pointer) {
				Logger.log("start"); 
				Payload pl = new Payload();
				pl.setDragActor(imgCross);
				return pl;
			}

			@Override
			public void dragStop(InputEvent event, float x, float y,
					int pointer, Payload payload, Target target) {
				super.dragStop(event, x, y, pointer, payload, target);
				Logger.log("stop");
			}
		});
```
With above code, the dragStop is called immediately after 1 call of drag. Because in the removeActor method:
```javascript
public boolean removeActor (Actor actor) {
		if (!children.removeValue(actor, true)) return false;
		Stage stage = getStage();
		if (stage != null) stage.unfocus(actor);
		actor.setParent(null);
		actor.setStage(null);
		childrenChanged();
		return true;
	}
```
When DragActor is added to Stage, it will be removed from stage first, so stage.unfocus will be called:
```javascript
public void unfocus (Actor actor) {
		cancelTouchFocus(actor);
		if (scrollFocus != null && scrollFocus.isDescendantOf(actor)) scrollFocus = null;
		if (keyboardFocus != null && keyboardFocus.isDescendantOf(actor)) keyboardFocus = null;
	}
```
The result is stage will cancel touch focus on dragActor, it makes the DragAndDrop call dragStop after 1 call of drag. Old version of libgdx doesn't have this issue.

**Comment by NathanSweet** [comment]
It seems reasonable to unfocus actors when they are removed. This stops bugs where a removed actor receives a touch up event, which would be tedious to guard against.

Since the remove is done from `Stage#addActor`, the stage actually does know that the actor will be added back and that the listener's touch focus will remain valid. I propose adding a `Group#removeActor(Actor, boolean)` method which only calls `Stage#unfocus` when passed true.
