### ISSUE TITLE
TextField blink and non continuous rendering.

### ISSUE THREAD

**Issue by RotaruDan** [libgdx/libgdx#2905]
Should the TextField's cursor blink with non continuous rendering?

I've realised that requestRendering() isn't called when the cursor is suposed to blink, is this the desired behavior?

(I guess that the same behavior is happening with TextAreas)

**Comment by NathanSweet** [comment]
When using noncontinuous rendering the caret is shown all the time, it
doesn't blink. This is by design, since using noncontinuous rendering means
you probably don't want extra rendering triggered for a simple caret blink.

**Comment by RotaruDan** [comment]
It makes sense and I this it's a good design decision, thank you for the fast response.

Closing.
