### ISSUE TITLE
Sort keys in preferences [desktop]

### ISSUE THREAD

**Issue by mk1x86** [libgdx/libgdx#2911]
I've got quite a few entries in my preferences and sometimes I need to manually edit them (desktop only) for testing purposes. It seems like they're stored in a hashmap and thus not ordered which results in a total mess. I've got a few entries for gamepads, all starting with "controller..." and it'd be nice to see them in order.
I guess this isn't a difficult change since all that has to be done is using an ordered hashmap. Would be nice to have.

**Comment by NathanSweet** [comment]
Submit a PR?

**Comment by mk1x86** [comment]
I'm currently preoccupied and thus cannot build libgdx from source. :-/ Hopefully I'll find some time next month.

**Comment by MobiDevelop** [comment]
Closing this, submit a PR if you want a change.
