### ISSUE TITLE
Images not displaying

### ISSUE THREAD

**Issue by aaryadev** [libgdx/libgdx#2915]
While reading :https://github.com/libgdx/libgdx/wiki/Textures,-textureregion-and-spritebatch
noticed that images are not loading !. Are they removed ?

**Comment by nooone** [comment]
The source images are there. Github replaces `<img src="..." />` and `![](...)` with some kind of proxy:

<img data-canonical-src="http://libgdx.googlecode.com/svn/wiki/img/textures_regions_batch_result_2.png" alt="" src="https://camo.githubusercontent.com/3bf06586ddec6c6db8dc8829bfe6f883c108b722/687474703a2f2f6c69626764782e676f6f676c65636f64652e636f6d2f73766e2f77696b692f696d672f74657874757265735f726567696f6e735f62617463685f726573756c745f322e706e67">

That "https://camo.githubusercontent.com/3bf0658..." returns 404. Seems to be a GitHub issue?

**Comment by Tom-Ski** [comment]
These images are not returning valid cache control headers, specifically there is no 'no-cache'.   Guess we should just move them off google code for an easy resolution.

**Comment by Tom-Ski** [comment]
Aight, fixed.

**Comment by nooone** [comment]
Our wiki's pics are back! Hurray for Tomski! :clap: :tada: :dancer:

:octocat: is proud of you!

**Comment by aaryadev** [comment]
Thanks a lot
