### ISSUE TITLE
libgdx gdx-setup.jar Build failed

### ISSUE THREAD

**Issue by GruchaAP** [libgdx/libgdx#2921]
Hi all,
I have problem with resolving dependencies. Have you guys had similar issue? Any ideas?
thanks in advance

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'test'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find org.robovm:robovm-gradle-plugin:1.0.0-SNAPSHOT.
     Searched in the following locations:
         https://repo1.maven.org/maven2/org/robovm/robovm-gradle-plugin/1.0.0-SNAPSHOT/maven-metadata.xml
         https://repo1.maven.org/maven2/org/robovm/robovm-gradle-plugin/1.0.0-SNAPSHOT/robovm-gradle-plugin-1.0.0-SNAPSHOT.pom
         https://repo1.maven.org/maven2/org/robovm/robovm-gradle-plugin/1.0.0-SNAPSHOT/robovm-gradle-plugin-1.0.0-SNAPSHOT.jar
         https://jcenter.bintray.com/org/robovm/robovm-gradle-plugin/1.0.0-SNAPSHOT/maven-metadata.xml
         https://jcenter.bintray.com/org/robovm/robovm-gradle-plugin/1.0.0-SNAPSHOT/robovm-gradle-plugin-1.0.0-SNAPSHOT.pom
         https://jcenter.bintray.com/org/robovm/robovm-gradle-plugin/1.0.0-SNAPSHOT/robovm-gradle-plugin-1.0.0-SNAPSHOT.jar
     Required by:
         :test:unspecified

**Comment by GruchaAP** [comment]
it works when I uncheck iOS subproject... Have no idea how to fix it

**Comment by badlogic** [comment]
rhanks @tomski, i'm an idiot.

**Comment by GruchaAP** [comment]
thanks for commit. I'm compiling latest version. When will you update .jar which is for download on:
http://libgdx.badlogicgames.com/download.html ?

**Comment by Tom-Ski** [comment]
That is automatically built base on the bleeding edge. Should be good to go.

**Comment by GruchaAP** [comment]
Another little issue:
* What went wrong:
Could not compile build file 'C:\te\test\build.gradle'.
> startup failed:
  build file 'C:\te\test\build.gradle': 255: expecting '}', found '' @ line 255, column 1.
  1 error


when generating

**Comment by Tom-Ski** [comment]
Probably missed it as I rushed it, will have to look when I'm back at home.

**Comment by GruchaAP** [comment]
ok. I'm also looking into code. I've added bracket but not sure if in proper place as I don't know gradle. Now I'm receiving:
* What went wrong:
A problem occurred configuring root project 'test'.
> Could not resolve all dependencies for configuration ':classpath'.
   > You must specify a URL for a Maven repository.

**Comment by cemadil** [comment]
hi there,

I receive the same failure ( org.robovm:robovm-gradle-plugin:1.0.0-SNAPSHOT) when I download the latest setup.jar from http://libgdx.badlogicgames.com/download.html

should I compile from libgdx-master? 

thanks

**Comment by Tom-Ski** [comment]
Latest setup should be fine.

**Comment by GruchaAP** [comment]
Hi, few days ago I compiled gdx-setup with ant.
Target jar is working like a charm

**Comment by cemadil** [comment]
thanks changed 1.0.0-SNAPSHOT to 1.0.0 and it worked as suggested

**Comment by chandujr** [comment]
2.3.0 is not working either. I tried both 2.2.0 and 2.2.1 as well and they are giving the same error messages. I didn't use snapshots.
