### ISSUE TITLE
Sound.play fails on iOS

### ISSUE THREAD

**Issue by badlogic** [libgdx/libgdx#2922]
I assume this has to do with the latest fix regarding preloaded sound effects. Simple to reproduce on both device and simulator:

```java
public class MyGdxGame extends ApplicationAdapter {
	@Override
	public void create () {
		Sound sound = Gdx.audio.newSound(Gdx.files.internal("shotgun.wav"));
		sound.play(1);
	}
}
```

**Comment by ebbybeh** [comment]
Will this fix be available in the latest nightly?

**Comment by badlogic** [comment]
Yes, update to the latest nightlies (delete gradle cache etc.)
