### ISSUE TITLE
tiled object Y property returns wrong value

### ISSUE THREAD

**Issue by chriscamacho** [libgdx/libgdx#2929]
I stumbled onto this myself but noticed it here http://stackoverflow.com/questions/23837533/libgdx-tiled-y-position also

basically object layers objects Y position is returned incorrectly

**Comment by xoppa** [comment]
Please provide enough information to reproduce the issue you're reporting. See also https://github.com/libgdx/libgdx/wiki/Getting-Help.

**Comment by MobiDevelop** [comment]
In libgdx we use an inverted y value to account for the y-up orientation in
libgdx. You are probably not taking that into account.

**Comment by chriscamacho** [comment]
The value returned for the objects Y property is not the one stored in the objects physical Y value in the Y property as viewed in tiled
IE
here omp are the properties returned for an object in the object layer

y = omp.get("y",float.class);  
does NOT get the "Y" value seen in tiled

**Comment by MobiDevelop** [comment]
It isn't supposed to.

**Comment by chriscamacho** [comment]
Some objects are placed correctly their Y values look good, if I invert the Y value, mapheight-Y then the objects are in the wrong place...

**Comment by gjroelofs** [comment]
To give some validity to this:

This happens because any Polygons on the map have their vertices flipped as
well, which makes it a bit harder to translate back again.
I'll push a PR this afternoon which makes flipping the objects on the map a
variable in the parameters.

**Comment by BeWaryOfMiscreant** [comment]
I can confirm that, for an object at 16,16 in a Tiled object layer (and displayed that way in the Tiled editor)

libgdx's mapProperties.get("x", Float.class) will return 16.
mapProperties.get("y", Float.class) will return something that depends on the height of the map.

The solution is:

y = mapHeight - tilesize - y;

as elucidated here.
http://badlogicgames.com/forum/viewtopic.php?t=7723&p=35259#p35262
