### ISSUE TITLE
Label wrong height, alignment (when use bitmapfont create by Shoebox) 

### ISSUE THREAD

**Issue by ldthai** [libgdx/libgdx#2931]
I create BitmapFont with lineHeight=90
But i create label then label height=216
if i set label height to 90 then text draw to out of label bound 
and label.setAlignment(Align.center) not work

how to label height = BitmapFont lineHeight ? and how to setAlignment(Align.center) work?

this is my @font_dialog_title.fnt file:

info face="@font_dialog_title" size=32 bold=0 italic=0 charset="" unicode=0 stretchH=100 smooth=1 aa=1 padding=0,0,0,0 spacing=0,0
common lineHeight=90 base=26 scaleW=216 scaleH=258 pages=1 packed=0 alphaChnl=1 redChnl=0 greenChnl=0 blueChnl=0
page id=0 file="@font_dialog_title.png"
chars count=10
char id=71 x=75 y=88 width=72 height=88 xoffset=0 yoffset=2 xadvance=72 page=0 chnl=0 letter="G"
char id=65 x=147 y=88 width=67 height=87 xoffset=0 yoffset=3 xadvance=67 page=0 chnl=0 letter="A"
char id=77 x=0 y=0 width=87 height=88 xoffset=0 yoffset=2 xadvance=87 page=0 chnl=0 letter="M"
char id=69 x=157 y=0 width=59 height=87 xoffset=0 yoffset=3 xadvance=59 page=0 chnl=0 letter="E"
char id=79 x=87 y=0 width=70 height=88 xoffset=0 yoffset=2 xadvance=70 page=0 chnl=0 letter="O"
char id=86 x=0 y=88 width=75 height=83 xoffset=0 yoffset=3 xadvance=75 page=0 chnl=0 letter="V"
char id=82 x=0 y=171 width=69 height=87 xoffset=0 yoffset=3 xadvance=69 page=0 chnl=0 letter="R"
char id=80 x=69 y=176 width=64 height=82 xoffset=0 yoffset=5 xadvance=64 page=0 chnl=0 letter="P"
char id=32 x=0 y=0 width=0 height=0 xoffset=0 yoffset=0 xadvance=30 page=0 chnl=0 letter=" "
char id=9 x=0 y=0 width=0 height=0 xoffset=0 yoffset=0 xadvance=0 page=0 chnl=0 letter="	"

kernings count=0

thanks!

**Comment by NathanSweet** [comment]
This issue tracker is inappropriate for such questions.
https://github.com/libgdx/libgdx/wiki/Getting-help
