### ISSUE TITLE
Fog error in animated ModelInstance

### ISSUE THREAD

**Issue by massonetto** [libgdx/libgdx#2935]
If i have a animated modelInstance, the fog don't work correctly. Looks like it calculates the postion on [0,0,0] not relative to the camera. In others no animated ModelInstance, it works normally.

**Comment by xoppa** [comment]
Please include the information required to reproduce the issue you're reporting. See https://github.com/libgdx/libgdx/wiki/Getting-Help

**Comment by massonetto** [comment]
I try to reproduce this error in one separate class to send to you. But i can't. I think the error is on my game. Thanks for attention.
