### ISSUE TITLE
Box2D crash

### ISSUE THREAD

**Issue by gamingchris3** [libgdx/libgdx#2936]
Assertion failed!

Program: C:\Program Files (x86)\Java\jre7\bin\javaw.exe
File: /var/lib/jenkins/workspace/libgdx/extensions/gdx-box2d/gdx-box2d/jni/Box2D/Collision/Shapes/b2PolygonShape.cpp, Line 430

Expression: area > 1.19209289550781250000e-7F

This is all it told me. This is one time crash, not even sure if this should be reported here or to JBox2D

**Comment by Darkyenus** [comment]
This is not JBox2D but native Box2D

**Comment by gamingchris3** [comment]
OOopssssssssssssssss I just realized that I was creating a body of size 0. Sorry for the spam.
