### ISSUE TITLE
Unable to use PolyRegion with a TextureAtlas

### ISSUE THREAD

**Issue by MonsterOfCookie** [libgdx/libgdx#2937]
Hey,

I was trying to reduce the draw calls in a prototype I was toying with, by replacing the individual textures with an atlas.

I am currently using a PolygonRegion with the appropriate batch. But unfortunately I can't get it to render my textures from my texture atlas correctly. It appears to a end up rendering the entire sprite sheet.

I have mocked up a really simple example using 1px textures, it can be downloaded from here - https://dl.dropboxusercontent.com/u/13890121/Poly.zip. I render 2 square (or 4 triangles) the one on the right is from a straight up texture the on on the left is the atlas.

I appreciate I may be doing something wrong, this polygon stuff is fairly new to me. But the javadoc does say that the PolygonRegion class does support TextureAtlas'

Cheers

James

**Comment by xoppa** [comment]
Could you include the [minimum code](https://github.com/libgdx/libgdx/wiki/Getting-Help#executable-example-code) (single class) required to reproduce the issue you're reporting? Most rather prefer to copy paste code instead of downloading an unknown zip file.

**Comment by MonsterOfCookie** [comment]
Hi,

Thanks for responding, I appreciate you taking the time. let me show you the sample code, if you will.

```
public class MyGdxGame extends ApplicationAdapter {
   
	PolygonSpriteBatch batch;
	TextureAtlas atlas;
    TextureRegion textureRegion;
    TextureAtlas.AtlasRegion atlasRegion;


	@Override
	public void create () {
		batch = new PolygonSpriteBatch();
        atlas = new TextureAtlas("assets.txt");
        textureRegion = new TextureRegion(new Texture("dark_grey.jpg"));
        atlasRegion = atlas.findRegion("dark_grey");
      
	}

	@Override
	public void render () {
		Gdx.gl.glClearColor(1, 0, 0, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		batch.begin();
        polygon(batch, 0, 0, 100, 0, 100, 100, 0, 100, atlasRegion);
        polygon(batch, 100, 0, 200, 0, 200, 100, 100, 100, textureRegion);
		batch.end();
	}

    private void polygon(PolygonSpriteBatch polygonSpriteBatch,
                         float x1, float y1,
                         float x2, float y2,
                         float x3, float y3,
                         float x4, float y4,
                         TextureRegion textureRegion) {

        float dx2 = x2 - x1;
        float dy2 = y2 - y1;

        float dx3 = x3 - x1;
        float dy3 = y3 - y1;

        float dx4 = x4 - x1;
        float dy4 = y4 - y1;

        PolygonRegion polygonRegion = new PolygonRegion(textureRegion,
                new float[]{
                        0, 0,
                        dx2, dy2,
                        dx3, dy3,
                        0, 0,
                        dx4, dy4,
                        dx3, dy3
                },
                new short[]{0, 1, 2, 3, 4, 5}
        );

        polygonSpriteBatch.draw(polygonRegion, x1, y1);
    }
}
```

The assets are:
![assets](https://cloud.githubusercontent.com/assets/2905478/6659457/f91b6a9a-cbc0-11e4-8823-7808ecab38da.png)
![dark_grey](https://cloud.githubusercontent.com/assets/2905478/6659458/f91f4188-cbc0-11e4-82e0-6c41044e5755.jpg)

```
assets.png
format: RGB888
filter: Nearest,Nearest
repeat: none
dark_green
  rotate: false
  xy: 14, 2
  size: 1, 1
  orig: 1, 1
  offset: 0, 0
  index: -1
dark_grey
  rotate: false
  xy: 17, 2
  size: 1, 1
  orig: 1, 1
  offset: 0, 0
  index: -1
light_green
  rotate: false
  xy: 20, 2
  size: 1, 1
  orig: 1, 1
  offset: 0, 0
  index: -1
light_grey
  rotate: false
  xy: 23, 2
  size: 1, 1
  orig: 1, 1
  offset: 0, 0
  index: -1
red
  rotate: false
  xy: 2, 2
  size: 2, 2
  orig: 2, 2
  offset: 0, 0
  index: -1
white_2
  rotate: false
  xy: 6, 2
  size: 2, 2
  orig: 2, 2
  offset: 0, 0
  index: -1
white
  rotate: false
  xy: 10, 2
  size: 2, 2
  orig: 2, 2
  offset: 0, 0
  index: -1
```

I really do hope it turns out I am doing something wrong!

**Comment by bachtrong43** [comment]
Wrong triangle indices, try to change new short[]{0, 1, 2, 3, 4, 5} to {0,1,2,0,3,2}

**Comment by NathanSweet** [comment]
OP, please verify fix.

**Comment by MonsterOfCookie** [comment]
Hey!

Sorry I missed that previous comment.

Whilst that does mean I render a triangle instead of a square, the problem remains that the entire atlas texture is used in the rendering, of the left triangle, not just the region that was required.

I have worked around this, so this isn't an issue for me anymore.

**Comment by NathanSweet** [comment]
Okie, closing as not an issue. :)
