### ISSUE TITLE
[GWT] HttpResponse.getHeaders() returns null

### ISSUE THREAD

**Issue by JFixby** [libgdx/libgdx#2942]
The goal was to connect to a server from the GWT backend and to exchange some data using HTTP call: https://github.com/libgdx/libgdx/issues/1639

At the step 5: Http call was successfully executed, data submitted to the server from the GWT backend and the code "200 OK" received back.

Code:
```
public class GDXMessageTransport implements HttpResponseListener {
	private static final String GDX_API_PROXY_URL = "http://localhost:18080/gdx-entry-point-proxy/";

//CALL:
	public void establishConnection() {
		HttpRequest httpRequest = new HttpRequest();
		httpRequest.setMethod(HttpMethods.GET);
		httpRequest.setUrl(GDX_API_PROXY_URL);
		Gdx.net.sendHttpRequest(httpRequest, this);
	}

	@Override
	public void handleHttpResponse(HttpResponse httpResponse) {
		L.d("httpResponse", httpResponse);
		HttpStatus status = httpResponse.getStatus();
		L.d("status", status);
		int statusCode = status.getStatusCode();
		L.d("statusCode", statusCode);

		byte[] result = httpResponse.getResult();
		L.d("result", result);
		if (result != null) {
			L.d("result.length", result.length);
		}
		String string_result = httpResponse.getResultAsString();
		L.d("string_result", string_result);
		
		String header_set_cookie = httpResponse.getHeader("Set-Cookie");
		L.d("header_set_cookie", header_set_cookie);
		

		Map<String, List<String>> headers = httpResponse.getHeaders();
		print_map("map", headers);
		throw new Error("EXIT HERE");
	}
	
	private static void print_map(String name, Map<?, ?> value) {
		Set<?> keys = value.keySet();
		Iterator<?> i = keys.iterator();
		L.d("---" + name + "[" + value.size() + "]---");
		int k = 0;
		while (i.hasNext()) {
			Object key = i.next();
			Object val = value.get(key);
			L.d("   [" + k + "] " + key + " :-> " + val);
			k++;
		}
	}

	@Override
	public void failed(Throwable t) {
		t.printStackTrace();
	}

	@Override
	public void cancelled() {
		L.d("cancelled()");
	}

}
```

DesktopOutput:
```
G: httpResponse > com.badlogic.gdx.net.NetJavaImpl$HttpClientResponse@2e6f1b1c
G: status > com.badlogic.gdx.net.HttpStatus@32e920bb
G: statusCode > 200
G: result > [B@7f15be32
G: result.length > 0
G: string_result > 
G: header_set_cookie > JSESSIONID=dfe2e46d4bde2683e774d984d4e0; Path=/gdx-entry-point-proxy; HttpOnly
G: ---map[8]---
G:    [0] Transfer-Encoding :-> [chunked]
G:    [1] null :-> [HTTP/1.1 200 OK]
G:    [2] Server :-> [GlassFish Server Open Source Edition  4.0]
G:    [3] Access-Control-Allow-Origin :-> [*]
G:    [4] Set-Cookie :-> [JSESSIONID=dfe2e46d4bde2683e774d984d4e0; Path=/gdx-entry-point-proxy; HttpOnly]
G:    [5] Date :-> [Sun, 15 Mar 2015 15:12:20 GMT]
G:    [6] Access-Control-Allow-Headers :-> [Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With, Access-Control-Allow-Origin]
G:    [7] X-Powered-By :-> [Servlet/3.1 JSP/2.3 (GlassFish Server Open Source Edition  4.0  Java/Oracle Corporation/1.8)]

```
GwtOutput:
![b1](https://cloud.githubusercontent.com/assets/1580663/6656450/f4209280-cb2b-11e4-8234-a37bd4512007.png)

![b3](https://cloud.githubusercontent.com/assets/1580663/6656559/30334c70-cb2e-11e4-9fb6-13d7f57a73ce.png)

![b2](https://cloud.githubusercontent.com/assets/1580663/6656449/f42091b8-cb2b-11e4-9edb-0ecf80cc7d69.png)

GDX version: 1.5.3
L.d() - is a logger class.

**Comment by MobiDevelop** [comment]
You seem to have CORS misconfigured. Your server should send the "Access-Control-Expose-Headers" header in the response, and list the headers that it is allowing to be read.

**Comment by JFixby** [comment]
Here is the exact line of code that need to be fixed: https://github.com/libgdx/libgdx/blob/master/backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtNet.java#L82

I don't think that re-configuring my (or any other) server would somehow do this.

**Comment by MobiDevelop** [comment]
It works when you don't use CORS, or when you expose the headers. Sorry the browser doesn't work to your liking.

**Comment by JFixby** [comment]
In the line 80 com.google.gwt.http.client.Response returns bad headers. Ok, this is external and has nothing to do with Gdx.

Then gdx-scope starts.
GwtNet receives external object "Header[] responseHeaders". Then at the line 82  it calls .getName() method without checking if the received object is valid.
```
String headerName = responseHeaders[i].getName();
```
Drops exception because of a missing null-check.

**Comment by MobiDevelop** [comment]
Well, arguably - there should be no null items in the array. That is a side-effect of misconfiguration. But we can add a null check.

**Comment by JFixby** [comment]
Ok.

Probably there should be also something like:

```
if (header == null) {
Log.e("Failed to receive headers from com.google.gwt.http.client.Response.");
}
```
So that wouldn't be a mystery of missing headers in the future.

**Comment by MobiDevelop** [comment]
I don't really see any need to differentiate between getting no headers and getting no headers because some underlying library failed to return them.

**Comment by JFixby** [comment]
Well there are two different situations:

1) Server didn't return any headers. So it is ok, and the fixed code works as planned.

2) com.google.gwt.http.client.Response returned garbage output. Something is wrong.

I think here we should form an Exception and pass it to the HttpResponseListener calling the failed() method. So gdx-user can print it and to see the problem:
```
 @Override
    public void failed(Throwable t) {
        t.printStackTrace();
    }
```

Otherwise people will spend lives wondering about empty headers.

**Comment by MobiDevelop** [comment]
Now we are elevating a missing header (due to the browser following the
spec) to failing the entire request? I definitely don't think that's the
right thing to do.

**Comment by JFixby** [comment]
Ok.
