### ISSUE TITLE
Can't find locations of extensions? .dll files in appdata

### ISSUE THREAD

**Issue by David-Solodukhin** [libgdx/libgdx#2948]
In the box2d library, there is a settings file which lets you adjust performance variables such as max vertex count. However, i cannot find this .cpp file anywhere. It is not in libgdx.jar, box2d.jar, etc. I don't know how the "box-2d" class files are loaded through the dll's but i would like to change properties of the box2d extension. How can i do this?

**Comment by MobiDevelop** [comment]
All of the Box2D sources are located in the jni directory here:

https://github.com/libgdx/libgdx/tree/master/extensions/gdx-box2d/gdx-box2d/jni/Box2D

Note, you will have to recompile the box2d native libs for each platform yourself if you change anything in there.

**Comment by David-Solodukhin** [comment]
how do i recompile the native libs? Thank You.

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Building-libgdx-from-source, but you probably don't want to go that road. This is an issue tracker, if you need help on how to accomplish something then use the forum or irc instead. See https://github.com/libgdx/libgdx/wiki/Getting-Help.
