### ISSUE TITLE
Stage2Ds ScrollPane sets alpha for the batch and doesn't reset it

### ISSUE THREAD

**Issue by PMunch** [libgdx/libgdx#2949]
The ScrollPane sets the alpha of the batch it is passed to fade it's scrollbars. It is not reset after it's draw call finishes which leads to objects not related to the UI disappearing when in the same batch as a ScrollPane.

**Comment by MobiDevelop** [comment]
Actors don't reset the batch state after they are done drawing. You must reset the state before you draw other things.
