### ISSUE TITLE
Vector2 angleRad() method always returns 0 or pi if current Vector2 is (0,0)

### ISSUE THREAD

**Issue by viet54** [libgdx/libgdx#2952]
If I have a Vector2 pos1 at (0,0) and a Vector2 pos2 at any other point beside (0,0) like (1,1) and then do pos1.angleRad(pos2) it will return 0 or pi depending on the value of pos2 and never any other values.

**Comment by xoppa** [comment]
Why would you expect anything else? This is an issue tracker. If you need help on how to do something then please use the forum or irc. See https://github.com/libgdx/libgdx/wiki/Getting-Help
