### ISSUE TITLE
Music is not paused / muted when window is deactivate / minimized on desktop

### ISSUE THREAD

**Issue by titovmaxim** [libgdx/libgdx#2954]
Music is not paused / muted when window is deactivate / minimized on desktop application. It is a general requirement that the game should pause / mute the audio when minimized. 

Looks like a bug, but I found no code for that LwjglApplication, so it could be intentional. No flags in LwjglApplicationConfiguration seems to be responsible for that. The same behavior was noticed in #1263 but was not answered.

Minimal example (the music keeps playing disregarding the window state):
<pre><code>public static void main(String[] args)
	{
		final LwjglApplicationConfiguration cfg = new LwjglApplicationConfiguration();

		new LwjglApplication(new ApplicationAdapter()
		{
			Music music;

			@Override
			public void create()
			{
				music = Gdx.audio.newMusic(Gdx.files.internal("audio/music_01.mp3"));
				music.play();
			}

			@Override
			public void dispose()
			{
				music.dispose();
			}
		}, cfg);
	}
</code></pre>

**Comment by NathanSweet** [comment]
It probably should be up to application code to stop audio. Maybe the app
is for music playback, maybe it's doing voice communication it wants to
keep active, etc.

**Comment by titovmaxim** [comment]
OK, clear. Just got the feeling of inconsistency because the behavior is different from other (mobile) platforms, on which music is stopped automatically.
