### ISSUE TITLE
BitmapFont doesn't support reading float values from .fnt files

### ISSUE THREAD

**Issue by larrxu** [libgdx/libgdx#2960]
When reading a fnt file that contains float values instead of integers, BitmapFont crashes at line:
```
File: BitmapFont.java
973: int amount = Integer.parseInt(tokens.nextToken());
```
This is a bug as nowadays many tools are generating fnt files with float values. For example:

```
char id=43  x=1  y=248  width=17  height=18  xoffset=-3  yoffset=14  xadvance=12.7  page=0  chnl=0  letter="+"
kernings count=1703
kerning first=34 second=42 amount=-0.5
```

Please change to allow reading floats, or round to an integer.

**Comment by MobiDevelop** [comment]
What tools are generating .fnt files with float values?

**Comment by larrxu** [comment]
I was using https://www.glyphite.com/

**Comment by MobiDevelop** [comment]
I guess the next question is whether or not float values are actually valid. Glyphite seems to be taking some liberties with the format, they are also the ones using tabs instead of spaces. Are there other tools taking these liberties?

**Comment by xoppa** [comment]
According to [this specification](http://svn.code.sf.net/p/bmfont/code/trunk/bin/doc/file_format.html) the values in the binary format are either `int` or `uint`. I don't see any reference of allowing float values. But I guess that it doesn't harm to allow floats (and round them to int e.g.), if someone sends a PR for that.

**Comment by xoppa** [comment]
Going to close this, but please send a pull request if you like to contribute it.

**Comment by azakhary** [comment]
Awesome! I'll try to PR tomorrow ^_^
