### ISSUE TITLE
AndroidFileHandle cannot be extended

### ISSUE THREAD

**Issue by clementhely** [libgdx/libgdx#2966]
Hello,

I am trying to use an APK Expansion Files in combination with libGDX. My plan is to store all game's assets in this .zip file, as our APK will soon reach the 50 MiB limit.

I started by creating a new FileHandle and a new FileHandleResolver to load all assets directly from the ZIP file. This seems to do the trick quite well for most assets, except for audio files... When trying to load audio files, I get a ClassCastException from line 145 of com.badlogic.gdx.backends.android.AndroidAudio, since the FileHandle is cast to an AndroidFileHandle and my custom FileHandle extends com.badlogic.gdx.files.FileHandle and not AndroidFileHandle.

When encountering this problem, I of course tried to extend AndroidFileHandle instead. And this is when I noticed that this was not possible as AndroidFileHandle constructors are both package private...

Is there something I am missing on the way to use AndroidFileHandle? Or is there a way to extend this class?

Otherwise I guess I could make these constructors public or create a wrapper in com.badlogic.gdx.backends.android to be able to access them from outside the package.

**Comment by MobiDevelop** [comment]
Near duplicate of #2565. Unfortunately, as noted in the referenced PR, even if you were to get past the ClassCastException, you still wouldn't be able to load audio directly from the zip.

**Comment by clementhely** [comment]
Thank you for the quite reply, and sorry for the duplicate.

I guess I will have to find another solution to load audio files then! I'll probably leave them in the APK and only put the other assets inside the expansion file.

Thanks again for your help. :+1: 
I guess this can be closed then.
