### ISSUE TITLE
Crash on OS X when using Excelsior Jet AND when gamepad is connected

### ISSUE THREAD

**Issue by schleinzer** [libgdx/libgdx#2972]
Hi,

I have a rather specific issue, which might be known to someone: I "packed" my game with the evaluation version of Excelsior Jet 10.5 for OS X.

The  game runs fine *unless* I connect my gamepad to the mac. When starting the game with a gamepad connected, the game crashes right at the start with a "pointer freed, but not allocated" problem.

When running the game on the very same configuration with "java -jar ..." (that is, no JET) it works fine - no matter if a gamepad is connected or not.

Is there anybody experiencing the same issue?

Thank you!

**Comment by MobiDevelop** [comment]
Since it works under normal usage circumstances, this doesn't appear to be a libgdx issue.

Also, this type of question is better suited for the forum or irc than the issue tracker.

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://lixusapps.com/plant.php?imlq1>

 

loogie@basicelementdesign.com
