### ISSUE TITLE
GeometryUtils#polygonArea(..) is broken

### ISSUE THREAD

**Issue by dermetfan** [libgdx/libgdx#2974]
`GeometryUtils.polygonArea(..)` returns wrong values if offset and count are not `0` and `polygon.length`.

Here's a method to test:
```java
public static boolean isBroken() {
	float[] polygon = {0, 0, 1, 0, 1.5f, .5f, 1, 1, .5f, 1.25f, 0, 1};
	float area1 = com.badlogic.gdx.math.GeometryUtils.polygonArea(polygon, 0, polygon.length);

	float[] polygon2 = {99, 99, 0, 0, 1, 0, 1.5f, .5f, 1, 1, .5f, 1.25f, 0, 1, 99, 99};
	float area2 = com.badlogic.gdx.math.GeometryUtils.polygonArea(polygon2, 2, polygon.length);

	return area1 != area2;
}
```

**Comment by mk1x86** [comment]
I guess this is about floating point precision although all your values should be represented by IEEE754.
Use a comparison like return Math.Abs(area1-area2) < epsilon with a epsilon being a very small value

**Comment by dermetfan** [comment]
@mk1x86 I don't think so. Have a look at the output:

area1: 1.375
area2: -48.125
