### ISSUE TITLE
Custom Cursor doesn't work on OSX

### ISSUE THREAD

**Issue by Scellow** [libgdx/libgdx#2975]
It works on Windows and Ubuntu, but not on OSX Yosemite

```java
Pixmap pm = new Pixmap(Gdx.files.internal("textures/ui/cursor_x16.png"));
Gdx.input.setCursorImage(pm, 0, 0);
pm.dispose();
```

# Problem:

Custom cursor seems to work for few seconds then it go back to original OS cursor

# What is the result expected:

Custom Cursor should be displayed all the time

# Tested with

- libGDX 1.5.5
- libGDX 1.5.4

# Where it works:

- [x] Windows 8/10
- [x] Ubuntu 15.04
- [ ] OS X Yosemite

**Comment by MobiDevelop** [comment]
Works for me on Yosemite.

**Comment by Scellow** [comment]
It's probably because of my texture ?

https://bitbucket.org/Scellow/prototype-3d/src/0daf76fbb2e7ecac10d8d873eabb036b5f073a02/core/assets/textures/ui/cursor_x16.png?at=master

I'll try the patch of dermetfan once i have free time

**Comment by MobiDevelop** [comment]
It works correctly for me with your image.

I think dermetfan referenced the wrong issue when he committed, that isn't related to this.

**Comment by Scellow** [comment]
Well, today i cleaned my code, and the cursor works now

I don't know what was the cause of the issue, i'll do some test and report back

**Comment by MobiDevelop** [comment]
Assuming all is well since you didn't report back. Will reopen if that isn't the case and you can provide an example showing the issue.
