### ISSUE TITLE
Label bounds don't take scale into account

### ISSUE THREAD

**Issue by BlueRiverInteractive** [libgdx/libgdx#2977]
It seems the latest changes to BitmapFont and Label broke bounds for scaled fonts. Regardless what fontScale you specify for a Label, layout.setText() in computeSize() will always deliver you the same layout width and height. 

UPDATE: The width changes with the scale but the height doesn't. Thus the label isn't correctly positioned, either too high or too low.

**Comment by BlueRiverInteractive** [comment]
That here doesn't make any sense:
https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g2d/BitmapFont.java#L808

Dividing a number with itself always results in 1. So the values actually are never scaled.

**Comment by NathanSweet** [comment]
Aye it needs a "this.". I can look at it in a bit.

**Comment by BlueRiverInteractive** [comment]
I fixed it locally that changes it somehow but still the font is off on the y-axis for different scales. Perhaps there is some value that also needs to be scaled?

Here is a screenshot of how it is of: http://prntscr.com/6lmhcd

**Comment by BlueRiverInteractive** [comment]
From my observations, if the scale is below 1, the text drifts upwards, if it is above 1 it drifts downwards. Only when the scale is 1 the text is centered within the label bounds.

**Comment by badazdz** [comment]
This is label with setFontScale(2f) with 26.3 nightly
![font](https://cloud.githubusercontent.com/assets/1550507/6859653/a28860ee-d41b-11e4-9989-6bcffe239bf9.PNG)

**Comment by NathanSweet** [comment]
Seems ok with that fix.

UITest with scale of 2:
![](http://i.imgur.com/N6QVORt.png)

LabelTest with scale of 2 (not sure why the "d" sticks out of the bounds though!):
![](http://i.imgur.com/l5vYzxJ.png)

**Comment by BlueRiverInteractive** [comment]
Yes, that fixes it! Thx

**Comment by RobRendell** [comment]
I'm not sure if I should open a new issue, or add to this one.  It seems that the fix to font bounds with a scale other than 1f doesn't work for incrementally-generated font glyphs.

Screenshot:
![fontissue](https://cloud.githubusercontent.com/assets/1848870/6884027/3ebb2d4a-d622-11e4-950b-fb7d9d8cddc6.png)
```
public class FontSizeIssue extends ApplicationAdapter {

    private SpriteBatch batch;

    private FreeTypeFontGenerator generator;
    private BitmapFont font1;
    private BitmapFont font2;
        
    @Override
    public void create () {
        batch = new SpriteBatch();
        generator = new FreeTypeFontGenerator(Gdx.files.internal("tubular.ttf"));
        FreeTypeFontGenerator.FreeTypeFontParameter parameter1 = new FreeTypeFontGenerator.FreeTypeFontParameter();
        parameter1.size = 20;
        parameter1.incremental = true;
        parameter1.characters = "aeiou";
        font1 = generator.generateFont(parameter1);
        font1.getData().setScale(0.75f);
        FreeTypeFontGenerator.FreeTypeFontParameter parameter2 = new FreeTypeFontGenerator.FreeTypeFontParameter();
        parameter2.size = 40;
        parameter2.incremental = true;
        parameter2.characters = "aeiou";
        font2 = generator.generateFont(parameter2);
        font2.getData().setScale(0.75f);
    }

    @Override
    public void render () {
        Gdx.gl.glClearColor(1, 0, 0, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        batch.begin();
        font1.draw(batch, "small text", 100, 100);
        font2.draw(batch, "large text", 100, 200);
        batch.end();
    }
}
```
