### ISSUE TITLE
Incorrect sizes for incremental fonts with one generator and more than one font (different parameters)

### ISSUE THREAD

**Issue by RobRendell** [libgdx/libgdx#2981]
(Note that to try to isolate this bug, I've removed anything manipulating `FreeTypeBitmapFontData.scale`, so scale is 1.0f in all cases.  Thus, I don't believe this is a duplicate of #2977)

In my game, I have a single FreeTypeFontGenerator (since I only have one TTF file), but I create three different fonts using that generator by using different FreeTypeFontParameter values (different sizes, colours, border widths etc).

Trying out gdx 1.5.6-SNAPSHOT, I've modified my code now so that if I create my fonts up-front everything is rendering correctly.  However, if I set `parameter.incremental = true` and `parameter.characters = ""` so it generates everything incrementally, the different fonts are all rendering the same size as each other despite having different size parameters.  The other differences, e.g. colours, border sizes, drop shadows etc are displayed correctly.  If I change my code to create a new instance of FreeTypeFontGenerator for each different configuration of FreeTypeFontParameter, the incremental fonts go back to being sized correctly, so presumably there's something being set in the shared generator instead of the distinct data instances which is causing this.

As part of debugging this, I've dumped out the texture atlas using PixmapPackerIO, so I can see that the glyphs are indeed being created with the incorrect (equal) size - it's not something to do with the way that I'm rendering them.

**Comment by RobRendell** [comment]
I created a minimal libgdx project that demonstrates the problem.  Tar-gzip in my dropbox:

https://dl.dropboxusercontent.com/u/16299287/fontSizeIssue.tgz

It creates two fonts from the one generator, with different sizes and `parameter.incremental = true`.  It also sets `parameter.characters = "aeiou"` for both fonts, which means it pregenerates the vowels and then loads the remaining characters incrementally.  You can see that the consonants of both strings are the same size, and the text for what is supposed to be the small font has mixed sizes for the vowels and consonants.

![fontsize](https://cloud.githubusercontent.com/assets/1848870/6863295/deb22de8-d4a2-11e4-87db-d82a7169f706.png)

```
public class FontSizeIssue extends ApplicationAdapter {

    private SpriteBatch batch;

    private FreeTypeFontGenerator generator;
    private BitmapFont font1;
    private BitmapFont font2;
        
    @Override
    public void create () {
        batch = new SpriteBatch();
        generator = new FreeTypeFontGenerator(Gdx.files.internal("tubular.ttf"));
        FreeTypeFontGenerator.FreeTypeFontParameter parameter1 = new FreeTypeFontGenerator.FreeTypeFontParameter();
        parameter1.size = 20;
        parameter1.incremental = true;
        parameter1.characters = "aeiou";
        font1 = generator.generateFont(parameter1);
        FreeTypeFontGenerator.FreeTypeFontParameter parameter2 = new FreeTypeFontGenerator.FreeTypeFontParameter();
        parameter2.size = 40;
        parameter2.incremental = true;
        parameter2.characters = "aeiou";
        font2 = generator.generateFont(parameter2);
    }

    @Override
    public void render () {
        Gdx.gl.glClearColor(1, 0, 0, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        batch.begin();
        font1.draw(batch, "small text", 100, 100);
        font2.draw(batch, "large text", 100, 200);
        batch.end();
    }
}
```

**Comment by NathanSweet** [comment]
Thanks!
