### ISSUE TITLE
vSync in fullscreen on OSX will run very slow

### ISSUE THREAD

**Issue by orangepascal** [libgdx/libgdx#2982]
Setting vSyncEnabled=true or calling graphics.setVSync(true) doesn't work correctly when running in Fullscreen mode on OSX.  Framerate seems to drop to 50%.

Works correctly in windowed mode, even works perfect when manually resizing the window to fullscreen.  But framerate drops by 50% when setting Fullscreen=true on graphics.

Seems to work fine on Windows and Linux, just not on OSX.

(tested on OSX Yosemite)

**Comment by NathanSweet** [comment]
What backend?

**Comment by orangepascal** [comment]
what do you mean with backend ?

**Comment by Tom-Ski** [comment]
lwjgl / jglfw / headless (hehe)

**Comment by orangepascal** [comment]
ah, lwjgl  :) didn't know there were other options

**Comment by xoppa** [comment]
That call is directly being [forwarded](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGraphics.java#L446) to the lwjgl [Display](http://legacy.lwjgl.org/javadoc/org/lwjgl/opengl/Display.html#setVSyncEnabled(boolean)) class. If this is an issue (the lwjgl javadoc says that it isn't guaranteed to succeed) then it's probably a lwjgl issue.

**Comment by MobiDevelop** [comment]
I'm not seeing any issues with vsync and fullscreen (MacBook Pro 15", Yosemite).

**Comment by BSVogler** [comment]
You know that FPS can only be 30 or 60 FPS if you have sync enabled? FPS will drop to 30 if the system can't deliver 60 FPS. Maybe related to this?

**Comment by Darkyenus** [comment]
With vsync framerate can be anything <= display framerate (60). While vsync can drop the framerate a bit, it should not be that extreme, and should be reproducible in windowed. (Windowed should be slower than fullscreen, if anything.)

**Comment by NathanSweet** [comment]
It could be LWJGL or the graphics drivers. I don't think it's a libgdx issue, nothing we can do I'm afraid.
