### ISSUE TITLE
GWT texture blending broken on firefox but works in chrome - change since dec 2014

### ISSUE THREAD

**Issue by sridharsundaram** [libgdx/libgdx#2985]
@MobiDevelop 
My GWT application based on libGdx was earlier working in IE, firefox and Chrome. Now it works only on chrome.
My suspicion is that [this cl may have broken it] (https://github.com/libgdx/libgdx/commit/32a8ceb5edf9974f6b1d8e875a314b18edee7cc3?diff=split</code>)
- [ ] Creating a texture from a pixmap with a sem-transparent color no longer works in firefox. The texture does not have transparency.
- [ ] Drawing an image over another image so that both are composited no longer works in firefox.

**Comment by MobiDevelop** [comment]
When I made those changes I am pretty sure I tested it in all supported browsers. If it worked before in Firefox, then Firefox was not handling the composite modes correctly.

Will have another look.

**Comment by MobiDevelop** [comment]
Ran through our tests on the latest Chrome and Firefox and they function the same for me. Unfortunately, I won't be able to reproduce the issue you are seeing without sample code.

**Comment by sridharsundaram** [comment]
Thanks for the prompt response.
I could reproduce the incorrect blending bug in firefox for a simple
example.

Here are the sample images for chrome and firefox - 3 colored rectangles
layered on top of each other
The desktop version shows results identical to chrome.

The sample code being used is at the end.

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CHROME

[image: Inline image 2]


-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FIREFOX
[image: Inline image 1]

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
We can see that blending is not happening in Firefox but happening Chrome.
Here is the code example that I am using
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
public class GwtLauncher extends GwtApplication {

  private static Image createColorImage(Color color, int size) {
    Pixmap pixmap = new Pixmap(1, 1, Pixmap.Format.RGBA8888);
    Blending b = Pixmap.getBlending();
    Pixmap.setBlending(Blending.None);
    pixmap.setColor(color);
    pixmap.fill();
    TextureRegion textureRegion = new TextureRegion(new Texture(pixmap), 1,
1);
    pixmap.dispose();
    Pixmap.setBlending(b);
    Image img = new Image(textureRegion);
    img.setSize(size, size);
    img.setPosition(Gdx.graphics.getWidth() / 2 - size / 2,
        Gdx.graphics.getHeight() / 2 - size / 2);
    return img;
  }

  @Override
  public GwtApplicationConfiguration getConfig() {
    GwtApplicationConfiguration cfg = new GwtApplicationConfiguration(1024,
768);
    return cfg;
  }

  @Override
  public ApplicationListener getApplicationListener() {
    return new MyApplication();
  }

  private class MyApplication implements ApplicationListener {
    Stage stage;

    @Override
    public void create() {
      Viewport viewport = new ScalingViewport(Scaling.fill,
          Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
      this.stage = new Stage(viewport);
      Image img1 = createColorImage(new Color(1, 0, 0, 1f), 300);
      Image img2 = createColorImage(new Color(0, 1, 0, 0.5f), 200);
      Image img3 = createColorImage(new Color(0, 0, 1, 0.25f), 100);
      stage.addActor(img1);
      stage.addActor(img2);
      stage.addActor(img3);
    }

    @Override
    public void render() {
      Gdx.gl.glViewport(0, 0, Gdx.graphics.getWidth(),
Gdx.graphics.getHeight());
      Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT | GL20.GL_DEPTH_BUFFER_BIT);
      stage.draw();
    }

    @Override
    public void resize(int width, int height) {
    }

    @Override
    public void pause() {
    }

    @Override
    public void resume() {
    }

    @Override
    public void dispose() {
    }

  }
}

**Comment by sridharsundaram** [comment]
(Sorry, inline images in earlier comment sent via email did not get uploaded - uploading them directly now)
Chrome image
![image](https://cloud.githubusercontent.com/assets/200954/6912475/9ced986c-d78f-11e4-99c0-bab2810707d4.png)

Firefox image
![image](https://cloud.githubusercontent.com/assets/200954/6912483/adc6cde8-d78f-11e4-88ce-12381ca1cbb4.png)
