### ISSUE TITLE
Decal setter for DecalMaterial

### ISSUE THREAD

**Issue by scientistnm** [libgdx/libgdx#2986]
Hello,

I was trying to change blending of decals in my app.
But I needed to use glBlendFuncSeparate instead of glBlendFunc.

So I needed to extended Decal class and DecalMaterial, and override DecalMaterial set() method.
To change the instance od DecalMaterial in Decal class I needed to to set new instance of my custom DecalMaterial in constructor of custom Decal class. Like:

material = new CustomDecalMaterial();

It's working and it's fine, but I think that would be much cleaner solution if Decal has setter for custom material.

setMaterial(DecalMaterial material){
     this.material = material;
}

This would be much cleaner solution for customizing blending of decals.

**Comment by nooone** [comment]
If you already do have a solution, would you mind creating a PR for it?

I don't know whether your usecase is very common, but that additional setter won't hurt.

**Comment by scientistnm** [comment]
Hello,

I have none experience in working with GIT and GitHub.
Because of that I opened an issue, instead of PR.
I was hopping that this can be done by someone else.

I currently don't have much time, because I have a lot on my back right now.

So if someone can do this, that would be great,

**Comment by scientistnm** [comment]
I've sent a pull request for this issue.
Pull #3167
