### ISSUE TITLE
No IntelliJ IPR files generated

### ISSUE THREAD

**Issue by entangledloops** [libgdx/libgdx#2994]
The advanced option to generate Intellij IPR project files does not function in 1.5.5, even though the checkbox is enabled. A screenshot of my settings is shown below.

![libgdx](https://cloud.githubusercontent.com/assets/3599701/6910014/fcc2073e-d71a-11e4-9fe0-ce78622a3bb8.png)

**Comment by Tom-Ski** [comment]
Works for me, and that output looks like it worked too.  What do you mean by "it does not function"?

**Comment by MobiDevelop** [comment]
Also works for me.

**Comment by entangledloops** [comment]
How strange! It produced nothing for me, no project files of any kind. However, after closing and opening the project setup jar numerous times, killing/restarting Java, and rerunning it with the same settings, it finally and mysteriously worked. Some obscure bug no doubt, but unfortunately I'm not sure what else I can provide to assist.
