### ISSUE TITLE
libgdx with Box2D - Random Performance Issue

### ISSUE THREAD

**Issue by neopraveen** [libgdx/libgdx#2995]
I am experiencing a strange issue in my game - 
https://play.google.com/store/apps/details?id=com.pieteams.supercar.racing

The game scene has some performance issue while rendering. Some time their is no issue(one out of 5 times) you can play the full session without a single jerk, but some time it is very annoying. The performance issue is reproducible in I-phone 5c also. Please help me, I am very frustrated, because their is no similar issue on google. I am unable to find the reason, because if it is an memory issue or rendering issue then it must be reproduced every time. Please suggest, what may be wrong. If this bug make any sense please share your thoughts, it might help me to find the exact problem.
Thanks in advance.

**Comment by Tom-Ski** [comment]
This question is better suited to the forums as this is an issue tracker.  If you suspect there to be a problem with LibGDX, please create an issue with a self contained executable example that reproduces your issue.  (Posting a link to your game is not one of these examples)

To give you a few hints with your problem, monitor memory usage, body creation, make sure you are pooling where possible and not creating a lot of garbage.
