### ISSUE TITLE
BitmapFont draw y position (and letter y position partially) not working as intended when drawn font is scaled?

### ISSUE THREAD

**Issue by daranus** [libgdx/libgdx#2998]
Hi there,

I recently updated to the newest nightlies and all my BitmapFont.draw() calls seem to be slightly/majorly broken. I spotted 2 problems happening when the drawn BitmapFont is scaled:

The y Position of the whole drawn text seems to be working differently than before (not sure exactly how it works now, but it neither aligns the top nor the bottom to the specified y. the only thing i can think of is that the default align is center by default but I'd need to check on that and try it out (in my setup I had the y Position depending on the lineheight/2f but as that didnt work anymore I set a fixed y position for testing purposes))

The y Position of certain letters gets screwed up, if the font has been scaled (in this example, the 7 is vertically bigger than the other letters and thats the one appearing screwed up vertically when the font is scaled)

![screenshot 2015-04-02 01 08 46](https://cloud.githubusercontent.com/assets/8322297/6955088/8fc6f4ee-d8d9-11e4-9958-95f5a2ce49cf.png)

The pictures are displaying the same drawcall with a fixed y position, but different setScale() (one is about 0.3f I think and the other one is 1)

Any insight or help would be greatly appreciated!

Edit:

SSCCE: http://pastebin.com/mi2Q456U

Font:
https://www.dropbox.com/s/0uj0kpq7at0h85h/uiDistance2015.fnt?dl=0
https://www.dropbox.com/s/rd58ithju0f9r9m/uiDistance2015.png?dl=0

![screenshot 2015-04-02 02 10 09](https://cloud.githubusercontent.com/assets/8322297/6955490/9f1bc8a2-d8de-11e4-95a6-7c8e07469a3f.png)

**Comment by NathanSweet** [comment]
Your SSCCE doesn't compile with the latest from Git. Fixing that, I see:

![](http://i.imgur.com/IKPAXLh.png)

**Comment by daranus** [comment]
Sorry, I was indeed on 1.5.5, not on the latest nightlies. Luckily, latest nightlies seem to fix either partially or all the issues, will report back after i tested!

**Comment by daranus** [comment]
Updated to the latest nightly, the things broken in 1.5.5 now work as intended again, CLOSED.
