### ISSUE TITLE
GWT graphics.getDensity is fixed

### ISSUE THREAD

**Issue by Kjos** [libgdx/libgdx#3003]
Hi,
I noticed getDensity and other density related functions in GWTGraphics are fixed. I wonder if this has a cause and if it could be improved to allow for better viewing on Android and so on.
Regards,
Kjos

**Comment by MobiDevelop** [comment]
There is probably an opportunity to use `window.devicePixelRatio` to get a more accurate estimate of these values.

**Comment by Kjos** [comment]
Yes, I also notice that on a Nexus 7 the scaling is way off (in regards that the sizes of elements are set to fixed pixel size), but this might be a browser issue (?).

**Comment by xoppa** [comment]
Would it be possible for you to send a pull request?

**Comment by intrigus** [comment]
I'll send a PR for this if I have finished and tested my other PRs.

**Comment by intrigus** [comment]
I'm not sure if we can use ```window.devicePixelRatio```, because "```window.devicePixelRatio``` changes with zoom on desktops yet remains static on mobile devices"  see http://ryanve.com/lab/resolution/#dpr
