### ISSUE TITLE
TideMapLoader Map/Layers properties not stored

### ISSUE THREAD

**Issue by ACedric** [libgdx/libgdx#3004]
The properties of maps and layers created with tIDE are not stored into the TiledMap object.

I've tested the following fix (with a custom Loader) :
For Map properties, edit [TideMapLoader.java L109](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/maps/tiled/TideMapLoader.java#L109)  :
```
Element properties = root.getChildByName("properties");
```
And replace by :
```
Element properties = root.getChildByName("Properties"); // Uppercase "P"
```

For Layers properties, edit [TideMapLoader.java L264](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/maps/tiled/TideMapLoader.java#L264) and insert :
```
Element properties = element.getChildByName("Properties");
if (properties != null) {
	loadProperties(layer.getProperties(), properties);
}
```
In the same way, it might be great to auto-generate some basic dimensions properties on Map / Layers (width, height, tileHeight, tileWidth). If I remember well, it's already done for TmxMapLoader.

**Comment by MobiDevelop** [comment]
Thanks for the report.
