### ISSUE TITLE
ProgressBar does not update visual value in 1.5.5

### ISSUE THREAD

**Issue by Astrimedes** [libgdx/libgdx#3005]
With no other code changes, my ProgressBar actor doesn't update it's visual value after upgrading to 1.5.5 from 1.5.4.  The new value is reflected, but the visual-only values are not displaying, so the bar jumps from set value to set value only.

I have tried with and without setting the stage's actionsRequestRender to true.

**Comment by essaic** [comment]
https://github.com/libgdx/libgdx/wiki/Getting-Help#help-us-help-you

**Comment by dermetfan** [comment]
probably a duplicate of #2947 which is fixed in 1.5.6

**Comment by MobiDevelop** [comment]
We'll go with it being a duplicate, if not reopen.

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://chocolatewelshmountainsheep.com/weather.php?l4xd>

 

loogie@basicelementdesign.com
