### ISSUE TITLE
Hiero unable to select system fonts

### ISSUE THREAD

**Issue by nooone** [libgdx/libgdx#3006]
I've downloaded the latest version of Hiero from [here](http://libgdx.badlogicgames.com/releases/). However, the last time I've used it, I've selected a .ttf file. Now I wanted to select a system font which I've installed in C:\Windows\Fonts. When I scroll through the list of system fonts, I can see it, but for some reason the radio button there is disabled.

Am I doing something wrong?

![hiero](https://cloud.githubusercontent.com/assets/5896510/6994198/821a210c-db10-11e4-8f02-54db6574742f.PNG)

**Comment by nooone** [comment]
Seconds after creating this issue @kotcrab (https://github.com/kotcrab) told me that clearing the filepath manually will enable the "System" radiobutton and font list.

It's a strange behaviour, but not really critical. Should I close this issue?

**Comment by NathanSweet** [comment]
I'd say closing it is fine, unless you want to create a PR. :)

**Comment by nooone** [comment]
Yeah, I'm too lazy to look into Hiero currently...

**Comment by NathanSweet** [comment]
I guess you just don't Swing that way yet.

On Sat, Apr 4, 2015 at 10:48 PM, Daniel Holderbaum <notifications@github.com

**Comment by kotcrab** [comment]
I wanted to fix this issue, ran Hiero from sources and can't reproduce this. Looks like it has been fixed already and hiero.jar [here](http://libgdx.badlogicgames.com/releases/) is outdated.
