### ISSUE TITLE
Particle editor emitter panel missing on OSX

### ISSUE THREAD

**Issue by Plastix** [libgdx/libgdx#3008]
There is a blank panel on the top left. There _should_ be a panel on the bottom left that lists the emitters. Unfortunately this means I am unable to use the particle editor because I cannot export my particle effect without it.

Running on OSX 10.10 (Java 8) with the particle editor from GDX 1.5.5. Also confirmed happening with the editor from the latest nightly. 

![screen shot 2015-04-06 at 8 24 36 am](https://cloud.githubusercontent.com/assets/1526881/7004242/6669ac58-dc36-11e4-8529-0d943c707692.png)

**Comment by NathanSweet** [comment]
Not sure why this would be happening. I don't have OS X convenient, so I won't be able to debug it. Maybe you can fix and submit a PR?

**Comment by cypherdare** [comment]
Looks fine on Yosemite with JDK 1.7. I haven't tried 8.

![screen shot 2015-05-07 at 10 54 41 pm](https://cloud.githubusercontent.com/assets/1843131/7529828/8d630856-f50c-11e4-8399-f92873b5d641.png)

**Comment by MobiDevelop** [comment]
This seems to be specific to Java 8. Using Java 7 it works correctly.

**Comment by NathanSweet** [comment]
Bizarre. Maybe some code to manipulate the splitter will cause it to work.

**Comment by badlogic** [comment]
Works on Sierra with last JDK 8 update.
