### ISSUE TITLE
Small Caps Support for FreeTypeFontGenerator

### ISSUE THREAD

**Issue by darkfrog26** [libgdx/libgdx#3009]
The font generator works very well, but for a scenario when something like small-caps is needed there is no support:

https://github.com/libgdx/libgdx/blob/master/extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator.java#L676

**Comment by NathanSweet** [comment]
Maybe you can make a PR?

**Comment by darkfrog26** [comment]
@NathanSweet I don't have the code checked out at the moment, but I can try in the near future. A simple work-around to make this work would be to have a boolean "smallCaps" that if set to true, the font size is "size * 0.68" for lowercase text (toUpperCase) and that gives you roughly the correct size and then all uppercase / other characters would just be rendered as "size".

**Comment by NathanSweet** [comment]
That's a bit hacky, it would be best to use FreeType if it supports small
caps.

**Comment by Darkyenus** [comment]
Aren't small caps just a feature of font/different font anyway? Those scaling values would have to be tweaked separately and the font would have to be probably rasterized separately for that scale to look good. Most we can do, is support changing font per glyph (which could be useful anyway, think emoji only font or something).

**Comment by nooone** [comment]
> this work would be to have a boolean "smallCaps" that if set to true, the font size is "size * 0.68" for lowercase text (toUpperCase) and that gives you roughly the correct size

Where did you get the value 0.68 from?

**Comment by NathanSweet** [comment]
I don't see anything in FreeType that lets us specify small caps or other variants. We can use a float smallCaps setting where 0 is off and 1 uses all caps at 100% of the x-height. Scaled small caps [won't look as good](http://en.wikipedia.org/wiki/Small_caps#/media/File:True_vs_Scaled_Small_Caps.svg).
