### ISSUE TITLE
Render called between pause and resume

### ISSUE THREAD

**Issue by nooone** [libgdx/libgdx#3016]
Today I've realized that `render()` is still called in between `pause()` and `resume()` on desktop (at least on Windows 7+8).

I think the current implementation calls pause and resume when the window loses and regains focus. In some cases that's probably a good way to be notified about those events. However in *most* cases, I believe, it's causing problems or at least inconveniences (like being moved to a pause screen every time I switch to another window when I'm not in full-screen mode).

In two of my games I'm also taking the time between pause and resume into account of my gameplay logic. However, because the standard render(deltaTime) is still called in between pause and resume, I'm actually counting that time twice, which in one game of mine causes a doubled penalty, in the other a doubled bonus.

I don't think that people still expect render to be called after a pause (also [the lifecycle graph](https://github.com/libgdx/libgdx/wiki/The-life-cycle) in the wiki does not show that). And somehow I think that it's also *wrong*.

I believe that a better solution would be, to make this configurable via `LwjglApplicationConfiguration`, but *disable* it by default. That's the default behaviour that makes sense to me the most. However, if we want to maintain backwards compatibility, we could also enable it by default (however, I really don't think that anyone actually relies on the fact, that there's a pause + resume in this case).

What do you guys think?

**Comment by NathanSweet** [comment]
Some apps want to keep rendering in the background. If you don't, maybe LwjglApplicationConfiguration `backgroundFPS=-1` does what you want?

**Comment by nooone** [comment]
You got me wrong. I also want the app to keep rendering "in the background", because it's not really in the background. What I *don't* want, is pause+resume to be called in this case.

**Comment by NathanSweet** [comment]
Ah. I suppose you can just check Gdx.app.getType and return from the pause/resume methods. Not sure a config setting is really any better.

**Comment by nooone** [comment]
Yep, that's what my solution would be. IMHO the callbacks are just not appropriate, that's why I'd change it. They are actually "window lost focus" and "window gained focus" instead of pause and resume, what the API makes you believe here.

Pause and resume is kind of a "hackish" way to implement these events. It's okay if you *really* want to listen to those, but I think the majority of people don't want that and don't even know that the app is not actually paused.

**Comment by NathanSweet** [comment]
The assumption is that in general people don't want to react to pause/resume on desktop. Is that really the most common use case?

The wiki actually uses the word "focus" for pause/resume (for Android).

So the issue is that render is called between pause and resume, which I agree is a bit odd and may be unexpected. Do many people have a problem with this? It's the first time it's been brought up. If we change the default then we break existing apps that rely on the old behavior in a way that won't be readily apparent.

**Comment by nooone** [comment]
> So the issue is that render is called between pause and resume, which I agree is a bit odd and may be unexpected.

I'd still formulate it the other way around. It's not the problem that it keeps rendering, but that pause + resume is called. If you think about it like that, it's just plain wrong, isn't it? (The app is **not** paused at all).

> If we change the default then we break existing apps that rely on the old behavior in a way that won't be readily apparent.

It wouldn't be the very first time that something breaks after an update. If one doesn't read the release notes it's his/her own fault imo. Plus, who would really rely on the current behaviour? What is one supposed to do when the window loses it's focus, keeps running, but maybe with a lower framerate? The only things I could imagine would be something like turning off the sound when not having focus, or switching to a pause screen. And that not happening cannot be considered "breaking" the apps.

> It's the first time it's been brought up.

That's actually pretty suprising. On the other hand it also took me more than a year to realize that behaviour at all. And I would not have realized it, if my games wouldn't have these kind of "special" game mechanics.

**Comment by nooone** [comment]
That being said, now that I've understood the "problem" myself, I can easily "fix" it in my games. I thought it makes sense to change that behaviour in general, but if you think it does not, or we keep it for backwards compatibility reasons, I can close this issue.

**Comment by NathanSweet** [comment]
> The app is not paused at all.

Either perspective could be used and the other way would be wrong. I'm pretty sure pause/resume for desktop was added because someone wanted those events. You're right we could break it and it's not likely a big deal. I don't personally rely on those events and don't really feel strongly either way. Anyone other opinions?
