### ISSUE TITLE
Rendering of TiledDrawable

### ISSUE THREAD

**Issue by mk1x86** [libgdx/libgdx#3017]
I'm having a problem with rendering a TiledDrawable. It sometimes happens that the drawable is rendered at places that exceed the size of the rect where it should actually be drawn. This is due to float precision and the way the number of times the drawable needs to be rendered is calculated.

In TiledDrawable.java ln44 there's while(x < endX). In my case x is 491.80124 while endX is 491.80127. Consequently the drawable is rendered again exceeding the actual size. Since this depends on the size of the drawable and the rect it should be rendered in I can't provide a simple test. The problem is evident though, the solution prolly simple:
Instead of subtracting the size of the drawable every time calculate the number of drawables that fit into the rect ONCE. Render the drawables. calculate remaining area/width/height by subtracting widthRect - numRenderedHorizontal*regionWidth and fill the rest with a cropped version of the drawable.

Screenshot: The problem is in the bottom right corner. The panel's border is extended to the right of the screen.
![2015-04-09 10_37_25-canyonwave](https://cloud.githubusercontent.com/assets/4849383/7063141/75c1b86a-dea4-11e4-8143-6e9fbe316408.png)

**Comment by NathanSweet** [comment]
> Since this depends on the size of the drawable and the rect it should be rendered in I can't provide a simple test.

You could make a test that uses the problematic sizes. Without a test, how can any fix be tested?

**Comment by mk1x86** [comment]
Sorry yes, this is of course possible. Here's a fully working core file with the values used from my app.
![2015-04-09 14_49_19-tdrawabletest](https://cloud.githubusercontent.com/assets/4849383/7066961/afd7c8fa-dec7-11e4-8242-e3390bed3bf4.png)

Blue line indicates the desired width. The TiledDrawable exceeds that width.

```Java
package com.mk1x86.G3DViewer;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.Pixmap;
import com.badlogic.gdx.graphics.Pixmap.Format;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.graphics.g2d.TextureRegion;
import com.badlogic.gdx.scenes.scene2d.utils.TextureRegionDrawable;
import com.badlogic.gdx.scenes.scene2d.utils.TiledDrawable;

public class TDrawableTest extends ApplicationAdapter {
	private TiledDrawable tiledDrawable;
	private TextureRegionDrawable regionDrawable;
	private Texture texture;
	private SpriteBatch batch;
	public TDrawableTest() {
	}
	
	@Override
	public void create () {
		// create simple texture
		Pixmap p = new Pixmap(155,10, Format.RGB888);
		p.setColor(Color.GRAY);
		p.fill();
		p.setColor(Color.BLUE);
		p.drawLine(0, 0, 0, 9);
		p.setColor(Color.RED);
		p.drawLine(154, 0, 154, 9);
		texture = new Texture(p);
		p.dispose();
		
		tiledDrawable = new TiledDrawable(new TextureRegion(texture));
		
		regionDrawable = new TextureRegionDrawable(new TextureRegion(texture, 0,0,1,1));
		batch = new SpriteBatch();
	}

	@Override
	public void render () {
		Gdx.gl.glClearColor(1,1,1,1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT | GL20.GL_DEPTH_BUFFER_BIT);
		batch.begin();
		float x1 = 26.80124f;
		float w = 586.1776f;
		regionDrawable.draw(batch, x1, 25, w, 2); // blue line for comparison
		tiledDrawable.draw(batch, x1, 10, w, 10); // tiled drawable, should have same length
		batch.end();
	}
	
	@Override
	public void dispose() {
		batch.dispose();
		texture.dispose();
	}
}

```

**Comment by NathanSweet** [comment]
Great, thanks!
