### ISSUE TITLE
3D ParticleSystem crashes second time the game starts on Android

### ISSUE THREAD

**Issue by krial057** [libgdx/libgdx#3018]
Hey,

I'm using 3d Particle Effect in my Game on Android. However, the game will crash the second time I start it. Here is the error log:
```
04-07 15:32:10.680: E/AndroidRuntime(31308): FATAL EXCEPTION: GLThread 644
04-07 15:32:10.680: E/AndroidRuntime(31308): com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NullPointerException
04-07 15:32:10.680: E/AndroidRuntime(31308): 	at com.badlogic.gdx.assets.AssetManager.handleTaskError(AssetManager.java:540)
04-07 15:32:10.680: E/AndroidRuntime(31308): 	at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:356)
04-07 15:32:10.680: E/AndroidRuntime(31308): 	at lu.internet.alain_krier.ggame.World.update(World.java:239)
04-07 15:32:10.680: E/AndroidRuntime(31308): 	at lu.internet.alain_krier.ggame.screens.GameScreen.update(GameScreen.java:30)
04-07 15:32:10.680: E/AndroidRuntime(31308): 	at lu.internet.alain_krier.ggame.screens.GameScreen.render(GameScreen.java:35)
04-07 15:32:10.680: E/AndroidRuntime(31308): 	at com.badlogic.gdx.Game.render(Game.java:46)
04-07 15:32:10.680: E/AndroidRuntime(31308): 	at lu.internet.alain_krier.ggame.Ggame.render(Ggame.java:46)
04-07 15:32:10.680: E/AndroidRuntime(31308): 	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
04-07 15:32:10.680: E/AndroidRuntime(31308): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1516)
04-07 15:32:10.680: E/AndroidRuntime(31308): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
04-07 15:32:10.680: E/AndroidRuntime(31308): Caused by: java.lang.NullPointerException
04-07 15:32:10.680: E/AndroidRuntime(31308): 	at com.badlogic.gdx.assets.AssetManager.get(AssetManager.java:148)
04-07 15:32:10.680: E/AndroidRuntime(31308): 	at com.badlogic.gdx.graphics.g3d.particles.batches.BillboardParticleBatch.load(BillboardParticleBatch.java:678)
04-07 15:32:10.680: E/AndroidRuntime(31308): 	at com.badlogic.gdx.graphics.g3d.particles.ParticleEffectLoader.loadSync(ParticleEffectLoader.java:117)
04-07 15:32:10.680: E/AndroidRuntime(31308): 	at com.badlogic.gdx.graphics.g3d.particles.ParticleEffectLoader.loadSync(ParticleEffectLoader.java:29)
04-07 15:32:10.680: E/AndroidRuntime(31308): 	at com.badlogic.gdx.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:139)
04-07 15:32:10.680: E/AndroidRuntime(31308): 	at com.badlogic.gdx.assets.AssetLoadingTask.update(AssetLoadingTask.java:89)
04-07 15:32:10.680: E/AndroidRuntime(31308): 	at com.badlogic.gdx.assets.AssetManager.updateTask(AssetManager.java:477)
04-07 15:32:10.680: E/AndroidRuntime(31308): 	at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:354)
04-07 15:32:10.680: E/AndroidRuntime(31308): 	... 8 more
```

I figured out, that it is because ParticleSystem class uses the Singleton Pattern and therefore has a static variable holding the instance(which causes trouble due to the Android Life Cycle). I called the constructor of ParticleSystem manually and then it works.

I suggest removing the Singleton pattern and force the user to manually instantiate the ParticleSystem class to be able to use it.

regards,
Alain

**Comment by nooone** [comment]
It would be pretty exotic if static variables lose their values, even in an Android context. That happens only when the class would be unloaded or something similar happens. I don't think that Android really unloads classes and reloads them within a single lifetime of an app.

Even if it *does* happen though, there's a nullcheck in [the singleton](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g3d/particles/ParticleSystem.java#L17).

How did you backtrack this to ParticleSystem? It's not in the stacktrace. Plus: How did you call the constructor? Did you use black magic (aka reflection), because it's private.

**Comment by MobiDevelop** [comment]
The NPE you see in the stack trace is triggered by a null AssetDescriptor being sent to the AssetManager - how does this have anything to do with the ParticleSystem?

**Comment by krial057** [comment]
Yes, I used reflection to call the private constructor(as workaround for now).

I used the following code to load particle assets:
```
ParticleEffectLoader.ParticleEffectLoadParameter loadParam = new ParticleEffectLoader.ParticleEffectLoadParameter(ParticleSystem.get().getBatches());
        ParticleEffectLoader loader = new ParticleEffectLoader(new InternalFileHandleResolver());
        assets.setLoader(ParticleEffect.class, loader);
```

That's where the ParticleEffectLoader gets set up with the help of the ParticleSystem Singleton

**Comment by xpenatan** [comment]
krial057, I got a similar problem.   Check if your having duplicated ParticleSystem#batches, if you do, clear them before adding it.

My problem was when rotating the device assetManager crashed. It was because it was having duplicated batches.  Since ParticleSystem is static, the old batches is still in the array.
