### ISSUE TITLE
Error occurs when exiting LibGDX game(AL lib: (EE) alc_cleanup: 1 device not closed)

### ISSUE THREAD

**Issue by xJeremyCx** [libgdx/libgdx#3019]
I have this code
```java
Gdx.input.setInputProcessor(new InputAdapter()
 {
     @Override
     public boolean keyUp(int keycode)
     {
        if(keycode==Input.Keys.ESCAPE)
        {
            Gdx.app.exit();
        }
        return true;
    }
});
```
When I press the Esc button,(or exit manually), my game exits and the console shows this message.
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000000d98c83b, pid=6828, tid=3184
#
# JRE version: Java(TM) SE Runtime Environment (7.0_75-b13) (build 1.7.0_75-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.75-b04 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ig4icd64.dll+0x19c83b]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\user\AppData\Local\Temp\\hs_err_pid6828.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
AL lib: (EE) alc_cleanup: 1 device not closed
```
The version of LibGDX I'm using is 1.5.5. Any helps are appreciated.

**Comment by nooone** [comment]
I'm also doing that, but don't have that problem.

I assume you might be doing something wrong in your `dispose()` methods, which will be called after that. Those might lead to the actual crash which will leave `1 device not closed`.

**Comment by xJeremyCx** [comment]
Uhm nope.
My code doesn't have any ```pause()``` method(which means I don't use it). I only dispose ```Texture```s in ```dispose()``` methods. My game doesn't have any sounds/musics too.

**Comment by xoppa** [comment]
This is an issue tracker. If you need help, then please use the forum or irc. See also: https://github.com/libgdx/libgdx/wiki/Getting-Help.
If you are reporting an issue with libgdx then please include the information (a single class runnable example) required to reproduce the issue you're reporting. See https://github.com/libgdx/libgdx/wiki/Getting-Help#executable-example-code.

**Comment by xJeremyCx** [comment]
@xoppa I guess there's something to do with my code. If I didn't load the first ```Screen```, everything works fine.

**Comment by xJeremyCx** [comment]
This problem doesn't occur if I use an old LibGDX build.(not sure which version was it, the date modified was 10/10/2014. It doesn't occur too, if I remove code in line 47 to 50.(http://pastebin.com/4VvZrTbr)

**Comment by xoppa** [comment]
Like said, please include the minimal required runnable example to reproduce the issue you' re reporting. Also, how exactly did you verify that this isn't an issue with your code (does it also happen with a newly created project)?

**Comment by nooone** [comment]
How did you update the libgdx version? Maybe you are using incompatible natives?

**Comment by xJeremyCx** [comment]
@xoppa I do not use the Gdxsetup app. Instead, I set all things up myself. I'm using IntelliJ
Main class
```java
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration;

public class Wat
{
    public static void main(String[] args)
    {
        LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
        config.title = "wat";
        config.width = 1024;
        config.height = 768;
        config.fullscreen = true;
        config.resizable = false;
        new LwjglApplication(new Bootstrap(), config);
    }
}
```
Bootstrap class
```java
import com.badlogic.gdx.Game;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.Input;
import com.badlogic.gdx.InputAdapter;
import com.badlogic.gdx.graphics.OrthographicCamera;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;

public class Bootstrap extends Game
{
    private static Game game;
    private OrthographicCamera bCam;
    private SpriteBatch bBatch;

    @Override
    public void create()
    {
        game = this;
        bCam = new OrthographicCamera(Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
        bCam.setToOrtho(false, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());

        bBatch = new SpriteBatch();
        bBatch.setProjectionMatrix(bCam.combined);

        setScreen(new SLogo(bCam, bBatch));

        Gdx.input.setInputProcessor(new InputAdapter()
        {
            @Override
            public boolean keyUp(int keycode)
            {
                if(keycode==Input.Keys.ESCAPE)
                {
                    Gdx.app.exit();
                }
                return true;
            }
        });
    }

    public static Game getGame()
    {
        return game;
    }
}
```
SLogo class
```java
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.ScreenAdapter;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.OrthographicCamera;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.utils.Timer;

public class SLogo extends ScreenAdapter
{
    private OrthographicCamera cam;
    private SpriteBatch batch;
    private Texture logo;

    public SLogo(OrthographicCamera cam, SpriteBatch batch)
    {
        this.cam = cam;
        this.batch = batch;
    }

    @Override
    public void show()
    {
        logo = new Texture(Gdx.files.internal("assets/images/wat.png")); //get img from http://imgur.com/q4WavI2
    }

    @Override
    public void render(float delta)
    {
        super.render(delta);
        Gdx.gl.glClearColor(28 / 255, 28 / 255, 28 / 255, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        cam.update();
        batch.begin();
        batch.draw(logo, Gdx.graphics.getWidth() / 2 - logo.getWidth() / 2, (Gdx.graphics.getHeight() / 2 - logo.getHeight() / 2) + 100);
        batch.end();
    }

    @Override
    public void dispose()
    {
        super.dispose();
        logo.dispose();
    }
}
```
The game can be launched in full screen mode and the image is painted, perfectly. But when I hit Esc button, AL lib: (EE) alc_cleanup: 1 device not closed.

@nooone I don't use the setup app because I don't like Gradle. I downloaded LibGdx files directly from http://libgdx.badlogicgames.com/releases. And what do you mean by incompatible natives?

**Comment by xoppa** [comment]
So, how exactly did you verify that this isn't an issue with your code? You are never disposing the SpriteBatch. As said, this is an issue tracker, if you need help debugging your code then use the forum or irc. If you don't like the setup utility then manually create a new project to verify it isn't a problem with your code. Will reopen if you provide a valid test required to reproduce the issue.

**Comment by xJeremyCx** [comment]
I'm here to confirm that this issue only presents in projects built with LibGDX 1.5.5. I just ran my game with LibGDX 1.5.4, it ran fine, and exited without any errors.

I have these 4 JARs included in my project library.
```
gdx.jar
gdx-natives.jar
gdx-backend-lwjgl.jar
gdx-backend-lwjgl-natives.jar
```
If I LibGDX 1.5.4 or lower, everything works fine. Not sure why.

**Comment by davebaol** [comment]
@xJeremyCx 
Are gdx native jars in your project up-to-date?

**Comment by xJeremyCx** [comment]
@davebaol 
Yes, all are up-to-date(version 1.5.5)

![](http://i.imgur.com/5oqN26Q.png)

.
