### ISSUE TITLE
Multiple bone animations at the same time not working

### ISSUE THREAD

**Issue by VoidZombie** [libgdx/libgdx#3020]
This issue refers to this forum thread:
http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=18951

In short: using multiple AnimationController objects to apply multiple skeletal\bone animations is not working.

Example can be downloaded here: https://drive.google.com/file/d/0B-NYp-bbU4aValJteWRGTUFCLVU/view?usp=sharing

**Comment by xoppa** [comment]
Your model contains three animations, all of which affect the node named `j4`. [You can't apply multiple animations that affect the same node](https://github.com/libgdx/libgdx/wiki/3D-animations-and-skinning#applying-a-single-animation). Please provide a valid test model to show the issue.
