### ISSUE TITLE
Looping Music does not work on Mac OSX

### ISSUE THREAD

**Issue by robertmk** [libgdx/libgdx#3024]
Hi,

I am not able to get a Music instance to loop on OSX. Use the following sample code to reproduce:

import com.badlogic.gdx.Audio;
import com.badlogic.gdx.Files;
import com.badlogic.gdx.audio.Music;
import com.badlogic.gdx.backends.lwjgl.LwjglFiles;
import com.badlogic.gdx.backends.lwjgl.LwjglNativesLoader;
import com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio;

public class GDXMusicLoopDemo {
    public static void main(String[] args){
        LwjglNativesLoader.load();
        Files files = new LwjglFiles();
        Audio audio = new OpenALAudio();
        final Music music = audio.newMusic(files.absolute("/Users/krueger/sounds/loops/flowing_river.wav"));
        music.setLooping(true);
        music.play();
    }
}

The sound is only played back once. Expected behaviour would be for it to loop. Tried with libgdx version 1.5.5 on OSX 10.10.2. 
Note that looping works fine on OSX when using Sound instead of Music.

**Comment by MobiDevelop** [comment]
Music looping works correctly for me.

**Comment by robertmk** [comment]
Did you execute the code above or how did you test? If so, would it help if I made the sample available?

**Comment by MobiDevelop** [comment]
I used our MusicTest with tracks in each format. The problem could be sample specific, so it might help if you provide that as well.

Is there a reason you are initializing everything yourself instead of going through the libgdx lifecycle, or was this only for the sample code here?

**Comment by robertmk** [comment]
The sample is here: https://www.dropbox.com/s/ykra9qzyloduja6/flowing_river2.wav

I do the initialization myself because I only use libgdx's audio engine as a workaround for bugs in JavaFX's media engine, which is buggy as hell and will probably not be fixed for a while.  

I have another problem on OSX where libgdx only plays a part of a particular wav sample (the same sample plays fine with libgdx  on iOS) and then stops but I'll wait with the bug report until you have tested this, because maybe it's the same root cause.

**Comment by MobiDevelop** [comment]
You have no loop driving the audio. You'll need to call OpenALAudio#update() from your game loop.

This modification to your sample loops correctly:

```java
public static void main(String[] args){
	LwjglNativesLoader.load();
	Files files = new LwjglFiles();
	OpenALAudio audio = new OpenALAudio();
	final Music music = audio.newMusic(files.internal("flowing_river2.wav"));
	music.setLooping(true);
	music.play();
	while (true) {			
		audio.update();
		try {
			Thread.sleep(15);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
	}
}
```

**Comment by robertmk** [comment]
Ah, OK. Thanks for the hint!
