### ISSUE TITLE
Pan does not work for Sound instances on OSX

### ISSUE THREAD

**Issue by robertmk** [libgdx/libgdx#3025]
Pan values seem to be ignored when playing back Sound instances on Mac OSX. Use the following code to reproduce:
```
import com.badlogic.gdx.Audio;
import com.badlogic.gdx.Files;
import com.badlogic.gdx.backends.lwjgl.LwjglFiles;
import com.badlogic.gdx.backends.lwjgl.LwjglNativesLoader;
import com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio;

public class GDXSoundPanDemo {
    public static void main(String[] args){
        LwjglNativesLoader.load();
        Files files = new LwjglFiles();
        Audio audio = new OpenALAudio();
        audio.newSound(files.absolute("/Users/krueger/sounds/loops/flowing_river.wav")).play(1, 1, 1);
    }
}
```
This should pan to the right but whatever value I use for pan, the sound is played in the center. Tested with libgdx 1.5.5 on OSX 10.10.2.

**Comment by MobiDevelop** [comment]
Pan seems to work fine for me on OSX. Perhaps your sound is a stereo sound?

**Comment by robertmk** [comment]
You are right. I was expecting this to work then as balance but that is probably an invalid assumption. Pan with mono samples seems to work fine. Sorry for the confusion.
