### ISSUE TITLE
Method not found: Array.put while running Android app

### ISSUE THREAD

**Issue by nunoflores** [libgdx/libgdx#3026]
While running Android app (via Eclipse+emulator), I have the following FATAL EXCEPTION:

E/AndroidRuntime(1279): java.lang.NoSuchMethodError: com.badlogic.gdx.utils.ArrayMap.put

Any ideias why?

Thanks

Cheers

**Comment by mk1x86** [comment]
This is a bug tracker, not a help desk. Either use the forum or ask on the irc channel. Without code we can't help you
