### ISSUE TITLE
build.gradle and Native libraries

### ISSUE THREAD

**Issue by obigu** [libgdx/libgdx#3027]
I've been trying to add a dependency on a 3rd party library that included a native .so library and I've found (as reported here https://github.com/libgdx/libgdx/issues/2733) that the task 

```
tasks.withType(com.android.build.gradle.tasks.PackageApplication) { pkgTask ->
    pkgTask.jniFolders = new HashSet<File>()
   pkgTask.jniFolders.add(new File(projectDir, 'libs'))
```

was deleting it and thus was not being included in the APK.

If I'm not wrong this task was the workaround for adding native dependencies before NDK support was added to the build tools on version 0.8. From 0.8 onwards it's possible to define the jndi libs folder for a project and the plugin takes care of the rest (see http://sysmagazine.com/posts/216353/).

In our case we can keep the current directory structure (necessary for Eclipse apparently) just by setting the jndiLibs folder to 'libs' in the sourceSets element
```
 sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            jniLibs.srcDir 'libs'
            ...
```

Now we can comment out/delete the task and let the plugin handle it
```
//tasks.withType(com.android.build.gradle.tasks.PackageApplication) { pkgTask ->
//pkgTask.jniFolders = new HashSet<File>()
 //pkgTask.jniFolders.add(new File(projectDir, 'libs'))
```

Sorry if I'm missing a specific case here, in my tests it works nicely.

**Comment by Tom-Ski** [comment]
Needs to be tested on all major IDE's with and without Gradle integration.
