### ISSUE TITLE
Trying to extend IOSApplication class

### ISSUE THREAD

**Issue by ne0conquer** [libgdx/libgdx#3028]
I'm trying to extend the IOSApplication class so I can create a custom UIWindow.  Can the fields be made protected so they can be accessible from my custom IOSApplication class?  The reason I'm trying to do this is here: http://www.badlogicgames.com/forum/viewtopic.php?f=15&t=19036

**Comment by mickmuzac** [comment]
Extending the IOSApplication class may be unnecessary in this situation (citation needed).

Couldn't you be able to fiddle around with [Viewports](https://github.com/libgdx/libgdx/wiki/Viewports) to achieve the same effect?

**Comment by Tom-Ski** [comment]
You're best off just using Viewports to solve this problem as suggested.
