### ISSUE TITLE
Sound class implementation needs optimization for Android L

### ISSUE THREAD

**Issue by StanDem** [libgdx/libgdx#3031]
On Nexus 5 with Android L loading sounds takes a lot of time. On devices with version <=4.4 everything is fine.
We have around 40 sound effects to load in our project. While it takes 3-4 seconds to load on most devices, on Android L it takes around 35 seconds. I think this is a major issue. 

According to google it appears this a know bug, but it can be fixed I guess:

https://androidbycode.wordpress.com/2015/02/04/nexus-lollipop-soundpool-load-not-so-sweet/
https://code.google.com/p/android-developer-preview/issues/detail?id=1812

**Comment by MobiDevelop** [comment]
I don't see any actual fixes in those links. What are you proposing?
