### ISSUE TITLE
Hiero v3.1 font kerning broken

### ISSUE THREAD

**Issue by darkfrog26** [libgdx/libgdx#3032]
I'm loading an existing TTF font into Hiero v3.1 (from nightly) and following the instructions here: https://github.com/libgdx/libgdx/wiki/Distance-field-fonts to generate a Distance field font (Open Sans Semibold 30 from Google Fonts using Scale 32, Spread 4.0, Padding 4, X -8, Y -8, Page width 512, Page height 256, NEHE) and the kerning is really screwed up:

http://pasteboard.co/2FCiPH85.png

I am simply displaying it using a Label in Scene2d. I'm loading libgdx from Maven version 1.5.6 (updated after I had this problem with 1.5.5 as well).

**Comment by darkfrog26** [comment]
I was able to use TWL Theme editor to create the same font (though it doesn't support Distance fields) and it renders perfectly.

**Comment by Darkyenus** [comment]
Does it occur when generating non-distance-field-fonts?

**Comment by darkfrog26** [comment]
Yes

**Comment by NathanSweet** [comment]
What Java version are you using? Are you loading the font from a file or by selecting it as a system font. Your screenshot is broken, try imgur.com.

**Comment by darkfrog26** [comment]
Using Java 8.

Here is the image: http://i.imgur.com/CzRHNy1.png?1

**Comment by NathanSweet** [comment]
Are you loading the font from a file or by selecting it as a system font?

**Comment by darkfrog26** [comment]
From a file.

**Comment by NathanSweet** [comment]
Ok, well, look in the .fnt file and see if it has kerning. Breakpoint in Hiero and see if it is reading the kerning.

**Comment by darkfrog26** [comment]
Are you guys not able to reproduce this?  If you can't then feel free to close the ticket, I've already migrated away from using Hiero.

**Comment by NathanSweet** [comment]
It would take a lot of time to go find the particular font you used, put in the same settings, and write an example that uses it, just to reproduce something that it seemed you have easily available.

FWIW, I use the BMFont tool because it does super sampling.

**Comment by BendedWills** [comment]
where did you get hiero 3.1
