### ISSUE TITLE
viewport.update(int screenWidth, int screenHeight, boolean centerCamera) doesn't use the first two parameter

### ISSUE THREAD

**Issue by panighetti** [libgdx/libgdx#3038]
This is the code from the Viewport.java ([source](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/viewport/Viewport.java#L64-L66))
```java
	/** Configures this viewport's screen bounds using the specified screen size and calls {@link #apply(boolean)}. Typically called
	 * from {@link ApplicationListener#resize(int, int)} or {@link Screen#resize(int, int)}.
	 * <p>
	 * The default implementation only calls {@link #apply(boolean)}. */
	public void update (int screenWidth, int screenHeight, boolean centerCamera) {
		apply(centerCamera);
	}
```

As you can see, the two parameters screenWidth and screenHeight are not used.

**Comment by Darkyenus** [comment]
That is not an issue, this method is overriden in Viewport subclasses. It is even javadoc'd that this only calls apply(boolean).
