### ISSUE TITLE
Audio PCM stutter on play (W/AudioTrack﹕ AUDIO_OUTPUT_FLAG_FAST denied by client)

### ISSUE THREAD

**Issue by robertodormepoco** [libgdx/libgdx#3042]
I'm developing a casual game with just few pcm sounds (i.e. 01.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, stereo 44100 Hz), my dev device is a Motorola Moto G (2 gen. AKA 2014) with Android 5.0.2, and every time i play one of the wav sounds they stutter (casually the play fine)
i've tested this in the 1.5.6 gdxVersion and the 1.5.7-SNAPSHOT
the only hint is that flag in the issue title, reading around it seems to be related to the low level client/server audio protocol mismatching in the communication (i.e. wrong sampling rate, checked it with the sdk preferences tool, nothing wrong)
i've also followed some path due to the known issue with the nuPlayer, without luck
last thought was about the deprecated use of the soundpool constructor vs the builder way

any help will be gold

thanks

p.s. i've tested this behaviour on another Motorola Moto G (2° gen), a 1° gen one and a Nexus 7 (all Lollipop, one with 5.0.1 too)

**Comment by wsrdzg** [comment]
Read this: http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=19041

**Comment by MobiDevelop** [comment]
Don't think there is anything to be done on our end about this.
