### ISSUE TITLE
Strange issue with Assetloader & TextureAtlas

### ISSUE THREAD

**Issue by voidstarfire** [libgdx/libgdx#3044]
I've noticed that some of my graphics/textures are black squares when I compile my app for iOS (Device & Simulator). Now I was thinking this is probably something todo with Power of Two on iOS? (some POT graphics work, other's don't)

For example, I have two circle textures as a test, one is 300x300 and one is 256x256.
I draw both of them the same size, but only the 300x300 works AND it's on the same TextureAtlas PNG..

It works on every Android device I can test on.

My Atlas packer settings are: (it does not allow PoT for individual textures on atlas)
```
TexturePacker.Settings tSettings = new TexturePacker.Settings();
        tpSettings.maxWidth = 2048;
        tpSettings.maxHeight = 2048;
        tpSettings.filterMag = Texture.TextureFilter.MipMapLinearNearest;
        tpSettings.filterMin = Texture.TextureFilter.Nearest;
        tpSettings.pot = true; //(for whole atlas)
        TexturePacker.process(tpSettings, args[0], args[1], args[2]);
```

When loading the asset with AssetManager
Note there is no option to set and params here. The TextureAtlasParam only contains one param = flip.
```
this.assetManager.load(DEFAULT_PACK, TextureAtlas.class);
```

I store my texture atlases like so (for static string retrieval)
```
//Get atlases
            TextureAtlas defaultAtlas = this.assetManager.get(SpriteLoader.DEFAULT_PACK, TextureAtlas.class);

            //Load in regions

            //Default regions (stored in an array.)
            atlasRegionObjectMap.put(DEFAULT_WHITE_CIRCLE, defaultAtlas.findRegion(DEFAULT_WHITE_CIRCLE));
```

After they are loaded and stored, I get them like this:
After they are loaded i retrieve sprites like so:

```
    public Sprite getSprite(String textureName)
    {
        return new Sprite(this.atlasRegionObjectMap.get(textureName));
    }
```

I render a sprite as such:
Update first:
```
this.sprite.setBounds(
                    getLeft() + (this.paddingX / 2f), //Left X
                    getBottom() + (this.paddingY / 2f), //Bottom Y
                    getWidth() - this.paddingX, //Right Width
                    getHeight() - this.paddingY //Top Height
            );
            this.sprite.setRotation(this.rotationDegree);
            this.sprite.setOriginCenter();
```
The Render:
```
if(!this.isInvisible && getAlpha() > ValueStorage.FLOAT_EPSILON && isOnScreen()){
            //Draw the sprite.
            this.sprite.setColor(getRGBA()[RED], getRGBA()[GREEN], getRGBA()[BLUE], getRGBA()[ALPHA]);
            this.sprite.draw(spriteBatch);
        }
```

I have tried with various different texture filters with no effect.

Any ideas?

**Comment by NathanSweet** [comment]
I'm not an iOS guy, but maybe it requires square textures?

**Comment by voidstarfire** [comment]
I have a wall texture that is 500x104 and that works.

**Comment by voidstarfire** [comment]
I managed to narrow this down, it's actually only one texture atlas (sprite map) that isn't working. In my app i use an atlas of reusable white textures the color them for simple things like circles and squares for menus and other shapes.

Still can't figure out why this is the only one showing black textures while everything else works.

Here's the image:
![image](https://cloud.githubusercontent.com/assets/6940726/7323095/89787196-eaac-11e4-8430-336cd5523a01.png)

And here the atlas:

default.png
size: 2048,512
format: RGBA8888
filter: Nearest,MipMapLinearNearest
repeat: none
debug_square
  rotate: false
  xy: 404, 120
  size: 282, 282
  orig: 282, 282
  offset: 0, 0
  index: -1
invisible_texture
  rotate: false
  xy: 1262, 274
  size: 128, 128
  orig: 128, 128
  offset: 0, 0
  index: -1
white_circle
  rotate: false
  xy: 2, 2
  size: 400, 400
  orig: 400, 400
  offset: 0, 0
  index: -1
white_square
  rotate: false
  xy: 990, 132
  size: 270, 270
  orig: 270, 270
  offset: 0, 0
  index: -1
white_triangle
  rotate: false
  xy: 688, 152
  size: 300, 250
  orig: 300, 250
  offset: 0, 0
  index: -1

**Comment by voidstarfire** [comment]
For some reason the image didn't upload, can find it here: 
https://imgur.com/DOnASvR

**Comment by voidstarfire** [comment]
Ok I have stumbled upon something quite weird could be a libGDX thing or an iOS thing.

ONLY on some iOS devices and Android devices the GPU has textures preloaded into the "default" atlas space name. If you load up the TextureAtlas and point it towards code such as:

```
//Not proper usable just an example
this.assetManager.load("default.atlas", TextureAtlas.class);
TextureAtlas menuAtlas = SpriteLoader.getInstance().getAssetManager().get(SpriteLoader.DEFAULT, TextureAtlas.class);
atlasRegionObjectMap.put(SHAPE,default.findRegion(SHAPE));
````

Then you get a pre-loaded texture pack that is only on some iOS devices and Android devices (Samsungs..) da-f***.

**Comment by titovmaxim** [comment]
@voidstarfire, in my experience iOS like square textures, like @xoppa says. 2048x512 is POT, but not SQUARE. And you have to get the assetManager chance to finish loading before getting the texture, I suppose.

**Comment by voidstarfire** [comment]
I found the issue. It's with LibGDX pre-loading assets into memory under the 'default.atlas' namespace.

**Comment by MobiDevelop** [comment]
Your comments about "pre-loading assets into memory under the 'default.atlas' namespace" doesn't make any sense. We don't pre-load anything that you don't specify to load. Please provide an [SSCCE](http://sscce.org/) showing the issue you are describing.

**Comment by voidstarfire** [comment]
If you use 'default' as the atlas name you'll find that on iOS this is
already taken up by the splash screen graphics. Just need to append
libgdx-default or something like that. I can post a demo up if you'd like.

**Comment by titovmaxim** [comment]
What kind of splash screen? LibGDX has no built-in splash. I think the
problem is in your code. Buy we can not help since there are no example
from you.
19 мая 2015 г. 14:19 пользователь "voidstarfire" <notifications@github.com>
написал:

**Comment by voidstarfire** [comment]
iOS has a loading splash. Make a new project from scratch, plug in you're
test iPhone, run it for device. First thing you'll see is the loading iOS
splash. This is loaded as default.atlas on all instances of internally
pointed asset managers.

**Comment by Tom-Ski** [comment]
Those are 'Launch Images', and they aren't anything to do with LibGDX.

**Comment by voidstarfire** [comment]
Yes I know but they are loaded into the asset manager, example from a fresh project:

```
 this.assetManagerInternal.load("default.atlas", TextureAtlas.class);
```

```
TextureAtlas defaultAtlas = SpriteLoader.getInstance().getAssetManagerInternal().get("default.atlas", TextureAtlas.class);
```

```
defaultAtlas.findRegion("any_texture") //<< This produces errors.
```

So when loading into the default atlas file it produces these errors. I was stuck on this for a while because at first it was certain that it was the launch image messing around with it. (was just black squares.)

But I guess if anyone else gets stuck on this they should see this post. So I'll close it?

**Comment by Tom-Ski** [comment]
They aren't loaded into any AssetManager unless you do it yourself.

**Comment by voidstarfire** [comment]
But that's the point, I was making a texture atlas called "default.atlas". I was unaware that iOS/LibGDX loads up "default.atlas" into the asset manager, so when I was retrieving regions from 'default.atlas' I was getting graphics errors. I'm making an example project now.

**Comment by Tom-Ski** [comment]
It doesn't do any such thing.

**Comment by badlogic** [comment]
An iOS app does indeed package a default.atlas file, which is not a libGDX
texture atlas. The easiest fix is to rename your own atlas file. The iOS
resources (launch screens, icons, etc.) And you games resources are likely
merged when the final app is packaged.

**Comment by voidstarfire** [comment]
Yes I now prefix all atlas names with the project name now.

**Comment by voidstarfire** [comment]
And anyone else having the same issue will stumble upon this post. So all good :+1:
