### ISSUE TITLE
fundamental ProgressBar behavior improvement suggestions

### ISSUE THREAD

**Issue by dermetfan** [libgdx/libgdx#3046]
_suggested labels: enhancement, scene2d_

I think there are some aspects of the ProgressBar's behavior that need to be addressed.

![progressbar](https://cloud.githubusercontent.com/assets/4956158/7299604/3a0be03c-e9d7-11e4-8078-b06694f7ed29.png)

Here's a (vertical) ProgressBar as reference to what I'm saying.

1. If the background of the ProgressBar is a NinePatchDrawable, the _knobBefore_ Drawable is not drawn over the unresizable parts of the background. I think it should be.  
In the image, the green fill is the _knobBefore_. Both the background and _knobBefore_ are NinePatchDrawables. To my knowledge, it is not possible to draw the _knobBefore_ from the very bottom to the very top of the ProgressBar, making a filling ProgressBar impossible unless you don't use a NinePatch as background. No NinePatch would mean round edges are always stretched over the whole ProgressBar though. So in effect you have to choose between either a filling ProgressBar with no round edges or a ProgressBar with round edges but ugly _knobBefore_.  
If the _knobBefore_ was drawn over the unresizable parts of the NinePatch background as well, this wouldn't be a problem. If the user doesn't want it to be drawn over these parts he could use a NinePatch _knobBefore_ with transparent parts, so no functionality is lost but only new added.  
This is of course also the case regarding _knobAfter_ which should go from the _knob_ to the very end of the ProgressBar, not just to the end of the resizable/inner part of the _background_ NinePatch.

2. The green rectangle is the actual size of the ProgressBar, set with  `bar.setWidth(200); bar.setHeight(500);`. Vertical ProgressBars only adjust to their height, horizontal ProgressBars only adjust to their width. In my opinion the user should be able to size them theirselves instead of being forced to have them look 140 pixels wide/tall regardless of their actual size.

What do you think about these suggestions?

_especially adressing ProgressBar authors @badlogic and @NathanSweet_

**Comment by NathanSweet** [comment]
1. The NinePatchDrawable uses the top/right/bottom/left sizes from the NinePatch, but you can set these yourselves. Set them to zero to get what you want.
2. You can size a progress bar however you like. 140 is an arbitrary pref size, because without a pref size the progress bar would have 0 width or height.

**Comment by dermetfan** [comment]
1. Ouch, that's embarassing. One never stops learning. Thanks!
2. That's what I thought. Unfortunately I can't seem to confirm it. Here's a test Screen showing that no matter if I use _setSize_ directly or size the ProgressBar using a Table, it appears to stay 140 pixels.

```java
package com.badlogic.gdx.tests;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.ProgressBar;
import com.badlogic.gdx.scenes.scene2d.ui.Skin;
import com.badlogic.gdx.scenes.scene2d.ui.Table;
import com.badlogic.gdx.tests.utilsGdxTest;

public class ProgressBarSizeTest extends GdxTestScreen {

	Stage stage;

	@Override
	public void create() {
		stage = new Stage();

		stage.setDebugAll(true);

		Skin skin = new Skin(Gdx.files.internal("data/uiskin.json"));

		ProgressBar bar = new ProgressBar(0, 1, .001f, true, skin);
		bar.setSize(200, 500);

		ProgressBar bar2 = new ProgressBar(0, 1, .001f, true, skin);

		Table table = new Table();
		table.setFillParent(true);
		table.add(bar2).size(200, 500);

		stage.addActor(bar);
		stage.addActor(table);

		Gdx.input.setInputProcessor(stage);
	}

	@Override
	public void resize(int width, int height) {
		stage.getViewport().update(width, height, true);
	}

	public void render() {
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		stage.act();
		stage.draw();
	}

	@Override
	public void dispose() {
		stage.dispose();
	}

}
```

**Comment by NathanSweet** [comment]
1. Not at all, it's not readily apparent what is going on.
2. Your executable example is missing a main method! I don't know what you see, but I see huge progress bars. http://i.imgur.com/nstFmfe.png

**Comment by dermetfan** [comment]
That is precisely what I see. Excuse my wording, I didn't mean the _actual_ Actor size but the size of the background within. I would have preferred to see something like this:

![bars](https://cloud.githubusercontent.com/assets/4956158/7309999/a14277f4-ea25-11e4-994b-ae5c1ac76ff0.png)

That would mean the background is sized to the Actor size. I see why this is not a good idea though: A Drawable has a min size but no max size. As it currently is, I can set the min size to get the result in the image above. However, since a Drawable has no max size, I would not be able to set said max size to go back to the result in your screenshot.

I guess `background.setMinWidth/Height(..)` is way to go then. Thanks for your time!

**Comment by NathanSweet** [comment]
I think probably you want the track to be a specific width (for a vertical slider) for aesthetics, but you might want the slider actor wider so it is easier to hit with a mouse/touch. You can have it either way with setMinWidth, as you found. Cheers!
