### ISSUE TITLE
Box2D: Box2DDebugRenderer Render call before RayHandler Render call.

### ISSUE THREAD

**Issue by CoderMusgrove** [libgdx/libgdx#3049]
Yesterday, I was working on re-learning Box2D, and I had a previous example before-hand. When I was doing this, I was having trouble rendering the fixture that I have created, and I had no idea why.

What it turned out to be was that I was calling code in this order:
```
box2dDebugRenderer.render(world, camera.combined);
rayHandler.render();
```

Calling the code this way, without having any *Light* objects in my *RayHandler* would keep my *Box2DDebugRenderer* from rending my *Body*.

Full *working* Code (if necessary):
```java
public class TestBox2D extends EGGame {

	int width;
	int height;

	static final Vector2 ZERO_GRAVITY = new Vector2(0f, 0f);

	OrthographicCamera camera;
	World world;
	Body body;
	Box2DDebugRenderer box2dDebugRenderer;
	RayHandler rayHandler;
	Array<Body> bodies;

	public TestBox2D(EGVersion version, String dataFolderName, LwjglApplicationConfiguration config) {
		super(version, dataFolderName, config);
	}

	@Override
	protected void init() {
		width = Gdx.graphics.getWidth()/4;
		height = Gdx.graphics.getHeight()/4;
		camera = new OrthographicCamera(width, height);
		camera.position.set(width / 2, height / 2, 0);
		camera.update();

		world = new World(ZERO_GRAVITY, true);
		box2dDebugRenderer = new Box2DDebugRenderer();
		rayHandler = new RayHandler(world);
		rayHandler.setCombinedMatrix(camera.combined);

		BodyDef bodyDef = new BodyDef();
		bodyDef.type = BodyDef.BodyType.StaticBody;
		 bodyDef.position.set(width / 2, height / 2);

		body = world.createBody(bodyDef);

		CircleShape shape = new CircleShape();
		shape.setRadius(1f);

		FixtureDef fixtureDef = new FixtureDef();
		fixtureDef.shape = shape;
		body.createFixture(fixtureDef);

		bodies = new Array<>();
		
//		new PointLight(rayHandler, 500, Color.GREEN, 50, 20, 20);
	}

	@Override
	protected void updateGame() {
		world.step(1f / 30f, 6, 2);
		world.getBodies(bodies);
		rayHandler.update();
	}

	@Override
	protected void renderGame() {
//		rayHandler.render();
		box2dDebugRenderer.render(world, camera.combined);
	}

	@Override
	public void dispose() {
		world.dispose();
	}

	public static void main(String... args) {
		new TestBox2D(null, null, new LwjglApplicationConfiguration());
	}
}
```

**The Issue is**:

When rendering, if the code is called like:
```java
box2dDebugRenderer.render(world, camera.combined);
rayHandler.render();
```
and there are no *Light* objects associated with the *RayHandler*, the *Box2DDebugRenderer* doesn't render (at least) the fixtures.

**Comment by MobiDevelop** [comment]
So... What exactly is the issue you are reporting?

**Comment by CoderMusgrove** [comment]
When rendering, if the code is called like:
```java
box2dDebugRenderer.render(world, camera.combine);
rayHandler.render();
```
and there are no *Light* Objects associated with the *RayHandler*, the *Box2DDebugRenderer* doesn't render (at least) the fixtures.

**Comment by MobiDevelop** [comment]
Box2DDebugRenderer knows nothing about lights. Perhaps you filed this issue
on the wrong tracker?

**Comment by CoderMusgrove** [comment]
I thought there would have been an issue with this. If there is a better place to report this, please tell me.

The reason I reported it as so is because just swapping those two lines will allow the Box2DDebugRenderer to function as expected, if that makes sense.

This works as expected:
```java
rayHandler.render();
box2dDebugRenderer.render(world, camera.combined);
```

While this doesn't (if the RayHandler has no Light objects to work with):
```java
box2dDebugRenderer.render(world, camera.combined);
rayHandler.render();
```

**Comment by MobiDevelop** [comment]
It is probably more suitable at the box2dlights issue tracker as the
problem is more likely to be there.

**Comment by nooone** [comment]
Does it render the fixtures if you completely remove the `RayHandler` and all other box2dlights specific things? If so, this is definetely the wrong place for this issue. Try it at https://github.com/libgdx/box2dlights/issues

**Comment by Tom-Ski** [comment]
^
