### ISSUE TITLE
Random performance issue with box2d

### ISSUE THREAD

**Issue by neopraveen** [libgdx/libgdx#3052]
HI,
About my game - 
It is a super Mario type game using box2d. I am using rube to design and load my level. It is also available on playstore - https://play.google.com/store/apps/details?id=com.pieteams.the.exit.gate

About the Problem - 
The performance of game is random. The rendering sticks most of the time. The strange point is, if their is an issue and I put the game background and again brings to foreground the game goes smooth (some time). First I was checking for memory leaks, but the problem is reproducible in the very first launch(I think memory leak can't reproduce in very first launch).
I diagnose the issue using debugger, but the memory is not increasing after many of relaunches.

Test device used - 
Samsung Grans Quattro(Quad-core processor with 1 GB ram)
iPhone 5c(The Robovm build produces same issue)

Moto-G (game performance is better than other.)

Sorry for my bad english.

**Comment by xoppa** [comment]
This is an issue tracker. Go to the forum or irc if you need help. https://github.com/libgdx/libgdx/wiki/Getting-Help
