### ISSUE TITLE
OnePlusOne 4.4.4 music setLooping bug

### ISSUE THREAD

**Issue by souldown** [libgdx/libgdx#3065]
Hi,Theres a playback bug with setLooping.
Its on OnePlusOne phone - cynagen mod (11.0-XNPHO5Q) 64gb model A0001 android 4.4.4.
It has to do with using the Music class, particularly the .setLooping method. 

Basically after you set a track looping, after some time, it goes quiet, then the libgdx activity freezes. 

Ive grabbed a Gist from ADT - https://gist.githubusercontent.com/souldown/1c9b9bb6a392def5d996/raw/Audio%20mutes

It seems like something is going a bit odd with the audio on the phone (not just my activity) then at 04-27 09:31:21.667 it goes mute and just outputs E/AudioPlayerï¹• Ignore seek and post seek complete. Then when the audio track gets to the end to be looped, the app freezes. Although the log cat still just writes the same message (above) over again.

Ive also tried using wav, mp3 and ogg.
Tried not using the asset manager.
the music track is 1:15 long.

I also posted in the badlogic forumns about this bug but had no help there, just another user with the same issue (http://www.badlogicgames.com/forum/viewtopic.php?t=19156)

**Comment by MobiDevelop** [comment]
I'm afraid that a device specific bug on a custom rom isn't going to be something we can do anything about.

**Comment by souldown** [comment]
Thanks Mobi, Its annoying because its my phone so i play test a lot on this device and its a bit of a shitty bug that crashes the app. Thanks for the info.

**Comment by souldown** [comment]
Okay i flashed my phone with the Oxygen loader. bugs gone. Looks like a compatibility thing with cynagen mod :(
