### ISSUE TITLE
Simpler method to rotate Textures

### ISSUE THREAD

**Issue by graham01** [libgdx/libgdx#3067]
Hello!

There is currenty one SpriteBatch.draw method that allows rotation of Textures which requires many other variables to be sent to the method. Currently it is easier to put the Texture into a Sprite and then setOrigin and setRotation at render time. It would be nice if there was an easier solution for just rotating Textures, e.g.

SpriteBatch.draw(Texture texture, float x, float y, float originx, float originy, float rotation(degrees));

Hope this is a good suggestion :)

**Comment by MobiDevelop** [comment]
We already have a ton of draw methods on the Batch interface. We can't keep adding them for every use case. You should use a sprite, or make a utility method for yourself that you can call from your code that hides the additional parameters.

**Comment by NathanSweet** [comment]
Agreed.
