### ISSUE TITLE
SpriteBatch.draw not correct or documentation wrong

### ISSUE THREAD

**Issue by gmgunderground** [libgdx/libgdx#3068]
I'm using Android, I have to rotate a TextureRegion but the point of rotation originX and originY is not relative to the screen space coordinates but relative to x and y coordinates.

For example: if I put my image at 100, 100 (image with=10, image height=10) and I want to rotate it on its center I have to put originX and originY at 5,5 but as I understand from documentation originX and originY must be 105,105

originX - the x-coordinate of the scaling and rotation origin relative to the screen space coordinates
originY - the y-coordinate of the scaling and rotation origin relative to the screen space coordinates

I'm doing somthing wrong or I have understand something wrong or is a libgdx bug?

Tanks

**Comment by NathanSweet** [comment]
It works correctly. The origin is relative to the screen space drawing coordinates (ie, the x,y you specified for where to draw the region).
