### ISSUE TITLE
x/y rounding causes text jumps in Label

### ISSUE THREAD

**Issue by FyiurAmron** [libgdx/libgdx#3070]
https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Label.java#L181
https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Label.java#L195

Both `width`, `height`, `textWidth` & `textHeight` are float values. With e.g. https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Label.java#L179 , this causes desired behaviour - the actual positioning of the text is linearly dependent on those values. However, when L181 is triggered, the average is clamped to int, resulting in accuracy loss & discrete, nonlinear jump - extremely visible when the positioning is done in e.g. (0,0)-(1,1) coordinate system.

The simplest way to reproduce it is to tween the font scale of label from e.g. 0.001 to 0.1 in such coordinate system - it will trigger a "jump" in e.g. Y direction each time when a treshold value has been reached.

Proposed solution is to drop the `(int)` casting in both of those lines or to provide an explicit way to trigger that behaviour, i.e. no truncation on the floats. Dropping the casts fixes the issue without any apparent side-effects.

Note: I am aware of the `BitmapFont#setUseIntegerPositions( boolean integer )` etc. If the truncation is provided here for the same or similar reason (doubful, since e.g. L179 does no such rounding), it still should be possible to disable the rounding in a similar way here.

**Comment by NathanSweet** [comment]
That looks right, thanks!
