### ISSUE TITLE
no support for BMFont's (.fnt) padding - xHeight & capHeight invalid for padded fonts

### ISSUE THREAD

**Issue by FyiurAmron** [libgdx/libgdx#3074]
Current BitmapFont.java implementation just ignores the `padding=` field; it makes using fonts with e.g. shadow/glow very hard, since both *xHeight* & *capHeight* are calculated based on actual texture size, not the size minus padding one. Since for shadowed/glowed fonts the texture size is often 2-3x bigger than the proper *xHeight*/*capHeight* calculated from of the "core" of the glyph, this results in very poor vertical positioning of the glyphs during text compositing (i.e. it's almost impossible to calculate where the actual glyph will appear due to offseting from padding). Horizontal positioning is unaffected, since it's directly based on raw .fnt data.

The solution I used to work around this was replacing https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g2d/BitmapFont.java#L472 line with
```
// private static final int paddingCount = 4;
                String line = reader.readLine();
                String keyword = "padding=";
                String substr = line.substring( line.indexOf( keyword ) + keyword.length() );
                String[] paddingStr = substr.substring( 0, substr.indexOf( ' ' ) ).split( ",", paddingCount );
                if ( paddingStr.length != paddingCount ) {
                    throw new IOException();
                }
                int[] padding = new int[paddingCount];
                for( int i = 0; i < paddingCount; i++ ) {
                    padding[i] = Integer.parseInt( paddingStr[i] );
                }
                // up, right, down, left
                int paddingHorizontal = padding[1] + padding[3], // currently unused
                        paddingVertical = padding[0] + padding[2];
```
and then, in lines 606 through 628, all occurences of `xGlyph.height`/`capGlyph.height`/`glyph.height` with the respective `.height - paddingVertical`.

I don't know if this is the best way to do this, but it seems that it fixes the issue. Any suggestions/patches are most welcome.

**Comment by NathanSweet** [comment]
How can I see the issue?

**Comment by FyiurAmron** [comment]
a) load a font with a significant amount of padding (example here http://www.filedropper.com/caviarshade (.fnt) & http://www.filedropper.com/caviarshade_1 (.png)),
b) call e.g. `getXHeight()`, `getCapHeight()` or `getAscent()` (the last one based directly on capHeight) and try to use the values returned in any sensible way; it's impossible, since the values will not account for vertical padding. The heights will be about 2x the actual values. OTOH, `getDescent()`, `getDown()` & `getBaseline()` are completely correct and usable, since they are based on the raw .fnt data (`lineHeight`, `base=`, `yOffset=`). As a result, you can't determine the actual (usable) xHeight, capHeight & ascent based just on BitmapFont.in this case.

**Comment by NathanSweet** [comment]
Thanks. You can see the issue most easily in BitmapFontMetricsTest. I've committed fixes so font metrics are not affected by padding. Some fixes where needed for glyph layout, because glyph width contains padding and glyph xoffset only negates `padLeft`.

I do think the changes are good, but they most likely break all libgdx apps that use fonts with padding -- text will be drawn in a slightly different place and take up less space in both directions. The fastest way to fix this is to go back to the old behavior, which can be done with this:

```java
/** Adjusts the font data metrics to not take padding into account. */
static private void includePaddingInMetrics (BitmapFontData fontData) {
	float padY = fontData.padTop + fontData.padBottom;
	fontData.xHeight += padY;
	fontData.capHeight += padY;
	fontData.ascent -= padY;
	fontData.descent -= fontData.padBottom;
	fontData.padTop = 0;
	fontData.padLeft = 0;
	fontData.padBottom = 0;
	fontData.padRight = 0;
}
```

**Comment by NathanSweet** [comment]
[Blahrged.](http://www.badlogicgames.com/wordpress/?p=3678)

**Comment by FyiurAmron** [comment]
![We Are Just So Friggin Awesome](http://www.troll.me/images/business-cat-needs/good-job.jpg)
