### ISSUE TITLE
IOSInput#getTextInput doest't implement I18N

### ISSUE THREAD

**Issue by panli32811** [libgdx/libgdx#3084]
The two buttons are named "Cancel" and "OK".

**Comment by Tom-Ski** [comment]
Eh, not sure what the best resolution for this is.  We don't implement I18N in core at all, and there are a few places where it could. Exposing fields or adding method arguments to specify these strings feels ugly. 

Should LibGDX have some base implementation of I18N ? @xoppa @MobiDevelop @NathanSweet @badlogic

**Comment by badlogic** [comment]
If you need I18N you'll have to bite the bullet and write native iOS/Android code for native dialogues.
