### ISSUE TITLE
elasticOut kinda broken

### ISSUE THREAD

**Issue by vlaaad** [libgdx/libgdx#3086]
I made a small demo to see difference between interpolations, you can see output here:
![Interpolations in action](http://i.imgur.com/iIrlat3.png)
AFAIK, interpolation's purpose is interpolating value from 0 to 1 in a fancy way. I think, it should be a rule that for every `a == 0`, interpolated value of `a` will be 0, and for every `a == 1`, interpolated value of `a` will be 1. This applies to every interpolation except elasticOut.

How to reproduce:

``` java
    System.out.println(Interpolation.elasticOut.apply(0)); //prints 1.0000001
```

**Comment by NathanSweet** [comment]
Floating point works this way. I guess we can special case elasticOut.

See InterpolationTest for visuals.
