### ISSUE TITLE
[BUG] GestureDetector/GestureListener gets coordinates of the previous touch up event

### ISSUE THREAD

**Issue by mfronczyk** [libgdx/libgdx#3093]
I've noticed that my game doesn't react to mouse clicks when the game window gets focus. It's because my touchUp handler receives x and y of the previous click. Since the game already performed the action in the previous location, it looks like it doesn't react. This only happens when you don't move the cursor after the window gets focus. If after the initial click (the one to bring focus to the game window) you move the cursor a bit and click again, it works fine. It just doesn't work when you switch from another app and you want to click somewhere in the game window without moving the cursor after the first click that brings focus to the game.

LibGDX - 1.5.6
OS: OS X Yosemite
JVM: 1.8.0_31
Game type: Desktop

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/Getting-help#executable-example-code
