### ISSUE TITLE
Label's bounds works incorrect when updating to 1.5.6

### ISSUE THREAD

**Issue by panli32811** [libgdx/libgdx#3095]
If I use markup color, the label become to:
![8e37850a-5c09-460e-9bad-5c065184ff9b](https://cloud.githubusercontent.com/assets/8217836/7492400/59b180ce-f42a-11e4-9858-17cf5fb7fc32.png)

my code are written below:
<code>

		BitmapFont font = new BitmapFont(Gdx.files.internal("data/1.fnt"));
		font.getData().markupEnabled = true;
		label = new Label("color[#ff0000]oddsggfhgfjghfjjy[]", new LabelStyle(font, Color.WHITE));
		label.setWrap(true);
		label.setBounds(300, 300, 200, 100);
		addActor(label);
		label.debug();
</code>

**Comment by panli32811** [comment]
And in ver1.6.0, it's more strange:
![tmp3c82638b](https://cloud.githubusercontent.com/assets/8217836/7507790/e6b32e32-f4a7-11e4-9bab-72b5854d4afa.png)

**Comment by NathanSweet** [comment]
The color change is considered a valid wrap point, so the latest behavior is correct.

**Comment by panli32811** [comment]
But why the color became green?
