### ISSUE TITLE
When more than 3 fingers pressed simultaneously, InputProcessor work incorrectly

### ISSUE THREAD

**Issue by ygdx** [libgdx/libgdx#3098]
On android, InputProcessor should call touchDown() three times, but instead it call touchDown() twice and touchUp() once.

On iOS, if 4 fingers pressed simultaneously, InputProcessor will cause the game to quit.

Please look into this issue.

**Comment by MobiDevelop** [comment]
On my Android device (Nexus 5) and can touch with all my fingers and get 10 touchDown and 10 touchUp calls. Perhaps your device has broken multitouch.

Can't test on iOS as I have no device.

**Comment by ygdx** [comment]
If I do touch down one finger after another, it will work.  But all three fingers same time, it will call touchDown() 2 times and touchUp() 1 time.  And when I lift up my 3 fingers, no touchUp() is called.  Tried this on HTC One M7 and LG-V400 same symptom.

**Comment by Tom-Ski** [comment]
What version of LibGDX are you using? This happens on HTC due to multi gestures breaking multi touch. see https://github.com/libgdx/libgdx/issues/2622

**Comment by ygdx** [comment]
My Libgdx is 1.4.1.  Probably I should try higher version?
This also happens on LG-V400, thought not as frequent on HTC.  about 9 press out of 10 will behave normally, and 1 will process differently.

Did a little debugging.  I found that such touch event was captured in AndroidMultiTouchHandler.java, which captures the MotionEvent.java class defined in Android SDK.  When screen is touched, android sdk will send MotionEvent to AndroidMultiTouchHandler.  then AndroidMultiTouchHandler.java will consider MotionEvent.ACTION_DOWN and MotionEvent.ACTION_POINTER_DOWN as touchDown event, and case MotionEvent.ACTION_UP, MotionEvent.ACTION_POINTER_UP, MotionEvent.ACTION_OUTSIDE, MotionEvent.ACTION_CANCEL as touchUp event.

The values of these event are given below:
MotionEvent.ACTION_DOWN                    =0 
MotionEvent.ACTION_POINTER_DOWN  =5
MotionEvent.ACTION_UP                           =1
MotionEvent.ACTION_POINTER_UP         =6
MotionEvent.ACTION_OUTSIDE                =4
MotionEvent.ACTION_CANCEL                 =3
MotionEvent.ACTION_MOVE                     =2

I placed this segment of code into AndroidMultiTouchHandler.java (Only the System.out.println line)
                ....
		synchronized (input) {
			System.out.println("AndroidMultiTouchHandler switch on action " + action);
			switch (action) {
			case MotionEvent.ACTION_DOWN:
                ....

And I found with 3 fingers press at the same time, it will show:
AndroidMultiTouchHandler switch on action 0
AndroidMultiTouchHandler switch on action 5
AndroidMultiTouchHandler switch on action 3

Meaning Android believe that we first have a ACTION_DOWN, then a ACTION_POINTER_DOWN, then a ACTION_CANCEL.

Probably android thinks the third finger cancel the possibility of zoom?  Anyway, if android fire event this way, libgdx will always consider that as two touchDown and one touchUp, as defined in AndroidMultiTouchHandler.java.

At this point, I am not quite sure how to fix it.

**Comment by Tom-Ski** [comment]
That means that your other device is also picking up some kind of gesture.  I don't think there is anything we can do about devices not passing on their touch events correctly.  

I tested this on iOS, no issue.  You should supply a self executing example with the latest LibGDX and RoboVM that reproduces the issue.

**Comment by ygdx** [comment]
Thank you Tom-Ski.  Looks like that's the same issue.  Did we fix it in later libgdx?  right now I just switched off HTC's media gesture.

**Comment by Tom-Ski** [comment]
The out of bounds crash was fixed, you still wont get correct multi touch if you have media gestures enabled. This is in all apps btw, not just LibGDX.

**Comment by ygdx** [comment]
Got it thanks.  I will do more iOS testing to make sure.  Maybe my app crashed for other reason.

**Comment by Tom-Ski** [comment]
Feel free to re-open if you can provide a [http://sscce.org/](http://sscce.org/)

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://consea.com.br/peer.php?14>

 

loogie@basicelementdesign.com

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://essential-organizer.com/conscious.php?8gdzo>

 

loogie@basicelementdesign.com

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://jubilingostoryperformers.com/qualify.php?qf>

 

loogie@basicelementdesign.com
