### ISSUE TITLE
Setup on Windows 8 Fails

### ISSUE THREAD

**Issue by IcanBENCHurCAT** [libgdx/libgdx#3103]
I have the android SDK installed in the default location (if you let Android Development Studio install it) on a Windows 8 machine. This is in C:\Users\username\AppData\...

When I go to browse for it, the AppData folder does not appear in the folder chooser dialogue.
If I manually type the entire path instead of browsing, it says that no SDK exists or is missing features.

**Comment by MobiDevelop** [comment]
Sounds like a system configuration problem. I have Windows 8.1 and the setup works correctly for me.

Please use the forums or irc for questions and help.
