### ISSUE TITLE
Removing final Pointlight from and Environment removes DirectionalLight attribute V1.6.1 nightly

### ISSUE THREAD

**Issue by Dogflaps** [libgdx/libgdx#3104]
Line 121 [Environment.java]
(https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g3d/Environment.java)

removing the last pointlight will remove the directional light attribute. Should this be the pointlight attribute?

**Comment by xoppa** [comment]
Thanks, good catch! Should be fix now.
