### ISSUE TITLE
Plane miss no-arg constructor

### ISSUE THREAD

**Issue by GhostNr1** [libgdx/libgdx#3111]
In com.badlogic.gdx.math.Plane there are a missing no-arg constructor.

**Comment by FyiurAmron** [comment]
Hm. And what exactly would you expect a no-arg Plane constructor to do? To define a plane, you need at least 2 vectors - v0 & normal. While you can assume v0 = 0, you can't have a "default" normal, because no R3 normal is "default" - and you can't have a "0" normal.

**Comment by Darkyenus** [comment]
It would be useful for serialization and when preallocating with no valid value in mind.

**Comment by FyiurAmron** [comment]
@Darkyenus You ninja'd me - 100% true, I've just though of that about 15 seconds before your answer *duh*
