### ISSUE TITLE
Libgdx non continuous rendering with saving prefs

### ISSUE THREAD

**Issue by raicabogdan** [libgdx/libgdx#3112]
A simple case I find really stupid, probably me not doing something, but anyway asking just in case. Docs on github don't say much regarding non-continuous rendering about this.

Basically what I do is saving 1 score at a time (one per game) in the prefs file and then getting the score back to store them in variable. I probably should just update the values from the already stored values in variable(thinking now ..., will probably do that).

The issue however is when saving the prefs. Its causing the render to not trigger on input (from docs a render should trigger when an input event is triggered). If I remove the prefs part, the render works fine.

Also if I re-enable continuous rendering using

```` Gdx.graphics.setContinuousRendering(true); ````

before the prefs saving method, then its still not working. Really lost on this one.

However if leaving continuous rendering in place, it seems to work fine. It also works fine if I send another touch input, just that first one seems to be blocking something.

What am I doing?

The code I use for the Prefs:
````
@Override
public void saveScore(String type, int value) {
    preferences.putInteger(type, value);
    preferences.flush();
}

@Override
public HashMap<String, Integer> getScore() {
    scores = new HashMap<String, Integer>(3);

    scores.put("wins", preferences.getInteger("wins", 0));
    scores.put("draws", preferences.getInteger("draws", 0));
    scores.put("losses", preferences.getInteger("losses", 0));

    return scores;
}
````
I just hope I didn't hit some bug with it, also I would really like to keep the non-continous rendering, its just a simple board game, so the things are mostly static.

Thank you!

**Comment by NathanSweet** [comment]
I'm unable to make sense of what the issue is.
https://github.com/libgdx/libgdx/wiki/Getting-help

**Comment by raicabogdan** [comment]
Yes, sorry about that. was about 5am and I was a walking zombie at the time...

I tried making a simple / proper test case, but it seems it was working just fine. Then checked my code again and thought instead of using ``` Gdx.graphics.setContinuousRendering(true); ```, I should just request rendering in the render method if the game ended and until I regenerate a new instance of the game. And sure enough, I was getting the expected result. I think my delays in some of the logic of the game was affecting the rendering request that libgdx is doing by default on touch input being triggered, since its only doing one render request, and delay was set to about 2 seconds, the frame rendering was already done / ended while the actions were still delayed, thus I was seeing that issue and needed another touch input for render to trigger.

That makes more sense now I guess? Hopefully it will help someone else if he's using non-continuous rendering and using delays in some of the game actions.

Thanks tough for your reply.
