### ISSUE TITLE
Docs claim PixmapIO.PNG instances are reusable, but they are not

### ISSUE THREAD

**Issue by ttencate** [libgdx/libgdx#3113]
The JavaDoc for `PixmapIO.PNG` says: `An instance can be reused to encode multiple PNGs with minimal allocation.` However, this doesn't work, because the deflate stream is closed in the `write` method [here](https://github.com/libgdx/libgdx/blob/6f101b16ae8816405f05e935ee9cb622dbd59e05/gdx/src/com/badlogic/gdx/graphics/PixmapIO.java#L306).

I suppose the deflater cannot be reused, but then this class needs some more work. Or the claim about reusability could simply be removed.

**Comment by NathanSweet** [comment]
DeflaterOutputStream `finish`: Finishes writing compressed data to the output stream without closing the underlying stream. Use this method when applying multiple filters in succession to the same output stream.

What is the problem?

**Comment by ttencate** [comment]
Hmm, so I can only reproduce this on Android, not desktop. Nexus 7, Android 4.4.4, build KTU84P. This is what happens:
```
W/System.err( 5680): java.io.IOException: attempt to write after finish
W/System.err( 5680):    at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:172)
W/System.err( 5680):    at java.io.OutputStream.write(OutputStream.java:82)
W/System.err( 5680):    at libcore.io.Streams.writeSingleByte(Streams.java:53)
W/System.err( 5680):    at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:161)
W/System.err( 5680):    at com.badlogic.gdx.graphics.PixmapIO$PNG.write(PixmapIO.java:298)
W/System.err( 5680):    at com.frozenfractal.bigcanvas.PngUtils.toPng(PngUtils.java:21)
W/System.err( 5680):    at com.frozenfractal.bigcanvas.TileManager.sendDelta(TileManager.java:95)
W/System.err( 5680):    at com.frozenfractal.bigcanvas.TileManager.maybeSendDeltas(TileManager.java:79)
W/System.err( 5680):    at com.frozenfractal.bigcanvas.Bigcanvas.render(Bigcanvas.java:111)
W/System.err( 5680):    at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
W/System.err( 5680):    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1523)
W/System.err( 5680):    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```

I found that phrase [here](https://github.com/google/j2objc/blob/592382e0bf314134fac9bfee862dacca50fccdb1/jre_emul/android/libcore/luni/src/main/java/java/util/zip/DeflaterOutputStream.java#L172), so it might actually be an Android bug :( If so, let's figure out a workaround.

**Comment by NathanSweet** [comment]
Looks like Android is broken. Want to make a PR that recreates the DeflaterOutputStream if Gdx.app.type is Android?

**Comment by ttencate** [comment]
That's the least I can do for filing crappy bug reports against you :)

**Comment by ttencate** [comment]
Android devs say this is working as intended. To play it safe, I'll update my PR tonight (CEST) to always recreate the stream.

**Comment by badlogic** [comment]
do you have a link to the android devs stating that?

**Comment by ttencate** [comment]
See above: https://code.google.com/p/android/issues/detail?id=172620

**Comment by FyiurAmron** [comment]
Hm. As I understand the `#finish()` docs, it only mentions not closing the *underlying* Stream (i.e. the one passed in e.g. https://docs.oracle.com/javase/7/docs/api/java/util/zip/DeflaterOutputStream.html#DeflaterOutputStream%28java.io.OutputStream%29 constructor), not the `this` DOStream itself. The DOS will be (and should be, as per AH tests) invalid for output after `#finish()`; `PNG.write()` *does* close the underlaying DOS before return though. I think that being able to re-use it in this matter on a desktop is a code artifact at best.

**Comment by ttencate** [comment]
That was also my conclusion. I've updated the PR accordingly.

**Comment by NathanSweet** [comment]
The javadocs don't say it can't be reused and it can be reused on desktop.
We should special case for Android, who seem to have implemented it wrong.

Hm. As I understand the #finish() docs, it only mentions not closing the
*underlying* Stream (i.e. the one passed in e.g.
https://docs.oracle.com/javase/7/docs/api/java/util/zip/DeflaterOutputStream.html#DeflaterOutputStream%28java.io.OutputStream%29
constructor), not the this DOStream itself. The DOS will be (and should be,
as per AH tests) invalid for output after #finish(); PNG.write() *does*
close the underlaying DOS before return though. I think that being able to
re-use it in this matter on a desktop is a code artifact at best.

—
Reply to this email directly or view it on GitHub
<https://github.com/libgdx/libgdx/issues/3113#issuecomment-101363163>.

**Comment by FyiurAmron** [comment]
>The javadocs don't say it can't be reused
That's exactly the point. It also doesn't say it *can* be reused after it - as such, it creates an obvious implementation dependence since it's an artifact, not a guaranteed API feature. Relaying on implementation-dependent behaviour, not guaranteed by API's contract is the easiest way to create WTFs as soon as the underlying lib implementation details change for any reason.

>who seem to have implemented it wrong.
I agree that the docs are ambiguous here, and I agree that `#finish()` *shouldn't* close the DOS for the convenience of API user - and that Android has taken the inconvenient route here... however without any explicit JDK doc reference stating that it indeed *can* be reused, we're basing the code on implementation details, not the API itself. It's your call, one way or the other, and I'm not saying that https://code.google.com/u/100542696791565253700/ has to be right on this, because the interpretations may vary. I'm just saying that relaying on UB is always a high risk strategy in my book.

**Comment by MobiDevelop** [comment]
I would generally interpret a method called `finish` to mean "I am done with this and won't be using it again", so would expect to not be able to use it again. Further, I'd imagine that "minimal allocation" is not a huge requirement when writing images and the creation of a new DeflaterOutputStream is .

Based on discussion here and my agreement that relying on undefined behavior is risky, I'd be in favor of merging the PR without special casing Android.

**Comment by NathanSweet** [comment]
If a method has a side effect that leaves the object in an unusable state, that *must* be in the method contract / javadoc. I'd say it is a reasonable assumption, given the rarity and importance of that side effect, that if a method does *not* specify this that the object is still in a usable state, regardless of the method name. There is no undefined behavior here. The javadocs don't say the object is no longer usable, so an implementation that makes it no longer usable is wrong.

That said, I agree the allocation isn't a big deal. To workaround the poor implementation, I'm fine with not special casing stupid Android. :)

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://igooprint.com/instant.php?i>

 

loogie@basicelementdesign.com
