### ISSUE TITLE
gradlew android:assembleRelease

### ISSUE THREAD

**Issue by panli32811** [libgdx/libgdx#3114]
After done, the APK generated doesn't include the resources from src in "core", but if they come from the 3rd jar, will be included

**Comment by Tom-Ski** [comment]
What resources are you talking about?

**Comment by panli32811** [comment]
Not source code, maybe lua script

**Comment by Tom-Ski** [comment]
Ok well this is all very vague.  You should try the forum for help with configuring your project to your specific needs, this is an issue tracker.
