### ISSUE TITLE
Sprite.getOriginX() & Sprite.getOriginY functions returns in pixels

### ISSUE THREAD

**Issue by ebattal** [libgdx/libgdx#3115]
When you call getOriginX() or getOriginY() functions of a Sprite, it returns the X or Y values in pixels but actually it should return with respect to the sizes defined in setSize(float width,float height) function.

Workaround : 
float originX = getX()+getWidth()/2;
float originY = getY()+getHeight()/2;

Edit: Example
Texture t = new Texture(Gdx.files.internal("data/sprite.png"));  // 256 pixels by 256 pixels
Sprite target = new Sprite(t);
target.setSize(5,5);
float x1 =  target.getOriginX();  // returns 128 (meaning that the results are in pixels)
float y1 = target.getOriginY(); //returns 128

float x2 = target.getWidth()/2; //returns 2.5 (relative to what`s defined in setSize(float,float)
float y2 = target.getHeight()/2; // returns 2.5

**Comment by MobiDevelop** [comment]
Please provide an example showing an issue. As far as I can tell, it works exactly as intended. You should be calling setOrigin after setSize if you want the origin to change.

**Comment by ebattal** [comment]
don`t getOriginX and getOriginY return the center of the pixels using the scales in defined setSize(float,float) relative to the bottom left edge of the sprite?

**Comment by xoppa** [comment]
No it doesnt. Both the size and origin are in world units (virtual viewport units if you like), they are not in pixels. You can set them to whatever you like, they are not directly related to each other. In fact, the documentation says that is slightly more efficient to change the origin *prior* to changing the size. If `setSize` would change the origin as well it should be called `setSizeAndOrigin`.

Please note that this is an issue tracker. If you need help using the API then use the forum or irc. See https://github.com/libgdx/libgdx/wiki/Getting-Help.
