### ISSUE TITLE
GWT reflection adjustments

### ISSUE THREAD

**Issue by czyzby** [libgdx/libgdx#3116]
Method#isAnnotationPresent seems to throw exception when tested method does not have any annotations.

Would it be a problem to include an array (of Type/Class) with all types present in the generated GWT reflection pool? I think that such an array wouldn't be an issue (especially if you also let the user clear it or completely disable its creation).  Well, I won't lie that - after you implemented method annotations - it would allow me to implement GWT class scanning without the need for nasty workarounds or my own reflection pool.

**Comment by MobiDevelop** [comment]
I would prefer not to emit even more metadata than we already do for reflection.

**Comment by czyzby** [comment]
OK, is there a way to use native JavaScript to iterate over static fields of an object to extract them? I tried: `/*@com.badlogic.gwtref.client.IReflectionCacheGenerated::c0;*/;` - but it does not have access to the generated class when the JSNI methods are validated, so it fails to build.

I could try to extract all static fields, but I'm not sure where the references are actually stored.

**Comment by czyzby** [comment]
OK, I guess I'll use a custom generator to store an array of available classes. Still, fixing method annotations would be nice.

**Comment by MobiDevelop** [comment]
I pushed a fix to that a couple hours ago.
