### ISSUE TITLE
NullPointerException when calling GlyphLayout.settext with null color

### ISSUE THREAD

**Issue by windlord0408** [libgdx/libgdx#3118]
Hi, after update to libgdx nightly 5/7/2014, my game crash at this line in my code:

GlyphLayout l = Pools.obtain(GlyphLayout.class);
l.setText(font, text, 0, text.length(), null, width,Align.center, false, "..");

And this's crash log:

GlobalMessageHandler: nulljava.lang.NullPointerException
StackTrace: com.badlogic.gdx.graphics.Color.set(Color.java:83)
StackTrace: com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:137)

My code work fine with the previous libgdx version. Please help me to fix this.

**Comment by NathanSweet** [comment]
Not without repro steps I'm afraid.
https://github.com/libgdx/libgdx/wiki/Getting-help
