### ISSUE TITLE
scene2d.utils.Align missing from 1.6.0

### ISSUE THREAD

**Issue by shvelo** [libgdx/libgdx#3138]
I'm trying to build my game with Gradle 2.4, `$gdxVersion 1.6.0`, task `:core:compileJava`  and I get the following error message 

      error: cannot find symbol 
      import com.badlogic.gdx.scenes.scene2d.utils.Align;
                                                   ^
      symbol:   class Align
      location: package com.badlogic.gdx.scenes.scene2d.utils

**Comment by davebaol** [comment]
`com.badlogic.gdx.scenes.scene2d.utils.Align` has been moved to `com.badlogic.gdx.utils.Align`
