### ISSUE TITLE
ExtendViewport does not Always Preserve Aspect Ratio

### ISSUE THREAD

**Issue by cogmind** [libgdx/libgdx#3141]
A square shape with x = y = 10 does not render as a square, when using ExtendViewport. Instead a y-stretched rectangle is presented. When switching to FitViewport with the same parameters, the aspect ratio is maintained.

```java
	public void create () {
	    camera = new OrthographicCamera(800, 480);
	    viewport = new ExtendViewport(800, 480, camera);
	    stage = new Stage(viewport);
```

			shapeRenderer.begin(ShapeType.Filled);
			shapeRenderer.identity();
			shapeRenderer.setColor( Colors.get(square.color));			
			shapeRenderer.rect(square.x, square.y, square.width, square.height);
			shapeRenderer.end();

I noticed that FitViewport extends ScalingViewport while ExtendViewport extends Viewport. The difference might be due to using enum *fit* in ExtendViewport:

```java
		Vector2 scaled = Scaling.fit.apply(worldWidth, worldHeight, screenWidth, screenHeight);
```

In the FitViewport this is simply:

```java
		Vector2 scaled = scaling.apply(getWorldWidth(), getWorldHeight(), screenWidth, screenHeight);
```

**Comment by MobiDevelop** [comment]
The sample code you've given doesn't even use the viewport.
