### ISSUE TITLE
No custom Json serialization of enum

### ISSUE THREAD

**Issue by BlueRiverInteractive** [libgdx/libgdx#3143]
If you have a custom Serializer of an enum or if the enum implements Serializable the read method will never be called because it is already handled with the default readValue method. This makes sense for Serializable but for a Serializer it would be nice if we could handle it. 

Consider having a enum type that stores some additional info, for example a product ID and a price. By default only the enum constant name will be written and read. But we want to write the id and the price to the json. When reading the json we want to use the id to find the enum constant and update its price value.

Something like:
```Java
String id = jsonData.getString("id");
Product product = Product.findById(id);
product.setPrice(jsonData.getDouble("price");
return product;
```

**Comment by NathanSweet** [comment]
Enums aren't usually stateful. You can use Serializable or a serializer to customize their serialization (after a fix I'll push soon).
