### ISSUE TITLE
[Enhancement] Add compatability with normal Android code.

### ISSUE THREAD

**Issue by RandomAltThing** [libgdx/libgdx#3144]
Alot of people are familiar with normal Android app coding. Why not add support for it in LibGDX application? It is possibly to use it, I tried startActivity. I add extends Activity to the beginning and I added the usual android imports but I still get errors. I'm assuming this isint support?

**Comment by badlogic** [comment]
We do support this. AndroidApplication is an Activity.

**Comment by RandomAltThing** [comment]
I see. It was AIDE deciding it didn't want to save my changes.
