### ISSUE TITLE
Is it correct that draw(Texture) behaves differently than draw(TextureRegion)?

### ISSUE THREAD

**Issue by btd-f-lago** [libgdx/libgdx#3145]
I stumbled across something I would consider weird:

Drawing a texture region with:
public void draw (TextureRegion region, float x, float y, float originX, float originY, float width, float height,
		float scaleX, float scaleY, float rotation)

behaves differently from:
public void draw (Texture texture, float x, float y, int srcX, int srcY, int srcWidth, int srcHeight)

called with region.getTexture(), same x,y, region.getRegionOriginX(), region.getRegionOriginY(), same width and height parameters.

The former was called with scaleX = 1.0f, scaleY = 1.0f and rotation = 0.

When called with a very small width (5 or 10 pixels) the drawn image shifts to the left by a few pixels, as the width gets closer to the actual region width, the problem gradually disappears.

I was wondering if this might be a bug due to float point math in the rotation matrix, but I'd expect it still to be smaller than one pixel.
I can't seem to find a clear problem with the code though, I was wondering if anyone had experienced the same problem.

**Comment by Darkyenus** [comment]
Are you sure that you understand how origin in those functions works? When rotation is 0, no rotation code is executed, so there can't be any float errors. Also, TextureRegion does not have any getRegionOrigin methods. You are probably confusing that with Sprite, which handles drawing a bit differently than TextureRegion, and that is probably why are you seeing some differences there.

**Comment by xoppa** [comment]
This is an issue tracker, please use the forum or irc instead. https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md#using-the-issue-tracker.
