### ISSUE TITLE
Empty IntIntMap contains 'zero' value

### ISSUE THREAD

**Issue by alex-dorokhov** [libgdx/libgdx#3146]
Asserts below are failed:

```groovy
def intMap = new IntIntMap()
assert !intMap.containsValue(0)
assert intMap.findKey(0, -1) == -1

def floatMap = new IntFloatMap()
assert !floatMap.containsValue(0)
...
```

I guess this also happens for others Int*Map classes.

**Comment by Darkyenus** [comment]
[containsValue](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/IntIntMap.java#L449) should also check if there is any key for checked value. Right now it assumes that the map is absolutely full (including stash).

**Comment by alex-dorokhov** [comment]
I didn't find unit tests for collection classes. Do they exist?

**Comment by MobiDevelop** [comment]
Nope, they don't exist.

**Comment by MobiDevelop** [comment]
IntMap#findKey also fails:

```java
IntIntMap i = new IntIntMap();
System.out.println("Key = " + i.findKey(0, -1));
----------------------------------------------------------
Output:
Key = 0
```

```java
IntIntMap i = new IntIntMap();
i.put(10, 0);
System.out.println("Key = " + i.findKey(0, -1));
----------------------------------------------------------
Output:
Key = 0
```

**Comment by GreenLightning** [comment]
https://github.com/libgdx/libgdx/commit/153c12ac7f14ee9fd6fc709c5e4ba79b7f757ba3

Shouldn't this commit have closed this issue?

**Comment by NathanSweet** [comment]
Yep, I ef'ed up the #. :)
