### ISSUE TITLE
Intersector.intersectRayTriangle failures (again)

### ISSUE THREAD

**Issue by fwolff** [libgdx/libgdx#3147]
I have found another issue with intersectRayTriangle. How to reproduce:

```java
Vector3 t1 = new Vector3(90.0f, -150.0f, 1077.0f);
Vector3 t2 = new Vector3(90.0f, -120.0f, 1109.0f);
Vector3 t3 = new Vector3(120.0f, -150.0f, 1076.0f);

Ray ray = new Ray(new Vector3(90.0f, -150.0f, 1077.1f), new Vector3(-0.0f, 0.99503726f, 0.099503726f));
System.out.println(Intersector.intersectRayTriangle(ray, t1, t2, t3, null); // error: print false
```

It's not obvious there is an intersection, but it is at: [90.0, -149.89658, 1077.1104]

Suggested fix (adapted from the [Möller-Trumbore algorithm](http://www.cs.virginia.edu/~gfx/Courses/2003/ImageSynthesis/papers/Acceleration/Fast%20MinimumStorage%20RayTriangle%20Intersection.pdf)):

```java
private static final float epsilon = 0.00001f;

public static boolean intersectRayTriangle (Ray ray, Vector3 t1, Vector3 t2, Vector3 t3, Vector3 intersection) {
	Vector3 edge1 = v0.set(t2).sub(t1);
	Vector3 edge2 = v1.set(t3).sub(t1);
	
	Vector3 pvec = v2.set(ray.direction).crs(edge2);
	float det = edge1.dot(pvec);
	if (det > -epsilon && det < epsilon) {
		p.set(t1, t2, t3);
		if (p.testPoint(ray.origin) == PlaneSide.OnPlane && isPointInTriangle(ray.origin, t1, t2, t3)) {
			if (intersection != null) intersection.set(ray.origin);
			return true;
		}
		return false;
	}
	
	det = 1.0f / det;

	Vector3 tvec = i.set(ray.origin).sub(t1);
	float u = tvec.dot(pvec) * det;
	if (u < 0.0f || u > 1.0f) return false;
	
	Vector3 qvec = tvec.crs(edge1);
	float v = ray.direction.dot(qvec) * det;
	if (v < 0.0f || u + v > 1.0f) return false;
	
	float t = edge2.dot(qvec) * det;
	if (t < 0) return false;
	
	if (intersection != null) {
		if (t < epsilon) {
			intersection.set(ray.origin);
		} else {
			ray.getEndPoint(intersection, t);
		}
	}
	
	return true;
}
```

The only difference with the original algorithm is that the method returns true when the ray origin is inside the triangle. It is clear this new code should be tested thoroughly to make sure it doesn't break existing applications.

Should I send a new pull request?

**Comment by nooone** [comment]
I smell unit tests! :nose:

**Comment by fwolff** [comment]
Sure ;) Where are libgdx unit tests?

The only one I can find is com.badlogic.gdx.utils.BitsTest in gdx/test/...

**Comment by nooone** [comment]
I could not find that test anywhere.

I'm not sure we have any unit tests. I thought a while ago, the JUnit dependency was added to libgdx, but right now I can't find any unit tests.

**Comment by MobiDevelop** [comment]
@nooone https://github.com/libgdx/libgdx/blob/master/gdx/test/com/badlogic/gdx/utils/BitsTest.java

**Comment by xoppa** [comment]
thanks @fwolff could you send a new PR?

**Comment by fwolff** [comment]
Done: pull request https://github.com/libgdx/libgdx/pull/3291.

Thanks!

**Comment by fwolff** [comment]
New PR from a fresh fork: https://github.com/libgdx/libgdx/pull/3301.

Hope this one is good ;)

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://from5pounds.com/beach.php?m>

 

loogie@basicelementdesign.com
