### ISSUE TITLE
Please fix the utterly useless docs (of GlyphLayout).

### ISSUE THREAD

**Issue by AgrarPirat** [libgdx/libgdx#3148]
Guys, 

I understand that making the API incompatible might be a necessary evil from time to time, but supplying utterly useless documentation is a major annoyance.
For example: What's a "runs of glyphs for a piece of text"? 
Or even more important: What are the parameters 'start' and 'end', used at one of the Ctors and setText(), used for?

What I'm actually trying to figure out is how to replace a simple call like:
int yOffset = (int) bitmapFont.getWrappedBounds(msg, contentWidth).height;
But the docs ain't much of a help. 

As a side note, if you're using libGDX in a production environment, you're spending more time reading its source code than reading it's documentation, yes you're getting used to it, but it's annoying non the less...

**Comment by badlogic** [comment]
Hi,

The docs are writeable by everyone! Knock yourself out!

Ciao,
Mario and Team, who provide this service to you for free in return for a tiny little bit of decency

**Comment by AgrarPirat** [comment]
Please excuse me.
I was stressed out and forgot myself.
Its actually a really awesome engine - thank you.

**Comment by badlogic** [comment]
No stress, happens to all of us. @nathansweet is the enemy. Maybe he can
revamp the docs once he's back from his hiatus.

**Comment by FyiurAmron** [comment]
> @nathansweet is the enemy.

http://www.memebucket.com/mb/2012/10/If-My-Enemys-Enemy-Is-My-Friend-753.png

**Comment by AgrarPirat** [comment]
:)
