### ISSUE TITLE
BitmapFont.draw() is drawing only a single \n character in case of various subsequent \n characters.

### ISSUE THREAD

**Issue by AgrarPirat** [libgdx/libgdx#3153]
Hi libGDX Team,

While migrating from 1.5.5 to 1.6.0, I've discovered that the new (1.6.0) BitmapFont.draw() method replaces an occurrence of various \n characters with a single \n character. For example, a call of:
```font.draw(batch, "Hello libGDX!\n\n\nHello\n \nlibGDX", xPos, yPos, 800, Align.center, true);```
Leads to the following result:
![libgdx](https://cloud.githubusercontent.com/assets/8950110/7750686/e228415c-ffd5-11e4-8252-0f455905bd16.png)
Version 1.5.5 printed two additional empty lines between the first and the second line of text.
As a workaround, placing a space character between the two \n characters can be used to avoid the issue.

**Comment by MobiDevelop** [comment]
Already fixed in https://github.com/libgdx/libgdx/commit/30d4014a82da6f1b4436df61caca67c28248b65a.
