### ISSUE TITLE
the  scrollPane  setScale

### ISSUE THREAD

**Issue by muyexiudong** [libgdx/libgdx#3157]
when  the scrollPane  setScale slide will have problems   ，when  i   set  the scrollPane's parent  scale  have  the same  problem, the  slider not  same  as the  finger

**Comment by muyexiudong** [comment]
maybe  to  try, code is easy ,   test  by  android  

		Group group=new Group();
		
	
		Texture   texture=new Texture("other_user_info_item_bg.png");
	
		for(int i=0;i<20;i++){
			Image image=new Image(texture){
				@Override
				public void draw(Batch batch, float parentAlpha) {
					// TODO Auto-generated method stub
					Gdx.app.log("TB", "image=="+getName());
					super.draw(batch, parentAlpha);
				}
			};
			image.setName(""+i);
			image.setPosition(0, (108*i+10*i));
			 group.addActor(image);
		}
		
		group.setBounds(0, 0, 246, 108*20+10*19);
		ScrollPane scrollPane=new ScrollPane(group);
		scrollPane.setBounds(0, 0, 246, 600);

		mStage.getRoot().setScale(MyGdxGame.screenScale);
		mStage.addActor(scrollPane);
		textLabel=new Label("", new Label.LabelStyle(new BitmapFont(), Color.RED));
		mStage.addActor(textLabel);

**Comment by NathanSweet** [comment]
Works fine in UITest with `stage.getRoot().setScale(1.3f);`. With an SSCCE there's nothing we can do.

**Comment by muyexiudong** [comment]
the  scrollpane  slide  and  finger   delta no  same

**Comment by muyexiudong** [comment]
i  try  the same thing  a lot  ，and make sure  have  the  problem

**Comment by NathanSweet** [comment]
I can't figure out what the problem is. Show an SSCCE or a fix?

**Comment by muyexiudong** [comment]
can  i   make  a   demo  to  you  tomorrow  .because  my english  is  bad

**Comment by muyexiudong** [comment]
package com.mygdx.game;

import javax.swing.text.html.ImageView;

import sun.rmi.runtime.Log;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.scenes.scene2d.Group;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Image;
import com.badlogic.gdx.scenes.scene2d.ui.ScrollPane;
import com.sun.org.apache.bcel.internal.generic.ISTORE;

public class MyGdxGame extends ApplicationAdapter {
   ScrollPane mScrollPane;
   Group      testGroup;
   private Stage  stage;
   private boolean isOnTouch=false;
	
	@Override
	public void create () {
		stage=new Stage(){
			@Override
			public boolean touchDown(int screenX, int screenY, int pointer, int button) {
				// TODO Auto-generated method stub
				isOnTouch=true;
				return super.touchDown(screenX, screenY, pointer, button);
			}
			
			@Override
			public boolean touchDragged(int screenX, int screenY, int pointer) {
				// TODO Auto-generated method stub
				isOnTouch=true;
				Gdx.app.log("TB", "screenY="+screenY);
				return super.touchDragged(screenX, screenY, pointer);
			}
		};
		stage.getRoot().setScale(1.5f);
		Texture texture=new Texture("other_user_info_item_bg.png");
		testGroup=new Group();
	   for(int  i=0;i<100;i++){
		   Image  image=new Image(texture);
		   image.setBounds(0, 108*i, 246, 108);
		   testGroup.addActor(image);
		   
	   }
	   testGroup.setBounds(0, 0, 246, 108*100);
	   mScrollPane=new ScrollPane(testGroup);
	   mScrollPane.setBounds(0, 0, 246, 108);
	   stage.addActor(mScrollPane);	
	   
	   Gdx.input.setInputProcessor(stage);
		
	}

	@Override
	public void render () {
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		stage.act();
		stage.draw();
		if(isOnTouch){
		Gdx.app.log("TB", "scroll.getVisualScrollY="+mScrollPane.getVisualScrollY());
	     isOnTouch=false;
		}
		
		
	}
}


the  log:
TB: screenY=759
TB: screenY=760
TB: scroll.getVisualScrollY=0.0
TB: screenY=758
TB: scroll.getVisualScrollY=0.0
TB: screenY=754
TB: scroll.getVisualScrollY=0.0
TB: screenY=746
TB: scroll.getVisualScrollY=0.0
TB: screenY=736
TB: scroll.getVisualScrollY=10.0
TB: screenY=725
TB: scroll.getVisualScrollY=21.0
TB: screenY=714
TB: scroll.getVisualScrollY=32.0
TB: screenY=705
TB: scroll.getVisualScrollY=41.0
TB: screenY=698
TB: scroll.getVisualScrollY=48.0
TB: screenY=696
TB: scroll.getVisualScrollY=50.0

this is  the demo  and  the  scrollpane slider faster  than  the  finger , i  think  this is  wrong,

**Comment by muyexiudong** [comment]
the  visualScrollY and  the screenY delta  show   not  equal, if  i  set the scale
