### ISSUE TITLE
TextArea not calculating height on setPrefRows

### ISSUE THREAD

**Issue by ghandhikus** [libgdx/libgdx#3158]
TextArea is not recalculating height when setting prefered rows through setPrefRows.
It does after resizing though. There is no public method to recalculate the height though.

The thing I am trying to do is to force TextArea to have height of the text. I inserted it into ScrollPane and it does not resize itself out of the box. Is there any other way to recalculate it without extending the class?

Test code:
```
	public void update()
	{
		String str = stringStream.toString();
		Globals.consoleText.setText(str);
		Globals.consoleText.setPrefRows(Globals.consoleText.getLines());
	}
```

**Comment by ghandhikus** [comment]
It was an issue with ScrollPane not updating the height after TextArea height was changed.

I resolved it temporary in a ugly way:
```
		scrollPane.setHeight(scrollPane.getHeight()+1);
		scrollPane.setHeight(scrollPane.getHeight()-1);
```

**Comment by anserran** [comment]
`setPrefRows` is designed as other layout methods in other widgets (for example, the size methods in Container): you set some data that is used during the layout process, but calling the method does not update the size immediately. 

However, if you want to force the layout, you can always call invalidate/invalidateHierarchy.

**Comment by MobiDevelop** [comment]
So, as I gather, this is operating as designed. Is that correct @anserran? Should this be closed?

**Comment by anserran** [comment]
@MobiDevelop Yep.

**Comment by MobiDevelop** [comment]
Cool, thanks for confirming.
