### ISSUE TITLE
Enhancement: Separate Util Library

### ISSUE THREAD

**Issue by chbachman** [libgdx/libgdx#3165]
I haven't looked at it in much detail, but a lot of the Util (e.g. the gdx.utils package) classes would be amazing as a separate library for general use. The Array and ImmutableArray classes especially are really nice to work with, and are fairly general use. It would be nice to include only those in many non game development projects. 

Is this possible? I totally understand, I can always rip them from the current library, however it would be nice to be able to grab them from the libgdx maven. 

Thanks for your time.

**Comment by MobiDevelop** [comment]
We've had some conversation around this at https://github.com/libgdx/libgdx/issues/2793, so probably best not to open another issue/conversation. Please feel free to weigh in on #2793.
