### ISSUE TITLE
missing ClassReflection#getComponentType(Class)

### ISSUE THREAD

**Issue by dermetfan** [libgdx/libgdx#3168]
Just another feature request for ClassReflection... not my first, I know :grin:

**Comment by MobiDevelop** [comment]
Shouldn't be a problem to add, looks like we already have this information in the reflection cache, it just has no accessor.

**Comment by MobiDevelop** [comment]
Actually, are you sure you can't just call Class#getComponentType()? GWT seems to implement it in its emulation.

**Comment by dermetfan** [comment]
Indeed, you are right. `isArray()` is also emulated so #2943 would not have been necessary either...
