### ISSUE TITLE
Multiple crashes in GlyphLayout

### ISSUE THREAD

**Issue by gr3ger** [libgdx/libgdx#3172]
Hey!

I have multiple issues regarding GlyphLayout that is fairly common with users of my app, I have yet to be able to reproduce the problem, here are some stacktraces:

```
java.lang.NullPointerException
       at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:137)
       at com.badlogic.gdx.graphics.g2d.BitmapFontCache.addText(BitmapFontCache.java:482)
       at com.badlogic.gdx.graphics.g2d.BitmapFontCache.addText(BitmapFontCache.java:470)
       at com.badlogic.gdx.graphics.g2d.BitmapFont.draw(BitmapFont.java:207)
       at se.xxx.xxx.objects.BasicSquare.renderList(BasicSquare.java:291)

java.lang.IndexOutOfBoundsException: index can't be >= size: 1 >= 0
       at com.badlogic.gdx.utils.Array.get(Array.java:127)
       at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:197)
       at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:63)
       at se.xxx.xxx.objects.PlateAnimationHolder.startAnimation(PlateAnimationHolder.java:60)

java.lang.IllegalArgumentException: object cannot be null.
       at com.badlogic.gdx.utils.Pool.free(Pool.java:56)
       at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:197)
       at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:63)
       at se.xxx.xxx.objects.BasicSquare.renderList(BasicSquare.java:244)

```

I am not sure what causes this, but some of the issues seem to stem from wrapping the font, and some others seem to stem from "color" being null for some unknown reason. Hopefully someone will be able to help me with this since I'm at a loss.

LibDGX version: 1.6.1 release
Platform: Android

**Comment by Tom-Ski** [comment]
Need more information, LibGDX version at least.

**Comment by gr3ger** [comment]
Latest (1.6.1) release was used when these errors occured, and the platform is android.
The frequency of these errors are somewhat arbitrary and as to my knowledge there's no way of reliably replicating the issues.

**Comment by xoppa** [comment]
This is an issue tracker. Please use the forum or irc if you need help using the api. If you did find an issue with libgdx then include enough information to reproduce the issue (e.g. create an [sscce.org](sscce.org)) and how you verified that it is indeed an issue with libgdx and not your code.

**Comment by gr3ger** [comment]
As I mentioned earlier, there's no reliable way to reproduce the issue on all devices, it seems like only a handful of them are affected.
I've made sure not to make changes to fonts/glyphlayouts outside the game loop, the game functioned perfectly previous to adding glyphlayouts, and I used them exactly as the examples in the repo.
But I guess we'll have to abandon this until I've found a device that can reproduce this isse reliably.

**Comment by rotter** [comment]
Im facing an exception similar to the 2nd posted reliably, on desktop, when showing a dialog with any title with 2 or more chars (with a single char it doesnt crash).

Exception in thread "LWJGL Application" java.lang.IndexOutOfBoundsException: index can't be >= size: 0 >= 0
	at com.badlogic.gdx.utils.FloatArray.get(FloatArray.java:104)
	at com.badlogic.gdx.graphics.g2d.GlyphLayout.truncate(GlyphLayout.java:262)
	at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:153)
	at com.badlogic.gdx.scenes.scene2d.ui.Label.layout(Label.java:199)

**Comment by rotter** [comment]
In my case, for some reason it tries to truncate when it didnt need to. I found out that "targetWidth" is coming with 0 in the Label->GlyphLayout->setText->truncate flow for some reason, so I believe this causes the truncate code to crash (or maybe it's unrelated).

The part of code that crashes is:

(GlyphLayout.java, 1.6.1)
run.glyphs.clear();
run.xAdvances.clear();
run.xAdvances.addAll(truncateRun.xAdvances);
run.width += truncateRun.xAdvances.get(0); <---- crashes here

because "truncateRun" is empty (xAdvances.size == 0).

**Comment by intrigus** [comment]
Could you please provide a http://sscce.org/ ?

**Comment by rotter** [comment]
Workaround: disabling truncate will stop the crash.

label.setEllipsis(false);

The default is false, but probably the Dialog class sets it to true somewhere, so we just set it back to false.

So as for the SSCCE, maybe simply turn ellipsis on for a widthless Label?

I will try here on another project and write back.

**Comment by rotter** [comment]
Ok, after 2 hours trying to reproduce, I think I've found the culprit: the font texture doesn't have the . (dot) character, so when it tries to calculate the truncate stuff using the ellipsis it fails somewhere since there are no valid glyphs (0 length, and he tries to read the 1st element).

**Comment by rotter** [comment]
I've written a sample project, is there somewhere standard where I can upload it?

Basically this is the relevant code, but you need to create a font without the . (dot) character:

```java
BitmapFont fontWithoutDotChar = new BitmapFont(Gdx.files.internal("font_dummy.fnt"), Gdx.files.internal("font_dummy.png"), false);

Label thisLabelWillCrash = new Label("Any 2 or more chars string will crash", new LabelStyle(fontWithoutDotChar, Color.BLACK));
thisLabelWillCrash.setEllipsis(true);

// This is needed to crash, or it won't force the truncate
// Note that on Dialog this line doesnt exist, but something there forces the Label width to 0 which has the same effect
thisLabelWillCrash.setWidth(10f);

Table containerToLabel = new Table();

// This is needed to crash: "addActor" instead of "add", the same way it's done in the Dialog class
containerToLabel.addActor(thisLabelWillCrash);

containerToLabel.pack();
```

**Comment by intrigus** [comment]
And why should this be an issue with libgdx?
It's a problem with your font and not with libgdx.

**Comment by rotter** [comment]
Are you serious? Have you even taken the time to read the bug description?

I put the chars I want in my font.

**Comment by MobiDevelop** [comment]
So, having the '.' glyph in your font corrects the issue then? Perhaps libgdx can verify that the ellipsis glyph(s) exist in the font before attempting to use them?

**Comment by rotter** [comment]
That is necessary, but not sufficient I believe. There may be other problems around (since in 1.6.0 this didnt crash).

Yes, the truncate method can't simply assume the latin dot character exists, because, well, it might not. Maybe allow the Label to set which string should be used for the ellipsis, and/or simply truncate without ellipsis if the dot (or any char in the passes ellipsis string) doesnt exist.

But something else I noticed: adding the Label to the Table using "addActor" makes the Table validate() method skip the label to fix its size, but the layout() method kicks in for it (for all its children), which cause the truncate to run on a 0-width Label. I dont know if this is expected behavior or not, but I found these 2 things odd (1: that the Dialog adds the Label as a children, and not as a cell, and 2: that there is a different treatment for children and for cells inside the Table layout() method).

Best

**Comment by Tom-Ski** [comment]
Setting the ellipse character seems reasonable. One thing at a time, this issue is already derailed enough.  You should open up a separate issue for the ellipse character issue, and any other unrelated issue that is **suitable** for the issue tracker.

**Comment by rotter** [comment]
Ok, I will do that now! Best

**Comment by Tom-Ski** [comment]
This original issue looks to be a misuse of threading, if a self executing example is provided that shows an issue with LibGDX we can reopen.
