### ISSUE TITLE
Texture Wrap does not work for non-power-of-two images on iOS

### ISSUE THREAD

**Issue by schmoofer** [libgdx/libgdx#3178]
Simplest method to reproduce this error (for iOS):
1. Setup default project with project setup JAR
2. Resize the included "badlogic.jpg" from 256x256 to 256x257 or some non-power-of-2 dimensions.
3. Enable Texture Wrap on the image with the following line placed within the create method:
```img.setWrap(TextureWrap.Repeat, TextureWrap.ClampToEdge);```

Result will be a black void where the image is expected to be. If either the image is power-of-two or Texture Wrap is disabled, the image will appear correctly.

**Comment by Tom-Ski** [comment]
This is in line with the open gles spec, you need POT textures for that wrapping mode.

----- Reply message -----

**Comment by schmoofer** [comment]
Understood. Was not aware of it. Thanks.
