### ISSUE TITLE
relative and absolute paths on Android

### ISSUE THREAD

**Issue by snovak** [libgdx/libgdx#3179]
Hey All,

I'm having an issue with loading a g3dj with relative links to texture files.  It seems that android, specifically wants texture files in the same directory as the model.  Desktop accepts relative links without issue.  

For example, the following works on Desktop (OSX), not on Android. 
```javascript
// snippet from g3dj file
"textures": [
                      {
                           "id": "Texture.005",
                           "filename": "../materials/miami-hurricanes-tiled.jpg",
                           "type": "DIFFUSE"
                      }
                 ]
```
I have tried both relative and absolute path format
Relative: "../materials/miami-hurricanes-tiled.jpg" // should navigate one up from current directory
Absolute: "/materials/miami-hurricanes-tiled.jpg"  // should navigate from top level of assets folder

Here is my assets directory hierarchy: 

![screen shot 2015-05-28 at 2 51 09 pm](https://cloud.githubusercontent.com/assets/317561/7884982/5a0ed4d2-05ef-11e5-93ae-f3c3a388e48c.png)

The error from LogCat reports: 
05-28 15:16:45.243: E/AndroidRuntime(2681): com.badlogic.gdx.utils.GdxRuntimeException: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load dependencies of asset: models/../materials/miami-hurricanes-tiled.jpg

What DOES work, is having the texture file in the same directory as the g3dj file.

**Comment by FyiurAmron** [comment]
AFAIK (I might be wrong), this is directly related to
https://github.com/libgdx/libgdx/issues/2617
with workaround being to use
````
public String normalize(String filenameWithDots) {
    return new URI( file.parent().child( filenameWithDots ).path() ).normalize().getPath();
}
```
e.g. in the g3dj loader (https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g3d/loader/G3dModelLoader.java#L216), like
jsonTexture.fileName = normalize(jsonTexture.fileName)

**Comment by snovak** [comment]
I ended working around the problem for the time being.  My models and materials are in different directories.  So, I load geometric data from /models with a simple material.  
After the model loads, I'm loading more complex materials with linked maps in the same directory.  That works for now.  I'll backtrack and fix this if I have some time left.  

Let's call this a duplicate and close for now.  Thanks for the link!
