### ISSUE TITLE
(OOP) modify Model class to allow subclasses with custom loading sequence calling existing loading methods

### ISSUE THREAD

**Issue by FyiurAmron** [libgdx/libgdx#3186]
To implement a different `load()` behaviour, one currently has to Ctrl+C/Ctrl+V the entire related code from Model, even if it is necessary to only change a slightest bit.

The proposed solution would be to change all related methods () from `private` to `final protected`, allowing easy modular changes and/or replacements via subclasses with constructors calling no-arg `Model()` c-tor with custom `load()` variant.

As a side note, `nodePartBones` can be made either final and accessible for subclasses via `final protected`, to allow using it in custom subclass loader, or (possibly better, since AFAIK it's only used during loading and just hogging the memory for the Model later on) converted from field to `loadNodes()` method variable, passed to `loadNode()` as a parameter.

If this's somewhat too big for an instant dev patch, I'd be more than happy to do a PR for it.

**Comment by xoppa** [comment]
Yeah, need to refactor that part a bit. If I find the time, I will have a look at it later this week. Thanks for reporting.

**Comment by VinceAngel** [comment]
Maybe https://github.com/libgdx/libgdx/pull/3705 have to be referenced too
