### ISSUE TITLE
TextField with Chinese initial value will break incremental chinese freeTypeFont

### ISSUE THREAD

**Issue by bill-lin** [libgdx/libgdx#3187]
For example, there is an incremental chinese  freeTypeFont used in inputTextFieldStyle2
Following code is ok:
```
public TextField createInputTextField2(String defaultValue) {
        TextField textField= new TextField("default", inputTextFieldStyle2);
        textField.setText(defaultValue);
        return textField;
    }
```

But following code will cause all chinese chars not displayable in inputTextFieldStyle2's font

```
public TextField createInputTextField2(String defaultValue) {
        TextField textField= new TextField("林彬", inputTextFieldStyle2);
        textField.setText(defaultValue);
        return textField;
    }
```

I am using version 1.6.0

**Comment by xoppa** [comment]
Please check: https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md#using-the-issue-tracker. If you are actually reporting an issue with libgdx then include enough information to reproduce the issue, including the font you've used that contains those characters. Will reopen if you provide the required information.

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://bookings-sicilia.com/closer.php?0nsoj>

 

loogie@basicelementdesign.com
