### ISSUE TITLE
headless backend on raspberry pi [enhancement]

### ISSUE THREAD

**Issue by mk1x86** [libgdx/libgdx#3188]
I'd love to use libgdx with a headless backend on the raspberry pi to use it as server for my game. However the ARM natives use a different abi and thus don't work with rpi. Is there any chance to add those to the build process?

**Comment by meisterfuu** [comment]
Isn't a headless version of libgdx just plain java? Split your game logic from rendering, write a loop and you are good to go. Though a headless libgdx build would make this a "one click" solution.

**Comment by Darkyenus** [comment]
[There are some natives even in headless](https://github.com/libgdx/libgdx/tree/master/gdx/jni), for example Matrix4 and (for) Pixmap.

**Comment by MobiDevelop** [comment]
See https://github.com/libgdx/libgdx/pull/2940

**Comment by xranby** [comment]
SharedLibraryLoader has been patched to support JDK 8 ABI detection to ARM GNU/Linux shared library loading https://github.com/libgdx/libgdx/commit/8f83f0f4449d5f4e71ba3771fa151e9f40e84721

The libgdx build server needs new cross compile scripts to provide pre-compiled libgdx*.so for arm This is worked on in #3196
