### ISSUE TITLE
Proposal: Lua extension

### ISSUE THREAD

**Issue by deathbeam** [libgdx/libgdx#3189]
Why Lua? Because games like WoW made it super popular and choice #1 for scripting in games.
I think that scripting support is the last thing that people can miss from libGDX.
I am working on Lua backend for Java written mostly in C++ and based on LuaJava, so it is really fast compared to popular Lua backend LuaJ. And it is tested and working on all platforms that libGDX supports (except Gwt). It is also compatible with libGDX build system as I used jnigen there.

You can view gdx-compatible branch of it here: https://github.com/nondev/nonlua/tree/experimental
I am still working on it but I think in a week or so I will finish it.

I am willing to offer this project to libgdx as extension (something like gdx-lua). What do you think about it? There are still some parts of LuaJava (with proper license headers), but as they are under MIT license, I think it shouldn't be problem.

I also posted thread on [forums](http://www.badlogicgames.com/forum/viewtopic.php?f=17&t=19443) but forum is a bit inactive.

P.S Sorry for my English

**Comment by badlogic** [comment]
The more options the merrier. But i think it would make sense to make this
a 3rd party extension. We can get it into the setup app, but we won't
include it in the main repo. We simply don't have the resources to maintain
it.

**Comment by Tom-Ski** [comment]
Sounds great, I agree with Mario, the best fit for this is as a third party extension. Please check out https://github.com/libgdx/libgdx/wiki/Third-Party-Extension-Support

**Comment by deathbeam** [comment]
Okay, great. I will try to finish entire API this week and publish it to Sonatype.

**Comment by hepin1989** [comment]
@deathbeam wow ,that's very nice!I will take a deep look at it,you know what,by this way ,the server write in java could share some logic with the client via your project.

I think an extension is very nice,you project is very valuable.

**Comment by deathbeam** [comment]
It is published on Sonatype but release will be delayed cause I do not own Mac (going to buy it in next 2 months). Also, did some experiments with LuaJIT as replacement for Lua 5.3 native and when I ran all tests, performance was in average more than 10 times better than LuaJ performance.

**Comment by Tom-Ski** [comment]
Cool! Submit an extension PR when its done. :)
