### ISSUE TITLE
Font without dot character causes crash on Label Ellipsis

### ISSUE THREAD

**Issue by rotter** [libgdx/libgdx#3190]
Originally I had this crash when using a plain Dialog, but I have replicated the bug below without the Dialog overhead. To replicate with Dialog is a one liner: new Dialog(...).show(...), but you need to create a skin, stage, etc, and of course using a font without the dot character.

Some info:

1) This happens on LibGDX 1.6.1 (it didnt happen on 1.6.0)

2) Adding the Label to the Table using the "addActor" is needed so the Label "lingers" on the Table and is not affected by the layout() method's resizing of the cells.

3) Using a Group instead of a Table doesnt cause the crash because the Group doesnt have the "pack" mechanism (which is where the crash happens).

4) As a suggestion I put on the other GlyphLayout issue, maybe one could set the string for the ellipsis on the Label, so he can avoid the crash without being forced to add the dot character on the font texture. BUT this is not sufficient IMHO, I think the mechanism should still check if the ellipsis characters exist, and if not simply truncate the Label without any ellipsis fluffiness.

This is the relevant code, but you need to create a font without the . (dot) character:

```java
BitmapFont fontWithoutDotChar = new BitmapFont(Gdx.files.internal("font_dummy.fnt"), Gdx.files.internal("font_dummy.png"), false);

Label thisLabelWillCrash = new Label("Any 2 or more chars string will crash", new LabelStyle(fontWithoutDotChar, Color.BLACK));
thisLabelWillCrash.setEllipsis(true);

// This is needed to crash, or it won't force the truncate
// Note that on Dialog this line doesnt exist, but something there forces the Label width to 0 which has the same effect
thisLabelWillCrash.setWidth(10f);

Table containerToLabel = new Table();

// This is needed to crash: "addActor" instead of "add", the same way it's done in the Dialog class
containerToLabel.addActor(thisLabelWillCrash);

containerToLabel.pack();
```

**Comment by FyiurAmron** [comment]
BTW I can only add that I wholeheartedly agree with 4) (setting ellipsis string on demand) - my GDX Label extension has extended `layout()` with https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Label.java#L173 retrofitted with a custom ellipsis field working just described by @rotter; it's a neat feature to have.

**Comment by NathanSweet** [comment]
What would you want for an ellipsis instead of "..."?

**Comment by FyiurAmron** [comment]
@NathanSweet there are many situations where a single ellipsis glyph [http://www.fileformat.info/info/unicode/char/2026/index.htm -like one] is visually a lot better -monospaced fonts come to mind here - than three explicit dot glyphs.
