### ISSUE TITLE
Sigsegv when trying to get alpha from pixel value

### ISSUE THREAD

**Issue by ArdaKara97** [libgdx/libgdx#3193]
When I call Color.rgba8888toColor( c, v ) method it gives that error:

SIGSEGV (0xb)at pc=0xa3818794, pid=5722, tid=2643958592

Problematic frame:

C [libgdx.so+0xb794] get_pixel_alpha+0x4

And problem gdes off when I comment out that line:

color.a = (( value & 0x000000ff)) / 255f

It happens only whit textures created from a pixmap

**Comment by xoppa** [comment]
This is an issue tracker. If you need help using the API then please use the forums or IRC instead. If you are indeed reporting an issue with libGDX then provide enough information to reproduce the issue. See also: https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by ArdaKara97** [comment]
Well the part which gives error is from API itself and it is a native crash

**Comment by MobiDevelop** [comment]
Include an SSCCE showing the issue. The information you've given isn't enough for us to reproduce.

**Comment by ArdaKara97** [comment]
I will provide an sscce as soon as possible.

**Comment by xoppa** [comment]
Will reopen if you provide the required information.
