### ISSUE TITLE
Proposal: Simple Take Screenshot System

### ISSUE THREAD

**Issue by Emilio17MC** [libgdx/libgdx#3194]
Add method do Take Screenshot to game and easy save example:

if (Gdx.input.isKeyPressed(Input.Keys.A)) {
            screenshot.take;
        }

**Comment by MobiDevelop** [comment]
There is ScreenUtils.getFrameBufferPixmap for taking screenshots, and PixmapIO.writePNG to write Pixmaps to PNG files. They make it pretty easy to do this.
