### ISSUE TITLE
Bits.nextClearBit(int) returns incorrect results

### ISSUE THREAD

**Issue by Antag99** [libgdx/libgdx#3198]
> Returns the index of the first bit that is set to false that occurs on or after the specified starting index. If no such bit exists then -1 is returned.

There is no such case; a clear bit always exist. To demonstrate this error, I wrote the following test case, which fails with `java.lang.AssertionError: expected:<64> but was:<-1>`.
```java
Bits bits = new Bits();
for (int i = 0; i < 64; ++i) { // Edit: changed from 65 to 64.
    bits.set(i);
    assertEquals(i + 1, bits.nextClearBit(0));
}
```
To fix this issue, `return -1;` can be replaced with `return bits.length << 6;`. This nasty bug occurs in two places in the `Bits.nextClearBit(int)` function.

**Comment by xoppa** [comment]
Thanks for reporting! Sounds like a good solution given the definition of the class. Should change the javadocs as well in that case. Perhaps you can send a PR to change it?

**Comment by Antag99** [comment]
All right, opened #3199.
