### ISSUE TITLE
Loading corrupted PNG image may result in native crash

### ISSUE THREAD

**Issue by kotcrab** [libgdx/libgdx#3200]
Normally when trying to load corrupted png file libGDX will throw "Couldn't load file" exception and that's ok but somehow my file got corrupted in such way that loading it results in native crash. 
The crash occurs somewhere here in native code: https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g2d/Gdx2DPixmap.java#L266

Image: http://dl.kotcrab.com/nativecrasher.png (just try to load it as Texture)
Error log: http://pastebin.com/XzKeCwgw (OS: Win7 64bit)

**Comment by NathanSweet** [comment]
libgdx uses stb_image to load images efficiently. It may fail with some images. When making apps you generally have control over the images, so this is not a problem. There used to be a gdx-image extension for loading with other libs, but it seems to be gone.
