### ISSUE TITLE
[feature request] Method to allow Callable<> i.e. Gdx.app.postCallable()

### ISSUE THREAD

**Issue by adam-law** [libgdx/libgdx#3201]
I'm finding that, when developing for desktop, I have situations where I'm outside of the OpenGL context, but need to process something within its thread. **Gdx.app.postRunnable** is  a boon in these situations, but there are times when I need to use **Future<>** and future.get(), to be sure that what I want processed has completed properly.

Would it be possible to add this function to the package?

Thanks.

**Comment by avianey** [comment]
could help doing https://github.com/libgdx/libgdx/issues/2874

**Comment by nooone** [comment]
Might not be that easy, because on GWT `Future` still doesn't exist.

If I understand your request correctly, you want to block your background thread via `Future.get` until the GL thread has finished your `Runnable` and then proceed in the background thread?

**Comment by MobiDevelop** [comment]
For completeness, Callable also doesn't exist in GWT.

**Comment by adam-law** [comment]
yes, noone, you are correct. Returning a processed result, would be icing on the cake.

regarding GWT, that's surprising. off-topic, and understandably that it's from another team, guava has an emulation of Callable since version 11, I believe.

**Comment by MobiDevelop** [comment]
Well, Future and Callable are just interfaces, so emulating them isn't really a problem (aside from implying support for the concurrent package when there is no real support).

**Comment by badlogic** [comment]
The problem is that there's no real concurrency in GWT, which means any future emulation will dead lock :)

Sorru folks, you'll have to continue hand rolling this one.
