### ISSUE TITLE
Proposal: Android SDK manager

### ISSUE THREAD

**Issue by deathbeam** [libgdx/libgdx#3203]
So currently, in gdx-setup user needs to specify location to his/her installed version of Android SDK. I have found this great [tool](https://github.com/JakeWharton/sdk-manager-plugin), which checks, if user have specified or never version of Android SDK installed and if not it installs it. I am using it for a while with all libgdx-related projects I am working on and I must say that it is working perfectly.

What are advantages?
* simple installation
* software needed to be installed before building libGDX project reduced only to JDK
* less troubles for Linux users (as there is no installer for Android SDK for Linux, so you need to download archive, extract it and manually update PATH)
* easier deployement of libGDX projects to GitHub (by eliminating local.properties)

I can create pull request for this.

**Comment by MobiDevelop** [comment]
There are licenses that need to be accepted to download and use the Android SDK. That tool stated that acceptance is bypassed. I don't think we should be bypassing that for new users.

**Comment by deathbeam** [comment]
Maybe link to [this(]) website from gdx-setup UI with text like
```
If you do not have Android SDK already installed, it will be automatically installed and so by installing LibGDX you also accept [Android SDK terms and conditions of use](https://developer.android.com/sdk/terms.html)
```
or something like that (my English is not very good, sorry) would solve it.

**Comment by MobiDevelop** [comment]
I'm against this idea, but will let others decide.

**Comment by sonzhihui** [comment]
In China，There are no  Google and android。we visit Google by VPN。

**Comment by sonzhihui** [comment]
I'm against this idea。

**Comment by deathbeam** [comment]
@sonzhihui If it is usual in China, I see no problem here, as tool checks first if you already have Android SDK installed and if you downloaded it through VPN it and installed it before, it will detect it. Also, it installs the SDK only if you are using Android backend.

**Comment by sonzhihui** [comment]
But most of us maybe can‘t access https://developer.android.com/。

**Comment by sonzhihui** [comment]
Considering the situation of China，it shoud be treated carefully。

**Comment by hepin1989** [comment]
In fact the Android Studio provide something like notifying the SDK updates and so on,and I think this feature could leave out.

For the GFW blocking,I think that's not a problem,right?You are a programmer not a normal user.

**Comment by Tom-Ski** [comment]
Not a fan of doing this, lots of people have weird and wonderful ways of downloading and managing their SDK, no doubt it will interfere. If you like using this tool, I think you should just use it yourself

**Comment by FyiurAmron** [comment]
The tool is neat (thanks for the link!), but a) the dependence on external lib in not a good thing (possible security/stability issues, version updates etc), b) what @Tom-Ski said - I've had some strange SDK installations myself, c) gdx-setup is merely a helper, the same goes for sdk-manager-plugin; forcing a user/developer to use one particular helper tool stack is never good IMO.

Adding some toggle-able option to add that plugin to the Gradle build script generated from gdx-setup would still be neat (though probably mostly useless IMO).

**Comment by badlogic** [comment]
I'm currently doing some work on a custom IntelliJ based IDE. Will likely
have a project wizard and automatically installs all the things for you.
Stay tuned.

**Comment by Tom-Ski** [comment]
Going to close this out, I guess MarioADT is the solution everyone wants deep down.

**Comment by badlogic** [comment]
No, but it's the solution you deserve :)
