### ISSUE TITLE
Implement equals() and hashCode() for collection classes

### ISSUE THREAD

**Issue by Antag99** [libgdx/libgdx#3204]
The collection classes in libgdx should implement `equals()` and `hashCode()`. This includes the various `Entry` classes. Here is a list of classes missing `equals()` or `hashCode()` implementations:
- `com.badlogic.gdx.utils.Array` - only `equals()` is implemented
- `com.badlogic.gdx.utils.ArrayMap` - uses `ObjectMap$Entry`
- `com.badlogic.gdx.utils.BinaryHeap`
- `com.badlogic.gdx.utils.BinaryHeap$Node`
- `com.badlogic.gdx.utils.BooleanArray` - only `equals()` is implemented
- `com.badlogic.gdx.utils.ByteArray` - only `equals()` is implemented
- `com.badlogic.gdx.utils.CharArray` - only `equals()` is implemented
- `com.badlogic.gdx.utils.FloatArray` - only `equals()` is implemented
- `com.badlogic.gdx.utils.IntArray` - only `equals()` is implemented
- `com.badlogic.gdx.utils.IdentityMap`
- `com.badlogic.gdx.utils.IdentityMap$Entry` - could be replaced with `ObjectMap$Entry`
- `com.badlogic.gdx.utils.IntFloatMap`
- `com.badlogic.gdx.utils.IntFloatMap$Entry`
- `com.badlogic.gdx.utils.IntIntMap`
- `com.badlogic.gdx.utils.IntIntMap$Entry`
- `com.badlogic.gdx.utils.IntMap`
- `com.badlogic.gdx.utils.IntMap$Entry`
- `com.badlogic.gdx.utils.IntSet`
- `com.badlogic.gdx.utils.LongArray` - only `equals()` is implemented
- `com.badlogic.gdx.utils.LongMap`
- `com.badlogic.gdx.utils.LongMap$Entry`
- `com.badlogic.gdx.utils.ObjectFloatMap`
- `com.badlogic.gdx.utils.ObjectFloatMap$Entry`
- `com.badlogic.gdx.utils.ObjectIntMap`
- `com.badlogic.gdx.utils.ObjectIntMap$Entry`
- `com.badlogic.gdx.utils.ObjectMap`
- `com.badlogic.gdx.utils.ObjectMap$Entry`
- `com.badlogic.gdx.utils.ObjectSet`
- `com.badlogic.gdx.utils.OrderedMap` - extends `ObjectMap`, but semantics may be different
- `com.badlogic.gdx.utils.OrderedSet` - extends `ObjectSet`, but semantics may be different
- `com.badlogic.gdx.utils.PooledLinkedList`
- `com.badlogic.gdx.utils.ShortArray` - only `equals()` is implemented
- `com.badlogic.gdx.utils.SortedIntList`

Seriously, shouldn't all these primitive type variations be auto-generated?

**Comment by marianomdq** [comment]
Sounds reasonable. But maybe there's an even more reasonable reason.

**Comment by nooone** [comment]
> Seriously, shouldn't all these primitive type variations be auto-generated?

Sounds like a cool idea. A lot of combinations of primitive types for maps for example are also missing. Do you want to code such a generator?

If nobody is going to write a generator like this, we might finally need to introduce some base classes for the collections (probably non-generic ones for the primitive variations), otherwise adding equals/hashcode everywhere will result in a huge code-duplication-mess.

**Comment by Antag99** [comment]
> Do you want to code such a generator?

I might do that, but I'm doing other stuff right now. The main problem is that the APIs have minor differences; maps whose values are primitive have methods such as `getAndIncrement()`. Also, `IntMap` allows for keys whose values are `0`, but `ObjectMap` does not allow for keys that are `null`. This makes sense, but I think it would be good to introduce something like `hasNullValue` in `ObjectMap`, like `IntMap`'s `hasZeroValue`.

Also, how do you think such a generator should work? It's possible to generate classes from scratch using a library like [javapoet](https://github.com/square/javapoet), but would it be nice maintaining such a thing afterwards? Another idea is to write a template file with conditionals, like done in [HPPC](https://github.com/carrotsearch/hppc).

Another note: The collection classes should also implement `Poolable`, so they can be safely used using `Pools.obtain()`. Right now it's a bit problematic; if one user calls `clear()` before usage, and another `clear()` after usage, things are not going to end up well.

**Comment by MobiDevelop** [comment]
I think you should wait for Nate or Mario's input before you start implementing these ideas.

**Comment by NathanSweet** [comment]
A code generator will have to handle many small differences. Doing that to replace working code is pointless. It's only a dozen or so classes, it is manageable.

I have a feeling this PR is not driven by an actual need.

**Comment by Antag99** [comment]
> I have a feeling this PR is not driven by an actual need.

It is. I needed a `hashCode()` and `equals()` implementation for `ObjectMap`, but ended up implementing it myself. When reporting this issue, it didn't make sense to introduce these methods only for `ObjectMap`.

**Comment by NathanSweet** [comment]
Ok. equals and hashCode make sense for the collections. Code duplication is fine, these classes are already far down that path.

I don't think it is needed for classes like `BinaryHeap$Node` and `*$Entry`. Entry instances are usually reused and shouldn't be kept anyway.

**Comment by Antag99** [comment]
#3236 fixes this issue.
