### ISSUE TITLE
gdx-setup checks local before gradle downloaded.

### ISSUE THREAD

**Issue by sonzhihui** [libgdx/libgdx#3205]
gdx-setup show check if the gradle is installed before.

**Comment by xoppa** [comment]
So, what's the issue? 
https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by MobiDevelop** [comment]
We use the gradle wrapper as is recommended by the [gradle documentation](https://docs.gradle.org/current/userguide/gradle_wrapper.html). The wrapper will check if the particular Gradle version has already been downloaded before downloading it again.
