### ISSUE TITLE
Sound loading becomes slower when more than 6 files

### ISSUE THREAD

**Issue by kandaaaaa** [libgdx/libgdx#3211]
Here is my code. Simply load all the sound files

        Gdx.app.log("PERFORMANCE", "Load sound stars");
        soundMPWin = Gdx.audio.newSound(Gdx.files.internal("SoundEffect/MPWin.mp3"));
        Gdx.app.log("PERFORMANCE", "MPWin done");
        soundMPLose = Gdx.audio.newSound(Gdx.files.internal("SoundEffect/MPLose.mp3"));
        Gdx.app.log("PERFORMANCE", "MPLose done");
        soundShipTouched = Gdx.audio.newSound(Gdx.files.internal("SoundEffect/ShipTouched.mp3"));
        Gdx.app.log("PERFORMANCE", "ShipTouched done");
        soundControlObjectExplode = Gdx.audio.newSound(Gdx.files.internal("SoundEffect/ControlExplosion.mp3"));
        Gdx.app.log("PERFORMANCE", "ControlExplosion done");
        soundButtonClick  = Gdx.audio.newSound(Gdx.files.internal("SoundEffect/ButtonClick.mp3"));
        Gdx.app.log("PERFORMANCE", "ButtonClick done");
        soundKillWave = Gdx.audio.newSound(Gdx.files.internal("SoundEffect/KillWave.mp3"));
        Gdx.app.log("PERFORMANCE", "KillWave done");
        soundRockPause = Gdx.audio.newSound(Gdx.files.internal("SoundEffect/RockPause.mp3"));
        Gdx.app.log("PERFORMANCE", "RockPause done");
        soundBlackHole = Gdx.audio.newSound(Gdx.files.internal("SoundEffect/BlackHole.mp3"));
        Gdx.app.log("PERFORMANCE", "BlackHole done");
        soundGoldCoin = Gdx.audio.newSound(Gdx.files.internal("SoundEffect/GoldCoin.mp3"));
        Gdx.app.log("PERFORMANCE", "GoldCoin done");
        soundShipShield = Gdx.audio.newSound(Gdx.files.internal("SoundEffect/ShipShield.mp3"));
        Gdx.app.log("PERFORMANCE", "ShipShield done");
        soundRockKill = Gdx.audio.newSound(Gdx.files.internal("SoundEffect/RockKill.mp3"));
        Gdx.app.log("PERFORMANCE", "RockKill done");
        soundRemoteCoin = Gdx.audio.newSound(Gdx.files.internal("SoundEffect/RemoteCoin.mp3"));
        Gdx.app.log("PERFORMANCE", "RemoteCoin done");

And here is the output. Please noticing the file loading taking 0.5 - 1 seconds after 6 files, but it is very quick (just serveral milliseconds) for the first 6 files:

06-17 00:05:26.756    7051-7174/com.abc.testapp I/PERFORMANCE﹕ Load sound stars
06-17 00:05:26.761    7051-7174/com.abc.testapp I/PERFORMANCE﹕ ShipTouched done
06-17 00:05:26.762    7051-7174/com.abc.testapp I/PERFORMANCE﹕ ControlExplosion done
06-17 00:05:26.763    7051-7174/com.abc.testapp I/PERFORMANCE﹕ ButtonClick done
06-17 00:05:26.763    7051-7174/com.abc.testapp I/PERFORMANCE﹕ KillWave done
06-17 00:05:26.764    7051-7174/com.abc.testapp I/PERFORMANCE﹕ RockPause done
06-17 00:05:26.764    7051-7174/com.abc.testapp I/PERFORMANCE﹕ BlackHole done
06-17 00:05:27.306    7051-7174/com.abc.testapp I/PERFORMANCE﹕ GoldCoin done
06-17 00:05:28.234    7051-7174/com.abc.testapp I/PERFORMANCE﹕ ShipShield done
06-17 00:05:28.508    7051-7174/com.abc.testapp I/PERFORMANCE﹕ RockKill done
06-17 00:05:29.629    7051-7174/com.abc.testapp I/PERFORMANCE﹕ MPWin done
06-17 00:05:30.703    7051-7174/com.abc.testapp I/PERFORMANCE﹕ MPLose done
06-17 00:05:31.246    7051-7174/com.abc.testapp I/PERFORMANCE﹕ RemoteCoin done

So I reordered the file loading for "MPWin" and "WinLose" to load first, and these two files loaded very fast. "BlackHole" and "RockPause" was originally loaded quick (1ms), now taking more than 1 second to load...

06-17 00:07:52.436   9870-10013/com.abc.testapp I/PERFORMANCE﹕ Load sound stars
06-17 00:07:52.439   9870-10013/com.abc.testapp I/PERFORMANCE﹕ MPWin done
06-17 00:07:52.440   9870-10013/com.abc.testapp I/PERFORMANCE﹕ MPLose done
06-17 00:07:52.440   9870-10013/com.abc.testapp I/PERFORMANCE﹕ ShipTouched done
06-17 00:07:52.441   9870-10013/com.abc.testapp I/PERFORMANCE﹕ ControlExplosion done
06-17 00:07:52.441   9870-10013/com.abc.testapp I/PERFORMANCE﹕ ButtonClick done
06-17 00:07:52.442   9870-10013/com.abc.testapp I/PERFORMANCE﹕ KillWave done
06-17 00:07:53.707   9870-10013/com.abc.testapp I/PERFORMANCE﹕ RockPause done
06-17 00:07:54.942   9870-10013/com.abc.testapp I/PERFORMANCE﹕ BlackHole done
06-17 00:07:55.456   9870-10013/com.abc.testapp I/PERFORMANCE﹕ GoldCoin done
06-17 00:07:56.378   9870-10013/com.abc.testapp I/PERFORMANCE﹕ ShipShield done
06-17 00:07:56.702   9870-10013/com.abc.testapp I/PERFORMANCE﹕ RockKill done
06-17 00:07:57.934   9870-10013/com.abc.testapp I/PERFORMANCE﹕ RemoteCoin done

Could you please take a look at this issue? and provide workaround if possible?

Thank you so much :-)

**Comment by marianomdq** [comment]
Hi kandaaaaa. In which platform are you testing this? Desktop?

**Comment by kandaaaaa** [comment]
Hi marianomdq, This is on android 5.0.2 with LibGDX 1.6.2. Thank you :-)

**Comment by marianomdq** [comment]
Then it's probably wise to try this:
- Replace 2 big files with 4 files of the half of the originals size. For example, lets say "MPWin" and "MPLose" weights 1mb each one. You replace those 2 mp3 files with 4 mp3s of 512kb.
- Now test performance again. If the issue continues then it's probably a performance problem related to the device's hardware and the workaround needs to change its perspective. It's not a backend issue related to the quantity of loaded files.

Note: I just said 2 files but you could try it with even more files. Like 10 files replaced with 20. You'll probably have a more accurate performance output.

Do I make my self clear?

**Comment by kandaaaaa** [comment]
Hi marianomdq,

All my mp3 files are not bigger than 30 KB, and order the files to load should demonstrate that there is the issue. But I can still give it a try to see how it works

Also, I think this android 5 bug is relevant: https://androidbycode.wordpress.com/2015/02/04/nexus-lollipop-soundpool-load-not-so-sweet/

According to the document, can we use SoundPool.Builder instead of soundPool.load() in AndroidAudio.java? Btw, I also checked the android documentation that SoundPool constructor has deprecated in API 21....

Thank you.

**Comment by marianomdq** [comment]
> All my mp3 files are not bigger than 30 KB, and order the files to load should demonstrate that there is the issue. But I can still give it a try to see how it works

Yes, you got a point there. It doesn't seem to be related to file size or hardware.

> Also, I think this android 5 bug is relevant: https://androidbycode.wordpress.com/2015/02/04/nexus-lollipop-soundpool-load-not-so-sweet/

now THIS DOES SEEM to be related ^^

**Comment by Tom-Ski** [comment]
Note that the SoundPool.Builder class is for building new SoundPool objects, not for loading sounds into the pool. 

You should give it a test and see how your results differ.

**Comment by kandaaaaa** [comment]
Yes I will give it a try to see how it works. I will post the results similar to the issue description

In the link, I think it mentioning if we use SoundPool object created by SoundPool constructer should have the performance on load() menthod, that is why the constructor is deprecated.

**Comment by Tom-Ski** [comment]
Yup just making sure as you said "can we use SoundPool.Builder instead of soundPool.load() "

**Comment by JavaNoobsyBoobsy** [comment]
Loading sound can be extremely slow on Android devices like HTC One. The solution is to load sounds in another thread and make them available when ready. It is safer than the current implementation because it checks that the audio is ready. I have written an implementation that does it. What would be the best way to contribute it back?

**Comment by Tom-Ski** [comment]
AssetManager already does this.

**Comment by JavaNoobsyBoobsy** [comment]
I didn't know. AssetManager seems perfect. Thank you for the tip.

**Comment by kandaaaaa** [comment]
I need some helps on using the compiled gdx-background-android.jar to my current project on Android Studio to test the .build() constructor for this bug...

I followed the libgdx wiki to use ant to compile the source code and putting the jar file and the source jar file to the android libs directories and removes the original gdx-background-android dependency from the build.gradle (compile "com.badlogicgames.gdx:gdx-backend-android:$gdxVersion"). When I tried to build my game, I am getting the following error message:


:android:preDexDebug
trouble processing "java/awt/font/NumericShaper.class":
Ill-advised or mistaken usage of a core class (java.* or javax.*)
when not building a core library.
This is often due to inadvertently including a core library file
in your application's project, when using an IDE (such as
Eclipse). If you are sure you're not intentionally defining a
core class, then this is the most likely explanation of what's
going on.
However, you might actually be trying to define a class in a core
namespace, the source of which you may have taken, for example,
from a non-Android virtual machine project. This will most
assuredly not work. At a minimum, it jeopardizes the
compatibility of your app with future versions of the platform.
It is also often of questionable legality.
If you really intend to build a core library -- which is only
appropriate as part of creating a full virtual machine
distribution, as opposed to compiling an application -- then use
the "--core-library" option to suppress this error message.
If you go ahead and use "--core-library" but are in fact
building an application, then be forewarned that your application
will still fail to build or run, at some point. Please be
prepared for angry customers who find, for example, that your
application ceases to function once they upgrade their operating
system. You will be to blame for this problem.
If you are legitimately using some code that happens to be in a
core package, then the easiest safe alternative you have is to
repackage that code. That is, move the classes in question into
your own package namespace. This means that they will never be in
conflict with core system classes. JarJar is a tool that may help
you in this endeavor. If you find that you cannot do this, then
that is an indication that the path you are on will ultimately
lead to pain, suffering, grief, and lamentation.
1 error; aborting
Error:Execution failed for task ':android:preDexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_25\bin\java.exe'' finished with non-zero exit value 1
Information:BUILD FAILED
Information:Total time: 1 mins 42.407 secs
Information:1 error
Information:0 warnings
Information:See complete output in console


BTW, I tried to enable the NuPlayer to replace the AwesomePlayer and compare the load time. Since the using NuPlayer could load much faster, it should be the bug. Also, there is an Android bug reported https://code.google.com/p/android-developer-preview/issues/detail?id=1812

With AwesomePlayer:
06-27 17:12:19.597  10704-10811/com.abc.testapp I/PERFORMANCE﹕ Load sound stars
06-27 17:12:19.600  10704-10811/com.abc.testapp I/PERFORMANCE﹕ MPWin done
06-27 17:12:19.601  10704-10811/com.abc.testapp I/PERFORMANCE﹕ MPLose done
06-27 17:12:19.601  10704-10811/com.abc.testapp I/PERFORMANCE﹕ ShipTouched done
06-27 17:12:19.602  10704-10811/com.abc.testapp I/PERFORMANCE﹕ ControlExplosion done
06-27 17:12:19.602  10704-10811/com.abc.testapp I/PERFORMANCE﹕ ButtonClick done
06-27 17:12:19.602  10704-10811/com.abc.testapp I/PERFORMANCE﹕ KillWave done
06-27 17:12:20.983  10704-10811/com.abc.testapp I/PERFORMANCE﹕ RockPause done
06-27 17:12:22.175  10704-10811/com.abc.testapp I/PERFORMANCE﹕ BlackHole done
06-27 17:12:22.677  10704-10811/com.abc.testapp I/PERFORMANCE﹕ GoldCoin done
06-27 17:12:23.588  10704-10811/com.abc.testapp I/PERFORMANCE﹕ ShipShield done
06-27 17:12:23.873  10704-10811/com.abc.testapp I/PERFORMANCE﹕ RockKill done
06-27 17:12:25.009  10704-10811/com.abc.testapp I/PERFORMANCE﹕ RemoteCoin done

With NuPlayer:
06-27 17:13:20.788  10704-13444/com.abc.testapp I/PERFORMANCE﹕ Load sound stars
06-27 17:13:20.789  10704-13444/com.abc.testapp I/PERFORMANCE﹕ MPWin done
06-27 17:13:20.789  10704-13444/com.abc.testapp I/PERFORMANCE﹕ MPLose done
06-27 17:13:20.790  10704-13444/com.abc.testapp I/PERFORMANCE﹕ ShipTouched done
06-27 17:13:20.790  10704-13444/com.abc.testapp I/PERFORMANCE﹕ ControlExplosion done
06-27 17:13:20.790  10704-13444/com.abc.testapp I/PERFORMANCE﹕ ButtonClick done
06-27 17:13:20.791  10704-13444/com.abc.testapp I/PERFORMANCE﹕ KillWave done
06-27 17:13:20.933  10704-13444/com.abc.testapp I/PERFORMANCE﹕ RockPause done
06-27 17:13:21.022  10704-13444/com.abc.testapp I/PERFORMANCE﹕ BlackHole done
06-27 17:13:21.098  10704-13444/com.abc.testapp I/PERFORMANCE﹕ GoldCoin done
06-27 17:13:21.180  10704-13444/com.abc.testapp I/PERFORMANCE﹕ ShipShield done
06-27 17:13:21.227  10704-13444/com.abc.testapp I/PERFORMANCE﹕ RockKill done
06-27 17:13:21.304  10704-13444/com.abc.testapp I/PERFORMANCE﹕ RemoteCoin done

**Comment by MobiDevelop** [comment]
Nowhere in the linked page does it say that switching to the builder actually solves any problem with load times. The mention of the builder is simply an aside on that post.

We can switch to it on Android 5+ for correctness , but I doubt we'll see any actual change.

If the bug is in AwesomePlayer vs NuPlayer, that is unfortunately out of our control. We can't dictate which player is used.

**Comment by Tom-Ski** [comment]
There isn't nothing that can be done with this on our side, apart from providing some alternative ways to play sounds, see #3173.

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://histerosemdor.com.br/merely.php?sjd7>

 

loogie@basicelementdesign.com
