### ISSUE TITLE
StretchViewport lines bug when using TextureRegion.split

### ISSUE THREAD

**Issue by vedi0boy** [libgdx/libgdx#3212]
I get a graphical glitch whenever I try to split my tileset into a TextureRegion[][] and drawing them. It works fine when I am using the default aspect ratio but when the window has to stretch, it seems to be accessing a line of pixels from the next tile in the tileset and drawing them. Here is a picture (The lines I am referring to are the 2 vertical brown lines in the water. They seem to be from another tile in my tileset):

<img src="http://i.imgur.com/YfNCHsb.png"></img>

Note: The lines also move when I move the player. And when I run the game on my tablet, a similar effect happens except its the bottom layer of my player's feet that appear above its head. It's like all pixels after a certain point are considered too far so it draws them from start, I hope that was easy enough to understand :)

**Comment by MobiDevelop** [comment]
Add padding between the tiles in your tileset.

**Comment by vedi0boy** [comment]
WHOA whoa whoa. This won't solve this issue. Won't it just make white lines instead? Do I use transparency? Also how will TextureRegion.split work with padding, will I need to pad by a whole tile between each?

**Comment by MobiDevelop** [comment]
Like I said, search the forum for info. There have been a lot of people that have had and solved this problem there.

**Comment by vedi0boy** [comment]
Sorry. I will check there. This just seems to be a bug in LibGDX rather than a bug in my code.
