### ISSUE TITLE
Please improve GlyphLayout by adding get and set methods to access its properties.

### ISSUE THREAD

**Issue by AgrarPirat** [libgdx/libgdx#3213]
Please add get() and set() methods for the following properties of GlyphLayout:
* color
* font
* width (to re-layout the text in case the size of the displayed ares has changed)
* alignment
* wrapping
* text (get only)

Currently those properties can only be set all together by either creating a new instance of GlyphLayout or by calling one of the setText() methods. Unfortunately this makes GlyphLayout cumbersome to use if, for example, the text color throughout the whole game should be changed.
Also, it would be very useful if the text could be queried at a later time.

**Comment by NathanSweet** [comment]
GlyphLayout has a list of runs, width, and height as public fields. GlyphRun exposes all its fields as public. Other data such as text, alignment, or wrap is used for layout but is not stored, you can store that yourself.
