### ISSUE TITLE
[feature request] AudioRecorder/Device support for ByteBuffers

### ISSUE THREAD

**Issue by entangledloops** [libgdx/libgdx#3214]
It would be great if we could do a ByteBuffer read/write, especially in AudioRecorder. ByteBuffers can be passed down by address to JNI directly, and most hardware expects to fill byte buffers anyway. I wouldn't expect the additional methods to be difficult to patch in, but I'm not familiar with the source. The current implementation forces me to either copy shorts or re-implement my own OS-specific code.

I do understand the motivation for using shorts when gdx only supports 16-bit PCM (which is fine), but I could use the direct access performance improvement.

Thanks!

**Comment by xoppa** [comment]
Please include the required information to reproduce the actual issue you're having. The arrays are passed in as critical array, which you can also do in whatever it is you are trying to do.
