### ISSUE TITLE
No way to set the crossOrigin attribute on an ImageElement using AssetDownloader

### ISSUE THREAD

**Issue by WillCalderwood** [libgdx/libgdx#3216]
I'm trying to load Facebook profile pictures into the GWT version of my game and I'm struggling with cross origin issues despite all the required headers being in place. From this blog
http://blog.chromium.org/2011/07/using-cross-domain-images-in-webgl-and.html

It looks like a specific crossOrigin attribute needs to be set on the image.

Without this it's not possible to load cross domain images into a texture. Is this something that can be resolved in libgdx, or is this a GWT issue?

**Comment by WillCalderwood** [comment]
Not to worry, I just noticed the ImageElement.setAttribute method.

**Comment by WillCalderwood** [comment]
I'm reopening this as I can't get it working. I believe the `crossOrigin` attribute needs to be set on the `ImageElement` before the image is requested. Using the `AssetDownloader`, I can't see a way that I can get access to the `ImageElement` until the `onSuccess` event is fired. I believe we need to be able to set `crossOrigin = "anonymous";` at the point the image element is created. Maybe an overloaded version of AssetDownloader.loadImage should be created?

The code I use for downloading a crossDomain texture asset is as follows.

    @Override
    public void downloadPixmap(final String url, final DownloadPixmapResponse response) {
        new Image(url);

        try {
            AssetDownloader loader = new AssetDownloader();
            loader.setUseBrowserCache(false);

            loader.loadImage(url, "image/jpg", new AssetDownloader.AssetLoaderListener<ImageElement>() {
                @Override
                public void onProgress(double amount) {
                }

                @Override
                public void onFailure() {
                    Gdx.app.log("Image Download", "onFailure");
                    response.downloadFailed(null);
                }

                @Override
                public void onSuccess(ImageElement result) {
                    result.setAttribute("crossDomain", "");
                    Gdx.app.log("Image Download", "onSuccess");
                    HtmlLauncher.application.getPreloader().images.put(url, result);
                    response.downloadComplete(new Pixmap(Gdx.files.internal(url)));
                }
            });

        } catch (Exception e) {
            Gdx.app.log("Error", e.getMessage(), e);
        }
    }

**Comment by WillCalderwood** [comment]
I've tried delving into this a little more deeply by taking a copy of the AssetDownloader class and making what I thought were the required changes, but even wtithout any changes I was getting the javascript error `h_0.onEvent is not a function`.

I'm not sure my understanding of GWT and javsscript are really up to this!

I also tried writing some new code from scratch but I couldn't get that working either.

Here's my stackoverflow question where this is discussed with an example code snippit showing that the image returned by the URL I'm using can be loaded into a texture of the crossOrigin attribute is set.
http://stackoverflow.com/questions/30945945/tainted-canvases-may-not-be-loaded-cross-domain-issue/30956367?noredirect=1#comment49973145_30956367

**Comment by WillCalderwood** [comment]
Example code to reproduce the issue
    
    public class MyGdxGame extends ApplicationAdapter {
        public static Texture textTexture;
        SpriteBatch batch;
        Texture img;
        public static ClickListener listener = new ClickListener();
    
        @Override
        public void create() {
            batch = new SpriteBatch();
            img = new Texture("badlogic.jpg");
    
            if (listener != null) {
                listener.cancel();
                listener = null;
            }
        }
    
        @Override
        public void render() {
            Gdx.gl.glClearColor(1, 0, 0, 1);
            Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
            batch.begin();
            batch.draw(img, 0, 0);
    
            if (textTexture != null) {
                batch.draw(img, 100, 100);
            }
    
            batch.end();
        }
    }


    public class HtmlLauncher extends GwtApplication {
    
        @Override
        public GwtApplicationConfiguration getConfig() {
            return new GwtApplicationConfiguration(480, 320);
        }
    
        @Override
        public ApplicationListener getApplicationListener() {
            return new MyGdxGame();
        }
    
    
        @Override
        public void onModuleLoad() {
            MyGdxGame.listener = new ClickListener(){
                @Override
                public void cancel() {
                    downloadPixmap("https://graph.facebook.com/1387819034852828/picture?width=150&height=150");
                    //downloadPixmap("http://localhost:8080/html/assets/badlogic.jpg");  // This works fine
                }
            };
    
            super.onModuleLoad();
        }
    
        public void downloadPixmap(final String url) {
            try {
                AssetDownloader loader = new AssetDownloader();
                loader.setUseBrowserCache(false);
    
                loader.loadImage(url, "image/jpg", new AssetDownloader.AssetLoaderListener<ImageElement>() {
                    @Override
                    public void onProgress(double amount) {
                    }
    
                    @Override
                    public void onFailure() {
                    }
    
                    @Override
                    public void onSuccess(ImageElement result) {
                        getPreloader().images.put(url, result);
                        MyGdxGame.textTexture = new Texture(new Pixmap(Gdx.files.internal(url)));
                    }
                });
    
            } catch (Exception e) {
                Gdx.app.log("Error", e.getMessage(), e);
            }
        }
    }

**Comment by WillCalderwood** [comment]
I eventually got this working for me with the following hacky code. In the longer term, integration with the AssetDownloader would be a good thing.

    public void downloadPixmap(final String url, final DownloadPixmapResponse response) {
        final RootPanel root = RootPanel.get("embed-html");
        final Image img = new Image(url);
        img.getElement().setAttribute("crossOrigin", "anonymous");
        img.addLoadHandler(new LoadHandler() {

            @Override
            public void onLoad(LoadEvent event) {
                HtmlLauncher.application.getPreloader().images.put(url, ImageElement.as(img.getElement()));
                response.downloadComplete(new Pixmap(Gdx.files.internal(url)));
                root.remove(img);
            }
        });
        root.add(img);
    }

**Comment by MobiDevelop** [comment]
I don't have any problem with adding a parameter to specify the crossOrigin attribute in the `loadImage` method if you've got a PR for that.

**Comment by WillCalderwood** [comment]
@MobiDevelop I'll have to get more familiar with GIT and building libgdx from source to make the change and test it. I'll look at doing it in the not too distant future and submit a PR.
