### ISSUE TITLE
glGetTexLevelParameter not implemented

### ISSUE THREAD

**Issue by FyiurAmron** [libgdx/libgdx#3218]
https://www.opengl.org/wiki/GLAPI/glGetTexLevelParameter

it's present in core since 1.0 till 4.5, so I guess it's kinda ubiquitous. Not a trace of it in GL20/GL30 though. Is there any reason for the lack of it, or it's just a random omission?

**Comment by MobiDevelop** [comment]
It was not added to OpenGL ES until 3.1 as far as I can tell. GL20 and GL30 abstract OpenGL ES 2.0 and 3.0 respectively, so wouldn't have been part of the API.

**Comment by FyiurAmron** [comment]
I checked it, you're obviously right; I wouldn't have expected that a call so old wouldn't be present at least in ES 3.0, but yeah, it's only recently added by `3.1`.

Still, it means that currently the only way to get it on supporting platforms is to call backend GL directly, e.g. `org.lwjgl.opengl.GL11.glGetTexLevelParameter()` or `android.opengl.GLES31.glGetTexLevelParameter()`? We don't have any bindings for ES 3.1 yet, do we?
