### ISSUE TITLE
allow easy delayed mipmap creation for Texture objects

### ISSUE THREAD

**Issue by FyiurAmron** [libgdx/libgdx#3219]
A real-life situation is an app that has low-quality set by the user, loads the textures without mipmaps, and then has the quality set to high (use mipmaps) by the user at run-time.

Currently, while the mipmaps can be created by the obvious
```
    texture.bind();
    Gdx.gl.glGenerateMipmap( GL20.GL_TEXTURE_2D ); 
```
it makes the Texture's TextureData state desync'ed with the real texture - `useMipmaps()` will return false, and there is no easy way to track if the texture actually has mipmaps or not (with the only solution coming to my mind being to create a separate data structure/class just to monitor the mipmap state of the Textures, making the TextureData useMipmaps() method completely useless); `glGetTexLevelParameter` is unavailable in libGDX since it's ES 3.1 addition; two TextureData implementations (File & ETC1) have package-private access on `useMipmaps` boolean, one (KTX) has it private - meaning that actually changing it requires nasty hacks. OTOH, calling `glGenerateMipmap()` defensively, even if the mipmaps are present, is a huge waste of GPU power, especially for applications with many textures loaded.

It would be a lot easier to deal with delayed mipmap creation by providing a Texture method `createMipmaps()` that would essentially do `bind(); Gdx.gl.glGenerateMipmap( GL20.GL_TEXTURE_2D );`, and then either switch the `useMipmaps` by some internal field access to its TextureData object, or just recreate the TextureData with that field updated (some package-private constructor just setting the fields and not doing the actual loading maybe?).

I'm asking this because extending Texture in implementation code is extremely tough since it's produced by many other libGDX classes (loaders, asset manager handler etc), so it basically requires porting all that tightly-coupled classes too. 

Note: I'm aware that it's near impossible to create CPU mipmaps after the pixmap has been disposed; still, HW mipmaps are readily available on most platforms, and we could just throw an exception if HW creation was impossible.

**Comment by xoppa** [comment]
Thanks! Sounds reasonable. Needs good testing though. Would it be possible for you to [send a PR](https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md)?

**Comment by FyiurAmron** [comment]
Sure, although I'd be really happy if https://github.com/libgdx/libgdx/pull/3262 could be pulled first; I hate spamming the PR queue with multiple concurrent PRs.

**Comment by xoppa** [comment]
Going to close this. Looking forward to your PR.
