### ISSUE TITLE
[feature request] adding something like JOGL's GLJPanel to the JOGL Backend

### ISSUE THREAD

**Issue by adam-law** [libgdx/libgdx#3221]
It's said that JOGL's GLJPanel works with [Java 8's SwingNode, allowing it to be embedded into JavaFX](http://www.java-gaming.org/topics/gljpanel-javafx/34103/msg/321543/view.html#msg321543). How it works is to do GLJPanel -> JFXPanel -> SwingNode -> Scene.

Currently, using LibGDX' LWJGLCanvas does not work with SwingNode, and nothing is displayed. Workarounds exist, such as the LWJGL-FX project, but it's not fully suited for production, as stuff like Box2dLights don't get rendered. A JOGL port of this project was made, but it forked from an earlier point of LWJGL-FX.

I wanted to know if an implementation similiar to GLJPanel for the JOGL backend is feasible / possible. Using LWJGL-FX has been great, in my experience, though I've recently found that Box2dLights doesn't render (maybe something to do with FBO). I'm hoping a port of GLJPanel will resolve things, once and for all, for devs who want to use JavaFX and LibGDX, at the same time.

Thanks.

Edit: Found that there was JOGL backend, and it's not the one for LWJGL (obviously).

**Comment by gouessej** [comment]
Hi

If it's up to be, it's up to me as usual:
http://forum.jogamp.org/GLJPanel-for-LibGDX-JOGL-backend-td4034741.html

You can close this report as the JogAmp LibGDX backend is actively maintained by the JogAmp community.

**Comment by adam-law** [comment]
Sorry to say this on a closed ticket, but the JogAmp team came through and we now have a working solution for embedding a LibGDX app in a JavaFX UI. It displays everything correctly, unlike the other JavaFX-based solutions found on the web, which fail to display stuff like Box2dLights, and likely, other FBO-types. as well

There're still things that need to be addressed, like getting the FPS count up, and memory usage, the latter of which the other solutions also suffer from.

Thanks gouessej :)
