### ISSUE TITLE
Strange behaviour with music.pause on GWT. isPlaying flag sometimes not being set.

### ISSUE THREAD

**Issue by WillCalderwood** [libgdx/libgdx#3223]
Looking at the code I can't see how this is happening, but it would appear the isPlaying flag is not always being set correctly when pause is called on the GWT back end.

I have a toggle button for tuning music on and off. Toggling on and off with the GWT back end was causing multiple tracks to play over the top of each other. Logging the state of the isPlaying flag when pressing the toggle button gave the following output.

![image](https://cloud.githubusercontent.com/assets/6973062/8308499/00c702aa-19bd-11e5-8c4c-3859cbe28a85.png)

Calling stop instead of pause it seems to work correctly, producing the following output, as expected.

![image](https://cloud.githubusercontent.com/assets/6973062/8308523/1c6d5612-19bd-11e5-96c2-0067fd4dd7d4.png)

This all works fine on the desktop version, iOS and Android.

#### Edit
A bit more info. I was conditionally calling pause depending on the isPlaying flag. If I always call pause, whether playing or not, the isPlaying flag in never set to true when I resume the music.

**Comment by MobiDevelop** [comment]
Assumed fixed by #3895.
