### ISSUE TITLE
TIMED_WAIT of executorService makes ended app hanging for about a minute

### ISSUE THREAD

**Issue by FyiurAmron** [libgdx/libgdx#3226]
Current https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/net/NetJavaImpl.java creates an ExecutorService to handle async HTTP requests. It works OK, but after processing the requests it doesn't call `executorService.shutdown()` etc [nor allow doing it in any way, since `executorService` is private]. As such, the ExecutorService's thread stays in `TIMED_WAIT` for about a minute after finishing everything, preventing the app from closing properly. This is an issue for both desktop & Android (since both call NetJavaImpl routines), but it's IMO most problematic for desktop, since the app window appears to have freezed.

Repro case is to simply send a request and call `Gdx.app.exit()` immediately. The app will "hang" for about a minute. Calling `executorService.shutdown()` solves the issue.

The proposed solution is to either a) call `executorService.shutdown()` automagically, or to b) allow manual calling it, e.g. by 
```
    synchronized public void shutdown() {
        executorService.shutdown();
    }
```
 _and_ do it automagically on `Gdx.app.exit()` calls.

Further reading:
http://stackoverflow.com/questions/1250643/how-to-wait-for-all-threads-to-finish-using-executorservice
http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ExecutorService.html

PS. Completely suppressing all the `IOException`s @ L52, L68, L87 & L117 makes identifying problems with HTTP services extremely hard (the thrown `IOException`s are actually very useful for identifyng the client-side problems with the connection); I'd given much for a switch allowing the exceptions to be propagated or at least logged/wrapped/retained. I'm currently using my own HTTP-related code due to above problems, but I hardly see that as a permanent solution when using net-enabled lib such as libGDX.

**Comment by MobiDevelop** [comment]
Shutting down the executor is probably something a LifecycleListener could/should handle.

**Comment by FyiurAmron** [comment]
Note: after digging around some more, it's obvious to me that what what I outlined above could be not enough... It reduced the delays on my box, but there's still a significant wait period after last HTTP request has been succesfully sent (`handleHttpResponse()` called), with the main thread dead already and some socket activity going on. There obviously _is_ somethings fishy going on with libGDX's HTTP requests, w.r.t. threading...

**Comment by FyiurAmron** [comment]
Note: to reproduce the issue, it's strictly necessary to *throw an uncaught exception*, asynchronously, after sending the HTTP request. Otherwise everything seems to be OK. The HTTP request finishes and the exception propagates, but the app hangs for some time. Repro case here: https://github.com/FyiurAmron/GdxNetImplTimeoutBug - it could be reduced even more, but I wanted to provide a real, working example for it.
