### ISSUE TITLE
Json serializer. Writing null values with a known type

### ISSUE THREAD

**Issue by WillCalderwood** [libgdx/libgdx#3235]
in Json.java writeValue can take a known type and an object, from which we get the actual type.

The first thing that writeValue does is check if the object is null, if it is it returns null. However, I believe if the value is null, it should do the following so that custom serializers are considered for null types.

        if (value == null) {
            Serializer serializer = classToSerializer.get(knownType);
            if (serializer != null) {
                serializer.write(this, value, knownType);
                return;
            }
            writer.value(null);
            return;
        }

**Comment by NathanSweet** [comment]
This could work:
```
if (value == null) {
	if (knownType != null) {
		Serializer serializer = classToSerializer.get(knownType);
		if (serializer != null) {
			serializer.write(this, value, knownType);
			return;
		}
	}
	writer.value(null);
	return;
}
```
Except Serializer `write` does not specify `object` can be null. All serializers will need to null check. This could break existing code and adds boilerplate since few serializers will want to handle null.

**Comment by WillCalderwood** [comment]
Passing null to `classToSerializer.get(knownType);` is fine isn't? It just returns null.

Fair point about breaking existing code though - that said, I feel that how it currently works is incorrect. I'd assume that if a custom serializer is specified it should be called no matter what. I also noticed the current code performs serialization on primitive types before checking for custom serializers, so it's not possible to add custom serializers for primitive types either.

I'm stumbling across this because I'm creating a GWT version of my game, so I'm switching from using Jackson for all Json to using the libgdx classes and I'm trying to maintain compatibility between the Json.

I think my fundamental point is what I said before. *"I'd assume that if a custom serializer is specified it should be called no matter what."*

If others think this is incorrect, then that's fair enough, please just close the issue. I just thought I should throw it out there.

**Comment by NathanSweet** [comment]
ObjectMap disallows null keys, so passing null to `get` would fail.

We could have `NullSerializer extends Serializer` which would be a tag interface, allowing nulls to `write` and allowing returning null from `read`. Though, why do you want to customize null? What would you write instead? This use case has never come up.

Similarly, why would you want to customize primitive serialization? What would you write?

Keep in mind the Json class has more limitations than just these. JSON as a format just isn't a great fit for complex object serialization. Eg, it cannot easily support references. I suggest using [Kryo](https://github.com/EsotericSoftware/kryo) for complex serialization.

**Comment by WillCalderwood** [comment]
I'm pretty sure I tested passing null to get as a watch and it just
returned null, I could be wrong though. I've not looked at the code for
ObjectMap.

Custom serialization of null was something I happened to stumble across
when I was trying to work out why it wasn't hitting my serializer, it's not
something I actually need to do, it just wasn't the behaviour I expected.
With regards to customizations of primitives, the issue I was having was
libgdx writing an array of Longs as an array of long objects rather than
just an array of numeric values, which is what Jackson expected.

I can obviously work around this by customising serialization of the
containing class, so it's not a major issue for me, it's just not the
behaviour I would expect having specified a custom serializer.

Cheers for the pointer towards Kryo, I'll take a look.

**Comment by NathanSweet** [comment]
You'll get a nasty type wrapper even for primitives when the type is not known, eg:

```
public static void main (String[] args) throws Exception {
	Json json = new Json();
	System.out.println(json.toJson(new long[] {1, 2, 3}));
	System.out.println(json.toJson(new Object[] {1, 2, 3}));
	System.out.println(json.toJson(new Object[] {1, 2, 3}, null, long.class));
}
```

That last one specifies the element type so wrappers aren't output. You can also use Json `setElementType` for your classes.

I highly suggest Kryo (but then it's my lib :D), using TagFieldSerializer. It is fast and allows your code to evolve without breaking previously serialized bytes. The evolution is limited, but in practice it is good enough for almost all purposes and code can be written to fix any situations where it isn't.

**Comment by WillCalderwood** [comment]
Thanks for the tips with the libgdx json. I'll take a look at Kyro. I'm
guessing I probably wont use it now as all my json code is pretty much
working again after my transition from Jackson. Looks like a useful lib
though, so I'll definitely make a note for the future.

**Comment by badlogic** [comment]
Closing this out.
