### ISSUE TITLE
[HTML/GWT Backend] HttpRequest doesn't work with custom headers

### ISSUE THREAD

**Issue by JFixby** [libgdx/libgdx#3242]
Example code:
```
public class HttpRequestTest extends ApplicationAdapter {

	@Override
	public void create() {
		go();
	}

	public static void go() {
		Gdx.app.setLogLevel(Application.LOG_DEBUG);

		com.badlogic.gdx.Net.HttpRequest gdx_request = new com.badlogic.gdx.Net.HttpRequest();

		gdx_request.setUrl("http://localhost:31676/entry-point");
		gdx_request.setMethod("GET");
		gdx_request.setHeader("Custom-Header", "Hello");

		HttpResponseListener httpResponseListener = new com.badlogic.gdx.Net.HttpResponseListener() {

			@Override
			public void handleHttpResponse(
					com.badlogic.gdx.Net.HttpResponse httpResponse) {
				com.badlogic.gdx.net.HttpStatus status = httpResponse
						.getStatus();
				log("status", status);
				int statusCode = status.getStatusCode();
				log("statusCode", statusCode);

				log("httpResponse", httpResponse);

				java.util.Map<String, java.util.List<String>> gdx_result_headers = httpResponse
						.getHeaders();

				log("gdx_result_headers", gdx_result_headers);

				log("headers.size", gdx_result_headers.size());

				for (Iterator<String> i = gdx_result_headers.keySet()
						.iterator(); i.hasNext();) {
					String key = i.next();
					java.util.List<String> values = gdx_result_headers.get(key);
					log(" " + i, values);
				}

				exit();
			}

			@Override
			public void failed(Throwable t) {
				log("failed", t);
				t.printStackTrace();
				exit();
			}

			@Override
			public void cancelled() {
				log("cancelled");
				exit();
			}

		};
		Gdx.net.sendHttpRequest(gdx_request, httpResponseListener);

	}

	public static void log(String string) {
		Gdx.app.error("G", string + "");
	}

	public static void log(String name, Object value) {
		Gdx.app.error("G", name + " > " + value);
	}

	private static void exit() {
		System.exit(0);
	}

}
```

Error message:
![gdx](https://cloud.githubusercontent.com/assets/1580663/8418062/eac93484-1eb0-11e5-8676-add3eb73f5e9.jpg)

The web server (http://localhost:31676/entry-point) didn't receive any incoming connections. So the request stuck somewhere at the backend side.

**Comment by MobiDevelop** [comment]
The browser is blocking cross-origin resource access (cross-origin includes different ports on the same host). Look up CORS for details and solutions.

This is not a libgdx specific problem so I'm going to go ahead and close this.

**Comment by JFixby** [comment]
I'm sorry but I didn't get it. What I suppose to fix?

My web server didn't receive any incoming connections from gwt-backend. Is it something wrong with the Jetty server on which the the gwt-backend is running on?

**Comment by MobiDevelop** [comment]
Look up CORS, that will tell you what you need to do to make this work. Alternatively, use the same origin (scheme, host, port).

**Comment by JFixby** [comment]
Ok, as I see from wiki: CORS is something that I have to fix on a server side.

I have two servers:
1) Jetty server provided by libGDX setup to run HTML/GWT backend.
2) My testing web server.

When I run the example code above my testing web server does not receive any incoming connections. Nothing.

This lefts the Jetty server provided by libGDX setup. Is it correct? Is it the Jetty I should fix?

**Comment by xoppa** [comment]
This is an issue tracker. Please use the forum or IRC if you need help, see https://github.com/libgdx/libgdx/wiki/Getting-Help.

**Comment by JFixby** [comment]
Ok, I want to report the issue:

Jetty server provided by libGDX setup to run HTML/GWT-backend doesn't work with custom headers.

Thank you.

**Comment by MobiDevelop** [comment]
The problem you are seeing has absolutely nothing to do with custom headers.

**Comment by JFixby** [comment]
Case A (https://github.com/libgdx/libgdx/issues/3243): I send HttpRequest. Testing web server receives incoming call.

Case B (This): I add one line of code: ```   gdx_request.setHeader("Custom-Header", "Hello"); ``` and request stuck at the client side. Testing web server does not receive any incoming connections.

Please see the output and example code above.

**Comment by MobiDevelop** [comment]
LibGDX uses standard GWT requests and the Gradle Jetty plugin. If you are seeing a problem, it is not due to libgdx code.

I suggest you learn and understand how cross-origin requests work.
