### ISSUE TITLE
update OpenAL to OpenAL Soft 1.16.0

### ISSUE THREAD

**Issue by FyiurAmron** [libgdx/libgdx#3253]
Since 1.16.0 has been around for about a year already (http://kcat.strangesoft.net/openal-releases/), I think it can be considered pretty stable. Is there a chance of updating the 1.15.1 DLLs to the newest ones? (I've also filed this on https://github.com/LWJGL/lwjgl/issues/117, yet the DLLs can be updated out-of-the-box without any LWJGL hassle by just renaming the 32/64-bit binaries got from the official http://kcat.strangesoft.net/openal-soft-1.16.0-bin.zip link)

note: you may try latest "nightlies" from http://repo.or.cz/w/openal-soft.git/ if you're feeling adventurous; they patch quite a lot of things vs 1.16.0; I think that (well, if preceded with some testing with some reference libGDX apps) using those shouldn't bring more trouble with OpenAL than we already have. Anyway, I have a hunch that 1.16.1 or 1.17 ain't that far away anyway.

As a side note: what's our status on LWJGL 3? AFAIK, it's 100% completed & stable, and it integrates newest OpenAL-Soft out-of-the-box.

**Comment by Antag99** [comment]
Mario is creating a new LWJGL 3 backend; like mentioned in the linked issue, the OpenAL libraries won't be updated for LWJGL 2.
