### ISSUE TITLE
add support for URL-safe base64 encoding

### ISSUE THREAD

**Issue by FyiurAmron** [libgdx/libgdx#3255]
Similarily to https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html , libGDX's base64 encoder should provide a way to encode with URL-safe (Table 2 of RFC 4648) charset. The change to existing code would be essentially trivial (e.g. adding another map with two last entries changed from `+`/`/` to `-`/`_` in https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/Base64Coder.java#L45 and providing a method to allow using those different maps here). Possibly allowing selecting other index 63/64 chars, because custom values are often needed, as shown in https://en.wikipedia.org/wiki/Base64#Implementations_and_history, would be great.

I can do a PR with my code implementing those changes, if anyone's interested.

**Comment by MobiDevelop** [comment]
A PR would be appreciated.

**Comment by FyiurAmron** [comment]
I haven't been able to test this extensively, so any comments/changes are welcome.

**Comment by xoppa** [comment]
Fixed in #3262
