### ISSUE TITLE
Music loop stops after a while

### ISSUE THREAD

**Issue by utgarda** [libgdx/libgdx#3256]
Background music loop starts ok and eventually stops after a minute or so, without provocation. Doesn't depend on playing any sfx sounds over it - same thing even if it's the only sound played at all.

```java
    Music music = Assets.getMusic(bgMusicName)
    music.setLooping(true)
    music.play()
```

    D/audio_hw_primary(  189): out_set_parameters: enter: usecase(0: deep-buffer-playback) kvpairs: routing=2
    I/NuPlayerDecoder(  189): [OMX.google.vorbis.decoder] resubmitting CSD
    W/SoftVorbis(  189): vorbis_dsp_synthesis returned -135
    I/NuPlayerDecoder(  189): [OMX.google.vorbis.decoder] resubmitting CSD
    W/SoftVorbis(  189): vorbis_dsp_synthesis returned -135
    I/AudioFlinger(  189): BUFFER TIMEOUT: remove(4096) from active list on thread 0xb5a96000
    D/audio_hw_primary(  189): disable_audio_route: reset and update mixer path: deep-buffer-playback
    D/audio_hw_primary(  189): disable_snd_device: snd_device(2: speaker)

Android 5.1.1, LG Nexus 5, LibGDX v1.6.3 , but same on other versions and devices.

**Comment by FyiurAmron** [comment]
http://review.cyanogenmod.org/#/c/86768/1//COMMIT_MSG
https://www.codeaurora.org/cgit/external/gigabyte/froyo-gb-dsds-7227/plain/frameworks/base/media/libstagefright/codecs/vorbis/dec/VorbisDecoder.cpp

seems it's a NuPlayer bug, VorbisDecoder errors and the sound stops.

**Comment by MobiDevelop** [comment]
Closing as not a libgdx issue, maybe someday Android will get audio right.
