### ISSUE TITLE
add no-arg constructor for VertexAttribute _or_ make the class non-final.

### ISSUE THREAD

**Issue by FyiurAmron** [libgdx/libgdx#3258]
VertexAttribute is currently little more than a POJO with a couple of static utility methods, yet it can't be deserialized because it misses a no-arg constructor, and it's impossible to provide one by derivation since the class is final. I am aware that the no-arg would be useless without reflective change of usageIndex, but that's not a problem for deserialization, while lack of no-arg obviously is.

**Comment by xoppa** [comment]
why would you want to serialize VertexAttribute in the first place?

**Comment by FyiurAmron** [comment]
I'm serializing ModelMesh.

**Comment by xoppa** [comment]
Why would you want to serialize ModelMesh in the first place?

**Comment by FyiurAmron** [comment]
Because ModelData uses it, and using ModelData is the easiest way to store data pre-parsed by ModelLoader.

**Comment by Antag99** [comment]
Why do you need to store pre-parsed data?

**Comment by FyiurAmron** [comment]
Because that's the easiest way to not have to parse it again?

**Comment by Antag99** [comment]
What's wrong with parsing it again?

**Comment by badlogic** [comment]
Deserialization will take longer than parsing. Please close this issue.

**Comment by badlogic** [comment]
Also, please stop using our tracker as a real-time chat. Go to #libgdx on
irc.freenode.net instear or use the forums.

**Comment by FyiurAmron** [comment]
@badlogic I didn't use the tracker as a chat. I posted an issue. I'm not responsible for behaviour of other people. I understand that your suggestion is that I shouldn't respond to questions?

**Comment by badlogic** [comment]
My request was aimed at everyone involved in this issue.

> I understand that your suggestion is that I shouldn't respond to
questions?

Suggesting that would make me an idiot. Is that what you are suggesting?

People were asking what you are trying to do, multiple times, as
serializing runtime data is an extremely uncommon use case. Please state
your motivation from the beginning so all information is available for
discussion. This brings down the number of back and forths and thereby
reduces noise on the tracker.

**Comment by badlogic** [comment]
Please don't edit your replies, i'm doing tracker maintenance via e-mail where edits will not turn up.

Posting your code and data in your first message would have given us all info we need to discuss this.

**Comment by FyiurAmron** [comment]
@badlogic I'm not suggesting anything; I don't understand what should I do in situation when multiple people ask me questions that are IMO completely irrelevant to the issue. I seriously considered not answering those questions, but I thought that would be straightforwardly rude. The problem for me was the lack of no-arg and impossibility to create one. I don't see how my usage pattern would be useful for anything else than trying to prove to me that what I was trying to do was invalid/illogical/inefficient. That, on the other hand, has completely nothing to do with the fact of VertexAttribute having neither no-arg nor any way of subclassing, since that problem is completely atomic.

**Comment by badlogic** [comment]
Again, my message was aimed at everybody, not just you.

As for the API change: removing final or adding no-arg constructors to classes with final fields (leaving them in an indetermined state) needs to be motivated with a usage scenario. If that scenario has a work around that doesn't involve changing the API in that way, we prefer that. Hence the need to know the scenario.
