### ISSUE TITLE
Stage.hit generated drag-events

### ISSUE THREAD

**Issue by ar-** [libgdx/libgdx#3266]
I'm using Stage2D. I have an Actor that implements all 3 touch events in a listener (touchDown, touchDrag, touchUp). It is used to move this actor on the screen.

In another part of the program I am using Stage.hit() to see which actor is at that position.

After a long time trying to find the cause for a weird error I found, that the hit()-method generates Drag events, so the Actor above starts moving suddenly weirdly.

Am I not supposed to use hit() by myself? Is it only meant to be used by the internal touchEvent stuff?

Example: I'm calling stage.hit(1,1,false) to check for a collision/overlap

then my Actor receives the InputEvent with event.getStageX() == event.getStageY() == 1

If that is the supposed behaviour, the documentation should be updated, because it doesn't say that I shouldn't use it.

Can anyone supply a quick patch?

**Comment by ar-** [comment]
Directly after writing this bug report, I found a fix for me. I use

stage.getRoot().hit(1,1,false)

instead of 

stage.hit(1,1,false)

to skip the input processing. I don't know why I didn't see that earlier.

**Comment by NathanSweet** [comment]
Not sure what "skip the input processing" means. 'stage.hit' takes stage coordinates. `stage.getRoot().hit` takes local coordinates for the root. Neither one results in input or drag events being fired.
