### ISSUE TITLE
Weird behavior with LwjglCanvas inside of a JSplitPane with java 8 on OSX

### ISSUE THREAD

**Issue by jonbonazza** [libgdx/libgdx#3268]
When using Java 8, the following code produces improper layout when application starts:

```java
package com.test;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.backends.lwjgl.LwjglCanvas;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.TextArea;

public class Main extends JFrame {


    public Main() {
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        JScrollPane sp = new JScrollPane(new TextArea());
        sp.setPreferredSize(new Dimension(300, 600));
        JPanel canvasPanel = new JPanel(new BorderLayout());
        LwjglCanvas renderCanvas = new LwjglCanvas(new ApplicationAdapter() {});
        canvasPanel.add(renderCanvas.getCanvas());

        JSplitPane splitPane = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, sp, canvasPanel);
        getContentPane().add(splitPane);

        setVisible(true);
        pack();
        setSize(1200, 768);
        setLocationRelativeTo(null);
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main();
            }
        });
    }
}
```

Basically, the canvas is not layed out properly and the JSplitPane divider is non-functional. If you resize the window (causing a redraw), then things go to normal.

I noticed three things:

1) this issue doesn't exist with java 7, so it may be a bug in java 8 itself.

2) the issue does not occur on windows... I haven't tried on linux, but it **does** occur on mac osx.

3) if I call ```new Main()``` directly, instead of via ```SwingUtilities.invokeLater()```, things work as intended, even on java 8.

I am not really sure what is causing this, and like I said, may very well be a bug in java8, but I thought I would bring it to your attention.

**Comment by jonbonazza** [comment]
Also should note that calling ```new Main()``` directly, as mentioned above as a workaround, causes an exception on Windows, so you need to check the platform first and react appropriately.

**Comment by MobiDevelop** [comment]
Sounds similar to issue #3008.

**Comment by NathanSweet** [comment]
Not sure what we can do. You might try poking at it by calling some Swing
layout methods until it works, than submit a PR with that black magic.

**Comment by badlogic** [comment]
We'll not fix this, integration with Swing is terrible and broken.
