### ISSUE TITLE
Implicit version number 110 not supported by GL3 forward compatible context

### ISSUE THREAD

**Issue by s0ft** [libgdx/libgdx#3273]
On some ATI graphics card you get the above error, the only work around is using this as the shader:
    static public ShaderProgram createDefaultShader () {
       String vertexShader = "#version 330 core\n"
          + "in vec4 " + ShaderProgram.POSITION_ATTRIBUTE + ";\n" //
          + "in vec4 " + ShaderProgram.COLOR_ATTRIBUTE + ";\n" //
          + "in vec2 " + ShaderProgram.TEXCOORD_ATTRIBUTE + "0;\n" //
          + "uniform mat4 u_projTrans;\n" //
          + "out vec4 v_color;\n" //
          + "out vec2 v_texCoords;\n" //
          + "\n" //
          + "void main()\n" //
          + "{\n" //
          + "   v_color = " + ShaderProgram.COLOR_ATTRIBUTE + ";\n" //
          + "   v_color.a = v_color.a * (255.0/254.0);\n" //
          + "   v_texCoords = " + ShaderProgram.TEXCOORD_ATTRIBUTE + "0;\n" //
          + "   gl_Position =  u_projTrans * " + ShaderProgram.POSITION_ATTRIBUTE + ";\n" //
          + "}\n";
       String fragmentShader = "#version 330 core\n"
          + "#ifdef GL_ES\n" //
          + "#define LOWP lowp\n" //
          + "precision mediump float;\n" //
          + "#else\n" //
          + "#define LOWP \n" //
          + "#endif\n" //
          + "in LOWP vec4 v_color;\n" //
          + "in vec2 v_texCoords;\n" //
          + "out vec4 fragColor;\n" //
          + "uniform sampler2D u_texture;\n" //
          + "void main()\n"//
          + "{\n" //
          + "  fragColor = v_color * texture(u_texture, v_texCoords);\n" //
          + "}";

I was wondering why this wasn't the shader that comes with Libgdx by default.

**Comment by FyiurAmron** [comment]
see https://github.com/libgdx/libgdx/issues/2605 ; exactly the same problem. Doing a search beforehand is always a good thing, mate.

also, it ain't the shader that comes with libGDX by default, because libGDX uses "ubershaders", supporting e.g. lighting & maps by default.

**Comment by xoppa** [comment]
Don't set `useGL30` to true if you don't want to use gles3.
