### ISSUE TITLE
New tooltips

### ISSUE THREAD

**Issue by nooone** [libgdx/libgdx#3275]
In case there was a PR prior to adding the new scene2d.ui `Tooltip`s, I've missed that. However now after trying them out I'd like to add my 2 cents and discuss them here a bit.

I have tooltips in nearly every game (prototype) of mine and I think they were really missing in libgdx, although I've never thought about contributing my own implementation. I'm happy they were added by @NathanSweet, but I personally find them to be too limited to really use them.

The `Tooltip` is actually no new widget (`Actor`), but instead an `EventListener`. That is nice, because it makes adding tooltips to actors very easy, but on the other hand it makes it harder to change what it is displaying.

Currently it assumes to display only a single text `Label` and nothing else. That might be enough for the most simple usecase of tooltip, but games these days usually display [a lot more information](https://www.google.de/search?q=game+tooltip&source=lnms&tbm=isch).

I suggest changing the current implementation while not many people are using it yet. I suggest making `Tooltip` a subclass of `Window` and having a seperate `TooltipListener`, which is responsible for adding the tooltip to the stage, removing it, triggering an animation, moving it with the pointer/finger etc. Maybe something similar to the following (+the extra stuff that the current implementation does, like disabling all of them, animations etc):

    public abstract class Tooltip extends Window {
    
        protected Actor targetActor;
        protected TooltipListener listener;
    
        public Tooltip(String title, Skin skin, final Actor targetActor) {
            super(title, skin, "tooltip");
            this.targetActor = targetActor;
    
            setTransform(true);
            setTouchable(Touchable.disabled);
    
            listener = new TooltipListener(this, true);
            targetActor.addListener(listener);
        }
    
        @Override
        public void act(float delta) {
            super.act(delta);
            if (targetActor != null && targetActor.getStage() == null) remove();
        }
    }

And the listener:

    public class TooltipListener extends InputListener {
    
        private boolean inside;
    
        private Actor tooltip;
        private boolean followCursor;
    
        private Vector2 position = new Vector2();
        private Vector2 tmp = new Vector2();
        private Vector2 offset = new Vector2(10, 10);
    
        public TooltipListener(Actor tooltip, boolean followCursor) {
            this.tooltip = tooltip;
            this.followCursor = followCursor;
        }
    
        @Override
        public boolean mouseMoved(InputEvent event, float x, float y) {
            if (inside && followCursor) {
                updateTooltipPosition(event, x, y);
            }
            return false;
        }
    
        @Override
        public void enter(InputEvent event, float x, float y, int pointer, Actor fromActor) {
            inside = true;
            event.getStage().addActor(tooltip);
            tooltip.setVisible(true);
            tooltip.toFront();
            updateTooltipPosition(event, x, y);
        }
    
        private void updateTooltipPosition(InputEvent event, float x, float y) {
            event.getListenerActor().localToStageCoordinates(tmp.set(x, y));
            tooltip.setPosition(tmp.x + position.x + offset.x, tmp.y + position.y + offset.y);
        }
    
        @Override
        public void exit(InputEvent event, float x, float y, int pointer, Actor toActor) {
            inside = false;
            tooltip.setVisible(false);
            tooltip.remove();
        }
    
        /**
         * The offset of the tooltip from the touch position.
         */
        public void setOffset(float offsetX, float offsetY) {
            offset.set(offsetX, offsetY);
        }
    }

The title should probably be optional though. For the most simple usecase we can add another `LabelTooltip` with a single label added to the window.

**Comment by Darkyenus** [comment]
>  I suggest making `Tooltip` a subclass of `Window`

As the presented `TooltipListener` does not really care what kind of actor it uses as a tooltip, why should the default `Tooltip` extend window? I would probably just add a label based tooltip (as it exists now) for convenience, and let the users create their own "rich tooltips". Because if I understand correctly, `TooltipListener` will handle all tooltip related logic anyway, so the actual tooltip actor should be easy to create and thus does not need a special subclass.

**Comment by nooone** [comment]
Extending Window will make sure that the tooltip will stay inside the visible area. Plus it is a `Table` which means it has a background which probably all tooltips will need. And Table itself is a very dynamic widget that you can basically use to add and display anything you want.

But you are right, `TooltipListener` does not depend on the `Tooltip` being a `Window` or `Table` (or even a `Tooltip`). People could also use it by itself and use any other `Actor` as their `Tooltip`.

**Comment by NathanSweet** [comment]
See what you think.

**Comment by nooone** [comment]
Looks good to me now. Got much more flexible and you were able to remove a big bunch of magic numbers as well :)

Will close this and try to use the new version asap. If I find something else, I'll reopen this.

Thanks for changing it!
