### ISSUE TITLE
Screen issue (Robovm) 

### ISSUE THREAD

**Issue by Yayo-Arellano** [libgdx/libgdx#3278]
I add a banner subview in top of the libgdx view just like this->

![Image of libgdx](https://dl.dropboxusercontent.com/u/78073642/ImagenesPosteadasEnForos/2014-01-02%2017.10.46.jpg)

All my buttons are set with scene2d, but i notice that i have to press below the buttons to get the changed event. 
if i do not add the banner view there is no problem about pressing the buttons.

I was looking the source code in the robovm back-end and i think the problem is the function getBounds, cause you are getting the size of all the screen, and not the view that is using libgx

As mario said in this comment its an issue with Libgdx. http://robovm.com/robovm-1-5-released-cross-platform-development-robopods/#comment-2128199229

**Comment by Tom-Ski** [comment]
#2105 related, do you have a test example with this layout so we can test?

**Comment by badlogic** [comment]
This has been fixed via #3590. Please report back if it didn't fix the issue for you.
