### ISSUE TITLE
Changes to JsonValue.toString break JSON nested class parsing.

### ISSUE THREAD

**Issue by yogeto** [libgdx/libgdx#3282]
In commits to JsonValue.java from Dec 18, 2014, the toString() method is changed to pre-pend its name to the contents. As a result the following JSON fails to parse:
{
"base" : [
    {
        "type" : "com.badlogic.gdx.graphics.Texture",
        "path" : "data/bg_2048.png",
        "parameters" : {
            class: com.badlogic.gdx.assets.loaders.TextureLoader$TextureParameter,
            "minFilter": "MipMap",
            "magFilter": "Linear",
            "genMipMaps": "true"
        }
    }
]
}

The call "String paramStr = jsonData.get("parameters").toString();" will result in:
Before the change: "{\nclass: com.badlogic.gdx.assets.loa......."
After the change: "parameters : {\nclass: com.badlogic.gdx.assets.loa......."

Subsequent call to json.fromJson(null, paramStr); fails to parse the string with exception: Error parsing JSON on line 2 near: class: "com.badlogic.gdx.assets.loaders.TextureLoader$TextureParameter"

**Comment by yogeto** [comment]
Worked around it by using prettyPrint(JsonWriter.OutputType.minimal, 0) instead of toString()

**Comment by NathanSweet** [comment]
I don't see an error.
```
public static void main (String[] args) throws Exception {
	JsonValue parse = new JsonReader().parse("{\r\n" + 
		"\"base\" : [\r\n" + 
		"{\r\n" + 
		"\"type\" : \"com.badlogic.gdx.graphics.Texture\",\r\n" + 
		"\"path\" : \"data/bg_2048.png\",\r\n" + 
		"\"parameters\" : {\r\n" + 
		"class: com.badlogic.gdx.assets.loaders.TextureLoader$TextureParameter,\r\n" + 
		"\"minFilter\": \"MipMap\",\r\n" + 
		"\"magFilter\": \"Linear\",\r\n" + 
		"\"genMipMaps\": \"true\"\r\n" + 
		"}\r\n" + 
		"}\r\n" + 
		"]\r\n" + 
		"}");
	System.out.println(parse.get("base").get(0).get("parameters").toString()); 
}
```
Always post an SSCCE!
