### ISSUE TITLE
TextureMapObject loaded with incorrect y value?

### ISSUE THREAD

**Issue by souzabrizolara** [libgdx/libgdx#3284]
I am have some problems to position correctly an TextureMapObject loaded from an tiled map.

The objects are loaded with an negative offset on y axis (equals to the size of the tile).
That is, the object is positionated below the expected position (viewed on tiled editor).

It seems that the problem is due to the fact that the x,y positions returned from tiled corresponds
to the bottom left point of the image, instead of the top-left point (like an rectangle object).
This can be checked on tiled, positioning an rectangle object and an image object on same position.
The rectangle should be drawed below the image.

The fix seems to be simple. Changing the line correspondent to the 243 line on BaseTmxMapLoader (on method loadObject).
Changing this:

         object.getProperties().put("y", (flipY ? y - height : y) * scaleY);

to this:

          object.getProperties().put("y", y * scaleY);

 I had tested quickly the change by extending the TmxMapLoader and copying the loadObject method.
But i have not tested this with an not flipped map.

To know, i am using the 0.12.3 version of tiled and i am rendering these objects with the following code (i had extended the OrthogonalTiledMapRenderer):

       @Override
	public void renderObject(MapObject object) {
		if(object instanceof TextureMapObject){
			TextureMapObject textObj = (TextureMapObject)object;
			TextureRegion texRegion = textObj.getTextureRegion();
			
			getBatch().draw(texRegion
							, textObj.getX() 
							, textObj.getY() 
							, textObj.getOriginX() 
							, textObj.getOriginY()
							, texRegion.getRegionWidth()
							, texRegion.getRegionHeight()
							, textObj.getScaleX() 
							, textObj.getScaleY()
							, textObj.getRotation()
							);
		}
	}

I hope have been clear. If you want, i can make a pull request with those little changes.

Thanks!

**Comment by saltares** [comment]
But it does work as expected with the default `OrthogonalTiledMapRenderer` doesn't it?

**Comment by MobiDevelop** [comment]
The default renderers don't render any objects.

**Comment by nooone** [comment]
I can confirm this. The `TextureMapObjects` are exactly 1 tile off on Y.

**Comment by MobiDevelop** [comment]
This appears to be due to a change in how Tiled stored these objects in the tmx file. The size of tile-backed objects did not previously carry a width and height, so the flipY thing never caused any problems. Now, these objects do have their own width and height, so they are being offset when they shouldn't be.

**Comment by nooone** [comment]
Poor scale, but well done :)
