### ISSUE TITLE
Slow Decal Batching

### ISSUE THREAD

**Issue by graham01** [libgdx/libgdx#3288]
As discussed in a previous issue, I am having some issues with batching lots of the decals that use the same TextureRegion, just different locations, colours and speeds.

Below is my class filtered just for the Decal setup and rendering. (I hope this is what you were after @xoppa ?) 

Currently just testing on a Sony Xperia Z, I don't have access to my other testing devices at the moment. But after 30 seconds or so it settles at roughly 30fps. A strange thing I just noticed, if DB.add(d) and DB.flush() are removed, it settles at 60fps, so setting 2000x Decal.setPosition and Decal.lookAt every frame is speedy enough, but removing Decal.setPositon and Decal.lookAt (and only rendering the stationary Decals) seems to sit around 50fps. Combine the 2 and boom, 30fps. 

    import com.badlogic.gdx.Gdx;
    import com.badlogic.gdx.Screen;
    import com.badlogic.gdx.graphics.Color;
    import com.badlogic.gdx.graphics.GL20;
    import com.badlogic.gdx.graphics.PerspectiveCamera;
    import com.badlogic.gdx.graphics.Texture;
    import com.badlogic.gdx.graphics.g2d.Sprite;
    import com.badlogic.gdx.graphics.g2d.TextureRegion;
    import com.badlogic.gdx.graphics.g3d.decals.CameraGroupStrategy;
    import com.badlogic.gdx.graphics.g3d.decals.Decal;
    import com.badlogic.gdx.graphics.g3d.decals.DecalBatch;
    import com.badlogic.gdx.math.MathUtils;
    import com.badlogic.gdx.math.Vector3;
    import com.badlogic.gdx.utils.Array;
    import com.badlogic.gdx.utils.viewport.FitViewport;
    import com.badlogic.gdx.utils.viewport.Viewport;
    
    public class DecalTest implements Screen {
    
        int APP_WIDTH = 1080;
        int APP_HEIGHT = 1080*Gdx.graphics.getHeight()/Gdx.graphics.getWidth();
        int scrWidth = Gdx.graphics.getWidth();
        int scrHeight = Gdx.graphics.getHeight();
    
        PerspectiveCamera cam3D;
        CameraGroupStrategy cam_strategy;
        Viewport viewport3D;
    
        DecalBatch DB;
    
        int noOfGasParticles = 2000;
        float[] initial_gas_angles = new float[noOfGasParticles];
        float[] gas_z_angles = new float[noOfGasParticles];
        float[] gas_x_angles = new float[noOfGasParticles];
        float[] gas_radii = new float[noOfGasParticles];
        float[] gas_speeds = new float[noOfGasParticles];
        Vector3[] gas_positions = new Vector3[noOfGasParticles];
        Vector3[] gas_axis = new Vector3[noOfGasParticles];
    
        Array<Decal> gas_decals = new Array<Decal>();
    
        public DecalTest() {
    
            cam3D = new PerspectiveCamera(60, 1, APP_HEIGHT / APP_WIDTH);
            viewport3D = new FitViewport(APP_WIDTH,APP_HEIGHT, cam3D);
            cam3D.near = 10.0f;
            cam3D.far = 6000.0f;
            cam3D.position.set(500,500,500);
            cam3D.lookAt(0,0,0);
            cam3D.up.set(0,1,0.2f);
            viewport3D.apply();
            cam3D.update();
    
            cam_strategy = new CameraGroupStrategy(cam3D);
    
            Gdx.gl.glEnable(GL20.GL_BLEND);
    
            DB = new DecalBatch(noOfGasParticles, cam_strategy);
    
            initialiseGas();
    
        }
    
        private void initialiseGas(){
    
            for(int i = 0; i < noOfGasParticles;i++){
                initial_gas_angles[i] = MathUtils.random(0f,360f);
                gas_z_angles[i] = MathUtils.random(-0.1f,0.1f);
                gas_x_angles[i] = MathUtils.random(-0.1f,0.1f);
                gas_axis[i] = new Vector3(gas_x_angles[i],1, gas_z_angles[i]);
                gas_radii[i] = MathUtils.random(250f,350f);
                gas_speeds[i] = ((50-Math.abs(300f- gas_radii[i]))/50f)*2+0.1f;
                gas_positions[i] = new Vector3(gas_radii[i]*MathUtils.sinDeg(initial_gas_angles[i]),0, gas_radii[i]*MathUtils.cosDeg(initial_gas_angles[i]));
            }
    
            Texture gas_t = new Texture(Gdx.files.internal("gas.png"));
            gas_t.setFilter(Texture.TextureFilter.Linear, Texture.TextureFilter.Linear);
    
            Sprite gas_spr = new Sprite(gas_t);
    
            for(int i = 0; i < noOfGasParticles;i++){
                Decal gas = Decal.newDecal(2,2,new TextureRegion(gas_spr),true);
                float col = (70-Math.abs(300f- gas_radii[i]))/70f;
                Color tint = new Color(1.0f,0.3f,col,0.3f);
                gas.setColor(tint);
                gas.setScale(MathUtils.random(1.0f,2.0f));
                gas.setBlending(GL20.GL_SRC_ALPHA, GL20.GL_ONE);
                gas.setPosition(gas_positions[i]);
                gas.lookAt(cam3D.position, cam3D.up);
                gas_decals.add(gas);
            }
        }
    
    
        @Override
        public void render(float delta) {
    
            Gdx.gl.glClearColor(0f, 0f, 0f, 1f);
            Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT | GL20.GL_DEPTH_BUFFER_BIT);
    
            int k = 0;
    
            for(Decal d: gas_decals) {
                d.setPosition(gas_positions[k]);
                d.lookAt(cam3D.position, cam3D.up);
                DB.add(d);
                k++;
            }
    
            DB.flush();
    
            for(int i = 0; i < noOfGasParticles;i++){
                gas_positions[i].rotate(gas_axis[i], gas_speeds[i]);
            }
    
            out("FPS " + Gdx.graphics.getFramesPerSecond());
    
        }
    
        private void out(Object msg) {
            Gdx.app.debug("info", msg.toString());
        }
    
        @Override
        public void resize(int width, int height) {
            viewport3D.update(width, height);
            cam3D.position.set(500,500,500);
            cam3D.lookAt(0,0,0);
            cam3D.up.set(0,1,0.2f);
            cam3D.update();
        }
    
        @Override
        public void pause() {
    
        }
    
        @Override
        public void resume() {
    
        }
    
        @Override
        public void dispose() {
            DB.dispose();
        }
    
        @Override
        public void show() {
    
        }
        @Override
        public void hide() {
    
        }
    
    }

⇩ gas.png is actually right here
![gas](https://cloud.githubusercontent.com/assets/12170223/8759878/75ad1822-2cf8-11e5-947e-e0d0ab0e20fd.png)
⇧

**Comment by graham01** [comment]
![gas](https://cloud.githubusercontent.com/assets/12170223/8759882/9f95cfb2-2cf8-11e5-8e4e-c0bdc91bae75.png)

**Comment by mk1x86** [comment]
fps don't scale linear with performance. That being said it's quite reasonable that rendering and setting position/lookAt combined result in 30 fps. I encountered that problem as well and wrote my own decal batch which supports multiple threads. That's prolly the way to go for you, too.

**Comment by graham01** [comment]
Thanks, would you be able to share this please?

**Comment by mk1x86** [comment]
it's highly customized, sorry. Doesn't even use the Decal class

**Comment by xoppa** [comment]
Please make sure to link to it when referring to a previous issue. I don't think that there's an actual issue here. If you render a lot then indeed it might cause your frame time to go up. In this case it looks like you're using Decals where you actually should be using Particles.
