### ISSUE TITLE
About the Listeners

### ISSUE THREAD

**Issue by sephirot47** [libgdx/libgdx#3289]
First of all, your library is AWESOME !!!

But it would be a good idea to make the *Listeners as Interfaces instead of classes :dancer:

See ya! Keep up the good work! I love LibGDX <3

**Comment by badlogic** [comment]
Uhm, which listeners aren't interfaces?

**Comment by sephirot47** [comment]
ClickListener for example (I think...)

**Comment by Darkyenus** [comment]
Look at the implementation of ClickListener, it cannot possibly be an interface.

**Comment by antag99** [comment]
Well, there should be no reason for it being an interface. Anonymous inner classes works fine, right?

**Comment by sephirot47** [comment]
Ye, you are right, they work right, that's what I used. 
I guess it's what Darkyenus said, for some reason a ClickListener is forced to be a class. Thank you very much guys !!! <3
