### ISSUE TITLE
BaseTmxMapLoader loads TextureMapObjects incorrectly

### ISSUE THREAD

**Issue by Vichy97** [libgdx/libgdx#3290]
Hi I'm not sure what update it was in but I recently updated libgdx and noticed that my map objects were being loaded incorrectly.

 It used to load texture objects from tiled as RectangleMapObjects which was fine because i made a work around. Now it loads them as TextureMapObjects which is great!.... except it sets the texture incorrectly... I'm pretty sure this is a bug in the new update of Libgdx in the BaseTmxMapLoader class. 

PS: im not sure if this is the right place to post this but I just noticed it so I thought I would put this here. Feel free to move it if you need.

**Comment by MobiDevelop** [comment]
It has been like this for 6 months (see #2757).

You're going to have to elaborate on what "sets the texture incorrectly" means exactly. How is it incorrect?

**Comment by Vichy97** [comment]
Ok I double checked and the bug was added in update 1.5.4 and is in the method loadObject around line 200. It sets all of the textures the same for every object and they are never the right texture (it seems to choose the first texture in the tileset).

**Comment by Vichy97** [comment]
Oh and ive seen that issue also. I was happy when it loaded them as rectangle. TextureMapObjects would be better... if they worked :(

**Comment by MobiDevelop** [comment]
You are probably misusing it. The TextureMapObject uses TextureRegion. I am guessing you are then calling getTexture(), which gives you the entire backing texture.

**Comment by Vichy97** [comment]
No I am using getTextureRegion. It is just giving me the wrong thing and I'm pretty sure it is loading it incorrectly (my code worked before that update).

**Comment by MobiDevelop** [comment]
Show your code, everything looks correct in the implementation.

**Comment by Vichy97** [comment]
@Override
    public void renderObject(MapObject mapObject) {
        if(mapObject instanceof TextureMapObject) {
            vector2.set(((TextureMapObject) mapObject).getX(), ((TextureMapObject) mapObject).getY());
            getBatch().draw(((TextureMapObject) mapObject).getTextureRegion(), vector2.x, vector2.y);
        }
    }

This is in my custom TileMapRenderClass but even if i dont use my custom class and just say:
tilemapRender.render(); it renders all object layer incorrectly. I am using an AtlasTileMapLoader. maybe that implementation doesnt work with that?

**Comment by Vichy97** [comment]
I think the line element.getAttribute("gid")  needs to be changed to object.getProperties.get("gid", Integer.class) and use an int instead of a string. I had a nearly identical implementation before that update to load TextureMapObjects from a tiled map except for that string.

**Comment by MobiDevelop** [comment]
Please provide an [SSCCE](http://sscce.org) showing the issue, looking at the implementation, I don't see any problem with how they are loaded. The same region that backs the tile is used to create the object. If the tile works, the object should also work.

**Comment by Vichy97** [comment]
? I just showed you my code. Where else should I post it?

**Comment by MobiDevelop** [comment]
Create a complete sample showing the issue... Not two lines.l of code.

**Comment by Vichy97** [comment]
Ok just a minute. I am testing whether I can fix that method.

**Comment by Vichy97** [comment]
Alright now I'm not completely sure if it is the loader that is the issue. I will let you know what I come up with after I have done some more testing.

**Comment by nooone** [comment]
I've tried it myself with (`TmxMapLoader` though) and my texture regions are correct.

**Comment by Vichy97** [comment]
Ya I double checked and it is definitely a problem with update 1.5.4. I also tried it with TmxMapLoader and it is working. I think it may be loading the tilesets wrong in AtlasMapLoader, but I need to use the AtlasMapLoader. Anyone know what could be wrong?

**Comment by MobiDevelop** [comment]
The problem is you haven't provided the requested SSCCE.

**Comment by Vichy97** [comment]
Haha sorry guys. it was not an issue with my code or libgdx code it was an issue with the way i was packing the texture atlas. I still have no idea why it used to work though, but that doesnt matter anymore. I guess this issue can be deleted now, but im not sure how to do that.

**Comment by nooone** [comment]
I'm interested, how did you pack it to get this behaviour?

**Comment by Vichy97** [comment]
I packed the tilesets and didnt edit the tmx file.... I think... I packed it a long time ago but for some reason it had worked until that update (I just updated yesterday)

**Comment by MobiDevelop** [comment]
I actually have an idea of what probably went wrong here... It is probably related to #2843. It looks like that change might have had some unintended consequences when using multiple tilesets with AtlasTmxMapLoader.

**Comment by Vichy97** [comment]
Um ya your right. It is still messing up when I use more tilesets.

**Comment by Vichy97** [comment]
Can that commit be undone? It kinda messes up Atlas map loaders.

**Comment by MobiDevelop** [comment]
Please give the next nightly/snapshot a try and see if that fixes it. It is building now.

**Comment by Vichy97** [comment]
Yes! Thank you that works perfectly!
