### ISSUE TITLE
SplitPane splitter misbehave

### ISSUE THREAD

**Issue by lisandroCT** [libgdx/libgdx#3293]
If you have vertical SplitPane and then calls splitPane.setVertical(false); the splitter drawable is not updated appropriately.
![screenshot from 2015-07-20 18 30 56](https://cloud.githubusercontent.com/assets/6520671/8787954/7f42c4e2-2f0d-11e5-82af-2eeabb29fb39.png)

**Comment by MobiDevelop** [comment]
You will have to update the style after changing the orientation of the SplitPane. SplitPane doesn't retain a reference to the skin (if one was provided) nor would it know which style to choose if it did.
