### ISSUE TITLE
How can I get release build 1.6.4?

### ISSUE THREAD

**Issue by truonguit2010** [libgdx/libgdx#3295]
I don't use Gradle, I use Ant build, so I need jar packages like in http://libgdx.badlogicgames.com/nightlies/

But I cannot see 1.6.4 on http://libgdx.badlogicgames.com/releases/

How can I get 1.6.4 release.

Thanks,
TruongPS

**Comment by saltares** [comment]
This is an issue tracker, could you please use the [forums](http://www.badlogicgames.com/forum) instead?

**Comment by antag99** [comment]
I'd say it's a valid issue. There is no 1.6.4 version in the releases directory; no 1.6.3 or 1.6.2 either.

**Comment by moonwolf-github** [comment]
Maybe it's because of this? 
"Old-Style Builds

We strongly discourage using these old release builds, please use the Gradle based setup application instead."

**Comment by MobiDevelop** [comment]
I believe @badlogic intentionally stopped publishing the zip distribution for releases.

**Comment by Tom-Ski** [comment]
I'd rather step away from this dist format all together. (Note you can get all the artifacts from releases here: http://search.maven.org/#search|ga|1|g%3A%22com.badlogicgames.gdx%22 )

No real harm in keeping the zips though, @badlogic can decide its fate

**Comment by badlogic** [comment]
I want to get rid of the zip distribution. As @Tom-Ski pointed out, you can fetch the Jar files from Maven central.
