### ISSUE TITLE
Intersector.splitTriangle reports wrong sides when splitting

### ISSUE THREAD

**Issue by Darkyenus** [libgdx/libgdx#3299]
This bug has been found while creating #3296. When splitTriangle is given a triangle to split which needs to be split, it splits it correctly, but triangles which should be in the front are reported to be in the back and vice versa. This does not happen when the triangle is not split. Tested only with 2 vertices in the back and one in the front, I don't know if it works with reversed triangle.

![Image](https://i.imgur.com/USqrcuu.png)

This image shows what is being tested in #3296. The red triangle is first test - no splitting. Correctly reported as being in the back. Green triangle (with blue part) is the second test. It is apparent that there should be one triangle in the front and two in the back. All vertices are correct though.

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://notiqagency.com/jazz.php?e>

 

loogie@basicelementdesign.com
