### ISSUE TITLE
AudioDevice sampling rate

### ISSUE THREAD

**Issue by entangledloops** [libgdx/libgdx#3306]
The documentation for [AudioDevice](http://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/audio/AudioDevice.html) says the device is 44.1khz (as does the source!), but a call to [newAudioDevice](http://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/Audio.html#newAudioDevice-int-boolean-) allows the user to specify the sampling rate.

Should an implementation of the AudioDevice use a sampling rate provided by the user or ignore and default to 44.1khz? (I would hope you you will allow configuration, as I'm at least one person writing an application that requires the use of audio in different sampling rates.)

Also, I can see that at least the Android implementation does take the specified sampling rate into account when initializing a new AudioTrack, but I think the docs should reflect this if it holds over all platforms.

**Comment by MobiDevelop** [comment]
The Android and LWJGL backends (the only two which currently support AudioDevice) both honor the provided samplingRate. The javadoc on AudioDevice should be updated.
