### ISSUE TITLE
Request: LerpAngle on MathUtils.

### ISSUE THREAD

**Issue by Gtoknu** [libgdx/libgdx#3307]
I would write a PR for this, since I found myself needing it more than once this week, but can't guarantee the solution I found to the problem is performant enough.

For more info, [this](http://docs.unity3d.com/ScriptReference/Mathf.LerpAngle.html) is what I'm requesting.

And [this](http://stackoverflow.com/a/14498790/1091440) is the best way that I found to do it . Anyone know a better way of doing it?

**Comment by xoppa** [comment]
Looks useful, would you mind to send a PR for it?

**Comment by GreenLightning** [comment]
Make sure to handle degrees and radians!
