### ISSUE TITLE
GL_SCISSOR_TEST doesn't work in iOS.

### ISSUE THREAD

**Issue by voidstarfire** [libgdx/libgdx#3311]
Created default app using LibGDX version 1.6.0
Compiled with RoboVM 1.5

    @Override
	public void render ()
    {
		Gdx.gl.glClearColor(1, 0, 0, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        
		batch.begin();
        Gdx.gl20.glEnable(GL20.GL_SCISSOR_TEST);
		batch.draw(img, 0, 0);
        Gdx.gl20.glDisable(GL20.GL_SCISSOR_TEST);
		batch.end();
	}

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by voidstarfire** [comment]
I performed a search with no result. This is a valid issue.

**Comment by Tom-Ski** [comment]
Please read the link, that isn't a self contained test, and 'doesn't work' is not a helpful description of an issue.

**Comment by xoppa** [comment]
This is not an issue with libgdx, this is an issue with your code. The code you provided clearly shows that you haven't verified that this is a libgdx issue. Try the forum or IRC first. Please don't use the issue tracker for personal support requests.

**Comment by voidstarfire** [comment]
I compiled with default app and only added those lines.

**Comment by FyiurAmron** [comment]
@voidstarfire could you please make a github repo with a minimal self-contained test case? If this is indeed a bug, I'd be glad to know of it, yet I don't have any Mac at hand ATM to verify.

**Comment by voidstarfire** [comment]
I found the solution for iOS devices.

    batch.begin() 

causes glScissor to be reset on iOS devices to 0,0,0,0.

Calling 

    Gdx.gl.glScissor(0,0, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());

at the start of the render loop seems to fix this, only needed for iOS devices.

The only thing I added to a default LibGDX 1.6.4 project with RoboVM 1.5 was: 

    @Override
    public void render ()
    {
        Gdx.gl.glClearColor(1, 0, 0, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

        batch.begin();
        Gdx.gl20.glEnable(GL20.GL_SCISSOR_TEST);
        batch.draw(img, 0, 0);
        Gdx.gl20.glDisable(GL20.GL_SCISSOR_TEST);
        batch.end();
    }

**Comment by voidstarfire** [comment]
Self contained test case:
https://github.com/voidstarfire/GL-Scissor-Example

**Comment by xoppa** [comment]
Ah, so the issue you were reporting is that if you enable scissors but *don't define* the scissor box, that the scissor box is *undefined*. Please be aware that there is no way we could get that from your issue description of 14 words, nor from the limited code you included (which just enables scissors and then disables it again, without ever using it).

**Comment by FyiurAmron** [comment]
Yup. It's just as xoppa pointed out - since OpenGL is a state machine, you generally shoudn't assume anything about any particular state until you set it yourself - same goes with scissoring. IMO you should provide e.g. `Gdx.gl.glScissor(0,0, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());` (or any other initial scissor values) on *every* platform before even using the scissor test. The fact it did work on platforms other than iOS means you got lucky; still, relying on UB is hardly a good thing.

**Comment by voidstarfire** [comment]
Ah yes sorry about the breif intro I was incrediblly intoxicated at the time. At least people who come across this bug or not will find a solution :-)
