### ISSUE TITLE
Json Serialization of an instance's fields that are initialized during declartion returns {}

### ISSUE THREAD

**Issue by Xtrinity** [libgdx/libgdx#3315]
I'm playing with Json and the example shown in the documentation works perfectly. [http://hastebin.com/elocacukul.avrasm]

However, if I do not use the setters to set the values first, the method toJson(); will return empty [http://hastebin.com/azovayihem.avrasm]. I'm not sure if this is a feature or bug. I suppose something like this could be considered extraneous as one wouldn't usually need to save the default initialized value. However, if say one were to allow a serialized JSON Setting Class to be exchanged over the net and one then changed the previous version's default values, some of the old settings might still be retained. Perhaps I should be implementing serialVersionUID but I would think the problem in that scenario would still persist.

Someone on IRC mentioned that I might be doing it wrong. If so, I would suggest that the documentation be more clear on the requirements of the Json.Serializable.

I've also tried some reflecting to see if I could find the names of the fields that are initialized during declaration. I've tried the code below with success.

for (Field f: settingTest.getClass().getFields()) {
      try {
        System.out.println(f.getGenericType() + " " + f.getName() + " = " + f.get(settingTest));
      } catch (IllegalAccessException e) {
        e.printStackTrace();
      }
}

Edit: Some further testing shows that JSON will output the correct JSON if the class being parsed is a class within the class calling the toJson(); method. If you are trying to parse a top-level class it will output {}. So, [http://hastebin.com/akuxukeqaq.avrasm] will work.

**Comment by MobiDevelop** [comment]
You should call `json.setUsePrototypes(false);` if you also want default values to be serialized.

**Comment by Xtrinity** [comment]
Thanks, it works now :)
