### ISSUE TITLE
Json nested Array/Maps deserialization

### ISSUE THREAD

**Issue by obigu** [libgdx/libgdx#3327]
I've observed an inconsistent behaviour while trying to deserialize nested Arrays/Maps.

I've attached 3 test cases.

1. **NestedArrayDeserialization**: Deserializes an ```ObjectMap<String, Array<CutomObject>>```
http://pastebin.com/kqSSqeHN

2. **NestedArrayListDeserialization**: Deserializes an ```ObjectMap<String, ArrayList<CutomObject>>```
http://pastebin.com/xPsDsXWL

3. **DoubleNestedArrayDeserialization**: Deserializes an ```ObjectMap<String, ObjectMap<String, ArrayList<CutomObject>>>```
http://pastebin.com/1rcd5bzC

Test 1 runs OK. Test 2 and 3 fail with different errors.

As a reference I've found a similar post where this could not be answered because of lack of information (sample cases): http://badlogicgames.com/forum/viewtopic.php?f=11&t=11016.

It may be that current libGDX Json implementation doesn't support the possibility to inform about the types of the "values" of a Map but it's currently not clear in the documentation how nested Maps and Arrays  should be deserialized.

In GSON for example it's possible to provide a type token in the following manner and the library  takes care of the rest: http://stackoverflow.com/questions/14358350/google-gson-nested-hashmaps-deserialization.

**Comment by NathanSweet** [comment]
The `Json` class doesn't support the GSON `TypeToken` trick, but does allow for simple "element" types to be specified.

Test 2, use:
`json.fromJson(ObjectMap.class, ArrayList.class, jsonString);`

Test 3, use:
`json.fromJson(ObjectMap.class, ObjectMap.class, jsonString);`

JSON isn't a great object serialization format, I suggest Kryo for more complex object graphs.
