### ISSUE TITLE
libGDX Truck Factor

### ISSUE THREAD

**Issue by gavelino** [libgdx/libgdx#3330]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **libGDX** and obtained a value of **2**.

The developers responsible for this TF are:

Mario Zechner (badlogic) - author of 52% of the files
Xoppa - author of 32% of the files

To validate our results, we would like to ask **libGDX** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **libGDX**?

(b) Do you agree that **libGDX** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **libGDX** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by badlogic** [comment]
I commented on your study a while ago, see

https://www.reddit.com/r/programming/comments/3czygt/what_is_the_truckfactor_of_popular_github/ct0kw03

And

https://www.reddit.com/r/programming/comments/3czygt/what_is_the_truckfactor_of_popular_github/ct0lpv5

That should answer your questions. In short: i think your study is flawed,
not only in our case but in case of of other projects you investigated, for
the reasons outlined in the comments above.

This is an issue tracker, not a place for general discussion. Please
contact us via email at contact@badlogicgames.com.
