### ISSUE TITLE
setUniformMatrix3fv exception

### ISSUE THREAD

**Issue by GiltanasDoto** [libgdx/libgdx#3331]
Hi, guys!
Recently i've tried to implement batching using setUniformMatrix3fv and FloatBuffer created as:
```
ByteBuffer tmfb = ByteBuffer.allocate(16*24*SIZEOF_FLOAT);
            tmfb.order(ByteOrder.nativeOrder());
            transportMatrixFloatBuffer[i] = tmfb.asFloatBuffer();
```
Where SIZEOF_FLOAT = 4.
So each FloatBuffer contains 24 matrices of 16 floats (4*4).
But when i tried to call setUniformMatrix3fv,with count=24 and transpose=false i've got next exception:
```
A/libc﹕ Fatal signal 11 (SIGSEGV) at 0x00000010 (code=1), thread 22773 (Thread-16940)
```
on GLES20.glUniformMatrix4fv call.
What should i do? Thanks in advance.

**Comment by xoppa** [comment]
Please read https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md (as you were presented when opening this issue) and try again.
