### ISSUE TITLE
Text paste issue in TextField with max length set

### ISSUE THREAD

**Issue by kotcrab** [libgdx/libgdx#3337]
There is issue when pasting text in TextField that has maximum length set. [SSCCE](https://gist.github.com/kotcrab/682a4ba43b0b89a52cec)

1. Select all text in TextField.
2. Try to paste something in field, all text will disappear even if pasted content length is shorter than field max length. 

Expected behavior is that old text will be replaced by pasted text.

**Comment by saltares** [comment]
Thanks for reporting.
