### ISSUE TITLE
Textfield: X, C, V inserted during Cut, Copy and Paste

### ISSUE THREAD

**Issue by GreenLightning** [libgdx/libgdx#3340]
When I use one of the copy and paste actions on a text field, it inserts the corresponding shortcut key as well. For example if I press Command + V (I'm on a Mac, see below) it pastes my clipboard content and then inserts a 'v' behind the pasted content. Similarly, a 'c' is inserted after copying some text and an 'x' is inserted after cutting.

To reproduce the issue you can use the UITest (one of the LibGDX tests / examples), which showcases a text field among other controls.

I tested this on OS X Yosemite, Java 8, using the latest source code.

If you can test this on your system, please leave a comment with your system specification and what behavior you experienced.

**Comment by saltares** [comment]
I might be doing something wrong but I cannot reproduce this issue on Windows 8 with the latest master from Libgdx.

Sanity check, are you sure you're not leaving the `V` key pressed after you release `Ctrl`? It shouldn't trigger the repeat key but still.

**Comment by GreenLightning** [comment]
Yeah, I am absolutely sure. It works like this: press command, press v, clipboard content and v appear immediately, release v, release command.

**Comment by MobiDevelop** [comment]
I can reproduce on OS X Yosemite.

**Comment by GreenLightning** [comment]
I think it might be OS X specific, but that is only speculation. Would be nice if someone could try and reproduce it on OS X.

On the other hand, I figured that the copy and paste actions are handled in the keyDown method of TextFieldClickListener and the text insertion is handled in keyTyped. However, nothing in keyTyped cancels the insertion if command / control is pressed.

@saltares: Could you add the following line as the first line to the keyTyped method in TextFieldClickListener and see what it prints?

    System.out.printf("typed '%c'%n", character);

For me it prints:

    typed '' // command pressed
    typed 'v' // v pressed

**Comment by MobiDevelop** [comment]
Also, for me, pasting seems to stop working correctly after the first paste. Afterwards, it takes several tries and very quick timing on the Command and V pressed to get it to work (they have to have been pressed nearly at the same time).

**Comment by GreenLightning** [comment]
Adding the following line to keyTyped fixes it for me, however pasting works fine for me, if you ignore the inserted characters.

    Stage stage = getStage();
    if (stage == null || stage.getKeyboardFocus() != TextField.this) return false;

    if (UIUtils.isMac && Gdx.input.isKeyPressed(Keys.SYM)) return true; // This line is new...

    if ((character == TAB || character == ENTER_ANDROID) && focusTraversal) {
        next(UIUtils.shift());
    }

Should I create a PR or does anyone have a different solution?

**Comment by MobiDevelop** [comment]
I added `if (UIUtils.ctrl()) return false;` on my end and it works, not sure if it affects things on the other platforms.

**Comment by GreenLightning** [comment]
If you check for `isMac` explicitly it won't affect other platforms. The condition that I've posted is just the part of the `UIUtils.ctrl()` method that handles OS X.

**Comment by MobiDevelop** [comment]
Yeah, but I guess I have to wonder... under what conditions would you actually want to append text while Ctrol (or Command) is pressed?

**Comment by GreenLightning** [comment]
This does only happen if you use the lwjgl test starter. It works fine on mac using the jglfw test starter...

**Comment by Arcnor** [comment]
I've also found this issue on OSX Yosemite. It also happens with <kbd>Cmd</kbd>+<kbd>A</kbd> to select everything (so it selects everything, then it types an `A`, so you get a field with only an `A` on it).

Also, and maybe related to what @MobiDevelop comments about it not working properly after a while, sometimes just pressing <kbd>A</kbd> clears the whole textfield and adds an `A` there, without me pressing <kbd>Cmd</kbd>
