### ISSUE TITLE
Wiki GitHub link

### ISSUE THREAD

**Issue by JahrudZ** [libgdx/libgdx#3342]
I don't think the "clone on desktop" link for the wiki is working...

**Comment by MobiDevelop** [comment]
That's a GitHub thing, we have no control over it.

**Comment by Githomie** [comment]
Any update on this? I was really hoping to be able to grab it for offline reference!

But it keeps timing out...

**Comment by badlogic** [comment]
This is not under our control, GitHub doesn't allow it for whatever reason.

**Comment by Githomie** [comment]
Wow, thanks for the fast reply! Is there some other location I can download it from?

If I have to, I can manually save the pages and generate an ePub or something, but would really prefer not to since that takes a fair amount of time.

**Comment by badlogic** [comment]
I'm afraid there's not.

**Comment by Githomie** [comment]
I'll go do what I said then. Are you interested in hosting a copy when I'm done archiving it?

**Comment by badlogic** [comment]
Given that the wiki changes a lot, hosting a copy would likely result in
additional update/maintenance burden. TL;DR: thanks, but we won't host it
atm.

**Comment by Githomie** [comment]
No worries, and I appreciate the fast replies to my inquiries! Thanks!
