### ISSUE TITLE
2d particle editor is broken on OSX 10.10.4 with java 1.8.0_40-b27

### ISSUE THREAD

**Issue by AgrarPirat** [libgdx/libgdx#3346]
Hello libgdx team,

The 2d particle editor is broken on OSX 10.10.4 with java 1.8.0_40-b27. Only a blank, unresponsive window shows up, with the cursor changed to the colorful rotating ball.
It might be related to this issue: https://github.com/libgdx/libgdx/issues/3008
A simple workaround is to use it on Windows, where it's still working well.

**Comment by GreenLightning** [comment]
Can not reproduce on OS X 10.10.4 using JDK 8 Update 45. Could you try updating your Java version?

**Comment by AgrarPirat** [comment]
Same behavior after updating java to the most recent version (1.8.0_51)

**Comment by GreenLightning** [comment]
What version of the particle editor are you running?

**Comment by AgrarPirat** [comment]
The most recent version I've tried was the nightly from August 11th 2015. I still have an older version laying around from June 19th 2015, which is also broken.

**Comment by AgrarPirat** [comment]
The particle editor was working well a few months ago. Last time I wanted to edit some particles, was around June 19th, where the previously working build was broken all out of a sudden. Since then I've not been able to get the particle editor working again. The fact that it broke all out of a sudden leads me to the conclusion that the issue is related to my development system...

**Comment by badlogic** [comment]
Can't reproduce on El Capitan with 1.8.0_51. It's weird because nobody touched the editor either. Will re-open if you got more info
