### ISSUE TITLE
Very bad frametimes

### ISSUE THREAD

**Issue by Teiby1** [libgdx/libgdx#3348]
I have found out that any game that was made in libgdx has some "Micro stuttering".
So I have made a simple game to measure the time between frames and it has a lot of lag spikes.
I have tested it on Android (Nexus 7) and Windows with activated vsync (so each frame should be at exact 16.67ms but it's often 30ms or 5ms).

The game and the function that calculates the frametime can be found here:
https://github.com/Teiby1/frametimetest/blob/master/core/src/de/teiby/frametimetest/FrametimeTest.java
It sums up all frametimes in a second that are not exact 16.67ms. On Android I get about 30ms-100ms and on Windows 1ms-10ms (fullscreen) and 10ms-50ms (windowed).
On both devices 60 FPS but it's not really smooth.

Use WASD or touch/mouse to move the square (but doesn't really affect the frametime).

Also here a logcat output when a frame took more or less than 4ms:
https://github.com/Teiby1/frametimetest/blob/master/android_measure.txt

You should run this testgame on a device that has a 60Hz monitor.

**Comment by xoppa** [comment]
So the issue you are reporting is that your frame time calculation doesn't consistently result in exactly 0.0166666? That's not an issue with libgdx, that's an issue with your expectations.

**Comment by Teiby1** [comment]
The calculation shows only the real facts. A frame should be rendered with a constant timestep but that's not the case.

**Comment by xoppa** [comment]
No, it shouldn't. Please use the forum or irc if you need help understanding that. Will close this, this is not the place for these kind of personal support requests.

**Comment by Teiby1** [comment]
24 FPS fraction or why can't you see it?

**Comment by gj12** [comment]
I suggest, that you read some articles about game/render loops etc.:
eg. http://obviam.net/index.php/the-android-game-loop/
You can find example code for libgdx on github and the forum
