### ISSUE TITLE
TilemapPacker doesnt work for some tilesets

### ISSUE THREAD

**Issue by Vichy97** [libgdx/libgdx#3349]
TilemapPacker always crashes when you try to pack a tileset that is made from a collections of images instead of one tileset image. It crashes at line 274. Normally I would use a single tileset image but it annoying when you have lots of odd shaped tiles and even when you do it still doesn't work. (wrong tiles are rendered most of the time)

**Comment by MobiDevelop** [comment]
Don't use the TiledMapPacker for "Collection of images" tilesets, it wasnt designed to work with them. Just use TexturePacker and add an atlas property to your tmx.
