### ISSUE TITLE
XmlReader.java gets stuck in infinite loop on nVidia Android hardware due to ART optimizations

### ISSUE THREAD

**Issue by Unsanctioned** [libgdx/libgdx#3351]
The tight loops inside XmlReader.java end up being optimized by the ART on nVidia hardware - Shield TV and possibly others - such that changes to the loop variables are lost.

The problem occurs with the variables _upper and _lower in the while(true) loops at lines 130 and 152.

A workaround is to access those variables at the bottom of the loop in a debug log message between lines 141-142 and between 163-164.

**Comment by MobiDevelop** [comment]
Sounds to me like an issue which should be reported to the Android team.

**Comment by Unsanctioned** [comment]
I would agree, except for a couple of pieces of information:

1) In the dozen devices I've tested, this only seems to affect the nVidia Shield TV - which suggests it's an issue for nVidia to fix rather than Android.

2) nVidia's response is: "(The software team) believe it's a valid optimization that ART is doing much like a C compiler would do in the same instance."

That doesn't leave much option for having it fixed outside of libgdx. For my own needs, I'll likely be hacking a local version of XmlParser.java that works around the issue.

**Comment by xoppa** [comment]
Can you include a link to the nvidia (and android?) response? Afaik the XmlReader class is generated by Ragel, so it is probably not a good idea to modify that class directly. Otherwise, I guess a simple solution would be to use `while (_upper >= _lower)`

**Comment by Unsanctioned** [comment]
The response was in an email thread with their developer support team. The response was:

"I did ask some of the SW people about that and they believe it's a valid optimization that ART is doing much like a C compiler would do in the same instance. They suggest you explicitly use the variables which it sounds like you are doing as the WAR."

**Comment by davebaol** [comment]
I'd close this issue for the reasons below:
* It's clearly a device-specific issue
* that device is not so common
* you could ask the ragel team to generate more usual code (like the one suggested by @xoppa ) [here](http://code.openhub.net/file?fid=mA4YnADt_Y0YdyAvzlzaRKkcRHk&cid=ZZ3NBAdF2vc&s=&fp=549446&projSelected=true#L296), [here](http://code.openhub.net/file?fid=mA4YnADt_Y0YdyAvzlzaRKkcRHk&cid=ZZ3NBAdF2vc&s=&fp=549446&projSelected=true#L349) and [here](http://code.openhub.net/file?fid=mA4YnADt_Y0YdyAvzlzaRKkcRHk&cid=ZZ3NBAdF2vc&s=&fp=549446&projSelected=true#L372). If they release a new version we will use it for sure.

**Comment by xoppa** [comment]
I don't agree that an optimization which clearly alters the functionality is valid (at least not if you cant disable it somehow). But I guess there isn't much we can do about that. Going to close this for above reasons. Please send a [pull request](https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md#pull-requests) when this is fixed in ragel.

**Comment by Unsanctioned** [comment]
I very much agree that the optimization itself is incorrect. As much as anything, I wanted an issue listed here in case others run into it and go looking for solutions. My workaround ended up being replacing XmlParser.java with a locally-modified version, and inserting that into a local replacement for TmxMapLoader.
