### ISSUE TITLE
Improve behavior of Array#removeRange

### ISSUE THREAD

**Issue by antag99** [libgdx/libgdx#3355]
Array and friends use an inclusive range for the `removeRange` methods. I want to remove the first `n` elements of an array; what I currently have to do is this:
```java
if (n > 0)
    array.removeRange(0, n - 1);
```
If it weren't from the `n > 0` check, I would get an `IndexOutOfBoundsException` saying `start can't be > end` for the case where `n` is `0`. This seems quite problematic API-wise.

I think it's better to have `end` exclusive, but that requires a nasty breaking change. An idea is to make `removeRange` do nothing for the case where `start > end`. The intention of this ticket is to remove the need of an if check on the caller side if feasible.

**Comment by MobiDevelop** [comment]
It is a programming error if your range ends at a lower index than your start, that should throw an exception. It should not be ignored.

I'm struggling to see why having the if condition in your code is a bad thing. Sometimes you have to write code.

**Comment by antag99** [comment]
> I'm struggling to see why having the if condition in your code is a bad thing. Sometimes you have to write code.

I think it's somewhat of a flaw in the API - it's impossible to specify an empty range. Using half-open ranges is way better, but changing the `removeRange` methods in that way is not too great. It's possible to introduce new methods and remove the old ones, though.

> It is a programming error if your range ends at a lower index than your start, that should throw an exception. It should not be ignored.

It could be a good idea to permit specifying empty ranges, however it's kind of a off-by-one hell.

**Comment by MobiDevelop** [comment]
The javadoc indicates it is inclusive.

Not sure why removing an empty range is desired. Simply don't call removeRange if the range would be empty.

**Comment by antag99** [comment]
I don't think the documentation is wrong. I think the definition of `removeRange` is wrong.

Ranges in Java are almost always half-open, and this is a good convention. I don't understand why the `removeRange` methods initially were implemented the way they are, as they require silly if checks and `-1` expressions. An example is removing `n` elements at offset `off`; you'll have to write this:

```java
if (n > off)
    array.removeRange(off, off + n - 1);
```

If the `removeRange` method would accept empty ranges this would be:
```java
array.removeRange(off, off + n - 1);
```

And if it used half-open ranges:
```java
array.removeRange(off, off + n);
```

It *works* as it currently is, but it's not great.

**Comment by MobiDevelop** [comment]
As you said, it can't be changed without considerable breakage. Ignoring the exception is not a solution so unless @NathanSweet, @badlogic, or @xoppa agreed to the breakage, I am inclined to close closed this.

**Comment by xoppa** [comment]
I don't see why having a well defined and implemented method is "quite problematic API-wise". Agreed, it is not consistent with `ArrayList`, but as you correctly point out, you can adjust for that by simply substracting `1` from the second argument.

If you look closely at the [javadocs of `ArrayList#removeRange`](http://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html#removeRange(int,%20int)), then you'll notice that it is (documented) inconsistent with itself: the second argument is excluse, *unless* it is the same as the first argument, in which case it is inclusive... So the behavior of `ArrayList#removeRange(s, s + n)` equals with the behavior of `ArrayList#removeRange(s, s + n + 1)`, but only when `n = 0`. Too me that sounds much more like a "quite problematic API-wise".

Please note that an "empty range" is an, well, empty range. So it wouldn't remove anything. For both `Array` and `ArrayList` that would mean that the second argument is less than the first argument. And both classes are consistent in not accepting such range. So, I don't think that's a valid argument.

**Comment by xoppa** [comment]
Nvm, I should read before I write things.

**Comment by xoppa** [comment]
Going to close this. Unfortunately in some cases a fix breaking the api is more problematic than the problem it fixes.
