### ISSUE TITLE
TextField Alignment

### ISSUE THREAD

**Issue by darkfrog26** [libgdx/libgdx#3357]
It would seem there is no current way to set the text within a text field to be right-aligned. I've attempted `setAlignment` but it aligns the component, not the text.

**Comment by xoppa** [comment]
Please include the [sscce](http://sscce.org/) required to reproduce (and fix) the issue you're reporting. https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by darkfrog26** [comment]
```java
TextField field = new TextField(text, skin);
field.setAlignment(Align.bottomRight);
```
Does not align to the right. Even looking at the source code for this it's simply something not implemented. I'm not sure how else to show you that you don't have a feature.

**Comment by xoppa** [comment]
What do you mean by "Even looking at the source code for this it's simply something not implemented"? Which specific code (link to the line) are you referring to? Please include all information that might help to fix the issue you're reporting. Would it perhaps be possible for you to send a PR instead?

**Comment by darkfrog26** [comment]
Oops...I was looking at the wrong code. Using `Align.bottomRight` does not work because it explicitly looks for `Align.right`. I would argue that this is a bug, but at least I know how to fix my problem now.
