### ISSUE TITLE
mipmap downscaling needs to do alpha weighting

### ISSUE THREAD

**Issue by makoConstruct** [libgdx/libgdx#3358]
Here is what happens when you render a downscaled texture of a black antialiased circle against a black background in libgdx

![screenshot](http://i.imgur.com/btFCScA.png)

The color of the pixels around the edges of the image(fully transparent white) are being mixed with the not-entirely transparent pixels(black) on the alias of the circle. This can be avoided by using a blending function that weights the colors of transparent pixels by their alpha (so pixels you fully can't see wont interfere with your render)

Wolfire discuss it here blog.wolfire.com/2009/01/scaling-images-with-alpha/

There are other workarounds, but that seems like the most reasonable default behavior.

btw, here's precicely how I'm loading the image:
```scala
def scalableTexture(fileName:String) = {
	val ret = new Texture(new FileHandle(fileName), true) //mipmapping on
	ret.setFilter(Texture.TextureFilter.MipMapLinearLinear, Texture.TextureFilter.MipMapLinearLinear)
	ret
}
```

**Comment by xoppa** [comment]
Thanks for your contribution! If you think that there's an issue with the way your GPU samples texture or generates mipmaps then please report an issue with your GPU manufacturer. If you think that there's an issue with the OpenGL ES specification then please report an issue with the Khronos group. Either way, this is not an issue of libgdx.
