### ISSUE TITLE
v1.6.4: Gdx.input.isKeyPressed() for Keys.ALT_LEFT and Keys.ALT_RIGHT always true

### ISSUE THREAD

**Issue by adam-law** [libgdx/libgdx#3362]
It is as the title states, doing this check always returns true, even when another key is pressed. I don't know which version it crept in, because it was working properly before.

**Comment by davebaol** [comment]
SSCCE please

**Comment by nooone** [comment]
I tried it with 1.6.4 on windows with both `isKeyJustPressed` and `isKeyPressed` and both return true only when the key is really pressed.

**Comment by adam-law** [comment]
sorry for not seeing this right away. I'll have to check again. I may have been mistaken about what version I'm using. I forgot I set it up on Gradle to use the latest snapshot, which is at 1.6.6 as of this writing.

**Comment by adam-law** [comment]
It maybe an issue with the (Razr) keyboards we're using, along with some other environmental issues that's making the report for ALT erratic.

Thanks for looking in on this.

**Comment by adam-law** [comment]
Sorry to reopen this, I think I found out what the issue was. My dev environment is in Windows 7 64-bit, so I use Alt+Tab to switch between windows. When I return to running application, the check for ALT, will then always be true.

**Comment by nooone** [comment]
I've got Windows 7 64bit as well and tried this. Cannot confirm.

**Comment by adam-law** [comment]
ah. I see. I apologize, it was a long day when I reopened this. After seeing your comment, I looked into it some more and found that the issue is caused by a backend I'm using. I'll take it up with the authors there. Closing this one again.
