### ISSUE TITLE
Apostrophes in project name are not escaped in build.gradle

### ISSUE THREAD

**Issue by scaryuncledevin** [libgdx/libgdx#3370]
When creating a new project and putting an apostrophe in the name, the project build.gradle is not escaped causing a gradle build error at appName, such as

    appName = 'Devin's App'

Which should be escaped to

    appName = 'Devin\'s App'

**Comment by jonbonazza** [comment]
I actually suggest changing the ' to " in this case. For example:
```groovy
appName = "Devin's App"
```

This way you don't need to worry about escaping at all.

**Comment by Darkyenus** [comment]
Unless I am missing something, then you have to escape the ". Although it is very unlikely that somebody would use that to name their project.

**Comment by scaryuncledevin** [comment]
It's not likely but I would still say it's possible. Either way, whichever character is used to enclose the appName will need to be escaped within the name itself.

**Comment by jonbonazza** [comment]
Ah that's true. I hadn't considered that... You are right. While very unlikely, it's not an impossibility.
