### ISSUE TITLE
TextTooltip size calculation is wrong

### ISSUE THREAD

**Issue by Arcnor** [libgdx/libgdx#3374]
There is an issue with the calculation of `TextTooltip` size, although I'm not 100% sure of what it is.
* In the best case, calculation works, and you get a nice tooltip.
* In the worst case, you end up with a label that never finishes getting a correct size, and its text constantly shrinks and grows forever

I'm not sure of what the problem might be, although it might have to do with the width size calculation not taking into account pads for the label size?

**Comment by Arcnor** [comment]
![adventure_composer](https://cloud.githubusercontent.com/assets/28616/9465663/d4a89a76-4b71-11e5-9f50-579d9503819e.png) Example of "not-so-great case"

**Comment by Arcnor** [comment]
![libgdx cursor](https://cloud.githubusercontent.com/assets/28616/9465758/a61fa810-4b72-11e5-840e-7a02de13ad2e.gif) Example of worst case in slow motion so it can be appreciated

**Comment by bladecoder** [comment]
More info...

This happens when the label style has the background property set:

	com.badlogic.gdx.scenes.scene2d.ui.TextTooltip$TextTooltipStyle: {
		default: {label: { font: default-font, fontColor: text-dark, background: message}, background: message}
	},

Deleting the background works well:

	com.badlogic.gdx.scenes.scene2d.ui.TextTooltip$TextTooltipStyle: {
		default: {label: { font: default-font, fontColor: text-dark}, background: message}
	},

**Comment by NathanSweet** [comment]
Can you post an SSCE?

**Comment by TaiVuong** [comment]
I fix this issue by add this function 
```java
public void setText(CharSequence full_tooltip) {
    label.setText(full_tooltip);
    label.validate();
    container.width(new Value() {
	public float get (Actor context) {
		return Math.min(TooltipManager.maxWidth, label.getGlyphLayout().width);
	}
    });

    getContainer().pack();
}
```

**Comment by NathanSweet** [comment]
Since I don't have a way of seeing what the problem is, I hesitate to copy/paste a "fix".

**Comment by TaiVuong** [comment]
perhaps I had misunderstood the issue.
that "fix" use when I modify text of the tooltip.

**Comment by TaiVuong** [comment]
I just remembered why do so.
Tooltip's background'll dont resize if label.setWrap(true);

**Comment by NathanSweet** [comment]
The style now controls the wrap width so `pack` works.
