### ISSUE TITLE
[Improvement] Allow to cache BoundingBox in Model, ModelInstance and Node

### ISSUE THREAD

**Issue by realitix** [libgdx/libgdx#3375]
I think adding cached boundingbox to Model, ModelInstance and Node would be great for performance improvement.
The cached boundingBox would be computed only on access [getBoundingBox] (so if no access, no compute). And updated if mesh is updated or if modelinstance is moved.
It would increase performance for frustum culling or others.

What is your opinion about it ?

**Comment by xoppa** [comment]
I don't think that would be a good idea. If users need to cache such information then they can extend ModelInstance and add it (e.g. see my blog on how to do that). Using the `calculateBoundingBox` method is the most naive method and most typical use-cases don't need to use that method (btw, moving a ModelInstance does not change its bounding box).

**Comment by realitix** [comment]
OK
