### ISSUE TITLE
uiskin in json format is wrong and should be in double qoutes

### ISSUE THREAD

**Issue by Wisienkas** [libgdx/libgdx#3377]

**Comment by MobiDevelop** [comment]
The libgdx json reader supports an unquoted "minimal" format. While it is not true json, it is valid for its intended use.

**Comment by Wisienkas** [comment]
But it doesn't support qouted. Would just prefer to apply schema etc. for it which would be beneficial in many purposes

**Comment by MobiDevelop** [comment]
It does support quoted values as well.

**Comment by Wisienkas** [comment]
Try pass the following into a skin then:

```Java
"com.badlogic.gdx.scenes.scene2d.ui.TextButton$TextButtonStyle": {
    "default": {
      "down": "default-round-down",
      "up": "default-round",
      "font": "default-font"
    }
  }
```

**Comment by MobiDevelop** [comment]
I added that to uiskin.json and it works correctly.

**Comment by xoppa** [comment]
Please read https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md (which you were presented with when you opened this issue). If you need help, then use the forum or IRC instead.
