### ISSUE TITLE
Headless Backend doesn't properly Mock up all of the backend pieces

### ISSUE THREAD

**Issue by TheAks999** [libgdx/libgdx#3383]
When you create a new headless application there are some crucial components that are missed in initialization that are needed for using part of the backend.

So far I have found that it missed Gdx.gl and Gdx.gl20 and you cannot create a new texture without these. Also there are a lot of little things inside of that area that need more than just mock(GL20.class)

like compiling shaders:
com.badlogic.gdx.graphics.g2d.SpriteBatch.createDefaultShader(SpriteBatch.java:157)

This is for libgdx version 1.6.5, however the appropriate code doesn't look like it is available for more recent versions.

**Comment by nooone** [comment]
Why are you using headless if you want to use textures and shaders?

**Comment by TheAks999** [comment]
I'm unit testing. I don't want to have to do a significant backflip to get
something to work when the backend really should be handling this.

new Texture('file.png'); should generally work if you have a
HeadlessApplication set up. It works on all other backends (as far as I can
tell).

On Sat, Aug 29, 2015 at 3:24 PM, Daniel Holderbaum <notifications@github.com
> wrote:

> Why are you using headless if you want to use textures and shaders?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/libgdx/libgdx/issues/3383#issuecomment-136044545>.
>



-- 
Alex Shepard
~Shep~

**Comment by xoppa** [comment]
Don't use headless if you don't want it to be headless. This is an issue tracker. Please use the forum or irc if you need help. https://github.com/libgdx/libgdx/wiki/Getting-Help
