### ISSUE TITLE
Loss of controller input when changing displayMode

### ISSUE THREAD

**Issue by clubmine** [libgdx/libgdx#3384]
When the displaymode is changed from fullscreen to windowed or vice versa, the controller loses input and reports the last values before the displaymode change. This issue has been posted before and was reportedly fixed but the current version seems to still have this problem. I am running Windows 10 and have tested a Xbox One controller as well as a Xbox 360 USB Controller.

**Comment by badlogic** [comment]
Will hopefully be fixed when the LWJGL 3 backend is done.

**Comment by badlogic** [comment]
This has been fixed in the new LWJGL 3 backend.
