### ISSUE TITLE
gdx Json format

### ISSUE THREAD

**Issue by JFixby** [libgdx/libgdx#3385]
Hi,

I'm not sure if it is a bug or it was done intentionally, but looks like GDX-produced Json is not compatible with the Json.org format standard.

At least it is what the validator https://jsonformatter.curiousconcept.com/ says:
"Strings should be wrapped in double quotes."

Cheers.

**Comment by nooone** [comment]
What happens if you set the `OutputFormat` to `Json`?

**Comment by JFixby** [comment]
Then it is perfectly fine.
