### ISSUE TITLE
Fatal error when exiting LibGDX game after graphic driver update

### ISSUE THREAD

**Issue by PojahnM** [libgdx/libgdx#3387]
I installed new drivers for my AMD Radeon HD 69** card. After that, I get some strange exception whenever I exit a LibGDX:

A fatal error has been detected by the Java Runtime Environment:

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000007fee145d6c4, pid=5876, tid=2100

JRE version: Java(TM) SE Runtime Environment (8.0_05-b13) (build 1.8.0_05-b13)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.5-b02 mixed mode windows-amd64 compressed oops)
Problematic frame:
C  [OPENGL32.dll+0xdd6c4]

**Comment by MobiDevelop** [comment]
Looks like a driver issue. I'm afraid we can't do anything about that.
