### ISSUE TITLE
(1.6.5) TextField width can't be changed

### ISSUE THREAD

**Issue by federicodangelo** [libgdx/libgdx#3389]
The getter TextField.getPrefWidth() return a fixed value of 150, so there is no way to change the default width of a TextField, it would be nice to have a setPrefWidth() method and using an instance variable to store the prefWidth, with a default value of 150.

**Comment by NathanSweet** [comment]
See discussion: https://github.com/libgdx/libgdx/issues/1336#issuecomment-35028001
TLDR; the size a widget feels is its min/pref/max width is the widget's opinion, not your opinion. Use a Table or Container to use a different value for layout, or ignore the widget's suggestion entirely and set the size explicitly.

**Comment by nooone** [comment]
A common workaround for this is to subclass the widget and override `getPrefWidth()`.

**Comment by NathanSweet** [comment]
That will work, though I'd say it's better to either set the text field width explicitly, or use a layout manager (like Container or Table) that sizes the text field as you want.
