### ISSUE TITLE
Bullet - btBvhTriangleMeshShape allows only 1024 mesh parts

### ISSUE THREAD

**Issue by realitix** [libgdx/libgdx#3393]
Hello everyone,
I'm using btBvhTriangleMeshShape in conjunction with the HeightField from Xoppa to generate my height map.
However I found a bug but I don't know if it's bullet or the libgdx bullet wrapper.
I use it like that:

```
btBvhTriangleMeshShape shape = new btBvhTriangleMeshShape(this.model.meshParts);
```
If the mesh part number is upper 1024, then bullet wouldn't create no more physical triangle, it will stop at 1024 triangles max.

but if I don't use the 'useQuantizedAabbCompression', it works.
```
btBvhTriangleMeshShape shape = new btBvhTriangleMeshShape(this.model.meshParts, false);
```
1024 = 10 bits = 1111111111.
So I think, there is somewhere an array with only 10 bits for key.
It's just a guess, I tried to get into the wrapper code but it's JNI and difficult to understand.

PS: I use the gdx-bullet-1.6.5 wrapper

**Comment by realitix** [comment]
I think it's bullet physics behavior.
In the file 'src/bullet/BulletCollision/BroadphaseCollision/btQuantizedBvh.h' : 
```
// 10 gives the potential for 1024 parts, with at most 2^21 (2097152) (minus one
// actually) triangles each (since the sign bit is reserved
#define MAX_NUM_PARTS_IN_BITS 10
```

And in the file 'src/bullet/BulletCollision/CollisionShapes/btOptimizedBvh.cpp':
```
virtual void internalProcessTriangleIndex(btVector3* triangle,int partId,int  triangleIndex)
		{
			// The partId and triangle index must fit in the same (positive) integer
			btAssert(partId < (1<<MAX_NUM_PARTS_IN_BITS));
			btAssert(triangleIndex < (1<<(31-MAX_NUM_PARTS_IN_BITS)));
			//negative indices are reserved for escapeIndex
			btAssert(triangleIndex>=0);

```

It looks like it that. So I have to recompile bullet if I want more mesh parts :-1: 
I will stick with 1024 parts! Xoppa, do you see a workaround ?

**Comment by xoppa** [comment]
Perhaps use `btHeightfieldTerrainShape` instead? If you do, would you mind to contribute a small test?
![Decision chart](https://github.com/libgdx/libgdx/wiki/images/bullet_shape_decision.png)
https://github.com/libgdx/libgdx/wiki/Bullet-Wrapper---Using-models

**Comment by realitix** [comment]
I tried  to use btHeightfieldTerrainShape without success. And the documentation is so poor! There is only one developer working on bullet physics, that's amazing!
I would give another shot to the terrainShape.

**Comment by jrenner** [comment]
a long time ago when I tried to use btHeightfieldTerrainShape I couldn't
get it to reliable produce a mesh matching my libgdx mesh, I think it's
possible it's broken
