### ISSUE TITLE
libGDX Setup Layout is too big in resolution 1366x768

### ISSUE THREAD

**Issue by johanessurya** [libgdx/libgdx#3395]
This is not bug but it would better if you make 'gdx-setup.jar' more friendly with smaller resolution.

Here the screenshot. Look at the bottom of the 'gdx-setup.jar'. I can't see the rest of it. 
![libgdx it too big](https://cloud.githubusercontent.com/assets/2444537/9698266/d80136d2-53d8-11e5-9b20-c093dca78890.png)

**Comment by Gtoknu** [comment]
Agreed, I tried resizing it but no luck.

I always move it up to read the logs then move down when done to close it.

**Comment by badlogic** [comment]
Yeah, there's a lot of whitespace we could get rid of. @Tom-Ski do you want to shrink your baby or should i?

**Comment by Tom-Ski** [comment]
I'm on it!
