### ISSUE TITLE
Add History In 'gdx-setup.jar'

### ISSUE THREAD

**Issue by johanessurya** [libgdx/libgdx#3396]
It is not bug but it would be great if you add history recently that we have create last time. For example: We have create first project and fill all field.
Next day, we want to create new project, but we should fill all of them again, besides we only want to change the title or class. 

It would be great id you add dropdown that have recent history of it, and just load it when it clicked.

For Android SDK field you could detech ANDROID_HOME first if not found then add default value. It would make a lot easier to generate new project.

![libgdx history](https://cloud.githubusercontent.com/assets/2444537/9698301/1a02be4c-53da-11e5-9c51-17369844d7c8.jpg)

**Comment by nooone** [comment]
Are you serious...?

**Comment by johanessurya** [comment]
Yes :)

Did I say something wrong?

**Comment by badlogic** [comment]
Nah, you didn't. I appreciate your idea of improving the user experience.
That being said, think about what saving 90% of the values means. When
creating a new project, you'd still have to change:

* the app's name
* the destination folder
* the package name/main class name

There's no net win, you still have to modify these. I'm not sure how
Dropbox would help. Also, you'd need to provide credentials for that to
work. That's a lot of work on our end, for little to no gain.

Reading ANDROID_HOME should already be done. If not, we should add that :)

**Comment by nooone** [comment]
I think by Dropbox he meant a dropdown menu with the recently created projects. It took me a while to figure that out as well.

@johanessurya I didn't want to sound rude, but it really sounds like you will have a hard time actually programming the game code itself if you are too lazy to re-enter a few fields in the setup ui :)

**Comment by johanessurya** [comment]
Thank you for quick reply. I'm very appreciate that. 

> Reading ANDROID_HOME should already be done. If not, we should add that :) 

Yes, we should. It's little bit annoying when always copy and paste path on it.

> * the app's name
> * the destination folder
> * the package name/main class name

I mean for beginner who just re-create like me. Hehehehe...

@nooone 
Hahaha... probably. I'm really lazy person to type that over and over again.
Yes, I mean dropdown not dropbox. I'm sorry about that.

**Comment by nooone** [comment]
ANDROID_HOME is already set automatically... https://github.com/libgdx/libgdx/blob/master/extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetupUI.java#L524

**Comment by johanessurya** [comment]
@nooone WOW! Thanks :)

**Comment by Tom-Ski** [comment]
As stated ANDROID_HOME is already set, and is the only field that should be automatically picked up.  You shouldn't be making projects that often with the same settings.
