### ISSUE TITLE
Field API lacks optimization for primitive types

### ISSUE THREAD

**Issue by antag99** [libgdx/libgdx#3397]
Java's reflection API offers primitive variations of the `get(Object)` and `set(Object, Object)` methods in `java.lang.reflect.Field` that can be used to avoid boxing. The reflection wrapper does not expose this functionality, which I need to reduce overhead when comparing lots of objects that contain primitive fields.

**Comment by MobiDevelop** [comment]
Not sure how this would look on the GWT emulation.

**Comment by antag99** [comment]
It could just box the primitives, I'm primarily concerned about the performance on non-gwt platforms.

**Comment by MobiDevelop** [comment]
If you don't care about GWT, just use standard reflection.

**Comment by antag99** [comment]
I'm writing a library that needs to be compatible with GWT. Performance under GWT already sucks, so I don't think this optimisation would yield any difference worth the effort.

**Comment by MobiDevelop** [comment]
So, are you proposing that we blindly cast in the GWT implementation? I'm not sure that would result in consistent behavior.

**Comment by antag99** [comment]
I'm proposing that we box/cast/wrap the primitives, which should yield exactly the same results (unless the GWT reflection is improperly implemented).

**Comment by MobiDevelop** [comment]
I think you should make a PR for how you think it should be done, making sure that the behavior is consistent.

**Comment by badlogic** [comment]
Closing this in favor of a PR.
