### ISSUE TITLE
Ninepatch wrong work with flipped TextureRegion

### ISSUE THREAD

**Issue by igorushko** [libgdx/libgdx#3403]
if a textureregion is flipped and then new a ninepatch using this region, the drawing is not correct.
http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=6193&p=80344&hilit=NinePatch+flip#p80344

**Comment by tomcashman** [comment]
+1

**Comment by tomcashman** [comment]
From what I can tell I'd need to add some logic to the NinePatch constructor to check if the TextureRegion is flipped on either the X and/or Y axis and then make sure that the u, v, u2 and v2 values are correct in each of the patches. However, I'm not entirely sure what those values are/represent in the TextureRegion class, maybe @badlogic or @xoppa could explain?

**Comment by badlogic** [comment]
Saw a code fix in the forum thread. Not sure it was proper. Please test and send a PR if this fixes the issue.
