### ISSUE TITLE
[Defect] Gdx.gl20 has no glPointSize

### ISSUE THREAD

**Issue by Gtoknu** [libgdx/libgdx#3411]
While it's understandable that such method has no use on OpenGL ES, on desktop it still has a role:
setting the `gl_PointSize` variable on a vertex shader does nothing when rendering points on desktop, the only way to increase points size is to use `Gdx.gl10.glPointSize(int)`, but this is unusable since `gl10` is `null`.

Should the `GL20` interface have a `glPointSize()` method that does nothing on mobile implementation but calls LWJGL's glPointSize on desktop implementation?

**Comment by xoppa** [comment]
I don't think that it's a good idea to add a method to the GL20 interface which is not actually part of the gles 2 spec. Especially not if it is only going to work on one platform only. Note that in the desktop launcher you do have access to all opengl (non ES) methods. See https://github.com/libgdx/libgdx/wiki/Interfacing-with-platform-specific-code.

**Comment by MobiDevelop** [comment]
I agree with @xoppa.

**Comment by FyiurAmron** [comment]
slightly related: https://github.com/libgdx/libgdx/issues/3218 (another GL command that's "missing"); so yup, in a nutshell - for consistency reasons, IMO it's best the way it is.

**Comment by Gtoknu** [comment]
I get it, I'm currently using plaform specific code on my project but I thought that you'd want to know.
So, this might be closed then, thanks guys :)
