### ISSUE TITLE
Could not find dependency with some gradle configuration

### ISSUE THREAD

**Issue by GerardPaligot** [libgdx/libgdx#3414]
Hello,

I started to work on the integration of the Google Plays Games in my game but I got quickly an error with the gradle configuration.

After some researches, I have exactly the same problem than [this topic](http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=19634&p=82212&hilit=BaseGameUtils#p82212) on the LibGdx's forum but the ["solution"](http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=19634&p=82212&hilit=BaseGameUtils#p82257) is weird.

It seems that, sometimes, some LibGdx projects can't use external dependencies and the solution is to create a new LibGdx project (bad solution!).

**Comment by MobiDevelop** [comment]
How is it a libgdx issue that you don't have the correct Google artifacts?

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md#using-the-issue-tracker
