### ISSUE TITLE
Tooltip needs more flexibility

### ISSUE THREAD

**Issue by sarkanyi** [libgdx/libgdx#3418]
Currently Tooltip only supports hovering a pointing device. It would be nice if it would support any kinds of InputEvent if someone wants it. Right now it is impossible for example to make tooltips to appear using LongPress which is the convention on touchscreen devices without hover support.
One Option would be Tomski's proposed solution: https://gist.github.com/Tom-Ski/a02f0cb692abb707ec48
This would add flexibility to extend BaseTooltip to use different EventListeners and to support any kind of behaviour.

**Comment by NathanSweet** [comment]
It looks like currently a tooltip will be shown if you long press. Is that not the case?

TooltipManager could have a `show(Tooltip)` method if you want to programmatically trigger showing.

**Comment by sarkanyi** [comment]
Nope, it's not the case, at least on Android. On the computer it seems to work, because there was a mouseMoved() before. Also I tried calling getManager().enter() however that doesn't works because there is a condition "if (Gdx.input.isTouched)) return; which prevents setContainerPosition to be called. I tried something like this: https://gist.github.com/sarkanyi/85a9dc0150da0efbed9

**Comment by sarkanyi** [comment]
Well, based on this I've implemented my own tooltip, that gives me even more flexibility so I guess it's safe to close this if it's not desired on libgdx level.

**Comment by NathanSweet** [comment]
Sorry, this issue got buried in the backlog. Enter is fired for mouse move on the desktop and also for each mouse down / touch on all platforms. Ultimately we need if something in tooltip needs to be improved. https://github.com/libgdx/libgdx/wiki/More-Info
