### ISSUE TITLE
create framebuffer object with stencil and depth buffer on android, return GL_FRAMEBUFFER_UNSUPPORTED

### ISSUE THREAD

**Issue by yangweigbh** [libgdx/libgdx#3422]
when create a framebuffer object with stencil and depth buffer on android, the glCheckFramebufferStatus return GL_FRAMEBUFFER_UNSUPPORTED

actually on android, if both stencil and depth buffer will be used in framebuffer object, the renderbuffer should use stencil and depth combined renderbuffer,  such as GLES11EXT.GL_DEPTH24_STENCIL8_OES. Here is my code specific to android platform

if (hasStencil && hasDepth) {
            gl.glBindRenderbuffer(GL20.GL_RENDERBUFFER, depthStencilBufferHandle);
            gl.glRenderbufferStorage(GL20.GL_RENDERBUFFER, GLES11Ext.GL_DEPTH24_STENCIL8_OES, colorTexture.getWidth(), colorTexture.getHeight());
            gl.glFramebufferRenderbuffer(GL20.GL_FRAMEBUFFER, GL20.GL_DEPTH_ATTACHMENT, GL20.GL_RENDERBUFFER, depthStencilBufferHandle);
            gl.glFramebufferRenderbuffer(GL20.GL_FRAMEBUFFER, GL20.GL_STENCIL_ATTACHMENT, GL20.GL_RENDERBUFFER, depthStencilBufferHandle);
        }

**Comment by yangweigbh** [comment]
test with android 4.4 and android 5.1 on nexus5

**Comment by realitix** [comment]
I had problems too with this, thanks for that, we'll wait for Xoppa, he is the 3D guy !

**Comment by xoppa** [comment]
Can you send a PR to fix it. Or, include a small sscce which I can use to verify and fix it?

**Comment by yangweigbh** [comment]
PR created
https://github.com/libgdx/libgdx/pull/3460

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://beta.lotosus.com/italian.php?fr>

 

loogie@basicelementdesign.com
