### ISSUE TITLE
Use android.app.fragment instead of support library

### ISSUE THREAD

**Issue by wonson** [libgdx/libgdx#3427]
Can i use android.app.fragment instead of android.support.v4.app.Fragment (AndroidFragmentApplication extends android.support.v4.app.Fragment) if my target api > 11 ? 

API 11 is very old version, so I want to stay native with the os code.

**Comment by nooone** [comment]
What's your issue exactly? You want us to change from android.support.v4.app.Fragment to android.app.Fragment?

The target API doesn't matter btw, it's the minimum API that counts here and libgdx still supports everything down to API 8 AFAIK. So I believe it can't be changed.

What's the problem with using the support library?

**Comment by wonson** [comment]
Hmmm, I don't mean you should change that, but I want at maybe optional class (or project build tool option) to use native android.app.Fragment if my minimum API is above 11 (In fact I want to make it 19+ so the support library is redundant to me.)

Using android.support.v4.app.Fragment means the Activity must also change to FragmentActivity, that also causes me some troubles, but thats another story

**Comment by MobiDevelop** [comment]
It is open source, you could just copy the FragmentApplication source into a standard fragment.

**Comment by wonson** [comment]
Yup, that's the only way I can think of.
