### ISSUE TITLE
Controller detection

### ISSUE THREAD

**Issue by orangepascal** [libgdx/libgdx#3431]
I've been running into issues with controllers, mostly they can be filtered down to "weird hardware" which seems to be detected as a controller when it isn't.

Not sure if that's fixable at all, just wanted to make sure you guys are aware of it.

What I ran into so far:
- Midi-keyboards / midi-gadgets are detected as the first controller
- "game keyboards" like this (http://www.razerzone.com/gaming-keyboards-keypads/razer-nostromo) are detected as first controller (could say it IS a controller of sorts I guess)
- a Youtuber's microphone also triggered this.

I have no idea how the code works deciding on what a controller is or not, and I don't have the hardware to test these things, I just know the problem exists. Maybe you guys have a brilliant idea about it ;)

if not, just close the issue.. it's a minority problem

**Comment by badlogic** [comment]
If we switch to LWJGL 3, this should be mostly fixed hopefully. I'll leave this open for now.

**Comment by intrigus** [comment]
Out of interest, how will lwjgl3 help? Do you want to use the game pad API of GLFW?

**Comment by badlogic** [comment]
This has been fixed in the LWJGL 3 backend. It can't be fixed in the LWJGL 2 backend i'm afraid.
