### ISSUE TITLE
Inconsistent handling of space before any color tag, even a [] tag with bitmapfonts.

### ISSUE THREAD

**Issue by xGnoSiSx** [libgdx/libgdx#3432]
Versions affected: master:1.6.6-SNAPSHOT and goes back to 1.5.0 (haven't tested 1.4.x)
I'm using color tags to emphasize keywords and f.draw handles spaces before tags poorly even in a single line string. I don't know if spaces are skipped or if it's a glyphrun bug.

I haven't tried it with fixed width fonts.

``` Java
        f.draw(batch, "...blah blah[RED] BINGO[] blah blah... ",300,300);
        f.draw(batch, "...blah blah [RED]BINGO []blah blah... ",300,270);
```

![bug](https://cloud.githubusercontent.com/assets/8305672/10016787/1aa8d3d0-6132-11e5-99c3-3dece750a2d6.png)

Adding 1 extra space seems to work but it's not elegant.

``` Java
        f.draw(batch, "...blah blah  [RED]BINGO  []blah blah... ",300,240);
```

Edit: Provided test code & assets in my last comment. Please review.

**Comment by davebaol** [comment]
This looks related to issue #3378

**Comment by xGnoSiSx** [comment]
I read that issue before posting but imho this looks completely different. Also this is only for the space character. Without spaces, the string comes out ok, so there's definitely something going on with space handling.

**Comment by davebaol** [comment]
Then it looks related to issue #3134 and PR #3217 which is supposed to fix it   :P

**Comment by xGnoSiSx** [comment]
Oh, kk thanks for spotting it. 
I won't touch my game text yet and will be waiting for a fix on master.

**Comment by davebaol** [comment]
Please provide a [SSCCE](http://sscce.org/)

**Comment by xGnoSiSx** [comment]
Will do ASAP...

**Comment by xGnoSiSx** [comment]
Ok, sorry for the long delay, here's a minimal project:

MyGdxTest.java:
```java
package com.mygdx.tests;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;

public class MyGdxTest extends ApplicationAdapter {
	SpriteBatch batch;
	Texture img;
	BitmapFont f;
	
	@Override
	public void create () {
		batch = new SpriteBatch();
		img = new Texture("badlogic.jpg");
		f = new BitmapFont(Gdx.files.internal("opti-30-b.fnt"), false);
		f.getData().markupEnabled = true;
	}

	@Override
	public void render () {
		Gdx.gl.glClearColor(0.5f, 0.5f, 0.5f, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		batch.begin();
		batch.draw(img, 0, 0);
		
        f.draw(batch, "...blah blah[RED] BINGO[] blah blah... ",300,300);
        f.draw(batch, "...blah blah [RED]BINGO []blah blah... ",300,270);
		
		batch.end();
	}
}
```

assets dir:

https://www.dropbox.com/s/a2t2yimx1xgb324/badlogic.jpg?dl=0
https://www.dropbox.com/s/n9ek0wy9omrnxzb/opti-30-b.fnt?dl=0
https://www.dropbox.com/s/15cr4beyzo7uyjs/opti-30-b.png?dl=0

Let me know if this needs more work.

**Comment by NathanSweet** [comment]
Works correctly with latest.
