### ISSUE TITLE
Add and apply a field for unitScale Y in IsometricTiledMapRenderer 

### ISSUE THREAD

**Issue by del-sol** [libgdx/libgdx#3435]
Currently, the renderer applies the same value for unit scale to both tile length and width. Some isometric tiled maps have tiles with different values for width and length, causing the map to be drawn off center (vertically). This adds unnecessary complications to stuff like path finding,  graphs / grids aligned to world coords, and converting screen to world coords, down to a specific tile.

Adding a constructor to pass a unit scale value for Y, and a field for it to be applied to the rendering computations, would fix this cleanly.

**Comment by del-sol** [comment]
Wrote a simple modification the isometric renderers to handle this issue, and made a pull request here:
https://github.com/libgdx/libgdx/pull/3436

Thanks.

**Comment by xoppa** [comment]
See #3436
