### ISSUE TITLE
Adding an icon too big crashes without an exception

### ISSUE THREAD

**Issue by tuxayo** [libgdx/libgdx#3441]
I'm currently porting a Java Swing app to LibGDX
When using addIcon() with the old icon (I didn't noticed that it was 850x850...)
The app crashes without any exception or error message

**Comment by xoppa** [comment]
Please include the required information to reproduce the issue and the steps you took to verify that this is indeed an issue with libgdx.
https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md

**Comment by tuxayo** [comment]
I reproduced the bug using the default project generated by the setup + adding an icon.

https://gitlab.com/tuxayo/libgdx_icon_bug_reproduced

There are two branches, one with a 359² icon thats works and another with a 360² icon that crashes.

https://gitlab.com/tuxayo/libgdx_icon_bug_reproduced/compare/works_icon_359x359...crash_icon_360x360
