### ISSUE TITLE
Graphics crash with java 8

### ISSUE THREAD

**Issue by Frontrider** [libgdx/libgdx#3443]
I found a report on java's bug tracker, whitch pointed me to report it here.
I tought that is the current temporary video card (an old one), but its crashing for other people too.

Downgrading to java7 for now.

http://pastebin.com/hHpKqnTi

**Comment by xoppa** [comment]
This is an issue tracker. Please use the forum or irc for personal support requrest.
https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md
