### ISSUE TITLE
List<Label> issue

### ISSUE THREAD

**Issue by TaiVuong** [libgdx/libgdx#3450]
Method toString() in Label should return "text" only instead of returning "Label: text".

**Comment by nooone** [comment]
I think it's pretty common to include the class in the `toString()` method. It's usually for debugging only anyway. What's the problem with the current implementation?

**Comment by FyiurAmron** [comment]
I agree with nooone - `toString()` is a debugging method, it shouldn't be used for actual serialization/textification of the object. For the Label class you should use `getText()` instead. Please close this "issue".

**Comment by MobiDevelop** [comment]
I agree.

**Comment by GreenLightning** [comment]
Regarding the title:

If you just want a list with several textual entries, you should use List<String> instead of List<Label>.
