### ISSUE TITLE
Issue with live wallpaper visibility

### ISSUE THREAD

**Issue by denis-isaev** [libgdx/libgdx#3454]
1) Press button "Set wallpaper" while wallpaper staying in loading state (screenshot: http://i.imgur.com/68iI8ye.png).
2) Go to home screen
3) Wallpaper is not visible (black screen).

It looks like problem in AndroidWallpaperEngine.onVisibilityChanged method. When it calls with true value, wallpaper already closed (by pressing "set wallpaper") and method AndroidWallpaperEngine.isVisible return false.

**Comment by denis-isaev** [comment]
It happens only on Android 4.4.4 and hardware device (Samsung S4 google edition in my case). In virtual device (genymotion) with android 4.4.4 all works fine. On hardware Nexus 5 with Android 5.1 works fine too.

**Comment by intrigus** [comment]
Have you also tried it with a official emulator?
I heard that Genymotion isn't always 100% correct.

**Comment by denis-isaev** [comment]
Yes, just now. All works well. 
I'll try to find another hardware device with Android 4.4.4 and test it.

**Comment by denis-isaev** [comment]
I think I found something.

In two situation (when I press button "Set wallpaper" normally and when I press button "Set wallpaper" too fast) method AndroidLiveWallpaperService.onSurfaceDestroyed works differently.

If I press button "Set wallpaper" too fast ([wallpaper has not been rendered yet](http://i.imgur.com/68iI8ye.png)) there are the following differences:
1) `AndroidLiveWallpaperService.this.engines` is 2 instead of 3 in normal situation. Maybe because preview engine has not been created at all?
2) The condition `AndroidLiveWallpaperService.this.linkedEngine == this` is true.
3) Called the method `AndroidLiveWallpaperService.this.view.surfaceDestroyed` because `AndroidLiveWallpaperService.this.linkedEngine == this && AndroidLiveWallpaperService.this.view != null` is true.
4) So, code
 
    this.engineWidth = 0;
    this.engineHeight = 0;
clears width and height in current `AndroidLiveWallpaperService.this.linkedEngine` because `AndroidLiveWallpaperService.this.linkedEngine == this` is true.
5) Maybe `AndroidLiveWallpaperService.this.linkedEngine` in this situation is not preview engine, but engine than uses for homescreen, and this code clear width and height for homescreen engine, that is why homescreen is black? How can I check this assumption?

**Comment by badlogic** [comment]
I guess nobody could repro this, so a fix is unlikely to appear. OP, please send a PR if you can reliably fix this issue on your test device.
