### ISSUE TITLE
Padded fonts have inconsistent space calculation around [] tags in marked up strings.

### ISSUE THREAD

**Issue by xGnoSiSx** [libgdx/libgdx#3455]
Please merge #3432 and other relevant issues to this:

After testing with padded and not-padded fonts it is clear that padding is bugged.

Tested with the built-in: data\arial-32.fnt and data\arial-32-pad.fnt for contrast (and to eliminate issues with my personal assets that I wrongly uploaded in #3432).

The top pair of draws are the padded font, the second pair has no padding and is displayed correctly.

If the last glyphrun ended with a space, the location to start the new glyphrun (for the next colored text section) doesn't compute the correct offset taking into account pad left & pad right.

The same happens when closing a tag since a new run starts with the previous color.

Edit: Note that it's not about glyphs or spaces at all, the text from the next run has wrong offset and overlaps the previous text and the total width of the text element is incorrect.

Edit 2: Note how the 4rth line is also different than the 3d this is a seperate and maybe a linked issue since it's not affected by font padding.

![output](https://cloud.githubusercontent.com/assets/8305672/10265004/6bb0d220-6a27-11e5-83e9-162a964d3107.png)

Application class:

```java
package com.mygdx.tests;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;

public class MyGdxTest extends ApplicationAdapter {
    SpriteBatch batch;
    BitmapFont f,f_no_pad;

    @Override
    public void create () {
        batch = new SpriteBatch();
        
        f = new BitmapFont(Gdx.files.internal("data/arial-32-pad.fnt"), false);
        f_no_pad = new BitmapFont(Gdx.files.internal("data/arial-32.fnt"), false);
        f.getData().markupEnabled = true;
        f_no_pad.getData().markupEnabled = true;
    }

    @Override
    public void render () {
        Gdx.gl.glClearColor(0.5f, 0.5f, 0.5f, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        batch.begin();

        
        f.draw(batch, "...blah blah[RED] BINGO[] blah blah... ",200,300);
        f.draw(batch, "...blah blah [RED]BINGO []blah blah... ",200,270);

        f_no_pad.draw(batch, "...blah blah[RED] BINGO[] blah blah... ",200,200);
        f_no_pad.draw(batch, "...blah blah [RED]BINGO []blah blah... ",200,170);

        batch.end();
    }
}
```

**Comment by xGnoSiSx** [comment]
Any Ideas how we should handle this bug? By going through the code myself I found out that it isn't trivial to fix this by a long shot and requires a re-write even perhaps braking the API. 

For my use, I am changing all of my game strings on init adding an extra space where need, keeping my resource files correct as to remove this init code if the bug gets fixed. This is how I dealt with it, but you can still point it out if you know where & what to look for.

This issue has been open for 2 months now. Can we just begin pondering a solution?

**Comment by NathanSweet** [comment]
The second issue is that 1) we break text into runs both at new lines and when the color changes, and 2) each glyph run has tightly fitting bounds by using the negative xoffset of the first glyph so it is drawn at the drawing position (not left of it) and computing the run width by using the last glyph's width (not xadvance). Consider:

```
font.draw(batch, "A[RED] B[]", 200, 200);
// run 1 width: 0 "A" offset + 22 "A" width = 22
// run 2 width: 0 " " offset + 9 " " xadvance + 22 "B" width = 31
// total width: 53
font.draw(batch, "A [RED]B[]C", 200, 170);
// run 1 width: 0 "A" offset + 21 "A" xadvance + 9 " " width = 30
// run 2 width: -3 "B" offset + 22 "B" width = 19
// total width: 49
```

Tightly fitting bounds are useful for word wrap or other situations where you don't want text drawn outside of some bounds. Because we use runs for colors, unfortunately the tightly fitting bounds result in different glyph spacing than when laying out the glyphs without colors.

To fix this we can turn off tightly fitting bounds for a run delimited by a color tag. Wrapping or other measuring of a "color" run may not have tightly fitting bounds, but this seems more acceptable than color tags changing the spacing between glyphs.
