### ISSUE TITLE
TextField font rendering issues

### ISSUE THREAD

**Issue by Arcnor** [libgdx/libgdx#3456]
This is a screenshot of a button (top) and a textfield (bottom). As you can see, the text on the textfield looks as if some characters are moved a bit up (you can see the capital 'T' is cut at the top, for example)

<img width="120" alt="textfield" src="https://cloud.githubusercontent.com/assets/28616/10266389/bc611978-6aa9-11e5-9034-00dfb28dc682.png">

I've done some testing, and overriding `setStyle` for the `TextField` and making the `textHeight` 1 pixel bigger fixes the issue. However, I've checked the text height for the button (it's a `Label`) and it's exactly the same as the one on the `TextField` (before doing my fix) so probably there is an underlying issue that needs fixing. Also, changing the height of the `TextField` itself doesn't fix the issue.

Does anyone have an idea of what might be happening? I'm happy to try fixing the issue myself if somebody can point at some probable cause (the code is a bit big) but if nobody can, I'll post an SSCCE

**Comment by NathanSweet** [comment]
Probably text rendering is drawn at a fractional position. Need SSCCE.

**Comment by Xtrinity** [comment]
I just had this issue. If you're using FreeTypeFontGenerator you may want to generate your font with an even font size.

**Comment by NathanSweet** [comment]
25 days, no SSCCE.
