### ISSUE TITLE
repeated Texture behaviour differs on Android and iOS (RoboVM) based on image size

### ISSUE THREAD

**Issue by julienvillegas** [libgdx/libgdx#3461]
The sample code below generates a 3 by 3 image using the setWrap(Texture.TextureWrap.MirroredRepeat, Texture.TextureWrap.MirroredRepeat) and setRegion functions.

Problem:
* On Android, independently of the size of the source image , it works.
* On iOS, using RoboVM, the image size mut be a power of two. if the image is not a power of two, the image is shown as black.

            
      public class GameScreen implements Screen {
    
        MyGdxGame game;
        private Stage stage;
    
        public GameScreen(MyGdxGame aGame){
            stage = new Stage(new ScreenViewport());
            game = aGame;
            Texture imgTexture = new Texture(Gdx.files.internal("badlogic.jpg"));
            imgTexture.setWrap(Texture.TextureWrap.MirroredRepeat, Texture.TextureWrap.MirroredRepeat);
            TextureRegion imgTextureRegion = new TextureRegion(imgTexture);
            imgTextureRegion.setRegion(0,0,imgTexture.getWidth()*3,imgTexture.getHeight()*3);
    
            TextureRegionDrawable imgTextureRegionDrawable = new TextureRegionDrawable(imgTextureRegion);
            Image img = new Image();
            img.setDrawable(imgTextureRegionDrawable);
            img.setSize(imgTexture.getWidth()*3,imgTexture.getHeight()*3);
            stage.addActor(img);
        }
    
        @Override
        public void show() {
    
        }
    
        @Override
        public void render(float delta) {
            Gdx.gl.glClearColor(1, 0, 0, 1);
            Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
            stage.act(delta);
            stage.draw();
        }
    
        @Override
        public void resize(int width, int height) {
            stage.getViewport().update(width, height, true);
        }
    
        @Override
        public void pause() {
    
        }
    
        @Override
        public void resume() {
    
        }
    
        @Override
        public void hide() {
    
        }
    
        @Override
        public void dispose() {
            stage.dispose();
        }
    }

  [1]: http://i.stack.imgur.com/bh5qY.png

**Comment by MobiDevelop** [comment]
The OpenGL ES 2.0 spec only guarantees support for CLAMP_TO_EDGE on non-power-of-two textures. Any other mode may or may not work depending on the driver and the extensions it supports.

Basically, use POT textures if you want consistent wrapping and/or mipmap support.

**Comment by xoppa** [comment]
I guess, strictly speaking, that this is an issue of the android gpu driver, because [the spec says](https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexParameter.xml):
> Similarly, if the width or height of a texture image are not powers of two and either the GL_TEXTURE_MIN_FILTER is set to one of the functions that requires mipmaps or the GL_TEXTURE_WRAP_S or GL_TEXTURE_WRAP_T is not set to GL_CLAMP_TO_EDGE, then the texture image unit will return (R, G, B, A) = (0, 0, 0, 1).
