### ISSUE TITLE
KTXProcessor crashes when I try to konvert ktx into zktx

### ISSUE THREAD

**Issue by denis-isaev** [libgdx/libgdx#3463]
I am trying convert ktx (with etc1 texture) into zktx.
Run:

```
D:\_proj\libgdx-1.6.1>java -cp gdx.jar;gdx-natives.jar;gdx-backend-lwjgl.jar;gdx-backend-lwjgl-natives.jar;gdx-backend-headless.jar;extensions\gdx-tools\gdx-tools.jar com.badlogic.gdx.tools.ktx.KTXProcessor D:\test.ktx D:\test.zktx
```

Output:

```
0 = D:\test.ktx
1 = D:\test.zktx
Processing : D:/test.ktx for face #0
Exception in thread "HeadlessApplication" com.badlogic.gdx.utils.GdxRuntimeException: Unsupported output format 
    at com.badlogic.gdx.tools.ktx.KTXProcessor$KTXProcessorListener.create(KTXProcessor.java:288)
    at com.badlogic.gdx.backends.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:105)
    at com.badlogic.gdx.backends.headless.HeadlessApplication$1.run(HeadlessApplication.java:90)
```

libgdx 1.6.1
java 1.8.0_60-b27
windows 10 x64

**Comment by xoppa** [comment]
you didnt specify the -etc1(a) option. Perhaps we should add a shortcut that in case in:ktx,out:zktx (or the other way around) is specified with no other options, that the file is simply (un)zipped as is.

**Comment by denis-isaev** [comment]
Help says KTXProcessor already able to do this:

    D:\_proj\libgdx-1.6.1>java -cp gdx.jar;gdx-natives.jar;gdx-backend-lwjgl.jar;gdx-backend-lwjgl-natives.jar;gdx-backend-headless.jar;extensions\gdx-tools\gdx-tools.jar com.badlogic.gdx.tools.ktx.KTXProcessor
    usage : KTXProcessor input_file output_file [-etc1|-etc1a] [-mipmaps]
      input_file  is the texture file to include in the output KTX or ZKTX file.
              for cube map, just provide 6 input files corresponding to the faces in the following order : X+, X-, Y+, Y-, Z+, Z-
      output_file is the path to the output file, its type is based on the extension which must be either KTX or ZKTX

      options:
        -etc1    input file will be packed using ETC1 compression, dropping the alpha channel
        -etc1a   input file will be packed using ETC1 compression, doubling the height and placing the alpha channel in the bottom half
       -mipmaps input file will be processed to generate mipmaps

      examples:
        KTXProcessor in.png out.ktx                                        Create a KTX file with the provided 2D texture
        KTXProcessor in.png out.zktx                                       Create a Zipped KTX file with the provided 2D texture
    KTXProcessor in.png out.zktx -mipmaps                              Create a Zipped KTX file with the provided 2D texture, generating all mipmap levels
        KTXProcessor px.ktx nx.ktx py.ktx ny.ktx pz.ktx nz.ktx out.zktx    Create a Zipped KTX file with the provided cubemap textures
        KTXProcessor in.ktx out.zktx                                       Convert a KTX file to a Zipped KTX file

Last line: **KTXProcessor in.ktx out.zktx Convert a KTX file to a Zipped KTX file**

But it didn't work.
