### ISSUE TITLE
NullPointerException thrown when AssetLoader.getDependencies returns null

### ISSUE THREAD

**Issue by jmp** [libgdx/libgdx#3467]
Using latest nightlies, `AssetManager` now crashes with NullPointerException when attempting to load assets with no dependencies, using custom loaders.

The cause is here:
https://github.com/libgdx/libgdx/commit/491f2646309e3d71f41ca7dbc8e02b5e09ba98d3#diff-d0ba77a9cde8d11730d759b7be8e8df8R101

As you can see, `dependencies == null`. But then, in `removeDuplicates`, the code is trying to access `array.ordered` which causes the NPE.

The code probably shouldn't even be trying to do anything with `dependencies` since it's `null`.

**Comment by xoppa** [comment]
Great catch, thanks!
