### ISSUE TITLE
GWT compilation error when using annotations with Class property set to primitive type

### ISSUE THREAD

**Issue by kotcrab** [libgdx/libgdx#3468]
When you have annotation with Class property and then you set it to some primitive type eg. `boolean.class` you will get GWT compilation errors in reflection cache generator: 
```
Compiling module com.kotcrab.playground.GdxDefinition
   Resolving com.kotcrab.playground.Playground.Foo
      Found type 'com.kotcrab.playground.Playground.Foo'
         [ERROR] Annotation error: cannot resolve boolean
java.lang.ClassNotFoundException: boolean
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[...]
         Invoking generator com.badlogic.gwtref.gen.ReflectionCacheGenerator
            [ERROR] Error invoking annotation method.
[...]
[ERROR] Line 10966: This method must return a result of type Class
```
[(full log)](https://gist.github.com/kotcrab/f4d6c7ac9041b88c2068#file-gistfile1-txt-L18-L21)

SSCCE:
```
public class AnnotationIssue extends ApplicationAdapter {
	@Override
	public void create () {
		Foo f = new Foo();
	}

	public static class Foo {
		@TestAnnotation(type = boolean.class)
		public int foo;
	}

	@Retention(RetentionPolicy.RUNTIME)
	@Target(ElementType.FIELD)
	public @interface TestAnnotation {
		Class<?> type ();
	}
}
```

**Comment by MobiDevelop** [comment]
Unfortunately, this is coming from the GWT compiler itself. I don't think there is anything we can do on our end.

**Comment by kotcrab** [comment]
I hoped it was libGDX issue, it will probably take forever to fix it in GWT and libGDX doesn't even use latest GWT version, right? Anyways I should be able to workaround this by using `Boolean.class`. Fell free to close if you are sure nothing can be done on libGDX side.

**Comment by MobiDevelop** [comment]
No, libgdx does not use the latest GWT version, however it does not appear to be fixed there. Since this is error is occurring in the GWT compiler when it tries to evaluate the annotation, there really isn't anything that can be done on the libgdx side.
