### ISSUE TITLE
Scene2d TextArea does not scroll by itself or when it is inside a ScrollPane

### ISSUE THREAD

**Issue by Xtrinity** [libgdx/libgdx#3469]
There was a fix posted on stackoverflow that involved setting the preferred rows but it breaks on some cases and is more of a hack.

I've tried the following solutions to no avail:
1. Outer container containing ScrollPane which contains TextArea
Problem: Outright doesn't scroll
2. Outer container and inner container containing TextArea with widths and heights
Problem: Will scroll but as more text is entered it will start deleting old text or something else funkier
3. Setting prefRows to change with the increasing lines in TextArea
Problem: Same issue as #2 but would take longer for that to happen. If you enter a lot of lines you can notice that something is definitely wrong.

**Comment by rami-alisawi** [comment]
Your first try should let you scroll if you use container.height/container.width to be smaller than the TextArea size.

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/issues/3796#issuecomment-202729107
