### ISSUE TITLE
String.replace() used in JsonWriter is extremely slow

### ISSUE THREAD

**Issue by nikoliazekter** [libgdx/libgdx#3476]
String.replace() clearly isn't suited for a lot of Json serializing every frame (profiler showed that it uses about 6% of the whole frame time in my case). I propose replacing it with what is described here http://stackoverflow.com/a/16229133/1992654

**Comment by Darkyenus** [comment]
(This does not solve the problem but) you probably shouldn't be serializing json every frame anyway. If you really need to serialize every frame, consider a binary format (try Kryo).

**Comment by nikoliazekter** [comment]
I'm actually using artemis-odb and Kryo should be supported soon. As for every frame serialization, I need it for some features of my in-game editor.
