### ISSUE TITLE
Check compatibility with Android 6.0 M

### ISSUE THREAD

**Issue by intrigus** [libgdx/libgdx#3481]
Changes in Android 6.0:
# Permissions

The permission model changes with Android 6.0
There are some things to check : 
- [ ] Read/Write to external Storage
- [ ] other things ?

Previously to Android 6.0 permissions were granted at install-time, now permissions can be granted and revoked at runtime. 
Only [dangerous permissions](http://developer.android.com/guide/topics/security/permissions.html#perm-groups) (Scroll down to table 1) need to be granted at runtime, [normal permissions](http://developer.android.com/guide/topics/security/normal-permissions.html) are automatically granted if they are declared in the manifest
# Runtime

Are we affected by these [changes](http://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-runtime) ? 

See 
- http://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-runtime-permissions
- http://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-runtime

**Comment by jtuta** [comment]
Since Nexus5 updated to 6.0 I have problems with full screen or immresive mode on Andorid.  At the bottom of application (where in non immersive mode buttons lay) I see black bar. 

Am I the only one?

**Comment by badlogic** [comment]
From my testing so far, the default permissions we use are a-OK.

**Comment by dgw** [comment]
If libgdx is handling the loading of files stored on a device's "sdcard", it should probably handle prompting for runtime permissions. When I updated my phone the only libgdx game I've tested so far immediately started force-closing instantly on start because it couldn't load external resources.

See kbz/SIFTrain#16.
