### ISSUE TITLE
Document MinimumTranslationVector

### ISSUE THREAD

**Issue by saltares** [libgdx/libgdx#3489]
`MinimumTranslationVector` is not documented and a user was confused about it on the [forums](http://www.badlogicgames.com/forum/viewtopic.php?f=15&t=20816). 

I will take this one later.

**Comment by xoppa** [comment]
While we're at it. What is the reason for having this class in the first place? Commonly you'd use a vector for both the direction and strength (@MobiDevelop https://github.com/libgdx/libgdx/commit/aabf5e58ff0c2ebdd8a9e9b5bee86cb674ce6344 for [issue 926 on google code](https://code.google.com/p/libgdx/issues/detail?id=926))

**Comment by saltares** [comment]
I suspect in most use cases you just want to know the normal to use it in
some other calculation. Having it as a unit vector might be more handy and
you'd save the normalisation later on.

On 14 October 2015 at 19:23, Xoppa <notifications@github.com> wrote:

> While we're at it. What is the reason for having this class in the first
> place? Commonly you'd use a vector for both the direction and strength (
> @MobiDevelop <https://github.com/MobiDevelop> aabf5e5
> <https://github.com/libgdx/libgdx/commit/aabf5e58ff0c2ebdd8a9e9b5bee86cb674ce6344>
> for issue 926 on google code
> <https://code.google.com/p/libgdx/issues/detail?id=926>)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/libgdx/libgdx/issues/3489#issuecomment-148144449>.
>



-- 
David Saltares Márquez

Software Developer
http://saltares.com

**Comment by MobiDevelop** [comment]
It was a concept I carried forward from the reference implementation I used. I have no strong feelings about it, so if it makes sense to not have it, that's fine with me.

**Comment by xoppa** [comment]
I see, thanks, I was just wondering. No need to fix something that isn't broken.
