### ISSUE TITLE
JNIGen compile but won't execute on x64

### ISSUE THREAD

**Issue by omulmann** [libgdx/libgdx#3490]
Build
```java
package bar;
public class Build{
    public static void main (String[] args) throws Exception {
        NativeCodeGenerator jnigen = new NativeCodeGenerator();
        jnigen.generate("src\\test\\java", "test-classes", "jni", new String[] {"Foo.java"}, null);
        BuildTarget win64 = BuildTarget.newDefaultTarget(TargetOs.Windows, true);
        new AntScriptGenerator().generate(new BuildConfig("foo"), win64);
        BuildExecutor.executeAnt("jni/build-windows64.xml", "-v -Dhas-compiler=true clean postcompile");
        BuildExecutor.executeAnt("jni/build.xml", "-v pack-natives");
    }
}
```

Native

```java
public class Foo {
	// @off
    static public native int add (int a, int b); /*
        return a + b;
    */
    public static void main (String[] args) throws Exception {
    	new JniGenSharedLibraryLoader("libs/foo-natives.jar").load("foo64");
    	System.out.println(add(1, 2));
    }
}
```

After running build (successful - jar with foo64.dll bundled), executing Foo ... fails ... (as in the video):

```java
Exception in thread "main" java.lang.NullPointerException: entry
	at java.util.zip.ZipFile.getInputStream(ZipFile.java:346)
	at com.badlogic.gdx.jnigen.JniGenSharedLibraryLoader.getFromJar(JniGenSharedLibraryLoader.java:152)
	at com.badlogic.gdx.jnigen.JniGenSharedLibraryLoader.extractLibrary(JniGenSharedLibraryLoader.java:129)
	at com.badlogic.gdx.jnigen.JniGenSharedLibraryLoader.loadLibrary(JniGenSharedLibraryLoader.java:104)
	at com.badlogic.gdx.jnigen.JniGenSharedLibraryLoader.load(JniGenSharedLibraryLoader.java:184)
	at Foo.main(Foo.java:13)
```

Doing instead:

```java
new JniGenSharedLibraryLoader("libs/foo-natives.jar").load("foo");
```

Produce:

```java
Exception in thread "main" java.lang.UnsatisfiedLinkError: Foo.add(II)I
	at Foo.add(Native Method)
	at Foo.main(Foo.java:15)
```
Platform: Windows 7 x64 Intel
JDK: 8u60 64-bit (compilation, execution)

Tried the trick as in the video (uh) launching with JDK 8u60 x86, and guess, doesn't work.
Time wasted: 3h

**Comment by badlogic** [comment]
You didn't pack your dll in your classpath.

**Comment by omulmann** [comment]
It is packed (40KB). It wouldn't have reach the line `System.out.println(add(1, 2));` otherwise, as its predecessor is unzip the jar looking for a Zip entry (the DLL).

**Comment by omulmann** [comment]
"Hacked" `JniGenSharedLibraryLoader` so it return the DLL path. 

Example of path: `C:\Users\jdoe\AppData\Local\Temp\jnigen\113076097273425\`

Then did:

```java
String path = new JniGenSharedLibraryLoader("libs/foo-natives.jar").load("foo");
System.setProperty("java.library.path", subPath);
System.loadLibrary("foo64");
System.out.println(add(1, 2));
```
And get:

```java
Exception in thread "main" java.lang.UnsatisfiedLinkError: no foo64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at Foo.main(Foo.java:20)
```

Despite foo64.dll exist if the path

**Comment by omulmann** [comment]
I guess I won't have any helping feedback here. I guess there is a need for such project. So will fork it and rewrite this project JDK8u60 getting ride of ANT externalizing inlined code. Will post here the github link when done

**Comment by NathanSweet** [comment]
ZipFile `getEntry` returns null. That means the file it is looking for is not in your zip.

JniGenSharedLibraryLoader is similar to SharedLibraryLoader, just without gdx dependencies. You might want to port SharedLibraryLoader to JniGenSharedLibraryLoader, since it seems SharedLibraryLoader has become a bit more sophisticated.

**Comment by omulmann** [comment]
I guess you haven't read this thread fully. Thanks anyway
