### ISSUE TITLE
(v1.7.0) GlyphLayout.setText.197 - IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Osaris31** [libgdx/libgdx#3491]
Hi,
I'm having random crashes caused by the GlyphLayout class.

```
java.lang.IndexOutOfBoundsException: index can't be >= size: 2 >= 0
	at com.badlogic.gdx.utils.Array.get(Array.java:127)
	at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:197)
	at com.badlogic.gdx.graphics.g2d.BitmapFontCache.addText(BitmapFontCache.java:494)
	at com.badlogic.gdx.graphics.g2d.BitmapFontCache.addText(BitmapFontCache.java:482)
	at com.badlogic.gdx.graphics.g2d.BitmapFont.draw(BitmapFont.java:208)
```

So, let me be clear from the start: Yes, this issue is most likely related to multi-threading. Now, I understand that libgdx is not thread-safe, but is this a reason to make it so much thread unfriendly?

The issue I'm experiencing here as been described a lot of time now, in #3388, #3369, #3172, etc...
Everytime you close it because "it's just a multithread problem". But wouldn't it be worth looking into the code of GlyphLayout to reduce the occurrence of bugs like this?

GlyphLayout use a `static private final Array<Color> colorStack` and then clears it like this:
```java
for (int i = 1, n = colorStack.size; i < n; i++)
	colorPool.free(colorStack.get(i));
colorStack.clear();
```
This seems the most *thread unfriendly* way of doing that. I know libgdx is not thread safe, but given the number of people who have bugs like this, it could be really great to change this colorStack into maybe a member instead of a static or something like that.

Thanks

**Comment by Darkyenus** [comment]
There is a good reason why is libGDX not thread-safe - adding thread safety would also add a considerable overhead and complexity, which would in most cases just slow the code down for no benefit. When developing an application with multiple threads, it is assumed that you know what you are doing and can workaround these problems. Anyway, libGDX provides a way to interface with it from other threads via `Gdx.app.postRunnable()`. Anything more advanced/complex requires a good knowledge of libGDX and threading (threads are powerful tools and it is easy to shoot yourself in a foot with them).

As a note on the colorStack: Yes it is the most thread unfriendly way, but it is also the most _memory friendly_ way, which is in something like libGDX far more important. (Only a handful of people use threads but _everybody_ uses memory)

**Comment by FyiurAmron** [comment]
@Osaris31 since the issue here is due to the threaded, unsynchronized use of static `colorStack` in `setText` method, just either
a) synchronize the calls to this method,
b) override this method with custom-tailored copy-paste version that uses a local color stack field instead of shared static one,
c) send a PR that would allow calling `setText` with `Array<Color> colorStack` as parameter,
e.g. change the current `setText` method to accept it, and make old signature do
```java
/** docs here */
public void setText (BitmapFont font, CharSequence str, int start, int end, Color color, float targetWidth, int halign, boolean wrap, String truncate, Array<Color> currentColorStack) {
   // old code requires changing to use the param instead of the static one
}

/** docs here */
public void setText (BitmapFont font, CharSequence str, int start, int end, Color color, float targetWidth, int halign,
		boolean wrap, String truncate) {
    setText( font, str, start, end, color, targetWidth, halign, wrap, truncate, GlyphLayout.colorStack );
}
```

as to solution c), it gives little benefit to API (the only thing it allows is decreased dependence on static fields), but has no real drawback as is (no functional changes, no speed changes etc.).

If at least one libGDX dev gives a thumb up about it, I can send the PR myself.

Still, IMO you should just synchronize your threads properly.

**Comment by Osaris31** [comment]
Hi,
Thank you for your feedback.

I think the issue here is that most devs wouldn't expect a method as simple as "setText()", to need to be called in a synchronized way:  "setText()" refers to an individual BitmapFontCache object, doesn't draw anything or do anything that you would expect to need synchronizing.
Therefore, having to create a Gdx.app.postRunnable for such a simple operation seems strange and does add a considerable overhead and complexity.
Solution a) cannot work because the "setText()" is also called internally a lot of time by UI elements such as Label. Solution b) and c) implie to override a lot of things, not only GlyphLayout but also BitmapFontCache which calls it.

It's too bad because every multiplayer games will face that, but I guess it's just that libGDX is not designed for multiplayer games and we'll have to live with it :p

**Comment by Darkyenus** [comment]
In multiplayer games I usually receive and parse/preprocess all network data on the off thread and then act on it on the main thread. It is not slower than doing all that work in singleplayer game (main thread does not deal with any IO, only processing) and it is way easier than synchronizing everything, where you would have to also make sure that you are not causing race conditions with your own game logic. But discussion is more suited to the IRC or forums.

On the suggested solutions: nothing except a) (synchronizing the call) will work properly in all cases. They will prevent this exact problem, but setText modifies local state and therefore if two threads call setText on the same object in the same time, it will most likely break again. c) will allow two concurrent calls of setText on different GlyphLayouts, but I wonder if it is even worth the hassle for such niche use case. If somebody decides to implement it, make sure to document that it does not provide full thread safety.

**Comment by Osaris31** [comment]
You're right, I'm going to close the issue and go for solution d) (rewrite BitmapFontCache so that setText() only really set a String and do nothing else, and then the draw() method will prepare the Glyphs if the String was changed since last draw)

**Comment by NathanSweet** [comment]
Back from vacation!

`colorStack` is working memory for a GlyphLayout. It uses a static to avoid allocating an Array per GlyphLayout, but this isn't a huge savings since you will try to avoid allocating GlyphLayout on the fly anyway. I'm fine with `colorStack` being non-static.

**Comment by NathanSweet** [comment]
Note that makes it more likely that different GlyphLayout instances can be used from different threads, but it looks like `Pools` is used which may have race conditions (eg if a map is resized while being accessed).

**Comment by Darkyenus** [comment]
Often-breaking thread safety is IMO better than sometimes-maybe-breaking thread safety.

**Comment by NathanSweet** [comment]
Yep. At least now multithreading will work just fine, until it doesn't. :)

**Comment by NathanSweet** [comment]
I was just considering moving it back to static and vaguely remembered this thread. @Darkyenus I realize now you were saying you prefer it static, so it is a more obvious problem. 4.5 years late, but I finally got it. :D

**Comment by Darkyenus** [comment]
@NathanSweet Looking at this whole issue five years later: Maybe we could get rid of using the `Color` pool altogether, by turning the `colorStack` into an `IntArray` (or `FloatArray`), and storing the color as packed into a primitive.

(This has nothing to do with thread safety, `colorStack` could stay happily static, but the code would get shorter, I think.)

**Comment by NathanSweet** [comment]
Hmm, that's interesting. Looks [like this](http://n4te.com/x/712-q1xm.txt). I like not needing a color pool. In the (common) case of markupEnabled == false, we convert the color to an int, then every run uses Color `set(int)`.  That's probably OK, though I'd like the non-markup case to not be affected by markup as much as possible. Not sure if it could be done better.
