### ISSUE TITLE
The Label issues

### ISSUE THREAD

**Issue by serhii-k** [libgdx/libgdx#3495]
Hello, yesterday I've updated libgdx from 1.5.2 to 1.7.0 and have noticed some issues with scene2d.ui Labels.

## Issue 1

Maybe it's intended, maybe not. In 1.7.0 Labels don't have a little space before the first character (actually the part of this character) and after the last one.

Please, see this example. It's a Label added to a table cell. Compare its left and right boundaries as was in the version 1.5.2 and as is in the version 1.7.0.

![space](https://cloud.githubusercontent.com/assets/10563821/10561560/54c44096-7536-11e5-8f26-c22ed42d8977.png)

## Issue 2 - really bizarre one

When you add a Label to a table cell and set the width of the latter, some characters may become broken...

Here is an example, where I have a table and add a lot of labels into its cells (like table.add(label).width(columnWidth)). Please, notice some strange artifacts in some characters (especially 'F', '5', '6'). The same thing without setting the width is below -- as you can see, all characters there are rendered correctly. Btw the font is 32px size and pregenerated with FreeTypeFontGenerator.

Please, click on the image to see it in full size.

![label_artifacts1](https://cloud.githubusercontent.com/assets/10563821/10561589/6325fcb8-7538-11e5-81cf-3f3c6d2040ce.png)

Another example is with a TextButton and its Label. When simply added to a table, the Label is rendered correctly, but if added followed by fillX(), the artifact appears:

![label_artifacts2](https://cloud.githubusercontent.com/assets/10563821/10561596/e24f3676-7538-11e5-8e6d-d30cd80aee5e.png)

The font is Lato 2.015 Light (Lato-Light.ttf):
http://www.latofonts.com

**Comment by serhii-k** [comment]
The previous examples were from Desktop.

Here are some from Android. Please, click on the images to see them in full size.

![example1](https://cloud.githubusercontent.com/assets/10563821/10564597/a60a144e-75c2-11e5-83cf-bea541f2135b.png)

![example2](https://cloud.githubusercontent.com/assets/10563821/10564598/aba701be-75c2-11e5-9a55-e503f7941b26.png)

**Comment by serhii-k** [comment]
I've checked different gdx versions. Both issues were introduced in libgdx 1.6.0.

**Comment by FyiurAmron** [comment]
probably the result of https://github.com/libgdx/libgdx/issues/3074 , http://www.badlogicgames.com/wordpress/?p=3678 - check your fonts first, it's probable they have some semi-strange values in them.

**Comment by serhii-k** [comment]
Hi @FyiurAmron, thank you for your reply!
I have just tried to simply use the mentioned fixing function this way:
includePaddingInMetrics(mLight.getData());
Where mLight is one of my pre-generated fonts. I hope this was correct... But both issues still remain.
I will have more time tomorrow to see into these solutions. And also I will check other fonts. However, I'm not sure this is something appropriate for the 2nd issue -- a label is rendered perfectly till it's placed into a resized cell. So, I've done a simple workaround for this issue -- to place my Labels into additional Containers.
Anyway, thank you for your recommendation!

**Comment by serhii-k** [comment]
Well, I've tested with these fonts:
* Arial
* Verdana
* Times New Roman
* Georgia
* Roboto-Thin

Both issues appear for all of them. So, I don't think they are related to a specific font.

**Comment by FyiurAmron** [comment]
@serhii-k to be more precise: by "check your fonts" I meant you should check the fonts (i.e. the resulting data structures) *generated* by your calls to FreeTypeFontGenerator. If there's a discrepancy in font rendering engine, tracking the font's data structs all the way from the beginning in FTFG is usually the best way to go.

Using libGDX's reference Arial font (in the bitmap version) is a good way to start debugging it. IMO if you can repro this bug with reference libGDX's Arial - we've a bug in font rendering. If not, we've a bug in FTFGen. BTW always try to reduce the dependency on external assets while reporting bugs - by minimizing the amount & complexity of data needed to repro the bug, the amount of code which needs to be analyzed to track the bug gets reduced.

**Comment by qzole** [comment]
I think I bumped into this issue too, at least the artifacts were similar with libgdx 1.7.1, what I did was different:
Generate a BitmapFont with FreeTypeFontGenerator (some fonts I used: LiberationSans-bold and Windows 10 system font arialbd) with size 48.
Render some text with the generated font, for example: "Game Over", "512", "256", "8"
Some of the characters are cut off and seems like they are misplaced a few pixels (like the top of G is cut off, and it's higher then the rest "ame").
This problem didn't occurred when using size 64, and for size 32 some fonts looked good while some fonts had errors.
With libgdx 1.5.2, I haven't seen any error with these generated fonts.
I'll fiddle with it a bit and I'll post an example code later today or tomorrow.

**Comment by qzole** [comment]
Ok, I found what my problem was, which seems that not directly related to this issue.
`FreeTypeFontGenerator` sets the `integer` boolean of the generated `BitmapFont` to false. I don't know what is the reason for that. When creating the `BitmapFont` directly it is set to true (as it is documented at `usesIntegerPositions`).
This solved my issues with my artifacts, see example code where it is reproduced here: https://github.com/qzole/gdx-font-test

Could it be that the same is happening here? This problem of course only happens if you try to render at a non integer position. I could imagine that without setting the width it could just so happen that everything is put on an integer position?

Tested my problem with 1.5.2, and if I try to put text on a non integer position, I can reproduce my issue (in the previous comment, when I changed version I changed where I rendered my text because `GlyphLayout` was not available.

So it seems that the two issues are not related, but it could be a (better?) workaround to simply set the font's `setUseIntegerPosition` to true.

**Comment by NathanSweet** [comment]
BitmapFont constructs default the `integer` parameter to true when omitted. You're right, FreeTypeFontGenerator doesn't. I don't think `integer` even belongs as a constructor parameter. It isn't needed when loading the font and just blows up the number of convenience constructors needed. I think we should remove the parameter and default `integer` to true. Anyone disagree? It would be a breaking change for those passing `integer` as false, but pretty obvious to fix (call the setter using false).

FreeTypeFontGenerator would then return a font with `integer` true.

**Comment by NathanSweet** [comment]
FreeTypeFontGenerator has been updated to use `integer=true` by default.

Your other issue (1) is by design, fonts now have tighter bounds.

**Comment by serhii-k** [comment]
Guys, thank you very much for resolving this issue!
I have just checked and the fonts are now rendered perfectly!
Thank you!!!!!
