### ISSUE TITLE
Gdx setup not escaping apostrophe in app name

### ISSUE THREAD

**Issue by avianey** [libgdx/libgdx#3496]
... so the android string.xml is in error : Error:(2) Apostrophe not preceded by \ (in name with apo'stro'phe)

**Comment by xoppa** [comment]
Which version are you using. See: https://github.com/libgdx/libgdx/commit/d18ee144ff3c2426cd07094b816ba6465ae691ba

**Comment by avianey** [comment]
The gdx-setup.jar was downloaded the 9 october (same issue with the one downloaded today).
I check the commit but it's not really related... When writing `wasn't me` as an app name in the setup panel, it generates 
```xml
<resources>
    <string name="app_name">wasn't me</string>
</resources>
```
that should be 
```xml
<resources>
    <string name="app_name">wasn\'t me</string>
</resources>
```
