### ISSUE TITLE
ScrollPane without backgroud cause wrong scissor

### ISSUE THREAD

**Issue by leeho0108** [libgdx/libgdx#3499]
when I create a ScrollPane without setup background,the screen result can only see the scrollpane content. so I lockup for why. I found this code in ScrollPane.java(580).It seem is the reson why the result is not right.the code not invoke 
```	
batch.flush() 
```
when scrollpane not setup a backgroup.to workaround this issue,I have to setup a empty background,and it works correct.
```
	if (style.background != null) {
			style.background.draw(batch, 0, 0, getWidth(), getHeight());
			batch.flush();
		}
```

sorry for my english.

**Comment by NathanSweet** [comment]
ScrollPane `draw` calls `applyTransform` which calls `batch.setTransformMatrix` which flushes the batch.

I can't reproduce the problem. Please provide a SSCCE:
http://sscce.org

**Comment by leeho0108** [comment]
I miss something
I forget to notice that: 
I am using `CpuSpriteBatch` instead `SpriteBatch`,so `setTransformMatrix`  not case a `flush` operation.
CpuSpriteBatch only `flush` at switch texture or buffer is full,
so when I using `CpuSpriteBatch` to save drawcalls,scollpane without `background` will case this issue.

**Comment by NathanSweet** [comment]
It seems Batch setTransformMatrix (and other methods?) should not have in the method contract that a flush is performed, since this can't be relied upon for some subclasses. `applyTransform` should explicitly flush the batch.

**Comment by NathanSweet** [comment]
Ah, actually `applyTransform` should not flush, which is the whole point of using CpuSpriteBatch.

Testing UITest with CpuSpriteBatch, I fixed a problem with SplitPane. I don't see a problem with ScrollPane.

**Comment by NathanSweet** [comment]
Think I got it.
