### ISSUE TITLE
AndroidMultiTouchHandler  ACTION_CANCEL issue

### ISSUE THREAD

**Issue by ACrsm** [libgdx/libgdx#3507]
MotionEvent may contain more than one point ACTION_CANCEL？ AndroidMultiTouchHandler only process one。
 
In Android GestureDetector.class
case MotionEvent.ACTION_CANCEL:
            cancel();
            break;

**Comment by badlogic** [comment]
Unclear what the issue is. Will re-open if you can tell us what the problem is and how to reproduce it

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://portobrasilrestaurant.com/insect.php?l>

 

loogie@basicelementdesign.com
