### ISSUE TITLE
Libgdx Fatal JBullet Error, problematic file and frame

### ISSUE THREAD

**Issue by Flame6332** [libgdx/libgdx#3511]
I have recently been using the jbullet extension of libgdx and as I check collision, a fatal error comes up with the frame and stuff:
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000064038a21, pid=58324, tid=55408
#
# JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [gdx-bullet64.dll+0x48a21]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Yousef\Desktop\Java Files\workspace\JBox2D_Workspace-core\assets\hs_err_pid58324.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

The code that seems to cause the failure itself is when i added this simple collision code,

boolean isColliding() {
		
		//creates the 2 coll obj wrappers
		CollisionObjectWrapper co1 = new CollisionObjectWrapper(ballObj);
		CollisionObjectWrapper co2 = new CollisionObjectWrapper(groundObj);
		
		//collision algorithim info
		btCollisionAlgorithmConstructionInfo caci = new btCollisionAlgorithmConstructionInfo();
		//set dispatcher of coll agorithim
		caci.setDispatcher1(collDispatcher);
		
		//create the algorithim
		btCollisionAlgorithm algorithim = new btSphereBoxCollisionAlgorithm(
		//persistent manifold, info,  wrapper 1 and 2, isSwapped
				null, caci, co1.wrapper, co2.wrapper, false
		);
		
		//dispatcher info
		btDispatcherInfo dispatchInfo = new btDispatcherInfo();
		btManifoldResult manifoldResult = new btManifoldResult();
		
		//processing collision (wrap 1 - 2, dispatchInfo, manResult
		algorithim.processCollision(co1.wrapper, co2.wrapper, dispatchInfo, manifoldResult);
		
		boolean r = manifoldResult.getPersistentManifold().getNumContacts() > 0;
		
	manifoldResult.dispose();
        dispatchInfo.dispose();
        algorithim.dispose();
        caci.dispose();
        co1.dispose();
        co2.dispose();
		
	       return r;
		
}

I update this code at 60fps and as soon as collision happens, the fatal error happens

if (!collision) {
	ballY -= .1;
	ball.transform.setTranslation(0, ballY, 0); 	
	ballObj.setWorldTransform(ball.transform);
	collision = isColliding();	
}

This looks like a java problem not a code problem so a fix may be necesary

**Comment by eadle** [comment]
You forgot to pass the collision object wrappers to btManifoldResult when you constructed it.

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md
