### ISSUE TITLE
Touch screen then crash issue

### ISSUE THREAD

**Issue by Twinsens** [libgdx/libgdx#3512]
After play 40-45 minutes when I touch an area of screen app suddenly crash. This report was copy/paste from google play ANR results;

Crash only : Android 4.4
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/matisse3gjv/matisse3g:4.4.2/KOT49H/T532JVU1AOA2:user/release-keys'
Revision: '3'
pid: 2687, tid: 6341, name: Thread-647  >>> GAME.PACKAGE.NAME                                                       <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
    r0 00000000  r1 79d0c1e0  r2 7d518014  r3 0000a020
    r4 7d0ca008  r5 79d0c1e0  r6 7d0ca008  r7 72591eb0
    r8 7d518014  r9 72591ea4  sl 79d0c1e0  fp 78373b24
    ip 7a3a3144  sp 78373ad8  lr 7a391454  pc 7a392278  cpsr 20010010
    d0  0000000000000000  d1  0000000000000000
    d2  000003e800000000  d3  0000000000000014
    d4  fe8000003f000001  d5  000122e800000000
    d6  0000000000000000  d7  00000000000022ec
    d8  000000004e6e6b28  d9  0000032000000500
    d10 4448000000000000  d11 0000000a00000000
    d12 bf800000bca3d70a  d13 3f800000bf800000
    d14 bf80000000000000  d15 4372b48a449c76e7
    d16 000045a798fdce3f  d17 002e00640069006f
    d18 002e006900750067  d19 0061007200470049
    d20 0063006900680070  d21 0066006600750042
    d22 0072005000720065  d23 006300750064006f
    d24 00c300c200c200c1  d25 00c600c500c400c0
    d26 0000000000000000  d27 0000000000000000
    d28 009e009d009c0098  d29 00a0009c009f009e
    d30 00c600c600c600c6  d31 0000000000000000
    scr 2000001a

backtrace:
    #00  pc 0001a278  /data/app-lib/GAME.PACKAGE.NAME-1/libgdx-box2d.so (b2Fixture::CreateProxies(b2BroadPhase*, b2Transform const&)+20)
    #01  pc 00019450  /data/app-lib/GAME.PACKAGE.NAME-1/libgdx-box2d.so (b2Body::SetActive(bool)+80)
    #02  pc 00020d4c  /system/lib/libdvm.so (dvmPlatformInvoke+112)
    #03  pc 00051b47  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+398)
    #04  pc 00000214  /dev/ashmem/dalvik-jit-code-cache (deleted)

code around pc:
    7a392258 e3a03000 e584300c e8bd8070 e92d45f8  
    7a392268 e1a06000 e590000c e1a0a001 e1a08002  
    7a392278 e5903000 e593300c e12fff33 e3500000  
    7a392288 e586001c d8bd85f8 e3a07000 e1a05007  
    7a392298 e596000c e1a03005 e5964018 e1a02008  
    7a3922a8 e590c000 e0844007 e287701c e1a01004  
    7a3922b8 e59cc018 e12fff3c e1a0000a e1a01004  
    7a3922c8 e1a02004 ebffd8ab e596301c e5845014  
    7a3922d8 e2855001 e1530005 e5846010 e5840018  
    7a3922e8 caffffea e8bd85f8 e92d45f8 e1a07000  
    7a3922f8 e590301c e1a08001 e3530000 da00000d  
    7a392308 e3a04000 e3e0a000 e1a05004 e5976018  
    7a392318 e1a00008 e2855001 e0866004 e284401c  
    7a392328 e5961018 ebffd8af e597301c e586a018  
    7a392338 e1530005 cafffff4 e3a03000 e587301c  
    7a392348 e8bd85f8 e92d4ff0 e1a0b001 e590101c  

code around lr:
    7a391434 e2855a19 e2855f76 08bd8070 e280600c  
    7a391444 e1a00004 e1a01005 e1a02006 eb000383  
    7a391454 e5944004 e3540000 1afffff8 e8bd8070  
    7a391464 e5905058 e3540000 e3c33020 e1c030b4  
    7a391474 e2855a19 e2855f76 0a000005 e1a00004  
    7a391484 e1a01005 eb000398 e5944004 e3540000  
    7a391494 1afffff9 e5963070 e3530000 0a000008  
    7a3914a4 e5960058 e593400c e2800a19 e5931004  
    7a3914b4 e2800f76 eb0000df e3540000 e1a03004  
    7a3914c4 1afffff6 e3a03000 e5863070 e8bd8070  
    7a3914d4 e1d020b4 e1a03000 e7e00252 e1500001  
    7a3914e4 012fff1e e3510000 e1a00003 13822010  
    7a3914f4 03c22010 e1c320b4 e3a02000 e5832048  
    7a391504 eafffd78 e92d40f0 e1a04000 e5905008  
    7a391514 e24dd00c e59f01b8 e08f0000 ebfffc81  
    7a391524 e59f01b0 e08f0000 ebfffc7e e59f01a8

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md#using-the-issue-tracker
