### ISSUE TITLE
ParticleEffect isComplete is true on continuous effects if delayTimer >= delay after update

### ISSUE THREAD

**Issue by Xkynar** [libgdx/libgdx#3516]
Lets take into case a continuous ParticleEffect with a single emitter. This is ParticleEffect's "isComplete" method:

public boolean isComplete () {
		for (int i = 0, n = emitters.size; i < n; i++) {
			ParticleEmitter emitter = emitters.get(i);
			if (!emitter.isComplete()) return false;
		}
		return true;
	}

This means that it depends on the emitter's completion. This is ParticleEmitter's "isComplete":

public boolean isComplete () {
		if (delayTimer < delay) return false;
		return durationTimer >= duration && activeCount == 0;
	}

It depends mostly on delayTimer, and if we check the update method of ParticleEmitters:

if (delayTimer < delay) {
			delayTimer += deltaMillis;
		} else { ... }

And this is the way you say we should update particles:

for (int i = effects.size - 1; i >= 0; i--) {
    PooledEffect effect = effects.get(i);
    effect.draw(batch, delta);
    if (effect.isComplete()) {
        effect.free();
        effects.removeIndex(i);
    }
}

What can and will happen (it happened to me) is that, after the update, in the random case in which "delayTimer += deltaMillis;" will be greater or equal than delay, isComplete will return true, even if the effect is continuous, and if we free/remove all particles which are complete just like in the cycle above, we will end up removing random continuous effects that should not be removed.

**Comment by NathanSweet** [comment]
Please suggest a fix/PR (preferred) or provide a way to reproduce the problem, else we have to try fixing it blindly which is error prone.

**Comment by Xkynar** [comment]
The fix is very simple, an emitter should take into account its "complete" flag when asked if it is complete..

public boolean isComplete () {
//ADD THIS
if(continuous) return false;

if (delayTimer < delay) return false;
return durationTimer >= duration && activeCount == 0;
}

A continuous emitter should never be complete. It is a simple check, much safer than just checking for the delay timers.

As for the reproduction of the bug, as I said, it only happens in the particular case in which you are removing the "complete" particleeffects after their update. the "isComplete" check is flawed, and if durationTimer ends up being >= than duration after the update, isComplete will return true before the next update cycle has a chance to reset "delayTimer" (because of the effect's continous flag).

In my case, i had a permanent effect in my game and it just disappeared randomly, after some time.
When i made a proper isComplete check, taking into account the emitters' continous flag manually, it was ok, but that should really be unecessary, since isComplete should NEVER return true on a continuous effect.

**Comment by dkoding** [comment]
This breaks allowCompletion and memory management for particle effects.
After this 'fix' it is impossible to use pooling for particle effects.
Before you could do like this:

onDeath() {
   particleEffect.allowCompletion(); // Effect is continuous
}

Then, in a cleanup-method:

   private void updateEffects(float deltaTime, PooledLinkedList<ParticleEffectPool.PooledEffect> effects) {
        effects.iter();
        ParticleEffectPool.PooledEffect effect = effects.next();

        while (effect != null) {
            if (effect.isComplete()) {
                effect.free();
                effects.remove();
            } else {
                effect.update(deltaTime);
            }
            effect = effects.next();
        }
    }

This is no longer possible. How can I see if a continuous particle effect is ready for return to the particle effect pool now?

**Comment by rafaskb** [comment]
According to this change, the documentation for ParticleEmitter#allowCompletion() should be changed: 

> Ignores the continuous setting until the emitter is started again. This allows the emitter to stop smoothly.
