### ISSUE TITLE
[FreeTypeFontGenerator] missing chars on font size above 200

### ISSUE THREAD

**Issue by JFixby** [libgdx/libgdx#3525]
Example code
```
FreeTypeFontGenerator generator = new FreeTypeFontGenerator(gdx_font_file);
FreeTypeFontParameter parameter = new FreeTypeFontParameter();
parameter.size = 210;
parameter.flip = true;
parameter.magFilter = TextureFilter.Linear;
parameter.minFilter = TextureFilter.Linear;
parameter.characters = requiredCharacters;
gdx_font = generator.generateFont(parameter);
```

Output for size = 200:
![font200](https://cloud.githubusercontent.com/assets/1580663/10865487/47926d1c-800d-11e5-8cb5-a6e767c634cc.jpg)

Output for size = 210:
![font210](https://cloud.githubusercontent.com/assets/1580663/10865491/54c1e7ce-800d-11e5-8765-91a6551e9b91.jpg)

**Comment by Darkyenus** [comment]
I would guess that they simply don't fit on the texture page, try bigger textures.

**Comment by JFixby** [comment]
How can I do that?

**Comment by JFixby** [comment]
Setting ```FreeTypeFontGenerator.setMaxTextureSize(FreeTypeFontGenerator.NO_MAXIMUM);``` expands the limit and now it breaks on size above 480:

![font481](https://cloud.githubusercontent.com/assets/1580663/10865588/3a945ffa-8010-11e5-90af-88a9dc021cbb.jpg)

Taking everything into account it is fine, but I would suggest throwing some exception about aggressive input.

**Comment by Darkyenus** [comment]
Well, it is assumed that nobody uses fonts this crazy big. But at least a warning would be nice I guess. But not an exception, it is better to work with missing glyphs than crash.

**Comment by JFixby** [comment]
Also, 
FreeTypeFontGenerator  throws ```com.badlogic.gdx.utils.GdxRuntimeException: No cap character found in font``` when parameter size <=1

**Comment by JFixby** [comment]
I prefer hard crash during development and silent warning in production phase.

**Comment by badlogic** [comment]
Changing thag could potentially break existing apps, i'd rather not throw exceptions.

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://KLICOLORS.COM/pretend.php?4y58>

 

loogie@basicelementdesign.com
