### ISSUE TITLE
Input.Keys.BACK and Input.Keys.MENU conflict

### ISSUE THREAD

**Issue by collinsmith** [libgdx/libgdx#3529]
My device that I test using is a *Galaxy Note 5*, and on this device, the hardware **BACK** and **MENU** buttons are the same, e.g., tap = **BACK**, short hold = **MENU**. The issue that I am experiencing is that I am trying to catch the **MENU** key press to open the menu, and the **BACK** key press to exit the application. The behavior in this case is that the application exits once the **BACK** key is pressed, even though my intention is to perform a short press on the hardware button to actually call the **MENU** key.

I've already looked through the documentation and tried a few tricks using *Input.isKeyPressed(int)* and *Input.isKeyJustPressed(int)*, however I have not had success. Does anyone have any ideas on how to resolve this issue? My current thoughts would be to impose some delay on the catching of the **BACK** key until I can be sure the user did not intend to select the **MENU** key instead.

**Comment by MobiDevelop** [comment]
Please use the forum or irc for questions.

**Comment by collinsmith** [comment]
I believe this is a bug related to how the back button press is caught, as no native android apps have this behavior. That's why I created this issue

**Comment by xoppa** [comment]
Please include the required information to reproduce the issue you're reporting and the steps you took to verify that it is indeed an issue of libgdx.

**Comment by MobiDevelop** [comment]
If you think there is a bug, please fix it and submit a pull request. Since you have the device in question, you are an ideal candidate for debugging it. 

Overloaded back buttons are not the norm in Android, so perhaps look into Samsung developer documentation for how they suggest to support their behavior.

**Comment by collinsmith** [comment]
Will do
