### ISSUE TITLE
add support for global audio volumes

### ISSUE THREAD

**Issue by collinsmith** [libgdx/libgdx#3533]
I was looking through the API, and while there are some methods for setting the volume of a sound effect when it is played (or in the case of music, while it is playing), there does not seem to be a globalized audio manager with methods for *setSoundVolume(float)* or *setMusicVolume(float)* which would take effect across all sounds and persist as the default for new sounds (i.e., this setting would be default and overridden by sound, or applied on top of the sound, so if global sound volume is *0.5f* and the sound is played at *0.5f*, the audio would play at *0.25f*).

My current implementation to add similar functionality is becoming overly verbose, and I feel like this feature would greatly easy the production of more robust audio. In the meantime as a workaround, I am attempting to use a wrapper to create all of the audio objects and manage their volume levels.

Is my use-case intended to be accomplished with using a custom *AudioDevice*? If so, is there a way to plug that *AudioDevice* into *Gdx.audio* as the default audio device?

**Comment by Tom-Ski** [comment]
This has been discussed before on here in part #3279. It's a tough one as everyone usually has their own way of handling their game audio.  I'd suggest not touching any of the underlying interfaces and create a thin manager. 

Most people already do this, but it might be useful to have a default manager for people to be able to:

* Register the sounds/music clips they want to play with an id
* Register the sounds/music clips to groups that can have volume/pan tweaked for entire group
 * Useful for Location based sounds
 * useful for sfx vs game music vs UI audio etc
* Register default properties for each specific clip for mixing at runtime (pan/loop/volume)
* Have a global volume setting that would have an effect on all clips played through the manager

**Comment by collinsmith** [comment]
@Tom-Ski Alright, I was thinking of a thin manager as well, and that's what I'm creating right now. I completely agree though, implementation will differ depending on the use-case. Thanks again for your input!

**Comment by collinsmith** [comment]
I would like to re-open this as a feature request. I am trying to implement a customized loader for MusicLoader and SoundLoader and I think it would be beneficial to have at least protected access to the currently loaded Sound/Music object. I would like to grab the created object and keep a reference to it which can then have its volume managed externally. I believe this is the least invasive way of accomplishing this task.

To clarify, I would like to create loaders which extend the references loaders and then set sound and music files to use those instead. I am already overriding those manually, however I believe with protected access to the object references (or a getter method for the object reference) would make it a lot cleaner than basically rewriting the entire class)

Specifically these are the files:

/src/com/badlogic/gdx/assets/loaders/MusicLoader.java
/src/com/badlogic/gdx/assets/loaders/SoundLoader.java

**Comment by Tom-Ski** [comment]
Pull request welcome, although do it on another issue as these aren't related.

**Comment by collinsmith** [comment]
@Tom-Ski Gladly, thanks!

**Comment by badlogic** [comment]
You can replace loaders, so wrap the existing loaders in custom loaders
that retain the references on load.
