### ISSUE TITLE
Remove GdxRuntimeException from AssetManager.unload(String) or add a new function

### ISSUE THREAD

**Issue by collinsmith** [libgdx/libgdx#3544]
I would be interested in adding an additional method to the AssetManager class which will unload an asset if it exists and will not throw an error otherwise. *AssetManager.tryUnload(String)* would increase the usability of LibGdx by allowing users to unload assets without needing to worry about whether or not the asset was loaded when the unload action takes place.

Currently attempting to unload an asset which is not loaded will throw a *GdxRuntimeException*, and a workaround for this behavior is to simply check if the asset is loaded via *AssetManager.isLoaded(String)* before unloading, however I believe this to be overly verbose for the most common case (when the developer knows an asset is loaded) and *AssetManager.unload* should not throw this exception in the first place. If an asset is not loaded, then why would we care that explicitly unloading it did not work? Alternatively, if that information is valuable to users, then perhaps a boolean return of whether or not the asset existed would be acceptable.

**Comment by xoppa** [comment]
Trying to unload something that you haven't loaded might result in unwanted behavior since they're ref counted. It sounds like you're trying to solve the wrong problem. Please provide a valid use-case for when you would like to unload something that you haven't loaded.

**Comment by collinsmith** [comment]
In my use-case, I was disposing of a Music asset during its onCompletion event, and additionally when the parent container was disposed (i.e., Whichever comes first). The unload call in the container's dispose event was throwing the exception

**Comment by xoppa** [comment]
Yeah that sounds like you're trying to solve the wrong problem, you should fix your code instead. Imagine what would happen if you have two of those cases using the same asset. Better throw an exception instead of to rely on a race condition. Closing this. Please use the forum or IRC if you need help using the API.
