### ISSUE TITLE
TooltipManager

### ISSUE THREAD

**Issue by TaiVuong** [libgdx/libgdx#3545]
Tooltip always wrong position with "Timer.schedule(showTask, time)" (position = old position if touch down)
and true with "showTask.run()"

**Comment by NathanSweet** [comment]
I don't understand, sorry. Please show an [example](https://github.com/libgdx/libgdx/wiki/Getting-Help#executable-example-code).

**Comment by TaiVuong** [comment]
same as https://github.com/libgdx/libgdx/issues/3538
tooltipManager.initialTime = 0  --> tooltip show at tooltipManager.offset (right)
tooltipManager.initialTime = 2  --> tooltip show at enter point (wrong)

**Comment by NathanSweet** [comment]
Describing the problem and showing a video is nice, but I need example code that shows the problem.
"""
No matter what, an executable example has to be written to properly test, fix, and verify the fix. If you can't debug and fix the problem yourself, you can still help by providing the executable example.
"""
https://github.com/libgdx/libgdx/wiki/Getting-Help#executable-example-code
