### ISSUE TITLE
Android backend getNativeOrientation()

### ISSUE THREAD

**Issue by Bazylot** [libgdx/libgdx#3548]
Hi, i am trying to handle screen orientation change in my app and i use Gdx.input.getNativeOrientation(). No matter what orientation the device is getNativeOrientation() method returns always Orientation.Portrait orientation. I looked into sources and i am pretty sure the condition that resolves orientation used in constructor at line 173 of AndroidInput.java is broken.
There is:
if (((rotation == 0 || rotation == 180) && (mode.width >= mode.height))
    || ((rotation == 90 || rotation == 270) && (mode.width <= mode.height))) {
        nativeOrientation = Orientation.Landscape;
    } else {
        nativeOrientation = Orientation.Portrait;
}
but should be something like:
if (rotation == 0 || rotation == 180){
    nativeOrientation = Orientation.Landscape;
}else if (rotation == 90 || rotation == 270){
    nativeOrientation = Orientation.Portrait;
}else{
    //default orientation, for example
    nativeOrientation = Orientation.Portrait;
    or initialize it at member level to make it sure it's initialized and screw this 'else'
}

**Comment by MobiDevelop** [comment]
Native orientation is the natural orientation of the device. For phones it is typically portrait, for tablets it is typically landscape. It doesn't really have anything to do with the current orientation of the device.

**Comment by Bazylot** [comment]
ok, my bad ;) i misunderstood the name of method. Not a bug!
