### ISSUE TITLE
Add a speed value to Music

### ISSUE THREAD

**Issue by Voltasalt** [libgdx/libgdx#3555]
It could be useful to slow down or speed up a music track, as well as pitch shift, perhaps?

**Comment by Voltasalt** [comment]
I've found using reflection to set the sampleRate field in OpenALMusic to a lower value sort of works, but the sound jitters (as does the getPosition() value).

**Comment by badlogic** [comment]
This is unlikley to happen, as implementing it for all platforms is currently impossible.

**Comment by ciction** [comment]
https://stackoverflow.com/questions/26567686/libgdx-change-pitch-in-music

**Comment by mwhiter** [comment]
For folks in the future encountering this, if you have a use case where the speed change is well-known and not dynamic, you can implement something similar by doing the following:
1. Calculating the duration of the original and sped up music tracks
2. When switching to the sped up version, calculate the current percent of the original track (e.g. I'm 30% through of the track), then switch to the sped up version and setting the position to 30% of the sped up track.

This creates the illusion of tempo change without having to dynamically change this yourself.

Get the duration here: https://stackoverflow.com/a/3009973

Calculate the position here:
```
fun setPositionPercent(p: Float) {
    val percent = if (p <= 0f) 0f else if (p >= 1f) 1f else p
    val position = percent * duration
    music.position = position
  }
```

And then swap music tracks as necessary
