### ISSUE TITLE
ScrollPane#setScrollbarsOnTop does not work on not fade scrollbars

### ISSUE THREAD

**Issue by yagodar** [libgdx/libgdx#3558]
Hello! There is problem with `ScrollPane#setScrollbarsOnTop`.

I use following code:
``` java
Table widget = new Table();
widget.defaults().expandX().width(800).pad(10);

ScrollPane.ScrollPaneStyle scrollPaneStyle = //default libgdx style;
scrollPaneStyle.vScroll = null;

ScrollPane scrollPane = new ScrollPane(widget, scrollPaneStyle);
scrollPane.setOverscroll(false, false);
scrollPane.setFadeScrollBars(false);
scrollPane.setScrollbarsOnTop(true);

Container container = new Container();
container.align(Align.bottom);
container.fillX();
container.setActor(scrollPane);

Table table = new Table();
table.defaults().width(800);
table.add(/*some another container*/).height(300);
table.row();
table.add(container).height(100);

widget.add(/*label*/).width(/*width*/).align(/*align*/);
widget.row();
...
widget.add(/*label*/).width(/*width*/).align(/*align*/);
widget.row();
```

The problem is - scrollbars still drawing **not** on top of widget.

**But** if i set this `scrollPane.setFadeScrollBars(true)` - all works as expected.

**Comment by MobiDevelop** [comment]
Using [ScrollPaneScrollBarsTest](https://github.com/libgdx/libgdx/blob/master/tests/gdx-tests/src/com/badlogic/gdx/tests/ScrollPaneScrollBarsTest.java) to test, it appears to be working correctly. Please provide a proper [SSCCE](http://sscce.org/) which shows the issue.

**Comment by yagodar** [comment]
I test again using [ScrollPaneScrollBarsTest](https://github.com/libgdx/libgdx/blob/master/tests/gdx-tests/src/com/badlogic/gdx/tests/ScrollPaneScrollBarsTest.java).

And I found the difference. Yes, in case `fade=false`, `onTop=true`, it draws on top, **but not at the edges**. Then `fade=true`, it draws on top **also at the edges**. 
I try to explain this via images (pay attention to the *TOP-LEFT*).

1) `fade=true`, `onTop` - unessesary, draws on top **also at the edges**.
![image](https://cloud.githubusercontent.com/assets/1713346/11148722/8c8f2596-8a2f-11e5-8ea0-eed8a025ebb5.png)

2)`fade=false`, `onTop=true`, draws on top, **but not at the edges**.
![image](https://cloud.githubusercontent.com/assets/1713346/11148757/c2c57a84-8a2f-11e5-8343-6427a4d6d883.png)

Best wishes!

**Comment by MobiDevelop** [comment]
So the issue you are reporting is that the when the scrollbars are at top or left, the contained widget is offset so that you can actually see it? This seems like it would be desired behavior. Why would you want to obscure part of the widget in a way that the user could not scroll to see it?

**Comment by yagodar** [comment]
Ok, i see, it would be desired behaivor. Thank you for your reply, @MobiDevelop. I gess issue should be closed.
