### ISSUE TITLE
creating a FrameBuffer with stencil and depth attachments causes a crash on Linux/GeForce GTX 970

### ISSUE THREAD

**Issue by nstolpe** [libgdx/libgdx#3561]
This is a similar issue to https://github.com/libgdx/libgdx/issues/3422

When creating a FrameBuffer with both depth and stencil buffers on my Linux desktop with a GeForce GTX 970, [line 183 of GLFrameBuffer] (https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/glutils/GLFrameBuffer.java#L183) returns GL_FRAMEBUFFER_UNSUPPORTED.

To test the validity of this, I modified [line 186] (https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/glutils/GLFrameBuffer.java#L186) to:

`&& (Gdx.graphics.supportsExtension("GL_OES_packed_depth_stencil") || Gdx.graphics.supportsExtension("GL_EXT_packed_depth_stencil"))) {`

The crash does not happen and the FrameBuffer is created when using the altered version of GLFrameBuffer.

I've tested the stencil buffer by running my stencil code inside of it and then rendering the FB texture with a SpriteBatch and received the same screen output as I do when not using the FB, so it seems to be a valid fix.

**Comment by realitix** [comment]
Good catch, what do you think about it @xoppa ?

**Comment by xoppa** [comment]
Looks good. Would it be possible to send a PR for this?

**Comment by realitix** [comment]
@nstolpe Do you want to create PR for this ? If not I can do it.

**Comment by nstolpe** [comment]
Hey, thanks guys. I hadn't been able to monitor this for the past week, sorry I missed doing the PR.
