### ISSUE TITLE
Reducing the size of the repo with BFG?

### ISSUE THREAD

**Issue by JesseTG** [libgdx/libgdx#3565]
I know that the Git repo for libgdx is huge due to historical reasons (it used to have binaries included).  There's a tool for removing files from old commits, though, called [BFG](https://rtyley.github.io/bfg-repo-cleaner/).  It's supposed to be far easier to use than Git's built-in tools for cleaning up history.  Has anyone looked into that?

**Comment by Darkyenus** [comment]
I have always used `--depth` flag when cloning. It does not solve this problem, but it is a good workaround.

**Comment by FyiurAmron** [comment]
Frankly, what *I* would like to see would be - instead of BFG (although it's very neat) - simply *libGDX 2 * with fresh repo and reduced legacy content... as soon as the development state of libGDX is stable/grown enough to warrant naming it "2" *chuckle*.

**Comment by badlogic** [comment]
There shall never be a 2.0 :p

I don't want to kill the history, including the binaries. Let's call the
reasons "personal". Check out at depth 1 is the best we can do, i think the
repo should otherwise be clean of large binaries, except for test assets.

**Comment by anubiann00b** [comment]
@badlogic Are you still of the same opinion on this? A 1gb repository is pretty ridiculous...
