### ISSUE TITLE
2d-particle ui problem

### ISSUE THREAD

**Issue by LynkLin** [libgdx/libgdx#3571]
I can not see effect emitters at left-bottom when run the 2D-particles, please fix the bug. 
I use MAC OS.
<img width="1112" alt="particle editor" src="https://cloud.githubusercontent.com/assets/3417659/11205205/d79f2bb2-8d40-11e5-8d4d-f5cd84c24e82.png">

**Comment by MobiDevelop** [comment]
Duplicate of #3008.
