### ISSUE TITLE
"Deprecated Carbon Component Manager" on OS X El Capitan

### ISSUE THREAD

**Issue by IKIGames** [libgdx/libgdx#3572]
Hello! After updating to OS X El Capitan I'm seeing the following warning when launching LibGDX games:

"WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h."

This is an OpenAL-Soft issue, [which has already been fixed](https://github.com/kcat/openal-soft/issues/20). According to [this thread in LWJGL forums](http://forum.lwjgl.org/index.php?topic=5994.0), for updating LWJGL2 apps "it should just be matter of dropping the latest openal-soft natives (which you can grab them from the nightly builds of LWJGL3) over the old natives". But I'm not sure if that applies to LibGDX apps too. 

Notice that the current nightly build of LWJGL does not include the updated OpenAL-Soft library (yet.)

**Comment by badlogic** [comment]
LWJGL needs to release this to Maven Central so we can consume it.

**Comment by NagiQ** [comment]
OK. Meanwhile, I tried the following:
1. Download latest LWJGL3 build.
2. Grab native libopenal.dylib and drop file over native openal lib currently packed with LibGDX.
3. Warning should be gone.
liblwjgl.dylib is fine, no need to mess with it.

**Comment by AndyBarron** [comment]
I'm also getting this warning message. Any ETA on a fix? :smiley:

**Comment by NagiQ** [comment]
A caveat: don't use the OpenAL bundled with LWJGL3 if you need support for OS X < 10.9. Compile it yourself.

**Comment by sarith** [comment]
LWJGL 2 will probably never get these new versions of the openal-soft natives, for supporting older projects and for lack of further development on LWJGL 2.  I'm mostly speculating, but I think my assumption is probably correct.  

If/when newer versions of OS X drop support for the older Carbon Component Manager, LWJGL 2 functionality (and therefore libgdx) will probably go with it  :(  Unless libgdx upgrades to LWJGL 3 at some point in the future.

**Comment by badlogic** [comment]
libGDX has LWJGL3 support

**Comment by badlogic** [comment]
No fix for LWJGL2 will come, and it's working with LWJGL3. Closing.
