### ISSUE TITLE
Sprite vertex winding is not counter clockwise

### ISSUE THREAD

**Issue by xoppa** [libgdx/libgdx#3577]
I just noticed that unlike [what the comment says](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g2d/SpriteBatch.java#L253), the vertex winding is not counter clockwise. If you look at the code, you'll see that it starts at the bottom left (`fx, fy`), then to the top left (`fx, fy + height`) and then to the top right (`fx + width, fy + height`), and so on. This will cause everything to be culled when back face culling is enabled. It is easy to reproduce, in any of the tests enable backface culling:

``` java
Gdx.gl.glEnable(GL20.GL_CULL_FACE);
```

Either switching to frontface culling (`Gdx.gl.glCullFace(GL20.GL_FRONT);`) or switching to clockwise winding (`Gdx.gl.glFrontFace(GL20.GL_CW);`) will make it appear again.

I noticed this when using the vertices of the `Sprite` class (to benefit from `AtlasSprite`) as base for a 3d surface. So it is not only `SpriteBatch`.

Although easy to fix, I'm not sure what the impact of it would be.

**Comment by NathanSweet** [comment]
Yeah it's always been backward. Keeps you 3D guys on your toes! I wouldn't mind seeing it fixed. Maybe it would be a good time to also make Sprite not extend TextureRegion.

**Comment by cypherdare** [comment]
I still remember this gotcha from when I started using Libgdx five years ago. I think I was mixing 2D and 3D and couldn't figure out why my sprites weren't drawing.

**Comment by badlogic** [comment]
Don't see this happening :)

**Comment by NathanSweet** [comment]
That's the spirit!
