### ISSUE TITLE
Gdx class has static reference to Activity

### ISSUE THREAD

**Issue by vashisthg** [libgdx/libgdx#3579]
Hey guys, 
I see that onCreate and onResume of AndroidApplication https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplication.java#L164 the instance of current activity is saved as a static field in Gdx class. 

This would be causing a memory leak. I couldn't find any issues in issue tracker regarding this. 

Should we remove the reference in onDestroy/orPause ourselves?

**Comment by xoppa** [comment]
Please include the [sscce](http://sscce.org) showing the issue you're reporting. https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md

**Comment by vashisthg** [comment]
Actually I am using many android 'Activity's in the app. One of the activity contains the game and so it extends AndroidApplication. Other Activities contains native android UI. 

When the game activity finishes, then because of the static reference, it leaks. 

One can confirm this by using LeakCanary https://github.com/square/leakcanary or by creating hprof file and observing it. 

Should I create a hprof and upload it here?

**Comment by Pedramrn** [comment]
I have the same issue, here is the heap trace file to GC_ROOT.[heap_trace.txt](https://github.com/libgdx/libgdx/files/48514/heap_trace.txt)

It refers to 
`static com.badlogic.gdx.Gdx.input`
refrences to 
`com.badlogic.gdx.backends.android.AndroidInputThreePlus.context`
which cause to leak
`com.myapp.MainActivity` instance.

I'm using it in a fragment.

**Comment by Pedramrn** [comment]
hey @vashisthg  any news on that?

**Comment by gaurav-fueled** [comment]
@Pedramrn The leak is due to static reference to the activity. cc @xoppa

**Comment by Pedramrn** [comment]
@gaurav-fueled yes the tittle states that for sure, I was trying to show the issue as @xoppa requested **sscce** standard.

**Comment by MobiDevelop** [comment]
This is something we should look into. I'm not sure where exactly we should unset the Gdx static members, probably not in pause, possibly in stop or destroy.

**Comment by Pedramrn** [comment]
@MobiDevelop Using a `WeakReferecne` is an option here. It reliefs you from manually removing the references to any `Context` or `Activity` instances. Also if you need only a `Context` consider useing `ApplicationContext` if possible. You can get one with calling `getApplicationContext()` on any instances of `Context` or `Activity`.

**Comment by MobiDevelop** [comment]
I think we just need to determine where the correct place to perform clean up is.

**Comment by ragdroid** [comment]
I am getting similar leaks by using https://github.com/square/leakcanary

Listing a few more:
 - `com.badlogic.gdx.scenes.scene2d.ui.Cell` has a private static variable `app`
 -  `com.badlogic.gdx.graphics.glutils.ShaderProgram.shaders` has a private static Map `shaders` which causes leaks

**Comment by MobiDevelop** [comment]
The Cell class (and a few others) has no reference to the app as of version 1.7.2.

**Comment by JFixby** [comment]
https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/glutils/ShaderProgram.java#L705

While destroying the activity gdx fails to remove old app instance from the ```shaders``` regestry keeping static reference alive. For some reason the dispose() method receives a link to the new app instead of the old one that should be removed.

More details on that: https://github.com/libgdx/libgdx/issues/3951

**Comment by Tom-Ski** [comment]
Should be resolved now.

**Comment by ilyaklyukin** [comment]
Actually, static field Gdx.app still keeps reference to activity - and LeakCanary reports a leak here.. Why closed? (v.1.9.6)
