### ISSUE TITLE
Set up a LibGDX project on a flash-drive or on GitHub with dependencies?

### ISSUE THREAD

**Issue by AMPBEdu** [libgdx/libgdx#3588]
Is there any way to setup an eclipse project on a flash drive or on GitHub that i can easily just import from any eclipse on any computer with dependencies already packaged so I don't have to download them again?

I can't find any documentation or tutorials on how to do this.

**Comment by Tom-Ski** [comment]
I have a branch on my fork which does this, its the relative branch and it will pull in the dependencies and make them local to the project, allowing you to use your project from a USB. Note that it's specific to eclipse, and you lose gradle ide features this way.

----- Reply message -----

**Comment by xGnoSiSx** [comment]
Gradle was added for dependency management among other things. Moving away from dependency management invites trouble on many levels.

I don't know if there is a way to 'migrate' the gradle dependency cache from an installation to another machine. Perhaps you should set up your own artifact repository and draw from there?

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
