### ISSUE TITLE
Performance regression in VertexBufferObjectWithVAO

### ISSUE THREAD

**Issue by code-disaster** [libgdx/libgdx#3593]
For now I just want to document this, as I don't have an idea yet how to resolve this in a nice way, and without breaking the VertexData interface.

Issue caused by  #3050, #3051

When using VertexBufferObjectWithVAO / GL30, vertex buffer and vertex attributes bindings are redone each VertexBufferObjectWithVAO.bind() call. I'm not sure about the actual performance hit on current desktop GPUs, but it causes a lot of unnecessary GL calls.

**Comment by code-disaster** [comment]
Example for rendering a static mesh, powered by 'apitrace' - all of those calls except the glBindVertexArray() should not be needed.
<img width="389" alt="screen shot 2015-11-23 at 16 18 21" src="https://cloud.githubusercontent.com/assets/4644167/11340657/348e40e8-91ff-11e5-9e20-9918d0f72dcb.png">

**Comment by xoppa** [comment]
If that is an issue, then it is not an issue specifically to VertexBufferObjectWithVAO. VertexArray and VertexBufferObject do that as well. I don't see how to "fix" this without a lot of context bookkeeping though. This is not specific to mesh, there are other places where this would solve redundant gl calls. However, I'm not convinced that is worth it. Perhaps you can profile it so we know what we're talking about?

**Comment by code-disaster** [comment]
The VAO is meant to be that "context bookkeeping" object. "Intended" use of VAO would assume that both vertex buffer and attribute bindings don't ever change after creation, but the current interface does not enforce anything like that.

You are right that it probably won't be worth the extra work to change every implementation of VertexData, but there still might be some potential for uses of VertexBufferObjectWithVAO, which might get even more interesting with GLES 3.

I'm currently doing an experiment by writing a slim replacement just for our use of VertexBufferObjectWithVAO. I'll have a look at performance gains, though they might not be as big yet. I'm not batching as much as I should, but still use a lot of small buffers.

**Comment by code-disaster** [comment]
Ok, with my current test scenario, the change reduces the number of GL function calls by ~40%, and increases fps by ~10%. As said, that's with rendering *a lot* of small buffers, so the gain will probably much less when reducing render calls.

**Comment by xoppa** [comment]
Ow, didnt know that, haven't had the chance to play with that kind of optimizations on gles 3 that much yet. Can you link to the spec that defines that? I guess that means that the issue is that VAO is intended to bound to a specific shader, which conflicts with the current setup where meshes are rendered by multiple shaders?

**Comment by code-disaster** [comment]
It's intended to be bound to a VBO(*) and a certain set of vertex layout/locations. The VAO is just a state block for vertex attributes and locations. Goal is to rebind the whole block just by calling glBindVertexArray().

Multiple shaders would be no problem as long as they do not change vertex locations, but this isn't verified by the current API. I can only assume that's been the issue leading to #3051.

(*) actually not true but highly misleading thanks to the usual quality of GL documentation. That stuff is *confusing* at best:
https://www.opengl.org/wiki/Vertex_Specification#Vertex_Array_Object

**Comment by xoppa** [comment]
Ok, cool. I think it would be fine to cache the locations in a private final int array to cache them. Also, it looks like the `glBindVertexArray` should be moved out of the branch. And the `glIsVertexArray` call looks like it might be superfluous. I highly doubt that `invalidate()` is ever going to be called, but if it is, then perhaps might as well call `glGenVertexArrays` right away instead of checking each bind call.

If we change this, then it probably would be a good idea to have a test for it though. Perhaps you can have a look at it? I'm afraid I wont have the time before the weekend.

**Comment by code-disaster** [comment]
Current status: https://github.com/code-disaster/libgdx/commit/9055982decf5119f84b21851564b2ca1c0d6e939

I can only claim "it's working for us" right now. No GdxTests yet. Working with Eclipse makes me want to smash things.

**Comment by realitix** [comment]
@xoppa This pull request should be reverted #3051 .
Like code-disaster said, binding attributes during VAO creation allows to gain performance.

When I did this pull request, I didn't have my current knowlege ;) Sorry !

**Comment by code-disaster** [comment]
Resolved with #3916.
