### ISSUE TITLE
Optional absolute path to preferences directory

### ISSUE THREAD

**Issue by titovmaxim** [libgdx/libgdx#3602]
Some game portals (like G-Cluster) manage separate directories for game saves for every game / player. They supply the absolute path to the game via their SDK. The problem is that such directory can be outside the user folder. Like "C:\saves\...".

Unfortunately LwjglApplicationcreates an instance of LwjglPreferences using FileType.External. It would be nice to have a config option to supply the desired filetype (either FileType.External, or FileType.Absolute). Otherwise one has to override getPreferences method of LwjglApplication, which is not that nice.

**Comment by NathanSweet** [comment]
Seems reasonable. Want to make a PR? Maybe `getPreferences (FileHandle
file)`? Otherwise you can just write save files yourself, you don't have to
use preferences. `properties.storeToXML` isn't great anyway.
