### ISSUE TITLE
Minor addition to wiki (re: NBAndroid installation)

### ISSUE THREAD

**Issue by mbaranczak** [libgdx/libgdx#3612]
wiki page: https://github.com/libgdx/libgdx/wiki/Setting-up-your-Development-Environment-%28Eclipse%2C-Intellij-IDEA%2C-NetBeans%29

NetBeans 8.1 broke compatibility with NBAndroid. They've just published a separate version for 8.1 - to install it, use this update center URL: http://nbandroid.org/release81/updates/updates.xml . 

Reference: https://bitbucket.org/nbandroid/nbandroid/issues/63/nbandroid-will-not-install-in-netbeans-81

**Comment by MobiDevelop** [comment]
Please just update the wiki, no need to create an issue.

**Comment by mbaranczak** [comment]
Done. Sorry, I hadn't realized the wiki is publicly editable.
