### ISSUE TITLE
Extremely high draw call count when using multiple ParticleEffect's with the same particle image

### ISSUE THREAD

**Issue by joelmeijering** [libgdx/libgdx#3614]
I noticed that my ParticleEffects where taking up most of my game's frame time, they were slowing down my game significantly.

After some openGL tracing I found that manually drawing 2000 sprites each frame with random position, opacity and color with additive blending enabled was no problem on my Nexus 7, and resulted in only 3 glDrawElements calls each frame. I had an FPS of 60.

Strangely, when using 200 ParticleEffect's to draw a total of 2000 sprites per frame (additive) with the same particle sprite and particle file (*.p), the framerate drops to ~30. Per frame around 800 glDrawElements calls were made. FPS was 30.

I think this is due to the fact that every time a ParticleEffect is loaded, a new sprites is created, creating a new texture instance. 

This test hack improved my framerate from 30 to 60:

	public void loadEmitterImages (FileHandle imagesDir) {
		ownsTexture = true;
		HashMap<String, Sprite> loadedSprites = new HashMap<String, Sprite>(emitters.size);
		for (int i = 0, n = emitters.size; i < n; i++) {
			ParticleEmitter emitter = emitters.get(i);
			String imagePath = emitter.getImagePath();
			if (imagePath == null) continue;
			String imageName = new File(imagePath.replace('\\', '/')).getName();
			Sprite sprite = loadedSprites.get(imageName);
			if (sprite == null) {
				sprite = new Sprite(loadTexture(imagesDir.child(imageName)));
				loadedSprites.put(imageName, sprite);
			}

			emitter.setSprite(sprite);
			
			// Test, reduces draw calls when using multiple emitters with the same particle sprite
			emitter.setSprite(Game.img);
		}
	}

What do you guys think? Should we write a fix for this? I think its just a matter of statically caching any sprite that gets loaded using a particleeffect. Whe we cache this by filename, and reuse instances while loading particleeffects the problem should be gone.

I can upload a demo project that shows the framerate difference if needed.

(Tested using LibGDX 1.7.1 on Android 4.4.4 on Google Nexus 7 2012)

**Comment by xoppa** [comment]
Sounds like something AssetManager should solve. Please include the required information to reproduce the issue.

**Comment by Tom-Ski** [comment]
This should already happen with the `loadedSprites` map, without the nasty staticness. Note you can also supply your particle sprites in an atlas which will save you even more calls.

Please Include a self contained executable example if you still think there is an issue to be solved here.

**Comment by Tom-Ski** [comment]
You are most likely seeing the draw calls because you are using additive blending with your ParticleEffects and not using ParticleEffect's `setEmittersCleanUpBlendFunction` function, which will cause a flush after drawing every emitter.

Please reopen with appropriate code if you think there is something else.

**Comment by joelmeijering** [comment]
@Tom-Ski When using atlasses, the same instance might be used, so you might be right that the problem wont occur in that case.
@Tom-Ski I commented out all the setBlendingMode calls in ParticleEmitter, so this cannot be the case
@xoppa What to do mean by self-contained executable? Wouldn't it be better to have to code so you can see the difference with/without the fix? Here is an Eclipse project: 

The hack is applied to to ParticleEffect.java line 210. Uncomment that line to use see the performance difference. 
Download link to project:
https://www.dropbox.com/s/ibt6g6w69ts2uha/particletest.zip?dl=0

GL Trace without hotfix:
![without](https://cloud.githubusercontent.com/assets/4020092/11539345/e0714a3a-9926-11e5-8c6f-5f90eecbba6a.png)

GL Trace with fix:
![with](https://cloud.githubusercontent.com/assets/4020092/11539414/2dd15b1c-9927-11e5-9d3c-1075f08d1a63.png)

**Comment by Tom-Ski** [comment]
You'll want to use ParticleEffectPool for this, in conjunction with setEmittersCleanUpBlendFunction.

```java
        ParticleEffect particleEffect = new ParticleEffect();
        particleEffect.load(Gdx.files.internal("fire.p"), Gdx.files.internal(""));
        particleEffect.setEmittersCleanUpBlendFunction(false);

        ParticleEffectPool pool = new ParticleEffectPool(particleEffect, 0, 400);

        for(int i = 0; i < 400; i++){
            ParticleEffect pe = pool.obtain();
            Vector2 pos = null;
            if(i == 0){
                pos = new Vector2(50, 650);
            }else{
                pos = new Vector2(50, 6*i);
            }
            pe.getEmitters().first().setPosition(pos.x, pos.y);
            pe.start();
            anis[i] = pe;
        }
```

**Comment by joelmeijering** [comment]
I see, so this only occurs when not using a pool and not calling setEmittersCleanUpBlendFunction(false).

For me the issue is solved, thanks. But still though. Everyone who calls setEmittersCleanUpBlendFunction but does not use a pool will suffer the large call count.

I guess everyone should just use a pool when using more than one ParticleEffect, which makes sense.

**Comment by xGnoSiSx** [comment]
We should stress on the documentation/wiki that you must use pools. There are many caveats like this lying around.

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://newstintuc.info/file.php?p>

 

loogie@basicelementdesign.com

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://ausasolar.com/hate.php?zfvb>

 

loogie@basicelementdesign.com
