### ISSUE TITLE
Gdx.files.internal

### ISSUE THREAD

**Issue by TaiVuong** [libgdx/libgdx#3617]
It too slowly since you support APK expansion.
I load ~100 files in one batch for ~4s with Gdx.files.external  
~240s with internal (normal)
~350s with internal (apk expansion obb)

PS: android only

**Comment by saltares** [comment]
I think we need a [sscce](https://github.com/libgdx/libgdx/wiki/Getting-Help#executable-example-code) for us to be able to consider a solution, which could be:

1. Optimising APK expansion
2. Offer the possibility of disabling it via a [`AndroidApplicationConfiguration`](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/backends/android/AndroidApplicationConfiguration.html) parameter.

**Comment by Tom-Ski** [comment]
@saltares this already happens if you don't actually set the app to use APK expansion.  Internal will lookup internal first, if no internal file is found, it will then search the expansion, if enabled.

**Comment by saltares** [comment]
Then I have said nothing :-).

**Comment by TaiVuong** [comment]
it was faster when I load .obb with ZipFileHandleResolver; but it still slowly if I load it directly from assets/... with Gdx.files.internal (dont use apk expansion file)

**Comment by MobiDevelop** [comment]
You are saying it takes four minutes to open ~100 files from internal? And those same files take only four seconds to open from external storage? That seems highly unlikely.

**Comment by TaiVuong** [comment]
https://github.com/clintbellanger/flare-game/blob/master/mods/alpha_demo/items/items.txt

Double currentTime = System.nanoTime();
open item.txt with Gdx.files.internal(items.txt).read(8192) --> readLine
few lines to link to other files (cloth, amor...)
--> dont close parent --> Gdx.files.internal(cloths.txt).read(8192)--> readLine --> close this
.... ~100 file
close parent.
time = (System.nanoTime() - currentTime)/1000000000.0;

skin.load(Gdx.files.internal("uiskin/uiskin.json")); not slow down

Close this if u want.

**Comment by NathanSweet** [comment]
Every read(8192) allocates a 8192 byte buffer. I'd guess this is what is slow on Android.

**Comment by sarkanyi** [comment]
If no expansion file is set, then Gdx.files.internal works the same way as before. If there is one, then an extra assets.open(path).close(); check is run which shouldn't be that expensive imho. The last time I made tests on it it was the order of a couple thousands nanoseconds/call on my Note 4. Even for 100 files that would be a maximum of 1-4 milliseconds. Do you need to check for existence of directories or non-existing files? Those tend to be slow.

**Comment by NathanSweet** [comment]
I don't understand. What problem are you reporting?

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info

**Comment by TaiVuong** [comment]
@sarkanyi 
```
Do you need to check for existence of directories or non-existing files?
```
That it!

**Comment by sarkanyi** [comment]
Well, normally you shouldn't need to do that, because as the developer you should KNOW what files you have there ;).

**Comment by TaiVuong** [comment]
My game has many mods. each mod may be contain a file "item.txt". I have to check and combine them. Fortunately, APK expansion too good and I just need it.

**Comment by sarkanyi** [comment]
And the mods are at Gdx.files.internal()? Why not a different place Gdx.files.classpath(). I think internal should be used with files that are normally shipped with the game at all times.

**Comment by TaiVuong** [comment]
You're right, I just try to use it because I just want to test it on android with one click, but the result is I lost two days to test. it called laziness :D
