### ISSUE TITLE
LibGDX and Tiled rendering issue black tiles

### ISSUE THREAD

**Issue by bvisonl** [libgdx/libgdx#3621]
I am having issues with Tiled and Libgdx. I am making a scroll platform game and I am trying to make 1 (for now) background that will repeat itself. The main map in Tiled is composed of various images stacked one next to the other, once I fill all the cells that makes up a full background (normal stuff..)

My problem comes with rendering, as you can see in the images below as I move the main character to the right the image suddenly disappears, I know that the tiled renderer is supposed to efficiently render only what you will see but in this case I am still seeing an area that the renderer just stops rendering. 

How can I make the renderer wait until a tile is out of the camera before it stops rendering it?

Images:

[Starting position is like at the middle of the first tile](http://postimg.org/image/cinkcib8t/)

[Almost getting out of the first tile](http://postimg.org/image/ku54jtrpr/)

As for the code I am basically using the code in [this tutorial](https://github.com/libgdx/libgdx/wiki/Tile-maps) since I am currently just testing things out like this:

    public class PlayScreen implements Screen {

    private OrthographicCamera camera;
    private Viewport viewport;

    private World world;
    private Box2DDebugRenderer b2dRenderer;

    // Map

    private TiledMap tiledMap;
    private OrthogonalTiledMapRenderer mapRenderer;

    public PlayScreen(PGame game) {
        this.game = game;
        camera = new OrthographicCamera();
        camera.setToOrtho(false, PGame.V_WIDTH, PGame.V_HEIGHT);       

        viewport = new FitViewport(PGame.V_WIDTH / Constants.PPM, PGame.V_HEIGHT / Constants.PPM, camera);
        camera.position.set(viewport.getWorldWidth() / 4, viewport.getWorldHeight() / 2, 0);

        // No gravity for now..
        world = new World(new Vector2(0, -0*9.81f), true);
        b2dRenderer = new Box2DDebugRenderer();
        
        // create the box of the player seen in the image
        .....

        TmxMapLoader loader = new TmxMapLoader();

        tiledMap = loader.load("backgrounds/1.tmx");
        float unitScale = 1 / 100f;
        mapRenderer = new OrthogonalTiledMapRenderer(tiledMap, unitScale);

    }

    public void update(float delta) {
        
        // handle input to move the b2d body
        .....

        world.step(1 / 60f, 6, 2);

        // Make the camera follow the player
        camera.position.set(player.getPosition());

        camera.update();
    }

    @Override
    public void render(float delta) {
        update(delta);

        Gdx.gl.glClearColor(0, 0, 0, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

        mapRenderer.setView(camera);
        mapRenderer.render();

        b2dRenderer.render(world, camera.combined);

    }

}

**Comment by MobiDevelop** [comment]
You're going to have to provide a bit more information if you want us to be able to help you. Please provide a self contained example (including the tmx, tileset, and complete code usable to reproduce the issue).

**Comment by bvisonl** [comment]
Problem is "solved". I tested out the same code with another map that was made with smaller tilesets, apparently this happens if you have tiles too big. Right now the only issue is that some black lines are appearing but that seems to be that the padding is missing. If anyone experience something like this try with smaller tiles.

**Comment by nhydock** [comment]
Tile sets can not have a resolution greater than 4096x4096.  I found that out the hard way a few years ago when I tried using some tilesets for RPG Maker XP from ![RPG Palace](http://downloads.rpg-palace.com/index.php?cmd=8&page=1) in my game.  It's a limitation of texture buffer memory.

**Comment by MobiDevelop** [comment]
The max size is hardware dependent. If you want to support mobile, you probably want to stick to 2048 as a max size, for maximum compatibility (unless you want to also support low-end devices, then 1024). On the flip side, my laptop supports textures up to 16384.

You just need to decide what you want to support and make your assets conform.
