### ISSUE TITLE
Intersector.pointLineSide returns wrong side

### ISSUE THREAD

**Issue by palador** [libgdx/libgdx#3622]
Sometimes, this function returns a wrong value.
Here's a test with a line and a point. Obviously, the point is on the left side of the line:

```
val start = Vector2(-10f, -20f)
val end = Vector2(+10f, -20f)
val point = Vector2(0f, 0f)
val side = Intersector.pointLineSide(start, end, point)
Assert.assertEquals(side, -1)
```

This snipped is written in Kotlin, but you should get the point (hopefully you do better than this function does :) )

**Comment by palador** [comment]
I've made my function, which works as expected, feel free to use that code.

    fun sidePointLine(from: Vector2, to: Vector2, point: Vector2): Int {
        val distPart = (to.y - from.y) * point.x - (to.x - from.x) * point.y + to.x * from.y - to.y * from.x
        return when {
            distPart isSimilarTo 0f -> 0
            distPart > 0f -> 1
            else -> -1
        }
    }

**Comment by AldousP** [comment]
I also noticed this behavior when working with some Intersection methods over the weekend. I got around it by change the order of the passed in vertices for the line, I agree with the expected behavior being backwards, but I'm curious if there is an unwritten rule regarding the order of points passed in, from an algorithm perspective.

**Comment by intrigus** [comment]
https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/math/Intersector.java#L92-L93

"Left and right are relative to the lines direction which is linePoint1 to linePoint2."

**Comment by palador** [comment]
Yes, changing the order may be a workaround. But the documentation is definitely wrong: When you walk from P1 (0:0) to P2(0:10), P3(-1:10) is on the left side, but 1 is returned which means right according to the documentation. I think just the documentation should be fixed. Otherwise a lot of existing code may broke.
