### ISSUE TITLE
Unable to get real JsonValue ValueType

### ISSUE THREAD

**Issue by nikoliazekter** [libgdx/libgdx#3623]
There are currently these value types:
```java
	public enum ValueType {
		object, array, stringValue, doubleValue, longValue, booleanValue, nullValue
	}
```
Imagine we have these variable:
```java
    int iAmNotLong;
    float iAmNotDouble;
```
`iAmNotLong` has `longValue` type and `iAmNotDouble` has `doubleValue` type. Using this knowledge user might try to assign numbers to these variables that are out of their range. This will cause
```java
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.SerializationException: Unable to convert value to required type: iAmNotLong: 100000000000000000 (int)
```
when deserialized back.

However, since `Json` uses reflection to serialize objects, it's possible to get real primitive types of variables. It would be much better to have `intValue` and `floatValue` in `ValueType`.

**Comment by NathanSweet** [comment]
JsonValue only needs to store long and double, these types can hold all int and float values. Serializing this to JSON and back works fine. If you have bad data in your JSON (or JsonValue) that will cause object serialization (the `Json` class) to fail, then you just shouldn't do that. Eg, a JsonValue may be holding a string value that object serialization will use to look up an enum value. Someone may provide JSON or a JsonValue with a string that is an invalid enum value which would cause object serialization to fail, but I don't think this is a problem that concerns JsonValue.

**Comment by nikoliazekter** [comment]
I'm working on in-game editor wherer user can modify variable values at run-time through UI, something like this 
![Unity](http://docs.unity3d.com/uploads/Main/PropertiesExample.png).
The problem is I can't set proper min and max possible values because I don't know the type of variables. Of course, one possible solution would be to allow only ints and floats (what I'm actually doing right now). But if I ever need to store time or UUID or any other big numbers, my solution wouldn't work properly.

**Comment by intrigus** [comment]
I assume that you use reflection to change the values. 
If you can use reflection, you can also get the type of the value.

I don't understand how your problem is related to json serialisation. 
If you don't know the type of the value, how will your proposed change help?

**Comment by nikoliazekter** [comment]
I don't use reflection to change variables, I use `JsonValue.set()` and deserialize changed JsonValue. It seems like reasonable thing to do because Json gives me convenient object graph.

**Comment by NathanSweet** [comment]
If you are just poking values strings into a JsonValue object graph with `set(String)` then you have no checking for what is valid input. If the user enters "abc" for a number, it's not JsonValue's problem. I thin the right answer is to write application logic to process your values appropriately.
