### ISSUE TITLE
GWT: Don't always return new Application in getApplicationListener()

### ISSUE THREAD

**Issue by intrigus** [libgdx/libgdx#3628]
https://github.com/libgdx/libgdx/blob/master/extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/html/src/HtmlLauncher#L17

Currently, when you call getApplicationListener(), you always get a new Application. I don't think that this is good. Many people rely on the fact that getApplicationListener() returns the AppListener, but NOT a new AppListener every time it's called.

I propose to cache the value, and only create a new AppListener, if the cache is null.

``` 
public class HtmlLauncher extends GwtApplication {
        private ApplicationListener listener;
        @Override
        public GwtApplicationConfiguration getConfig () {
                return new GwtApplicationConfiguration(480, 320);
        }

        @Override
        public ApplicationListener getApplicationListener () {
                if(listener == null) {
                        listener = new %MAIN_CLASS%();
                }
                return listener;         
        }
}
```

**Comment by MobiDevelop** [comment]
Sounds reasonable.

**Comment by MobiDevelop** [comment]
It probably makes sense to add an abstract `createApplicationListener` method to GwtApplication which will be called to create the application listener, and then let `getApplicationListener` just be a getter.
