### ISSUE TITLE
Non-Continuous Rendering CPU

### ISSUE THREAD

**Issue by darkfrog26** [libgdx/libgdx#3629]
I was testing setting continuous rendering to false and noticed that my CPU is still maxed out even though my framerate drops accordingly.  I'm using JGLFW and I have vsync set to false.  This can be reproduced in any project by simply calling:

```java
Gdx.graphics.setContinuousRendering(false)
```

And using the JGLFW renderer with vsync set to false.

**Comment by MobiDevelop** [comment]
Did you set the `foregroundFPS` value on your configuration?

**Comment by nhydock** [comment]
Even if continuous rendering is off, there's still other processes executing each cycle, such as post-render runnables, updating input, and Syncing the application's sleep time to match desired FPS.  While I doubt those are intensive enough to max out the cpu, benchmarking probably should be done to those actions to make sure they're not eating up more CPU than they really need, just to be sure as I don't think anyone has actually done that before.

That said, I am unsure about the level of support for the JGLFW backend.  It always appeared to be more of an experimental backend compared to how much support and usage the LWJGL one gets.  Plus it may just become obsolete when LWJGL 3 come around and backend support is added for that, as LWJGL3 uses GLFW.

**Comment by darkfrog26** [comment]
@nhydock, I agree regarding LWJGL 3, but that presumes they'll ever get 1.0 released and then there will actually be a libgdx backend implemented.

I'll give it a try with LWJGL and see if that changes things.

**Comment by darkfrog26** [comment]
That's strange, I have vSyncEnabled = false, but it's still rendering at 61fps with LWJGL.

**Comment by MobiDevelop** [comment]
On the LWJGL backend the `foregroundFPS` is set to 60 by default. On the JGLFW backend the `foregroundFPS` is set to 0 (effectively unset) by default. You can set both via the respective configuration object.

**Comment by darkfrog26** [comment]
Wow, I set `foregroundFPS = 0` on LWJGL and it's barely using any CPU when `continuousRendering` is `false`.  If I set it to true the FPS goes to 6k like it's supposed to.

Thanks, I guess I'll just switch to LWJGL as my preferred backend, but this should be considered a bug in JGLFW.

**Comment by darkfrog26** [comment]
Definitely a bug when the LWJGL defaults in the config are not the same as the defaults in JGLFW.

**Comment by NathanSweet** [comment]
PRs are welcome.
