### ISSUE TITLE
is it possible to customized the render sequence of Stage

### ISSUE THREAD

**Issue by royrang** [libgdx/libgdx#3631]

**Comment by AldousP** [comment]
As in, what actors are being drawn?

**Comment by royrang** [comment]
Currently, the stage render all its actor in the order which as it is added in the stage if there is no hierarchy.
I may want to change this default order. For example, the order could be depend on the y coordinate or the actor. Is it possible? Thanks.

**Comment by AldousP** [comment]
This sounds like you're referring to the z-index if you're only intent is
to change the order that the actors are drawn/overlap.

**Comment by royrang** [comment]
Ah, yes. something like it.

**Comment by AldousP** [comment]
Every actor has a z index that can be set. You can also group actors together using the group class.

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker

**Comment by xGnoSiSx** [comment]
The z index numbering of each actor is local to the current group. Your main stage is a group.
