### ISSUE TITLE
Intersector method to determine Polygon area of Intersection

### ISSUE THREAD

**Issue by AldousP** [libgdx/libgdx#3632]
Intersector method for intersecting two shapes and determining the resulting overlap is only usable with the Rectangle class. I'm currently attempting to determine overlap of two rotated Rectangles which isn't viable given that Rectangles do not currently have a concept of rotation. So the only other option currently is to use a Polygon. I recognize the difficulty of Polygon clipping and the fact that tasks such as this can be solved by Box2D, but it seems beneficial to also have the functionality in vanilla LibGDX

**Comment by NathanSweet** [comment]
Feel free to try a PR, else I'm not sure when someone will find time for this.

**Comment by AldousP** [comment]
Can do. I'll see what I can whip up in the next week or so.
