### ISSUE TITLE
Protecting Color.WHITE

### ISSUE THREAD

**Issue by doit-ceo** [libgdx/libgdx#3638]
If someone did this in complex multi-projects 

```
Color c=Color.WHITE;
c.a=0.5f;
```
Then it will be very hard to know why your alpha is wrong all over. We need to find a way to make the alpha (also rbg) to final when we have a constant like white. 

One of our developer did such a modification on this constant and this took very long time to discover why our alpha was wrong !  

Thanks

**Comment by JesseTG** [comment]
Wouldn't be the first time.  #3424

**Comment by MobiDevelop** [comment]
Indeed, this has come up several times before. Please see the linked issue for relevant discussion and if there is something new to add please keep the conversation on that issue.
