### ISSUE TITLE
getScale in Matrix3 always >0

### ISSUE THREAD

**Issue by Magnesus** [libgdx/libgdx#3639]
Method getScale in Matrix3 will always return positive values. There should be sign too.

**Comment by kerberjg** [comment]
This is the code for Matrix3.getScale(Vector2)
```java
public Vector2 getScale (Vector2 scale) {
		float[] val = this.val;
		scale.x = (float)Math.sqrt(val[M00] * val[M00] + val[M01] * val[M01]);
		scale.y = (float)Math.sqrt(val[M10] * val[M10] + val[M11] * val[M11]);
		return scale;
	}
```

As you can see it uses a square root to calculate the value, it'll always be positive.

**Comment by Magnesus** [comment]
Yes, which means for flipped things (scale(-1,0) for example flips horizontally AFAIK) it will show scale as a positive value while it should be negative. I have found a version of matrix decomposition where the sign of MM0 is used for scale.x and sign of M10 is used for scale.y - I don't know if it's correct though. The code would look like that then:

```
public Vector2 getScale (Vector2 scale) {
        float[] val = this.val;
        scale.x = (float)(Math.signum(val[M00])*Math.sqrt(val[M00] * val[M00] + val[M01] * val[M01]));
        scale.y = (float)(Math.signum(val[M10])*Math.sqrt(val[M10] * val[M10] + val[M11] * val[M11]));
        return scale;
    }
```

I am using that version right now for SVG matrix decomposition and it seems to work fine.

**Comment by Magnesus** [comment]
On the other hand I found another version of determining the sign of scale.x/scale.y:
```
scale[0] = sqrt(row0x * row0x + row0y * row0y)
scale[1] = sqrt(row1x * row1x + row1y * row1y)

// If determinant is negative, one axis was flipped.
double determinant = row0x * row1y - row0y * row1x
if (determinant < 0)
    // Flip axis with minimum unit vector dot product.
    if (row0x < row1y)
        scale[0] = -scale[0]
    else
        scale[1] = -scale[1]
```
