### ISSUE TITLE
Font generated with FreeTypeFontGenerator and added to skin.json at runtime is not rendering.

### ISSUE THREAD

**Issue by Gnipe** [libgdx/libgdx#3640]
I generate font at runtime and add it to skin.json like noone shows here: http://stackoverflow.com/questions/24856201/putting-freetypefont-into-libgdx-skin

It was working fine with earlier 1.7.2-SNAPSHOT (few weeks old).
When using new 1.7.2-SNAPSHOT font is not rendering, 1.7.1 works fine.

I'm not getting any errors and otherwise game works fine.
![font-issue](https://cloud.githubusercontent.com/assets/4393598/11811791/685ee22c-a340-11e5-900b-8f9e91156823.png)

**Comment by xGnoSiSx** [comment]
please supply a SCE and note that answered questions on stack exchange are NOT de facto correct.

**Comment by Gnipe** [comment]
Looks like using shadowOffset makes font to disappear. I'll close this since there is more appropriate issue ticket about this. See #3650.
