### ISSUE TITLE
Incorrect Capitalisation in libGDX Project Generator

### ISSUE THREAD

**Issue by drguildo** [libgdx/libgdx#3641]
The libGDX Project Generator UI has incorrect and inconsistent capitalisation of terms. The ones I've spotted are:
- "LibGDX" should be "libGDX"
- "Ios" should be "iOS"
- "Html" should be "HTML"
- "Box2d" should be "Box2D"
- "Box2dlights" should be "Box2DLights"
- "Ai" should be "AI"

**Comment by davebaol** [comment]
CapiTaLiSaTIOn LoOks coRrEct TO mE   :smile:

**Comment by NathanSweet** [comment]
PR?

**Comment by crykn** [comment]
[Liftoff](https://github.com/tommyettinger/gdx-liftoff) is currently being tested to become the new main setup tool. So, I'm closing this for now, considering there haven't been any comments to this issue in the last 5 years.
