### ISSUE TITLE
[FreeType] Premultiplied alpha option

### ISSUE THREAD

**Issue by AdrianNostromo** [libgdx/libgdx#3642]
Will there be an option to generate bitmap fonts with premultiplied alpha?

**Comment by NathanSweet** [comment]
There could be. Care to submit a PR?

**Comment by JFixby** [comment]
I guess this is related to: https://github.com/libgdx/libgdx/issues/3521

**Comment by NathanSweet** [comment]
~1 year without a PR, guess no one wants this bad enough.
