### ISSUE TITLE
Reflection issue with arrays

### ISSUE THREAD

**Issue by anubiann00b** [libgdx/libgdx#3645]
In my `.gwt.xml` file I included:

```
<extend-configuration-property name="gdx.reflect.include" value="com.badlogic.ashley.core.Component" />
```

I have a `Component[] components` that has a handful of components, and when I try to convert it to Json, it does gets to https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/Json.java#L514, where it does `ArrayReflection.getLength(components);`, and then crashes:

```
java.lang.RuntimeException: Couldn't find Type for class '[Lcom.badlogic.ashley.core.Component;'
```

The issue can be traced here: https://github.com/libgdx/libgdx/blob/master/backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/utils/reflect/ArrayReflection.java#L32

For some reason, `ReflectionCache.getType()` fails on an array. Is there a way to register an array type for reflection?

I can convert an `Array<Component>` or a single Component to Json just fine.

**Comment by anubiann00b** [comment]
Ok I got a fix for this. I created

```
public class TestObject {

    public Component[] components;
}
```

And then added it in my xml:

```
<extend-configuration-property name="gdx.reflect.include" value="com.example.TestObject" />
```

Now serialization of a `Component[]` works fine, and the generated reflection cache contains:

```
c10 = new Type("com.badlogic.ashley.core.Component[]", 10, com.badlogic.ashley.core.Component[].class, null, null);
```

Shouldn't we have a way to manually add an array of a specific type? And why do we need to get the type of the array to get its length?

**Comment by MrStahlfelge** [comment]
Please open an issue on Ashley repo. The class must be included on ashley's gwt configuration files.
