### ISSUE TITLE
[Minor docs issue] BitmapFont: Only one texture atlas page supported

### ISSUE THREAD

**Issue by mhilbrunner** [libgdx/libgdx#3647]
There are some docs stating that BitmapFont only supports a single texture atlas page.
As far as I can tell, this is no longer true.

Below references to this should probably be changed/removed:

The JavaDoc on line 43/44 of BitmapFont.java states:
"Currently only a single image of glyphs is supported."

https://github.com/libgdx/libgdx/wiki/Gdx-freetype states:
"If you use too big of a size, things might explode. BitmapFonts still only support a single atlas page at the moment, something I'll try to fix in the next couple of weeks. ..."

**Comment by NathanSweet** [comment]
Please just change the wiki if you would like the wiki changed.

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://heatingairconditioningalexandria.com/commercial.php?0>

 

loogie@basicelementdesign.com
