### ISSUE TITLE
Using freetype with border and shadow makes font disappear

### ISSUE THREAD

**Issue by Trurl101** [libgdx/libgdx#3650]
A big issue:
With LibGDX 1.7.2 the freetype implementation has a bug.
If you use both, border and shadow, than the font disappears. No errors or messages or something, the font will simply will not be drawn and has no bounds.

A minor issue:
Don't know if that was true before but If you specify only one parameter for the shadow offset like only the x-offset and not the y-offset, the game crashes. I don't know if this comes with Libgdx 1.7.2 too or has been true before.

**Comment by MobiDevelop** [comment]
I am able to reproduce the first issue, but specifying only one of x-offset or y-offset on the shadow seems to work fine for me.
