### ISSUE TITLE
Removing unwanted jars

### ISSUE THREAD

**Issue by serge144** [libgdx/libgdx#3655]
Hey everyone,

So my android app excedeed the number of total methods permited (65K) so it can't build into a dex file. Basically, when i first created the libgdx project i included some extensions that were available (AI, box2d, bullet, lights ) and now i see i don't need anything of those jars in my project. How can i remove these jars so i can make my app more lightweight?. I'm also trying to use proguard to reduce the number of packages used in google play services.

Best Regards

**Comment by MobiDevelop** [comment]
Remove the unwanted items from the dependencies section(s) in the `build.gradle`.

Please use the forum or irc for questions in the future.

**Comment by Tom-Ski** [comment]
You can enable multidex to get around the limit, but if you aren't using those libraries remove them from your root build.gradle file. You shouldn't need to, but a `gradlew clean` task after you have removed them wouldn't be the worst idea.

Please use the forum or the irc for help with matters like this, we like to keep the issue tracker for issues only.
