### ISSUE TITLE
Scaling Action on Scene2d Window affects stageBackground dim

### ISSUE THREAD

**Issue by azurlake** [libgdx/libgdx#3656]
Hello there,

I think this might be considered as a bug - I understand why it works this way but I think it is not the expected way for the functionality it is meant to provide.

When applying a scaling Action to a window, for example:

```java
Window win = new Window ("title", skin);
...
stage.addActor(win);
win.setScale(0, 0);
win.addAction(Actions.scaleTo(1, 1, 0.4f));
```
One may expect the stageBackground drawable (which is meant to dim the rest of the stage while the dialog window is showing) to cover 100% of the screen from the beginning, even while scaling - that is, if you want a fancy window to scale in, you don't want the background dim to scale in too, but to have it full screen from the beginning. Currently the background dim drawable scales in too, resulting in a weird and undesired effect.

Is this correct? If so, is it easy to fix so that the scaling Action is only applied to the window container itself, but not the stage background?

**Comment by NathanSweet** [comment]
It's not easy to fix. The stage background is drawn when the window is drawn, so the batch is configured to draw using the window's transform.

I suggest drawing your own background when a window is open. Eg, you could add an image to the stage immediately under the window. `setFillParent` can be used on the image.

**Comment by azurlake** [comment]
Ok; that's what I thought. Thanks for the answer - I'll draw another image in the background with `setFillParent` as you suggested. You can close the issue.
