### ISSUE TITLE
Stage Constructor Allowing Root Group to be Supplied

### ISSUE THREAD

**Issue by darkfrog26** [libgdx/libgdx#3658]
I would like to extend the `Group` that is used for `root` in `Stage` but `root` is final and doesn't have a constructor that allows you to pass it in.

I would like to propose a simple modification of this constructor:

``` java
public Stage (Viewport viewport, Batch batch) {
```

to look like:

``` java
public Stage (Viewport viewport, Batch batch, Group root) {
```

and you can add another constructor:

``` java
public Stage (Viewport viewport, Batch batch) {
  this(newport, batch, new Group);
}
```

**Comment by xoppa** [comment]
Can you explain the use-case a bit more? What would be a practical example where you'd need this?

**Comment by darkfrog26** [comment]
For example, if I want to set ScissorStack on the root so that nothing draws outside of the stage bounds on the screen.  I can accomplish this by adding a custom `Group` to the root, but that forces me to change everything and remember never to add to root directly.  It would be far more useful if the root was able to be overridden and set explicitly.  This feature wouldn't cause any problems but would add to the flexibility of `Stage`.

**Comment by nhydock** [comment]
So what you're saying is you just want to have the ability to have your own custom class (or any class) that extends Group be the root node of the stage instead of a standard Group?

**Comment by darkfrog26** [comment]
Yes

**Comment by xGnoSiSx** [comment]
I second this, cause it's too restrictive as it is now.

**Comment by NathanSweet** [comment]
Please explain the downsides to just adding your stuff to the root group.

**Comment by kotcrab** [comment]
+1. In my case I'm using custom root to get notified when new modal window was added so I can disable keyboard shortcuts, [example](https://github.com/kotcrab/vis-editor/blob/master/editor/src/com/kotcrab/vis/editor/util/scene2d/VisGroup.java).
