### ISSUE TITLE
Add the ability to clear all pools in Pools

### ISSUE THREAD

**Issue by asherbar** [libgdx/libgdx#3659]
I think it would be useful to add the ability to clear all pools that are stored internally in [Pools](https://github.com/libgdx/libgdx/blob/fde893cec5448fdd09e778d1c103aac474950873/gdx/src/com/badlogic/gdx/utils/Pools.java) via the `static` variable `typePools`. 
The implementation seems to be rather straightforward: Simply iterate over all the `pools` and call their `clear` method. Something like this: 

``` java
public class Pools {
    // ...
    public static void clear() {
        for (ObjectMap.Entry<Class, Pool> entry : typePools)  {
            entry.value.clear();
        }
    }
}
```

**Comment by xoppa** [comment]
Please include an example of a practical use-case where this would be useful.

**Comment by asherbar** [comment]
Consider the following use case:
On Android, due to the App's lifecycle, `static` references are kept alive when the App is hidden. So say we use `Pools` to obtain objects which reference a [Disposable](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/utils/Disposable.html) resource. This means that indirectly, these resources are statically referenced, because they are kept inside the `static` variable `typePools`.

It is considered (or so I understand) good practice to dispose resources in [ApplicationListener's](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/ApplicationListener.html) `dispose`. So if I do that, this means that after returning to the game, i.e., after `disposed` has been called, recycled objects that were kept alive due to the `static` referencing, are now referencing `disposed` resources. When I obtain these objects from `Pools`, I get unexpected behaviour.

With the above request, this problem can be easily be solved by clearing all pools in `Pools`.

**Comment by xGnoSiSx** [comment]
I didn't quite understood the use case asherbar, but:

this would save memory while increasing app switching speed since you have to recreate the pools once you switch back to the application. I'd say to add the ability, but without testing in each different app for performance impact there might be trouble.

**Comment by asherbar** [comment]
@xGnoSiSx I agree the use case I wrote is not too simple, but roughly, any use case you can imagine that would require [clearing a Pool](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/utils/Pool.html#clear--), can be applied to this proposed feature as well.

> ... but without testing in each different app for performance impact there might be trouble

What sort of trouble do you have in mind?

**Comment by cypherdare** [comment]
Seems like since this is apparently the only use case, you'd actually want a `clearDisposables` method that clears only the objects that implement Disposable.

**Comment by cypherdare** [comment]
I'm going to close this, as a valid use case that doesn't abuse the handling of `Disposables` was never demonstrated. Disposables aren't practical to place into ReflectionPools, as any of the libGDX classes implementing Disposable are unlikely to have a useful empty constructor and also be the sort of thing you need many of.

Suppose you want to pool Pixmaps or FrameBuffers. These don't have useful empty constructors. You would need to make your own Pool that calls a specific constructor with specific parameters in `newObject()`. And then you can `freeAll()` your own pool when the game is disposed.

If a reflection-pooled class references Disposable objects that it does not own, it should null out the references in `reset()`.
