### ISSUE TITLE
Clearing pixmap doesn't work on HTML5

### ISSUE THREAD

**Issue by Dimitri0xff** [libgdx/libgdx#3660]
It's supposed be done like this:
```java
Pixmap.setColor(Color.CLEAR);
Pixmap.fill();
```
It works on desktop but not on HTML5.
Filling with any other color works, but clearing the pixmap to be all transparent again doesn't work on HTML5.
Is this a bug or setting a different blendmode could work?

**Comment by intrigus** [comment]
What exactly 'doesn't work'?
What did you expect?
What did actually happen?

**Comment by MobiDevelop** [comment]
You probably need to set the BlendMode to None.

**Comment by Dimitri0xff** [comment]
Yes it works with Blending set to none. Thank you.
