### ISSUE TITLE
defaultConfig.applicationId in android/build.gradle

### ISSUE THREAD

**Issue by serhii-k** [libgdx/libgdx#3662]
Hello guys,

Please, add the defaultConfig.applicationId with a package name to android/build.gradle, inside the Setup App.

I've encountered a weird issue - my app couldn't be installed on some new Samsung devices, like Note 5 and Galaxy S6, if they had some other app installed with the same problem (see below). People received the -505 error code during the installation of my app.

The explanation that helped me is here:
https://code.google.com/p/android/issues/detail?id=193567

Yes, and this issue appeared after I updated Google Analytics.

**Comment by Tom-Ski** [comment]
Thanks for the report.

**Comment by serhii-k** [comment]
Tom, thank you for such quick commit!
