### ISSUE TITLE
Gwt local files with LocalStorage API

### ISSUE THREAD

**Issue by billy1380** [libgdx/libgdx#3663]
There seems to be a class that emulates a file system using local storage API in the gwt backend, but GwtFileHandle and GwtFiles throw exceptions for everything of FileType.local. Does anyone know why the default implementations of these classes is not used and let the emulating class (java.io.File) take over?

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/File-handling
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
