### ISSUE TITLE
Support for GL_TEXTURE_EXTERNAL_OES

### ISSUE THREAD

**Issue by doit-ceo** [libgdx/libgdx#3666]
I'm trying to create Texture that is GL_TEXTURE_EXTERNAL_OES to share the texture through multiple threads (i.e. Android & LibGDX) , the problem that I have with this that the OO structure of Texture & GLTexture classes make it impossible to use any thing other than the hardcoded GL_TEXTURE_2D as the Texture class is hiding the most important constructor of the GLTexture (public GLTexture (int glTarget, int glHandle)) , not sure why !

Any alternative way for this ? I can create this texture in Android, but not sure how to convert it to LibGDX Texture after that to pass it around to UIs 

Thanks

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
