### ISSUE TITLE
Game Controller Wrappers

### ISSUE THREAD

**Issue by kennycason** [libgdx/libgdx#3668]
Hi, this is more of just a discussion point, but basically every time I integrate controllers into games I end up doing something similar to what I do in this post: http://kennycason.com/posts/2015-12-27-libgdx-controller.html

That is, 1) create an easier to use controller interface, 2) support input from multiple controllers at once (imagine seamless keyboard + controller support) (optional), 3) basic timestamps for keypresses 4) support key combos (not in demo posted)

Is this sort of wrapper useful for people over all? Or is this too specific to my use-cases? Just figured it would be worth bringing up. 

Feel free to close the issue at any time :)

**Comment by Darkyenus** [comment]
(In case this does not get into the core:) You can always make a third party library/extension

**Comment by nhydock** [comment]
@kennycason Your implementation has a lot of boilerplate necessary for creating control schemes.  I went and spent a few minutes creating something that's a bit more generic and maps closer with libgdx's normal approach to input handling, which should make it a bit easier to integrate into projects.  Hope you don't mind

https://gist.github.com/nhydock/dc0501f34f89686ddf34

**Comment by kennycason** [comment]
@nhydock I don't mind at all and am still very much learning libgdx. :) I will check out the gist.

**Comment by kennycason** [comment]
I think I agree that the boiler plate required to support "isA" "isB" is too much and just passing in a GameInput.A to a single isPressed() is much better. :) I will make updates to the code as well as consider pushing to a core and/or extension. 
If you don't mind I would also like to update my blog post with this refactoring (will give reference)

**Comment by nhydock** [comment]
@kennycason go right ahead

**Comment by kennycason** [comment]
@nhydock Thanks!

**Comment by badlogic** [comment]
This is nice, if you aren't super against it, i'd prefer it to be an
extension though. Can be integrated with our setup-ui so others can use it
easily.

**Comment by kennycason** [comment]
That works for me. I'll model the formatting/packaging of other extensions.

**Comment by kennycason** [comment]
Made the changes: https://github.com/kennycason/starlight/tree/master/core/src/com/kennycason/starlight/input

Ignore the app-specific mapping + builder. If people like the direction I will break it out into it's own module and start adding support/tests for other controllers.

**Comment by kennycason** [comment]
@nhydock @badlogic I created the start of the project here:

https://github.com/kennycason/gdx-controller

It's also available in maven central. I'm about to start a game that needs controller support so I'll begin hashing out some of the TODOs. Feel free to peer review, create issues, or whatever you feel needed! :)

Thanks again for the awesome java game framework!
