### ISSUE TITLE
ShapeRenderer wrong behavior with Line/Filled

### ISSUE THREAD

**Issue by vinicri** [libgdx/libgdx#3671]
Code below only draws filled shapes. Checked desktop(OsX Yosemite ) and android 

		shapeRenderer.setProjectionMatrix(camera.combined);
		shapeRenderer.begin(ShapeRenderer.ShapeType.Line);
		 shapeRenderer.circle(randomX, randomY, 80);
		shapeRenderer.end();

		shapeRenderer.begin(ShapeRenderer.ShapeType.Filled);
		 shapeRenderer.circle(randomX2, randomY2, 80);
		shapeRenderer.end();

**Comment by NathanSweet** [comment]
ShapeRendererTest appears to work.
https://github.com/libgdx/libgdx/wiki/More-Info
