### ISSUE TITLE
Space bar keypress is not detected when you have left arrow and top arrow pressed.

### ISSUE THREAD

**Issue by cobolfoo** [libgdx/libgdx#3675]
Ok this is kind of specific, but here to reproduce.

1) Use libgdx 1.7.2 (I tried 1.7.3-snapshot and 1.6.2, both have the same issue).
2) Run gdx input test program
3) Press LEFT (code: 21) and TOP (code: 19) then also press SPACE BAR (62), the SPACE BAR don't get reported in the InputProcessor keyDown function.

**Comment by MobiDevelop** [comment]
Unfortunately, this is likely a limitation of your keyboard. Many keyboards have very limited ability to report concurrent keypresses on the same rows and/or columns. See [Keyboard Ghosting Explained](https://www.microsoft.com/appliedsciences/antighostingexplained.mspx).

This key combination does work correctly on my Macbook, but not on my Windows laptop.

**Comment by cobolfoo** [comment]
I tested a little bit further.

I grabbed LWJGL 2.9.3, which have the same issue.

MobileDevelop: Why it's happening across all three platforms and do not affect AWSD or RIGHT TOP SPACEBAR?

**Comment by cobolfoo** [comment]
OK OK, ghosting, you won :)

http://www.keyboardtester.com/
