### ISSUE TITLE
Image's draw method sets the batch color to its color and never changes it back.

### ISSUE THREAD

**Issue by barodapride** [libgdx/libgdx#3676]
Image sets the batch's color in the draw method and never sets it back. This means that if you alter an Image's color or alpha, once that image is drawn all the following Actors will be drawn with the same color. I can't imagine this is intended since it is unintuitive and not useful in any way that I can imagine.

To work around it, one can extend Image and override the draw method to reset the batch color.

**Comment by MobiDevelop** [comment]
This is the intended behavior. Please see https://github.com/libgdx/libgdx/issues/1851, where this was previously reported.
