### ISSUE TITLE
Eclipse Import: Timeout of 120000 reached waiting for exclussive access to file 'gradle-2.4-all.zip'.

### ISSUE THREAD

**Issue by GiantCrocodile** [libgdx/libgdx#3678]
I just get the error `Eclipse Import: Timeout of 120000 reached waiting for exclussive access to file 'gradle-2.4-all.zip'.` when I try to import my freshly generated libgdx project in Eclipse Mars.

![gradle_error](https://cloud.githubusercontent.com/assets/6271057/12036817/bd92cc72-ae49-11e5-90c1-dc5f7defd3d1.jpg)

`Gradle IDE 3.7.3.201512211912-CI-B53` is currently installed.

I'm unsure where to find the mentioned erorr log. I don't see one in my project directory.

Thanks for looking at this!

**Comment by badlogic** [comment]
It appears that the Gradle 2.4 distribution is no longer available. That's nice backward compatibility by Gradle :)

@tomski, could you update our stuff to use Gradle 2.10? Thanks!

**Comment by GiantCrocodile** [comment]
So how should I go on @badlogic? Is there some easy way to change Gradle to newer version myself or do I have to wait for some bigger patch?

**Comment by MobiDevelop** [comment]
The 2.4 distribution is still available... That said, I am sure it would be fine to update.

**Comment by MobiDevelop** [comment]
@GiantCrocodile if you go into the <project-root>/gradle/wrapper/gradle-wrapper.properties, you can change the version there.

**Comment by GiantCrocodile** [comment]
Official Gradle download server is very slow at the moment. I get less than 20 kB/s. So it just timed out because of download speed. I just changed to some mirror and tried to use Gradle 2.10 but it fails because 2.2 is required @badlogic. Then I tried 2.9 like @MobiDevelop said and it works now.
