### ISSUE TITLE
VM Crash using Pixmap#dispose on Win64

### ISSUE THREAD

**Issue by me4502** [libgdx/libgdx#3683]
The Java VM crashes in some circumstances when Pixmap#dispose is called. I can't reliably reproduce it, it just occurs randomly, regardless of the manner in which it is called.

Here is the VM crash log, http://pastebin.com/bV5xtVc7

Using LibGDX 1.7.2 on Windows64

**Comment by badlogic** [comment]
Looks like you are freeing an already disposed Pixmap.

**Comment by me4502** [comment]
Isn't an exception normally thrown in that case?

**Comment by me4502** [comment]
As an update, I'm also getting infrequent instances of Java displaying a 'stopped responding' dialogue, which means I'm unable to get the crash log in those instances.

**Comment by xoppa** [comment]
This is better suited for the forum or irc. https://github.com/libgdx/libgdx/wiki/Issue-Tracker. If you still think that there's an issue with libgdx, then please include the required information.
