### ISSUE TITLE
Shrinking a Pixmap with interpolation / smoothing.

### ISSUE THREAD

**Issue by mnori** [libgdx/libgdx#3686]
I am trying to shrink Pixmaps with interpolation.
In the docs it says I can use this to get smooth resizing with `pixmap.drawPixmap(...)`:

```
Pixmap.setFilter(Pixmap.Filter.BiLinear);
```

When I tested this, I could produce a nice interpolated image when the size is increased, but if the size is reduced, the results look identical to when `Pixmap.Filter.NearestNeighbour` is used. I.e. no smoothing.

Is this a bug or a feature with the `Pixmap.Filter.Bilinear`? Am I doing something wrong? Is there maybe an alternative way of shrinking Pixmaps smoothly?

Thanks!

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info

**Comment by mnori** [comment]
I've just figured out this is the same issue as previously reported in #2923, apologies.

I made a small example app and put it in that thread
