### ISSUE TITLE
Bullet wrapper - disable generating finalizers

### ISSUE THREAD

**Issue by tukez** [libgdx/libgdx#3688]
I think SWIG generating finalizers should be disabled for the Bullet wrapper. As far as I understand, all the objects should be manually disposed (as in all libgdx code?), so the finalizers are just slowing down GC.

SWIG manual reference to disable generating finalizers: http://www.swig.org/Doc1.3/Java.html#performance

**Comment by nooone** [comment]
Aren't the finalizers generating log warnings in case something has not been cleaned up correctly by the user?

**Comment by tukez** [comment]
Yes they are, but since other classes in libgdx are not doing the same, why should bullet wrapper? I would prefer performance.

**Comment by xoppa** [comment]
So the issue you're reporting is that the fail safe warning has an impact on the performance? I've profiled the wrapper alot and never found the fail safe to have a noticeable impact on the performance when object were properly disposed. Please include the required information to reproduce the issue you are reporting.
See: https://github.com/libgdx/libgdx/wiki/More-Info

**Comment by tukez** [comment]
xoppa, I don't have a specific issue at hand. I'm going to use the bullet wrapper on the server side and I reported this issue already, because I know finalizers have a big performance impact. I cannot easily test the bullet wrapper with and without finalizers as that would mean making the modifications to the wrapper (I don't know how). What I can do though is make a general test to benchmark finalizer impact on performance:

```java
package test;

import java.lang.management.GarbageCollectorMXBean;
import java.lang.management.ManagementFactory;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.Supplier;

public class TestFinalizationPerformance {

    public static void main(String[] args) {
        long startTime = System.currentTimeMillis();

        final int rounds = 5000;
        AtomicInteger tracker = new AtomicInteger(0);
        // test(rounds, () -> new ClassWithTrivialFinalizer(tracker));
        test(rounds, () -> new ClassWithNonTrivialFinalizer(tracker));

        long endTime = System.currentTimeMillis();

        long totalGcTime = 0;
        for (GarbageCollectorMXBean gcBean : ManagementFactory.getGarbageCollectorMXBeans()) {
            long gcTime = gcBean.getCollectionTime();
            if (gcTime != -1) {
                totalGcTime += gcTime;
            }
        }

        System.out.println("Tracker count: " + tracker.get());
        System.out.println("Total gc time: " + totalGcTime + "ms");
        System.out.println("Total time:    " + (endTime - startTime) + "ms");
    }

    public static <A extends ITestClass> void test(int totalRounds, Supplier<A> supplier) {
        List<A> objects = new ArrayList<>();

        for (int i = 0; i < 1000; i++) {
            objects.add(supplier.get());
        }

        Random rand = new Random(123);

        for (int rounds = 1; rounds <= totalRounds; rounds++) {
            for (int i = 0; i < 10000; i++) {
                int itemToReplace = rand.nextInt(objects.size());
                A object = objects.set(itemToReplace, supplier.get());
                object.doStuff();
            }
        }
    }

    private interface ITestClass {
        void doStuff();
    }

    private static final class ClassWithNonTrivialFinalizer implements ITestClass {

        public AtomicInteger tracker;

        public ClassWithNonTrivialFinalizer(AtomicInteger tracker) {
            this.tracker = tracker;
        }

        @Override
        public void doStuff() {
            // Do nothing here, do the stuff in the finalizer instead.
        }

        @Override
        protected void finalize() throws Throwable {
            tracker.incrementAndGet();
        }

    }

    private static final class ClassWithTrivialFinalizer implements ITestClass {

        public AtomicInteger tracker;

        public ClassWithTrivialFinalizer(AtomicInteger tracker) {
            this.tracker = tracker;
        }

        @Override
        public void doStuff() {
            tracker.incrementAndGet();
        }

        @Override
        protected void finalize() throws Throwable {
            // Do nothing, empty finalizer is trivial and optimized away.
        }

    }

    public static final class FinalizationTracker {

        public final AtomicInteger finalizationCount = new AtomicInteger(0);

    }
}
```

The results are for ClassWithTrivialFinalizer:
Tracker count: 50000000
Total gc time: 9ms
Total time:    1205ms

And for ClassWithNonTrivialFinalizer:
Tracker count: 8686161
Total gc time: 32963ms
Total time:    43109ms

As you can see the difference is quite big. Of course the performance impact on the wrapper is not that  big but it would be an easy(?) fix to help with GC problems.

Here is some stackoverflow discussion on finalizers: http://stackoverflow.com/questions/2954948/performance-implications-of-finalizers-on-jvm

So the trade off here is between ease of coding and performance. The thing is that as a libgdx bullet user, you can make your code correct by disposing every object you allocate. There is nothing you can do to the finalizers if/when they cause problems.

**Comment by xoppa** [comment]
Looks like you are looking for problems that don't exist. The bullet wrapper is designed in such way that the GC should never be triggered in performance crucial parts anyway (just like everything else of libGDX). As long as there is no actual issue, I don't see why we should implement any fix for it. If you really like to (prematurely) optimize those few calls that might happen then you might as well use the static API methods instead. That way you'll avoid all the (non-jni) overhead the wrapper adds all together. The warning and cleanup is there for a reason.
