### ISSUE TITLE
Blender model being displayed skewed after applying parenting with automatic weights.

### ISSUE THREAD

**Issue by Unexperienced** [libgdx/libgdx#3689]
Hi everyone and happy new year!

I've decided to experiment a little bit with 3D Modelling, Texturing, Skinning and Animation with Blender and for this purpose I've followed this tutorial https://www.youtube.com/watch?v=vUFRnU1xEYw .

I managed to create an object and import it in Libgdx, but the model is somehow getting skewed.
The problem is occuring after I've applied the parenting between the mesh and the bones. In Blender as you can see everything is proportioned and working perfectly fine. After exporting the model without applying any parenting between the bones and the mesh everything is being displayed fine, but after I applied "Set parent to with automatic weight" as mentioned in the tutorial and exported the model I've got those strange skewing effects.
What I've tried until now
- recalculating normals, clear transformations, recalculating rolls, exporting as G3DJ, changing the UP direction.
Its not just a simple rotation. The whole mesh is somehow strangely skewed and I don't know how to fix it.

Does anyone have any idea?
Thank you!

![image01](https://cloud.githubusercontent.com/assets/16527359/12079615/73101dfa-b248-11e5-935c-233baaa6e327.png)

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
