### ISSUE TITLE
rotateBy surpasses 360 & 0

### ISSUE THREAD

**Issue by agmcleod** [libgdx/libgdx#3690]
While the rotation looks fine on screen, the number output is wrong. It should clamp to 0, and 360, then roll over to the next value as it goes past either. The reason I request this is i'd like to rotate to an angle by the shortest route. I realized this is tricky to calculate when the rotation surpasses 360deg.

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info

**Comment by agmcleod** [comment]
```
package com.badlogic.gdx.tests.lwjgl;

import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.g2d.Batch;
import com.badlogic.gdx.scenes.scene2d.Actor;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.actions.Actions;

class MyActor extends Actor {
    public MyActor() {

    }

    @Override
    public void draw(Batch batch, float alpha) {
        addAction(Actions.rotateBy(100));
        System.out.println(this.getRotation());
    }
}

public class MyGdxGame extends ApplicationAdapter {
    private Stage stage;

    @Override
    public void create () {
        stage = new Stage();
        stage.addActor(new MyActor());
    }

    @Override
    public void render () {
        Gdx.gl.glClearColor(1, 0, 0, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        stage.act();

        stage.draw();
    }

    public static void main (String[] args) throws Exception {
        new LwjglApplication(new MyGdxGame());
    }
}
```

Here's a simple code example to try. Can see how each frame the angle output just keeps going up rather than looping around back to zero.

**Comment by mbrlabs** [comment]
I'm pretty sure, that this is intended. However in your case you can just use the modulus operator to get a degree between 0 and 360: rotation % 360

**Comment by agmcleod** [comment]
@mbrlabs yeah if it's intended, then you can close it. Just came off as odd behaviour given how we learn rotation in grade school as 0-360 :)

**Comment by xoppa** [comment]
Having an angle below zero or above 360 degrees is perfectly valid (at least it was at my grade school :)). If the class would keep the angle within the 0-360 range then it might remove information the user might need. For example, the number of times it has been fully rotated `((int)(angle / 360))`. Also, it would imply that adding a value might result in a lower value (`x > 0 && a + x < a`). Whether or not this is useful depends on the use-case. You can normalize the angle (`a < 0 ? 360 - (-a % 360) : a % 360`) if needed (although commonly the range -180 - 180, is often used as well).

**Comment by agmcleod** [comment]
@xoppa fair point. I have dealt with the -180 to 180 somewhere in games/graphics, though I don't recall which library :). I'll implement the modulus in my game as the solution, just used rotateTo until we figured something out. Thanks for the responses!
