### ISSUE TITLE
Is gdx-freetype can load NotoColorEmoji font on android

### ISSUE THREAD

**Issue by bangive** [libgdx/libgdx#3692]
I try to load NotoColorEmoji font on android with gdx-freetype but have the following error:

```
E/AndroidRuntime(26776): com.badlogic.gdx.utils.GdxRuntimeException: Couldn't se
t size for font
E/AndroidRuntime(26776):        at com.badlogic.gdx.graphics.g2d.freetype.FreeTy
peFontGenerator.setPixelSizes(FreeTypeFontGenerator.java:264)
E/AndroidRuntime(26776):        at com.badlogic.gdx.graphics.g2d.freetype.FreeTy
peFontGenerator.<init>(FreeTypeFontGenerator.java:118)
```

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info

**Comment by bangive** [comment]
I've tried to search on forums and issues on this repo but found no related info.
Use the newest gdx-setup app.
Here is [my project](https://drive.google.com/file/d/0B4dCHEToS7afaE53Vk1feW9la1U/view?usp=sharing) for you to invest. It does not contain libraries so please run on command line
```gradlew.bat clean --no-daemon``` to download them.
Do i need to provide more info?

**Comment by lachiemurray** [comment]
I'm also having this problem. Attempting to load the font like so:

```java
FreeTypeFontGenerator generator = new FreeTypeFontGenerator(
    Gdx.files.internal("NotoColorEmoji.ttf"));
FreeTypeFontParameter parameter = new FreeTypeFontParameter();
parameter.size = 22;
font = generator.generateFont(parameter);
generator.dispose();```

**Comment by alexdriedger** [comment]
I am also having the problem of libdgx not rendering emojis

**Comment by MrStahlfelge** [comment]
"Libgdx not rendering emojis" is probably just the problem that the emojis are not included in the bitmapfont.
The original issue is very old and there is no sign from the original authors, so I am closing this. Feel free to reopen with a better exception code given by the linked PR.
That said, emojis and libgdx is a topic that is not covered well. If anyone has a best practices, an addation to the wiki would be great.

**Comment by crykn** [comment]
Just for future reference, there is a [gdx-EmojiSupport](https://github.com/DavidPDev/gdx-EmojiSupport) project using glyph injection.

**Comment by MrStahlfelge** [comment]
Interesting project, will have a look!
