### ISSUE TITLE
Gdx.app.exit() doesn't work on HTML platform

### ISSUE THREAD

**Issue by tsteinholz** [libgdx/libgdx#3695]
I found an `exit()` call for a `GwtApplication` in the [JavaDocs](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/backends/gwt/GwtApplication.html) but it isn't automatically called when i execute the code `Gdx.app.exit()`. Am I misunderstanding this use case for this or how I am supposed to do this? Is it not implemented? I'm just expecting the browser tab to close...

System Details
OS: Windows 10 Home Edition
Arch: x64
Browser: Google Chrome Version 47.0.2526.106 (latest)

**Comment by MobiDevelop** [comment]
It is not implemented. A window may only be closed by a script if it was opened by a script. You may, however, override the exit method in your HtmlLauncher to close the window if your window was opened by a script

**Comment by tsteinholz** [comment]
Is it the exit function that hasn't been implemented or the callback to the exit function from calling the app exit? And when would that be implemented? I have just running the dist from the html on the root of my server with some modifications to the HTML and CSS to make it full screen. So I don't have a script executing it, would you recommend that as the way to go? And if so I'm assuming I need to use JavaScript right?

Von meinem iPhone gesendet

**Comment by MobiDevelop** [comment]
The exit method is called, it just doesn't do anything (it's an empty method in GwtApplication). If you want to be able to call `Gdx.app.exit()` to close the window you'll have to open it via a `window.open` script from another page and implement the exit method to call `window.close`.

**Comment by MobiDevelop** [comment]
If you don't mind, I'll close this and be happy to continue discussion at the forum or irc.

**Comment by tsteinholz** [comment]
Well for others with this problem you can add this to your HTML launcher instead

```java
    @Override
    public void exit() {
        super.exit();
        Window.alert("You can only exit the application, just hit close tab...");
    }
```
