### ISSUE TITLE
Wrong dependency project name when setting up new project for Eclipse

### ISSUE THREAD

**Issue by tjacoel** [libgdx/libgdx#3696]
I have created a new project using the gdx-setup.jar tool available from https://libgdx.badlogicgames.com/download.html with the option to generate the .project files for Eclipse.

After importing the projects in Eclipse, I can see that the configuration is wrong: the Java Build Path includes a project named "my-gdx-game-core" but it doesn't exist. I am able however to include the project name "core" that is on my workspace.

**Comment by Tom-Ski** [comment]
This is working correctly in Mars 4.5.1. Make sure you let the setup tool complete, and follow the instructions on successful completion to import correctly into eclipse.
