### ISSUE TITLE
Wiki pages that need to be updated due to LWJGL3 breaking things

### ISSUE THREAD

**Issue by intrigus** [libgdx/libgdx#3700]
- [x] https://github.com/libgdx/libgdx/wiki/Fullscreen-%26-vsync 
- [ ] https://github.com/libgdx/libgdx/wiki/Starter-classes-%26-configuration
- [x] https://github.com/libgdx/libgdx/wiki/Take-a-Screenshot
- [x] https://github.com/libgdx/libgdx/wiki/Controllers
- [x] https://github.com/libgdx/libgdx/wiki/Cursor-visibility-%26-catching

All of those pages are outdated due to LWJGL3.
- [x] https://github.com/libgdx/libgdx/wiki/Configuration-%26-querying

This page is also outdated, see #3594 (Addition of Gyroscope). We should also add an extra wiki page for the Gyroscope.

**Comment by badlogic** [comment]
Awesome, thanks for doing this work!

**Comment by badlogic** [comment]
I removed the full-screen/vsync article in favor of a more elaborate one. 

I rewrote the "Take a screenshot" article.

I fixed up the controllers page.

@intrigus could you revamp the starter classes configuration, cursor visibility and input config/querying pages as you suggested?

Controllers doesn't need an update from what i can tell.

**Comment by intrigus** [comment]
I've updated https://github.com/libgdx/libgdx/wiki/Starter-classes-&-configuration. I removed the old Xamarin backend and added the iOS Robovm backend. I don't know the Robovm so could you maybe add the information for it?
I added a section for LWJGL3, but it's blank, because it's not yet available through the setup ui, is it?

I've also added a Gyroscope page but it's more a stub than a page.
