### ISSUE TITLE
getDesktopDisplayMode()

### ISSUE THREAD

**Issue by dimecoin** [libgdx/libgdx#3703]
Using this with 1.8.1 libgdx nightly back end

if I set :

    cfg.fullscreen = true;
    cfg.width = LwjglApplicationConfiguration.getDesktopDisplayMode().width;
    cfg.height = LwjglApplicationConfiguration.getDesktopDisplayMode().height;

I get this:

    Exception: java.lang.UnsatisfiedLinkError thrown from the UncaughtExceptionHandler in thread "main"

getDisplayMode() doesn't exist in 1.8.1 nightlies.

If I manual set width/height it works fine (or if I don't set).

It's using the old/current LWJGL back end (2.9.2).  Windows 7 64bit.

**Comment by Darkyenus** [comment]
Read [changelogs](http://www.badlogicgames.com/wordpress/?p=3870) if you are on nigtlies. `getDesktopDisplayMode()` has been renamed.

**Comment by dimecoin** [comment]
I saw that, but the old methods are still accessible.  Shouldn't they be removed or set to private, instead of just crashing?

**Comment by badlogic** [comment]
Could you please be more structured? I have a hard time following the issue. From what i gather:

1. You are using libGDX 1.8.1-SNAPSHOT
2. You are using the "old" LWJGL2 backend
2. You are calling LwjglApplicationConfiguration.getDesktopDisplayMode(), which fails with an unsatisfied link error

Are you using Gradle? Did you temporarily switch to the LWJGL3 backend? My guess is that libGDX is trying to load lwjgl.dll from LWJGL3 of a previous run of yours, instead of overwritting it with lwjgl.dll from LWJGL2.

**Comment by dimecoin** [comment]
Yes, that is exactly right.  Those 3 steps.

I'm not using gradle.    I just manually download snapshots and put in 'libs' and it is built in ant in linux or Eclipse in windows..   No code or build changes, just updated binaries.

                <classpath>
                        <pathelement path="${lib.dir}/gdx-backend-lwjgl-natives.jar"/>
                        <pathelement path="${lib.dir}/gdx-backend-lwjgl-natives.jar"/>
                        <pathelement path="${lib.dir}/gdx-backend-lwjgl.jar"/>
                        <pathelement path="${lib.dir}/gdx-natives.jar"/>
                        <pathelement path="${lib.dir}/gdx.jar"/>               
                        <pathelement path="${lib.dir}/ashley-1.7.0.jar" />
                        <pathelement path="${lib.dir}/gdx-box2d.jar"/>
                        <pathelement path="${lib.dir}/gdx-box2d-natives.jar"/>
                        <pathelement path="${libs.dir}/box2dlights-1.5-SNAPSHOT.jar"/>
                </classpath>

**Comment by dimecoin** [comment]
My apologizes, it looks like this is a non-issue.  Not sure what was going on, but think it was file permission issues.  (I wrote you a test case/build, but worked fine).
