### ISSUE TITLE
Powering off Xbox controller is ignored by gdx-controllers extension

### ISSUE THREAD

**Issue by MyRealityCoding** [libgdx/libgdx#3706]
When calling `Controllers.getControllers()` in the render code and check for the size (number of controllers plugged in) it doesn't change when I plug out/power off the controller.

This gets problematic when implementing support for dynamic controller plugging.

**Comment by intrigus** [comment]
This is a known issue. Should be fixed, if you switch to LWJGL 3.

**Comment by MyRealityCoding** [comment]
Ah thanks!
