### ISSUE TITLE
TexturePacker exception message doesn't contain the filename

### ISSUE THREAD

**Issue by goph-R** [libgdx/libgdx#3707]
When there is a problem with an image, I don't know which image have caused the error. Could use something like above to avoid this?

TexturePacker.java 635. line:
throw new RuntimeException("Error packing images. (The last processed image was: " + input + ")" , ex);

Thank you!

**Comment by xoppa** [comment]
Would it be possible for you to send a pull request for this?

**Comment by intrigus** [comment]
I have looked at TexturePacker and I think the exception message should include the filename, do you have a [SSCCE](http://sscce.org) that shows the issue?

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info
