### ISSUE TITLE
Add ability to allow 'software mode' rendering in LWJGL 3 backend.

### ISSUE THREAD

**Issue by me4502** [libgdx/libgdx#3711]
The previous LWJGL backend allowed the option of allowing 'software mode' rendering. This is useful in cases where you are making software with LibGDX that is not very graphics intensive, and you want to regain maximum compatibility.

**Comment by badlogic** [comment]
That was true for fixed function OpenGL. Since libGDX abandoned fixed function a few years ago, that can't be done anymore, no matter the backend.

**Comment by me4502** [comment]
So this no longer works in LibGDX's LWJGL 2 backend?

**Comment by badlogic** [comment]
It still works until you use any rendering classes as they rely on
programmable shaders. You can directly use OpenGL 1.1 via the LWJGL API in
that case.
