### ISSUE TITLE
scene2d/ui: problem extending  package classes

### ISSUE THREAD

**Issue by voidburn** [libgdx/libgdx#3712]
When having to customize a widget or component, sometimes even small changes ( lately happened with the Window class, when I needed the titleTable to take into account the font size in the titleLabel ) I found it impossible to extend the class and apply the changes by overriding the methods, due to the fact that almost every useful field is private.

This so far has lead me to creating my own class dumping all the original class code in there and swapping all instances of the component/widget with my own. This feels really really wrong for massive classes such as ScrollPane and Window, and makes it difficult to track and integrate fixes from the upstream.

Could this be made more flexible by making the fields protected instead of private? Any suggestions for better dealing with this otherwise?

**Comment by ShibaBandit** [comment]
Yes I've also had problems with this. I've had to basically copy the source into new classes that are extensible. I think the scene2d ui classes should either be marked final or change them to be extendable.

**Comment by NathanSweet** [comment]
Exposing everything as public API would increase the chance that your app breaks when libgdx changes. It's better to define what is exposed, so we try not to expose things needlessly. There's no good solution either way. If what you need is generally useful, please consider a PR to make it customizable. Keep in mind we may not want to introduce a lot of complexity for a seldom used feature. If you are doing extensive or application specific changes, copy/pasting a scene2d class is reasonable.
