### ISSUE TITLE
Using setFontScale has undesired effect post v1.7.1

### ISSUE THREAD

**Issue by ebbybeh** [libgdx/libgdx#3713]
My font was fine in 1.7.1. When using setFontScale(0.5f) my font looked like this: 
![image](https://cloud.githubusercontent.com/assets/1280342/12206678/7fdaade2-b5ff-11e5-8aa9-c415eaac34f6.png)

Now, after upgrading to 1.7.2, it looks like this: 
![image](https://cloud.githubusercontent.com/assets/1280342/12206720/b5fce1ce-b5ff-11e5-98c9-630b2b1a7e74.png)

Scaling down in general seems to look bad.

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info
