### ISSUE TITLE
OpenGL Timer Query support ?

### ISSUE THREAD

**Issue by JorenJoestar** [libgdx/libgdx#3714]
Hello there,
   I was wondering if you have plan to add Timer Query support, many times when developing GPU features it is helpful to know the exact timing!

Thank you!

**Comment by xoppa** [comment]
Afaik gles2 doesn't support timer queries. Please include the required information for your feature request: https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md#feature-requests. Or consider sending a pull request.
