### ISSUE TITLE
backgroundFPS affecting foreground framerate

### ISSUE THREAD

**Issue by vmilea** [libgdx/libgdx#3715]
With non-continuous rendering over LWJGL backend, the foreground app could end up in a busy loop (main loop keeps hogging CPU without updating display).

Relevant code in `LwjglApplication.mainLoop()` :

    if (!isActive && graphics.config.backgroundFPS == -1) shouldRender = false;
    int frameRate = isActive ? graphics.config.foregroundFPS : graphics.config.backgroundFPS;
    if (shouldRender) {
        graphics.updateTime();
        graphics.frameId++;
        listener.render();
        Display.update(false);
    } else {
        // Sleeps to avoid wasting CPU in an empty loop.
        if (frameRate == -1) frameRate = 10;
        if (frameRate == 0) frameRate = graphics.config.backgroundFPS;
        if (frameRate == 0) frameRate = 30;
    }
    if (frameRate > 0) Display.sync(frameRate);

Required setup: non-continuous rendering, v-sync off, `foregoundFPS = 0`, `backgroundFPS = -1`, window active. This ends up with `frameRate = -1`, so `Display.sync()` won't get called.

**Comment by NathanSweet** [comment]
SSCCE
```
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration;

public class BusyLoop extends ApplicationAdapter {
	public void create () {
		Gdx.graphics.setContinuousRendering(false);
	}

	public void render () {
		System.out.println("render");
	}

	static public void main (String[] args) throws Exception {
		LwjglApplicationConfiguration c = new LwjglApplicationConfiguration();
		c.foregroundFPS = 0;
		c.backgroundFPS = -1;
		c.vSyncEnabled = false;
		new LwjglApplication(new BusyLoop(), c);
	}
}
```

`foregroundFPS = 0` means to never sleep when in the foreground. With `setContinuousRendering(false)` this does mean a busy loop, but it is doing what you asked of it. Do you have a suggested fix?

**Comment by vmilea** [comment]
With non-continuous rendering I expected `foregroundFPS = 0` to mean: loop as fast as possible while there are posted events. If there is nothing to do, the library may at least `Thread.sleep(1)` to stop from wasting CPU.

Anyway, it's an edge case, don't mind leaving it closed.
