### ISSUE TITLE
ImageButton not affected by setSize() when up-scaling

### ISSUE THREAD

**Issue by chandruscm** [libgdx/libgdx#3716]
skin = new Skin(atlas); // I have a texture atlas named 'atlas' initialized.
button = new ImageButton(skin.getDrawable("buttonUp"),skin.getDrawable("buttonDown"));

button.setSize(button.getWidth() / 1.5f, button.getHeight() / 1.5f); // This works
button.setSize(button.getWidth() * 1.5f, button.getHeight() * 1.5f); // This does not work

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info
