### ISSUE TITLE
RepeatAction does not work

### ISSUE THREAD

**Issue by Try4W** [libgdx/libgdx#3717]
For example:
image.addAction(Actions.forever(Actions.rotateTo(359.0F, 1.0F)));

Action runs only one time.

**Comment by MobiDevelop** [comment]
Are you sure the action is not repeating or can you just not see any change. Once the actor is rotated to the target rotation, you wouldn't see any change when it rotates from its current rotation to its current rotation.

Perhaps you mean to use rotateBy?

**Comment by Try4W** [comment]
Thanks. I realized my mistake. rotateBy helped in my case.
