### ISSUE TITLE
LWJGL 3 miss ApplicationListener.resize notification when changing between windowed and full screen mode

### ISSUE THREAD

**Issue by titovmaxim** [libgdx/libgdx#3718]
The ApplicationListener.resize is no called during changing between windowed and full screen mode by calling Gdx.graphics.setFullscreenMode and Gdx.graphics.setWindowedMode. Also tap events starts to report wrong coordinates. Version: libgdx 1.8.0 & lwjgl 3.0.

The temporal solution which works is to call Gdx.app.getApplicationListener().resize explicitly after every full screen <-> windowed change.

**Comment by badlogic** [comment]
Thanks for reporting, i fixed the resize issue. Could you please open a separate issue for the tap coordinate issue? I could not reproduce it.

**Comment by titovmaxim** [comment]
I believe tap problems should be ok now (stage will receive .resize event).
