### ISSUE TITLE
gdx-backend-lwjgl3 build error

### ISSUE THREAD

**Issue by vmilea** [libgdx/libgdx#3720]
When trying to build libgdx, `ant -f fetch.xml && ant` fails at Lwjgl3Net.java because of missing Apple extensions.

    [javac] e:\dev\libgdx\backends\gdx-backend-lwjgl3\src\com\badlogic\gdx\backends\lwjgl3\Lwjgl3Net.java:23: error: package com.apple.eio does not exist

**Comment by badlogic** [comment]
Thanks for reporting, we are missing the Apple extensions jar in the Ant build. Will fix it.
