### ISSUE TITLE
PolygonSprite:  setRegion uses mutable Color instance without resetting to vertex values

### ISSUE THREAD

**Issue by bryanwagner** [libgdx/libgdx#3722]
In PolygonSprite, `getVertexColor` should be called inside `setRegion` before using the mutable `Color` instance, otherwise the color can be modified by side-effects.

Example:

``` java
import com.badlogic.gdx.*;
import com.badlogic.gdx.Input.Keys;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.graphics.*;
import com.badlogic.gdx.graphics.g2d.*;

public class BarebonesBatch extends ApplicationAdapter {
    PolygonSpriteBatch batch;
    Texture texture;
    PolygonRegion region;
    PolygonSprite sprite;

    public void create () {
        batch = new PolygonSpriteBatch();
        texture = new Texture(Gdx.files.internal("data/badlogic.jpg"));
        region = new PolygonRegion(new TextureRegion(texture), new float[] { 0, 0, 0, 100, 100, 100 }, new short[] { 0, 1, 2 });
        sprite = new PolygonSprite(region);
        sprite.setColor(0, 1, 0, 1);
    }

    public void render () {
        // Example:  calling getColor and modifying it causes a side-effect
        if (Gdx.input.isKeyJustPressed(Keys.SPACE)) {
          Color color = sprite.getColor();
          color.set(1, 0, 0, 1);  // only setColor should actually change the color
          //sprite.getVertexColor();  // fix: getVertexColor should be called inside setRegion
          sprite.setRegion(region);
        }
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        batch.begin();
        sprite.draw(batch);
        batch.end();
    }

    public static void main (String[] args) throws Exception {
        new LwjglApplication(new BarebonesBatch());
    }
}
```

**Comment by Darkyenus** [comment]
This might be intentional, see somewhat similar issue #3380

**Comment by bryanwagner** [comment]
See the Javadoc for `setColor`, the above example contradicts it:

```java
/** Returns the color of this sprite. Changing the returned color will have no affect, {@link #setColor(Color)} or
 * {@link #setColor(float, float, float, float)} must be used. */
public Color getColor () {
	return color;
}
```

**Comment by Darkyenus** [comment]
In that case either the code or javadoc is probably wrong.

**Comment by Tom-Ski** [comment]
The problem is that `setRegion` is resetting the vertex colours to the current Color instance value, which is mutable.  This is why in your example (where you `setRegion` in render) you see the colour changing.  I'd suggest adding a cache for the float packed vertex color, and using that when setRegion is called, or just add the documentation warning to the setRegion method.  

That said, you shouldn't really be calling setRegion before every render.

**Comment by bryanwagner** [comment]
I actually didn't run into this as a problem, I just noticed it's a bug in the source of [PolygonSprite](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g2d/PolygonSprite.java).  It's very clear from the source and Javadoc that returning the member variable `color` is designed to avoid an unnecessary reallocation of a Color instance.  Internally, the class works with the `vertices` array which is ready to send to `PolygonSpriteBatch` and is externally unmodifiable.  The bug is here:

```
// Set the color and UVs in this sprite's vertices.
float[] vertices = this.vertices;
for (int i = 0, v = 2, n = regionVertices.length; i < n; i += 2, v += 5) {
	vertices[v] = color.toFloatBits();  // assumes color has not been modified externally
	vertices[v + 1] = textureCoords[i];
	vertices[v + 2] = textureCoords[i + 1];
}
```

This snippet from `setRegion` assumes the `color` instance has not been modified.  My example contradicts this assumption and the Javadoc for the `getColor` method by introducing a side effect that leaks into the `vertices` array in this snippet.  A fix is very simple and would prevent side effects caused by external mutation of the color instance:

```
// Set the color and UVs in this sprite's vertices.
float[] vertices = this.vertices;
getVertexColor();
for (int i = 0, v = 2, n = regionVertices.length; i < n; i += 2, v += 5) {
	vertices[v] = color.toFloatBits();
	vertices[v + 1] = textureCoords[i];
	vertices[v + 2] = textureCoords[i + 1];
}
```

The reason this fixes the issue is because of this line, which reads the actual color value from the `vertices` array and subsequently restores the values in the local color instance:
```
int intBits = NumberUtils.floatToIntColor(vertices[2]);
```

Since we're assuming single-threaded access, we can continue sharing this `Color` instance internally and externally, but this change disallows me from externally modifying the `vertices` array by side effects.

**Comment by cypherdare** [comment]
Aside from contradicting the `getColor` docs, `setRegion()` should not be doing anything to the color in the first place. The docs don't say it will. It's unexpected. It would be convoluted for someone to want to change the color simultaneously when setting a new region, and to do so they use `getColor().set()` before calling `setRegion()`. Also, it doesn't match what Sprite does--Sprite doesn't reset the color when calling `setRegion()`.

**Comment by cypherdare** [comment]
Never mind, I see why color has to be reapplied. We might be creating a new vertex array.
