### ISSUE TITLE
gdx-tools should not reference gdx-backend-lwjgl directly

### ISSUE THREAD

**Issue by darkfrog26** [libgdx/libgdx#3726]
I am trying to switch from gdx-backend-lwjgl to gdx-backend-lwjgl3 and it's still pulling in gdx-backend-lwjgl because of the reference in gdx-tools to it.  This is a problem since I am using tools in my application (BitmapFontWriter to create font caches).

**Comment by darkfrog26** [comment]
https://github.com/libgdx/libgdx/blob/master/extensions/gdx-tools/pom.xml#L22

**Comment by cypherdare** [comment]
BitmapFontWriter is (almost?) the only class from tools that would ever be used in a core project. Can the class simply be moved to the core util package?

**Comment by badlogic** [comment]
Gdx-tools has a hard dependency in LWJGL2, as LWJGL3 doesn't support Swing/AWT. Until we find a solution for this dependency on Swing/AWT, this can't be fixed.
