### ISSUE TITLE
Fonts in LibGDX1.8

### ISSUE THREAD

**Issue by Trurl101** [libgdx/libgdx#3727]
Some issues I found with the fonts/labels in LibGDX 1.8

If I use very large size for a freetype font (like above 300px) the fonts is messed up. Some char textures are displaced. It seems this happens only when the font size is so big that more than one 1024x1024 texture is used for the character texture.

If I use scene2D label with an empty string the font data is messed up for all Labels created after that (fonts appear invisible or displaced).

**Comment by oliveti** [comment]
Hi,

I've got the same issue, have you found a workaround for this ?

**Comment by Trurl101** [comment]
I don't know a workaround other than the obvious: Not using very large font with many characters involved and check a string before using it with a label.

Happily these bugs made me aware of the fact how unnecessary it is to use a very large font size, at least for my projects. The font size in my current app depended on screen resolution but for todays very large resolution on high end devices such large fonts sizes are redundant, because there is no visible difference between a large and very large font size. So I made the font creation more "intelligent" (with a max font size) and the font drawing respectively label creation font size independent (with label scaling depending on screen resolution).

**Comment by JFixby** [comment]
https://github.com/libgdx/libgdx/issues/3525

**Comment by intrigus** [comment]
@Trurl101 Is this issue LibGDX 1.8.0 specific? Does it work on older libGDX versions?

**Comment by JFixby** [comment]
I think it is not an issue.

**Comment by Trurl101** [comment]
I first encountered this problem with LibGDX1.8 it is still there with 1.9.1. I don't know if this happens on older versions.

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info
