### ISSUE TITLE
Gdx.input.setCursorPosition bug when catched [LWJGL 3]

### ISSUE THREAD

**Issue by MrJavaFrank** [libgdx/libgdx#3732]
With the new LWJGL 3 backend the `Gdx.input.setCursorPosition(x, y)` method works fine as long as the cursor isn't catched. However when the cursor is catched, it behaves really weird. So it is always near the position i want it to be, but never exactly at the position.
Here the releveant code snippet to test :

``` java
public class CursorTest extends ApplicationAdapter implements InputProcessor {
    boolean holdMouse;

    @Override
    public void create () {
        Gdx.input.setInputProcessor(this);
    }

    @Override
    public void render () {
        if(holdMouse) { 
            Gdx.input.setCursorPosition(100, 100);
        }
        Gdx.app.log("Mouse Position", Gdx.input.getX() + ", " + Gdx.input.getY());
    }

    @Override
    public boolean keyDown(int keycode) {
        if(keycode == Keys.C) Gdx.input.setCursorCatched(!Gdx.input.isCursorCatched());
        if(keycode == Keys.M) holdMouse = !holdMouse;
        return false;
    }
    ...
}
```

[Desktop, Java 8 Update 66 (64 Bit), libGDX 1.8.0/1.8.1-SNAPSHOT with the LWJGL 3 backend, Windows 10]

**Comment by MrJavaFrank** [comment]
Today I tested this on Linux (Ubuntu), and recognized, that this bug also happens, when the cursor is not catched (on Linux, on Windows it works) ... However, the cursor is positioned in the right way, but the mouseX and mouseY variables are not updated when the 'setCursorPosition' method is called, so that the variables do not point to the actual position of the cursor anymore. I hope that helps, fixing this issue :)

**Comment by crykn** [comment]
> However when the cursor is catched [...] it is always near the position i want it to be, but never exactly at the position.

I can confirm that this behaviour still happens, but I'm wondering whether there is even a reason to use both `setCursorPosition(x, y)` and `setCursorCatched(true)`. Usually (e.g., for FPS games), catching the cursor should be enough. I realise that you opened this issue nearly 5 years ago, but did you have any good reason to use both of those methods _together_?

**Comment by crykn** [comment]
After further investigation, this _does_ happen in LWJGL 3-only apps as well, but only if a `GLFWCursorPosCallback` is used and not `glfwGetCursorPos`. If anyone stumbles upon this issue in the future and the above-mentioned workaround does not suffice, consider reporting this to the [LWJGL 3](https://github.com/LWJGL/lwjgl3) or the [GLFW](https://github.com/glfw/glfw) project.
