### ISSUE TITLE
TV remote gamepad profile support for tvos

### ISSUE THREAD

**Issue by cobolfoo** [libgdx/libgdx#3733]
I would really like to have gamepad profile supported in robovm for tvos, I want to port my game (http://store.steampowered.com/app/412230/) to it but I need at least 2 buttons to be supported (jump, crouch) along the dpad.

So far, the TV remote generates touchUp, touchDown and touchDragged events, which is great but it will not make the difference between a click on the touchpad andr a simple swipe. The other buttons do not generate anything.

Here is what I have done so far. 
- I added 2 frameworks to robovm.xml:
  <framework>CoreBluetooth</framework>
  <framework>GameController</framework>
- When I run the game I do that (after intialization):
  if (GCController.getControllers().size() > 0) {
            controller = GCController.getControllers().first();
            System.out.println("CONTROLLER:" + controller);
            System.out.println("VENDOR NAME:" + controller.getVendorName());
            System.out.println("ATTACHED?:" + controller.isAttachedToDevice());
            System.out.println("PLAYER INDEX:" + controller.getPlayerIndex());
            System.out.println("GAMEPAD EXTENDED: " + controller.getExtendedGamepad());
            System.out.println("GAMEPAD:" + controller.getGamepad());
  }

I detect 1 controller, which is a Remote (vendor name),  attached is false, player index is not set. 
Both gamepad and extended gamepad are NULL.

It looks like to me that robovm needs to implement GCMicroGamepad. https://developer.apple.com/library/tvos/documentation/GameController/Reference/GCMicroGamepad_Ref/index.html

But again I don't have access to robovm source. Maybe all the controller stuff is full of stub functions :)

It is possible to extends the current GCController class than use the BRO thing to add support for GCMicroGamepad?

**Comment by MrStahlfelge** [comment]
You can use gamepads on iOS by using the module from controllerutils lib (see Controllers wiki article).
