### ISSUE TITLE
Android networking code fails on numerous devices on WIFI if domain name is resolved to an IPv6 address

### ISSUE THREAD

**Issue by JavaNoobsyBoobsy** [libgdx/libgdx#3736]
We have a networked game communicating with servers using HTTP. We have received dozen of complaints of players not being able to connect to the server. 

The issue is 100% reproductible 
IF your network receives an IPv6 AND
IF you have an Android device with OS < 4.3 (possibly also affects newer devices).

The current network implementation for Android fails immediately in `NetJavaImpl.sendHttpRequest`
The reason is because a time out value is set on the connection. If a timeout value is set on the connection, the call to `connection.connect()` fails immediately (1 sec.) instead of exhausting the timeout value (30,000 = 30 sec.) if an IPv6 is provided by the network.
error: "failed to connect to game.uniwar.com/2600:3c00::f03c:91ff:fea8:53af (port 80) after 30000ms"
despite what this message says, it fails immediately.

*NOT CALLING the method below fixes the problem*.
`connection.setConnectTimeout(httpRequest.getTimeOut());`
I suggest to remove this line from the Android implementation or to change the API to have 2 time out setters one for the connection & one for the read. Anyway, I am not even sure if Android implements a timeout on the connection...

I am wondering if the Android implementation is buggy. When failing to connect to IPv6 address, it will not try to connect to IPv4 as it should. The internal Android Implementation does not seem to follow the contract described below:

[Android spec URLConnection](http://developer.android.com/reference/java/net/URLConnection.html#setConnectTimeout(int))

Some posts from [Google suggesting that their implementation might be broken](https://code.google.com/p/android/issues/detail?id=40874)

**Comment by JavaNoobsyBoobsy** [comment]
I am not sure where I can find the C or Java from the Android implementation that deals with the connection time out value but if we find it. We should be able to understand the cause of the bug. It would be useful to know how widespread this issue is in term of the Android OS versions. If more and more ISP start to roll IPv6 addresses in name resolutions, then this issue might become more and more widespread if it is caused by the buggy implementation that deals with IPv6.

**Comment by JavaNoobsyBoobsy** [comment]
_Issue & Workaround have been confirmed on the following devices: (Manufacturer, Device, OS)_
Motorola	Droid X4 (XT984)	4.1.2
Motorola	RazrI	4.1.2
blu	Quattro 4.5	4.0.4
HTC	One V	4.0.3
Samsung 	GT-I9100 SGS2	4.1.2
Huawei	Ascend Y300	4.1.1
Samsung	Google Nexus S - Dev Ed.	4.1.2

_Issue confirmed but workaround failing on:_
Motorola	Droid X2	2.3.5
Samsung 	Fascinate	2.3.5
Amazon	Kindle Fire (2nd gen)	2.3.4

_Issue not happening on:_
Motorola	Nexus 6	5
Amazon	Fire HD 6 (4th gen)	4.4
HTC	One	4.3
HTC	Desire 820	5.0.2
Samsung	I747 SGS3	4.4.2
Motorola	E (XT1528) 2nd gen	5.1
Samsung	Galaxy S6	5
Samsung	Galaxy S5	4.4
Motorola	X (XT1060)	5.1.0
Amazon	Fire HDX 7 (3rd gen)	4.4.3
Kyocera 	Event	4.0.4

**Comment by JavaNoobsyBoobsy** [comment]
Apparently, it's just luck that it worked on devices with OS >= 4.3 because some players are reporting the issue on:
Samsung Galaxy S6 Edge running Android 5.1.1
Samsung Galaxy Note 5 with 5.1.1

It seems that Android devices have a broken IPv6 implementation (which would fine if it would gracefully switch to IPv4 as requested by the spec).
Similar issue related to IPv6 are explained here:
https://code.google.com/p/android/issues/detail?id=79576
https://code.google.com/p/android/issues/detail?id=3389
https://code.google.com/p/android/issues/detail?id=32621&q=ipv6&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars
https://code.google.com/p/android/issues/detail?id=32662

**Comment by badlogic** [comment]
There's sadly nothing we can do about this. We merely use the standard Java
classes for networking.

**Comment by JavaNoobsyBoobsy** [comment]
Did you notice that the bug does not happen IF the 'connection.setTimeOut()' is not being called because in that case, the phone gracefully switches to IPv4?
That's why I am calling to make that changes. I currently have deployed production versions with that fix.

**Comment by xoppa** [comment]
Perhaps you can send a PR with the suggested change?

**Comment by JavaNoobsyBoobsy** [comment]
The patch that I wrote fixes the issue only on some devices (4.x to 4.3). Due to the limited benefit of it, it is not worth doing a PR. We can close this issue. There is simply NO WAY to have an IPv6 server now that communicates correctly with Android devices (even OS 6.0.1 has issues causing slow communication of 30+ seconds when the server responds in less than 10 millis).

**Comment by OrOrPe** [comment]
Hi, Some of our users are experiencing this issue, @JavaNoobsyBoobsy did you manage to solve it entirely by removing connection.setTimeOut()?
Btw, from my research, it seems that this bug started with version 1.8 of Libgdx.
I couldn't find anything directly related to the Net implementation between 1.7.2 to 1.8 except one method which only happens on the GWT implementation.

One other change I found which I'm not sure related, is a change in the android build tools from 23 to 25 on the Gradle dependencies.

I'm really desperate to fix this, as this wasn't an issue before 1.8.
Do you have any new ideas about it that weren't mentioned here?

Thanks,
