### ISSUE TITLE
HTML sample compile error

### ISSUE THREAD

**Issue by slajar** [libgdx/libgdx#3737]
I just downloaded the samplecode by gdx-setup.jar and ran desktop --> worked. After that I ran the gradle compileGwt task and it gives:

<code>
[ERROR] Unable to find 'com/artemis/backends/artemis_backends_gwt.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?
</code>

It seems that html compile is broken.

**Comment by MobiDevelop** [comment]
Artemis has nothing to do with libgdx and is not referenced anywhere by the setup, did you add it yourself? If not, which third party extensions did you choose?

**Comment by slajar** [comment]
no, I have never installed Artemis. Actually, I don't know what it is ;)

**Comment by slajar** [comment]
here is a more deatiled command line output:

./gradlew checkGwt
Configuration on demand is an incubating feature.
:core:compileJava UP-TO-DATE
:core:processResources UP-TO-DATE
:core:classes UP-TO-DATE
:core:jar UP-TO-DATE
:html:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
:html:processResources UP-TO-DATE
:html:checkGwt
Loading inherited module 'com.mygdx.game.GdxDefinition'
   Loading inherited module 'com.kotcrab.vis.vis-runtime'
      Loading inherited module 'com.artemis.backends.artemis_backends_gwt'
         [ERROR] Unable to find 'com/artemis/backends/artemis_backends_gwt.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?
      [ERROR] Line 29: Unexpected exception while processing element 'inherits'

**Comment by MobiDevelop** [comment]
OK, so it looks like the maintainer of the VisRuntime extension depends on artemis and doesn't declare this dependency. You should report that to the maintainer of VisRuntime so they can fix it.

**Comment by davebaol** [comment]
Closing this

**Comment by slajar** [comment]
Pavel says that the comfiguration is not correct: https://github.com/kotcrab/VisEditor/issues/118#issuecomment-171997745

Well, I did just use the Project Generator. Isn't it meant to compile out of the box?

**Comment by kotcrab** [comment]
In this case, no. Gdx-setup can't add external dependency to other modules. (`artemis-odb-gwt` in this case) For this reason additional configuration is required for html module. This was also discussed [here](https://github.com/libgdx/libgdx/pull/3537#issuecomment-156844608).
