### ISSUE TITLE
Typo explicitely instead of explicitly

### ISSUE THREAD

**Issue by adam4813** [libgdx/libgdx#3739]
This is in a few files https://github.com/libgdx/libgdx/search?utf8=%E2%9C%93&q=explicitely

I don't have time to issue a patch at this minute with the Jam and all, but I can do it afterwards.

**Comment by adam4813** [comment]
Why close before a patch or pr is submitted?

**Comment by davebaol** [comment]
Because apart from `issues.txt` they're fixed.

**Comment by adam4813** [comment]
Ah ok then I won't bother making a pr.
