### ISSUE TITLE
Bug. AssetManager doesn't decrement the variable toLoad on asset load failed.

### ISSUE THREAD

**Issue by AdrianNostromo** [libgdx/libgdx#3741]
If I load a bitmap font that doesn't exist, the function `handleTaskError` from `AssetsManager` is called but the variable `toLoad` from `AssetsManager` is never decremented.
Also because cleanup occurred, `unload` will not fix this.

Example code:
```
assetsManager.load("ExampleFont.fnt", BitmapFont.class);
try {
    assetsManager.update(100);
}catch(GdxRuntimeException e) {
    // Exception is caught here but assetsManager.toLoad will remain 1 and assetsManager.loaded will remain 0.
}
```

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info
