### ISSUE TITLE
BitmapFont draws out of bounds when first character has negative xoffset

### ISSUE THREAD

**Issue by geertjan-apptornado** [libgdx/libgdx#3755]
Since libGDX version 1.7.2, `BitmapFont` draws out of bounds when the first character has a negative `xoffset`. Version 1.7.1 does not show this issue.

Here is an example app showing a `Label` with a red background:

![example](https://cloud.githubusercontent.com/assets/5756227/12483853/8cc2852c-c057-11e5-8e82-a55941fe1c48.png)

``` java
public class TestGame extends ApplicationAdapter {
    private Stage stage;
    private BitmapFont font;

    @Override
    public void create() {
        font = new BitmapFont(Gdx.files.internal("Chewy_80.fnt"));
        font.getRegion().getTexture().setFilter(TextureFilter.Linear, TextureFilter.Linear);

        Pixmap pixmap = new Pixmap(1, 1, Pixmap.Format.RGBA8888);
        pixmap.setColor(Color.RED);
        pixmap.fill();
        Texture texture = new Texture(pixmap);
        pixmap.dispose();

        LabelStyle style = new LabelStyle(font, Color.WHITE);
        style.background = new TextureRegionDrawable(new TextureRegion(texture));

        Label label = new Label("Test", style);
        label.setPosition(32, 32);

        stage = new Stage(new FitViewport(200, 200));
        stage.addActor(label);
    }

    @Override
    public void resize(int width, int height) {
        stage.getViewport().update(width, height, true);
    }

    @Override
    public void render() {
        Gdx.gl.glClearColor(0.5f, 0.5f, 0.5f, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

        stage.act();
        stage.draw();
    }

    @Override
    public void dispose() {
        stage.dispose();
        font.dispose();
    }
}
```

I also included the bitmap font used for this test: [Chewy_bitmap.zip](https://github.com/libgdx/libgdx/files/99316/Chewy_bitmap.zip)

I'm not sure whether this is related to issue #3472, but if it is, this still seemed to be worth a separate bug report.

_[EDIT] Updated after finding out which libGDX version exactly changed this._
_[EDIT2] Simplified example code a bit._

**Comment by NathanSweet** [comment]
Glyph run bounds in the latest code look correct:
![](http://n4te.com/x/2045-K2fx.png)

In the repro code it seems it's 1px out of bounds, maybe some rounding or filtering? Not sure it's a problem.
![](http://n4te.com/x/2046-Y15W.png)
