### ISSUE TITLE
Lifecycle listener not called when a Timer is used

### ISSUE THREAD

**Issue by xoppa** [libgdx/libgdx#3758]
The [Timer.TimerThread](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/Timer.java#L289) class removes itself as listener in the `dispose` method, which is called in an [enhanced for loop](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGraphics.java#L477-L479) in `AndroidGraphics` . This causes the next lifecycle listener in the array not to be called.

**Comment by badlogic** [comment]
Uhm, i assume it doesn't get called because the dispose/remove causes an exception? In any case, we should make a copy of the listeners there for this case, just like we do with Runnables et al.

**Comment by xoppa** [comment]
For reference, here is a test case:

```java
public class LifeCycleTest extends GdxTest {

	@Override
	public void dispose () {
		Gdx.app.log("Test", "app destroyed");
	}

	@Override
	public void pause () {
		Gdx.app.log("Test", "app paused");
	}

	@Override
	public void resume () {
		Gdx.app.log("Test", "app resumed");
	}

	@Override
	public void render () {
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
	}

	@Override
	public void create () {
		Gdx.app.log("Test", "app created: " + Gdx.graphics.getWidth() + "x" + Gdx.graphics.getHeight());
		Timer.schedule(new Task() {
			@Override
			public void run () {
				Gdx.app.log("Hello", "world!");
			}
		}, 0.1f, 1f);
		for (int i = 0; i < 10; i++) {
			final int idx = i;
			Gdx.app.addLifecycleListener(new LifecycleListener() {
				@Override
				public void pause () {
					Gdx.app.log("Test", "pause listener: " + idx);
				}

				@Override
				public void resume () {
					Gdx.app.log("Test", "resume listener: " + idx);
				}

				@Override
				public void dispose () {
					Gdx.app.log("Test", "dispose listener: " + idx);
				}
			});
		}
	}

	@Override
	public void resize (int width, int height) {
		Gdx.app.log("Test", "app resized: " + width + "x" + height + ", Graphics says: " + Gdx.graphics.getWidth() + "x"
			+ Gdx.graphics.getHeight());
	}
}
```

Removing the Timer.schedule shows that the difference. I'll commit the fix soon.

**Comment by xoppa** [comment]
Fixed it by using `SnapshotArray` for lwjgl and android. I noticed that the GWT, Lwjgl3 and Robovm backends don't call dispose on the listeners at all.
