### ISSUE TITLE
Running a game on an extended desktop

### ISSUE THREAD

**Issue by ajaychandran** [libgdx/libgdx#3759]
Is it possible to (automatically) launch a LibGdx app that spans an extended monitor with 2 (or more) monitors?

I have a workaround that creates 2 separate windows using the new LWJGL3 backend but this presents some challenges of its own.
1. The game logic is now split across two different applications.
2. Additional "wiring" is required for communicating between both windows.

**Comment by badlogic** [comment]
No, fullscreen APIs only work on one  (logical) monitor. Your OS must support joining extended monitors to one (logical) monitor.
