### ISSUE TITLE
Gdx.input.getX() does not return the last pointer coordiante

### ISSUE THREAD

**Issue by azakhary** [libgdx/libgdx#3760]
The comment on the method says:

```
/** @return The x coordinate of the last touch on touch screen devices and the current mouse position on desktop for the first
	 *         pointer in screen coordinates. The screen origin is the top left corner. */
	public int getX ();
```

But when tested, getX() does not return the Last touch as it says it will.

Steps to reproduce.

1) Have a code that outputs Gdx.input.getX() on every frame
2) press somewhere on the left side of the screen with one finger, loop will start outputting small number
3) while holding prev finger press on the right side of the screen. because it's the latest touch, then getX should start returning a bigger number, but instead it still returns the coordinate of prev finger.

Is there something wrong I am doing?

I was trying to avoid this, by using  something like getX(pointer), but I also see no way to get what was the "last" pointer. I was looking if there was a method that I can use to retrieve a current last pointer when the justTouched is true, but could not find anything similar as well. Now I am kind of forced to implement code to keep track of pointers and see which one got "dissapeared" or "appeared" to be sure which one is last. But this seems like a wrong way to do it.

**Comment by azakhary** [comment]
I can do PR to change the comment on the method. If everyone is ok with this.

**Comment by badlogic** [comment]
Yes, please do. Closing this out.

**Comment by intrigus** [comment]
Shouldn't we fix the method instead of changing the javadoc/comment? Or did I understand something wrong?
