### ISSUE TITLE
RoboVM REGRESSION: iOS Release builds crashes with NPE on non null final instances since LibGDX 1.8.0, RoboVM 1.12.0

### ISSUE THREAD

**Issue by JavaNoobsyBoobsy** [libgdx/libgdx#3765]
The same code used to work with prior versions of LibGDX and RoboVM. Same code works fine in DEBUG mode, it crashes in release mode on both the Simulator (iPhone-5s - 9.2 on x86_64) and on devices (iPod *, iPhones *).

* Is there any limitation with RoboVM in term of using final keywords or anonymous inner class?
* Is it possible that the instance got GC'ed due to a specific GC implemented in RoboVM that would not respect the JVM GC behavior? Is it a mark & sweep implementation that takes into account final variables assigned

Here is the stacktrace of code that leads to NPE:

java.lang.NullPointerException
	at uniwar.scene.game.CreateCustomOnlineGameScene$12.run(CreateCustomOnlineGameScene.java:390)
....

    private void gameCreatedSuccessfully(final NewGame newGame) {
        final DialogScene scene = DialogScene.getInfoScene(Texts.GAME_SUCCESSFULLY_CREATED);
        scene.actionToPerformOnDismiss = new Runnable() {
            @Override
            public void run() {
                scene.removeScene();
                if (newGame.saveRequested) { // <== CAUSES NPE but newGame is not null
                    newGame.setAllPlayerSeats(GamePlayer.Seat.OPEN);
                    newGame.save();
                }
                Stage.setScene(canvas.currentGamesScene);
            }
        };
        Stage.pushScene(scene);
    }

    private void createGame() {
        newGame.name = nameSprite.textField.getText();
        if (newGame.name.length() <= 0) {
            DialogScene.showErrorScene(Texts.INVALID_GAME_NAME);
            return;
        }
        if (newGame.saveRequested) {
            newGame.save();
        }
        final CommandCreateGame command = new CommandCreateGame(newGame);
        command.addListener(new CommandResultListener() {
            @Override
            public void commandPerformed(boolean success) {
                if (success) {
                    canvas.currentGamesScene.requestDownload();
                    gameCreatedSuccessfully(command.newGame); // command.newGame is final too
                }
            }
        });
        command.showScene();
    }

**Comment by JavaNoobsyBoobsy** [comment]
using Mac OS X El Capitan 10.11.2
using Xcode 7.2 (7C68)

**Comment by intrigus** [comment]
I'd suggest creating a SSCEE.org and creating a new issue [https://github.com/robovm/robovm](here)

**Comment by badlogic** [comment]
Please refrain from making your titles obnoxious... As @intrigus please provide an SSCCE.

**Comment by JavaNoobsyBoobsy** [comment]
I  apologize if the comments felt hard. It was not my intention. I know that you guys work really hard on this tech. You are doing an incredible work.
