### ISSUE TITLE
1.9.0 missing resources

### ISSUE THREAD

**Issue by gyulavoros** [libgdx/libgdx#3779]
The latest release adds support for x86_64 and arm64-v8a, but the binary resources are missing, e.g.: [libgdx.so](https://libgdx.badlogicgames.com/nightlies/dist/x86_64/libgdx.so).

**Comment by intrigus** [comment]
Please check the issue tracker before creating a new one. 
See https://github.com/libgdx/libgdx/issues/3777

**Comment by jazn** [comment]
:+1:
