### ISSUE TITLE
touchDown events not firing correctly on Windows 10

### ISSUE THREAD

**Issue by davesb** [libgdx/libgdx#3780]
On Windows 10 using a touchscreen, the touchDown event doesn't get fired until you remove your finger (i.e. fired at the same time as a touchUp). I've confirmed that the touchscreen driver is ok by using an application that came with it - an onscreen piano that captures touchdowns straight away - and sanity-checked with a small JavaFX program that also sees touch down events correctly. Here's a libGDX application that shows this up (for me anyway);

``` java
    package com.test.touch;

    import com.badlogic.gdx.ApplicationAdapter;
    import com.badlogic.gdx.Gdx;
    import com.badlogic.gdx.InputProcessor;
    import com.badlogic.gdx.graphics.GL20;
    import com.badlogic.gdx.graphics.Texture;
    import com.badlogic.gdx.graphics.g2d.SpriteBatch;

    public class TouchTestGame extends ApplicationAdapter implements InputProcessor {
       SpriteBatch batch;
       Texture img;

       @Override
       public void create() {
          batch = new SpriteBatch();
          img = new Texture("badlogic.jpg");
          Gdx.input.setInputProcessor(this);
       }

       @Override
       public void render() {
          Gdx.gl.glClearColor(1, 0, 0, 1);
          Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
          batch.begin();
          batch.draw(img, 0, 0);
          batch.end();
       }

       @Override
       public void dispose() {
          batch.dispose();
       }

       @Override
       public void resize(int width, int height) {
       }

       @Override
       public void pause() {
       }

       @Override
       public void resume() {
       }

       @Override
       public boolean keyDown(int keycode) {
          return false;
       }

       @Override
       public boolean keyUp(int keycode) {
          return false;
       }

       @Override
       public boolean keyTyped(char character) {
          return false;
       }

       @Override
       public boolean touchDown(int screenX, int screenY, int pointer, int button) {
          System.out.println("touchDown : " + screenX + ", " + screenY);
          return false;
       }

       @Override
       public boolean touchUp(int screenX, int screenY, int pointer, int button) {
          System.out.println("touchUp : " + screenX + ", " + screenY);
          return false;
       }

       @Override
       public boolean touchDragged(int screenX, int screenY, int pointer) {
          System.out.println("touchDragged : " + screenX + ", " + screenY);
          return false;
       }

       @Override
       public boolean mouseMoved(int screenX, int screenY) {
          System.out.println("mouseMoved : " + screenX + ", " + screenY);
          return false;
       }

       @Override
       public boolean scrolled(int amount) {
          System.out.println("scrolled : " + amount);
          return false;
       }
    }
```

So, on Windows 10 with a touchscreen (Viewsonic TD2340) there is no event fired when you put your finger on the screen, and when you take it off a touchDown event is fired followed immediately by a touchUp. The touchDown is also fired if you move your finger (i.e. immediately before the touchDragged).

**Comment by Darkyenus** [comment]
Which libGDX version and which backend? If LWJGL, please try with [LWJGL3](http://www.badlogicgames.com/wordpress/?p=3870).

**Comment by davesb** [comment]
libGDX 1.9.0. It was LWJGL 2, but I've updated the test project (as above) to use LWJGL3 and it still has the same issue. The only difference is that now, when I lift my finger, it's firing a mouseMoved, then touchDown, then touchUp, then another mouseMoved (so extra mouseMoves in front and behind). Nothing is fired when I put my finger on the screen.

**Comment by NathanSweet** [comment]
I think you'll have better luck filing a bug with LWJGL, since libgdx just receives input events from them.

**Comment by skipperalfie** [comment]
I am having the same problem at work. We are trying to get 2 different computers to be able to turn things on and off on a production line. We see it turn on and then off when we remove our finger from the button. The mouse works fine as does the pen but when you touch it it only fires upon releasing the button. We are using a Man Machine Interface so not sure how I would incorporate a LWJGL bug fix into it. 2 of us have been playing with this for 2 days with no luck. Looks like windows once again has put something out there before it was ready (the norm for them)!
