### ISSUE TITLE
Steam Controller doesn't register with gdx-controllers

### ISSUE THREAD

**Issue by xSke** [libgdx/libgdx#3783]
Nothing. It just acts like it's not there.

**Comment by SolarLune** [comment]
How are you running your application? Through Steam?

**Comment by Voltasalt** [comment]
I'm apparently a complete retard.

**Comment by xSke** [comment]
I'm apparently a complete retard. Just had to set the controller preset in *desktop mode* to Xbox Controller.

**Comment by SolarLune** [comment]
Ah. So when you set the desktop configuration to the Gamepad preset, the controller showed up in LibGDX as an Xbox controller?

**Comment by xSke** [comment]
Huh. Seems to be actually broken now. Thoughts?

**Comment by Magnesus** [comment]
Any update on this?

**Comment by intrigus** [comment]
Which backend, which version, which OS?
