### ISSUE TITLE
iOS bundle identifier without the 'IOSLauncher' suffix

### ISSUE THREAD

**Issue by serhii-k** [libgdx/libgdx#3794]
Hi guys,

First thing to mention, I'm a complete newbie to iOS development.

In the ios/robovm.properties generated by the setup app there is a line:
app.id=com.mygdx.game.IOSLauncher

As I understand, this will be used as a bundle identifier in App Store.

However, I don't understand why it has the '.IOSLauncher' suffix. For me, it would be awesome if my app had a bundle identifier just com.mydomain.myapp, without it.

Am I safe to just remove this suffix from the app.id property inside robovm.properties? Maybe somewhere else? What is the intention of this suffix? Maybe it's just a rudimental and should be removed from the setup?

Sorry, if it's something obvious, but I'm confused...

Kind regards,
Serhii

**Comment by Tom-Ski** [comment]
As far as I know you should be OK with just deleting this.  We should remove this from the setup to make the ID a little cleaner, like was done here https://github.com/libgdx/libgdx/commit/816cc0cda01ff5260fcec39e166dcc6cf79dcc3a

@badlogic could you confirm if it is OK to change app.id?

**Comment by badlogic** [comment]
Can confirm

**Comment by serhii-k** [comment]
Thank you very much guys!
