### ISSUE TITLE
Lwjgl3Window "de-minimize" is not working

### ISSUE THREAD

**Issue by ajaychandran** [libgdx/libgdx#3795]
Unable to restore a window with `Lwjgl3Window.deiconifyWindow()` that was minimized using `Lwjgl3Window.iconifyWindow()`.

**System info:**
Linux ***\* 3.19.0-43-generic #49-Ubuntu SMP Sun Dec 27 19:43:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
``

**Comment by badlogic** [comment]
Please provide a test case.

**Comment by ajaychandran** [comment]
@badlogic Created [test](https://gist.github.com/ajaychandran/a0c0a2ac4f95b1fbee10).

**Comment by code-disaster** [comment]
I can not confirm on Windows, test works here as expected. A GLFW platform issue, maybe?

**Comment by NathanSweet** [comment]
Seems good on Windows and Mac OS 10.15.5. Can reopen if still an issue.
