### ISSUE TITLE
Intersector duplicating vertices when overlapping polygon

### ISSUE THREAD

**Issue by azakhary** [libgdx/libgdx#3804]
Intersector:
`public static boolean intersectPolygons (Polygon p1, Polygon p2, Polygon overlap)`

method is working presumably faulty for a specific scenario when intersecting polygons have exactly intersecting vertices, as a result this vertices get duplicated.

Here is an example:
![polytestdiag](https://cloud.githubusercontent.com/assets/2115888/12695409/b3a08cbe-c766-11e5-8f26-125b3b726409.png)

The resulting overlap polygon has A and B vertices duplicated, resulting in a 10 size array of floats.

**Comment by AldousP** [comment]
Will look at this and https://github.com/libgdx/libgdx/issues/3805 in the next few days.

**Comment by AldousP** [comment]
Should be fixed by https://github.com/libgdx/libgdx/pull/3918

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://motocons.com/spite.php?odpp>

 

loogie@basicelementdesign.com
