### ISSUE TITLE
Intersector causes IllegalArgumentException when no overlap happens.

### ISSUE THREAD

**Issue by azakhary** [libgdx/libgdx#3805]
Here at the line 213 of Intersector, when overlapping polygons, if no result is found, it returns the following:

`overlap.setVertices(new float[0])`

Where overlap is a Polygon.

If we look at Polygon class, setVertices method states:
`if (vertices.length < 6) throw new IllegalArgumentException("polygons must contain at least 3 points.");`

Thus resulting in IllegalArgumentException. Instead of returning empty polygon.

**Comment by AlexKopp** [comment]
Also: The method calls `getVertices()` from Polygons p1 and p2, but should call `getTransformedVertices()`. I was going crazy finding this bug xD

**Comment by AldousP** [comment]
Should be fixed by https://github.com/libgdx/libgdx/pull/3918
