### ISSUE TITLE
TextureAttribute has poor extensibility due to non-abstract/interface fields usage and internal mask checking.

### ISSUE THREAD

**Issue by shdwshard** [libgdx/libgdx#3810]
TextureAttribute contains the following field, which I would like to be typed GLTexture instead of Texture:
`	public final TextureDescriptor<Texture> textureDescription;`
The reasoning is that classes such as TextureArray, and others which extend the GLTexture interface can then be passed into Shaders using the existing set(Uniform, TextureDescription) methods, making the overall usage of derived Texture Types much easier and standard to implement.

This change also involves modifying the Generics on the various constructors of TextureAttribute
`	public <T extends Texture> TextureAttribute (...)`

Texture is a poor choice of a superclass because it contains several hard coded GL attributes which don't apply to all types of textures.

Similarly, there should be a way to add to or modify this field, such that additional texture types (Such as Stencils or SplatMaps) can be added.
`	protected static long Mask = Diffuse | Specular | Bump | Normal | Ambient | Emissive | Reflection;`

The CubeMapAttribute and some related classes could be collapsed back into a normal TextureAttribute with these changes.

**Comment by xoppa** [comment]
No, attributes must be well defined an unambiguous. Making them generic would defeat that. `TextureAttribute` is an attribute which specifies a 2d texture. `CubeMapAttribute` is an attribute which specifies a cubemap. Those are two very different things and cannot be treated the same, e.g. you need different glsl code for a 2d texture than you need for a cubemap.
