### ISSUE TITLE
FreeType returning buffer with wrong capacity

### ISSUE THREAD

**Issue by intrigus** [libgdx/libgdx#3811]
[Freetype.getBuffer()](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeType.java#L590) returns a Buffer with a wrong capacity.
@NathanSweet 

How to reproduce:
1. Change

```
public ByteBuffer getBuffer() {
            if (getRows() == 0)
                // Issue #768 - CheckJNI frowns upon env->NewDirectByteBuffer with NULL buffer or capacity 0
                //                  "JNI WARNING: invalid values for address (0x0) or capacity (0)"
                //              FreeType sets FT_Bitmap::buffer to NULL when the bitmap is empty (e.g. for ' ')
                //              JNICheck is on by default on emulators and might have a point anyway...
                //              So let's avoid this and just return a dummy non-null non-zero buffer
                return BufferUtils.newByteBuffer(1);
            return getBuffer(address);
        }
```

to 

```
public static int i = 0;
        public ByteBuffer getBuffer() {
                    if (getRows() == 0)
                        // Issue #768 - CheckJNI frowns upon env->NewDirectByteBuffer with NULL buffer or capacity 0
                        //                  "JNI WARNING: invalid values for address (0x0) or capacity (0)"
                        //              FreeType sets FT_Bitmap::buffer to NULL when the bitmap is empty (e.g. for ' ')
                        //              JNICheck is on by default on emulators and might have a point anyway...
                        //              So let's avoid this and just return a dummy non-null non-zero buffer
                        return BufferUtils.newByteBuffer(1);

                    ByteBuffer b = getBuffer(address);
                    if(i < 1) {
                    for(int k = 0; k < java.lang.Math.min(10000, b.capacity()); k++){
                            System.out.println(b.get(k));
                        }
                                                i++;    
                    }
                    return b;
                }
```
1. Run FreeTypeMetricsTest.
   Save the generated output.
2. Run FreeTypeMetricsTest again.
   Save the generated output.
3. Diff the outputs e.g using https://www.diffchecker.com/
4. The diffs will be the same up to the 1139th(=1140) line. 1140 is exactly `bmp->rows * abs(bmp->pitch)`. The rest of the log (`bmp->rows * abs(bmp->pitch) * bmp->width`) is garbage.

Gdx Version is 1.9.1
OS: Mac OS X El Capitan

See https://github.com/libgdx/libgdx/commit/8578f791a0f8d0813cc0b5381e897bd15e6dbb61#diff-cd2a8e6f2b978bfd546ad39168f00533R645

**Comment by NathanSweet** [comment]
I found only 9 lines different on Windows 10:
![](http://i.imgur.com/QTKV9OZ.png)

If the buffer size is wrong, what is the fix?

**Comment by intrigus** [comment]
The fix would be to restore the old behavior.
This means changing `bmp->rows * abs(bmp->pitch) * bmp->width` back to `bmp->rows * abs(bmp->pitch)`.
But I'm pretty sure that you've had some reasons to alter the behavior.

It would be good if you could explain why you changed the code in the first place :)

**Comment by NathanSweet** [comment]
Sorry for the late response. I'm afraid I don't remember why it was changed. You're right it looks wrong, since pitch is the number of bytes per row.
