### ISSUE TITLE
Batch ,scale,origin

### ISSUE THREAD

**Issue by Vittek1978** [libgdx/libgdx#3814]
Hi.

When drawing TextureRegion with SpriteBatch, and origin set to centre (or != {0,0}),
changing scale shifts image to bottom-left. I can see that in code the corners are scaled but not the origin. Is it a bug? Am I reading this wrong? Will that fix it:

`650/770		final float worldOriginX = x + scaleX == 1 ?  originX : originX * scaleX;`
`651/771		final float worldOriginY = y + scaleY == 1 ?  originY : originY * scaleY;`

Same goes for PolygonSpriteBatch.

Regards,
Mariusz

**Comment by Vittek1978** [comment]
No comments?

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
Please use the forum or IRC if you need help. If you think you found an actual issue then include the required information to reproduce it.
