### ISSUE TITLE
Multi-Viewport/Splitscreen 

### ISSUE THREAD

**Issue by xpenatan** [libgdx/libgdx#3815]
The issue is with this https://github.com/libgdx/libgdx/wiki/Viewports#multiple-viewports
The current way to get splitscreen or multiple viewports to work for stage and/or for 2d/3d 
is to currently do 
```
int offsetX = 0, offsetY = 0;

...

offsetX = 0;
viewport1.update();
viewport1.setScreenPosition(viewport1.getScreenX() + offsetX, viewport1.getScreenY() + offsetY);
viewport1.apply();
// draw
offsetX = Gdx.graphics.getWidth() / 2;
viewport2.update();
viewport2.setScreenPosition(viewport2.getScreenX() + offsetX, viewport2.getScreenY() + offsetY);
viewport2.apply();
// draw

...

```
The problem is that Viewport#update(..) reset screenX, screenY, screenWidth and screenHeight   values for each viewport type and Viewport#apply() use those values to call glViewport(..). The goal is to use any viewport type and still use it as a sub-window/splitscreen but without calling apply multiple times (Viewport#update(..) already calls apply). 

The solution I see is to take away Viewport#apply from all Viewport#update( ) or have a offsetX/offsetY inside viewport class so the code above could change to the one below.
 
```
viewport1.setOffset(0, 0);
viewport1.update(..);
// draw
viewport2.setOffset(Gdx.graphics.getWidth() / 2, 0);
viewport2.update(...);
// draw

```

To move the viewport window to another place (Ex a minimap) you can just update the Viewport#setOffset(..).

![multiviewport](https://cloud.githubusercontent.com/assets/6472084/12753795/aa575656-c9af-11e5-96a2-a651bc683f71.png)

Picture above is a example where shadows and stage inside stage working with Viewport#setOffset (Game window using ScalingViewport for 3d stuff  and the default viewport for Info UI).

**Comment by xoppa** [comment]
Probably related #2220

**Comment by xpenatan** [comment]
What I suggest is to have a bit of control (a feature) when using viewport methods. 
Option 1 (having offset) is not to mess with screenX and screenY original values and have the ability to move the viewport to anywhere without the need to call update and setScreenPosition. Only viewport class need to change. It wont break anything. 

Every use of "screenX/Y" in viewport needs to be "screenX/Y + offsetX/Y"
Viewport class would be something like this:
```Java
public abstract class Viewport{

...

int offsetX, offsetY;

public void setOffset(int x, int y)
{
	this.offsetX = x;
	this.offsetY = y;
}

public void apply (boolean centerCamera) {
	HdpiUtils.glViewport(screenX + offsetX, screenY + offsetY, screenWidth, screenHeight);
	camera.viewportWidth = worldWidth;
	camera.viewportHeight = worldHeight;
	if (centerCamera) camera.position.set(worldWidth / 2, worldHeight / 2, 0);
	camera.update();
}

public void calculateScissors (Matrix4 batchTransform, Rectangle area, Rectangle scissor) {
	ScissorStack.calculateScissors(camera, screenX + offsetX, screenY + offsetY, screenWidth, screenHeight, batchTransform, area, scissor);
}

....

}
```


There is also Option 2 (If offset is not a option) that is to make it possible to customize the method calls for example: disabling Viewport#update() from calling Viewport#apply() and Viewport#apply() from calling Camera#update() will also be great because it will give even more control.

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://malachimusic325.com/age.php?b>

 

loogie@basicelementdesign.com
