### ISSUE TITLE
Lwjgl3 window listener issue? + doc misspelled

### ISSUE THREAD

**Issue by Thomas447** [libgdx/libgdx#3818]
1) In the class Lwjgl3ApplicationConfiguration the doc above the method setResizable() says 

> /** 
	 * @param resizable whether the windowed mode window is resizable (default false)
> */

but it should be (default true) because of the implementation

2) The second issue is that the focusGained() method is AFTER windowIsClosing() called. 
How to test: Add a Lwjgl3WindowListener 

            configuration.setWindowListener(new Lwjgl3WindowListener() {         

            @Override
            public void deiconified() {
                System.out.println("deiconified");
            }

            @Override
            public void focusGained() {
                System.out.println("focusGained");
            }

            @Override
            public void focusLost() {
                System.out.println("focusLost");
            }

            @Override
            public void iconified() {
                System.out.println("iconified");
            }

            @Override
            public boolean windowIsClosing() {
                System.out.println("windowIsClosing");
                return true;
            }
        });

Now try to close via the red X button on the top-right position
It works. Output is: 

> focusGained
focusLost
focusGained
focusLost
iconified
deiconified
focusGained
windowIsClosing

> 

Now trying to close the window by clicking on the close menu via taskbar contextmenu. This happens: 

> focusGained
focusLost
focusGained
focusLost
iconified
deiconified
focusGained
focusLost
windowIsClosing
focusGained

> 

Sry for my English. English is not my native language. 

Edit: Libgdx 1.9.2-snapshot version, Windows 10 64x

**Comment by intrigus** [comment]
Related to 2) https://github.com/glfw/glfw/issues/190

**Comment by code-disaster** [comment]
windowIsClosing() isn't closing the window, it is notifying the app about the user intention to close the window, and gives the option to block it. That's also why there's a focusGained() afterwards, because this is what happens - the window regains focus.

I'd actually recommend to rename the function to better reflect its use, e.g. requestClosing().

**Comment by badlogic** [comment]
In favor of renaming. First PR gets a pony!
