### ISSUE TITLE
import  project get a error

### ISSUE THREAD

**Issue by hstcscolor** [libgdx/libgdx#3824]
<get src="${domain}/extensions/gdx-controllers/gdx-controllers-desktop-natives.jar" dest="extensions/gdx-controllers/gdx-controllers-desktop/libs"/>

ant -f fetch.xml 
have not folder libs， so gdx-controllers-desktop-natives.jar become  libs file

**Comment by Tom-Ski** [comment]
Please read https://github.com/libgdx/libgdx/wiki/Getting-help

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://batti.in/guide.php?tfo>

 

loogie@basicelementdesign.com
