### ISSUE TITLE
texture filtering issue

### ISSUE THREAD

**Issue by aboudaladdin** [libgdx/libgdx#3828]
hello 
i have a problem in rendering textures as in photo,, the texture appears as if filters are set to 
Nearest 
but the parameters are Linear for both min & mag filters 

also i set them to linear and no thing happens !

![image](https://cloud.githubusercontent.com/assets/15913543/12883289/9ef9f7be-ce5f-11e5-8156-2f1dd7b88351.png)
thanks in advance

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
