### ISSUE TITLE
NullPointerException while importing project

### ISSUE THREAD

**Issue by shultzy88** [libgdx/libgdx#3831]
I get a NullPointerException error while importing my project into Eclipse. I checked and I have all the requirements (JDK 1.7+, Android SDK, ADT Plugin for Eclipse and Eclipse Integration Gradle. I am using JDK 1.8
![importgradleproject](https://cloud.githubusercontent.com/assets/10048519/12919796/58f5c778-cf0b-11e5-9efc-9134968f4110.png)
![nullpointerexceptionmessage](https://cloud.githubusercontent.com/assets/10048519/12919795/58eae1f0-cf0b-11e5-9de3-1315b8753ed0.png)

**Comment by badlogic** [comment]
Expand details and provide the full stack trace please

**Comment by shultzy88** [comment]
Ok, here is the full detailed message of the error. No stack trace was generated.
![image](https://cloud.githubusercontent.com/assets/10048519/12920402/11a23700-cf0e-11e5-8813-64125b661ea5.png)

**Comment by davebaol** [comment]
Looks like problem with your setup. See http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=17535
