### ISSUE TITLE
[GWT] Keeps loading old assets

### ISSUE THREAD

**Issue by JFixby** [libgdx/libgdx#3832]
When I make changes in assets folder I also put a file in there that stores current assets version. Later I print out the content of the file into console to be sure that I'm using the right assets.

This revealed the problem: GWT keeps using the old assets. Cleaning browser cache doesn't help.

**Comment by MobiDevelop** [comment]
Unable to reproduce, please provide the necessary information to reproduce the issue. Will close until that is received and it is determined there is an actual issue here.
