### ISSUE TITLE
PolygonSpriteBatch or PolygonSprite limited drawing.

### ISSUE THREAD

**Issue by m8tto** [libgdx/libgdx#3834]
Hi. I'm making runner game.
I'm trying to render my bodies (bodies of platforms) with PolygonSprite.
But for some reason only some of them are drawn (only some at start, around 5-8 blocks avg.)

What I do.
1. I'm creating Brick object with body in it.
2. In init() method I'm creating new PolygonSprite.
3. I draw them with PolygonSpriteBatch with camera ProjectionMatrix

At some point they're just stop drawing. 
Log output says that everything is ok. And also sprite-create method is the same for all of the blocks.

So when camera is moved to 300 - 400 by x axis (world width is 100) they stop rendering.
Box@dDebugRenderer draws everything fine.
See screenshot.

What could that be?

Here's sprite creating in brick class.
Objects are pool able for now, thats why checking sprite for null. (That's not an issue cause when they were not pool able problem still were there).
<img width="840" alt="2016-02-11 14 58 32" src="https://cloud.githubusercontent.com/assets/8543124/12975871/841d4f4a-d0d0-11e5-822b-601cd02e6f1a.png">

```
p = (PolygonShape)fxt.getShape();
int vertexCount = p.getVertexCount();
float[] vertices = new float[vertexCount * 2];
Vector2 mTmp = new Vector2();
for (int k = 0; k < vertexCount; k++) {
    p.getVertex(k, mTmp);
    mTmp.add(b.getPosition()); 
    vertices[k * 2] = mTmp.x;
    vertices[k * 2 + 1] = mTmp.y;
}
short triangles[] = gg.ECT.computeTriangles(vertices).toArray();
if(sprite==null){
    sprite =  new PolygonSprite(new PolygonRegion(gg.atl.findRegion("wood"), vertices, triangles));
} else {
    sprite.setRegion(new PolygonRegion(gg.atl.findRegion("wood"), vertices, triangles));
}
```

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
