### ISSUE TITLE
Native artifacts: Rename from gdx-platform to gdx, and extension 'so' instead of 'jar'

### ISSUE THREAD

**Issue by Nthalk** [libgdx/libgdx#3837]
The major android-maven-plugin uses a specific type and classifier to extract and supply native libraries to the android application:
http://simpligility.github.io/android-maven-plugin/native-deps.html

However, there are some rules about this, at first, I just extracted the .so files from the jars and published those, but the android plugin extracts them as the artifact name, so their artifact names should be changed to.

GDX makes it difficult to NOT load the system library: "gdx", one can get around GdxNativesLoader.disableNativesLoading by implementing an android application, however, it is impossible to stop AndroidGL20's static initializer from loading "gdx"

I propose that the android arch artifacts should be named: gdx-[arch-classifier].so and released like that, instead of embedded in jars.

This would allow a much simpler maven based build system for android.

**Comment by badlogic** [comment]
AndroidGL20 can be modified to read disableNativesLoading. I'm not in favor of renaming our artifacts to work with an unofficial Maven plugin for Android I'm afraid. Please send a PR for the modification to AndroidGL20.
