### ISSUE TITLE
Security alert from google play

### ISSUE THREAD

**Issue by bachtrong43** [libgdx/libgdx#3853]
Recently most of my games developed using libgdx have security alert from google play:
```javascript 
"Your app is using an unsafe implementation of the X509TrustManager interface with an Apache HTTP client, resulting in a security vulnerability. Please see this Google Help Center article for details, including the deadline for fixing the vulnerability."
```
My games don't use any external library, only used libgdx API. I don't know how to address this issue. Anyone help me?, I used libgdx 1.7.0

**Comment by attritionorg** [comment]
"Please see this Google Help Center article for details" <- Can you provide the link the error message gave?
