### ISSUE TITLE
Json: Cannot parse from printPretty json.

### ISSUE THREAD

**Issue by vedi0boy** [libgdx/libgdx#3854]
This may have been done on purpose but I still feel that it should be changed. Right now, if you serialize an object with `json.printPretty(Object o)`, you are unable to parse it back into an object because of missing commas and other things.

The reason I think it would be better this way is so that, when saving to a file, you can easily change things from the file without needing to make an editor.

My idea is to make it so that printPretty makes a json string that works except the only difference is that it have spacing and line breaks to make it easier to read. To parse it back to an object, all that will be needed to do this is to strip the json string of all spaces and line breaks.

Edit: To elaborate, right now printPretty doesn't serialize correctly with arrays and apparently (according to this: [https://github.com/libgdx/libgdx/issues/3838](https://github.com/libgdx/libgdx/issues/3838)) doesn't serialize the last number properly either.

**Comment by Tom-Ski** [comment]
This works just fine, perhaps provide a sscce that replicates your issue.

**Comment by vedi0boy** [comment]
It's not an error, I just think it should be changed. It would allow other things to be much easier.

**Comment by Tom-Ski** [comment]
The issue you filed was "Cannot parse from printPretty json", this would be an error, no?  You can parse from a pretty printed string just fine so I'm not sure what the error you are reporting here is.  

The error you reference is the result of entering invalid json rather than the result of pretty print.

**Comment by vedi0boy** [comment]
Ok, I will share my code. Sorry about my misunderstanding.

I have a TileData object that contains a bunch of properties. The only important ones for now are: id, name, x & y.

I load them like this to test (they are in an array):
```
TileData[] data = json.fromJson(TileData[].class, Gdx.files.internal("path/to/json/file"))];
//Load tile data....

//Try to print it to see
System.out.println(json.prettyPrint(data));
```

The print result:

```
[
{
	id: grass
	name: Grass
}
{
	id: water
	x: 1
	name: Water
}
{
	id: dirt
	x: 3
	y: 1
	name: Dirt
}
]
```

This is is no way parseable. If I use `json.toJson(data);` I get this: 
`[{id:grass,name:Grass},{id:water,x:1,name:Water},{id:dirt,x:3,y:1,name:Dirt}]`

I can easily parse it back to a TileData[] with toJson, but it doesn't work with prettyParse.

**Comment by vedi0boy** [comment]
I found the solution. I didn't know it was possible to have PrettyPrintSettings. Sorry about that.

**Comment by Tom-Ski** [comment]
That output is parseable by LibGDX. See this test: https://gist.github.com/Tom-Ski/fbe5f252566fe99367d1

**Comment by vedi0boy** [comment]
Thanks for you help.
