### ISSUE TITLE
Missing sort() method for all back-ends except desktop.

### ISSUE THREAD

**Issue by JFixby** [libgdx/libgdx#3855]
I don't understand why but here is no sorting:

![what](https://cloud.githubusercontent.com/assets/1580663/13117357/db7e9e14-d59f-11e5-824b-4ded3b05e910.jpg)

**Comment by MobiDevelop** [comment]
That's a Java 8 method, only those backends supporting Java 8 can use it.

**Comment by JFixby** [comment]
Ok. 
Seems like the ```Collections.sort(list, comparator)``` works on Android.

On GWT com.badlogic.gdx.utils.Array may help:
```
com.badlogic.gdx.utils.Array<T> tmp = new com.badlogic.gdx.utils.Array<T>();
		while (legacy.size() > 0) {
			T e = list.remove(0);
			tmp.add(e);
		}
		tmp.sort(comparator);
		for (T e : tmp) {
			list.add(e);
		}
```

**Comment by JFixby** [comment]
Sorry for bothering.
