### ISSUE TITLE
Vulkan for LibGDX

### ISSUE THREAD

**Issue by SonicACCEL** [libgdx/libgdx#3860]
Vulkan 1.0 was officially released yesterday 
- https://www.khronos.org/news/press/khronos-releases-vulkan-1-0-specification

Some great benefits for desktop and Android ( http://www.androidauthority.com/opengl-es-3-2-vulkan-everything-to-know-632068/ )

Is there a plan to implement Vulkan in LibGDX?

**Comment by davebaol** [comment]
See issues #3344 and #3494
