### ISSUE TITLE
Adding irc hook to github repo (5 minutes to do it!)

### ISSUE THREAD

**Issue by realitix** [libgdx/libgdx#3873]
Hi administrators,
it would be great to add IRC hook to this repo, it would allow to be notified on event directly on IRC.
It takes only 5 minutes to install, follow the guide :

1 - Go into libgdx repository setting under "Webhooks & services"
2 - In the "Services" section, click on "Add service" and select "IRC"
3 - Fill the configuration.
After my tests, I recommend to disable color.
Enable "Message without join" option but don't forget to execute `/msg ChanServ set #CHANNELNAME mlock -n` on IRC to allow external message.
Branch : master

Here it will work but we have to add "issue" event to get notification when posting an issue:

4 - Find hooks id:
curl -u admin_name -i https://api.github.com/repos/libgdx/libgdx/hooks
You get a json with an "id", it's the hook id.

5 - Enable issue events:
curl -u admin_name -i https://api.github.com/repos/libgdx/libgdx/hooks/hook_id --request PATCH --data '{"add_events": ["issues","issue_comment"]}'

That's all, 5 minutes!

**Comment by MobiDevelop** [comment]
I would rather we not spam IRC with these kinds of messages. People who want to be notified of issues can watch the repo.

**Comment by realitix** [comment]
Ok I close this issue so.
