### ISSUE TITLE
Strange indent on first line while using Label

### ISSUE THREAD

**Issue by Swift42** [libgdx/libgdx#3874]
libgdx: 1.9.1

I have a simple Label:

Label.LabelStyle style = new Label.LabelStyle();
Assets.vars.textFontSmall.getData().setLineHeight(17);
style.font=Assets.vars.textFontSmall;
label = new Label("IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII\nIIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII IIII\n",style);
label.setWrap(true);
label.setWidth(336);
label.setHeight(150);
label.setPosition(30, 42);
label.setAlignment(Align.left);

When I render this via
label.draw(batch,1);

Then the first line of text has always a strange indent.
Tested on Windows and Android. Same result.

[The output](http://www.3d4x.ch/temp/libgdx.png)

**Comment by Swift42** [comment]
Can you please tell me: what have I done wrong in my report to deserve a "How not to report an issue"-label without further explaination?
A small hint would be very helpful.

**Comment by davebaol** [comment]
https://github.com/libgdx/libgdx/wiki/Getting-Help

**Comment by Tom-Ski** [comment]
When you opened this issue, you must have just ignored the issue template that was there telling you exactly how to file an issue correctly.

**Comment by Swift42** [comment]
No, I don't have ignored the template. The opposite is the case...
The template says:
#### Issue details: check!
#### Reproduction steps/code: check!
#### Version of LibGDX and/or relevant dependencies: check!
#### Stacktrace: not relevant because it was no crash
#### Please select the affected platforms: check!

All this information can be found in my comment.
Was a code snippet not enough? Is this the problem?
Or is it because I removed the ####-headlines?
Heeeeeelp :-)

Please give me a sign and I will do my best to repost the issue perfectly.

**Comment by Tom-Ski** [comment]
Having the format makes the issue easier to read, but the main issue is that you haven't supplied appropriate code that reproduces the issue. As the template says 

"_Please provide the steps to reproduce this issue, or even better, a [SSCCE](http://sscce.org/) that reproduces your issue.
You can find barebones templates [here](https://github.com/libgdx/libgdx/wiki/Getting-help)_"

Please read those links, ideally you should provide a single barebones test  (like in the links) that we can just copy and paste to see the issue.

**Comment by Swift42** [comment]
Thanks for the reply.
I will repost the issue with the said template.
Sorry for the hassle.
