### ISSUE TITLE
[FeatureRequest] Photoshop filters (layer modes)

### ISSUE THREAD

**Issue by JFixby** [libgdx/libgdx#3876]
Hello,

There are different simple filters in Photoshop widely used by digital artists:
![untitled-1](https://cloud.githubusercontent.com/assets/1580663/13293026/52a1b43a-db1e-11e5-9434-cb397b77d4d8.jpg)

It would be terrific to have them in libGDX. 

For example I can draw something like this in Photoshop as a game concept:
![f49a16214fc095b0549a70349e5df87a](https://cloud.githubusercontent.com/assets/1580663/13293127/b3bae4ee-db1e-11e5-94ce-9a10ea40f14f.png)

But implementing it as a game becomes extremely complicated. 

Another example: Hue-Saturation Photoshop layer with moving mask:  
![010-forum](https://cloud.githubusercontent.com/assets/1580663/13293871/d74270d2-db21-11e5-9c67-40473f550f84.gif)

I just tried myself to implement a simple shader for gray-scale effect but seems like a heavy task that brings me into the deep forest of the libGDX source-code and then farther to the GLLS-language which is way out of my area of knowledge.

So if the Photoshop filters come to libGDX, that would be great. Even if it is just a couple of them or something simple like "make area grayscale".

Thank you for your attention.

**Comment by Tom-Ski** [comment]
There is no one to one relationship between blend modes and Photoshop blend modes so you have to do this with shaders.  Almost all of the PS blend modes require custom glsl to approximate the same effect and there are plenty of examples with source on the web for achieving a similar effect with glsl.  Even if we could somehow provide generic shaders for each of these blend modes, you wouldn't get the same result as you think you would due to other issues like blending and how SpriteBatch batches.  So you will still require an understanding of what all these effects are doing under the hood.

This is something better suited to either a post processing library, or for you to learn how to work with shaders so you can get the effects that you want.

**Comment by JFixby** [comment]
Well I was somehow able to feed a simple "make texture grayscale"-shader string into the SpritebBatch and get the effect. Then I tried to pass canvas xy-coordinates into the shader, telling him where exactly I want the effect. This is where it becomes complicated. Shader works with window coordinates (gl_FragCoord) and I have to skip the canvas coordinates through gdx-code (camera?) to project it. And this is where I start loosing myself in the forest of the gdx-source code or even worse writing my own "engine".

**Comment by Tom-Ski** [comment]
You don't need to look into gdx source, its all shaders.  Most people do end up writing a tiny engine on top of the LibGDX framework, as all these things are project specific.  You may want the effect to do something one way, another person might not.  That's the great thing about LibGDX, you are free to implement these things the way you want.

Depending the shader, you might want to pass in x-y width and height for the rectangle in NDC space coordinates.  Take your world coordinates for each of these points, use your camera to find screen coordinates of these points, and then map to NDC space.  ((screenspacex/resolutionx) * 2.0) - 1.0

These questions are better suited for the forum or the irc.

**Comment by JFixby** [comment]
Ok, I spent this whole week offering sacrifices to the tech gods, discovering the shaders topic and finally I was able to implement the filters. Seems like it is not that hard for someone who knows the subject.

Anyway here is how I see the feature can be introduced into the libGDX without any big problems.

First we need to create an enum:
```
public enum BLENDING_MODE {
   GDX_DEFAULT, PHOTOSHOP_NORMAL, PHOTOSHOP_MULTIPLY, ....etc.
}
```
Then update the SpriteBatch by adding the following methods:

```
public void begin(BLENDING_MODE blending_mode){
    .... here we do the magic
}

public void begin(){
    this.begin(BLENDING_MODE.GDX_DEFAULT);
     /// backward compatibility for games targeting previous gdx versions
}

public void end(){
    this.end(BLENDING_MODE.GDX_DEFAULT); /// backward compatibility
}

public void end(BLENDING_MODE exiting_mode){
      ///undo the magic
}

public void setShader(ShaderProgram program){
   if(current_mode!=BLENDING_MODE.GDX_DEFAULT){
         //report error;
    }
}
```

So from the library user point of view the whole thing would work as follows:
```
public void render(){

      spriteBatch.begin();
                ///draw some regular sprites like we did before;
      spriteBatch.end();

      spriteBatch.begin(BLENDING_MODE.PHOTOSHOP_OVERLAY);
                ///draw some magic using the effect;
      spriteBatch.end(BLENDING_MODE.PHOTOSHOP_OVERLAY);

}
```

This way libGDX users can use special effects without even being aware of existence of shaders at all.

**Comment by MobiDevelop** [comment]
I agree with Tomski that this sort of thing is better suited as a library outside of libgdx.

**Comment by JFixby** [comment]
Something like ```BlendingSpriteBatch extends SpriteBatch``` ?
