### ISSUE TITLE
TextField does not support writing arabic letters correctly

### ISSUE THREAD

**Issue by ataw85** [libgdx/libgdx#3878]
Please ensure you have given all the following requested information in your report.

#### Issue details
I have a number of TextFields that need arabic letters input. When using any font that supports arabic, the letters are put separately and in reverse order. I added a listener that takes the last letter and places it at the beginning (which makes the letters appear in the correct order) but still the letters are not in the connected form which is not right.

#### Reproduction steps/code
I have the following code:

        FreeTypeFontGenerator generator = new FreeTypeFontGenerator(Gdx.files.internal("fonts/arialuni.ttf"));//Arial universal font
        FreeTypeFontGenerator.FreeTypeFontParameter parameter = new FreeTypeFontGenerator.FreeTypeFontParameter();
        parameter.size = w / 20;//Screen width divided by 20
        BitmapFont font12 = generator.generateFont(parameter);
        generator.dispose();

        Pixmap pm1 = new Pixmap(1, 1, Pixmap.Format.RGB565);
        pm1.setColor(Color.WHITE);
        pm1.fill();

        txtStyle = new TextField.TextFieldStyle();
        txtStyle.background = new TextureRegionDrawable(new TextureRegion(new Texture(pm1)));
        txtStyle.font = font12;
        txtStyle.fontColor = Color.BLACK;

        txtName = new TextField("", txtStyle);

After setting width, height, and location of the TextField txtName then adding the actor to the stage, everything looks fine but the previously mentioned problem happen.
The arabic word should look like:
السلام عليكم
but instead it looks like:
م ك ي ل ع   م ا ل س ل ا
without the spaces but in the same shape.

LibGdx ver 1.9.1 for Android on Windows 7 using Android Studio with a live emulation connection to HTC Desire 820

P.S. I've already seen the other issues that are relevant to writing and rendering right to left characters and none of them offers a real solution.

With best regards and most appreciation

**Comment by davebaol** [comment]
See issue #1589

**Comment by CrowniAPIs** [comment]
RTL languages like Arabic not just direction from RIGHT to LEFT, but how connect their letters with each other and some letters as a block with 2 or more letters.
So, I do it with fully supporting RTL language. 
https://github.com/CrowniAPIs/libGDX-RTL-Language
