### ISSUE TITLE
Lwjgl3 multi window cursor crash

### ISSUE THREAD

**Issue by piotr-j** [libgdx/libgdx#3880]
#### Issue details
Setting a cursor in multiwindow Lwjgl3 app will cause a native crash when multiple windows are disposed. Clearing the map from after the cursors are disposed sounds like a correct solution.

#### Reproduction steps/code
https://gist.github.com/piotr-j/6724fe74f41ab340235e

#### Version of LibGDX and/or relevant dependencies
1.9.2+

#### Stacktrace
```java
j  org.lwjgl.glfw.GLFW.glfwDestroyCursor(J)V+20
j  com.badlogic.gdx.backends.lwjgl3.Lwjgl3Cursor.disposeAll()V+62
j  com.badlogic.gdx.backends.lwjgl3.Lwjgl3Graphics.dispose()V+7
j  com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.dispose()V+22
j  com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.cleanup()V+28
j  com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lcom/badlogic/gdx/ApplicationListener;Lcom/badlogic/gdx/backends/lwjgl3/Lwjgl3ApplicationConfiguration;)V+250
j  com.mygdx.game.MyGdxGame.main([Ljava/lang/String;)V+20
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by piotr-j** [comment]
While this fixed the native crash, it causes another bug. Since all cursors are disposed when any window closes, if other window has a cursor set this change is lost. See updated gist for example:
https://gist.github.com/piotr-j/6724fe74f41ab340235e

**Comment by davebaol** [comment]
Reopened
