### ISSUE TITLE
No new libgdx snaphshots

### ISSUE THREAD

**Issue by intrigus** [libgdx/libgdx#3885]
There hasn't been a new snapshot for almost 2 weeks.

The problem seems to be @badlogic's MacMini.
The build itself works (on the Linux host), but since the mac is offline, the build can't complete.

Mario said that it looks like the mac died.
If that's the case, are there any plans to either buy a new mac mini (using the money from patreon?) or maybe move the compilation of the mac-natives to Travis-CI?

**Comment by badlogic** [comment]
Sorry, been a few busy weeks. I think i managed to fix the Mac. It may still randomly drop Wifi connection.

**Comment by 3xp0n3nt** [comment]
Can we please re-open this? There haven't been any new snapshots uploaded to the sonatype repo for 9 days now. https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/gdx/gdx/1.9.3-SNAPSHOT/

**Comment by badlogic** [comment]
Fixed

**Comment by 3xp0n3nt** [comment]
@badlogic Thanks for the lightning-fast response!

**Comment by intrigus** [comment]
Hey, @badlogic could you please fix the nightly builds :)

**Comment by 3xp0n3nt** [comment]
@badlogic [libgdx-mac](http://144.76.220.132:8080/job/libgdx-mac/) is **offline** blocking [libgdx](http://144.76.220.132:8080/job/libgdx/). No new snapshots for 11 days now. :crying_cat_face:
