### ISSUE TITLE
Arrow keys insert spaces when using Textfield.setOnlyFontChars(false)

### ISSUE THREAD

**Issue by intrigus** [libgdx/libgdx#3888]
#### Issue details

If you use `Textfield.setOnlyFontChars(false)` and press one of the arrow keys, a space will be inserted.
I'm not sure if this is intended behavior.
I can only reproduce this on Lwjgl2, Lwjgl3 works fine.
#### Ssccee

``` java


package com.badlogic.gdx.tests;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Skin;
import com.badlogic.gdx.scenes.scene2d.ui.TextField;
import com.badlogic.gdx.utils.viewport.ScreenViewport;

public class MacTextFieldIssue {

    public static class UITest extends ApplicationAdapter {
        Skin skin;
        Stage stage;

        @Override
        public void create () {
            skin = new Skin(Gdx.files.internal("data/uiskin.json"));
            stage = new Stage(new ScreenViewport());
            Gdx.input.setInputProcessor(stage);

            TextField textfield = new TextField("", skin);
            textfield.setOnlyFontChars(false);
            textfield.setMessageText("Click here!");

            stage.addActor(textfield);
        }

        @Override
        public void render () {
            Gdx.gl.glClearColor(0.2f, 0.2f, 0.2f, 1);
            Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
            stage.act(Math.min(Gdx.graphics.getDeltaTime(), 1 / 30f));
            stage.draw();
        }

        @Override
        public void resize (int width, int height) {
            stage.getViewport().update(width, height, true);
        }

        @Override
        public void dispose () {
            stage.dispose();
            skin.dispose();
        }
    }

    public static void main (String[] a) {
        new LwjglApplication(new UITest());
    }

}


```
#### Reproduction steps/code

Modify [UITest.java](https://github.com/libgdx/libgdx/blob/master/tests/gdx-tests/src/com/badlogic/gdx/tests/UITest.java) and add `textfield.setOnlyFontChars(false);` after https://github.com/libgdx/libgdx/blob/master/tests/gdx-tests/src/com/badlogic/gdx/tests/UITest.java#L103
#### Version of LibGDX and/or relevant dependencies

Latest master/1.9.2
#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS
- [x] LWJGL2
- [ ] LWJGL3

**Comment by NathanSweet** [comment]
I believe this has been fixed, cannot repro with latest.

**Comment by intrigus** [comment]
Have you tried it on a mac?
It may be os specific.

**Comment by xoppa** [comment]
Reopened on request of @intrigus, perhaps it only exposes on mac. Perhaps someone can verify on mac. @intrigus please include a sscce which can be copied pasted for convenience.

**Comment by intrigus** [comment]
Added a sscce.

**Comment by NathanSweet** [comment]
Mac people?

**Comment by NathanSweet** [comment]
Mac people don't care I guess.

**Comment by ollipekka** [comment]
Confirmed that this still reproduces. I can try to take a look at it.

**Comment by ollipekka** [comment]
This is actually a problem that there is a missingGlyph in the font and MacOSX emits keyTyped for arrow buttons. Once missingGlyph is set to null for loaded fonts, this works properly.

Emitted keyTyped event:
[Screenshot](http://i.imgur.com/MXJH2QH.png)

I think this is a problem with lwjgl2 and OSX and how libgdx uses it. This isn't a problem with lwjgl3.

**Comment by floralvikings** [comment]
It looks like this is because MacOSX (at least version 10.12) emits the following character codes when the arrow keys are typed:

```
Up:    '\uF700'
Down:  '\uF701'
Left:  '\uF702'
Right: '\uF703'
```

I've worked around this for now with this (rather ugly) kludge:

```java
// Hack - custom text field for OSX arrow key character codes
TextField textField = new TextField(value, skin){
    @Override
    protected InputListener createInputListener() {
        return new TextFieldClickListener() {
            @Override
            public boolean keyTyped(InputEvent event, char character) {
                // These character codes are emitted by OSX when the arrow keys are pressed.
                if((character >= '\uF700') && (character <= '\uF703')) {
                    return false;
                }
                return super.keyTyped(event, character);
            }
        };
    }
};
```


@NathanSweet I know this is an old issue, but if you're interested in a fix I can submit a PR for this and add a similar check to the `keyTyped()` method of `TextFieldClickListener`, but if you've got other ideas for a fix I'm definitely open to suggestions.

**Comment by carlislefox** [comment]
Hi there everyone, I too have ran into this issue on OSX - although in addition to the arrow keys tab is also inserting characters.

It is reassuring to see people have approached the problem the same way I have, I worked around it with the following code (which also allows you to forward the events to the listener, should one be registered):

`public class ExtendedFontTextField extends TextField {

    private TextFieldListener textFieldListener;

    public ExtendedFontTextField(String text, Skin skin) {
        super(text, skin);
    }

    @Override
    protected InputListener createInputListener() {
        return new ExtendedFontTextFieldListener();
    }

    @Override
    public void setTextFieldListener(TextFieldListener textFieldListener) {
        this.textFieldListener = textFieldListener;
        super.setTextFieldListener(textFieldListener);
    }

    private class ExtendedFontTextFieldListener extends TextFieldClickListener {

        /**
         * Handle special characters in the extended font for keys that normally don't have characters like the d-pad,
         * tab, etc.
         */
        @Override
        public boolean keyTyped(InputEvent event, char character) {
            boolean handled = false;

            switch (character) {
                case '\uF700':
                    // Up Arrow
                    handled = true;
                    break;

                case '\uF701':
                    // Down Arrow
                    handled = true;
                    break;

                case '\uF702':
                    // Left Arrow
                    handled = true;
                    break;

                case '\uF703':
                    // Right Arrow
                    handled = true;
                    break;

                case '\t':
                    // Tab
                    next(UIUtils.shift());
                    handled = true;
                    break;
            }

            if (handled) {
                if (textFieldListener != null) {
                    textFieldListener.keyTyped(ExtendedFontTextField.this, character);
                }

                return true;
            }

            return super.keyTyped(event, character);
        }
    }

}`

Can someone tell me if Scene2d.ui is accepting pull requests at this time? I'd like to submit a real fix.

Liam

**Comment by NathanSweet** [comment]
@carlislefox scene2d is actively maintained, if a little slowly these days. I'm not an OS X person though.

It could be that some backends give characters for keys that other backends don't. The question is, do we really want InputProcessor `keyTyped` to fire for arrows keys, etc?

**Comment by carlislefox** [comment]
I use it to move the keyboard focus to different fields when users press things like _enter_ on Android (which feels the most intuitive to me), and to have total control over the use of _tab_, _shift + tab_ etc on PC.

Personally I think it is intuitive to forward these events to the listener and we don't lose anything by doing so, to squash them would be to take an opinionated view on what people might be using the listener for which I think does more harm than good in this case.

What do you think? My code example above highlights the specific characters that _fall through the cracks_ so to speak on OSX, I haven't been able to find any others.

Thanks for the response, I'm happy to put together a pull request if we can agree on an approach :)

Cheers,
Liam

**Comment by NathanSweet** [comment]
Arrow keys already fire events: key down and key up events. Note that tab does have a character.

If nothing is typed, I think a key typed event should not occur. We do lose something by letting that happen -- our sanity! It's not just an opinionated view, it's a logical one, plus methods have contracts. InputListener `keyTyped` says:
```
/** Called when a key is typed. When true is returned, the event is {@link Event#handle() handled}.
	 * @param character May be 0 for key typed events that don't map to a character (ctrl, shift, etc). */
```

**Comment by carlislefox** [comment]
Hmm, but without the ability to handle those presses within this listener we lose an easy way of handling TextField input all in one place. Handling key up and key down events out-of-scope of the TextFieldListener feels wrong to me.

To be clear I'm just playing devils advocate here... I don't have a use for the arrow key presses myself, and I can't really think of one either.

My example code above just handles them as they were causing square characters - that I forward them to the listener was just autopilot coding as I don't consume them.

**Comment by carlislefox** [comment]
Re-reading your message, I'm not sure we are talking about the same thing - my example code forwards them to the TextFieldListener (a proprietary interface instance on TextField) but deliberately does not forward them to the _keyTyped()_ method as that was the source of my issue.

**Comment by carlislefox** [comment]
I see, in which case agreed on all counts.
