### ISSUE TITLE
Alpha channel in KTX compressed textures rendered separately

### ISSUE THREAD

**Issue by tyrondis** [libgdx/libgdx#3890]
#### Issue details
LibGDX renders a KTX compressed texture containing an alpha channel (compressed with KTXProcessor) incorrectly. Rather than re-combining the RGB and Alpha channels, it renders them separately.

#### Reproduction steps/code
Checkout and run my sample project: https://github.com/tyrondis/ktx-alpha

#### Version of LibGDX and/or relevant dependencies
1.9.2

#### Stacktrace
n/a

#### Please select the affected platforms
- [x] Android
- [x] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS

**Comment by tyrondis** [comment]
I am trying to create a PR for this, however I am uncertain as to how to determine whether a KTX compressed texture includes an alpha channel or not. Currently there does not seem to be a way to check that, as it is simply the original texture doubled in height with the alpha channel underneath it.

However, I might be able to adjust the `glBaseInternalFormat` field. Currently, in case of ETC textures, it always contains `GL20.GL_RGB`. I could put `GL20.GL_RGBA` into here in case we are adding the alpha channel.

Any thoughts?

**Comment by tyrondis** [comment]
@vbousquet do you have an opinion on this?

**Comment by vbousquet** [comment]
ETC1 texture do not support Alpha channel. KTXProcessor propose a hack to go around this (there are others way to do so) but it is a hack and LibGdx is not supposed to render it without tweaking.

I tried to make it clear in the doc [here](https://github.com/libgdx/libgdx/wiki/Texture-Compression) and provided a test with full source code to let you implement it if you need [here](https://github.com/libgdx/libgdx/blob/master/tests/gdx-tests/src/com/badlogic/gdx/tests/KTXTest.java).

From my point of view, this is not an issue but the expected operation.

Regards,

    Vincent

**Comment by xoppa** [comment]
Let's not hack in a different shader based on the texture properties or something, that will not work. Indeed, there's not really a good solution, other than for the user to use a custom shader. E.g. the shader provided by @vbousquet in the test. If this isn't clear from the wiki then could you please fix that by modifying the wiki @tyrondis.

**Comment by JFixby** [comment]
In my opinion KTX and ETC1 compressors should be able to specify what color to use instead of the alpha pixels. Currently it is default black.

Also discarded alpha channel should be stored somewhere to be later merged back by means of simple Pixmap or a shader.

**Comment by xoppa** [comment]
Closing this, please update the wiki as you feel appropriate.
