### ISSUE TITLE
Robovm Music class problem

### ISSUE THREAD

**Issue by soylomass** [libgdx/libgdx#3891]
#### Issue details

(The following applies to both iOS simulator and actual device, both on iOS 9)

I'm porting an Android project to iOS using RoboVM.

(Almost) Everything works fine except of Music. I'm using .mp3 files. Whenever I try to create a Music object using Audio.newMusic, the following fatal error appears:

com.badlogic.gdx.utils.GdxRuntimeException: Error opening music file at ...
at com.badlogic.gdx.backends.iosrobovm.IOSAudio.newMusic(IOSAudio.java)

I even tried to load a mp3 file that works right when loaded with the Sound class, but it doesn't work either. So I guess there's a difference between Sound and Music classes on how they load the files.

UPDATE: I've just tried with .wav, .ogg, .mp4 and .mp3 with different bitrates and all throw the same error.

**IMPORTANT: I just discovered that actually the problem is the Internal storage, Sounds doesn't actually work when loaded from there, but they don't throw a Fatal Error, just the following error:

IOSLauncher[1160:26466] OAL Error: -[OALSimpleAudio internalPreloadEffect:reduceToMono:]: Could not load effect /Users/fedejm/Library/Developer/CoreSimulator/Devices/C185A369-7580-4E5E-8698-2C99D9DAA53F/data/Containers/Bundle/Application/563DAF14-D4E1-4638-9D58-2695765531C4/IOSLauncher.app/data/sounds/togglepowerup.mp3

Both Music and Sound load and play correctly when loaded from Local storage. It seems I should find a workaround.**

#### Reproduction steps/code

These are the two files I tried:
[sounds.zip](https://github.com/libgdx/libgdx/files/150226/sounds.zip)

The following code gives error:
Gdx.audio.newMusic(Gdx.files.internal("data/themes/"+theme+"/food.mp3"));

The following code works:
Gdx.audio.newSound(Gdx.files.internal("data/themes/"+theme+"/food.mp3"));

#### Version of LibGDX and/or relevant dependencies
Just used Libgdx installer 2 days ago, so lastest stable version. 1.12 RoboVM that came with it.

#### Stacktrace
```java
com.badlogic.gdx.utils.GdxRuntimeException: Error opening music file at /Users/fedejm/Library/Developer/CoreSimulator/Devices/C185A369-7580-4E5E-8698-2C99D9DAA53F/data/Containers/Bundle/Application/41812F6A-BBAD-43AF-B1E3-73CD7641FED2/IOSLauncher.app/data/themes/clownfish/bg.mp3
	at com.badlogic.gdx.backends.iosrobovm.IOSAudio.newMusic(IOSAudio.java:67)
	at com.me.eatthelinetwo.Screenplay.addBackground(Screenplay.java:2360)
	at com.me.eatthelinetwo.Screenplay.resetGame(Screenplay.java:976)
	at com.me.eatthelinetwo.Screenplay.show(Screenplay.java:927)
	at com.badlogic.gdx.Game.setScreen(Game.java:61)
	at com.me.eatthelinetwo.EatTheLine.create(EatTheLine.java:31)
	at com.badlogic.gdx.backends.iosrobovm.IOSGraphics.draw(IOSGraphics.java:307)
	at com.badlogic.gdx.backends.iosrobovm.IOSGraphics$1.draw(IOSGraphics.java:209)
	at com.badlogic.gdx.backends.iosrobovm.IOSGraphics$1.$cb$drawRect$(IOSGraphics.java)
	at org.robovm.apple.uikit.UIApplication.main(Native Method)
	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java:413)
	at com.me.eatthelinetwo.IOSLauncher.main(IOSLauncher.java:30)
```

#### Please select the affected platforms
- [x] iOS

**Comment by soylomass** [comment]
Update for more info.

**Comment by sjosegarcia** [comment]
Just to make sure does theme return a string for a different directory. I
do not know if you meant theme +".mp3"

**Comment by soylomass** [comment]
I tried both in the same line just changing newMusic with newSound and it works. I've even hardcoded the path and it throws the same Exception.

It may have something to do with encoding, but I don't know why the same file works as a sound but not as a music.

**Comment by soylomass** [comment]
UPDATE: I've just tried with .wav, .ogg, .mp4 and .mp3 with different bitrates and all throw the same error.

**Comment by soylomass** [comment]
IMPORTANT: I just discovered that actually the problem is the Internal storage, Sounds doesn't actually work when loaded from there, but they don't throw a Fatal Error, just the following error:

IOSLauncher[1160:26466] OAL Error: -[OALSimpleAudio internalPreloadEffect:reduceToMono:]: Could not load effect /Users/fedejm/Library/Developer/CoreSimulator/Devices/C185A369-7580-4E5E-8698-2C99D9DAA53F/data/Containers/Bundle/Application/563DAF14-D4E1-4638-9D58-2695765531C4/IOSLauncher.app/data/sounds/togglepowerup.mp3

Both Music and Sound load and play correctly when loaded from Local storage. It seems I should find a workaround.

**Comment by Tom-Ski** [comment]
How exactly are you running your tests? What are the precise steps that you are using to launch?  People have had issues with loading from internal directories (depending on how they launch) as the directories are not declared in the robovm.xml.  As a simple test, try putting the sound in the root assets directory and loading from there instead of the folders.

**Comment by soylomass** [comment]
The strange thing is image files load correctly from the same Internal paths.

I'm launching using the default configuration that came with the iOS version file:
`@Override
    protected IOSApplication createApplication() {
        IOSApplicationConfiguration config = new IOSApplicationConfiguration();
        gdxApp = new IOSApplication(new EatTheLine(this), config);
        
        
        return gdxApp;
    }

    public static void main(String[] argv) {
        NSAutoreleasePool pool = new NSAutoreleasePool();
        UIApplication.main(argv, null, IOSLauncher.class);
        pool.close();
    }`

I haven't added any path to robovm.xml, but I tried right now moving the sound file to the root of the assets folder and it didn't work either.

**Comment by soylomass** [comment]
EDIT: The assets folder was actually a linked folder from another project. I've removed the link and copied the folder directly in the project folder, and now image files don't load neither. So it seems the weird behaviour had something to do with the folder being linked.
I'll try to do things correctly with robovm.xml and come back when I have new results.

**Comment by Tom-Ski** [comment]
These assets are in the android/assets folder correct?  You still didn't say how you were launching, robovm plugin for eclipse? gradle? IDEA plugin?

I very much doubt this is an issue with robovm/LibGDX (rather more likely to be a configuration error) , but unfortunately I don't have a mac to test.

**Comment by soylomass** [comment]
Check my last comment I just wrote. About the launch config, I'm using Robovm plugin for eclipse, imported Libgdx projects downloaded with the Libgdx setup tool as Gradle projects.

**Comment by soylomass** [comment]
Well, problem solved. It works now with the folder not being linked and including the assets path with Include: **/* in robovm.xml

Thanks for your support!

**Comment by chandujr** [comment]
@soylomass Can you elaborate on that? I have the exact issue working with Intel MOE in Libgdx. How to unlink the asset folder? The problem is only for sound files (wav, mp3, ogg). Should I copy the asset folder in xcode project directory?
