### ISSUE TITLE
json hashmap reader broken

### ISSUE THREAD

**Issue by kizinfo** [libgdx/libgdx#3898]
Please ensure you have given all the following requested information in your report.

#### Issue details
same json file parses fine in 1.7.2 but won't read in 1.9.1

#### Reproduction steps/code
make a json containing class:java.util.HashMap and try to read it using Json.fromJson

#### Version of LibGDX and/or relevant dependencies
works in 1.7.2, fails 1.9.1

#### Stacktrace
```java
 (com.badlogic.gdx.utils.SerializationException) com.badlogic.gdx.utils.SerializationException: Unable to convert value to required type: class: java.util.HashMap
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by davebaol** [comment]
Providing an SSCCE is your best bet to get it fixed.

**Comment by kizinfo** [comment]
class mymap {
    HashMap<Integer,Integer> map=new HashMap<>();
}

....
Json json=new Json();
json.fromJson(mymap.class, "{map:{class:java.util.HashMap,1:2}}");
....

**Comment by intrigus** [comment]
Probably caused by https://github.com/libgdx/libgdx/commit/204c3a8dcd5870d4e6848dc4bb25011324488ee3 since it seems to be the only commit between 1.7.2 and 1.9.2 that modified the behavior of json serialization.

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info

**Comment by kizinfo** [comment]
just ripped out the json source files from 1.7.2 (before backward compatibility was broken) and used those instead.

**Comment by Utlaen** [comment]
Well here you go

[JsonMapReader.zip](https://github.com/libgdx/libgdx/files/243174/JsonMapReader.zip)
