### ISSUE TITLE
StringBuilder.toString() does not work in GWT with large strings using the LibGDX StringBuilder

### ISSUE THREAD

**Issue by WillCalderwood** [libgdx/libgdx#3904]
#### Issue details

`StringBuilder.toString()` does not work in GWT with large strings when using the LibGDX `StringBuilder`. There is a known bug in the `String` constructor in GWT when working with large strings which I've worked around in the past in my own code. See [here](http://stackoverflow.com/questions/32844235/new-stringbytes-causing-maximum-call-stack-size-exceeded-in-gwt-client). I'm hitting this problem when creating JSON from a large object.
#### Reproduction steps/code

The following code will reproduce the issue. This works fine with the Java String Builder

```
    StringBuilder sb = new StringBuilder();
    for (int i = 1; i < 100000; i++) {
        sb.append("Hello!");
    }
    String s = sb.toString();
```
#### Version of LibGDX and/or relevant dependencies

All
#### Stacktrace

```
com.google.gwt.core.client.JavaScriptException: (RangeError) 
 __gwt$exception: <skipped>: Maximum call stack size exceeded
at Unknown.__valueOf(html-0.js@30:197503)
at Unknown.valueOf_100(html-0.js@10:197712)
at Unknown._String_3(html-0.js@10:197468)
at Unknown.$toString_12(html-0.js@10:63725)
at Unknown.$prettyPrint_2(html-0.js@10:58593)
at Unknown.$prettyPrint_4(html-0.js@10:58679)
at Unknown.$prettyPrint_1(html-0.js@10:46957)
at Unknown.$prettyPrint_0(html-0.js@10:46953)
at Unknown.$prettyPrint(html-0.js@10:46949)
at Unknown.getString_4(html-0.js@25:203579)
at Unknown.$saveUser(html-0.js@43:182979)
```
#### Please select the affected platforms
- [x] HTML/GWT

**Comment by MobiDevelop** [comment]
Issues with GWT itself should be reported to the GWT project.

**Comment by WillCalderwood** [comment]
I've been told it's fixed in the latest GWT version, but as far as I'm aware there are no plans for LibGDX to be updated to use 2.7 in the near future, so we could do with some kind of workaround for now.

**Comment by MobiDevelop** [comment]
How large is large here? I am not convinced this is a widespread enough issue that hacking around it is actually a worthwhile endeavor.

**Comment by WillCalderwood** [comment]
@MobiDevelop I'll run a test and get back to you on that.

**Comment by WillCalderwood** [comment]
@MobiDevelop 124893 characters triggers the error in my test.

**Comment by aliasaila** [comment]
> I've been told it's fixed in the latest GWT version

I can confirm that it's fixed in 2.7.

**Comment by stefanhaustein** [comment]
Just got bitten by this yesterday. Using JsArrayString and join as a workaround :(

**Comment by WillCalderwood** [comment]
No longer an issue with the switch to GWT 2.8
