### ISSUE TITLE
JARs import proposal

### ISSUE THREAD

**Issue by JFixby** [libgdx/libgdx#3905]
When I import freshly downloaded gdx projects from the repository, they all are "red" because of missing jars:
![gdx](https://cloud.githubusercontent.com/assets/1580663/13576449/0af2bed0-e48e-11e5-85c3-fe353021b07d.jpg)

I know the documentation says that I have to download the missing jars from the gdx-nightly server and manually re-import them (which btw is not very handy).

I would like to propose (I believe) a better solution that I already successfully use for the JAR's import.

The idea is that:
1) You create a new repository and call it **gdx-nightly**.
2) There you upload an eclipse project that contains all the jars. Here is an example: https://github.com/JFixby/libgdx-nightly
3) Then you import that project into eclipse workspace and link the jars.

That would be a solution for the Eclipse.

Now when you import freshly downloaded gdx projects from the repository, they will all immediately resolve the missing jars right when you import the **gdx-nightly** into your workspace. 

Pros:
- no manual resolution, just import the **gdx-nightly**
- you can deduce related paragraph in the doc to simple "just import the **gdx-nightly**"
- bonus: you can use git to switch libraries between versions to test you code against older jars

**Comment by MobiDevelop** [comment]
I don't understand what it is you are trying to accomplish here.

Is it simply that you don't want to have to run the fetch script when cloning the libgdx repo? Dropping binaries into a git repo is generally a bad idea, and is the reason there is a fetch script in the first place.

**Comment by badlogic** [comment]
Please use `ant -f fetch.xml` and close this issue.

**Comment by JFixby** [comment]
Sorry for my ignorance about the Ant.

**Comment by JFixby** [comment]
How to call the **ant -f fetch.xml** in Windows?

**Comment by Tom-Ski** [comment]
Install ant, and use ant -f fetch.xml. Or use the gradle wrapper, and run ./gradlew fetchNatives

**Comment by JFixby** [comment]
I thought it is some feature of the Eclipse.

Ok, I downloaded ant http://ant.apache.org/bindownload.cgi
and called **<%AntLocation%>\bin\ant -f fetch.xml** from the lingdx directory. Seems to be working.

**Comment by JFixby** [comment]
Yet ```gdx-controllers-desktop``` is red due to the missing ```gdx-controllers-desktop-natives.jar```
