### ISSUE TITLE
ObjectMap copy ctor broken as of libgdx 1.7.2

### ISSUE THREAD

**Issue by JohanStolk** [libgdx/libgdx#3908]
#### Issue details
ObjectMap copy constructor fails as of libgdx 1.7.2 :
```java
ObjectMap<String, Object> dataCopy = new ObjectMap<String, Object>(data); 
```
See example below.

#### Reproduction steps/code
```java
import com.badlogic.gdx.utils.ObjectMap;

public class ObjectMapCopyCtorBug
{
	public static void main(String[] args) throws Exception
	{
		ObjectMap<String, Object> data = new ObjectMap<String, Object>();
		for (int i = 0; i < 17; i++) // above a certain size copy fails 
			data.put("key" + i, i + 0.5f);

		ObjectMap<String, Object> dataCopy = new ObjectMap<String, Object>(data); // copy ctor fails as of libgdx 1.7.2
		for (int i = 0; i < data.size; i++)
		{
			String key = "key" + i;
			Object dataValue = data.get(key);
			Object dataCopyValue = dataCopy.get(key);
			System.out.println(dataValue + " = " + dataCopyValue);
			if (!dataValue.equals(dataCopyValue))
				System.out.println("wrong copy for key " + key);
		}
	}
}
```
output:
0.5 = 0.5
1.5 = 1.5
2.5 = 2.5
3.5 = 3.5
4.5 = 4.5
5.5 = 5.5
6.5 = 6.5
7.5 = 7.5
8.5 = 8.5
9.5 = 9.5
10.5 = 10.5
11.5 = 11.5
12.5 = null
wrong copy for key key12
13.5 = null
wrong copy for key key13
14.5 = null
wrong copy for key key14
15.5 = null
wrong copy for key key15
16.5 = null
wrong copy for key key16

#### Version of LibGDX and/or relevant dependencies
version 1.7.2 and higher

#### Please select the affected platforms
All

**Comment by davebaol** [comment]
Sounds very similar to issue #3843

**Comment by JohanStolk** [comment]
Agreed, in my case I also saw differences in capacity/size between the original and the copy. In 1.7.2 some changes were made in parts of the code which affects the capacity/size (with next power of 2) but this has broken the original copy constructor code...

**Comment by Tom-Ski** [comment]
We can resolve these issues by just making a complete clone of all settings, not a very elegant solution mind you.  Generating with a load of 1 resolves most of the issues, but there are still one or two variables that are out of sync.

**Comment by JohanStolk** [comment]
I don't know the code that well but the new constructor code has:

```java
initialCapacity = MathUtils.nextPowerOfTwo((int)Math.ceil(initialCapacity / loadFactor));
```

and will get the _next_ power of 2, so a copy with original size 64 gets size 128...

Will changing

```java
public ObjectMap (ObjectMap<? extends K, ? extends V> map) {
 		this(map.capacity, map.loadFactor);
```

into

```java
public ObjectMap (ObjectMap<? extends K, ? extends V> map) {
 		this(map.capacity-1, map.loadFactor);
```

Do the trick in this case? Maybe Nathan is available to check this?

**Comment by Tom-Ski** [comment]
```java
	public ObjectMap (ObjectMap<? extends K, ? extends V> map) {
		this(map.capacity, 1f);
		stashSize = map.stashSize;
		loadFactor = map.loadFactor;
		threshold = map.threshold;
		size = map.size;
		System.arraycopy(map.keyTable, 0, keyTable, 0, map.keyTable.length);
		System.arraycopy(map.valueTable, 0, valueTable, 0, map.valueTable.length);
	}
```
Will give you an identical ObjectMap

**Comment by JohanStolk** [comment]
Nice, is there any unit-testing code with these classes?
I guess not, otherwise this bug would have been caught earlier ;-)

**Comment by FredGithub** [comment]
I noticed that another way to solve the broken copy constructor is by adding this line, rather than setting the load factor to 1, but I have no clue if it's correct or not:

```
mask = map.mask;
```

There are unit tests (CollectionTests.java) but they do not test the copy constructors.

Will someone solve that issue? I would gladly do a pull request but I'm not sure I'm the most adequate person for that task.

**Comment by nanonull** [comment]
Still actual
