### ISSUE TITLE
Gdx2DPixmap.setPixel() actually performs drawing pixel, not setting it, Also doing it wrong.

### ISSUE THREAD

**Issue by JFixby** [libgdx/libgdx#3917]
I have a tricky problem here which is the result of the subject.

Basically I have a Pixmap and I want to set it's pixel to a specific color.
```Pixmap``` has no method to do that. <- **important fact A**

However it has the ```drawPixel()``` method that calls ```Gdx2DPixmap.setPixel()```
```
/** Draws a pixel at the given location with the given color.
	 * 
	 * @param x the x-coordinate
	 * @param y the y-coordinate
	 * @param color the color in RGBA8888 format. */
	public void drawPixel (int x, int y, int color) {
		pixmap.setPixel(x, y, color);
	}
```

Seems like a lucky mistake at first but unfortunately the ```Gdx2DPixmap.setPixel()``` doesn't set pixel to a specific color. Instead it draws the parameter color on top of the previous one. <- **important fact B**

And here something bad is happening. When the original color had Alpha=0 and the new color has Alpha !=1 the draw method takes the original color and mixes it with the new one.

Example:
original color RGBA = **#0000FF00** // transparent Blue
new color RGBA = **#FFFFFF80** // 50% white
Call ```Gdx2DPixmap.setPixel()```
Output color should be **#FFFFFF80**
Output color is: **#8080FF80**

Here is example code to reproduce the issue:
```
 public static void main(String[] args) {
	GdxNativesLoader.load();
	final float W = 400;
	final float H = 400;
	Pixmap pixmap = new Pixmap((int) W, (int) H, Format.RGBA8888);
	pixmap.setColor(0x0000FF00);// clear background, Alpha == 0
	pixmap.fill();
	for (int x = 0; x < W; x++) {
	    for (int y = 0; y < H; y++) {
		pixmap.setColor(0xffffff80);// set color White with Alpha=0.5
		pixmap.drawPixel(x, y);
	    }
	}
	FileHandle file = new FileHandle("1.png");
	System.out.println("writing: " + file);
	PixmapIO.writePNG(file, pixmap);
	pixmap.dispose();

    }

```
What I expect to get: image with 50%-opacity white.
What I actually get:  image with 50%-opacity blue.

![1](https://cloud.githubusercontent.com/assets/1580663/13709675/7e2b0216-e7b5-11e5-8836-2ce7a433c7ff.png)

So in summary:
-  ```Pixmap.drawPixel()``` calls ```Gdx2DPixmap.setPixel()``` while should call ```Gdx2DPixmap.drawPixel()```
-  ```Pixmap``` has no ```setPixel()``` method
-  ```Gdx2DPixmap``` has no ```drawPixel()``` method
- ```Gdx2DPixmap.setPixel()``` doesn't perform set operation, actually it does drawing and do it wrong by taking in account RGB value of a color with zero alpha.

Suggestion about how it should be fixed:
```Pixmap``` and ```Gdx2DPixmap``` both should have two methods: ```setPixel()``` and ```drawPixel()```
 - ```setPixel()``` - sets the new color value ignoring the previous one. In the given example ```setPixel()``` must result into **#FFFFFF80**
 -  ```drawPixel()``` - draws new value on top of the previous one taking in account the original alpha and resulting into a mixed color. When the original color's alpha is zero, the color shouldn't affect the result.

**Comment by mbrlabs** [comment]
You have to use `Pixmap.setBlending(Pixmap.Blending.None);` to disable this behaviour

**Comment by JFixby** [comment]
@mbrlabs Thank you!
