### ISSUE TITLE
Dialog flickering .show

### ISSUE THREAD

**Issue by keeyzar** [libgdx/libgdx#3920]
#### Issue details
Standard Libgdx dialog flickers at .show(stage) function.

#### Reproduction steps/code
Create a bright background, create a dialog and then dialog.show(stage).
(I guess it's when the following happens:
stage.act();
dialog.show(stage);
stage.draw();
but i'm not sure as why it happens. But I know how to fix it)

#### Version of LibGDX and/or relevant dependencies
1.9.2 

#### Please select the affected platforms
- [x] Android testet
- [ ] iOS
- [ ] HTML/GWT
- [X] Windows testet
- [ ] Linux
- [ ] MacOS

####Solution:
following helped in my case:
Color color = dialog.getColor();
color.a = 0;
dialog.setColor(color);
dialog.show();

**Comment by Tom-Ski** [comment]
Please provide a self contained example that reproduces your issue as the issue template requests.
