### ISSUE TITLE
Clicking a Button creates an enter event followed by an exit event

### ISSUE THREAD

**Issue by cypherdare** [libgdx/libgdx#3928]
#### Issue details
If I click a button without moving the cursor off of it, its listener's `enter` method is called, followed by its `exit` method. Neither is expected because the cursor has not moved off of the button.

#### Reproduction steps/code
[Run this ApplicationListener](https://gist.github.com/cypherdare/4aa45a300c46e12b1ce2) and watch log while clicking a button. 

#### Version of LibGDX and/or relevant dependencies
1.7.2 (possibly earlier or forever) onwards to at least 1.9.2

**Comment by vinf100** [comment]
Isn't this the expected behaviour of a ClickListener?
The libgdx API states that: "Detects mouse over, mouse or finger touch presses, and clicks on an actor", so shouldn't a click of the button call the enter method?

**Comment by cypherdare** [comment]
No, you're thinking of touchDown. Moving the cursor over the button from
off the button triggers enter.

**Comment by NathanSweet** [comment]
When you touch or mouse press you get an enter event where `pointer != -1`. InputListener#enter javadoc: Called any time the mouse cursor **or a finger touch** is moved over an actor.

**Comment by intrigus** [comment]
@NathanSweet
I don't really understand why you closed the issue. 
If the mouse is already over an actor, why should an enter and exit event be fired when I click the actor? 
Javadoc says that `exit` will be
````
Called any time the mouse cursor or a finger touch is moved out of an actor.
````

If I click, the cursor is definitely not moved out of the actor.

**Comment by cypherdare** [comment]
@intrigus it makes sense to me now. This is a dual purpose event. You get
events with pointer = -1 for hover entering and exiting, and events with
the pointer when clicking. Perhaps the Javadoc could be clearer.

**Comment by SomeTroglodyte** [comment]
You could also check `fromActor == null` or `toActor == event.listenerActor` to detect bogus events.

The mentioned JavaDoc is IMHO not clear enough, the only perfectly clear thing would be to read source:
https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/utils/ClickListener.java#L98-L104
