### ISSUE TITLE
Java cannot find audio class.

### ISSUE THREAD

**Issue by Shymain** [libgdx/libgdx#3941]
#### Issue details
I am trying to learn how to use the library, and while attempting to follow the instructions of the demo project, I am receiving a couple of unusual errors -- that java cannot find the class Audio in com.badlogic.gdx.Gdx, even though it has been imported, and I have checked the code of the library to ensure it is there. I suspect it is a case sensitivity error, but I can't be sure. Regardless, it is a problem, and I have absolutely no idea how to fix this, and after half an hour of Googling the problem and trying out solutions, including cleaning + rebuilding the project, I have been unable to fix this problem. I'm using Intellij IDEA, if that helps.

#### Reproduction steps/code
I haven't seen this anywhere else, but all I do to recreate this is create a new project using the gradle install, and follow the demo as to how you create a new game. Class: http://hastebin.com/sisuruvizi.avrasm

#### Version of LibGDX and/or relevant dependencies
The current version used in the Gradle install. 1.9.2, I believe.

#### Stacktrace
```java
Error:(26, 28) java: cannot find symbol
  symbol:   class audio
  location: class com.badlogic.gdx.Gdx
Error:(27, 28) java: cannot find symbol
  symbol:   class audio
  location: class com.badlogic.gdx.Gdx
```

#### Please select the affected platforms
- [x] MacOS

**Comment by badlogic** [comment]
`Gdx.audio` is a static variable, not a class. You use `new` with this
static variable, that obviously doesn't work. Remove `new` and all should
be fine (and then please close the issue :))

**Comment by Shymain** [comment]
I could have sworn I checked the code for stupid errors like this! Arrgh, that was a waste of time! Thank you for your help!
