### ISSUE TITLE
Tests/Demos Issue 

### ISSUE THREAD

**Issue by zerubeus** [libgdx/libgdx#3945]
#### Issue details
I've followed every step in the wiki to run tests but still getting this Error : 

```bash
Could not find or load main class com.badlogic.gdx.tests.lwjgl.LwjglTestStarter
```
what I'm missing ? 

####  platforms
- [ ] Windows

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
