### ISSUE TITLE
windows 10 gefroce gtx 960 slow performence

### ISSUE THREAD

**Issue by peterpostpunkgames** [libgdx/libgdx#3947]
Please ensure you have given all the following requested information in your report.

#### Issue details
_Please provide the details of your issue_

#### Reproduction steps/code
_Please provide the steps to reproduce this issue, or even better, a [SSCCE](http://sscce.org/) that reproduces your issue.
You can find barebones templates [here](https://github.com/libgdx/libgdx/wiki/Getting-help)_

#### Version of LibGDX and/or relevant dependencies
_Please provide the version(s) affected._

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by badlogic** [comment]
You successfully managed to ignore the issue template.
