### ISSUE TITLE
windows 10 slow performance

### ISSUE THREAD

**Issue by peterpostpunkgames** [libgdx/libgdx#3948]
hello,

When i generate default libgdx project via Setup app, after add a simply fps check in render method:

System.out.println(Gdx.graphics.getFramesPerSecond());

i have in my console max 30 fps.

What is wrong? Any ideas?

configuration:

newest libgdx
intel i5
geforce gtx 960

**Comment by badlogic** [comment]
Disable vsynch via Gdx.graphics or LwjglApplicationConfiguration. Check
your displays screen refresh rate, especially if you run in full screen.
Please close this issue and use the forums at
https://www.badlogicgames.com/forum

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
