### ISSUE TITLE
[OSX] (Scene2D) UI events sometimes doesn't work

### ISSUE THREAD

**Issue by Scellow** [libgdx/libgdx#3952]
#### Issue details
I run the game, UI events don't work, i have to double click to a button to trigger the clicked event, the button don't event display the down state

It's totally random, on different game restart, the issue will disappear

#### Reproduction steps/code
Just create some UI controls 

#### Version of LibGDX and/or relevant dependencies
1.9.3-SNAPSHOT
Lwjgl3 backend

#### Stacktrace
None

#### Please select the affected platforms
- [ ] Android (not tested)
- [ ] iOS (not tested)
- [ ] HTML/GWT (not tested)
- [ ] Windows (not tested)
- [ ] Linux (not tested)
- [x] MacOS

**Comment by Darkyenus** [comment]
Please provide [SSCCE](http://sscce.org/), without code it is practically impossible to determine what is the problem, especially when it is nondeterministic.

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
