### ISSUE TITLE
touch issue on ios for landscape orientation

### ISSUE THREAD

**Issue by serpent7776** [libgdx/libgdx#3954]
Please ensure you have given all the following requested information in your report.
#### Issue details

I'm experiencing issue similar to robovm/robovm#1236. On iOS 7 device in landscape orientation touches are incorrectly handled. Tested on libGDX 1.9.2. Everything works correctly for libGDX 1.8.0.
#### Reproduction steps/code

sample app here: [serpent7776/gdx-touch-issue-sample](https://github.com/serpent7776/gdx-touch-issue-sample)
#### Version of LibGDX and/or relevant dependencies

issue present on libGDX 1.9.2, robovm 1.14.0. Works correctly on libGDX 1.8.0
#### Stacktrace

not applicable 
#### Please select the affected platforms
- [ ] Android
- [X] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by rungkutta** [comment]
Yeah this is a known problem with a known fix, discussed in #3590 and #3709.  Landscape touch coordinates aren't interpreted correctly on both iOS 7 and iOS8 in the recent libGDX versions.

Anyone know when these fixes might get integrated?

**Comment by MrStahlfelge** [comment]
Is this still a thing? We could close the issue. I never had problems with my games on iOS.

**Comment by serpent7776** [comment]
Sorry, but I'm not using libGDX any more, so I'm unable to help.

**Comment by MrStahlfelge** [comment]
Ok, closing this. Probably fixed by #3590
