### ISSUE TITLE
FreeTypeFontGenerator GWT/HTML Support using JS library

### ISSUE THREAD

**Issue by np511** [libgdx/libgdx#3958]
In some of the projects I've created with libGDX, I've found the freetype extension invaluable. When I wish to give the player the ability to insert their own font, their is no better option. However, in a game with the ability for the user to choose their own font, HTML is no longer supported. I know that the extension uses native code, but there are JS libraries that can generate a font as well.

I have briefly looked at [OpenType.js](https://github.com/nodebox/opentype.js), and I looked at the variables in the console: [Live Example](http://nodebox.github.io/opentype.js/).

Is there any reason that OpenType.js and GWT could not be used?

**Comment by MobiDevelop** [comment]
Probably not something any of us has time to look into in the foreseeable future. Would be open to considering pull requests if someone implements. If you don't mind, I am going to close this out since it is not really an issue.

**Comment by intrigus** [comment]
@MobiDevelop There is still my PR #3857. When it has been merged and #3842 has been fixed, I could add gdx-freetype-gwt as a third party extension.
