### ISSUE TITLE
red & blue colors reversed on iOS device(on simulator not)

### ISSUE THREAD

**Issue by Gintasz** [libgdx/libgdx#3960]
If I run my game on iOS simulator, everything looks fine. If I run it on my device(iPhone 6), red and blue colors are reversed: http://i.imgur.com/fZKnlLs.png
Using libGDX 1.9.2, haven't tested on other versions.
This line exists in my robovm.xml, which supposedly should fix this issue, but doesn't:
```
<skipPngCrush>true</skipPngCrush>
```

**Comment by Darkyenus** [comment]
Check your robovm.xml again, I had this problem too and it turned out that the `<skipPngCrush>` was not in the right place. ([Example in docs](http://docs.robovm.com/configuration.html#resources))

**Comment by Gintasz** [comment]
Right, I had two _resource_ tags and _skipPngCrush_ had to be inside both of them. Thanks man.
