### ISSUE TITLE
Weird Scene2D stretched Image padding on iOS

### ISSUE THREAD

**Issue by Gintasz** [libgdx/libgdx#3962]
#### Issue details

Here is how it looks like on iOS:
![image](https://cloud.githubusercontent.com/assets/6189625/14034453/1ade46a6-f22c-11e5-9d59-70a864fb8b50.png)

on desktop(OS X) everything seems fine(same resolution):

![image](https://cloud.githubusercontent.com/assets/6189625/14034492/557da5ae-f22c-11e5-8dd5-6b9077b35cac.png)
#### Reproduction steps/code

```
float viewportWidth = Gdx.graphics.getWidth();
float viewportHeight = Gdx.graphics.getHeight();
this.stage = new Stage(new StretchViewport(viewportWidth, viewportHeight));
Gdx.input.setInputProcessor(stage);
TextureAtlas atlas = ResourceManager.getInstance().getTextureAtlas();

float bgstretchWidth = viewportWidth;
float bgstretchHeight = viewportHeight * 66f / 150f;
Image bgstretch = new Image(atlas.findRegion(Constants.UI_SPRITES_MAINMENU_BGSTRETCH));
bgstretch.setSize(bgstretchWidth, bgstretchHeight);
bgstretch.setPosition(0, viewportHeight * 35f / 150f);
stage.addActor(bgstretch);
```

```
@Override
public void render(float delta)
{
    Gdx.gl.glClearColor(38f / 256f, 35f / 256f, 34f / 256f, 1f);
    Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

    stage.act();
    stage.draw();
    stage.setDebugAll(true);
}
```

Image I'm stretching(it's 1px width):
![image](https://cloud.githubusercontent.com/assets/6189625/14034508/77b1b9bc-f22c-11e5-9e71-65a5972b22a7.png)
#### Version of LibGDX and/or relevant dependencies

1.9.2, haven't tested on others.

**Comment by NathanSweet** [comment]
You may need to use more pixels, eg 3 wide and stretch the center. I doubt there's anything we can do.
