### ISSUE TITLE
ApplicationListener.dispose for app in background on Android

### ISSUE THREAD

**Issue by alex-dorokhov** [libgdx/libgdx#3966]
#### Issue details
On Android, if app in **background** was killed by the user or by the system, then `ApplicationListener.dispose()` and `LifecycleListener.dispose()` is never called.

As consequences:
- no action performed for any listener implementations (consider user's native resources)
- static variables are not reset (e.g. `gdx.Timer` is deactivated and remains so on app restart)

#### Reproduction steps/code
The following steps should work on Android 4 and Android 5 at least.

1. Put log statements on `Activity.onDestroy` and setup listener with `Gdx.app.addLifecycleListener` inside your `ApplicationListener.create()` method
2. Open the app. Wait it is loaded
3. Press *Home* on Android.
4. Open *Recent activities* on Android and kill the app with a swipe.
5. See logs: `Activity.onDestroy()` is called, but `LifecycleListener.dispose()` is not

Alternative steps (to see how gdx.Timer stops to work):

1. see 1. step above
2. Open Android settings -> Developer settings, and enable option "Don't keep activities"
3. In the app add `gdx.Timer` task that should run after a few millis on some click event.
4. Open the app. Make the timer task run.
5. Press *Home* on Android
6. See logs: `Activity.onDestroy()` is called, but `LifecycleListener.dispose()` is not
7. Open the app from the recent activities on Android
8. Try to make the timer task run again. See nothing happens. Timer will not work until you kill the current VM (e.g. with a swipe in *Recent Activities*).

#### Version of LibGDX and/or relevant dependencies
1.9.2 or earlier

#### Please select the affected platforms
+ [x] Android

### Idea to fix
Seems the design of the current lifecycle methods was made to run them always in the gdx thread. Maybe if the app is going to be destroyed from background (Gdx lifecycle was already paused and `Activity.onDestroy` is called at the moment) it is safe to call `ApplicationListener.dispose()` and `LifecycleListener.dispose()` directly from the main Android's thread.

**Comment by MobiDevelop** [comment]
Since dispose involves destroying OpenGL resources, it has to be called on the render thread.
