### ISSUE TITLE
Gdx.input.setCursorPosition y coordinate is bottom-left on Mac

### ISSUE THREAD

**Issue by travishaynes** [libgdx/libgdx#3972]
`Gdx.input.setCursorPosition(0, 0)` on Linux puts the cursor at the top-left corner of the window, which is what the docs say it should do, but on Mac it puts the cursor at the bottom-left corner. I don't have Windows, so I don't know what it does on that OS.

I tested this in a new application created using the setup tool for version 1.9.2.

**Comment by intrigus** [comment]
Which backend?

**Comment by travishaynes** [comment]
When I step through the code it appears it is using lwjgl.

**Comment by travishaynes** [comment]
It looks like it inverts the cursor position intentionally: https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglInput.java#L1044 - which is what I ended up doing to workaround the issue.

**Comment by Tom-Ski** [comment]
We just defer to LWJGL for this, so it will most likely be an issue there.  Could you try this in fullscreen mode on Mac?

**Comment by travishaynes** [comment]
I tried maximizing the window, and using fullscreen in the lwjgl configuration. Both put 0,0 at the bottom-left.

**Comment by Tom-Ski** [comment]
Confirmed, I'm not sure it is even setting it correctly, any movement after the set will flash the cursor back to its original position.  But this is an Lwjgl 2.x issue, nothing we can do here I'm afraid.

**Comment by travishaynes** [comment]
So you're just going to call it somebody else's problem and ignore it? Why would you not fix it? Something like this should work:

```java
if (LWJGLUtil.getPlatform() == LWJGLUtil.PLATFORM_MACOSX)
  Mouse.setCursorPosition(x, y);
else
  Mouse.setCursorPosition(x, Gdx.graphics.getHeight() - 1 - y);
```

**Comment by Darkyenus** [comment]
This is an open-source project and contributors are volunteers. You are welcome to submit a PR though.

**Comment by Tom-Ski** [comment]
That's a hack, as lwjgl development on 2 has slowed down it may not be the worst workaround but when I tested on Mac not only did it give the wrong y coordinate but it wasn't persistent , something that couldn't be fixed with such a workaround .

----- Reply message -----

**Comment by travishaynes** [comment]
You are getting different results than I am, then, because the only thing that I'm seeing is that the y-coordinate is inverted.
