### ISSUE TITLE
TextArea & Android Auto Complete

### ISSUE THREAD

**Issue by doit-ceo** [libgdx/libgdx#3975]
Please ensure you have given all the following requested information in your report.
#### Issue details

I see a bug in Android, sometimes the Auto Complete gets active in the keyboard, most apps will show the text while typing in the field and in the keyboard, but in LibGDX, we can only see the text in the keyboard (Auto Complete bar) ! and it's confusing !

I have some images here 
http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=22040

Maybe the solution would be to allow the creation of custom AndroidOnscreenKeyboard, then developer can send some flags (on textView) to disable the Auto Complete or even show Numeric keyboard.
#### Reproduction steps/code

By default, you will not get Auto Complete bar in the keyboard, however, you may get it if you switch language or do other interaction with the keyboard, then the TextArea will longer receives the key events. 
#### Version of LibGDX and/or relevant dependencies

1.9.2
#### Stacktrace

``` java
//Please provide the stacktrace if applicable 
```
#### Please select the affected platforms
- [ ] Android

**Comment by MrStahlfelge** [comment]
This is not possible, libgdx can't know what the system keyboard will suggest. Besides, I don't have had that behaviour on any of my devices, so it was probably an system enhancement made by the manufacturer.
