### ISSUE TITLE
Replace all StringBuffers with StringBuilders

### ISSUE THREAD

**Issue by JFixby** [libgdx/libgdx#3977]
```StringBuffer``` is synchronized, ```StringBuilder``` is not.

Related reading: http://stackoverflow.com/questions/355089/stringbuilder-and-stringbuffer

**Comment by saltares** [comment]
Libgdx is generally not thread safe as pointed out in the documentation. I don't think we want to start making it thread safe in "some" places only.

From the thread you linked:

locka:
>  If someone wants to synchronize on a `StringBuilder`, they can just surround the entire block of code with a `synchronized (sb) { }` on the instance.

Peter Lawrey:
> I would argue that StringBuffer is never a good idea (unless you have an API which requires it

Won't close just yet. Maybe let someone else in the team pitch in.

**Comment by Darkyenus** [comment]
@saltares I believe this issue is to make it thread unsafe, that is to use the thread-unsafe version instead of the thread safe one.

This [report](http://pastebin.com/HSrymaJz) lists all places where StringBuffer is used (85 occurrences), some are obviously wrong, like in `toString()`.

**Comment by xoppa** [comment]
@JFixby please use the forum or irc if you want to start a discussion.
https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md

**Comment by JFixby** [comment]
There is nothing really to discuss. Libgdx currently uses thread-safe StringBuffer. I suggest to replace it with StringBuilders because for the reason @saltares just said:

> Libgdx is generally not thread safe as pointed out in the documentation. I don't think we want to start making it thread safe in "some" places only.

**Comment by davebaol** [comment]
Well, sounds reasonable as long as does not break public API

**Comment by JFixby** [comment]
StringBuffer is the evil synchronized twin brother of the StringBuilder. They are fully identical and mutually replaceable.

**Comment by davebaol** [comment]
Yes, I know, but if you replace a **public** `StringBuffer` with a `StringBuilder` you are making an API breaking change.

**Comment by JFixby** [comment]
I did ```ReplaceAll``` in Eclipse and looks like the StringBuffer is never used publicly: https://github.com/JFixby/libgdx/pull/9/files
