### ISSUE TITLE
ShapeRenderer not displayed on Android Flyme 4.5.4.2l

### ISSUE THREAD

**Issue by RotaruDan** [libgdx/libgdx#3982]
#### Issue details
I've quickly implemented an actor that draws a polygon using ShapeRenderer: https://github.com/RotaruDan/cytopathology/blob/prototype1/core/src/es/eucm/cytochallenge/view/widgets/challenge/result/PolygonActor.java#L14

This works completely fine on Desktop, HTML and most of Android devices I've tried, as you can see a correct result of the PolygonActor:

![image](https://cloud.githubusercontent.com/assets/5658058/14207891/fe39bf48-f81c-11e5-9941-94ca84b867bb.png)

but on the Meizu Note 2 Android phone (using Flyme 4.5.4.2l, Android 5.1 OS): http://www.gsmarena.com/meizu_m2_note-7266.php
the polygon isn't displayed at all. There is no crash, so the application keeps running correctly with the difference that no pollygon is drawn.

#### Version of LibGDX and/or relevant dependencies
gdxVersion = '1.9.1'

#### Affected platforms
- Android

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info

**Comment by RotaruDan** [comment]
I'll provide more information as soon as I can :+1:

**Comment by Darkyenus** [comment]
Make sure to check OpenGL error; [GLProfiler](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/profiling/GLProfiler.java) class provides a convenient way to do it.

**Comment by xoppa** [comment]
Okay, will close this for now. Please reopen when you added the required information.
