### ISSUE TITLE
New 'Data' FileHandle location type

### ISSUE THREAD

**Issue by me4502** [libgdx/libgdx#3989]
Currently there isn't a FileHandle type that properly fits the generic application data store on different systems.

A data type would preferably store files in the Application Support folder on a Mac, AppData on Windows, the Data section of the app on iOS, and the Data section of the app on Android.

For the desktop OSs, it'd also make sense to have it inside it's own folder, so instead of just the raw AppData, it could be in AppData/ProgramName

The current closest is external, which saves to the SD card on android and the users home directory. The iOS behaviour is undefined by the javadocs. This behaviour however, this is not preferable for storing data.

**Comment by krukhlis** [comment]
Imho, it's almost impossible. Even with Windows there is no guarantee the AppData will be used. And even if it's used -- there are 2 options: local and roaming. Under various linux distib-s -- I've seen different approaches as well for application data:** ~/.local/share** vs **user.home** env. var. Under Mac OS as far as I remember Apple also recommends against any hardcode of the Application Support folder.
Guys can say about Android( different versions) and iOS more. Also, it's unclear what can be  used for Web.

Preferences, actually do most of the job for "Data" type. And they are crossplatform.

**Comment by nhydock** [comment]
Typically what I use is this

```
public static String getAppData() {
        String path;
        FileHandle h;
        if (UIUtils.isWindows)
            path = System.getenv("APPDATA") + "/" + APPNAME;
        else if (UIUtils.isMac)
            path = System.getProperty("user.home") + "/Library/Application Support/" + APPNAME;
        else
            path = System.getProperty("user.home") + "/.local/share/" + APPNAME;

        h = Gdx.files.absolute(path);
        if (!h.exists()) {
            h.mkdirs();
        }
        return path;
    }
```

On windows, app data will go underneath roaming, whereas on linux it goes underneath the local/share folder typically found in a user's home directory, where apps save user data that's not typically config files.

**Comment by me4502** [comment]
The standard place for stuff to go on Windows is AppData/Roaming.
There are places on the other OSs that are specified for this purpose. And preferences are only useful for preferences, not storing of potentially hundreds of megabytes of downloaded data, such as level packs etc,

**Comment by np511** [comment]
On windows, a good method is to use `System.getProperty("user.home")+"/Saved Games/appname"`.
On Linux, `System.getProperty("user.home")+".config/appname"`.

IIRC, the Windows one will work on anything 98 or newer (meaning always), and the Linux one will work for sure on Debian-based systems (including Ubuntu and IIRC Mint), and if you create parent folders as well it will work even if it non-standard.

**Comment by intrigus** [comment]
http://stackoverflow.com/questions/16889940/on-windows-7-how-does-java-jvm-set-user-home-system-property

**Comment by np511** [comment]
I realized a better solution anyway:

Display a file chooser and have the user manually choose where they want it. This provides the additional bonus that the user won't accidentally delete it, not knowing what it is, and enables storing data on a portable device (SD card, USB, etc).

For large files, the user should be warned about both the size and increased rate of deterioration of USB devices.

**Comment by me4502** [comment]
A file chooser isn't really a better solution. The OS specifies locations as data locations for a reason. And a file picker wouldn't work properly on iOS or android.

**Comment by MobiDevelop** [comment]
I don't think we need yet another FileType personally.

**Comment by me4502** [comment]
This filetype to me seems like the one that would actually be most used.

It'd be where games store there data, in the designated data spot of the OS

**Comment by Tom-Ski** [comment]
Games generally store their data in the private data location for the game, that way when it the app is uninstalled, their data and files are cleaned up too.  It also is always available, and it is only accessible by your app.

A Data FileType might be nice if there is a neat solution for it, but the suggested use cases aren't the ones that would be suitable.

**Comment by me4502** [comment]
What do you mean by private data location?

**Comment by Tom-Ski** [comment]
In terms of LibGDX, the Local FileHandle.  On Android this is the private files location for the app. On iOS, it is a subdirectory in the the per-app data container, which prevents users from gaining access, as well as other apps.  On mobile this means easy clean up, and a tiny bit of security.  On the desktop platforms, the location of local is where the application is, which makes for a nice portable install.

If the data belongs to your app, and should be deleted when the user uninstalls, then you should be using local.  If the data is something that should persist, for example taking screenshots, or if your app is a photo editor, you would want to save the output somewhere sensible for the data type, and somewhere it would persist with or without your app.  e.g the external file type.

**Comment by krukhlis** [comment]
I also can't understand why we need special File handle type for this particular limited case. If someone needs to find a dir for saves -- he can use either local handle, either something similar to https://github.com/libgdx/libgdx/issues/3989#issuecomment-205618029
Or invent its own specific wheel( 15-30 lines of code to locate the right folder). Why should one extend the whole platform just for particular application needs? Also, do not forget that you have to (in any case) handle security exceptions -- if you decide to write to some folder it doesn't mean the application will have write access to this folder. So in any case you will need to deal with particular directories and design your own fallback mechanism.

Otherwise -- lets create separate File Handle type for **temporary folder**, etc. ( this folder is for lots of applications even more important 'n folder for saves). [It's joke, I'm against this as well]

**Comment by np511** [comment]
I think temporary files and folders are already supported.

**Comment by xoppa** [comment]
I agree with @Tom-Ski, indeed not convinced of the use-case for this new file type. Closing this, please reopen if you can add a well-defined use-case/implementation.
Btw, please don't store hundreds of megabytes of downloaded data in a roaming profiles.

**Comment by np511** [comment]
Actually, after spending the weekend cleaning up my computers (both my 
Microshit - sorry, Micro/soft/ - one and my Debian one), I can't agree 
more. I removed over 3GB that was in there and unneeded. When using a 
32GB Acer Cloudbook (which I didn't realize came with Restricted Boot 
until too late) and storing most files locally, that's kind of 
important. Storing that much in the roaming profile is evil.
