### ISSUE TITLE
Preferred IPA build method: Gradle vs RoboVM plugin?  Size difference

### ISSUE THREAD

**Issue by rungkutta** [libgdx/libgdx#3993]
#### Issue details
As far as I can tell, there are at least two ways to generate an IPA for iOS testing or deployment.  I have previously used Gradle at the command line: `gradle ios:createIPA`

With the RoboVM plugin in Intellij IDEA, you can also select `Create IPA` from the `Build` menu.

I've been unable to determine the technical differences between these two, but I have noticed that the IDEA method creates a much larger IPA.  On one example app, Gradle makes a 34 MB IPA, while IDEA makes a 42 MB one, ~~and both seem to work equivalently~~.  Correction: the IDEA version won't run at all on a development device - I think this might be a signing issue?

Opening up the two IPAs, everything is identical except the executable (`Payload\appname.app\appname`), which is way bigger on the IDEA version.

Any ideas what's going on, or what to check for?  Is this due to some setting I'm not understanding?  Is one of these methods preferred?

#### Reproduction steps/code
- Create an IPA at the command line: `gradle ios:createIPA`
- Create an IPA in Intellij IDEA: `Build > Create IPA`
- Compare!

#### Version of LibGDX and/or relevant dependencies
libGDX 1.9.1
RoboVM 1.12.0

#### Please select the affected platforms
- [ ] Android
- [x] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
At a guess, the IDEA build might automatically create the 64 bit version too.  It looks a little small for that though, so perhaps its bitcode being generated automatically with the IDEA plugin.  Try the different arguments for the gradle plugin to test. See https://github.com/robovm/robovm-gradle-plugin for docs.

**Comment by rungkutta** [comment]
Yep, I just figured this out, thanks.  The IDEA build did include the 64 bit version, and the size difference between the IPAs was actually much larger once unzipped.

Are you saying there's a way to set arguments for the plugin within IDEA, or is this a suggestion to keep using the command line?

I was able to build the 32-and-64-bit version on the command line, and got a similar result to what IDEA made.  However, the IDEA version _will not_ run on a development iPad - the home icon disappears after installation, before I have a chance to run it.  I think this may be a signing identity problem - IDEA forces you to choose, whereas the simple `gradle ios:createIPA` command doesn't.  Any idea how I would figure out what the simple command uses?  Or am I off track here?

**Comment by Tom-Ski** [comment]
I think intellij robovm plugin just invokes the gradle plugin.  With the intellij plugin I believe you can select the signing identity, provisioning profile and the architectures you want to use.  On command line I think it will still try to find some identity to use if you don't supply one, not 100% on that.  I'm going to close this issue out though as it is best suited to either the libgdx forum or the robovm groups.
