### ISSUE TITLE
Implement GPU-based font rendering

### ISSUE THREAD

**Issue by xSke** [libgdx/libgdx#3995]
I saw [this post](https://medium.com/@evanwallace/easy-scalable-text-rendering-on-the-gpu-c3f4d782c5ac) on reddit, and I feel like it would be great to have built-in to libGDX. It would probably work similar to the DistanceFieldFont, API-wise.

**Comment by MobiDevelop** [comment]
This feels like a conversation better suited for the forum or IRC. If you have an idea for implementing this in a cross-platform way, please work up a proposal and open a discussion and/or PR.
