### ISSUE TITLE
Gdx.graphics.getDisplayMode Returns Incorrect Results on LWJGL 2 Backend

### ISSUE THREAD

**Issue by 3xp0n3nt** [libgdx/libgdx#3997]
#### Issue details

`Gdx.graphics.getDisplayMode` returns incorrect results in **1.9.3-SNAPSHOT** with **LWJGL 2** backend. Works in **1.9.2**. Untested on other backends.

Returns correct results in main thread, but in render thread, window size is reported, not screen size. Also, bpp & hz are 0 (unset).

#### Reproduction steps/code
```
import com.badlogic.gdx.*;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.graphics.GL20;

public class Barebones extends ApplicationAdapter {
    public void create () {
        System.out.println("Incorrect: " + Gdx.graphics.getDisplayMode());
    }

    public void render () {
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
    }

    public static void main (String[] args) throws Exception {
        new LwjglApplication(new Barebones());
        System.out.println("Correct: " + Gdx.graphics.getDisplayMode());
    }
}
```

#### Version of LibGDX and/or relevant dependencies
LibGDX 1.9.3-SNAPSHOT
LWJGL 2 backend

#### Stacktrace
N/A

#### Please select the affected platforms
- [ ] Android - **UNTESTED**
- [ ] iOS - **UNTESTED**
- [ ] HTML/GWT - **UNTESTED**
- [X] Windows
- [ ] Linux - **UNTESTED**
- [X] MacOS

**Comment by 3xp0n3nt** [comment]
Potential culprit is [#3903 L520](https://github.com/libgdx/libgdx/pull/3903/commits/de9b7e72f0b0fd81aff6927f40218fe50db9941a#diff-dbd98d8fdbc32ac832444afac3ab31d2R520).

**Comment by Tom-Ski** [comment]
Thanks @3xp0n3nt, nice catch.

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://Phantom-Products.com/haul.php?tlu>

 

loogie@basicelementdesign.com

**Comment by IonAgorria** [comment]
The problem with this is that when you switch to a display mode with different HZ freq other than the monitor highest value, the getDesktopDisplayMode() doesn't reflect the current HZ but the highest one.

My original intention was to get the current HZ, also I guess that the zero bpp and hz is due to being in window mode, which doesn't report such values AFAIK

**Comment by 3xp0n3nt** [comment]
> IonAgorria commented 2 days ago • edited
> The problem with this is that when you switch to a display mode with different HZ freq other than the monitor highest value, the getDesktopDisplayMode() doesn't reflect the current HZ but the highest one.

Please create a new issue about this, with all of the relevant information (affected platforms, how to reproduce, etc).
