### ISSUE TITLE
TransformDrawable's draw method not implemented in TiledDrawable

### ISSUE THREAD

**Issue by gknedo** [libgdx/libgdx#4005]
*Sorry for my horrible english.
#### Issue details

Basically, if u draw a TiledDrawable after a cast to a TransformDrawable and use the method draw of TransformDrawable interface the TextureRegion wont draw tiles, it extend like standard TextureRegion.
#### Reproduction steps/code

This is where i create a TiledDrawable and return as a TrasformDrawable.

```
private static TransformDrawable createDrawable(float x, float y, float width, float height) {
        TiledDrawable drawable = new TiledDrawable(getAtlas().findRegion("tile_wood"));
        return drawable;
    }
```

and here is where i draw, if i do this, the texture will be expanded and not tiled:

`transformDrawable.draw(batch, x, y, originX, originY, width, height, scaleX, scaleY, rotation);`

and it tiles normally if i do this:

`transformDrawable.draw(batch, x, y, width, height);`
#### Version of LibGDX and/or relevant dependencies

Tested on libgdx 1.9.2, compiling for Windows.
#### Please select the affected platforms
- [x] Android
- [x] iOS
- [x] HTML/GWT
- [X] Windows
- [x] Linux
- [x] MacOS

**Comment by gknedo** [comment]
Looking in code libgdx, what cause this bug is because TiledDrawable extends TextureRegionDrawable and wont override the draw method inherited from TransformDrawable.

**Comment by Tom-Ski** [comment]
Yup, PRs welcome to implement that method.

**Comment by NathanSweet** [comment]
Yep, PR is welcome to implement rotated and scaled drawing for TiledDrawable.
