### ISSUE TITLE
ios constant memory increases in empty render loop

### ISSUE THREAD

**Issue by sicancode** [libgdx/libgdx#4006]
#### Issue details
Running a simple libgdx app on IOS will result in a constant increase in memory, ~1/3 of a MB per ten seconds. This is using a sample that does nothing in the render loop.

This is a problem as eventually it's going to generate garbage collection, let alone when you add your game code on top.

Perhaps I am doing something wrong?

#### Reproduction steps/code
Simply run the libgdx setup sample code (libgdx project generator, gdx-setup.jar) on ios simulator or real device, attach "instruments" app and observe the rapid memory increases.
I've also created a quick sample to show this in log statements: http://pastebin.com/QEiYLRLA
#### Version of LibGDX and/or relevant dependencies
gdxVersion = '1.9.2'
roboVMVersion = '1.12.0'
eclipse mars
robovm plugin 1.14 

#### Please select the affected platforms
- [x] iOS

**Comment by sicancode** [comment]
The Desktop version has similar increases but eventually will level out and stop.. ios will continue all day.
Would really appreciate some input on this one. Hopefully it's something I have just overlooked?

many thanks

**Comment by intrigus** [comment]
How have you determined that "ios will continue all day" ?
Garbage collection is a normed thing that has sometime to happen. You should try to minimise it, but you can't avoid it.

**Comment by sicancode** [comment]
It continuously increases in memory usage and will eventually GC.

When you use pools and spend time making sure your application doesn't need to GC only to find that the underlying engine is not trying ( at all it would seem ) to do the same, it's very disappointing.

Obviously GC is the Java way but 1/3MB per ten seconds? seriously you defend this?

**Comment by Tom-Ski** [comment]
You shouldn't be seeing any increase with just libgdx. Please post a test that doesn't create new string objects and still reproduces the issue.

**Comment by sicancode** [comment]
http://pastebin.com/FqRA5tQq

**Comment by sicancode** [comment]
Total Bytes continues to increase while the application has no implementation ~1/3mb every ten seconds.

**Comment by sicancode** [comment]
@Tom-Ski Add this as the libgdx application on ios and attach instruments to see the increases

**Comment by Tom-Ski** [comment]
Have you tested that example on desktop? I see no increase at all apart from the initialization of LibGDX.

**Comment by sicancode** [comment]
As per original comment, Desktop is ok. This bug is specifically targeted at ios performance.
Out of interest, did you try the example above on IOS as per my original post?

**Comment by xoppa** [comment]
which device did you test this on?

**Comment by sicancode** [comment]
I do appreciate it's quite possible I am doing something wrong.. but I am totally stuck with this and hope that libgdx on ios doesn't consume as much memory as the profiler is suggesting.

**Comment by Tom-Ski** [comment]
You said `The Desktop version has similar increases`... I am running a blank application, no increase on desktop at all.

**Comment by sicancode** [comment]
"will level out and stop"

**Comment by sicancode** [comment]
iPhone 6 iOS 9.2 simulator and real device.

**Comment by Tom-Ski** [comment]
Please take it easy on commenting, every comment will send email notifications to anyone following the project.   

With regards to you issue, I think you may be misunderstanding some of the columns in the Instruments application.  There is no leak for me when I am testing on iPhone 6 iOS 9.2 sim.  Perhaps you are looking at just the total amount of allocations (which should always go up as the app is constantly allocating and de-allocating memory), rather than the actual persistent memory usage which stays the same as long as you aren't personally allocating memory.

**Comment by sicancode** [comment]
Thanks @Tom-Ski so "Persisted Bytes" is the only one that matter heres? This value is certainly stable. 
#Persistent #Transient and more importantly 'Total Bytes' do all go up, but if these are definitely not important then that's great.

**Comment by Tom-Ski** [comment]
In terms of actually leaking memory, yes.

Check out https://developer.apple.com/library/ios/documentation/DeveloperTools/Conceptual/InstrumentsUserGuide/Instrument-Allocations.html for clarification on each of the columns.
