### ISSUE TITLE
Use of Google Guava with GDX causes GWT compilation to fail.

### ISSUE THREAD

**Issue by juckele** [libgdx/libgdx#4007]
#### Issue details
Importing com.google.common.io.BaseEncoding into the core project of a gdx project causes the gwt compilation to fail. This is specifically an interaction with gdx, as removing the gdx code will allow the gwt code to compile.

#### Reproduction steps/code
I've created a repo that reproduces this in the minimum amount of code here: https://github.com/juckele/gdx-gwt-guava-bug

Clone the repo and run `gradle war` with and without commenting out the libgdx inherit line in the html project's main gwt.xml file.

#### Version of LibGDX and/or relevant dependencies
I was able to reproduce this is 1.9.2 and 1.9.1

#### Stacktrace
```
   Validating units:
      [ERROR] Errors in 'com/google/common/io/super/com/google/common/io/BaseEncoding.java'
         [ERROR] Line 142: The constructor IOException(Throwable) is undefined
   [ERROR] Aborting compile due to errors in some input files
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [X] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by juckele** [comment]
I thought about this some more and think I might have found the issue:

This is the GWT source for IOException:
https://github.com/gwtproject/gwt/blob/master/user/super/com/google/gwt/emul/java/io/IOException.java

GDX also has emulation source for IOException:
https://github.com/libgdx/libgdx/blob/master/backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/java/io/IOException.java

It seems that the Java library emulation in gdx is an older or less complete version than the most recent GWT emulation code.

Without investigating full feasibility yet, would it made sense to use GWT Java core code emulation through dependencies instead of copying GWT source directly?

**Comment by juckele** [comment]
Alternatively, could we just rely on the GWT specified in the gradle build files?

**Comment by juckele** [comment]
BTW, how often do SNAPSHOT builds get deployed? It looks like what's up on sonatype is still a couple of weeks before this change: https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/gdx/gdx-backend-gwt/1.9.3-SNAPSHOT/

**Comment by MobiDevelop** [comment]
The builds are currently not completing due to the mac being offline, until @badlogic gets that up and running again we'll see no new builds.
