### ISSUE TITLE
ARM64/x86_64 Android binaries not ignored by version control

### ISSUE THREAD

**Issue by Fringale** [libgdx/libgdx#4016]
#### Issue details
It’s not really important, but the recently added ARM64 and x86_64 binaries for Android can inadvertently get committed to version control, as the following paths haven’t been added yet to the corresponding gitignore file (https://github.com/libgdx/libgdx/blob/master/extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/gitignore#L21):

> android/libs/arm64-v8a
> android/libs/x86_64

#### Reproduction steps/code
- Create a new LibGDX project
- (I’m using Mercurial, so I rename .gitignore to .hgignore and add `syntax: glob`, but, well, it shouldn't matter : p )
- Use the 'status' command of the VCS or refresh using the IDE

=> The `android/libs/arm64-v8a/libgdx.so` and `android/libs/x86_64/libgdx.so` binaries show up with the other unversioned files to add.

#### Version of LibGDX and/or relevant dependencies
1.9.2

#### Stacktrace
N/A

#### Please select the affected platforms
N/A

**Comment by intrigus** [comment]
I'll try having a look at this tomorrow, since there are also other directories that should be excluded from VCS.

**Comment by Fringale** [comment]
Neat, thanks. : ) If you're doing a pass on that file, some potential additions off the top of my head would be `thumbs.db` (the dreaded counterpart to `.DS_Store`) and `ios/robovm-build`.

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://digiasia.net/maintain.php?h4>

 

loogie@basicelementdesign.com
