### ISSUE TITLE
Bullet - btActionInterface Inheritance

### ISSUE THREAD

**Issue by floralvikings** [libgdx/libgdx#4022]
#### Issue details
It would be very useful if it were possible to inherit from the `btActionInterface` class to create custom actions to be executed during a simulation step of a `btDynamicsWorld`; this is how the example `btKinematicCharacterController` class included in Bullet works.

I'm not terribly familiar with JNI, SWIG or how the native wrapping in libGDX works, but if I understand SWIG correctly it should be possible to generate a "director" class from the native C++ code that acts as a go-between for Java and C++.  According to the [Wiki Page](https://github.com/libgdx/libgdx/wiki/Bullet-Wrapper---Using-the-wrapper) on using the Bullet wrapper, there are already several callback classes that do something similar, but I'm completely clueless with regards to how those classes were created/written.

#### Reproduction steps/code
Not really a bug, as you wouldn't expect it to work in the first place, but inheriting from the `btActionInterface` and overriding the `updateAction` method has no effect on the native Bullet code.  

Without knowing that the Bullet classes are wrapped native C++, I would've assumed that the overridden `updateAction` method would execute during the `stepSimulation` call on a `btDynamicsWorld`. 

Using an anonymous override of `btKinematicCharacterController` as an example; as far as I'm aware, this and `btRayCastVehicle` are the only concrete implementations of this class:

```java
new btKinematicCharacterController(body, shape,  DEFAULT_SIZE.y * 0.5f) {
    @Override
    public void updateAction(btCollisionWorld collisionWorld, float deltaTimeStep) {
        super.updateAction(collisionWorld, deltaTimeStep);
        System.out.println("Test"); // Doesn't execute, no native calls to the Java code
    }
};
```

#### Version of LibGDX and/or relevant dependencies
All versions of gdx-bullet

#### Stacktrace
Not Applicable

#### Please select the affected platforms
- [x] Android
- [x] iOS
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by floralvikings** [comment]
I've actually got this working locally now, after adding this line to `dynamics.i`:

```c
%feature("director") btActionInterface;
```

I regenerated the swig files using the Ant build in `extensions/gdx-bullet/jni/swig` and rebuilt libGDX from source.

Didn't realize it at the time, but I had actually installed swig 3.0.8, so a handful of the files in `swig-src` had a few changes made to them, and they all had the version number in the leading comment updated; everything seems to be running just fine though.  Would you like a PR with those changes?  Or prefer me to get ahold of swig 3.0.7 and generate the wrapper code with that?

**Comment by xoppa** [comment]
A PR would be good, thank you. Updating SWIG is okay. If it's difficult to read / differentiate the actual changes from generated changes, then please split them into two commits.

How much is this method going to be called though? The method signature contains a reference to the collisionworld and debugdrawer. If we don't take care of that then it would create at lot of garbage and might cause hickups.

Perhaps a new director class, e.g. `CustomKinematicCharacterController`, which has a method `virtual void updateAction(float deltaTime)` (so without the collision world), would be an alternative?

**Comment by floralvikings** [comment]
Hadn't thought of that; the method is called on every action added to a `btDynamicsWorld` each time the `stepSimulation` method is called, so... a lot.   Without access to the collision world, tough, I don't know if implementing the interface is as useful.  Although I suppose the collision world could just be passed into implementations of the class via a constructor or setter.

I'll see about adding the new director class and get back with a PR.  Thanks for the quick response!

**Comment by floralvikings** [comment]
@xoppa Do you mind taking a look at that PR and making sure I understood what you meant RE the excess garbage from the method signature?
