### ISSUE TITLE
DecalBatch should explicitly bind textures to unit 0.

### ISSUE THREAD

**Issue by tdzbdao** [libgdx/libgdx#4024]
Please ensure you have given all the following requested information in your report.

#### Issue details

When using a `DecalBatch` along with custom texture binding, `Material.set()` called in `DecalBatch.render()` is not guaranteed to bind to texture unit 0 anymore. This results in garbage results while rendering. An easy fix would be to add this line before calling Material.set(): 
`Gdx.gl.glActiveTexture(GL20.GL_TEXTURE0);`

#### Reproduction steps/code
Manually binding any texture to texture in prior to call `DecalBatch.flush()` will trigger this. The reason this is happening is because `Material.set()` does not explicitly bind the texture to a fixed unit. Instead, the currently active texture unit state is used. The shader program used for decal rendering on the other hand requires `u_texture` to be bound at texture unit 0.

#### Version of LibGDX and/or relevant dependencies
1.7.2

#### Please select the affected platforms
- [x] Android
- [x] iOS
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info
