### ISSUE TITLE
SequenceAction not restarting

### ISSUE THREAD

**Issue by ivanvinski** [libgdx/libgdx#4033]
#### Issue details
_When I call restart() on SequenceAction, it doesn't restart. When I call it on Action, it restarts._

#### Reproduction steps/code
_http://www.java-gaming.org/topics/libgdx-action-restart-works-sequencedaction-restart-doesn-t-work/37350/view.html
or
http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=22349_

#### Version of LibGDX and/or relevant dependencies
_1.9.1_

#### Stacktrace
```java
No stack trace.
```

#### Please select the affected platforms
- [*] Android
- [*] iOS
- [*] HTML/GWT
- [*] Windows
- [*] Linux
- [*] MacOS

**Comment by piotr-j** [comment]
Not a bug. Pooled actions are reset automatically when done. Done hold references to pooled actions.
