### ISSUE TITLE
Pressing "Enter" on Mac using the LWJGL3 backend doesn't insert a new line into a TextArea

### ISSUE THREAD

**Issue by intrigus** [libgdx/libgdx#4034]
#### Issue details

Pressing "Enter" on a Mac using the LWJGL3 backend doesn't insert a new line into a `TextArea`.
It works perfectly fine using LWJGL2.
#### Reproduction steps/code

``` java
public class LWJGL3TextAreaTest extends GdxTest {
    private Stage stage;
    private Skin skin;

    @Override
    public void create () {
        stage = new Stage();
        Gdx.input.setInputProcessor(stage);
        skin = new Skin(Gdx.files.internal("data/uiskin.json"));
        TextArea textArea = new TextArea(
            "Text Area\nEssentially, a text field\nwith\nmultiple\nlines.\n"
                + "It can even handle very loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong lines.",
            skin);
        textArea.setX(10);
        textArea.setY(10);
        textArea.setWidth(200);
        textArea.setHeight(200);

        TextField textField = new TextField("Text field", skin);
        textField.setX(10);
        textField.setY(220);
        textField.setWidth(200);
        textField.setHeight(30);
        stage.addActor(textArea);
        stage.addActor(textField);
    }

    @Override
    public void render () {
        Gdx.gl.glClearColor(0.2f, 0.2f, 0.2f, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        stage.act();
        stage.draw();
    }

    @Override
    public void resize (int width, int height) {
        stage.getViewport().update(width, height, true);
    }

    @Override
    public void dispose () {
        stage.dispose();
        skin.dispose();
    }
}

```
#### Version of LibGDX and/or relevant dependencies

Latest Master/ Libgdx 1.9.3-SNAPSHOT 
LWJGL3 backend
#### Issue description/solution

The problem is that LWJGL3 generates '\r' on an enter press, while LWJGL2 generated a '\n' on an enter press. Therefore [this line](https://github.com/libgdx/libgdx/blob/a1a2cb9df14016d34b735995e826f44386b3796e/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextField.java#L950) (`ENTER_ANDROID` is '\r') is executed, which selects the next text field.
#### How to fix?

I don't know how to fix this issue. We could either generate '\n' key events instead of '\r' events or we could fix the `TextField` class.
#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS

**Comment by krukhlis** [comment]
It's strange and i think it is bug in LWJGL3. Before MacOS X -- apple used '\r'. So it was funny:
1) Unix uses '\n'
2) MacOS '\r'
3) Windows uses both at the same time CR+LF
But with MacOS X, which is Unix based, there should be regular '\n' used. I've checked on my MBP13 -- all applications show that I type '\n' on an "enter" press.

**Comment by nlert** [comment]
Had this same issue on Windows just now.

Making a version of the TextField class that used '\n' for ENTER_DESKTOP instead of '\r' did seem to resolve it in my case.

**Comment by badlogic** [comment]
Confirmed, wth.

**Comment by voidburn** [comment]
I noticed it too, pressing enter either in a textfield or textarea cycles the focus like tab does.

**Comment by kylemclean** [comment]
This issue still exists. The easiest solution would be to remove the behaviour of pressing ENTER_ANDROID to change focus.

**Comment by crykn** [comment]
This is no longer an issue.
