### ISSUE TITLE
[BUG] JRE 8 fails to open LibGDX project with OpenGL error

### ISSUE THREAD

**Issue by SonicACCEL** [libgdx/libgdx#4040]
#### Issue details

If a LibGDX project is opened on the PC (Windows 10, HD Graphics 3000, latest drivers) and JAVA JRE 8 32-bit is installed, the following error is thrown:

"OpenGL 2.0 or higher with the FBO extension is required. OpenGL version 1.1.0"

If JAVA JRE 8 32-bit is uninstalled, and JAVA JRE 7 32-bit is installed instead -- the project runs with no problems.

Another user describe the same issue and solution here: http://stackoverflow.com/questions/32423629/opengl-2-0-or-higher-with-the-fbo-extension-is-required-libgdx-error

#### Version of LibGDX and/or relevant dependencies
LibGDX 1.6.4
JAVA JRE 8 [Broken]
JAVA JRE 7 [Works]

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [X] Windows
- [?] Linux
- [?] MacOS

**Comment by MobiDevelop** [comment]
Please update to the latest version of libgdx and see if the issue still exists. There have been quite a few releases since 1.6.1.

**Comment by SonicACCEL** [comment]
I apologize, the version is 1.6.4

Is it a known issue that was fixed in a later release?

**Comment by jpsgamboa** [comment]
I've run into this problem with an HD Graphics 3000. I don't know the real cause, but seems like a combination of Windows 10 and JRE 8u60+. Can you try running your project with a JRE 8u51 or previous and see of it works?

**Comment by MobiDevelop** [comment]
It is only getting an OpenGL version of 1.1.0, why that is I don't know - it is probably specific to certain configurations where it is falling back to a software renderer.

**Comment by krukhlis** [comment]
Guys, you can check this:
https://www.reddit.com/r/techsupport/comments/3imyud/opengl_problems_on_windows_10_with_intel_hd/

It's well known problem with intel HD/3000 specificly and win10( part of the responsibility is on microsoft with their ugly win10).

Just quote:

> What is your version of JAVA? With Java version 8 update 60 and windows 10 you get this error. You can get java 8 update 45

> Holy cow, it actually worked

You can try different versions like 8.5x as well.

**Comment by SonicACCEL** [comment]
Thank you for the awesome help,

I installed Java 8 update 51 and it works perfectly.

But as to the root cause, will updating to the latest version of LibGDX certainly fix compatibility with Java 8 build 60 and later? 

Is there a specific LibGDX version where this issue was resolved?

**Comment by MobiDevelop** [comment]
Sounds to me like it isn't a libgdx problem but a Windows/Java problem. So, no, there is no guarantee that updating libgdx will fix it.

**Comment by krukhlis** [comment]
Hi SonicACCEL.
This problem is not caused by LibGDX. Any Java application with JRE 8.60 on Win 10 with Intel HD\3000 chip will experience the same. Moreover, it's not only Java that suffers. Some native games that require OpenGL also fail in the same setup. One was Medal Of H-r. At the same time other native games can work in OpenGL mode on the same system.

I will even add that I've seen Blender Game Engine fails on the same setup( and it has no relation to java at all)
