### ISSUE TITLE
RoboVM - FitViewport doesn scale properly on iOS

### ISSUE THREAD

**Issue by dorottyas** [libgdx/libgdx#4042]
Hey guys, I am almost done creating my first game, however, I have run into some problems on the iOS version. i use FitViewport for each of my Screens, but it doesn't seem to dothe job. The code below works perfect on Desktop and Android.

#### Issue details
i use a class called Renderer to initialize the elements for resizing, and I call them in the resize method of the Screen class. 

#### Reproduction steps/code

```
camera = new OrthographicCamera(MenuScreen.VIRTUAL_WIDTH,
            MenuScreen.VIRTUAL_HEIGHT);
viewport = new FitViewport(MenuScreen.VIRTUAL_WIDTH,
            MenuScreen.VIRTUAL_HEIGHT, camera);
viewport.apply();
camera.position.set(camera.viewportWidth / 2,
            camera.viewportHeight / 2, 0);
b = new SpriteBatch();
b.setProjectionMatrix(camera.combined);
```

```
@Override
public void resize(int width, int height) {
    renderer.getViewport().update(width, height);
    renderer.camera.position.set(renderer.camera.viewportWidth / 2,
            renderer.camera.viewportHeight / 2, 0);
    renderer.getB().setProjectionMatrix(renderer.getCamera().combined);

}

```

Here is a photo of the simulator (iPhone 6s [9.3], iPhone 5 looks completely the same)

![qhzkw](https://cloud.githubusercontent.com/assets/18572347/14671676/6399229a-06f3-11e6-826b-05cbfd9b7141.gif)

#### Please select the affected platforms
- [ ] iOS
- [ ] MacOS
- [ ] libGDX
- [ ] RoboVM
- [ ] resize
- [ ] FitViewport
- [ ] OrthographicCamera``

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info
