### ISSUE TITLE
com.badlogic.gdx.graphics.Camera.unproject alters given Vector3 values

### ISSUE THREAD

**Issue by jani-r** [libgdx/libgdx#4043]
Please ensure you have given all the following requested information in your report.

#### Issue details
Method public Vector3 unproject(Vector3 screenCoords) in com.badlogic.gdx.graphics.Camera alters values of it's parameter. This is quite surprising given the definition and description in API "Function to translate a point given in screen coordinates to world space."

I would suggest changing the API documentation to be more clear that the contents of the given Vector3 will be also modified.

#### Reproduction steps/code

camera.unproject(tp.set(screenX, screenY, 0))

yields the same result as

Vector3 new_coord = camera.unproject(new Vector3(screenX, screenY,0));
tp.set(new_coord);

#### Version of LibGDX and/or relevant dependencies
1.9.2

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [ ] MacOS

**Comment by xoppa** [comment]
Thanks. Please send a pull request to fix the javadocs as you think is required. https://github.com/libgdx/libgdx/wiki/Contributing
