### ISSUE TITLE
Tiled Layer Offset not rendered

### ISSUE THREAD

**Issue by liorry** [libgdx/libgdx#4047]
#### Issue details

Libgdx doesn't render Tiled Layer Offset.
#### Reproduction steps/code
1. Create a map with Tiled
2. Set horizontal/vertical offset to one of the map's layers.
3. load map with TmxMapLoader().load();
4. Render map with IsometricTiledMapRenderer
5. Notice the defined offset isn't rendered.
#### Version of LibGDX and/or relevant dependencies

Libgdx version 1.9.2. Latest Tiled.
#### Affected platforms

All platforms

**Comment by MobiDevelop** [comment]
The offset feature in Tiled was added after the map api was built. It might take some time before we get to adding it, so a PR would be appreciated.

**Comment by badlogic** [comment]
Assuming no PR was issues and nobody on the core team having time for this, I'm closing this out.
