### ISSUE TITLE
Suggestion: Update from LibGDX 1.7.2 to latest stable or 1.7.3-SNAPSHOT

### ISSUE THREAD

**Issue by Lucrecious** [libgdx/libgdx#4053]
I noticed that controller connection/disconnection(on ControllerListener) was not implemented properly on the version of LibGDX that Bdx is using (1.7.2), so hotplugging isn't possible (even with polling from Controllers.getControllers()).

If there is an alternate way to achieve hotplugging, please show me. Otherwise, here's a thread with this information I mentioned:
https://www.bountysource.com/issues/3405158-detect-controller-hotplugging

Here's the Controller wiki:
https://github.com/libgdx/libgdx/wiki/Controllers

Thanks.

**Comment by xoppa** [comment]
Looks like you posted on the wrong issue tracker.
