### ISSUE TITLE
Native crash at /data/app/com.hmack.hammerize-1/lib/arm/libgdx-box2d.so

### ISSUE THREAD

**Issue by reime005** [libgdx/libgdx#4056]
After playing my game Hammerize, I got this error.

#### Issue details
Game crashed random

#### Reproduction steps/code
Random, not reproducable

#### Version of LibGDX and/or relevant dependencies
1.8.0

#### Stacktrace
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/t03gxx/t03g:4.4.2/KOT49H/N7100XXUFND3:user/release-keys'
Revision: '11'
ABI: 'arm'
pid: 6810, tid: 6895, name: GLThread 9068 >>> com.hmack.hammerize <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1001d
r0 00010001 r1 c206e72d r2 00000001 r3 00000006
r4 00010001 r5 c206e72d r6 676d7860 r7 00010001
r8 676d7860 r9 6975cb50 sl 00000000 fp 12c07880
ip 83c3580c sp 83c35798 lr 69a8e48c pc 69a8f2f8 cpsr 20000010

backtrace:
#00 pc 0001a2f8 /data/app/com.hmack.hammerize-1/lib/arm/libgdx-box2d.so (b2Fixture::DestroyProxies(b2BroadPhase*)+8)
#01 pc 00019488 /data/app/com.hmack.hammerize-1/lib/arm/libgdx-box2d.so (b2Body::SetActive(bool)+136)
#02 pc 0002d3c4 /data/app/com.hmack.hammerize-1/lib/arm/libgdx-box2d.so (Java_com_badlogic_gdx_physics_box2d_World_jniDeactivateBody+100)
#03 pc 0045f45b /data/dalvik-cache/arm/data@app@com.hmack.hammerize-1@base.apk@classes.dex

#### Please select the affected platforms
- [ x ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
