### ISSUE TITLE
BitmapFont not working with small scale on libgdx 1.7.2+

### ISSUE THREAD

**Issue by pedja1** [libgdx/libgdx#4057]
I have OrthographicCamera with viewport 16x9. Lets say for example that devices real resolution is 1024x576

```java
this.cam = new OrthographicCamera(16, 9);
```
I create BitmapFont like this:

```java
FreetypeFontLoader.FreeTypeFontLoaderParameter params = new FreetypeFontLoader.FreeTypeFontLoaderParameter();
params.fontFileName = "font.ttf";
params.fontParameters.size = 19;
```

Font size in pixels iz 19. That is calculated like this: `screenHeight(576)/cameraViewportHeight(9)*0.3`
0.3 is how big font should be in camera units

Since font is rendered on camera mentioned above, we have to scale font to our camera size:

```java
font.getData().setScale(0.015f);// 0.3/19
````

I dont know if my math is ok, but this works fine on libgdx version 1.7.1. If i update to any higher version (currently 1.9.2, but i also tried 1.7.2), font just dont display

**Comment by Darkyenus** [comment]
Make sure that the [integer rounding](https://github.com/libgdx/libgdx/blob/055b9f762e90303d3d5367b2e974bbaf595a7c64/gdx/src/com/badlogic/gdx/graphics/g2d/BitmapFont.java#L339) for the font is disabled

**Comment by pedja1** [comment]
Yep, figured it out, thanks
