### ISSUE TITLE
Old Style Builds: Nightlies & Release Builds?

### ISSUE THREAD

**Issue by noblemaster** [libgdx/libgdx#4058]
The "Old Style Builds" via https://libgdx.badlogicgames.com/download.html haven't been created in a while now. I am fine with the release-builds not being available, but now the nighlies are not updated anymore as well. Is there a way to get those back? I am aware that Gradle is the big new thing and I am partly using it for Android/iOS builds. However, it's dead slow to build besides the constant IDE freezes & the under the hood magic that make it difficult to impossible to customize.

I guess I'll build it from source myself. If I am the only one still reluctant to fully make the switch to Gradle and all the "magic" that comes with it? Anyhow, if that's the case, feel free to close this issue :)

**Comment by xoppa** [comment]
You can download the snapshots from here: https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/. Perhaps we should remove the old releases on that page and instead tell people to get it from the repo.

**Comment by Tom-Ski** [comment]
The nightlies are still built, we just havent had a build in a few days.  This means the mavenized snapshots are also not built.

As for Gradle, you don't have to build with it (you can simply use it to bring in your dependencies), or use it at all. You can get the artifacts release and snapshots from sonatype or maven central, and you can use another build tool such as maven.

I've never had such problems with performance in the IDE, even on old hardware, but it does vary from build to build.  It is definitely slower though, so for that reason I personally don't use gradle integration in the IDE itself to run, I just use it for the dependency management, and for deploying. We should official deprecate those old style builds.
