### ISSUE TITLE
Glsl is horrific !

### ISSUE THREAD

**Issue by js78** [libgdx/libgdx#4063]
#### Issue details
In the default shader, we declare directional light like that:

```
struct DirectionalLight
{
	vec3 color;
	vec3 direction;
};
uniform DirectionalLight u_dirLights[numDirectionalLights];
```

In the DefaultShader.java, we access it by `u_dirLights[0].color` .

Here the amazing compilation:
 - if `numDirectionalLights > 1` : No problem!
 - if `numDirectionalLights == 1` : Oh my g** `u_dirLights[0].color` is inexistant (location = -1).

#### WHY ??
Because if there is only one element in the array (numDirectionalLights == 1),
`uniform DirectionalLight u_dirLights[numDirectionalLights];` becomes `uniform DirectionalLight u_dirLights`. You must use `u_dirLights.color` and not `u_dirLights[0].color` to access this element.

Sadly DefaultShader doesn't handle this exception, so you can't have only one directional light.

@xoppa Have you got an idea ?

**Comment by np511** [comment]
I've never really worked with GLSL (or direct OpenGL at all, really), 
but isn't this something you can handle with macros? If 
numDirectionalLights is 1, just set the array size to 2, and ignore the 
second element.

If I'm being an idiot then just ignore me.

**Comment by xoppa** [comment]
Guess you mean `u_dirLights[1].color`. I can't remember ever having an issue with a single light and I'm pretty I accounted for that. Can you provide your sscce?

**Comment by js78** [comment]
No I really mean `u_dirLights[0].color` to get the location.
I will provide an sscce.

**Comment by js78** [comment]
I tested on another computer and I don't have the problem. Maybe a driver fault... Do you think a driver could do such black magic @xoppa ?

**Comment by xoppa** [comment]
Probably. It is very unlikely that the spec defines a different [introspection](https://www.opengl.org/wiki/Program_Introspection) based on the size of an array. It seems like the reserve is true though: "Note that the array index can be removed in these cases. Thus the query-by-name APIs will accept either anArray​ or anArray[0]​. But if you query the name, you will always get the "[0]" version." So it might be possible to always omit the `[0]`, to work around your issue. But can't say that for sure though, I haven't tested it. It also might be different for glsl es or expose other driver issues. And it sure does not make it more readable. So I'm reticent for such "fix", especially if it fixes a very scarce driver issue.

**Comment by js78** [comment]
Ok I tested again and again and indeed it a driver bug!I close this.
