### ISSUE TITLE
handle unchecked exceptions in handleHttpResponse()

### ISSUE THREAD

**Issue by TomGrill** [libgdx/libgdx#4068]
#### Issue details

If you look at this file:

https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/net/NetJavaImpl.java

On line 204 handleHttpResponse() of the given listener is called. When I override this method in my HttpResponseListener and within this method an exception is thrown some strange happens:
#### Reproduction steps/code

I made an example project:
https://github.com/TomGrill/NetJavaImplProblemExample

Whenever an exception is thrown within handleHttpResponse() and I do not catch this exception, then the exception will be caught on line 210 and on line 213 the failed() method of my listener is called AFTER handleHttpResponse() has already been called.

So my question is:

Am I supposed to handle unchecked exceptions (for checked exceptions I am of course) within handleHttpResponse() to prevent failed() beeing called? If so I think this is a design flaw since it is very easy to oversee an unchecked exception. Maybe at least put this to the description of the handleHttpResponse() method to warn users about this problem.

It took me quite a while to figure out a bug I had in my code.

Is this good and supposed to be like it is or do we need to rewrite the class above? I am happily making a PR. Just want to discuss what you think before acting.

**Comment by badlogic** [comment]
As you noticed, guarding against unchecked exceptions is essentially a lost battle. Not only in your code, but also in libGDX's code. A case can be made to let the app fail hard and not call the failure callback.
