### ISSUE TITLE
SpriteBatch#draw draws nothing and gives no error if very high rotation value is passed

### ISSUE THREAD

**Issue by prineside** [libgdx/libgdx#4081]
#### Issue details
_When very high values are passed as rotation in [SpriteBatch#draw](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/graphics/g2d/SpriteBatch.html#draw-com.badlogic.gdx.graphics.Texture-float-float-float-float-float-float-float-float-float-int-int-int-int-boolean-boolean-) (for example, 100,000,000f), nothing is drawn and no errors appear in log._

#### Reproduction steps/code
```
package com.mygdx.game;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.graphics.g2d.TextureRegion;

public class MyGdxGame extends ApplicationAdapter {
	SpriteBatch batch;
	Texture img;
	TextureRegion tr;
	
	@Override
	public void create () {
		batch = new SpriteBatch();
		img = new Texture("badlogic.jpg");
		tr = new TextureRegion(img, 128, 128);
	}

	@Override
	public void render () {
		Gdx.gl.glClearColor(1, 0, 0, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		batch.begin();
		batch.draw(tr, 0, 0, 64, 64, 128, 128, 1, 1, 100000000f);
		batch.end();
	}
}
```

#### Version of LibGDX and/or relevant dependencies
_1.9.2_

#### Please select the affected platforms
- [x] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Darkyenus** [comment]
This is because `MathUtils.sin/cos` lose precision significantly for high input values. I doubt it will be fixed, because it would incur performance penalty. It could be documented somewhere though.

**Comment by laubed** [comment]
I agree with @Darkyenus . Someone could fix that by using a modulo operation on the rotation inside that method. But modulo is based on division which is really slow on some devices (mostly mobile). Therefore you would introduce a huge performance impact on most users.
A better way would be to check your rotation variable every frame or two and subtract 360 if the value is greater than 360. Because sin/cos are periodic this is possible. Same goes with negative values.

**Comment by NathanSweet** [comment]
I think it's best if users just avoid passing such high values.
