### ISSUE TITLE
ios-moe in newest libGDX setup is incompatible

### ISSUE THREAD

**Issue by RaimundWege** [libgdx/libgdx#4082]
#### Issue details
Today i've downloaded the newest libGDX setup to get in touch with the Multi-OS Engine but now i stuck at the build process. When i run the ios-moe project without any changes i get:
`Error:Failed to resolve: com.badlogicgames.gdx:gdx-backend-moe:1.9.2`

when i change the gdx-version to: 1.9.3 i get:
`Error:Could not find com.badlogicgames.gdx:gdx-platform:1.9.3.
Searched in the following locations:
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/badlogicgames/gdx/gdx-platform/1.9.3/gdx-platform-1.9.3.pom
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/badlogicgames/gdx/gdx-platform/1.9.3/gdx-platform-1.9.3-natives-armeabi.jar
    file:/my_hidden_path/.m2/repository/com/badlogicgames/gdx/gdx-platform/1.9.3/gdx-platform-1.9.3.pom
    file:/my_hidden_path/.m2/repository/com/badlogicgames/gdx/gdx-platform/1.9.3/gdx-platform-1.9.3-natives-armeabi.jar
    https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-platform/1.9.3/gdx-platform-1.9.3.pom
    https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-platform/1.9.3/gdx-platform-1.9.3-natives-armeabi.jar
    https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/gdx/gdx-platform/1.9.3/gdx-platform-1.9.3.pom
    https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/gdx/gdx-platform/1.9.3/gdx-platform-1.9.3-natives-armeabi.jar
    https://oss.sonatype.org/content/repositories/releases/com/badlogicgames/gdx/gdx-platform/1.9.3/gdx-platform-1.9.3.pom
    https://oss.sonatype.org/content/repositories/releases/com/badlogicgames/gdx/gdx-platform/1.9.3/gdx-platform-1.9.3-natives-armeabi.jar
Required by:
    ce3d:android:1.0`

and when i change the gdx-version to: 1.9.3-SNAPSHOT i get:
`/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/java -Didea.launcher.port=7532 "-Didea.launcher.bin.path=/Applications/Android Studio.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/lib/tools.jar:/my_hidden_path/libGDX/ce3d/ios-moe/build/classes/main:/my_hidden_path/libGDX/ce3d/core/build/classes/main:/Applications/Android Studio.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain de.i2e.ce3d.IOSMoeLauncher
Exception in thread "main" java.lang.NoClassDefFoundError: com/badlogic/gdx/backends/iosmoe/IOSApplication$Delegate
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:260)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:122)
Caused by: java.lang.ClassNotFoundException: com.badlogic.gdx.backends.iosmoe.IOSApplication$Delegate
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more`

and in Xcode:
`ld: warning: directory not found for option '-L../build/libs/static'
ld: warning: directory not found for option '-L../build/libs/static/iphonesimulator'
ld: warning: directory not found for option '-F../build/libs/static'
ld: warning: directory not found for option '-F../build/libs/static/iphonesimulator'
ld: warning: directory not found for option '-F../build/libs/dynamic'
ld: warning: directory not found for option '-F../build/libs/dynamic/iphonesimulator'
ld: file not found: /my_hidden_path/libGDX/ce3d/ios-moe/xcode/native/ios/libObjectAL.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

#### Reproduction steps/code
Try to start an iOS build with the newest gdxSetup.jar and Multi-OS Engine.

#### Version of LibGDX and/or relevant dependencies
libGDX 1.9.2, 1.9.3, 1.9.3-SNAPSHOT

#### Affected platforms
- [ ] Android
- [X] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
You to run at least once in IDEA or AS before you run in xcode.

----- Reply message -----

**Comment by RaimundWege** [comment]
I've tried to run the project in Android Studio before but i've got the error:
`Error:Failed to resolve: com.badlogicgames.gdx:gdx-backend-moe:1.9.2`
Than i've changed the gdx-version to 1.9.3 and i've got the error:
`Error:Could not find com.badlogicgames.gdx:gdx-platform:1.9.3.`
So at least i've tried gdx-verion 1.9.3-SNAPSHOT and i've got:
`Exception in thread "main" java.lang.UnsatisfiedLinkError: com.intel.moe.natj.general.NatJ.initialize()V
	at com.intel.moe.natj.general.NatJ.initialize(Native Method)
	at com.intel.moe.natj.general.NatJ.init(NatJ.java:189)
	at com.intel.moe.natj.general.NatJ.register(NatJ.java:239)
	at ios.NSObject.<clinit>(NSObject.java:70)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:260)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:122)
Exception in thread "Thread-0" java.lang.UnsatisfiedLinkError: com.intel.moe.natj.general.NatJ.handleShutdown()V
	at com.intel.moe.natj.general.NatJ.handleShutdown(Native Method)
	at com.intel.moe.natj.general.NatJ.access$000(NatJ.java:39)
	at com.intel.moe.natj.general.NatJ$2.run(NatJ.java:154)`

**Comment by Tom-Ski** [comment]
Sounds like you haven't setup your environment correctly.  What version of MOE have you installed, what run configuration are you trying to run?

**Comment by RaimundWege** [comment]
The run configuration it was! I've just added a new one for "Multi-OS Engine iOS Application" and the project starts in the iOS Simulator.

But at least i had to change the gdx-version to 1.9.3-SNAPSHOT in the build script.
Thank you for your support!
