### ISSUE TITLE
Assetmanager not loading files that load perfectly with standard FileHandles

### ISSUE THREAD

**Issue by bertvanovermeir** [libgdx/libgdx#4083]
There seems to be an issue with the AssetManager when loading a particleeffect file on Android, probably to do with Android studio:

`ParticleEffectLoader.ParticleEffectLoadParameter loadParam = new ParticleEffectLoader.ParticleEffectLoadParameter(particleSystem.getBatches());
            ParticleEffectLoader loader = new ParticleEffectLoader(new InternalFileHandleResolver());
            Assets.instance.assetManager.setLoader(ParticleEffect.class, loader);
            Assets.instance.assetManager.load("bb.pfx", ParticleEffect.class, loadParam);
            Assets.instance.assetManager.finishLoading();
effect1=Assets.instance.assetManager.get("bb.pfx",ParticleEffect.class).copy();`

Will result in an Asset Not Loaded Exception only on Android.
I can check AND read the file because:

`FileHandle file = Gdx.files.internal("bb.pfx");
            String text = file.readString();`

Results in a String with the file contents.

#### Reproduction steps/code
Create a new project and use a particleEffect to load with the assetmanager

#### Version of LibGDX and/or relevant dependencies
I am using the latest version of libgdx from the gradle setup.

#### Stacktrace
`FATAL EXCEPTION: GLThread 165
                                                                      Process: bvo.games.colorspace, PID: 13910
                                                                      com.badlogic.gdx.utils.GdxRuntimeException: Asset not loaded: bb.pfx
                                                                          at com.badlogic.gdx.assets.AssetManager.get(AssetManager.java:144)
                                                                          at bvo.games.colorspace.settings.Assets$AssetBillboard.<init>(Assets.java:115)`

#### affected platforms
- [x ] Android

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
