### ISSUE TITLE
Using BoxShapeBuilder with BoundingBox yields box with vertices at model center

### ISSUE THREAD

**Issue by sodacode** [libgdx/libgdx#4085]
#### Issue details
`BoxShapeBuilder.build(meshPartBuilder, boundingBoxInstance)` creates a box with some vertices at the center of the model.

#### Reproduction steps/code
Reproduction code at https://github.com/sodacode/mesh-error
This code renders this screen:
![Weird mesh](https://coda-files.s3.amazonaws.com/MeshError_2016-05-16_11-37-22.png)

The blue box was created with `modelBuilder.createBox(...` while the red box was created with `BoxShapeBuilder.build(...`.
#### Version of LibGDX and/or relevant dependencies
1.9.3
#### Stacktrace
No stacktrace available...

#### Please select the affected platforms
- [x] Android
- [x] iOS
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by xoppa** [comment]
Thanks for reporting
