### ISSUE TITLE
onPause() not called on android 6.0.1 Nexus 5

### ISSUE THREAD

**Issue by Hotshot5000** [libgdx/libgdx#4088]
Please ensure you have given all the following requested information in your report.
#### Issue details

On libgdx 1.9.1 (haven't tested on other versions) it seems that AndroidGraphics.pause() kills the running process because pause doesn't get set to false by onDrawFrame() and it timeouts.

Normally, from what I have seen when running an emulator, clicking the HOME button when in a libgdx application calls AndroidApplication.onPause() and AFTER that it kills the render surface. But on a Nexus 5 with latest updates (android 6.0.1 marshmallow), onPause() is called after onDrawFrame() stops being called, meaning that pause = false never gets called, so after a timeout of 4000 ms the process gets killed.
#### Reproduction steps/code

Put a breakpoint in AndroidApplication.onPause() and check if onDrawFrame() still called after the breakpoint hits. On nexus 5 android 6.0.1 you will notice that the rendersurface is destroyed before onPause() gets called, while in the emulator it's the other way around. This bug could happen on other devices as well but I only have a nexus 5 at hand right now.
#### Version of LibGDX and/or relevant dependencies

1.9.1 possibly on other versions
#### Please select the affected platforms
- [x ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by intrigus** [comment]
Please create an http://sscce.org

**Comment by MobiDevelop** [comment]
I haven't found this to be the case on my Nexus 5 running Android 6.0.1.

**Comment by Hotshot5000** [comment]
It doesn't happen every time. I can't lock in to why it happens when it happens. I will test some more and come back later when I'll find a pattern.

**Comment by badlogic** [comment]
Can't reproduce on Nexus 6P running 6

**Comment by gfphoenix** [comment]
This happens in xiaomi MIX2 with android 8.0.0 when you lock and unlock the screen. Hotshot5000 is right that GL thread doesn't run onDrawFrame before paused.
