### ISSUE TITLE
Gwt SuperDev mode: file doesn't exist

### ISSUE THREAD

**Issue by St1nger13** [libgdx/libgdx#4090]
App works well while launching desktop project. When I am trying to launch html project, I get the next error:
**GwtApplication: exception: Error reading file: skin/uiskin.json
skin/uiskin.json does not exist**
![image](https://cloud.githubusercontent.com/assets/15645701/15367747/12512490-1d33-11e6-904a-675e9af9db45.png)

#### Issue details
So I have the next structure in the core/assets folder:
![image](https://cloud.githubusercontent.com/assets/15645701/15367719/f4b27010-1d32-11e6-9fab-4379a9f6d164.png)

I am trying to read uiskin.json file like above:
`Skin skin = new Skin(Gdx.files.internal("skin/uiskin.json")) ;`

#### Version of LibGDX and/or relevant dependencies
LibGdx version: Last (downloaded yesterday)

#### Please select the affected platforms
- [x] HTML/GWT
- [x] Windows

**Comment by MobiDevelop** [comment]
Try to open that file directly in the browser, look at developer tools in your browser to see what is going on.

https://github.com/libgdx/libgdx/wiki/More-Info
