### ISSUE TITLE
Enable/Disable drag and drop? 

### ISSUE THREAD

**Issue by nrallakis** [libgdx/libgdx#4092]
How can I enable or disable a DragAndDrop object?
In my case I have a card hand and I want to enable or disable the ability to drag and drop cards whenever I want.

**Comment by Frotty** [comment]
:+1:

**Comment by carlislefox** [comment]
:+1:

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
