### ISSUE TITLE
'Gradle: Execution failed for task' when using BaseGameUtils from Google

### ISSUE THREAD

**Issue by DanHale123** [libgdx/libgdx#4094]
#### Issue details
When trying to run a libgdx project made with the new version of libgdx and new gdx-setup with the BaseGameUtils from the android basic samples added the compilation fails with the following error:

```
Error:Gradle: Execution failed for task ':BaseGameUtils:extractReleaseAnnotations'.
> originalComplianceLevel
```

#### Reproduction steps/code
1. Create a new LibGDX project in gdx setup.
2. Add in BaseGameUtils following the steps in the 'Intellij setup' section of https://github.com/libgdx/libgdx/wiki/Google-Play-Game-Services-in-LibGDX
3. Run the default android run configuration created by the setup

#### Version of LibGDX and/or relevant dependencies
gdxVersion = '1.9.3'
roboVMVersion = '2.1.0'
com.mobidevelop.robovm:robovm-gradle-plugin:2.1.0 (Maybe this is relevant)

#### Stacktrace
```java
I doesn't give a stacktrace and I'm not sure how to make it give one, sorry.
```

#### Please select the affected platforms
- [X] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
This has been resolved https://github.com/libgdx/libgdx/issues/4091

You'll have to use 2.2.0-SNAPSHOT for robovm for now if you want the fix.

**Comment by DanHale123** [comment]
Thanks
