### ISSUE TITLE
Make HttpResponseListener usable by multiple requests by including the HttpRequest in the parameters of each method

### ISSUE THREAD

**Issue by ClaudiuBele** [libgdx/libgdx#4095]
Out of the box there is no way of using HttpResponseListener on multiple different requests. HandleHttpResponse does work if the server code you are running gives back information on what action has been performed by the client, but with `failed(Throwable)` or `cancelled()` there is no way of knowing which request made with the same HttpResponseListener has failed or has been cancelled. 

I think that overall it would be very usefull if the HttpRequest would be passed in each method of the HttpResponseListener ( similar to how Android handles listeners e.g. OnClickListener which passes the view that was clicked as a parameters) , HttpResponseListener having these method headers afterwards:

```
void handleHttpResponse(HttpRequest, HttpResponse);
void failed(HttpRequest, Throwable);
void cancelled(HttpRequest);

```

**Comment by badlogic** [comment]
I like this suggestion. If you can send a PR for it I'll happily merge it.
