### ISSUE TITLE
Music.setOnCompletionListener along with looping

### ISSUE THREAD

**Issue by PojahnM** [libgdx/libgdx#4101]
I am developing a game with LibGDX for desktop, currently testing on Windows 10.

I noticed that a musics completion listener won't be executed if looping is set to true.
This behaviour have some drawbacks. 

For example, most game music consist of an intro, a starting point for looping and obviously an end. When a music ends, we set the position to the looping point in the completion listener and starts playing it again. 
This is nice because we only  want to hear the intro the first time.

Since the music is in a stopped state in the listener, we will get a short pause each time the music loops, making it sound laggy. Some songs are from the starting point to the end just 30 seconds, giving us a "pause" ever half minute.

In TinySound for example, the completion listener is executed even if looping is set to true. So we simply set the position there and the results are smooth and nice.

Can we get something similar in LibGDX?

**Comment by np511** [comment]
You could create a separate music file, for instance mymusic-intro.mp3, load both mymusic.mp3 and mymusic-intro.mp3, set mymusic-intro to play (not loop) and have mymusic-intro's completion listener start the looping of mymusic.

**Comment by PojahnM** [comment]
Sound kinda painful and demorsalizing. Besides, we would still have a pause in the transition between the intro and loop music. So you are just replacing one bigger problem with a smaller one.

**Comment by np511** [comment]
I don't mean to do that as a permanent solution, but you can use it for 
now while you wait.

Alternately, don't loop the music at all: just set it to play once and 
have the completion listener set the position to after the intro every 
time it finishes - this plays the intro once, only needs the one music 
file, and shouldn't have a pause.

**Comment by PojahnM** [comment]
Sorry for not following but what am I waiting for? 

As for the alternative, that's exactly what I am doing, and it have a pause, because whenever the completion listener is executed, the music is in a paused state, which results in a little pause. 

music.setVolume(volume);
music.play();
 music.setOnCompletionListener(music1 -> {
     music1.play();
      music1.setPosition(seconds);
});

**Comment by np511** [comment]
I meant while you wait for a loop completion listener.

Rather than having the listener apply to the end of a loop as well, do 
you think it would be a good idea to have a "setLoopBounds" method? Like 
when listening to music with the VLC player, you can use A-B looping - 
why not have that instead? When the specified B position is reached, it 
should automatically go to the A position?

**Comment by np511** [comment]
I just looked through the source, this would require modifying the 
back-ends - I've never worked with OpenAL, so I am not going to even try 
to do anything about this.

**Comment by Tom-Ski** [comment]
I think that having a completion listener respond to a looping instance 'ending' is a nice feature, perhaps with a loop count too.  However it seems that you want it to hack around a problem with looping audio having some sort of delay when it loops? If that is the case it should be fixed at the source and not with this.

**Comment by np511** [comment]
Is the delay in the music file? If so, you can use a mp3 cutter to 
remove it, otherwise, I really don't see the problem with two separate 
files. A separate file with -intro appended before the file extension 
seems easy enough to me.

**Comment by PojahnM** [comment]
Thanks for at least looking into this. 

setLoopBounds would indeed be a nice feature, making things even easier than a completion listener.  TinySound have for example Music.setLoopPositionBySeconds(double).

There is no delay in the music file, the outro is cut. So point A(looping point) to B(end point) contains no pauses. If you for example in an audio editor append sound starting from point A and a few seconds forward, the results will be smooth and natural. Sounds like the music is just continuing. 

Making the sound continuing "forever" **smoothly** in LibGDX is my goal. 

Tom-Ski: Not sure I understood your question, but I am not trying to achieve any sort of hack.
A short summary of what I would love to see in LibGDX: Trigger completion listener for looping instances.

**Comment by np511** [comment]
Some people might not want the completion listener to trigger when 
looping - maybe have a method to set whether the loop triggers the listener?

Although having two files might be a better solution anyway. If looping 
triggered the listener, it might start playing from the beginning for a 
fraction of a second (longer on older devices) before the listener 
caused the seek to after the intro.

**Comment by PojahnM** [comment]
Line 230 in OpenALMusic looks interesting. It seems to call stop when the music have ended and then calls the completion listener. When I get home, I'ill try to replace the stop part with setPosition and see if it works and is smooth.

**Comment by Tom-Ski** [comment]
I'm still not sure what it is exactly yu

**Comment by PojahnM** [comment]
Having two songs will probably work fine, just like you say. But wouldn't be **easier** if it was just _one_ file? Wouldn't it be more **consistent** to have _one_ Music instance represent _one_ song? 

Having two music instances represent one song adds lot's of complexity when dynamically switching between songs(such as when you enter a different room).

Also, doesn't re-saving a lossy music file further degrade the quality? 

I haven't actually tried the change in OpenALMusic yet, because my projects have some other bugs. But I could try it tomorrow.

**Comment by np511** [comment]
I don't think it lowers the quality - if you re-save a 128kbit/s mp3 
file, it will be the same quality - 128kb/s. If you compress it to 
108kb/s, then it would lose quality. Just cutting it won't affect 
quality. Though as I found out the hard way, volume boosting does. It 
also caused my ears to lose quality...

I personally don't see the big deal with having two files.

Does GDX currently have a way to cut music files?

**Comment by PojahnM** [comment]
Well... 

I haven't tried the line change at line 230 in OpenALMusic, because I wasn't able to compile the backend project(dependency hell). 
Anyway, I noticed that some songs take longer to play than others, so this issue is not always present. I haven't compared the songs that have longer play startup with the shorter ones.

I can live with the current situation. Still think there should be an easy way to set a looping point though. So if there are no plans to implement a looping point feature, this ticket should be closed.

**Comment by np511** [comment]
I agree that there should be an easier way to do this, but as I 
mentioned before I've never worked with OpenAL (or OpenGL) directly, and 
I don't really want to waste time on this - I have a lot of work I want 
to do over the summer, mainly on finishing up projects I meant to finish 
half a year ago.

**Comment by PojahnM** [comment]
Cheers to that! :) 

No stress, maybe one day in the future. ^^

**Comment by badlogic** [comment]
Looping points would be doable on the desktop, but not on mobile I'm afraid :/
