### ISSUE TITLE
Current display mode HZ/freq is not posible to read

### ISSUE THREAD

**Issue by IonAgorria** [libgdx/libgdx#4109]
#### Issue details

The display mode that reports LWJGL2 backend is only the initial mode, which normally results in the highest display frequency even when display mode is changed with lower frequency.

Possible solution was provided in #3903 but caused #3997, probably due to attempting to get display mode in window mode (not confirmed) probably due to window not having own hz/bpp parameters as its not a "monitor display mode" per se

Maybe an alternate solution would be to provide a dedicated getHZ/getBPP or similar mechanism to workaround the limitation.
#### Reproduction steps/code
- Set fullscreen display mode with lower display hz than maximum supported by monitor
- Read the current display mode
#### Version of LibGDX and/or relevant dependencies
- 1.9.2
- 1.9.3
#### Please select the affected platforms
- [?] Android
- [?] iOS
- [?] HTML/GWT
- [X] Windows
- [X] Linux
- [?] MacOS

**Comment by badlogic** [comment]
LWJGL2 is pretty much a lost cause at this point. We could try working around issues like this, but I feel the focus should be on LWJGL3 instead. I'm happy to merge any PR that fixes this.
