### ISSUE TITLE
Lwjgl3Application desktop window disappears on resize

### ISSUE THREAD

**Issue by DanilaFe** [libgdx/libgdx#4110]
I understand that Lwjgl3 is a new and unstable back-end, but If this is an actual, non-local issue, reporting this might be helpful.

#### Issue details
Using the Lwjgl3 backend on OS X El Capitain, the resulting window cannot be resized. When attempt to resize it is made, the window either disappears or quickly shrinks to what I assume is a 1x1 rectangle. The game continues to run, but no interaction seems to be possible.

#### Reproduction steps/code
The steps I took:

1. Create new LibGDX application from the latest setup app
2. Change backend to lwjgl3 from lwjgl
3. Update the desktop launcher class accordingly
4. Run the application and attempt to resize the window

#### Version of LibGDX and/or relevant dependencies
The man build.gradle file lists the following versions:
``` 
gdxVersion = '1.9.3'
roboVMVersion = '2.1.0'
box2DLightsVersion = '1.4'
ashleyVersion = '1.7.0'
aiVersion = '1.8.0'
```

#### Stacktrace
N/A

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS

#### Video
[Issue Video](http://puu.sh/p9uB5/bc710cd42d.mp4)

**Comment by intrigus** [comment]
It would be nice if you could create a sscce.org .

**Comment by DanilaFe** [comment]
I'm not sure how I'd do that - should I provide an entire basic application?

**Comment by Tom-Ski** [comment]
A simple ApplicationAdapter will do.  See https://github.com/libgdx/libgdx/wiki/Getting-help for examples.

**Comment by code-disaster** [comment]
Can not reproduce on a MacBook Pro, OS X 10.11.5, latest libGDX snapshot.

**Comment by DanilaFe** [comment]
Can confirm that this issue is not present in 1.9.4-SNAPSHOT, though it still appears in 1.9.3
I guess that this issue is closed since it is fixed in the snapshots.
