### ISSUE TITLE
Strange behavior with touchDragged

### ISSUE THREAD

**Issue by breakmt** [libgdx/libgdx#4112]
#### Issue details
I'm trying to impement dragging for actor, but I see strange effect - when I try to drag actor it starts blinking and change positions randomly. Here is a short video: https://youtu.be/KpGujQ7KHc0

#### Reproduction steps/code
Actor:
```
public class Item extends Actor {
    private String id;
    private TextureRegion texture;

    public Item() {
        this.id = "passport";

        texture = PicturesData.getPicture(getId());
        setSize(texture.getRegionWidth(), texture.getRegionHeight());

        addListener(new DragListener() {
            @Override
            public boolean touchDown(InputEvent event, float x, float y, int pointer, int button) {
                return true;
            }

            @Override
            public void touchDragged(InputEvent event, float x, float y, int pointer) {
                Log.add("Dragged: " + x + ", " + y);
                setPosition(x, y);
            }
        });
    }

    public String getId() {
        return id;
    }

    @Override
    public void draw(Batch batch, float parentAlpha) {
        batch.draw(texture, getX(), getY());
    }
}
```
The screen is basic too:
```
public class GameScreen implements Screen {
    private Stage stage;

    public GameScreen() {
        stage = new Stage(new StretchViewport(800, 600));
        Gdx.input.setInputProcessor(stage);

        Item item = new Item();

        stage.addActor(item);
    }

    @Override
    public void show() {
    }

    @Override
    public void render(float delta) {
        Gdx.gl.glClearColor(0, 0, 0, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT | GL20.GL_DEPTH_BUFFER_BIT);

        stage.act(delta);
        stage.draw();
    }

    @Override
    public void resize(int width, int height) {

    }

    @Override
    public void pause() {

    }

    @Override
    public void resume() {

    }

    @Override
    public void hide() {

    }

    @Override
    public void dispose() {

    }
}
```
#### Version of LibGDX and/or relevant dependencies
1.9.3, 1.9.1

#### Please select the affected platforms
- [x] Android
- [x] Windows

**Comment by breakmt** [comment]
Problem is solved!
Instead of setPosition I should you use moveBy method.
               
```
    @Override
    public void touchDragged(InputEvent event, float x, float y, int pointer) {
        moveBy(x - getWidth()/2, y - getHeight()/
    }
```
I think in javadoc should be information that X and Y in touchDragged are not new position, but delta with previous position!

**Comment by dotw** [comment]
@breakmt Hi, I encounter the same problem. I have a big map and user can drag it to view part of it. The issue is I have already using the delta, why it still has blinking and random positions?

map.addListener(new InputListener() {
            @Override
            public boolean touchDown(InputEvent event, float x, float y, int pointer, int button) {
                start.set(x, y, 0);
                return true;
            }

            @Override
            public void touchUp(InputEvent event, float x, float y, int pointer, int button) {
                //
                map.dynamicLoadMaps(camera.position.x, camera.position.y);
            }

            @Override
            public void touchDragged(InputEvent event, float x, float y, int pointer) {
                end.set(x, y, 0);
                dragMap((start.x - end.x), (start.y - end.y));
                start.set(x, y, 0);
            }
        });

**Comment by dotw** [comment]
here is the dragMap method

 private synchronized void dragMap(float deltaX, float deltaY) {
        //
        camera.translate(deltaX, deltaY, 0);
 }

**Comment by dotw** [comment]
for those still struggling with this.  the blinking is go away when using the code below.
`
            public void touchDragged(InputEvent event, float x, float y, int pointer) {
                dragMap(-Gdx.input.getDeltaX(), Gdx.input.getDeltaY());
            }
`
