### ISSUE TITLE
Multi touch problem for actors on stage in iOS version.

### ISSUE THREAD

**Issue by majiddaeinejad** [libgdx/libgdx#4113]
My problem is multi touch in actors of stage that occured in iOS version. You can see my question in stackoverflow site:
[http://stackoverflow.com/questions/37525648/frozen-touchpad-when-im-using-more-than-one-actor-with-touchpad-in-stage](url)

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
