### ISSUE TITLE
GLversion instance not available at ApplicationListener::create time on iosrobovm backend

### ISSUE THREAD

**Issue by manuelbua** [libgdx/libgdx#4116]
This is due to the `GLVersion` instance being created later on, after `app.listener.create();` is called in [IOSGraphics.java](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSGraphics.java#L310).

I'm not sure if the `GLVersion` instance should or shouldn't be available at `create()` time, but it looks like to be the right place to log one-off GL information at startup time: the Android and desktop backends behave the same and i can safely use the instance there.
 

#### Please select the affected platforms
- [ ] Android
- [X] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
Yes it should, thanks for the issue.
