### ISSUE TITLE
Softkeyboard doesn't show up on GWT when using from a phone.

### ISSUE THREAD

**Issue by intrigus** [libgdx/libgdx#4117]
#### Issue details

`Gdx.input.setOnscreenKeyboardVisible(true);` doesn't work on GWT when using from a phone.
#### Reproduction steps/code

Will add repro later.
#### Version of LibGDX and/or relevant dependencies

1.9.3 or latest
#### Please select the affected platforms
- [x] HTML/GWT
- [x] Mobile
#### Possible Fix

It should be possible to add a fake `<input type="text>` and focus it.
This should bring up the keyboard on most platforms.

First reported here http://www.badlogicgames.com/forum/viewtopic.php?f=12&t=18011

**Comment by julienvillegas** [comment]
Also reported here: http://stackoverflow.com/questions/37565369/libgdx-softkeyboard-on-gwt-module

**Comment by raver1975** [comment]
So the above possible fix doesn't work, because once the <input> has focus, the keyboard events don't go to the libgdx app anymore. Anyone know how to put the focus back on the libgdx app?

**Comment by juckele** [comment]
I've also run into this. Clicking on a TextInput in the html rendered webpage on a mobile device doesn't bring up the keyboard, and there doesn't seem to be a way to bring it up.

**Comment by julienvillegas** [comment]
I have been looking for solutions to this issue for a few days. In the end the simplest approach was to show a clickable image of a mobile keyboard detecting which part of the image was clicked. It worked well.

**Comment by doit-ceo** [comment]
Did any one managed to fix this ?

**Comment by julienvillegas** [comment]
Yes, by implementing a soft keyboard (a clickable image) specifically for HTML implementation.

**Comment by raver1975** [comment]
We solved this by using JSNI to have Libgdx call a javascript function that pops up the keyboard on mobile devices.

**Comment by julienvillegas** [comment]
You can see my implementation of the softkeyboard here by the way: 
http://wordfiesta.com/web/index.html?gridID=5206673425694720

**Comment by doit-ceo** [comment]
Thanks everyone, I managed to popup  open the keyboard using JS (set focus), I created custom a OnscreenKeyboard  , now the input is the problem, it's buggy in iOS and it doesn't work at all in Android ! the only thing working in Android is the backspace button!

@raver1975 could you please share your solution and confirm that the text input works ?

**Comment by badlogic** [comment]
Our focus for the HTML backend is definitely not mobile, for which native Android and iOS backends are available. I'll be happy to merge and PR that fixes this issue, but nobody on the core team will fix this.

**Comment by doit-ceo** [comment]
I really hope libGDX change direction regarding mobile, WebGL is very mature nowadays, please look at http://venturebeat.com/2016/11/28/html5-is-the-next-100-billion-game-platform/ and try the game (not ours). We have the below site with spine, shader and actions and running 55-60 fps. 

We took different direction regarding editing (Overlay Native Editing) and we solved almost all problems regarding keyboard, please try http://demo.doit.com.sa this basically adding HTML input on-top of LibGDX after edited we setText(...), this way we avoid predictive keyboard problems (compositionstart compositionupdate compositionend) and also access different type of keyboards (i.e. tel, text, email, etc. ). 

Please scroll to the bottom of the site (http://demo.doit.com.sa) 

Regarding this issue the correct and cross platform way to open the keyboard is to issue "focus()" on native html input(text), we set this to absolute and top:-1000px , also important to note that iOS (8.0+) will only open keyboard if executed from within user action and for that you need to run this from "touchDown" in libGDX (very important).

**Comment by badlogic** [comment]
No, we will not change direction on this. If you target mobile, please go
native. Targeting mobile browsers, especially Safari with it's piss poor
WebGL support, would be like porting libGDX to another 12 platforms.

**Comment by Emperorlou** [comment]
@doit-ceo if you created a modular solution to this problem, would you mind sharing the code somewhere so we can contribute and use it?
