### ISSUE TITLE
[FR] Add 2 GLFW keycodes for better non-US keyboard support

### ISSUE THREAD

**Issue by Fringale** [libgdx/libgdx#4119]
#### Issue details

On desktop, when using a keyboard that has more character keys than the US one, the keyDown() callback gives a keycode of 0 (UNKNOWN) for those few additional keys. A workaround to use them still would be to check keyTyped() in conjunction, but this is not ideal.

In my case, on an AZERTY (French) Macbook Pro (see layout [here](https://images-na.ssl-images-amazon.com/images/I/71AzlASSbTL._SL1500_.jpg), it has one extra character key compared to an US keyboard), the top-left _#@_ key gets the UNKNOWN keycode treatment (GRAVE being the bottom left _<>_). Other reports of this behavior may include this [old issue](https://github.com/libgdx/libgdx/issues/2263#issuecomment-53264980), and this recent [forum post](http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=22724).

Under the hood, for my _#@_ example, the LWJGL 2 and 3 backends each actually report a specific keycode,  but those keycodes get map to UNKNOWN in LwjglInput / Lwjgl3Input as they have no equivalent in Input.Keys:
- LWJGL3 gives [GLFW_KEY_WORLD_1](http://www.glfw.org/docs/latest/group__keys.html) for this _#@_ key,
- while LWJGL2 returns a quite unrelated [KEY_SECTION](http://legacy.lwjgl.org/javadoc/constant-values.html#org.lwjgl.input.Keyboard.KEY_SECTION) (for a hypothetical _§_ key I suppose).

I don’t think the LWJGL2 case is worth taking a look at, as the backend will be phased out, plus a solution could prove ugly to implement if there’s a wide list of possible additional keycodes.

However, regarding the LWJGL3 backend, GLFW seems to provide just two keycodes specifically for this use case (GLFW_KEY_WORLD_1 and GLFW_KEY_WORLD_2). **As such, could two equivalent keycodes be added in Input.Keys and mapped adequately in the LWJGL3 backend?**
#### Reproduction steps/code
- Have a non-US keyboard with additional character keys
- Find the key(s) returning 0 with this code and some key mashing : )

```
package com.mygdx.game;

import com.badlogic.gdx.*;

public class MyGdxGame extends InputAdapter implements ApplicationListener {

    @Override
    public void create () {
        Gdx.input.setInputProcessor(this);
    }

    @Override
    public void render () {
    }

    @Override
    public void resize(int width, int height) {
    }

    @Override
    public void pause() {
    }

    @Override
    public void resume() {
    }

    @Override
    public void dispose() {
    }

    @Override
    public boolean keyDown(int keycode) {
        System.out.println(keycode);
        return true;
    }
}
```
#### Version of LibGDX and/or relevant dependencies

1.9.3
#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X] Windows
- [X] Linux
- [x] MacOS

_(I only did test on OS X, though)_

**Comment by RoyBeer** [comment]
This is also an issue on Windows and Ubuntu 16.04 with a German QWERTY Keyboard.

**Comment by NathanSweet** [comment]
Your best bet would be to submit a PR or otherwise suggest a fix, as not all dev team members have keyboards that can reproduce this problem.

**Comment by Fringale** [comment]
@NathanSweet Thanks for the answer, I’ll dig further and see about submitting a PR.

**Comment by badlogic** [comment]
Will process PR, closing this out.
