### ISSUE TITLE
GlyphLayout ignores BitmapFontData.lineHeight when drawing multiline text

### ISSUE THREAD

**Issue by TheMorfeus** [libgdx/libgdx#4120]
#### Issue details

When trying to render multilined GlyphLayout, I had noticed that lines are spaced too far apart. When trying to adjust that by setting BitmapFontData.lineHeight (as it is used in calculating GlyphLayout.height, i had assumed that as a way of adjustment), I noticed that there is no change to how the font is rendered, even if i set BitmapFontData.lineHeight to zero.

#### Reproduction steps
Create a GlyphLayout with multilined text, then change BitmapFontData.lineHeight of its font to zero, with no effect.

#### Version of LibGDX and/or relevant dependencies

LibGDX 1.9.3

#### Stacktrace
N/A

#### Affected platforms
Tested on windows, presumed to be a problem on all platforms.

#### Note
I am using Freetype to generate fonts. 
A workaround is to change FreeTypeFontParameter.spaceY to negative to fix the line spacing

**Comment by NathanSweet** [comment]
You are changing the line height after GlyphLayout has computed all the glyph positions? That won't change them of course. No SSCCE? https://github.com/libgdx/libgdx/wiki/More-Info
