### ISSUE TITLE
Audio doesn't work [LWJGL3]

### ISSUE THREAD

**Issue by intrigus** [libgdx/libgdx#4123]
#### Issue details
Audio doesn't work in the LWJGL3 backend.
This has been caused by #4104 .
First reported [here](http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=22754).

#### Version of LibGDX and/or relevant dependencies
1.9.4-SNAPSHOT LWJGL3

#### Stacktrace
```java
Lwjgl3Application: Couldn't initialize audio, disabling audio
java.lang.IllegalStateException: No ALCapabilities instance set for the current thread or process. Possible solutions:
   a) Call AL.createCapabilities() after making a context current.
   b) Call AL.setCurrentProcess() or AL.setCurrentThread() if an ALCapabilities instance already exists.
   at org.lwjgl.openal.AL.getCapabilities(AL.java:135)
   at org.lwjgl.openal.AL10.nalGenSources(AL10.java:669)
   at org.lwjgl.openal.AL10.alGenSources(AL10.java:687)
   at com.badlogic.gdx.backends.lwjgl3.audio.OpenALAudio.<init>(OpenALAudio.java:108)
   at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:82)   
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by intrigus** [comment]
Your error seems to be caused by LWGJL3 and not by libGDX.
You could try https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/test/java/org/lwjgl/demo/openal/ALCDemo.java and see if it works. If I doesn't file an issue for LWJGL.

**Comment by Tom-Ski** [comment]
Thanks!
