### ISSUE TITLE
Android OnScreenKeyboard distorted when using immersive mode

### ISSUE THREAD

**Issue by hasuo** [libgdx/libgdx#4125]
When enabling immersive mode the keyboard is streched. Its width is larger then the screen. Also it's height shrinks. Happens with the google keyboard, but also with all the others I've tested.
I would provide a screenshot, but its actually correct on all the screenshots I've made. 
(Very strange bug)

Please note, that the keyboard is only drawn wrong. Touch input is actually where it should be. 

I have done all my tests to fix this on a Nexus 7 (2012) with kitKat (android-19) but the same issue was reported by all my test-Users (~10 different devices)

Example here: 
https://github.com/hasuo/OSKBug-Example/
I've tested a lot of things to fix this, but no change. 

I've used libgdx 1.9.3, details are in the graddle files. No exceptions were logged.

I have only tested Android. 

As a work around I will try to switch immersive mode on/off whenever the keyboard is shown/not shown, but I would be very grateful for any pointers how to prevent this bug from happening.

**Comment by MobiDevelop** [comment]
We have no control over the keyboard, not sure there is anything that can be done on the libgdx side.
