### ISSUE TITLE
Ignored second call of ColorAction in SequenceAction

### ISSUE THREAD

**Issue by milanbalaz** [libgdx/libgdx#4126]
Please ensure you have given all the following requested information in your report.

#### Issue details
ColorAction is ignored if one instance is used multiple times in SequenceAction

#### Reproduction steps/code

In some Class extends Actor
...
private void startBlinking()
{
	Action blink = Actions.color(Colors.TEXT_INFO_BLINK);
	Action toNormalFast = Actions.color(Colors.TEXT_INFO_NORMAL, 0.3f);
	Action toNormalSlow = Actions.color(Colors.TEXT_INFO_NORMAL, 1.5f);
	Action pause = Actions.delay(4.5f);
	Action seq = Actions.sequence(pause,blink,toNormalFast,blink,toNormalSlow);
	addAction(Actions.forever(seq));
}
...
The second call of "blink" is not performed.

#### Version of LibGDX and/or relevant dependencies
1.9.3

#### Please select the affected platforms
- [ ] Android
Maybe others too...

**Comment by MobiDevelop** [comment]
Using the same action instance without resetting it will do that.

**Comment by cypherdare** [comment]
I don't know how often people run into this issue, but it might be nice to provide an easy way to work around it:

```
//RestartAction extends DelegateAction:

protected boolean delegate(float delta){ 
    if (!restarted) {
        action.restart();
        restarted = true;
    }
    return action.act(delta);
}

public void restart () {
    super.restart();
    restarted = false;
}

public void reset () {
    super.reset();
    restarted = false;
}
```

And if we want to automate it, have this in SequenceAction:

```
public void addAction (Action action){
    if (actions.contains(action)) action = Actions.restart(action);
    super.addAction(action);
}
```

**Comment by cypherdare** [comment]
Or a more verbose to use, but possibly less surprising version:

```
//RestartAction extends DelegateAction:

protected boolean delegate(float delta){ 
    action.restart();
    return true;
}
```

```
//SequenceAction
public void addAction (Action action){
    if (actions.contains(action)) 
        super.addAction(Actions.restart(action));
    super.addAction(action);
}
```

**Comment by NathanSweet** [comment]
That would be OK, until it is put in a parallel action. Better to have less magic, people have to understand that the action should be reset or (most commonly) different action instances used.
