### ISSUE TITLE
It's unclear how interpolations act like

### ISSUE THREAD

**Issue by desertkun** [libgdx/libgdx#4127]
[This](https://github.com/libgdx/libgdx/wiki/Interpolation) article have good explanations for interpolations, but unfortunatelly, it's unclear how do these interpolations actually look like. That's important, if you want to have control over your variables.

So I rendered them using google charts: [interpolation.zip](https://github.com/libgdx/libgdx/files/301468/interpolation.zip)

They looks like these:
![bounce](https://cloud.githubusercontent.com/assets/1666014/15839958/6b3027fc-2c4f-11e6-8ffe-2f6b81fdbf78.png) ![swingin](https://cloud.githubusercontent.com/assets/1666014/15839961/6b323920-2c4f-11e6-931e-aec1a2a21681.png) ![elastic](https://cloud.githubusercontent.com/assets/1666014/15840094/34e1f594-2c50-11e6-9b14-d406687c5a1c.png)

Would be great if you add them to the article. Thank you.

**Comment by Tom-Ski** [comment]
The wiki is publicly editable, feel free to alter it.

**Comment by desertkun** [comment]
@Tom-Ski seems like I can't upload images (but can refer), so where should I store them? Is github itself a good solution?

**Comment by Tom-Ski** [comment]
You can host them anywhere as long as your host allows linking.  Or you can upload the file via git.

**Comment by davebaol** [comment]
@desertkun 
Just use the linkd of the images you uploaded in the 1st post. :wink:

**Comment by desertkun** [comment]
@davebaol Thank you, [that did the trick](https://github.com/libgdx/libgdx/wiki/Interpolation#visual-display-of-interpolations).

**Comment by davebaol** [comment]
nice work :+1:

**Comment by xoppa** [comment]
It looks like the y axis on those images are not correct. The values can actually exceed the range [0 - 1] which they do not in those images. But they practically all start at (close to) zero and end at one, which is also not the case in those images.

**Comment by desertkun** [comment]
@xoppa I am not sure if exceeding the range [0 - 1] would make sense. AFAIK, for interpolations you need only values [0 - 1], and then you scale them as you want.

**Comment by xoppa** [comment]
It doesn't matter whether that functionality makes sense (it does btw, give it a try). It does what it does and those images do not reflect that. E.g. according to your images `Interpolation.elastic.apply(0)` would result in `~0.2` while it actually results in `0`.

**Comment by desertkun** [comment]
@xoppa got the point. Will fix when get some time.
