### ISSUE TITLE
Particle in game is not the same in editor

### ISSUE THREAD

**Issue by massonetto** [libgdx/libgdx#4132]
#### Issue details
When i add the ParticleEffect in my game it is different from the original in the editor

#### Reproduction steps/code
Here is the particle : 
[particle.zip](https://github.com/libgdx/libgdx/files/304982/particle.zip)

If it is loaded on Game, it will be different if loaded in Editor

#### Version of LibGDX and/or relevant dependencies
I am using the last version on GIT

**Comment by Tom-Ski** [comment]
Please provide a self contained example as the issue template asks for.  2D? 3D? 

You can reopen this issue when you have supplied all the information required for us to investigate.

**Comment by massonetto** [comment]
Thanks, when i was building the sample, i found the problem. It was in the camera.
