### ISSUE TITLE
Issues with Versioning, Backends, and Deprecations

### ISSUE THREAD

**Issue by JBird62** [libgdx/libgdx#4133]
I have successfully built and deployed a LibGDX game on desktop for linux, 
but I am having issues with attempting to use a JOGL backend on a new project. 
I currently develop on 64 bit ubuntu 14.04 using LibGDX 1.9.3 and Gradle 2.13.

I have researched for a few weeks and I am confused on the topic on using a JOGL backend. My end goal is to build a game/GUI that can be deployed on a Raspberrypi 2B with the latest raspian Jessie. RPI just released a few weeks ago the ability to use OpenGL ES 2 on Raspbian Jessie. I have attempted to port multiple games(or at least game samples) to my PI; all games were used with a lwjgl backend with nothing but errors forming from PI. 
 I came across using JOGL backends in LIBGDX. However, I have read using JOGL was deprecated, yet in the github repository, there were files released for doing just that 8 days ago, though I haven't been able to find some of the files I am told to alter (i.e. multiple pom.xml files). Also, most ports to Raspberry pi that I came across were done back in 2013 when Raspbian Wheezy was the supported image. Wheezy is now deprecated and Jessie is now the supported image.
  I saw a build.gradle file in the LibGDX master repository I downloaded; I attempted to execute a build with my gradle version 2.13(the Latest I do Believe). Running the build with --stacktrace, I was told I needed to build with the Gradle Version 2.2 as well as a problem occured evaluating root project (the master repository I downloaded). My questions are this.

  If I was to build using Gradle 2.2, I would only want to use it once for this build. Is that possible? I only see about changing a path to use Gradle wrapper 2.2.

  Was using JOGL Backend with LibGDX only when LibGDX was using the AntBuild? The reason I ask is because of all the pom.xml files I apparantly need to alter.

  If using a JOGL backend build with LibGDX is possible, do I need to alter the files in the LibGDX master repository I downloaded and build it to a new gdx_setup.jar?

Can anyone supply a possible link to explain to me how to to use the LibGDX Master Repository effectively and efficiently? That would be greatly appreciated.

Thank you all in advance. I appreciate any help.

**Comment by MobiDevelop** [comment]
LibGDX has not maintained a JOGL backend in several years. There was a third-party JOGL backend which may or may not still be maintained, but there would be no way to use that via the setup application.

Please use the forum or irc for further questions.
