### ISSUE TITLE
LWJGL3 - OpenGL 3.2 - switching to fullscreen or back breaks rendering.

### ISSUE THREAD

**Issue by NateAustin** [libgdx/libgdx#4135]
With LWJGL3 back end, when using OpenGL 3 (requesting 3.2), switching to fullscreen mode while the app is running (or to windowed mode from fullscreen)  causes rendering to fail. glClear works, but no subsequent render calls seem to.

EXPECTED:
badlogic logo shows up after switching to fullscreen. (This works on LWGL2 and on LWJGL3 without OpenGL 3 core profile.)

ACTUAL:
demo app shows red screen with no logo. 

#### Reproduction steps/code
This is barebones app with 3 changes.

1. use lwjgl3 backend
2. `useOpenGL3(true, 3, 2);`
3. code to toggle fullscreen on any keypress

gradle:
```
project(":desktop") {
    apply plugin: "java"
    dependencies {
        compile project(":core")
        compile "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
    }
}
```

launcher:
```
public class DesktopLauncher {
  public static void main (String[] arg) {
    Lwjgl3ApplicationConfiguration config = new Lwjgl3ApplicationConfiguration();
    config.useOpenGL3(true, 3, 2);
    new Lwjgl3Application(new TestLwjgl3(), config);
  }
}
```

App:
```
public class TestLwjgl3 extends ApplicationAdapter {
	
	private SpriteBatch batch;
	private Texture img;
	private boolean shouldBeFullscreen = false;
	
	@Override
	public void create () {
		batch = new SpriteBatch();
		img = new Texture("badlogic.jpg");


		Gdx.input.setInputProcessor(new InputAdapter() {
			@Override
			public boolean keyDown(int keycode) {
				shouldBeFullscreen = !shouldBeFullscreen;

				if (shouldBeFullscreen) {
					if (!Gdx.graphics.isFullscreen()) {
						Gdx.graphics.setFullscreenMode(Gdx.graphics.getDisplayMode());
					}
				} else {
					if (Gdx.graphics.isFullscreen()) {
						Gdx.graphics.setWindowedMode(640, 480);
					}
				}
				
				return true;
			}
		});
		
	}

	@Override
	public void render () {

		Gdx.gl.glClearColor(1, 0, 0, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		batch.begin();
		batch.draw(img, 0, 0);
		batch.end();
	}
}
```

#### Version of LibGDX and/or relevant dependencies

1.9.3 and 1.9.4-SNAPSHOT, lwjgl3

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [x] MacOS

I'm totally willing to help chase this down, especially if someone can point me in the right direction.

**Comment by intrigus** [comment]
Quick guess: glfw didn't provide a function to (directly) switch to full screen, so badlogic emulated it by creating a full screen window that shares its context with the non full screen window.
Afaik not everything of a context can be shared. You may have hit this case. 
Iirc glfw allows switching to full screen in the latest version, but it's is not yet implemented.

**Comment by NateAustin** [comment]
Thanks for the context!

**Comment by intrigus** [comment]
Works fine here.
Mac OS X version 10.11.4 (15E65).

Your example didn't compile btw, I had to add this
````java
ShaderProgram.prependVertexCode = "#version 140\n#define varying out\n#define attribute in\n";
ShaderProgram.prependFragmentCode = "#version 140\n#define varying in\n#define texture2D texture\n#define gl_FragColor fragColor\nout vec4 fragColor;\n";
````

Nur sore why it works on your Mac :)

**Comment by NateAustin** [comment]
You're right, sorry! I took a shortcut and only tested my testbed on Windows. Since my real app is having trouble on both windows and mac, I assumed it was the same issue. Looks like it's not the same issue, I'll dig some more.

**Comment by NateAustin** [comment]
Ok, I've done some more thorough testing and narrowed this down to a few different issues. On Mac there's a bug with reported size, but there's a workaround. On windows I get more severe problems when resizing generally, and fatal problems when switching to fullscreen under LWJGL3 and OpenGL3.
## On Windows
1. For regular window resizing (dragging the window edge), under LWJGL3 it is now necessary for the user to call `glViewport` with the new window size.
2. On Windows Using LWJGL3 and OpenGL 3, transitioning to fullscreen from windowed mode breaks all rendering (except for clear color.) Transitioning back to windowed does not fix the issue. LWJGL3 without OpenGL3 specified does not see this problem. I've tested on 1 NVIDIA and 1 intel integrated card with the same results.
3. Additionally, similar to mac, the `Gdx.graphics.getWidth()` /etc.. functions return out of date values, but only when transitioning to Fullscreen. This occurs with or without `config.useOpenGL3(true,3,2);`

## On Mac
In the `ApplicationListener.resize` call, only when switching to and from fullscreen, the arguments passed to `resize()` are correct, and the value of `Gdx.graphics.isFullscreen()` are correct, howerver the values of `Gdx.graphics.getWidth() / getHeight() and Gdx.graphics.getBackBufferWidth() / Height()` are out of date. For example:
```
resizing to FULLSCREEN: 1920, 1200 (Gdx.graphics.getX: 640, 480) (Gdx.graphics.getBackBufferX: 640, 480)
resizing to WINDOW: 640, 480 (Gdx.graphics.getX: 1920, 1200) (Gdx.graphics.getBackBufferX: 1920, 1200)
```
This is confusing and doesn't match other resize behavior. This occurs with or without `config.useOpenGL3(true,3,2);`

Here's my modified testbed:
```
public class TestLwjgl3 extends ApplicationAdapter {
	
	private SpriteBatch batch;
	private Texture img;

	@Override
	public void create () {
		ShaderProgram.prependVertexCode = "#version 140\n#define varying out\n#define attribute in\n";
		ShaderProgram.prependFragmentCode = "#version 140\n#define varying in\n#define texture2D texture\n#define gl_FragColor fragColor\nout vec4 fragColor;\n";

		batch = new SpriteBatch();
		img = new Texture("badlogic.jpg");

		Gdx.input.setInputProcessor(new InputAdapter() {
			@Override
			public boolean keyDown(int keycode) {
				if (Gdx.graphics.isFullscreen()) {
					Gdx.graphics.setWindowedMode(640, 480);
				} else {
					Gdx.graphics.setFullscreenMode(Gdx.graphics.getDisplayMode());
				}
				return true;
			}
		});
		
	}

	@Override
	public void resize(int width, int height) {
		String ew = Integer.toString(Gdx.graphics.getWidth());
		String eh = Integer.toString(Gdx.graphics.getHeight());
		String sw = Integer.toString(width);
		String sh = Integer.toString(height);
		String logicalW = Integer.toString(Gdx.graphics.getBackBufferWidth());
		String logicalH = Integer.toString(Gdx.graphics.getBackBufferHeight());
		String mode;
		if (Gdx.graphics.isFullscreen()) {
			mode = "FULLSCREEN";

		} else {
			mode = "WINDOW";
		}
		System.out.println("resizing to " + mode + ": " + sw + ", " + sh
				+ " (Gdx.graphics.getX: " + ew +  ", " + eh + ")"
				+ " (Gdx.graphics.getBackBufferX: " + logicalW +  ", " + logicalH + ")");

		batch.getProjectionMatrix().setToOrtho2D(0, 0, width, height);
		//The following line is necessary on Windows to make window resizing work correctly. Not needed on Mac.
		//Gdx.gl20.glViewport(0, 0, width, height);
	}

	@Override
	public void render () {
		Gdx.gl.glClearColor(1, 0, 0, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		batch.begin();
		batch.draw(img, 0, 0, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
		batch.end();
	}
}
```

Should I break this up into separate issues?

**Comment by intrigus** [comment]
Please break it up into separate issues.
