### ISSUE TITLE
Controllers extension - The sent HWND is not valid!

### ISSUE THREAD

**Issue by metc** [libgdx/libgdx#4139]
I use `libgdx` version 1.5.6 with the same `gdx-controllers` version on PC (tested on Windows).

When I start a libgdx application in "standalone" mode (using `LwjglApplication`), the controllers extensions works as expected and I am able to use the connected controller.

But when I launch the libgdx application in a Swing frame (using a `LwjglAWTCanvas`), the same application code makes the JVM crashing. This is due to this line:

```java
Controllers.getControllers();
```

I get this error:

```
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'OIS::Exception'
  what():  Win32InputManager::Win32InputManager >> The sent HWND is not valid!
AL lib: (EE) alc_cleanup: 1 device not closed
```

![jvm](https://cloud.githubusercontent.com/assets/229670/15956099/6ae9717e-2ee6-11e6-8253-ee463860aac9.png)

**Comment by Darkyenus** [comment]
Try updating libGDX to the latest version and reproducing the error there, I doubt anybody will want to debug libGDX this old. That said, I'm not sure we even still support AWT in latest version, as it is hard to get it right (as you have just noticed).

**Comment by metc** [comment]
Ok, thanks.
