### ISSUE TITLE
FR: Add getUrl() to FileHandle, use in GWT sound construction (and potentially for other resources)

### ISSUE THREAD

**Issue by stefanhaustein** [libgdx/libgdx#4145]
Currently, it's not possible to create sounds from data with LibGdx.

Theoretically, one could create a temp file for this purpose, but for the web platform, the only file system available is read-only, and adding unnecessary FS IO seems to be quite inefficient.

A getUrl() method (perhaps utilizing an optional, type- and platform-specific base URL) would allow users to create custom FileHandle implementations that could provide "data:" urls (when generating simple resources clientside) and / or blob urls (e.g. for indexeddb blobs) on the web platform.

**Alternatives considered**

Direct sound / image construction from URLs

- URLs for specific types of data (byter buffers, database entries) may not be desirable / available on all platforms. 
- FileHandle is already used to construct resources from URLs, just in a way that can't be directly utilized by the user for bytebuffers or database entries

Direct sound / image construction from Data

- Would require to materialize data asynchronously on the web platform in cases where handing over a handle would be sufficient

**Comment by badlogic** [comment]
I'd rather not introduce fullblown URL support in FileHandle. It's
absolutely not portable, and if implemented by us, would likely generate
tons of garbage and be broken in funky ways.

FileHandle is simple enough to be extended and implemented in a custome
way, e.g. provide access to in-memory data. I think I've actually seen
people wrap bytebuffers and data URLs that way for very specific purposes.

**Comment by stefanhaustein** [comment]
My use case is: I have a (platform-specific) database full of wav and png data. I need to turn this into Pixmap and Sound instances. However, the GWT sound implementation just uses the file name to construct a URL in a specific way, assuming there is a sound file relative to some app base URL. I don't think any amount of custom FileHandle code would be able to address this in some magic way.

**Comment by stefanhaustein** [comment]
After working with libgdx some more, I agree that first class URL support wouldn't be a good match for FileHandle, as potentially would introduce async problems down the line. The GWT sound issue persists, but I think I might be able to create a smaller scope pull request to address this.
