### ISSUE TITLE
Pixmap.getPixels() doesn't return the pixel data for GWT

### ISSUE THREAD

**Issue by stefanhaustein** [libgdx/libgdx#4148]
Platform: GWT
Expected: Pixmap.getPixels() returns a "native" nio buffer backed by the canvas pixel array.
Actual: An int buffer of size 1 containing the image id is returned.

**Comment by MobiDevelop** [comment]
See: https://github.com/libgdx/libgdx/pull/3665

**Comment by stefanhaustein** [comment]
Well I guess that explains to some extent why the method doesn't do what one would expect.

It doesn't explain why it does something completely different, making debugging more tricky than necessary (opposed to an exception).

Shouldn't there be at least a warning in the JavaDoc that the method doesn't work for the web platform? 

While it would certainly be possible to implement a ByteBuffer that behaves as expected (e.g. accessing pixels via the Pixmap instance with a null check), it would probably be relatively inefficient, in particular for writing... Is there any chance of adding bulk data read / write methods that can actually work efficiently on all platforms?

**Comment by badlogic** [comment]
We have a readme in the backend that discusses issues https://github.com/libgdx/libgdx/blob/master/backends/gdx-backends-gwt/issues.txt

I'll link to that in the respective places in the wiki.
