### ISSUE TITLE
WebGL error when load (png) image in Firefox Developer Edition.

### ISSUE THREAD

**Issue by Dgzt** [libgdx/libgdx#4149]
#### Issue details

WebGL error when load (png) image in Firefox Developer Edition.
#### Reproduction steps/code
- Download gdx-setup.jar
- Generate empty (HTML) project
- ./gradlew html:dist
- Open in the Firefox Developer Edition from local server
#### Version of LibGDX and/or relevant dependencies

libGDX 1.9.3
Firefox Developer Edition 49.0a2 (2016-06-13)
#### Stacktrace in browser's console

Error: WebGL: texImage2D: Chosen format/type incured an expensive reformat: 0x1908/0x1401
#### Please select the affected platforms
- [x] HTML/GWT

**Comment by MobiDevelop** [comment]
This sounds like a Firefox issue, not a libgdx issue.

Appears to also be affecting three.js, see https://github.com/mrdoob/three.js/issues/9109.
