### ISSUE TITLE
Model instance.transform rotation and translate dont work perfectly together

### ISSUE THREAD

**Issue by Aduci01** [libgdx/libgdx#4150]
touchPosition.x = Gdx.input.getX();
        touchPosition.y = Gdx.input.getY();
        rotation.y = (float) Math.atan2(touchPosition.x - Gdx.graphics.getWidth() / 2, touchPosition.y - Gdx.graphics.getHeight() / 2) * MathUtils.radiansToDegrees + 90;
        shipInstance.transform.translate(-10, 0, 0);
        shipInstance.transform.setToRotation(new Vector3(0,1,0),rotation.y);

Only the rotation works, translation does not.

**Comment by Tom-Ski** [comment]
If you want to report an issue, please read the issue template that is presented to you when you create a new issue.

**Comment by mbrlabs** [comment]
` shipInstance.transform.setToRotation(new Vector3(0,1,0),rotation.y);` 
this resets your matrix and then rotates it, so the translation is lost.

Try this instead:
```
transform.translate(-10, 0, 0);
transform.rotate(new Vector3(0,1,0),rotation.y);
```
