### ISSUE TITLE
RotateToAction behavior missing wrap around logic

### ISSUE THREAD

**Issue by wiverson** [libgdx/libgdx#4154]
#### Issue details

RotateToAction does not properly deal with rotation cases around the 360 degree barrier - it always goes "the long way around".

```
com.badlogic.gdx.scenes.scene2d.actions.RotateToAction.update (float percent) {
        target.setRotation(start + (end - start) * percent);
    }
```

should probably be implemented as something like...

`target.setRotation(MathUtils.lerpAngleDeg(start, end, percent));
`
#### Version of LibGDX and/or relevant dependencies

  `gdxVersion = '1.9.3'
`
#### Affected platforms  - All

My first reported issue, so be kind.  :)  Seems awfully tiny for a pull request, but if that or anything else would be helpful just let me know.

**Comment by xoppa** [comment]
So, you are suggesting that if an actor is currently unrotated and you apply a RotateToAction to 360 or 720 degrees to it, then it should do nothing (instead of fully rotating once or twice)? That doesn't sound right. Why do you think that?

**Comment by wiverson** [comment]
Right now, if you have an actor currently rotated to 359, and you give it a RotateTo of 1, it goes all the way around (moving a full 358 degrees) instead of moving two degrees back to the 1.  That doesn't seem right either.

It might be that there is room for two Actions here instead, maybe a RotateTo and a RotateToDirect or something, or a parameter for RotateTo...?

**Comment by wiverson** [comment]
Another idea - RotateTo (which takes a destination angle and rotates directly to the angle) and SpinTo (which explicitly spins to the target angle, multiple times if given values above 360 or below 0, clockwise if positive and counter-clockwise if negative).

Happy to do a pull if that is helpful.

**Comment by badlogic** [comment]
This is about taking the shortest path for a rotation. Should be a parameter to RotateTo. Happy to merge PRs for that.
