### ISSUE TITLE
Jnigen can't have a Class argument 

### ISSUE THREAD

**Issue by mdsimmo** [libgdx/libgdx#4157]
Whenever a native method with a Class argument is passed, jnigen will crash with this error:

```
Generating C/C++ for 'src/main/java/my/domain/MyClass.java'
...Exception in thread "main" java.lang.RuntimeException: Couldn't find C method for Java method 'MyClass#myNativeMethod'
at com.badlogic.gdx.jnigen.NativeCodeGenerator.generateCppFile(NativeCodeGenerator.java:322)
at com.badlogic.gdx.jnigen.NativeCodeGenerator.processDirectory(NativeCodeGenerator.java:267)
at com.badlogic.gdx.jnigen.NativeCodeGenerator.processDirectory(NativeCodeGenerator.java:245)
...
```
#### Reproduction steps/code

Try to create this native method:

```
public static native <T> int myNativeMethod (int a, Class<T> crashParam, int b); /*
    return a + b;
*/
```

If `crashParam` is removed, the code compiles cleanly and runs fine. Note: when the program does crash, only the *.h file is created.
#### Version of LibGDX and/or relevant dependencies

JNIGen version 1.9.3.
Not using LibGDX.
Running Ubuntu

**Comment by mdsimmo** [comment]
I've made a pull request that fixes this here: #4158

**Comment by np511** [comment]
Does this happen if you don't template the Class parameter?

**Comment by mdsimmo** [comment]
"template the Class parameter" is referring to the generic type, right? If so, then yes. The same bug occurs using raw types or generic types. My solution in the pull request will only work with raw types.

**Comment by badlogic** [comment]
@mdsimmo commented on the PR. Closing this out.
