### ISSUE TITLE
Clicklistener loses focus when 'actor' added to a stage

### ISSUE THREAD

**Issue by Magic-WoW** [libgdx/libgdx#4170]
#### Issue details
ClickListener won't listen after operations on 'Stage' 

#### Reproduction steps/code
Here's the listener:
```
 connectButton.addListener(new ClickListener(){
            @Override
            public void clicked(InputEvent ev, float x, float y){
                Notification.show("text", SUCCESS, stage);
             });
```

```
public static void show(String text, NotificationType type, Stage stage){

        Skin skin = new Skin(Gdx.files.internal("data/notificationskin.json"));
        Dialog dialog = new Dialog("", skin);
        dialog.setSize(Gdx.graphics.getWidth(), Gdx.graphics.getHeight()/10);
        dialog.setPosition(0, Gdx.graphics.getHeight() + dialog.getHeight());
        Label label = new Label(text, skin);
        dialog.add(label);

        label.setColor(Color.BLUE);
        dialog.setKeepWithinStage(false);



        MoveToAction moveTo = new MoveToAction();
        moveTo.setPosition(dialog.getX(), Gdx.graphics.getHeight() - dialog.getHeight());
        moveTo.setDuration(2f);

        MoveToAction moveBack = new MoveToAction();
        moveBack.setPosition(dialog.getX(), Gdx.graphics.getHeight() + dialog.getHeight());
        moveBack.setDuration(2f);

        SequenceAction action = new SequenceAction(moveTo, Actions.delay(1.0f), moveBack, Actions.removeActor());

        dialog.addAction(action);

        stage.addActor(dialog);


    }

```
After clicking ONCE, the button won't listen till the actor is removed from the stage. There are two options:
1. Thread is stopped - which is wrong, cause drawing is performed (as I know, gdx uses one thread). Also, I made a Log output after 'stage.addActor(dialog)' and it prints immediately which means that none if these lines block the thread.
2. Button, (when clicked) adds the actor and loses focus somehow.

Is this a bug, or I'm just a stupid newbie?
#### Version of LibGDX and/or relevant dependencies
latest, pulled yesterday

**Comment by intrigus** [comment]
That's not a [sscce.org](http://www.sscce.org).
I'm unable to reproduce this issue, since it can't be compiled.

The problem is most likely in your code.
If you need help, have a look at https://github.com/libgdx/libgdx/wiki/Getting-Help, the issue tracker is not the right place for questions.

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
