### ISSUE TITLE
Warning: Class 'com.foo.DesktopLauncher' not found in module 'desktop' immediately after following setup directions

### ISSUE THREAD

**Issue by johndanek** [libgdx/libgdx#4173]
#### Issue details
I followed the instructions at https://github.com/libgdx/libgdx/wiki/Project-Setup-Gradle so I have a brand new, blank libgdx project. I am now attempting to follow the instructions at https://github.com/libgdx/libgdx/wiki/Gradle-and-Intellij-IDEA to run this blank program. I am using IntelliJ and am getting stuck at the Running Your Project -> Desktop section.

If I follow the steps described, when I select the DesktopLauncher class, there is an error at the bottom of the window saying "Warning: Class 'com.foo.DesktopLauncher' not found in module 'desktop'". I can't seem to get around this. If I click Apply then Ok, then attempt to run, the program crashes with the same error in a stack trace:

```java
Exception in thread "main" java.lang.ClassNotFoundException: com.foo.DesktopLauncher
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:122)
```

It is interesting to note that when I click on the button to choose the main class, it does not appear under the Search By Name list. It is a selection of 30 classes in the standard sun library, starting with the letters A-C. If I set "Use classpath of module" to <no module>, my main class DOES appear under the Main class -> Search by Name list. But, it won't run without choosing a module.

#### Version of LibGDX and/or relevant dependencies
I'm not exactly sure what version of LibGDX I'm using, but I downloaded the jar from the Download Setup App link at https://libgdx.badlogicgames.com/download.html on Saturday, June 25th. I am using IntelliJ CE 2016.1.3

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS

**Comment by johndanek** [comment]
Does anyone have advice for how to get around this issue? I'm still experiencing it. IntelliJ always complains: 

Exception in thread "main" java.lang.ClassNotFoundException: com.mygdx.game.desktop.DesktopLauncher

**Comment by Tom-Ski** [comment]
I cant reproduce given the steps that you said you took.  Please open up a thread on the forum or come into the irc if you need help troubleshooting.

**Comment by johndanek** [comment]
This was fixed by refreshing the Gradle tasks (via the refresh button in the Gradle tool window), then manually attempting to run the main class by right-clicking it in the project view (instead of first setting up a Run Config). This forced IntelliJ to attempt to compile my code to the point where I could create the run config.
