### ISSUE TITLE
Avoid creating LIBGDX Window on create method

### ISSUE THREAD

**Issue by kapcip** [libgdx/libgdx#4174]
I want to use LIBGDX on the server side to create animation using **Universal Tween Engine**: [http://www.aurelienribon.com/blog/projects/universal-tween-engine/](url)

Problem is when we use LIBGDX it always calls create method (life cycle method) and opens up the Window. I need to avoid that window to be created and create animation and save the frames to the file system.

This is my create method:

`@Override
	public void create() {
		Tween.setWaypointsLimit(10);
		Tween.setCombinedAttributesLimit(3);
		Tween.registerAccessor(Sprite.class, new SpriteAccessor());

		batch= new SpriteBatch();
		
		img=new Texture("data/splash/embrace.png");
		bgImg=new Texture("data/splash/bg.jpg");

		tween = new Sprite(img);
		center(tween,-3,2);
		tween.setSize(250f,120f);
		tween.setX(800f);
		tween.setY(600f);
		tween.setScale(1,1);
		bg = new Sprite(bgImg);

		buffer = new FrameBuffer(Format.RGB888,Gdx.graphics.getWidth(),Gdx.graphics.getHeight(),false);

		
		Timeline.createSequence()
		.push(Tween.set(tween, SpriteAccessor.OPACITY).target(0))
		.push(Tween.to(tween, SpriteAccessor.OPACITY, 0.2f).target(1))
		.push(Tween.to(tween, SpriteAccessor.CPOS_XY, 0.2f).target(400,200).ease(Cubic.INOUT))
		.beginParallel()
		.push(Tween.to(tween, SpriteAccessor.ROTATION, 1f).target(360))
		.push(Tween.to(tween, SpriteAccessor.OPACITY, 0.2f).target(0.7f).repeatYoyo(1, 1))
		.end()
		.push(Tween.to(tween, SpriteAccessor.CPOS_XY, 0.2f).target(400,200).ease(Quint.INOUT))
		.push(Tween.to(tween, SpriteAccessor.SCALE_XY,1f).target(2f, 2f).ease(Back.INOUT))
		.push(Tween.to(tween, SpriteAccessor.TINT, 0.2f).target(1, 1, 1))
		.push(Tween.to(tween, SpriteAccessor.TINT, 0.2f).target(0, 1, 1))
		.push(Tween.to(tween, SpriteAccessor.TINT, 0.2f).target(1, 0, 1))
		.push(Tween.to(tween, SpriteAccessor.TINT, 0.2f).target(1, 1, 0))
		.push(Tween.to(tween, SpriteAccessor.OPACITY, 1f).target(0.4f))
		.push(Tween.to(tween, SpriteAccessor.OPACITY, 2f).target(1))
		.start(tweenManager);
		tStart = System.currentTimeMillis();
	}`
There is render method too. Currently a window opens and displays the animation and save animated frames sequences to the file system ( according to the code I've written). I want to avoid that window to be shown up so that I can do animation silently at the backend.

I am using LIBGDX 1.6.1 and OS X 10.10

**Comment by xoppa** [comment]
See Lwjgl3ApplicationConfiguration#setInitialVisible

**Comment by kapcip** [comment]
I wish to use LIBGDX on the Server backend. I read about it, I found there is a way to do that and it is running out Application in headless environment. I don't know how to do that?
There is mocking of Graphics and Audio.

My requirement is to use my Application as a library running at the backend.

**Comment by nhydock** [comment]
@kapcip you'll want to use gdx-backend-headless instead of lwjgl for your project.  Just edit your project's gradle conf to change the dependency and make the appropriate code changes to launch the HeadlessApplication.

**Comment by kapcip** [comment]
Yeah but I cannot find any help in creating HeadlessApplication. There's nothing much over Internet. I start with a Hello World Application and it throws a NullPointerException.

Below is my main method.

`public static void main(final String[] args) { 
                   HeadlessApplicationConfiguration cfg = new HeadlessApplicationConfiguration(); 
                   new HeadlessApplication(new App());
	}`

**Comment by xoppa** [comment]
Please use the forum or irc for personal support requests.
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
