### ISSUE TITLE
Suggestion: don't ignore screenX and screenY while updating Viewports

### ISSUE THREAD

**Issue by rafcolson** [libgdx/libgdx#4175]
[badlogicgames forum topic: Viewport.update() ignores screenX and screenY](http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=22932)

I started this issue for the suggestion made in #3681.

Currently I'm working on [Viewports for BDX](https://github.com/GoranM/bdx/issues/701). The behavior of LibGDX viewports as being described in this issue is causing some inconveniences. First there's the necessity to set `screenX` and `screenY` and call `apply()` after calling `update()` and secondly some of the Viewport types, such as FitViewport, won't update correctly so `screenX`, `screenY`, `screenWidth` and `screenHeight` had to be recalculated. These issues made me consider not to utilize LibGDX Viewports, but maybe that wouldn't be necessary.

@nooone mentioned that the current behavior of LibGDX Viewports is intended because they ought to be positioned at the center of the screen, when updated. I would like to suggest to change this behavior so Viewports, such us ExtendViewport, StretchViewport and FitViewport (ScalingViewports) are centered relatively to their position and size. Also ScreenViewport wouldn't always be at the left bottom corner. The old behavior would still apply if the position would be (0, 0) and the size would be the same as the size of the screen.

**Comment by NathanSweet** [comment]
It's been a while since I had my head in the viewport stuff. Can't you make a viewport that calls `setScreenBounds` to size and position the viewport wherever you like?
