### ISSUE TITLE
Suggestion: Gdx.files.internal vs. local / android vs. desktop

### ISSUE THREAD

**Issue by Swift42** [libgdx/libgdx#4178]
I used gdx-setup.jar to create an android/desktop-project for AndroidStudio.
This will result in a shared assets-folder for both modules (pointing to android/assets). This is great.
To make this work, gdx-setup.jar sets the working directory of the desktop module to the android assets folder.

But this will result in a problem:
When I'm using the desktop-module for testing (started from within AndroidStudio) and I want to save some data, I use Gdx.files.local (as suggested).

But: On desktop this will write these files to the assets folder, because that's the current working directory!
When I later compile the android-project, AS will pack these written files into the APK.
But I don't want these files in the APK.
To fix this, I currently prefix the local-path on desktop with "../../", so it will write the data in the project-root instead of the assets folder. But this is a slightly inconvenient solution.

A more convenient behaviour would be very helpful.
If there is an easier way to accomplish this via the current libgdx, please tell me.

**Comment by tdionizio** [comment]
I also had that problem, and modified my gradle file for desktop to look like something like this.

The assets directory is added to the java resources directory, meaning the files are available from the classpath which is where libgdx will look for the files if they aren't found in the 'local' directory, and copied automatically to the right place without having to depend on workarounds to make it work.

Maybe this could be included in gdx-setup?

```gradle
apply plugin: "java"

sourceCompatibility = 1.6
sourceSets.main.java.srcDirs = [ "src/" ]
// add assets to the java resources path
sourceSets.main.resources.srcDirs = [ "src/", "../android/assets/" ]

project.ext.mainClassName = "main.class.name"

task run(dependsOn: classes, type: JavaExec) {
    main = project.mainClassName
    classpath = sourceSets.main.runtimeClasspath
    standardInput = System.in
    // no longer necessary, can start from another directory
    // workingDir = project.assetsDir
    ignoreExitValue = true
}

task dist(type: Jar) {
    from files(sourceSets.main.output.classesDir)
    from files(sourceSets.main.output.resourcesDir)
    from {configurations.compile.collect {zipTree(it)}}
    // no longer necessary
    // from files(project.assetsDir);

    manifest {
        attributes 'Main-Class': project.mainClassName
    }
}

dist.dependsOn classes

...
```

**Comment by badlogic** [comment]
@tdionizio 's solution is the way to go. There's no way for us to work around this within the file i/0 AP I'm afraid. Including this by default will lead to other issues though, e.g. packaging directories that shouldn't be packaged in desktop builds etc. Please apply this fix manually to your Gradle build.
