### ISSUE TITLE
backgroundFPS = 0 for rendering when not in focus dont work Libgdx - Timers, they wont call until back in focus

### ISSUE THREAD

**Issue by genaray** [libgdx/libgdx#4182]
Please ensure you have given all the following requested information in your report.
#### Issue details

Normally the Timers should also be called when in background or not in Focus using backgroundFPS = 0; but that dont work with LwjglApplication. When i use a timer it only triggers when the game is in focus. 
#### Reproduction steps/code

```
LwjglApplicationConfiguration cfg = new LwjglApplicationConfiguration();
cfg.title = "Your Title";

cfg.vSyncEnabled = false;
cfg.forceExit = true;

cfg.backgroundFPS = 0; // enable to also render when not in focus (dont work)
cfg.foregroundFPS = 100; // Fps - Cap

cfg.width = 1920;
cfg.height = 1080;

cfg.fullscreen = false;

System.setProperty("org.lwjgl.opengl.Window.undecorated", "true");

new LwjglApplication(new GameClass(), cfg); // Put in here your Libgdx Game class with a timer in the render method !
```
#### Version of LibGDX and/or relevant dependencies

1.9.3
#### Stacktrace

java, libgdx, window, lwjgl, thread, lifecycle
#### Please select the affected platforms
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by genaray** [comment]
Could someone please tell me if he gets the same problem as me ? Tested it on 2 devices and it didnt worked, normally it should right ?

**Comment by code-disaster** [comment]
I can confirm this behavior. Though this seems to not be an issue, but a feature.

Timers != Rendering

The render function is still called with backgroundFPS != -1 and the application window not in focus. 

The thread responsible for updating timers is registered as a LifecycleListener, which means it gets suspended when the window loses focus. As far as I can see, there is currently no option available to prevent that.

**Comment by 3xp0n3nt** [comment]
@genaray If you use @code-disaster's hack, you'll need to manually call `TimerThread#dispose`.

**Comment by 3xp0n3nt** [comment]
I would also call `Timer.instance()` (or `new Timer()`) before removing the `LifecycleListener`, just to be 100% sure that `Timer.thread` isn't null.

**Comment by badlogic** [comment]
Works as designed.
