### ISSUE TITLE
Scene2d Table Not expected behavior

### ISSUE THREAD

**Issue by Yayo-Arellano** [libgdx/libgdx#4183]
#### Issue details
When i create a Table after that i call row() and then i add an item is expected that that this item is in the next line. 

In Libgdx version 1.6.5 i create a TextButton with some text then i called row() to add a new label to this button. This label will be in a new line but after libgdx version 1.7.0 this label will be in the right side of the previous label. 

This image was taken using 1.6.5.
![screen shot 2016-07-08 at 9 23 58 pm](https://cloud.githubusercontent.com/assets/3458265/16688803/65eb05a2-4552-11e6-817e-88551bcb01b1.png)

And this one using the latest release 1.9.3.
![screen shot 2016-07-08 at 9 26 00 pm](https://cloud.githubusercontent.com/assets/3458265/16688849/a0b49ba8-4552-11e6-8c96-84d17979ba50.png)

#### Reproduction steps/code
I created a simple code. Using the default skin. 

```java
public class TableBug extends ApplicationAdapter {
    
    public Skin skin;
    Stage stage;
    Table container;


    @Override
    public void create() {
        skin = new Skin(Gdx.files.internal("UI/uiskin.json"));

        container = new Table();
        container.setFillParent(true);


        stage = new Stage();
        stage.addActor(container);

    }

    @Override
    public void render() {
        Gdx.gl.glClearColor(1, 0, 0, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

        stage.act();
        stage.draw();

        if (Gdx.input.justTouched()) {
            TextButton newButton = new TextButton("Button ", skin);
            container.row();
            container.add(newButton);
        }
    }
}
```

#### Version of LibGDX and/or relevant dependencies
version 1.7.0 and up

#### Please select the affected platforms
- [ yes] Android
- [ yes] iOS (robovm)
- [ yes] iOS (MOE)
- [ yes] HTML/GWT
- [ yes] Windows
- [ yes] Linux
- [ yes] MacOS

**Comment by cypherdare** [comment]
[It was introduced here.](https://github.com/libgdx/libgdx/commit/b1483bf4589424f661f4cbca1b08420cce5f6a0d) I ran into this a while ago and forgot to submit an issue or look into it.

Can't test it on this computer, but I think the `row()` method in Table needs to set `implicitEndRow` to false.
