### ISSUE TITLE
Where is model-loaders project?

### ISSUE THREAD

**Issue by huylv177** [libgdx/libgdx#4191]
Hello
I'm following this tutorial https://www.youtube.com/watch?v=Ufm-89CkGZk to run the ModelLoaderAdapters project, it require model-loaders project as library. But i cant found it in latest commit. I found "model-loaders" in an older commit (in someone's github), i try import but give many errors because of the GL10 was removed. 
So, where is the model-loaders now?

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
