### ISSUE TITLE
There is not setSize() method in the class com.badlogic.gdx.utils.FloatArray of gdx.jar of downloading on official site.

### ISSUE THREAD

**Issue by linguokunSponia** [libgdx/libgdx#4193]
There is not "setSize(int newSize)" method in the class com.badlogic.gdx.utils.FloatArray of gdx.jar downloaded on official site.

So that Android Studio reported error when I used Spine-libgdx runtimes library. Please help.

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker

**Comment by linguokunSponia** [comment]
@xoppa  Hello, my question is not a small trouble for me. I'm an Android Developer, I use Android Studio to develop but the gdx.jar and the library of this is compile from jdk1.8. If Androd Studio apply to jdk1.8, it must be enabled jackOptions that lead to build the project for more than 5 minutes. 
So I can't use the jar or gdx library of Github that compiled by jdk1.8. Please Help to me.
I think many Android Developer will meet this problem?

**Comment by xoppa** [comment]
As said in that link, please use the forum or irc for personal support requests.
