### ISSUE TITLE
Add 3D audio functionality to Music and Sound

### ISSUE THREAD

**Issue by CreamyCookie** [libgdx/libgdx#4196]
In OpenAL a sound can have a 3D position and velocity. Being able to set these for `Sound` and `Music` would be great.

The function signatures would probably look something like this:

``` java
public void setSourcePosition(Vector3 position)
public void setSourceVelocity(Vector3 velocity)
```

**Comment by Metaphore** [comment]
As I know problem comes in portability. For example Android doesn't provide OpanAL and LibGDX uses native classes like `MediaPlayer`. And they come with very limited control over playback...

**Comment by badlogic** [comment]
I'm afraid @metaphore is correct, we can't port spatial audio to anything but desktop systems.

**Comment by CreamyCookie** [comment]
@badlogic That's true, but may I ask why that is a problem?  There are certainly features that are [only supported on Android](https://github.com/libgdx/libgdx/wiki/Configuration-%26-querying#disabling-accelerometer--compass-android-only) and I would never argue that they shouldn't be there because of that. Of course, I understand that it's a good idea to not clutter the API with too many platform specifics, but that's not even the case here and I can certainly see those methods being useful on mobile platforms as well.

Only slightly related but Google's Cardboard SDK for Android [will get spatial audio support](https://developers.googleblog.com/2016/01/spatial-audio-comes-to-cardboard-sdk.html).

**Comment by badlogic** [comment]
We start with these 2 methods. Then users will want the full OpenAL feature set (if I added spatial audio I'd not be happy with just these two methods). The things explode and only work on desktop and users will complain.
