### ISSUE TITLE
HttpRequest does not support DELETE method properly

### ISSUE THREAD

**Issue by Fumble-eric** [libgdx/libgdx#4197]
#### Issue details

When using HttpRequest to send a DELETE with JSON content, it does not work properly and the JSON is ignored
#### Reproduction steps/code

Try the following code with a proper REST service supporting DELETE command:

``` java
         HttpRequest httpGet = new HttpRequest(HttpMethods.DELETE);
         httpGet.setHeader("Content-Type", "application/json");
         httpGet.setHeader("Accept", "application/json");
         httpGet.setUrl("https://myservice.com/main/v1/user/me/achievement");
         httpGet.setContent("{\"achievements\":[{\"achievement\":\"MY_ACHIEVEMENT\"}]}");

         Gdx.net.sendHttpRequest (httpGet, new HttpResponseListener() {

            @Override
            public void handleHttpResponse(HttpResponse httpResponse) {
                try
                {
                    String result = httpResponse.getResultAsString();
                    Json json = new Json();
                    Map<String, Object> test = json.fromJson(parameters.getClass(), result);
                    if (httpResponse.getStatus().getStatusCode()!=HttpStatus.SC_NO_CONTENT)
                    {
                        if (listener!=null)
                            listener.removeAchievementFailed("Status not ok: " + result);
                        return;
                    }
                    if (listener!=null)
                        listener.removeAchievementSucceeded(achievement);
                }
                catch(RuntimeException e)
                {
                    if (listener!=null)
                        listener.removeAchievementFailed("Error parsing httpResponse");
                }
            }

            @Override
            public void failed(Throwable t) {
                if (listener!=null)
                    listener.removeAchievementFailed("Connection failed");

            }

            @Override
            public void cancelled() {
                if (listener!=null)
                    listener.removeAchievementFailed("Connection cancelled");

            }
        });         
```

After analysis the problem come from the com.badlogic.gdx.net.NetJavaImpl class in the method sendHttpRequest.
If you look at the code, the GET, POST and PUT method are taking into account and not the DELETE.
Especially with the doingOutput which should be true for DELETE.

The sending of httpRequest.getContent() is conditionned by this flag so it is not sent for a DELETE.
#### Version of LibGDX and/or relevant dependencies

Version 1.7.1
#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [ ] MacOS

**Comment by nhydock** [comment]
DELETE should not have message bodies, it's supposed to handle things directly by URI.  If you want to have a message body in a request, use POST.  A lot of servers ignore bodies on DELETE requests, and most clients now (including Android) will strip off a body of a DELETE request.  Bodies on deletes, while not explicitly indicated as to not be allowed as part of the spec, are not universally supported and shouldn't be used.

A "proper REST service supporting DELETE command" should be ignoring the message body or returning a 400 when on is present.

**Comment by Fumble-eric** [comment]
Agree but the service I'm using (which is not under my control), expect to receive a body with a DELETE request

**Comment by badlogic** [comment]
@Fumble-eric please submit a PR for this.

**Comment by alexzk1** [comment]
It seems it is broken yet in 1.9.6
Facebook API does not receive "access_token"
DELETE https://graph.facebook.com/[{REQUEST_OBJECT_ID}_{USER_ID}]?
      access_token=[USER or APP ACCESS TOKEN]
