### ISSUE TITLE
iOS app generated from basic setup, createIPA should be submittable

### ISSUE THREAD

**Issue by ericnondahl** [libgdx/libgdx#4198]
#### Issue details

Use LibGDX setup tool to generate a basic iOS app. Attempting to submit to app store fails due to several missing requirements. We should probably start new developers off on the right foot by having the minimum requirements in the generated iOS app, so they can start developing instead of troubleshooting the setup. I'll make a PR to improve this if I have time, just documenting the idea right now.
#### Reproduction steps/code
- Download libgdx setup app
- Create basic ios project
- Build with gradle task createIPA
- Attempt to submit to app store

Upload fails:
- Missing 64 bit support
- No minimum iOS version set
- Error about multitasking config
#### Version of LibGDX and/or relevant dependencies

1.93
#### Please select the affected platforms
- [X] iOS (robovm)

**Comment by Tom-Ski** [comment]
64 bit is supported, not sure what you mean by that it is missing.  

There should be a minimum iOS version set of iOS 6, can you pastebin a full log of building your artifact.

**Comment by ericnondahl** [comment]
Just to clarify - 64 bit is not enabled in the basic app by the setup tool in the robovm.xml., it only lists thumbv7, which disables 64 bit support. 

https://github.com/libgdx/libgdx/blob/31e73274718e66ad3a50eb081c3f85b24f4114d9/extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/ios/robovm.xml

There is no minimum iOS version set in the Info.plist.

https://github.com/libgdx/libgdx/blob/31e73274718e66ad3a50eb081c3f85b24f4114d9/extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/ios/Info.plist.xml

**Comment by badlogic** [comment]
The robovm.xml only allows to specify the default arch to compile for. You
can't specify multiple archs iirc. For that, you either use the IPA export
dialog in the IDE, or the Gradle plugin parameters, either as CLI args, or
in build.gradle.

**Comment by Tom-Ski** [comment]
That would mean that all builds would automatically build 64 bit also, which isn't something you want to be doing during development.  As I said, there is no minimum set in the info.plist, but it should be set by robovm. Please pastebin the log of building.

**Comment by ericnondahl** [comment]
Hm, I would expect the basic `createIPA` gradle task to generate an app that is submittable by default. 64bit and thumbv7 can be enabled in `robovm.xml` by just removing the line that only specifies thumbv7.

All of the errors listed above were errors during the itunesconnect upload, if I have time I will redo the process and paste the exact wording here.

**Comment by badlogic** [comment]
That may be the case re:createIPA. Should modify Gradle template to build
thumb/arm64 by default.

**Comment by ericnondahl** [comment]
Updated issue to pull out the iOS 7 based changes.

**Comment by ericnondahl** [comment]
Pastebin of initial itunes upload errors from sample iOS app: http://pastebin.com/8Us93Dgz

Note the 64 bit errors and the minimum OS Version issue, along with the multitasking support issue.

**Comment by TaiVuong** [comment]
gradle.build
```
robovm {
	archs = "thumbv7:arm64"
}
```

**Comment by badlogic** [comment]
We are now generating a config that creates both the thumbv7 and arm64 slices in the IPA. The minimum version is set by the RoboVM compiler if omitted.
