### ISSUE TITLE
Color.rgb888ToColor erroneously treats incoming color as ARGB instead of RGB.

### ISSUE THREAD

**Issue by ccourtney** [libgdx/libgdx#4199]
#### Issue details
Color.rgb888ToColor erroneously treats incoming color as ARGB instead of RGB.

#### Reproduction steps/code
RGB color is currently treated as ARGB by the masks:
	public static void rgb888ToColor (Color color, int value) {
		color.r = ((value & 0x00ff0000) >>> 16) / 255f;
		color.g = ((value & 0x0000ff00) >>> 8) / 255f;
		color.b = ((value & 0x000000ff)) / 255f;
	}

 Should be instead treated as RGB by the masks:
	public static void rgb888ToColor (Color color, int value) {
		color.r = ((value & 0xff000000) >>> 16) / 255f;
		color.g = ((value & 0x00ff0000) >>> 8) / 255f;
		color.b = ((value & 0x0000ff00)) / 255f;
	}

#### Version of LibGDX and/or relevant dependencies
gdx version 1.9.3

#### Stacktrace
N/A

#### Please select the affected platforms
- [x ] Android
- [x ] iOS (robovm)
- [x ] iOS (MOE)
- [x ] HTML/GWT
- [x ] Windows
- [x ] Linux
- [x ] MacOS

**Comment by Darkyenus** [comment]
It is RGB, but it is assumed to be aligned to the LSB side, which is IMHO more standard.

Btw. you forgot to adjust the bit shifts in your proposed code.

**Comment by ccourtney** [comment]
Yes, I just realized that. Sorry for the confusion!
