### ISSUE TITLE
Hiero creates fnt file without any space delimiting the fields for higher Unicode blocks

### ISSUE THREAD

**Issue by CreamyCookie** [libgdx/libgdx#4202]
#### Issue details
Hiero creates a file where for Unicode characters with high codepoints there's no space delimiting the `ìd` and `x` attribute.  This results in `BitmapFont` not being able to parse the file (results in a `NumberFormatException`).

#### Reproduction steps/code
1. Start Hiero
2. Insert `😀` into the example text field
3. Select font that supports this character (e.g. DejaVu Sans)
4. Export file
5. Load or open file, see that there's no space
6. Search for "128512"

`char id=128512x=704  y=0    width=19   height=19   xoffset=-1   yoffset=-1   xadvance=18   page=0    chnl=0 `

#### Version of LibGDX and/or relevant dependencies
1.9.4-SNAPSHOT

#### Please select the affected platforms
Ubuntu 16.04, very likely all platforms Hiero runs on

#### Quickfix
add spaces between `id=128512` and `x=704`.

**Comment by Tom-Ski** [comment]
Please actually provide the code and resources required to reproduce this issue. Font file and single ApplicationAdapater will be sufficient.

**Comment by CreamyCookie** [comment]
Sure! Here's the font: [DejaVuSans.ttf.zip](https://github.com/libgdx/libgdx/files/381262/DejaVuSans.ttf.zip) You don't need any code to see the the malformed `fnt` file.
