### ISSUE TITLE
New projects don't correctly build when using the gradle task gwtDev.

### ISSUE THREAD

**Issue by juckele** [libgdx/libgdx#4205]
#### Issue details
New projects don't correctly run gwtDev mode from command line with gradle.

#### Reproduction steps/code
1. Create a new project with sub-projects of Desktop and Html.
2. `cd` to the new project folder and run `gradle gwtDev`.
3. gwtDev is unable to resolve the `*.gwt.xml` in the core project.

A repo demoing this bug is available here: https://github.com/juckele/broken-gwt

#### Version of LibGDX and/or relevant dependencies
1.9.3

#### Stacktrace
N/A

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [X] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
You should be using html:superDev rather than gwtDev.

**Comment by juckele** [comment]
Thanks for the heads up. I had thought this worked until recently.
