### ISSUE TITLE
Multiple Texture Atlases in Skin constructor

### ISSUE THREAD

**Issue by ecumene-software** [libgdx/libgdx#4206]
#### Issue details
I'm suggesting that Scene2D have support for multiple Texture Atlases in `Skin`, here's how I think it'll work:

Skin.java
Before:
```
/** Creates a skin containing the resources in the specified skin JSON file. If a file in the same directory with a ".atlas"
 * extension exists, it is loaded as a {@link TextureAtlas} and the texture regions added to the skin. The atlas is
 * automatically disposed when the skin is disposed. */
public Skin (FileHandle skinFile) {
	FileHandle atlasFile = skinFile.sibling(skinFile.nameWithoutExtension() + ".atlas");
	if (atlasFile.exists()) {
		atlas = new TextureAtlas(atlasFile);
		addRegions(atlas);
	}

	load(skinFile);
}

[...]

/** Creates a skin containing the resources in the specified skin JSON file and the texture regions from the specified atlas.
 * The atlas is automatically disposed when the skin is disposed. */
public Skin (FileHandle skinFile, TextureAtlas atlas) {
	this.atlas = atlas;
	addRegions(atlas);
	load(skinFile);
}	
```

After:
- Note I haven't tested this, I'm on the edge that it works...
```
/** Creates a skin containing the resources in the specified skin JSON file. If a file in the same directory with a ".atlas"
 * extension exists, it is loaded as a {@link TextureAtlas} and the texture regions added to the skin. The atlas is
 * automatically disposed when the skin is disposed. */
public Skin (FileHandle skinFile) {
	for(FileHandle sibling : skinFile.parent().list())
            if(sibling.extension().toLowerCase().equals("atlas")) 
                addRegions(new TextureAtlas(sibling));
	load(skinFile);
}

[...]

/** Creates a skin containing the resources in the specified skin JSON file and the texture regions from the specified atlas.
 * The atlas is automatically disposed when the skin is disposed. */
public Skin (FileHandle skinFile, TextureAtlas ... atlases) {
	this.atlas = atlas;
	for(TextureAtlas atlas : atlases) addRegions(atlas);
	load(skinFile);
}	
```

**Comment by Metaphore** [comment]
I'm totally agree that skin should support multiple atlases somehow, but this way we may take even more problems. You see, atlas is not limited with pages, that's what makes it's flexible enough and gives no limitation on packed textures in, so you can extend your skin as long as possible. When you we use multiple atlases like this, we may take name collisions and I don't know how could they be properly solved without explicit reference to region's atlas in skin file (could be something like `image: atlas_name.region_name`. Maybe json should also have all required atlases listed inside.

**Comment by cypherdare** [comment]
Maybe instead of cluttering Skin (already a massive class), add the ability to merge TextureAtlases. It could have a merge method that takes a parameter for how to handle name collisions (omit the regions vs. modify their names). 

This potentially is more versatile. I didn't understand the reason for needing multiple atlases at first, but I can think of one use case. If you have some parts of your skin that are resolution independent, while you have some that need multiple sizes, it might be handy to put them in separate atlases so you never have to load anything whose size is unneeded on the installed device. However, this could cause a lot of batch flushing.

**Comment by metaphore** [comment]
I think the typical case may be when there is some dedicated part of UI that requires a lot of unique images to be drawn and to optimize render you would rather keep them all in same texture, but that's what you usually can't control from TextureAtlas generators, they pack images into pages in random order.

**Comment by cypherdare** [comment]
Seems like a shortcoming of the GUI TexturePackers to me. I've never
encountered one that is as easy to use or provides as much control as
simply placing them in directories with json config files.

**Comment by ecumene-software** [comment]
Just to add onto what @cypherdare said, I wanted this because users may want to change the VisUI theme in my game, and still retain the old skin atlas as well as their own which is another use.

**Comment by metaphore** [comment]
@cypherdare you're right about packers, it's not related to framework limitations.

And I should say that I totally like the idea of customization, like to supply a user with ability to redefine the way image references resolve in skin. I can think of similar example of that as here https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/attachments/AtlasAttachmentLoader.java
This is a bit different, but the idea is the same, to give user ability to customize reference resolution per resource type in own factory class.

**Comment by NathanSweet** [comment]
Create an empty skin with `new Skin()` and populate it with multiple atlases by calling `addRegions(TextureAtlas)` multiple times. The only difference is you will need to dispose the atlases yourself, whereas when using the constructor the skin owns the atlas and disposes it with the skin.
