### ISSUE TITLE
Preferences doesn't support storing or fetching double's

### ISSUE THREAD

**Issue by WickedShell** [libgdx/libgdx#4207]
#### Issue details
Is there any reason that the preferences interface doesn't support double's? (or opposition to adding support for them?)

I might get time to put in a PR for this in a couple of weeks if there is no opposition, but if someone else wants to do it thats fine by me! (I still have to sort out CLA/checkout the source etc)

**Comment by xoppa** [comment]
See: https://developer.android.com/reference/android/content/SharedPreferences.html
Also, please use the forum or irc for questions, see: https://github.com/libgdx/libgdx/wiki/Issue-Tracker

**Comment by MobiDevelop** [comment]
Android's SharedPreferences doesn't support double - would have to convert to a supported type.

Something like:
put: `editor.putLong(key, Double.doubleToLongBits(value));`
get: `Double.longBitsToDouble(prefs.getLong(key, Double.doubleToLongBits(defaultValue)));`
