### ISSUE TITLE
Wrong display size on IOS

### ISSUE THREAD

**Issue by little-dgek** [libgdx/libgdx#4208]
Please ensure you have given all the following requested information in your report.

#### Issue details
On IOS application (RoboVM) I get wrong display size. For example, on IPhone 6 and 5s (OS 9.3) get w=640.0 h=960.0.
But, the other project with same info.plist.xml and robovm.xml work fine.
#### Version of LibGDX and/or relevant dependencies
1.9.3

#### Stacktrace
```java
[debug] IOSApplication: iOS version: 9.3
[debug] IOSApplication: Running in 64-bit mode
[debug] IOSApplication: scale: 2.0
[debug] IOSApplication: Status bar is not visible
[debug] IOSApplication: Total computed bounds are w=640.0 h=960.0
[debug] IOSGraphics: Display: ppi=264, density=1.65
[debug] IOSApplication: created
[debug] IOSApplication: resumed
[debug] IOSApplication: Status bar is not visible
[debug] IOSApplication: Total computed bounds are w=640.0 h=960.0

#### Please select the affected platforms
- [ ] Android
- [*] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Darkyenus** [comment]
Check that you have launch images for iPhone 5s/6 etc., that would be my first guess.

**Comment by little-dgek** [comment]
Oh! Yes! Thank you!
