### ISSUE TITLE
Pixmap default scaling filter and blend mode inconsistency

### ISSUE THREAD

**Issue by serpent7776** [libgdx/libgdx#4214]
#### Issue details
Pixmap scaling filter is initialized to linear and blend mode to source over in [Gdx2DPixmap.java](https://github.com/libgdx/libgdx/blob/1.9.3/gdx/src/com/badlogic/gdx/graphics/g2d/Gdx2DPixmap.java#L84-L85), but [gdx2d.c
](https://github.com/libgdx/libgdx/blob/1.9.3/gdx/jni/gdx2d/gdx2d.c#L20-L21) initializes scaling filter to nearest and blend mode to none.
They should be initialized to same default value.

#### Version of LibGDX and/or relevant dependencies
checked on 1.9.3

#### Please select the affected platforms
- [x] core
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by intrigus** [comment]
> Pixmap scaling filter is initialized to linear and blend mode to source over in Gdx2DPixmap.java, but gdx2d.c
> initializes scaling filter to nearest and blend mode to none.
That's not really correct. Gdx2DPixmap.java initializes scaling and blend mode which changes the scaling and blend mode in gdx2d.c

This means that gdx2d.c may initialize them to 'nearest' and 'none', but whenever you use libgdx they will never have those values.
I don't think that this should be changed since there is no problem and the fix could break code that directly uses gdx2d without libgdx.

**Comment by serpent7776** [comment]
Good to know that behaviour is well defined. Anyway I think it is good idea to at least leave a comment in gdx2d.c stating that these values are overriden by Gdx2DPixmap.java and to make it clear that this is a known fact. Now it's very confusing - makes one think whether it's bug or something.

**Comment by intrigus** [comment]
Feel free to send a PR.

**Comment by MobiDevelop** [comment]
Why does someone looking at `gdx2d.c` need to know (or care) that `Gdx2DPixmap.java` sets them to different values? Putting comments in code about how some consumer of that code uses it at a particular point in time isn't helpful. If `Gdx2DPixmap.java` were to change its defaults, someone would have to remember to go update the comment (if they even knew it was there).

As for the default values... I think it is perfectly acceptable that they do not have the same defaults.

**Comment by serpent7776** [comment]
> Why does someone looking at gdx2d.c need to know (or care) that Gdx2DPixmap.java sets them to different values? Putting comments in code about how some consumer of that code uses it at a particular point in time isn't helpful. If Gdx2DPixmap.java were to change its defaults, someone would have to remember to go update the comment (if they even knew it was there).

Yeah, you have a point, Maybe it was just me confused about static initialization of java/c code.
