### ISSUE TITLE
Missing OpenGL ES 3.0 functions

### ISSUE THREAD

**Issue by spamrakuen** [libgdx/libgdx#4224]
#### Issue details

Some OpenGL ES 3.0 functions are missing
#### Reproduction steps/code

file: libgdx\backends\gdx-backend-android\src\com\badlogic\gdx\backends\android\AndroidGL30.java
example of missing function:
// @Override
// public long glFenceSync(int condition, int flags) {
// return GLES30.glFenceSync(condition, flags);
// }
There are more commented functions like this one.

Also in this other file:
libgdx\gdx\src\com\badlogic\gdx\graphics\GL30.java
#### Version of LibGDX and/or relevant dependencies

last one
#### Please select the affected platforms
- [x] Android
- [?] iOS (robovm)
- [?] iOS (MOE)
- [?] HTML/GWT
- [x] Windows
- [?] Linux
- [?] MacOS

**Comment by spamrakuen** [comment]
I was able to fix this by myself. Details here:
http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=23147

**Comment by badlogic** [comment]
Could you send a PR with your changes? Thanks!
