### ISSUE TITLE
Label setFontScale(1) doesn't set the BitmapFont scale to 1

### ISSUE THREAD

**Issue by obigu** [libgdx/libgdx#4232]
#### Issue details
Label setFontScale(int scale) doesn't work when the argument is 1. The Label font scaling implementation makes the assumption that the underlying BitmapFont scale is set to 1 so that if the Label fontScaleX and fontScaleY are set to 1, there's no need to set the scale on the underlying BitmapFont.

That assumption is wrong as there are use cases in which it is useful to set the BitmapFont common scale to a value different than 1 and the use the specific Label's fontScale to scale each text.

Instead of comparing to 1, the implementation should compare the Label fontScaleX and fontScaleY with the BitmapFont scaleX and scaleY or, alternatively, keep a flag "fontScaleChanged" to be set to true if fontScale is modified and then use it to check if there's a need to change the BitmapFont's scale.

I will provide a PR when I get the chance. As a simple workaround in the meantime you can use setFontScale(0.9999f) instead.

#### Reproduction steps/code

SSCCE
http://pastebin.com/rsF6GDu2

#### Version of LibGDX and/or relevant dependencies
1.9.3

#### Please select the affected platforms
- [x] Android
- [x] iOS (robovm)
- [x] iOS (MOE)
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by domdomdom** [comment]
This forces users to set a font scale on a label(as it will always be set to 1 otherwise, ignoring the bitmap font scale). 

Could an improvement to this fix be to scale the value to bitmapfont scale * label scale?

IE:

`if (fontScaleX != oldScaleX || fontScaleY != oldScaleY) font.getData().setScale(fontScaleX*oldScaleX, fontScaleY*oldScaleY);`

This would keep existing behavior of allowing the whole font to scale, and keep the resetting the value when !=1.

**Comment by obigu** [comment]
You are right that #4233 has the problem of making the BitmapFont scale useless when using Labels.

I believe your suggested solution doesn't work either. Imagine you have a BitmapFont scale set to 0.5 and then want Label to be half that size (that is 0.5 * 0.5  = 0.25 total). To do that you'd need to set the Label fontScale to 0.5 as well and the condition would not be triggered.

The best solution I can think is to add a "fontScaleChanged" or "forceBitmapFontScale" flag in Label to be set to true when the Label fontScaleX or fontScaleY are explicitely modified. I won't be able to provide a PR until next week though.

**Comment by domdomdom** [comment]
Good point. Ideally I think the label scale should be a multiplier of the font scale, rather than setting it. That way for the example above, if your font scale is 2, then your label scale should be 0.5 to get a final scaled of 1. This would be a larger behavior change though.

**Comment by domdomdom** [comment]
Is there any way to reopen this? As it looks like it made it into 1.9.4. If this is expected/correct behavior now then I'll just change my local copy.

**Comment by obigu** [comment]
See #4270
