### ISSUE TITLE
IOS Landscape LaunchImage

### ISSUE THREAD

**Issue by ACrsm** [libgdx/libgdx#4235]
I create an Landscape Game by libgdx 1.9.3.
The gdx-setup example launch image is portrait, so I change all the launch image to Landscape
for example:
Default-Landscape-568h@2x.png  is 1334x640.
Default-Landscape.png  is 480x320
.......

When I use Application Loader to upload ipa, 

ERROR ITMS-90096: "Your binary is not optimized for iPhone 5 - New iPhone apps and app updates submitted must support the 4-inch display on iPhone 5 and must include a launch image referenced in the Info.plist under UILaunchImages with a UILaunchImageSize value set to {320, 568}. Launch images must be PNG files and located at the top-level of your bundle, or provided within each .lproj folder if you localize your launch images. Learn more about iPhone 5 support and app launch images by reviewing the 'iOS Human Interface Guidelines' at 'https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/IconsImages/IconsImages.html#//apple_ref/doc/uid/TP40006556-CH14-SW5' and the 'iOS App Programming Guide' at 'https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/App-RelatedResources/App-RelatedResources.html#//apple_ref/doc/uid/TP40007072-CH6-SW12'."

Thanks!

**Comment by ACrsm** [comment]
OK, I have solved this by  add Default-568h@2x.png with 640x1136.
But I do not know why I should have  two files:
Default-Landscape-568h@2x.png with 1334x640.
Default-568h@2x.png with 640x1136

My Game is Landscape!

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
