### ISSUE TITLE
Controller API Lwjgl3 Not Detecting POV Movement (DPAD)

### ISSUE THREAD

**Issue by fatalcubez** [libgdx/libgdx#4241]
Right now I have my application setup to use the new lwjgl3 backend and the events for connecting and disconnecting a controller work (unlike before), but now the `povMoved` event never fires when I'm pressing on the DPAD. 

Also, I know that some events are working because the event for `axisMoved` is being triggered when I move one of the analog sticks and `buttonDown` is being triggered when any of the buttons are being hit.

Additional Info:
- Controller: Xbox One Controller
- OS: Windows 8.1 x64
- LWJGL 3 backend (and all associated Gradle dependencies needed for the Controllers extension)

EDIT:
After looking through the actual `Lwjgl3ControllerManager` class it looks like there is no event in place to handle the DPAD. The events are `connected`, `disconnected`, `axisChanged`, and `buttonChanged`. Is this going to be added?

**Comment by CreamyCookie** [comment]
Doesn't the DPAD trigger axis events for you? It did for me. However I'm on Ubuntu (Linux).

**Comment by fatalcubez** [comment]
No the DPAD only triggered `povMoved` events before and is not triggering axis events now.

**Comment by CreamyCookie** [comment]
Regarding only having `axisChanged` and `buttonChanged`, I think this is intended as seemingly hats are either reported as buttons or as axes: https://github.com/glfw/glfw/issues/278

**Comment by badlogic** [comment]
As long as GLFW doesn't provide a better gamepad API, there's nothing we can do I'm afraid.
