### ISSUE TITLE
VerticalGroup alignment issues

### ISSUE THREAD

**Issue by obigu** [libgdx/libgdx#4243]
#### Issue details

VerticalGroup always aligns its elements to **center** independently of the alignment setting. Seems related to https://github.com/libgdx/libgdx/commit/3840e4eea50482409972fc78a60e1deb69a59250.

In addition to adding wrapping, at least VerticalGroup behaviour is different than it was on earlier libGDX versions (with wrap set to false). I use VerticalGroup/HorizontalGroup as a lightweight containers for displaying elements in a column/row that auto-sizes with the inserted elements. Now setSize() seems to be required,  if this is intended behaviour it should probably be added to the CHANGES because it breaks existing UIs that make use of them.
#### Reproduction steps/code

SSCCE
http://pastebin.com/JWiHkHwk
#### Version of LibGDX and/or relevant dependencies

1.9.4-SNAPSHOT
#### Please select the affected platforms
- [x] Android
- [x] iOS (robovm)
- [x] iOS (MOE)
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by 1nt3g3r** [comment]
Looked your code on PasteBin, and mentioned that you call only stage.draw(), but you didn't call stage.act(). I think it's trouble (stage.act() method should be called before draw())

**Comment by obigu** [comment]
Thanks, edited. It didn't matter in this case, behavior is the same but you're right it should be there.

**Comment by Teiby1** [comment]
Same here. Downgrade to 1.9.3 fixed that problem.

**Comment by langurmonkey** [comment]
Can confirm, downgrading fixed it.

**Comment by NathanSweet** [comment]
Sorry it took so long for me to get to fixing this!

When VerticalGroup and HorizontalGroup were refactored, it was a pretty big change with some API breakage. They are much more powerful so I hope you find the minor breakage (at least when it's working correctly) worthwhile.

Note there is now 2 settings for alignment. align/top/left/bottom/right are for aligning ALL the actors within the group. columnAlign/columnLeft/columnRight/columnCenter for VerticalGroup and rowAlign/rowTop/rowBottom/rowCenter for HorizontalGroup are for aligning the actors within the row or column. When wrapping is not used, there is only 1 row or column. See GroupTest for an example.

**Comment by phunni** [comment]
So, which version contains the fix?

**Comment by mikemee** [comment]
> VerticalGroup always aligns its elements to center independently of the alignment setting. 

In case someone else notices this and is looking for the quick fix.  For my code, _YMMV!_, I was able to replace:
```java
	private final VerticalGroup stack = new VerticalGroup();
        ....
        // add rows of horizontalGroups to the stack
        ....
        stack.align(align);
```
with
```
	private final VerticalGroup stack = new VerticalGroup();
        ....
        stack.columnAlign(align);
```
And then all was right with the world again.
