### ISSUE TITLE
setFlip(boolean X, boolean Y) dosent affect ParticulesEfct but flipY() does 

### ISSUE THREAD

**Issue by Pugli123** [libgdx/libgdx#4244]
ParticulesEffect is inside an actor 

`public class ParticleEffectActor extends Actor {
    ParticleEffect effect;
    public ParticleEffectActor(ParticleEffect particleEmitter) {
        super();
        this.effect = particleEmitter;
    }
    public void draw(Batch batch, float parentAlpha) {

```
    effect.update(Gdx.graphics.getDeltaTime());
    effect.draw(batch);
}
public ParticleEffect getPartticleEffct(){
    return effect;
}
```

}`

then here goes the pertinent code

`
 shellActor.getPartticleEffct().getEmitters().first().getEmission().setLow(50);
        shellActor.getPartticleEffct().start();
        **shellActor.getPartticleEffct().setFlip(true,false);**`

.setFlip() dont work in any combination but instead flipY() fliip it verticaly.

**Comment by MobiDevelop** [comment]
The `setFlip` method is flipping the particle sprites (for particles which have already been emitted and future particles). The `flipY` flips the actual emitter values by negating the `angle`, `gravity`, `wind`, `rotation`, and `yOffset`.

They appear to server very different purposes so it is probably a documentation issue.

Maybe @NathanSweet can comment on the very different behavior of these similarly named methods and come up with some documentation (of which the ParticleEmitter class has effectively none).

**Comment by Pugli123** [comment]
yes, it would be really coll cos this is the onli information for the method in the api 

> public void setFlip(boolean flipX,
                    boolean flipY)

also would be cool to add a flipX() to emmiters

>  private void flipEmmitersX(){


        emmiter.getAngle().setHigh(emmiter.getAngle().getHighMin(),emmiter.getAngle().getHighMax());
        emmiter.getAngle().setLow(emmiter.getAngle().getLowMin(),emmiter.getAngle().getLowMax());

        emmiter.getGravity().setHigh(emmiter.getGravity().getHighMin(),emmiter.getGravity().getHighMax());
        emmiter.getGravity().setLow(emmiter.getGravity().getLowMin(),emmiter.getGravity().getLowMax());

        emmiter.getWind().setHigh(-emmiter.getWind().getHighMin(),-emmiter.getWind().getHighMax());
        emmiter.getWind().setLow(-emmiter.getWind().getLowMin(),-emmiter.getWind().getLowMax());

        emmiter.getRotation().setHigh(-emmiter.getRotation().getHighMin(),-emmiter.getRotation().getHighMax());
        emmiter.getRotation().setLow(-emmiter.getRotation().getLowMin(),-emmiter.getRotation().getLowMax());

        emmiter.getYOffsetValue().setLow(emmiter.getYOffsetValue().getLowMin(),emmiter.getYOffsetValue().getLowMax());

        emmiter.getXOffsetValue().setLow(emmiter.getXOffsetValue().getLowMin(),emmiter.getXOffsetValue().getLowMax());

    }

thanks for the help

**Comment by NathanSweet** [comment]
I don't remember. Honestly, I haven't used the 2D particle stuff in years. There are parts in there others have contributed that aren't recognizable to me at all, like `setCleansUpBlendFunction`. PRs to improve documentation is welcome.
