### ISSUE TITLE
Feature for Scene2D: ImmutableList

### ISSUE THREAD

**Issue by RaimundWege** [libgdx/libgdx#4246]
I want to show a list of entities from a specific entity family. The entities are all placed in an immutable array and I can't set this array directly as datasource for the list. To refresh the list I only could remove all entities and add them again. An ImmutableList would be nice.

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info

**Comment by RaimundWege** [comment]
Whooops. I accept your argument. Its even to specific because it would mix up Scene2D and ashley. I've realized that the immutable list comes from ashley and is not in the main part of libGDX. From now on I will use the Scene2D list and update it only all 5 seconds with an interval system.
