### ISSUE TITLE
Requesting details or documentation about adding images to android game so that their size will adjust according to screen size

### ISSUE THREAD

**Issue by cdwijayarathna** [libgdx/libgdx#4253]
#### Issue details
I am creating an android game using libgdx and I use some images in some of the windows. I am placing my images in the window like following.

 ```
           screenWidth = Gdx.graphics.getWidth();
           screenHeight = Gdx.graphics.getHeight(); 
           batch.draw(playImage, screenWidth / 2 - texture.getWidth() / 2, screenHeight / 4 - texture
                    .getHeight() / 2);
            font.draw(batch, message, screenWidth / 2 - layout.width / 2, 5 * screenHeight / 8 -
                    layout.height / 2);
```

Will this give any issues when I use a different screen size? If so how should I handle this kind of scenario? Is there any documentation or tutorial on how to do this?

#### Please select the affected platforms
- [x ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
Please use the forums or the irc channel. https://github.com/libgdx/libgdx/wiki/Issue-Tracker
