### ISSUE TITLE
font.getData().setScale() not work

### ISSUE THREAD

**Issue by kongbt** [libgdx/libgdx#4254]
When i upgade libgdx to new version 1.9.4 and i build my project on android studio with MOE

i can't set scale font for Lable.
Pls help me.

#### Version of LibGDX and/or relevant dependencies
1.9.4

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [x ] Android
- [ ] iOS (robovm)
- [ x] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
If you need help please use the forum or the irc channel, this is an issue tracker. https://github.com/libgdx/libgdx/wiki/Issue-Tracker
