### ISSUE TITLE
ShapeRenderer#line(float, float, float, float, Color, Color) doesn't apply colors when shapeType is Filled

### ISSUE THREAD

**Issue by prineside** [libgdx/libgdx#4255]
#### Issue details

Description for [ShapeRenderer#line(float x, float y, float z, float x2, float y2, float z2, Color c1, Color c2)](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/graphics/glutils/ShapeRenderer.html#line-float-float-float-float-float-float-com.badlogic.gdx.graphics.Color-com.badlogic.gdx.graphics.Color-) says _"Draws a line using ShapeRenderer.ShapeType.Line or ShapeRenderer.ShapeType.Filled. The line is drawn with two colors interpolated between the start and end points."_, but in fact color args are ignored with ShapeType.Filled:

``` java
public void line (float x, float y, float z, float x2, float y2, float z2, Color c1, Color c2) {
    if (shapeType == ShapeType.Filled) {
        rectLine(x, y, x2, y2, defaultRectLineWidth);
        return;
    }
    // ...
}
```

Maybe this method should throw an exception if used with ShapeType.Filled saying "use rectLine instead" or have a different description in docs (this method works, but not as expected)
#### Reproduction steps/code

``` java
ShapeRenderer shapeRenderer = new ShapeRenderer();
shapeRenderer.begin(ShapeRenderer.ShapeType.Filled);
shapeRenderer.line(5f, 5f, 10f, 10f, Color.RED, Color.GREEN);
shapeRenderer.end();
```
#### Version of LibGDX and/or relevant dependencies

1.9.3

**Comment by badlogic** [comment]
I've added a new `rectLine` method that takes a color for each line end point. This method is now called from `line` when the shape type is set to filled.
