### ISSUE TITLE
Sound panning should work for stereo files (and if not, add it to the docs)

### ISSUE THREAD

**Issue by CreamyCookie** [libgdx/libgdx#4256]
#### Issue details

Pan doesn't work on Stereo files. If this can't be supported for some reason, it should at least be mentioned in the documentation of `Sound`.
#### Reproduction steps/code

Code taken from #2560:

``` java
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.Input;
import com.badlogic.gdx.InputAdapter;
import com.badlogic.gdx.audio.Sound;

public class LibGdxScratchpad extends ApplicationAdapter {

    private Sound sound;

    @Override
    public void create() {

        sound = Gdx.audio.newSound(Gdx.files.internal("test.wav"));

        Gdx.input.setInputProcessor(new InputAdapter() {
            @Override
            public boolean keyDown(int keyCode) {
                if (keyCode == Input.Keys.LEFT) {
                    sound.play(1.0f, 1.0f, -1.0f);
                } else if (keyCode == Input.Keys.RIGHT) {
                    sound.play(1.0f, 1.0f, 1.0f);
                }
                return true;
            }
        });
    }
}
```
#### Version of LibGDX and/or relevant dependencies

1.9.4-SNAPSHOT
#### Please select the affected platforms

Tested on Ubuntu 16.04 (Linux), likely all

**Comment by CreamyCookie** [comment]
@badlogic Thanks! How hard would it be to make it work for stereo files?

**Comment by badlogic** [comment]
We'd have to hack OpenAL soft to support spatial stereo mixing. Or split
stereo sounds up into two mono sources and manually manage both of their
positions.
