### ISSUE TITLE
Unicode font not rendering properly

### ISSUE THREAD

**Issue by chandujr** [libgdx/libgdx#4258]
#### Issue details

I'm using an Indian font ([Malayalam](https://en.wikipedia.org/wiki/Malayalam_script), specifically) in my app. I used `FreeTypeFontGenerator` to generate `BitmapFont` that I use in Actors. But the text is not displayed correctly in the app. For example, take a look at the below screenshots:

---

![unicode_non_font_shot1](https://cloud.githubusercontent.com/assets/14921501/17801597/afe44c6e-6608-11e6-8f8a-0033b1a47e66.PNG)
_Image 1_

![unicode_font_shot1](https://cloud.githubusercontent.com/assets/14921501/17801615/c7154726-6608-11e6-8489-a835dfafa650.PNG)
_Image 2_

---

The text should be displayed as seen in the 1st image. But what I'm getting is the 2nd image. One particular character is split into it's component elements where it should be combined automatically. There are other similar characters in this language that shows this property. I actually don't know the technical thing going on behind this conversion. In many situations, the conversion is done automatically (e.g., in Character Map in Windows, see below). The 1st image is got by using a non-unicode font which has all characters ready-made. In both the cases, I had to supply all the characters to the `FreeTypeFontGenerator` using `FreeTypeFontParameter`.

---

![unicode_conv](https://cloud.githubusercontent.com/assets/14921501/17802071/90e083ac-660b-11e6-9d36-3c67022d4e1c.gif)
_Note the character conversion._

---
#### Reproduction steps/code

Please download this project and run in Desktop module.
[UnicodeBugReportProject.zip](https://github.com/libgdx/libgdx/files/426526/UnicodeBugReportProject.zip)
#### Version of LibGDX and/or relevant dependencies

```
appName = "UnicodeBugReportProject"
gdxVersion = '1.9.3'
roboVMVersion = '2.1.0'
box2DLightsVersion = '1.4'
ashleyVersion = '1.7.0'
aiVersion = '1.8.0'
```
#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by MarcinSc** [comment]
Judging by the fact that the rendering of characters is done from an image file with all the characters, I don't think it will be doable to achieve composite characters.

**Comment by chandujr** [comment]
Oh, I see. Is there a way to display composite characters? There may be other languages that have them. LibGDX may already support them.

**Comment by Darkyenus** [comment]
AFAIK this issue is much more complicated than it seems and would probably require integration of a 3rd party project such as Harfbuzz, along with rewriting font rendering/rasterization pipeline.

**Comment by chandujr** [comment]
Okay. Thanks for that info.

**Comment by NathanSweet** [comment]
GlyphLayout was added with the hope of one day using Harfbuzz or similar to support more complex layout, but that day has not come.

**Comment by aslamca** [comment]
Use ANSI fonts and type the text in ANSI format instead of unicodes. You will be able to display the text. I suggest software baraha to write Indian languages in ANSI format.
