### ISSUE TITLE
Scene2d label font rendering bug makes it faded unexpectedly?

### ISSUE THREAD

**Issue by vedi0boy** [libgdx/libgdx#4259]
#### Issue details
I am working on a game and I am implementing a menu system. I created a class that extends Window and I have added buttons and things to it. My issue is that for some reason, it randomly fades the font used to render the text on text buttons, labels and window title (textfields are unaffected for some reason). Sometimes it is half faded and some times it is fully faded and you can't see the text at all, just the element.

Also, if it wasn't already fully faded the first time, it completely fades the second time I open the menu. And if I go back to the main menu, the fonts get messed up their too even though they were fine when I loaded up the main menu to play the game.

Could there be a bug with the font rendering? I tested everything. I don't change the color of the font or the batch and it still does this.

Here are 2 images to show what happens: http://imgur.com/a/FB82i

Here is my project: https://github.com/vedi0boy/Archipelo/. The classes that would be of concern are in the core under src at "screen/GameScreen.java" (renderUi is where I call stage.draw()) and "screen/gamescreen/MainMenuWindow.java" and as you can see (it also happens in "screen/gamescreen/MainMenuWindow.java"), I don't ever set the font color. It happens on it's own. I do change the batch color in other classes but if this was the issue, wouldn't the whole stage be affected, not just the font?

Thanks in advance!

#### Reproduction steps/code
I simply open the window and it does this.

#### Version of LibGDX and/or relevant dependencies
v1.9.3 and I don't use any other ui related dependencies. Just networking stuff.

#### Stacktrace
Visual bug, no stacktrace.

#### Please select the affected platforms
- [x ] Windows (I have only tested windows so far)

**Comment by obigu** [comment]
You should close this issue if you've found it's not a libGDX bug (http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=22833).
