### ISSUE TITLE
Suggestion: Add support for sharing depth and/or stencil buffers between FrameBuffer

### ISSUE THREAD

**Issue by MarcinSc** [libgdx/libgdx#4260]
At the moment a lot of direct OpenGL calls have to be made to share depth/stencil buffers between FrameBuffers. It would be nice to have a method like:

    GLFrameBuffer::attachExternalBuffersFrom(GLFrameBuffer sourceFrameBuffer, boolean depthBuffer, boolean stencilBuffer)
    GLFrameBuffer::detachExternalBuffers(boolean depthBuffer, boolean stencilBuffer);

Of course sanity check should be made, that this buffer doesn't have these attachments already. Also, it should not manage the buffers itself, as they are "owned" by the sourceFrameBuffer.

**Comment by intrigus** [comment]
I don't think that this functionality should be added to libgdx since there are simply to many "nice methods".
You can always create your own utility classes, which hides the gl calls.

**Comment by Tom-Ski** [comment]
Agree with @intringus, although an IDEA to think about with the FBO builder interface.
