### ISSUE TITLE
Setup app not fully updated to 1.9.4

### ISSUE THREAD

**Issue by Fringale** [libgdx/libgdx#4269]
#### Issue details
I just downloaded the setup app from the usual location, and the build.gradle file generated at the root still refers to libGDX 1.9.3 and RoboVM 2.1.0, instead of 1.9.4 / 2.2.0. What’s weird is that other stuff specific to 1.9.4 seems to be in (like this commit: https://github.com/libgdx/libgdx/commit/9e88159b4fb98c1991fc8df49d0c236e8749ff7a) - but not version changes made in DependencyBank.

#### Reproduction steps/code
Download the setup app from https://libgdx.badlogicgames.com/download.html, create a new libGDX project, and check the value of `gdxVersion` and `roboVMVersion` in the root build.gradle.

#### Version of LibGDX and/or relevant dependencies
Current setup app as of 24/08/2016

#### Stacktrace
N/A

#### Please select the affected platforms
N/A

**Comment by Tom-Ski** [comment]
Try downloading again, should be fixed now.

**Comment by Fringale** [comment]
Yup, thanks for the quick rebuild.  : )
