### ISSUE TITLE
Quaternion getYaw() less accurate

### ISSUE THREAD

**Issue by ACrsm** [libgdx/libgdx#4271]
Please ensure you have given all the following requested information in your report.

#### Issue details
Quaternion rotation = new Quaternion();
rotation.setEulerAngles(-128, 0, 0);
System.out.println(rotation.getYaw());

output:
-128.23029

I also test on Unity, the output is 232.00000 (360 - 128).

#### Version of LibGDX and/or relevant dependencies
1.9.3

**Comment by intrigus** [comment]
Please try the latest libgdx version. It has been fixed iirc.

**Comment by ACrsm** [comment]
1.9.4 also output -128.23029

**Comment by Tom-Ski** [comment]
We use faster approximations for trig functions, you can keep track of the 'actual' yaw yourself in a variable, or perhaps use your own implementation to get a yaw at the expense of cpu.  Why is it you need something more accurate?
