### ISSUE TITLE
Description in Setting up Development Environment

### ISSUE THREAD

**Issue by domdobis** [libgdx/libgdx#4276]
Please ensure you have given all the following requested information in your report.

#### Issue details
_Please provide the details of your issue_

The issue is in the description of Setting up the RoboVM for iOS development, specifically the IntelliJ section of it.  The CMD+; doesn't go to Plugins. In order, to go to the Plugins open IntelliJ window and click the configure button on the bottom right hand corner.

#### Reproduction steps/code
_Even if you think your issue is trivial to reproduce, please supply a [SSCCE](http://sscce.org/) that demonstrates your issue.  This saves time on our end, and makes it much more likely that your issue will be fixed.
You can find barebones templates [here](https://github.com/libgdx/libgdx/wiki/Getting-help)_

#### Version of LibGDX and/or relevant dependencies
_Please provide the version(s) affected._

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
The wiki is publicly editable, feel free to update that article with your findings.
