### ISSUE TITLE
Running Demos issue on Android Studio Gradle Build

### ISSUE THREAD

**Issue by mliitfall** [libgdx/libgdx#4283]
Hi, im new to libgdx and just trying the demo from https://github.com/libgdx/libgdx/wiki/Running-Demos
But the problem is when its imported to android studio, it stuck at "Building Gradle project info..".
Anyone had this problem before? Any soluion for this? Thanks in advance

**Comment by Tom-Ski** [comment]
You have a thread open for this question on the forum which is the correct place for a question like this. This is an issue tracker.
