### ISSUE TITLE
GlyphLayout setText has a bug

### ISSUE THREAD

**Issue by moreJoying** [libgdx/libgdx#4284]
gdx version 1.9.4
my code :

		BitmapFont font = new UiBitmapFont(Gdx.files.internal("text.fnt"));
		font.getData().markupEnabled = true;

		Label label = new Label("aaaaa[#ffffff]bbbbb", new LabelStyle(font, Color.WHITE));
		label.setAlignment(Align.center);
		label.setWrap(true);
		label.setSize(200, 200);
		label.debug();
		label.moveBy(100, 100);
		stage.addActor(label);

problem :

		“aaaaa” align center but “bbbbb” align left
		because of “bbbbb” behind [#ffffff]

**Comment by Tom-Ski** [comment]
Please use the template provided, it is there for a reason.
