### ISSUE TITLE
Broken links in wiki

### ISSUE THREAD

**Issue by moonwolf-github** [libgdx/libgdx#4285]
There are several links to images in https://github.com/libgdx/libgdx/wiki/Mesh,-color-&-texture all directing to http://libgdx.googlecode.com/svn/wiki/img/... - which gives 404 error. Unfortunately i didn't found those images on github so i'm unable to correct links.

Also in **Conclusion** there are links directing to http://code.google.com which is wrong i suppose.

**Comment by Scellow** [comment]
I reuploaded the images on imgur, so you should now be able to see the images

Luckily there was a snapshot of the repo on web archive :p

**Comment by moonwolf-github** [comment]
Looks OK now (:)
