### ISSUE TITLE
TexturePacker stripWhitespaceY offset is from bottom instead of top

### ISSUE THREAD

**Issue by IBwWG** [libgdx/libgdx#4288]
Please ensure you have given all the following requested information in your report.
#### Issue details

The .atlas file output where stripWhitespaceY is enabled has the offset output from the bottom-left instead of the top-left.
#### Reproduction steps/code

Pack an image that's vertically off-centre such as:

![0006](https://cloud.githubusercontent.com/assets/16719964/18158296/bb210f62-7022-11e6-9a18-81142a259bb9.png)

...with these settings in your pack.json:

``` json
{
    pot: true,
    paddingX: 2,
    paddingY: 2,
    bleed: true,
    edgePadding: true,
    duplicatePadding: false,
    rotation: true,
    minWidth: 16,
    minHeight: 16,
    maxWidth: 4096,
    maxHeight: 4096,
    square: false,
    stripWhitespaceX: true,
    stripWhitespaceY: true,
    alphaThreshold: 0,
    filterMin: Nearest,
    filterMag: Nearest,
    wrapX: ClampToEdge,
    wrapY: ClampToEdge,
    format: RGBA8888,
    alias: true,
    outputFormat: png,
    jpegQuality: 0.9,
    ignoreBlankImages: true,
    fast: false,
    debug: false,
    combineSubdirectories: true,
    flattenPaths: false,
    premultiplyAlpha: false,
    useIndexes: true,
    limitMemory: false,
    grid: false,
    scale: [ 1 ],
    scaleSuffix: [ "" ]
}
```

The output for that frame contains:

```
  size: 242, 405
  orig: 480, 700
  offset: 142, 53
```

The X part of the offset is correct, but the Y part is the distance from the bottom, rather than the top.
#### Version of LibGDX and/or relevant dependencies

Nightly download of standalone tool from yesterday.
#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by NathanSweet** [comment]
AtlasRegion#offsetY javadoc says, "The offset from the bottom of the original image to the bottom of the packed image, after whitespace was removed for packing." Where does the assumption come from that the offset should be from the top?
