### ISSUE TITLE
LibGdx Compilation Error in Android Studio

### ISSUE THREAD

**Issue by HarrySuppal** [libgdx/libgdx#4290]
I am creating my first LibGDX demo project - FlappyBird and following @BrentAureli tutorials on this.

For reproducing the issue please follow this link, as I have done exactly what is listed here:
https://github.com/MobiDevelop/robovm/issues/13

To resolve the issue, I followed this thread:
https://github.com/libgdx/libgdx/issues/4091

I have also posted the question, screenshot, fixes and further problem in StackOverflow:
http://stackoverflow.com/questions/39263386/libgdx-project-modules-edit-configurations-in-android-studio

After doing all the changes in the above thread, I am still getting below error:

If my Gradle is in offline mode, I am getting this error:
```
Error:A problem occurred configuring root project 'FlappyBird'.

> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.mobidevelop.robovm:robovm-gradle-plugin:2.2.0-SNAPSHOT.
     Required by:
         :FlappyBird:unspecified
      > No cached version of com.mobidevelop.robovm:robovm-gradle-plugin:2.2.0-SNAPSHOT available for offline mode.
      > No cached version of com.mobidevelop.robovm:robovm-gradle-plugin:2.2.0-SNAPSHOT available for offline mode.
```

If I put my Gradle in Online mode, I am getting this error:

```
Error:A problem occurred configuring root project 'FlappyBird'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find com.mobidevelop.robovm:robovm-gradle-plugin:2.2.0-SNAPSHOT.
     Searched in the following locations:
         file:/D:/ANDROID_STUDIO_IDE/gradle/m2repository/com/mobidevelop/robovm/robovm-gradle-plugin/2.2.0-SNAPSHOT/maven-metadata.xml
         file:/D:/ANDROID_STUDIO_IDE/gradle/m2repository/com/mobidevelop/robovm/robovm-gradle-plugin/2.2.0-SNAPSHOT/robovm-gradle-plugin-2.2.0-SNAPSHOT.pom
         file:/D:/ANDROID_STUDIO_IDE/gradle/m2repository/com/mobidevelop/robovm/robovm-gradle-plugin/2.2.0-SNAPSHOT/robovm-gradle-plugin-2.2.0-SNAPSHOT.jar
         file:/C:/Users/Harry Suppal/.m2/repository/com/mobidevelop/robovm/robovm-gradle-plugin/2.2.0-SNAPSHOT/maven-metadata.xml
         file:/C:/Users/Harry Suppal/.m2/repository/com/mobidevelop/robovm/robovm-gradle-plugin/2.2.0-SNAPSHOT/robovm-gradle-plugin-2.2.0-SNAPSHOT.pom
         file:/C:/Users/Harry Suppal/.m2/repository/com/mobidevelop/robovm/robovm-gradle-plugin/2.2.0-SNAPSHOT/robovm-gradle-plugin-2.2.0-SNAPSHOT.jar
         https://repo1.maven.org/maven2/com/mobidevelop/robovm/robovm-gradle-plugin/2.2.0-SNAPSHOT/maven-metadata.xml
         https://repo1.maven.org/maven2/com/mobidevelop/robovm/robovm-gradle-plugin/2.2.0-SNAPSHOT/robovm-gradle-plugin-2.2.0-SNAPSHOT.pom
         https://repo1.maven.org/maven2/com/mobidevelop/robovm/robovm-gradle-plugin/2.2.0-SNAPSHOT/robovm-gradle-plugin-2.2.0-SNAPSHOT.jar
         https://oss.sonatype.org/content/repositories/snapshots/com/mobidevelop/robovm/robovm-gradle-plugin/2.2.0-SNAPSHOT/maven-metadata.xml
         https://oss.sonatype.org/content/repositories/snapshots/com/mobidevelop/robovm/robovm-gradle-plugin/2.2.0-SNAPSHOT/robovm-gradle-plugin-2.2.0-SNAPSHOT.pom
         https://oss.sonatype.org/content/repositories/snapshots/com/mobidevelop/robovm/robovm-gradle-plugin/2.2.0-SNAPSHOT/robovm-gradle-plugin-2.2.0-SNAPSHOT.jar
     Required by:
         :FlappyBird:unspecified
```

For the folders on my system, the compiler is not able to find "mobidevelop" folder in my IDE folder because there isn't any such folder there. But why the online links are not working?!

Is there any way I can download or upgrade the gradle to incorporate the 'mobidevelop' folder so that the project gets compiled in offline mode?

Furthermore, I am also not able to find the LibGdx sub-modules while creating the EditConfigurations for Desktop application - Please guide in this as well. 

#### Version of LibGDX and/or relevant dependencies
Android Studio Version - 2.1.2

#### Please select the affected platforms
Working on Windows 8

Creating LibGDX project for Android, iOS and Desktop

**Comment by Tom-Ski** [comment]
This question is better suited to the forum, this is an issue tracker. You should be using RoboVM 2.2.0, not 2.2.0-SNAPSHOT now.
