### ISSUE TITLE
Small pixmaps (8*8) or less cant be transparent cursors

### ISSUE THREAD

**Issue by ThomasWrobel** [libgdx/libgdx#4292]
Please ensure you have given all the following requested information in your report.
#### Issue details

When attempting to make a completely transparent cursor (to effectively hide the system default), I noticed it comes out black unless the size is over 8*8.
#### Reproduction steps/code

```
Pixmap pm = new Pixmap(8,8,Format.RGBA8888); 
Pixmap.setBlending(Pixmap.Blending.None); 
pm.setColor(Color.CLEAR);
pm.fillRectangle(0, 0, 8, 8);  
Gdx.graphics.setCursor(Gdx.graphics.newCursor(pm, 0, 0));
```
#### Barebones desktop application;

```
public class Barebones extends ApplicationAdapter {

    public void create () {

        //set cursor transparent test
        Pixmap pm = new Pixmap(8,8,Format.RGBA8888); //16x16 works.  8x8 does not.
        Pixmap.setBlending(Pixmap.Blending.None); //ensure when we draw transparent we REPLACE the pixels with a transparent color.
        pm.setColor(0f,0f,0f,0f);
        pm.fillRectangle(0, 0, 8, 8); //16x16 works.  8x8 does not.
        Gdx.graphics.setCursor(Gdx.graphics.newCursor(pm, 0, 0));
        //--------------------------
    }

    public void render () {
        Gdx.gl.glClearColor(1, 0, 0, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
    }

    public static void main (String[] args) throws Exception {
        new LwjglApplication(new Barebones());
    }
}

```

With the above code, the cursor gets set to a black square.
If, however, the size of the pixmap and fill is set to 16x16, the result is the cursor is set transparent as you'd expect.
Not sure if the problem is with the fill or the newCursor.
#### Version of LibGDX and/or relevant dependencies

Applies at least to;
1.7.2
1.9.4
#### Please select the affected platforms
- Tested on Windows 10 desktop.
#### New observations;

I noticed that when using a 8x8 pixmap it in fact produces a horizontal black _rectangle_. (4x8 I think). I said square earlier, this was wrong.
The rectangle might imply the fill function is half working ? replacing the lower pixels with transparent but not the top?

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info

**Comment by intrigus** [comment]
Windows probably doesn't not support such small cursors.
Or does a completely green 8x8 cursor work? I bet it doesn't.

**Comment by ThomasWrobel** [comment]
Apologizes. Not really asking for help here, as the workaround works and I am happy enough with that. Just though I was reporting what _seemed_ fairly obvious bug. But maybe its more complex. I assume its a executable you want? There's absolutely no assets involved here.
So working on trying to make a executable code. But first updating GDX to 1.9.4 (little trouble with Gradle to deal with first...).

In the meantime;
@intrigus 
Good idea to test, But it works if set to green (full opacity) even if the size is 2x2. So the problem seems to lie in alpha.
Green with zero alpha, incidentally, produces black again.

**Comment by ThomasWrobel** [comment]
* Posted barebones example. 
* Also added a new observation, correcting a earlier statement I made.
* Tested in 1.9.4, same effect.

**Comment by xoppa** [comment]
Fwiw, in my test both [`org.lwjgl.input.Cursor.getMinCursorSize()`](http://legacy.lwjgl.org/javadoc/org/lwjgl/input/Cursor.html#getMinCursorSize()) and `getMaxCursorSize()` returns `32`. Also, lwjgl3 doesnt seem to allow a fully transparent image, regardless its size.

I doubt there's much we can do about this. But perhaps it would be better to have a method to simply hide the cursor altogether.

**Comment by ThomasWrobel** [comment]
Well, the behavior documented above seems to happen every time, at least on Windows10, so I guess support is partial but undocumented? or something weird is happening internally and it comes out transparent anyway for sizes about 8x8.
If anyone else has tried it, let me know your results.

Makes my position a bit awkward, as I was happy enough with the workaround, but I really shouldn't be relaying on _"something that works but shouldn't"_

As for hiding the cursor;
The downside of that is the cursor remains hidden even outside the window boundaries. This was a safe way as it only was set to invisible within the GDX windows frame.
It just seemed more user-friendly to me.

**Comment by ThomasWrobel** [comment]
Oh, and if there is nothing to do on the GDXside codewise, maybe at least a note on the javadocs?
Currently the newCursor function says;

> 
The Pixmap must be in RGBA8888 format, width & height must be powers-of-two greater than zero (not necessarily equal), and alpha transparency must be single-bit (i.e., 0x00 or 0xFF only). This function returns a Cursor object that can be set as the system cursor by calling...

Would mentioning the additional limitations there make sense?

**Comment by badlogic** [comment]
I've updated the Javadocs on the method. Thanks for reporting.
