### ISSUE TITLE
Hiero writes BMFont file padding with incorrect order

### ISSUE THREAD

**Issue by bryanwagner** [libgdx/libgdx#4295]
#### Issue details

Hiero writes the padding array in the incorrect order, according to the [BMFont file specification](http://www.angelcode.com/products/bmfont/doc/file_format.html). Both the file tags and binary versions specify the ordering as:  up, right, down, left.

Hiero is writing out the padding ordering as:  [up, left, down, right](https://github.com/libgdx/libgdx/blob/f504a294a4aac57a3d43e2ab8cfa8c860ac90044/extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/BMFontUtil.java#L72).

I believe this is an error, but please let me know if it was intentional for any reason (I'm patching my local build; will submit a PR).
#### Reproduction steps/code

Run Hiero, File > Save BMFont files (text)... and open the BMFont file.
#### Version of LibGDX and/or relevant dependencies

1.9.4
#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by badlogic** [comment]
Our `BitmapFont` assumes that order. Changing this in `BitmapFont` as well as `Hiero` would break a lot of code and assets our in the open. Worse, if people regenerate only some of their fonts with `Hiero` using the new order, while other fonts are saved with the old order, people would be very confused and later on upset. I'm afraid we won't change this at this point.
