### ISSUE TITLE
Add setMaximized to Lwjgl3ApplicationConfiguration

### ISSUE THREAD

**Issue by CreamyCookie** [libgdx/libgdx#4298]
Add `setMaximized(boolean maximized)` (and `isMaximized()`) to `Lwjgl3ApplicationConfiguration`, which would set the window to maximized. This should be possible using the window hint `GLFW_MAXIMIZED`. More information: https://github.com/glfw/glfw/blob/master/docs/window.dox
#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by code-disaster** [comment]
Added in 3ed4e06.

**Comment by CreamyCookie** [comment]
Thanks @cypherdare !
