### ISSUE TITLE
way to get the pressure

### ISSUE THREAD

**Issue by custozza** [libgdx/libgdx#4301]
Hey. I know it is not so much an issue but maybe more a feature...? Is there a way to get the pressure from the android touch event?

- [ X] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by nhydock** [comment]
IIRC, android touch events do not have "pressure", what you may see in apps to simulate pressure is nothing more than detecting the length of time between a touch down and touch up event.  Some android tablets do have pressure sensitive stylus's, like the samsung note, but those are different input devices from standard touch.  

Implementing a standard pressure sensitive input interface for tablets would be nice, but I don't think it'd be something that should be implemented if it doesn't also include support for graphics tablets (such as wacom and n-trig) on windows, mac, and linux.

**Comment by MobiDevelop** [comment]
Android MotionEvent does have a "pressure", however I am not sure how often that value is set (I've never checked). I imagine on those touch panels which support it, the value will be set.

**Comment by custozza** [comment]
@nhydock @MobiDevelop 
androids internal simulation of pressure must do some calculation of the area which is touched. Base on the paper of a colleague  of mine the pressure measurements are a very good approximation of really pressure applied ...
so if the pressure measurement of the MotionEvent is not passed on is there some sort of work around to get the original MotionEvent?

i tried something like setting a manual onTouch Listener but i can't pass on the event
View view = initializeForView(new MyGdxGame(), config);
		view.setOnTouchListener(new View.OnTouchListener() {
			@Override
			public boolean onTouch(View v, MotionEvent event) {
				getInput().onTouch(v, event);
				Log.v("log", "hooked");
				return false;
			}
		});

any help is appreciated

**Comment by custozza** [comment]
so sry for bothering you guys somehow it works now
don't asks me what i did differently beside setting return value to true but thx anyways
		View view = initializeForView(game, config);
		view.setOnTouchListener(new View.OnTouchListener() {
			@Override
			public boolean onTouch(View v, MotionEvent event) {
				getInput().onTouch(v, event);
				game.setPressure(event.getPressure());
				Log.v("log", "hooked " + event.getPressure());
				return true;
			}
		});
