### ISSUE TITLE
Jnigen: add support String with null value in native methods. Also allow use of GetXXXArrayElement instead of GetPrimitiveArrayCritical

### ISSUE THREAD

**Issue by AlessandroBorges** [libgdx/libgdx#4307]
Hi !
I'd like to submit a pull request which address the issues listed below.
#### Issue details
1. Add support for null String.
   If you pass a null string to a native method, JVM will crash.
2. Allow use GetXXXArrayElements as option to read/write primitive arrays.
   Current jnigen uses GetPrimitiveArrayCritical for all primitive array in JNI side.
   But GetPrimitiveArrayCritical has some constraints, as stalling GC. Would be nice to be able to chose one or other.
#### Reproduction steps/code

To reproduce null String error just compile and run [MyJniClass2](https://github.com/AlessandroBorges/libgdx/blob/master/extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/test/MyJniClass2.java).

There is no bug with GetPrimitiveArrayCritical, just an enhancement. 
#### Version of LibGDX and/or relevant dependencies

All.
#### Stacktrace for null String

>  A fatal error has been detected by the Java Runtime Environment:
>   EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000006a9f3982, pid=1464, tid=6368
>  JRE version: Java(TM) SE Runtime Environment (8.0_77-b03) (build 1.8.0_77-b03)
>  Java VM: Java HotSpot(TM) 64-Bit Server VM (25.77-b03 mixed mode windows-amd64 compressed oops)
>  Problematic frame:
>  V  [jvm.dll+0x143982]
> 
>  Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
> 
>  An error report file with more information is saved as:
>  D:\Users\Livia\Documents\GitHub\libgdx\extensions\gdx-jnigen\hs_err_pid1464.log
> 
>  If you would like to submit a bug report, please visit:
>    http://bugreport.java.com/bugreport/crash.jsp
#### Proposed Solution

The proposed solution add set/get methods NativeCodeGenerator.java to boolean fields `usePrimitiveArrayCritical` and `supportNullString`
The default values will not change current output of JniGen.

```
boolean usePrimitiveArrayCritical = true;
boolean supportNullString = false;
```

To enable use of **GetXXXArrayElements** , the generator must set `usePrimitiveArrayCritical`as **_false_**.
To allow use of null Strings `supportNullString`must be set as **_true_**.

Example:

```
NativeCodeGenerator jnigen = new NativeCodeGenerator();
jnigen.setUsePrimitiveArrayCritical(false);
jnigen.setSupportNullString(true);
jnigen.generate("src", "bin", "jni", new String[] { "**/MyJniClass2.java" }, null);
```
#### Please select the affected platforms
- [X] Android
- [X] iOS (robovm)
- [X] iOS (MOE)
- [X] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by AlessandroBorges** [comment]
The affect files, already available at my fork, are the following:

[/jnigen/NativeCodeGenerator.java](https://github.com/alessandroborges/libgdx/blob/master/extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/NativeCodeGenerator.java)

[/jnigen/parsing/JavaMethodParser.java](https://github.com/AlessandroBorges/libgdx/blob/master/extensions/gdx-jnigen/src/com/badlogic/gdx/jnigen/parsing/JavaMethodParser.java)

**Comment by badlogic** [comment]
Could you please link me to a source on GC stalls due to primitive array critical usage? We use this instead of element wise getters because the latter usually incurs a copy of the entire primitive array, which has measurable impact on performance.

I'm happy with the null string addition. I've quickly looked through your PR, please apply our formatter to your changes. We'll continue this talk in your PR.

**Comment by AlessandroBorges** [comment]
Hi !
Thanks for reply !

> Could you please link me to a source on GC stalls due to primitive array critical usage? We use this instead of element wise getters because the latter usually incurs a copy of the entire primitive array, which has measurable impact on performance.

The proposed _optional_ use of critical GetXXXArrayElement instead of GetPrimitiveArrayCritical was made for multithreaded apps accessing same array data, like Vulkan. By the specs, GetPrimitiveArrayCritical does not work very well with multiple simultaneous access and GC.

**Comment by Hamlin-Li** [comment]
I hope [Region Pinning in JDK](https://bugs.openjdk.java.net/browse/JDK-8276094) may help eliminate or alleviate this problem in the future.
