### ISSUE TITLE
Pool allows Individual Object to be freed multiple times.

### ISSUE THREAD

**Issue by itravers** [libgdx/libgdx#4310]
I found this while writing Unit Tests for my project.

#### Issue details

Should a pool be able to add a single object multiple times with free(Object)?
I find I am able to add an Object to a pool twice by calling free(Object) twice.
Then when I try to obtain that object, I do, but it also remains in the pool available to 
be obtained again.
This doesn't seem like the correct behavior to me.

#### Reproduction steps/code
1. Create an implemented class that extends Pool.
2. Obtain an Object from the Pool.
3. call Pool.free(Object) Twice in a row.
   -The Pool's Array now contains two references to the Object, instead of the expected one reference.
4. call Pool.obtain() to get an Object for TaskA
5. call Pool.obtain() again to get an Object for TaskB

The Object for TaskA should NOT be the same Object for TaskB.
Yet it is.

#### Suggested Possible Fix
Don't allow Pool.free(Object) to add a specific object to it's array
twice. The Pools array should only have 1 reference to a free'd Object.

When it checks ``` if(freeObjects.size < max) ```
```java
	public void free (T object) {
		if (object == null) throw new IllegalArgumentException("object cannot be null.");
		if (freeObjects.size < max) {
			freeObjects.add(object);
			peak = Math.max(peak, freeObjects.size);
		}
		reset(object);
	}
```
You can just change the check to:
 ``` if(freeObjects.size < max && !freeObjects.contains(object, true)) ```
as so:
```java
    public void free (T object) {
        if (object == null) throw new IllegalArgumentException("object cannot be null.");
        if (freeObjects.size < max && !freeObjects.contains(object, true)) {
            freeObjects.add(object);
            peak = Math.max(peak, freeObjects.size);
        }
        reset(object);
    }
```
I'm using this modified version and everything is testing as expected.

#### Version of LibGDX and/or relevant dependencies
Occurs in the current Master branch

#### Please select the affected platforms
I didn't test them all, but it looks liket his will occur in any
platform that uses the Pool Class
- [ x] Android
- [ x] iOS (robovm)
- [x ] iOS (MOE)
- [x ] HTML/GWT
- [ x] Windows
- [x ] Linux
- [ x] MacOS

**Comment by Darkyenus** [comment]
I am not in favor of this change for two reasons. First is performance. Pools are widely used and doing these checks could bring severe performance penalty when freeing big amount of objects. Second reason is, that overfreeing is (AFAIK) never legal in other contexts. Applications should be written to not overfree.

I am not sure what is libGDX's stance on asserts, but something like `assert !freeObjects.contains(object, true);` would do just fine here.

**Comment by cypherdare** [comment]
I agree, it would be too much of a performance hit just to protect the class from misuse. Just don't free something multiple times.

**Comment by rvmfonseca** [comment]
Hello. I lost several hours due to this choice of design (which I support by the way). It's very time consuming to diagnose this kind of behavior without any previous clue.

Can this information be added to the documentation?? I only see there:

Frees an object from the {@link #get(Class) pool}
and
Puts the specified object in the pool, making it eligible to be returned by {@link #obtain()}. If the pool already contains {@link #max} free objects, the specified object is reset but not added to the pool.

Thank you.
