### ISSUE TITLE
No option for rendering Arc Lines

### ISSUE THREAD

**Issue by hareshkh** [libgdx/libgdx#4313]
I was recently writing some code in libGDX when I came across a problem that there is no method in the `ShapeRenderer` class that can render a Arc in form of a line. The default `arc` method renders a pie shaped sector, which is evident from the code. With little changes to the the base arc method a new method can be made which renders arc as a line. I have done the same and code to which can be found [here](https://github.com/karandesai-96/Magneto-Mania/blob/hw-refactor/core/src/com/sdsmdg/kd/helpers/ArcDrawer.java). The `arc` method in this class can be used to draw an arc line instead of a pie sector.

**Comment by hareshkh** [comment]
Basically, 
Result of **ShapeRenderer**:
![shape](https://cloud.githubusercontent.com/assets/16576273/18615415/59e0e876-7dc4-11e6-8a91-33d29c71c406.png)

**Required**:
![required](https://cloud.githubusercontent.com/assets/16576273/18615416/59e313d0-7dc4-11e6-8737-4f435b8bb290.png)

**Comment by Tom-Ski** [comment]
ShapeRenderer is generally used for debugging purposes, if your use case is otherwise I'd recommend you use SpriteBatch or build a mesh yourself.

Feel free to submit a PR though.
