### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by dungnart** [libgdx/libgdx#4320]
Please ensure you have given all the following requested information in your report.

#### Issue details
I have just submitted our game to Apple for reviewing. They have rejected our game because of IPv6. This is their reply: "We discovered one or more bugs in your app when reviewed on iPad and iPhone running iOS 10.0.1 on Wi-Fi connected to an IPv6 network.We found the app displays an error message upon launch. Please run your app on a device while connected to an IPv6 network (all apps must support IPv6) to identify the issue(s), then revise and resubmit your app for review."
I want to know that does Libgdx support IPv6 ? How to implement IPv6 in my code ?

Thanks !

#### Version of LibGDX and/or relevant dependencies
 gdxVersion = '1.9.4'
 roboVMVersion = '2.2.0'
 box2DLightsVersion = '1.4'
 ashleyVersion = '1.7.0'
 aiVersion = '1.8.0'

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [ ] Android
- [x ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by noblemaster** [comment]
I am the original developer of the Gdx.net backend. Is that what you are referring to? Also, what are you exactly trying to do? Are you creating a socket connection? Are you doing an HTTP request? A code sample would go a long way too.

Generally, Java supports both IPv4 and IPv6. I assume the same will hold true for the RoboVM backend. I haven't done any tests yet. It's possible this needs fixing? Generally this "fix" wouldn't have to be done on your end, but a patch would have to be added to RoboVM. If it's necessary, I don't think it will be too difficult but then you never know :)

Anyhow, I have an app that I am going to update soon. It uses Gdx.net/HTTP. If I get the same error, I'll investigate & fix.

**Comment by dungnart** [comment]
Thank for your reply @noblemaster !

I am using Gdx.net to create socket connection. I've create MMORPG online game. So I have to use socket connection to transfer data. It worked find on all platform with IPv4 connection. 

This is my java code: 

`	public SocketConnection(String address) {
		try {
			String[] strs = address.split(":");
			String ip = strs[0];
			int port = Integer.parseInt(strs[1]);
			SocketHints socketHints = new SocketHints();
			socketHints.keepAlive = true;
			socket = Gdx.net.newClientSocket(Protocol.TCP, ip, port, socketHints);
		} catch (Exception e) {
		}
	}`

I believe that Libgdx can not connect to server by using IPv6. Please fix this bug  ASAP. My game is stucking in here. Thanks a lot !

**Comment by dungnart** [comment]
Hi Mr @badlogic  !

Do you have any idea for above problem ?

**Comment by noblemaster** [comment]
I see. I think I got a solution. Supplying an IPv4 address won't work over a IPv6-ONLY network. Rather than using an IP address directly, please add a DNS entry for you server so the DNS entry maps to both IPv4 and IPv6.

Create e.g. a DNS entry such as "server01.example.com". Then add both the IPv4 & IPv6 address (you should have both from your provider!) to that entry.

In the game, use "server01.example.com" to connect to the server! I believe that should do the trick. The network will internally use either the IPv4 or IPv6 address. You won't need to worry about it.

**Comment by xoppa** [comment]
See: https://github.com/libgdx/libgdx/wiki/Issue-Tracker. Please use the forum or irc for personal support requests.

If you do think that there is an issue with libgdx, then please provide the information required as you were requested when opening this issue, see also: https://github.com/libgdx/libgdx/wiki/More-Info.
