### ISSUE TITLE
Switch field modifiers of BitmapFont to "private"

### ISSUE THREAD

**Issue by avamix** [libgdx/libgdx#4321]
#### Issue details

I need to override BitmapFont but can't do this because of some field modifiers of BitmapFont are "package", such as

```
    final BitmapFontData data;
    Array<TextureRegion> regions;
    boolean integer;
```

There are getters for all of them, but some classes in the same package use them as is. 
For example:

```
GlyphLayout uses font.data (com/badlogic/gdx/graphics/g2d/GlyphLayout.java:84)
BitmapFontCache uses font.regions.size (com/badlogic/gdx/graphics/g2d/BitmapFontCache.java:346)
```

Could you set all of field modifiers to private for BitmapFont.
It really helps me with overriding.
#### Version of LibGDX and/or relevant dependencies

1.9.4
#### Please select the affected platforms

All platforms

**Comment by Darkyenus** [comment]
Just use a different name for your fields, package level visibility is quite common in libGDX.

**Comment by avamix** [comment]
It doesn't work for me. I need to make a proxy for BMFont. So I need to redefine every method in the class and I did it. But some another classes uses fields directly, but I can't redefine fields in package level visibility.
Package level visiblity for fields is a bad practice.

**Comment by Darkyenus** [comment]
I agree that for this use it is not enough. Ideally, we would have a better system for implementing different types of fonts, but it would mean rewriting a lot of libGDX font code which depends on BitmapFont being implemented as it is.

**Comment by sarkanyi** [comment]
Then wouldn't protected be a better idea?

**Comment by Tom-Ski** [comment]
Protected would be better, what exactly are you trying to override here?

**Comment by avamix** [comment]
It doesn't matter private or protected. Any encapsulation is a good.
I've already made encapsulation in my local version. I've just opened issue to improve libGdx code.

**Comment by NathanSweet** [comment]
Package access is not bad practice. Why are you adding a class in the same package? Why can't you use different field names?

**Comment by badlogic** [comment]
Sorry, won't fix.
