### ISSUE TITLE
Lwjgl3: When going from fullscreen to windowed, the window isn't restored on the correct monitor

### ISSUE THREAD

**Issue by CreamyCookie** [libgdx/libgdx#4322]
#### Issue details
The window isn't restored on the correct monitor if going from fullscreen to windowed.

#### Reproduction steps/code
Execute, immediately drag the window to any non-primary monitor.

```java
import com.badlogic.gdx.*;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.graphics.*;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;

public class BarebonesBatch extends ApplicationAdapter {
    SpriteBatch batch;
    Texture texture;

    public void create () {
        batch = new SpriteBatch();
        texture = new Texture(Gdx.files.internal("data/badlogic.jpg"));

    }

    int i = 0;

    public void render () {
        i++;
        if (i == 100000) {
            Gdx.graphics.setFullscreenMode(Gdx.graphics.getDisplayMode());
        } else if (i == 200000) {
            Gdx.graphics.setWindowedMode(400,400);
        }
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        batch.begin();
        batch.draw(texture, 100, 100);
        batch.end();
    }

    public static void main (String[] args) throws Exception {
        new LwjglApplication(new BarebonesBatch());
    }
}
```

#### Version of LibGDX and/or relevant dependencies
1.9.4

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by CreamyCookie** [comment]
@Tom-Ski Hey! I just realized I made a big mistake. I assumed that the monitor had to be supplied, but actually one has to supply `0`:

> This function sets the monitor that the window uses for full screen mode or, if the monitor is {@code NULL}, makes it windowed mode.

Please revert my pull request. Sorry for the inconvenience.  (I should have tested this, but didn't because my second monitor isn't attached. )

**Comment by Tom-Ski** [comment]
Yup, I skipped over that documentation a little too quickly also, woops!
