### ISSUE TITLE
Runtime failure on iOS 10.0: Cannot parse iOS version string "10.0"

### ISSUE THREAD

**Issue by magicgoose** [libgdx/libgdx#4328]
#### Issue details
App crashes with message `Cannot parse iOS version string "10.0"`
I guess it's self explanatory and easy to fix, but I am not sure yet if it's a bug in libgdx or in MOE.

#### Reproduction steps/code
Try to launch a ios-moe project on iOS 10.0 simulator.
I can add [SSCCE](http://sscce.org/) if necessary.

#### Version of LibGDX and/or relevant dependencies
gdxVersion = '1.9.5-SNAPSHOT'

#### Log
```
assertion failed: 15G1004 14A345: libxpc.dylib + 62597 [37A9DF49-35C1-3D93-B854-B35CACF0100F]: 0x7d
Error: -[IOSVersion init]: Cannot parse iOS version string "10.0"
objc[74486]: Invalid or prematurely-freed autorelease pool 0x7fd1718b1040.
```

#### Affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [x] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

### Update

I think, the message is from this code

https://searchcode.com/codesearch/view/255216/

And it looks like an obvious error.

```
		NSString* versionStr = [[UIDevice currentDevice] systemVersion];
		unichar ch = [versionStr characterAtIndex:0];
		if(ch < '0' || ch > '9' || [versionStr characterAtIndex:1] != '.')
		{
			NSLog(@"Error: %s: Cannot parse iOS version string \"%@\"", __PRETTY_FUNCTION__, versionStr);
		}
```

**Comment by magicgoose** [comment]
https://github.com/kstenerud/ObjectAL-for-iPhone/issues/98 — found the relevant issue
Can the fix be integrated into libgdx?

**Comment by Tom-Ski** [comment]
Should be resolved in the next build.
