### ISSUE TITLE
Reported Memory Footprint continues to grow

### ISSUE THREAD

**Issue by MondayHopscotch** [libgdx/libgdx#4329]
#### Issue details
App memory (Windows Desktop) continues to grow. I was debugging something in a game I've been working on and noticed that If I just let the app sit open, the memory footprint continually increases. For my game, it started at about 200MB, but got up to over 1.2GB after letting it sit for 45 minutes.

After banging my head on it, I made a base LibGDX project and performed the same test. Using JVisualVM, the memory consumption appears normal. I see a nice slow sawtooth profile. But according to Windows (Observing through Task Manager) the memory started at ~45MB, but after about 15 minutes, it's reporting about 110MB.

#### Reproduction steps/code

Latest at the time of observing this was version 1.9.4
Run the desktop project (I'm currently using IntelliJ Community 2016.2)
Open Task Manager and watch the processes reported Private Working Set

#### Version of LibGDX and/or relevant dependencies
 
I am only aware of this issue on Windows

**Comment by intrigus** [comment]
This is not an issue.
If memory consumption appears normal when using VisualVM everything is fine.
Java's memory may grow for various reasons which are totally unrelated to your program.
If you indeed found a memory leak in libgdx, please attach an SSCCE, so it can be fixed.

**Comment by Tom-Ski** [comment]
That's most likely VisualVM that is using all that memory to track your allocations and invokations etc. As @intrigus said, please attach a SSCCE if you believe there is a problem, and reopen this issue.
