### ISSUE TITLE
Game crashing without stacktrace, presumably box2d

### ISSUE THREAD

**Issue by ForsakenHarmony** [libgdx/libgdx#4332]
#### Issue details
Game crashes on certain collisions?
Windows freezes with no output

#### Reproduction steps/code
https://github.com/ForsakenHarmony/GameProt
crashes when shooting other ships

controls: wasd,space

Video: https://youtu.be/11KLDI5MC9o

#### Version of LibGDX and/or relevant dependencies
gdxVersion = '1.9.4'
box2DLightsVersion = '1.4'
ashleyVersion = '1.7.3'
aiVersion = '1.8.0'
kotlin_version = '1.0.4'

#### Stacktrace
```java
//no output
```

#### Please select the affected platforms
- [x] Windows
- [ ] Linux (didn't test)
- [ ] MacOS (didn't test)

**Comment by Tom-Ski** [comment]
Please use the forum or the irc for help with your own code.  https://github.com/libgdx/libgdx/wiki/Issue-Tracker
