### ISSUE TITLE
Robovm 1.14.0 didn't support IPV6?

### ISSUE THREAD

**Issue by guojinshang** [libgdx/libgdx#4334]
My IOS Game was reject by apple for my iap-item can't be got in IPV6 environment,does anybody meet
this problem?How to resolve it?Is it robovm bug?

Issue details
I request iap-item form apple service as below code show.And It's ok in IPV4 environment.
public void initIAP(){
SKPaymentQueue.getDefaultQueue().addTransactionObserver(StoreObserver.getInstance());
		NSNotificationCenter.getDefaultCenter().addObserver(StoreManager.IAPProductRequestNotification,
				StoreManager.getInstance(), NSOperationQueue.getMainQueue(), new VoidBlock1<NSNotification>() {
					@Override
					public void invoke(NSNotification a) {
						Gdx.app.log(TAG, "handleProductRequestNotification");
						handleProductRequestNotification(a);
					}
				});
		NSNotificationCenter.getDefaultCenter().addObserver(StoreObserver.IAPPurchaseNotification,
				StoreObserver.getInstance(), NSOperationQueue.getMainQueue(), new VoidBlock1<NSNotification>() {
					@Override
					public void invoke(NSNotification a) {
						handlePurchasesNotification(a);
					}
				});
}
Version of LibGDX and/or relevant dependencies
Lbgdx 1.9.2 ,robovm 1.14.0

The affected platforms
 iOS (robovm)

**Comment by Tom-Ski** [comment]
This is an issue tracker for LibGDX, not Robovm 1.14.0, please asks these questions on the forum or the irc.  If you believe there is an issue with LibGDX itself, please read the issue template fully so people can help.
