### ISSUE TITLE
Libgdx: Save and Load a screen

### ISSUE THREAD

**Issue by Lafrag** [libgdx/libgdx#4338]
Hi, I want to save and load the progression of a player in my game, I came to the conclusion that
 I'll give each of my screens a name or a number. When I load a screen, I can do
`preferences.putInt("currentScreen", screenName);`
. Then when I reopen my game, in the
`create() method`
, I'd do
`preferences.get("currentScreen")`
and set the screen from the name I get
but how to tell the machine to get the last screen or the last variable ?

**Comment by Darkyenus** [comment]
See: https://github.com/libgdx/libgdx/wiki/Issue-Tracker. Please use the forum or irc for personal support requests.

If you do think that there is an issue with libgdx, then please provide the information required as you were requested when opening this issue, see also: https://github.com/libgdx/libgdx/wiki/More-Info.
