### ISSUE TITLE
[backend-lwjgl3] setInitialBackgroundColor has no effect

### ISSUE THREAD

**Issue by Scellow** [libgdx/libgdx#4340]
#### Issue details

For the LWJGL3 backend, changing initialBackgroundColor in the Lwjgl3ApplicationConfiguration has no effect

No mater what color i choose, the screen is still white

I tried the JGLFW backend, and it works fine
#### Reproduction steps/code

Choose the LWJGL3 backend, in your desktop module use this as config

``` kotlin
    val config = Lwjgl3ApplicationConfiguration()
    config.setWindowedMode(1440,900)
    config.setInitialBackgroundColor(Color.BLACK)
    Lwjgl3Application(TheRoguer(), config)
```
#### Version of LibGDX and/or relevant dependencies

libGDX 1.9.5-SNAPSHOT
LWJGL3 Backend 1.9.5-SNAPSHOT
#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows 10
- [x] Linux
- [ ] MacOS

**Comment by code-disaster** [comment]
Works fine here. Are you sure you're not clearing the window yourself in create() or render()?

**Comment by voidburn** [comment]
I have the exact same problem, when the lwjgl3window is created it's cleared with white, no matter what initial color is set. 

When I launch the application it flashes white before I glclear with black in my render loop. 

A similar artifact can be seen while resizing the window. A smaller white square is rendered in the buffer.

**Comment by code-disaster** [comment]
I think I found a solution. At least I see the correct color now when I do some time-intensive stuff in ApplicationListener.create().

**Comment by voidburn** [comment]
I was just about to push a PR that did the exact same thing! Ty CD!

**Comment by Scellow** [comment]
Thanks a lot @code-disaster 😃!
