### ISSUE TITLE
Android Plugin for Gradle doesn't play nice with the current libGDX source

### ISSUE THREAD

**Issue by Zomby2D** [libgdx/libgdx#4341]
#### Issue details
As previously discussed in issue #4230, starting with version 1.3 the Android Plugin for Gradle doesn't like a module and it's parent sharing the same name. You end up with an error message when trying to do a Gradle Sync or to build and run the Android project from within the IDE.

In both Android Studio and IntelliJ IDEA, you get the following error:
```java
Error:(23, 1) A problem occurred evaluating project ':tests:gdx-tests-android'.
> Failed to apply plugin [id 'com.android.application']
   > Your project contains 2 or more modules with the same identification com.badlogicgames.gdx:gdx-box2d
at ":extensions:gdx-box2d" and ":extensions:gdx-box2d:gdx-box2d".
You must use different identification (either name or group) for each modules.
```

That part is easy enough to fix. All you need to do is to rename the parent "module".  I have already done this part in commit 50179d2a870c1c938d5a0c5014b9c0a09fc3c4d7 on my fork. Up until a few days ago it was enough to get the code to Sync and Run nicely in the IDE. (I even submitted PR #4316 to that effect.)

Unfortunately, with the refactoring of the Gradle build (0ea025084f59d8feb7711f825bf0f11c440830bd) the Gradle Sync and Instant Run within the IDE are no longer working even with this fix.

We're now left with the following error:
```java
Error:(18, 1) A problem occurred evaluating project ':tests:gdx-tests'.
> Could not find method compile() for arguments [project ':gdx'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

Interestingly, the command-line Grade build and installDebug do work without a hitch. It would appear that the Android plugin get confused with the dependencies. Manually adding ``apply plugin: "java"`` to the ``gradle.build`` file of ``:tests:gdx-tests`` will allow the build to proceed further but even when adding it to all the related modules, other errors crop up further along so it's not a viable solution and I had to admit defeat due to my limited knowledge of Gradle.

**Comment by Tom-Ski** [comment]
make sure configure on demand is off in your IDE

**Comment by Zomby2D** [comment]
Thanks, that did the trick. I don't get why IDEA and Android Studio are ignoring the line in gradle.properties though.
