### ISSUE TITLE
Since 1.9.4 font scale no longer effects size of scene2d label

### ISSUE THREAD

**Issue by pstreef** [libgdx/libgdx#4346]
#### Issue details
When rendering bitmap fonts directly, the bitmapfontdata scale effects the size of the drawn text. If a label using the same bitmap is rendered. the scale no longer has any effect (since 1.9.4)

I use the scale feature heavily with distance field fonts.

#### Reproduction code
[full compilable project](http://streefgames.com/bitmapfonttest.rar)
```
public class BitmapFontTest extends ApplicationAdapter
{
	SpriteBatch batch;

	Label bigLabel;
	Label smallLabel;
	BitmapFont big;
	BitmapFont small;


	@Override
	public void create()
	{
		batch = new SpriteBatch();
		small = new BitmapFont();
		big = new BitmapFont();

		small.getData().setScale(1.0f);
		big.getData().setScale(4.0f);

		bigLabel = new Label("not big label",new Label.LabelStyle(big, Color.WHITE));
		bigLabel.setPosition(0,100);
		smallLabel = new Label("small label",new Label.LabelStyle(big, Color.WHITE));
	}

	@Override
	public void render()
	{
		Gdx.gl.glClearColor(1, 0, 0, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		batch.begin();
		bigLabel.draw(batch, 1.0f);
		smallLabel.draw(batch, 1.0f);
		big.draw(batch,"big font",100,125);
		small.draw(batch,"small font",100,25);
		batch.end();
	}

	@Override
	public void dispose()
	{
		batch.dispose();
		big.dispose();
		small.dispose();
	}
}
```

#### Version of LibGDX and/or relevant dependencies
<1.9.3 works, 1.9.4 & 1.9.5 does not

#### Please select the affected platforms
only tested on windows but it seems to be a scene2d issue. So I presume all platforms

**Comment by Tom-Ski** [comment]
Looks fine to me, have you tested with 1.9.5-SNAPSHOT ? There isn't a 1.9.5 version yet, so not sure what you mean by saying 1.9.5 it doesn't work.

http://pix.asidik.com/tomski-NlzQLQ.png

**Comment by pstreef** [comment]
Sorry about that, I was under the impression I had tested 1.9.5 as well, but as you say it does not even exist! The issue only occurs in 1.9.4 it seems, because 1.9.5-SNAPSHOT also shows the same as your screenshot (working as intended).

So I guess this is an old issue and can be closed. Thanks for the quick reply and sorry for wasting time!

**Comment by Tom-Ski** [comment]
Cool, no problem.  You can take a look at previous entries (open and closed) in the issue tracker to make sure your issue is unique.
