### ISSUE TITLE
libEGL warning: failed to create a pipe screen for i965

### ISSUE THREAD

**Issue by raeleus** [libgdx/libgdx#4347]
#### Issue details

One of my users has [reported an error](https://github.com/raeleus/skin-composer/issues/11) under Ubuntu Linux when running any LibGDX app using the LWJGL3 backend: `libEGL warning: failed to create a pipe screen for i965` I can't reproduce the issue under Ubuntu or Linux Mint, so I imagine it is specific to Intel processors or his particular hardware setup. The Window decorations render, however the game screen does not display and instead shows something of a snapshot of what was underneath the window. He's tested with a basic app that only renders a skin and it still reproduces the issue.

After doing some research, I found the following documented LWJGL3 issue: https://github.com/LWJGL/lwjgl3/issues/205 which sounds exactly like what this user was experiencing. The page speaks of a fix or partial workaround. Can this be applied to LibGDX? Thanks for your time.
#### Reproduction steps/code

Any project that implements the LWJGL3 backend and run under Ubuntu Linux on certain hardware configurations. An example jar here: https://github.com/raeleus/skin-composer/files/509721/Quantum.Horizon.zip
#### Version of LibGDX and/or relevant dependencies

_1.9.4 and 1.9.5-SNAPSHOT_
#### Stacktrace

``` java
java -jar skin_composer.jar
java.lang.NullPointerException
at org.lwjgl.system.APIUtil.apiGetManifestValue(APIUtil.java:97)
at org.lwjgl.system.Library.checkHash(Library.java:260)
at org.lwjgl.system.Library.(Library.java:44)
at org.lwjgl.system.MemoryAccess.(MemoryAccess.java:17)
at org.lwjgl.system.ThreadLocalUtil$UnsafeState.(ThreadLocalUtil.java:86)
at org.lwjgl.system.ThreadLocalUtil.getInstance(ThreadLocalUtil.java:43)
at org.lwjgl.system.ThreadLocalUtil.(ThreadLocalUtil.java:20)
at org.lwjgl.system.MemoryStack.stackPush(MemoryStack.java:577)
at org.lwjgl.system.Callback.(Callback.java:35)
at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:78)
at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.(Lwjgl3Application.java:87)
at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:42)
libEGL warning: failed to create a pipe screen for i965
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
```
#### Affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] MacOS

**Comment by magicgoose** [comment]
Maybe ask him which **kernel** does he use?

**Comment by badlogic** [comment]
This is a bug in LWJGL3, or rather GLFW. According to the other issue, it's being worked on by the GLFW maintainer. Until they fix the bug, there's nothing we can do.

**Comment by intrigus** [comment]
Not sure whether you were using lwjgl3.0 but 3.1 should have fixed this issue. 
Libgdx has only been recently updated to 3.1 so there's a chance that it has been fixed.

**Comment by sreich** [comment]
I can confirm that at least, the null pointer manifest issue is present in latest libgdx release(1.9.4 I think). Apparently it's not an important error though from what I've found. 

But that is separate from the Intel driver issue..

**Comment by raeleus** [comment]
Well, I haven't heard back from my user so I'll have to assume it's fixed or not relevant anymore.  Thanks guys.

**Comment by badlogic** [comment]
In my (vast, hauntint) experience with Intel drivers, especially on Linux, it was most likely fixed by a binary blob driver update.
