### ISSUE TITLE
HorizontalGroup Layout

### ISSUE THREAD

**Issue by little-dgek** [libgdx/libgdx#4354]
HorizontalGroup layout in 1.9.5 is wrong. Downgrade to 1.9.3 fix it
Code is equivalent of this.

```
HorizontalGroup group = new HorizontalGroup() {
      @Override
    public float getPrefWidth() {
        return 100;
    }

    @Override
    public float getPrefHeight() {
        return 100;
    }
};
group.center().addActor(button);
```
#### Issue details

<img width="592" alt="2016-10-10 2 31 08" src="https://cloud.githubusercontent.com/assets/9482740/19224604/deb9a320-8e91-11e6-98ce-82a0dcb832f5.png">
#### Version of LibGDX and/or relevant dependencies

1.9.5
#### Please select the affected platforms
- [ *] Android
- [ *] iOS (robovm)
- [ *] iOS (MOE)
- [ *] HTML/GWT
- [ *] Windows
- [ *] Linux
- [ *] MacOS

**Comment by obigu** [comment]
Related to #4243
