### ISSUE TITLE
SpriteBatch: IllegalArgumentException with OpenGL ES 3.0 in OS X

### ISSUE THREAD

**Issue by manabreak** [libgdx/libgdx#4359]
#### Issue details
I'm trying to run a plain project with OpenGL ES 3.0 enabled. When I try to create a SpriteBatch, the program crashes with IllegalArgumentException. This only seems to happen on OS X; the code runs fine on Arch Linux. It seems to be caused by the default shader.

#### Reproduction steps/code
1. Enable OpenGL ES 3.0 by setting `config.useGL30 = true`
2. Create a SpriteBatch with default constructor

#### Version of LibGDX and/or relevant dependencies
Tested with 1.9.3 and 1.9.4, both crash

#### Stacktrace
```java
Exception in thread "LWJGL Application" java.lang.IllegalArgumentException: Error compiling shader: ERROR: 0:1: '' :  #version required and missing.
ERROR: 0:1: 'attribute' : syntax error: syntax error
ERROR: 0:1: '' :  #version required and missing.
ERROR: 0:7: 'varying' : syntax error: syntax error

	at com.badlogic.gdx.graphics.g2d.SpriteBatch.createDefaultShader(SpriteBatch.java:160)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:123)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:78)
	at com.badlogic.gdx.scenes.scene2d.Stage.<init>(Stage.java:100)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [X] MacOS

**Comment by xoppa** [comment]
Don't enable gles 3 if you don't want to use gles 3.0. If you do want to use gles 3 then you'll have to use a gles 3 compatible shader.

**Comment by manabreak** [comment]
See, I *want* to use GLES 3. Does this mean that `SpriteBatch` doesn't support GLES 3 out-of-the-box on OS X?

**Comment by xoppa** [comment]
Yes, you could say that. Please use the forum or IRC for further support, this is not the place for that.
