### ISSUE TITLE
BoundingBox in 2d

### ISSUE THREAD

**Issue by Heerbann** [libgdx/libgdx#4360]
Less an issue but suggestion:

When using the provided methods for checking intersection or contain of the [BoundingBox](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/math/collision/BoundingBox.html) it always checks for validity first. 

`public boolean isValid () {
        return min.x < max.x && min.y < max.y && min.z < max.z;
    }`

this of course returns never true in a strict 2d environment and one has to set max.z > 0 manually. 

a solution could be

`public boolean isValid () {
        return min.x < max.x && min.y < max.y && min.z <= max.z;
    }`

but I dont know about the implications in 3d.

Cheers

**Comment by xoppa** [comment]
Sounds reasonable. It should be consistent among all axes though. Also the javadoc would need to be updated and it should be noted in CHANGES.

Not sure about the implications indeed. Afaik all code paths use `.inf()` for invalid bounds, but it's best to verify that at least by running the tests.

Care to send a pull request?

**Comment by Heerbann** [comment]
#isValid() is really only used for #contains() and #intersects() and in said methods the equal operator is already in use -> for reference: [here](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/math/collision/BoundingBox.java#L304) and [here ](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/math/collision/BoundingBox.java#L276) and [here ](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/math/collision/BoundingBox.java#L296).
I guess that was just overlooked. 

> Care to send a pull request?

not gonna lie, I have no idea how to do that. I would if I could.

**Comment by kerberjg** [comment]
I agree about the need for consistency here, but If we opted for consistency among all axes, a `BoundingBox` with a volume of zero would be then considered valid.

If that's not a problem, I could take care of the PR.

**Comment by badlogic** [comment]
Please submit a PR, closing this out.
