### ISSUE TITLE
Weird behaviour with pixmap colors (alpha)

### ISSUE THREAD

**Issue by Skrelpoid** [libgdx/libgdx#4364]
#### Issue details
There seems to be a bit of a buggy behaviour when working with colors in a pixmap. If you do setPixel with a color that doesn't have full alpha, it changes all the other color values. If you do getPixel you will get a different color than what you originally wanted.
This is really bugging me right now, because I wanted to save the colors (that I get by getPixel) in json and then load the json and get the same color. However, what happens is that the colors get darker and darker the more i load and save.

#### Reproduction steps/code
```
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.graphics.Pixmap;
import com.badlogic.gdx.graphics.Pixmap.Format;

public class PixmapColor extends ApplicationAdapter {

	public static void main(String[] args) {
		new LwjglApplication(new PixmapColor());
	}

	@Override
	public void create() {
		Pixmap pixmap = new Pixmap(64, 64, Format.RGBA8888);
		int color = 0xff0000dd; // red that is a bit transparent

		// Prints ff0000dd
		Gdx.app.log("PixmapColor", Integer.toHexString(color));

		pixmap.drawPixel(0, 0, color);

		// Prints wrong color: dd0000dd
		Gdx.app.log("PixmapColor", Integer.toHexString(pixmap.getPixel(0, 0)));

		pixmap.dispose();
	}

}
```

#### Version of LibGDX and/or relevant dependencies
1.9.2

#### Stacktrace
None

#### Please select the affected platforms
- [x] Android
- [x] iOS (robovm)
- [x] iOS (MOE)
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by mbrlabs** [comment]
That's the default blending. You can disable that with `Pixmap.setBlending(Pixmap.Blending.None)`.
It's all in the docs ;)

**Comment by Skrelpoid** [comment]
Oh thanks! I didn't think this was intended haha. Guess I should read more of the docs.
