### ISSUE TITLE
Increase upper limit for decoded audio

### ISSUE THREAD

**Issue by CreamyCookie** [libgdx/libgdx#4365]
According to [this part in the docs](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/Audio.html#newSound-com.badlogic.gdx.files.FileHandle-) "current upper limit for decoded audio is 1 MB." This seems quite low. Especially on the desktop.

Is there limit for how many sounds can be played at the same time?

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker

**Comment by CreamyCookie** [comment]
@xoppa Hey :) Sorry, the question was just an additional thing, which I've now removed. This issue is a about the problem of having very small upper limit for audio.  (not a bug though).

**Comment by xoppa** [comment]
Sounds like you're confusing Sound and Music. Anyways, please use the forum or IRC for this.
