### ISSUE TITLE
AndroidApplicationConfiguration.useWakeLock is misleading

### ISSUE THREAD

**Issue by Betalord** [libgdx/libgdx#4370]
The use of "useWakeLock" seems misleading to me; let me explain:

Android uses two different mechanisms to keep the screen on at all times (so that it doesn't dim out or turn off due to inactivity). One of them is via FLAG_KEEP_SCREEN_ON flag and is done this way:

getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);

The other, more complex (which needs a special permission in the manifest) is called Wakelock and is achieved like this:

mWakeLock = mPowerManager.newWakeLock(PowerManager.SCREEN_BRIGHT_WAKE_LOCK, 
                getClass().getName());

(and needs to be released as well).

Now, the "useWakelock" modifier that libgdx uses obviously seems to apply use of Wakelock mechanism. However, it turns out this is not the case. If you look at the AndroidApplication.java (libgdx/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplication.java), you will see it calls createWakeLock() method in it's init() method. Now let's see it's implementation:

```
protected void createWakeLock (boolean use) {
    if (use) {
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
    }
}
```

As can be seen from this source code, it uses the FLAG_KEEP_SCREEN_ON mechanism which has nothing to do with the Wakelock mechanism (which offers much more control, requires a permission in the application's manifest etc.).

So, can someone verify this? I think this is an issue and needs to be taken care of.

**Comment by MobiDevelop** [comment]
Both are a wake lock, it is just one (the one we use) is managed by the system.

**Comment by badlogic** [comment]
Fixed by changing docs to be more explicit.
