### ISSUE TITLE
Video Play Support

### ISSUE THREAD

**Issue by vanimarcos** [libgdx/libgdx#4374]
Include a the ability to play videos on the library using multiples video files format with no platform dependency, its hard to develop a game with a library that does not have this functionality. Right now we need to include another library that increases the application layers, and consequently the size. I can contribute.

**Comment by Tom-Ski** [comment]
This isn't something that would be integrated into the core library. You can check out https://github.com/libgdx/gdx-video for video playback within libgdx.

**Comment by vanimarcos** [comment]
With all respect, It's a BAD decision not to do so.
Adding this library is no easy the Gradle dependencies are not resolving I read an article saying that I need to change to this compile "es.e-ucm.com.badlogicgames.gdx:gdx-video:0.0.1-SNAPSHOT", its confusing.
The last this I need is confusion in my code and mind.

**Comment by Tom-Ski** [comment]
If you have an issue with gdx-video I suggest you open up an issue there.
