### ISSUE TITLE
Add excludes to Android Gradle files to prevent common errors due to expected duplicates

### ISSUE THREAD

**Issue by czyzby** [libgdx/libgdx#4379]
#### Issue details
Currently the Android project can fail to compile (due to detected duplicate files in included libraries) even if the files are somewhat expected - like licenses or RoboVM meta-data.

Proposed solution: add something along [these lines](https://github.com/czyzby/gdx-setup/blob/master/src/main/kotlin/com/github/czyzby/setup/data/platforms/android.kt#L116-L130) to Android `build.gradle` files.

#### Reproduction steps/code
You can easily reproduce this issue by including two libraries with `robovm.xml`, like `gdx-kiwi` and `gdx-lml`. See https://github.com/czyzby/gdx-lml/issues/46

Use these dependencies in the `core` or `android` Gradle project to reproduce the issue due to duplicate `META-INF/robovm/ios/robovm.xml` file:
```Groovy
    dependencies {
        // ...
        compile "com.github.czyzby:gdx-lml:1.9.1.9.4-SNAPSHOT"
        compile "com.github.czyzby:gdx-autumn:1.9.1.9.4-SNAPSHOT"
        compile "com.kotcrab.vis:vis-ui:1.1.1"
    }
```

#### Version of LibGDX and/or relevant dependencies
`gdx-setup` 1.9.4 (and below).

#### Affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
You have duplicate robovm.xml files in the same jar, what is the reason for that?  If you can provide an example where this happens due to valid dependencies we can do something about this, but this looks like an issue in your artifacts.

**Comment by czyzby** [comment]
This is kind of weird that Gradle does that and I'll look into it, but ts seems that the issue appears when you include *two* libraries which define *two* separate files with the *same* path. For example, this issue would appear if you tried to include two libraries with two different implementations of `com.example.Test` class.

**Comment by czyzby** [comment]
See: [1](https://stackoverflow.com/questions/20673625/android-gradle-plugin-0-7-0-duplicate-files-during-packaging-of-apk), [2](https://stackoverflow.com/questions/22467127/error-duplicate-files-during-packaging-of-apk).

**Comment by ghandhikus** [comment]
See: http://i.imgur.com/5tGDQls.png

**Comment by czyzby** [comment]
Yeah, I [fixed that](https://github.com/czyzby/gdx-lml/commit/0a018418134664f433c5a35bd0cf058b0f7eec80) on my part, but I'm pretty sure this is still an issue - I'll try to reproduce that issue with correct libraries with non-duplicated `robovm.xml` (VisUI + snapshots of `gdx-lml` and `gdx-autumn`).

**Comment by MobiDevelop** [comment]
Not sure we want to get into the habit of making decisions for users based on issues that may or may not exist in libraries that they may or may not use.

**Comment by czyzby** [comment]
Well, if it's a matter of including two "officially supported" third-party extensions that happen to support RoboVM by including extra meta-data with reflected classes, I'd say it's not such an uncommon issue.

Anyway, I'll check if this was solely the incorrect Gradle setup on my part that caused this or is this because using multiple libraries with `META-INF/robovm/ios/robovm.xml` files are the source of the problem.

**Comment by czyzby** [comment]
As I expected, this is still an issue even after fixing LML setup:

```
* What went wrong:
Execution failed for task ':android:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/robovm/ios/robovm.xml
  	File1: /home/mj/.gradle/caches/modules-2/files-2.1/com.kotcrab.vis/vis-ui/1.1.1/842e46897e09630af3f126f3761e1e0b8cf797a8/vis-ui-1.1.1.jar
  	File2: /home/mj/.gradle/caches/modules-2/files-2.1/com.github.czyzby/gdx-lml/1.9.1.9.4-SNAPSHOT/6e0e9f308a8b1ef520ba9b3d1a417973a02a4383/gdx-lml-1.9.1.9.4-SNAPSHOT.jar
  	File3: /home/mj/.gradle/caches/modules-2/files-2.1/com.github.czyzby/gdx-autumn/1.9.1.9.4-SNAPSHOT/af37c23c13e61548074e5cb9ac2287e996aa0ba8/gdx-autumn-1.9.1.9.4-SNAPSHOT.jar
```

Basically, if multiple dependencies include RoboVM meta-data (`META-INF/robovm/ios/robovm.xml`), Gradle will fail to compile the Android application without the exclude. I understand that adding excludes to licenses (and so on) should be left to the LibGDX user, but since RoboVM is one of the official backends, I'd add an exclude for its meta-data at the very least.

**Comment by czyzby** [comment]
Dependencies that reproduce the issue:
```Groovy
    dependencies {
        compile "com.badlogicgames.gdx:gdx:$gdxVersion"
        compile "com.github.czyzby:gdx-lml:1.9.1.9.4-SNAPSHOT"
        compile "com.github.czyzby:gdx-autumn:1.9.1.9.4-SNAPSHOT"
        compile "com.kotcrab.vis:vis-ui:1.1.1"
    }
```

**Comment by Tom-Ski** [comment]
Thanks for the reproducible example.
