### ISSUE TITLE
FreeTypeFontGenerator - add margin parameter

### ISSUE THREAD

**Issue by Betalord** [libgdx/libgdx#4380]
I believe that the FreeTypeFontGenerator needs another parameter passed via FreeTypeFontParameter (or otherwise) that would specify margins when creating BitmapFont. Let me explain. When the generator creates the font, the bitmaps created are exactly the height of the highest letter, hence not leaving any spacing above and bellow. However, some users (like myself) may want to have some additional spacing because of blending issues. Let's look at my concrete example:

https://vid.me/RWxo

In this video, the text "50" is moving. Its filters are GL_LINEAR. Now, the upper pixel row and bottom pixel row seem to be "blinking". This is because the blending function has no "space" at those borders to draw the gradiant.
Now, the same problem can be seen even better in this image:
https://raw.githubusercontent.com/wiki/mattdesl/lwjgl-basics/images/vAVHc.png
![vavhc](https://cloud.githubusercontent.com/assets/22757675/19761500/919ed33c-9c36-11e6-905b-cbba059bcbc9.png)
The borders at GL_LINEAR look "cut out", because there isn't any space in the texture to draw the blended border.

This is why I propose a margin parameter to be added to the FreeTypeFontGenerator, in order for the user to specify these extra borders to avoid blending issues as described here.

**Comment by Tom-Ski** [comment]
You can pass in your own packer to provide padding if you via the FreeTypeFontParameters.  

A video is not very helpful on its own, see https://github.com/libgdx/libgdx/wiki/Getting-help
