### ISSUE TITLE
[feature] gdx-setup : Keep Android SDK path in cache...

### ISSUE THREAD

**Issue by nbourre** [libgdx/libgdx#4381]
As a teacher, I create a lot of small projects.

I think this is a simple feature, would it be a complicated task to keep the android SDK path in cache for GDX-SETUP?

Each time we create a project, we need to browse all the way to the Android SDK which does not change much over time.

This would save a bit of frustration everytime. ;)

Keep doing a great job guys!

**Comment by nbourre** [comment]
Thanks! My searches about your answer brought me to unofficial postings here and there. Is it documented somewhere?

**Comment by nbourre** [comment]
I've setup the ANDROID_HOME environment variable, but gdx-setup does not load the path. I've also tried to type %android_home% into the field, and it does not recognize it.

**Comment by Tom-Ski** [comment]
There is no documentation on this, if you set the ANDROID_HOME variable correctly the setup tool will pick it up and fill it in.  If its not there, Java can't see your variable, so its probably a configuration on your end.
