### ISSUE TITLE
Add a function in Controller to get the number of buttons / axis

### ISSUE THREAD

**Issue by CreamyCookie** [libgdx/libgdx#4383]
I don't know about LWJGL and others, but GLFW (which is used in LWJGL 3) has methods for getting the number of [buttons](http://www.glfw.org/docs/latest/group__input.html#gace54cd930dcd502e118fe4021384ce1b) and [axis](http://www.glfw.org/docs/latest/group__input.html#ga6271d46a5901ec2c99601ccf4dd14731).

**Comment by badlogic** [comment]
Sadly, Android's APIs don't allow enumeration of buttons. As such, this API wouldn't be portable :/

https://developer.android.com/training/game-controllers/controller-input.html
