### ISSUE TITLE
Introduce PooledList implementation

### ISSUE THREAD

**Issue by Try4W** [libgdx/libgdx#4386]
It will be nice to have a default implementation of something like `PooledList` for long lists with images and other heavy widgets.

**Comment by xoppa** [comment]
It already contains a `Pool` class, http://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/utils/Pool.html. See also: https://github.com/libgdx/libgdx/blob/master/.github/CONTRIBUTING.md#feature-requests.

**Comment by Try4W** [comment]
Under "PooledList" I meant Actor, something like RecyclerView from Android API.
