### ISSUE TITLE
[Feature request] Support S3TC (aka DXT1-5) texture loading on Desktop

### ISSUE THREAD

**Issue by magicgoose** [libgdx/libgdx#4388]
It seems that it's the most widely supported format on desktop GPUs, so it would be very useful.

There's an old forum post where Mario said it's doable: http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=10482

But also this:

> Integration with TextureAtlas would be a bit more work.

Why it'll be more work?

**Comment by magicgoose** [comment]
As far as I understand, the KTX[Z] format allows to store any compression format. So the only problem here is to find a way to put DXT* textures into KTX format, or add support for it into KTXProcessor, right?

**Comment by sp-1234** [comment]
>As far as I understand, the KTX[Z] format allows to store any compression format. So the only problem here is to find a way to put DXT* textures into KTX format, or add support for it into KTXProcessor, right?

yes, that's right. I tested it and it works, libgdx has no problem with DXT textures.
and as far as I understood, ktx[z] can indeed be used to store virtually any compressed texture format (one only needs to implement the writer) and they are loaded transparently by libgdx (if hardware supports that format), that's cool.
