### ISSUE TITLE
Update GWT to 2.8

### ISSUE THREAD

**Issue by barkholt** [libgdx/libgdx#4389]
Is anyone working on upgrading the GWT backend to 2.8? 

The 2.6 release of GWT is almost three years old now, and missing lots of fixes and improvements in GWT. I have more than once had to work around issues in GWT that are fixed in newer versions.

If no one is working on it, and the maintainers are open to upgrading, I'm willing to investigate how to update the project. I'm just unsure about the libGDX maintainers plans concerning the GWT backend - some of the patches I have been submitting attempting to improve the GWT backend, haven't really gotten much response.
#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [x] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by MobiDevelop** [comment]
We've not yet looked into it because 2.8 was a pre-release until a week ago. Will look into it soon. Hopefully we have better luck with it than we did with 2.7.

**Comment by Leejjon** [comment]
Hi, I'm interested in having libgdx to use GWT 2.8.0 with my game, so I can use Java 8 everywhere on my client/server. I'll be doing a GWT project soon so hoping to learn some more GWT. If somebody starts working on this please update progress in this ticket or somewhere. I'll see if I can help out with testing/bugfixing. Will you guys create a separate branch for this all GWT backend 2.8.0 modifications so that it's easy to follow the changes that are being made for it?

**Comment by RUSshy** [comment]
> We've not yet looked into it because 2.8 was a pre-release until a week ago. Will look into it soon. Hopefully we have better luck with it than we did with 2.7.

isn't pre-release/beta/alpha exist so dev can  start to work on integration, so customer will have software ready on day 1?

**Comment by MobiDevelop** [comment]
Sure, but it was in pre-release for upwards of a year (with no clear estimate of when it would be released) and we aren't going to release libgdx using a pre-release version when the existing version was working.

**Comment by ThomasWrobel** [comment]
[comes out of the corner]
Out of interest, what was the issues with Gwt2.7?


--
http://lostagain.nl <-- our company site.
http://fanficmaker.com <-- our, really,really, bad story generator.

**Comment by xoppa** [comment]
See #2845

**Comment by MobiDevelop** [comment]
Made a [branch] (https://github.com/libgdx/libgdx/tree/gwt-2.8.0) and pushed the minimal changes required to use GWT 2.8.0. There are some classes in our emulation which can be removed since GWT itself now emulates them, but I did not include those removals so far.

**Comment by MobiDevelop** [comment]
2.8.0 seems to not suffer from the same slow compile times as 2.7.0 did, so that's good news.

**Comment by ThomasWrobel** [comment]
+1. Good stuff. 
Does this mean Java1.8 is possible across all compile platforms of LibGDX?

(Oh, worth noting that if you use GWT 2.8 and make use of Guava, you also need to use Guava 20.0, as it breaks compatibility. (well worth noting for me, anyway). Guava now in turn seems to depend on some new stuff I haven't fully worked out yet.)

**Comment by VinceAngel** [comment]
Nice, I'm interested too in GWT 2.8, it is still WIP ? 
Would be nice to have it ASAP since we work on a GWT project :+1:

**Comment by MobiDevelop** [comment]
I think we are good to put this into master sometime this week.

**Comment by badlogic** [comment]
I put it into master :D
