### ISSUE TITLE
There's no secure way to get gdx-setup.jar except building from source

### ISSUE THREAD

**Issue by magicgoose** [libgdx/libgdx#4390]
#### Issue details
The download of gdx-setup.jar is served over plain text connection (http), which is not suitable for executable code.

#### Reproduction steps/code
Try to download it from the location given in Wiki, notice the redirect to `http://libgdx.badlogicgames.com/nightlies/dist/gdx-setup.jar`

	$ curl -L -v https://bitly.com/1i3C7i3
	* Connected to bitly.com (67.199.248.14) port 443 (#0)
	* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
	* Server certificate: *.bitly.com
	* Server certificate: DigiCert SHA2 High Assurance Server CA
	* Server certificate: DigiCert High Assurance EV Root CA
	> GET /1i3C7i3 HTTP/1.1
	> Host: bitly.com
	> User-Agent: curl/7.43.0
	> Accept: */*
	>
	< HTTP/1.1 301 Moved Permanently
	< Server: nginx
	< Date: Mon, 31 Oct 2016 05:36:42 GMT
	< Content-Type: text/html; charset=utf-8
	< Content-Length: 147
	< Connection: keep-alive
	< Cache-Control: private, max-age=90
	< Content-Security-Policy: referrer always;
	< Location: http://libgdx.badlogicgames.com/nightlies/dist/gdx-setup.jar
	< Referrer-Policy: unsafe-url
	< Set-Cookie: _bit=g9v5AG-4efa2ea0d48fc2213d-00i; Domain=bitly.com; Expires=Sat, 29 Apr 2017 05:36:42 GMT
	<
	* Ignoring the response-body
	{ [147 bytes data]
	100   147  100   147    0     0     37      0  0:00:03  0:00:03 --:--:--    37
	* Connection #0 to host bitly.com left intact
	* Issue another request to this URL: 'http://libgdx.badlogicgames.com/nightlies/dist/gdx-setup.jar'
	*   Trying 144.76.220.132...
	* Connected to libgdx.badlogicgames.com (144.76.220.132) port 80 (#1)
	> GET /nightlies/dist/gdx-setup.jar HTTP/1.1
	> Host: libgdx.badlogicgames.com
	> User-Agent: curl/7.43.0
	> Accept: */*
	>
	< HTTP/1.1 200 OK
	< Server: nginx/1.4.6 (Ubuntu)
	< Date: Mon, 31 Oct 2016 05:36:43 GMT
	< Content-Type: application/java-archive
	< Content-Length: 1493634
	< Last-Modified: Thu, 27 Oct 2016 21:12:39 GMT
	< Connection: keep-alive
	< ETag: "58126dc7-16ca82"
	< Accept-Ranges: bytes
	<

And building from source would be OK, if it was in a separate repo… unfortunately git has to download >100MB of data even if I need only single folder (yes I tried using depth=1 and sparse mode)

**Comment by Tom-Ski** [comment]
Fixed via https://github.com/libgdx/libgdx-site/commit/3c5942e037d26c725949b6018cb5794169dd61ec
