### ISSUE TITLE
[FreeTypeFontGenerator] doesn't work for russian (cyrillic) characters

### ISSUE THREAD

**Issue by JFixby** [libgdx/libgdx#4392]
#### Issue details

Works fine for latine chars. Fails to render cyrillic.

Tracking the call I discovered that FreeTypeFontGenerator calls the line 423 and receives null for cyrillic characters:
```
Glyph glyph = createGlyph(c, data, parameter, stroker, baseLine, packer);
```
where createGlyph returns null at line 492
```
boolean missing = face.getCharIndex(c) == 0 && c != 0;
		if (missing) return null;
```

after making JNI-call getCharIndex:
```
private static native int getCharIndex(long face, int charCode);
// return FT_Get_Char_Index((FT_Face)face, charCode);
```

See 
https://github.com/libgdx/libgdx/blob/master/extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator.java#L423

#### Version of LibGDX and/or relevant dependencies
Current code 1.9.5 (1-Nov-2016)

#### affected platforms
- [X ] Windows

**Comment by MobiDevelop** [comment]
Can you please provide more information - such as a SSCCE, and the font you are using?

**Comment by MobiDevelop** [comment]
Seems to work for me using Roboto... maybe your font simply doesn't contain the characters you are trying to use.

**Comment by JFixby** [comment]
I followed your advice and tried another Cyrillic font and it works. Thank you for the hint.
