### ISSUE TITLE
Tilesets with margin/spaces cause flickering when rendering while camera moves

### ISSUE THREAD

**Issue by PojahnM** [libgdx/libgdx#4393]
I am using Tiled to create a TMX map which I render in LibGDX. The tiles in the tileset have 1 pixel margin. This cause the rendering unit to flicker while rendering the tiles when the camera moves. You can actually see the margin color. 

Using the latest on nightly as of this date. Testing on Windows 10 using LWJGL3 backend. 

This is how the flickering looks:
https://s11.postimg.org/xr702rtgj/line.png

The vertical line the two arrows point at are visible when the camera moves. 

This is the tile image:
https://s15.postimg.org/mnyg4wh57/report.png

In Tiled, both space and margin is set to 1.

**Comment by xoppa** [comment]
See: https://github.com/libgdx/libgdx/wiki/Issue-Tracker. Please use the forum or irc for personal support requests.

If you do think that there is an issue with libgdx, then please provide the information required as you were requested when opening this issue, see also: https://github.com/libgdx/libgdx/wiki/More-Info.
