### ISSUE TITLE
Getting core and desktop build jar added to dependencies of theirself

### ISSUE THREAD

**Issue by Litarvan** [libgdx/libgdx#4394]
#### Issue details
I saw on IntelliJ that desktop/build/libs/desktop-1.0.jar was in the dependencies of the 'desktop' project, and core/build/libs/core-1.0.jar was in the dependencies of the 'core' project, it causes a lot of problems, i need to manually delete it from the dependencies when i do a Gradle sync, i searched i didn't found anything on the gradle files causing this issue. If i don't delete the dependency, i need to build to refresh code completion/error detection/etc...

#### Reproduction steps/code
Create a project with gdx-setup, (adding scala ? and vis-ui ?), building desktop and core, import the project and do gradle sync on IntelliJ.

#### Version of LibGDX and/or relevant dependencies
1.9.4 (with IntelliJ 2016.3 EAP)

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux (The only one i tested)
- [ ] MacOS

**Comment by intrigus** [comment]
Gdx-Setup doesn't support scala afaik, so how do you create your project?

**Comment by Litarvan** [comment]
Just added :

On core build.gradle :
```groovy
apply plugin: "scala"
...
sourceSets.main.scala.srcDirs = ["src/"]
```

On root build.gradle :
```groovy
project(":core") {
    ...
    apply plugin: "scala"
    ...
    dependencies {
        ...
        compile "org.scala-lang:scala-library:2.11.7"
    }
    ...
}
```

On the gdx setup generated project

**Comment by aspic** [comment]
The Scala and SBT section on the wiki worked for me a couple of days ago: https://github.com/libgdx/libgdx/wiki/Using-libgdx-with-Scala

**Comment by Litarvan** [comment]
This is exactly what i used, but i don't think it is the cause of my issue

**Comment by Litarvan** [comment]
What ? My problem isn't solved it wasn't related to scala ;_;

**Comment by MobiDevelop** [comment]
If there is a problem with your output jars becoming dependencies for that project, it is a problem with your own build setup, not a libgdx issue. If you have questions or need general help, please use the forum or irc.

**Comment by Litarvan** [comment]
This is a gdx-setup issue, because it comes from the gradle files (if i delete the dependency on the settings, it registers again when gradle sync), that were generated by gdx-setup and that i didn't modified (just to add scala).

**Comment by MobiDevelop** [comment]
Nobody else has this problem and we've been on Gradle for a very long time. Again, please use the forum or irc to ask questions and get help with your project setup.

**Comment by Litarvan** [comment]
I'll try to reproduce it with a 100% clean project, i'll keep you informed

**Comment by Litarvan** [comment]
I did it ! 

How to reproduce :
 * Create a project with gdx-setup with : Desktop, Android, Html, iOS (not moe), and VisUI
 * Import it on IntelliJ (i'm using 2016.3 EAP), select to use gradle wrapper, import everything, and when it asks you include de GWT, Android, etc... files
 * Wait for refreshing, indexion, etc...
 * Add scala to the project using this link : https://github.com/libgdx/libgdx/wiki/Using-libgdx-with-Scala with Gradle, and do the optional source dir in core/build.gradle
 * Change VisUI version to 1.1.1
 * Refresh gradle project, and wait for everything
 * Build, and see, core/build/libs/core-1.0.0.jar is a dependency, desktop/build/libs/desktop-1.0.0.jar is too, etc... (sometimes, you need to build multiple time, idk)

**Comment by MobiDevelop** [comment]
So if you don't add Scala, and you don't change the VisUI version it doesn't do this?

**Comment by Litarvan** [comment]
Your right, seems to be a problem with VisUI, it does sometimes when the vis-ui sources (no :html) aren't in the same version of the library, this is very strange i wasn't even able to rebuild, think you should update because, the 1.1.1 VisUI version (the one that gdx-setup install) isn't compatible with GDX 1.9.4, but the last one (1.2.4) is.

Thank you for the help :)
