### ISSUE TITLE
First Textfield initialization 3-5ms longer than the rest

### ISSUE THREAD

**Issue by spectre329** [libgdx/libgdx#4397]
#### Issue details
For example:
We have pre-loaded graphics, fonts so loading a textfield is just a matter of nanoseconds, simple objects creation.

We have 4 textfields: tf1, tf2, tf3, tf4
When we initialize them via 'new', first Textfield will initialize in 3-5 milliseconds and the rest in ~30000 nanoseconds = 0.03 ms.

No matter how many textfields are there, only the first one gets the lag.

#### Reproduction steps/code

So, I have a little bit custom Textfield (with textfieldstyle in constructor) but there's no leak - I'm sitting here for 2 days and I checked everything.

```
  public TextField(String text) {
       // this super lasts max 10 000 nano (assets are pre-loaded) (but 1st time it lasts 3ms)
        super(text, new TextFieldStyle(AssetsLoader.getDefaultFont(), AssetsLoader.getDefaultColor(), null, null, null));
        setFocusTraversal(false);
  }

```
getDefaultFont execution time is max 3000ns, it's just a static reference (tested 12312313524534 times)
getDefaultColor - same

So there's only one thing left - the super() textfield constructor:
```
	setStyle(style);
	clipboard = Gdx.app.getClipboard();
	initialize();
	setText(text);
	setSize(getPrefWidth(), getPrefHeight());
```

Tested it, execution of this constructor takes longer with the first textfield in code (but still not 3-5 ms), something around 1ms, when normally it takes 0.01 at max. I have already tested each of these methods by overriding them.

So, if you could look at this, I would be grateful, cause I don't know if I'm retarded since monday (I proved that I'm not) or there's something wrong.

#### Version of LibGDX and/or relevant dependencies
        gdxVersion = '1.9.4'
        roboVMVersion = '2.2.0'
        box2DLightsVersion = '1.4'
        ashleyVersion = '1.7.0'
        aiVersion = '1.8.0'

#### Please select the affected platforms
- [x] Android
- [x] Windows
Tested on these

**Comment by xoppa** [comment]
See: https://github.com/libgdx/libgdx/wiki/Issue-Tracker. Please use the forum or irc for personal support requests.

If you do think that there is an issue with libgdx, then please provide the information required as you were requested when opening this issue, see also: https://github.com/libgdx/libgdx/wiki/More-Info.
