### ISSUE TITLE
Why buffer.toByteArray() can not work on html ?

### ISSUE THREAD

**Issue by tianqiujie** [libgdx/libgdx#4399]
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ *] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

```
ByteArrayOutputStream buffer = new ByteArrayOutputStream();
        try {
            ImageIO.write(bi, "png", buffer);
        } catch (IOException e) {
            e.printStackTrace();
        }

        return new Pixmap(buffer.toByteArray(), 0, buffer.toByteArray().length);
```

Error is: "array[] can not covert to int" at the 
```
new Pixmap(buffer.toByteArray(),
```

**Comment by MobiDevelop** [comment]
Pixmap is emulated on GWT (it has only a subset of available constructors), you cannot create a Pixmap from a byte array there. Also, ImageIO is not available in GWT (or any supported platform other than desktop), so that code wouldn't work anyway.
