### ISSUE TITLE
libGdx Wiki - Extending the simple game - Sample code does not dispose assets

### ISSUE THREAD

**Issue by PeterStampfli** [libgdx/libgdx#4406]
Concerns the libGdx wiki page: [https://github.com/libgdx/libgdx/wiki/Extending-the-simple-game](https://github.com/libgdx/libgdx/wiki/Extending-the-simple-game):
The code for the GameScreen class uses its dispose()-method to dispose diverse assets. Unfortunately, this method is not called automatically:  
In [https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/Screen.html](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/Screen.html) you see 

> Note that dispose() is not called automatically.

This is fine, but we have to take care. Thus we need to call the dispose()-method of the GameScreen instance in the dispose()-method of the Drop class extending Game. This is missing and assets will thus not be disposed, creating memory leaks. I found the same error in other libGdx tutorials too.
**This is subtle and everyone should be aware of it, I suppose.** It would be good to update the wiki.

**Comment by Tom-Ski** [comment]
The wiki is publicly editable, feel free to update it.
