### ISSUE TITLE
Bullet wrapper - wrong return type in btShapeHull

### ISSUE THREAD

**Issue by parnold-x** [libgdx/libgdx#4408]
Hello, i think i found a issue with the swig wrapping of **btShapeHull**.

the method **getVertexPointer()** returns a single btVector3
see [here](https://github.com/libgdx/libgdx/blob/9b8f20b2d0e96e53f0f2b98dc8f6131c810aae71/extensions/gdx-bullet/jni/swig-src/collision/com/badlogic/gdx/physics/bullet/collision/btShapeHull.java#L81)

but it should be some kind of List of vectors
see [here](https://github.com/libgdx/libgdx/blob/9b8f20b2d0e96e53f0f2b98dc8f6131c810aae71/extensions/gdx-bullet/jni/src/bullet/BulletCollision/CollisionShapes/btShapeHull.h#L51)

also the method getIndexPointer should be return a longbuffer
see [here](https://github.com/libgdx/libgdx/blob/9b8f20b2d0e96e53f0f2b98dc8f6131c810aae71/extensions/gdx-bullet/jni/swig-src/collision/com/badlogic/gdx/physics/bullet/collision/btShapeHull.java#L86)

but should return some kind of list of integers
see [here](https://github.com/libgdx/libgdx/blob/9b8f20b2d0e96e53f0f2b98dc8f6131c810aae71/extensions/gdx-bullet/jni/src/bullet/BulletCollision/CollisionShapes/btShapeHull.h#L55)

i think this is strange but it could be intended though. Would be nice to know in this case.

Thanks and Greetings
Peter

**Comment by xoppa** [comment]
Thanks! Not all methods can be translated automatically and need to be changed manually. This is one of those methods (well strictly speaking the method is correct, because the native code returns the pointer to the first element in the array, but that's not how it is intended of course ;).

We'll have to add these manually. What's the use-case you need these methods for?

**Comment by parnold-x** [comment]
Thanks for the answer again. I try to use the libgdx wrapped bullet (which is awesome btw :+1: ) to replace my jbullet code that I use till now and gets to outdated. I prototype some new constraints and scences in a lwjgl window that draws the bullet shapes directly and this is using these methods see [here](https://github.com/bubblecloud/jbullet/blob/master/src/test/java/com/bulletphysics/demos/opengl/GLShapeDrawer.java#L275)

**Comment by xoppa** [comment]
Would you mind to verify the fix? Snapshot should be updated in about an hour or so.

**Comment by parnold-x** [comment]
Can verify the fix works. Had to first figure out that the returned vector3 is temporary till the next call. 
Thank you!
