### ISSUE TITLE
"unknown error 36059" when instantiating FrameBufferCubemap

### ISSUE THREAD

**Issue by JustinMullin** [libgdx/libgdx#4409]
When attempting to construct a simple FrameBufferCubemap on OS/X Yosemite (10.10.5), using LibGDX 1.9.4 stable on the LWJGL/Desktop backend, I'm getting the error below. I have not attempted to reproduce on other platforms.

OpenGL appears to return an error status from `glCheckFramebufferStatus` if it's queried before `glBindFramebuffer`. In the current state of GLFrameBuffer the status is queried before the FB bind, resulting in an error code.

This appears to be regression on https://github.com/libgdx/libgdx/issues/3227. See also the original fix commit at: https://github.com/libgdx/libgdx/pull/3233.

Stack trace:

```
Exception in thread "LWJGL Application" java.lang.IllegalStateException: frame buffer couldn't be constructed: unknown error 36059
at com.badlogic.gdx.graphics.glutils.GLFrameBuffer.build(GLFrameBuffer.java:230)
at com.badlogic.gdx.graphics.glutils.GLFrameBuffer.<init>(GLFrameBuffer.java:118)
at com.badlogic.gdx.graphics.glutils.FrameBufferCubemap.<init>(FrameBufferCubemap.java:88)
at com.badlogic.gdx.graphics.glutils.FrameBufferCubemap.<init>(FrameBufferCubemap.java:75)
at xyz.jmullin.fbcube.error.desktop.FbCubeError.create(FbCubeError.java:11)
at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```

Minimal application to reproduce:

```
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.*;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.Pixmap;
import com.badlogic.gdx.graphics.glutils.FrameBufferCubemap;

public class FbCubeError extends ApplicationAdapter {
	public void create () {
		new FrameBufferCubemap(Pixmap.Format.RGB888, 1024, 1024, true);
	}

	public void render () {
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
	}

	public static void main (String[] args) throws Exception {
		new LwjglApplication(new FbCubeError());
	}
}
```

**Comment by JustinMullin** [comment]
I've closed my initial PR (https://github.com/libgdx/libgdx/pull/4411) for this, which re-introduced the change made by #3233. Per discussion on the PR, it looks like this isn't just a matter of when the status is queried, and this might not actually be legitimate regression.

This does still appear to be a legitimate issue, however, but I'm not clear on the root cause.

**Comment by xoppa** [comment]
Note that 36059 = 0x8CD8 which is GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER. Unfortunately I can't test this atm.

**Comment by xoppa** [comment]
Do you also get the error if you use RGBA8888?

**Comment by code-disaster** [comment]
According to the [docs.gl](http://docs.gl/gl3/glFramebufferTexture) page, I would assume that at least [this call](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/glutils/GLFrameBuffer.java#L170) is wrong in case of cube map textures. The third parameter should be `GL_TEXTURE_CUBE_MAP_POSITIVE_X + n`.

I don't know if there are other issues. For example, the glBindTexture() calls may be required to change as well, e.g. to use `colorTexture.glTarget`.

**Comment by JustinMullin** [comment]
@xoppa I do get the error with RGBA8888 and with other formats.

**Comment by xoppa** [comment]
Indeed, that doesn't look correct @code-disaster, probably because cubemap was added later. Could you have a look at fixing that? Otherwise I can look at that this weekend. I currently can't test on yosemite though.

**Comment by code-disaster** [comment]
Yeah, I can give it a try later tonight. I'm on El Capitan, and the error happens here too with FrameBufferCubemapTest.

**Comment by code-disaster** [comment]
Please have a look at my PR. The shader attribute system is uncharted territory for me.

**Comment by xoppa** [comment]
@JustinMullin could you verify whether this is fixed for you with latest snapshot?

**Comment by JustinMullin** [comment]
@code-disaster @xoppa Looks good with the nightlies, no more error.

👍 👍 👍

**Comment by xoppa** [comment]
Thanks for reporting back. Will close this.
