### ISSUE TITLE
Persian support

### ISSUE THREAD

**Issue by siml173** [libgdx/libgdx#4413]
why Libgdx doesn't support complex script like Persian?
can you add this feature for lots of programmers that put Libgdx away just for this reason?

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
Please follow the issue template as you were requested when opening this issue.
Although it's unclear what you mean, I guess this is a duplicate of #1589.

**Comment by arezaee** [comment]
hi, I just want to say, somebody has done it:
https://github.com/CrowniAPIs/libGDX-RTL-Language

**Comment by ahmady173** [comment]
thank you soooo much

**Comment by arezaee** [comment]
hi, I just want to say , somebody has done it.
https://github.com/CrowniAPIs/libGDX-RTL-Language
