### ISSUE TITLE
Gdx.graphics.getDensity() reporting the wrong DPI

### ISSUE THREAD

**Issue by Zac-Garby** [libgdx/libgdx#4424]
Please ensure you have given all the following requested information in your report.

#### Issue details
On my iMac 5k (2015), using `Gdx.graphics.getDensity()` returns 0.65. This is wrong, because the dpi of my screen is 442, and therefore should be higher than 1.

#### Reproduction steps/code
Call `Gdx.graphics.getDensity()` on an iMac 5k

#### Version of LibGDX and/or relevant dependencies
1.9.3, I think, based on the fact that my project uses _gdx-1.9.3.jar_.

#### Please select the affected platforms
- [x] MacOS
- [x] Possibly win and linux

**Comment by badlogic** [comment]
The problem is that we can not query the true DPI of a monitor on the desktop via GLFW or LWJGL2. The returned value is an approximation. You can use the display resolution as a heuristic.

**Comment by Zac-Garby** [comment]
Do you know of any other way to make a game density independant then?

**Comment by NathanSweet** [comment]
```
Object obj = Toolkit.getDefaultToolkit().getDesktopProperty("apple.awt.contentScaleFactor");
if (obj instanceof Float) {
	Float f = (Float)obj;
	// Do something with f, like set the config overrideDensity
}
```
If you make this work for Mac, we'd likely merge (I'm not a Mac person).

**Comment by Progruzovik** [comment]
This issue still remains on the macOS with libGDX 1.9.8. Perhaps we just need to multiply the screen resolution by the LWJGL scale factor?
`Toolkit.getDefaultToolkit().getScreenResolution() * Display.getPixelScaleFactor() / 160f`
