### ISSUE TITLE
Label.pack zeros the width !

### ISSUE THREAD

**Issue by doit-ceo** [libgdx/libgdx#4427]
#### Issue details
To get the text to wrap correctly you set the width and then call pack !
however this doesn't work correctly and this problem is clear when Label is skinned, calling "Label.pack()" cause further problem because this method **will zero the width** by "setSize(getPrefWidth(), getPrefHeight());" in the default pack method, as you can see, when wrap=true , then the getPrefWidth()=0 which cause this.

Some other solution found in the internet (http://stackoverflow.com/questions/24276180/libgdx-label-multiline-text-height) request you to call pack and then set the width again !

So simply the method "Label.pack()" is buggy when Label.wrap=true (also it would be good idea to expose this variable isWrap())

#### Reproduction steps/code
This is a fix , also note that the "wrap" variable is not visible :( so it's hard to fix this in a subclass.

`
public void pack () {
	if (wrap){
		validate();
		setSize(getWidth(), getPrefHeight()); //or simply setHeight(getPrefHeight())
	}else{
		super.pack();
	}
}
`

#### Version of LibGDX and/or relevant dependencies
1.9.4

#### Please select the affected platforms
Shows on all platforms.

**Comment by NathanSweet** [comment]
Your understanding of pack is incorrect. See Layout#pack javadocs.

Pack sizes the widget to its pref size, nothing more. Pref width of a label with wrap is 0.
```
Label label = new Label(...);
label.setWrap(true);
label.setWidth(123);
label.validate();
label.setHeight(label.getPrefHeight());
```
