### ISSUE TITLE
iOS sounds are muted after a timer/incoming call

### ISSUE THREAD

**Issue by serhii-k** [libgdx/libgdx#4429]
The issue was probably introduced with iOS 10.

Sounds, that are obtained from Gdx.audio.newSound() become silent when:
1) a timer popup is shown
2) after an incoming call

Music, obtained from Gdx.audio.newMusic() plays as normal.

#### Reproduction steps/code
Set the timer to 1 minute. Return to your game and play. When you see the timer popup, all sounds become muted.

Or, make an incoming call from another phone, while you are playing.

To hear sounds again, you need to restart the app:
- Press the "home" button twice, swipe away your app. Restart it again.

#### Version of LibGDX and/or relevant dependencies
I only tried 1.9.4 with robovm. I didn't have much time to familiarize with MOE yet...

#### Please select the affected platforms
- [X] iOS (robovm)
- [not tested] iOS (MOE)

**Comment by badlogic** [comment]
I believe this is fixed via the fix for this. https://github.com/libgdx/libgdx/issues/4430

**Comment by serhii-k** [comment]
Wow, it really resolved this issue! Thank you very much, Mario!!!
