### ISSUE TITLE
iOS sounds and the ringer/mute switch

### ISSUE THREAD

**Issue by serhii-k** [libgdx/libgdx#4430]
When the ringer/mute switch on a side of an iPhone is enabled, all sounds/music inside a game become silent. There are other games that continue to play sounds in this state.

As I understand, these lines set such behaviour:

https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSAudio.java#L36

https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-moe/src/com/badlogic/gdx/backends/iosmoe/IOSAudio.java#L36

Is there any way to make this behaviour configurable?

#### Please select the affected platforms
- [X] iOS (robovm)
- [X] iOS (MOE)

**Comment by cypherdare** [comment]
Apple guidelines are that you only override the switch if you are playing media, not a game. The whole purpose of the switch is to instantly silence everything. As an iPhone user, I would be very annoyed if a game did this.

**Comment by serhii-k** [comment]
Thank you, Mario!
