### ISSUE TITLE
[Lwjgl3 backend] Window crashes when resizing via window corner drag

### ISSUE THREAD

**Issue by voidburn** [libgdx/libgdx#4434]
#### Issue details
When resizing the window via mouse and drag on a corner (any corner, but not single edges) the application crashes in the natives layer.

#### Reproduction steps/code
Open the Lwjgl3TestStarter, grab a corner (CORNER, does not happen if only an edge is being resized) of the window and start resizing.

Tested on Windows 10 64bit
Video card: GTX 980ti
Nvidia drivers 375.70

Tested on Linux Ubuntu 16.04.x
Video card: iGPU on an intel i5 3570k
Drivers: mesa 11.0

#### Version of LibGDX and/or relevant dependencies
Snapshot from the current master (commit b68e50bb4ef06e679e86d5eb14fb751b59b0da91)

#### Stacktrace
None given, it crashes in the natives. Traced it back to the Lwjgl3Graphics class, in the resize callback handler:

```java
private GLFWFramebufferSizeCallback resizeCallback = new GLFWFramebufferSizeCallback() {
		@Override
		public void invoke(long windowHandle, final int width, final int height) {
			updateFramebufferInfo();
			if (!window.isListenerInitialized()) {
				return;
			}
			window.makeCurrent();
			gl20.glViewport(0, 0, width, height);
			window.getListener().resize(getWidth(), getHeight());
			window.getListener().render();
			GLFW.glfwSwapBuffers(windowHandle); //<--- Commenting this buffer swap avoids the crash
		}
	};
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows (Only tested on windows)
- [x] Linux (Does not crash, but the application is hit hard and takes a while to recover)
- [ ] MacOS

**Comment by cypherdare** [comment]
This does not occur for me on Windows 10 or macOS Sierra. Are you working from the gradle snapshot or from source? The Lwjgl3 backend was updated recently with new natives to fetch, so if you're working from source you might need to update them (`gradlew fetch` or `ant -f fetch.xml`).

**Comment by voidburn** [comment]
Yep, fresh ant and git pull! I wouldn't be surprised at all if it's a driver issue. I'm pretty sure it's not a libgdx bug, but I lack the knowledge to dig further and report it to either lwjgl or glfw. Hope someone more knowledgeable than me ca reproduce it. 

Will test on linux + intel igpu later today.

**Comment by voidburn** [comment]
Tested on linux with an i5 3570k integrated GPU. It does not crash, but it seriously cripples the application, it takes a minute for it to recover. Behaves regularly with that buffer swap commented out though.

**Comment by voidburn** [comment]
I can reproduce this even with the Lwjgl3 demos, I guess we can close this one, it's definitely something on their end. I'll open the issue on their tracker.
