### ISSUE TITLE
There are no non-deprecated 1-channel texture formats for desktop

### ISSUE THREAD

**Issue by sp-1234** [libgdx/libgdx#4436]
The formats GL_ALPHA, GL_LUMINANCE, GL_LUMINANCE_ALPHA and GL_INTENSITY have been deprecated in OpenGL (non-ES), long ago. There are still one and two channel formats — GL_RED and GL_RG.

But `Gdx2DPixmap` doesn't know about these non-deprecated formats as can be seen from this code:

```
	public static int toGlFormat (int format) {
		switch (format) {
		case GDX2D_FORMAT_ALPHA:
			return GL20.GL_ALPHA;
		case GDX2D_FORMAT_LUMINANCE_ALPHA:
			return GL20.GL_LUMINANCE_ALPHA;
		case GDX2D_FORMAT_RGB888:
		case GDX2D_FORMAT_RGB565:
			return GL20.GL_RGB;
		case GDX2D_FORMAT_RGBA8888:
		case GDX2D_FORMAT_RGBA4444:
			return GL20.GL_RGBA;
		default:
			throw new GdxRuntimeException("unknown format: " + format);
		}
	}
```

I think it should be possible to use 1 and 2 channel textures with libgdx on newest hardware (which might drop support for deprecated OpenGL features)

**Comment by xoppa** [comment]
Possible duplicate of #4029

**Comment by sp-1234** [comment]
@xoppa oh yeah, that's pretty much what I wanted to say.
