### ISSUE TITLE
Bits#lastSetBit, enhancement proposal

### ISSUE THREAD

**Issue by kerberjg** [libgdx/libgdx#4439]
I'm using the [Bits](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/Bits.java) class to write a faster version of [IntMap](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/IntMap.java) which doesn't use hashes for mapping, by simply keeping a raw array of objects instead of a hash table, and a bitset for faster allocation.

When writing the `shrink()` method for my `FastIntMap` class, I found myself in need of finding the index of the *last set bit*, in order to know from which position should the array be trimmed.

I could implement this in my own code, but it would be just plain ugly. If this is something that could be of use to others as well, I'd be glad to submit a PR for Bits.

**Comment by badlogic** [comment]
Sounds good! Please send a PR.
