### ISSUE TITLE
List.draw() method draws items as selected when they are not

### ISSUE THREAD

**Issue by Betalord** [libgdx/libgdx#4445]
I just found a bug in the List.draw() method: when using List\<String\>, all items that have the same name will be drawn as selected when in reality only one of them is selected. This is due to String.equals() comparison instead of "==" comparison.

This is the affected code (from the List.draw()):

```
font.setColor(fontColorUnselected.r, fontColorUnselected.g, fontColorUnselected.b, fontColorUnselected.a * parentAlpha);
for (int i = 0; i < items.size; i++) {
	if (cullingArea == null || (itemY - itemHeight <= cullingArea.y + cullingArea.height && itemY >= cullingArea.y)) {
		T item = items.get(i);
		boolean selected = selection.contains(item);
		if (selected) {
			selectedDrawable.draw(batch, x, y + itemY - itemHeight, width, itemHeight);
			font.setColor(fontColorSelected.r, fontColorSelected.g, fontColorSelected.b, fontColorSelected.a * parentAlpha);
		}
		drawItem(batch, font, i, item, x + textOffsetX, y + itemY - textOffsetY);
		if (selected) {
			font.setColor(fontColorUnselected.r, fontColorUnselected.g, fontColorUnselected.b,
				fontColorUnselected.a * parentAlpha);
		}
	} else if (itemY < cullingArea.y) {
		break;
	}
	itemY -= itemHeight;
}
```

The problem is in this line:
`boolean selected = selection.contains(item);`
The contains() method (deeper down the line) uses "equals()" instead of "==" comparison, this is why this bug occurs. So instead of drawing only 1 line as selected, it will draw multiple lines as selected (all the lines that have the same string value).

**Comment by NathanSweet** [comment]
The selection uses equality (not identity) by design. You can wrap your values in a unique object which has a `toString` method that returns the string to display (though I'm not sure when it's useful to put multiple of the same object in the list).
