### ISSUE TITLE
[Feature request] TextureArray inside TextureAtlas/TextureRegion/AtlasRegion

### ISSUE THREAD

**Issue by magicgoose** [libgdx/libgdx#4453]
libgdx already [supports loading `TextureArray`s](https://github.com/libgdx/libgdx/pull/3807), that's great, but their most useful application (drawing regions from multi-page atlases in arbitrary order) are currently out of reach because TextureAtlas can't use TextureArray yet, right?

I might actually try to implement it myself, but I wonder if someone is already working on it, and if there are any potential pitfalls or maybe I'm missed something.

**Comment by badlogic** [comment]
Nobody is working on it, knock yourself out. Feel free to open an (incomplete) PR for further discussion once you got a WIP. Closing this for now.

**Comment by magicgoose** [comment]
@badlogic see  #4465
