### ISSUE TITLE
Noticeable pause after pasting into a TextField when non continous rendering

### ISSUE THREAD

**Issue by WickedShell** [libgdx/libgdx#4456]
Please ensure you have given all the following requested information in your report.

#### Issue details
When non continuous rendering is enabled (only tested on desktop w/ LWJGL backend), pasting into a textfield can have a long pause that is long enough for the user to think they hit the wrong key combo and paste again.

#### Reproduction steps/code
Ran into a problem trying to get gradle to build the LWJGL tests due to some android/version problems. The code below just dropped into the template building a desktop only. (And dropping in the uiskin/default font resources).
```
package com.mygdx.game;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.Graphics;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.OrthographicCamera;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Skin;
import com.badlogic.gdx.scenes.scene2d.ui.TextField;
import com.badlogic.gdx.utils.viewport.ScreenViewport;

public class MyGdxGame extends ApplicationAdapter {
        SpriteBatch batch;
        Texture img;
        Stage stage;
        Skin skin;
        
        @Override
        public void create () {
                batch = new SpriteBatch();
                img = new Texture("badlogic.jpg");
                stage = new Stage();
                skin = new Skin(Gdx.files.internal("uiskin.json"));
                Gdx.graphics.setContinuousRendering(false);
                Gdx.input.setInputProcessor(stage);

                TextField field = new TextField("test", skin);
                field.setPosition(0, Gdx.graphics.getHeight() / 2);
                stage.addActor(field);
        }

        @Override
        public void render () {
                System.out.println("render");
                Gdx.gl.glClearColor(1, 0, 0, 1);
                Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
                batch.begin();
                batch.draw(img, 0, 0);
                batch.end();

    stage.act();
    stage.draw();
        }
        
        @Override
        public void dispose () {
                batch.dispose();
                img.dispose();
        }
}
```

#### Version of LibGDX and/or relevant dependencies
1.9.4

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [ ] MacOS

**Comment by Darkyenus** [comment]
LWJGL 2 or 3?

**Comment by WickedShell** [comment]
LWJGL 2. Non continuous rendering only just made it in for LWJGL3, and not
sure if I want to swap to that impl yet.

**Comment by NathanSweet** [comment]
I don't see any pause pasting in your example app using ctrl+c on Windows 10.

**Comment by WickedShell** [comment]
I'll redeploy to windows and test here, I was seeing problems even on
windows 10 within my full blown application.

**Comment by WickedShell** [comment]
@NathanSweet tested on windows, I can confirm it does happen on windows, but I only see it on the initial paste after launching the application, and if I cut first I don't see it. On Linux I every time, assuming I'm pasting from an external source, if I'm pasting something I yanked from the textbox I don't see a pause.

Looking at basically just under a second of pause normally here, and it doesn't appear to be length dependent (that happens for a single letter paste)

**Comment by NathanSweet** [comment]
You'll have to debug it then, because I can't reproduce the issue.

**Comment by WickedShell** [comment]
With a bit of help from @Tom-Ski tracked it down. It actually does happen with continous rendering as well. It's the access time of the clipboard, possibly (probably?) related to resolving permissions. Takes about anywhere from a half 100ms to 530 ms to actually fetch the contents of the clipboard. This manifests as a noticeable hitch. On windows with Oracle JDK I'm only seeing the hitch the first time I fetch the contents, with OpenJDK I'm seeing it everytime contents are fetched.
