### ISSUE TITLE
BitmapFonts don't load properly in GWT 2.8.0

### ISSUE THREAD

**Issue by monkeymanboy** [libgdx/libgdx#4459]
Please ensure you have given all the following requested information in your report.

#### Issue details
Simply loading in any bitmapfont causes this same error.
Also I tried printing out the contents of the font file and its all there so it isn't an issue of the file not being loaded.
EDIT: I'm not completely sure on this but it looks like it could be an issue with the Pattern class not working in gwt and this is why it isn't parsing the font file correctly

#### Reproduction steps/code
Just load any bitmapfont (even the default arial font gives the same error)
`BitmapFont font = new BitmapFont();`
#### Version of LibGDX and/or relevant dependencies
1.9.5-SNAPSHOT
#### Stacktrace
//Error message
GwtApplication: exception: Error loading font file: font.fnt
Error loading font file: font.fnt
Invalid page id:
For input string: ""

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [x] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by dsgraham81** [comment]
@monkeymanboy What did you find was the solution to fix this?  We are getting this same error right now.

**Comment by monkeymanboy** [comment]
@dsgraham81 It's not merged with the repo yet but I made a pull request with a fix so if you need it urgently use that if not then just wait for it to be merged and it will start working again.

**Comment by dsgraham81** [comment]
Ahh yeah I see your pull request doesn't look like it made it into the release of 1.9.5.  Looks like we will use 1.9.4 for our Ludum Dare project.  Thanks!
