### ISSUE TITLE
confusing try-catch in AndroidGraphics

### ISSUE THREAD

**Issue by Try4W** [libgdx/libgdx#4463]
#### Issue details
I use libgdx with rxjava with GdxScheulder that schedule tasks via `Gdx.app.postRunnable`.

There is `AndroidGraphics.java` sources's part: 

```
			for (int i = 0; i < app.getExecutedRunnables().size; i++) {
				try {
					app.getExecutedRunnables().get(i).run();
				} catch (Throwable t) {
					t.printStackTrace();
				}
			}
```
As you can see, any exception thrown by Runnable posted via `Gdx.app.postRunnable` will be ignored and app won't crash&pass it up throught call hierarchy.

#### Version of LibGDX and/or relevant dependencies
1.9.4

#### Please select the affected platforms
- [ ] Android

**Comment by badlogic** [comment]
Please submit a PR for this. It appears the other backends don't catch the exception.
