### ISSUE TITLE
Looks like Eclipse formatting settings cannot be used in IJ IDEA anymore, a replacement is needed?

### ISSUE THREAD

**Issue by magicgoose** [libgdx/libgdx#4469]
So I tried to follow CONTRIBUTING guide.

>If you work on libGDX code, we require you to use the Eclipse formatter located in the root directory of the repository.
Failure to use the formatter will result in Nate being very upset.
If you are using IntelliJ IDEA, you can still make use of the eclipse code formatter. See this article for more information.

For some reason, importing Eclipse formatting settings doesn't work, there's just no such option, and if I pretend it's IDEA xml, then it (as expected) fails to import it.

![screen shot 2016-12-09 at 9 36 06 am](https://cloud.githubusercontent.com/assets/1442206/21041448/b812f0aa-bdf3-11e6-9ca3-295cb23fbde5.png)
![screen shot 2016-12-09 at 9 37 01 am](https://cloud.githubusercontent.com/assets/1442206/21041451/ba12e8b0-bdf3-11e6-90e1-ee6ce989a7f6.png)

What do I do now?

How hard is to create an alternative for IDEA? (Using Eclipse is a big turn off for me and I'm sure for many others too)

If there's a complete specification of code style in words, I can try to go ahead and create the corresponding rules for IDEA.

**Comment by magicgoose** [comment]
What do you think about http://editorconfig.org/ ?

**Comment by sp-1234** [comment]
@magicgoose calm down. You probably just disabled "Eclipse Integration" plugin. Turn it back on and everything should work.

**Comment by magicgoose** [comment]
yep
