### ISSUE TITLE
ClassCastException in Animation.getKeyFrames()

### ISSUE THREAD

**Issue by Mur4ik** [libgdx/libgdx#4476]
#### Issue details
Affected calss com.badlogic.gdx.graphics.g2d.Animation

code:
`Animation<TextureRegion> animation = new Animation<TextureRegion>(...);`
`TextureRegion[] f = animation.getKeyFrames();`
cause:
Exception in thread "LWJGL Application" java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lcom.badlogic.gdx.graphics.g2d.TextureRegion;

this code:
`Object[] f = animation.getKeyFrames();`
does not throw exceptions

#### Version of LibGDX and/or relevant dependencies
LibGDX v1.9.5

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by Tom-Ski** [comment]
Backing array is an Object[], without a class provided in the constructor T[] will not be able to be cast.  Probably best to use an Array internally, otherwise the class would have to be passed in.

**Comment by intrigus** [comment]
Can not reproduce this issue, please add a www.sscce.org
Works fine here. At least what I tried worked fine.

**Comment by patrickhoey** [comment]
Environment:
LibGDX: LATEST from master branch on Github as of 18-Feb-2017
IntelliJ IDEA IDE Community Edition 
Java: jdk1.8.0_102
Gradle Source Compatibility = 1.8

The issue is related to which constructor overload is used in Animation.java. The constructor that takes a var-arg parameter works correctly (no issue with type erasure), but the other constructors that take an Array object result in runtime exceptions shown below.

I took the latest source of LibGDX and the following sample demonstrates the bug (related to type erasure):

The existing test class that was modified: 
\libgdx\tests\gdx-tests\src\com\badlogic\gdx\tests\AnimationTest.java

Changes to two methods:

```
import com.badlogic.gdx.utils.Array;
@Override
public void create () {
	texture = new Texture(Gdx.files.internal("data/walkanim.png"));

	Array<TextureRegion> leftWalkFrames = new Array<>();
	leftWalkFrames.addAll(TextureRegion.split(texture, 64, 64)[0]);

	Array<TextureRegion> rightWalkFrames = new Array<>(leftWalkFrames.size);

	for (int i = 0; i < rightWalkFrames.size; i++) {
		TextureRegion frame = new TextureRegion(leftWalkFrames.get(i));
		frame.flip(true, false);
		rightWalkFrames.set(i, frame);
	}
	leftWalk = new Animation<>(0.25f, leftWalkFrames);
	rightWalk = new Animation<>(0.25f, rightWalkFrames);

	cavemen = new Caveman[100];
	for (int i = 0; i < 100; i++) {
		cavemen[i] = new Caveman((float)Math.random() * Gdx.graphics.getWidth(),
			(float)Math.random() * Gdx.graphics.getHeight(), Math.random() > 0.5 ? true : false);
	}
	batch = new SpriteBatch();
	fpsLog = new FPSLogger();
}

@Override
public void render () {
	Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
	batch.begin();
	for (int i = 0; i < cavemen.length; i++) {
		Caveman caveman = cavemen[i];

		TextureRegion frame = null;

		if(caveman.headsLeft){
			frame = leftWalk.getKeyFrames()[0];
		}else{
			frame = rightWalk.getKeyFrames()[0];
		}
		batch.draw(frame, caveman.pos.x, caveman.pos.y);
	}
	batch.end();

	for (int i = 0; i < cavemen.length; i++) {
		cavemen[i].update(Gdx.graphics.getDeltaTime());
	}

	fpsLog.log();
}
```

Runtime exception and stack Trace:

> :tests:gdx-tests-jglfw:classes
> java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lcom.badlogic.gdx.graphics.g2d.TextureRegion;
> 	at com.badlogic.gdx.tests.AnimationTest.render(AnimationTest.java:95)
> 	at com.badlogic.gdx.backends.jglfw.JglfwApplication.render(JglfwApplication.java:270)
> 	at com.badlogic.gdx.backends.jglfw.JglfwApplication$2.windowRefresh(JglfwApplication.java:157)
> 	at com.badlogic.jglfw.GlfwCallbacks.windowRefresh(GlfwCallbacks.java:45)
> 	at com.badlogic.jglfw.Glfw.glfwPollEventsJni(Native Method)
> 	at com.badlogic.jglfw.Glfw.glfwPollEvents(Glfw.java:793)
> 	at com.badlogic.gdx.backends.jglfw.JglfwInput.update(JglfwInput.java:140)
> 	at com.badlogic.gdx.backends.jglfw.JglfwApplication.frame(JglfwApplication.java:221)
> 	at com.badlogic.gdx.backends.jglfw.JglfwApplication.start(JglfwApplication.java:200)
> 	at com.badlogic.gdx.backends.jglfw.JglfwApplication.initialize(JglfwApplication.java:180)
> 	at com.badlogic.gdx.backends.jglfw.JglfwApplication$1.run(JglfwApplication.java:89)
> 	at java.lang.Thread.run(Thread.java:745)
> :tests:gdx-tests-jglfw:launchTestsJglfw

	
The issue is in a constructor in Animation.java:
```
public Animation (float frameDuration, Array<? extends T> keyFrames) 
{
...
		T[] frames = (T[]) new Object[keyFrames.size];
...
}
```

One fix could be to support passing the type as a parameter to the constructor as Tom-Ski noted.

**Comment by cypherdare** [comment]
Sorry, my fault when I last updated Animation. 

Using an Array internally doesn't help because the internal Array would still need to be aware of the type.

Take a look at the PR. I updated it to use a correct type of backing array if the source Array was type aware, and I made `TextureAtlas.findRegions()` return a type-aware Array.

**Comment by cypherdare** [comment]
In this PR. the reason I didn't add a constructor to Animation that has a Class parameter is that Array already has that option, so there's no reason to clutter this class with two more constructors. But I did need to update TextureAtlas to return type-aware Arrays to take advantage of this.

**Comment by JuKu** [comment]
I get the same exception with libGDX 19.6 .

**Comment by MrStahlfelge** [comment]
Can confirm. :-(

**Comment by cypherdare** [comment]
This PR was made after the 1.9.6 release. It won't show up until 1.9.7
unless you use the snapshot.

**Comment by MrStahlfelge** [comment]
Ah, I was not aware that it was pulled in June - did only see your commit from March. Thank you for pointing out.

**Comment by samboadas221** [comment]
This still happen in 2019. Any solution?

**Comment by Darkyenus** [comment]
@samboadas221 This has already been fixed. Read the [javadoc of the constructors carefully](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g2d/Animation.java#L56).
