### ISSUE TITLE
  setCursorPosition not working properly on OSX

### ISSUE THREAD

**Issue by vladimirslav** [libgdx/libgdx#4479]
#### Issue details

I've loaded my libgdx project on OSX recently and for most part, things are working great. However, I've noticed that setCursorPosition does not work the same way as it does on Windows/Linux.

On other systems, the cursor moves to the right slowly. On OS X, however, it's jumping on one place. setCursorPosition sets the input x correctly (getX returns new value). However, on the next loop, when render is called, input.getX() is reverted to old position (for some reason).

#### Reproduction steps/code
I've created a basic libgdx project and altered render() function:
`   @Override
   public void render () {
      Gdx.gl.glClearColor(1, 0, 0, 1);
      Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
      batch.begin();
      batch.draw(img, 0, 0);
      batch.end();

      System.out.println("OLD X:" + Gdx.input.getX());
      Gdx.input.setCursorPosition(Gdx.input.getX() + 1, Gdx.input.getY());
      System.out.println("NEW X:" + Gdx.input.getX());
   }`

#### Version of LibGDX and/or relevant dependencies
LibGDX Nightly build, took it on December 7.
Java: Oracle JDK 8 (if that changes something)

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [X] MacOS

Thanks!

**Comment by xoppa** [comment]
Which backend are you using?

**Comment by vladimirslav** [comment]
I am using the default one, lwjgl. (The launches imports com.badlogic.gdx.backends.lwjgl.LwjglApplication).

**Comment by vladimirslav** [comment]
Just a heads-up: I've updated to 1.9.5 and the issue is still there. I've also tried using lwjgl's Mouse.setPosition and Mouse.getX() directly and the results are the same.

**Comment by NathanSweet** [comment]
It appears there is nothing we can do on our end. LWJGL2 is getting old and no longer maintained. Consider using LWJGL3, if possible.
