### ISSUE TITLE
TextArea.setAlignment is not working

### ISSUE THREAD

**Issue by SamehMahmoud** [libgdx/libgdx#4480]
#### Issue details
setAlignment is not effecting text area alignment at all ! just text message is effected by alignment.

#### Version of LibGDX and/or relevant dependencies
Latest

Thanks

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info

**Comment by MobiDevelop** [comment]
I don't think we're ever going to get more info.
