### ISSUE TITLE
BitmapFont use regex (not work in GWT)

### ISSUE THREAD

**Issue by SergeyLabutin** [libgdx/libgdx#4485]
#### Issue details
BitmapFont use regex (not work in GWT)

#### Reproduction steps/code
import java.util.regex.Matcher;
import java.util.regex.Pattern;

#### Version of LibGDX and/or relevant dependencies
1.9.5

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [x] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by MobiDevelop** [comment]
There are currently two PRs open to fix this, no need to also make a separate issue.
