### ISSUE TITLE
Libgdx html (gwt) font error - Invalid page id

### ISSUE THREAD

**Issue by okilimnik** [libgdx/libgdx#4490]
When I try to run html application I get this error in browser:

GwtApplication: exception: Error loading font file: fonts/comic-en.fnt 
Error loading font file: fonts/comic-en.fnt 
Invalid page id: 
For input string: ""

Android build runs always successfully, the font file is correct. This bug happens even while running libgdx sample projects or using a standard font like:

`BitmapFont font = new BitmapFont();`

 Is there some secret magic?

Libgdx version  - 1.9.5
The project is generated by gdx-setup.jar

**Comment by slarbu** [comment]
Fixed in #4475
