### ISSUE TITLE
root in TiledMapLoader.loadAsync is not set

### ISSUE THREAD

**Issue by Lucrecious** [libgdx/libgdx#4494]
#### Issue details
I get this exception when I try to load a TiledMap asynchronously.
```java
Caused by: java.lang.NullPointerException
	at com.badlogic.gdx.maps.tiled.TmxMapLoader.loadTilemap(TmxMapLoader.java:158)
	at com.badlogic.gdx.maps.tiled.TmxMapLoader.loadAsync(TmxMapLoader.java:110)
```

#### Reproduction steps/code
Trivial reproduction.
Initialize a new TmxMapLoader, and use the loadAsync method.
Here's the line of code that causes grief:
`String mapOrientation = root.getAttribute("orientation", null);`
Clearly, "root" is the null exception.

However, even if root was set, loadAsync assumes that the required dependancies (i.e. texture files) have already been loaded, so it still fails (I tried running loadAsync after a call to "getDependancies" and I still get exceptions regarding loads).
So loadAsync isn't really "loadAsync".  I can't finish loading the required dependancies either because I'm on a different thread, which means, I'd have to load them in from outside in a thread with the OpenGL context.

All this to say: loadAsync, doesn't seems to work as intended?

Am I using loadAsync incorrectly?

Thanks.

#### Version of LibGDX and/or relevant dependencies
Latest

#### Stacktrace
Provided above

#### Please select the affected platforms
Probably affects all platforms.

**Comment by MobiDevelop** [comment]
You should be using AssetManager for loading asynchronously, rather than calling loadAsync directly.
