### ISSUE TITLE
[Feature Request] Ability to apply lighting to decals.

### ISSUE THREAD

**Issue by Vichy97** [libgdx/libgdx#4497]
It isn't possible to apply lighting using an Environment (or any other way I'm aware of) to a Decal. There should be a way to pass an Environment to the DecalBatch.

**Comment by cypherdare** [comment]
I think this would be best realized as a subclass of CameraGroupStrategy that also takes an Environment parameter and has a built-in default shader that works with lights.

**Comment by cypherdare** [comment]
It's not possible with the DecalBatch library because it doesn't have enough vertex attributes. You can try my FlexBatch library. It doesn't yet take an environment however. I might add it someday if I have a need for lit decals but you're welcome to do a PR.
