### ISSUE TITLE
[Feature Request] Create a reset method for Gdx.input.getX and Y

### ISSUE THREAD

**Issue by LogicWrite** [libgdx/libgdx#4505]
this is the despription of the method `Gdx.input.getX()`

`/** @return The x coordinate of the last touch on touch screen devices and the current mouse position on desktop for the first
	 *         pointer in screen coordinates. The screen origin is the top left corner. */
`
we should place a method for reset all the pointers to (0,0)

**Comment by MobiDevelop** [comment]
What would be the benefit of resetting these to 0?

**Comment by nhydock** [comment]
Best thing I can think of is if you move your mouse outside of the window on desktop you might want the mouse to return to origin, and same with touch if you're not touching the phone you might want it to be at origin.  I can't think of any personal use cases for such a feature, but someone else probably can.

**Comment by xoppa** [comment]
Yeah, my guess is that providing incorrect coordinates (0,0 is valid but incorrect) will cause more issues than there are valid use-cases.

Closing this, @LogicWrite  please read this again: https://github.com/libgdx/libgdx/blob/master/.github/CONTRIBUTING.md#feature-requests.
Will reopen if the required information is provided.
