### ISSUE TITLE
Ask about other libs integration

### ISSUE THREAD

**Issue by tes1oner** [libgdx/libgdx#4507]
Please ensure you have given all the following requested information in your report.

#### Issue details
_It is possible to integrate LibGDX with other libraries, example for the use of web services, without this affecting the product in different platforms (eg iOS)_

#### Detalles
_Es posible integrar LibGDX con otras librerías, ejemplo para el uso de servicios web, sin que esto afecte el producto en las distintas plataformas(ej, iOS)_

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
