### ISSUE TITLE
[Feature Request] Input Emulation

### ISSUE THREAD

**Issue by nhydock** [libgdx/libgdx#4508]
With LibGDX providing an input abstraction for all backends, I feel it could be useful to also provide emulation features for the Input interface so developers may programmatically invoke input events.  

Such a feature can be used for testing UIs, testing game logic dependent on input, or even doing scripted tutorials, all while following through the standardized input handling interfaces.

**Comment by Flame6332** [comment]
This seems unnecessary if proper code is created with functions that control movements instead of input events. I can see your point though.

**Comment by nhydock** [comment]
Yeah, with clean and abstract implementation of your logic relating to input, it can be unnecessary.  However, with input emulation you can also expose features that are not typically available on your platform, such as gyroscopes on desktop, so it allows for quick and dirty ways to test and enable functionality without rewriting code.

There's also the advantage of being able to write input hook applications and jars for libgdx applications that can allow you to play/test them without knowing how the input logic was written to be handled by the app's execution, because you'll just be firing basic input events.

**Comment by badlogic** [comment]
Implement the Inout interface, wrap the actual Input object, then intercept calls and either forward to the backend implementation, or create your own responses. Finally, set your wrapper on Gdx.input. This is how we implemented the old gdx-remote (control desktop app with Android device).
