### ISSUE TITLE
Performance improvement when clearing *Map classes

### ISSUE THREAD

**Issue by tdionizio** [libgdx/libgdx#4510]
When clearing a Map instance the `keyTable` array is traversed in reverse order when setting the array elements to `EMPTY`, thus clearing the array.

When iterating in 'normal' order the JVM seems to be able to optimize the loop and can see great improvements.

Current code (excerpt from IntIntMap.clear()):
```java
for (int i = capacity + stashSize; i-- > 0;)
	keyTable[i] = EMPTY;
```

Changing it to
```java
for (int i = 0, n = capacity + stashSize; i < n; i++)
	keyTable[i] = EMPTY;
```

or even using `Arrays.fill(keyTable, 0, capacity + stashSize, EMPTY);` brings noticable performance improvements.

Stumbled upon it when doing tests with ModelCache and changing the IntIntMap as mentioned brought an improvement from ~200 to ~250 fps (just for reference, ignoring what and how it was being tested) clearly showing this change can be useful.

Other Map classes should be changed in the same way.

Can contribute with a push request, just can't do it sometime soon, but leaving this suggestion in case someone has any interest in doing it first.

**Comment by yuripourre** [comment]
It was fixed!
