### ISSUE TITLE
iOS Accelerometer broken using MOE

### ISSUE THREAD

**Issue by aaimister** [libgdx/libgdx#4511]
#### Issue details
I updated to the lastest LibGDX [1.9.5] & MOE [1.2.5] versions and this broke the Accelerometer on iOS.
The Accelerometer works with LibGDX [1.9.5], MOE[1.2.2] & Build Tools [1.5.0].
This may be an issue with the newest version of MOE and not LibGDX.

#### Reproduction steps/code
You can test using my current project at: http://pastebin.com/xxb8KKAL

#### Version of LibGDX and/or relevant dependencies
LibGDX 1.9.5
MOE 1.2.5
Build Tools 2.2.0

#### Stacktrace
none

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [X] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
Please can you provide a single application adapter that reproduces your issue, thats quite the codebase to submit for an issue like this.  https://github.com/libgdx/libgdx/wiki/Getting-help#executable-example-code

**Comment by aaimister** [comment]
I'll work up a quick project soon.  =)

**Comment by Tom-Ski** [comment]
You don't need to provide a whole project, a single class should be sufficient.

**Comment by aaimister** [comment]
Updated comment with barebones skeleton of issue.  http://pastebin.com/xxb8KKAL

**Comment by crykn** [comment]
iOS moe is discontinued.
