### ISSUE TITLE
[BUG] Gradle update does not install Bullet past 1.9.2

### ISSUE THREAD

**Issue by Flame6332** [libgdx/libgdx#4516]
To update libGDX, one must open the build.gradle file in their libGDX Gradle project and change the version specification of gdxVersion to whichever version they choose. In my testing project, I realized it was out of date and updated the project as usual. This time, however, everywhere that a Bullet reference was located, and error showed up. After some digging, I found that the gdx-bullet.jar had completely disappeared from all projects. After multiple Gradle updates to see where this issue occurs, I discovered that when updating to any libGDX build over version 1.9.2, the jar disappears completely and all you are left with is gdx-bullet-platform.jar that contains nothing but a META-INF file inside. I believe this is a bug as it occurs with other libGDX projects.

If its of any importance, this project was originally created in version 1.7.0.

For a reference, here is the build.gradle file:

<br><br><br>
<b>
buildscript {
    repositories {
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        jcenter()
    }
    dependencies {
        classpath 'de.richsource.gradle.plugins:gwt-gradle-plugin:0.6'
    }
}

allprojects {
    apply plugin: "eclipse"
    apply plugin: "idea"

    version = '1.0'
    ext {
        appName = "JBox2D_Workspace"
        gdxVersion = '1.9.2'
        roboVMVersion = '1.8.0'
        box2DLightsVersion = '1.4'
        ashleyVersion = '1.6.0'
        aiVersion = '1.5.0'
    }

    repositories {
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url "https://oss.sonatype.org/content/repositories/releases/" }
    }
}

project(":desktop") {
    apply plugin: "java"

    dependencies {
        compile project(":core")
        compile "com.badlogicgames.gdx:gdx-backend-lwjgl:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
        compile "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-desktop"
        compile "com.badlogicgames.gdx:gdx-controllers-desktop:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx-controllers-platform:$gdxVersion:natives-desktop"
        compile "com.badlogicgames.gdx:gdx-bullet-platform:$gdxVersion:natives-desktop"
    }
}

project(":html") {
    apply plugin: "gwt"
    apply plugin: "war"

    dependencies {
        compile project(":core")
        compile "com.badlogicgames.gdx:gdx-backend-gwt:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx:$gdxVersion:sources"
        compile "com.badlogicgames.gdx:gdx-backend-gwt:$gdxVersion:sources"
        compile "com.badlogicgames.gdx:gdx-box2d:$gdxVersion:sources"
        compile "com.badlogicgames.gdx:gdx-box2d-gwt:$gdxVersion:sources"
        compile "com.badlogicgames.gdx:gdx-controllers:$gdxVersion:sources"
        compile "com.badlogicgames.gdx:gdx-controllers-gwt:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx-controllers-gwt:$gdxVersion:sources"
        compile "com.badlogicgames.box2dlights:box2dlights:$box2DLightsVersion:sources"
    }
}

project(":core") {
    apply plugin: "java"

    dependencies {
        compile "com.badlogicgames.gdx:gdx:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx-controllers:$gdxVersion"
        compile "com.badlogicgames.box2dlights:box2dlights:$box2DLightsVersion"
        compile "com.badlogicgames.gdx:gdx-bullet-platform:$gdxVersion"
       
    }
}

tasks.eclipse.doLast {
    delete ".project"
}</b>

**Comment by Tom-Ski** [comment]
In your core section you have 
` compile "com.badlogicgames.gdx:gdx-bullet-platform:$gdxVersion"
`
when it should be 
`compile "com.badlogicgames.gdx:gdx-bullet:$gdxVersion"`
