### ISSUE TITLE
New reflected Class not included when executing the application with GWT superDev mode

### ISSUE THREAD

**Issue by LennartH** [libgdx/libgdx#4518]
#### Issue details
It seems like the reflection cache isn't updated, when you test the application with the GWT superDev mode (`gradle html:superDev`). This leads to the error `Couldn't find Type for class`, when the application is recompiled, after a new class thats used with reflection has been added.

#### Reproduction steps/code
1. Include an empty package to the reflection
```
<module>
	<source path="com.application" />
	
	<extend-configuration-property name="gdx.reflect.include" value="com.application.reflect.me" />
</module>
```
2. Start the code server (e.g. with `gradle html:superDev`)
3. Test that the application runs error free
4. Create a new class in the previously added package and create a new instance with the reflection API
5. Recompile the application

#### Workaround
1. Stop the coder server
2. ~~Package the application for the web (e.g. with `gradle html:dist`)~~
3. Start the code server again

If there's no way to fix this properly, please add a note to the [reflection wiki page](https://github.com/libgdx/libgdx/wiki/Reflection#gwt).

#### Version of LibGDX and/or relevant dependencies
1.9.6-SNAPSHOT

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [x] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
Confirmed, looks like the cache gets recreated on compile, but it doesn't pick up any changes. @MobiDevelop any ideas?

The workaround just requires shutting down the superDev instance and restarting it, no dist required.

**Comment by LennartH** [comment]
Yes, I can confirm that restarting the superDev instance is enough to update the reflection cache.

I don't think that there's an easy way to fix this, since other frameworks that rely on reflection (like artemis-odb) have the same issue. But a note in the reflection wiki page would be helpful.

**Comment by MrStahlfelge** [comment]
There are some other things not updated or recompiled when you just recompile from superDevMode, for example assets or changed dependencies.  As TomSki said, you have to shutdown the server and restart the compilation process.
