### ISSUE TITLE
HTML/GWT only loading the 'badlogic.jpg' image

### ISSUE THREAD

**Issue by pentolope** [libgdx/libgdx#4543]
I'm fairly new to libgdx, so I could have simply missed something, but for some reason, the only asset I can load when running a html project is the default 'badlogic.jpg' image. 
I just downloaded the most recent setup jar, generated the project (I used tools and Box2d plugins), and imported the gradle project into intellij and did the other steps needed to start a desktop application, which works great. 
This happens regardless if I have the android configuration checked. Even if I rename the file in the assets folder, it still loads on the webpage. But the really weird part is that if I delete every badlogic.jpg image in my entire project and restarting my ide and html server, it still loads on the webpage. My only guess it that something isn't updating, but I can't find what or how to fix it. 
For example, if I try to load 'badlogics.jpg' (only by adding a 's' to the 'img = new Texture("badlogic.jpg");' in the default code), the webpage spits out 
"GwtApplication: exception: Couldn't load image 'badlogics.jpg',file does not exist
Couldn't load image 'badlogics.jpg', file does not exist"
even if it really does exist in the assets folder.
I have started the html project within the terminal with 'gradlew html:superDev' and with by ide and gradle by adding it as a run configuration, the setting for that are as follows 
Gradle project: Game:html 
Tasks: html:superDev

I am on Windows 10, if that helps.

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker

**Comment by pentolope** [comment]
What is wrong with my post? As far as I can tell, it is an issue with libgdx. I've searched and tried things for over 6 hours trying to figure out what is wrong. I read that document already. What about it? Was I not clear enough? Do you need more information?

**Comment by MobiDevelop** [comment]
It's not a problem with libgdx as much as it is a problem with your browser
caching old files. Try clearing your browser cache.

**Comment by pentolope** [comment]
Huh. Well that worked... Thank you.
