### ISSUE TITLE
PixmapPacker.pack method may change Pixmap.Blending value

### ISSUE THREAD

**Issue by serpent7776** [libgdx/libgdx#4552]
#### Issue details
Running multiple instances of `PixmapPacker` on background thread may change `Pixmap.Blending` value to `Pixmap.Blending.None`.
This is caused by `PixmapPacker.pack` method changing `Pixmap.Blending` which is global state: https://github.com/libgdx/libgdx/blob/1.9.5/gdx/src/com/badlogic/gdx/graphics/g2d/PixmapPacker.java#L174

#### Reproduction steps/code
Run multiple instances on PixmapPacker on background thread. Eventually `Pixmap.Blending` will be changed to `Pixmap.Blending.None`.

#### Version of LibGDX and/or relevant dependencies
1.9.x

#### Please select the affected platforms
Probably all of them, observed on android and iOS.
- [x] Android
- [x] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
Are you using multiple instances of `PixmapPacker` across multiple threads, or are you running them all on the same thread?

**Comment by serpent7776** [comment]
This occured when using multiple threads, each having it's own instance of `PixmapPacker`.
Thanks for fixing this.

**Comment by BenMcLean** [comment]
This change does not work on GWT!! Please fix.

**Comment by BenMcLean** [comment]
Fixed in commit 46d4a62fec74c2c821cf3fbd1831719552041b1d
Thanks.
