### ISSUE TITLE
Couldn't load shared library 'gdx64.dll' for target: Windows 10, 64-bit

### ISSUE THREAD

**Issue by zjc121** [libgdx/libgdx#4553]
how to fix it?

**Comment by agmcleod** [comment]
You'll need to give some more details on what you're doing exactly to cause this error. Is this from a built game? Is this when you try to compile/run your project? Did you use setup.gdx?

**Comment by zjc121** [comment]
is a runtime exception  
i download gdx from github

**Comment by agmcleod** [comment]
For creating a project, i strongly suggest using the setup jar file: https://libgdx.badlogicgames.com/nightlies/dist/gdx-setup.jar, and then have a look in the wiki: for getting it going in your IDE of choice.
