### ISSUE TITLE
"News" page of official site is empty 

### ISSUE THREAD

**Issue by raincole** [libgdx/libgdx#4556]
[https://libgdx.badlogicgames.com/news.html](https://libgdx.badlogicgames.com/news.html)

It's empty for a long time.

**Comment by Darkyenus** [comment]
It has used a google feed API, which ["is officially deprecated and will stop working after December 15th, 2016"](https://developers.google.com/feed/). Time for a rewrite :/

**Comment by Tom-Ski** [comment]
Thanks, we have an issue open for this on the site's repo.
