### ISSUE TITLE
SequenceAction: unusable without an actor

### ISSUE THREAD

**Issue by denisk20** [libgdx/libgdx#4558]
I don't use Actors in my current project, but I do use Actions and Pools. So far I've been successful in using `FloatAction` and `ColorAction` without attaching Actors to them -- that is I call `act(delta)` directly and get the values from the actions. 
However it's different with `SequesceAction`: if I don't set an actor it will always execute only the first action and ignore the rest. From `SequenceAction.act(delta)`:

```
...
if (actions.get(index).act(delta)) {
	if (actor == null) return true; // This action was removed.
...
```
My understanding was that some Actions are intended to be actor-agnostic (at least I can see an effort to make them like that). Why is it different with `SequenceAction`? If I can use `ColorAction` without attaching an actor to it I should be able to chain several `ColorAction`s using `SequenceAction`, still without attaching an actor, no?

**Comment by Tom-Ski** [comment]
The Action system is built with specific use with Scene2d in mind. The actor agnostic Actions aren't there because an effort was made to make them Actor agnostic, but because they don't need to manipulate the actor itself (the actor is not the target). 

Using all Actions outside of scene2D would require a rewrite of the Actions system to allow it to do things it was never intended to to.  

Perhaps a tweening engine would be more useful for you?

**Comment by denisk20** [comment]
My question was in fact about SequenceAction only, I'm aware that many actions (such as `MoveByAction`, `RotateByAction` etc.) can't be used outside of scene2D, they just don't make sense without an attached actor. `SequenceAction` doesn't look like one of them, it seems that it could very well function without an attached actor. This is proofed by the fact that if I attach an empty dummy actor it executes all underlying actions correctly. Maybe it would make sense to make it a dual-purpose action, similar to `ColorAction` which can function with or without an attached actor. If it's acceptable I can try to come up with a pull request.

**Comment by Tom-Ski** [comment]
I know, as I said those actions that look like they can be used outside of scene2D only do so because they don't manipulate the target actor.
