### ISSUE TITLE
Default gitignore is too restrictive

### ISSUE THREAD

**Issue by mgsx-dev** [libgdx/libgdx#4560]
gitignore file generated by gdx setup have undesirable side effects : any folder you want to track with git (including java package) which is named "war", "build", "out" or "bin" will be ignored. Note that I discovered this issue creating a "war" game with a "war" package name somewhere, so other developers  may face the same problem.

IMO best practice is to avoid recursive path in gitignore as much as possible (all path without a leading slash are processed recursively).

My proposal would be to keep some global recursive ignore in the root file (*.class, *.project ...) and dispatch specific parts to related sub-project : For instance, "war/" would be replaced by "/war" and moved to web sub-project.

What do you think ?

**Comment by Tom-Ski** [comment]
Sure, PR welcome, let's keep it at one master .gitignore though

----- Reply message -----
