### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by zjc121** [libgdx/libgdx#4568]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000065591ce0, pid=6304, tid=0x0000000000001098
#
# JRE version: Java(TM) SE Runtime Environment (8.0_111-b14) (build 1.8.0_111-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.111-b14 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [gdx64.dll+0x11ce0]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x0000000018a2e800):  JavaThread "LWJGL Application" [_thread_in_native, id=4248, stack(0x000000001a2e0000,0x000000001a3e0000)]

siginfo: ExceptionCode=0xc0000005, writing address 0x000000000000000d

Registers:
RAX=0x0000000065581790, RBX=0x0000000016f04ff8, RCX=0x0000000000000001, RDX=0x0000000018a2b060
RSP=0x000000001a3de708, RBP=0x000000001a3de780, RSI=0x0000000018a2e800, RDI=0x00000000ffffffff
R8 =0x0000000000000001, R9 =0x0000000018a2b060, R10=0x0000000002747f48, R11=0x000000005d3cb580
R12=0x0000000000000000, R13=0x0000000016f04ff8, R14=0x000000001a3de7a0, R15=0x0000000018a2e800
RIP=0x0000000065591ce0, EFLAGS=0x0000000000010202

Top of Stack: (sp=0x000000001a3de708)
0x000000001a3de708:   0000000002747f74 0000000018a2e800
0x000000001a3de718:   0000000016f04ff8 0000000018a2e800
0x000000001a3de728:   0000000018a2e800 000000001a3de7f0
0x000000001a3de738:   0000000002747ca2 000000001a3de740
0x000000001a3de748:   0000000016f04ff8 000000001a3de7a0
0x000000001a3de758:   0000000016f05190 0000000000000000
0x000000001a3de768:   0000000016f04ff8 0000000000000000
0x000000001a3de778:   000000001a3de7a0 000000001a3de7e8
0x000000001a3de788:   000000000273835d 00000000d63fd988
0x000000001a3de798:   00000000027419d8 0000000000000001
0x000000001a3de7a8:   000000001a3de7a8 0000000016f02d09
0x000000001a3de7b8:   000000001a3de7f0 0000000016f05190
0x000000001a3de7c8:   0000000000000000 0000000016f02d18
0x000000001a3de7d8:   000000001a3de7a0 000000001a3de7f8
0x000000001a3de7e8:   000000001a3de8d0 00000000027308da
0x000000001a3de7f8:   0000000000000000 0000000000000000 

Instructions: (pc=0x0000000065591ce0)
0x0000000065591cc0:   53 48 83 ec 20 48 89 cb 48 8b 49 18 e8 ff 2c 02
0x0000000065591cd0:   00 48 89 d9 48 83 c4 20 5b e9 f2 2c 02 00 66 90
0x0000000065591ce0:   89 51 0c c3 66 66 66 2e 0f 1f 84 00 00 00 00 00
0x0000000065591cf0:   89 51 10 c3 66 66 66 2e 0f 1f 84 00 00 00 00 00 

Register to memory mapping:

RAX=0x0000000065581790 is an unknown value
RBX={method} {0x0000000016f05000} 'setBlend' '(I)V' in 'com/badlogic/gdx/graphics/g2d/Gdx2DPixmap'
RCX=0x0000000000000001 is an unknown value
RDX=0x0000000018a2b060 is an unknown value
RSP=0x000000001a3de708 is pointing into the stack for thread: 0x0000000018a2e800
RBP=0x000000001a3de780 is pointing into the stack for thread: 0x0000000018a2e800
RSI=0x0000000018a2e800 is a thread
RDI=0x00000000ffffffff is an unallocated location in the heap
R8 =0x0000000000000001 is an unknown value
R9 =0x0000000018a2b060 is an unknown value
R10=0x0000000002747f48 is at code_begin+840 in an Interpreter codelet
method entry point (kind = native)  [0x0000000002747c00, 0x0000000002748560]  2400 bytes
R11=0x000000005d3cb580 is an unknown value
R12=0x0000000000000000 is an unknown value
R13={method} {0x0000000016f05000} 'setBlend' '(I)V' in 'com/badlogic/gdx/graphics/g2d/Gdx2DPixmap'
R14=0x000000001a3de7a0 is pointing into the stack for thread: 0x0000000018a2e800
R15=0x0000000018a2e800 is a thread

Stack: [0x000000001a2e0000,0x000000001a3e0000],  sp=0x000000001a3de708,  free space=1017k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [gdx64.dll+0x11ce0]
C  0x0000000002747f74

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.setBlend(I)V+0
j  com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.<clinit>()V+1
v  ~StubRoutines::call_stub
j  com.badlogic.gdx.graphics.Pixmap.<init>(Lcom/badlogic/gdx/files/FileHandle;)V+15
j  com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(Lcom/badlogic/gdx/files/FileHandle;Lcom/badlogic/gdx/graphics/Pixmap$Format;Z)Lcom/badlogic/gdx/graphics/TextureData;+99
j  com.badlogic.gdx.graphics.Texture.<init>(Lcom/badlogic/gdx/files/FileHandle;Lcom/badlogic/gdx/graphics/Pixmap$Format;Z)V+4
j  com.badlogic.gdx.graphics.Texture.<init>(Lcom/badlogic/gdx/files/FileHandle;)V+4
j  de.swagner.paxbritannica.Resources.<init>()V+23
j  de.swagner.paxbritannica.Resources.getInstance()Lde/swagner/paxbritannica/Resources;+10
j  de.swagner.paxbritannica.background.Debris.<init>(Lcom/badlogic/gdx/math/Vector2;)V+194
j  de.swagner.paxbritannica.background.BackgroundFXRenderer.createDebris()V+39
j  de.swagner.paxbritannica.background.BackgroundFXRenderer.<init>()V+43
j  de.swagner.paxbritannica.mainmenu.MainMenu.<init>(Lcom/badlogic/gdx/Game;)V+43
j  de.swagner.paxbritannica.PaxBritannica.create()V+6
j  com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop()V+29
j  com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run()V+27
v  ~StubRoutines::call_stub

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x00000000006ae800 JavaThread "DestroyJavaVM" [_thread_blocked, id=6312, stack(0x0000000002120000,0x0000000002220000)]
=>0x0000000018a2e800 JavaThread "LWJGL Application" [_thread_in_native, id=4248, stack(0x000000001a2e0000,0x000000001a3e0000)]
  0x000000001733e000 JavaThread "Service Thread" daemon [_thread_blocked, id=6916, stack(0x0000000018f30000,0x0000000019030000)]
  0x0000000017327000 JavaThread "C1 CompilerThread2" daemon [_thread_blocked, id=3280, stack(0x0000000018e30000,0x0000000018f30000)]
  0x00000000172ff000 JavaThread "C2 CompilerThread1" daemon [_thread_blocked, id=8684, stack(0x0000000018d30000,0x0000000018e30000)]
  0x00000000172f9000 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=3596, stack(0x0000000018c30000,0x0000000018d30000)]
  0x00000000172f7800 JavaThread "Attach Listener" daemon [_thread_blocked, id=5544, stack(0x0000000018b30000,0x0000000018c30000)]
  0x0000000018673800 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=6836, stack(0x0000000018a30000,0x0000000018b30000)]
  0x000000000272d000 JavaThread "Finalizer" daemon [_thread_blocked, id=604, stack(0x0000000018530000,0x0000000018630000)]
  0x0000000002722000 JavaThread "Reference Handler" daemon [_thread_blocked, id=4264, stack(0x0000000018430000,0x0000000018530000)]

Other Threads:
  0x00000000172a7000 VMThread [stack: 0x0000000018330000,0x0000000018430000] [id=112]
  0x00000000186d5800 WatcherThread [stack: 0x0000000019320000,0x0000000019420000] [id=7380]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap:
 PSYoungGen      total 38400K, used 10877K [0x00000000d5980000, 0x00000000d8400000, 0x0000000100000000)
  eden space 33280K, 32% used [0x00000000d5980000,0x00000000d641f568,0x00000000d7a00000)
  from space 5120K, 0% used [0x00000000d7f00000,0x00000000d7f00000,0x00000000d8400000)
  to   space 5120K, 0% used [0x00000000d7a00000,0x00000000d7a00000,0x00000000d7f00000)
 ParOldGen       total 87552K, used 0K [0x0000000080c00000, 0x0000000086180000, 0x00000000d5980000)
  object space 87552K, 0% used [0x0000000080c00000,0x0000000080c00000,0x0000000086180000)
 Metaspace       used 6320K, capacity 6595K, committed 6912K, reserved 1056768K
  class space    used 620K, capacity 656K, committed 768K, reserved 1048576K

Card table byte_map: [0x0000000011af0000,0x0000000011ef0000] byte_map_base: 0x00000000116ea000

Marking Bits: (ParMarkBitMap*) 0x000000005d9ba6c0
 Begin Bits: [0x00000000125a0000, 0x0000000014570000)
 End Bits:   [0x0000000014570000, 0x0000000016540000)

Polling page: 0x0000000000600000

CodeCache: size=245760Kb used=2075Kb max_used=2075Kb free=243684Kb
 bounds [0x0000000002730000, 0x00000000029a0000, 0x0000000011730000]
 total_blobs=815 nmethods=402 adapters=326
 compilation: enabled

Compilation events (10 events):
Event: 1.806 Thread 0x0000000017327000 nmethod 397 0x000000000292f050 code [0x000000000292f1c0, 0x000000000292f388]
Event: 1.806 Thread 0x0000000017327000  398   !   3       java.lang.ClassLoader::getPackage (118 bytes)
Event: 1.807 Thread 0x00000000172ff000 nmethod 396 0x0000000002937650 code [0x00000000029377a0, 0x0000000002937918]
Event: 1.807 Thread 0x0000000017327000 nmethod 398 0x0000000002936590 code [0x0000000002936760, 0x0000000002937268]
Event: 1.810 Thread 0x0000000017327000  400       3       java.net.URLClassLoader$1::run (5 bytes)
Event: 1.810 Thread 0x0000000017327000 nmethod 400 0x00000000029361d0 code [0x0000000002936340, 0x00000000029364e8]
Event: 1.810 Thread 0x0000000017327000  401   !   3       java.net.URLClassLoader$1::run (63 bytes)
Event: 1.810 Thread 0x0000000017327000 nmethod 401 0x0000000002935810 code [0x00000000029359e0, 0x0000000002935f08]
Event: 1.813 Thread 0x0000000017327000  402       3       java.io.FilterInputStream::read (9 bytes)
Event: 1.813 Thread 0x0000000017327000 nmethod 402 0x0000000002935190 code [0x0000000002935300, 0x0000000002935528]

GC Heap History (0 events):
No events

Deoptimization events (0 events):
No events

Internal exceptions (10 events):
Event: 0.318 Thread 0x00000000006ae800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d5c58878) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u111\7883\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
Event: 0.318 Thread 0x00000000006ae800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d5c58a88) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u111\7883\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
Event: 0.320 Thread 0x00000000006ae800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d5c5c6d0) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u111\7883\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
Event: 0.320 Thread 0x00000000006ae800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d5c5c8e0) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u111\7883\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
Event: 0.507 Thread 0x00000000006ae800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d5db8d80) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u111\7883\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
Event: 0.508 Thread 0x00000000006ae800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d5dbaa58) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u111\7883\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
Event: 0.508 Thread 0x00000000006ae800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d5dbbbc8) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u111\7883\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
Event: 0.508 Thread 0x00000000006ae800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d5dc0d30) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u111\7883\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
Event: 0.508 Thread 0x00000000006ae800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d5dc1988) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u111\7883\hotspot\src\share\vm\prims\jvm.cpp, line 1386]
Event: 0.508 Thread 0x00000000006ae800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d5dc25b0) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u111\7883\hotspot\src\share\vm\prims\jvm.cpp, line 1386]

Events (10 events):
Event: 1.811 loading class sun/net/DefaultProgressMeteringPolicy
Event: 1.811 loading class sun/net/ProgressMeteringPolicy
Event: 1.811 loading class sun/net/ProgressMeteringPolicy done
Event: 1.811 loading class sun/net/DefaultProgressMeteringPolicy done
Event: 1.812 loading class com/badlogic/gdx/utils/StreamUtils
Event: 1.812 loading class com/badlogic/gdx/utils/StreamUtils done
Event: 1.812 loading class com/badlogic/gdx/utils/StreamUtils$OptimizedByteArrayOutputStream
Event: 1.812 loading class com/badlogic/gdx/utils/StreamUtils$OptimizedByteArrayOutputStream done
Event: 1.813 loading class com/badlogic/gdx/graphics/g2d/Gdx2DPixmap
Event: 1.813 loading class com/badlogic/gdx/graphics/g2d/Gdx2DPixmap done

Dynamic libraries:
0x00007ff69bfe0000 - 0x00007ff69c017000 	C:\Program Files\Java\jre1.8.0_111\bin\javaw.exe
0x00007ffcca450000 - 0x00007ffcca621000 	C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ffcc9a70000 - 0x00007ffcc9b1b000 	C:\WINDOWS\System32\KERNEL32.DLL
0x00007ffcc7500000 - 0x00007ffcc771d000 	C:\WINDOWS\System32\KERNELBASE.dll
0x00007ffcc9b20000 - 0x00007ffcc9bc2000 	C:\WINDOWS\System32\ADVAPI32.dll
0x00007ffcca350000 - 0x00007ffcca3ee000 	C:\WINDOWS\System32\msvcrt.dll
0x00007ffcc97f0000 - 0x00007ffcc9849000 	C:\WINDOWS\System32\sechost.dll
0x00007ffcc9ef0000 - 0x00007ffcca011000 	C:\WINDOWS\System32\RPCRT4.dll
0x00007ffcc98c0000 - 0x00007ffcc9a25000 	C:\WINDOWS\System32\USER32.dll
0x00007ffcc6b80000 - 0x00007ffcc6b9e000 	C:\WINDOWS\System32\win32u.dll
0x00007ffcc9a30000 - 0x00007ffcc9a64000 	C:\WINDOWS\System32\GDI32.dll
0x00007ffcc69f0000 - 0x00007ffcc6b72000 	C:\WINDOWS\System32\gdi32full.dll
0x00007ffcc1ed0000 - 0x00007ffcc2149000 	C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.14393.447_none_42191651c6827bb3\COMCTL32.dll
0x00007ffcca080000 - 0x00007ffcca348000 	C:\WINDOWS\System32\combase.dll
0x00007ffcc7840000 - 0x00007ffcc7935000 	C:\WINDOWS\System32\ucrtbase.dll
0x00007ffcc7720000 - 0x00007ffcc778a000 	C:\WINDOWS\System32\bcryptPrimitives.dll
0x00007ffcc81e0000 - 0x00007ffcc820e000 	C:\WINDOWS\System32\IMM32.DLL
0x000000005d0c0000 - 0x000000005d192000 	C:\Program Files\Java\jre1.8.0_111\bin\msvcr100.dll
0x000000005d1a0000 - 0x000000005da3a000 	C:\Program Files\Java\jre1.8.0_111\bin\server\jvm.dll
0x00007ffcc7b20000 - 0x00007ffcc7b28000 	C:\WINDOWS\System32\PSAPI.DLL
0x00007ffcbe700000 - 0x00007ffcbe709000 	C:\WINDOWS\SYSTEM32\WSOCK32.dll
0x00007ffcc7d30000 - 0x00007ffcc7d9a000 	C:\WINDOWS\System32\WS2_32.dll
0x00007ffcc4d40000 - 0x00007ffcc4d63000 	C:\WINDOWS\SYSTEM32\WINMM.dll
0x00007ffcc2e40000 - 0x00007ffcc2e4a000 	C:\WINDOWS\SYSTEM32\VERSION.dll
0x00007ffcc4d10000 - 0x00007ffcc4d3b000 	C:\WINDOWS\SYSTEM32\WINMMBASE.dll
0x00007ffcc6d70000 - 0x00007ffcc6db2000 	C:\WINDOWS\System32\cfgmgr32.dll
0x000000005d0b0000 - 0x000000005d0bf000 	C:\Program Files\Java\jre1.8.0_111\bin\verify.dll
0x000000005d080000 - 0x000000005d0a9000 	C:\Program Files\Java\jre1.8.0_111\bin\java.dll
0x000000005d060000 - 0x000000005d076000 	C:\Program Files\Java\jre1.8.0_111\bin\zip.dll
0x00007ffcc8220000 - 0x00007ffcc9729000 	C:\WINDOWS\System32\SHELL32.dll
0x00007ffcc6e20000 - 0x00007ffcc74fa000 	C:\WINDOWS\System32\windows.storage.dll
0x00007ffcc68f0000 - 0x00007ffcc693c000 	C:\WINDOWS\System32\powrprof.dll
0x00007ffcca020000 - 0x00007ffcca072000 	C:\WINDOWS\System32\shlwapi.dll
0x00007ffcc68e0000 - 0x00007ffcc68ef000 	C:\WINDOWS\System32\kernel.appcore.dll
0x00007ffcc7790000 - 0x00007ffcc7839000 	C:\WINDOWS\System32\shcore.dll
0x00007ffcc68c0000 - 0x00007ffcc68d4000 	C:\WINDOWS\System32\profapi.dll
0x0000000065580000 - 0x0000000065616000 	C:\Users\zjc\AppData\Local\Temp\libgdxzjc\1bf02e4c\gdx64.dll
0x00007ffcc6380000 - 0x00007ffcc6397000 	C:\WINDOWS\SYSTEM32\CRYPTSP.dll
0x00007ffcc5df0000 - 0x00007ffcc5e23000 	C:\WINDOWS\system32\rsaenh.dll
0x00007ffcc6490000 - 0x00007ffcc64bb000 	C:\WINDOWS\SYSTEM32\bcrypt.dll
0x00007ffcc6060000 - 0x00007ffcc607f000 	C:\WINDOWS\SYSTEM32\USERENV.dll
0x00007ffcc63a0000 - 0x00007ffcc63ab000 	C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
0x000000005d040000 - 0x000000005d05a000 	C:\Program Files\Java\jre1.8.0_111\bin\net.dll
0x00007ffcc61e0000 - 0x00007ffcc623c000 	C:\WINDOWS\system32\mswsock.dll
0x00007ffcc5f70000 - 0x00007ffcc5fa8000 	C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
0x00007ffcc81d0000 - 0x00007ffcc81d8000 	C:\WINDOWS\System32\NSI.dll
0x00007ffcc0f20000 - 0x00007ffcc0f36000 	C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
0x00007ffcc0ee0000 - 0x00007ffcc0efa000 	C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
0x000000005d020000 - 0x000000005d031000 	C:\Program Files\Java\jre1.8.0_111\bin\nio.dll
0x0000000180000000 - 0x0000000180053000 	C:\Users\zjc\AppData\Local\Temp\libgdxzjc\dc0f0009\lwjgl64.dll
0x00007ffcaaa80000 - 0x00007ffcaaba3000 	C:\WINDOWS\SYSTEM32\OPENGL32.dll
0x00007ffcae7f0000 - 0x00007ffcae81d000 	C:\WINDOWS\SYSTEM32\GLU32.dll
0x00007ffcb4570000 - 0x00007ffcb4667000 	C:\WINDOWS\SYSTEM32\DDRAW.dll
0x00007ffcbea90000 - 0x00007ffcbea98000 	C:\WINDOWS\SYSTEM32\DCIMAN32.dll
0x0000000019420000 - 0x0000000019484000 	C:\Users\zjc\AppData\Local\Temp\libgdxzjc\dc0f0009\OpenAL64.dll
0x00007ffcc79e0000 - 0x00007ffcc7b17000 	C:\WINDOWS\System32\ole32.dll
0x00007ffcc4f90000 - 0x00007ffcc5025000 	C:\WINDOWS\system32\uxtheme.dll
0x00007ffcc7c90000 - 0x00007ffcc7d2f000 	C:\WINDOWS\System32\clbcatq.dll
0x00007ffcc41a0000 - 0x00007ffcc4325000 	C:\WINDOWS\System32\PROPSYS.dll
0x00007ffcc9730000 - 0x00007ffcc97ef000 	C:\WINDOWS\System32\OLEAUT32.dll
0x00007ffcc7940000 - 0x00007ffcc79dc000 	C:\WINDOWS\System32\msvcp_win.dll
0x00007ffcab8a0000 - 0x00007ffcab93b000 	C:\WINDOWS\SYSTEM32\dsound.dll
0x00007ffcc13e0000 - 0x00007ffcc1451000 	C:\WINDOWS\System32\MMDevApi.dll
0x00007ffcc5540000 - 0x00007ffcc5568000 	C:\WINDOWS\System32\DEVOBJ.dll
0x00007ffcabe40000 - 0x00007ffcabed4000 	C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
0x00007ffcc3810000 - 0x00007ffcc3946000 	C:\WINDOWS\SYSTEM32\wintypes.dll
0x00007ffcc7b30000 - 0x00007ffcc7c8b000 	C:\WINDOWS\System32\MSCTF.dll
0x00007ffcc44e0000 - 0x00007ffcc4506000 	C:\WINDOWS\system32\dwmapi.dll
0x000000005a680000 - 0x000000005c4ec000 	C:\WINDOWS\SYSTEM32\nvoglv64.DLL
0x00007ffcc7da0000 - 0x00007ffcc81c9000 	C:\WINDOWS\System32\SETUPAPI.dll
0x00007ffcc4160000 - 0x00007ffcc4173000 	C:\WINDOWS\SYSTEM32\WTSAPI32.dll
0x00007ffcbd880000 - 0x00007ffcbda12000 	C:\WINDOWS\SYSTEM32\dbghelp.dll
0x00007ffcc6dc0000 - 0x00007ffcc6e15000 	C:\WINDOWS\System32\WINTRUST.dll
0x00007ffcc68b0000 - 0x00007ffcc68c0000 	C:\WINDOWS\System32\MSASN1.dll
0x00007ffcc6ba0000 - 0x00007ffcc6d69000 	C:\WINDOWS\System32\CRYPT32.dll
0x00007ffcc5cc0000 - 0x00007ffcc5cf2000 	C:\WINDOWS\SYSTEM32\ntmarta.dll
0x00007ffcc2580000 - 0x00007ffcc2611000 	C:\WINDOWS\SYSTEM32\mscms.dll
0x00007ffcad800000 - 0x00007ffcad842000 	C:\WINDOWS\SYSTEM32\icm32.dll
0x00007ffcc5a20000 - 0x00007ffcc5a76000 	C:\WINDOWS\SYSTEM32\WINSTA.dll
0x00007ffcc5840000 - 0x00007ffcc58df000 	C:\WINDOWS\system32\dxgi.dll
0x00007ffcc34d0000 - 0x00007ffcc3786000 	C:\WINDOWS\system32\d3d11.dll
0x00007ffcc2e90000 - 0x00007ffcc2f25000 	C:\WINDOWS\SYSTEM32\DriverStore\FileRepository\nvdmwu.inf_amd64_26aa6356770b2e86\nvumdshimx.dll
0x00007ffcc2e50000 - 0x00007ffcc2e82000 	C:\WINDOWS\System32\DriverStore\FileRepository\nvdmwu.inf_amd64_26aa6356770b2e86\nvinitx.dll
0x000000005c4f0000 - 0x000000005c4f6000 	C:\Program Files\NVIDIA Corporation\CoProcManager\_etoured.dll
0x00007ffcba700000 - 0x00007ffcba73a000 	C:\Program Files\NVIDIA Corporation\CoProcManager\nvd3d9wrapx.dll
0x00007ffcba890000 - 0x00007ffcba8b4000 	C:\Program Files\NVIDIA Corporation\CoProcManager\nvdxgiwrapx.dll
0x00007ffca19e0000 - 0x00007ffca2d5a000 	C:\WINDOWS\System32\DriverStore\FileRepository\nvdmwu.inf_amd64_26aa6356770b2e86\nvwgf2umx.dll

VM Arguments:
jvm_args: -Dfile.encoding=GBK 
java_command: de.swagner.paxbritannica.desktop.DesktopLauncher
java_class_path (initial): C:\Users\zjc\Downloads\android\newone\libgdx-demo-pax-britannica-master\desktop\bin;C:\gradle\caches\modules-2\files-2.1\com.badlogicgames.gdx\gdx-backend-lwjgl\1.9.6-SNAPSHOT\90789ced691e1a20fabc8d746f8ef34d4bf572bc\gdx-backend-lwjgl-1.9.6-SNAPSHOT.jar;C:\gradle\caches\modules-2\files-2.1\com.badlogicgames.gdx\gdx-platform\1.9.6-SNAPSHOT\f9f10c8987f0772ebbf4e6f3a153fdf6e0b7c51d\gdx-platform-1.9.6-SNAPSHOT-natives-desktop.jar;C:\gradle\caches\modules-2\files-2.1\com.badlogicgames.jlayer\jlayer\1.0.1-gdx\7cca83cec5c1b2f011362f4d85aabd71a73b049d\jlayer-1.0.1-gdx.jar;C:\gradle\caches\modules-2\files-2.1\net.java.jinput\jinput-platform\2.0.5\385ee093e01f587f30ee1c8a2ee7d408fd732e16\jinput-platform-2.0.5-natives-windows.jar;C:\gradle\caches\modules-2\files-2.1\net.java.jinput\jinput-platform\2.0.5\53f9c919f34d2ca9de8c51fc4e1e8282029a9232\jinput-platform-2.0.5-natives-osx.jar;C:\gradle\caches\modules-2\files-2.1\net.java.jinput\jinput-platform\2.0.5\7ff832a6eb9ab6a767f1ade2b548092d0fa64795\jinput-platform-2.0.5-natives-linux.jar;C:\gradle\caches\modules-2\files-2.1\net.java.jinput\jinput\2.0.5\39c7796b469a600f72380316f6b1f11db6c2c7c4\jinput-2.0.5.jar;C:\gradle\caches\modules-2\files-2.1\net.java.jutils\jutils\1.0.0\e12fe1fda814bd348c1579329c86943d2cd3c6a6\jutils-1.0.0.jar;C:\gradle\caches\modules-2\files-2.1\org.jcraft\jorbis\0.0.17\8872d22b293e8f5d7d56ff92be966e6dc28ebdc6\jorbis-0.0.17.jar;C:\gradle\caches\modules-2\files-2.1\org.lwjgl.lwjgl\lwjgl-platform\2.9.2\510c7d317f5e9e700b9cfaac5fd38bdebf0702e0\lwjgl-platform-2.9.2-natives-windows.jar;C:\gradle\caches\modules-2\files-2.1\org.lwjgl.lwjgl\lwjgl-platform\2.9.2\d276cdf61fe2b516c7b7f4aa1b8dea91dbdc8d56\lwjgl-platform-2.9.2-natives-linux.jar;C:\gradle\caches\modules-2\files-2.1\org.lwjgl.lwjgl\lwjgl-platform\2.9.2\d55b46b40b40249d627a83a7f7f22649709d70c3\lwjgl-platform-2.9.2-natives-osx.jar;C:\gradle\caches\modules-2\files-2.1\org.lwjgl.lwjgl\lwjgl\2.9.2\a9d80fe5935c7a9149f6584d9777cfd471f6
Launcher Type: SUN_STANDARD

Environment Variables:
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_111
PATH=C:/Program Files/Java/jre1.8.0_111/bin/server;C:/Program Files/Java/jre1.8.0_111/bin;C:/Program Files/Java/jre1.8.0_111/lib/amd64;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\VisualSVN Server\bin;C:\Program Files\Java\jdk1.8.0_111\bin;C:\Users\zjc\Downloads\gradle-3.2\bin;C:\Users\zjc\Downloads\apache-tomcat-9.0.0.M13\bin;C:\Program Files\Java\jdk1.8.0_111\jre\bin;C:\Users\zjc\AppData\Local\Microsoft\WindowsApps;C:\Users\zjc\Downloads\gradle-3.2\bin;;C:\Users\zjc\Desktop;
USERNAME=zjc
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 42 Stepping 7, GenuineIntel

---------------  S Y S T E M  ---------------

OS: Windows 10.0 , 64 bit Build 14393 (10.0.14393.0)

CPU:total 4 (2 cores per cpu, 2 threads per core) family 6 model 42 stepping 7, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, aes, clmul, ht, tsc, tscinvbit

Memory: 4k page, physical 8332856k(4231564k free), swap 9119288k(4237632k free)

vm_info: Java HotSpot(TM) 64-Bit Server VM (25.111-b14) for windows-amd64 JRE (1.8.0_111-b14), built on Sep 22 2016 19:24:05 by "java_re" with MS VC++ 10.0 (VS2010)

time: Wed Jan 25 21:41:05 2017
elapsed time: 1 seconds (0d 0h 0m 1s)

**Comment by Tom-Ski** [comment]
Please stop creating issues that completely bypass the issue template.
