### ISSUE TITLE
ARM/RPI Support for GDX Headless

### ISSUE THREAD

**Issue by littletinman** [libgdx/libgdx#4571]
I am working on setting up a Jenkins server to run all my unit tests on a Raspberry Pi 3 I have. Everything works flawlessly up until my unit tests need to reference GDX elements (mocked or otherwise). I understand the in theory LibGDX is not meant for the Pi family, but being able to at least support it headless would be amazing for hobbyists like myself.

#### Issue details
Currently when I run my test project on Raspbian with Jenkins I get:
~~~~
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'libgdxarmgnueabihf.so' for target: Linux, 32-bit
~~~~

#### Reproduction steps/code
1. Get a Raspi 3
2. Install Rasbian
3. Install Android Studio
4. Using the SDK Manager install the necessary versions of dependencies (https://libgdx.badlogicgames.com/versions.html)
5. Setup a GDX project and some unit tests (https://github.com/TomGrill/gdx-testing for instructions)
6. Run your tests

#### Version of LibGDX and/or relevant dependencies
LibGDX: 1.9.5
Raspbian:  4.4.26-v7+
Raspi: 3

#### Stacktrace
```java
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'libgdxarmgnueabihf.so' for target: Linux, 32-bit
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:119)
	at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:33)
	at com.badlogic.gdx.backends.headless.HeadlessNativesLoader.load(HeadlessNativesLoader.java:24)
	at com.badlogic.gdx.backends.headless.HeadlessApplication.<init>(HeadlessApplication.java:66)
	at com.philiproyer.battleroom.tests.GdxTestRunner.<init>(GdxTestRunner.java:40)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] MacOS

Potential people for input: @TomGrill (https://github.com/TomGrill/gdx-testing) @natdan (https://github.com/natdan/rpi-libgdx-example)

**Comment by krukhlis** [comment]
I doubt LibGdx supports Raspberry Pi at all.That's why it can't find its own native library that is compatible with RPi.

**Comment by littletinman** [comment]
@krukhlis While currently it does not, a few years ago it used to support ARM (from what I understand) and there are working ports for Raspberry Pi but they require a separate DesktopLauncher and dependancies. See https://github.com/natdan/rpi-libgdx-example for example.

**Comment by intrigus** [comment]
I don't think that any core contributer has a Raspberry Pi which makes it hard to test a Rpi port. 
So you either implement it yourself or you have to sponsor a Rpi for some contributor.

**Comment by MobiDevelop** [comment]
I have a Raspberry Pi 3... Problem is I don't have a lot of time to work on it.

**Comment by natdan** [comment]
Problem seems not to be in contributors having RPi or not (I am quite happy to donate one if that would make any difference) but updating build scripts in correct way so it builds RPi favour of ARM libraries. Check here:

https://github.com/libgdx/libgdx/pull/3196#event-557304403

Anyone happy to invest time and understand all the issues about how to seamlessly integrate RPi build in existing LibGDX build could help a lot. Until then I decided to try to keep up with current version in off official repository (hence example above) with jogl impl. as that was only one I could reproduce following discussions on RPi forums and/or here. Soon I get time I'll update to the latest snapshot + push everything to github so everyone can reproduce unofficial RPi build themselves.

**Comment by littletinman** [comment]
@intrigus I'd be happy to donate a Raspi or two for the cause!

@MobiDevelop I think that's what I saw about ARM support and assumed it included desktop. Thank you for clarifying.

@natdan You are my hero! It's been super fun being able to deploy a branch of my game on the Raspi and let my kid have at it.

**Comment by simondid** [comment]
has there been made any progress on this topic ?

**Comment by natdan** [comment]
Not that I am aware.

**Comment by MrStahlfelge** [comment]
@PokeMMO can this get closed now?

**Comment by PokeMMO** [comment]
Yeah, headless should work just fine on ARM on SNAPSHOT builds.
