### ISSUE TITLE
Desktop/Win7: Gdx.input.isKeyPressed(Keys.BACK) is TRUE, when I change the volume!?

### ISSUE THREAD

**Issue by Swift42** [libgdx/libgdx#4572]
I would like to report a very strange problem:
I'm using a Logitech G-110 keyboard. The keyboard has a volume-wheel and a mute button.
When used, the volume will be changed in Windows (as expected). This works in/from every app without any problems.

But when my LibGdx-app is running and I use the wheel OR the key, Gdx.input.isKeyPressed(Keys.BACK) will be true! This results in unwanted behaviour, because my code then calls the previous screen (this is actually implemented for android).

To fix this, I now ignore the Back-Key on Desktop, but nevertheless I wanted to report this bug/strange behavior.

OS: Windows 7
Libgdx: 1.9.5

**Comment by DarkMuesli** [comment]
I can confirm this behaviour on Windows 10, libGDX 1.9.4

Specified behaviour occurs when pressing the volume up, volume down **or** mute function buttons on my asus laptop.

Also, this behaviour affects the polling based input through `Gdx.input.isKeyPressed()`, but **not** the event based input through the `keyDown()` method of a `InputProcessor`, which i think is even more critical.

**Comment by MrStahlfelge** [comment]
Can someone check if this is still a thing, and if it concerns Lwjgl2 or Lwjgl3 backend?

**Comment by MrStahlfelge** [comment]
Closed, apparently no one concerned any more.
