### ISSUE TITLE
RoboVM: audio doesn't pause when app goes to background

### ISSUE THREAD

**Issue by Try4W** [libgdx/libgdx#4575]
#### Reproduction steps/code
1. start playing something with newMusic
2. pause app (press home button)

#### Version of LibGDX and/or relevant dependencies
gdxVersion = '1.9.5'
roboVMVersion = '2.3.0'

#### Please select the affected platforms
- [ ] iOS (RoboVM)

**Comment by TomGrill** [comment]
Isn't the music stream not supposed to continue playing when the app goes to background. Like a MP3 player does?

**Comment by Try4W** [comment]
On Android it works so. (see AndroidApplication implementation)

**Comment by GiGurra** [comment]
Hmm this does NOT happen to me. I'm also deploying to ios with robovm 2.3.0, gdx 1.9.5.
Iphone 6 here.

**Comment by Try4W** [comment]
Yeah, I just tried to deploy my app to physical device instead of simulator and get that behaviour that you described.

It looks like libgdx's developers relay on how iOS manage app's audio output instead of pausing it manually.

But still, on iOS emulator(iPhone 5s) audio keep playing even after app is paused.
