### ISSUE TITLE
MOE FileHandle.list() always return empty array

### ISSUE THREAD

**Issue by alexandr2levin** [libgdx/libgdx#4577]
#### Reproduction steps/code
![image](https://cloud.githubusercontent.com/assets/5736157/22398736/7c24da6c-e59f-11e6-812e-3c2b021b3ed6.png)
```java
	@Override
	public void create () {
		batch = new SpriteBatch();
		img = new Texture("badlogic.jpg");

		FileHandle dirFileHandle = Gdx.files.internal("some_dir/");
		FileHandle[] filesList = dirFileHandle.list();

		Gdx.app.log(TAG, "filesList.length: " + filesList.length);
	}
```

#### Version of LibGDX and/or relevant dependencies
libgdx 1.9.5
'org.multi-os-engine:moe-gradle:1.3.0-beta-2'

#### Output on MOE
`MyGdxGame 4 filesList.length: 0`

#### Output on RoboVM
`[info] MyGdxGame: filesList.length: 3`

#### Please select the affected platforms
- [ ] iOS (MOE)

**Comment by xoppa** [comment]
Try an external folder instead of an internal folder.

**Comment by Try4W** [comment]
The same result.
`Gdx.files.external("some_dir/");`

`MyGdxGame 4 filesList.length: 0`

**Comment by xoppa** [comment]
The file must exist on external storage and contain files ofcourse. Simply replacing the word internal with external wont work.

**Comment by Try4W** [comment]
I understend. But I want to get files list inside "assets" dir, not from external storage.

Also I have no idea how libgdx's external storage looks&works on ios. (and how it can be edited)
On Android external storage is sdcard.
On iOS — ?

**Comment by crykn** [comment]
Closing this, as the iOS moe backend is discontinued.
