### ISSUE TITLE
[GWT] WebGL low frame rate.

### ISSUE THREAD

**Issue by SergeyLabutin** [libgdx/libgdx#4578]
After fix error, fps increases from 11 to 29, and from 20 to 60.

#### Issue details
GwtGL20 in backend-gwt have function glGetError. Seems it is incredible slow operation for WebGL, without any gl errors. For fix need hardcode return 0; without call native function.

#### Version of LibGDX and/or relevant dependencies
1.9.5

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [x] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info

**Comment by SergeyLabutin** [comment]
public class GwtGL20 implements GL20
...
public int glGetError () {
-	return gl.getError();
+	return 0;
}
Profit x3 fps in any browser.

**Comment by xoppa** [comment]
Sounds like you are trying to solve the wrong problem. If you dont want to call gl.getError then just dont call glGetError. Anyways, use the forum for personal support requests with your code design. Closing this. If you still think there's an issue with libgdx, then please provide the required information and reopen.

**Comment by SergeyLabutin** [comment]
Sorry. Really production use Debug build, because if you build in gradle with gwt plugin second itteration not clear war.

Fix for me write function in clean remove war folder before any build.

Steps for reproduse.
1 Build debug
2 Build release

Because code not changed only env for build gradle think UP-TO-DATE files.

Not shure that this problem libgdx, this problem gwt plugin for gradle.

But maybe good idea add to generated code for html project:
task cleanWar(type: Delete) {
    delete fileTree(dir: 'war')
}
clean.dependsOn cleanWar

P.S. Sorry if this not libgdx problem, i understand each maybe make in own project this code.
