### ISSUE TITLE
scale is always = UIScreen.mainScreen().nativeScale()

### ISSUE THREAD

**Issue by doit-ceo** [libgdx/libgdx#4589]
#### Issue details
Just looking at the internal code of moe-ios and I found this line that seems not correct 

float scale = (float)(getIosVersion() >= 8 ? UIScreen.mainScreen().nativeScale() : UIScreen.mainScreen().nativeScale());

This is line 138 in IOSApplication.java

Note : that this has no effect on me so far, but the developer have the same code (UIScreen.mainScreen().nativeScale()) in both parts of this condition !
#### Version of LibGDX and/or relevant dependencies
1.9.5

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ X] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by MrStahlfelge** [comment]
Closed, we have removed moe.
