### ISSUE TITLE
GWT build will not load without Flash On Some Browsers

### ISSUE THREAD

**Issue by ajayyy** [libgdx/libgdx#4590]
Please ensure you have given all the following requested information in your report.

#### Issue details
When trying to run on a fresh Ubuntu install with Firefox, the game does not load, and an error appears in the console. (in stacktrace section)

I even have preferFlash to false:

```
public GwtApplicationConfiguration getConfig () {
        	GwtApplicationConfiguration config = new GwtApplicationConfiguration(getWindowInnerWidth(), getWindowInnerHeight());
        	config.preferFlash = false;
            return config;
        }
```

This appears: 

![](https://i.stack.imgur.com/yao56.png)

#### Reproduction steps/code
Running a game on Firefox on fresh Ubuntu. Here is a link to my test game in case you need it: http://ajayinkingston.com/splats/

#### Version of LibGDX and/or relevant dependencies
1.9.5 and 1.9.4 seem to have this issue.

#### Stacktrace

```
SoundManager: No Flash detected. Trying HTML5-only mode. soundmanager2-jsmin.js:32:357
SoundManager V2.97a.20130512 (AS3/Flash 9) + HTML5 audio soundmanager2-jsmin.js:32:357
SoundManager 2: soundManager: Fatal error: Flash is needed to play some required formats, but is not available. soundmanager2-jsmin.js:32:357
SoundManager 2 HTML5 support: mp3 = false (using flash), mp4 = false (using flash), ogg = true, opus = true, wav = true soundmanager2-jsmin.js:32:357
soundManager: No Flash response within expected time. Likely causes: Flash blocked or JS-Flash security error. soundmanager2-jsmin.js:32:357
soundManager: Waiting indefinitely for Flash (will recover if unblocked)...
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [x] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Mur4ik** [comment]
Have You tried **config.preferFlash = false** in **GwtApplicationConfiguration** ?

**Comment by ajayyy** [comment]
@Mur4ik Yes, sorry I forgot to include it in the post. I have set preferFlash to false.

**Comment by Mur4ik** [comment]
In which format your sound assets is (mp3, ogg)?

```
SoundManager 2: soundManager: Fatal error: Flash is needed to play some required formats, but is not available. soundmanager2-jsmin.js:32:357
SoundManager 2 HTML5 support: mp3 = false (using flash), mp4 = false (using flash), ogg = true, opus = true, wav = true soundmanager2-jsmin.js:32:357
```
That is true for old FF versions.

But in fresh FF without flash plugin installed, your app get in console:
```
SoundManager 2: No Flash detected. Trying HTML5-only mode.  soundmanager2-jsmin.js:33:488
SoundManager V2.97a.20150601 (HTML5-only mode)  soundmanager2-jsmin.js:33:488
SoundManager 2 HTML5 support: mp3 = true, mp4 = true, ogg = true, opus = true, wav = true  soundmanager2-jsmin.js:33:488
SoundManager 2: Ready. ✓
```

**Comment by ajayyy** [comment]
@Mur4ik That means it started and is working, I just didn't have the multiplayer servers running.

So, it's just an issue with old Firefox, that makes sense. But, I am not using any sound at the moment, so they are not **required** formats. Is this a bug?

**Comment by Mur4ik** [comment]
Can you please provide a versions of Ubuntu and Firefox that cause an issue?
And Soundmanager2 V2.97a.20130512 (from libGDX 1.9.5 and below) and V2.97a.20150601 (from libGDX 1.9.6-SNAPSHOT) have the same behavior?
Does update Firefox to latest version fix the issue?

**Comment by Mur4ik** [comment]
And one other thing that can be as a workaround is set mp3 and mp4 formats not required for SoundManager2 initialization:
```
// somewhere in your GwtApplicationLuncher
private native void tempWorkaroundForIssue4590() /*-{
    $wnd.soundManager.audioFormats.mp3.required = false;
    $wnd.soundManager.audioFormats.mp4.required = false;
}-*/;
```
and then call that method from your overrided getConfig for example.

But that is only my assumption, I have not try this.

And yes, looks like bug (or by design behavior) in SM2

**Comment by intrigus** [comment]
I'll send a PR which adds a config, to entirely disable sound when not needed.

**Comment by ajayyy** [comment]
@Mur4ik That workaround looks perfect, I will try that out. And I'll see what version of Firefox it is. It is the preinstalled version on an Ubuntu LiveCD.

@intrigus that looks cool.

**Comment by ajayyy** [comment]
@Mur4ik It is Firefox version 47.0, and I can't get the workaround working because sound manager is not recognized as a variable. But, I will keep tweaking it to try to get it to work.

**Comment by Mur4ik** [comment]
Look at the https://github.com/libgdx/libgdx/blob/master/backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtApplication.java
after onModuleLoad native $wnd.soundManager sould be available
    ```
@Override
    public void onModuleLoad() {
        super.onModuleLoad();

        tempWorkaroundForIssue4590();
    }

    private native void tempWorkaroundForIssue4590() /*-{
        $wnd.soundManager.audioFormats.mp3.required = false;
        $wnd.soundManager.audioFormats.mp4.required = false;
    }-*/;
```

**Comment by ajayyy** [comment]
@Mur4ik Did you purposely delete that?

**Comment by ajayyy** [comment]
@Mur4ik awesome, I will try that. Thanks a lot for your help.

**Comment by Mur4ik** [comment]
Its another dirty way without patching soundmanager2-jsmin.js.

1. Create class CustomGwtApplication.java in package com.badlogic.gdx.backends.gwt inside your html/src folder
```
package com.badlogic.gdx.backends.gwt;

import com.badlogic.gdx.backends.gwt.preloader.Preloader;
import com.badlogic.gdx.backends.gwt.soundmanager2.SoundManager;
import com.badlogic.gdx.utils.Timer;

public abstract class CustomGwtApplication extends GwtApplication {
    @Override
    public void onModuleLoad () {
        super.onModuleLoad();

        Timer.schedule(new Timer.Task() {
            @Override
            public void run() {
                if (!SoundManager.ok() || getPreloader() == null) {
                    startPreloader();
                }
            }
        }, 3);
    }

    private void startPreloader() {
        final Preloader.PreloaderCallback callback = getPreloaderCallback();
        preloader = createPreloader();
        preloader.preload("assets.txt", new Preloader.PreloaderCallback() {
            @Override
            public void error (String file) {
                callback.error(file);
            }

            @Override
            public void update (Preloader.PreloaderState state) {
                callback.update(state);
                if (state.hasEnded()) {
                    getRootPanel().clear();
                    if (loadingListener != null) loadingListener.beforeSetup();
                    setupLoop();
                    if (loadingListener != null) loadingListener.afterSetup();
                }
            }
        });
    }
}
```
2. Extend your HtmlLauncher.java from newly created CustomGwtApplication

Hope that clear for you.

**Comment by BenMcLean** [comment]
It is worth emphasizing that this happens even with Flash installed and homestarrunner.com working right

**Comment by ajayyy** [comment]
But does the disabling mp3s fix this for flash too?

**Comment by BenMcLean** [comment]
Since my game didn't use sound anyway, this is really frustrating. I've got it happening on all browsers now on Windows 10: Chrome, FireFox AND Edge.

I wish there was some way to build for the web which didn't even attempt to use sound.

**Comment by ajayyy** [comment]
@BenMcLean My game doesn't use sound either, that's why I was confused and posted the issue. It's really weird.

**Comment by ajayyy** [comment]
@BenMcLean Oh, are you getting the random ones? I had a workaround that had java script that checked the page for the error message once libgdx was loaded, then refreshed the page if it saw it.

**Comment by ajayyy** [comment]
Wait, so now I can disable sound?

**Comment by intrigus** [comment]
Yup,
you just have to change your GwtApplicationConfiguration.

**Comment by ajayyy** [comment]
@intrigus That's Awesome! Thank you! I just realised though I'd have to wait until a new update right?

**Comment by intrigus** [comment]
You'd have to build from source or you'd have to wait for a new Snapshot.

**Comment by ajayyy** [comment]
Ok, that makes sense. Thanks for your help.
