### ISSUE TITLE
Update documentation about using Scala + SBT 

### ISSUE THREAD

**Issue by molikto** [libgdx/libgdx#4591]
Sorry for not following the format. But this is not a bug. Only about documentation.

If anyone is interested in using SBT + Scala with MobiDevelop's fork of RoboVM, then one should use

1. this fork of sbt-robovm https://github.com/molikto/sbt-robovm, you need too publish-local this plugin.
2. this fork of project templete https://github.com/Darkyenus/libgdx-sbt-project.g8 and setting sbt-robovm and RoboVM version to 2.3.0. Then it will resolve to the plugin publish-local'ed

Scala + Gradle works but I found IntelliJ IDEA is extremely buggy with this combination

**Comment by Tom-Ski** [comment]
https://github.com/libgdx/libgdx/wiki/Using-libGDX-with-other-JVM-languages would be an appropriate place for this.
