### ISSUE TITLE
Closing the application window resets desktop color tinting from redshift

### ISSUE THREAD

**Issue by jtara1** [libgdx/libgdx#4593]
#### Issue details

After closing the window from the desktop launcher, the color tinting resets to none / white then tints the screen again 2-3 seconds later.

#### Reproduction steps/code

0. Install redshift on Ubuntu 16.04 64bit and run it (there should be some noticeable color shift)
1. On Ubuntu 16.04 64bit, create libgdx project using gdx-setup.jar
2. Open new libgdx project in Eclipse
3. Run the desktop launcher
4. Close the libgdx game application
5. The color shift occurs here

#### Version of LibGDX and/or relevant dependencies
from build.gradle
```
    apply plugin: "eclipse"
    apply plugin: "idea"

    version = '1.0'
    ext {
        appName = "my-gdx-game"
        gdxVersion = '1.9.5'
        roboVMVersion = '2.3.0'
        box2DLightsVersion = '1.4'
        ashleyVersion = '1.7.0'
        aiVersion = '1.8.0'
    }
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] MacOS

#### Code ran
MyGdxGame.java
```java
package com.mygdx.game;

import com.badlogic.gdx.*;
import com.badlogic.gdx.graphics.GL20;


public class MyGdxGame extends ApplicationAdapter {
    public void create () {
        // your code here
    }

    public void render () {
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        // your code here
    }
}
```

DesktopLauncher.java
```java
package com.mygdx.game.desktop;

import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration;
import com.mygdx.game.MyGdxGame;

public class DesktopLauncher {
	public static void main (String[] arg) {
		LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
		new LwjglApplication(new MyGdxGame(), config);
	}
}
```

**Comment by Tom-Ski** [comment]
Redshift issue.

**Comment by RUSshy** [comment]
It also happen on macOS with F.lux
In Windows i can't reproduce

I guess it's a LWJGL issue in their multiplatform code
