### ISSUE TITLE
public constructors for backend FileHandle

### ISSUE THREAD

**Issue by Longri** [libgdx/libgdx#4595]
Is it possible to make the constructors of the individual backend FileHandle public, as with the LwjglFileHandle?

I need to create a FileHandle instance before Gdx.App/ Gdx.files is initialized.

**Comment by Tom-Ski** [comment]
AndroidFileHandles aren't usable until LibGDX has been initialized, so this wouldn't help you.  What exactly do you need to do before LibGDX is initialized?

**Comment by Longri** [comment]
Ok, you are right, I wanted to configure my logger with a Config-File.
I will rework my code, so that log messages are cached until Gdx is initialized and I have read the Config-File.
If this is done, then I will process the stored log's again and fire if it corresponds to the Config.

sorry, can close
