### ISSUE TITLE
Pixel Stuttering when rotating an object and fixating the camera to one point

### ISSUE THREAD

**Issue by pFreak** [libgdx/libgdx#4600]
#### Issue details
I'm trying to rotate a Texture, fixate the camera to one point of it and also rotate the camera when the texture rotates.
That way I want my camera to stay on the exact same point and look like nothing is moving, although the object itself is indeed rotating.
When doing so I see pixel-stuttering on the rotated texture ( https://youtu.be/t72ZhC4Ejm4 ).

#### Reproduction steps/code
Rotate an object and use the projectionMatrix to fixate your camera to one point of it that you calculate relative to the rotation of the object. Then apply the same rotation to the camera that you apply to the texture. That way from the camera perspective everything should look like nothing is changing, since you cancle out all moving factors.
The problem is that you still see pixel-movement inside the texture.
**I attached a Demo-Project that reproduces this exact issue:**
[test.zip](https://github.com/libgdx/libgdx/files/768326/test.zip)

Here is the Code from the Game-Class 
```

package com.mygdx.game;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.OrthographicCamera;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.graphics.g2d.TextureRegion;
import com.badlogic.gdx.math.MathUtils;
import com.badlogic.gdx.math.Vector2;
import com.badlogic.gdx.utils.viewport.ScreenViewport;
import com.badlogic.gdx.utils.viewport.Viewport;

public class MyGdxGame extends ApplicationAdapter {
    private static final int SIZE = 500;

    private Viewport viewport = new ScreenViewport();
    private SpriteBatch batch;
    private TextureRegion img;
    private float rotation = 0f;

    @Override
    public void create() {
        batch = new SpriteBatch();
        img = new TextureRegion(new Texture("badlogic.jpg"));
    }

    @Override
    public void render() {
        // Creating Viewport
        viewport.update(Gdx.graphics.getWidth(), Gdx.graphics.getHeight(), true);
        OrthographicCamera camera = (OrthographicCamera) viewport.getCamera();
        camera.viewportWidth = 1000;
        camera.viewportHeight = 1000;
        camera.zoom = 0.1F;

        final float camMod = Gdx.graphics.getDeltaTime() * 300F;
        rotation = translateRotation(rotation + camMod);

        final Vector2 pos = localToParentCoordinates(new Vector2(SIZE / 2, SIZE / 2));
        camera.position.set(pos, 0);
        camera.rotate(-camMod);
        camera.update();

        Gdx.gl.glClearColor(1, 0, 0, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        batch.setProjectionMatrix(camera.combined);
        batch.begin();
        batch.draw(img, -SIZE / 2, -SIZE / 2, SIZE / 2, SIZE / 2, SIZE, SIZE, 1, 1, rotation);
        batch.end();
    }

    public Vector2 localToParentCoordinates(Vector2 localCords) {
        final float cos = MathUtils.cosDeg(360F - rotation);
        final float sin = MathUtils.sinDeg(360F - rotation);
        return new Vector2(
                localCords.x * cos + localCords.y * sin,
                localCords.x * -sin + localCords.y * cos
        );
    }

    public static float translateRotation(float degrees) {
        while (degrees > 360F) {
            degrees -= 360F;
        }
        while (degrees < 0F) {
            degrees += 360F;
        }
        return degrees;
    }
}

```

#### Version of LibGDX and/or relevant dependencies
gdxVersion = '1.9.5'

#### Stacktrace
No stacktrace

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [X] MacOS
I only tested it in Windows and MacOS, but I'm pretty sure this is not platform-specific

**Comment by tavomaciel** [comment]
```java
final float camMod = Gdx.graphics.getDeltaTime() * 300F;
//then
camera.rotate(-camMod);
```

I'm pretty sure this is the problem.

**Comment by pFreak** [comment]
Hi, please explain what you mean. Why do you think this is the problem?
I'm rotating the camera into the opposite direction that I rotate the sprite to.
That why the rotation effect of the sprite should cancle out due to the rotation of the camera into the opposite direction. And this is exactly what it does, except I'm having this Pixel-Stutterings that I'm describing here. Both lines you posted are using the Libgdx-Library, why should that not be Libgdx-Relevant?

**Comment by Darkyenus** [comment]
This discussion is better suited for forums or IRC.

That said, your problem is most likely in float precision. Floats are not real numbers and operations that are perfectly reversible in theory will introduce irreversible errors, resulting in slight differences in output image, like you are seeing. There are many ways to prevent this, but I'll not discuss such lengthy topic in issue tracker as it spams those who watch the tracker.

This can be closed as wontfix. If you want help, I and many others are on IRC.

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
