### ISSUE TITLE
Can not play 2 Music instances at the same time on Android

### ISSUE THREAD

**Issue by SasLuca** [libgdx/libgdx#4601]
#### Issue details
I am developing a game in which I need to play 2 Music instances at the same time. On Desktop they both run at the same time, no problem. On Android however they don't, I did not find anything online related to this issue so I am posting it here. I tried using both Gdx.audio.newMusic() and AssetManager and both methods did not work. I am compiling Java 8 with Retrolambda on a One Plus 3 with Android 7.0 Nougat, buildToolsVersion 25.0.2 and compileSdkVersion 24.

#### Reproduction steps/code
Here is a code sample. This code play both songs on Desktop but not on Android

```java    
Music test1;
Music test2;

AssetManager manager = new AssetManager();

@Override public void create()
{
    manager.load("reversion.mp3", Music.class);
    manager.load("collapse.mp3", Music.class);

    while (!manager.update()) {}
    manager.finishLoading();

    test1 = manager.get("reversion.mp3");
    test2 = manager.get("collapse.mp3");

    test1.setVolume(1);
    test1.play();
    test2.setVolume(1);
    test2.play();
}
```

#### Version of LibGDX and/or relevant dependencies
LibGDX version: 1.9.5

#### Please select the affected platforms
- [X] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by SasLuca** [comment]
I seem to have found a solution to this problem. If I load all my music instances at the beginning of the game and then use them there is no problem. However, the LibGDX wiki states "Music instances are heavy, you should usually not have more than one or two at most loaded.". This being said I had not encounter any performance issues by loading all my Music instances at the beginning. Maybe the documentation is meant to say "Only play() one or two at most" instead. I don't know. I hope either the issue gets fixed or the  documentation amended.

**Comment by cdetamble** [comment]
Have you encountered any further problems with this approach of loading all music files up-front? I face the same issue and came to thesame work-around as you described it. It seems to work for now. As I understand, instances of the Music class are streamed and not fully loaded into RAM.

**Comment by obigu** [comment]
I have been loading 8 `Music` instances (1 minute+ .ogg files) on app startup for years without any issues, even on low end devices. It's true `MediaPlayer` is quite a heavy object but the wiki recomendation may be a bit too strict. I'll close this and update the wiki with a higher number.
