### ISSUE TITLE
addActorBefore()/addActorAfter() should not be used with Table

### ISSUE THREAD

**Issue by nanodeath** [libgdx/libgdx#4602]
Please ensure you have given all the following requested information in your report.

#### Issue details
[Table](https://github.com/libgdx/libgdx/blob/db805953849780161df7c1fb96f81248c19cff44/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Table.java) inherits (indirectly) from [Group](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/Group.java), which means Table has the following three methods for adding a child node:

* [add(Actor)](https://github.com/libgdx/libgdx/blob/db805953849780161df7c1fb96f81248c19cff44/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Table.java#L194)
* [addActorBefore(Actor, Actor)](https://github.com/libgdx/libgdx/blob/db805953849780161df7c1fb96f81248c19cff44/gdx/src/com/badlogic/gdx/scenes/scene2d/Group.java#L290)
* [addActorAfter(Actor, Actor)](https://github.com/libgdx/libgdx/blob/db805953849780161df7c1fb96f81248c19cff44/gdx/src/com/badlogic/gdx/scenes/scene2d/Group.java#L304)

A developer using Scene2d *might* reasonably assume that all of these will work, when in fact, only the first method works -- the other two methods will execute and return normally, but will not layout the newly-added actor correctly (it'll be laid out underneath the last child of the Table).

#### Reproduction steps/code
_Even if you think your issue is trivial to reproduce, please supply a [SSCCE](http://sscce.org/) that demonstrates your issue.  This saves time on our end, and makes it much more likely that your issue will be fixed.
You can find barebones templates [here](https://github.com/libgdx/libgdx/wiki/Getting-help)_

I'm not sure this requires repro steps or code. Let me know if you want them.

#### Version of LibGDX and/or relevant dependencies
LibGDX 1.9.5, but current mainline appears affected as well.

#### Stacktrace
No stacktrace.

#### Affected platforms
All.

#### What I'm looking for

I'm looking for anything that would have saved me an hour of fiddling with `pack()` and `invalidateHierarchy()` just to find that these methods just don't work presently. I'd be happy with any of the following:

1. Override `addActor{Before|After}()` in Table so they work as expected.
2. Override `addActor{Before|After}()` in Table and make them throw an exception.
3. Override `addActor{Before|After}()` in Table and have it call `super`, but *also* annotate the method as `@Deprecated` with a reason why.

I can see that the [documentation](https://github.com/libgdx/libgdx/wiki/Table#inserting-cells) does mention this exact issue, near the very bottom, but I didn't see this and I suspect others might miss it as well.

**Comment by cypherdare** [comment]
Other Widgets that invalidate super methods throw exceptions, so that's the precedent. No way  to easily make it behave as expected.

**Comment by metaphore** [comment]
Though it may look confusing, but it's like a common practice now to use two approaches working with children in the `Table`. One is to put actors into table cells as it was intended using `Table#add()` methods and another is to use regular `Group`'s methods like `Group#addActor(Actor)`, `Group#addActorBefore(Actor)`, `Group#addActorAfter(Actor)` to make them not participate in table's layout and behave like them was added to regular `WidgetGroup`. And it actually gives us good flexibility to put custom actors in front or beneath any other table widgets. So I would say it's better to keep current approach, because it's definitely has it's own purpose.

**Comment by NathanSweet** [comment]
Agreed, in some cases it's convenient to add actors to a table without having them participate in table layouting.
