### ISSUE TITLE
[Feature request] create audio from array of samples

### ISSUE THREAD

**Issue by cheece** [libgdx/libgdx#4605]
hello

it will be very nice  to have a method
```java
Sound newSoundFromSamples(float[] samples);
```
in the Audio class,

I know AudioDevice has a writeSamples method that can be used for procedural sound, but i doesn't work very well, i played the demo "AudioDeviceTest" and the audio was a bit choppy  

I think  the method i propose would be much better

**Comment by mgsx-dev** [comment]
This would be a nice feature for some use cases including pre-generating some sounds at load time.

Unfortunately, according to http://stackoverflow.com/questions/26844839/load-sound-from-memory-in-android (and other posts) this can't be done on android prior to API 23 (android 6). Desktop backend (OpenAL) should not be a problem but I didn't look for others backends.

The only workaround for now is to write data in a file (including WAV header) and then load it as usual (newSound method).

> I know AudioDevice has a writeSamples method that can be used for procedural sound, but i doesn't work very well, i played the demo "AudioDeviceTest" and the audio was a bit choppy

Maybe related to playback buffer size and your hardware, did you tried to increase number of buffers and buffer size ?  I just think this [recent fix](https://github.com/libgdx/libgdx/pull/4442) might be related too.

**Comment by jd4096** [comment]
I have recently tried AudioDeviceTest and it worked pretty good! So it maybe is your hardware. Try smaller sample rate value.

**Comment by cheece** [comment]
i was running the compiled jar gdx-tests on Linux,  if i can use writeSamples then i'm done, it will do the trick, thanks
