### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by rqcy** [libgdx/libgdx#4606]
Hi, FreeBSD support would be very welcome! Thank you!

**Comment by lvivtotoro** [comment]
Yes, I would like this very much, too.

**Comment by lvivtotoro** [comment]
Maybe [this repo](https://github.com/arksu/libgdx-freebsd) can be merged (not directly)?  
It's two years old, though, so these changes may mess something else up.

**Comment by crykn** [comment]
I don't really understand why libGDX was supposed to not run on FreeBSD. According to [this lwjgl issue](https://github.com/LWJGL/lwjgl3/issues/421), at least lwjgl 2.9.x (released April 2013!) supports FreeBSD. Regardless, this is more of a LWJGL issue than a libgdx one. Can this be closed?

**Comment by NathanSweet** [comment]
Seems like we'd need to detect FreeBSD like this:
https://github.com/arksu/libgdx-freebsd/blob/master/gdx-patched/gdx/src/com/badlogic/gdx/utils/SharedLibraryLoader.java#L38
Used here:
https://github.com/arksu/libgdx-freebsd/blob/master/gdx-patched/backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglNativesLoader.java#L60
Maybe better to make `isLinux` true when on FreeBSD.

We could make these changes blindly, but ideally someone on FreeBSD can submit a tested PR.

**Comment by yuripourre** [comment]
Apache commons lang does the same check for FreeBSD.

https://github.com/apache/commons-lang/blob/master/src/main/java/org/apache/commons/lang3/SystemUtils.java#L1299

**Comment by Mia-Rain** [comment]
> Seems like we'd need to detect FreeBSD like this: https://github.com/arksu/libgdx-freebsd/blob/master/gdx-patched/gdx/src/com/badlogic/gdx/utils/SharedLibraryLoader.java#L38 Used here: https://github.com/arksu/libgdx-freebsd/blob/master/gdx-patched/backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglNativesLoader.java#L60 Maybe better to make `isLinux` true when on FreeBSD.
> 
> We could make these changes blindly, but ideally someone on FreeBSD can submit a tested PR.

I blindly made these changes and am currently testing if the natives compile. 
LWJGL3 has it's own issues but I also have a WIP freebsd port for it.

Something to note is that compilation will not being without gcc, might be a good idea to modify the repo to use `cc` as it's likely clang compilation works fine.

I'll report back on my findings.

**Comment by tommyettinger** [comment]
Clang support would be great on any platforms we can get it; it often produces better code than GCC in my experience these days. If something needs GCC-specific functions/macros, that could be a problem, though.

**Comment by Mia-Rain** [comment]
So far compilation works but gdx-freetype has issues getting headers since /usr/local/freetype2 isn't in the include folders since $CC_FLAGS is ignored

**Comment by Mia-Rain** [comment]
I'll write a patch to modify the headers to pull from `/usr/local/freetype2/` but if `-I/usr/local/freetype2/` could somehow be added to the CC_FLAGS that would also work

**Comment by Mia-Rain** [comment]
seems that modifying extensions/gdx-freetype/jni/build-linux64.xml:25 to include `${CC_FLAGS}` fixes this; 
if one runs `export CC_FLAGS="$CC_FLAGS -I/usr/local/freetype2"`

however I can't seem to find out where build-linux64.xml actually comes from since it's not part of the original source.

**Comment by Tom-Ski** [comment]
It comes from gdx-jnigen which is configured here for this extension: 
https://github.com/libgdx/libgdx/blob/master/extensions/gdx-freetype/build.gradle

**Comment by Mia-Rain** [comment]
Thanks, was able to modify that instead to produce a successful build pretty sure, heres a patch file.

[freebsd-build.patch.txt](https://github.com/libgdx/libgdx/files/9418865/freebsd-build.patch.txt)

**Comment by Mia-Rain** [comment]
> Thanks, was able to modify that instead to produce a successful build pretty sure, heres a patch file.
> 
> [freebsd-build.patch.txt](https://github.com/libgdx/libgdx/files/9418865/freebsd-build.patch.txt)

Pretty sure if [extensions/gdx-freetype/build.gradle](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-freetype/build.gradle) is just edited to use `$CC_FLAGS` and `$CPP_FLAGS` in `cFlags` and `cppFlags`; testing this now.

And isLinux is true for FreeBSD should have easy support since had no compilation issues.  

I haven't tested cross compiling yet tho so that may be something to look into.

**Comment by Mia-Rain** [comment]
yes that works, library properly builds, I can't test cross compiling but I'll submit a pr since it does produce working libraries.
