### ISSUE TITLE
Add standard Eclipse files to root .gitignore

### ISSUE THREAD

**Issue by wiverson** [libgdx/libgdx#4608]
Please ensure you have given all the following requested information in your report.

#### Issue details
Started working with the libgdx as a contributor, noticed that the .gitignore for the repo is missing the standard Eclipse working files.

#### Reproduction steps/code
Check out the repo, open the project[s] in Eclipse.

Should add the following to the .gitignore

# Eclipse
.classpath
.project
.settings/

Or optionally the longer list at http://www.bmchild.com/2012/06/git-ignore-for-java-eclipse-project.html

LMK if you want me to do a PR for this - it's kind of a top level file and I don't want to blow anything up, but happy to submit if that is easier.

#### Version of LibGDX and/or relevant dependencies
all, or 1.9.6-SNAPSOT

#### Stacktrace
n/a

#### Please select the affected platforms
- [X] Android
- [X] iOS (robovm)
- [X] iOS (MOE)
- [X] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by wiverson** [comment]
Here's a really good site with a nicely commented set of Eclipse files:

https://www.gitignore.io/api/eclipse

**Comment by mgsx-dev** [comment]
@wiverson I totally agree but I have to warn you (and others) about not so common gitignore pitfall (see https://github.com/libgdx/libgdx/issues/4560). Usually those kind of gitignore template causes drawbacks, for instance "bin/" will ignore all directory named bin recursively. Best way is to use a leading slash "/bin/" to prevent ignoring another bin folder in java package hierarchy or any other folder you don't want to ignore.

Maybe there is a reason why all these files are tracked in GIT ?

**Comment by wiverson** [comment]
Yeah, pattern matching can be tricky.  The current .gitignore already excludes Intelli/J files, but Eclipse is the recommended IDE for libGDX committers, which is why I went ahead and opened the issue.

**Comment by mgsx-dev** [comment]
some eclipse files are already tracked in the repo, so we don't want to ignore them for now.
