### ISSUE TITLE
Would overview diagrams for scene2d stuff be useful?

### ISSUE THREAD

**Issue by zeromancer** [libgdx/libgdx#4615]
I have created some diagrams that display dependencies/workflow of scene2d stuff
would it be useful/helpful to include all/some of them into the wiki ?
https://gist.github.com/zeromancer/072f9f8e419b70cd20cedb196a93502d

**Comment by mgsx-dev** [comment]
Could be a good idea but I think you mixed up several concepts in your graphs : inheritance, dependencies, workflow/dataflow ... 
UML modeling would be a good start for you to clearly separate/identify these concepts.
