### ISSUE TITLE
Question to Texture class

### ISSUE THREAD

**Issue by GoGonania** [libgdx/libgdx#4618]
I have looked into the source code of the Texture class and found something, i couldnt explain to myself: in the base constructor of the Texture the load(TextureData) method gets called. In this method the current texture is being bound. Then the wrap &amp; filter is being set. And in both methods the texture will be bound again. Then after the texture is loaded, at the end of the load() method, the current texture is unbound again.

My question is: Is it really necessary to call the bind() method 4 times only to load a texture? And why is it unbound again? In my project, i load the textures once at startup in there own texture units. And to do that, the bind method is being called 5 times per texture.

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
