### ISSUE TITLE
Container#removeActor(Actor, boolean) overridden method is missing

### ISSUE THREAD

**Issue by metaphore** [libgdx/libgdx#4623]
#### Issue details
`Container` overloads whole set of add/remove actor methods to define its specific singular child logic. But it has no override for `Group#removeActor(Actor, boolean)` which causes next bug: if child actor calls `remove()` on self, it triggers parent's `Group#removeActor(Actor, boolean)` and not `Group#removeActor(Actor)`, so `Container` will simply call super method (of `Group`) and keep reference to child actor.

Looks like regression bug, because javadoc of `Actor#remove()` also refers to `Group#removeActor(Actor)`, but actually calls only `Group#removeActor(Actor, boolean)`

#### Reproduction steps/code
``` java
Actor actor = new Actor();
Container container = new Container();
container.setActor(actor);
actor.remove();
assert(container.getActor() == null);
```

#### Version of LibGDX and/or relevant dependencies
1.9.5

#### Please select the affected platforms
- [ ] Core

**Comment by NathanSweet** [comment]
Closed via e5d44539d146abbc2fd6203e494f27b36b1843d5, thanks!
