### ISSUE TITLE
[robovm] Glitchy music

### ISSUE THREAD

**Issue by Try4W** [libgdx/libgdx#4624]
#### Issue details
I tried to play a couple of tracks and every N seconds I hear glitches.
The same glitch I hear when my app crashed while I play music.

In main menu it happens every 2 minutes.
In game screen in happens every 6 seconds.

#### Reproduction steps/code
I use libgdx to play mp3/wav.
I tried this implementations:
[IOSSound](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSSound.java)
[IOSAudio](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSAudio.java)

and with both of them I can reproduce this issue

The mp3 to play with: https://drive.google.com/open?id=0B7tY1W3cB0R8d3laTzZadGsxQkE

*It happens when GC occur.*
```
[Thread-6] DEBUG red.kometa.quest.player.KRQuestApplicationListener - javaHeap: 15092 kb, nativeHeap: 15092 kb
[Thread-6] DEBUG red.kometa.quest.player.KRQuestApplicationListener - javaHeap: 15716 kb, nativeHeap: 15716 kb
// GLITCH
[Thread-6] DEBUG red.kometa.quest.player.KRQuestApplicationListener - javaHeap: 10764 kb, nativeHeap: 10764 kb
[Thread-6] DEBUG red.kometa.quest.player.KRQuestApplicationListener - javaHeap: 10800 kb, nativeHeap: 10800 kb
```

#### Version of LibGDX and/or relevant dependencies
- libgdx 1.9.5
- Robovm: 2.3.0
- XCode: 8.2.1
- JDK: 1.8

#### affected platforms
- [ ] iOS (robovm)

**Build Targets:**

Physical iPhone 5s

duplicated from: [robovm issue](https://github.com/MobiDevelop/robovm/issues/112) as related too

**Comment by Tom-Ski** [comment]
Please see https://github.com/libgdx/libgdx/wiki/Issue-Tracker 

You can monitor GC and memory using instruments from xcode on ios.

**Comment by Try4W** [comment]
I don't need to monitor memory. I need to know how to stop playing audio from 'lags' when gc occur.

It's kind of bug and should be reported to issue tracker. I am wrong?

**Comment by mgsx-dev** [comment]
@Try4W : Your problem seams related to wrong usage of java memory in your game specific code (in your screens). LibGDX provides what you need to avoid GC as much as possible (batch, pool, array, ...). If you follow [libGDX guidelines about GC](https://github.com/libgdx/libgdx/wiki/Memory-management), you shouldn't have GC occurring so often (maybe no GC at all in the best case). Memory monitoring would help you to fix memory consumption in your code and then reduce glitches. If you really suspect audio implementation, you'll have to provide a [SSCCE](http://sscce.org/) to confirm it.

**Comment by Try4W** [comment]
@mgsx-dev Thanks! I missed this article about Memory management in libgdx.

So, glitches on iOS are expected and should occur but not too often?

**Comment by mgsx-dev** [comment]
@Try4W : Actually it depends on lot of things (VM, GC tuning, device ...) and not specifically related to iOS platfform. Full GC CPU consumption may lead to audio glitches and frames dropping but with good memory management you might get rid of it. So when I say not too often I mean almost never (or maybe once per hour but certainly not every few seconds).

As per https://github.com/libgdx/libgdx/wiki/Issue-Tracker, we shouldn't continue discussion here but use libgdx forum/IRC/Stackoverflow instead since it's not a LibGDX issue.

**Comment by Try4W** [comment]
Fixed with this code:

```
        val session = AVAudioSession.getSharedInstance()
        session.preferredIOBufferDuration = 1.0
        session.setActive(true)
```
all I need is to set longer preferredIOBufferDuration
