### ISSUE TITLE
AndroidGraphics: waiting for pause synchronization took too long; assuming deadlock and killing

### ISSUE THREAD

**Issue by connectmekiran** [libgdx/libgdx#4626]
Im trying to add a trackview in one my fragment . First time it load the trackview , but when clicking the back button and come back to the trackview app closing automitically

**Comment by Tom-Ski** [comment]
Please don't bypass the issue template.

**Comment by tpnet** [comment]
@connectmekiran  Have you solved it? If I lock the screen on Android8.1 and unlock it, I will have this problem.

**Comment by Ameb** [comment]
The workaround discussed [here](https://github.com/libgdx/libgdx/issues/3861#issuecomment-185684468) (#3861) works.

**Comment by tpnet** [comment]
@Ameb  Yeah, Thanks
