### ISSUE TITLE
TextArea mishapen, aligns text wrong and draws selection box outside widget

### ISSUE THREAD

**Issue by BenMcLean** [libgdx/libgdx#4629]
#### Issue details
The TextArea draws incorrectly.

First, the text appears in a position that is inconsistent with TextField.

Second, the selection box can go outside the TextArea if the TextArea doesn't have padding, and we don't always want padding.

TextField seems to work just fine: it's only TextArea which has the problem.

#### Reproduction steps/code
[I have a code example here](https://github.com/BenMcLean/libgdx-dos-skin/blob/901b353b2a58a5d8086cb655a54df57248ada38a/core/src/net/benmclean/libgdxdos/sscce.java). It requires having the default scene2D ui skin from libgdx tests.

I have a picture in [this tweet](https://twitter.com/McLeanBen/status/837085069466558464).

#### Version of LibGDX and/or relevant dependencies
1.9.4

1.9.6-SNAPSHOT (as of today)

#### Please select the affected platforms
Probably affects all platforms but I've only tested on GWT and Windows.

- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [X] HTML/GWT
- [X] Windows
- [ ] Linux
- [ ] MacOS

**Comment by kolen** [comment]
The same appearance as in screenshot in `1.9.7-SNAPSHOT` downloaded today (I don't know how to determine exact snapshot version) on Mac OS desktop.

**Comment by MrStahlfelge** [comment]
Closing this, probably fixed with #6164. In any case, Twitter image is not available any more due to closed account.
