### ISSUE TITLE
GWT says, "soundManager: No Flash response within expected time. Likely causes: Flash blocked or JS-Flash security error."

### ISSUE THREAD

**Issue by BenMcLean** [libgdx/libgdx#4637]
#### Issue details
I get this on GWT:
> soundManager: No Flash response within expected time. Likely causes: Flash blocked or JS-Flash security error.
> soundManager.disable(): Shutting down  soundmanager2-jsmin.js:32:357
> SoundManager 2 failed to load (Flash security/load error)

This causes the libGDX loading screen to not come up.

#### Reproduction steps/code
I observed it in [this commit here](https://github.com/BenMcLean/libgdx-dos-skin/commit/9e22ea613727027aedf4c42584991034c7d94093) of my project, but it happens on multiple projects and was happening on 1.9.6-SNAPSHOT.

It happens every time in FireFox and Edge but seems to happen randomly on Chrome. All on Windows 10.

#### Version of LibGDX and/or relevant dependencies
1.9.6

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [X] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
duplicate #4590

**Comment by BenMcLean** [comment]
Oh, it's the same issue? I wasn't sure because it gave a different error.
