### ISSUE TITLE
Nortorn anti-vrius recognizing 'gdx-box2d64.dll' as 'unsafe'

### ISSUE THREAD

**Issue by AndrewCarre** [libgdx/libgdx#4641]
Hi,

I am running into an issue where Norton Internet Security quarentines the 'gdx-box2d64.dll' when I compile the project. Here is my software and version information:

```
gdxVersion = '1.9.6'
        roboVMVersion = '2.3.0'
        box2DLightsVersion = '1.4'
        ashleyVersion = '1.7.0'
        aiVersion = '1.8.0'
```

Norton version '22,9.0.71'

I whitelisted the directory and moved on. I just wanted to let you know this is happening.

-Andrew

**Comment by Tom-Ski** [comment]
Not much we can do about this, will report false positives to Norton, I'd advise you to do the same. 
Thanks for the report.
