### ISSUE TITLE
Is it possible to load a list of AndroidApplication view into RecyclerView?

### ISSUE THREAD

**Issue by channguyen** [libgdx/libgdx#4644]
From my understanding, in order to display a 3D view, the app need to extends from AndroidApplication. 
In this class, there is a method to initialize view:
`View view = initializeForView(new MyGdxGame(), config);`
Looking at source code of AndroidApplication, I saw a lot of callbacks to deal with Android activity life cycle and a lot of objects like `input`, `files`, `net`, `audio`. So I'm wondering is it reasonable to display these views inside a RecyclerView with adapter model? My goal is not to create a game but rather an app that can display 3D model with transformation and animation.   
Any feedback would be greatly appreciated.

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
