### ISSUE TITLE
Native library libgdx.so potentially loaded two times on Android

### ISSUE THREAD

**Issue by netomi** [libgdx/libgdx#4653]
#### Issue details
I have noticed that the native library libgdx.so might be loaded twice on Android:

  * first time using GdxNativesLoader (used in AndroidApplication)
  * second time in AndroidGL20 via System.loadLibrary

This might be an artefact of the time when the AndroidGL20 class had its own native library.
From my understanding it should not be needed anymore to call System.loadLibrary explicitly in the AndroidGL20 class.

In general this should not make problems, but when using some obfuscators (e.g. DexGuard) it would be easier if the native library is only loaded via one mechanism, i.e. GdxNativesLoader -> SharedLibraryLoader.

#### Version of LibGDX and/or relevant dependencies
in master (currently 1.9.7-SNAPSHOT?)

#### Please select the affected platforms
- [X] Android

**Comment by badlogic** [comment]
Makes sense, I see what I can do.

**Comment by netomi** [comment]
Thanks a lot!
