### ISSUE TITLE
Not online Javadoc for LWJGL3

### ISSUE THREAD

**Issue by raitz-code** [libgdx/libgdx#4667]
Now the new project uses LWJGL3 instead of LWJGL as desktop backend by default, but there is still no related API doc online. For example [here](http://libgdx.badlogicgames.com/nightlies/docs/api/) isn't `Lwjgl3Application`, only `LwjglApplication`.

**Comment by Tom-Ski** [comment]
The project doesn't use lwjgl3 by default yet.  

Javadocs should be published for the lwjgl3 backend though.

**Comment by crykn** [comment]
Apart from the missing LWJGL 3 classes, the javadocs haven't been updated since we migrated the build to GH Actions. @Tom-Ski do you happen to know how we can upload the javadocs within our workflows or is that a badlogic matter?

**Comment by crykn** [comment]
Fixed by https://github.com/libgdx/libgdx.github.io/pull/105.
