### ISSUE TITLE
hello,how to use the PerspectiveCamera into Stage group actor ,please.

### ISSUE THREAD

**Issue by chongbo2013** [libgdx/libgdx#4678]
hello,how to use the PerspectiveCamera into Stage group actor ,please.
thanku .

I use it but I can't show it
 camera = new PerspectiveCamera(70, 0, 1000);
        FitViewport viewport =  new FitViewport(Gdx.graphics.getWidth(), Gdx.graphics.getHeight(), camera);
        stage = new Stage3D(viewport, batch);

        camera.position.set(0, 0, 500);
        camera.near = 1f;
        camera.far = 10000;
        camera.lookAt(0,0,0);
        camera.translate(1280/2, 720/2, 200);

        group=new Group();
        view2D=new View2D();
        group.addActor(view2D);
        view3D=new View3D();
//        group.addActor(view3D);
        stage.addActor(group);

**Comment by Tom-Ski** [comment]
Please use the forums or irc for these questions.

**Comment by feivur** [comment]
Facing this issue. How to use PerspectiveCamera?

**Comment by MrStahlfelge** [comment]
Best is really if you join the discord and ask for help.
