### ISSUE TITLE
TextArea drag-scroll doesn't work (TextAreaTest)

### ISSUE THREAD

**Issue by rdamiano** [libgdx/libgdx#4682]
GIF of issue(s): http://i.imgur.com/U6dTzkb.gif

_**Edit:** Ignore the misaligned selection/cursor, I believe it was due to some adjustments to capHeight/lineHeight etc I was unknowingly applying to fonts._

#### Issue details
1) TextArea doesn't scroll when dragged out of bounds. As in, to scroll up in a many-line textarea to see the top lines (out of view), scrolling does not occur.

~2) Selection background and cursor image are rendered very badly aligned, as evidenced in the GIF.~

#### Reproduction steps/code
1) TextAreaTest, just add some more lines to the TextArea and try to drag/select and scroll up.

~2) Not sure, this doesn't happen on TextAreaTest. I've tried two different font files. In a TextField with the same font selection/cursor renders perfectly, but in a TextArea it's all messed up.~

~Do TextAreas use some type of data from the BitmapFont in order to judge where to draw/how to draw the selection/cursor vs a TextField that doesn't do such a thing?~

#### Version of LibGDX and/or relevant dependencies
Latest nightly as of submission.

**Comment by BenMcLean** [comment]
Same issue as #4629
