### ISSUE TITLE
Multi-OS Engine build failed in Android Studio

### ISSUE THREAD

**Issue by cjortegon** [libgdx/libgdx#4683]
#### Issue details

I'm recently getting an error building a Multi-OS engine project using LibGDX in Android Studio. This is the output from the Multi-OS Engine console:

ERROR: Failed to upgradeonly on device, Unknown error
Command failed: [/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java, -Dfile.encoding=UTF-8, -Duser.country=US, -Duser.language=en, -Duser.variant, -jar, /Users/camilo/.moe/moe-sdk-1.3.0-beta-2/tools/ios-device.jar, --app-path=/path/to/my/project/ios-moe/build/moe/xcodebuild/Debug-iphoneos/MyApp.app, --wait-for-device, --launch-arg=-args, --launch-arg=--debug, --install-mode=upgradeonly]

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ios-moe:moeLaunch'.
> Process exited with non-zero exit value

* Try:
:ios-moe:moeLaunch FAILED
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

#### Reproduction steps/code
I tried to solve the problem removing Android Studio and all the related files. I installed everything from zero. Then I installed Multi-OS Engine Plugin. Then I generated a new project using gdx-setup. I imported using gradle and I opened ios-moe.xcodeproj with Xcode to add signing team.

#### Version of LibGDX and/or relevant dependencies
I'm working on a Mac.
My main gradle file looks like this:

buildscript {
    ...
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'org.multi-os-engine:moe-gradle:1.3.3'
    }
}
LibGDX version = 1.9.6

Nonetheless the Application is installed in the device, but I cannot see the logs in the console. When I change the build target to Simulator it works just fine.

**Comment by Tom-Ski** [comment]
Can you get the log from the device console, you can get that from xcode. Does the app attempt to launch?

**Comment by haxpor** [comment]
@Tom-Ski I had faced with this similar problem about MOE. Due to it's long ago, so I cannot remember exactly. Anyway, gdx-setup introduced this bug when merged for kotlin support long ago. See my [PR](https://github.com/libgdx/libgdx/pull/4812).
