### ISSUE TITLE
Android Device Crashes while calling .tmx file image for game

### ISSUE THREAD

**Issue by Nisi123** [libgdx/libgdx#4684]
I am trying to make a game and using .tmx file format. testing on window works fine but testing on android device it crashes and give message "unfortunately, your game has stopped working". How can I solve this problem? Thank you and would like to hear from you as soon as possible.

**Comment by MobiDevelop** [comment]
You'll need to provide a stack trace if we are to determine if there is indeed any problem in libgdx or if the problem is in your code.

Please use the forum or irc to ask questions. We'd like the issue tracker to remain dedicated to actual issues within libgdx.
