### ISSUE TITLE
InputProcessor keyUp and subsequent keyDown events missed for non-character keys (like shift) when application switches to background after initial keyDown

### ISSUE THREAD

**Issue by elohanlon** [libgdx/libgdx#4686]
#### Issue details
On the Desktop platform (or at least in macOS 10.12.3, which is what I'm testing on), InputProcessor keyUp events are missed for non-character keys (like shift, command, etc.) when the application is in the background.

#### Reproduction steps/code
Using the code example below (see "Working code example" section), if you press and hold a non-character key -- I'll use left shift as an example -- you'll see log output that says "INFO: Key down: 59".  If you continue to hold down the left shift key, but click outside of the application window so that the app goes into the background, and then release the key, the keyUp event will be missed and there will be no log output.  If you then bring the application into the foreground again, and press the left shift key down and then up, the keyDown event will be missed and you'll only get a keyUp event.  So the complete log output for this example will look like:

```
INFO: Key down: 59
INFO: Key up: 59
```

But it should look like:

```
INFO: Key down: 59
INFO: Key up: 59
INFO: Key down: 59
INFO: Key up: 59
```

One interesting thing to note is that this problem doesn't occur for character keys (like if you press the "a" key or "b" key).

#### Working code example

```
public class MyGdxGame extends ApplicationAdapter implements InputProcessor {
	
	@Override
	public void create () {
		Gdx.input.setInputProcessor(this);
	}

	@Override
	public void render () {
		Gdx.gl.glClearColor(1, 0, 0, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
	}
	
	@Override
	public void dispose () {
	}

	@Override
	public boolean keyDown(int keycode) {
		Gdx.app.log("INFO", "Key down: " + keycode);
		return false;
	}

	@Override
	public boolean keyUp(int keycode) {
		Gdx.app.log("INFO", "Key up: " + keycode);
		return false;
	}

	@Override
	public boolean keyTyped(char character) {
		return false;
	}

	@Override
	public boolean touchDown(int screenX, int screenY, int pointer, int button) {
		return false;
	}

	@Override
	public boolean touchUp(int screenX, int screenY, int pointer, int button) {
		return false;
	}

	@Override
	public boolean touchDragged(int screenX, int screenY, int pointer) {
		return false;
	}

	@Override
	public boolean mouseMoved(int screenX, int screenY) {
		return false;
	}

	@Override
	public boolean scrolled(int amount) {
		return false;
	}
}
```

#### Version of LibGDX and/or relevant dependencies
LibGDX 1.9.6

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS

**Comment by Harvtronix** [comment]
I also see this same issue on my projects. With my input processing logic, it makes me have to double press the key when I get back to the app for that button to start working again so I can receive a key up event.

**Comment by Mikeywalsh** [comment]
For what it's worth, this seems like a Mac specific bug, I can't seem to reproduce this on my windows 10 machine. If I click outside of the application window, the keyUp event is fired instantly, no matter what key i'm using.

**Comment by NathanSweet** [comment]
This is an old bug, is it still happening? If so, what backend? Eg, LWJGL2 or LWJGL3? Likely it is a bug for those libraries.

**Comment by crykn** [comment]
Just checked it on OS X 10.15.3: It's still happening with the LWJGL2 backend, but not with the LWJGL3 one.

**Comment by NathanSweet** [comment]
Thanks @crykn. Not sure we can fix it on the libgdx side, likely it's an issue for LWJGL2, but I'm not sure they are still doing fixes there.

**Comment by NathanSweet** [comment]
It appears there is nothing we can do on our end. LWJGL2 is getting old and no longer maintained. Consider using LWJGL3, if possible.

A hacky workaround that may work is to use java.awt.Robot and do `keyPress` then `keyRelease` when the window gains focus.
