### ISSUE TITLE
LwjglAWTCanvas multisampling not working

### ISSUE THREAD

**Issue by dzolo** [libgdx/libgdx#4687]
#### Issue details
I am trying to get working multisamling (anti-aliasing) with LwjglAWTCanvas.
I have studied the code and reviewed differences between LwjglAWTCanvas and LwjglCanvas which supports the multisampling (with the same LwjglApplicationConfiguration configuration that I am applying to the  LwjglAWTCanvas). Both are using the LwjglGraphics but LwjglAWTCanvas does not create LWJGL Display which includes setting of pixel and buffer formats whose activates the multisampling. Due to restriction in Display (only one instance per application) the LwjglAWTCanvas do not use it and render directly to place where AWT canvas is located.

Is there any way to activate multisampling with LwjglAWTCanvas for multiple windows?

#### Version of LibGDX and/or relevant dependencies
1.9.6

#### Stacktrace
```java
Game game = ...;
LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
config.samples = 4;
LwjglAWTCanvas canvas = new LwjglAWTCanvas(game, config);
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by mgsx-dev** [comment]
maybe this one could be closed since LWJGL 2 is no longer maintained and multiple windows seams to be a LWJGL 3 feature.

**Comment by NathanSweet** [comment]
Agreed. I don't think anyone here knows how to help at any rate. Could try asking the LWJGL guys.

**Comment by dzolo** [comment]
Are there any plans in adding support for AWT in LWJGL 3 using [lwjgl3-awt](https://github.com/LWJGLX/lwjgl3-awt)?

**Comment by Tom-Ski** [comment]
There are no plans. People are welcome to submit PRs for feature support
