### ISSUE TITLE
GwtGL20 doesn't accept FRAMEBUFFER_BINDING, but WebGL does support it

### ISSUE THREAD

**Issue by metaphore** [libgdx/libgdx#4688]
#### Issue details
I'm trying to obtain handle of current bound frame buffer from GL context by using `Gdx.gl.glGetIntegerv(GL_FRAMEBUFFER_BINDING, intBuf)` but on GWT build this code crashes within `GwtGL20` implementation. The problem is `GwtGL20#glGetIntegerv(int, IntBuffer)` supports only limited set of GL codes, and obviously FRAMEBUFFER_BINDING is missing here.

I'm not an exert in WebGL, but after some googling I'm not found any mention on this limitation. Then I just wrote direct call to WebGL context to obtain that value:
```java
GwtGraphics graphics = (GwtGraphics) Gdx.graphics;
WebGLRenderingContext renderingContext = graphics.getContext();
int fbHandle = renderingContext.getParameteri(GL_FRAMEBUFFER_BINDING);
```
And it appears to work fine. So the questions is: Is there any reason to not support FRAMEBUFFER_BINDING code for GWT?

#### Version of LibGDX and/or relevant dependencies
_1.9.6_

#### Affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [x] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by metaphore** [comment]
After few more hours of experiments I found that things are more complicate that I expected.
At first, `GwtGL20#glGetIntegerv(int, IntBuffer)` actually always returns null. 
But this should be find after I found that `WebGLRenderingContext` has specific method to retrieve frame buffer - `#getParametero(int)`. The only problem that the return type is `WebGLObject` or `WebGLFramebuffer` in my case and looks like there is no simple way to access something like a handle or ID for it.

I'm a bit lost in here, probably someone with WebGL experience could help me with it?

**Comment by metaphore** [comment]
_Captain's log, day two_
After even more googling, I finally got some understanding how GWT/WebGL things work. Now I clearly see there is a lot of difference in how JS WebGL structure organized and realize why it's so hard to implement all `GL20` methods for `GwtGL20` in a way they work for the rest of backends.

Back to my problem, I kinda found solution to obtain FrameBuffer's handle. `GwtGL20#frameBuffers` keep track of all existing FrameBuffers and this is how GWT implementation pretends to work in the same way as the others. But then I came with another question: why `GwtGL20` implements some simple calls (mostly those return primitive values) and throws exception on the rest? I understand that this is specific case to obtain bound FrameBuffer (`GL_FRAMEBUFFER_BINDING`) or let's say current viewport (`GL_VIEWPORT`), and they require extra code to extract values from WebGL JS classes, but in other hand `GwtGL20` completely closed for accessing them in any other way. Of course I can write some native GWT code to access these values, but isn't that a `GwtGL20`'s responsibility to maintain that level of abstraction?

General question is:
Should `GwtGL20` codebase be extended to support such specific calls or not (at least they can be written on request, like this one)?

**Comment by Tom-Ski** [comment]
Why do you want to query the currently bound fbo in this way? You are adding extra overhead querying for this when you can just keep track of what fbo is bound yourself.

Checking briefly it looks like it should be supported given the webgl spec to query via glGet, but would have to give it a run to test.

Generally, non-implemented methods are either not supported by the subset, or just simply haven't been implemented due to it not being required in the core framework, and/or not being requested.  You'll have to look at each method case by case.

**Comment by metaphore** [comment]
Thanks @Tom-Ski, looking forward to it!

I will try to explain the reason for this. I have sort of utility wrapper over `FrameBuffer` - `FboWrapper`. This wrapper is able to properly resize and preserve state of OpenGL (viewport, previously bound frame buffer) and `Batch` (matrices) for the moment of drawing into this FBO. So, right when FBO should be unbound, wrapper simply restores all state and things are getting a lot easier than managing this all by hand every time. And one of the biggest advantages of this approach is, while using this technique, I can draw into FBO while I'm "drawing" into another FBO, so it's like nested calls, and this works because `FboWrapper` always know what `FrameBuffer` should be set as bound after its `end()` was called. And to be versatile solution for any application, I just prefer to ask GL about current bound frame buffer on every `FboWrapper#begin()`. I know it may be slow, but I didn't ever noticed any performance impact on mobile devices.

**Comment by RUSshy** [comment]
libGDX need proper opengl state management, otherwise people will bloat their code and make mistakes, especially when consuming other people's lib that manage states their own way already

libGDX will benefit a lot from modernizing the way stuff are rendered, i was thinking about copying the way MonoGame is doing, but that would mean changing how shaders around bound and meshes rendered

**Comment by metaphore** [comment]
I put some thoughts around my custom frame buffer implementation on this page https://github.com/crashinvaders/gdx-vfx/wiki/VFX-Frame-Buffer

It kinda explains the reason behind this issue existence.
