### ISSUE TITLE
How to transparent background on AndroidFragmentApplication

### ISSUE THREAD

**Issue by chongbo2013** [libgdx/libgdx#4690]
I have made the forum, but no one answered me.plz
http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=26210

I used the following code, but the background is still black and there is no transparent channel.
libgdx-1.9.5

AndroidApplicationConfiguration cfg = new AndroidApplicationConfiguration();
cfg.r = cfg.g = cfg.b = cfg.a = 8;

View view = initializeForView(application, cfg);
if (view instanceof SurfaceView) {
GLSurfaceView glView = (GLSurfaceView) graphics.getView();
glView.getHolder().setFormat(PixelFormat.TRANSLUCENT);
glView.setZOrderMediaOverlay(true);
glView.setZOrderOnTop(true);

**Comment by hopewise** [comment]
did you make any progress on this issue?
