### ISSUE TITLE
Proguard Configuration

### ISSUE THREAD

**Issue by Kurimatzu** [libgdx/libgdx#4696]
#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [ ] MacOS

Does anyone have any proguard.cfg compatible with the most current version of libgdx? (Windows)

**Comment by Kurimatzu** [comment]
Upy

**Comment by Tom-Ski** [comment]
The one supplied in the setup tool is compatible, but it depends on your particular configuration as to what you want.  Please use the forum or the irc if you need help with this.
