### ISSUE TITLE
Meshes do not check if index array larger than index array size

### ISSUE THREAD

**Issue by amcolash** [libgdx/libgdx#4697]
#### Issue details
In `Mesh.java`, the Mesh will not check bounds if it is not a `VertexArray`. I found this bug only recently as a silent crash. The fix is relatively simple, just need to check if the `count + offset` is greater than the total number of indicies in the buffer.

#### Reproduction steps/code
Make a mesh that says it has more indicies than were created.

#### Version of LibGDX and/or relevant dependencies
All versions?

#### Please select the affected platforms
- [X] Android
- [X] iOS (robovm)
- [X] iOS (MOE)
- [X] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by amcolash** [comment]
[index_patch.txt](https://github.com/libgdx/libgdx/files/922745/index_patch.txt)

**Comment by jrenner** [comment]
I think it should be an Exception

**Comment by amcolash** [comment]
Made a PR #4727
