### ISSUE TITLE
Unable to import in android studio

### ISSUE THREAD

**Issue by himanshuraja** [libgdx/libgdx#4699]
Please ensure you have given all the following requested information in your report.

#### Issue details
Hi I am not able to import the libgdx into my android studio 2.x
![rob](https://cloud.githubusercontent.com/assets/9448918/25069868/421f5dd0-22ab-11e7-9cf5-f2a7d3f5ff9e.png)

#### Reproduction steps/code
_Even if you think your issue is trivial to reproduce, please supply a [SSCCE](http://sscce.org/) that demonstrates your issue.  This saves time on our end, and makes it much more likely that your issue will be fixed.
You can find barebones templates [here](https://github.com/libgdx/libgdx/wiki/Getting-help)_

#### Version of LibGDX and/or relevant dependencies
_Please provide the version(s) affected._

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [x] Android

**Comment by Tom-Ski** [comment]
You either don't have enough RAM, or you have a 32bit jdk installed on a 64bit system. If you have the first case, lower the RAM in gradle.properties file, if its the second, uninstall the 32bit jdk and install a 64bit one.
