### ISSUE TITLE
Mac 10.12.4  libgdx 1.9.6 ant error

### ISSUE THREAD

**Issue by davewang** [libgdx/libgdx#4703]
1.sudo `ant -f fetch.xml`    is ok.
2.sudo `ant`  throws error as follows
.....
check-natives:

compile-natives:

all:
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/sources/gdx-backend-android-sources.jar
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backend-android/libs/arm64-v8a does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backend-android/libs/armeabi does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backend-android/libs/armeabi-v7a does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backend-android/libs/x86 does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backend-android/libs/x86_64 does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backend-android/libs/ios32 does not exist.
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/gdx-backend-android.jar

gdx-backend-gwt:

clean:
   [delete] Deleting directory /Users/dave/dev/libgdx-1.9.6/backends/gdx-backends-gwt/target

init:
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backends-gwt/target
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backends-gwt/target/java
     [copy] Copying 6 files to /Users/dave/dev/libgdx-1.9.6/backends/gdx-backends-gwt/target/java

compile:
    [javac] Compiling 191 source files to /Users/dave/dev/libgdx-1.9.6/backends/gdx-backends-gwt/target/java
    [javac] 警告: [options] 未与 -source 1.6 一起设置引导类路径
    [javac] 注: 某些输入文件使用或覆盖了已过时的 API。
    [javac] 注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
    [javac] 注: 某些输入文件使用了未经检查或不安全的操作。
    [javac] 注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
    [javac] 1 个警告

check-natives:

compile-natives:

all:
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/sources/gdx-backend-gwt-sources.jar
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backends-gwt/libs/arm64-v8a does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backends-gwt/libs/armeabi does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backends-gwt/libs/armeabi-v7a does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backends-gwt/libs/x86 does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backends-gwt/libs/x86_64 does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backends-gwt/libs/ios32 does not exist.
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/gdx-backend-gwt.jar

gdx-backend-robovm:

fetch-robovm:
      [get] Getting: https://libgdx.badlogicgames.com/robovm/robovm/lib//robovm-cacerts-full.jar
      [get] To: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backend-robovm/libs/robovm-cacerts-full.jar
      [get] Getting: https://libgdx.badlogicgames.com/robovm/robovm/lib//robovm-cocoatouch.jar
      [get] To: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backend-robovm/libs/robovm-cocoatouch.jar
      [get] Getting: https://libgdx.badlogicgames.com/robovm/robovm/lib//robovm-objc.jar
      [get] To: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backend-robovm/libs/robovm-objc.jar
      [get] Getting: https://libgdx.badlogicgames.com/robovm/robovm/lib//robovm-rt.jar
      [get] To: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backend-robovm/libs/robovm-rt.jar

clean:
   [delete] Deleting directory /Users/dave/dev/libgdx-1.9.6/backends/gdx-backend-robovm/target

init:
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backend-robovm/target
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backend-robovm/target/java

compile:
    [javac] Compiling 30 source files to /Users/dave/dev/libgdx-1.9.6/backends/gdx-backend-robovm/target/java
    [javac] 警告: [options] 未与 -source 1.6 一起设置引导类路径
    [javac] 注: 某些输入文件使用或覆盖了已过时的 API。
    [javac] 注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
    [javac] 1 个警告

check-natives:

compile-natives:

all:
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/sources/gdx-backend-robovm-sources.jar
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backend-robovm/libs/arm64-v8a does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backend-robovm/libs/armeabi does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backend-robovm/libs/armeabi-v7a does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backend-robovm/libs/x86 does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backend-robovm/libs/x86_64 does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/backends/gdx-backend-robovm/libs/ios32 does not exist.
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/gdx-backend-robovm.jar

gdx-freetype:

clean:
   [delete] Deleting directory /Users/dave/dev/libgdx-1.9.6/extensions/gdx-freetype/target

init:
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-freetype/target
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-freetype/target/java

compile:
    [javac] Compiling 5 source files to /Users/dave/dev/libgdx-1.9.6/extensions/gdx-freetype/target/java
    [javac] 警告: [options] 未与 -source 1.6 一起设置引导类路径
    [javac] 注: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator.java使用了未经检查或不安全的操作。
    [javac] 注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
    [javac] 1 个警告

check-natives:

compile-natives:

all:
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-freetype/sources
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-freetype/sources/gdx-freetype-sources.jar
     [copy] Copying 1 file to /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-freetype
     [copy] Copying 1 file to /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-freetype/arm64-v8a
     [copy] Copying 1 file to /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-freetype/armeabi
     [copy] Copying 1 file to /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-freetype/armeabi-v7a
     [copy] Copying 1 file to /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-freetype/x86
     [copy] Copying 1 file to /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-freetype/x86_64
     [copy] Copying 2 files to /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-freetype/ios
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-freetype/gdx-freetype.jar

gdx-tools:

clean:
   [delete] Deleting directory /Users/dave/dev/libgdx-1.9.6/extensions/gdx-tools/target

init:
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-tools/target
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-tools/target/java

compile:
    [javac] Compiling 87 source files to /Users/dave/dev/libgdx-1.9.6/extensions/gdx-tools/target/java
    [javac] 警告: [options] 未与 -source 1.6 一起设置引导类路径
    [javac] 注: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-tools/src/com/badlogic/gdx/tools/flame/FlameMain.java使用或覆盖了已过时的 API。
    [javac] 注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
    [javac] 注: 某些输入文件使用了未经检查或不安全的操作。
    [javac] 注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
    [javac] 1 个警告

check-natives:

compile-natives:

all:
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-tools/sources
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-tools/sources/gdx-tools-sources.jar
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-tools/libs/arm64-v8a does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-tools/libs/armeabi does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-tools/libs/armeabi-v7a does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-tools/libs/x86 does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-tools/libs/x86_64 does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-tools/libs/ios32 does not exist.
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-tools/gdx-tools.jar

gdx-box2d:

clean:
   [delete] Deleting directory /Users/dave/dev/libgdx-1.9.6/extensions/gdx-box2d/gdx-box2d/target

init:
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-box2d/gdx-box2d/target
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-box2d/gdx-box2d/target/java
     [copy] Copying 1 file to /Users/dave/dev/libgdx-1.9.6/extensions/gdx-box2d/gdx-box2d/target/java

compile:
    [javac] Compiling 51 source files to /Users/dave/dev/libgdx-1.9.6/extensions/gdx-box2d/gdx-box2d/target/java
    [javac] 警告: [options] 未与 -source 1.6 一起设置引导类路径
    [javac] 1 个警告

check-natives:

compile-natives:

all:
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-box2d/sources
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-box2d/sources/gdx-box2d-sources.jar
     [copy] Copying 1 file to /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-box2d
     [copy] Copying 1 file to /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-box2d/arm64-v8a
     [copy] Copying 1 file to /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-box2d/armeabi
     [copy] Copying 1 file to /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-box2d/armeabi-v7a
     [copy] Copying 1 file to /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-box2d/x86
     [copy] Copying 1 file to /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-box2d/x86_64
     [copy] Copying 2 files to /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-box2d/ios
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-box2d/gdx-box2d.jar

gdx-box2d-gwt:

clean:
   [delete] Deleting directory /Users/dave/dev/libgdx-1.9.6/extensions/gdx-box2d/gdx-box2d-gwt/target

init:
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-box2d/gdx-box2d-gwt/target
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-box2d/gdx-box2d-gwt/target/java
     [copy] Copying 1 file to /Users/dave/dev/libgdx-1.9.6/extensions/gdx-box2d/gdx-box2d-gwt/target/java

compile:
    [javac] Compiling 188 source files to /Users/dave/dev/libgdx-1.9.6/extensions/gdx-box2d/gdx-box2d-gwt/target/java
    [javac] 警告: [options] 未与 -source 1.6 一起设置引导类路径
    [javac] 1 个警告

check-natives:

compile-natives:

all:
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-box2d/sources/gdx-box2d-gwt-sources.jar
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-box2d/gdx-box2d-gwt/libs/arm64-v8a does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-box2d/gdx-box2d-gwt/libs/armeabi does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-box2d/gdx-box2d-gwt/libs/armeabi-v7a does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-box2d/gdx-box2d-gwt/libs/x86 does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-box2d/gdx-box2d-gwt/libs/x86_64 does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-box2d/gdx-box2d-gwt/libs/ios32 does not exist.
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-box2d/gdx-box2d-gwt.jar

gdx-controllers:

clean:
   [delete] Deleting directory /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers/target

init:
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers/target
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers/target/java
     [copy] Copying 1 file to /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers/target/java

compile:
    [javac] Compiling 10 source files to /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers/target/java
    [javac] 警告: [options] 未与 -source 1.6 一起设置引导类路径
    [javac] 注: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers/src/com/badlogic/gdx/controllers/Controllers.java使用了未经检查或不安全的操作。
    [javac] 注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
    [javac] 1 个警告

check-natives:

compile-natives:

all:
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-controllers/sources
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-controllers/sources/gdx-controllers-sources.jar
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers/libs/arm64-v8a does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers/libs/armeabi does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers/libs/armeabi-v7a does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers/libs/x86 does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers/libs/x86_64 does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers/libs/ios32 does not exist.
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-controllers/gdx-controllers.jar

gdx-controllers-desktop:

clean:
   [delete] Deleting directory /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-desktop/target

init:
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-desktop/target
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-desktop/target/java

compile:
    [javac] Compiling 7 source files to /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-desktop/target/java
    [javac] 警告: [options] 未与 -source 1.6 一起设置引导类路径
    [javac] 注: 某些输入文件使用了未经检查或不安全的操作。
    [javac] 注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
    [javac] 1 个警告

check-natives:

compile-natives:

all:
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-controllers/sources/gdx-controllers-desktop-sources.jar
     [copy] Copying 1 file to /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-controllers
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-desktop/libs/arm64-v8a does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-desktop/libs/armeabi does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-desktop/libs/armeabi-v7a does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-desktop/libs/x86 does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-desktop/libs/x86_64 does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-desktop/libs/ios32 does not exist.
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-controllers/gdx-controllers-desktop.jar

gdx-controllers-lwjgl3:

clean:
   [delete] Deleting directory /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-lwjgl3/target

init:
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-lwjgl3/target
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-lwjgl3/target/java

compile:
    [javac] Compiling 3 source files to /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-lwjgl3/target/java

check-natives:

compile-natives:

all:
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-controllers/sources/gdx-controllers-lwjgl3-sources.jar
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-lwjgl3/libs/arm64-v8a does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-lwjgl3/libs/armeabi does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-lwjgl3/libs/armeabi-v7a does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-lwjgl3/libs/x86 does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-lwjgl3/libs/x86_64 does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-lwjgl3/libs/ios32 does not exist.
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-controllers/gdx-controllers-lwjgl3.jar

gdx-controllers-android:

clean:
   [delete] Deleting directory /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-android/target

init:
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-android/target
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-android/target/java

compile:
    [javac] Compiling 4 source files to /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-android/target/java
    [javac] 警告: [options] 未与 -source 1.6 一起设置引导类路径
    [javac] 1 个警告

check-natives:

compile-natives:

all:
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-controllers/sources/gdx-controllers-android-sources.jar
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-android/libs/arm64-v8a does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-android/libs/armeabi does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-android/libs/armeabi-v7a does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-android/libs/x86 does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-android/libs/x86_64 does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-android/libs/ios32 does not exist.
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-controllers/gdx-controllers-android.jar

gdx-controllers-gwt:

clean:
   [delete] Deleting directory /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-gwt/target

init:
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-gwt/target
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-gwt/target/java
     [copy] Copying 1 file to /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-gwt/target/java

compile:
    [javac] Compiling 8 source files to /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-gwt/target/java
    [javac] 警告: [options] 未与 -source 1.6 一起设置引导类路径
    [javac] 1 个警告

check-natives:

compile-natives:

all:
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-controllers/sources/gdx-controllers-gwt-sources.jar
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-gwt/libs/arm64-v8a does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-gwt/libs/armeabi does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-gwt/libs/armeabi-v7a does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-gwt/libs/x86 does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-gwt/libs/x86_64 does not exist.
     [copy] Warning: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-controllers/gdx-controllers-gwt/libs/ios32 does not exist.
      [jar] Building jar: /Users/dave/dev/libgdx-1.9.6/dist/extensions/gdx-controllers/gdx-controllers-gwt.jar

gdx-bullet:

clean:
   [delete] Deleting directory /Users/dave/dev/libgdx-1.9.6/extensions/gdx-bullet/target

init:
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-bullet/target
    [mkdir] Created dir: /Users/dave/dev/libgdx-1.9.6/extensions/gdx-bullet/target/java

compile:
    [javac] Compiling 482 source files to /Users/dave/dev/libgdx-1.9.6/extensions/gdx-bullet/target/java
    [javac] 警告: [options] 未与 -source 1.6 一起设置引导类路径
    [javac] /Users/dave/dev/libgdx-1.9.6/extensions/gdx-bullet/jni/swig-src/softbody/com/badlogic/gdx/physics/bullet/softbody/btSoftBody.java:130: 警告: '_' 用作标识符
    [javac]     public final static class _ {
    [javac]                               ^
    [javac]   (Java SE 8 之后的发行版中可能不支持使用 '_' 作为标识符)
    [javac] /Users/dave/dev/libgdx-1.9.6/extensions/gdx-bullet/jni/swig-src/softbody/com/badlogic/gdx/physics/bullet/softbody/btSoftBody.java:190: 警告: '_' 用作标识符
    [javac]     public final static class _ {
    [javac]                               ^
    [javac]   (Java SE 8 之后的发行版中可能不支持使用 '_' 作为标识符)
    [javac] /Users/dave/dev/libgdx-1.9.6/extensions/gdx-bullet/jni/swig-src/softbody/com/badlogic/gdx/physics/bullet/softbody/btSoftBody.java:244: 警告: '_' 用作标识符
    [javac]     public final static class _ {
    [javac]                               ^
    [javac]   (Java SE 8 之后的发行版中可能不支持使用 '_' 作为标识符)
    [javac] /Users/dave/dev/libgdx-1.9.6/extensions/gdx-bullet/jni/swig-src/softbody/com/badlogic/gdx/physics/bullet/softbody/btSoftBody.java:301: 警告: '_' 用作标识符
    [javac]     public final static class _ {
    [javac]                               ^
    [javac]   (Java SE 8 之后的发行版中可能不支持使用 '_' 作为标识符)
    [javac] /Users/dave/dev/libgdx-1.9.6/extensions/gdx-bullet/jni/swig-src/softbody/com/badlogic/gdx/physics/bullet/softbody/btSoftBody.java:357: 警告: '_' 用作标识符
    [javac]     public final static class _ {
    [javac]                               ^
    [javac]   (Java SE 8 之后的发行版中可能不支持使用 '_' 作为标识符)
    [javac] /Users/dave/dev/libgdx-1.9.6/extensions/gdx-bullet/jni/swig-src/softbody/com/badlogic/gdx/physics/bullet/softbody/btSoftBody.java:415: 警告: '_' 用作标识符
    [javac]     public final static class _ {
    [javac]                               ^
    [javac]   (Java SE 8 之后的发行版中可能不支持使用 '_' 作为标识符)
    [javac] /Users/dave/dev/libgdx-1.9.6/extensions/gdx-bullet/jni/swig-src/softbody/com/badlogic/gdx/physics/bullet/softbody/btSoftBody.java:476: 警告: '_' 用作标识符
    [javac]     public final static class _ {
    [javac]                               ^
    [javac]   (Java SE 8 之后的发行版中可能不支持使用 '_' 作为标识符)
    [javac] /Users/dave/dev/libgdx-1.9.6/extensions/gdx-bullet/jni/swig-src/softbody/com/badlogic/gdx/physics/bullet/softbody/btSoftBody.java:2487: 警告: '_' 用作标识符
    [javac]         public final static class _ {
    [javac]                                   ^
    [javac]   (Java SE 8 之后的发行版中可能不支持使用 '_' 作为标识符)
    [javac] /Users/dave/dev/libgdx-1.9.6/extensions/gdx-bullet/jni/swig-src/softbody/com/badlogic/gdx/physics/bullet/softbody/fDrawFlags.java:67: 警告: '_' 用作标识符
    [javac]   public final static class _ {
    [javac]                             ^
    [javac]   (Java SE 8 之后的发行版中可能不支持使用 '_' 作为标识符)
    [javac] /Users/dave/dev/libgdx-1.9.6/extensions/gdx-bullet/jni/swig-src/collision/com/badlogic/gdx/physics/bullet/collision/Collision.java:140: 错误: 找不到符号
    [javac]   public static void setGContactAddedCallback(SWIGTYPE_p_f_r_btManifoldPoint_p_q_const__btCollisionObjectWrapper_int_int_p_q_const__btCollisionObjectWrapper_int_int__bool value) {
    [javac]                                               ^
    [javac]   符号:   类 SWIGTYPE_p_f_r_btManifoldPoint_p_q_const__btCollisionObjectWrapper_int_int_p_q_const__btCollisionObjectWrapper_int_int__bool
    [javac]   位置: 类 Collision
    [javac] /Users/dave/dev/libgdx-1.9.6/extensions/gdx-bullet/jni/swig-src/collision/com/badlogic/gdx/physics/bullet/collision/Collision.java:144: 错误: 找不到符号
    [javac]   public static SWIGTYPE_p_f_r_btManifoldPoint_p_q_const__btCollisionObjectWrapper_int_int_p_q_const__btCollisionObjectWrapper_int_int__bool getGContactAddedCallback() {
    [javac]                 ^
    [javac]   符号:   类 SWIGTYPE_p_f_r_btManifoldPoint_p_q_const__btCollisionObjectWrapper_int_int_p_q_const__btCollisionObjectWrapper_int_int__bool
    [javac]   位置: 类 Collision
    [javac] /Users/dave/dev/libgdx-1.9.6/extensions/gdx-bullet/jni/swig-src/collision/com/badlogic/gdx/physics/bullet/collision/Collision.java:141: 错误: 找不到符号
    [javac]     CollisionJNI.gContactAddedCallback_set(SWIGTYPE_p_f_r_btManifoldPoint_p_q_const__btCollisionObjectWrapper_int_int_p_q_const__btCollisionObjectWrapper_int_int__bool.getCPtr(value));
    [javac]                                            ^
    [javac]   符号:   变量 SWIGTYPE_p_f_r_btManifoldPoint_p_q_const__btCollisionObjectWrapper_int_int_p_q_const__btCollisionObjectWrapper_int_int__bool
    [javac]   位置: 类 Collision
    [javac] /Users/dave/dev/libgdx-1.9.6/extensions/gdx-bullet/jni/swig-src/collision/com/badlogic/gdx/physics/bullet/collision/Collision.java:146: 错误: 找不到符号
    [javac]     return (cPtr == 0) ? null : new SWIGTYPE_p_f_r_btManifoldPoint_p_q_const__btCollisionObjectWrapper_int_int_p_q_const__btCollisionObjectWrapper_int_int__bool(cPtr, false);
    [javac]                                     ^
    [javac]   符号:   类 SWIGTYPE_p_f_r_btManifoldPoint_p_q_const__btCollisionObjectWrapper_int_int_p_q_const__btCollisionObjectWrapper_int_int__bool
    [javac]   位置: 类 Collision
    [javac] 4 个错误
    [javac] 10 个警告

BUILD FAILED
/Users/dave/dev/libgdx-1.9.6/build.xml:297: The following error occurred while executing this line:
/Users/dave/dev/libgdx-1.9.6/build-template.xml:50: Compile failed; see the compiler error output for details.

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS

**Comment by code-disaster** [comment]
Can not reproduce. I tried from both head revision and the 1.9.6 tag. Mac OS 10.12.4, ant 1.10.1.

What's your JDK version?

**Comment by Tom-Ski** [comment]
Can't reproduce either.
