### ISSUE TITLE
Does libgdx (Android) support loading a .dae file?

### ISSUE THREAD

**Issue by jaychang0917** [libgdx/libgdx#4705]
I have some questions about libgdx:
- Does it support loading a .dae model format?
- Can I apply skeleton animation like rotating a joint programmatically? 
- Does it support playing pose animation?

Thanks!

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker

**Comment by Duna** [comment]
Any news regarding this? the link posted by @xoppa is broken

**Comment by crykn** [comment]
Is it? The link was suggesting that this is an _issue_ tracker for bugs & feature requests. So any _questions_ regarding the usage of libGDX, etc. should be asked on our [Discord](https://libgdx.com/community/discord/) server instead.
