### ISSUE TITLE
NullPointerException in Bezier#approxLength

### ISSUE THREAD

**Issue by MaxMega** [libgdx/libgdx#4706]
#### Issue details
Setting the points of a Bezier path with `Bezier#set(Array<T> points, int offset, int length)` causes a subsequent call to `Bezier#approxLength(int samples)` to throw a NullPointerException.

#### Reproduction steps/code
In the aforementioned method `Bezier#set(Array<T> points, int offset, int length)` the temp variables `tmp2` and `tmp3` are not set as they should (see also the other method `Bezier#set(T[] points, int offset, int length)`). So calling `Bezier#approxLength(int samples)` throws a NPE because it uses `tmp2` and `tmp3`.

#### Version of LibGDX and/or relevant dependencies
_Please provide the version(s) affected._

#### Stacktrace
no need

#### Please select the affected platforms
- [ X ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by xoppa** [comment]
Please include the required information as requested, see also: https://github.com/libgdx/libgdx/wiki/More-Info
