### ISSUE TITLE
Support for Blender 2017

### ISSUE THREAD

**Issue by Kurimatzu** [libgdx/libgdx#4712]
Fbx-conv has never been updated, and does not support blender 2017.

Loading a normal .obj, made in blender, the following error occurs.

Invalid part specified ( offset=0, count=0, max=39804 )

Is there another Fbx-conv compatible with Blender 2017?

**Comment by mbrlabs** [comment]
You probably forgot to select a mesh when you exported the model to obj. It's very unlikly that Blender suddenly changed how the obj file format (or any other format) works.
Also make sure to read [this](https://github.com/libgdx/libgdx/wiki/Importing-Blender-models-in-LibGDX) guide.
