### ISSUE TITLE
Invalid Provisioning Profile. Application Loader

### ISSUE THREAD

**Issue by ruffiely** [libgdx/libgdx#4717]
I need to create this ticket I have no more idea. It took me time to get moe with libgdx working and now everything works fine I can test on my ipad and simulator. But I can't distribute the IPA to app store I tried everything.

So I use the command ./gradlew moeIpaBuild Build is Successfull
I upload it with the application loader and then error: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle net.rainware.cat [Payload/fatflatcat.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."

What I already did / tried. Providing signing information in build.gradle I set my distribution profile my team everything. In the logs it always seems like he is using development. Also I had to uncheck automatic signing since this also not worked. Then I tried setting up everything manually in xcode to distribution no luck. I generated new distribution profile and certificate no luck it is always the same error 90161

The build provides a log at /var/folders/z3/xsf5js3d27b1q9h45zy_2d7c0000gn/T/ios-moe_2017-04-24_13-55-01.197.xcdistributionlogs there i can only see development sigining never distribution which is set in xcode.

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [X] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by nevabyte** [comment]
Try loading the project in Xcode directly and adding your provisioning profile in their.

By loading I mean, right clicking on the ios-moe directory and clicking open in Xcode.

It should work :)

**Comment by ruffiely** [comment]
I did that. How should I build from there? I setup provisioning profile in xcode directly and executed ./gradlew moeIpaBuild afterwards same issue.

**Comment by nevabyte** [comment]
Build directly from Xcode also, don't use gradle. I think that once set in Xcode it doesn't propagate the setting to gradle, so it doesn't work.

If not then you could try downgrading MOE, as it was working before the latest update.

**Comment by ruffiely** [comment]
Thanks with xCode it is working, but I had to re add all icons and launch images which took me some time.

**Comment by nevabyte** [comment]
Glad I could help.
