### ISSUE TITLE
There are problems plotting the texture picture in android

### ISSUE THREAD

**Issue by chongbo2013** [libgdx/libgdx#4720]
1、when i set the android Acitivty theme such like this: android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen"
2、i get GLSurfaceView and setView TRANSLUCENT
      config.r = config.g = config.b = config.a = 8;
        View v=initializeForView(mListem,config);
		if (v instanceof GLSurfaceView) {
			GLSurfaceView glView = (GLSurfaceView) v;
			glView.getHolder().setFormat(PixelFormat.TRANSLUCENT);
			//glView.setZOrderMediaOverlay(true);
			//glView.setZOrderOnTop(true);
		}
3、When I draw a texture with TRANSLUCENT png , there will be a problem.

**Comment by chongbo2013** [comment]
![qq 20170425121559](https://cloud.githubusercontent.com/assets/3191545/25368696/f890d1f0-29b0-11e7-9d45-0500575ed717.jpg)
For example: see the desktop icon

**Comment by xoppa** [comment]
See: https://github.com/libgdx/libgdx/wiki/Issue-Tracker. Please use the forum or irc for personal support requests.

If you do think that there is an issue with libgdx, then please provide the information required as you were requested when opening this issue, see also: https://github.com/libgdx/libgdx/wiki/More-Info.
