### ISSUE TITLE
Freetype font rendering bug after 1.7.1 version

### ISSUE THREAD

**Issue by dawez** [libgdx/libgdx#4725]
There is a font rendering bug appearing on **ALL** versions on libgdx past 1.7.1.

In 1.71 I have:
![selection_027](https://cloud.githubusercontent.com/assets/2534771/25548569/5a9d0698-2c6d-11e7-9a42-2fcf3262576a.png)

While in 1.7.2 and tried also 1.9.6
![selection_026](https://cloud.githubusercontent.com/assets/2534771/25548567/52a416de-2c6d-11e7-903a-0dbf84699c28.png)

```java
private static float scale = ScreenResolution.GAMEHEIGHT / Gdx.graphics.getHeight();
private static void createFont(Font font, Skin skin) {
   generator = new FreeTypeFontGenerator(Gdx.files.internal("data/fonts/" + font.getTtfName()));
   FreeTypeFontGenerator.FreeTypeFontParameter parameter = new FreeTypeFontGenerator.FreeTypeFontParameter();

   parameter.minFilter = Texture.TextureFilter.Linear;
   parameter.magFilter = Texture.TextureFilter.Linear;
   parameter.genMipMaps = false;
   parameter.size = (int) Math.ceil(font.getSize() / scale);

   BitmapFont generatedFont = generator.generateFont(parameter);

   generatedFont.getData().setScale((int) 1f * scale);

   fontsList.add(generatedFont);
   skin.add(font.getName(), generatedFont, BitmapFont.class);
}
```

#### Version of LibGDX and/or relevant dependencies
1.7.2 to most recent 1.9.6

#### Please select the affected platforms
Tested on Android. Maybe affecting other platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [X] Linux
- [ ] MacOS

**Comment by NathanSweet** [comment]
Executable example please.
https://github.com/libgdx/libgdx/wiki/More-Info

**Comment by dawez** [comment]
sure here is the class BareBonesStages.java. I took the file from https://github.com/libgdx/libgdx/wiki/Getting-Help#executable-example-code and modified it. There are also some resources required [fonts and and skin] which are attached in a zip file. Please let me know if I need to provide more info.

[android_assets.zip](https://github.com/libgdx/libgdx/files/1063117/android_assets.zip)


`package com.desktop.testfonts;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Label;
import com.badlogic.gdx.scenes.scene2d.ui.Skin;
import com.badlogic.gdx.scenes.scene2d.ui.Table;
import com.badlogic.gdx.utils.viewport.ExtendViewport;

import java.util.EnumSet;

public class BarebonesStage extends ApplicationAdapter {
	private Stage stage;

	public static void main(String[] args) throws Exception {

		LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
		config.title = "Font tester";
		config.width = 384;
		config.height = 640;

		new LwjglApplication(new BarebonesStage(), config);
	}

	public void create() {
		float GAMEWIDTH = 240f;
		float GAMEHEIGHT = 400f;
		stage = new Stage(new ExtendViewport(GAMEWIDTH, GAMEHEIGHT));

		Skin skin = new Skin();
		FontLoaderTest fontLoader = new FontLoaderTest();
		fontLoader.addFontsToSkin(skin);
		skin.load(Gdx.files.internal("data_fontstester/skins/main.json"));

		Label label1 = new Label("Your Best Score: 200", skin, fontLoader.getName(Font.HUD_LABEL_SMALL));
		Label label2 = new Label("Your Best Score: 200", skin, fontLoader.getName(Font.HUD_LABEL_BIG));

		Table table = new Table();
		stage.addActor(table);
		table.setFillParent(true);

		table.debug();
		table.defaults().space(6);
		table.add(label1);
		table.row();
		table.add(label2);
	}

	public void render() {
		Gdx.gl.glClearColor(255.0f, 255.0f, 255.0f, 1f);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		stage.draw();
	}

	public void resize(int width, int height) {
		stage.getViewport().update(width, height, false);
	}

	public enum Font {
		HUD_LABEL_BIG("hud_text_big", "troika", 16),
		HUD_LABEL_SMALL("hud_text_small", "troika", 12);

		private final String name;
		private final String ttfName;
		private final int size;

		Font(String name, String ttfFileName, int size) {
			this.ttfName = ttfFileName;
			this.name = name;
			this.size = size;
		}

		private String getName() {
			return name;
		}

		private String getTtfName() {
			return ttfName;
		}

		private int getSize() {
			return size;
		}
	}

	class FontLoaderTest {
		private float scale = 400f / Gdx.graphics.getHeight();

		void addFontsToSkin(Skin skin) {
			EnumSet<Font> fonts = EnumSet.allOf(Font.class);
			for (Font font : fonts) {
				addFontToSkin(font, skin);
			}

		}

		private void addFontToSkin(Font font, Skin skin) {
			FreeTypeFontGenerator generator = new FreeTypeFontGenerator(Gdx.files.internal("data/fonts/" + font.getTtfName() + ".ttf"));
			FreeTypeFontGenerator.FreeTypeFontParameter parameter = new FreeTypeFontGenerator.FreeTypeFontParameter();
			parameter.minFilter = Texture.TextureFilter.Linear;
			parameter.magFilter = Texture.TextureFilter.Linear;
			parameter.genMipMaps = false;
			parameter.size = Math.round((float) font.getSize() / scale);

			BitmapFont generatedFont = generator.generateFont(parameter);

			generatedFont.getData().setScale(scale);

			skin.add(font.getName(), generatedFont, BitmapFont.class);
		}

		String getName(Font fontName) {
			EnumSet<Font> fonts = EnumSet.allOf(Font.class);
			for (Font font : fonts) {
				if (font == fontName) {
					return font.getName();
				}
			}
			return null;
		}
	}
}
`

**Comment by EvenAR** [comment]
Similar problem on Windows, using libktx `1.10.0-b1` (based on libgdx 1.10.0). It seems to trigger with certain Window resolutions. 

height=301:
![image](https://user-images.githubusercontent.com/5177099/115990167-25b83600-a5c2-11eb-8249-e0c0fb59cf4b.png)

height=300:
![image](https://user-images.githubusercontent.com/5177099/115990207-4a141280-a5c2-11eb-89ec-55ccd6792f42.png)


Complete example:
```kt
fun main() {
    val config = LwjglApplicationConfiguration1().apply {
        width = 300
        height = 301
        foregroundFPS = 60
    }
    LwjglApplication(TextApplication(), config)
}

class TextApplication : KtxApplicationAdapter {
    private lateinit var screenViewport: ScreenViewport;
    private lateinit var spriteBatch: SpriteBatch
    private lateinit var font: BitmapFont

    override fun create() {
        val fontBase = FreeTypeFontGenerator(Gdx.files.internal("C:\\WINDOWS\\FONTS\\COUR.TTF"))
        screenViewport = ScreenViewport()
        spriteBatch = SpriteBatch()
        font = fontBase.generateFont(FreeTypeFontGenerator.FreeTypeFontParameter().apply {
            size = 20
        })
        font.setUseIntegerPositions(false)
    }

    override fun resize(width: Int, height: Int) {
        screenViewport.update(width, height)
    }

    override fun render() {
        screenViewport.camera.update()
        spriteBatch.use(screenViewport.camera.combined) {
            font.draw(it, "Hello world", 0f, 0f)
        }
    }
}
```

**Comment by tommyettinger** [comment]
I cannot reproduce this; it may be an issue with DPI scaling on your particular OS and machine. Using the system ARIAL.TTF file (not Courier, because you didn't take a screenshot with Courier), I get this with height 300:

![Height 300](https://i.imgur.com/jKc3zBJ.png)

And this with height 301:

![Height 300](https://i.imgur.com/yI6HzHD.png)

Here's my code, in Java without KTX:

```java
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator;
import com.badlogic.gdx.utils.ScreenUtils;
import com.badlogic.gdx.utils.viewport.ScreenViewport;

public class Issue4725 extends ApplicationAdapter {

    private ScreenViewport screenViewport;
    private SpriteBatch spriteBatch;
    private BitmapFont font;

    @Override
    public void create() {
        FreeTypeFontGenerator fontBase = new FreeTypeFontGenerator(Gdx.files.absolute("C:\\WINDOWS\\FONTS\\ARIAL.TTF"));
        screenViewport = new ScreenViewport();
        spriteBatch = new SpriteBatch();
        FreeTypeFontGenerator.FreeTypeFontParameter param = new FreeTypeFontGenerator.FreeTypeFontParameter();
        param.size = 20;
        font = fontBase.generateFont(param);
        font.setUseIntegerPositions(false);
    }
    @Override
    public void resize(int width, int height) {
        screenViewport.update(width, height);
    }
    @Override
    public void render() {
        ScreenUtils.clear(Color.BLACK);
        screenViewport.getCamera().update();
        spriteBatch.setProjectionMatrix(screenViewport.getCamera().combined);
        spriteBatch.begin();
        font.draw(spriteBatch, "Hello world", 0f, 0f);
        spriteBatch.end();
    }
}
```

I tried both desktop (LWJGL2) and LWJGL3, with the same results. Both of those I configured to 300 and 301 height in the configuration for the launcher.

I noticed your code doesn't clear the screen; could that be the issue? Does KTX handle that silently?

**Comment by NathanSweet** [comment]
Wow, originally from 2017. Sorry this was missed!

It looks OK for me:
![](http://n4te.com/x/1895-VnD0.png)

The other example code I can't run because it isn't Java.

tommyettinger's code at 300 height:
![](http://n4te.com/x/1896-XUkO.png)
At 301:
![](http://n4te.com/x/1897-6eNV.png)

The viewport is setup so 0,0 is at the center of the window. The odd window dimension means 0,0 falls on a half pixel, so you get filtering. `screenViewport.update(width, height, true);` can be used so 0,0 is the bottom left corner of the window, rather than the center, and since it falls on a pixel there won't be filtering artifacts.

```
public class Issue4725 extends ApplicationAdapter {
	private ScreenViewport screenViewport;
	private SpriteBatch spriteBatch;
	private BitmapFont font;

	public void create () {
		FreeTypeFontGenerator fontBase = new FreeTypeFontGenerator(Gdx.files.absolute("C:\\WINDOWS\\FONTS\\ARIAL.TTF"));
		screenViewport = new ScreenViewport();
		spriteBatch = new SpriteBatch();
		FreeTypeFontGenerator.FreeTypeFontParameter param = new FreeTypeFontGenerator.FreeTypeFontParameter();
		param.size = 20;
		font = fontBase.generateFont(param);
		font.setUseIntegerPositions(false);
	}

	public void resize (int width, int height) {
		screenViewport.update(width, height, true);
	}

	public void render () {
		ScreenUtils.clear(Color.BLACK);
		screenViewport.getCamera().update();
		spriteBatch.setProjectionMatrix(screenViewport.getCamera().combined);
		spriteBatch.begin();
		font.draw(spriteBatch, "Hello world", 100, 100);
		spriteBatch.end();
	}

	static public void main (String[] args) throws Exception {
		LwjglApplicationConfiguration c = new LwjglApplicationConfiguration();
		c.height = 301;
		new LwjglApplication(new Issue4725(), c);
	}
}
```

If there is still an issue please let us know and we'll reopen.
