### ISSUE TITLE
html libgdx load the game twice ?

### ISSUE THREAD

**Issue by alaaodeh95** [libgdx/libgdx#4733]
Hello 
i just deployed my libgdx project into html5 ,working perfect
its loaded into this
`<div  id="embed-html"></div>
`what i want is to load the game twice ,,not just one time
i need this too much 
anyway to fix this ?
i cant access any thing about "embed-html"
can i access the game with another div with another id

**Comment by doomers** [comment]
can you please explain what do you mean by load the game twice
do you want to instantiate two instances of game in a single Webpage()
