### ISSUE TITLE
Headless Application Updates Faster than specified interval

### ISSUE THREAD

**Issue by ckcornflake** [libgdx/libgdx#4742]
Please ensure you have given all the following requested information in your report.

#### Issue details
HeadlessApplication updates at a rate faster than the specified interval.  For example, I've taken the average delta time for a headless application for the default interval (60 frames per second).   Expected average is around 16.666 ms, but I get around 16.3 ms on average.

#### Reproduction steps/code
Implement an Application Listener and record the delta times of each frame.  Take a sample of a few dozen (or any number) deltaTimes and average them.   Replacing this line: 

t = TimeUtils.nanoTime() + interval

with this

t += interval;

Corrected the issue.

#### Version of LibGDX and/or relevant dependencies
Master branch.

#### Stacktrace
Not necessary.

#### Please select the affected platforms
- Headless

**Comment by noblemaster** [comment]
That appears to be a bug.

**Comment by MrStahlfelge** [comment]
Caused because nanotime is not taken into account for Thread.sleep.

**Comment by tommyettinger** [comment]
This should be fixed in the next nightly by @MrStahlfelge 's PR #6265 , which I just merged.
