### ISSUE TITLE
Add a way to convert TextureRegion to Texture or more advanced SpriteBatch calls

### ISSUE THREAD

**Issue by egordorichev** [libgdx/libgdx#4746]
I've just swiched from assets manager to texture atlas. 
Here is my code before:

```java
Graphics.batch.draw(this.tiles, x * Block.SIZE,
			y * Block.SIZE, Block.SIZE, Block.SIZE,
			Block.SIZE * (binary), variant * Block.SIZE, Block.SIZE,
			Block.SIZE, false, false);
```

But now, because I can't convert TextureRegion (with is produced by TextureAtlas), I've switched to TextureRegions.

But the thing is, that I can't render it with the same code! There is not SpriteBatch call,  for drawing TextureRegion with custom src!

**Please, add a way to convert TextureRegion to Texture or more advanced SpriteBatch calls !**
Thanks.

**Comment by egordorichev** [comment]
@Tom-Ski, why did you close the issue?

**Comment by Tom-Ski** [comment]
You don't switch from asset manager to texture atlas, these are two very different things.
You don't convert a TextureRegion to a Texture, a TextureRegion references a certain area of a Texture.

Please use the forum or the irc channel for assistance, or state explicitly what it is you think is missing. 

Please see https://github.com/libgdx/libgdx/wiki/Issue-Tracker
