### ISSUE TITLE
BitmapFont after 1.5.5 update: scale with no good letter pacing

### ISSUE THREAD

**Issue by buzzo123** [libgdx/libgdx#4747]
I had a game with the old version of FreeType lib. For some reason, I update the lib but there was some change to do, so I did. But after I have a problem with the letter spacing.
i change
bitmapFont.SetScale();
with
bitmapFont.getData().SetScale();

but the letter spacing between letter is not correct

this is a link from my question on StackOverflow:
http://stackoverflow.com/questions/44018970/libgdx-freetype-new-lib-issue-with-letter-spacing/44022243?noredirect=1#comment75090417_44022243

**Comment by itsabhiaryan** [comment]
I am trying to specify this issue more clearly here #4751
