### ISSUE TITLE
Libgdx internals conflict with JLayer?

### ISSUE THREAD

**Issue by 01HD** [libgdx/libgdx#4748]
#### Issue details
I'm trying to get PCM data from a MP3 file and Jlayer seems to be the main way of doing so (at least in java).
Whenever I call the decodeFrame method of Jlayer, I get an error saying it can't find the method. I used gradle to add the Jlayer dependency. This only occurs when it's a LibGDX project as I created a non LibGDX gradle project and added MP3SPI and everything worked fine.

Another thing to note is that Jlayer also works when I moved the dependency in the build.gradle to the top (LibGDX dependencies are below Jlayer's) and make sure gradle is loading in the order ```build.gradle``` is in (gradle classpath sorting strategy set to "As returned by build script" in Eclipse). However doing this broke the MP3 music playback from LibGDX.

This seems to be an issue of java reflection. 

PS: I was originally using Mp3SPI alongside Jlayer but noticed the error. I realized it was an issue with Jlayer and LibGDX.

#### Reproduction steps/code
1. create new LibGDX project (Desktop and Android selected, Freetype is the only tool)
2. Use example code from MP3SPI documentation: http://www.javazoom.net/mp3spi/documents.html
3. Added MP3SPI dependency to ```build.gradle```
4. launch (make sure to specify path to music (mp3).

The code below is copy and paste ready and will show the same error as long as the project is set up following the previously mentioned steps.
```java
//The following only works if MP3SPI's dependency in build.gradle is above all other dependencies and gradle's classpath order system is following the build script.

public class MyGdxGame extends ApplicationAdapter {
	SpriteBatch batch;
	Texture img;

	@Override
	public void create() {
		batch = new SpriteBatch();
		img = new Texture("badlogic.jpg");
		
		testPlay("PATH TO MUSIC");
	}

	@Override
	public void render() {
		Gdx.gl.glClearColor(1, 0, 0, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		batch.begin();
		batch.draw(img, 0, 0);
		batch.end();
	}

	@Override
	public void dispose() {
		batch.dispose();
		img.dispose();
	}

	public void testPlay(String filename) {
		try {
			File file = new File(filename);
			AudioInputStream in = AudioSystem.getAudioInputStream(file);
			AudioInputStream din = null;
			AudioFormat baseFormat = in.getFormat();
			AudioFormat decodedFormat = new AudioFormat(AudioFormat.Encoding.PCM_SIGNED, baseFormat.getSampleRate(), 16,
					baseFormat.getChannels(), baseFormat.getChannels() * 2, baseFormat.getSampleRate(), false);
			din = AudioSystem.getAudioInputStream(decodedFormat, in);
			// Play now.
			rawplay(decodedFormat, din);
			in.close();
		} catch (Exception e) {
			// Handle exception.
		}
	}

	private void rawplay(AudioFormat targetFormat, AudioInputStream din) throws IOException, LineUnavailableException {
		byte[] data = new byte[4096];
		SourceDataLine line = getLine(targetFormat);
		if (line != null) {
			// Start
			line.start();
			int nBytesRead = 0, nBytesWritten = 0;
			while (nBytesRead != -1) {
				nBytesRead = din.read(data, 0, data.length);
				if (nBytesRead != -1)
					nBytesWritten = line.write(data, 0, nBytesRead);
			}
			// Stop
			line.drain();
			line.stop();
			line.close();
			din.close();
		}
	}

	private SourceDataLine getLine(AudioFormat audioFormat) throws LineUnavailableException {
		SourceDataLine res = null;
		DataLine.Info info = new DataLine.Info(SourceDataLine.class, audioFormat);
		res = (SourceDataLine) AudioSystem.getLine(info);
		res.open(audioFormat);
		return res;
	}
}
```

#### Version of LibGDX and/or relevant dependencies
LibGDX 1.9.6
MP3SPI 1.9.5
JLayer 1.0.1
Tritonus 0.3.7

#### Stacktrace
```java
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: javazoom.jl.decoder.LayerIIIDecoder.<init>(Ljavazoom/jl/decoder/Bitstream;Ljavazoom/jl/decoder/Header;Ljavazoom/jl/decoder/SynthesisFilter;Ljavazoom/jl/decoder/SynthesisFilter;Ljavazoom/jl/decoder/Obuffer;I)V
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchMethodError: javazoom.jl.decoder.LayerIIIDecoder.<init>(Ljavazoom/jl/decoder/Bitstream;Ljavazoom/jl/decoder/Header;Ljavazoom/jl/decoder/SynthesisFilter;Ljavazoom/jl/decoder/SynthesisFilter;Ljavazoom/jl/decoder/Obuffer;I)V
	at javazoom.jl.decoder.Decoder.retrieveDecoder(Decoder.java:229)
	at javazoom.jl.decoder.Decoder.decodeFrame(Decoder.java:145)
	at javazoom.spi.mpeg.sampled.convert.DecodedMpegAudioInputStream.execute(DecodedMpegAudioInputStream.java:185)
	at org.tritonus.share.TCircularBuffer.read(TCircularBuffer.java:138)
	at org.tritonus.share.sampled.convert.TAsynchronousFilteredAudioInputStream.read(TAsynchronousFilteredAudioInputStream.java:197)
	at com.mygdx.game.MyGdxGame.rawplay(MyGdxGame.java:71)
	at com.mygdx.game.MyGdxGame.testPlay(MyGdxGame.java:56)
	at com.mygdx.game.MyGdxGame.create(MyGdxGame.java:28)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

```

#### Please select the affected platforms
Im just going to assume that its not going to work on all platforms because this error doesn't seem very relevant to platform. I am using **Windows** though, and have not tried running on android.

**Comment by Zomby2D** [comment]
Libgdx uses a [modified version of JLayer](https://github.com/libgdx/jlayer-gdx) for MP3 decoding on the desktop. When you're changing the loading order in the Gradle build, it changes which version is loaded.

**Comment by 01HD** [comment]
Ah thanks, I was lead to believe that I should be using Jlayer original version due to a post somewhere else and since I can't actually access Libgdx's built in Jlayer backend (since it's in a different project) I believed it.

Right then, no reason to keep this opened then.
