### ISSUE TITLE
Not able to render BitmapFont properly, I've generated font by gdx-freetype

### ISSUE THREAD

**Issue by itsabhiaryan** [libgdx/libgdx#4751]
When I render BitmapFont, it's not properly render. I am using latest version **1.9.6**. When I tried with version **1.5.5**, it's works fine. 

I tried many different `.ttf`, Result are almost same for all files.

This is my Test Code :

```
public class MyGdxGame extends ApplicationAdapter {

	SpriteBatch batch;
	Texture img;

	BitmapFont font;
	OrthographicCamera camera;

	@Override
	public void create () {
		batch = new SpriteBatch();
		img = new Texture("badlogic.jpg");

		float w=Gdx.graphics.getWidth();
		float h=Gdx.graphics.getHeight();

		float worldWidth=400;
		float worldHeight=h / (w / worldWidth);

		camera=new OrthographicCamera();
		camera.setToOrtho(false,worldWidth,worldHeight);

		FreeTypeFontGenerator freeTypeFontGenerator=new FreeTypeFontGenerator(Gdx.files.internal("ariblk.ttf"));
		FreeTypeFontGenerator.FreeTypeFontParameter ftp=new FreeTypeFontGenerator.FreeTypeFontParameter();
		ftp.size=400;
		font=freeTypeFontGenerator.generateFont(ftp);

		font.setScale(0.04f);  // when I use version 1.5.5
               //font.getData().setScale(0.04f);    // when I use version 1.9.6
	}

	@Override
	public void render () {

		Gdx.gl.glClearColor(1, 0, 0, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

		batch.setProjectionMatrix(camera.combined);

		batch.begin();
		font.draw(batch,"LEADERBOARD",10,200);
		batch.end();
	}
}
```

And Result with both version 

<img width="425" alt="screen shot 2017-05-20 at 9 08 07 pm" src="https://cloud.githubusercontent.com/assets/7019724/26277017/48ee7752-3da1-11e7-80ae-344da81e0fd2.png">

**Comment by MrGussio** [comment]
Does the same thing happen by using 
> font.getData().scale(0.04f);

instead of

> font.getData().setScale(0.04f);

Because when I look into the docs, there are 3 different methods for the scaling of BitmapFontData:
1) setScale(float scaleX, float scaleY), individual axes
2) setScale(float scaleXY), both axes
3) scale(float amount), relative scale

I think you should be using the 3rd one instead of the 2nd, because you're right now not scaling it relatively.

**Comment by itsabhiaryan** [comment]
@MrGussio,  I know the difference between these three methods.

1st  : -  Scales the font by the **specified amounts** on respective axes
2nd  : -  Do same thing as in 1st, with same amount on both directions/axes
3rd  : - Sets the font's scale **relative to the current scale**.

but this is not my question, Please read my issue once more !

When I scale down my font with large amount then not able to draw properly, I've attached image for the same. 

Also no rendering problem when I use  version 1.5.5. There is some [bitmapFont refactoring ](http://www.badlogicgames.com/wordpress/?p=3658) on March 24, 2015 so I use previous version 1.5.5 for testing.

**Comment by piotr-j** [comment]
You need to do this `font.setUseIntegerPositions(false);` if you want to scale fonts to very small sizes.

**Comment by itsabhiaryan** [comment]
@piotr-j Thanks for suggestion, but still same result with your suggestion.

**Comment by piotr-j** [comment]
Are you certain the the generator is the problem here? Try making the font in hiero instead and see if it renders correctly.

**Comment by itsabhiaryan** [comment]
When I tried same `.ttf` file with gdx version 1.5.5, It's working fine so I conclude, there is some issue in [BitmapFont Refectoring](http://www.badlogicgames.com/wordpress/?p=3658).

**Comment by piotr-j** [comment]
Many things changed. Its entirely possible that generator is broken for some fonts. Make the bitmap font in hiero and see if it works.

**Comment by itsabhiaryan** [comment]
Yeah lot of changes. I've tested many `.ttf` files so I don't think so problem is in `.ttf` file, If problem is in `.ttf` then why result with version 1.5.5 is fine.  I have to use gdx-freetype this is my 1<sup>st</sup> requirement so I can't use hiero that generate BitmapFont(`.fnt` file and associated `.png` file)

**Comment by piotr-j** [comment]
Your 1st requirement should be to find out which part is broken. You have a .ttf on one end and broken rendering on the other. Try to figure out a way to narrow down where the problem is.
