### ISSUE TITLE
Wrong ppi on iOS-MOE

### ISSUE THREAD

**Issue by FlorentMasson** [libgdx/libgdx#4755]
#### Issue details
the ppi of display is not calculated from the machine string, the lines are commented out... is there any reason ?
https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-moe/src/com/badlogic/gdx/backends/iosmoe/IOSGraphics.java#L163

#### Version of LibGDX and/or relevant dependencies
1.9.6

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [X] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
iirc something wasn't working correctly when I wrote the backend.  I'll take another look to see if its good now.

**Comment by Tom-Ski** [comment]
This should be fixed, testers wanted!
