### ISSUE TITLE
BaseTmxMapLoader: Add Support for Color type

### ISSUE THREAD

**Issue by jwillp** [libgdx/libgdx#4756]
#### Issue details
Tiled has now a new type of custom properties for Colors, which causes the Loader crash.
The code responsible for this is at line 283:
```java
		if (type == null) {
			return value;
		} else if (type.equals("int")) {
			return Integer.valueOf(value);
		} else if (type.equals("float")) {
			return Float.valueOf(value);
		} else if (type.equals("bool")) {
			return Boolean.valueOf(value);
		} else {
			throw new GdxRuntimeException("Wrong type given for property " + name + ", given : " + type
				+ ", supported : string, bool, int, float");
		}
```

I think a simple fix would be to do this (not tested):
```java 
else if (type.equals("color")) {
   return Color.valueOf(value);
}
```

#### Reproduction steps
1. Create a map with a custom map property of type color. 
1. Load that map with TmxMapLoader.

#### Version of LibGDX and/or relevant dependencies
latest on branch master

#### Stacktrace
```java
[17:00:49][FATAL]: Wrong type given for property ambiant_color, given : color, supported : string, bool, int, float
[17:00:49][FATAL]: com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.castProperty(BaseTmxMapLoader.java:289)
com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadProperties(BaseTmxMapLoader.java:273)
com.badlogic.gdx.maps.tiled.TmxMapLoader.loadTilemap(TmxMapLoader.java:202)
com.badlogic.gdx.maps.tiled.TmxMapLoader.load(TmxMapLoader.java:90)
com.badlogic.gdx.maps.tiled.TmxMapLoader.load(TmxMapLoader.java:65)
com.goatgames.ogruntime.OGRTGameScene.loadConfig(OGRTGameScene.java:98)
```

#### Please select the affected platforms
Libgdx core

#### Additionnal note
I guess this issue would also apply to object properties since they seem to share the MapProperties class,.

**Comment by jojorabbit** [comment]
Hi,
As far as I know Color and File are not supported, it should not be hard to add it, if you don't know how to make PR I or somebody else can do it, there is no problem with that.
I even think there is already PR for your problem, try searching issue list I remember seeing something like your issue a few weeks ago.
