### ISSUE TITLE
Key events not firing on games within Facebook

### ISSUE THREAD

**Issue by WillCalderwood** [libgdx/libgdx#4758]
#### Issue details
`keyDown`, `keyUp` and `keyTyped` are not being fired when a game in played within Facebook. The certainly worked in the past but I'm not sure if something has changed Facebook side or the libgdx side.

I've added logging on the keypress events on the menu screen.

Open a game outside of Facebook here and display the console within the browser and press some keys and you'll see logging.
https://wordburst-html5.appspot.com/build/index.jsp

Open a game within Facebook (Facebook points to the above URL, so it's the same code) here and display the console within the browser. Press keys and you'll see no logging.
https://apps.facebook.com/scribble-wordburst/

(Tested in Chrome and Firefox)

#### Reproduction steps/code
```
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.InputProcessor;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;

public class MyGdxGame extends ApplicationAdapter implements InputProcessor {
    SpriteBatch batch;
    Texture img;
    private int x = 0;
    private int y = 0;

    @Override
    public void create() {
        batch = new SpriteBatch();
        img = new Texture("badlogic.jpg");
        Gdx.input.setInputProcessor(this);
    }

    @Override
    public void render() {
        Gdx.gl.glClearColor(1, 0, 0, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        batch.begin();
        batch.draw(img, x, y);
        batch.end();
    }

    @Override
    public void dispose() {
        batch.dispose();
        img.dispose();
    }

    @Override
    public boolean keyDown(int keycode) {
        x += 10;
        return false;
    }

    @Override
    public boolean keyUp(int keycode) {
        y += 10;
        return false;
    }

    @Override
    public boolean keyTyped(char character) {
        if (character == 'x') {
            x = 0;
            y = 0;
        }

        return false;
    }

    @Override
    public boolean touchDown(int screenX, int screenY, int pointer, int button) {
        return false;
    }

    @Override
    public boolean touchUp(int screenX, int screenY, int pointer, int button) {
        return false;
    }

    @Override
    public boolean touchDragged(int screenX, int screenY, int pointer) {
        return false;
    }

    @Override
    public boolean mouseMoved(int screenX, int screenY) {
        return false;
    }

    @Override
    public boolean scrolled(int amount) {
        return false;
    }
}
```

#### Version of LibGDX and/or relevant dependencies
1.9.6

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [x] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by MrStahlfelge** [comment]
I think this is the same problem as in #2479 

The index.html template file should be improved.

**Comment by WillCalderwood** [comment]
@MrStahlfelge Yup, you nailed it. I'll look at changing the index template.

**Comment by WillCalderwood** [comment]
I've submitted a pull request in what I assume in the template for the index file
https://github.com/libgdx/libgdx/pull/4772
