### ISSUE TITLE
Controllers not working in GWT backend

### ISSUE THREAD

**Issue by MrStahlfelge** [libgdx/libgdx#4768]
#### Issue details
Controllers are not working in GWT backend. getControllers returns an empty list. 
I have no problems with my game on Android and on Desktop.

* The sample space invaders does also not work with controllers in my browser. 
* http://html5gamepad.com/ works with all my gamepads and browsers. 
* [Gamescratch demo](http://www.gamefromscratch.com/post/2014/09/22/LibGDX-Tutorial-Part-14-Gamepad-support.aspx) also reports no connected controller.

#### Reproduction steps/code
Use gdx invaders demo. 

#### Version of LibGDX and/or relevant dependencies
1.9.6 and GWT 2.8, also on 1.9.4 and GWT 2.6.1

#### Stacktrace
No stacktrace, but I suppose problem exists because gamepad support is not experimental in the browsers any more.

I debugged a bit and this method causes the problem:
`
	private static native JsArray<Gamepad> nativePollGamepads() /*-{
		return rawGamepads = (navigator.webkitGetGamepads && navigator.webkitGetGamepads()) || navigator.webkitGamepads;
	}-*/;
`

This must include calling the function without webkit prefix.
`return rawGamepads = navigator.getGamepads ? navigator.getGamepads() : ((navigator.webkitGetGamepads && navigator.webkitGetGamepads()) || navigator.webkitGamepads);`

Also, according to this [documentation](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API), the events "MozGamepadConnected" and "...disconnected" doesn't exist anymore, but "gamepadconnected" / "gamepaddisconnected".

#### Please select the affected platforms
- [x] HTML/GWT

**Comment by MrStahlfelge** [comment]
Another change is needed because gamepad.buttons is a list of objects, not of values any more.

In GwtControllers.java:
float oldButton = controller.getButtonAmount(i);
float newButton = **gamepad.getButton(i);**
GamepadSupport.consoleLog(i + ": " + oldButton + ", " + newButton);

In Gamepad.java a new method is needed:
	public native float getButton(int i) /*-{
	    var b = this.buttons[i];
        if (typeof(b) == "object") {
          return b.value;
        }
		return b;
	}-*/;

`

**Comment by MrStahlfelge** [comment]
I forked the project and sent a pull request #4780 on this issue. This was my first contribution ever made. I hope I did everything right.

**Comment by intrigus** [comment]
Did you try https://github.com/libgdx/libgdx/pull/4715 ? It seems to fix the same issue.

**Comment by MrStahlfelge** [comment]
Yes, it does. However, it replaces the old API with the new one. This works on all modern browsers, but I would be careful with this approach. So my implementation (which is just copied from the linked Mozilla's doc) adds the new API and falls back to the old one when it is not available.

**Comment by Zomby2D** [comment]
Are you aware of any browser which still uses the old api? And wouldn't the Gamepad button be in the wrong format anyway if the library was run against a bowser using the old webkit? When I submitted #4715 it was based on the [W3C Editor's Draft](https://w3c.github.io/gamepad/) which of course didn't include any fallback.

I'm just wondering if there's a point in keeping the old code in there, especially since it's now untested with the new buttons objects.

**Comment by MrStahlfelge** [comment]
I don't know which browsers do use the old API and when the change from the old to the new one were made. When the API change is not long ago there might still be users using a browser with the webkit API, but it's also my personal preference to keep backward compatibility when there is no drawback from it.

Anyway, I will be happy when the controllers work again in libGDX-gwt no matter which commit is used for it (although I would be honoured being a contributor to the project).

**Comment by Zomby2D** [comment]
The updated API has been in use for 3 years now (between April and June 2014 depending on the browser) I wouldn't call that recent. AFAIK, the extension has been broken for just as long.

There's probably no real drawback in keeping the old webkit API around though.

**Comment by MrStahlfelge** [comment]
No, that is not recent. This is strange, is the controller extension really this rarely used? In my opinion the extension also needs some other improvements.

**Comment by Tom-Ski** [comment]
Thanks for the report and PR.
