### ISSUE TITLE
1.9.6 GWT backend won't start in Firefox with Flash

### ISSUE THREAD

**Issue by MrStahlfelge** [libgdx/libgdx#4771]
#### Issue details
HTML5 game compiled with libGDX 1.9.6 won't start in Firefox with Flash and remain blank on Windows 10. Firefox without Flash and Chrome don't have a problem.

The Javascript console logs the following output:

SoundManager V2.97a.20130512 (AS3/Flash 9) + HTML5 audio + preferFlash  soundmanager2-jsmin.js:32:357
SoundManager 2 HTML5 support: mp3 = true (preferring flash), mp4 = true (preferring flash), ogg = true, opus = true, wav = true  soundmanager2-jsmin.js:32:357
Error: Permission denied to access property "href"[Weitere Informationen]  (unbekannt)
Error: soundManager: Fatal: JavaScript file build "V2.97a.20130512" does not match Flash SWF build "V2.97a.20150601" at https://v6p9d9t4.ssl.hwcdn.net/html/495497/html/soundmanager2_flash9_debug.swf. Ensure both are up-to-date.  soundmanager2-jsmin.js:94:452
soundManager: No Flash response within expected time. Likely causes: Flash blocked or JS-Flash security error.  soundmanager2-jsmin.js:32:357
soundManager.disable(): Shutting down  soundmanager2-jsmin.js:32:357
SoundManager 2 failed to load (Flash security/load error)  soundmanager2-jsmin.js:32:357

Probable cause:  #4426 

#### Reproduction steps/code
Compile a HTML5 game and run it in Firefox with Flash enabled.

#### Version of LibGDX and/or relevant dependencies
libGDX 1.9.6
libGDX 1.9.4 worked fine.

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [X] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by MrStahlfelge** [comment]
preferFlash=false prevents the problem. Nevertheless, it should be fixed asap. It prevents starting the whole libgdx application on Firefox with Flash.

**Comment by Tom-Ski** [comment]
Pretty sure this is already fixed. @intrigus can you confirm?

**Comment by MrStahlfelge** [comment]
No, [update documentation](https://github.com/libgdx/libgdx/wiki/Updating-LibGDX) isn't changed so far. Everyone coming from < 1.9.6 will get this problem.

**Comment by Tom-Ski** [comment]
I'm talking about the issue itself. Wiki documentation is editable by everyone, feel free to add anything you feel needs adding.
