### ISSUE TITLE
Little to no sound on iOS devices via internal speakers

### ISSUE THREAD

**Issue by euphonialabs** [libgdx/libgdx#4784]
#### Issue details
Sound is low/virtually non-existent on iOS devices if using internal speakers. When hooked up to headphones or external speakers, there is no problem. Tested on iPhone 5S and iPhone 6S.

#### Reproduction steps/code
Case A:

Follow the instructions at https://github.com/libgdx/libgdx/wiki/Sound-effects. Use any sound file. Run on iOS using RoboVM and confirm that there is no sound.

Case B:

Test on iOS with RoboVM the project at https://github.com/libgdx/libgdx-demo-superjumper. Confirm that there is no sound.

#### Version of LibGDX and/or relevant dependencies
(Tested to not work)
1.9.6, RoboVM 2.3.0
1.9.4, RoboVM 2.2.0

#### Stacktrace
N/A

#### Please select the affected platforms
- [x] iOS (robovm)

**Comment by Tom-Ski** [comment]
Can't reproduce.

**Comment by Lestat** [comment]
maybe you're sterile, or maybe not, just keep trying tomski, find a good woman and you will be able to reproduce.

**Comment by euphonialabs** [comment]
You're right. I did a system wipe and everything works without a hitch. Call it a freak incident.
