### ISSUE TITLE
Lwjgl3 crash on start

### ISSUE THREAD

**Issue by VladoCC** [libgdx/libgdx#4791]
#### Issue details
I switched on lwjgl3 from lwjgl2 and can't run game with that.

#### Reproduction steps/code
Lwjgl3ApplicationConfiguration config = new Lwjgl3ApplicationConfiguration();
config.setWindowedMode(1280, 720);
new Lwjgl3Application(new MyGdxGame(), config);

#### Version of LibGDX and/or relevant dependencies
LibGDX and Lwjgl ersion is 1.9.6

#### Stacktrace
https://pastebin.com/0N1tAYRk

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
Are you using lwjgl2 dependency still? Do you have gdx-tools or the lwjgl2 backend as a dependency still? If so, remove those.

**Comment by VladoCC** [comment]
Hm.. Gdx-tools? Idon't have lwjgl2 backend as a dependency, but I don't know what I need to do with gdx-tools. Can you explain it?

**Comment by Tom-Ski** [comment]
If you have it in your root build.gradle, you have to remove it.  Share your root build.gradle file.

**Comment by VladoCC** [comment]
No, I don't have his dependency or can't find where it is.
You can see my root `build.gradle` [here](pastebin.com/cE0XwFjR)

**Comment by Tom-Ski** [comment]
can you run on command line with `./gradlew  desktop:run` ?

**Comment by VladoCC** [comment]
No, I don't know how to do it.

**Comment by VladoCC** [comment]
Ok.. I ran it. 
Full log you van see [here](https://pastebin.com/uhqGZ9QW)

**Comment by Tom-Ski** [comment]
Can you run the following command line commands and pastebin the output of each.
`./gradlew desktop:dependencies`
`./gradlew -version`
`java -version`

**Comment by VladoCC** [comment]
1. https://pastebin.com/xj5E0hVV
2. https://pastebin.com/jXtFeC29
3. https://pastebin.com/HLMtdA7C

**Comment by Tom-Ski** [comment]
Lwjgl2 is still being brought in, can you run ./gradlew core:dependencies

**Comment by VladoCC** [comment]
Yeah, you right. Core project have dependency to lwjgl, but I cab't find info about raplacement for it.
https://pastebin.com/tdYnV7Rh

**Comment by Tom-Ski** [comment]
Can you pastebin your current root build.gradle and also your core/build.gradle file? That should not be a dependency in core.

**Comment by VladoCC** [comment]
1. Root https://pastebin.com/cE0XwFjR
2. Core https://pastebin.com/fYUn23YR

**Comment by Tom-Ski** [comment]
> dependencies {
>     compile 'org.lwjgl.lwjgl:lwjgl:2.9.2'
> }

In your core/build.gradle, remove it.

**Comment by VladoCC** [comment]
Can I ask second question here or need to create new issue?

**Comment by Tom-Ski** [comment]
The issue tracker if for bugs, if its a question please use the forums or the irc channel.
