### ISSUE TITLE
Fbx/g3db animation and attached models BUG?

### ISSUE THREAD

**Issue by klaszlo8207** [libgdx/libgdx#4794]
I have a custom model instance, animated fbx, g3db. And I have a model that I created an attached to it.

```
    attachedModel.globalTransform.setToTranslation(0, 4.4f, 16.6f);
```
When I animating the g3db via a controller, than my attached models transform's position will be (0, 0, 0), so it can't keep the attached positions until the animation is end... When the animation is ended than the attached models positions will be again the same : (0, 4.4f, 16.6f) 

Any help?

**Comment by Tom-Ski** [comment]
Please fill out the issue tracker template correctly when posting an issue.
