### ISSUE TITLE
Wrong xAdvance for labels when using markdown

### ISSUE THREAD

**Issue by dkarchnak** [libgdx/libgdx#4800]
#### Issue details
When using labels with markdown, xAdvance for GlyphLayout.GlyphRun is not calculated correctly, which results in unwanted spaces in the text.

#### Reproduction steps/code
The easiest way to reproduce this issue is by slightly changing BitmapFontTest.
Add following code to BitmapFontTest.create() method and compare 2 newly added labels.

```
labelToCompareA = new Label("This is a Test Label, to see if color markdown affects labels in any unwanted way!", skin);
labelToCompareB = new Label("This is a [GREEN]Test Label[], to see if color markdown affects labels in any unwanted way!", skin);
		
labelToCompareA.setPosition(100, 350);
labelToCompareB.setPosition(100, 380);
		
labelToCompareA.debug();
labelToCompareB.debug();
		
stage.addActor(labelToCompareA);
stage.addActor(labelToCompareB);
```

#### Screenshot of the issue
![labels](https://user-images.githubusercontent.com/16850838/27644664-6a3ae804-5c24-11e7-820b-6fa39f99c9f1.png)

#### Version of LibGDX and/or relevant dependencies
Current master branch is affected by this issue. This problem probably exists for a while though.

#### Please select the affected platforms
I believe all platforms are affected.

**Comment by dkarchnak** [comment]
I managed to fix this issue by editing class BitmapFont on line 801.

Original:
```
if (lastGlyph == null) { // First glyph.
    xAdvances.add((!tightBounds || glyph.fixedWidth) ? 0 : -glyph.xoffset * scaleX - padLeft);
}
```

Fixed:
```
if (lastGlyph == null) { // First glyph.
    xAdvances.add((!tightBounds || glyph.fixedWidth) ? 0 :  -padLeft);
}
```

Since it's first character I dont think we need to care about glyph xoffset. I might be wrong though. :)

**Comment by NathanSweet** [comment]
The negative `xoffset` is important. Some glyphs have pixels to the left of the glyph position.

I don't see a problem:
![](http://n4te.com/x/4702-VsCr.png)
Test case:
http://n4te.com/x/4703-SXJ6.txt

Please provide an actual test case that shows a problem, not partial instructions on how to construct one.

**Comment by CreamyCookie** [comment]
@NathanSweet  

Here's a testcase (might be a different problem then OP, but it's also about sth. being offset):

```java
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application;
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration;
import com.badlogic.gdx.files.FileHandle;
import com.badlogic.gdx.tests.utils.GdxTest;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Label;
import com.badlogic.gdx.scenes.scene2d.ui.Label.LabelStyle;
import com.badlogic.gdx.utils.viewport.ScreenViewport;


public class Issue4800 extends GdxTest {
    private Stage stage;

    public void create() {
        FileHandle file = Gdx.files.absolute("/tmp/04B_03.ttf");
        FreeTypeFontGenerator generator = new FreeTypeFontGenerator(file);


        BitmapFont font = generator.generateFont(new FreeTypeFontGenerator.FreeTypeFontParameter());

        font.getData().markupEnabled = true;
        font.getData().breakChars = new char[]{'-'};

        stage = new Stage(new ScreenViewport());

        LabelStyle style = new LabelStyle();
        style.font = font;
        Label labelToCompareA = new Label("Test: This is a Test Label, and more words.", style);
        Label labelToCompareB = new Label("[RED]Text[]: This is a [GREEN]Test Label[], and more words.", style);

        labelToCompareA.setPosition(10, 350);
        labelToCompareB.setPosition(10, 400);

        labelToCompareA.debug();
        labelToCompareB.debug();

        stage.addActor(labelToCompareA);
        stage.addActor(labelToCompareB);
    }

    public void render() {
        Gdx.gl.glClearColor(0, 0, 0, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        stage.act(Gdx.graphics.getDeltaTime());
        stage.draw();
    }

    public void resize(int width, int height) {
        stage.getViewport().update(width, height, true);
    }
}
```

![offset problem](https://user-images.githubusercontent.com/3063858/44416111-58d4dc80-a572-11e8-862f-1e525d2ac00d.png)

The font can be downloaded from the creators website here:
http://www.dsg4.com/04/extra/bitmap/index.html (the very first)

([direct link to download](http://www.dsg4.com/04/extra/bitmap/stuff/04b_03.zip))

Maybe I'm completely wrong about this, but I think the reason you might not have seen the offset is because it's very small, which is why it is more obvious with this pixel font.

**Comment by mgsx-dev** [comment]
@CreamyCookie "Test:" VS "Text:" ... are you sure about your test case ? :-)

**Comment by CreamyCookie** [comment]
@mgsx-dev oops, thanks for making me aware of that. I'll update it right away. (Won't change though, since it's a monospace font.)

**Comment by NathanSweet** [comment]
@CreamyCookie This is what I see (I am running from the latest source in the master branch):
![](http://n4te.com/x/4712-deUQ.png)

**Comment by CreamyCookie** [comment]
Oh, wow. I guess it must have been fixed in master then. I'm on 1.9.8. (using lwjgl3) Should have tested on the master branch. Sorry for the inconvenience!
