### ISSUE TITLE
Troubles import a .tmx map in Android Studio

### ISSUE THREAD

**Issue by MayeuldP** [libgdx/libgdx#4801]
Good evening, 
I'm trying to import a map on Android Studio that I did on Tiled Map E. But when I'm trying to put it on my Android Project ('res' folder on a new folder call 'map') I got these errors (see stacktrace). I tried different format in map properties CSV, XML... But I always got theses issues. So if anyone succeed to import a map on android studio, I need help :/ 
```java
mapLoader = new TmxMapLoader();
        map = mapLoader.load("map-finale.tmx");
        MapProperties prop = map.getProperties();
        int mapWidth = prop.get("width", Integer.class);
        int mapHeight = prop.get("height", Integer.class);
```

This code seems works well tho...

#### Issue details
Import a .tmx map on Android Studio

#### Version of LibGDX and/or relevant dependencies
last one

#### Stacktrace
```java
Error:Error: Unsupported type 'tileset'
Error:Error: Unsupported type 'layer'
```

#### Please select the affected platforms
- [X] Android

**Comment by MayeuldP** [comment]
Alright, it seems that it was just a problem of location. I got another error now, and I think it's just a problem of path... I put my map.tmx in the folder `assets/maps`
But I have an error of Null object reference when I want to print the properties of the map. 
Just check the pic below : 

![map](https://user-images.githubusercontent.com/15033774/27655946-82207d08-5c47-11e7-8bf5-62a2a05306b7.PNG)

**Comment by intrigus** [comment]
This is an issue tracker. This doesn't seem to be a libgdx issue, but a problem with your program.
If you have questions please use the forums or irc.
If this is indeed a problem with libgdx, please provice a sscce.org

**Comment by MayeuldP** [comment]
> This is an issue tracker. This doesn't seem to be a libgdx issue, but a problem with your program.
Hm, it seems weird. Do you have any links about how to setup libGdx in an existing android Studio' project. I only found how to generate one, but I don't want to do that... I didn't found anything for exisiting project. 
Than'ks !

**Comment by MobiDevelop** [comment]
It looks like you are loading the map before libgdx is initialized (Gdx.files is null). Please use the forum or irc for questions.l and general help.
