### ISSUE TITLE
Full screen game window is offset or zoomed to wrong position when game is downloaded from Steam

### ISSUE THREAD

**Issue by simernes** [libgdx/libgdx#4802]
![fromsteam](https://user-images.githubusercontent.com/1278451/27697048-7e0aa7e6-5cf3-11e7-9c3f-058eadd446d9.png)

#### Issue details
I've gotten my game accepted on Steam, and everything was working fine except one annoying issue on Windows 10. 
After I've uploaded the game to Steam, and downloaded it through the client, when I set the game to full screen, the position of the content of the game window is offset so that you cannot see all of it (see screenshot). It works fine on Ubuntu, and Windows 7. Or rather, it is maybe zoomed in a little too much towards the top left of the screen.

I pack the game with packr and then upload it to Steam. Before I upload it, it works fine. The full screen behaves as expected. However, for some reason after it's downloaded from Steam and I play it, this problem happens. Perhaps it has something to do with the Steam overlay, but it doesn't happen on any other platform I've tried so I don't know what to do. The Steam support guys didn't have very much to say on the matter either. 

Anyone else who have run into this issue?

The way I'm setting fullscreen is:
`
if(!Gdx.graphics.isFullscreen()) {
                                            Graphics.DisplayMode displayMode = Gdx.graphics.getDisplayMode();
                                            Gdx.graphics.setFullscreenMode(displayMode);
                                        } else {
                                            Gdx.graphics.setWindowedMode(1280, 720);
                                        }
`

#### Reproduction steps/code
Implement usage of Gdx.graphics.setFullscreenMode(displayMode) and upload to Steam, then download through steam client and run.

#### Version of LibGDX and/or relevant dependencies
1.9.4

#### Stacktrace
NA

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Flame6332** [comment]
What difference does it make if it was downloaded off of steam?

**Comment by LiwaaK** [comment]
i believe its something in your code, using a camera will automatically resize everything

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info
