### ISSUE TITLE
my game is freezing with "intel_do_flush_locked failed: Input/output error"

### ISSUE THREAD

**Issue by Queatz** [libgdx/libgdx#4804]
Please ensure you have given all the following requested information in your report.

#### Issue details
At random times during my game, it completely freezes.  About 10 seconds later it exits and prints this message:

```
intel_do_flush_locked failed: Input/output error
AL lib: (EE) alc_cleanup: 1 device not closed
```

#### Reproduction steps/code
_Even if you think your issue is trivial to reproduce, please supply a [SSCCE](http://sscce.org/) that demonstrates your issue.  This saves time on our end, and makes it much more likely that your issue will be fixed.
You can find barebones templates [here](https://github.com/libgdx/libgdx/wiki/Getting-help)_

#### Version of LibGDX and/or relevant dependencies
1.9.6

#### Stacktrace
See above.

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ X ] Linux
- [ ] MacOS

**Comment by Queatz** [comment]
Seems to have something to do with a looping sound.

If I remove:

```java
Sound sound = Gdx.audio.newSound(Gdx.files.internal("noise.ogg"));
long id = sound();
sound.setLooping(id, true);
```

I no longer run into the error.  With it, I consistently do.

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
