### ISSUE TITLE
Project generator: Kotlin is automatically picked when selecting IntelliJ as the target

### ISSUE THREAD

**Issue by LunarWatcher** [libgdx/libgdx#4805]
Not sure if this is the place to add this issue, as it is related to the project generator.

I am not sure whether or not this is a bug or if it is intended, but when I pick IntelliJ under advanced settings, it automatically picks Kotlin as the main programming language (bottom option. If I then reopen the advanced settings, unselect it, save and reopen, it is there again.

**Basic reproduction**

* Set up project (additional libraries, project details, target platforms, etc)
* Press advanced settings
* Check `IDEA` option
* Click `save`
* Generate the project / reopen advanced settings

Depending on the last step, you will either see the kotlin plugin and dependencies added, or you will see the Kotlin option checked.

Just because I use IntelliJ doesn't necessarily mean I want to use Kotlin. If I want to use Kotlin I would manually check it. It being automatically checked, generating dependencies and additional runtime data uses the little data I have available in the APK (without expansion files, that is 50 MB) (APK = Android for those who don't know that).

The version of the project generator, not sure exactly which it is (don't see a number). I downloaded it today, so the newest as of June 30th, 2017

**Comment by Tom-Ski** [comment]
Thanks for the report, should be resolved now.
