### ISSUE TITLE
maven deployment

### ISSUE THREAD

**Issue by jjYBdx4IL** [libgdx/libgdx#4806]
Just read the two years old article about the maven deployment that is still not finished.

You don't need to rebuild stuff using maven just to deploy it to maven central. Actually, it would be better, in order to have identical binaries, to not do that. Just use the download-maven-plugin to get the already compiled artifacts (binaries, javadoc, sources), attach them to the project and deploy them.

**Comment by jjYBdx4IL** [comment]
Or just use this:

https://docs.gradle.org/3.3/userguide/publishing_maven.html

**Comment by jjYBdx4IL** [comment]
I also would not put native binaries in separate packages. If you follow the JNA conventions, you can use JNA's lib loader to extract the correct dlls at runtime. And if developers don't want a cross-platform executable with all platform dlls included, they can separate those dlls on their own.

**Comment by MobiDevelop** [comment]
To which article are you referring? In any case, this is an issue tracker, not a discussion board. Please use the forum or irc channel for discussion.
