### ISSUE TITLE
Make Skin class use file a FileHandleResolver for solving file references within the json file

### ISSUE THREAD

**Issue by fmmarzoa** [libgdx/libgdx#4807]
#### Issue details
libGDX provides a great way for the developers to implement their own file resolvers and loaders. Unfortunately, there are parts of the libGDX code itself that does not support these yet. The Skin class is one of those. Basically, you cannot use the Skin class along with JSON files based skins if you have defined a custom FileHandleResolver because the Skin class code won't rely on it. 

#### Reproduction steps/code
I think all the involved code is within this method of the Skin class:

`protected Json getJsonLoader (final FileHandle skinFile)`

There are several file resolutions there that can be modified to rely on the FileHandleResolver approach and thus be made compatible with custom resolvers, just to pick the first one:

```
FileHandle fontFile = skinFile.parent().child(path);
if (!fontFile.exists()) fontFile = Gdx.files.internal(path);
if (!fontFile.exists()) throw new SerializationException("Font file not found: " + fontFile); 

```

This should be better written as:

```
FileHandle fontFile = resolver(path);
if (!fontFile.exists()) throw new SerializationException("Font file not found: " + fontFile); 
```

This would require some additional changes in the Skin class to have such resolver available. At least a way to provide the the resolver. It could be as easy as add this parameter to some of its constructors, much as it is done in the AssetManager class, for example:

```
/** Creates a new AssetManager with all default loaders. */
	public AssetManager (FileHandleResolver resolver) {

/** Creates a new AssetManager with optionally all default loaders. If you don't add the default loaders then you do have to
	 * manually add the loaders you need, including any loaders they might depend on.
	 * @param defaultLoaders whether to add the default loaders */
	public AssetManager (FileHandleResolver resolver, boolean defaultLoaders) {

```

It should be a matter of extrapolating that approach to the Skin class itself.

#### Version of LibGDX and/or relevant dependencies
1.9.3 and probably every other version 

#### Please select the affected platforms
- [X] Android
- [X] iOS (robovm)
- [X] iOS (MOE)
- [X] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by raeleus** [comment]
I believe the referenced line is only a fallback for special, internally packed fonts like the default font. I don't think there is much demand for this feature. Just make sure the font is in the same path of the Skin and you're golden, no matter what FileHandleResolver you use.
