### ISSUE TITLE
VertexArray needlessly creates DirectFloatBufferU

### ISSUE THREAD

**Issue by Bytekeeper** [libgdx/libgdx#4808]
Please ensure you have given all the following requested information in your report.

#### Issue details
When using a SpriteBatch on Desktop:
In VertexArray.bind(shader, locations), it passes ```byteBuffer``` to ```shader.setVertexAttribute```, although it actually *has* a FloatBuffer.
The ```ShaderProgram``` now calls ```glVertexAttribPointer``` which in turn calls ```asFloatBuffer()```, because the buffer is not a ```GL_FLOAT```.

I guess just passing ```buffer``` instead of ```byteBuffer``` in ```com.badlogic.gdx.graphics.glutils.VertexArray#bind(com.badlogic.gdx.graphics.glutils.ShaderProgram, int[])``` should do the trick.

#### Reproduction steps/code
This is difficult to reproduce in that it requires a profiler (like jvisualvm) to be connected to observe.

#### Version of LibGDX and/or relevant dependencies
1.9.6

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by Tom-Ski** [comment]
Thanks for the issue, resolved in https://github.com/libgdx/libgdx/commit/b4251c6532c7b31fff2eacb74df125378c808342
