### ISSUE TITLE
ShapeRenderer prevents BitmapFont from drawing

### ISSUE THREAD

**Issue by CorkScrewer** [libgdx/libgdx#4809]
When I do, in my code `sr.rect(100, 100, 128, 96);`, and then I write `Fonts.calibri.draw(sb, "Text", 102, 102)`, the text doesn't draw! I made sure to set up my shape renderer properly with `sr.setProjectionMatrix(camera.combined)` and `sr.begin(ShapeType.Line)` AND, after I render everything, `sr.end`.

I know that it is the Shape Renderer that is doing this because when I remove the `sr.rect();` function, the text draws!

I'm VERY sorry if this is not properly organized but, I just need to know what I can do to fix this!

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
