### ISSUE TITLE
TexturePacker does not preserve transparent background of some PNGs

### ISSUE THREAD

**Issue by ttencate** [libgdx/libgdx#4814]
#### Issue details
I have a set of PNG files which only contain white and transparent pixels. My software seems to have decided to store them as 1-bit grayscale with 1-bit alpha. The problem is that the transparency is not preserved by TexturePacker.

Full disclosure about an affected file:

```
$ identify -verbose repro.png 
Image: repro.png
  Format: PNG (Portable Network Graphics)
  Mime type: image/png
  Class: DirectClass
  Geometry: 9x16+0+0
  Units: Undefined
  Type: Bilevel
  Base type: Grayscale
  Endianess: Undefined
  Colorspace: Gray
  Depth: 8/1-bit
  Channel depth:
    gray: 1-bit
    alpha: 1-bit
  Channel statistics:
    Pixels: 144
    Gray:
      min: 0 (0)
      max: 255 (1)
      mean: 69.0625 (0.270833)
      standard deviation: 113.715 (0.445941)
      kurtosis: -0.964827
      skewness: 1.02065
      entropy: 0.842658
    Alpha:
      min: 0 (0)
      max: 255 (1)
      mean: 69.0625 (0.270833)
      standard deviation: 113.715 (0.445941)
      kurtosis: -0.964827
      skewness: -1.02065
      entropy: 0.842658
  Alpha: graya(0,0)   #00000000
  Colors: 2
  Histogram:
       105: (  0,  0,  0,  0) #00000000 graya(0,0)
        39: (255,255,255,255) #FFFFFFFF graya(255,1)
  Rendering intent: Undefined
  Gamma: 0.45455
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Background color: graya(255,1)
  Border color: graya(223,1)
  Matte color: graya(189,1)
  Transparent color: graya(0,0)
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 9x16+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: Zip
  Orientation: Undefined
  Properties:
    date:create: 2017-07-07T17:27:58+02:00
    date:modify: 2017-07-07T17:27:14+02:00
    png:bKGD: chunk was found (see Background color, above)
    png:cHRM: chunk was found (see Chromaticity, above)
    png:gAMA: gamma=0.45455 (See Gamma, above)
    png:IHDR.bit-depth-orig: 1
    png:IHDR.bit_depth: 1
    png:IHDR.color-type-orig: 0
    png:IHDR.color_type: 0 (Grayscale)
    png:IHDR.interlace_method: 0 (Not interlaced)
    png:IHDR.width,height: 9, 16
    png:text: 2 tEXt/zTXt/iTXt chunks were found
    png:tIME: 2017-07-07T16:51:18Z
    png:tRNS: chunk was found
    signature: dfe92f9234920fe6539a71664d74b16b3c0bc713c6c367adec3c5376be409c5e
  Artifacts:
    filename: repro.png
    verbose: true
  Tainted: False
  Filesize: 283B
  Number pixels: 144
  User time: 0.000u
  Elapsed time: 0:01.000
  Version: ImageMagick 6.9.8-10 Q16 x86_64 2017-06-12 http://www.imagemagick.org
```

#### Reproduction steps/code
Attached is a small PNG file `repro.png` with some white and transparency (you don't see it here):

![repro](https://user-images.githubusercontent.com/90930/27966361-46e187f6-633f-11e7-99b7-e85950caa5b8.png)

Put it in an otherwise empty directory `repro` and run this from the nightlies (on Linux; Windows probably needs `;` instead of `:`):

    java -cp gdx.jar:extensions/gdx-tools/gdx-tools.jar com.badlogic.gdx.tools.texturepacker.TexturePacker path/to/repro

This creates `path/to/repro-packed/repro.png`. Open that file and see how the transparency has been replaced by a black background:

![pack](https://user-images.githubusercontent.com/90930/27966402-66972038-633f-11e7-8c06-416300225e2c.png)

#### Version of LibGDX and/or relevant dependencies
libgdx-nightly-20170706

#### Please select the affected platforms
TexturePacker running on Arch Linux.
```
$ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by ttencate** [comment]
Further debugging: it looks like TexturePacker uses Java's image I/O functions, not LibGDX's. And the `BufferedImage` has `.getType() == 12`, which is `BufferedImage.TYPE_BYTE_BINARY`. According to the docs, this means

> Represents an opaque byte-packed 1, 2, or 4 bit image. The image has an IndexColorModel without alpha.

This is true; when I run

```
        val img = ImageIO.read(Gdx.files.absolute("/tmp/repro/repro.png").file())
        println(img.type)
        println(img.colorModel)
        println((img.colorModel as java.awt.image.IndexColorModel).getRGB(0))
        println((img.colorModel as java.awt.image.IndexColorModel).getAlpha(0))
        println((img.colorModel as java.awt.image.IndexColorModel).getRGB(1))
        println((img.colorModel as java.awt.image.IndexColorModel).getAlpha(1))
```

I get:

```
12
IndexColorModel: #pixelBits = 1 numComponents = 3 color space = java.awt.color.ICC_ColorSpace@5bec9239 transparency = 1 transIndex   = -1 has alpha = false isAlphaPre = false
false
-16777216
255
-1
255
```

So pixel value 0 means RGB = 0xff000000 (weird! it should be only 3 bytes) and alpha = 255, so this is opaque black. Pixel value 1 is opaque white.

Could it be that `ImageIO` just ignores the alpha? [Yes, it seems so.](https://stackoverflow.com/questions/4647404/imageio-ignores-png-alpha-channel) And [this was already reported back in 2008](http://bugs.java.com/view_bug.do?bug_id=6703368). Boo.

(Possibly related: [`ImageIO` implicitly performs lossy colour space conversions](https://stackoverflow.com/questions/31312645/java-imageio-grayscale-png-issue). So maybe `ImageIO` is just not so awesome for TexturePacker.)

**Comment by NathanSweet** [comment]
libgdx's Pixmap uses stb_image, which pukes on some PNGs (I believe with certain metadata, some PNGs from pngcrush and other tools, etc). ImageIO works on most PNGs, even if it does apparently have some bugs. I suggest saving all PNG-24 sRGB, eg with Photoshop's `Save for Web`. That is the format of the packed page images anyway.

**Comment by ttencate** [comment]
Thanks for your reply! I guess we can't have it all.

The trouble is that I use [eowise/gradle-packer-plugin](https://github.com/eowise/gradle-packer-plugin), which runs the PNGs through ImageMagick before feeding them to TexturePacker. I'll see if I can get a workaround submitted there.
