### ISSUE TITLE
Set origin based position on Sprite

### ISSUE THREAD

**Issue by RubicCube** [libgdx/libgdx#4817]
#### Issue details
There are
setPosition(x,y) (leftBottom point) and
setCenter(x,y) (center of sprite)
methods in Sprite class.
But there is no "origin based position set method" in Sprite class.

#### Reproduction steps/code
I wrote a method for Sprite class like below, i always use this "position set method" instead of setPosition() or setCenter(), because its very usefull when i want set origin based position point.

Can you add this method to Sprite class?

public void setOriginBasedPosition(float x, float y) {
    setPosition(x - originX, y - originX);
}

#### Version of LibGDX and/or relevant dependencies
1.9.6

#### Please select the affected platforms
- [ X] Android
- [X ] Windows

**Comment by oseph** [comment]
I've made a pull request with this method added to the Sprite class.

(gulp, this is my first contribution ... am I doing it right?)
