### ISSUE TITLE
LibGDX black screen on rooted Android 5+ devices

### ISSUE THREAD

**Issue by ErikTheV** [libgdx/libgdx#4819]
When running even the basic LibGDX setup example on a rooted Android 5 device, i only get black screens once SuperSU has asked for (and given) permission to access.

This concerns all versions of LibGDX. It's easy to reproduce. Just Setup a default LibGDX installation and add some code for hiding the Android systembar for instance:

`Process proc = Runtime.getRuntime().exec(new String[]{"su","-c","service call activity 79 s16 com.android.systemui"});
proc.waitFor();`

Debugging the app shows it's rendering. I noticed that touches also aren't registered in LibGDX when running black.

This all does work on Android 4 and lower

Please help!

**Comment by MobiDevelop** [comment]
It's very likely nobody is going to root their phone to debug your issue. When you start modifying your device to operate outside of it's intended use, you take a certain level of responsibility for the fact things may not work as expected. This appears to be the case here.

If you have questions or need general help, please use the forum or irc channel to discuss.
