### ISSUE TITLE
Cannot render converted obj->g3db file

### ISSUE THREAD

**Issue by odin-** [libgdx/libgdx#4822]
* Running on Android
* libgdx version 1.9.6
* FBX to G3Dx converter, version 0.01.0071 x32 , FBXSDK 2015.01

I do not know if this a libgdx or fbx-conv problem.

I have a obj, mtl and png file. Converted it. But when using the result g3db it does not display correctly in libgdx. However, if I use the original obj it works just fine.

> fbx-conv-win32.exe -v z:\src\main\assets\3dcube2.obj
INFO:     FBX to G3Dx converter, version 0.01.0071 x32 , FBXSDK 2015.01
STATUS:   Loading source file
PROGRESS: Import FBX 100.00%
WARNING:  [3dcube2_root] Node uses RrSs mode, transformation might be incorrect
WARNING:  [default] Node uses RrSs mode, transformation might be incorrect
VERBOSE:  [shape(default)] polygons: 1378 (4134 indices), control points: 691
STATUS:   Converting source file
STATUS:   Closing source file
VERBOSE:  Listing model information:
VERBOSE:  ID        :
VERBOSE:  Version   : Hi=0, Lo=1
VERBOSE:  Meshes    : 1 (820 vertices, 2 parts, 4134 indices)
VERBOSE:  Nodes     : 1 root, 2 total, 2 parts
VERBOSE:  Materials : 2 (1 textures)
STATUS:   Exporting to G3DB file: z:\betapet_mobile_android\lib_com_betapet_mobile\src\main\assets\3dcube2.g3db
STATUS:   Closing exported file

I am using AssetManager to load.

Camera:

```
        cam = new PerspectiveCamera(67, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
        cam.position.set(10f, 10f, 50f);
        cam.lookAt(0,0,0);
        cam.near = 1f;
        cam.far = 300f;
        cam.update();
```

ModelBatch renderer.

I cannot see any error log output.

Attaching files:
[assets.zip](https://github.com/libgdx/libgdx/files/1151349/assets.zip)

![capture](https://user-images.githubusercontent.com/7396319/28251220-e68316e0-6a78-11e7-861b-4229f3cdbebe.PNG)

**Comment by piotr-j** [comment]
Try g3dj and see if it looks reasonable inside.

**Comment by odin-** [comment]
It did look reasonable. However I solved this in a different way so we can put this issue on ice until further notice.

**Comment by Jonasdoubleyou** [comment]
@odin- I'm currently facing the same problem. How do you solved that in "a different way" ?
