### ISSUE TITLE
JVM Crash when calling dispose() on an OrthogonalTiledMapRenderer

### ISSUE THREAD

**Issue by phunni** [libgdx/libgdx#4826]
Please ensure you have given all the following requested information in your report.

#### Issue details
When I try and close my game using the following code:

` @Override
        public boolean keyDown(int keycode) {
            if (keycode == Input.Keys.ESCAPE) {
                GameScreen.this.dispose();
                Gdx.app.exit();
            }
return false;
}`

I get the following error:

`#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fdffccb434d, pid=1606, tid=0x00007fdfbf6fd700
#
# JRE version: OpenJDK Runtime Environment (8.0_112-b06) (build 1.8.0_112-release-b06)
# Java VM: OpenJDK 64-Bit Server VM (25.112-b06 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x7c34d]
Process finished with exit code 134 (interrupted by signal 6: SIGABRT)`

This does not happen if I simply close the game window and, from commenting out lines of code in the various dispose() methods, appears to be a result of a call to dispose() on OrthogonalTiledMapRenderer.

I have tried multiple JVMs including the one built in to Android Studio (openjdk 8), Openjdk8 - the latest version and the Oracle 8 jdk.  It appears on all of them - suggesting that it isn't a jvm bug.

#### Reproduction steps/code
It appears to happen if you call dispose() on an OrthogonalTiledMapRenderer - although it presumably requires a similar system to mine.

#### Version of LibGDX and/or relevant dependencies
1.9.6

#### Stacktrace
Provided above.  I tried to get it to create an error log, but failed.

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [X] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
You are probably disposing twice as Gdx.app.exit() will close the app and propagate exit calls to the application listeners.  If you are still having the issue, please reopen with steps to reproduce and full compilable example code as requested by the issue template.

**Comment by phunni** [comment]
I'm confident I'm not calling dispose() twice as I have log messages in all the relevant dispose methods and they only get logged when I call them explicitly as outlined above.

That said, I don't have any more details on how to reproduce it than I've given - I can't even reproduce it in another project, so I suppose I'll have to leave this closed and figure something else out.

**Comment by intrigus** [comment]
Full jvm crash log would also help.

**Comment by phunni** [comment]
and I've spent ages trying to generate one, but it never seems to work.  I've added 

`-XX:ErrorFile=/home/paul/hs_err_pid<pid>.log`

to the org.gradle.jvmargs in gradle.properties, but that doesn't appear to make any difference...

**Comment by phunni** [comment]
I have googled the last line of the error message:

> Process finished with exit code 134 (interrupted by signal 6: SIGABRT)`

and was able to find this: [https://groups.google.com/d/msg/comp.lang.java.machine/OibTSkLJ-bY/7Gi-nsMgyZwJ](url)

which says:

> Signal number 6 is probably SIGABRT, which most often means
> that some piece of code in the process deliberately called the libc abort()
> function, e.g. many implementations of the assert() macro.
> 
> Does your application contain any native code (accessed through JNI) that
> might use assert(), abort() or SIGABRT?  If not, then perhaps you're 
> tickling an assertion failure (i.e. bug) somewhere in the JDK's native code.

I'm not calling any native code, but, obviously, LWJGL does - so, perhaps, it's a bug there.

**Comment by mgsx-dev** [comment]
Hi, yes LibGDX is made of native and java code so it's usual to have that kind of error when something wrong happens in native code.

Anyway, your problem seams to be related to a "dispose twice". When you call dispose on the renderer, it just dispose its own batch. Maybe this batch is already disposed. Do you use it's own batch somewhere else in your code ? do you override/extends the renderer in some way ?

To not flood issue tracker, let's continue this subject on libGDX forum since it seams to be a bug in your code.
