### ISSUE TITLE
Desktop configuration dosen't work in IDEA

### ISSUE THREAD

**Issue by erikmartinessanches** [libgdx/libgdx#4827]
#### Issue details
When running 'Desktop' run configuration in IntelliJ IDEA the error below appears.
```
Error:com.android.tools.idea.gradle.util.Projects.lastGradleSyncFailed(Lcom/intellij/openapi/project/Project;)Z
```
#### Reproduction steps/code
Following the [setup instructions](https://github.com/libgdx/libgdx/wiki/Setting-up-your-Development-Environment-(Eclipse,-Intellij-IDEA,-NetBeans)#setting-up-intellij-idea), I've installed

- Android SDK API 26 Platform

With sdkmanager I've installed:

![image](https://user-images.githubusercontent.com/4912935/28480728-4da5daaa-6e62-11e7-91b1-bd1b8a3b6840.png)

Are Android emulator and Android NDK necessary? 

Enabled the org.robovm.idea-2.3.1-plugin-dist.jar plugin by install form disk option.

Following the instructions for [creating a libgdx project](https://github.com/libgdx/libgdx/wiki/Project-Setup-Gradle) with the following settings as in the article:
![image](https://user-images.githubusercontent.com/4912935/28479624-8a99c296-6e5d-11e7-8912-6ca9b605f4fa.png)

Then going to instructions about [Gradle and IntelliJ IDEA](https://github.com/libgdx/libgdx/wiki/Gradle-and-Intellij-IDEA).

I imported the project and set up a "Desktop" configuration as described (working directory pointing to /Users/erik/Documents/Dev/repos/mygame/android/assets) and when running it, the error mentioned above appears.

My project can be seen [here](https://github.com/erikmartinessanches/libgdxExample). (I've tried to include the IntelliJ project files...)

#### Version of LibGDX and/or relevant dependencies

libgdx: 1.9.6 (in build.gradle)
JDK: 1.8.0_141
org.robovm.idea-2.3.1-plugin-dist.jar enabled in Preferences -> Plugins -> Install plugin from disk...
IntelliJ IDEA IntelliJ IDEA 2017.2
Build #IU-172.3317.76, built on July 15, 2017
JRE: 1.8.0_152-release-915-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

![image](https://user-images.githubusercontent.com/4912935/28459164-af624e3c-6e0c-11e7-8921-e8f2cd760c37.png)
![image](https://user-images.githubusercontent.com/4912935/28459194-cd88f58c-6e0c-11e7-996e-ecb0ea629e6a.png)

#### Stacktrace
The error message is:
```
Error:com.android.tools.idea.gradle.util.Projects.lastGradleSyncFailed(Lcom/intellij/openapi/project/Project;)Z
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS

**Comment by Tom-Ski** [comment]
Uninstall your robovm plugin, or upgrade it to the latest snapshot

**Comment by erikmartinessanches** [comment]
It worked, thanks. Btw is the Android NDK necessary for building for Android?

**Comment by Tom-Ski** [comment]
Nope
