### ISSUE TITLE
visibility properties of tmx map object layer is not populated on load

### ISSUE THREAD

**Issue by alwex** [libgdx/libgdx#4828]
#### Issue details
I use Tiled to create my levels with multiple tile layer and object layer.
Tiled allow to disable visibility on a layer no matter the type (tile, object, image)

Visibility attribute is correctly setted to false or true for tile layers
Visibility attribute is not loaded and is always true for object layers

#### Reproduction steps/code
* create a new map with 2 object layers
* set the first object layer visibility to true
* set the second object layer visibility to false
* load the map using `TmxMapLoader`
* loop through the layers and dump `isVisible()`

```java
for (MapLayer tileLayer : map.getLayers().getByType(MapLayer.class)) {
    Gdx.app.log("DEBUG", tileLayer.isVisible());
}
```

#### Version of LibGDX and/or relevant dependencies
LibGDX 1.9.6
Tiled 1.0.2

#### Proposition
On `BaseTmxMapLoader`
```java
    @Override
    protected void loadObjectGroup (TiledMap map, XmlReader.Element element) {
        if (element.getName().equals("objectgroup")) {
            String name = element.getAttribute("name", null);
            MapLayer layer = new MapLayer();
            // load basic layer info added here
            // this will populate the name, opacity and visibility
            loadBasicLayerInfo(layer, element);
            layer.setName(name);
            XmlReader.Element properties = element.getChildByName("properties");
            if (properties != null) {
                loadProperties(layer.getProperties(), properties);
            }

            for (XmlReader.Element objectElement : element.getChildrenByName("object")) {
                loadObject(map, layer, objectElement);
            }

            map.getLayers().add(layer);
        }
    }
```

#### Please select the affected platforms
- [ x] Android
- [ x] iOS (robovm)
- [ x] iOS (MOE)
- [ x] HTML/GWT
- [x ] Windows
- [ x] Linux
- [ x] MacOS

**Comment by Tom-Ski** [comment]
Resolved by https://github.com/libgdx/libgdx/pull/4861
