### ISSUE TITLE
Website Board administrator issue

### ISSUE THREAD

**Issue by LiwaaK** [libgdx/libgdx#4829]
No verification email is sent, emails sent to the board administrator give a microsoft send error that the email is not found or something like that, therefore, i cant post in forums

**Comment by Tom-Ski** [comment]
I've tested this on a new account and the email verification is sent.  I've also resent your activation, have you checked spam filters?

**Comment by LiwaaK** [comment]
I checked my spam filters, and my inbox, nothing was recieved

**Comment by Tom-Ski** [comment]
I manually activated your account.

**Comment by LiwaaK** [comment]
Thank you :)
