### ISSUE TITLE
XML entities not converted for attribute value

### ISSUE THREAD

**Issue by mgsx-dev** [libgdx/libgdx#4831]
Please ensure you have given all the following requested information in your report.

#### Issue details

XML entities like &apos; are not converted for attribute values. It is for text nodes but not attribute values.

XML standard allow it : https://www.w3.org/TR/WD-xml-lang-970630#sec3.3.3

#### Reproduction steps/code

just run this code :

`new XmlReader().parse("<a info=\"it doesn&apos;t work...\">it doesn&apos;t bug :-)</a>")`

result :
```
<a info="it doesn&apos;t work...">
	it doesn't bug :-)
</a>
```

#### Version of LibGDX and/or relevant dependencies

1.9.6 and master I guess since Ragel code didn't change 

#### Stacktrace

N/A

#### Please select the affected platforms
- [x] Android
- [x] iOS (robovm)
- [x] iOS (MOE)
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by mgsx-dev** [comment]
I don't know how to generate this file. I think we need documentation about how to deal with Ragel generated code (how to use it, which version to use, etc).

**Comment by NathanSweet** [comment]
After editing the `.rl` file, you just run Ragel using the parameters at the top of the file, eg:
https://github.com/libgdx/libgdx/blob/master/gdx/res/com/badlogic/gdx/utils/XmlReader.rl#L2
The latest version of Ragel should be fine.

**Comment by tommyettinger** [comment]
Just want to comment here that the XmlReader.java file has been manually modified now (adding `@Null` annotations), so just running Ragel won't be sufficient. As I commented in a duplicate issue #6462 , you can get a working binary of Ragel from https://github.com/sci-bots/ragel/releases/tag/ragel-6.10 ; the official site only provides source. I've looked into modifying the .rl file, but I really don't have much idea what's going on.
