### ISSUE TITLE
Missing Javadoc for Netbeans libGDX project

### ISSUE THREAD

**Issue by TheGreatMarkus** [libgdx/libgdx#4835]
I'm using the Netbeans IDE and added the Gradle Support extension for Netbeans.
I made a project using the gdx-setup.jar file you download here : https://libgdx.badlogicgames.com/download.html
Afterward, I try running the project on the desktop sub-project and everything works fine. the default red window with the badLogicGame logo appears.

However, my problem is that there seems to be no Javadoc or source files attached to the gdx-1.9.6.jar or any other extensions I add with the libGDX project generator. I can't consult the Javadoc in my IDE and it give the following message : "Javadoc not found. Either Javadoc documentation for this item does not exist or there is no attached Javadoc to the JAR file containing this item: C:\Users\MyUserName\.gradle\caches\modules-2\files-2.1\com.badlogicgames.gdx\gdx\1.9.6\47d1e9b890e364ec28f128e9bb3b9a12a94c164\gdx-1.9.6.jar"

This problem has been driving me nuts and I can't find out why this is happening. I know I can consult your Javadoc online but I really want to know why this doesn't seem to work for me. Where can I download the javadoc so i can attach it to the project?

Versions : 
NetBeans IDE 8.2 (Build 201609300101)
Gradle Support 1.4.2
libGDX 1.9.6

Platform : 
Windows 10

**Comment by Tom-Ski** [comment]
The source files and javadoc jars are published to maven central and the snapshot repositories. They have the javadoc and sources classifiers. See https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22gdx%22

**Comment by TheGreatMarkus** [comment]
Hm that seems to do it. I tried it before I think (or maybe not I can't even remember. I was trying a bunch of stuff at once). It still sucks that it didn't do it automatically (and that I don't know why) but at least I have a solution now. 

Thanks Tom.

**Comment by Tom-Ski** [comment]
Great! Yeah that is annoying, if you come across a way to make it do it automatically please share it with us. Closing this out.
