### ISSUE TITLE
Someone want to try and Push this and test it?

### ISSUE THREAD

**Issue by SuckyNoob** [libgdx/libgdx#4840]
Sorry I am posting this here instead of the forums, I would post it there but I've registered 2 e-mail accounts on the Libgdx Forums and for some reason I haven't got an activation email all day, in either of them.

 I haven't learned to use Github yet and do pull requests, and I haven't learned how to edit the source code AND recompile it and all that yet, new to IntelliJ, Java and libgdx.

Anyways to the task at hand.

Alright so I tried to add to the BaseTmxLoader.java and the TiledMapTileLayer.java in order to see if I can get the Layer offsets to render.

However, I haven't figured out how to get access to the source code properly, build it and send it through Github...

I have no idea how to use Github yet, with the pull requests and all that, but should be learning soon. Got a lot on my plate at the moment.
And still learning to use IntelliJ IDEA, Libgdx, Gradle etc. etc. on top of all that.

Anywhere here are the two files I changed.

**For the first:
TiledMapTileLayer.java

I added Lines # 30 and 31 private Int's for offsetx and y.
- added Lines # 56 - 63 getter methods for TileLayer offsets.
- added to the Constructor on line 73 in it's arguments, added the offsetx and y.
- added Lines # 79 and 80.**

[TiledMapTileLayer.zip](https://github.com/libgdx/libgdx/files/1185452/TiledMapTileLayer.zip)

**For the second:

BaseTmxMapLoader.java

I added Lines # 80 and 81 inside the loadTileLayer method.**

[BaseTmxMapLoader.zip](https://github.com/libgdx/libgdx/files/1185453/BaseTmxMapLoader.zip)

Now I'm not sure but perhaps the TmxMapLoader.java also needs these fields added? Or perhaps also to the MapLayer.java class as well.

I'm not sure because at the moment I can't test it out I haven't learned to build the source code yet.

So if anyone wants to try and add this, and perhaps the same fields to the TmxMapLoader.java and MapLayer.java if they require it also, and knows how to do those pull requests and such. That would be awesome. Cause if it works I'd like to have it right inside Libgdx so I we can all benefit from TILED maps Layer Offsets :D

I also couldn't find exactly where it takes in all the render arguments unless I already covered that with what I added? But if someone can point to where that's happening I will try to add the offsets to the render code as well. And post the files again, cause I won't be figuring out Github this week I know that for sure.

**Comment by Tom-Ski** [comment]
This is better suited for the irc or forums. Double check your spam filters, if its still not there you can give me your username and I can manually activate it.

**Comment by SuckyNoob** [comment]
Alright I just triedd a different email it finally worked. I will post in the forums under Contributions. Or will check the IRC, sorry.
