### ISSUE TITLE
Cannot restart the game

### ISSUE THREAD

**Issue by dzikoysk** [libgdx/libgdx#4841]
#### Issue details
I have the same problem that is described there http://forum.lwjgl.org/index.php?topic=6483.0
It must to be a bug in libgdx because jMonkeyEngine works fine

#### Reproduction steps/code
Just open and close the game three times (in the same process)

#### Version of LibGDX and/or relevant dependencies
```xml
<dependency>
    <groupId>com.badlogicgames.gdx</groupId>
    <artifactId>gdx</artifactId>
    <version>1.9.6</version>
</dependency>
<dependency>
    <groupId>com.badlogicgames.gdx</groupId>
    <artifactId>gdx-backend-lwjgl</artifactId>
    <version>1.9.6</version>
</dependency>
<dependency>
    <groupId>com.badlogicgames.gdx</groupId>
    <artifactId>gdx-platform</artifactId>
    <version>1.9.6</version>
    <classifier>natives-desktop</classifier>
</dependency>
```

#### Stacktrace
```java
Exception in thread "LWJGL Application" java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glViewport(GL11.java:3261)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glViewport(LwjglGL20.java:839)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setWindowedMode(LwjglGraphics.java:492)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:166)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:144)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by piotr-j** [comment]
Im sure runnable example would help move things along.

**Comment by JuKu** [comment]
@dzikoysk What do you mean with "Just open and close the game three times (in the same process)"?
Open and close the full java application or only libGDX application on same process?

**Comment by dzikoysk** [comment]
I meant libGDX application in the same process. What's funny is, app throws that exception after the third restart

**Comment by JuKu** [comment]
@dzikoysk How do you close your application?

**Comment by dzikoysk** [comment]
I'm disposing ApplicationAdapter manually/LwjglAWTCanvas calls that when I dispose a frame

**Comment by shatterblast** [comment]
I'm thinking this issue is no longer relevant?

**Comment by dzikoysk** [comment]
I didn't try since then, if it's required I may try to check it with a new version

**Comment by shatterblast** [comment]
You have to manually enable LWJGL 3 for Desktop and maybe GWT / HTML.  Builds for Mobile devices, like iOS and Android, automatically use LWJGL 2 with no choice offered, but updates meant for LWJGL 3 also go into LWJGL 2 for Android at least.

**Comment by MobiDevelop** [comment]
LWJGL (whether 2 or 3) is only used on desktop. It has nothing to do with either GWT or mobile targets.

**Comment by shatterblast** [comment]
@MobiDevelop You know the entirety of LibGDX, even RoboVM, is based off of LWJGL's integration for OpenGL, right?  You can go look at RoboVM's source code.  You should know this.

**Comment by Tom-Ski** [comment]
What? Please stop spreading misinformation on this tracker or we will have to remove your access. Other platforms' gl implementation has nothing to do with lwjgl 2 or 3, as @MobiDevelop said.

**Comment by Tom-Ski** [comment]
@shatterblast Please also stop manipulating the wiki with your opinions and misinformation. This is your last warning as you have already been banned here once and if it continues we will have to remove you from contributing.

**Comment by noblemaster** [comment]
I believe this issue is related to graphics drivers/LWJGL2 rather than libGDX itself. This is nothing we can fix in libGDX as the error is thrown by LWJGL. 

I'll close the issue. I think (a) updating drivers or (b) using LWJGL3 might fix the problem.
