### ISSUE TITLE
some animation frames lost

### ISSUE THREAD

**Issue by hucaihua** [libgdx/libgdx#4843]
I only play the animation once , some frames lost  when start a animation like this . 

`animationController.setAnimation(
                modelConfig.tag,
                calcTime(action.begin),
                calcTime(action.end - action.begin),
                1,
                speed,
                animationListener);`

I trigger the animation like this:
`animationController.update(Gdx.graphics.getDeltaTime());`

**Comment by Velocity-** [comment]
Could it be that the deltatime is big enough to cover two frames, resulting in one being skipped? If the animation has very short frames (millisecond-length) then that could be a cause. Can you show what your animation definition looks like?

**Comment by hucaihua** [comment]
I have fix the problem . Thanks all the same.

The animations in the g3db file is placed in only one tag Take 001 . The begin and end tag in the following json means the start and the end of a animation. So there are six animations.

`{
		"name": "idle",
		"begin": 0,
		"end": 40,
		"sound":""
		},
		{
			"name": "walk",
			"begin": 43,
			"end": 91,
			"sound":""
		},
		{
			"name": "jump",
			"begin": 94,
			"end": 125,
			"sound":"models/pi.mp3"
		},
		{
			"name": "attack01",
			"begin": 128,
			"end": 155,
			"sound":"models/pi.mp3"
		},
		{
			"name": "attack02",
			"begin": 158,
			"end": 200,
			"sound":"models/pi.mp3"
		},
		{
			"name": "dead",
			"begin": 203,
			"end": 250,
			"sound":"models/pi.mp3"
		}`

But in the code of AnimationController , current.animation and the anim.animation is the same one. So It will play from the time of the last animation. I just change the allowSameAnimation to true to fix it.
`protected AnimationDesc setAnimation (final AnimationDesc anim) {
		if (current == null)
			current = anim;
		else {
			if (!allowSameAnimation && anim != null && current.animation == anim.animation)
				anim.time = current.time;
			else
				removeAnimation(current.animation);
			animationPool.free(current);
			current = anim;
		}
		justChangedAnimation = true;
		return anim;
	}`
