### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by syedfakher27** [libgdx/libgdx#4846]
When I generate desktop project it works fine but when i generate android project it gives me this error
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\android_studio_project\test\build.gradle' line: 53

* What went wrong:
A problem occurred evaluating root project 'test'.
> Failed to apply plugin [id 'android']
   > Could not create an instance of type com.android.build.gradle.AppExtension_Decorated.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

I can't understand what this problem is caused by?either it has some problem with my gradle version or some file is missing in my PC

**Comment by Tom-Ski** [comment]
You are running with the wrapper? Or you get this error in the setup tool?

**Comment by syedfakher27** [comment]
@Tom-Ski I didn't get you. this error displayed when i click generate button on libgdx setup

**Comment by Tom-Ski** [comment]
With what settings?

**Comment by syedfakher27** [comment]
I kept project name,package and game class to the default and provided correct path for android sdk and check only android platform without making any changes to advance option

**Comment by MrStahlfelge** [comment]
Closed, there are no problems with freshly generated projects at the moment.
