### ISSUE TITLE
Wrong parsed ID in .tmx maps

### ISSUE THREAD

**Issue by Nomeyho** [libgdx/libgdx#4856]
Hi!

#### Issue details
The tile ID set by the [Tiled map editor](http://www.mapeditor.org/) does not correspond to the tile ID obtained with Libgdx. More precisely, they are mismatched by one. For instance, the tile with id 221 in Tiled becomes 222 in Libgdx.
```
 <tile id="221">
  <image width="128" height="128" source="tiles/ground.png"/>
 </tile>
```

#### Reproduction steps/code
Create a `test.tmx` map with a single tile (pay attention to its ID) and iterate over the tiles with the following code:
```
// Load the map
TiledMap map = new TmxMapLoader().load("test.tmx"); 
// Get the map size
int mapWidth = (Integer) this.map.getProperties().get("width");
int mapHeight = (Integer) this.map.getProperties().get("height");
// Iterate
for(int i=0; i<mapWidth; ++i) {
    for (int j = 0; j < mapHeight; ++j) {
        cell = layer.getCell(i, j);
        if (cell == null) continue;
        System.out.println(cell.getTile().getId());
    }
}
```
You should get a a single output, whose value is the ID incremented by 1.

#### Version of LibGDX
Libgdx 1.9.6
Tiled 1.0.2

**Comment by Tom-Ski** [comment]
Your tileset probably has firstgid=1, which means that tileset is starting at 1 for that particular map. 

In Tiled, the tiles show their local tile ID, but Maps can consist of many tilesets (if you check in Tiled, they will all show their local ids, which would clash if used in one map), so there needs to be some global id system, which is what firstgid is for.

**Comment by wangdong20** [comment]
I got the same issue. Thx for this thread saving my life.
