### ISSUE TITLE
Skin#getJsonLoader Support BitmapFont from FreeTypeFontGenerator 

### ISSUE THREAD

**Issue by JasonMacKeigan** [libgdx/libgdx#4857]
#### Issue details
It is not possible to load a BitmapFont from a TrueTypeFontGenerator via the Skin#getJsonLoader when loading a Skin from an atlas and JSON file. It would be beneficial to add a flag to the Skin JSON file that determines whether or not the BitmapFont should be loaded via a FreeTypeFontGenerator or not, by default, false. 

This would allow for additional parameters to be passed to the generator, such as;
` Boolean freeTypeFont = json.readValue("freeType", Boolean.class, false, jsonData);
   Color shadow = json.readValue("shadow", Color.class, DEFAULT_COLOR, jsonData);
`

I would really enjoy it if this was implemented. 

#### Reproduction steps/code
NONE
#### Version of LibGDX and/or relevant dependencies
ALL
#### Stacktrace
NONE
#### Please select the affected platforms
- [x] Android
- [x] iOS (robovm)
- [x] iOS (MOE)
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by wpapsco** [comment]
https://github.com/libgdx/libgdx/wiki/Skin#bitmapfont

This isn't what you're looking for, right?

Can you clarify a little further if not?

**Comment by NathanSweet** [comment]
FWIW, the simplest workaround is to add your font(s) to the Skin before loading the JSON.
```
Skin skin = new Skin();
BitmapFont font = ...
skin.add("font", font);
skin.load(Gdx.files.internal("skin.json"));
```

**Comment by JasonMacKeigan** [comment]
@NathanSweet 
Yeah that is a fine workaround, but i'd preferably rather store the information in the JSON file appose to some class.

**Comment by MrStahlfelge** [comment]
@raeleus this is for you. I think the needed feature is covered by SkinComposer?

**Comment by raeleus** [comment]
Yes, I have a technique for this. Please see this page: https://github.com/raeleus/skin-composer/wiki/Creating-FreeType-Fonts#using-a-custom-serializer and this class: https://github.com/raeleus/stripe/blob/master/stripe/src/com/ray3k/stripe/FreeTypeSkin.java

I honestly don't think this should be added directly to GDX's default Skin Loader, but that is just my opinion. It assumes too many fields and makes for a messy JSON file if you hand write it. I believe most people will want to use Nate's technique anyway. Works fine for my Skin Composer users though. What do you guys think? @MrStahlfelge, @JasonMacKeigan @NathanSweet

**Comment by crykn** [comment]
In my projects I started using [freetype-skin](https://github.com/acanthite/freetype-skin), which is very similar to your solution @raeleus iirc. It makes asset loading easier, as I don't have to load the font files manually, and doesn't look that bad:
```
BitmapFont: {
		ui-element-18: {
			file: ../fonts/arial/Arial-Regular.ttf,
			size: 18
		},
}
```

If you are against this change, I have no problem with that, but I think we should give it a second thought.

**Comment by NathanSweet** [comment]
FWIW, I now prefer to do most of my skin configuration in code rather than JSON.

Maybe it would be sufficient to add a protected method that handles creating the fonts. It could be passed the JsonValue, so you can use whatever you like to configure your font generation. Though this is would be the same as @raeleus's solution so maybe not worth the trouble. There are many ways to generate a font, so it being app code seems fine.

**Comment by MrStahlfelge** [comment]
> What do you guys think?

I think we should add the repos linked by you and crykn to the wiki article about Skins and close this issue without a change.

**Comment by NathanSweet** [comment]
Sounds OK to me.

**Comment by crykn** [comment]
+1. Closing this.

**Comment by MrStahlfelge** [comment]
And the wiki article?

**Comment by crykn** [comment]
Working on it.
