### ISSUE TITLE
Texture packer creates brighter files

### ISSUE THREAD

**Issue by Abwuds** [libgdx/libgdx#4858]
#### Issue details
Textures are brighter when packed with the texture packer.

#### Reproduction steps/code
- Run the MyPacker [example](https://github.com/libgdx/libgdx/wiki/Texture-packer#running-texturepacker) on a png file. With the default configuration of the packer.
- The file created contains a brighter version of the original one.

#### Version of LibGDX and/or relevant dependencies
Gdx 1.9.3

#### The affected platforms
- On MacOS

**Comment by Scellow** [comment]
Have you tested with latest version?

https://libgdx.badlogicgames.com/versions.html

**Comment by Abwuds** [comment]
Yes, I just tried with the 1.9.6 and the result is the error shows up again

**Comment by piotr-j** [comment]
Ive made a simple test for this https://github.com/piotr-j/libgdxplayground/blob/master/core/src/io/piotrjastrzebski/playground/packs/PackColorTest.java
With this image https://github.com/piotr-j/libgdxplayground/blob/master/android/assets/pack_in/colors.png

Packed and source images are identical on windows and mac as far as i can tell.

Perhaps you can make a sample that shows the issue clearly.

**Comment by hiddicop** [comment]
Just had the same issue myself and discovered a solution. My image was encoded as a grayscale mode. Changing it to RGB-mode solved the problem.

**Comment by kolen** [comment]
Seems that it's problem with `AWT`'s `getScaledImage`

```java
package com.test.scalingtest;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class ScalingTest {
    public static void main(String[] args) {
        try {
            BufferedImage img = ImageIO.read(new File("grayscale.png"));
            Image image = img.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
            BufferedImage buffered = new BufferedImage(100, 100, BufferedImage.TYPE_BYTE_GRAY);
            buffered.getGraphics().drawImage(image, 0, 0, null);
            ImageIO.write(buffered, "png", new File("grayscale-out.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```

![image](https://user-images.githubusercontent.com/24191/29931112-f5056eec-8e78-11e7-87c1-d1effc0b2308.png)

[Discussion on Stackoverflow](https://stackoverflow.com/a/20084061/123642)

**Comment by Tom-Ski** [comment]
Please reopen if you can supply reproducible sample as the issue template requests.
