### ISSUE TITLE
Wrong Y coordinate in EllipseMapObject from tiled map

### ISSUE THREAD

**Issue by Shibalicious** [libgdx/libgdx#4860]
Please ensure you have given all the following requested information in your report.

#### Issue details
EllipseMapObject objects have wrong Y coordinates.

I created a map using Tiled. After loading map objects from .tmx file, casting them to EllipseMapObject and retrieving the x, y, width, height, the Y coordinate appears to be wrong whereas x, width and height variables are all correct. The .tmx file has the correct Y coordinate.

Example:

_In .tmx file:_

object id="3" name="obstacle" x="-63" y="-63" width="64" height="63.3333"

_In-game console:_

x = -63;
y = 383.6667;
width = 64;
height = 63.3333

#### Reproduction steps/code

**1.** Create an elliptical object in a map in Tiled.
**2.** Load the map into your LibGDX project.
**3.** Get elliptical object from the object layer.
**4.** Get Ellipse from the elliptical object and check its Y coordinate.

#### Version of LibGDX and/or relevant dependencies
Libgdx 1.9.4, 19.6
Tiled 1.0.2

#### Please select the affected platforms
- [x ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
Tiled is y down, by default the loaders flip objects into y up space.  This is probably what you are seeing. You can set flipY to false in the loaders if you don't want this behaviour. Please reopen supplying self contained executable example and the provide the map if you think there is still an issue.

**Comment by Shibalicious** [comment]
That was exactly the case, thank you very much!
