### ISSUE TITLE
Gdx.input.getDeltaX() and getDeltaY() not accurate

### ISSUE THREAD

**Issue by strongrex2001** [libgdx/libgdx#4863]
#### Issue details
I use the code below to update my player object’s position on the Stage.
The code is run in Screen.render, before Stage.draw
And the object’s movement doesn’t catch up with my finger.
My Screen Size is 540 * 960.
The Stage is 540 * 720 with the fitting viewport.

#### Reproduction steps/code
```java
if (vct2_zeroCmp == null)
		{
			//Log.w("Test", MainScreen.Stage.stageToScreenCoordinates(new Vector2()).toString());
			vct2_zeroCmp = MainScreen.Stage.screenToStageCoordinates(new Vector2(0, 0));
		}
		vct2_tmp1.set(Gdx.input.getDeltaX(), Gdx.input.getDeltaY());
		Center.add(MainScreen.Stage.screenToStageCoordinates(vct2_tmp1).sub(vct2_zeroCmp));
```

#### Version of LibGDX and/or relevant dependencies
libGdx 1.6.2

#### Stacktrace
```java
Player.Update()
MainScreen.render(float delta)
Main.render()
```

#### Please select the affected platforms
- [+] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
Delta is the difference between last position and current position, you probably want Gdx.input.getX() instead.

If you still think there is an issue, please fill out the issue template correctly.

**Comment by Lestat** [comment]
you should always use the latest stable release, why are you still using that old version?

**Comment by strongrex2001** [comment]
Thank you. Now I record the position when TouchDown, and every TouchDragged calculate the difference and calculate the right position...
I thought that using a zero Vector2 to compare with delta was accurate...
It's a rather old project, so using 1.6.2... I'm going to update then...
