### ISSUE TITLE
ZIndex / Actor.toFront() change the actor position in HorizontalGroup

### ISSUE THREAD

**Issue by doit-ceo** [libgdx/libgdx#4865]
#### Issue details
ZIndex usually change the "drawing order" of the actors and it should not effect the position of that actor within a layout managed group like HorizontalGroup. Trying to set Actor.toFront() which is a child of HorizontalGroup, will force the actor to be the last one in the list, the expect behavior that the Actor will be just drawing last and appear on top.  We need the layout help of the HorizontalGroup but to make extra effects that will go outside the actor/group bounds, we thought to use ZIndex / Actor.toFront() as currently anything drawing outside that bound is being hidden by neighbor actors.  The problem that the Group is using children array to manage drawing order, HorizontalGroup and other layout managed groups are using the same children array for the layout order too, I think they should be different arrays. 

![zindex](https://user-images.githubusercontent.com/8027780/29529499-9d120a60-86a8-11e7-9f1a-f90b5bde43ea.png)

#### Reproduction steps/code
```java
HorizontalGroup hg=new HorizontalGroup();
TextButton b1=new TextButton("Button 1", skin);
TextButton b2=new TextButton("Button 1", skin);
hg.addActor(b1);
hg.addActor(b2);

b1.toFront(); // This will change the order, making b2 as first item in list !
```

#### Version of LibGDX and/or relevant dependencies
1.9.6

**Comment by NathanSweet** [comment]
People may be relying on the current HorizontalGroup behavior so it is unlikely we will change it to use a separate array, though I do agree that would make sense. HorizontalGroup (and VerticalGroup) layouts are simpler cases of using Table, with the biggest difference being that adding/removing actors will requiring clearing the Table layout and adding all the actors back. You could just use Table, or you could add your actors, layout the HorizontalGroup, then never layout the HorizontalGroup again (override `layout` and don't call super to avoid performing layouts).
