### ISSUE TITLE
Color Correction Support

### ISSUE THREAD

**Issue by thedudeguy1** [libgdx/libgdx#4867]
I can't seem to find any add-on or feature to add color correction support to a libGDX project. Have I overlooked something or could this possibly be added in the near future? One of my friends has tritanomaly and I want to be able to provide good accessibility in my game to make for more comfortable playing. If this won't be implemented in the future, is it possible to modify all color values before rendering for my own implementation?

**Comment by haxpor** [comment]
You are able to get away with writing a custom shader, then set it to `SpriteBatch` as a whole. Then every sprites you are going to render under that batch; are going to adhere to custom stuff you wrote inside shader.

**Comment by thedudeguy1** [comment]
@haxpor I'm new to libGDX so I'm sorry if this question is dumb. When applying a custom shader to a ```SpriteBatch```, will that shader also apply to a TMX map when it is being rendered?

**Comment by MobiDevelop** [comment]
As long as the same SpriteBatch is being used to render the map.

**Comment by thedudeguy1** [comment]
Okay. How would I create a custom shader then? Would I use the tint on a ```SpriteBatch``` as shown [here](https://github.com/libgdx/libgdx/wiki/Spritebatch%2C-Textureregions%2C-and-Sprites#tinting) or do I do something else? Could you point me to where I can make and apply the shader?

**Comment by haxpor** [comment]
@thedudeguy1 no worry, your question is not dumb. I have example for you in my project. I need to draw a minimap which basically is TMX map; with custom shader. What I did is render layer by layer and send it value to order it to colorize or just render it as black and white. So you can manipulate color there. You can find that at [MinimapOrthogonalTiledMapRenderer](https://github.com/haxpor/raceplant/blob/master/core/src/io/wasin/raceplant/handlers/MinimapOrthogonalTiledMapRenderer.kt).

It's written in kotlin though, but it's relatively easy to see it as Java, so no big deal. You will at that file in these [lines](https://github.com/haxpor/raceplant/blob/master/core/src/io/wasin/raceplant/handlers/MinimapOrthogonalTiledMapRenderer.kt#L21-L24) in which you hook up your shader file to `OrthogonalTiledmapRenderer` itself.

If you just want to use it with normal `Sprite`, it can be done too by just setting it to `SpriteBatch` to batch draw those objects; similar to above file I linked in.

Apart of shader, you need to create [vertex shader](https://github.com/haxpor/raceplant/blob/master/android/assets/shader/minimap_vertex.glsl), and [fragment shader](https://github.com/haxpor/raceplant/blob/master/android/assets/shader/minimap_fragment.glsl) file (shaders file linked from the same project).

I think you will get an idea there.

**Comment by thedudeguy1** [comment]
Thank you for taking the time to make such a detailed reply. I'm truly grateful. I've never looked at kotlin before but I'll give it a shot. Thanks again!

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
