### ISSUE TITLE
New version of LibGDX (1.6.1) can't run Desktop

### ISSUE THREAD

**Issue by SHFRGRP** [libgdx/libgdx#4873]
I have these output:

****
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchFieldError: gl
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
Caused by: java.lang.NoSuchFieldError: gl
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setDisplayMode(LwjglGraphics.java:359)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:131)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)
****

My codes:
Desktop loader:
 ****
****
package com.shfrgrp.games.game2;

import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration;

import com.shfrgrp.games.game2.TiledMapGame;

public class Main {
	public static void main(String[] args) {
		LwjglApplicationConfiguration cfg = new LwjglApplicationConfiguration();
		cfg.title = "TiledMapGame";
		cfg.useGL20 = true;
		cfg.width = 1280;
		cfg.height = 720;
		
		new LwjglApplication(new TiledMapGame(), cfg);
	}
}
****
****

Main Game:
 ****
****
package com.shfrgrp.games.game2;

import com.badlogic.gdx.*;
import com.badlogic.gdx.audio.*;
import com.badlogic.gdx.graphics.*;
import com.badlogic.gdx.graphics.g2d.*;
import com.badlogic.gdx.math.*;
import java.util.*;
import com.badlogic.gdx.maps.tiled.*;
import com.badlogic.gdx.maps.tiled.renderers.*;
import com.shfrgrp.games.game2.objects.Player;
import com.badlogic.gdx.Application.ApplicationType;

public class TiledMapGame implements ApplicationListener
{
	
	OrthographicCamera camera;
    TiledMap map;
    OrthogonalTiledMapRenderer render;
    Player player;
    
    Texture playerTexture;
    
    //@Override
    public void show(){
        
    }
    
    @Override
    public void create()
	{
        camera = new OrthographicCamera();
        //map = new TmxMapLoader().load(Gdx.files.internal("maps/1.tmx"));
        map = new TmxMapLoader().load("maps/1.tmx");
        render = new OrthogonalTiledMapRenderer(map);
        
        
        if(Gdx.app.getType() == ApplicationType.Android) {
        	playerTexture = new Texture(Gdx.files.internal("img/player.png"));
        }else if (Gdx.app.getType() == ApplicationType.Desktop) {
        	playerTexture = new Texture("img/player.png");
        }
        
        
        player = new Player(new Sprite(playerTexture), map, "Platform");
        player.setPosition(6 * player.getCollisionLayer().getTileWidth(), (player.getCollisionLayer().getHeight()-10) * player.getCollisionLayer().getTileHeight());
        player.setSize(player.getWidth(), player.getHeight());
        
        Gdx.input.setInputProcessor(player);
        
    }

    @Override
    public void render()
	{
		Gdx.gl.glClearColor(0.9f, 0.9f, 0.9f, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT | GL20.GL_DEPTH_BUFFER_BIT);

        camera.position.set(player.getX() + player.getWidth() / 2, player.getY() + player.getHeight() / 2, 0);
		camera.update();
        
        render.setView(camera);
        
        render.render();
        
        render.getSpriteBatch().begin();
        
        render.renderTileLayer((TiledMapTileLayer)map.getLayers().get("background"));
        render.renderTileLayer((TiledMapTileLayer)map.getLayers().get("static"));
        player.draw(render.getSpriteBatch(), camera);
        render.renderTileLayer((TiledMapTileLayer)map.getLayers().get("foreground"));
        
        render.getSpriteBatch().end();
        
		//camera.update();
		
    }
	
	private void resetGame()
	{
		configureCamera();
        
		
	}

	private void configureCamera()
	{
		if (Gdx.graphics.getHeight() < Gdx.graphics.getWidth())
			camera.setToOrtho(false, 800, 800 * Gdx.graphics.getHeight() / Gdx.graphics.getWidth());
		else
			camera.setToOrtho(false, 800 * Gdx.graphics.getWidth() / Gdx.graphics.getHeight(), 800);
	}

	@Override
    public void dispose()
	{
        map.dispose();
        render.dispose();
        player.getTexture().dispose();
    }

    @Override
    public void resize(int width, int height)
	{
		//resetGame();
        camera.viewportWidth = width/3;
        camera.viewportHeight = height/3;
        camera.update();
    }

    @Override
    public void pause()
	{
    }

    @Override
    public void resume()
	{
    }
}
****
****
Player:
 
****
****
package com.shfrgrp.games.game2.objects;
import com.badlogic.gdx.*;
import com.badlogic.gdx.graphics.g2d.*;
import com.badlogic.gdx.maps.tiled.*;
import com.badlogic.gdx.math.*;
import com.badlogic.gdx.Input.Keys;
import com.badlogic.gdx.Input.Buttons;
import com.badlogic.gdx.maps.tiled.TiledMapTileLayer.Cell;
import com.badlogic.gdx.graphics.*;

public class Player extends Sprite implements InputProcessor
{

    

    public Vector2 velocity = new Vector2();
    
    public boolean falling;
    public Vector2 speed = new Vector2(60*2f, 60*2f);
    public float gravity = 60 * 1.8f, increment;
    
    private boolean canJump;
    
    private Vector3 touch = new Vector3();

    private String type;

    private boolean platform = false;

    private boolean rpg = false;
    
    private String blockedKey = "blocked";
	
    private TiledMapTileLayer collisionLayer;
    
    private TiledMap map;
    OrthographicCamera camera;
    
    
	/*public Player(Sprite sprite){
        this(sprite, "default");
		
	}*/
    public Player(Sprite sprite, TiledMap map, String tpe){
        super(sprite);
        this.collisionLayer = (TiledMapTileLayer) map.getLayers().get("static");;
        if (tpe == "rpg" || tpe == "RPG"){
            type = "RPG";
            rpg = true;
        }
        else if(tpe == "Platform" || tpe == "platform"){
            type = "Platform";
            platform = true;
        }else if (tpe =="default" || tpe == "Default"){
            type = "Default (platform)";
            platform = true;
        }else{
            type = "Unknown (using platform)";
            platform = true;
        }

	}

    public void setCollisionLayer(TiledMapTileLayer collisionLayer)
    {
        this.collisionLayer = collisionLayer;
    }

    public TiledMapTileLayer getCollisionLayer()
    {
        return collisionLayer;
    }

    
    
    public String getType(){
        return type;
    }
    public boolean isRPG(){
        return rpg;
    }
    public boolean isPlatform(){
        return platform;
    }
    //@Override
    //Swap SpriteBatch to Batch if using new LibGDX version
    public void draw(Batch batch, OrthographicCamera camera)
    {
        update(Gdx.graphics.getDeltaTime());
        this.camera = camera;
        
        // TODO: Implement this method
        super.draw(batch);
    }

    public void update(float deltaTime)
    {
        // Gravity
        if(platform){
            velocity.y -= gravity * deltaTime;
        } else if(rpg){
            
        }
            
            
        
        if(velocity.y > speed.y)
            velocity.y = speed.y;
        else if(velocity.y < -speed.y)
            velocity.y = -speed.y;
                
            
        float oldX = getX(), oldY = getY();
        boolean collisionX = false, collisionY = false;

        // move on x
        setX(getX() + velocity.x * deltaTime);

        // calculate the increment for step in #collidesLeft() and #collidesRight()
        increment = collisionLayer.getTileWidth();
        increment = getWidth() < increment ? getWidth() / 2 : increment / 2;

        if(velocity.x < 0) // going left
            collisionX = collidesLeft();
        else if(velocity.x > 0) // going right
            collisionX = collidesRight();

        // react to x collision
        if(collisionX) {
            setX(oldX);
            velocity.x = 0;
        }

        // move on y
        setY(getY() + velocity.y * deltaTime * 5f);

        // calculate the increment for step in #collidesBottom() and #collidesTop()
        increment = collisionLayer.getTileHeight();
        increment = getHeight() < increment ? getHeight() / 2 : increment / 2;

        if(velocity.y < 0) // going down
            canJump = collisionY = collidesBottom();
        else if(velocity.y > 0) // going up
            collisionY = collidesTop();

        // react to y collision
        if(collisionY) {
            setY(oldY);
            velocity.y = 0;
		}
            
        
    }
    private boolean isCellBlocked(float x, float y) {
        Cell cell = collisionLayer.getCell((int) (x / collisionLayer.getTileWidth()), (int) (y / collisionLayer.getTileHeight()));
        return cell != null && cell.getTile() != null && cell.getTile().getProperties().containsKey(blockedKey);
    }

    public boolean collidesRight() {
        for(float step = 0; step <= getHeight(); step += increment)
            if(isCellBlocked(getX() + getWidth(), getY() + step))
                return true;
        return false;
    }

    public boolean collidesLeft() {
        for(float step = 0; step <= getHeight(); step += increment)
            if(isCellBlocked(getX(), getY() + step))
                return true;
        return false;
    }

    public boolean collidesTop() {
        for(float step = 0; step <= getWidth(); step += increment)
            if(isCellBlocked(getX() + step, getY() + getHeight()))
                return true;
        return false;

    }

    public boolean collidesBottom() {
        for(float step = 0; step <= getWidth(); step += increment)
            if(isCellBlocked(getX() + step, getY()))
                return true;
        return false;
	}
    /**
    Computer Inputs
    */
    
    @Override
    public boolean keyDown(int p1)
    {
        switch(p1){
            case Keys.W:
            case Keys.SPACE:
                if(canJump) {
                    velocity.y = speed.y / 1.8f;
                    canJump = false;
                }
                break;
            case Keys.A:
                velocity.x = -speed.x;
                break;
            case Keys.D:
                velocity.x = speed.x;
                break;
            
        }
        return true;
    }

    @Override
    public boolean keyUp(int p1)
    {
        switch(p1){
            case Keys.A:
            case Keys.D:
                velocity.x = 0;
                break;
            
        }
        return true;
    }

    @Override
    public boolean keyTyped(char p1)
    {
        // TODO: Implement this method
        return false;
    }

    @Override
    public boolean touchDown(int p1, int p2, int p3, int p4)
    {
        if(rpg){
            touch.set(p1, p2, 0);
            camera.unproject(touch);
            setX((int) touch.x);
            setY((int) touch.y);
        }else{
            touch.set(p1, p2, 0);
            camera.unproject(touch);
            if(touch.x > getX()){
                velocity.x = speed.x;
            }else if(touch.x < getX()){
                velocity.x = -speed.x;
                
            }
            if(touch.y > getY()){
                if(canJump) {
                    velocity.y = speed.y / 1.8f;
                    canJump = false;
                }
            }
        }
        return true;
    }

    @Override
    public boolean touchUp(int p1, int p2, int p3, int p4)
    {
        if(rpg){
            
        }else{
            if(velocity.x != 0){
                velocity.x = 0;
            }
        }
        return true;
    }

    @Override
    public boolean touchDragged(int p1, int p2, int p3)
    {
        touchDown(p1, p2, 0, Buttons.LEFT);
        return true;
    }

    @Override
    public boolean mouseMoved(int p1, int p2)
    {
        // TODO: Implement this method
        return false;
    }

    @Override
    public boolean scrolled(int p1)
    {
        // TODO: Implement this method
        return false;
    }
    
	
	
}
****
****

Oh, i use older version, but i tried v1.6.1, it have some effect. I also used very old version (that not support tiled embedd animation), and it successfully runned. sorry for my bad english.

I followed this tutorial: https://www.youtube.com/playlist?list=PLXY8okVWvwZ0qmqSBhOtqYRjzWtUCWylb . with version of libgdx from this tutorial it works, but if i try to update it, it cause errors in output.

**Comment by SHFRGRP** [comment]
Oh, i use early version, but i tried v1.6.1, it have some effect. I also used old version (that not support tiled embedd animation), and it successfully runned. sorry for my bad english.

**Comment by piotr-j** [comment]
The current version is 1.9.6, the repo is from 2013, thats most likely 0.9.9 or something.  There ware many breaking changes since then.  Replacing the jars will not work. 

If you want to update the tutorial for some reason, start with 1.0.0, fix up all the errors and go to next major release. https://github.com/libgdx/libgdx/releases?after=gdx-parent-1.2.0

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
