### ISSUE TITLE
Box2D wrapper missing World#shiftOrigin method

### ISSUE THREAD

**Issue by voidburn** [libgdx/libgdx#4880]
Reading the box2d extension's changelist I see that some stuff didn't make the cut in the wrapper. World#shiftOrigin is one of those.

@badlogic @MobiDevelop : Is there a specific reason why it was left out? Would it be safe to expose it? 

https://github.com/libgdx/libgdx/blob/master/extensions/gdx-box2d/gdx-box2d/jni/Box2D/CHANGES

**Comment by Tom-Ski** [comment]
Feel free to add it!

**Comment by voidburn** [comment]
I don't have the setup to regenerate the JNI files, will the build server do that if I simply add the following to [World.java](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-box2d/gdx-box2d/src/com/badlogic/gdx/physics/box2d/World.java)? (Sorry, have never used JNI/Jnigen before)

```
/** Shift the world origin */
public void shiftOrigin (Vector2 newOrigin) {
	jniShiftOrigin(addr, newOrigin.x, newOrigin.y);
}

private native void jniShiftOrigin (long addr, float newOriginX, float newOriginY); /*
	b2World* world = (b2World*)addr;
	world->ShiftOrigin( b2Vec2( newOriginX, newOriginY ) );
*/
```

**Comment by Tom-Ski** [comment]
No it won't, and someone will have to test it....

You'll also need to add it to https://github.com/libgdx/libgdx/blob/master/extensions/gdx-box2d/gdx-box2d-gwt/src/com/badlogic/gdx/physics/box2d/gwt/emu/com/badlogic/gdx/physics/box2d/World.java

The method isnt in jbox2d, which is probably why this wasn't bound in the first place, so it would have to be implemented there, or a stub, which is less nice.

**Comment by voidburn** [comment]
Ah, the changelog didn't mention "(missing equivalent in GWT JBox2D port)" for the ShiftOrigin method. Better missing than inconsistent across platforms. Also, I definitely don't have the required experience to deploy and test this.

Unless I'm mistaken, feel free to close this, last thing we need is another pointless issue on the pile :D

**Comment by Tom-Ski** [comment]
You can hack it by just transforming all your objects I guess.  Will close it out, if its a vital feature feel free to reopen and we can tag it as an enhancement.
