### ISSUE TITLE
iOS Logging in to Game Center freezes seemingly because EULA needs to be shown

### ISSUE THREAD

**Issue by simernes** [libgdx/libgdx#4881]
Ive been working with GameCenter implementation on the RoboVM backend, but I have a problem where the application hangs after entering user credentials in the View Controller presented for Game Center.

Basically what happens is:
1. The application launches.
2. After the app has initialized, the user is presented a Game Center View where he or she is prompted to enter user credentials for Apple ID.
3. After the user enter the user credentials, the apple loading indicator (the little spinning wheel) spins for a while, and then the app freezes there. There is an option to Cancel logging in to Game Center, but that doesn't respond to clicks anymore. 
Ive attached a screenshot at the bottom of the issue to show where it hangs.

I then went into settings and checked out if anything could be found about Game Center (Im running an iPhone Simulator of specs iPhone 6 / iOS 9.3 (13E230).
I found that if I go into Game Center settings, I could see my email as logged in, and then I was prompted to accept the Game Center EULA.

After I accepted that in the settings and relaunched the app, it worked fine, and I was welcomed by a Game Center dialog sliding down from the top saying "Welcome Back Username".

**An important detail here is that the user used to log in to Game Center was completely new and had never used Game Center before.
If I try it with a user that has accepted the EULA in the iPhone Settings, then the login View dismisses correctly and everything proceeds smoothly.**

So, the user needs to be redirected to accept the EULA in some way. Is that possible? Ive seen that you can pass a completion argument to presentViewController, which I have set to null in my code if you'll have a look at the code that follows. Or is there some other way I can use to log in the user?

The main code that Im wondering about is 
```iOSApplication.getUIWindow().getRootViewController().presentViewController(uiViewController, false, null);```
Where Im wondering if it is possible to pass a VoidBlock as completion rather than null, which directs the user to accepting the EULA.

The full code used for authentication:

```

localPlayer = GKLocalPlayer.getLocalPlayer();
localPlayer.setAuthenticateHandler(new VoidBlock2<UIViewController, NSError>() {
			@Override
			public void invoke(UIViewController uiViewController, NSError nsError) {
				if(localPlayer.isAuthenticated()) {
					print("local player is authenticated");
					localPlayer.generateIdentityVerificationSignature(new VoidBlock5<NSURL, NSData, NSData, Long, NSError>() {
						@Override
						public void invoke(NSURL publicKeyUrl, NSData signature, NSData salt, Long timestamp, NSError error) {
							// TODO Auto-generated method stub
							//successfully logged into gamecenter
						}
					});
				} else if(uiViewController != null) {
					iOSApplication.getUIWindow().getRootViewController().presentViewController(uiViewController, false, null);
				} else {
					//canceled by the user or GameCenter is disabled
					print("not supported");
				}
			}
		});
```

I found this code at https://reimerm.de/2016/11/integrating-gamecenter-into-libgdx-java-multi-os-engine-8/ which is meant for multi-os-engine-8, but I managed to get it to work with a few very little tweaks.

![screen shot 2017-09-03 at 11 22 12 am](https://user-images.githubusercontent.com/1278451/30001856-9017ada0-909a-11e7-8c6f-84170622dfda.png)

#### Version of LibGDX and/or relevant dependencies
libgdx 1.9.6
robovm 2.3.0

**Comment by Tom-Ski** [comment]
Can you transfer this to the https://github.com/MobiVM/robovm repository issue tracker
