### ISSUE TITLE
Use PerformCounter in multi-thread asynchronous codes

### ISSUE THREAD

**Issue by softwareabc** [libgdx/libgdx#4887]
How to use PerformCounter in multi-thread asynchronous codes? When should I call tick() and stop()? Thanks.

Version 1.3.12

Platforms:
-  Windows
-  Linux

**Comment by piotr-j** [comment]
Presumably in the task you want to measure. Libgdx classes are not designed to be accesses from multiple threads, so you will have to lock stuff yourself.

**Comment by Tom-Ski** [comment]
As @piotr-j says, you're going to need to wrap this yourself. Please use the forum or the irc channel if you want assistance with it.
