### ISSUE TITLE
AssetManager is hanging up

### ISSUE THREAD

**Issue by JuKu** [libgdx/libgdx#4888]
Please ensure you have given all the following requested information in your report.

#### Issue details
I try to load and get an TextureAtlas asset file and use the AbsoluteFileHandlerResolver:
new AssetManager(new AbsoluteFileHandlerResolver())

After assetManager.load(), i call assetManager.finishLoadingAsset(atlasFile) which causes into a deadlock or something else. The window is frozen / hanging up forever (only STRG + C helps).

![lc](https://user-images.githubusercontent.com/1138046/30484056-71b6ebe4-9a29-11e7-81ba-51aa043432d3.PNG)

#### Reproduction steps/code

```java
Gdx.app.debug("WaterRenderer", "try to load atlas file: " + atlasFile);

//load asset
assetManager.load(atlasFile, TextureAtlas.class);

if (assetManager.isLoaded(atlasFile)) {
    Gdx.app.log("Water", "water animation is already loaded.");
} else {
    Gdx.app.log("Water", "water animation isnt loaded yet.");
}

//finish loading
assetManager.finishLoadingAsset(atlasFile); //this command is hanging up game, without this line the game isnt hanging up, but also asset isnt loaded

Gdx.app.debug("WaterRenderer", "atlas file loaded: " + atlasFile);
```

Full source code (i have tagged the not-working-code):
https://github.com/leeks-and-dragons/leeks-and-dragons/tree/libgdx_hanging_up_issue

#### Version of LibGDX and/or relevant dependencies
I use the newest libGDX Version, **libGDX 1.9.6**.

#### Stacktrace
There isnt any stacktrace.

#### Log

I have set asset manager log method to DEBUG. So this is the log:
```
WaterRenderer: try to load atlas file: D:\Users\Justin\IdeaProjects\LeeksAndDragons-Project\leeks-and-dragons\mods\maingame\animation\water\WaterAnimation.atlas
Water: water animation isnt loaded yet.
AssetManager: Loading: D:/Users/Justin/<Project Name>/mods/maingame/animation/water/WaterAnimation.atlas, com.badlogic.gdx.graphics.g2d.TextureAtlas
AssetManager: Loading dependency: D:/Users/Justin/<Project Name>/mods/maingame/animation/water/WaterAnimation.png, com.badlogic.gdx.graphics.Texture
```

**EDIT**:
If i print **assetManager.getDiagnostics()** before assetManager.finishLoadingAsset(atlasFile) call, i get this output:
```
WaterRenderer: try to load atlas file: D:\Users\Justin\IdeaProjects\LeeksAndDragons-Project\leeks-and-dragons\mods\maingame\animation\water\WaterAnimation.atlas
Water: water animation isnt loaded yet.
Water: 
========
BEGIN of asset manager diagnostics:
========
D:/Users/Justin/IdeaProjects/LeeksAndDragons-Project/leeks-and-dragons/mods/maingame/animation/water/WaterAnimation.png, Texture, refs: 1
./data/wallpaper/Loading_Screen.png, Texture, refs: 2
./data/wallpaper/Loading_Screen_layer_2.png, Texture, refs: 2
D:/Users/Justin/IdeaProjects/LeeksAndDragons-Project/leeks-and-dragons/mods/maingame/asset1.png, Texture, refs: 1
D:/Users/Justin/IdeaProjects/LeeksAndDragons-Project/leeks-and-dragons/mods/maingame/asset2.png, Texture, refs: 1
./data/sound/menu_selection_click/menu_selection_click_16bit.wav, Sound, refs: 1
D:/Users/Justin/IdeaProjects/LeeksAndDragons-Project/leeks-and-dragons/mods/maingame/animation/water/WaterAnimation.atlas, TextureAtlas, refs: 1, deps: [D:/Users/Justin/IdeaProjects/LeeksAndDragons-Project/leeks-and-dragons/mods/maingame/animation/water/WaterAnimation.png,]

========
END of asset manager diagnostics:
========
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

I have tested it only with Windows 10, maybe same problem occurres on Linux & Mac OS.

**Comment by piotr-j** [comment]
Try loading it via `new TextureAtlas(FileHandle);` and see if it works.

**Comment by JuKu** [comment]
@piotr-j Thanks for your answer! :)

I have tested it and it works with this snippet:
```java
FileHandle fileHandle = Gdx.files.absolute("mods/maingame/animation/water/WaterAnimation.atlas");
TextureAtlas atlas = new TextureAtlas(fileHandle);
```

So i think the bug is really in asset manager.

**Comment by JuKu** [comment]
I have reproduced this issue an little bit more and maybe i have found the problem.

This works fine:
```java
assetManager.load("mods/maingame/animation/water/WaterAnimation.atlas", TextureAtlas.class);
```

Also this works fine:
```java
assetManager.load("D:/Users/Justin/IdeaProjects/LeeksAndDragons-Project/leeks-and-dragons/mods/maingame/animation/water/WaterAnimation.atlas");
```

But this snippet doesnt work and causes an application hang up:
```java
File file = new File("mods/maingame/animation/water/WaterAnimation.atlas");
Gdx.app.debug("WaterRenderer", "atlas file: " + file.getAbsolutePath());

assetManager.load(file.getAbsolutePath(), TextureAtlas.class);//this line is game hanging up
```

Whats the problem? It's easier, than you think. The output from Gdx.app.debug() is this:
```
WaterRenderer: atlas file: D:\Users\Justin\IdeaProjects\LeeksAndDragons-Project\leeks-and-dragons\mods\maingame\animation\water\WaterAnimation.atlas
```

Whats the different? The last log uses windows backslashes "\" (because file.getAbsolutePath() returns string with backslashes on windows) instead of slashes "/".

So if i replace backslash with slash, this snippet works also:
```java
File file = new File("mods/maingame/animation/water/WaterAnimation.atlas");
Gdx.app.debug("WaterRenderer", "atlas file: " + file.getAbsolutePath());

assetManager.load(file.getAbsolutePath().replace("\\", "/"), TextureAtlas.class);
```

**Comment by toyknight** [comment]
Now you get it. Actually when running on a Japanese windows, those backslashes will become '¥'. So that's why you want to use FileHandle instead of java.io.File.
