### ISSUE TITLE
MoveToAction should expose startX and startY?

### ISSUE THREAD

**Issue by ghost** [libgdx/libgdx#4890]
I'm looping through an Actor's actions, and if it's a MoveToAction, I need to extend the X position (because I need to preserve its interpolation logic instead of creating a new action). 

However, I need to know which direction MoveToAction is going, which means it would be really convenient to call moveToAction.getStartX().  My workaround is rather nasty...

Unfortunately, these are private fields. Any change these could be made public via getters/setters?

Thanks.

**Comment by piotr-j** [comment]
Since you need custom logic, you should probably use custom action.

**Comment by notsonotso** [comment]
@piotr-j Being able to get the starting position would be convenient.

**Comment by gonzeD** [comment]
I've made a pull request to correct this issue https://github.com/libgdx/libgdx/pull/5043

**Comment by MrStahlfelge** [comment]
Closing this, attached PR was closed, to. As suggested, you should use a custom action.
