### ISSUE TITLE
OpenAL Music getPosition reports incorrect values after playing then stopping then playing again

### ISSUE THREAD

**Issue by chrislo27** [libgdx/libgdx#4895]
#### Issue details
Starting with commit https://github.com/libgdx/libgdx/commit/b0e71b000c978c179b17c9bfa8175b69d4029468, calling getPosition() on Music (desktop) returns incorrect values if played, stopped, and then played from the beginning.

#### Reproduction steps/code
1. Load a music object using `Gdx.audio.newMusic`.
2. Play it for several seconds. Usually at least three is enough, but more makes the effect more noticeable.
3. Call `stop` on the Music object. You'll see that the result of `getPosition` is 0.0.
4. Play the music again.
5. By checking the result of `getPosition`, you will see that it quickly returns the old position value prior to having `stop` called, but still increases. (eg: If you stopped it at 10.0 seconds, it will return 0.0 for the first frames of music, but then return to 10.0 and keep increasing.) The actual playback of music is 100% okay, though.

Below is a runnable example. SPACE will pause/play the music, S will stop it and print the position right after. You should replace the FileHandle for the music with something appropriate. So far this happens on all three supported formats from my testing (WAV, MP3, OGG).
```java
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.Input.Keys;
import com.badlogic.gdx.audio.Music;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.graphics.GL20;

public class Test extends ApplicationAdapter {

    Music music;

    public void create () {
        music = Gdx.audio.newMusic(Gdx.files.local("music.ogg"));
    }

    public void render () {
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

        if (Gdx.input.isKeyJustPressed(Keys.SPACE)) {
            if (music.isPlaying()) {
                music.pause();
            } else {
                music.play();
            }
        } else if (Gdx.input.isKeyJustPressed(Keys.S)) {
            music.stop();
            printPosition();
        }

        if (music.isPlaying()) {
            printPosition();
        }
    }

    void printPosition() {
        System.out.println(music.getPosition());
    }

    @Override
    public void dispose() {
        super.dispose();
        music.dispose();
    }

    public static void main (String[] args) throws Exception {
        new LwjglApplication(new Test());
    }
}
```

#### Version of LibGDX and/or relevant dependencies
https://github.com/libgdx/libgdx/commit/b0e71b000c978c179b17c9bfa8175b69d4029468

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by mgsx-dev** [comment]
I'm the author of the PR https://github.com/libgdx/libgdx/pull/4659. I'll check it and fix it ASAP.

Thanks for the test case!

**Comment by mgsx-dev** [comment]
Simpler than I thought. I was able to reproduce with the official test (com.badlogic.gdx.tests.MusicTest), I missed it sorry. It should be OK now.
