### ISSUE TITLE
touchDragged issue in Asus Zenfone 3 (Android)

### ISSUE THREAD

**Issue by yuripourre** [libgdx/libgdx#4898]
I am having touch issues only with my Zenfone 3 (Android). I tested the same code into a Moto G, Moto E and everything is fine.

#### Issue details
When I touch the screen, the method touchDown is called but soon after that the method touchDragged is always called even with just a fast touch.

I solved this comparing both timestamps and ignoring if the differece between both timestamps is too short (less than 100ms).

I am openning this issues to confirm if it happens with other devices.

#### Reproduction steps/code
Run the app into a Zenfone 3
Touch the screen.
You will see that both touchDown and touchDragged are called

#### Code
```
package com.my.app;

import android.os.Bundle;

import com.badlogic.gdx.ApplicationListener;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.InputProcessor;
import com.badlogic.gdx.backends.android.AndroidApplication;
import com.badlogic.gdx.backends.android.AndroidApplicationConfiguration;

public class InputDemo extends AndroidApplication implements ApplicationListener, InputProcessor {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        AndroidApplicationConfiguration config = new AndroidApplicationConfiguration();
        initialize(this, config);
    }

    @Override
    public void create() {
        Gdx.input.setInputProcessor(this);
    }

    @Override
    public void dispose() {}

    @Override
    public void render() {}

    @Override
    public void resize(int width, int height) {}

    @Override
    public void pause() {}

    @Override
    public void resume() {}

    @Override
    public boolean keyDown(int keycode) {
        // TODO Auto-generated method stub
        return false;
    }

    @Override
    public boolean keyUp(int keycode) {
        // TODO Auto-generated method stub
        return false;
    }

    @Override
    public boolean keyTyped(char character) {
        // TODO Auto-generated method stub
        return false;
    }

    @Override
    public boolean touchDown(int screenX, int screenY, int pointer, int button) {
        System.out.println("touchDown was called");
        return true;
    }

    @Override
    public boolean touchUp(int screenX, int screenY, int pointer, int button) {
        System.out.println("touchUp was called");
        return true;
    }

    @Override
    public boolean touchDragged(int screenX, int screenY, int pointer) {
        System.out.println("touchDragged was called");
        return true;
    }

    @Override
    public boolean mouseMoved(int screenX, int screenY) {
        // TODO Auto-generated method stub
        return false;
    }

    @Override
    public boolean scrolled(int amount) {
        // TODO Auto-generated method stub
        return false;
    }
}
```

Output after (fast) touch:
```
09-24 15:21:05.027 6258-6304/com.my.app I/System.out: touchDown was called
09-24 15:21:05.027 6258-6304/com.my.app I/System.out: touchDragged was called
09-24 15:21:05.043 6258-6304/com.my.app I/System.out: touchDragged was called
09-24 15:21:05.060 6258-6304/com.my.app I/System.out: touchDragged was called
09-24 15:21:05.060 6258-6304/com.my.app I/System.out: touchUp was called
```

#### Version of LibGDX and/or relevant dependencies
libgdx 1.9.6

#### Please select the affected platforms
- [X] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
Do you have gestures enabled?

**Comment by yuripourre** [comment]
No, Touch Gestures and Motion Gestures are off.

**Comment by Tom-Ski** [comment]
Can you log the positions from these events too.

**Comment by yuripourre** [comment]
Sure.
I touched the screen twice this time.

I changed the code a bit:
```
@Override
    public boolean touchDown(int screenX, int screenY, int pointer, int button) {
        System.out.println("touchDown is called: "+screenX+" "+screenY+" "+pointer+" "+button);
        return true;
    }

    @Override
    public boolean touchUp(int screenX, int screenY, int pointer, int button) {
        System.out.println("touchUp is called: "+screenX+" "+screenY+" "+pointer+" "+button);
        return true;
    }

    @Override
    public boolean touchDragged(int screenX, int screenY, int pointer) {
        System.out.println("touchDragged is called: "+screenX+" "+screenY+" "+pointer);
        return true;
    }
```


The output
```
09-24 19:38:08.845 20593-20696/com.my.app I/System.out: touchDown is called: 484 1066 0 0
09-24 19:38:08.862 20593-20696/com.my.app I/System.out: touchDragged is called: 484 1066 0
09-24 19:38:08.862 20593-20696/com.my.app I/System.out: touchUp is called: 484 1066 0 0
```
```
09-24 19:38:20.796 20593-20696/com.my.app I/System.out: touchDown is called: 459 745 0 0
09-24 19:38:20.812 20593-20696/com.my.app I/System.out: touchDragged is called: 459 745 0
09-24 19:38:20.828 20593-20696/com.my.app I/System.out: touchDragged is called: 459 745 0
09-24 19:38:20.845 20593-20696/com.my.app I/System.out: touchDragged is called: 459 745 0
09-24 19:38:20.845 20593-20696/com.my.app I/System.out: touchUp is called: 459 745 0 0
```

**Comment by Darkyenus** [comment]
Dragged positions are the same as the touch down positions - good input code should have some tolerance to dragging around the touch point as it is almost impossible to press and release exactly on the same point (well depends on your screen and fingers, I'm speaking from my experience), so this "bug" shouldn't have any impact on good input code.

However it is still weird. We could filter touchDragged events if they don't actually move anywhere to fix this - if we want to fix this, as outlined above.

I wonder what causes this, perhaps the phone calculates coordinates internally with higher precision and the resulting pixel coordinate turns out to be always the same? Are the coordinates always the same or do they change slightly sometimes?

**Comment by Tom-Ski** [comment]
Possibly, you'd have to make an android standalone test to determine if they are sub pixel events.  It could also be the vendor sending in rogue input.

**Comment by yuripourre** [comment]
@Darkyenus the positions are always the same.
I am doing a file manager app so I need to know if user is clicking or dragging.

@Tom-Ski I will try to test with other Asus devices (it might take a while).

**Comment by Darkyenus** [comment]
@yuripourre You should still have some movement tolerance, e.g. recognize the event as dragging only after touch position changes by ~10px or something. See `com.badlogic.gdx.input.GestureDetector`, it already does this. Otherwise it may be very hard for some users to tap without it being recognized as drag event.

**Comment by yuripourre** [comment]
@Darkyenus
That's a way to solve it too. I am comparing *timestamps* because I already have this value and I can check only once instead of check for *x* and *y* positions.

I will take a look on Gesture Detector later. I am using custom inputs to integrate with my [game library](https://github.com/Harium/etyl)

**Comment by noblemaster** [comment]
Given there is no further comment, I'll assume this is handled? I'll close this issue. It can be re-opened if needed.

**Comment by yuripourre** [comment]
I did a dirty fix on my own framework, don't want to merge with libgdx because the workaround is not beautiful.
