### ISSUE TITLE
Gdx setup for Robovm, MOE backend should use Asset Catalog for App Icon

### ISSUE THREAD

**Issue by keesvandieren** [libgdx/libgdx#4899]
#### Issue details

Details discussed in https://github.com/MobiVM/robovm/issues/210

The Robovm app generated by the GDX setup utility (and probably also the MOE variant) use CFBundleIcons in Info.plist.xml to define app-icons available.

Since the Xcode 9 release (and related App Store upgrades) this is no longer supported; asset catalog AppIocn needs to be used.

#### Reproduction steps/code

* Generate a new libgdx project with ios (Robovm backend)
* Register app id in iTunes Connect, Apple Member Center.
* Submit the app.

It will fail with the following error:

    Missing Info.plist value - A value for the "Info.plist" key CFBundleIconName is missing in the 
     bundle 'com.rosapp.choinkafull'. Apps that provide icons in the asset catalog must also provide 
    this Info.plist key. For more information see 
    http://help.apple.com/xcode/mac/current/#/dev10510b1f7.

#### Version of LibGDX and/or relevant dependencies
All versions (Xcode / App Store change)

#### Please select the affected platforms
- [ ] Android
- [x] iOS (robovm)
- [x] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by keesvandieren** [comment]
If anyone points me to a  Libgdx logo in SVG format (Inkscape compatible) I can easily generate the logos in all required formats and attach them to this issue

**Comment by piotr-j** [comment]
This works? https://github.com/libgdx/libgdx/blob/master/libgdx_logo.svg

**Comment by piotr-j** [comment]
I dont think there is a square one. You can rotate this one i guess https://github.com/libgdx/libgdx/blob/master/libgdx_logo.svg

**Comment by keesvandieren** [comment]
Pull request for Robovm has been accepted. MOE still needs to be done.
