### ISSUE TITLE
gdx-setup.jar finds a non-existent version of the build-tools

### ISSUE THREAD

**Issue by yrabbit** [libgdx/libgdx#4904]
Hello
#### Issue details
gdx-setup.jar finds a non-existent version of the build-tools.

#### Reproduction steps/code
* Install Android Studio 2.3.3 and build tools 26.0.2
* run java -jar gdx-setup 
* check Android box
* generate

Output:
IllegalStateException: Failed to find Build Tools revision 27.0.2

#### Please select the affected platforms
- [X ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

#### Cause
There are next lines in  file "Android/Sdk/build-tools/26.0.2/source.properties"
-----
#Pkg.Revision=27.0.2
Pkg.Revision=26.0.2
----

#### Possible solution: 
ignore comments (lines starting with #) in the 
"private static String readBuildToolsVersion (File parentFile)" function 
in the file "libgdx/extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetup.java".

**Comment by ttencate** [comment]
This should just use Java's built-in Properties parser. I'm preparing a PR.
