### ISSUE TITLE
[Java 9] Can you release a new version with updated lwjgl3?

### ISSUE THREAD

**Issue by ForsakenHarmony** [libgdx/libgdx#4918]
The current version gives this warning `WARNING: An illegal reflective access operation has occurred`

From what I've read here (https://github.com/LWJGL/lwjgl3/issues/334) it has been fixed in 3.1.1, the code seems to already be updated, but not released yet

**Comment by Tom-Ski** [comment]
We have updated, you can use the snapshots while you are waiting for the release.

**Comment by ForsakenHarmony** [comment]
how do I use the snapshots?

**Comment by ShaneG** [comment]
I'm having the same issue, did you figure this out?

**Comment by francogp** [comment]
@ForsakenHarmony use gdxVersion = '1.9.7-SNAPSHOT' on your main gradle config
