### ISSUE TITLE
Error in resizing Table

### ISSUE THREAD

**Issue by NasGitter** [libgdx/libgdx#4920]
#### Issue details
When the window gets resized, it can cause false resizing in a Table.
It is inconsistent and requires multible resizings for it to happen.
With ExtendViewport one needs to resize the screen width.
First make the window  very small, then make it very big, and then the error can be seen.
If you resize in small steps, the error cant be seen.
With ScreenViewport one needs to resize the screen heigth.
Resizing the window into a smaller version makes it happen.
Making the window bigger, and the error disappears.
Big resizing actions are needed for the error to appear.
Resizing in small steps keeps everything correct in size.

The error is that the table cells have the wrong sizes and that the inner table also has the wrong size and goes out of the screen and even out of the parent table.

A few logs:
(on start it is correct)
REAL SCREEN     : 791 592
Stage                  : 801.6892 600.0
root table           : 801.6892 600.0
inner table          : 160.0 600.0
viewport World   : 801.6892 600.0
viewport Screen  : 791 592

(after resizing inner table heigth is higher than root table)
REAL SCREEN     : 563 384
Stage                 : 879.6875 600.0
root table           : 879.6875 600.0
inner table          : 176.0 707.0
viewport World   : 879.6875 600.0
viewport Screen  : 563 384

And a picture to show the error:
[https://raw.githubusercontent.com/NasGitter/Sammelbecken/master/t2.png](https://raw.githubusercontent.com/NasGitter/Sammelbecken/master/t2.png)

```java
import com.badlogic.gdx.*;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.*;
import com.badlogic.gdx.utils.viewport.*;

public class BarebonesStage extends ApplicationAdapter {
	Stage stage;
	Table table;
	Table inner;
	Viewport view;

	public void create () {
		
		view = new  ExtendViewport(Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
	//	view = new ScreenViewport();
		stage = new Stage(view);
		Gdx.input.setInputProcessor(stage);

		table = new Table();
		stage.addActor(table);
		table.setFillParent(true);

		inner = new Table();
		inner.debug();
		
		table.add(inner).fill().expandY().width(Value.percentWidth((float) 0.20, table));
		table.add().expandY().width(Value.percentWidth((float) 0.70, table));
		table.add().expandY();
		table.left();

		inner.add().expandX().height(Value.percentHeight((float) 0.80, inner));
		inner.row();
		inner.add().expandX().height(Value.percentHeight((float) 0.10, inner));

		stage.addActor(table);
	}

	public void render () {
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		stage.draw();
	}
	
	public void resize (int width, int height) {
		stage.getViewport().update(width, height, true);
	}

	public static void main (String[] args) throws Exception {
		new LwjglApplication(new BarebonesStage());
	}
}

```

#### Please select the affected platforms
- [ x ] Windows

**Comment by NathanSweet** [comment]
`height(Value.percentHeight((float)0.80, inner))` means that the min/pref/max height is 80% of the height of `inner`. The min/pref/max height is used to decide the height of `inner`, so it is not good that those values have a dependency on the height of `inner` -- it means values from a previous layout can affect subsequent layouts.

If you change to `height(Value.percentHeight((float)0.80, table))` then it works fine. It is OK for min/pref/max sizes to depend on the size of the parent, but not the size of themselves. There is one exception: for `table` it is OK for min/pref/max to depend on the size of itself because `setFillParent` is used.
