### ISSUE TITLE
java.util.zip.ZipFile and Gdx.files.internal on android is not working

### ISSUE THREAD

**Issue by TypeOverride** [libgdx/libgdx#4926]
I have the problem that its not possible to use the "ZipFile"-class of java for internal storage when im on android. "ZipFile"-class needs a File as constructor parameter and so i make Gdx.files.internal(test.zip).file(), and it can't read the file. I've read its not working on internal files. For this i need a FileHandle. But i want to use the internal storage of the android device!

So the question is, is there a solution?

Its only affected an Android build (apk)

**Comment by MobiDevelop** [comment]
So, to make sure I understand correctly, you are trying to read a .zip file from the "assets", right? Since "internal" files are read as a Stream, in order to create a File pointing at it you will probably need to extract the file from internal to local or external storage before using Zip file with it.

**Comment by mgsx-dev** [comment]
Did you tried ZipInputStream instead of ZipFile ? As mentionned here : https://stackoverflow.com/questions/23869228/how-to-read-file-from-zip-using-inputstream

It could work like this : `new ZipInputStream(Gdx.files.internal(...).read())`, I didn't tried.

**Comment by TypeOverride** [comment]
**# SOLVED!**

**Thanks mgsx-dev (for giving me the link and the right track). And MobiDevelop (for saying only streams on internal) too.**

Ive solved it. I want to share my code here:

ArchiveFileHandleResolver2:
https://onedrive.live.com/download?cid=BFDD6BD31D2255F1&resid=BFDD6BD31D2255F1%21738&authkey=AILp06N0JAasVlY

ArchiveFileHandle2:
https://onedrive.live.com/download?cid=BFDD6BD31D2255F1&resid=BFDD6BD31D2255F1%21739&authkey=AKOzq9w636-EmGI

you can use it with the assetmanager. So make this:
```
FileHandleResolver resolver  = new ArchiveFileHandleResolver2(Gdx.files.internal(url_zip_file));
_assetManager.setLoader(Texture.class, new TextureLoader(map_resolver));
_assetManager.load("image.png", Texture.class);
```

(example for when the zip file has as content a "png-file" called "image.png")
