### ISSUE TITLE
Import project into existing Android Package Kit

### ISSUE THREAD

**Issue by shukis** [libgdx/libgdx#4930]
Hi,

I have such a question. I want to develop a game using libgdx and include it into existing android application, so there would be button "start game" and then game would be started. Is it possible to import aar from my game or how would be possible to do that?

Thank you in advance,

Pavel

**Comment by Tom-Ski** [comment]
Hi @shukis, please use the forum or the irc channel for such questions. 
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
