### ISSUE TITLE
Feature request: Make Gdx.app::exit accept an optional exit code parameter

### ISSUE THREAD

**Issue by lvivtotoro** [libgdx/libgdx#4931]
I am having at the moment a pretty bad situation where my program's exit code actually depends on some server's behavior. (Don't ask how I ended up here)  
I would call `System::exit` but it would not dispose any of my resources.

**Comment by Velocity-** [comment]
Well, you can take care of that really: once you call `exit()`, the `running` boolean is set to false on a desktop application, resulting in the render loop doing this:

```java
		synchronized (lifecycleListeners) {
			LifecycleListener[] listeners = lifecycleListeners.begin();
			for (int i = 0, n = lifecycleListeners.size; i < n; ++i) {
				listeners[i].pause();
				listeners[i].dispose();
			}
			lifecycleListeners.end();
		}
		listener.pause();
		listener.dispose();
		Display.destroy();
		if (audio != null) audio.dispose();
		if (graphics.config.forceExit) System.exit(-1);
```

Meaning that if you set `forceExit` to false in the `LwjglApplicationConfiguration`, you can call `System.exit(x)` yourself after the main loop ends. Hope that helps.

**Comment by lvivtotoro** [comment]
Thanks, but fyi, there are a lot of methods in this framework that are platform specific.  
I can't name them off the top of my head, though
