### ISSUE TITLE
Question: Kotlin in general + HTML/Browser version

### ISSUE THREAD

**Issue by SohnyBohny** [libgdx/libgdx#4933]
I'm happy to [read](https://github.com/libgdx/libgdx/wiki/Using-libGDX-with-Kotlin) that Kotlin is officially supposed in Libgdx.

Are there any disadvantages using Kotlin instead of Java with Libgdx. Any Bugs...?

Is there any way compiling a Kotlin Browser version? Or are there any plans supporting this in near future?

Thank you :smiley:

**Comment by Tom-Ski** [comment]
Its not possible with the web backend because it works via GWT, and requires java source code. This is the same for any other jvm language.  You can try solutions like teavm, but there is no official support as of now, and no plans to support in the future. People are welcome to submit PRs though.
