### ISSUE TITLE
TexturePacker with settings.interpolationMode?

### ISSUE THREAD

**Issue by gestaltdevstudio** [libgdx/libgdx#4934]
Hi,

I'm making a pixel art game and I need to upscale the images. I would like to do it while packing.
Is it possible that we have a settings.interpolationMode in [TexturePacker](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-tools/src/com/badlogic/gdx/tools/texturepacker/ImageProcessor.java#L168) when settings.scale[n] >1? 

Thanks!

**Comment by Velocity-** [comment]
I've submitted a pull request, hope it does what you had in mind!

**Comment by xGnoSiSx** [comment]
@gestaltdevstudio can you please try it and advise here how/if it works?

I assume the packed textures are scaled, and drawing would respect he correct texture filtering when creating the pages.

**Comment by gestaltdevstudio** [comment]
@Velocity- @xGnoSiSx Yes, it does! The Nearest mode did the trick!
Thanks!

**Comment by Velocity-** [comment]
Glad to hear, @gestaltdevstudio! Hope to get the PR merged to make it available in 1.9.8.
