### ISSUE TITLE
ARKit: Cannot access EAGLContext in iOS

### ISSUE THREAD

**Issue by RaimundWege** [libgdx/libgdx#4935]
#### Issue details
Currently I'm working on an ARKit implementation but now I get stuck at a point where I have to pass the EAGLContext of the iOS app to a native method and I can't find a way to access it. I've tried `EAGLContext.currentContext()` but it returns always null. I think it is because the current-context has never been set in IOSGraphics.java. This is the method I'm trying to call:

CoreVideo.CVOpenGLESTextureCacheCreate(null, null, EAGLContext.currentContext(), null, textureCache);

#### Version of LibGDX and/or relevant dependencies
libgdx 1.9.7-SNAPSHOT
moe 1.4.+

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [x] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by RaimundWege** [comment]
I've found a workaround with reflection:
>
        IOSGraphics iosGraphics = (IOSGraphics) Gdx.graphics;
        EAGLContext context;
        try {
            Field f = iosGraphics.getClass().getDeclaredField("context");
            f.setAccessible(true);
            context = (EAGLContext) f.get(iosGraphics);
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
            return false;
        } catch (IllegalAccessException e) {
            e.printStackTrace();
            return false;
        }

**Comment by Velocity-** [comment]
That's weird though, isn't it? I would assume currentContext() would return that variable, so I'm not sure why the reflection trick works in this case. Perhaps it grabs the thread-local context? Might be worth passing this to MOE as they may want to check this out.

**Comment by Tom-Ski** [comment]
We definitely set it. If you can provide a self executable example we can take a look. Otherwise consult MOE!
