### ISSUE TITLE
Libgdx1.9.7 Framebuffer breaks compatibility with Box2dLights

### ISSUE THREAD

**Issue by Trurl101** [libgdx/libgdx#4941]
Please ensure you have given all the following requested information in your report.

Libgdx1.9.7 Framebuffer breaks compatibility with Box2dLights, at least on android. Works in Desktop mode.

```
java.lang.NoSuchMethodError: No direct method <init>(Lcom/badlogic/gdx/graphics/Pixmap$Format;IIZ)V in class Lcom/badlogic/gdx/graphics/glutils/FrameBuffer; or its super classes (declaration of 'com.badlogic.gdx.graphics.glutils.FrameBuffer' appears in /data/app/xxx/base.apk)
W/System.err:     at box2dLight.LightMap.<init>(LightMap.java:120)
W/System.err:     at box2dLight.RayHandler.resizeFBO(RayHandler.java:142)
W/System.err:     at box2dLight.RayHandler.<init>(RayHandler.java:131)
```

**Comment by Tom-Ski** [comment]
Yes, there were breaking changes, so box2d lights would need an update. 
As of https://github.com/libgdx/libgdx/commit/c5fed1006b816fddf899b9e16826a4578a373114 this has been reverted for design, so it will be ok after this version.
