### ISSUE TITLE
TexturePacker and PixmapPacker should get 9-patch support

### ISSUE THREAD

**Issue by BenMcLean** [libgdx/libgdx#4942]
#### Issue details
TextureAtlas.AtlasRegion has the fields "pads" and "splits" for 9-patch information.
These fields get populated if the info is loaded from a .atlas file with the TextureAtlas (FileHandle packFile) constructor.

However, if you use TexturePacker.pack or PixmapPacker.pack to pack your TextureAtlas at runtime using the generateTextureAtlas method, this 9-patch information is lost. There's no way to give TexturePacker or PixmapPacker this information when packing.

I would suggest that there should be a version of the pack methods in TexturePacker and PixmapPacker which accepts this 9-patch info so that it comes out in the regions from generateTextureAtlas.

#### Reproduction steps/code
I wrote a sort of workaround in [this code here](https://github.com/BenMcLean/Planet-Generator/blob/dab8bfd26b4d8ed588a8e711492b6d6275189c9f/core/src/net/benmclean/utils/AtlasRepacker.java#L155-L169) which assumes the user will be packing from only one TextureAtlas and that all the names of all the textures will exactly match. However, this is an ugly hack. It would be better if TexturePacker and PixmapPacker handled this.

#### Version of LibGDX and/or relevant dependencies
All.

#### Please select the affected platforms
All platforms.

**Comment by Tom-Ski** [comment]
I've added this personally for my projects, and Is a handy feature. Ill see about making a PR for it soon.

**Comment by BenMcLean** [comment]
Looking forward to that! :)

**Comment by BenMcLean** [comment]
Anything happen with this? @Tom-Ski :)

**Comment by Tom-Ski** [comment]
Pushed support to PixmapPacker for this. TexturePacker already supports this
