### ISSUE TITLE
Box2D: World.destroyBody doesn't check if body is already destroyed

### ISSUE THREAD

**Issue by noties** [libgdx/libgdx#4943]
#### Issue details
I have noticed, that `World` object from `gdx-box2d` extention doesn't check if `Body` is already destroyed. This leads to the issue when one Body is stored in freeBodies `Pool` twice (`freeBodies.free(body);`). So, next time `createBody` is requested, the same object will be returned twice (like it's a new one). This leads for the `world.step()` to enter endless-loop (I assume).

#### Reproduction steps/code
```java
final Body body = world.createBody(bodyDef);
// ...
world.destroyBody(body);
world.destroyBody(body); // the same body

final Body body1 = world.createBody(bodyDef);
final Body body2 = world.createBody(bodyDef); // the same as `body1`
```

#### Version of LibGDX and/or relevant dependencies
Tested with `1.9.6` & `1.9.7`

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS
(most likely all, but I haven't tested on all platforms)

**Comment by Tom-Ski** [comment]
Box2D does not check if a body has already been destroyed, and it is never something you should do. LibGDX side we simply follow suite in our thin wrapper.

There are probably a lot of occasions where we could add safety checks, but I'm against these and would rather just stick to having the thinnest wrapper and delegate to the Box2D api.
