### ISSUE TITLE
Android Studio 3.0 vs libgdx 1.9.7 vs Android plugin 3.0.0

### ISSUE THREAD

**Issue by ProZhar** [libgdx/libgdx#4946]
#### Issue details
_Android Studio has just updated to version 3.0_

#### Reproduction steps/code
1. If using default gradle properties - all works:
- classpath 'com.android.tools.build:gradle:2.2.0'
- distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip
2. But if we update these settings to the recommended by the android studio 3:
- classpath 'com.android.tools.build:gradle:3.0.0'
- distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip

We'll see an error:
`Information:Gradle: Executing tasks: [:desktop:assemble, :core:assemble]`
`Information:26.10.2017 00:52 - Compilation completed with 1 error and 0 warnings in 8s 188ms`
`Error:Android Gradle Build Target: java.util.ServiceConfigurationError: com.android.ide.common.blame.parser.PatternAwareOutputParser: Provider com.squareup.sqldelight.intellij.parsing.OutputParser could not be instantiated`

3. If we run the DesktopLauncher
![111](https://user-images.githubusercontent.com/9317340/32025564-64f4bb68-b9e9-11e7-9559-aa49f3025a14.png)

 there will be the following error
#### Stacktrace
```java
java.lang.NoClassDefFoundError: com/badlogic/gdx/ApplicationListener
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.badlogic.gdx.ApplicationListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" 
Process finished with exit code 1
```

#### Version of LibGDX and/or relevant dependencies
_libgdx 1.9.7_
_gradle-4.1-all.zip_
_com.android.tools.build:gradle:3.0.0_

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
Gradle 4.0 is not supported. Please see https://github.com/libgdx/libgdx/issues/4698 for info. Its due to be resolved this autumn.

**Comment by julienvillegas** [comment]
Is there a way to use Android Studio 3.0 with LibGDX? Even if that somehow means using an older version of Gradle. As it stands, all new users who are going to try LibGDX are going to find that it does not work. I download LibGDX 1.97 (Great Release!) and upgraded Android Studio, the Android project works but not the Desktop project.
It gives:
`Error:com.android.tools.idea.gradle.util.Projects.lastGradleSyncFailed(Lcom/intellij/openapi/project/Project;)Z`

**Comment by Tom-Ski** [comment]
Even with hacking I could not get all projects to run in AS 3.0. I'd suggest to use IDEA with current libgdx versions of all plugins.

**Comment by julienvillegas** [comment]
Thanks Tom-ski, I will update the Wiki on github accordingly...

**Comment by Tom-Ski** [comment]
Where are their older versions? Are they available for download? Otherwise I'll just add a note saying its not currently supported. Alongside other warnings about the newer versions of the jetbrains based IDEs that have the same issues with Gradle 3.4+.

As for the official docs:
Its open source here https://github.com/libgdx/libgdx-site, these topics just need a little bit more oversight because of how fragile they can be and you need sight of the bigger picture, not just the tools one specific developer works with. The environment for writing docs is also much nicer there than with github wiki, for myself at least anyway. Contributions are welcome there.

**Comment by julienvillegas** [comment]
Compatible versions of Android Studio are available:

- [For Mac](https://android-studio.en.uptodown.com/mac/old)
- [For Windows](https://android-studio.en.uptodown.com/windows/old)

I tried Version 2.2 and it is working. I tried version 2.3+ and it is not.

**Comment by julienvillegas** [comment]
Actually! it seems someone found a solution here:
https://stackoverflow.com/questions/46975883/error2-0-plugin-with-id-jetty-not-found!

**Comment by Tom-Ski** [comment]
Does it work with the desktop project?

**Comment by itsabhiaryan** [comment]
I'm using Android Studio 3.0.1 with LibGDX version 1.9.7 using above hacks on Mac as well as on Windows.

Tested on Android, Desktop and Html module.

**Comment by yarnee** [comment]
It did also work for me (also on a mac).

**Comment by Leejjon** [comment]
I seem to have my game working with Android Studio 3 and gradle 4.3.1.

In the root project build.gradle in the buildscript dependencies:
`classpath 'com.android.tools.build:gradle:3.0.1' `

The build.
`android {
    buildToolsVersion "26.0.2"
    compileSdkVersion 26

    defaultConfig {
        applicationId "net.leejjon.blufpoker.android"
        minSdkVersion 24
        targetSdkVersion 26
        versionCode 19
        versionName "3.0"

        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }

        testOptions {
            // Currently have no Android specific unit tests.
            unitTests.returnDefaultValues = true
        }

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
}`

Do you guys still have issues with it?

**Comment by Tom-Ski** [comment]
This is still an issue. Dependency resolution is still broken, and make on build is also broken.  You wont see these problems running the android project, or running any gradle tasks as those are external.

**Comment by mahekmshah** [comment]
Any Update on this?

**Comment by Tom-Ski** [comment]
No :/ You can track _progress_ on the key issue here https://youtrack.jetbrains.com/issue/IDEA-122904. If you can backport Gradle in AS 3.0, then you should be OK. But afaik there are still issues with actually building the project without forcing it.
