### ISSUE TITLE
Prevent libgdx from creating DLLs in a temporary folder

### ISSUE THREAD

**Issue by qmatteoq** [libgdx/libgdx#4949]
#### Issue details
I'm helping a developer to bring his game built with libgdx to the Microsoft Store using the Desktop Bridge technology. One of the security requirements enforced by the Store and Windows 10 S is that applications aren't allowed to load code (DLLs, executables, etc.) from a folder different than the installation one. All the libraries leveraged by the application must be included in the package that is distributed on the Store.
Unfortunately, from my tests, libgdx violates this code integrity check because on Windows it generates multiple DLLs in the user's temporary folder (%LOCALAPPDATA%/Temp/libdgxtest) which are loaded at runtime by the javaw.exe executable.

Is there a way to prevent this behavior and include all the DLLs required by libgdx upfront?

Thanks!

#### Reproduction steps/code

- Start the game on Windows and notice the various DLLs that are created in the %LOCALAPPDATA%/Temp/libdgxtest location
- Package the game with the Desktop Bridge and execute it on Windows 10 S. Notice that, in the Windows log, there are multiple code integrity violations.

#### Version of LibGDX and/or relevant dependencies
Any

#### Stacktrace
This is a sample error logged on Windows 10 S:

Code Integrity determined that a process (\Device\HarddiskVolume1\Program Files\WindowsApps\xyz_1.0.0.0_x86__8x64rcfmpem5g\jre\bin\javaw.exe) attempted to load \Device\HarddiskVolume1\Users\test\AppData\Local\Temp\libgdxtest\a6a48221\gdx.dll that did not meet the Enterprise signing level requirements or violated code integrity policy.

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by xGnoSiSx** [comment]
This is strange, I'm not sure if this is java's handling of JNI Dlls or if the library is to be blamed - first time hearing this.

Regardless, the dlls are all inside the Jar that is distributed, but I guess that doesn't matter at all...

**Comment by qmatteoq** [comment]
Thanks for the update! If the library is using JNI then that's indeed the issue. All the Java apps I've worked on that had issues with the Desktop Bridge were using JNI, which generates DLL files at runtime outside the installation folder. Unfortunately, as you have correctly pointed out, the fact that they are included in the distributed JAR doesn't help. The problem, in fact, is caused by the unpacking of the DLLs outside the installation folder.

Thanks!

**Comment by xGnoSiSx** [comment]
I'm amazed that you didn't know about this. The back end libraries are interfaced with java - and they are platform specific binaries.

I would be very interested to read about how you;re gonna resolve this.

**Comment by Darkyenus** [comment]
It shouldn't be that hard to fix this. If you know what platform you are on, it should be enough to [disable loading of natives](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/GdxNativesLoader.java#L22) and load respective libraries yourself (see related classes on how to do that).

**Comment by Tom-Ski** [comment]
See @Darkyenus's comment.

**Comment by xGnoSiSx** [comment]
Sorry, but what's the impact if the natives are not loaded?

I would assume horrible performace or even crashes?

**Comment by Tom-Ski** [comment]
You won't be able to use anything bar java only classes.

**Comment by xGnoSiSx** [comment]
That would mena no OpenGL?

**Comment by Darkyenus** [comment]
No OpenGL or other native APIs, no app window (therefore no application loop, unless headless backend is used), IIRC no Matrix multiplication...

It isn't that hard to load them, most of the code in the classes I linked is about determining which natives to load, extracting natives from jars, storing them somewhere and then [one line to actually load them](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/SharedLibraryLoader.java#L327).

So the only thing that you have to do is to unpack correct natives somewhere near your assets during development (I know nothing about packaging for windows, the only requirement is, that you have to be able to access the lib as a standard file) and then at runtime, before anything libGDX-related in your `main()`, call `System.load(String)` for each native library, with a path to that library file.
And maybe you will have to determine if you want to load 32bit or 64bit versions, if they are not universal.

**Comment by xGnoSiSx** [comment]
@Darkyenus 

With respect to the OPs issue, this is still a security concern under the Microsoft app store... so no :P

**Comment by Tom-Ski** [comment]
Not if the problem is the directory that the natives are being loaded from.

**Comment by xGnoSiSx** [comment]
@Tom-Ski 
yes but when a non admin user is running the executable, it needs special permissions to be able to modfy the install folder. Even if the app were to create the dll on the user's space, that's still not allowed sice it's executable code.

**Comment by Tom-Ski** [comment]
There is no need to do that at runtime. It should be either part of an installation process or it should already be ready to run from the installation direction.
