### ISSUE TITLE
Move the asset folder in to the  root of the Project

### ISSUE THREAD

**Issue by mustii82** [libgdx/libgdx#4955]
since all Modules uses the same assets folder. It would be better to put the asset folder into the root of the Project. This will even solve the run DesktopLauncher which where you must set the android asset folder as the working environment.

#### Please select the affected platforms
- [ x] Android
- [x ] iOS (robovm)
- [x ] iOS (MOE)
- [x ] HTML/GWT
- [x ] Windows
- [ x] Linux
- [x ] MacOS

**Comment by NathanSweet** [comment]
AFAIK, Android requires the assets folder to be in that location, so everyone can suffer. I'll let someone who actually uses the nasty Android SDK close this, if still true.

**Comment by MobiDevelop** [comment]
I believe that it was the Android tooling in eclipse that requires it to be there, with Gradle it should be possible to put it anywhere but I've not tried it.

**Comment by Tom-Ski** [comment]
When we upgrade to 4.0 ill take a look at all the IDEs again and see if this is still and issue.

**Comment by Mickey248** [comment]
is a very good thing

**Comment by mustii82** [comment]
Grade can Handle that I saw LibGDX Projects which had the asset folder at the root and not on the android root anymore.

**Comment by Tom-Ski** [comment]
Gradle has always been able to. The problem was with IDE integrations that couldn't.

**Comment by mustii82** [comment]
We can test it when we update to Support Grade 4.0 and change it too if its working

**Comment by jojorabbit** [comment]
Hi,
if you really want to add it to project directly you have to set up assets.srcDirs in build.gradle for android subproject something like the following

```
sourceSets {
    main {
      manifest.srcFile 'AndroidManifest.xml'
      java.srcDirs = ['src/main/java']
      aidl.srcDirs = ['src/main/java']
      renderscript.srcDirs = ['src/main/java']
      res.srcDirs = ['res']
      assets.srcDirs = ['../assets'] // assets dir is at same level as core, no need to setup working directory in IntelliJ
      jniLibs.srcDirs = ['libs']
    }
```
Keep in mind that am not using latest gradle and i have not tested it with eclipse.
Hope it helps.

**Comment by MrStahlfelge** [comment]
@tommyettinger can you elaborate here how you managed to get this working for liftoff and if it is applicable for all users to change this?

**Comment by tommyettinger** [comment]
> @tommyettinger can you elaborate here how you managed to get this working for liftoff and if it is applicable for all users to change this?

Oops, I didn't see the mention for... almost a year...

I actually didn't do anything for Liftoff, it was already working in czyzby's gdx-setup, which I forked. I haven't heard of any issues with the root-level `assets/` other than IDEA complaining about duplicate asset roots (it builds and runs fine despite its complaining, and Gradle tasks also work without issue). I can't actually recall a time when the root-level `assets` was an issue, while I've been using libGDX... It seemed like a past-problem when I started being more active, but the awkward fix for the issue (which seems to be no longer an issue) has been around in gdx-setup for many years now. As discussed in #6612 , using root-level `assets` would make gdx-setup and gdx-liftoff act like each other, which makes providing help to users easier.

**Comment by Frosty-J** [comment]
> I haven't heard of any issues with the root-level assets/ other than IDEA complaining about duplicate asset roots (it builds and runs fine despite its complaining, and Gradle tasks also work without issue).

No surprises here, but Android Studio also complains when using `/assets/` or `/core/assets/` instead of `/android/assets/`. I'd rather not have people seeing scary messages after creating their very first libGDX project. Is there no solution?

> Duplicate content roots detected: Path [/home/james/libgdx-assets/test/assets] of module [test.android] was removed from modules [test.desktop]

**Comment by tommyettinger** [comment]
The "solution" is to have only one module. The whole idea with a shared assets folder is to share content between projects to avoid duplicating it, which apparently IDEA (and only that family of IDEs) takes exception to. Gradle doesn't give any warnings about this; it's purely a fault in IDEA. I also think that if people wet themselves after seeing a not-even-warning-level message, they probably aren't cut out for programming.

**Comment by raeleus** [comment]
I get the duplicate content roots messages even before this PR. I've learned to ignore them.
