### ISSUE TITLE
How to realize the waterRipples effect on the latest version？

### ISSUE THREAD

**Issue by xingchenfengn** [libgdx/libgdx#4956]
#### Issue details
As the title,I can realize waterRipples effect on The Old version,but How to realize the waterRipples effect on the latest version？Thanks in advance

#### Version of LibGDX and/or relevant dependencies
1.9.7

#### Please select the affected platforms
- [ ] Android

**Comment by Tom-Ski** [comment]
Please use the forum or the irc channel for these sorts of questions.

https://libgdx.badlogicgames.com/documentation/help/Community%20Help.html
