### ISSUE TITLE
Gradle bug in version libgdx downloads.

### ISSUE THREAD

**Issue by isubasinghe** [libgdx/libgdx#4957]
#### Issue details
Gradle has a bug in the version libgdx downloaded, this is fixed in gradle version 4.3.
See https://discuss.gradle.org/t/could-not-determine-java-version-from-9-0-1/24457, libgdx downloads gradle 

#### Reproduction steps/code
Details of environment:
JAVA VERSION: 9.0.1

1. Download libgdx.
2. Setup a project

#### Version of LibGDX and/or relevant dependencies
Latest on website at 2/11/2017 (dd-mm-yyyy), was not able to find version, an about section would be useful on the libgdx setup ui.

#### Error
"
Generating app in D:\Documents\Projects\sd
Executing 'D:\Documents\Projects\sd/gradlew.bat clean --no-daemon'

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '9.0.1'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Done!
To import in Eclipse: File -> Import -> Gradle -> Gradle Project
To import to Intellij IDEA: File -> Open -> build.gradle
To import to NetBeans: File -> Open Project...

"

#### Affected platforms
- [ ] Android 
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS
Note: only tested on windows.

**Comment by Tom-Ski** [comment]
This will be resolved when we can upgrade. see https://github.com/libgdx/libgdx/issues/4698
