### ISSUE TITLE
libgdx + Google ARCore integration

### ISSUE THREAD

**Issue by Ketsuko** [libgdx/libgdx#4958]
Hello everyone,

I'm working a little bit on the OpenGL SDK of Google ARCore, and was wondering, do you have any examples of integration of ARCore with the libgdx engine? I've seen there are many example of Google Tango + ARcore, but not for libgdx...

Thank you for your help!

**Comment by claywilkinson** [comment]
I shared out my project which integrates ARCore into LibGDX:  https://github.com/google/helloargdx.
