### ISSUE TITLE
Support iPhoneX screen size

### ISSUE THREAD

**Issue by dungnart** [libgdx/libgdx#4965]
Please ensure you have given all the following requested information in your report.

#### Issue details
The game screen size is smaller than device screen size. I believe that we have to modify `final boolean didFinishLaunching (UIApplication uiApp, UIApplicationLaunchOptions options) {..}` method in`IOSApplication.java` class to fix this error.

#### Reproduction steps/code
_Even if you think your issue is trivial to reproduce, please supply a [SSCCE](http://sscce.org/) that demonstrates your issue.  This saves time on our end, and makes it much more likely that your issue will be fixed.
You can find barebones templates [here](https://github.com/libgdx/libgdx/wiki/Getting-help)_

#### Version of LibGDX and/or relevant dependencies
_Please provide the version(s) affected._
1.9.7
ROBOVM 2.3.4 SNAPSHOT

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```
![image](https://user-images.githubusercontent.com/9654516/32414295-330edd02-c256-11e7-8abb-ed483bce5dec.png)
![image](https://user-images.githubusercontent.com/9654516/32414312-73eb379e-c256-11e7-844f-240baa47935b.png)

#### Please select the affected platforms
- [ ] Android
- [ x] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Leejjon** [comment]
MOE has the same, I made a ticket on their forums:
https://discuss.multi-os-engine.org/t/warning-when-running-libgdx-with-moe-1-4-0-on-iphone-x-simulator/1247

**Comment by Tom-Ski** [comment]
Yup, we just need to add the correct launch image to both. Will do so later today.

**Comment by Leejjon** [comment]
Alright, I'll help testing the MOE side in my app when you have added it.
