### ISSUE TITLE
Include progress bar for download in project setup

### ISSUE THREAD

**Issue by PawkyPenguin** [libgdx/libgdx#4967]
Currently the interface does not show a proper progress bar when it is downloading dependencies during the initial project setup. Although the output shows some dots when the file(s) is/are downloading, there is no way to tell when the downloading is finished. Sometimes, there is no indication of progress at all, leaving you wondering whether the Download is finished or the application is hanging (or both).

The following picture shows the issue; notice that there is no way to indicate progress:
![image](https://user-images.githubusercontent.com/18655912/32457528-bb634214-c329-11e7-854d-c6a36d4fb30a.png)

## Steps to reproduce
Download the `gdx-setup.jar` file, then enter some settings for a new project and click "Generate" to start generation of the project. From that point on, there are only very few progress bars that indicate liveness of the application.

## Remedy
Add progress bar for downloads (that show percentage).

**Comment by Tom-Ski** [comment]
Currently not possible! I will prevent this from happening on launch though as it isn't really required.
