### ISSUE TITLE
Game Controller issues on GWT and Chrome

### ISSUE THREAD

**Issue by MrStahlfelge** [libgdx/libgdx#4982]
I am experiencing the following issues on GWT, latest snapshot and on Chrome. **Firefox is working fine.**

#### Issue details
Chrome handles game controllers a bit different than Firefox. Game Controllers are hidden to sites until a button is pressed, then all connected controllers are shown. Also, Chrome always updates the timestamps on the controllers, even if no interaction was done.

It is very helpful to reproduce these different behaviours on www.html5gamepad.com because this is probably causing the game controller problems on Chrome.

#### Reproduction steps/code
1. Open Chrome, don't press any button on the game controller
2. Start the libgdx game with controller support
3. Press a button. The connect method fires for the controllers (good), but the button used for unhiding the controllers to the game is "hanging" (this is a problem). A solution is to reload the game. Then controllers work as intended.
4. Furthermore, if the user has more than one controller connected and changes the tab on Chrome and then returns to the game, some controllers are doubled in the list of connected controllers and connect method fires. These doubled controllers do not react on events any more. This is not solvable with reloading, Chrome has to be restarted.

#### Version of LibGDX and/or relevant dependencies
gdx-controllers-1.98-SNAPSHOT

#### Please select the affected platforms
- [X] HTML/GWT on Chrome (Windows)

**Comment by MrStahlfelge** [comment]
Cause of 4 is that indeed Chrome is raising "gamepadconnected" event and therefore `handleGamepadConnect` is called. So GwtController.java's event queue trusts the incoming event and adds the not-new controller to the array without checking if this controller is already in the list.

**Comment by bryanwagner** [comment]
+1 for this issue. This has been a problem for me for a while.

**Comment by MrStahlfelge** [comment]
Update: Issue exists on Linux, too. 
Chrome's behaviour changed in the meanwhile: #4 is not a problem anymore, and the always-updating timestamp problem is fixed, too. However, gdx-controllers-gwt does still not work on Chrome. I was able to track down the problem and will provide a fix.
