### ISSUE TITLE
Couldn't set size for font

### ISSUE THREAD

**Issue by dotw** [libgdx/libgdx#4983]
Please ensure you have given all the following requested information in your report.

#### Issue details
app crashed

#### Reproduction steps/code
```java
FreeTypeFontGenerator freeTypeFontGenerator = new FreeTypeFontGenerator(GlobalSettings.getInstance().getSangoGame()
					.getPlatformManager().getFontFile("msyhbd.ttf"));
			FreeTypeFontParameter param = new FreeTypeFontParameter();
			param.incremental = true;
			param.size = fontSize;
			BitmapFont defaultFont = freeTypeFontGenerator.generateFont(param);
			freeTypeFontGenerator.dispose();
			defaultFont.getData().markupEnabled = true;
                        skin = new Skin();
			skin.addRegions(new TextureAtlas(Gdx.files.internal("data/skin/uiskin.atlas")));
			skin.add("default-font", defaultFont, BitmapFont.class);
			skin.load(Gdx.files.internal("data/skin/uiskin.json"));
```
and later when I use
```java
Table tbl = new Table(skin);
tbl.add("中文")  ---crashed here with Chinese chars
```
#### Version of LibGDX and/or relevant dependencies
gdx 1.9.7
#### Stacktrace
It's strange there is no stacktrace in logcat but I debugged it's broken with FreeTypeFontGenerator#setPixelSizes method with "Couldn't set size for font"

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

#### FreeTypeFontGenerator says:
```java
/** Generates {@link BitmapFont} and {@link BitmapFontData} instances from TrueType, OTF, and other FreeType supported fonts.
 * </p>
 * 
 * Usage example:
 * 
 * <pre>
 * FreeTypeFontGenerator gen = new FreeTypeFontGenerator(Gdx.files.internal(&quot;myfont.ttf&quot;));
 * BitmapFont font = gen.generateFont(16);
 * gen.dispose();
 * </pre>
 * 
 * The generator has to be disposed once it is no longer used. The returned {@link BitmapFont} instances are managed by the user
 * and have to be disposed as usual.
 * 
 * @author mzechner
 * @author Nathan Sweet
 * @author Rob Rendell */
```
But this is not right, it seems BitMappFont stills using the generator after generateFont().

**Comment by intrigus** [comment]
First, this lacks an reproduction case. Your code is not sufficient. I would guess that your font probably doesn't contain those chars.

**Comment by dotw** [comment]
Actually, it has. The code works if I remove the dispose methods.

**Comment by Tom-Ski** [comment]
Please provide all required info for the sample code to be reproducible. This means any fonts that you are using, as well as providing fully compilable self contained example code.

**Comment by NathanSweet** [comment]
FreeTypeAtlasTest shows it works when the font is disposed. If you are doing incremental glyph generation then you must not dispose the FreeTypeFontGenerator. I'll add that to the javadocs and close this issue. If you still have a problem, please post an SSCCE to this issue and we can reopen it.
