### ISSUE TITLE
FreeTypeFont issue, Korean language

### ISSUE THREAD

**Issue by mariamKh** [libgdx/libgdx#4984]
Hi,

I'm implementing Korean version of our LibGDX game, and for this purpose I've imported GodoM.otf font in it. On Desktop version fonts display well, but on Android some letters somehow disappear.
Here is the code for font loading:

public void loadFonts (AssetManager assetManager, Array<FontSizePair> fontsToLoad) {
        LocaleFontLoader.LocaleFontLoaderParameter parameter = new LocaleFontLoader.LocaleFontLoaderParameter();

        parameter.fontSizePairsToLoad.addAll(fontsToLoad);

        for (FontSizePair pair : fontsToLoad) {
            FreeTypeFontGenerator.FreeTypeFontParameter param = new FreeTypeFontGenerator.FreeTypeFontParameter();
            param.incremental = true;
            param.size = sizeMap.get(pair.fontSize+"");
            param.minFilter = Texture.TextureFilter.Linear;
            param.magFilter = Texture.TextureFilter.Linear;

            FreeTypeFontGenerator.FreeTypeBitmapFontData data = new FreeTypeFontGenerator.FreeTypeBitmapFontData() {
                public int getWrapIndex (Array<BitmapFont.Glyph> glyphs, int start) {
                    return SimplifiedKoreanData.getWrapIndex(glyphs, start);
                }
            };

            parameter.freetypeParams.put(pair, param);
            parameter.freetypeDatas.put(pair, data);
        }

        parameter.fontPath = "fonts/android_mid/" + ttfPath;
        parameter.freetype = true;

        assetManager.load("data.localefont", GameResourceManager.FontPairWrapper.class, parameter);

    }

The screenshots to compare view on Android (with missing letters) and on Desktop are attached below:

![20171115_164608-collage](https://user-images.githubusercontent.com/11209829/32836880-bfa5cff2-ca24-11e7-86ef-48e347359661.jpg)
![20171115_164720-collage](https://user-images.githubusercontent.com/11209829/32836881-bfc6e390-ca24-11e7-9045-ae6b9f42a78a.jpg)

And this is the font file, just in case:

[GodoM.otf.zip](https://github.com/libgdx/libgdx/files/1474721/GodoM.otf.zip)

LibGDX version is: 1.9.6

**Comment by Tom-Ski** [comment]
As discussed, we need an example that compiles to test this.
