### ISSUE TITLE
There is no way to get the state of the particles in particle effects.

### ISSUE THREAD

**Issue by chhabraharsh** [libgdx/libgdx#4987]
#### Issue details
We want to store the state of each particle w.r.t time to replay the same effect later, but there is no way to access the particles in particle emitter.

Do let me know if there is a workaround to save/record the particle effect w.r.t.

**Comment by xGnoSiSx** [comment]
Not really sure what you're tryin to do. if you whant an effect to be replayer you just spawn it again.

If you're trying to record a scene, record the event triggers for the particle effects instead and replay those.
