### ISSUE TITLE
Singleton FreetypeFont between Android Activities.

### ISSUE THREAD

**Issue by Tokenyet** [libgdx/libgdx#4988]
#### Issue details
Font Generation is the slowest problem in my app, so I decide to generate it once in Static Singleton for different activity. The first time to launch Libgdx Activity was good, but when I jump to another activity and back, the words were broken.

![image](https://user-images.githubusercontent.com/6420527/32982218-be9b8252-ccbb-11e7-8081-154ad5ffc433.png)

#### Reproduction steps/code
	public final class FontManager {
		private Map<Integer, BitmapFont> fontMap;
		private FreeTypeFontGenerator freeTypeFontGenerator;
		private static FontManager fontManager;
		private FileHandle fileHandle;
		private FontManager() {
			fontMap = new HashMap<Integer, BitmapFont>();
			fileHandle = Gdx.files.internal("Fonts/DroidSansFallbackFull.ttf");
			freeTypeFontGenerator = new FreeTypeFontGenerator(fileHandle);
		}

		public boolean isExist(int size) {
			return fontMap.containsKey(size);
		}

		public void add(int size) {
			FreeTypeFontGenerator.FreeTypeFontParameter parameter = new FreeTypeFontGenerator.FreeTypeFontParameter();
			parameter.size = size;
			parameter.incremental = true;
			fontMap.put(size, freeTypeFontGenerator.generateFont(parameter));
		}

		public BitmapFont get(int size) {
			BitmapFont originFont = fontMap.get(size);
			return new BitmapFont(originFont.getData(), originFont.getRegions(), true);
		}

		public static FontManager getInstance() {
			if(fontManager == null)
				fontManager = new FontManager();
			return fontManager;
		}
	}

I think the problem is `new BitmapFont(originFont.getData(), originFont.getRegions(), true);`.
The `FreeTypeFontData`  or `Array<TextureRegion>` is not the same after Libgdx activity dispose, but I could not find any way to slove this :(

This is the Singleton I used.
#### Version of LibGDX 
1.9.6

#### Please select the affected platforms
- [O ] Android

**Comment by Tom-Ski** [comment]
You need to reinitialize any static variables on relaunch. Statics persist past your activity, so on relaunch they still have the old (wrong) values.
