### ISSUE TITLE
LibGDX Project Generator Build Failed

### ISSUE THREAD

**Issue by malaiemil14** [libgdx/libgdx#4990]
Please ensure you have given all the following requested information in your report.

#### Issue details
When I want to create a new project using the LibGDX Project Generator I get the BUILD FAILED message at the end of the log. But my project is still created. 

I can open it in Android Studio and run it (the app with the red background and the BadLogic logo), but one issue that I encountered is when I want to create a TextureAtlas for a Button. I pass Gdx.files.internal("ui/button.pack") as an argument for the TextureAtlas constructor and I get a "ui/button.pack" - File not found error.

Maybe someone knows why I get that BUILD FAILED error. Also, I provided the whole log down below.

#### Reproduction steps/code
Generating app in C:\Users\Emil\Desktop\test Executing 'C:\Users\Emil\Desktop\test/gradlew.bat clean --no-daemon idea' WARNING: An illegal reflective access operation has occurred WARNING: Illegal reflective access by org.gradle.internal.reflect.JavaMethod (file:/C:/Users/Emil/.gradle/wrapper/dists/gradle-2.14.1-bin/2r579t5wehc7ew5kc8vfqezww/gradle-2.14.1/lib/gradle-base-services-2.14.1.jar) to method java.lang.ClassLoader.getPackages() WARNING: Please consider reporting this to the maintainers of org.gradle.internal.reflect.JavaMethod WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations WARNING: All illegal access operations will be denied in a future release To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html. Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

Where: Build file 'C:\Users\Emil\Desktop\test\build.gradle' line: 53
What went wrong: A problem occurred evaluating root project 'test'.
javax/xml/bind/annotation/XmlSchema
Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED

Total time: 6.274 secs Done! To import in Eclipse: File -> Import -> General -> Existing Projects into Workspace To import to Intellij IDEA: File -> Open -> YourProject.ipr

#### Version of LibGDX and/or relevant dependencies
LibGDX 1.9.6 (Not sure tho)
Java 9
Android Studio with SDK for Android version 4.0 and 4.4w

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [*] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [*] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
The error you posted is unrelated to your problem, and caused by running java 9 with the current build scripts.

Your issue with TextureAtlas is not a bug, and most likely just a fault in your code.  Please join the irc channel or post a message on the forums for help on that topic.
