### ISSUE TITLE
IsometricTiledMapRenderer Performance Issues

### ISSUE THREAD

**Issue by wdavies973** [libgdx/libgdx#4991]
Please ensure you have given all the following requested information in your report.

#### Issue details
I'm using IsometricTiledMapRenderer to render a TiledMap from the Tiled Map editor. The renderer suffers extreme lagging when panning when the map is zoomed out. The renderer can only handle
about one unique tile, 30 x 30 tiles (128 by 64 pixels) causes it to lag. It seems like it shouldn't be lagging for this low amount of tiles. I've seen a rewrite for the Orthogonal version that's much much faster, but doesn't work for Isometric: https://gist.github.com/MobiDevelop/04a879ac125d7fa16035. This could be translated to isometric as a potential solution.

It also appears that the issue only occurs when using individual tile images instead of 1 tile set image.

#### Reproduction steps/code
Code: https://pastebin.com/VtgigMTs

#### Version of LibGDX and/or relevant dependencies
Gradle file: https://pastebin.com/XtsN1pEX

#### Stacktrace
N/A

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] HTML/GWT
- [ ] iOS (MOE)
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
Please provide full resources required to run your example. By the sounds of it you are using individual textures for each tile, which would be 900 draw calls worst case scenario. You should definitely be using an atlas.

Please reopen when all assets/code is supplied so we can test.
