### ISSUE TITLE
Robovm + Admob

### ISSUE THREAD

**Issue by Danbardo** [libgdx/libgdx#4993]
#### Issue details
Google is turned off all ads for SDK's lower than version 7.0.0.

I made some apps with libgdx a few years ago, and was hoping to update the version of Admob on them to avoid losing ad revenue.

I noticed that the Admob binding for iOS in this repository are below 7.0.0.

Will there be any updates to the bindings or is the best thing to do migrate to MultiOS?

- [x] iOS (robovm)

**Comment by Tom-Ski** [comment]
There is no admob binding in this repository. The latest bindings that MobiVM has is at version 7.11.0.
See https://github.com/MobiVM/robovm-robopods for bindings.

**Comment by Danbardo** [comment]
Thanks heaps Tom!

In case you were wondering what I was talking about:
https://github.com/libgdx/libgdx/wiki/Admob-in-libgdx#ios-setup-robovm

I worded it poorly, but I meant the bindings mentioned on that page.

**Comment by Tom-Ski** [comment]
Ah I see. Yes, that is very out of date! Give the ones I linked a go, and if they work perhaps also update the wiki 👍
