### ISSUE TITLE
Multiple font size loads in AssetManager

### ISSUE THREAD

**Issue by RotcivOcnarb** [libgdx/libgdx#4994]
#### Issue details
I want to load in the AssetManager the same font, but with different sizes

#### Reproduction steps/code
`FreeTypeFontLoaderParameter mySmallFont = new FreeTypeFontLoaderParameter();`
`mySmallFont.fontFileName = "fonts/olivers barney.ttf";`
`mySmallFont.fontParameters.size = 23;`
`assets.load("fonts/olivers barney.ttf", BitmapFont.class, mySmallFont);`

`FreeTypeFontLoaderParameter myBigFont = new FreeTypeFontLoaderParameter();`
`myBigFont.fontFileName = "fonts/olivers barney.ttf";`
`myBigFont.fontParameters.size = 48;`
`assets.load("fonts/olivers barney.ttf", BitmapFont.class, myBigFont);`

#### Version of LibGDX and/or relevant dependencies
1.9.6

#### Stacktrace
No stack traces, it just uses the first font loaded in the AssetManager when i use
 `assets.get("fonts/olivers barney.ttf", BitmapFont.class);` (in that case, the size 23 font)

#### Please select the affected platforms
- [x] Android
- [X] iOS (robovm)
- [X] iOS (MOE)
- [X] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by Tom-Ski** [comment]
The name you provide in `assets.load("bigfont.ttf", BitmapFont.class, bigfontParam)` is what you use to distinguish the different sizes.
