### ISSUE TITLE
[Suggestion] Uniform groups for Scene2D table cells?

### ISSUE THREAD

**Issue by draco123456ftw** [libgdx/libgdx#4995]
Currently every cell in a table have the ability to be sized the same as the maximum sized cell in the table using the uniform(), uniformX(), and uniformY() methods.

In a particular instance I have a table full of labels and buttons. I want the table to look aligned properly.

(ASCII table visualisation. H = header labels, S = side labels, B = buttons)
```
  | H | H | H | H
S | B | B | B | B
S | B | B | B | B
S | B | B | B | B
```

The main problem right now is, If i use both uniformX() and uniformY() on the side labels, then they are the same size as a button and they look unnecessarily long. If I use only uniformY() on the side labels, then if the side labels have different lengths of text they will be sized differently. 

I want them all to be uniform sized, but for the side labels I wanted a different uniform width than the buttons while keeping the same uniform height size of the buttons to keep them aligned.

I am unsure about how to achieve this using the current Scene2D cell space manipulation methods without resorting to ugly setSize() methods. I guess I can make the top row work by putting the row of labels in a new table with uniform() and insert it with a colspan, but I cant make the same work for the side labels.

Is it possible to have groups of uniforms, so that the cells would be sized to the largest cell in the group? I can suggest implementing this by having an optional uniform(String) method where the String would be the group name, and the uniform would correspond to the largest sized cell of the group rather than the entire table.

**Comment by xGnoSiSx** [comment]
Not sure if this counts as a solution or if it's feasible at all.

Have you considered having nested tables? The side labels could be one table nester in parent table that also holds the other stuff in its cells.

**Comment by draco123456ftw** [comment]
If i have nested tables then there's no certainty that the cells would be uniform size across all the nested tables, only to the cells contained in each separate table. It is a concern since my buttons are actually TextButtons with different lengths of text as well.

I mean I pretty much already know how to force solve this already with some sort of sizing hack using the inbuilt Scene2D's Value class, looping through all the relevant cells and forcing a strict size, but i just thought Scene2D could have some more of an elegant in-built solution since it's so long winded.

**Comment by NathanSweet** [comment]
A table already ensures each row is the same height and each column is the same width. It sounds like using `fill` would meet your needs.

**Comment by draco123456ftw** [comment]
Oh, I actually didn't realise about that. Sorry!

**Comment by NathanSweet** [comment]
No worries. Note once you fill the cell with the actor, the cell's alignment isn't very useful. For Label, you can set alignment on the label directly.
