### ISSUE TITLE
Feature request: FrameBuffer multisampling

### ISSUE THREAD

**Issue by AmazingThew** [libgdx/libgdx#4997]
Currently, it is possible to enable multisample antialiasing at startup via `Lwjgl3ApplicationConfiguration.setBackBufferConfig()`, but this applies only to the main backbuffer and not to any FrameBuffers subsequently created at runtime.

Being able to use MSAA with FrameBuffers would be a huge help for rendering high-quality visuals.

The last time this came up was [a pull request](https://github.com/libgdx/libgdx/pull/1971) several years ago, which was rejected due to lack of cross-platform support. Since then OpenGL ES 3.0, which supports multisampled framebuffers, has gained fairly widespread adoption on mobile, libGDX has added ES 3.0 support, and libGDX's FrameBuffers have received a significant refactor.

Could adding MSAA support to FrameBuffers be revisited, given these developments?

**Comment by Tom-Ski** [comment]
Looks like its only in GLES 3.1. Not 3.0.

**Comment by tarslangil** [comment]
Any updates on this?

**Comment by pkruczynski** [comment]
Bump

**Comment by yuripourre** [comment]
Bump

**Comment by kunterbunt2** [comment]
bump

**Comment by MikOfClassX** [comment]
Bump Bump Bump.. knock Knock .. 2023 has come

**Comment by MikOfClassX** [comment]
> 

having that in mind, it is easy to add a condition in the code : want MSAA but using GLES3.0 ? no MSAA in your FBO, else OK
i.e. pass a "samples" in the FBO constructor and use them just in case the impl allows it. Fallback to no MSAA
Yep, kick me, you already know the how-to much better than me.. ;)

**Comment by MikOfClassX** [comment]
> Looks like its only in GLES 3.1. Not 3.0.

having that in mind, it is easy to add a condition in the code : want MSAA but using GLES3.0 ? no MSAA in your FBO, else OK
i.e. pass a "samples" in the FBO constructor and use them just in case the impl allows it. Fallback to no MSAA
Yep, kick me, you already know the how-to much better than me.. ;)

**Comment by mgsx-dev** [comment]
Indeed, it requires GLES 3.1. So when we get #6945 merged, we could implement MSAA FBO. First things first.

**Comment by MikOfClassX** [comment]
@mgsx-dev it seems it's all already there. Did you schedule the merging ?

**Comment by MikOfClassX** [comment]
@mgsx-dev Well, it seems it's not conflicting at all and... "Approval not required". That's a sign :)
