### ISSUE TITLE
Accessing attributes from BufferBuilder and FrameBufferTextureAttachmentSpec

### ISSUE THREAD

**Issue by christian1993** [libgdx/libgdx#5003]
We created a subclass of ```FrameBuffer``` and want to overwrite:
```java
protected Texture createTexture (FrameBufferTextureAttachmentSpec attachmentSpec) 
```

Since our class is not in the same package as ```FrameBufferTextureAttachmentSpec``` and ```BufferBuilder```, we cannot access the attributes needed to create our custom texture (width, height, format). Public getter methods would help us to access these protected attributes.

We're using libgdx V. 1.9.8-Snapshot on Android and Windows.

Thanks in advance,
Christian

**Comment by Tom-Ski** [comment]
Can you provide an example for what it is you are trying to do by extending?

**Comment by christian1993** [comment]
We need to get a pixmap from the framebuffer object and keep the resulting texture after disposing the framebuffer.
But meantime we found out, that there is no need to overwrite the ```createTexture(..)``` function anymore. Maybe caused by updating to V. 1.9.8-Snapshot. So extracting the texture works fine now.

Christian
