### ISSUE TITLE
NPE in FreeTypeFontGenerator for incremental font with a shared pixmap packer (with fix)

### ISSUE THREAD

**Issue by vbousquet** [libgdx/libgdx#5008]
#### Issue details
Due to the data.regions field not being initialized, an NPE will be thrown for incremental font with a shared pixmap packer : 
https://github.com/libgdx/libgdx/blob/bc864a01de2e9ff37ce958ace597e31f944dd39a/extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator.java#L646

Initialization is performed here for these situations : 
https://github.com/libgdx/libgdx/blob/bc864a01de2e9ff37ce958ace597e31f944dd39a/extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator.java#L183

The problem is that this is preceed by a call to generateData which in turns calls getGlyph which needs data.regions to be initialized.
https://github.com/libgdx/libgdx/blob/bc864a01de2e9ff37ce958ace597e31f944dd39a/extensions/gdx-freetype/src/com/badlogic/gdx/graphics/g2d/freetype/FreeTypeFontGenerator.java#L475

So I see 3 solutions to solve this issue ;
- either perform the region initialization before calling 

>         if (data.regions == null && parameter.packer != null) data.regions = new Array();

- simply perform a default initialization in FreeTypeBitmapFontData (line 646)

>         Array<TextureRegion> regions = new Array<>();

- don't call getGlyph for space in generateData if we don't have regions initialized 

>         BitmapFont.Glyph spaceGlyph = data.regions != null ? data.getGlyph(' ') : null;

All the 3 works (I did test them). My preference goes to the third.

I can prepare a PR if you need. Just select the prefered fix or correct me if I missed something !

#### Reproduction steps/code
```java
         int texSize = 2048;
        PixmapPacker.PackStrategy packStrategy = new PixmapPacker.GuillotineStrategy();
        PixmapPacker packer = new PixmapPacker(texSize, texSize, Pixmap.Format.RGBA8888, 1, false, packStrategy);
        packer.setTransparentColor(Color.WHITE);
        packer.getTransparentColor().a = 0;
        FreeTypeFontGenerator generator = new FreeTypeFontGenerator(Gdx.files.internal("graphics/NotoSans-Regular.ttf"));
        FreeTypeFontGenerator.FreeTypeFontParameter param = new FreeTypeFontGenerator.FreeTypeFontParameter();
        param.incremental = true;
        param.size = 20;
        param.characters = "Y\u0000";
        param.packer = packer;
        FreeTypeFontGenerator.FreeTypeBitmapFontData data = new FreeTypeFontGenerator.FreeTypeBitmapFontData();
        BitmapFont font = generator.generateFont(param, data);
```

#### Version of LibGDX and/or relevant dependencies
1.9.7

#### Stacktrace
```java
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at org.softmotion.flibrary.FreeTypeFontGenerator$FreeTypeBitmapFontData.getGlyph(FreeTypeFontGenerator.java:654)
	at org.softmotion.flibrary.FreeTypeFontGenerator.generateData(FreeTypeFontGenerator.java:464)
	at org.softmotion.flibrary.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:170)
	at org.softmotion.flibrary.FLibrary.create(FLibrary.java:160)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

#### Please select the affected platforms
- [X] Android
- [X] iOS (robovm)
- [X] iOS (MOE)
- [X] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS
All platforms should be affected. I did only test on Windows.

Edit : added issue template (sorry, my last contribution is quite old)

**Comment by NathanSweet** [comment]
Thanks for the detailed bug report! Not having initialized `regions` is used to know if this is the first time the FreeTypeBitmapFontData is used. We want to use `data.getGlyph(' ')` if possible so the font's space size is used.
