### ISSUE TITLE
Jvm Assimp port, looking for synergy

### ISSUE THREAD

**Issue by elect86** [libgdx/libgdx#5011]
Hi, 

we are working at the jvm port of Assimp [here](https://github.com/kotlin-graphics/assimp)

At the moment we support the following: 
- exporter: assxml (ogrexml in progress)
- importer: assbin, stl, obj, ply, collada, md2, md3, md5 (fbx in progress)

I believe a full powerful importing jvm library on par of the original would be greatly useful for the jvm world, and especially for libgdx.

That's why I'm looking for some possible collaborations with the libgdx. 

I quickly chatted with Mario and he suggested me to speak with @xoppa 

My main goal is to catalyze attention and efforts (in porting code and finding bugs).

Is there any possibility in this regard? :)

**Comment by elect86** [comment]
binary fbx complete

**Comment by elect86** [comment]
and also ascii fbx

**Comment by shatterblast** [comment]
I would like to pick this up in the future.  It would be interesting to integrate it into LibGDX.

**Comment by elect86** [comment]
nice, I'll send you an invitation!

**Comment by shatterblast** [comment]
It may be a while before I can substantially contribute.  I definitely want to see this work.

**Comment by elect86** [comment]
Don't worry, any contribution is valuable. 

Moreover, I can support/guide you

**Comment by crykn** [comment]
Nice project you got there, elect86! Judging by the lack of responses in the last three years, there weren't many ideas for synergies. If you're still interested and have some concrete ideas, our [official discord](https://discord.gg/6pgDK9F) would be a better place to discuss this.

**Comment by elect86** [comment]
Yep, pity, I'll give a try over there sooner or later, thanks for the tip

**Comment by Duna** [comment]
> Hi,
> 
> we are working at the jvm port of Assimp [here](https://github.com/kotlin-graphics/assimp)
> 
> At the moment we support the following:
> 
> * exporter: assxml (ogrexml in progress)
> * importer: assbin, stl, obj, ply, collada, md2, md3, md5 (fbx in progress)
> 
> I believe a full powerful importing jvm library on par of the original would be greatly useful for the jvm world, and especially for libgdx.
> 
> That's why I'm looking for some possible collaborations with the libgdx.
> 
> I quickly chatted with Mario and he suggested me to speak with @xoppa
> 
> My main goal is to catalyze attention and efforts (in porting code and finding bugs).
> 
> Is there any possibility in this regard? :)

How the collaboration is going, do libGDX supports DAE?
