### ISSUE TITLE
Rotate node 3d from face tracking data

### ISSUE THREAD

**Issue by nqc8291** [libgdx/libgdx#5014]
#### Issue details
I added the 3d model to the camera and wanted it to rotate in the direction of the face but did not work.

#### Reproduction steps/code
node.rotation.setEulerAngles(xRatio,  yRatio , zRatio );

#### Version of LibGDX and/or relevant dependencies
_1.9.6

#### Please select the affected platforms
- [X ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
Please use the forum or irc for questions like this.
