### ISSUE TITLE
FAILURE: Build failed with an exception | libGDX 1.9.8 | Java 9 | Gradle 4.4

### ISSUE THREAD

**Issue by Rickodesea** [libgdx/libgdx#5015]
Please ensure you have given all the following requested information in your report.

#### Issue details
Trying to build a project but failing

#### Reproduction steps/code
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '9.0.1'.

I tried downgrading to java 8 but I got the exact same error.

#### Version of LibGDX and/or relevant dependencies
libGDX 1.9.8
Java 9
Gradle 4.4

#### Stacktrace
unable to provide

#### Please select the affected platforms
- [ x ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ x ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
That version of JDK and gradle is not supported. 

Your error comes from your Gradle version specifically, if you want to use that you'll have to go to Gradle for support on that issue.
