### ISSUE TITLE
Feature Request Android: Possibility to define keys that are catched other than menu/back

### ISSUE THREAD

**Issue by MrStahlfelge** [libgdx/libgdx#5020]
Hello,

we have the possibility to catch the Android back and menu buttons by calling `setCatchBackKey`/`setCatchMenuKey`. However, all other keys are **not** catched on Android and there is no possibility to do so. The responsible code in `AndroidInput.onKey`:

		if (keyCode == Keys.BUTTON_CIRCLE) return true;
		if (catchBack && keyCode == android.view.KeyEvent.KEYCODE_BACK) return true;
		if (catchMenu && keyCode == android.view.KeyEvent.KEYCODE_MENU) return true;
		return false;

([Go to AndroidInput](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidInput.java))

The `return false` statement tells Android that the game did not process the event - this is not correct in many cases. However, it also doesn't matter in most cases, so we normally have no problem here.

But besides the menu or back key, there are some other keys that need to be catched when used: Volume Up/Down, Fast Foward buttons are some examples. When targetting for FireTV devices and using the buttons available on the FireTV Remote Controller, Amazon rejects the game submission if the game does not return that the key event was handled. (They give the reason that a media player in background will react on the key events, which is true.) There is no easy way to solve this problem at the moment.

I suggest to add an array with keycodes that are catc hed, change the code above to something like

		if (keyCode == Keys.BUTTON_CIRCLE) return true;
		return keysToCatch.contains(keyCode);

and add a method `setCatchKey(keyCode, boolean)` to `AndroidInput` and the core interface for adding and removing the catched keycodes. With this approach, all buttons that need to be catched can be set by the developer.

I would be happy to add the change, but before doing so I wanted to discuss this change here.

**Comment by kalexmills** [comment]
<thinking-aloud>
What, if any, integration between Android and iOS should be considered? Could the same button have the same meaning on both platforms? Should we care?
</thinking-aloud>

**Comment by MrStahlfelge** [comment]
Closing this due to the open PR
