### ISSUE TITLE
TextField's cursor is not blinking with non continuous rendering

### ISSUE THREAD

**Issue by metaphore** [libgdx/libgdx#5023]
**NCR** - non continuous rendering

With *NCR* `TextField`'s cursor is not blinking and I find it is little hard to spot the cursor position when it isn't animated at all. I get the idea that with *NCR* we should reduce render calls wherever it's possible, but cursor blinks only trice in a second and also it only happens when field is selected. So maybe it would be better to just leave blinking in a place (we request rendering when text is changed and every tick when any `Action` is present after all)?

Other option could be to provide user with an option to choose blinking mode, but I hardly believe that someone really prefers to save 3 frames per second to overall usability.

#### Version of LibGDX and/or relevant dependencies
1.9.8

#### Please select the affected platforms
- [x] Android
- [x] iOS (robovm)
- [x] iOS (MOE)
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by metaphore** [comment]
My bad, I've checked `TextField`'s code once again and saw that `blink()` actually triggers from `render()` which makes my patch completely useless.

I can see two other options here:
1. Use `com.badlogic.gdx.scenes.scene2d.Action` as a blink timer. We will have to request render every frame when `TextField` is selected.
2. Use ` com.badlogic.gdx.utils.Timer`. But I'm not sure if using background thread is fine with the Scene2d widgets.

**Comment by metaphore** [comment]
Since `Timer` is used in `TextField` code already, I decided to go with this approach. Please review my [PR](#5027 ) and read about a drawback.

**Comment by NathanSweet** [comment]
Using Timer is a fine solution. Let's continue discussion in #5027
