### ISSUE TITLE
Tooltip restricted to drawing on stage of actor

### ISSUE THREAD

**Issue by JasonMacKeigan** [libgdx/libgdx#5026]
Please ensure you have given all the following requested information in your report.

#### Issue details
It's not possible to draw a tooltip on a different stage than what the target actor is on. This is an issue for my game design and what I assume would be various others as well. 

**Why?**
I have 2 stages. 1 stage uses a viewport with very small units, exactly 24x16. The other stage has a dimension of (24 *32) x (16 * 32) so it's exactly 32* larger than the first stage. This is because when drawing text on a stage with small world units will force the text to draw extremely large. 

**What is the solution?**
Simply allow for the possibility of Tooltip's to draw the underlying container on a different stage than the target actor of the tooltip. This would allow me to set the stage of the tooltip to effectively the 'font stage' which is what would draw the tooltip appropriately. 

#### Reproduction steps/code
```
Tooltip foo = ..

foo.setTargetStage(barStage);

```
#### Version of LibGDX and/or relevant dependencies
1.9.6

#### Please select the affected platforms
- [x] Android
- [x] iOS (robovm)
- [x] iOS (MOE)
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by JasonMacKeigan** [comment]
Anyone?

**Comment by JasonMacKeigan** [comment]
I scaled my world units by 32 times and resolved the issue. However, this is an extremely terrible hardcoded solution that is going to cause me a lot of issues in the future since now I have to remember that actors on the client end have different positions than the server end.

**Comment by NathanSweet** [comment]
It's a bit odd for a tooltip to know about some other stage.

You could scale your fonts so your stages don't need to be different sizes. You would also no longer have a need for multiple stages, which is nice.

**Comment by JasonMacKeigan** [comment]
@NathanSweet Yeah the solution of scaling the stage to x32 was a good decision and yeah, it allows me to depreate a stage I created for just 'font'.
