### ISSUE TITLE
missing file(image) in tutorials

### ISSUE THREAD

**Issue by FerdiNaNidreF** [libgdx/libgdx#5031]
#### Issue details
missing image in tutorials / broken link

#### Reproduction steps/code
**broken link:** http://libgdx.googlecode.com/svn/wiki/assets/sc_map.png
**in this tutorial:** https://github.com/libgdx/libgdx/wiki/Orthographic-camera
**string with a broken link:** that uses the file: sc_map.png Download the file here

Also " Image download: sc_map.png " this string in the same tutorial also might be incorrect.

**Comment by cypherdare** [comment]
Here's the image. I think a project member has to push a copy of it to the wiki images directory. https://web.archive.org/web/20140428231403/http://libgdx.googlecode.com/svn/wiki/assets/sc_map.png

**Comment by julienvillegas** [comment]
![sc_map](https://user-images.githubusercontent.com/12996613/34653163-6a5c206c-f3e8-11e7-8913-87738e62bc81.png)

**Comment by julienvillegas** [comment]
Loaded file here. it is not ideal. It should really be added to the wiki/images folder but only contributors can do it.
