### ISSUE TITLE
Broken Link on office web site

### ISSUE THREAD

**Issue by julienvillegas** [libgdx/libgdx#5032]
Please ensure you have given all the following requested information in your report.

#### Issue details
Link "Documentation" is missing in section "Running iOS RoboVM Project in Intelij Android Studio" here: https://libgdx.badlogicgames.com/documentation/gettingstarted/Running%20and%20Debugging.html#running-ios-robovm-project-in-intellij-android-studio

note: I have tried to fix it myself but could not find instructions on how to do it.

**Comment by Tom-Ski** [comment]
Docs are located here  https://github.com/libgdx/libgdx-site/tree/master/src/main/docs/src/docs

**Comment by Tom-Ski** [comment]
Moved issue to https://github.com/libgdx/libgdx-site/issues/25
