### ISSUE TITLE
ERR_EMPTY_RESPONSE from nightlies JavaDoc Actions.html

### ISSUE THREAD

**Issue by kalexmills** [libgdx/libgdx#5034]
It seems that the JavaDoc for Actions.java isn't building? At least it isn't showing up on the site.

#### Issue details
https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/scenes/scene2d/actions/Actions.html returns ERR_EMPTY_RESPONSE. Is the javadoc for Actions.java building appropriately?

#### Reproduction steps/code
Click [this](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/scenes/scene2d/actions/Actions.html
)
#### Version of LibGDX and/or relevant dependencies
Nightly build

Submitting this since it hasn't been reported before. This issue also affects the JavaDocs for other files.
![err_empty_response](https://user-images.githubusercontent.com/22620342/34322546-674e468e-e7ef-11e7-8ca1-d6a3785ba711.PNG)

**Comment by MobiDevelop** [comment]
It's working for me.

**Comment by kalexmills** [comment]
That is bizarre, because other links on the nightlies are working for me too -- but this one is being quite stubborn.

I am on Chrome on Windows 10 Creators Update.

I'll close the issue in 24 hrs if I am the only one affected.
