### ISSUE TITLE
Feature request: Alternative Type token/type reference for AssetManager.load method

### ISSUE THREAD

**Issue by MrPlow442** [libgdx/libgdx#5038]
#### Issue details
Currently AssetManager `load` function accepts a class reference which functions well enough for built-in loaders and custom loaders for simple java classes, however there are certain cases where the user might want to load a generic class, a class such as the fairly recently reworked `Animation` class. This type of a generic class is currently difficult to load, especially in languages like Kotlin which do not allow the use of untyped/type erased generic class references.  Jackson has mitigated this via a specialized [TypeReference](https://fasterxml.github.io/jackson-core/javadoc/2.2.0/com/fasterxml/jackson/core/type/TypeReference.html) which I think is based on [this fairly popular TypeToken idea by Neal Gafter](http://gafter.blogspot.hr/2006/12/super-type-tokens.html). Could something like that be implemented into the current `AssetManager` to allow loading of generic types?

#### Reproduction steps/code
N/A

#### Version of LibGDX and/or relevant dependencies
N/A

#### Stacktrace
N/A

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by noblemaster** [comment]
Given there are no comments or any kind of development for the past 2.5 years, I'll close this issue. Given that this has received no comments at all, it appears to be of little interest (I might be wrong).

We can re-open this again in the future as needed.
