### ISSUE TITLE
PolygonSprite.java setRegion bug

### ISSUE THREAD

**Issue by JKazma** [libgdx/libgdx#5039]
I am trying to execute this piece of code in my game.

`public void draw(Batch batch, float parentAlpha){
    PolygonRegion polyReg = new PolygonRegion(connectorTextureRegion, getVertices(), getTriangles());
    polygonSprite.setRegion(polyReg);
    polygonSprite.draw((PolygonSpriteBatch)batch);
}`

In general, it works well but sometimes I'm getting an ArrayIndexOutOfBounds exception caused by the setRegion line. If I dive into the methods code, it fails at the first line in the for loop.

    public void setRegion (PolygonRegion region) {
         this.region = region;

    float[] regionVertices = region.vertices;
    float[] textureCoords = region.textureCoords;

    if (vertices == null || regionVertices.length != vertices.length) vertices = new float[(regionVertices.length / 2) * 5];

    // Set the color and UVs in this sprite's vertices.
    float floatColor = color.toFloatBits();
    float[] vertices = this.vertices;
    for (int i = 0, v = 2, n = regionVertices.length; i < n; i += 2, v += 5) {
        vertices[v] = floatColor;
        vertices[v + 1] = textureCoords[i];
        vertices[v + 2] = textureCoords[i + 1];
    }

    dirty = true;
}`

Now let me know if I'm wrong, but I feel like there might be an issue with the if condition. We should have
`(regionVertices.length /2)*5!= vertices.length`
instead of
`regionVertices.length != vertices.length` 

Whenever I get the exception, it's because the length of the region vertices array and the length of the sprite vertices array are equal.

**Comment by JKazma** [comment]
Anyone?

**Comment by NathanSweet** [comment]
Sorry for the delay. It looks like you are right. I've committed a fix, @JKazma can you please test with whatever you used to produce the problem?
