### ISSUE TITLE
2D Particle Editor version not visible

### ISSUE THREAD

**Issue by nmaehlmann** [libgdx/libgdx#5040]
#### Issue details
When downloading the 2D Particle Editor from https://libgdx.badlogicgames.com/tools.html , there is no obvious way to see the supported libgdx version of the editor. At least I was not able to find out the version easily. So when something goes wrong while loading a particle effect in a java application, version issues can't be ruled out fast.

#### Reproduction steps/code
/

#### Version of LibGDX and/or relevant dependencies
/

#### Stacktrace
/
#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by piotr-j** [comment]
The downloads are all nightlies, ie latest. You can tell by checking the link. Or at least they should be. Running the editor directly from ide is probably the best idea, that way it will be always correct version. 

Gdx version would be easy to add to the editor, but that wont tell you if the particles will work with version -1 or whatever. They dont change very often.
