### ISSUE TITLE
Request: Switch to lwjgl version 3.1.4 for next release

### ISSUE THREAD

**Issue by maximiliancsuk** [libgdx/libgdx#5041]
Current libGDX version is using 3.1.3. Version 3.1.4 of lwjgl supposedly fixes an important issue that affects all windows (10) users with UI scaling > 100% (which is probably a lot, considering high density displays are commonplace).

This should fix the following libGDX issue: #3813

Here's the underlying lwjgl issue, closed via the 3.1.4 release:
https://github.com/LWJGL/lwjgl3/issues/252 

I'm happy to test a snapshot release of libgdx, if you make one!

**Comment by Tom-Ski** [comment]
Hi, sorry for the wait, snapshot up in 30 minutes if you'd like to give it a go.
