### ISSUE TITLE
File sc_map.png missing from wiki page

### ISSUE THREAD

**Issue by mcol** [libgdx/libgdx#5045]
The page https://github.com/libgdx/libgdx/wiki/Orthographic-camera references a file called `sc_map.png`, but the link to download it (http://libgdx.googlecode.com/svn/wiki/assets/sc_map.png) is now 404.

**Comment by julienvillegas** [comment]
This duplicates #5031
Issue has been resolved by loading the file in the wiki/images file 
Since only contributors can do I only loaded it into the issue and updated the wiki to point to it.
