### ISSUE TITLE
Closing LibGDX game deactivates Windows Night Mode

### ISSUE THREAD

**Issue by julcreutz** [libgdx/libgdx#5052]
#### Issue details
I noticed that my Windows' Night Mode deactives after closing my LibGDX game the first time I open it up. After I reactivate Windows Night Mode again, it doesn't happen anymore.
The slider doesn't change to deactivated, but the orange hue change is just not showing up anymore.

#### Reproduction steps/code
It's a general issue, not related to any specific code.

#### Version of LibGDX and/or relevant dependencies
1.9.6

#### Stacktrace
None.

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [ ] MacOS

**Comment by RUSshy** [comment]
I have same problem, this is annoying

**Comment by julcreutz** [comment]
Yeah, exactly like you stated.
I just installed f.lux. It's way better and isn't having the same problem as Windows Night Mode.

**Comment by RUSshy** [comment]
Ok i rebooted and tested again first with lwjgl and once closed Night Mode stays, then i tested again with libGDX and once closed Night Mode stop to work and i get full brightness again..

So there is something wrong on libGDX part

I tested with https://github.com/LWJGL/lwjgl3-demos  wich uses latest version: 3.1.6-SNAPSHOT

**Comment by xGnoSiSx** [comment]
I also Confirm it works with f.lux. 

Shouldn't this be a windows bug though? (and if not, then something that affects the parent LWJGL project)

**Comment by NathanSweet** [comment]
This also happens with Clippy and libgdx apps using the LWJGL 2 backend. I have a feeling it is a video driver issue and unrelated to libgdx, which I doubt messes around with the Windows gamma ramp.

**Comment by cygn-s** [comment]
I've also noticed this happening with Minecraft, which would support the idea that this is related to LWJGL.

**Comment by Tom-Ski** [comment]
Lwjgl issue, cannot fix at the libgdx side.
