### ISSUE TITLE
How do i use vscode with this?

### ISSUE THREAD

**Issue by VisualTuber** [libgdx/libgdx#5054]
Hi i want to use vscode with this but i don't know how to do it help.
(Windows 7/libGDX 1.9.8)

**Comment by Darkyenus** [comment]
Like you would any other Gradle based project. This is not really an issue, see: https://github.com/libgdx/libgdx/wiki/Getting-Help and try IRC or forums.

Btw. if you don't insist on VSCode, try [IntelliJ IDEA](https://www.jetbrains.com/idea/), the setup is even documented on the [wiki](https://github.com/libgdx/libgdx/wiki/Project-Setup-Gradle).
