### ISSUE TITLE
isXboxController returns false for XBOX 360 controller on Windows

### ISSUE THREAD

**Issue by Zarandor** [libgdx/libgdx#5061]
#### Issue details
Xbox.isXboxController returns false with my XBOX 360 controller connected on Windows.

The problem lies in the code of class Xbox line 157:
`return controller.getName().contains("Xbox")`

The name of the controller returned by method controller.getName() is:
Controller (XBOX 360 For Windows)

So the fact that contains is case sensitive is the problem here.

Here are the key codes for the controller on Windows:
// Button code
A						= 0;
B						= 1;
X						= 2;
Y						= 3;
L_BUMPER				= 4;
R_BUMPER				= 5;
BACK					= 6;
START					= 7;
// Axis code
L_STICK_VERTICAL_AXIS		= 0;
L_STICK_HORIZONTAL_AXIS	= 1;
R_STICK_VERTICAL_AXIS		= 2;
R_STICK_HORIZONTAL_AXIS	= 3;
L_TRIGGER				= 4;
R_TRIGGER				= 4; // same than L_TRIGGER
// unused
DPAD_UP					= -1;
DPAD_DOWN				= -1;
DPAD_LEFT				= -1;
DPAD_RIGHT				= -1;
L_STICK					= -1;
R_STICK					= -1;
GUIDE					= -1;

#### Reproduction steps/code
I just plugged in my XBox 360 controller on Windows and tested it on Desktop.

#### Version of LibGDX and/or relevant dependencies
1.9.7
LWJGL

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by EtK2000** [comment]
Did #5090 fix this?
If so this should be closed.

**Comment by noblemaster** [comment]
Given there is no response for nearly 2 years and #5090 might fix the problem, I'll close the issue. There have been other controller improvements in the past 2 years, so this might have become moot. We can re-open or create a new issue as needed.
