### ISSUE TITLE
[Feature Request] Upgrade Android backend compile SDK to newer version

### ISSUE THREAD

**Issue by obigu** [libgdx/libgdx#5064]
**Android backend is currently being compiled with Android 4.4 (Api Level 19)** using system libraries inside the /libs folder (_android-4.4.jar_ and _support-v4-19.0.1_).

It's good practice to use the latest compileSDK to take advantage of new compiler optimizations as well as get compiler warnings (such as deprectaion) or other compiler checks (https://medium.com/google-developers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd). Compile SDK is **almost independent** (explained later) from minSDK or targetSDK of projects using libGDX and doesn't break backwards compatibility.

**libGDX currently allows minSDK 9**. Android Support libraries do have minSDK requirements and that's what makes libGDX compileSDK not to be fully independent from minSDK. Latest SDKs Support libraries (26.0.0 onwards) require minSDK 14. The latest Support library which allows minSDK 9 is 25.4.0 (https://developer.android.com/topic/libraries/support-library/rev-archive.html).

**So, if we want to keep minSDK 9, we can use Android Nougat (Api Level 25) as the new SDK to compile the Android backend**.

It would also be interesting as a separate discussion to consider upgrading the minSDK to API Level 14  considering it's only used by 0.4% of active devices.

**Comment by Tom-Ski** [comment]
Pushed new API. If you need something specific with a newer support library let us know. The support libraries are not currently compatible with the build, so we would need to adjust.
