### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by farisbdev** [libgdx/libgdx#5066]
Issue details
Using gdx-setup, I get the following error:

Generating app in C:\Users\Brian\Downloads\test
Executing 'C:\Users\Brian\Downloads\test/gradlew.bat clean --no-daemon'
Picked up _JAVA_OPTIONS: -Xverify:none

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '9.0.4'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Done!
To import in Eclipse: File -> Import -> Gradle -> Gradle Project
To import to Intellij IDEA: File -> Open -> build.gradle
To import to NetBeans: File -> Open Project...

Reproduction steps/code
Run gdx-setup, generate project

**Comment by Fabpk90** [comment]
Hi!
I have run into this error myself this morning.
To solve this, I uninstalled the 9.0 JDK and installed the 8.0 one(8u161, to be precise).
Make sure to uninstalled all version before installing the 8.0.
Hope it helps.
Cheers!

**Comment by Tom-Ski** [comment]
9.0 not supported yet due to IDE issues with required Gradle version for 9.0 to be supported.
