### ISSUE TITLE
Gdx.input.isKeyPressed(ANY_KEY) broken (Linux)

### ISSUE THREAD

**Issue by nhatzHK** [libgdx/libgdx#5069]
After dragging the application window, the `Gdx.input.isKeyPressed()` method always returns false when `Input.Keys.ANY_KEY` is passed as parameter.

#### Issue details
I'm not familiar with the libgdx codebase enough, but I think the [`pressedKeys`](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglInput.java#L227) value stops being updated at a certain point for whatever reason. This is also a platform specfic issue. I tested the same program on Windows 7 and it works as expected.

#### Reproduction steps/code
[SSCCE That demostrates the issue.](https://github.com/nhatzHK/GDX_SSCCE_ANY_KEY/).

1. Clone the repository linked above.
2. Run the desktop launcher.
3. Press left, right, up, down, and space keys to verify that the image moves.
4. Drag the window either with your mouse or a key combination.
5. Repeat step 3.

**Expected behaviour:** At step 5 the program behaves like in step 3 with key presses moving the image inside the application window.

**Observed behaviour:** At step 5, the program keeps running normally, but `Gdx.input.isKeyPressed(Input.Keys.ANY_KEY)` [always returns false](https://github.com/nhatzHK/GDX_SSCCE_ANY_KEY/blob/c3b52d43313bc806571a438e818a39ba59c2c7c4/core/src/com/mygdx/game/SSCCE_Screen.java#L30) even though [input is still correctly processed](https://github.com/nhatzHK/GDX_SSCCE_ANY_KEY/blob/c3b52d43313bc806571a438e818a39ba59c2c7c4/core/src/com/mygdx/game/SSCCE_Screen.java#L59). 

#### Version of LibGDX and/or relevant dependencies
_libgdx 1.9.8_

#### Environment
**OS:** Linux
**Kernel:** x86_64 Linux 4.14.15-1-ARCH
**WM:** i3wm
**CPU:** Intel Core i7-5600U @ 4x 3.2GHz
**GPU:** Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2)

#### Java implementation
**openjdk version "1.8.0_162"**
**OpenJDK Runtime Environment (build 1.8.0_162-b12)**
**OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)**

#### Affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] MacOS

##### [EDIT]
- Added java implementation information (15 April 2018)

**Comment by yuripourre** [comment]
Can you please tell what JVM are you using?

**Comment by nhatzHK** [comment]
Here's the information about my java install. I just retested with this configuration,  can confirm the issue still exists.

**openjdk version "1.8.0_162"**
**OpenJDK Runtime Environment (build 1.8.0_162-b12)**
**OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)**

**Comment by yuripourre** [comment]
I could replicate this problem months ago but after upgrading for lwjgl3 it is working perfectly.

@nhatzHK I suggest you upgrade to lwjgl3 to fix the issue.

**Comment by crykn** [comment]
I think we can close this issue if the bug doesn't happen with LWJGL 3. LWJGL 2 itself is no longer actively developed since 4 years ago, so legacy projects should consider migrating over to our LWJGL 3 backend anyway.
