### ISSUE TITLE
Unsafe generic array cast

### ISSUE THREAD

**Issue by XIII-th** [libgdx/libgdx#5076]
#### Issue details
I found unpleasant surprise using `Array` calss. This class store items as a generic array (`T[]`), but this field initialised as `Object` array:  
```java
public Array (boolean ordered, int capacity) {
    this.ordered = ordered;
    items = (T[])new Object[capacity];
}
```
In result we have `Object` array can't be cast to `T` array.

Next methods crahes with `ClassCastException` if returned value will be assignet to `T[]`:
- `Array.shrink()`
- `Array.ensureCapacity()`
- `Array.setSize()`
- assign of `Array.items` to `T[]` variable
- `SnapshotArray.begin()`
- `SnapshotArray.setSize()`

#### Reproduction steps/code
```java
Array<MyObject> testArray = new Array<>();
testArray.add(new MyObject());
MyObject[] items = testArray.items;
// or
MyObject[] items = testArray.shrink();
```
#### Version of LibGDX and/or relevant dependencies
_1.9.8_

#### Stacktrace
```java
Caused by: java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lcom.test.Test$MyObject;
```

**Comment by cypherdare** [comment]
The Javadocs for `items` explains that the backing array is an Object[] if you don't pass a class type to the constructor. Not sure it would make sense to redundantly explain that in every method's docs rather than link to the `items` docs as it does now.

**Comment by XIII-th** [comment]
@cypherdare javadoc of `SnapshotArray` have example:  
```java
Object[] items = array.begin();
for (int i = 0, n = array.size; i &lt; n; i++) {
    Object item = items[i];
    // ...
}
array.end();
```
this totally right, but why method signature is `public T[] begin ()`?   
When I call method with return type `T[]` I expect to get `T` array (not `Object[]`).

**Comment by cypherdare** [comment]
The method signature is T[] because that is a lot more convenient to use
than Object[]. You just have to pass the class type into the constructor
for it to work.

**Comment by NathanSweet** [comment]
It's `T[]` for convenience, which was deemed worth the minor gotcha that it should be accessed as `Object[]` unless the type is passed to a constructor.
