### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Action.act(float) on a null object reference

### ISSUE THREAD

**Issue by denis-stepuschik** [libgdx/libgdx#5080]
#### Issue details
Crash appears while rendering screen.

#### Reproduction steps/code
StageScreen
```java
public void render(float delta) {
        Gdx.gl.glClear(16384);
        if(null != this.stage) {
            this.stage.act(delta);
            this.stage.draw();
        }

    }
```

BaseScreen
```java
 @Override
    public void render(float delta) {
        super.render(delta);
        if (null != fpsLabel) {
            fpsLabel.setText(String.valueOf(Gdx.graphics.getFramesPerSecond()));
        }
    }
```

BaseGame
```java
public void render() {
        if(this.screen != null) {
            this.screen.render(Math.min(Gdx.graphics.getDeltaTime(), 0.033333335F));
        }
    }
```

#### Version of LibGDX and/or relevant dependencies
gdxVersion = '1.9.6'

#### Stacktrace
```java
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.badlogic.gdx.scenes.scene2d.Action.act(float)' on a null object reference
       at com.badlogic.gdx.scenes.scene2d.actions.RepeatAction.delegate(SourceFile:29)
       at com.badlogic.gdx.scenes.scene2d.actions.DelegateAction.act(SourceFile:43)
       at com.badlogic.gdx.scenes.scene2d.Actor.act(SourceFile:96)
       at com.badlogic.gdx.scenes.scene2d.Group.act(SourceFile:49)
       at com.badlogic.gdx.scenes.scene2d.Group.act(SourceFile:49)
       at com.badlogic.gdx.scenes.scene2d.Stage.act(SourceFile:221)
       at ....StageScreen.render(SourceFile:98)
       at ....BaseScreen.render(SourceFile:71)
       at ....BaseGame.render(SourceFile:97)
       at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(SourceFile:459)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1583)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)
```

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Darkyenus** [comment]
Provided code can't cause your crash. Somewhere in your code, you must be adding `RepeatAction` with `null` action to repeat. This could be caused by releasing the `RepeatAction` back to its pool without actually removing it from the Actor. (Or maybe you are adding single `RepeatAction` instance to multiple `Actor`s).

Anyway, this does not appear to be a libGDX problem, so it would be more suited for the [forum or IRC](https://github.com/libgdx/libgdx/wiki/Getting-Help).

**Comment by julienvillegas** [comment]
Looks like one of the actor has been added to the Scene2d stage without having been instantiated.
This would happen if you have something like

```
Label fpsLabel;
stage.addActor(fpsLabel);
```

instead of 

```
Label fpsLabel = new Label();
stage.addActor(fpsLabel);
```

Hard to say without the full code...

**Comment by Darkyenus** [comment]
@julienvillegas `Action.act(float)` call threw NPE, so the null object in question is an `Action`, not an `Actor`. ([line of NPE](https://github.com/libgdx/libgdx/blob/9b8f20b2d0e96e53f0f2b98dc8f6131c810aae71/gdx/src/com/badlogic/gdx/scenes/scene2d/actions/RepeatAction.java#L29))

**Comment by julienvillegas** [comment]
oups! good point

**Comment by denis-stepuschik** [comment]
@Darkyenus, thank you for the clarification.
