### ISSUE TITLE
can't install libGDX on linux

### ISSUE THREAD

**Issue by ahmedsemihozmekik** [libgdx/libgdx#5082]
#### Issue details
So basically I am trying to install this library for java and facing with this problem.

screenshots from setup:

https://ibb.co/jCogi7
https://ibb.co/dG55An

    FAILURE: Build failed with an exception.
    *What went wrong:
     A problem occurred configuring root project 'test'.
     > Could not resolve all dependencies for configuration ':classpath'.
      > Could not download uast.jar (com.android.tools.external.com-intellij:uast:145.597.3)
       > Could not get resource 'https://center.bintray.com/com/android/tools/external/com-intellij/uast/145.597.3/uast-145.597.3.jar'
          > sun.security.validator.ValidatorException: No trusted certificate found

    *Try:
    Run with --stacktrace option to get the stack trace.Run with --info or debug option to get more log output.

    BUILD FAILED  

#### Version of LibGDX and/or relevant dependencies
1.9.6

#### My Platform

- [ +] Linux

**Comment by mgsx-dev** [comment]
maybe due to Java 9 certificates, more help here : https://stackoverflow.com/questions/41421340/gradle-no-trusted-certificate-found

**Comment by xoppa** [comment]
See: https://github.com/libgdx/libgdx/wiki/Issue-Tracker. Please use the forum or irc for personal support requests.

If you do think that there is an issue with libgdx, then please provide the information required as you were requested when opening this issue, see also: https://github.com/libgdx/libgdx/wiki/More-Info.
