### ISSUE TITLE
Unused branches

### ISSUE THREAD

**Issue by HoldYourWaffle** [libgdx/libgdx#5086]
There are 8 branches in this repository, 1 of which is actually being used. All the others are 500 - 1100 commits behind and 2 of them contain 1 'new' commit.
Is there a reason these branches are being kept? To me they just seem like unnecessary clutter.

**Comment by MrStahlfelge** [comment]
Yep, they were completely unused and merged. I've deleted them.

**Comment by cypherdare** [comment]
`newspritebatch` was pretty cool. I copied the api for FlexBatch. It solves the problem of all the crazy `draw` overload by using a builder pattern.

**Comment by MrStahlfelge** [comment]
Do you think we should restore it? I doubt anyone will have much benefit from it, especially if you've taken over the ideas in an extension for everyone to use.

**Comment by cypherdare** [comment]
Oh, no, sorry, I was just commenting. It's not something we would ever consider merging because it would be such a major API change.
