### ISSUE TITLE
Feature request: SelectBox should be focusable

### ISSUE THREAD

**Issue by Springrbua** [libgdx/libgdx#5093]
#### Issue details
The Scene2d `SelectBox` is not focusable at the moment.  
This means, that you are not able to use the keyboard to "tab" to the `SelectBox` and change it's value.  
You always need to click/touch it to open the picker and then select the value.  

I am not sure how it should behave on devices with soft-keyboards, but on Desktops and other devices with a hardware-keyboard, I think the whole UI should be accessible using the keyboard.

#### Reproduction steps/code
Add a focusable widged (for example `TextField`) and the `SelectBox` to a UI.  
Focus the `TextField` and press `tab` to focus the next field.  
The `SelectBox` won't get the focus.

#### Version of LibGDX and/or relevant dependencies
I am using the latest stable version (1.9.8)

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by NathanSweet** [comment]
scene2d.ui widgets (not just SelectBox) aren't fully traversable via the keyboard out of the box. TextField has a simple mechanism for focusing the next widget, but that is it. I agree it would be nice to have, but I also want to be careful it doesn't add too much complexity to the widgets and doesn't make it difficult to use, extend, or create new widgets. I don't know when we'll have bandwidth to work on this issue. Until then, I suggest building your own focus traversal.

**Comment by Springrbua** [comment]
@NathanSweet thank you for your fast reply.
Is there some example of how to build this focus traversal?
I guess I would have to subclass the widgets (for example `SelectBox`) and make them focusable, but a simple example would help.

**Comment by NathanSweet** [comment]
Sorry for the delay! Just the code in TextField `next()`.

**Comment by Springrbua** [comment]
Thanks a lot! I'll take a look at it

**Comment by MrStahlfelge** [comment]
For focusing scene2d.ui, I would also recommend [gdx-controllerutils project](https://github.com/MrStahlfelge/gdx-controllerutils/wiki/Button-operable-Scene2d). There's no focusable selectbox at the moment, but the provided focusable list should be enough to get going. I am happily accepting PRs for the repo.
Closing this, because an issue for enhancing the selectbox alone does not make sense if we have no focus support in scene2d.ui generally.
