### ISSUE TITLE
Running the Runnable_Action tutorial for HTML - cannot find skin.

### ISSUE THREAD

**Issue by Bobbeo** [libgdx/libgdx#5094]
#### Issue details
Running the Runnable_Action tutorial for HTML - cannot find skin.

#### Reproduction steps/code
1. Download the following repository:
https://github.com/julienvillegas/libgdx.info-Runnable_Action
2. Run the following:
gradlew html:superDev
I noticed building only gets to 91%.:

> 2018-02-16 21:43:58.282:INFO:oejs.Server:main: Started @4677ms
> > Building 91% > :html:superDev
> 

3. Navigate to http://localhost:8080/html/
The  libgdx web console displays the following:

> GwtApplication:exception: Error reading file: skin/glassy-ui.json
> Error reading file: skin/glassy-ui.json
> ...
> Invalid page id:
> For input string: ""

#### Version of LibGDX and/or relevant dependencies
1.9.5

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [*] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
Please report issue to the appropriate repository.

**Comment by Bobbeo** [comment]
I have reported it here:

https://github.com/julienvillegas/libgdx.info-Runnable_Action/issues/1
