### ISSUE TITLE
ProgressBar issue

### ISSUE THREAD

**Issue by HuangBoHong** [libgdx/libgdx#5095]
#### Issue details
I found some codes problem when I was using ProgressBar with NinePatchDrawable background in my game.

#### Reproduction steps/code
the codes in  ProgressBar.java (LibGDX 1.9.8):
![1](https://user-images.githubusercontent.com/11132087/36305693-9195c4e0-134f-11e8-8a41-d87e6592ed2c.png)
![3](https://user-images.githubusercontent.com/11132087/36305694-91c9ed24-134f-11e8-88a1-a6007ac7f941.png)
![5](https://user-images.githubusercontent.com/11132087/36305695-9201f796-134f-11e8-98ce-76bbce615377.png)
![7](https://user-images.githubusercontent.com/11132087/36305696-9236f66c-134f-11e8-9429-38826df8f916.png)
may cause the problem like this:
![res1](https://user-images.githubusercontent.com/11132087/36305816-299b3ca2-1350-11e8-8af4-8a6e2527585e.png)

*the green part: knobBefore; the yellow part: knobAfter; the red part: knob

the codes after I made some changes:
![2](https://user-images.githubusercontent.com/11132087/36305972-d59f7e14-1350-11e8-82a2-3a036cae290b.png)
![4](https://user-images.githubusercontent.com/11132087/36305973-d5d24038-1350-11e8-928a-e35388713e9e.png)
![6](https://user-images.githubusercontent.com/11132087/36305974-d6045c4e-1350-11e8-8113-265b1acc0e55.png)
![8](https://user-images.githubusercontent.com/11132087/36305975-d6356a32-1350-11e8-9228-6837e2902fd9.png)
and the problem seems to disappear:
![res2](https://user-images.githubusercontent.com/11132087/36306056-1719d146-1351-11e8-875c-51a2878a0927.png)

#### Version of LibGDX and/or relevant dependencies
All the libGDX version with ProgressBar...I think

#### Please select the affected platforms
- [X] Android
- [X] iOS (robovm)
- [X] iOS (MOE)
- [X] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by Tom-Ski** [comment]
Please provide code sample as requested by the issue template.

**Comment by NathanSweet** [comment]
Note improvements are welcome but we need to be able to test them, so we request code showing the problem. Also it would be difficult to translate your changes from screenshots to code edits. If you can submit a PR we can merge it efficiently.
