### ISSUE TITLE
Model instances aren't rendering correctly

### ISSUE THREAD

**Issue by lukehayes** [libgdx/libgdx#5096]
#### Issue details
I am currently learning the basics of LibGDX and I am experimenting with basic models. I have gotten a simple cube mesh to show but it isn't rendering correctly - see image:

![screen shot 2018-02-16 at 18 53 27](https://user-images.githubusercontent.com/3280616/36333360-49b9b95a-136e-11e8-8f5e-073f271352ea.png)

Here is the code that I am using to get the model:

` package com.lukegdx.game;`
` import com.badlogic.gdx.ApplicationAdapter;`
` import com.badlogic.gdx.Gdx;`
` import com.badlogic.gdx.graphics.*;`
` import com.badlogic.gdx.graphics.g2d.SpriteBatch;`
` import com.badlogic.gdx.graphics.g3d.Material;`
` import com.badlogic.gdx.graphics.g3d.Model;`
 `import com.badlogic.gdx.graphics.g3d.ModelBatch;`
 `import com.badlogic.gdx.graphics.g3d.ModelInstance;`
 `import com.badlogic.gdx.graphics.g3d.attributes.ColorAttribute;`
 `import com.badlogic.gdx.graphics.g3d.utils.CameraInputController;`
 `import com.badlogic.gdx.graphics.g3d.utils.ModelBuilder;`
 `import com.badlogic.gdx.math.Vector3;`

` public class LukeDDX extends ApplicationAdapter {`
`	SpriteBatch batch;`
`	Texture img;`

	ModelBatch modelBatch;
	ModelBuilder modelBuilder;
	ModelInstance modelInstance;
	Model model;

	PerspectiveCamera cam;
	int counter = 0;
	public CameraInputController camController;

	@Override
	public void create () {
		img = new Texture("badlogic.jpg");
		modelBatch = new ModelBatch();
		modelBuilder = new ModelBuilder();

		this.setCam();

		model = modelBuilder.createBox(10f,10f,10f,
				new Material(ColorAttribute.createDiffuse(Color.GREEN)),
				VertexAttributes.Usage.Position | VertexAttributes.Usage.Normal);

		modelInstance = new ModelInstance(model);
	}

	public void setCam() {
		cam = new PerspectiveCamera(67, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
		cam.position.set(10f, 10f, 10f);
		cam.lookAt(0,0,0);
		cam.near = 1f;
		cam.far = 300f;
		cam.update();

		camController = new CameraInputController(cam);
	}

	@Override
	public void render () {
		Gdx.gl.glClearColor(1, 0, 1, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

		camController.update();
		modelBatch.begin(cam);
		modelBatch.render(modelInstance);
		modelBatch.end();

	}
	
	@Override
	public void dispose () {
	    modelBatch.dispose();
	    model.dispose();
		img.dispose();

	}
}`

Im wondering if I have just written something in the wrong order? Id really appreciate some guidance on this.

#### Version of LibGDX
1.9.8

Affected platforms
- [ ] MacOS

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
