### ISSUE TITLE
ASCII fbx exported from Blender not rotated by fbx-conv

### ISSUE THREAD

**Issue by patrikturi** [libgdx/libgdx#5104]
#### Issue details
From the docs:
"The coordinate system Blender uses (z-up) is different compared to the most common system used for games (y-up). ... Fbx-conv will compensate the coordinate system by rotating the model (to y-up). However it will only be able to do this, if the fbx file itself contains the correct information"

This works when exporting a Binary fbx from Blender, but not with an ASCII fbx (the model is not rotated).
The problem might very well be in the Blender exporter not writing some information, but I am unable to identify it. If someone can point out what is missing then I can report the bug to Blender instead.

#### Reproduction steps/code
1) [original .blend file](https://www.dropbox.com/s/tiozkwo66x0fpe2/test0.blend?dl=0)
2) [exported ASCII .fbx file](https://www.dropbox.com/s/nw1ursesy3qcvyv/test0.fbx?dl=0)
With the following options:
[exporter options](https://www.dropbox.com/s/zynscsks7y5zjwi/img.bmp?dl=0)
Version: FBX 6.1 ASCII
Forward: -X
Up: Z
3) [.g3dj file created by fbx-conv](https://www.dropbox.com/s/x3wuccsfudmmhyx/test0.g3dj?dl=0)

**Expected:** the model pointing towards Z axis in Blender -- should point towards Y axis in libGDX -- as it was rotated by fbx-conv
**Actual:** the model points towards Z axis in both Blender and libGDX

#### Version of LibGDX and/or relevant dependencies
libGDX: 1.9.8
fbx-conv: 0.01.0071 x32
Blender: 2.79

**Comment by mgsx-dev** [comment]
Exporting to FBX ASCII format has been removed in Blender 2.8, so this is no longer an issue.
