### ISSUE TITLE
ModelBatch render with shader not being properly setted

### ISSUE THREAD

**Issue by RotcivOcnarb** [libgdx/libgdx#5105]
In the ModelBatch class, there is this function:

`public void render (final RenderableProvider renderableProvider, final Shader shader) {
		final int offset = renderables.size;
		renderableProvider.getRenderables(renderables, renderablesPool);
		for (int i = offset; i < renderables.size; i++) {
			Renderable renderable = renderables.get(i);
			renderable.shader = shader;
			renderable.shader = shaderProvider.getShader(renderable);
		}
	}`

(Line 282)

that makes shading in 3d be useless, i have acompplished a ""solution"" by creating a new ModelBatch class that extends, and Overriding the function just removing the line:

`renderable.shader = shaderProvider.getShader(renderable);`

but it would be great if someone fix this

**Comment by xoppa** [comment]
See: https://github.com/libgdx/libgdx/wiki/Issue-Tracker. Please use the forum or irc for personal support requests.

If you do think that there is an issue with libgdx, then please provide the information required as you were requested when opening this issue, see also: https://github.com/libgdx/libgdx/wiki/More-Info.
