### ISSUE TITLE
Implementation of AudioDevice for IOS-MOE

### ISSUE THREAD

**Issue by raver1975** [libgdx/libgdx#5106]
Could you please provide an implementation of AudioDevice in the IOS-MOE backend?

https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-moe/src/com/badlogic/gdx/backends/iosmoe/IOSAudio.java

	@Override
	public AudioDevice newAudioDevice (int samplingRate, boolean isMono) {
		// TODO Auto-generated method stub
		return null;
	}

- [ ] Android
- [ ] iOS (robovm)
- [x] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by simernes** [comment]
From @eix128 #5382 The back end should be ready on the RoboVM side, but the LibGDX implementation is still missing. @Tom-Ski closed the issue 4 days ago but no clue was given on wether or not any implementation was in the works (?).

**Comment by EtK2000** [comment]
The issue was closed because no one did anything with it.
If you have an iOS device you can implement the classes yourself and verify that they work.
Feel free to create a new pull request if they work.

**Comment by simernes** [comment]
I see. I wish I did, but I don't. Perhaps @eix128 would be kind enough to share his work again since the pasted code diffs expired before anyone had the chance to take a look, which in case a working solution was already implemented would be terrific.

**Comment by crykn** [comment]
iOS moe is discontinued.
