### ISSUE TITLE
Can I apply effects on an mp3 file?

### ISSUE THREAD

**Issue by pranay-mathur** [libgdx/libgdx#5119]
Please ensure you have given all the following requested information in your report.

#### Issue details
I am new to Superpowered. But would love to explore it for one of the projects I am working on. Have a quick question: Can I apply superpowered effects on a mp3 file which is already in my storage using Android?

#### Please select the affected platforms
- [YES ] Android

**Comment by Tom-Ski** [comment]
We do not use Superpowered.
