### ISSUE TITLE
Hiero padding wrong behavior?

### ISSUE THREAD

**Issue by quilance** [libgdx/libgdx#5125]
Not sure if this is intended but it causes texture bleeding.

#### Issue details
When I specify padding with Hiero, that padding is applied not only to generated Textures but also glyphs themselves. I don't want additional space between my glyphs but I need padding in Texture file between glyphs in order to avoid rendering artifacts.

#### Version of LibGDX and/or relevant dependencies
1.9.8

#### Please select the affected platforms
Windows

**Comment by NathanSweet** [comment]
You can set the spacing and x/y spacing separately to cover all use cases. Eg:
![](http://n4te.com/x/4062-vBVF.png)

**Comment by quilance** [comment]
I know those settings and they are what I'm actually talking about. They are not working properly. X-Y just increase character's position in metadata while padding applies not only to atlas's png but also to the glyphs themselves. This overall behavior causes texture bleeding or abnormally long spacing between glyphs and makes Hiero practically useless in most projects. BMFont behaviour is totally different. It only inserts those paddings into the uber texture used by atlas but glyph spacing remains the same.

**Comment by obigu** [comment]
@NathanSweet Actually @quilance is right, Hiero padding doesn't work properly, personally I stopped using it in favour of bmGlyph. Can't tell what's wrong but I believe the issue shouldn't be dismissed.

**Comment by NathanSweet** [comment]
Sorry for the delay.

@quilance you said:
> When I specify padding with Hiero, that padding is applied not only to generated Textures but also glyphs themselves. I don't want additional space between my glyphs but I need padding in Texture file between glyphs in order to avoid rendering artifacts.

This is how padding is meant to work in Hiero. Use padding to add space around glyphs in the texture (which will affect layout). Use the X/Y advance fields to add space for laying out glyphs (which will not affect the texture). If you want to add space around glyphs in the texture but not affect layout, then use padding and add the same amount of negative X/Y advance. Eg, padding=2,2,2,2 and x=-4,y=-4.

@obigu I don't see a problem. Hiero has always worked this way. Please feel free to update the wiki if it is lacking. If there is an actual problem with Hiero, please describe it.

FWIW, I don't use Hiero for my projects anymore. Instead, I use libgdx's BitmapFontWriter. For example:
http://n4te.com/x/351-7Qml.txt
