### ISSUE TITLE
Gdx.files.local(filePath).delete() doesent working

### ISSUE THREAD

**Issue by mustii82** [libgdx/libgdx#5126]
Gdx.files.local(filePath).delete() Dosent working Gdx.files.exist says the file doesent exist but after some investigation i discovered it is existing 100%

Even the filePath from Gdx.files.local(filePath).toString() tells me the exact same direction where my file exists.

I replaced Gdx.files.local(filePath).delete() with new File(filePath).delete and everything works fine.

**Comment by Tom-Ski** [comment]
Please provide full sample code as the issue template requests, and give the full detailed steps as to how to reproduce. You could be doing a number of things that would prevent the file from being deleted.
