### ISSUE TITLE
g3db and g3dj files aren't showing

### ISSUE THREAD

**Issue by DmitryUsik** [libgdx/libgdx#5130]
#### Issue details
Good evening, dear developers.
I have the problem with displaying 3d models in my android application.

#### Reproduction steps/code
It's a part of my code for displaying a 3d model.
https://pastebin.com/qG5zB6dC

The file with 3d model is read correctly, but nothing happens on the screen.
If i use the ObjLoader then the 3d model is displaying correctly.

Here are my files with 3d models in g3dj and obj formats.
https://pastebin.com/bc4jpqkq - obj
https://pastebin.com/ftpWLpmA - g3dj

The problem is also relevant for the g3db format.
Models are also displayed correctly in the fbxconv-gui.jar.

I will be glad to any help.

#### Version of LibGDX and/or relevant dependencies
The last version - 1.9.8

#### Stacktrace
I don't show any errors.

#### Please select the affected platforms
- [x] Android

**Comment by xoppa** [comment]
The opacity of your model is zero, see: https://github.com/libgdx/libgdx/wiki/Importing-Blender-models-in-LibGDX#troubleshooting-missing-textures. Please, in the future, use the forum or irc for personal support requests. See: https://github.com/libgdx/libgdx/wiki/Issue-Tracker.
