### ISSUE TITLE
How to use libgdx in AndroidRecycleview Item

### ISSUE THREAD

**Issue by xingchenfengn** [libgdx/libgdx#5135]
I want to show libgdx effect in  Recycleview Item  as a view ，but find libgdx connnet android with fragment and activity, Is there a solution? Thanks

**Comment by Tom-Ski** [comment]
Please use the forum or the irc channel for personal support requests.

**Comment by sourabhgupta811** [comment]
I want to achieve the same result. But couldn't find the solution. is there a way to achieve this solution? Thanks
