### ISSUE TITLE
Get texture from Texture Atlas with findRegion

### ISSUE THREAD

**Issue by klaszlo8207** [libgdx/libgdx#5139]
I have this code

```
textureAtlas = TextureAtlas("atlas.atlas")
val box = textureAtlas.findRegion("box")

```

I want to create a texture with "box". Is it possible? box.texture return the original texture, not the regioned one.

Oh and I don't want to use Sprite and SpriteBatch. I need this in 3D, not 2D.

Thanks

**Comment by Darkyenus** [comment]
https://github.com/libgdx/libgdx/wiki/Getting-Help

**Comment by klaszlo8207** [comment]
And what is the solution?:)

**Comment by Tom-Ski** [comment]
Please read the link provided and https://github.com/libgdx/libgdx/wiki/Issue-Tracker

**Comment by AAbhishek1234** [comment]
@klaszlo8207  did you get a solution ?
