### ISSUE TITLE
Fatal signal 6 (SIGABRT), code -6 in tid 27710 (FinalizerDaemon)

### ISSUE THREAD

**Issue by jianwenzhou** [libgdx/libgdx#5140]
hi,I have this problem every time I reboot.

A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 27710 (FinalizerDaemon)
 pid: 27702, tid: 27710, name: FinalizerDaemon  >>> com.richinfo.libgdx <<<
     #05 pc 002daf13  /data/app/com.richinfo.libgdx-2/lib/arm/libgdx-bullet.so
     #06 pc 002daf1d  /data/app/com.richinfo.libgdx-2/lib/arm/libgdx-bullet.so
     #07 pc 002daf9f  /data/app/com.richinfo.libgdx-2/lib/arm/libgdx-bullet.so
     #08 pc 002da61f  /data/app/com.richinfo.libgdx-2/lib/arm/libgdx-bullet.so
     #09 pc 002d9ea3  /data/app/com.richinfo.libgdx-2/lib/arm/libgdx-bullet.so
     #10 pc 001360f8  /data/app/com.richinfo.libgdx-2/lib/arm/libgdx-bullet.so (_ZN16btCollisionWorldD2Ev+76)
     #11 pc 001ab698  /data/app/com.richinfo.libgdx-2/lib/arm/libgdx-bullet.so (_ZN23btDiscreteDynamicsWorldD2Ev+364)
     #12 pc 001ab798  /data/app/com.richinfo.libgdx-2/lib/arm/libgdx-bullet.so (_ZN23btDiscreteDynamicsWorldD0Ev+8)
     #13 pc 00280acc  /data/app/com.richinfo.libgdx-2/lib/arm/libgdx-bullet.so (Java_com_badlogic_gdx_physics_bullet_dynamics_DynamicsJNI_delete_1btDiscreteDynamicsWorld+28)

**Comment by Tom-Ski** [comment]
Please do not bypass the issue template. Feel free to reopen when the template has been filled correctly.
