### ISSUE TITLE
Fatal signal 6 (SIGABRT), code -6 in tid 8413 (FinalizerDaemon)

### ISSUE THREAD

**Issue by jianwenzhou** [libgdx/libgdx#5141]
#### Issue details
Hello, for the first time running normally, click the handset back button, and then you get an exception.

#### Reproduction steps/code
_Pure virtual function called!
--------- beginning of crash
Fatal signal 6 (SIGABRT), code -6 in tid 8413 (FinalizerDaemon)
/data/app/com.richinfo.libgdx-1/lib/arm/libgdx-bullet.so
/data/app/com.richinfo.libgdx-1/lib/arm/libgdx-bullet.so
/data/app/com.richinfo.libgdx-1/lib/arm/libgdx-bullet.so
/data/app/com.richinfo.libgdx-1/lib/arm/libgdx-bullet.so
/data/app/com.richinfo.libgdx-1/lib/arm/libgdx-bullet.so
/data/app/com.richinfo.libgdx-1/lib/arm/libgdx-bullet.so (_ZN16btCollisionWorldD2Ev+76)
/data/app/com.richinfo.libgdx-1/lib/arm/libgdx-bullet.so (_ZN23btDiscreteDynamicsWorldD2Ev+364)
/data/app/com.richinfo.libgdx-1/lib/arm/libgdx-bullet.so (_ZN23btDiscreteDynamicsWorldD0Ev+8)
/data/app/com.richinfo.libgdx-1/lib/arm/libgdx-bullet.so (Java_com_badlogic_gdx_physics_bullet_dynamics_DynamicsJNI_delete_1btDiscreteDynamicsWorld+28)

#### Please select the affected platforms
- [x] Android

**Comment by xoppa** [comment]
See: https://github.com/libgdx/libgdx/wiki/Issue-Tracker. Please use the forum or irc for personal support requests.
