### ISSUE TITLE
Draw smooth fonts and curves in various different screen resolutions

### ISSUE THREAD

**Issue by Fang3s** [libgdx/libgdx#5145]
Please ensure you have given all the following requested information in your report.

#### Issue details
I want my game to fit any screen resolution (or window size) (I think it will use `Gdx.gl.glViewport(0, 0, w, h)` and `w`, `h` are calculated by the aspect ratio), although [Viewports](https://github.com/libgdx/libgdx/wiki/Viewports) can deal with different screens, it is far from perfect. 

Should we think in pixels when it comes to their world? According to [Orthographic camera](https://github.com/libgdx/libgdx/wiki/Orthographic-camera), LibGDX recommends us to avoid doing, but nonetheless the "Pixel per unit" ratios exist and I need it in some cases (for example, `Unit.circleSegments(Unit.radius)`.  
I have to solve it by myself like this:
```java
int width = Gdx.graphics.getWidth();
int height = Gdx.graphics.getHeight();

Gdx.gl.glViewport(0, 0, width, height);

springBatch.getProjectionMatrix().setToOrtho2D(0, 0, Unit.VIRTUAL_WIDTH, Unit.VIRTUAL_HEIGHT);
springBatch.begin();
// draw fps at the lower right corner of window
bmpFont.setColor(Color.BLACK);
bmpFont.draw(springBatch, "FPS:" + fps, 0, bmpFont.getLineHeight(), Unit.VIRTUAL_WIDTH, Align.right, false);
springBatch.end();

// All points whose coordinates (x,y) are in the interval [0 640]x[0 480] will be rasterized.
shapeRenderer.getProjectionMatrix().setToOrtho2D(0, 0, Unit.VIRTUAL_WIDTH, Unit.VIRTUAL_HEIGHT);
shapeRenderer.updateMatrices();
shapeRenderer.begin(ShapeRenderer.ShapeType.Line);
shapeRenderer.setColor(Color.BLUE);
shapeRenderer.circle(2 * Unit.radius, 4 * Unit.radius, Unit.radius, Unit.circleSegments(Unit.radius));
shapeRenderer.end();
```
If (w=640, h = 480)  --> (w=1280, h = 960), the font and circle will zoom to 2 times bigger after avoiding unnecessary multiplying and dividing by constants and just using a fixed 2D projection and applying an adjustive viewport.

I find vertical lines and horizontal lines are drawn smoothly no matter what the screen resolution (or window size) is, if I use a fixed 2D projection like the above example code.

In addition, when textures are drawn, they will be scaled up or down and it's tolerant and out of question for me. However, fonts and curves cannot be handled well. The unit of the former size is in pixels like textures and I don't expect they are also scaled up or down like textures because I can dynamically generate use `FreeTypeFontGenerator`, and the latter look like polygons because the window size gets larger so they are scaled up and the number of segments is not enough.
Can I get a chance to draw fonts with a right font size instead of scaling up or down they, at the same time, put fonts in the right place?

#### Reference
* [Viewports](https://github.com/libgdx/libgdx/wiki/Viewports)
* [Orthographic camera](https://github.com/libgdx/libgdx/wiki/Orthographic-camera)
* [Texture Mapping](http://www.glprogramming.com/red/chapter09.html)
* [LearnOpenGL - Coordinate Systems](https://learnopengl.com/Getting-started/Coordinate-Systems)
* [Graphics pipeline](https://en.wikipedia.org/wiki/Graphics_pipeline)
* [Graphics Pipeline & Rasterization](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-837-computer-graphics-fall-2012/lecture-notes/MIT6_837F12_Lec21.pdf)
* Refer to [simple viewport explanation](https://www.opengl.org/discussion_boards/showthread.php/168901-simple-viewport-explanatio):

> Some background reading from the [Redbook online](http://www.glprogramming.com/red/chapter03.html) will be beneficial. Chapter 3 explains all about the connections between viewport + projections + gluLookAt.
> 
> The arguments to Viewport are in pixel units and the rectangle you define with it must be no greater than the actual window itself.
> 
> `glOrtho` maps global X,Y,Z cooridinates to the viewport pixel cooridinates I,J as follows suppose you set
> ```c
> Gl.Viewport(10,20,50,50)
> Gl.glOrtho(0, 34.2, 0, 90.6, -1.0, 1.0)
> ```
> A point at (XYZ)=(0,0,0) would be mapped to the window at the far lower left pixel (IJ)=(10,20) and a point at (XYZ)=(34.2,90.6,0) would be mapped to the upper right window pixel (IJ)=(10+50,20+50). Points outside of the ortho box will simply be clipped ie not plotted to the screen.
> 
> So `glOrtho` allows you to define your global coordinate system in convenient units (ie not in pixels) and points will be automatically mapped back to the viewport pixels -- this is a valuable feature because it is best to avoid thinking in terms of pixels and think in terms of global coordinates appropriate to you model. Typically, the only time you think in terms of pixels is when you set Viewport, and from then on openGL maps your global coordinate system back to the screen for you without you needing to think about pixels again. This is a great help when you allow the window size to change and you only have to change the code accordingly in one spot, the `Gl.Viewport()` settings!

* [How to deal with different aspect ratios in libGDX?](https://stackoverflow.com/questions/9198932/how-to-deal-with-different-aspect-ratios-in-libgdx)
* [KEEP SCREEN ASPECT RATIO WITH DIFFERENT RESOLUTIONS USING LIBGDX](http://acamara.es/blog/2012/02/keep-screen-aspect-ratio-with-different-resolutions-using-libgdx/)

#### Reproduction steps/code
_Even if you think your issue is trivial to reproduce, please supply a [SSCCE](http://sscce.org/) that demonstrates your issue.  This saves time on our end, and makes it much more likely that your issue will be fixed.
You can find barebones templates [here](https://github.com/libgdx/libgdx/wiki/Getting-help)_

#### Version of LibGDX and/or relevant dependencies
gdx-1.9.8

#### Please select the affected platforms
- [x] Android
- [x] iOS (robovm)
- [ ] iOS (MOE)
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by Tom-Ski** [comment]
The best way is to never scale fonts. Using a screen viewport and fonts generated at runtime depending on device resolution. Or use other font rendering techniques like distance field.

**Comment by Fang3s** [comment]
The key issue is that using a fixed 2D projection (coordinate system in 2D world in convenient units) and changing viewport according window size (in pixels) to adapt to fit any window, fonts are magnified so as to become not so sharp and clear when the size of the window become larger.

Now, I find a workaround: regenerate font with a new size and scales the font by the ratio of the current size to the initial size of window/screen using `BitmapFont.BitmapFontData.setScale(float scaleXY)`.
