### ISSUE TITLE
Grammar of SpriteBatch - They are a batch but don't perform batching.

### ISSUE THREAD

**Issue by khlorghaal** [libgdx/libgdx#5146]
I'm new to GDX, coming into a project using it, and suffered lots of confusion over the SpriteBatch objects, which the documentation says do batching. Although they are a batch, they perform no batching; as any state changes other than vertex streaming simply cause a flush.

**Comment by Tom-Ski** [comment]
They batch to the best of their ability. If you break the batching in a way that SpriteBatch can't recover from, it will flush.

**Comment by khlorghaal** [comment]
@Tom-Ski I spent the last hour looking at the code, and the 2d batches simply flush upon any [texture](https://github.com/libgdx/libgdx/blob/4bc504d8b362c3b4b12908e48c355ef3b1c9e64c/gdx/src/com/badlogic/gdx/graphics/g2d/SpriteBatch.java#L1073) or [shader](https://github.com/libgdx/libgdx/blob/4bc504d8b362c3b4b12908e48c355ef3b1c9e64c/gdx/src/com/badlogic/gdx/graphics/g2d/SpriteBatch.java#L1082) change.
[ModelBatch batches blend state](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g3d/utils/DefaultRenderableSorter.java#L50) [but nothing else](https://github.com/libgdx/libgdx/blob/470f4b347cc3da9ecff1ef177819533249a01ea3/gdx/src/com/badlogic/gdx/graphics/g3d/ModelBatch.java#L203).

The SpriteBatch documentation that "The class will batch the drawing commands and optimize them for processing by the GPU." The documentation is claiming the presence of unimplemented features.

**Comment by khlorghaal** [comment]
@NathanSweet

**Comment by Tom-Ski** [comment]
Yes. It batches each sprite draw call into one big mesh, and submits that draw call together. This is exactly what the docs state. On the wiki the documentation is even more extensive. What feature exactly is the documentation claiming it does, which it doesn't?

ModelBatch does not just batch blend state, and what you linked is the sorting for draw order for blending, not the batching.

**Comment by khlorghaal** [comment]
I seem to have misunderstood the definition of batching, I thought it was for minimizing overall render state changes via state sorting instead of just mesh combination.

So in that sense the 2d batchers are grammatically correct. However ModelBatch does have vertex combining functionality, as thats mutex with the prebuilt VBOs it accepts.

**Comment by Tom-Ski** [comment]
For that you want something like ModelCache. It handles merging of sepearate meshes where compatible (materials and vertex layout/blending compatible) Its an expensive operation and shouldn't be done every frame for most use cases.

**Comment by badlogic** [comment]
We will not rename these classes. Sorry.

On Mar 27, 2018 10:37 PM, "khlorghaal" <notifications@github.com> wrote:

I seem to have misunderstood the definition of batching, I thought it was
for minimizing overall render state changes via state sorting instead of
just mesh combination.

So in that sense the 2d batchers are grammatically correct. However
ModelBatch does have vertex combining functionality, as thats mutex with
the prebuilt VBOs it accepts.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/libgdx/libgdx/issues/5146#issuecomment-376666858>, or mute
the thread
