### ISSUE TITLE
Build problem on OSX with JDK10 due to new version numbering

### ISSUE THREAD

**Issue by sutchark** [libgdx/libgdx#5147]
The old version sceme in Java was: java version "1.8.0_161"

With JDK10 they changed it: java 10 2018-03-20

See resulting problems below.

./gradlew ios:launchIPhoneSimulator
Downloading https://services.gradle.org/distributions/gradle-2.14.1-bin.zip

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '10'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

java --version

java 10 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)

**Comment by Tom-Ski** [comment]
This is a limitation of the old Gradle versions. It is fixed in newer versions of Gradle, but these cannot be used as it breaks IDE integration (see other related issues on this tracker). For now, java 10 is not supported officially, you are welcome to update your gradle wrapper version yourself, but there is no official support from us for it.

**Comment by sutchark** [comment]
No problem for me. Just something I noticed and thought I let you guys know.

Gradle 2.14.1 is probably a limitation of only the Android build? Or the iOS build as well?

**Comment by Tom-Ski** [comment]
If you are on command line only, all versions of Gradle are compatible with all the builds. The problem lies with IDE integration.

**Comment by sutchark** [comment]
Yes...only cli.

I am pretty sure though that even the most basic libgdx project won't build with Gradle 4.6 for: gradle android:assemble

FYI. Doesn't matter to me. I stick to the wrapper.

**Comment by Tom-Ski** [comment]
Ah yes, I meant that with a few version tweaks its fine. Latest Gradle versions need a bump of the android plugin. But build should still be the same.

**Comment by sutchark** [comment]
Great work btw...you and a few others rescued RoboVM and kept libgdx alive. I hope keeping RoboVM up-to-date is doable in the long run.
