### ISSUE TITLE
Bitmapfont.draw: wrap text drawn at the wrong position

### ISSUE THREAD

**Issue by QStormDS** [libgdx/libgdx#5150]
#### Issue details
Wrap text is drawn at the wrong position if align is set to center:
![image](https://user-images.githubusercontent.com/6698758/38073018-6f8e5944-3329-11e8-8e03-d5816725b888.png)

Maybe this is releated to the issues #4425, #4970 or #4192, but I am not sure.

I noticed also some other issues:
- dots of the german umlauts (e.g. "Ä", "Ü") are drawn outside the bounds for some fonts
- the lower part of some chars (e.g. "p", "q", "g") are drawn outside the bounds for all fonts (see picture) 

#### Reproduction steps/code
```
public class MyGdxGame extends ApplicationAdapter {

  SpriteBatch batch;
  Texture img;
  TextureRegion texReg;
  BitmapFont font;
  GlyphLayout layout;

  @Override
  public void create() {
    batch = new SpriteBatch();
    layout = new GlyphLayout();
    img = new Texture("blank.png");
    texReg = new TextureRegion(img);
    font = new BitmapFont();
  }

  @Override
  public void render() {
    String text = "Keine Spiele für den gewählten Spielmodus gefunden";
    float targetWidth = 250;
    float xTopLeft = 100;
    float yTopLeft = Gdx.graphics.getHeight() - 5.0f;

    Gdx.gl.glClearColor(Color.WHITE.r, Color.WHITE.g, Color.WHITE.b, Color.WHITE.a);
    Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

    batch.begin();

    // draw the text:
    font.setColor(Color.BLACK);
    layout.setText(font, text, font.getColor(), targetWidth, Align.center, true);
    font.draw(batch, text, xTopLeft, yTopLeft, targetWidth, Align.center, true);

    // draw border to see the desired bounds of the text:
    batch.setColor(Color.RED);
    batch.draw(texReg, xTopLeft, yTopLeft, layout.width, 1);
    batch.draw(texReg, xTopLeft, yTopLeft - layout.height, 1, layout.height);
    batch.draw(texReg, xTopLeft, yTopLeft - layout.height, layout.width, 1);
    batch.draw(texReg, xTopLeft + layout.width, yTopLeft - layout.height, 1, layout.height);

    batch.end();
  }

  @Override
  public void dispose() {
    batch.dispose();
    img.dispose();
    font.dispose();
  }
}
```

#### Version of LibGDX and/or relevant dependencies
1.9.6 and 1.9.8

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X] Windows
- [X] Linux
- [ ] MacOS

**Hint:** I only tested it on Windows and Linux, but it seems to be a genreal issue.

**Comment by NathanSweet** [comment]
Your code wasn't executable and made some wrong assumptions. This should explain:
```
public class MyGdxGame extends ApplicationAdapter {
	SpriteBatch batch;
	BitmapFont font;
	GlyphLayout layout;
	ShapeRenderer shapes;

	public void create () {
		batch = new SpriteBatch();
		layout = new GlyphLayout();
		font = new BitmapFont();
		shapes = new ShapeRenderer();
	}

	public void render () {
		String text = "Keine Spiele für den gewählten Spielmodus gefunden";
		float targetWidth = 250;
		float x = 100;
		float y = 100;

		Gdx.gl.glClearColor(0, 0, 0, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

		layout.setText(font, text, Color.WHITE, targetWidth, Align.center, true);

		batch.begin();
		font.draw(batch, layout, x, y);
		batch.end();

		// Draw target width. The layout height is cap height of first line to baseline of last. Add ascent if you want that.
		shapes.begin(ShapeType.Line);
		shapes.setColor(Color.GREEN);
		shapes.rect(x, y, targetWidth, -(layout.height + font.getAscent()));

		// This doesn't make sense. The text is aligned within targetWidth and may not originate at x, y.
		// shapes.setColor(Color.ORANGE);
		// shapes.rect(x, y, layout.width, -layout.height);

		// Runs also provide bounds information.
		for (GlyphRun run : layout.runs) {
			shapes.setColor(Color.ORANGE);
			shapes.rect(x + run.x, y + run.y, run.width, -(font.getCapHeight() + font.getAscent()));

			float baselineY = y + run.y - font.getCapHeight();
			shapes.setColor(Color.MAGENTA);
			shapes.line(x + run.x, baselineY, x + run.x + run.width, baselineY);
		}

		shapes.end();
	}

	static public void main (String[] args) throws Exception {
		new LwjglApplication(new MyGdxGame());
	}
}
```

**Comment by NathanSweet** [comment]
Also see BitmapFontMetricsTest.

**Comment by QStormDS** [comment]
Thanks for the explanation. Seems that some of the answers at stackoverflow are wrong as they are pointing to GlyphLayout.width and GlyphLayout.height to get the text bounds.

**Comment by NathanSweet** [comment]
The GlyphLayout width/height is correct for bounds. The `targetWidth` alignment/wrapping adjusts the X position, so the bounds may not be positioned at the coordinates passed to `font.draw()`. Usually you don't care about this, since you are probably drawing the text within a container which has a width of `targetWidth`. If you do, you could find the minimal X of the runs. We could store this on GlyphLayout as a `float x` field, but I haven't seen it needed in practice. Usually you either know the width for alignment/wrapping, or you use `targetWidth` of 0 and `Align.left` to compute the width of the text without alignment/wrapping.

**Comment by QStormDS** [comment]
Hi again,
Hopefully it will be noticed as the ticket is already closed. I tried your demo code with several true type fonts. However, the bounds of the glyph runs are not exact. As you can see in the attached image there is an inaccuracy of up to 30 pixel on the right side. Furthermore, some letters like "l", "g" or symbols like ")" are out of the bounds. Where does it come from?

![font](https://user-images.githubusercontent.com/6698758/38326428-133f84b6-3846-11e8-8841-7e1ee98a1c17.png)

I am using the free type font loader (everything else remains the same):

```
String fontname = "LiberationMono-Regular.ttf"; // paraaminobenzoic.ttf | primer print.ttf

    assetManager = new AssetManager();
    final FileHandleResolver resolver = new InternalFileHandleResolver();
    assetManager.setLoader(FreeTypeFontGenerator.class, new FreeTypeFontGeneratorLoader(resolver));
    assetManager.setLoader(BitmapFont.class, new FreetypeFontLoader(resolver));

    final FreeTypeFontLoaderParameter params = new FreeTypeFontLoaderParameter();
    params.fontFileName = Gdx.files.internal(fontname).path();
    params.fontParameters.size = 36;
    assetManager.load(fontname, BitmapFont.class, params);
    assetManager.finishLoading();
```
    font = assetManager.get(fontname, BitmapFont.class);

**Comment by NathanSweet** [comment]
I forget the reason why the top left corner was chosen as the origin for fonts, but I know all the options were considered and there were reasons it was chosen. It's too late to change it now at any rate. Utility methods to draw in ways that make sense for you are good. Note that Y is up in the math world. I had the same problem long ago, but you'll get used to it eventually!

The boxes you are drawing are using the font metrics. A font can report the descent is X but have glyphs the extend further below the baseline. I believe the font is to blame. From a GlyphLayout you can get each GlyphRun, which has an array of Glyphs, which each have positioning and size information. You can use this to find the bounding box that is accurate to a pixel. This is not normally needed for most text layout, so the work is not performed by default.
