### ISSUE TITLE
Recast4j support

### ISSUE THREAD

**Issue by hance** [libgdx/libgdx#5152]
Recast4j is java port of recastnavigation and I havent found the same thing already have in libgdx for the ai nav requirement. will it be supported? take time to feed back, thanks very much.

**Comment by NathanSweet** [comment]
I doubt it makes sense to include this in libgdx. Is anything stopping you from using it alongside libgdx? Why would libgdx need to know about Recast4j?

**Comment by hance** [comment]
sound like u could use bullet physics sideway so everybody easy going as well(it's hard to start a 3d library). it need a lot of work to integrate into libgdx and navmesh is a totally a new concept in current version libgdx which just lack 3d ai features, but everyone using, right now, like ue4 unity

**Comment by crykn** [comment]
I agree with Nate. Recast4j is a fully fledged, separate project. If anyone wants to work on a closer integration with libGDX, feel free to create a third-party library that does this.
