### ISSUE TITLE
A method doesn't return what expected from it.

### ISSUE THREAD

**Issue by oualidouazrou** [libgdx/libgdx#5154]
this [method](https://github.com/libgdx/libgdx/blob/c31fe0ad74a35f4b1e898885615f5b91ee382953/gdx/src/com/badlogic/gdx/graphics/g2d/TextureAtlas.java#L322) return only the regions that have the exact same name, I guess that it should return the regions that contain the same String. this can be fixed by replacing :
`if (region.name.equals(name)) matched.add(new AtlasRegion(region));`
with :
`if (region.name.contains(name)) matched.add(new AtlasRegion(region));`

**Comment by MobiDevelop** [comment]
It returns exactly what it says it will. It returns all indexed regions for the given name. It doesn't make any claims to be doing a partial match.

If you need the behavior you've proposed, you should get all regions and filter by partial match within your application code.
