### ISSUE TITLE
In Android, constantly setting the lookAt method will affect the camera rotation.

### ISSUE THREAD

**Issue by jianwenzhou** [libgdx/libgdx#5159]
Issue details

Through the orientation sensor, set the LookAt method in the PerspectiveCamera to continuously set the X axis and Y axis. The Z axis does not change. After turning the mobile phone many times, the model will be found to be offset, similar to the camera rotation angle.

Reproduction steps/code

import com.badlogic.gdx.graphics.PerspectiveCamera;
import com.badlogic.gdx.math.Quaternion;
import com.richinfo.libgdx.listener.HeadRotationListener;

public class SensorCamera extends PerspectiveCamera implements HeadRotationListener {

    private volatile float[] lookAtVector = new float[3];
    private volatile float[] oldLookAtVector = new float[3];
    private float[] tempLookAtVector = new float[3];
    private OnSensorChangeListener mListener;

    public SensorCamera(float fov, int width, int height) {
        super(fov, width, height);
        this.near = 1f;
        this.far = 100f;
        this.position.set(0f, 0f, 12f);
        this.lookAt(0f, 0f, 0f);
        this.update();
    }

    public void render() { //Constantly calling
        this.lookAt(lookAtVector[0], -lookAtVector[1], lookAtVector[2]);
        this.update();
    }

    public void setLookAtVector(float x, float y, float z) {
        lookAtVector[0] = x;
        lookAtVector[1] = y;
        lookAtVector[2] = z;
    }

    public float[] getLookAtVector() {
        return lookAtVector;
    }

    @Override
    public void update() {
        super.update();
    }

    @Override
    public void update(boolean updateFrustum) {
        super.update(updateFrustum);
    }

    public void dispose() {

    }

    @Override
    public void onRotationChanged(float[] orientation) {
        mListener.onSensorChange(orientation[0], orientation[1]);
        if (orientation[0] > 120 && orientation[0] < 280) {
            lookAtVector[0] = 12;
        } else {
            double cosX = Math.cos(0.5f * Math.PI + (orientation[1] / 180f * Math.PI));
            double sinX = Math.sin(orientation[0] / 180f * Math.PI);
            lookAtVector[0] = (float) (8f * sinX * cosX);
        }

        double cosY = Math.sin(0.5f * Math.PI + (orientation[0] / 180f * Math.PI));
        double sinY = Math.cos(orientation[1] / 180f * Math.PI);
        lookAtVector[1] = (float) (8f * sinY * cosY);
        lookAtVector[2] = 0;
        System.arraycopy(lookAtVector, 0, oldLookAtVector, 0, lookAtVector.length);

    }
Version of LibGDX and/or relevant dependencies

libGDX 1.9.8
Freetype extension checked in libGDX setup app
Please select the affected platforms

 Android

**Comment by piotr-j** [comment]
`lookAt` does a bunch of float math, doing it each frame will add up to noticeable error after a while. Perhaps resetting it to default will help.

**Comment by cypherdare** [comment]
I think it's float error building over time in the `Camera`'s `up` vector. This vector should be set explicitly before calling `lookAt()` if you are calling it repeatedly.
