### ISSUE TITLE
Allow skipProvisioning

### ISSUE THREAD

**Issue by dwaal** [libgdx/libgdx#5160]
Hi,

during development I need to create my IPA without provisioning or signing and do it later in a second step. However robovm doesn't allow this.

Disclaimer: I know there are free provisioning profiles and at the moment I create my IPA this way. Still it is not very optimal for my use case.

I used -Drobovm.iosSkipSigning=true on the gradle command to launch the :ios:createIPA task. Still the robovm task will crash since it wants to do the provisioning and the fitting profile is missing.

Could you add a robovm.iosSkipProvisioning parameter?

**Comment by crykn** [comment]
This seems to be a RoboVM issue and not a libGDX one. So, closing this.
