### ISSUE TITLE
Build windows32 natives cannot find -lpthread

### ISSUE THREAD

**Issue by yuripourre** [libgdx/libgdx#5162]
Hello, I am trying to build windows libgdx native libraries using ant on Fedora 27. I could generate linux (x32 and x64) native libraries without problems but I am have some issues generating windows' natives.

Steps:
Install mingw following: [jnigen](https://github.com/libgdx/libgdx/wiki/jnigen)
Install glibc to crossbuild to 32bits platforms
```
sudo dnf install mingw32-gcc-c++ mingw64-gcc-c++ glibc-devel.i686
```

Clone the repository: 
```
git clone https://github.com/libgdx/libgdx.git
```

Run ant:
```
cd libgdx/gdx/jni/
ant
```

Get the error:
```
Buildfile: /home/user/git/libgdx/gdx/jni/build.xml

compile-natives:

precompile:

create-build-dir:
     [copy] Copying 5 files to /home/user/git/libgdx/gdx/target/native/windows32

compile:

link:
     [exec] /usr/lib/gcc/i686-w64-mingw32/7.2.0/../../../../i686-w64-mingw32/bin/ld: cannot find -lpthread
     [exec] collect2: error: ld returned 1 exit status

BUILD FAILED
/home/user/git/libgdx/gdx/jni/build.xml:13: The following error occurred while executing this line:
/home/user/git/libgdx/gdx/jni/build-windows32.xml:131: exec returned: 1

Total time: 1 second
```

I couldn't find about how libgdx generate native libraries. Any tips?

**Comment by mgsx-dev** [comment]
I made a docker image do build natives for my extension (which link pthread as well) : https://hub.docker.com/r/mgsx/gdx-docker/

you can see what i've installed here (based on ubuntu) : https://github.com/mgsx-dev/gdx-docker/blob/master/Dockerfile

if it can help you ...

**Comment by yuripourre** [comment]
Thank you @mgsx-dev!
I could solve this installing winpthreads mingw packages (I will update the wiki).

Next step is MacOS!
Your docker might be useful!
