### ISSUE TITLE
IsometricTiledMapRenderer Performance Issues

### ISSUE THREAD

**Issue by wdavies973** [libgdx/libgdx#5164]
Please ensure you have given all the following requested information in your report.

#### Issue details
I'm using the IsometricTiledMapRenderer to render a TiledMap. The TiledMap has two different layers, with pixel sizes of 256 x 192 (4:3 aspect ratio for more immersion) and a map size of 80 by 80. When running on Android, my Galaxy S6 handles the map without any trouble, but running on the Galaxy S5 the app is so slow it's unplayable. For example, I put a System.out.println() call in render(), and it gets called about once every 10 seconds when running on the Galaxy S5, but it doesn't crash. I narrowed down the issue to the IsometricTiledMapRenderer.render() line, which is causing the slowness. I'm not sure if this a hardware issue with the Galaxy S5 or maybe my code needs to be more optimized.

Should I be using a TextureAtlas loader for the Tiled Map instead? Are there other performance tweaks I could use to improve the rendering without downscaling the graphics? 

#### Reproduction steps/code
Just normal usage, switching out OrthoganlMapRenderer for IsometricTiledMapRenderer here does the trick: http://www.gamefromscratch.com/post/2014/04/16/LibGDX-Tutorial-11-Tiled-Maps-Part-1-Simple-Orthogonal-Maps.aspx

#### Version of LibGDX and/or relevant dependencies
1.9.7

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
Use GLProfiler and see what your stats are. This is most likely due to a poorly formed atlas resulting in a lot of flushes due to texture swapping between tiles.

**Comment by wdavies973** [comment]
Thanks!
