### ISSUE TITLE
Shader log is not full

### ISSUE THREAD

**Issue by xahon** [libgdx/libgdx#5168]
#### Issue details
`ShaderProgram::getLog()` outputs not full information

#### Version of LibGDX and/or relevant dependencies
1.9.8

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] MacOS

Here is my vertex shader:

```
attribute vec4 a_position;
attribute vec2 a_texCoord0;

uniform mat4 u_projTrans;
uniform sampler2D u_texture;

varying vec4 v_color;
varying vec2 v_texCoords;

void main() {
    gl_Position = u_projTrans * a_position;

    vec2 texSize = textureSize(u_texture, 0);

    vec4 color = texture2D(u_texture, gl_Position.xy / texSize).rgba;
    v_color = color;

    v_texCoords = a_texCoord0;
}
```

This is code responsible for shader adding to batch via `Batch::setShader`

        if (!shaderProgram.isCompiled()) {
            throw new GdxRuntimeException(shaderProgram.getLog());
        }

        String log = shaderProgram.getLog();
        if (log.length() > 0) {
            Gdx.app.error("ShaderError", "Shader compilation log: " + log);
        }

Issue in my shader that i pass wrong parameters in line ` vec2 texSize = textureSize(u_texture, 0);`

Here is output of libgdx:

> Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Vertex shader
> 0:13(17): error: no matching function for call to `textureSize(sampler2D, int)'; candidates are:
> 0:15(53): warning: `texSize' used uninitialized
> 
> ... Stacktrace ....

Line after candidates is truncated. I can't see what candidates are

Is there `verbose` mode for shader program or it's an issue?

**Comment by Darkyenus** [comment]
`getLog()` retrieves data directly from the GPU drivers and Gdx.appl.logging does not do any truncating. Where are you seeing the outputs? Console, IDE? Maybe that is what truncates the output. (Or perhaps what you see is the full log...)

**Comment by xahon** [comment]
@Darkyenus in Intellij idea's terminal

**Comment by Tom-Ski** [comment]
Can't reproduce. Also as @Darkyenus says, this comes directly from the gpu. Perhaps try command line?
