### ISSUE TITLE
Default 3D shader rendering broken in Android only  (1.9.9-SNAPSHOT)

### ISSUE THREAD

**Issue by Laurent1967** [libgdx/libgdx#5169]
Hi,

I'm developing a game with 2D and 3D rendering using the default LibGdx shaders.
Since the last pulls of 1.9.9-SNAPSHOT, the rendering in 3D (using ModelBatch) is broken in Android with a diffuse "white lightening" covering the whole stage (see picture). The results are the same using Android SDK from 19 to 26, either on emulators or a real device. Note this issue affects ONLY Android builds with 1.9.9-SNAPSHOT. Desktop and IOS (roboVM) are working fine on 1.9.9-SNAPSHOT, as Android with 1.9.8. HTLM platform not tested.

Reproduction steps/code
Compile any 3D LibGdx application for Android with the last 1.9.9-SNAPSHOT using Android Studio.

Version of LibGDX and/or relevant dependencies
LibGDX 1.9.9-SNAPSHOT

Please select the affected platforms
- [X] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

The picture shows the issue in an Android Simulator (left) and the same application correctly displayed on Desktop (right). The tricolor pie on top is correctly displayed in 2D (ShapeRenderer and 2D stage / Actor). Note the left screenshot is mirrored, but this is a not a bug in LIbGDX ! Only screenshot bad manip. 
![screenshot_1523173522](https://user-images.githubusercontent.com/20874224/38465038-4dd0fb9a-3b17-11e8-931c-bb5c1500d658.png)

**Comment by Tom-Ski** [comment]
Can you provide the materials you are using for your objects?

**Comment by Tom-Ski** [comment]
That material has an emissiveColor of 969696ff

**Comment by Laurent1967** [comment]
These emissive colors are settings coming from Blender, but they are not taken into account (until now ...) by LibGdx. Anyway, either reimporting the model from blender after deleting them or replacing the UV texture by a simple black color doesn't change anything
`model.materials.get(0).set(new` Material(ColorAttribute.createDiffuse(Color.BLACK)));`

**Comment by Tom-Ski** [comment]
Yes, because we just added support, so that attribute would just sit there. Can you try removing the emissive Color attribute at runtime before creating an instance ? Also can you supply the fbx or blend file for your skybox.On 8 Apr 2018 19:39, Laurent Crenier <notifications@github.com> wrote:These emissive colors are settings coming from Blender, but they are not taken into account (until now ...) by LibGdx. Anyway, either reimporting the model from blender after deleting them or replacing the UV texture by a simple black color doesn't change anything
model.materials.get(0).set(new Material(ColorAttribute.createDiffuse(Color.BLACK)));`

**Comment by Laurent1967** [comment]
Ha ha ! Well done Tom-Ski !

By removing the material at runtime before setting the UV Texture, it works !


```
model = world.assets.get("models3D/skydome.g3db", Model.class);
model.materials.get(0).clear();
model.materials.get(0).set(material);
```

So probably my new fbx testing exportation from Blender was still carrying these attributes (I've to check that). I'm happy with that, but the remaining issue is then that the emissive support is only working for android and not for the other platforms 😀

**Comment by EtK2000** [comment]
Emissive works for me on desktop.
Try cleaning your desktop project and rebuilding.
