### ISSUE TITLE
Upgrading to Gradle 4.6

### ISSUE THREAD

**Issue by Tom-Ski** [libgdx/libgdx#5177]
Tracker for progress upgrading LibGDX to 4.6, replaces https://github.com/libgdx/libgdx/issues/4698

**LibGDX internally**
- [x] Documentation

_Test todos:_
- [x] Shell
- [x] Intellij
    - Known issues:
        - Resources are not being inherited
- [x] Eclipse
- [x] Android Studio
- [ ] Netbeans

**Generated projects:**
 - [ ] Experiement with moving asset dir

_Test todos:_
- [x] Shell
- [x] Intellij
- [x] Eclipse
- [x] Android Studio
- [ ] Netbeans

**Comment by mustii82** [comment]
Dont forget #4955

**Comment by Tom-Ski** [comment]
It is listed in the issue.

**Comment by mustii82** [comment]
any news?

**Comment by keturn** [comment]
desktop/build.gradle raises this deprecation:

> Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0.

I *think* that all that is necessary is changing the `sourceSets.main.output.classesDir` to `sourceSets.main.output.classesDirs` (plural), but I don't know this build system well, so don't take my word for it.

Though maybe we should get this Gradle 4.x support released before we start worrying about deprecations for Gradle 5.

**Comment by mustii82** [comment]
Yeah working for me with the latest gdx-setup can be closed
