### ISSUE TITLE
Unable to open numeric keyboard by code

### ISSUE THREAD

**Issue by DeRealMorgan** [libgdx/libgdx#5179]
You cant open the numeric soft keyboard by code when clicking on a textfield. This leaves the user with a complete keyboard while they are only allowed to use the digits 0-9 (specified by me: .setTextFieldFilter(new CustomTextField.TextFieldFilter.DigitsOnlyFilter());.

**Comment by MrStahlfelge** [comment]
See PR #5201

**Comment by MrStahlfelge** [comment]
Fixed by #6235
