### ISSUE TITLE
Actor Z-index method does not change order in which Actors are rendered in a Scene2D stage

### ISSUE THREAD

**Issue by julienvillegas** [libgdx/libgdx#5180]
#### Issue details
Actors within a Scene2D stage ought to be rendered according to their Z-index value.
An actor with a higher Z-index value should be rendered on top of another actor with a lower value.
Currently, setting the Z-index value does not change the rendering order, the order is set by the order in which Actors are added to the stage.

Sample code below should render blue image (Z-index:4) in front of green image (Z-index:3). instead it renders the other way around, that is in the order the actors have been added to the stage as shown [here](https://imgur.com/a/krdgXHH)

#### Reproduction steps/code
Run sample code below with two png in asset folder: green.png and blue.png

#### Version of LibGDX and/or relevant dependencies
1.9.8

#### Sample code

```java
package com.mygdx.game;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Image;
import com.badlogic.gdx.utils.viewport.ScreenViewport;

public class MyGdxGame extends ApplicationAdapter {

	private Stage stage;
	
	@Override
	public void create () {
		stage = new Stage(new ScreenViewport());

		Texture textureBlue = new Texture(Gdx.files.internal("blue.png"));
		Texture textureGreen = new Texture(Gdx.files.internal("green.png"));

		Image blueImage = new Image(textureBlue);
		blueImage.setPosition(Gdx.graphics.getWidth()/2-blueImage.getWidth()/2,Gdx.graphics.getHeight()/2-blueImage.getHeight()/2);
		blueImage.setZIndex(4);
		stage.addActor(blueImage);


		Image greenImage = new Image(textureGreen);
		greenImage.setPosition(Gdx.graphics.getWidth()/3-greenImage.getWidth()/2,Gdx.graphics.getHeight()/3-greenImage.getHeight()/2);
		greenImage.setZIndex(3);
		stage.addActor(greenImage);


	}

	@Override
	public void render () {
		Gdx.gl.glClearColor(1, 1, 1, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		stage.act();
		stage.draw();
	}
}
```

#### Please select the affected platforms
- [x] Android
- [x] iOS (robovm)
- [x] iOS (MOE)
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by NathanSweet** [comment]
As specified in the javadocs, an actor's z-index is its index in the parent children array. Setting a z-index does work, but must be between 0 and `actor.getParent().getChildren().size - 1`. Setting a higher z-index will move it to the end of the children array.

**Comment by NathanSweet** [comment]
I think the only reason it was done that way it is now is for simplicity. The parent's children are used for draw order. If a zindex property were added, the children array and zindex could get out of sync.

It doesn't have to be in Actor, you could add a zindex property to your actors and sort the parent's children using that.

**Comment by NathanSweet** [comment]
Note your proposal may cause problems for existing code, eg if code assumes an actor's z-index can be used as an index into the parent's children array.

**Comment by julienvillegas** [comment]
Thanks Nathan. Ok, So I can close this isue.
