### ISSUE TITLE
GLSurfaceView20 translucent parameter is useless

### ISSUE THREAD

**Issue by jingpeng** [libgdx/libgdx#5184]
Please ensure you have given all the following requested information in your report.

#### Issue details
GLSurfaceView20 translucent parameter is useless

#### Reproduction steps/code
public GLSurfaceView20 (Context context, boolean translucent, int depth, int stencil, ResolutionStrategy resolutionStrategy) {
    super(context);
    this.resolutionStrategy = resolutionStrategy;
    init(translucent, depth, stencil);
}

#### Version of LibGDX and/or relevant dependencies
gdx-backend-android-1.9.8

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
Not enough information. Translucent param works as intended.
