### ISSUE TITLE
No way to update 3D particles with delta

### ISSUE THREAD

**Issue by EtK2000** [libgdx/libgdx#5193]
This functionality exists in 2D particles afaik.
The lack of this functionality causes particles to simulate at different speeds based off fps even if the game compensates for this by calling update multiple times (when required).

**Comment by mgsx-dev** [comment]
I think it was fixed recently : https://github.com/libgdx/libgdx/commit/24d8be05043e0b7613ca0999d0fa961297814a5b

**Comment by EtK2000** [comment]
Oh...
I'm surprised I didn't see that.
That's for pointing it out!
