### ISSUE TITLE
Question: Collection methods: isEmpty() / nonEmpty()

### ISSUE THREAD

**Issue by TCreutzenberg** [libgdx/libgdx#5196]
Would you guys be interested to have .isEmpty() / .nonEmpty() methods like e.g. in Scala for the custom LibGDX collections? It is so inconvenient to write e.g. "array.size == 0" or "array.size > 0" all the time...

I am more than happy to provide a pull request for that, but I just want to ask in advance so I don't do the work for nothing.
Also I am asking because this pull-request will affect about 20 files, which would be too many to be merged according to the contribution details.

Please let me know, thank you!

**Comment by mgsx-dev** [comment]
did you read this : https://github.com/libgdx/libgdx/pull/3482 ?

**Comment by TCreutzenberg** [comment]
Ah, I searched but actually didn't find this...

When you use LibGDX with Scala though it would be great to be able to use the "same" methods for custom LibGDX collection as you would for Scala collections.

After reading https://github.com/libgdx/libgdx/pull/3482 I do have some questions.
- Why are extra methods/method calls such a bad thing? Will this cause any performance problems?
- People coming from Scala will miss these methods for collections
- Why is it bad to include these methods if some people like them? Why is this not good reasoning Please enlighten me, I really don't understand this.

**Comment by NathanSweet** [comment]
Avoiding use of the method internally makes adding `isEmpty` pretty OK. I agree it can be less annoying to type and makes the intent clear.

`nonEmpty` is a bit clunky because it has a negative. Copying what Scala does isn't important to me. Any better ideas? `hasItems`?

**Comment by TCreutzenberg** [comment]
Pull request was merged, issue can be closed i guess.
