### ISSUE TITLE
Huge compilation bottleneck because of the gradle architecture used.

### ISSUE THREAD

**Issue by LaP0573** [libgdx/libgdx#5203]
#### Issue details
We noticed a massive performance problem related to the gradle architecture used by LibGDX projects. Basically, compile times on desktop (and everything unrelated to android, so HTML, ios, etc) are way too high BECAUSE of android.

This is happening both on old versions of Gradle (like the one packed with LibGDX projects) and new Gradle versions (we upgraded to 4.7 and did the necessary modifications to the LibGDX project). 

Here is a quick rundown of tests :
- Running DesktopLauncher without having modified any files in core (so no compilation needed) : **3 seconds** of compilation.
- Running DesktopLauncher while having modified one line in a class in core (the line having little to no dependencies, so the compilation should be almost as fast as if nothing changed) : **24 seconds** of compilation.

We stumbled upon this as we wanted to optimize our compile times. We have a sizable commercial project and our compile times were beginning to be unsufferable : 24 seconds on my desktop, about 10-15 seconds on my MacBook. Just for compiling desktop for minimal changes.

After some tests, we noticed this was related to Android. Here are our results after both removing 'android' from the root settings.gradle and removing the whole project(":android") from the root build.gradle :
- Running DesktopLauncher without having modified any files in core (so no compilation needed) : **3 seconds** of compilation.
- Running DesktopLauncher while having modified one line in a class in core : **4 seconds** of compilation.

As you can see, removing (in a rather brutal way) the dependencies to the android module made us reach "normal" results for desktop compilation. So the problem comes from the android module.

We dived into Gradle (we had little to no knowledge about it before) to understand the problem, and it's actually very simple : the way the LibGDX project is configured for Gradle causes the problem.

When running Desktop:run (or DesktopLauncher), Gradle runs the whole root build.gradle file. And it goes through the ":android": block, which applies the android plugins. And these plugins destroy the compilation performance (we don't know why, maybe Gradle for android is just terrible since the Google Gradle android plugin seems very iffy). When commenting the two apply plugin lines (and emptying the build.gradle file of the android module, otherwise it won't sync) the compilation slowness disappears. As soon as one of the two plugins is applied ('android' or 'com.android.application'), boom, compilation is horrible.

That's actually a big problem. This means that the desktop subproject, in Gradle, is "linked" to the android subproject while the two should be 100% separate. Both rely on core, but they should have absolutely nothing to do with each other. Same thing goes for every other module (html, ios) but we ran our tests on desktop.  And in our case, with a sizeable codebase and project heavy with SDKs and dependencies, this becomes a big big problem for compilation times.

#### Reproduction steps/code
We can't supply reproduction code, only the steps above. You can't really reproduce it on a brand new LibGDX project because it's so small and fast, everything goes super fast and the issue isn't noticeable. It seems to only be noticeable on medium-large codebases. 

#### Version of LibGDX and/or relevant dependencies
LibGDX 1.9.6
Gradle 4.7
Android Gradle plugin 3.2.0-alpha10
IntelliJ 2018.1.2

#### Please select the affected platforms
- [ ] Android
- [x] iOS (robovm)
- [x] iOS (MOE)
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

#### Possible solution
We don't have any perfect solution, because our knowledge of Gradle isn't perfect. From the looks of it, the standard LibGDX gradle architecture needs to be rethought from the ground up. Right now everything is crammed into the root build.gradle and everything is together in general (the root settings.gradle includes everything). This would need to change and to be rethought.

In the meanwhile, we fixed the issue in our project so that we once again can have fast compilation times. Our fix isn't the cleanest, but it's the least intrusive given the current state of things. Here is a detailed rundown of it :

**Comment by Tom-Ski** [comment]
You should be using configure on demand. You should also be removing gradle facets from your IDE. This is an ongoing bug caused by improper handling of gradle projects in android studio and intellij.

For now the best work around is to manually remove these facets from your IDE to restore fast compilations.

**Comment by LaP0573** [comment]
@Tom-Ski We already have configure on demand on, how should we go about setting it up for this specific case ? Mind giving a very quick rundown of this facets removal process ?

**Comment by Tom-Ski** [comment]
Go into project structure, check out facets and remove all facets apart from the stock android one. You should have 0 gradle facets. Run a project wide build from the drop down, and then try to run your desktop launcher again.

**Comment by LaP0573** [comment]
Alright, that seems to be working and to achieve the same result as our workaround. However there's one issue, every time the IDE is restarted the facets are re-created as well. Is there a way to avoid this behaviour ?

**Comment by Tom-Ski** [comment]
Not that I could find no. Restart shouldn't restore these facets, but a gradle sync will.

**Comment by LaP0573** [comment]
Alright, we will stick to our workaround then since we regularly sync Gradle.

Isn't the fact that IntelliJ creates all these Android facets for everything related to the fact that android-gradle plugin is used for the whole project (instead of just for android) ? In which case maybe moving this specific dependency into android and letting regular gradle handle stuff like desktop would be the solution ?

**Comment by Tom-Ski** [comment]
It isn't, it is only applied to the android project. This is an issue with IDEA/AS.

**Comment by Tom-Ski** [comment]
see https://youtrack.jetbrains.com/issue/IDEA-122904 for tracked and confirmed issue.
