### ISSUE TITLE
LibGDX ignore image / jpeg EXIF orientation

### ISSUE THREAD

**Issue by doit-ceo** [libgdx/libgdx#5206]
#### Issue details
Mobile camera, capture and store pixmap data as always landscape, and it just store info about the rotation in EXIF "orientation", ignoring those data will result in loading images rotated 90 degree 

![selection_751](https://user-images.githubusercontent.com/8027780/39516309-3ff28a24-4e05-11e8-92da-aee70cd52992.png)

#### Reproduction steps/code
Take a camera picture from Android / iOS in Portrait mode and try to load it in LibGDX

#### Test Image 
Browsers may also not honoring the jpeg exif orientation?

![20180502_121404](https://user-images.githubusercontent.com/8027780/39516463-b63f7d90-4e05-11e8-9c77-11dbe8ca3682.jpg)

#### Version of LibGDX and/or relevant dependencies
1.9.8

#### Please select the affected platforms
- [X] Android
- [X] iOS (robovm)
- [X] iOS (MOE)
- [X] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by oswsozmo** [comment]
remove

**Comment by yuripourre** [comment]
I don't think libgdx should handle EXIF information. But you can implement it using (this library)[https://drewnoakes.com/code/exif/].

**Comment by NathanSweet** [comment]
Agreed, probably best to read the EXIF info yourself and rotate when needed.
