### ISSUE TITLE
LWJGL3 backend crash ([libpthread.so.0+0x9d44]  pthread_mutex_lock+0x4)

### ISSUE THREAD

**Issue by egordorichev** [libgdx/libgdx#5208]
Hello. I've switched to LWJGL 3 backend today, because of proper hotplugging support for controllers. The app runs fine in Intellij IDEA, but once I build a jar with `./gradlew desktop:dist` I get the following crash (when running the jar):

```
Loading settings...
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff5ee29cd44, pid=8793, tid=0x00007ff5eb557700
#
# JRE version: OpenJDK Runtime Environment (8.0_162-b12) (build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12)
# Java VM: OpenJDK 64-Bit Server VM (25.162-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libpthread.so.0+0x9d44]  pthread_mutex_lock+0x4
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/egor/Dungeon/hs_err_pid8793.log
Setting random seed to 1525433299144...
Loading locale...
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Aborted (core dumped)
```

Never happened to me before, and I did not find almost any info about this crash cause. I have no gdx-tools included in the project.

Thanks for your time, Egor.

**Comment by egordorichev** [comment]
@Darkyenus sorry, totally forgot about that :/ Here is the paste: https://pastebin.com/0ghkdyuQ

**Comment by Darkyenus** [comment]
Sadly, I don't see anything useful in it. Your best bet is to attach a debugger and step the code until you find on which line it crashes. If attaching a debugger prevents the problem from appearing, you will probably have to resort to "println" search :/ 

(You can start the jar with debugger with `java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005 -jar your-file.jar` and attach the debugger through IntelliJ's Remote configuration)
