### ISSUE TITLE
BoundingBox always includes (0,0,0) as part of bounds.

### ISSUE THREAD

**Issue by raver1975** [libgdx/libgdx#5216]
The current implementation of com.badlogic.gdx.math.collision.BoundingBox always includes the point (0,0,0) as part of the boundary.  For instance, if the the bound values are all negative, then the max vector's values are always (0,0,0) and can never become negative to reflect the true value of the bounds.

My quick fix for this was to set the initial min vector's x,y,z values to Float.POSITIVE_INFINITY and the max vector's x,y,z values to Float.NEGATIVE_INFINITY

**Comment by yuripourre** [comment]
@raver1975 can you provide an example? I don't think it is still happening.

**Comment by NathanSweet** [comment]
Can reopen if reproduction is given.
