### ISSUE TITLE
Snapshot builds aren't being released

### ISSUE THREAD

**Issue by EtK2000** [libgdx/libgdx#5221]
No snapshots since April 22nd.
I thought this had to do with Jenkins, but @badlogic said that's fixed.

**Comment by MobiDevelop** [comment]
Seems to be resolved as Sonatype has the latest snapshot occuring today.

https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/gdx/gdx/1.9.9-SNAPSHOT/

**Comment by EtK2000** [comment]
Yay!!
