### ISSUE TITLE
In Android O ,the power key make AndroidFragmentApplication#onPause timeout exception

### ISSUE THREAD

**Issue by ghost** [libgdx/libgdx#5224]
In my Android O devices,called MI 6,when I pressed the power key,making screen off,it makes AndroidFragmentApplication#onPause methed invoked ,but throws pause timeout exception and crashed

**Comment by Tom-Ski** [comment]
Can you provide a minimal case that reproduces this? I see no issue on my O device.

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info
