### ISSUE TITLE
Registration to Forum not working

### ISSUE THREAD

**Issue by WhiteBonsai** [libgdx/libgdx#5226]
#### Issue details
You cannot registrate a new account or get your passwort send to your mail adress as you have to complete a captcha: Name the last official libgdx version. - the provided link is not working at all. 
Searching for the last version: "1.9.8" is not working either.

**Comment by yuripourre** [comment]
I was confused too but reading carefully I understood that the answer should be *8.9.1*.

**Comment by WhiteBonsai** [comment]
Yes I figured it out, my bad. 

The provided link still isnt working.

**Comment by xoppa** [comment]
The [link](https://libgdx.badlogicgames.com/versions.html) seems to be fine to me. Anyways. let's close this.
