### ISSUE TITLE
removed jglfw

### ISSUE THREAD

**Issue by TaiVuong** [libgdx/libgdx#5227]
https://github.com/libgdx/libgdx/blob/2fa65826fa24d44d6e4083e3b615eb036bdb8ad7/fetch.xml#L159

**Comment by yuripourre** [comment]
@TaiVuong
What do you mean? I don't get it.
This line should be removed?

**Comment by TaiVuong** [comment]
i can not build because it try to download that lib but it is missing.
http://libgdx.badlogicgames.com/jglfw/nightlies/dist/jglfw-natives.jar
