### ISSUE TITLE
SelectBox Javadoc is wrong

### ISSUE THREAD

**Issue by Darkyenus** [libgdx/libgdx#5229]
[`SelectBox.getItems()`](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/SelectBox.java#L164) proclaims that `"If modified, {@link #setItems(Array)} must be called to reflect the changes."`, however this can't ever work, because [`setItems(Array)`](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/SelectBox.java#L148) clears `items`, which clears any modification done on `getItems()` `Array`.

I don't have time to look into this right now, but I believe that this pattern of `setItems(getItems())` is already present somewhere in libGDX and I am in favor of keeping it, because it can be useful (rather than fixing docs).

When fixing, scene2d should be searched whether this error appears somewhere else as well, as it looks like a copy-paste error.

**Comment by NathanSweet** [comment]
Looks like it is just in SelectBox. I'll copy what List does.
