### ISSUE TITLE
MathUtils.lerp weirdness

### ISSUE THREAD

**Issue by Skrelpoid** [libgdx/libgdx#5243]
Sorry I'm not using the template but after looking through some code, I found something weird.
MathUtils.lerp can return something bigger than toValue. Shouldn't it just return toValue if the calculated return value is greater than toValue?

**Comment by Skrelpoid** [comment]
Maybe add additional method lerpClamp where you do p = MathUtils.clamp(0, 1)
Or something  similar as this caused unexpected behaviour for me

**Comment by mgsx-dev** [comment]
@Skrelpoid i think it's better to handle it in your own code since it's not a common case.
I think most of devs expect extrapolation beyond 0-1 range. Adding a new method  lerpClamp is not so usefull, it still easy to clamp before interpolation.

**Comment by Skrelpoid** [comment]
@mgsx-dev You're right, This is easy enough. No need for this issue anymore
