### ISSUE TITLE
Skin not loading without fully qualified class   

### ISSUE THREAD

**Issue by simaipeter** [libgdx/libgdx#5248]
#### Issue details
Tried to load test uiskin.json, got these errors. I read in a commit about class tags    
https://github.com/libgdx/libgdx/pull/4293

#### Reproduction steps/code
 Skin skin = new Skin(Gdx.files.internal("uiskin.json"));
From-test
```

{

BitmapFont: { default-font: { file: default.fnt } },
Color: {
	green: { a: 1, b: 0, g: 1, r: 0 },
	white: { a: 1, b: 1, g: 1, r: 1 },
	red: { a: 1, b: 0, g: 0, r: 1 },
	black: { a: 1, b: 0, g: 0, r: 0 },
},
TintedDrawable: {
	dialogDim: { name: white, color: { r: 0, g: 0, b: 0, a: 0.45 } },
},
ButtonStyle: {
	default: { down: default-round-down, up: default-round },
	toggle: { parent: default, checked: default-round-down }
},
TextButtonStyle: {
	default: { down: default-round-down, up: default-round, font: default-font, fontColor: white },
	toggle: { parent: default, checked: default-round-down, downFontColor: red }
},
ScrollPaneStyle: {
	default: { vScroll: default-scroll, hScrollKnob: default-round-large, background: default-rect, hScroll: default-scroll, vScrollKnob: default-round-large }
},
SelectBoxStyle: {
	default: {
		font: default-font, fontColor: white, background: default-select,
		scrollStyle: default,
		listStyle: { font: default-font, selection: default-select-selection }
	}
},
SplitPaneStyle: {
	default-vertical: { handle: default-splitpane-vertical },
	default-horizontal: { handle: default-splitpane }
},
WindowStyle: {
	default: { titleFont: default-font, background: default-window, titleFontColor: white },
	dialog: { parent: default, stageBackground: dialogDim }
},
ProgressBarStyle: {
	default-horizontal: { background: default-slider, knob: default-slider-knob },
	default-vertical: { background: default-slider, knob: default-round-large }
},
SliderStyle: {
	default-horizontal: { background: default-slider, knob: default-slider-knob },
	default-vertical: { background: default-slider, knob: default-round-large }
},
LabelStyle: {
	default: { font: default-font, fontColor: white }
},
TextFieldStyle: {
	default: { selection: selection, background: textfield, font: default-font, fontColor: white, cursor: cursor }
},
CheckBoxStyle: {
	default: { checkboxOn: check-on, checkboxOff: check-off, font: default-font, fontColor: white }
},
ListStyle: {
	default: { fontColorUnselected: white, selection: selection, fontColorSelected: white, font: default-font }
},
TouchpadStyle: {
	default: { background: default-pane, knob: default-round-large }
},
TreeStyle: {
	default: { minus: tree-minus, plus: tree-plus, selection: default-select-selection }
},
TextTooltipStyle: {
	default: {
		label: { font: default-font, fontColor: white },
		background: default-pane, wrapWidth: 150
	}
},
}
`
```

#### Version of LibGDX and/or relevant dependencies
Latest

#### Stacktrace
```

`Executing: gradle :desktop:run
Arguments: [-PcmdLineArgs=, -PjvmLineArgs=, -c, C:\Users\SPL\szo\settings.gradle]

WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.
It will be removed at the end of 2018
:core:compileJava UP-TO-DATE
:core:processResources NO-SOURCE
:core:classes UP-TO-DATE
:core:jar UP-TO-DATE
:desktop:compileJava UP-TO-DATE
:desktop:processResources NO-SOURCE
:desktop:classes UP-TO-DATE
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.SerializationException: Error reading file: uiskin.json
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.load(Skin.java:98)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.<init>(Skin.java:75)
	at com.mygdx.game.myMenu.<init>(myMenu.java:29)
	at com.mygdx.game.Szo.create(Szo.java:28)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: com.badlogic.gdx.utils.SerializationException: Error reading file: uiskin.json
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:711)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.load(Skin.java:96)
	... 5 more
Caused by: com.badlogic.gdx.utils.SerializationException: 
	at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.read(Skin.java:440)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.read(Skin.java:434)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:903)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin$1.readValue(Skin.java:428)
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:709)
	... 6 more
Caused by: com.badlogic.gdx.utils.reflect.ReflectionException: Class not found: BitmapFont
	at com.badlogic.gdx.utils.reflect.ClassReflection.forName(ClassReflection.java:30)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.read(Skin.java:438)
	... 10 more
Caused by: java.lang.ClassNotFoundException: BitmapFont
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.badlogic.gdx.utils.reflect.ClassReflection.forName(ClassReflection.java:28)
	... 11 more
:desktop:run

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 12s
4 actionable tasks: 1 executed, 3 up-to-date
````

- [x] Windows

**Comment by NathanSweet** [comment]
>at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.read(Skin.java:438)
Skin:438 is blank. Your libgdx must not be up to date.
https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Skin.java#L438

**Comment by simaipeter** [comment]
`buildscript {
    

    repositories {
        mavenLocal()
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0'
        

    }
}

allprojects {
    apply plugin: "eclipse"
    apply plugin: "idea"

    version = '1.0'
    ext {
        appName = "szo"
        gdxVersion = '1.9.8'
        roboVMVersion = '2.3.3'
        box2DLightsVersion = '1.4'
        ashleyVersion = '1.7.0'
        aiVersion = '1.8.0'
    }

    repositories {
        mavenLocal()
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url "https://oss.sonatype.org/content/repositories/releases/" }
    }
}

project(":desktop") {
    apply plugin: "java"


    dependencies {
        compile project(":core")
        compile "com.badlogicgames.gdx:gdx-backend-lwjgl:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
        compile "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-desktop"
        
    }
}

project(":android") {
    apply plugin: "android"

    configurations { natives }

    dependencies {
        compile project(":core")
        compile "com.badlogicgames.gdx:gdx-backend-android:$gdxVersion"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-armeabi"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-armeabi-v7a"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-arm64-v8a"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-x86"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-x86_64"
        compile "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
        natives "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-armeabi"
        natives "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-armeabi-v7a"
        natives "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-arm64-v8a"
        natives "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-x86"
        natives "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-x86_64"
        
    }
}

project(":core") {
    apply plugin: "java"


    dependencies {
        compile "com.badlogicgames.gdx:gdx:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
        
    }
}

tasks.eclipse.doLast {
    delete ".project"
}`

**Comment by Tom-Ski** [comment]
If you are using the test skin from this repo, you should be using the snapshot versions of LibGDX. You are using last release, so you should go back to 1.9.8 tag and download the test skin from there.
