### ISSUE TITLE
com/badlogic/gdx/utils/async/ThreadUtils.java is pointless

### ISSUE THREAD

**Issue by EtK2000** [libgdx/libgdx#5249]
This class has a function that calls Thread.yield that's all.

Is there any reason this class exists?
If not I'd advise removing it.

**Comment by NathanSweet** [comment]
Did you search for it?
https://github.com/libgdx/libgdx/blob/master/backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/utils/async/ThreadUtils.java

**Comment by EtK2000** [comment]
I don't know how I missed that.
I feel dumb.

**Comment by Darkyenus** [comment]
It's easy to miss it. There are many such duplicates to work around GWT's limitations, such as reflection utils.
