### ISSUE TITLE
Exception in thread "main" java.awt.HeadlessException

### ISSUE THREAD

**Issue by Zarandor** [libgdx/libgdx#5250]
#### Issue details
I have to explain the context first. I try to launch my game on a set-top-box connected to a TV.
The OS of the box is Ubuntu 12.04.5 LTS. My game works well on this version of the OS that I have installed on my computer but not on the box.
After some digging I found out that the Ubuntu embedded has no graphical environment (no X11).
Another precision: I used packr and the executable made just quit with the message "Destroyed Java VM...". 
By launching it through java -jar mygame.jar I have the error message you can see in the Stacktrace section.
So what I understand is that the jre (LWJGL, JavaFX, and Java GUI) doesn't work because there's no graphical server.

And because I'm no expert on Unix system here are my questions:
- Is is to possible to add X11 the same way we add the JRE to the game when we pack it for desktop ? 
- Then launch it before the game in order for the JRE to use it ?
- Is is the right way to work around this problem ? 
What I can't do is install X.org on the box, so I'm looking for a way to extend the box OS from the files provided with my game to enable the JRE to work.

Another precision is that I have a "hello world" for the box that uses native code (in C) to create an OpenGL 2 context to display stuff and the main file of this program is called "hello-wayland.c"

So I'm looking for advices on how I can get over this issue.
Thanks for your help.

#### Reproduction steps/code
The box is connected to a monitor. I do a remote login on the box through ssh and launch my game by doing a simple java -jar game.jar

#### Version of LibGDX and/or relevant dependencies
1.9.8
packr 2.0 and packr 2.1

#### Stacktrace
```
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at sun.java2d.HeadlessGraphicsEnvironment.getDefaultScreenDevice(HeadlessGraphicsEnvironment.java:77)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration.getDesktopDisplayMode(LwjglApplicationConfiguration.java:140)
	at com.my.game.desktop.DesktopLauncher.main(DesktopLauncher.java:139)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [X ] Linux
- [ ] MacOS

**Comment by Darkyenus** [comment]
Try LWJGL3 backend. If that doesn't help, you are probably out of luck :/

**Comment by Zarandor** [comment]
Hi,
thank you for the suggestion but unfortunately the box is a 32 bits machine and LWJGL3 has no support 32 bits support.
