### ISSUE TITLE
Translation not properly working into 3D model in libgdx android. 

### ISSUE THREAD

**Issue by mayurviras** [libgdx/libgdx#5265]
I have to develop the Augmented reality app using libgdx and ARToolKit. In this app, I have to perform translation action into 3d model. and I face one issue there is after performing translation action the 3D model is rotated into the whole screen. I can not perform rotation action properly rotation into 3D model.so, please tell me the proper way to the translation of  3D model.

**Comment by Tom-Ski** [comment]
Please see
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
