### ISSUE TITLE
Xcode [9.0] or later required from July onward

### ISSUE THREAD

**Issue by julienvillegas** [libgdx/libgdx#5267]
#### Issue details
When uploading an app to iTune Connect for iOS I get the following warning.
This is not blocking yet (until July) but given that we are mid June, it means that in a couple of weeks I won't be able to upload new versions. Since I am using XCode 9.4 I think the error message is incorrect and it might be about how the library is working:

_We identified one or more issues with a recent delivery for your app, "Send A Crossword". Your delivery was successful, but you may wish to correct the following issues in your next delivery:
SDK Version Issue - In July 2018, iOS app updates submitted to the App Store will need to be built with the iOS '11.0' SDK or later, included in Xcode [9.0] or later. Make sure to update Xcode for future app deliveries._

#### Version of LibGDX and/or relevant dependencies
gdxVersion = '1.9.9-SNAPSHOT'
roboVMVersion = '2.3.4-SNAPSHOT'

#### Please select the affected platforms
- [ ] Android
- [x] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by kali-gandaki** [comment]
Hi , Don't deploy with old version of SDK. You might face some weird coordinate translation issues . The is is already solved here 
https://github.com/MobiVM/robovm/issues/302

**Comment by julienvillegas** [comment]
Thank you @kali-gandaki !
