### ISSUE TITLE
Life attribute on Particle Emitter is not applied to particles individually

### ISSUE THREAD

**Issue by obigu** [libgdx/libgdx#5280]
#### Issue details
The behaviour of Life and Life Offset attributes of a Particle Emitter is different than the rest of attributes such as Rotation, Angle, Gravity, etc... in the sense that it is not evaluated by particle but only by time. What this means is that All particles emitted at one time will have the same Life. This limitation doesn't allow simple effects such an explosion in which not all particles live the same.

According to the Wiki:

>Life: How long a single particle will live.

>Life Offset: How much life is used up when a particle spawns. The particle is still moved/rotated/etc for the portion of its life that is used up. This allows particles to spawn, eg, halfway through their life.

It could be that the way the Life attribute behaves atm is useful for some type of effect but as a user I miss a Life attribute that affects each particle individually.

**Whether we need a new Life attriubute or fix the existing one I will happily work on a PR.**

#### Reproduction steps/code
Video showing the issue, observe that when life value is modified to be Ranged, all particles have the same Life.
https://youtu.be/IXOgCgAUmk8

#### Version of LibGDX and/or relevant dependencies
1.9.8

**Comment by NathanSweet** [comment]
Note the `Emission`, `Life`, and `Life Offset` graphs say "Duration" while the other graphs say "Life". That label describes what the X axis of the chart represents. 

I've not used the particle emitters in a long time. To try what you propose, change this in ParticleEmitter:
```
particle.currentLife = particle.life = life + (int)(lifeDiff * lifeValue.getScale(percent));
```
To:
```
life = (int)lifeValue.newLowValue();
lifeDiff = (int)lifeValue.newHighValue();
if (!lifeValue.isRelative()) lifeDiff -= life;
particle.currentLife = particle.life = life + (int)(lifeDiff * lifeValue.getScale(percent));
```
It does seem to make sense, maybe providing better control than the current implementation, but I would have to get into trying to create effects both ways to see what I liked better. I'm not sure I'll find time to do that. Do others have opinions?

Can someone verify what this change would do to existing effects? I expect it breaks them pretty badly. I guess it could be a life setting or a separate property.

**Comment by obigu** [comment]
Thanks for your inputs.

In my opinion, most of the times, when you use Ranges you want property values to affect each particle indivuidually. There are some specific effects, though, that require those values to apply to all particles so no solution covers all cases. This applies to all properties, from Rotation to Velocity, not just Life.

If I had to design how the Particle Editor works, properties would affect "Each particle individually" by default and for extra versatility, a setting/checkbox on each of them would allow to switch to "All particles".

I agree that we must keep the option to set Life property to work as it has worked until now.

There are 2 options:
1. We leave current behaviour as default and add a setting to change it to apply particles individually.
2. We change current behaviour and add a checkbox to set it to how it was before.

Option 1 has the advantage of being fully backwards compatible.
Option 2 has the advantage of consitency across properties and (this is an opinion) that default will be the most common use case. It also opens the door for adding that setting to the rest of the properties.

I'll work on a PR, personally I prefer Option 2 but it can easily be changed.

**Comment by obigu** [comment]
If you want to play here's a modified Particle Editor with Nate's changes (bear in mind Life Offset behaviour has not been changed). I recommend opening it next to the old one to compare.
https://drive.google.com/open?id=1dTwDWn042aezX13dqJYFomsvgZ7fH1-W

**Comment by NathanSweet** [comment]
A checkbox and not breaking existing effects sounds good!
