### ISSUE TITLE
How to made snow and rain effect? 

### ISSUE THREAD

**Issue by tpnet** [libgdx/libgdx#5282]
#### Issue details
The parameters of ParticleEditor do not know how to set up

![image](https://user-images.githubusercontent.com/17380722/41885780-f9145a5e-792b-11e8-8f17-fbaf9f3e14ee.png)

![image](https://user-images.githubusercontent.com/17380722/41885795-107c4fee-792c-11e8-87ed-f8154ca23408.png)

![image](https://user-images.githubusercontent.com/17380722/41885802-1b558ab6-792c-11e8-9628-6fb219108d2c.png)

#### Version of LibGDX and/or relevant dependencies
1.9.8

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [√ ] Android

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker

**Comment by teelungsam** [comment]
Hhh
