### ISSUE TITLE
FileHandle moveTo() -> read() and weird characters

### ISSUE THREAD

**Issue by rdamiano** [libgdx/libgdx#5290]
I'm noting a lot of (non-fatal) crashes in my Android app originating from a `FileHandle.moveTo()`
Unsure if this is on iOS as I don't use this functionality there.

I can see a pattern in the names of the files attempted to be moved:

- /storage/sdcard0/Download/ߔ䠒ap do Rick Wubba Labba Dub Dub (Rick and Morty)l Kêita Beats.mp3 (Absolute)
- /storage/emulated/0/Download/GenYoutube.net_I-WANT-TO-KISS-MYSELF-DOO-DOO-DO-DOOߎ尟ζ-Created-by-Sr-Pelo_wAwkAjWIUSs.mp3 (Absolute)
- etc

The odd characters in the filename, I would assume, is the reason for the crash.

```
Non-fatal Exception: com.badlogic.gdx.utils.GdxRuntimeException
Error copying source file: /storage/emulated/0/Download/GenYoutube.net_I-WANT-TO-KISS-MYSELF-DOO-DOO-DO-DOOߎ尟ζ-Created-by-Sr-Pelo_wAwkAjWIUSs.mp3 (Absolute) To destination: /storage/emulated/0/Stick Nodes/sounds/GenYoutube.net_I-WANT-TO-KISS-MYSELF-DOO-DOO-DO-DOOߎ尟ζ-Created-by-Sr-Pelo_wAwkAjWIUSs.mp3 (Absolute)
com.badlogic.gdx.files.FileHandle.copyFile (FileHandle.java:690)
com.badlogic.gdx.files.FileHandle.copyTo (FileHandle.java:573)
com.badlogic.gdx.files.FileHandle.moveTo (FileHandle.java:599)
x.x.x.AndroidLauncher.scanDownloadFolderForFiles (AndroidLauncher.java:1185)
```

Using LibGDX 1.9.9-SNAPSHOT on Android.

**Comment by Tom-Ski** [comment]
Please read the issue template before submitting an isuse.
