### ISSUE TITLE
Input: How do I know if user pressed Delete or Backspace?

### ISSUE THREAD

**Issue by yuripourre** [libgdx/libgdx#5291]
#### Issue details
Delete and Backspace have the [same code](https://libgdx.badlogicgames.com/ci/nightlies/docs/api/constant-values.html#com.badlogic.gdx.Input.Keys.DEL)(67). How do I know if user pressed one or another?

#### Reproduction steps/code
- Start desktop application
- Press delete or backspace
- See the same code

[https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/Input.java#L95](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/Input.java#L95)

#### Version of LibGDX and/or relevant dependencies
1.9.8

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by NathanSweet** [comment]
Yep. Blame Android for poor constant names (and probably Mario for using those constants :p).
