### ISSUE TITLE
Gdx.graphics.setWindowedMode in windows min width is 120

### ISSUE THREAD

**Issue by Jiaming00** [libgdx/libgdx#5293]
#### Issue details
I am a newbie, my English is not good, I am using Google Translate. Sorry！
My pc : win7
Using Intellij IDEA;

I am learning this library, I want to change the window size in the wiki code example(https://github.com/libgdx/libgdx/wiki/Orthographic-camera) .

I found a method (Gdx.graphics.setWindowedMode) and called it in create() to change the window size to 100x100.

But this happened:

![100x100](https://user-images.githubusercontent.com/29698949/42196558-2df9ec22-7eb1-11e8-93ac-b30645729d41.jpg)

height is ok.
I think the reason is the three buttons in the upper right corner and program icons need those spaces(125px)

But when the program starts, I can still adjust the width to 116px.
![100x116](https://user-images.githubusercontent.com/29698949/42196740-195ef630-7eb2-11e8-8b79-58ee67b01283.jpg)

I know that this situation is basically impossible in game development because people don't use such a small window.

But on Windows I feel that these mechanisms are very confusing about width 125 and 116, why it happens. And setWindowMode returns true.

#### Reproduction steps/code
package org.cyberpunkonline.cpo;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.Input;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.OrthographicCamera;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.Sprite;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.math.MathUtils;

public class cpo extends ApplicationAdapter {
	static final int WORLD_WIDTH = 100;
	static final int WORLD_HEIGHT = 100;

	private OrthographicCamera cam;
	private SpriteBatch batch;

	private Sprite mapSprite;
	private float rotationSpeed;

	@Override
	public void create() {

		rotationSpeed = 0.5f;

		mapSprite = new Sprite(new Texture(Gdx.files.internal("assets/sc_map.png")));
		mapSprite.setPosition(0, 0);
		mapSprite.setSize(WORLD_WIDTH, WORLD_HEIGHT);

		System.out.println(Gdx.graphics.setWindowedMode(100,100));

		float w = Gdx.graphics.getWidth();
		float h = Gdx.graphics.getHeight();

		// Constructs a new OrthographicCamera, using the given viewport width and height
		// Height is multiplied by aspect ratio.
		cam = new OrthographicCamera(30, 30 * (h / w));
		cam.position.set(cam.viewportWidth / 2f, cam.viewportHeight / 2f, 0);
		cam.update();

		batch = new SpriteBatch();
	}

	@Override
	public void render() {
		handleInput();
		cam.update();
		batch.setProjectionMatrix(cam.combined);

		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

		batch.begin();
		mapSprite.draw(batch);
		batch.end();
	}

	private void handleInput() {
		if (Gdx.input.isKeyPressed(Input.Keys.A)) {
			cam.zoom += 0.02;
		}
		if (Gdx.input.isKeyPressed(Input.Keys.Q)) {
			cam.zoom -= 0.02;
		}
		if (Gdx.input.isKeyPressed(Input.Keys.LEFT)) {
			cam.translate(-3, 0, 0);
		}
		if (Gdx.input.isKeyPressed(Input.Keys.RIGHT)) {
			cam.translate(3, 0, 0);
		}
		if (Gdx.input.isKeyPressed(Input.Keys.DOWN)) {
			cam.translate(0, -3, 0);
		}
		if (Gdx.input.isKeyPressed(Input.Keys.UP)) {
			cam.translate(0, 3, 0);
		}
		if (Gdx.input.isKeyPressed(Input.Keys.W)) {
			cam.rotate(-rotationSpeed, 0, 0, 1);
		}
		if (Gdx.input.isKeyPressed(Input.Keys.E)) {
			cam.rotate(rotationSpeed, 0, 0, 1);
		}

		cam.zoom = MathUtils.clamp(cam.zoom, 0.1f, 100/cam.viewportWidth);

		float effectiveViewportWidth = cam.viewportWidth * cam.zoom;
		float effectiveViewportHeight = cam.viewportHeight * cam.zoom;

		cam.position.x = MathUtils.clamp(cam.position.x, effectiveViewportWidth / 2f, 100 - effectiveViewportWidth / 2f);
		cam.position.y = MathUtils.clamp(cam.position.y, effectiveViewportHeight / 2f, 100 - effectiveViewportHeight / 2f);

	}

	@Override
	public void resize(int width, int height) {
		cam.viewportWidth = 30f;
		cam.viewportHeight = 30f * height/width;
		cam.update();
		System.out.println(Gdx.graphics.getWidth());
	}

	@Override
	public void resume() {
	}

	@Override
	public void dispose() {
		mapSprite.getTexture().dispose();
		batch.dispose();
	}

	@Override
	public void pause() {
	}

}

#### Version of LibGDX and/or relevant dependencies
1.98

#### Stacktrace
invoked setWindowMode return true;
when calling resize   100  100;
but real size is 100x125

#### Please select the affected platforms

Windows

**Comment by Tom-Ski** [comment]
Dont think there is anything that can be done about this.
