### ISSUE TITLE
LWJGL3 Backend EGL Module

### ISSUE THREAD

**Issue by n-herbert-Mandoe** [libgdx/libgdx#5294]
#### Issue details
I was wondering if there are any plans to implement (or forks that implement) lwjgls EGL module? 
I have been working on a C++ rendering application that is exposed via JNI which has recently required the move to EGL for zero-copy methods using egl images. 
I setup a framebuffer before calling the JNI functions and using opengl I can render directly to the framebuffer (as the opengl context is on the same thread). But with EGL there is not context to be used and I am unable to render to the framebuffer. 

#### Version of LibGDX and/or relevant dependencies
1.98

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] MacOS

**Comment by EtK2000** [comment]
Anything platform or backed specific most likely won't be implemented.
If you implement it yourself and it works everywhere you can commit, otherwise I doubt it.

**Comment by n-herbert-Mandoe** [comment]
Any advice on getting the the dev environment setup to use the local libgdx version built from source?
I can see the files I have changed are appearing in my local maven repository folder.
I have mavenLocal() set in my build.gradle file, gdx version is set to 1.9.9-SNAPSHOT.
The external libraries included in the project are downloaded from remote though.

**Comment by EtK2000** [comment]
I created a project which is the source and a secondary project as a test which uses the first as a library.
This allows for me to easily write test code without having to remove it when committing.

**Comment by Tom-Ski** [comment]
No plans.

See https://libgdx.badlogicgames.com/documentation/hacking/Working%20from%20source.html#building-libgdx for guide on building from source and using in local projects.  You'll probably wan't to change the version or use a special classifier, otherwise every newer LibGDX snapshot will take precedenc eover your local 1.9.9-SNAPSHOT version.
