### ISSUE TITLE
Memory Leak on Particle Effect creation even with a ParticleEffectPool and dispose()

### ISSUE THREAD

**Issue by ange-black69** [libgdx/libgdx#5296]
#### Issue details

Memory Leak on Particle Effect creation even with a ParticleEffectPool and dispose()

#### Reproduction steps/code

`public class EntityParticleFire extends EntityParticle {

	private static ParticleEffect templateEffect = AssetsManager.getParticleEffect("Effects/fire.p");
	private static ParticleEffectPool particleEffectPool = new ParticleEffectPool(templateEffect, 1, 10);
	
	public EntityParticleFire(World world, Vector2 position) {
		super(world, position);
		effect = particleEffectPool.obtain();
		effect.allowCompletion();
		setParticlePosition(new Vector2(position.x, position.y));
		world.entityList.add(this);
		effect.start();
		
	}
	
	@Override
	public void setDead() {
		super.setDead();
		particleEffectPool.free(effect);
		effect.dispose();
	}
	
	@Override
	public void render(float delta) {
		super.render(delta);

	}`

`public abstract class EntityParticle extends Entity {
	
	protected World theworld;	
	protected PooledEffect effect;
	
	public EntityParticle(World world, Vector2 position)
	{
		super(world, position);
		theworld = world;
	}
	
	public void setDead()
	{
		super.setDead();
		world.entityList.remove(this);
		
	}
	

	@Override
	public void render(float delta) 
	{
		if(effect.isComplete())
		{
			this.setDead();
		}
		effect.draw(batch,delta);
		
	}`

The issue is when obtaining particle effect either from pool or not, upon particle effect completion, the memory eat like 8 MB more until Out Of Memory exception !

I've a entity manager which handle every entity in the world which consist of ticking each entity in a list.
the EntityParticle him self is well destroyed from list upon completion, the pool succesfully recycle particle effect as particlePool.getfree() return the value excepted.

I even call effect.dispose() but it doesn't resolve my issue..

the AssetsManager.getparticle() return a particle effect based on this line : assetManager.load("Effects/fire.p", ParticleEffect.class);

I'm a bit lost on where is the problem.

Thank you for your help

#### Version of LibGDX and/or relevant dependencies

        gdxVersion = '1.9.8'
        roboVMVersion = '2.3.1'
        box2DLightsVersion = '1.4'
        ashleyVersion = '1.7.0'
        aiVersion = '1.8.0'

#### Please select the affected platforms
- [X] Android
- [X] iOS (robovm)
- [X] iOS (MOE)
- [X] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by Tom-Ski** [comment]
Please use the forum or irc for personal help requests.
If you believe you have found a problem with libgdx, please see https://github.com/libgdx/libgdx/wiki/Getting-help#executable-example-code for examples of how to provide code so we can investigate.
