### ISSUE TITLE
InputProcessor removing itself from an InputMultiplexer causes exception.

### ISSUE THREAD

**Issue by PokeMMO** [libgdx/libgdx#5298]
#### Issue details
InputProcessor removing itself from an InputMultiplexer causes exception.

InputMultiplexer currently caches length before iterating
```java
for (int i = 0, n = processors.size; i < n; i++)
```

Not caching, will prevent the crash but will drop input to one InputProcesser on the frame one is removed.

```java
for (int i = 0; i < processors.size; i++)
```

Another fix might be to only actually process the removal after input is done for a frame.

Or this can just be an expected behavior and documented to inform users to wrap removals invoked from input in a postRunnable.

This issue also occurs when adding a listener to the front of the listeners from a listener's callback. This will not crash, but will cause the last listener to not receive input. As well as cause the immediately following listener to be triggered a second time (if it is not last).

#### Reproduction steps/code
```java
import com.badlogic.gdx.*;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;

public class InputMultiplexerRemoveTest extends ApplicationAdapter {
	InputMultiplexer multiplexer;
	InputTestProcessor processor1;
	InputTestProcessor processor2;
	
	@Override
	public void create () {
		multiplexer = new InputMultiplexer();

		processor1 = new InputTestProcessor();
		processor2 = new InputTestProcessor();
		multiplexer.addProcessor(processor1);
		multiplexer.addProcessor(processor2);
		
		Gdx.input.setInputProcessor(multiplexer);
	}

	public static void main (String[] args) throws Exception {
		new LwjglApplication(new InputMultiplexerRemoveTest());
	}
	
	class InputTestProcessor extends InputAdapter
	{
		@Override
		public boolean keyDown (int keycode) {
			if(this == processor1) {
				multiplexer.removeProcessor(processor1);
			}
			return false;
		}
	}
}
```

#### Version of LibGDX and/or relevant dependencies
1.9.9-SNAPSHOT

#### Stacktrace
```java
Exception in thread "LWJGL Application" java.lang.IndexOutOfBoundsException: index can't be >= size: 1 >= 1
	at com.badlogic.gdx.utils.Array.get(Array.java:154)
	at com.badlogic.gdx.InputMultiplexer.keyDown(InputMultiplexer.java:72)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:317)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:217)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by santouits** [comment]
@NathanSweet I'm having some problems with calling InputMultiplexer.clear() and I think this fix is what messes it up because when I set the input as handled in my inputProcessor and return true, the processors.end() is never called and the _iterating_ field in the DelayedRemovalArray just keeps increasing in every key:
```
processors.begin();
for (int i = 0, n = processors.size; i < n; i++)
if (processors.get(i).keyDown(keycode)) return true;
processors.end();
```
We could add processors.end() before returning true here, but  if @PokeMMO in his example handled the input and  added return true after 
```
multiplexer.removeProcessor(processor1);
```
the multiplexer would remove the processor and break the loop anyway, right?

**Comment by NathanSweet** [comment]
@santouits Sorry if my changed caused you problems. I don't follow what you are having trouble with. Can you please post a code example showing the problem like in the issue above?

**Comment by PokeMMO** [comment]
It looks like once an InputProcessor returns true, InputMultiplier also returns early before calling processors.end()

https://github.com/libgdx/libgdx/blob/5268da38a22663c8bbf4aff71d29ed47011fb58f/gdx/src/com/badlogic/gdx/InputMultiplexer.java#L87

**Comment by mgsx-dev** [comment]
@NathanSweet i think you should put a try/finally block around all loops to ensure processors.end() is called before methods return is all cases.

**Comment by santouits** [comment]
This, but I'm also not sure if this fix was needed at all, because in @PokeMMO 's example if he had handled the input by returning true, the loop of the processors would break and it would not cause an exception. Unless there is a use case that he shouldn't return true.

Like this:
```
@Override
public boolean keyDown (int keycode) {
	if(this == processor1) {
		multiplexer.removeProcessor(processor1);
                return true;
	}
	return false;
}
```

**Comment by mgsx-dev** [comment]
finally block is always executed whenether an exception is thrown or not. that fixes the issue.

**Comment by PokeMMO** [comment]
@santouits While that might be a valid solution for many users, for various reasons, I can't just return true for some of my InputProcessors. I could likely work around it with other solutions, but I wanted to see if there was a universally better option first.

Without any fix, the issue of adding additional processors to the front of an array causing input to be dropped would still exist. [The current fix removes this by adding an explicit exception on insert at position during iteration.](https://github.com/libgdx/libgdx/blob/237201beb0c5fafad9cb4503105b78a12c5fc6a3/gdx/src/com/badlogic/gdx/utils/DelayedRemovalArray.java#L142)

Prefix example of dropped input:
```java
import com.badlogic.gdx.*;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;

public class InputMultiplexerAddTest extends ApplicationAdapter {
	InputMultiplexer multiplexer;
	InputTestProcessor processor1;
	InputTestProcessor processor2;
	InputTestProcessor processor3;
	
	@Override
	public void create () {
		multiplexer = new InputMultiplexer();

		processor1 = new InputTestProcessor();
		processor2 = new InputTestProcessor();
		processor3 = new InputTestProcessor();
		multiplexer.addProcessor(processor1);
		multiplexer.addProcessor(processor2);
		
		Gdx.input.setInputProcessor(multiplexer);
	}
	
	@Override
	public void render()
	{
		if(processor1.enterPressed || processor2.enterPressed || processor3.enterPressed)
			System.out.println(processor1.enterPressed + " " + processor2.enterPressed + " " + processor3.enterPressed);
		super.render();
	}

	public static void main (String[] args) throws Exception {
		new LwjglApplication(new InputMultiplexerAddTest());
	}
	
	class InputTestProcessor extends InputAdapter
	{
		private boolean enterPressed = false;
		@Override
		public boolean keyDown (int keycode) {
			if(keycode == Input.Keys.ENTER) {
				enterPressed = true;
			}
			return false;
		}
		
		@Override
		public boolean keyUp (int keycode) {
			if(keycode == Input.Keys.ENTER) {
				enterPressed = false;
				
				if(multiplexer.getProcessors().size < 3)
					multiplexer.addProcessor(0, processor3);
			}
			return false;
		}
	}
}
```

This example will cause processor2 to think enter is still pressed.

**Comment by santouits** [comment]
@PokeMMO Changing the delayed array to a [snapshot array](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/SnapshotArray.java) will solve your case then?

**Comment by NathanSweet** [comment]
> It looks like once an InputProcessor returns true, InputMultiplier also returns early before calling processors.end()

Ah, of course. Sorry about that!

**Comment by PokeMMO** [comment]
@santouits Looks like it would.

@NathanSweet Is there any reason not to use SnapshotArray instead? It seems like it would be more feature complete and allow adding an InputProcessor to the front of the array without having to resort to postRunnable.
