### ISSUE TITLE
Extract math libraries in its own artifact

### ISSUE THREAD

**Issue by Sytten** [libgdx/libgdx#5300]
**_This is an enhancement request_**

#### Issue details
First of all, I have to say that I'm impressed by the quality of this lib (good job)!
My problem is that I only need the Math part of it and I don't want to pull the whole core to use it.
If you find the time, it would be very valuable for the community to have a separate package for this.
I personally need many of the utilities of Vector2 that I canno't find in other libs.

#### Version of LibGDX and/or relevant dependencies
Math package

#### Please select the affected platforms
- All

**Comment by Darkyenus** [comment]
Similar request appeared for the collections (`Array`s, `Map`s, etc.), and it would be nice to have both separated to own library/libraries.

Math stuff might be harder though, as it has some natives (at least some `Matix4` operations, IIRC).

**Comment by NathanSweet** [comment]
TBH, we are unlikely to separate parts of libgdx into separate libraries since we don't have the need for that ourselves. I suggest copying the parts you need into a separate library and using that (or just into your project).

**Comment by Sytten** [comment]
Someone did that (https://github.com/mini2Dx/gdx-math), just that it is better when it's official. Anyway I thought it would be useful for the java community at large since we don't have a lot of good simple math libraries, but I can understand if it is complicated for you.

**Comment by Lestat** [comment]
I remember when I copied the Animation class that used TextureRegions (back then it wasn't generic) and modified it to use whole Textures. It's that easy :)

**Comment by NathanSweet** [comment]
Ah, it's good someone has done it. As you can tell from the number of PRs and issues, libgdx maintainers are already struggling to keep up. I don't think we have the bandwidth for making it official, at least not now.
