### ISSUE TITLE
Dialog.show() different behavior based on arguments 

### ISSUE THREAD

**Issue by magakis** [libgdx/libgdx#5301]
#### Issue details
After getting some unexpected behavior while using the [Dialog ](https://github.com/libgdx/libgdx/blob/9b8f20b2d0e96e53f0f2b98dc8f6131c810aae71/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Dialog.java)class I realized that you get different behavior based on what overloaded version you call:

_show(Stage)_ : Your dialog will appear at the center of the stage with a default fade-in _Action_.
_show(Stage, Action)_: Your dialog will appear on stage with the specified action but not centered!

I find it misleading/confusing having an overloaded method where the "only" difference is the Action used in the process, having side effects on its position.

What do you think?

#### Version of LibGDX and/or relevant dependencies
Libgdx 1.9.9-SNAPSHOT, scene2d

**Comment by NathanSweet** [comment]
Yeah that isn't super nice. Probably neither method should change the dialog position. If we remove setPosition from `show(Stage)` then we likely break existing usage. If you want to use an action to animate the dialog into place, you might not want `show` to change the position, so we probably shouldn't move the setPosition to `show(Stage, Action)`. Maybe it is best we just live with the oddity and improve the javadocs.
