### ISSUE TITLE
TextureAtlas Slow Performance

### ISSUE THREAD

**Issue by JasonMacKeigan** [libgdx/libgdx#5302]
#### Issue details
TextureAtlas objects take far too long to create. This is creating a major bottleneck in my application right now because I cannot add more characters until I resolve this problem. 

An .atlas file with 500 lines and 4 associated images with dimensions less than 2048x2048 takes roughly 100-200 milliseconds. This needs to be improved as I am initializing roughly 20-24 atlases for a total overhead of 5000-7000 milliseconds.  Using a single atlas does not resolve the problem. 

#### Reproduction steps/code
`AssetManager manager = new AssetManager(new InternalFileHandleResolver());`
`manager.load("path/to/atlas", TextureAtlas.class);`
`manager.finishLoading();`

#### Version of LibGDX and/or relevant dependencies
1.9.8

#### Stacktrace
None

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS

**Comment by intrigus** [comment]
Please attach a http://sscce.org/

**Comment by mgsx-dev** [comment]
20 x 2048 x 2048 x 4 = about 320 MB, are you sure the bottleneck is the 500 lines in Atlas file or the huge amount of texture ?

**Comment by MobiDevelop** [comment]
Why not use AtlasManager's asynchronous loading mechanism instead of calling finishLoading()? Do you really need all of those texture atlases immediately?

**Comment by JasonMacKeigan** [comment]
@MobiDevelop Yes I need the assets immediately. On initialization I draw a 'level' scene as the background while the end-user is authenticating. This provides a rich scene and a good first impression for the end-user. It would not be ideal to draw a 'loading' scene while the assets are being created asynchronously.

**Comment by MobiDevelop** [comment]
I see, well, reality is that things take time. Immediately loading 20 texture atlases with each having 4 images of 2048 x 2048 is absolutely going to take substantial time no matter how 'optimized' the reading portion is.

**Comment by JasonMacKeigan** [comment]
@MobiDevelop It's possible you're right but considering there hasn't been any changes, let alone optimizations, to the TextureAtlas class in years, it's likely some improvements can be made.

**Comment by Tom-Ski** [comment]
The expense is uploading to the gpu, not parsing atlas data.  If you can provide standalone tests that demonstrate an issue specific to TextureAtlas compared with say a purely native approach to uploading a bitmap then there is probably something we can do. But until that is presented, this is pretty much expected behavior when uploading many large textures all at once.

**Comment by mgsx-dev** [comment]
@JasonMacKeigan sorry i meant 320 MB of texture data to inflate and upload to GPU. 79 MB of compreed data files still huge compared to a 500 lines json file :-)

**Comment by Roaddog56** [comment]
Upgrade or add atlas file?

**Comment by Lestat** [comment]
so many assets needs a loading screen. maybe show a simple loading screen to the authentication scene? thats the most obvious response. (Loading screen have existed for decades dude and for a reason)

**Comment by JasonMacKeigan** [comment]
@Lestat Just because it was done a decade ago, doesn't mean it was right. The last thing I want new end-users to do is wait for a loading screen to finish before they can access the game. I understand that there are limitations, however it is worth creating a discussion for. If it's not possible to reduce the time it takes then yes, I will ultimately have to load assets in the background while I concurrently draw a dummy loading screen.

**Comment by Tom-Ski** [comment]
Feel free to reopen if you can provide mode info for us to investigate, but currently marking this as non issue.
