### ISSUE TITLE
Gradle sync issue with com.google.gms:google-services:4.0.0+ firebase

### ISSUE THREAD

**Issue by naveenBhaskarSingh** [libgdx/libgdx#5305]
Facing an issue "**Cannot change strategy of configuration ‘:android:natives’ after it has been resolved.**" when syncing project with '**com.google.gms:google-services:4.0.0**' and up. I am using Gdx version 1.9.8 and Gradle version 3.1.2 in my project. If I comment out apply plugin: 'com.google.gms.google-services' I can compile and run but this causes issues with firebase.
"com.google.gms:google-services:3.1.1" is working fine with same project settings.

**Comment by Tom-Ski** [comment]
Duplicate
