### ISSUE TITLE
InputMultiplexer Done Broke

### ISSUE THREAD

**Issue by rdamiano** [libgdx/libgdx#5307]
Was running into a sporadic issue where my app crashes seemingly randomly - sometimes it does, sometimes not.

```
FATAL EXCEPTION: GLThread 1998
java.lang.IllegalStateException: Invalid between begin/end.
at com.badlogic.gdx.utils.DelayedRemovalArray.insert(DelayedRemovalArray.java:142)
at com.badlogic.gdx.InputMultiplexer.addProcessor(InputMultiplexer.java:37)
at ...
```

Haven't changed this part of my app in years, basically just creating a GestureListener
```
gestureDetector = new new GestureDetector(new MyGestureListener()
{
    //...
}
inputMultiplexer.addProcessor(0, gestureDetector); // <-- crashes sometimes
```

I see there was a change to this recently so something probs done borked.
(Using snapshot)

https://github.com/libgdx/libgdx/commit/5268da38a22663c8bbf4aff71d29ed47011fb58f#diff-ffe7423c20cbc67b70df554f19597047

Happening on Android definitely, unsure if other platforms.

**Comment by NathanSweet** [comment]
Sorry! This was fixed 7 hours ago: 92519461f233e6b78b65570c32ae8918c93a1b4b
