### ISSUE TITLE
Cannot convert relative path \. to an absolute file.

### ISSUE THREAD

**Issue by spkingr** [libgdx/libgdx#5308]
The generated project works fine on Android Simulator, but when start the `desktop:run` gradle command, it fails:

```
9:38:01: Executing task 'desktop:run'...

Cannot convert relative path \. to an absolute file.
9:38:01: Task execution finished 'desktop:run'.
```

The affected platforms
- [ ] Windows Desktop

Help, and thanks very much!

**Comment by spkingr** [comment]
I have made an `Application` starts from the `main` method of `desktop.DesktopLauncher`, that works for me.

**Comment by AmbujMishra** [comment]
In the "Run/Debug Configuration" for Aplication->DesktopLauncher, under Before launch:Build  +

Select "Build" instead of task run

**Comment by AmbujMishra** [comment]
![absolute error resolution](https://user-images.githubusercontent.com/8024050/54871240-5c06a400-4db1-11e9-8406-d420aa1db54b.JPG)
