### ISSUE TITLE
Question Regarding for implement of Screen objects

### ISSUE THREAD

**Issue by FrezCold** [libgdx/libgdx#5310]
I'm currently working on a adventure game project and I have come across this incident. I understand that for each frame you must clear the previous frame by doing 
```
Gdx.gl.glClearColor(0, 0,0.2f, 1);
Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
```
Or else the previous frame's image will not be erased causing unwanted effects. However it seems that even without the code for the object IntroScreen and GameScreen which implements Screen the frame seems to be drawing correctly with those two lines of codes. However when I tried it with the object that implements Game it results in the undesired effect of overlapping from previous frame. Why is there a difference between Screen object and Game object?

**Comment by Darkyenus** [comment]
Neither `Game`, `Screen` or any related `ApplicationListener` classes do anything with OpenGL. You are most likely overlooking some aspects of your code. I suggest stepping through your code with debugger, or studying the flow of your program more carefully.

As this is unlikely a problem with libGDX, it is not a good fit for the [issue tracker](https://github.com/libgdx/libgdx/wiki/Issue-tracker), try forums or IRC.
