### ISSUE TITLE
Expose setting for transparent windows on LWJGL3 backend.

### ISSUE THREAD

**Issue by raeleus** [libgdx/libgdx#5313]
#### Issue details
Please expose the window setting for transparent windows on LWJGL3 backend. This has been a feature of LWJGL since 3.1.4. It is only a matter of adding the window hint GLFW_TRANSPARENT_FRAMEBUFFER. This will allow for some neat effects with an undecorated window. I have tested and it works on my Windows 10 computer.

![Sample Image](https://ray3k.files.wordpress.com/2018/07/transparent-window.png)

#### Reproduction steps/code
Add the following to LWJGL3Application.createGlfwWindow():
`GLFW.glfwWindowHint(GLFW.GLFW_TRANSPARENT_FRAMEBUFFER, GLFW.GLFW_TRUE);`

In your LibGDX desktop app, use the following to clear the screen in the render method:
`Gdx.gl.glClearColor(0, 0, 0, 0);
Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);`

#### Version of LibGDX and/or relevant dependencies
1.9.9-SNAPSHOT

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by Tom-Ski** [comment]
This is currently broken on windows 10. I dont think it should be added until it works on all platforms.

**Comment by Tom-Ski** [comment]
I've added this as deprecated with the link to issue that breaks the functionailty of this on some systems.
