### ISSUE TITLE
Incorrect pixel density on android devices.

### ISSUE THREAD

**Issue by madmenyo** [libgdx/libgdx#5322]
#### Issue details
I have a Galaxy S8 which has a PPI of around 570 and calling `getDensity()` returns the following:

- Running `getDensity()` on WQHD+ returns 4 instead of roughly 3.52.
- Running `getDensity()` on Full HD+ returns 3 instead of roughly 2.64.

A call to `getPpiX()` and `getPpiY()` get a pretty good estimate vs the specs of my device I find online. [DISCLAIMER: No expert] and all that `getDensity()` should do is something like `getPpiX() / 160` since a mdpi of 160 is the baseline of density, at least for the font size unit DP afaik.

#### Reproduction steps/code
Print `Gdx.graphict.getDensity()` on a S8 but probably also other devices. Lookup the device PPI in the specs.

#### Version of LibGDX and/or relevant dependencies
1.9.8

#### Please select the affected platforms
My desktop is being calculated correctly by `getDensity()` and I can just test one Android device atm.

#### Workaround
Since getPpix and getPpiY work correctly or at least get a very close estimate on my device you can just devide the PPI by the baseline PPI of 160.

**Comment by MobiDevelop** [comment]
The getDensity() method returns the density as defined by the Android DisplayMetrics API.

See: https://developer.android.com/reference/android/util/DisplayMetrics.html#density

**Comment by madmenyo** [comment]
_However, if the screen resolution is increased to 320x480 but the screen size remained 1.5"x2" then the density would be increased (**probably to 1.5**)._

I'm not sure what the use is for getting a approximate guess of the density but I'll close it since it's not a LibGDX issue.
