### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError:

### ISSUE THREAD

**Issue by vito-Z80** [libgdx/libgdx#5325]
**Issue details**
I catch the exception when:
1) I am importing my old project into a new one (the contents of the core folder root)
2) in a new project, I change the main class Java file to Kotlin file

> AS 3.1.3
> build.gradle (Project) = classpath 'com.android.tools.build:gradle:3.1.0'
> build.gradle (Project) = classpath 'com.android.tools.build:gradle:3.1.3'
> gradle-wrapper.properties = distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-bin.zip
> gradle-wrapper.properties = distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-bin.zip
> gradle-wrapper.properties = distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
> all "compile" replaced to "implementation"

If my English is too bad, then please see the [video](https://youtu.be/SMxN1PYSNlI)

 **Reproduction steps/code**
Create a new project. Convert the core: main Java class to Kotlin class and run Desktop.
Code/Convert Java file to Kotlin file
or
Download [tester.zip](https://github.com/libgdx/libgdx/files/2235752/tester.zip)
1) run desktop project = work
2) uncomment the line of code `img = new AAA (). GetTexture ();` and run again = does not work
(in the commented line of code, the AAA class is the Kotlin class)

 **Version of LibGDX and/or relevant dependencies**
1.9.8 + Kotlin

 **Stacktrace**
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/mygdx/game/MyGdxGame
	at com.mygdx.game.desktop.DesktopLauncher.main(DesktopLauncher.java:10)
Caused by: java.lang.ClassNotFoundException: com.mygdx.game.MyGdxGame
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```

 **Please select the affected platforms**
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by vivissj3** [comment]
I think this is a known issue and not really caused by libgdx. Try running the desktop project from gradle task:
in Android Studio open the Gradle projects panel on the right side -> :desktop -> Tasks -> application -> run

This solved the issue for me

**Comment by nukesz** [comment]
I don't think it's a libgdx issue either, works fine from the command line / gradle task. I have experienced the same when I've changed the DesktopLauncher to kotlin also. I would guess something goes wrong in IntelliJ.

**Comment by itsabhiaryan** [comment]
For **LibGDX + Kotlin** project use gradle task

```
  gradlew desktop:run     // window
./gradlew desktop:run      //  mac
```

**Comment by vito-Z80** [comment]
gradlew desktop:run - it works and I did it, but I would like to run Shift + f10
I changed the gradle version to 3.5.all and plugin version to 2.3.3 to not use the command line

**Comment by itsabhiaryan** [comment]
It's works, I don't How/Why ?

Today again I tried to run `desktop module` using Run/Debug Configuration and it works. 

My project configuration :

1. Generate new project using [latest build](https://libgdx.badlogicgames.com/ci/nightlies/)
1. Android Studio 3.1.3
2. Kotlin in `core module` 
3. `org.gradle.configureondemand=false` in `gradle.properties`
4. Configure on demand disabled in my IDE(Android Studio)
5. Android gradle plugin version 3.1.3
