### ISSUE TITLE
FreeTypeFontGenerator bug

### ISSUE THREAD

**Issue by lolipok** [libgdx/libgdx#5326]
I need to adapt my game's fonts to screen size, so i started using the FreeTypeFontGenerator.
Some days ago i tried `font.getData ().setScale`, but the quality of sized fonts aren't good.
The current code is:
```
FreeTypeFontGenerator fontVerdana = new FreeTypeFontGenerator (Gdx.files.internal("fonts/Verdana.ttf"));
FreeTypeFontGenerator.FreeTypeFontParameter settings = new FreeTypeFontGenerator.FreeTypeFontParameter ();
settings.characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя-—«».,<>\"'/?!:;@#$%^&*()_+=~`[]{}\\|№•√÷×¶∆£€¢^°©®™іїєІЇЄ";

mChatFonts = new BitmapFont[11];
int[] sizes = {40, 35, 30, 28, 25, 20, 15, 13, 12, 10, 7};
for (int i = 0; i < 11; i++)
   {
     settings.size = Gdx.graphics.getHeight () / sizes[i];
     mChatFonts [i] = fontVerdana.generateFont (settings);
     mChatFonts [i].getData ().markupEnabled = true;
   }
fontVerdana.dispose ();
```
This code works, but i found that it has problems on  the devices with big resolution screen:
![image](https://user-images.githubusercontent.com/39791879/43355699-a6a1130a-9269-11e8-9867-23f94292332f.png)
I think, that the size of this font is more than 150-160 and some symbols could be invisible or broken.
Also i tried to change font, but it didn't help.

#### Version of LibGDX and/or relevant dependencies
![image](https://user-images.githubusercontent.com/39791879/43355742-52de5c04-926a-11e8-9023-78d0cd31f237.png)

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info
