### ISSUE TITLE
 java.util.concurrent.atomic.AtomicInteger spine2d pls help me.thank u

### ISSUE THREAD

**Issue by chongbo2013** [libgdx/libgdx#5328]
[ERROR] Errors in 'file:/C:/Users/x002/Desktop/nettygame/testgameClientandroid/core/src/com/esotericsoftware/spine/attachments/VertexAttachment.java'
      [ERROR] Line 46: No source code is available for type java.util.concurrent.atomic.AtomicInteger; did you forget to inherit a required module?

**Comment by EtK2000** [comment]
This doesn't follow the format for reporting.
https://github.com/libgdx/libgdx/wiki/Getting-help

Please supply more info:
• basic code example
• versions of anything relevant
• platform you're using
• anything else we need to properly find the issue

**Comment by NathanSweet** [comment]
It looks like this is a [Spine issue](https://github.com/EsotericSoftware/spine-runtimes/blob/3.6/spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/attachments/VertexAttachment.java#L43) and so should be reported there. However, the latest version of the Spine runtimes in the [3.7-beta branch](https://github.com/EsotericSoftware/spine-runtimes/blob/3.7-beta/spine-libgdx/spine-libgdx/src/com/esotericsoftware/spine/attachments/VertexAttachment.java#L42) no longer uses AtomicInteger. I suggest moving to the 3.7-beta runtime if possible. That means moving to the 3.7-beta editor, though 3.6 JSON is likely to work in 3.7 (binary is not).
