### ISSUE TITLE
Idea for Xbox deployment (UWP) and maybe more consoles!

### ISSUE THREAD

**Issue by LanguageAgnostic** [libgdx/libgdx#5330]
**This is more an idea than anything.** I asked it on LibGDX's Discord and it didn't seem that bad to share it here. 

### Concept
We could wrap the web distribution into a PWA (Progressive Web App) and then to a UWP (Universal Windows Platform) app. It would make it publishable to Xbox. This would be the first console support for LibGDX. :smiley:

I got inspired by looking at game frameworks like Phaser and how people could run their HTML5/JS games on Xbox One. See an example here: https://www.youtube.com/watch?v=4duLkwl0GQU

### Future
Looking a bit at the future, consoles might give first-class support to HTML5/JS games. We live in the golden age of JavaScript. Looking into this might help us later for other console support using our existent web distribution.

### Other notes
I'm interested in working on this. I could maybe create a guide and adapt our deployment settings. I'll wait for feedback on this first and take suggestions.

#### GWT -> PWA

https://github.com/gwidgets/gwt-pwa-demo

http://www.g-widgets.com/2016/08/11/progressive-web-apps-recipes-for-gwt/

https://www.slideshare.net/dodotis/gwt-and-pwa

#### UWP:
https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/development-lanes-html

https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/index

https://blogs.windows.com/msedgedev/2018/02/06/welcoming-progressive-web-apps-edge-windows-10/#wEEruIkzcQKSzKOh.97

https://blogs.windows.com/buildingapps/2016/09/30/uwp-hosted-web-app-on-xbox-one-app-dev-on-xbox-series/

#### Other links:
https://www.construct.net/ca/blogs/construct-official-blog-1/announcing-xbox-one-export-beta-857

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [X] HTML/GWT
- [X] (Potential) Xbox One
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by yuripourre** [comment]
I think that's a great idea, Wii U also supports HTML5.
https://developer.nintendo.com/tools

It would probably need some tweaks but having our games in a console would be awesome!

- [X] (Potential) Wii U

**Comment by developeralp** [comment]
I think game consols are really cool idea but what about supporting them by native ?

**Comment by SolarOmni** [comment]
I actually had this exact same idea and googled it and found my way here!

**Comment by MrStahlfelge** [comment]
It's a good idea, but state of now the GWT backend is lacking a lot of features. The two most eye-jumping problems are:

* slow bootstrap process of the games - there is an old PR from monsterofcookie/James Cook solving it
* a ton of sound issues: Sounds are played not on time, or not at all (on mobile devices)

**Comment by rafaskb** [comment]
I would love to see this happening, and it seems like the technology is already there.
Mini2dx (built on top of libGDX) devs are already working on Switch port as well through mono.

Console support would make libGDX shine more than ever.

- [x] (Potential) Switch

**Comment by MrStahlfelge** [comment]
Closing this. The problems I mentioned above are solved now. All in all, this is no issue and it is achievable with the HTML5 backend. Everything you need is a sample PWA project.
