### ISSUE TITLE
I am using html to write html5, please tell me how to use freetype

### ISSUE THREAD

**Issue by chongbo2013** [libgdx/libgdx#5331]
#### Issue details
I am using html to write html5, please tell me how to use freetype
#### Reproduction steps/code

I need to do chat with gdx, I can't know the text in advance, so I have to use the Chinese font library.

#### Version of LibGDX and/or relevant dependencies
1.9.8

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms

- [x] HTML/GWT

**Comment by Lestat** [comment]
use the forums/irc/discord for help

**Comment by Tom-Ski** [comment]
A wild lestat

**Comment by Tom-Ski** [comment]
Freetype is not supported on gwt.
