### ISSUE TITLE
UnsatisfiedLinkError: Can't link Physics Library

### ISSUE THREAD

**Issue by bunnylover123987** [libgdx/libgdx#5336]
Please ensure you have given all the following requested information in your report.

#### Issue details
When the app is run on XCode, it crashes before init() is complete. IosMOE has trouble loading the physics library (even though it is properly linked AND I tried a static Box2D.init()). Gradle has been built and rebuilt for IOS but still, the physics library isn't properly linked / loaded.

#### Reproduction steps/code
Create Desktop and IOSMoe Application with Box2D and Box2D lights. Create a new world object in constructor (World is NOT static and is created after the init() method). Main class: https://pastebin.com/vhF9DZVb. build.gradle: https://pastebin.com/BwP0gcFM. Here is my module setup: https://gyazo.com/3703edee0e21448dd4231405a7831f65
 NOTE: I used the LibGDX gui to create the project and all libraries run on the desktop and IOS perfectly, the trouble is with the Physics library.

#### Version of LibGDX and/or relevant dependencies
_Please provide the version(s) affected._
LibGDX 1.9.6
IosMoe 1.4.2
Box2D Version 1.9.6
Box2D Lights version 1.4

#### Stacktrace
java.lang.UnsatisfiedLinkError: No implementation found for long com.badlogic.gdx.physics.box2d.World.newWorld(float, float, boolean) (tried)

#### Please select the affected platforms
- [ ] iOS (MOE)

**Comment by Tom-Ski** [comment]
Post the complete stack trace please.

**Comment by bunnylover123987** [comment]
Full strack trace: https://pastebin.com/uT6bC2nm

**Comment by Tom-Ski** [comment]
This is an issue with the Moe proguard config, not the native binary or loading of the native binary.

**Comment by bunnylover123987** [comment]
Thank you! How would I replace the Moe proguard config with the correct one? Is this file in my project’s directory?

**Comment by SirTrashyton** [comment]
Fixed this issue on my own. Took me over a week and I got minimal help from others, so this is my makeshift solution. GDX project is not setup correctly with gdx-setup.jar so I forked [this](https://github.com/multi-os-engine/moe-samples-java/tree/moe-master/LibGDXMissileCommand/) github. Got the libraries linked and running by building with ant and maven, and then following [this](https://multi-os-engine.github.io/doc/multi-os-engine/9_game/1_libgdx/libgdx.html) tutorial on getting the app running on Xcode via IOS-Moe.
