### ISSUE TITLE
Error when creating new project on gradle compile phase

### ISSUE THREAD

**Issue by Shadkirill** [libgdx/libgdx#5338]
Hi! I have a gradle dependencies error when generating new project from LibGDX project generator. When i open the resulting project in IDE (Android Studio or IntelliJ) i have the same error and no configurations exists.I use MacOS.

Stacktrace:
```java
Executing '/Users/kirill/Downloads/test/gradlew clean --no-daemon'
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/4.6/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'test'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find bundletool.jar (com.android.tools.build:bundletool:0.1.0-alpha01).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/bundletool/0.1.0-alpha01/bundletool-0.1.0-alpha01.jar
   > Could not find builder-model.jar (com.android.tools.build:builder-model:3.1.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-model/3.1.0/builder-model-3.1.0.jar
   > Could not find apksig.jar (com.android.tools.build:apksig:3.1.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apksig/3.1.0/apksig-3.1.0.jar
   > Could not find baseLibrary.jar (com.android.databinding:baseLibrary:3.1.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/databinding/baseLibrary/3.1.0/baseLibrary-3.1.0.jar
   > Could not find annotations.jar (com.android.tools:annotations:26.1.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.1.0/annotations-26.1.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
```
- [ ] Android
- [ ] iOS
- [ ] MacOS

**Comment by Tom-Ski** [comment]
Can you provide exact reconstruction steps? What settings you are using in the tool, what JDK version, what android SDK version. Also providing the generated project would be good.

**Comment by Shadkirill** [comment]
java version "1.8.0_144"

Im using sdk from Android Studio:
Android sdk tools 26.1.1
Android sdk platform-tools 28.0.0

screenshot from generating tool: https://drive.google.com/file/d/1_G6kh70hRGO_2L0h8Pj2w1qikUrX3yI5/view?usp=sharing

generated project:
https://drive.google.com/file/d/1NAN_lPWPpcz-SH9JpD_yjSTM7BcVkhA7/view?usp=sharing

**Comment by Tom-Ski** [comment]
Can you try the following:
In your build.gradle switch line 9 and 10.
```
        jcenter()
        google()
```

to become
```
        google()
        jcenter()
```

After this, run ./gradlew build from command line.

**Comment by itsabhiaryan** [comment]
@Shadkirill   Works for me, I'm using Android Studio 3.1.4 and my system is in internet connection. 

Downloaded your project 
Imported into Android Studio, Tried to refresh for Gradle sync.
Not able to find `buildToolsVersion` `28.0.2`
Changed `buildToolsVersion` to `27.0.3` from `28.0.2` because I don't have `28.0.2` at that time.
Done
Run on android Device using Run/Debug config. No Problems.
