### ISSUE TITLE
Gdx.graphics.setWindowedMode full screen issue

### ISSUE THREAD

**Issue by TMTHY** [libgdx/libgdx#5339]
I have LibGdx game with GWT deployment. 
I use two method to switch full screen on and of:
Gdx.graphics.setFullscreenMode and Gdx.graphics.setWindowedMode. 

Everything works as expected on Chrome (68.0.3440)
But on FireFox (61.0.2 ) setFullscreenMode works, but setWindowedMode not. Game is not returning from full screen. 

I believe the problem is in code inside GwtGraphics.exitFullscreen:
if ($doc.webkitExitFullscreen) $doc.webkitExitFullscreen();
if ($doc.mozExitFullscreen) $doc.mozExitFullscreen();

But as stated here (https://developer.mozilla.org/ru/docs/DOM/Using_fullscreen_mode), FireFox expects  mozCancelFullScreen()

And after applying small hack (that checks for mozCancelFullScreen function and calls it) after setWindowedMode call, full screen is working as expected.

May be the list of possible cancel/exit full screen functions in exitFullscreen should be extended?

- [*] HTML/GWT

**Comment by julienvillegas** [comment]
Hello, if you provide a [SSCCE]( (http://sscce.org) ) can help with this...

**Comment by julienvillegas** [comment]
Added a new test to LibGDX test repo and tested on Mac that I could switch Full sceen mode to Window Mode with Safari, Chrome and FireFox.  I could not replicate the issue. 
I would close this issue. 
Happy to test another scenario if another issue is raised with more details.
