### ISSUE TITLE
How can I use libgdx with AndroidX

### ISSUE THREAD

**Issue by spkingr** [libgdx/libgdx#5341]
#### Issue details
Now the `support` library is migrated to `androidX` namespace, How can I use libgdx with `androidX` supported?

```java
implementation "androidx.appcompat:appcompat:$androidx_version" //this does not work
//implementation 'com.android.support:appcompat-v7:27.1.1' //the old dependencies
```

#### Affected platforms
- [ ] Android

**Comment by titanseason** [comment]
appcompat is not migrated to androidx. Use `implementation 'com.android.support:appcompat-v7:27.1.1'` as usual

**Comment by SimonIT** [comment]
Maybe try with this refactoring guide https://developer.android.com/topic/libraries/support-library/refactor

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
