### ISSUE TITLE
Feature Request: Polygon rotation direction

### ISSUE THREAD

**Issue by woozay** [libgdx/libgdx#5344]
The Polygon class is great, however when you set the rotation and call getTransformedVertices() it rotates the shape anti-clockwise. I would be great if you could specify a direction to rotate. I know you can just set the angle to a negative number to rotate the other way, but I think it would be nice if you could specify a direction. Feel free to comment.

The code in questions is:
```
if (rotation != 0) {
  float oldX = x;
  x = cos * x - sin * y;
  y = sin * oldX + cos * y;
}
```

Perhaps a boolean can be introduced which determines the direction of the rotation
```
if (rotation != 0) {
  float oldX = x;
  if(!clockwise){
    x = cos * x - sin * y;
    y = sin * oldX + cos * y;
  }else{
    x = cos * x + sin * y;
    y = sin * oldX - cos * y;
 }
}
```

**Comment by mgsx-dev** [comment]
Trigonometry convention is CCW positive. No need to overload API in my opinion.

**Comment by EtK2000** [comment]
Even if everyone wanted to do this I doubt it would be accepted.
There are many places throughout LibGDX that use rotations and they don't allow specifying CW or CCW.
This would either cause many inconsistencies, or be a huge pain.

**Comment by woozay** [comment]
Ok cool, thank you guys for your input. I didn't know that CCW positive was the standard in trigonometry. I will therefore close it.
