### ISSUE TITLE
Feature Request: Vibration intensity/amplitude

### ISSUE THREAD

**Issue by retrodaredevil** [libgdx/libgdx#5345]
Earlier in the year when android 8.0 came out, it added support for vibration amplitude: https://developer.android.com/reference/android/os/VibrationEffect. From what I can tell, it is also available in the IOS API: https://stackoverflow.com/questions/19822295/intensity-of-custom-iphone-vibration (maybe I'm wrong).

I think somehow adding this to the api would be very useful so it's not just on or off. I don't think it'd be too hard to add support for amplitude and check if amplitude is available on the current device. I'm guessing I'd be able to make a pull request for this but I wanted to know what you guys thought first or if there's someone more experienced than me who wants to try this or has any ideas.

#### Please select the affected platforms
- [x] Android
- [x] IOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by mgsx-dev** [comment]
I don't know for iOS but for android there's PWM (pulse width modulation) available already, see https://github.com/libgdx/libgdx/wiki/Vibrator and it works well to simulate vibration intensity.

**Comment by retrodaredevil** [comment]
Thanks for the PWM suggestion, it works OK, but can be pretty annoying (loudish and noticeable). I'm using a Galaxy S9 and using these patterns:
```OFF(), FULL(), P90(new long[]{2, 30}), P70(new long[]{5, 30}), P50(new long[]{10, 25}), P35(new long[]{15, 30}), P10(new long[]{20, 35});```
where OFF and FULL are special cases. 

If anyone has any better patterns for this that'd be cool. I still think using the new (not deprecated) android api would be a good idea.

**Comment by SirTrashyton** [comment]
This feature would be great for IOS - as it currently stands, the only option is a simple one length vibrate (the method ignores the input 'miliseconds').
