### ISSUE TITLE
Cant get Desktop version to run in Android Studio (1.9.9-Snapshot : Kotlin)

### ISSUE THREAD

**Issue by burf2000** [libgdx/libgdx#5360]
Please ensure you have given all the following requested information in your report.

#### Issue details
So I have a game written for Android, iOS (MOE) and Desktop.  I cant however launch it in Android Studio
I can do ./gradlew desktop:dist (then run the jar)
I cant do ./gradlew desktop:run (sits at 90%)

I have edited the project to do "Build Project" instead of "Build"

If I hit the play button in Android studio I get Exception in thread "main" java.lang.NoClassDefFoundError: com/burfdevelopment/hack24/Native

Native is an interface based on the LibGDX guide on how to call native features (so iOS, Android and Desktop have a simple hello world method)
https://github.com/libgdx/libgdx/wiki/Interfacing-with-platform-specific-code

#### Version of LibGDX and/or relevant dependencies
LibGDX 1.9.9
Gradle 4.4
Gradle tools 3.1.2
MOE 1.4.1
RoboVM 2.3.3
Kotlin 1.2.40

#### Stacktrace
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/burfdevelopment/hack24/Native
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.burfdevelopment.hack24.Native
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ X] MacOS

**Comment by burf2000** [comment]
I have managed to get  ./gradlew desktop:run to work by deleting:
**if(Os.isFamily(Os.FAMILY_MAC))
jvmArgs += "-XstartOnFirstThread"**

However I can still not launch it via play/debug button

**Comment by Tom-Ski** [comment]
When did you generate the project? Stalling on 90% of gradle run sounds like you have project generated on old broken setup.  In which case you need to remove the lines here: https://github.com/libgdx/libgdx/commit/295cdd4ab804015e696839039085ca0284371a52#diff-7ebae1deceea73c4ef6ad16303867edd

Did you follow the official documentation for importing and running in the IDE, especially nothing disabling of configure on demand?

**Comment by burf2000** [comment]
Hey mate the project is probably 1-2 years old.

I have disabled on demand
I have removed the 2 lines in the desktop build gradle
I have removed build and added build project

**Comment by Tom-Ski** [comment]
Can you show this project somewhere? Or generate a new project with latest setup and provide the project that reproduces your issue.

**Comment by Tim-Fronsee** [comment]
In regards to 'However I can still not launch it via play/debug button':

Android Studio's **Play/Debug** button is meant for running Android applications & test suites only.  Thus, if you are using Android Studio to code with (which is what I use) you may need to rely on command line tools (i.e., command line `gradle`) to compile, test, and run the other variants of the application.

If you can build your application via the command line, it is likely an issue with the configuration of the IDE or even incompatibility with that particular IDE.
