### ISSUE TITLE
TextureAtlas - performace improvement (findRegion method)

### ISSUE THREAD

**Issue by forgottenAnt** [libgdx/libgdx#5363]
#### Issue details
As some of you probably know, regions in TextureAtlas class are stored as array, which is probably not the best choice for working with findRegion method (even documentation says about speed issues).

#### Detailed solution
As for now, regions are stored in:
private final Array<AtlasRegion> regions = new Array();

If you ask me, I would probably change current Array class for something from Map class family (HashMap from pure Java, or something from Libgdx maps available in package com.badlogic.gdx.utils). By doing so, there would be visible speed up, and the ease of using findRegion will go up significantly as well (no need to manual cache references - in my case, sometimes there is about 100-200 textures that I need to take care of)

Even changing implementation for:
private final Map<AtlasRegion> regions = new HashMap();
would be probably a better choice in this case.

Thanks for hearing me out, and hope that I don't omit anything important about advantages of current Array implementation - if so, I would gladly hear the reason for using it :-)

**Comment by MobiDevelop** [comment]
If we didn't have indexed regions where many regions may have the same name, this would probably be fine. Since we have to account for the indexed regions, we'd either have to keep two maps or treat everything as indexed and incur the cost of creating and storing an array whether it is indexed or not.

**Comment by forgottenAnt** [comment]
I see. As you said, I didn't take region indexes into account - now it make more sense.

As for now, I will probably stick with using getRegions method and adding all of the regions into my own hash map right after creating the atlas instance.

Thanks for your fast response!

**Comment by EtK2000** [comment]
Technically it can be a map of arrays, but I'm thinking the extra complexity and overhead aren't worth it.

**Comment by MobiDevelop** [comment]
Will go ahead and close this as best implemented in application code if so desired.
