### ISSUE TITLE
Result of Method Camera.unproject is weird when the camera viewport size is inconsistent with the window size

### ISSUE THREAD

**Issue by Jiaming00** [libgdx/libgdx#5364]
Result of Method Camera.unproject is weird when the camera viewport size is inconsistent with the window size , and the value of y always has a small deviation. I don't understand the graphics transformation, so the source code is not understood. The above is the situation I can provide. Using my code, try changing x and y to output the corresponding result of unproject result, and the result of my own unproject method.(using google translator，sorry)

```
public class CameraControl extends ApplicationAdapter {
    SpriteBatch batch;
    Texture     img;
    Camera      camera;

    @Override
    public void create() {
        batch = new SpriteBatch();
        img = new Texture("test.bmp");
        Gdx.graphics.setWindowedMode(200, 200);
        camera = new OrthographicCamera(Gdx.graphics.getWidth()/2, Gdx.graphics.getHeight() /2) ;
        camera.position.set(0, 0, 0);
        camera.update();

        float x = -300;
        float y = 300;
        Vector3 v3   = new Vector3(x, y, 0);
        camera.unproject(v3, camera.position.x, camera.position.y, camera.viewportWidth, camera.viewportHeight);
        System.out.println("unproject:  "+v3.x + " " + v3.y);

        Vector2 v3_2  = new Vector2(x, y);
        unproject(camera, v3_2);
        System.out.println("   mycode:  "+v3_2.x + " " + v3_2.y);
    }

    Vector2 unproject(Camera camera, Vector2 mouse) {
        Vector3 cameraPosition = camera.position;
        float   cameraX        = cameraPosition.x;
        float   cameraY        = cameraPosition.y;
        float   viewportWidth  = camera.viewportWidth;
        float   viewportHeight = camera.viewportHeight;
        float   screenHeight   = Gdx.graphics.getHeight();
        float   screenWidth    = Gdx.graphics.getWidth();
        mouse.x = (cameraX - viewportWidth / 2)
                + viewportWidth * (mouse.x / screenWidth);
        mouse.y = (cameraY - viewportHeight / 2)
                + viewportHeight * ((screenHeight - mouse.y) / screenHeight);
        return mouse;
    }

    @Override
    public void render() {
        camera.update();
        batch.setProjectionMatrix(camera.combined);

        Gdx.gl.glClearColor(1, 0, 0, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        batch.begin();
        batch.draw(img, 0, 0);
        batch.end();
    }

    @Override
    public void dispose() {
        batch.dispose();
        img.dispose();
    }
}
```

**Comment by EtK2000** [comment]
You didn't really follow the guidelines for reporting an issue.
What platform and version?
What LibGDX version?
What's the expected result versus what you actually got?
Etc.

We can't (and probably won't) help you without enough information.

**Comment by Jiaming00** [comment]
@EtK2000 
platform windows10
IDE intellij 
used gdx-setup.jar lastest version
libgdx 1.9.8

![info](https://user-images.githubusercontent.com/29698949/45260299-47b31900-b416-11e8-8cc0-80054192a56f.jpg)

Vector3 v3=new Vector3(-100,100,0)
 camera.unproject(v3, camera.position.x, camera.position.y, camera.viewportWidth, camera.viewportHeight);

I expect the result to be x:-100.0 y:0.0
Actually I get  x:-150.0  y:49.0

I suspect that unproject is not working as I imagined. If my use is wrong, please correct me.
