### ISSUE TITLE
FreeType generated font misses some characters with certain parameters

### ISSUE THREAD

**Issue by Vlad-M-1** [libgdx/libgdx#5368]
#### Issue details
When using the font provided below and one of the affected sizes some characters are not rendered.

#### Reproduction steps/code
1. Generate new project with FreeType feature enabled
2. Replace the body of your generated ApplicationAdapter class (MyGdxGame by default) with this:

```
    private SpriteBatch batch;
    private BitmapFont font;

    @Override
    public void create() {
        batch = new SpriteBatch();

        FreeTypeFontGenerator fontGenerator =
                new FreeTypeFontGenerator(Gdx.files.internal("Carlito-Regular.ttf"));

        FreeTypeFontGenerator.FreeTypeFontParameter parameter =
                new FreeTypeFontGenerator.FreeTypeFontParameter();

        // Rendered text depending on font size:

        // 211:       "abcde" as expected
        // 212:       "something strange bcde"
        // 214 - 215: " b de"
        // 216 - 262: " b d "
        // 263:       " bcde"
        // 264 - 266: " b de"
        // 267 - 268: " b d "
        // 269:       "abcde" as expected

        parameter.size = 216;

        font = fontGenerator.generateFont(parameter);
    }

    @Override
    public void render() {
        Gdx.gl.glClearColor(0, 0, 0, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

        batch.begin();
        font.draw(batch, "abcde", 5, 300);
        batch.end();
    }

    @Override
    public void dispose() {
        batch.dispose();
        font.dispose();
    }
```

3. Download Carlito font from https://fontlibrary.org/en/font/carlito and copy Carlito-Regular.ttf to your assets folder
4. Set parameter.size to one of the values from the comments above
5. Run and see a certain kind of unexpected render

#### Version of LibGDX and/or relevant dependencies
• LibGdx 1.9.8
• Windows and Android, other platforms not tested
• Carlito-Regular.ttf font, other fonts not tested.

#### Please select the affected platforms
- [+] Android
- [?] iOS (robovm)
- [?] iOS (MOE)
- [?] HTML/GWT
- [+] Windows
- [?] Linux
- [?] MacOS

**Comment by obigu** [comment]
Does setting useIntegerPositions to false changes anything?
`font.setUseIntegerPositions(false);`

**Comment by Vlad-M-1** [comment]
> Does setting useIntegerPositions to false changes anything?
> `font.setUseIntegerPositions(false);`

Thank you for suggestion.
Just checked, unfortunately it stays the same way.

**Comment by NathanSweet** [comment]
You are rendering at a huge size. What do the font textures look like? What if you increase the PixmapPacker page size by setting `parameter.packer`?

**Comment by Vlad-M-1** [comment]
> 
> 
> You are rendering at a huge size. What do the font textures look like? What if you increase the PixmapPacker page size by setting `parameter.packer`?

That really worked. Thank you :) 

My use case for such a font size is a diagram editor. It supports zooming and needs to render a smooth text. As far as I remember, this font problem also occurred on smaller text sizes. Instead of absence of characters, some quite unusual ones were generated.

Probably it would be helpful to add some notice about large font size and `packer` on this page:
https://github.com/libgdx/libgdx/wiki/Gdx-freetype

Currently the only mention of packers on that page is `/** The optional PixmapPacker to use */` comment. And it doesn't tell when it's reasonable to set that parameter.

**Comment by Vlad-M-1** [comment]
Found a much more simple solution: 

> FreeTypeFontGenerator.setMaxTextureSize(4096);

Then I guess it's even better to mention this method on https://github.com/libgdx/libgdx/wiki/Gdx-freetype

**Comment by NathanSweet** [comment]
Cool, glad you got it sorted. Sorry it took so long to reply. I've updated the wiki. Feel free to make wiki contributions! I believe anyone can edit the wiki, that is what it is there for.

BTW, you might look at DistanceFieldFont:
https://github.com/libgdx/libgdx/wiki/Distance-field-fonts
That wiki page looks outdated though, since it doesn't even mention that you should use the shader created by DistanceFieldFont.createDistanceFieldShader.
