### ISSUE TITLE
ParticleEffect modification broke Particle Effect on GWT module #5280

### ISSUE THREAD

**Issue by julienvillegas** [libgdx/libgdx#5373]
Issue "Life attribute on Particle Emitter is not applied to particles individually" with ID #5280 broke Particle loader for the HTML/gwt module

#### Issue details
A new parameter (independent) has been added to the ParticleEffect configuration file ".p".
In order to ensure backward compatibility the lifeValue.loader in class ParticleEmitter
has been updated with a mark(100) followed by a reset (see below).
Problem is,

- On Desktop, Android, calling that works.
- On GWT this triggers an Exception as there is no implementation for the BuffereredReader.mark() method. This calls by default the method on Reader.java which by default raises an exception.

In class ParticleEmitter:
```
public void load (BufferedReader reader) throws IOException {
			super.load(reader);
			// For backwards compatibility, independent property may not be defined
			reader.mark(100);
			String line = reader.readLine();
			if (line == null) throw new IOException("Missing value: " + "independent");
			if (line.contains("independent"))
				independent = Boolean.parseBoolean(readString(line));
			else
				reader.reset();
		}
```

#### Reproduction steps/code

Run the Out of the box Tests on GWT, select the following test com.badlogic.gdx.tests.ParticleEmitterTest

You will get the Exception outlined in the stacktrace section below.

The issue does not happen with the android or Desktop module (which is probably why this went undetected).

#### Version of LibGDX and/or relevant dependencies

LibGDX Version: 1.9.9-SNAPSHOT

#### Stacktrace
```java
Uncaught Error: com.badlogic.gdx.utils.GdxRuntimeException: Error loading effect: data/test.p
    at rLd.JKd [as dyb] (com.badlogic.gdx.tests.gwt.GdxTestsGwt-0.js:159)
    at rLd.SKd [as lyb] (com.badlogic.gdx.tests.gwt.GdxTestsGwt-0.js:159)
    at rLd.EKd (com.badlogic.gdx.tests.gwt.GdxTestsGwt-0.js:159)
    at rLd.eLd (com.badlogic.gdx.tests.gwt.GdxTestsGwt-0.js:159)
    at rLd.lLd (com.badlogic.gdx.tests.gwt.GdxTestsGwt-0.js:159)
    at new rLd (com.badlogic.gdx.tests.gwt.GdxTestsGwt-0.js:159)
    at ZX.jY [as zt] (com.badlogic.gdx.tests.gwt.GdxTestsGwt-0.js:120)
...
com.badlogic.gdx.tests.gwt.GdxTestsGwt-0.js:159 Uncaught Error: java.lang.RuntimeException: com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'pwb' of undefined
    at mLd.JKd [as dyb] (com.badlogic.gdx.tests.gwt.GdxTestsGwt-0.js:159)
    at mLd.SKd [as lyb] (com.badlogic.gdx.tests.gwt.GdxTestsGwt-0.js:159)
    at mLd.FKd (com.badlogic.gdx.tests.gwt.GdxTestsGwt-0.js:159)
...
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [x] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by julienvillegas** [comment]
One option is to remove the mark() / reset() but this will break backward compatibility.
Ok?

**Comment by julienvillegas** [comment]
Hi @obigu, check my proposed solution, I think it allow us to use GWT (I tested it) **AND** be backward compatible with the new parameter.

**Comment by obigu** [comment]
@julienvillegas I've thought about something like this but it means letting the hack permeate yet another layer, making future changes even harder. It's really not up to me to decide though, @NathanSweet ?

What I'd suggest though is to take the changes from https://github.com/libgdx/libgdx/pull/5374 on **test.p** and **singleTextureAllAdditive.p** files and merge them in your PR to make the tests consistent with the latest version.

**Comment by julienvillegas** [comment]
alright! will do if the approach gets the blessing.

note: You are right about it not being neat. That class already has a few hacks there and then. I like your suggestion to move to a json based..

**Comment by julienvillegas** [comment]
ok, updated p files 👍

**Comment by mgsx-dev** [comment]
@julienvillegas @obigu any plan to fix this issue? 2D particles are broken for GWT since 1.9.9 and it would be better to have a hacky solution (like #5376) than having the whole thing broken, no?

**Comment by obigu** [comment]
AFAIK it will only break trying to load particle effects that use the old format. I believe it doesn't make sense anymore to merge the "hacky" solution as backwards compatibility has already been broken for a while. https://github.com/libgdx/libgdx/pull/5374 is still open and should be merged to cleanly handle GWT non supported classes and update the particle effects test files to the latest format.

**Comment by mgsx-dev** [comment]
My bad, I didn't see #5374, yes please fix formatting issue (maybe a CRLF / LF issue ? )

**Comment by obigu** [comment]
Here you go https://github.com/libgdx/libgdx/pull/5637

**Comment by julienvillegas** [comment]
Great! Thanks
