### ISSUE TITLE
controllers-lwjgl3 not detecting some Wireless Xbox One S inputs.

### ISSUE THREAD

**Issue by rafaskb** [libgdx/libgdx#5380]
#### Issue details
I recently got an Xbox One S Wireless controller that works via bluetooth to use on my Mac, and it works just fine for all games that I've tested it with, it doesn't need drivers, it works natively, pretty cool, except lwjgl3 doesn't recognize some of its inputs when in Wireless mode. If I use it with an USB cable though, everything works just fine.

Not only lwjgl3 doesn't recognize the controller, it also throws a LOT of errors to the console when the controller is active.

To be specific, here are the current mapping signals for this controller, in wireless mode:
- Controller Name: Xbox Wireless Controller
- Operating system: Mac OS X
- A: Button 0
- B: Button 1
- X: Button 3
- Y: Button 4
- D-Pad Left: Pov 0 West
- D-Pad Right: Pov 0 East
- D-Pad Up: Pov 0 North
- D-Pad Down: Pov 0 South
- Left Stick Left: Axis 0, from 0 to -1
- Left Stick Right: Axis 0, from 0 to +1
- Left Stick Up: Axis 1, from 0 to -1
- Left Stick Down: Axis 1, from 0 to +1
- Left Stick Click: Button 13
- Right Stick Left: Axis 2, from 0 to -1
- Right Stick Right: Axis 2, from 0 to +1
- Right Stick Up: Axis 3, from 0 to -1
- Right Stick Down: Axis 3, from 0 to +1
- Right Stick Click: Button 14
- Left Bumper: Button 6
- Right Bumper: Button 7
- **Left Trigger: NOT RECOGNIZED**
- **Right Trigger: NOT RECOGNIZED**
- **Back: NOT RECOGNIZED**
- Start: Button 11

I tested this issue on Windows 10 and macOS, the controller works normally on Windows, but is glitchy on Mac.

#### Reproduction steps/code
- Create a new LibGDX project for Desktop, with the lwjgl3 backend, libgdx v1.9.9-SNAPSHOT, and the Controllers library included.
- Have the following code in the Desktop launcher class:
```java
public class Example extends ApplicationAdapter {
    public static void main(String[] arg) {
        new Lwjgl3Application(new Example(), new Lwjgl3ApplicationConfiguration());
    }
    @Override
    public void create() {}
    @Override
    public void render() {}
    @Override
    public void dispose() {}
}
```

- Connect an Xbox One S controller via Bluetooth.
- Run the application.
- Errors will be printed to the console.

#### Version of LibGDX and/or relevant dependencies
LibGDX `1.9.9-SNAPSHOT`, commit `e8abed6`.

#### Stacktrace
```
[LWJGL] GLFW_INVALID_VALUE error
	Description : Invalid button in gamepad mapping 030000005e040000fd02000003090000 (Xbox Wireless Controller)
	Stacktrace  :
		org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:819)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:81)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:88)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS

**Comment by EtK2000** [comment]
This looks like it might be an issue in lwjgl/glfw.
Try it with a different backend and see if it works.

I'd advise reporting it to them.

**Comment by rafaskb** [comment]
The issue was in the GLFW backend, and was fixed today, as seen here: https://github.com/glfw/glfw/issues/1447

Now we just need to wait for lwjgl to incorporate glfw's changes, and for libdgx to do the same with lwjgl.

**Comment by MrStahlfelge** [comment]
Hi, please take a look at [gdx-controllers v2 prerelease snapshot](https://github.com/libgdx/gdx-controllers). It should solve your issue.
