### ISSUE TITLE
IOS Audio Updated

### ISSUE THREAD

**Issue by eix128** [libgdx/libgdx#5382]
Hi as I look IOSAudio on Libgdx but there is no microphone and speaker implementation.
But I have fixed the robovm issues for libgdx : 

To use library you need to patch mobivm :
https://github.com/MobiVM/robovm/issues/329

With new patch you can use Microphone and Speaker with Libgdx.
Feel free to use.

Example to use Robovm with Libgdx Audio for IOS:
It works fine on IOS Simulator but I had noisy sounds.
If someone also found a solution for that.
Please help.

ShortArrayQueue.java :
https://paste.ofcode.org/F2TuLhhXWw4Gqcd52jHGES

IOSRecorder2.java
https://paste.ofcode.org/3tiL2UXCjX43Tj6rqQe4XL

IOSPlayer.java
https://paste.ofcode.org/SzDys3fXgwiLaGzsgvu559

AudioUtils.java
https://paste.ofcode.org/b43yAcFaLLFKqR3TWy7CyG

Simple example on Robovm echo microphone to speaker back :
MyViewController.java
https://paste.ofcode.org/skFyJuVFAMQGN9qnLpcVay

affected platforms
- [ x ] iOS (robovm)

**Comment by eix128** [comment]
AudioUtils.java
https://paste.ofcode.org/b43yAcFaLLFKqR3TWy7CyG

**Comment by EtK2000** [comment]
If you want this implemented, it's faster to do it yourself.

**Comment by eix128** [comment]
git diff result : 
https://paste.ofcode.org/n48qRZGShkB7pz4zcp6mqE
