### ISSUE TITLE
Make Vector2.angle and Vector2.angleRad consistent

### ISSUE THREAD

**Issue by jcornaz** [libgdx/libgdx#5388]
### Current situation
* `Vector2.angle()` returns values between `[0, 360]`
* `Vector2.angle(Vector2)` returns values between `[-180, 180]` 
* `Vector2.angleRad()` returns values between `[-Math.PI, Math.PI]`
* `Vector2.angleRad(Vector2)` returns values between `[-Math.PI, Math.PI]`

There's two inconsistencies here.
1. Result range: Why only one of these function returns always positive values, while the 3 others don't?
2. Naming: Why some function are named with the angle unit, and not the others?

### Proposition:
1. Add `angleDeg()` and `angleDeg(Vetor2)` functions returning *both* values between `[-180, +180]`
2. Deprecate `angle()` and `angle(Vector2)` functions

This would make usage of angles in radians and degrees more consistent. Conversions would also be easier, since multiplying by `MathUtils.degreeToRadians` or `MathUtils.radiansToDegree` would always be enough.

### Reproduction steps/code

This:
```java
System.out.println(new Vector.2(0f, -1f).angleDeg()); // -90
System.out.println(new Vector.2(0f, -1f).angleRad()); // -Math.PI / 2
```

Would be preferable to:
```java
System.out.println(new Vector.2(0f, -1f).angle()); // 270
System.out.println(new Vector.2(0f, -1f).angleRad()); // -Math.PI / 2
```

### Version of LibGDX and/or relevant dependencies
1.9.8

### Please select the affected platforms
Platform is irrelevant here. This is math.

**Comment by obigu** [comment]
> Naming. Why is one named with the angle unit, and not the other?
I agree `angleDeg` would have been a better name although, from my experience, I don't think deprecating `angle` just for this reason would get enough support considering libGDX history on how it deals with backwards compatibility and deprectation PRs. Feel free to submit a PR though.

> Result range. Why is one always positive, and not the other?
I don't see an issue that "degrees methods" return in the range between `[0, 360]` and "radians methods" between `[-Math.Pi, Math.Pi]` because either you work with one or the other (and if you need converting it's trivial). It's simply a convention, it's common to use the `[-Math.Pi, Math.Pi]` range when working with polar coordinates.
What I agree is that consistency should be required for all methods with the same unit, so, ALL degrees methods should return in the `[0, 360]` range and ALL radians methods in the `[-Math.Pi, Math.Pi]`. Currently this is not the case (`Vector2.angle` and `Vector2.angle(Vector2 reference)` return in different ranges).

**Comment by jcornaz** [comment]
>Currently this is not the case (Vector2.angle and Vector2.angle(Vector2 reference) return in different ranges)

This is indeed way much worse. It advocate the need to unify the ranges of result for angle functions.

> I don't think deprecating angle just for this reason

Naming is a secondary reason. Range of return value is important. Theses inconsistencies in result ranges makes the usage of angle functions error-prone.

> (and if you need converting it's trivial)

It would be even more trivial if the ranges were consistent. Currently conversion needs to use 2 conditions, which means 3 execution paths to test. If the ranges were consistent, conversion would not need any condition and would have only on execution path to test.

>It's simply a convention, it's common to use the [-Math.Pi, Math.Pi] range when working with polar coordinates.

Yes. I haven't propose to change `angleRad` for that reason. But this convention is true regardless of the unit used. This is no excuse for having `angle` returning angles between `[0, 360]`.

**Comment by obigu** [comment]
>Yes. I haven't propose to change angleRad for that reason. But this convention is true regardless of the unit used. This is no excuse for having angle returning angles between [0, 360].

No, that convention is not true regardless of the unit used. The convention for degrees is [0, 360] and we must keep it like that.

**Comment by jcornaz** [comment]
>No, that convention is not true regardless of the unit used. The convention for degrees is [0, 360] and we must keep it like that.

Can you share the source of this statement?

I don't read anything like that here https://en.wikipedia.org/wiki/Sign_(mathematics).

GPS coordinates are also a good example of angle in degrees between [-180, 180] (for longitude) and between [-90, 90] (for the latitude).

**Comment by jcornaz** [comment]
> The word convention means that is what people usually use, nothing else, you won't find a statement online, just ask anybody how they usually work in 2D geometry.

So please, share the source stating that users usually use ranges between `[0, 360]` for angles in degrees.

Usually well established conventions can be found as statement in books or online. If no source of a "convention" can be found, then it is not a very good spread convention but more a personal preference.

Here's some conventions sources:
* Java conventions: https://www.oracle.com/technetwork/java/codeconventions-150003.pdf
* Kotlin code-style conventions: https://kotlinlang.org/docs/reference/coding-conventions.html
* Vector representation conventions: https://en.wikipedia.org/wiki/Euclidean_vector?section=8#Representations
* Sign conventions: https://en.wikipedia.org/wiki/Sign_(mathematics)#Sign_convention
* Human names conventions: https://en.wikipedia.org/wiki/Personal_name#Naming_conventions

I could continue this endless list, but that's not the point. The point is : "Well established conventions have written sources"

And about "just ask anybody how they usually work in 2D geometry": I studied 4 years and worked full-time 2 years in the domain of 2D geometry. I'm not able to remember such convention.
This is also why I am astonished by your statement, and therefore ask you to source it.

>those 2 links you provide don't proof all the functions on the engine work on that range 

Indeed they don't. But (I think) it is a good clue that the "convention" you mentioned either doesn't exist or is not that strong. Otherwise it would have been harder to find examples in such popular frameworks. But I know this is no proof. That's why I asked you to source your statement, which is the only way to *prove* the existence of such convention.

Be also aware that I found theses links by genuinely looking for confirmation of your statement. I thought that this convention could be confined to the video-game world, which would have explained my misunderstanding of the subject. But it doesn't seem to be the case. Or at least I haven't found a good source of it.

If both `[-180, +180]` and `[0, 360]` are possible, I think, `[-180, +180]` should be favored in order to have a better consistency with the other functions.

**Comment by obigu** [comment]
Wow. There was no need for all that, I've clearly defined what I meant by `convention` but you seem just to have ignored it.

Anyway, feel free to provide a PR, I think I've made my point.

**Comment by jcornaz** [comment]
>I've clearly defined what I meant by convention but you seem just to have ignored it.

Either I've not understood your point or you haven't read my answer. Can you please point out what I have "ignored"?

>feel free to provide a PR

I may open a PR. But shouldn't we agree on what to do first?

**Comment by Darkyenus** [comment]
All `Vector` methods dealing with angles in degrees use plain names, those in radians have `Rad` suffix. That seems pretty consistent and beginner friendly, so I see no need to change that.

Similarly, using 0-360 seems like a more beginner friendly way to represent angles, it is well documented and user code may rely on it.

I frankly don't see any issue here. From what I have seen and experienced, projects use either degrees or radians, without hardly any mixing of the two, so having two separate "conventions" doesn't seem like a big deal, especially considering that most functions don't care whether they get -10 or 350 deg, and angles are separately normalized if they do.

**Comment by jcornaz** [comment]
I aggree it is not a "big deal". I'm only saying it can be better.

Howver, we probably not have the same definition of "beginner friendly". I find it very difficult for a beginner to understand why none of `angle()`, `angle(Vector2)`, `angle()` and `angleRad(Vector2)` behave consistently. It would be so much simpler if they would all be consistent.

>user code may rely on it.

That's why I don't propose to change it, but to deprecate it and provide an alternative.

**Comment by jcornaz** [comment]
I wonder how can one argue that the `angle()` function doesn't fall into the "black sheep" code smell.

Let me state it once again: `angle()` is the **only** angle function (out of 4) which don't return values between `[-halfCircle, +halfCircle]`.

**Comment by obigu** [comment]
> I wonder how can one argue that the `angle()` function doesn't fall into the "black sheep" code smell.
> 
> Let me state it once again: `angle()` is the **only** angle function (out of 4) which doesn't return values between `[-halfCircle, +halfCircle]`.

Nobody has. 

This inconsistency was actually detected by me on my first reply before you edited your post to add it.

>What I agree is that consistency should be required for all methods with the same unit, so, ALL degrees methods should return in the [0, 360] range and ALL radians methods in the [-Math.Pi, Math.Pi]. Currently this is not the case (Vector2.angle and Vector2.angle(Vector2 reference) return in different ranges).

I'll create a PR for it (waitig for some fixes to be merged as libGDX project doesn't currently build).

So please, stop editing your posts and comments hours after reponses have been made, otherwise the discussion doesn't make any sense.

**Comment by jcornaz** [comment]
Thanks @obigu.

I only update my initial request in order to make it clearer, since it was apparently not clear enough.

But the reasons of my proposal as wall as the proposal itself hasn't changed.

**Comment by genrym** [comment]
Hi guys.

Just to sum it up - we all agree that there are inconsistent APIs behaviour.

So there are 2 approaches that are discussed here:
1. In next version - deprecate old APIs and introduce newer ones
    a. In next version + 1 - remove the deprecated APIs
    b. (optional) in next version + 2 - rename the new APIs to the old APIs naming
2. Change the behavior of the inconsistent API

I find first approach more constructive and more appealing as per backward compatibility aspects for the consumers of the inconsistent API.
First approach will clearly state in compile time what and how to adapt (given all Javadoc is in place), whether the second approach will just break the consumer.
Wdyt?
