### ISSUE TITLE
AndroidFragmentApplication.java with AndroidX Not compatible 

### ISSUE THREAD

**Issue by ishroid** [libgdx/libgdx#5393]
This class [AndroidFragmentApplication](
        libgdx/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidFragmentApplication.java
      ) use android support library internally but now google forcing us to build your application to target API  **28** , so we have to use AndroidX for this.

AndroidFragmentApplication.java is not compatible with AndroidX.

Please update AndroidFragmentApplication.java to work with AndroidX or I would generate a Pull request.

Thank you

**Comment by EtK2000** [comment]
You should create a pull request, that's the fastest way to get it implemented.

**Comment by MrStahlfelge** [comment]
At the moment, it is not recommended to use AndroidX in libraries. It breaks compatibility for projects not using Jetpack.

You should use jetifier instead.

**Comment by msgkatz** [comment]
For whom it may concern, here is version of gdx-backend-android module updated with androidx
https://github.com/msgkatz/gdx-backend-androidx

Works like a charm for one of my projects.

**Comment by phkoester** [comment]
I just copied the class AndroidFragmentApplication to AndroidxFragmentApplication (retaining the pkg) and derived from androidx.app.Fragment. Works like a charm. Farewell, AndroidApplication!

**Comment by cypherdare** [comment]
I think a good barometer for when to switch is when Google starts switching their own libraries like Google services. It hasn't happened yet. Jetifier is working fine with LibGDX for now.

**Comment by mgolebiowski95** [comment]
Hi, I'm writing to ask if there will be official support for AndroidX in any further update? Or is there any plans?

**Comment by SimonIT** [comment]
My PR #5846 makes libgdx AndroidX compatible

**Comment by lastpeony** [comment]
> My PR #5979 makes libgdx AndroidX compatible

how do i install your build ? currently i am using gradle to implement libgdx in my project.

**Comment by SimonIT** [comment]
@lastpeony You can use this by using the current libgdx snapshot, if the jenkins build is done

**Comment by bunty69** [comment]
> I just copied the class AndroidFragmentApplication to AndroidxFragmentApplication (retaining the pkg) and derived from androidx.fragment.app.Fragment. Works like a charm. Farewell, AndroidApplication!
> 
> But of course I hope we will see an AndroidX fragment in the next libGDX release ...

**Comment by bunty69** [comment]
> I just copied the class AndroidFragmentApplication to AndroidxFragmentApplication (retaining the pkg) and derived from androidx.fragment.app.Fragment. Works like a charm. Farewell, AndroidApplication!
> 
> But of course I hope we will see an AndroidX fragment in the next libGDX release ...


Hi, Can you help me how you done this..., I am looking some workaround for this.

**Comment by bunty69** [comment]
> For whom it may concern, here is version of gdx-backend-android module updated with androidx
> https://github.com/msgkatz/gdx-backend-androidx
> 
> Works like a charm for one of my projects.

Can you tell me how you used that..., i have tried to import it as library but got Gradle errors

**Comment by msgkatz** [comment]
> > For whom it may concern, here is version of gdx-backend-android module updated with androidx
> > https://github.com/msgkatz/gdx-backend-androidx
> > Works like a charm for one of my projects.
> 
> Can you tell me how you used that..., i have tried to import it as library but got Gradle errors

Here are sources of little mobile app, where I used that lib above
https://github.com/msgkatz/chartsnrates
