### ISSUE TITLE
Libgdx compile fix OSX

### ISSUE THREAD

**Issue by eix128** [libgdx/libgdx#5394]
Please ensure you have given all the following requested information in your report.

#### Issue details
Hi , I got libgdx source from GitHub.But when I try to compile with
./gradle assemble

https://paste.ofcode.org/SFQ8PHsMQX7ApAtdMkdWM7

I fixed the problem by adding patch

diff --git a/build.gradle b/build.gradle
index a1008d1cf..12b18232c 100644
--- a/build.gradle
+++ b/build.gradle
@@ -31,6 +31,7 @@ allprojects {
     }
 
     repositories {
+        google()
         mavenCentral()
         jcenter()
         maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x ] MacOS

**Comment by obigu** [comment]
Duplicate https://github.com/libgdx/libgdx/pull/5352
