### ISSUE TITLE
Scene2D Actor function setWidth and setHeight don't work.

### ISSUE THREAD

**Issue by SpyceTewan** [libgdx/libgdx#5396]
Please ensure you have given all the following requested information in your report.

#### Issue details
I want scale my actors but it doesn't work. Am I doing something wrong?

#### Reproduction steps/code
setWidth and setHeight don't change the size of ANY actor.

#### Please select the affected platforms
- [x ] Android
- [ x] iOS (robovm)
- [ x] iOS (MOE)
- [ x] HTML/GWT
- [x ] Windows
- [x ] Linux
- [x ] MacOS

**Comment by Darkyenus** [comment]
It is pretty unlikely that this is the case, because it works well for probably everybody else. You will have to supply [SSCCE](http://sscce.org/) if you really think that you have found a libGDX bug.

Do not skip the issue template instructions.

**Comment by NathanSweet** [comment]
Scale doesn't affect width/height values by design.
