### ISSUE TITLE
NullPointer Exception thrown for libgdx backend when e2e testing

### ISSUE THREAD

**Issue by TijmenGraft** [libgdx/libgdx#5397]
Please ensure you have given all the following requested information in your report.

#### Issue details
NullPointer exception thrown in e2e test suite.

#### Reproduction steps/code
The error happens when running the code in with JUnit Jupiter. This error occured multiple times before. But suddenly disappeared over nights. But the current error seems to be consistent. We are trying to setup up the currentScreen but some dependecies from LibGdx seems to not be instantiated.

Is there a way to force the instantation of instances? If necessary I can add more example code.

#### Version of LibGDX and/or relevant dependencies
1.9.8
Libwgt 3 

#### Stacktrace
```java
BitmapFont font = new BitmapFont();
Method threw 'java.lang.NullPointerException' exception. Cannot evaluate com.badlogic.gdx.graphics.g2d.BitmapFont.toString()

# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffa65c5f46d, pid=15100, tid=0x00000000000022a4
#
# JRE version: Java(TM) SE Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.171-b11 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [lwjgl_opengl.dll+0xf46d]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# D:\...\Project\hs_err_pid15100.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
AL lib: (EE) alc_cleanup: 1 device not closed
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Darkyenus** [comment]
You will have to be more specific, but there is a lot of things that can go wrong here. Issues with concurrency, running multiple tests in the same VM (as libGDX uses global state quite a bit), failure to initialize OpenGL or natives...

From your description I would look into threading first - i.e. don't have any, run everything from the main thread, especially when dealing with classes that have external (OpenGL) state (like BitmapFont).
