### ISSUE TITLE
NPE on BitmapFont

### ISSUE THREAD

**Issue by guichazan** [libgdx/libgdx#5406]
Hi,

Not sure when this started to occur, but using the last snapshot is throwing:

java.lang.NullPointerException
com.badlogic.gdx.graphics.g2d.BitmapFont.<init>(BitmapFont.java:158)
com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:200)
com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:188)

... when i try to load FontAwesome.

**Comment by Darkyenus** [comment]
[Please follow the issue template.](https://github.com/libgdx/libgdx/wiki/Getting-Help)

**Comment by guichazan** [comment]
Hi,

This can be easibly reproduced: 

FreeTypeFontGenerator.FreeTypeFontParameter parameter = new FreeTypeFontGenerator.FreeTypeFontParameter();
parameter.characters = "\uFF20";
... other parameters as usual
BitmapFont b = generator.generateFont(parameter);

The tip is to use a character that is NOT HANDLED by the font. I use the roboto font in my project

**Comment by NathanSweet** [comment]
@guichazan If you

**Comment by NathanSweet** [comment]
Please provide an SSCCE next time. http://n4te.com/x/5497-dTa4.txt
