### ISSUE TITLE
Why Camera is not an Actor?

### ISSUE THREAD

**Issue by xahon** [libgdx/libgdx#5409]
#### Issue details
`Camera` extends `Object` but it can be moved like any `Actor`. There is no common interface between them. So it's impossible to add an `Action` to it (To make a smooth moving for example. You need an `ActionExecutor` wrapper for that and overriding methods for both `Actor` and `Camera` classes to keep persistence in the code)

#### Reproduction steps/code
```Java
new Camera().addAction(new SomeAction());
Actor actor = new Camera();
```

#### Version of LibGDX and/or relevant dependencies
1.9.8

#### Please select the affected platforms
- [X] Android
- [X] iOS (robovm)
- [X] iOS (MOE)
- [X] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

It's definitely design issue

P.S. Also `Camera` has signature `.position.set` to change its position. But `Actor` has `setPosition`. Both have different count of overloads

**Comment by Tom-Ski** [comment]
Camera is not part of the scene2d graph at all, and nor should it be. If you want to make it an actor, you can make a wrapper Actor and use that instead.

**Comment by NathanSweet** [comment]
libgdx is not primarily a scene graph. This is a strength, as it is a big mistake to force everything into a scene graph.
