### ISSUE TITLE
The reason of setOrigin doesn't affect Actor's position 

### ISSUE THREAD

**Issue by xahon** [libgdx/libgdx#5410]
#### Issue details
Origin is the center of the object. If origin is outside and object having position (0, 0) it's logical that origin point must be at (0, 0) and object must keep offset from origin and not only affect rotation/scale but position too.

#### Reproduction steps/code
```Java
Actor actor = new Image("something.png");
actor.setPosition(0, 0);
actor.setOrigin(1000, 1000); // Nothing happened
actor.setOrigin(-1000, -1000); // Nothing happened
```

#### Version of LibGDX and/or relevant dependencies
1.9.8

#### Please select the affected platforms
- [X] Android
- [X] iOS (robovm)
- [X] iOS (MOE)
- [X] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

Another design issue

**Comment by Darkyenus** [comment]
`scene2d` implements a 2D scenegraph and such has different needs than 3D scenegraph that you are probably familiar with. In this context, it makes more sense that `Actor`s origin comes into consideration only for scaling and rotation, as it simplifies most operations that deal with position.

Most applications of `scene2d` use rectangular actors (UI, platformers, top-down games...) where the point in the center of the rectangle (your suggested origin) is really used only for scaling and rotation, all position/size related logic deals with the rectangle's corners.

This is not a design issue, the design here is sound. One could argue that it shouldn't be called origin but something like "transformCenter", as "origin" really does suggest something related to position, but changing that now would break too much code. The documentation on this could be improved though.

**Comment by xahon** [comment]
@darkyenus the name doesn't matter. It implies, as you say, the center of transformation. Translation is one of the existing transformation. It exists in 4x4 matrix of any 3d and 3x3 matrix of any 2d object. It is not simplification but issue. It can be defaulted to 0, 0 to keep things as it is at now. How often people override setPosition method to offset its target position to the left and bottom by a half width and height respectively? Is this convinient? To keep ability to rotate around a point they can add a separate method for this. Major version increment is soon its time to break compatibility with older api

**Comment by NathanSweet** [comment]
scene2d has been in use for more than 8 years. We are not going to change how origin works.

**Comment by NathanSweet** [comment]
I should say, while your proposed origin behavior does make sense, I feel in practice it is not necessary for 2D and the increased complexity for actors to render while respecting origin isn't worthwhile. Still, one of the strengths of scene2d is its simplicity. You are free to write actors that use the origin as you desire.
