### ISSUE TITLE
Can I set the model as parent(like unity)?

### ISSUE THREAD

**Issue by LukeDev2K** [libgdx/libgdx#5414]
#### Issue details
Hi guys, I created multi modelInstance object from different assets, can i set one as the parent, then when I set transform value on it, the children transform change as well(like in unity)  

thanks!

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by EtK2000** [comment]
This should be in the forums or irc, not a issue.

**Comment by LukeDev2K** [comment]
> This should be in the forums or irc, not a issue.

thank you, I will submit the question to the forum, but I will glad if someone tells me the answer here

**Comment by EtK2000** [comment]
I'm not sure if anyone will, you can try getting a response, but AFAIK answers aren't really given here to discourage creating issues for questions.

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
