### ISSUE TITLE
Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-4.6-bin.zip'

### ISSUE THREAD

**Issue by Unlimiter** [libgdx/libgdx#5419]
Hello! I researched on this problem a lot, but I still don't get any solutions.
My problem is when I generate a new LibGDX Project with the "gdx-setup.jar" file, it prints this message in the bottom console display (in gdx-setup window):
```
Generating app in C:\\Users\unlimiter\eclipse-workspace\test
Executing 'C:\Users\unlimiter\eclipse-workspace\test/gradlew.bat clean --no-daemon'
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/4.6/userguide/gradle_daemon.html.

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/4.6/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 1536000KB object heap


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
Done!
To import in Eclipse: File -> Import -> Gradle -> Gradle Project
To import to Intellij IDEA: File -> Open -> build.gradle
To import to NetBeans: File -> Open Project...
```
I ignored it and went to Eclipse and imported a new Existing Gradle Project (which is "C:\Users\unlimiter\eclipse-workspace\test"), and an error occurs as the project finishes to get imported:
```
Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-4.6-bin.zip'.
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/4.6/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 1536000KB object heap
```

**OS/System Info:**
- OS: Windows 7
- Windows Edition: Edition Integrale
- Service Pack: 1
- Processor: Intel Pentium 4 CPU 2.80GHz  2.79GHz
- RAM: 1.75Gb (1.17Gb used)
- System Type: 32-bit OS

**Eclipse IDE Info:**
- Version: 2018-09 (4.9.0)
- Build ID: 20180917-1800

**Gradle Info:**
- Version: 3.0.0.v20181017-2330-s

**Comment by Tom-Ski** [comment]
In gradle.properties file increase your ram allowance. Or try decreasing it since you are on a machine with little ram

**Comment by Unlimiter** [comment]
> In gradle.properties file increase your ram allowance. Or try decreasing it since you are on a machine with little ram.
> 
> There isn't much we can do about this otherwise, IDE is RAM hungry, and so is Gradle.

I tried to decrease it but nothing appears to be solved, I'll try to decrease it more.
Anyways, thanks for your help! :)

**Comment by SteveSmith16384** [comment]
I have the same issue.  I changed the setting all the way to -Xmx4000m, and still get "Could not reserve enough space for 4096000KB object heap".  If I try and allocate any more, I get "Invalid maximum heap size: -Xmx4100m".
