### ISSUE TITLE
libGDX Project Setup - FAILURE: Build failed

### ISSUE THREAD

**Issue by DarthYuber** [libgdx/libgdx#5421]
Hi,

I used "libGDX Project Setup" and then I get a error message:

https://i.imgur.com/zx7qkPm.png

Did I do something wrong? I have JDK etc installed.

![ddd](https://user-images.githubusercontent.com/44409784/47376198-a993bd80-d6fa-11e8-8fde-7bbd954124ac.png)

**Comment by piotr-j** [comment]
Most likely you can ignore that error. Open the generated project in idea or other ide if you like pain.

Dunno whats the point of the error box in the setup app, it just confuses people.

**Comment by georgwarden** [comment]
@piotr-j Actually, it is a Gradle error and it still appears if you try to import the project in IDEA or AS.

**Comment by RobinBen** [comment]
@georgwarden thank you for your solution :) I almost gave up
@DarthYuber I had the same problem and made it work now by following georgewarden's solution but i also had to remove the following line from the AndroidManifest.xml to make it work in AS.
`<uses-sdk android:minSdkVersion="9" android:targetSdkVersion="28" />`
