### ISSUE TITLE
Unable to write to Pixmap.getPixels() directly in GWT

### ISSUE THREAD

**Issue by tylerhasman** [libgdx/libgdx#5423]
Please ensure you have given all the following requested information in your report.

#### Issue details
I need to quickly change data in a pixmap. For the desktop version I do this by writing directly to the backing buffer of the pixmap. In GWT I cannot do this because the buffer that is being returned by getPixels() has a capacity of 1 which is obviously not correct.

#### Reproduction steps/code
```
public void putPixel(Pixmap changes, int x, int y, int color, int width, int height) {
        ByteBuffer pixels = changes.getPixels();

        int index = y * width * 4 + x * 4;

        Color c = new Color(color);

        pixels.put(index, (byte) (c.r * 255));
        pixels.put(index + 1, (byte) (c.g * 255));
        pixels.put(index + 2, (byte) (c.b * 255));
        pixels.put(index + 3, (byte) (c.a * 255));
 }
```

Version
1.9.8

Platform
- [ X] HTML/GWT

**Comment by tylerhasman** [comment]
So I found out if I do this:
`IntBuffer pixels = (IntBuffer) changes.getPixels();`
instead of
` ByteBuffer pixels = changes.getPixels()`
I can get it to compile but it doesn't seem to actually copy any data as the pixmap is blank.

**Comment by piotr-j** [comment]
Pixmap is emulated on GWT, there is not buffer to modify. https://github.com/libgdx/libgdx/blob/master/backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/graphics/Pixmap.java#L404

**Comment by tylerhasman** [comment]
Is there any other way to update a pixmap quickly then? I have a 'worms' like game and need the terrain to be editable down to the pixel so I can't compromise on this. Right now, copying 1000x500 pixels to the pixmap takes about 30 seconds which is far too long and also uses about 3GB of memory which is insane. I've tried other methods but they don't seem to work.

**Comment by piotr-j** [comment]
Poking pixels for terrain sounds somewhat suboptimal, did you try fbos? You can use them like so: https://github.com/piotr-j/libgdxplayground/blob/master/core/src/io/piotrjastrzebski/playground/fogofwar/FogOfWarTest.java
Not exactly, what you want but close enough to get you where you want to go.
