### ISSUE TITLE
Player Movement not the same on other PC

### ISSUE THREAD

**Issue by DarthYuber** [libgdx/libgdx#5424]
If I play my game on a different PC my player character moves suddenly much slower?
I sent it to my brother and on his PC he runs a little faster!?

How can I set my game that it runs on every PC the same speed?
This is how I move my player:

```
if( target_x > playerX){ playerX+=MOVEMENT_SPEED;  } 
         if( target_x < playerX){ playerX-=MOVEMENT_SPEED;  } 
         if( target_y < playerY){ playerY-=MOVEMENT_SPEED; } 
         if( target_y > playerY){ playerY+=MOVEMENT_SPEED; }
```

target_x > playerX is just so my player moves like in Pokemon games, he can only move tiles.

I tried using delta time like in Slick but then the movement becomes very laggy and unsmooth.

```
if( target_x > playerX){ playerX+=(60*Gdx.graphics.getDeltaTime())*MOVEMENT_SPEED;  } 
         if( target_x < playerX){ playerX-=(60*Gdx.graphics.getDeltaTime())*MOVEMENT_SPEED;  } 
         if( target_y < playerY){ playerY-=(60*Gdx.graphics.getDeltaTime())*MOVEMENT_SPEED; } 
         if( target_y > playerY){ playerY+=(60*Gdx.graphics.getDeltaTime())*MOVEMENT_SPEED; }
```

**Comment by Tom-Ski** [comment]
This is not a LibGDX issue, please use the forum for personal help requests.
