### ISSUE TITLE
Plan for WASM

### ISSUE THREAD

**Issue by SirHaswell** [libgdx/libgdx#5429]
Hello ! 

Have you plan in a future for Web Assembly support ?

**Comment by tr7zw** [comment]
Maybe using TeaVM or something comparable to compile libgdx games to web assembly should be possible.

**Comment by zerh** [comment]
@tr7zw, using bytecoder
https://github.com/mirkosertic/Bytecoder

**Comment by CoenRijsdijk** [comment]
I'm currently working on a project which can be used to compile a native app to web(WASM ), using [Bytecoder](https://github.com/mirkosertic/Bytecoder) .
Check it here: https://github.com/squins/libgdx-wasm-with-bytecoder
