### ISSUE TITLE
MOE status bar overlap & wrong touch

### ISSUE THREAD

**Issue by doit-ceo** [libgdx/libgdx#5432]
#### Issue details
Apple rejected our app, they rejected it because of the status bar not shown, it's 100% LibGDX app, but not a game. 

When we enabled it using  config.statusBarVisible = true; 

we got 2 issues 

- Status bar overlap with the app
- The touch input is shifted downward (as if the status bar is shown correct)

#### Reproduction steps/code
config.statusBarVisible = true;

#### Version of LibGDX and/or relevant dependencies
1.9.8

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [X] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by julienvillegas** [comment]
Should this be raised as an issue in the MOE repository?

**Comment by doit-ceo** [comment]
Maybe I confused you by "not a game" but we do build normal apps by LibGDX , I didn't want game developers to fear that apple will reject their games when they are not showing the status bar. 

But the app is totally based on LibGDX and not sure it's MOE issue,  this also seem very close to RoboVM issue https://github.com/libgdx/libgdx/issues/2766

**Comment by MrStahlfelge** [comment]
Closed. ios-moe support is removed from libgdx.
