### ISSUE TITLE
Kotlin - HTML5 target status

### ISSUE THREAD

**Issue by MauroCoppola** [libgdx/libgdx#5434]
#### Issue details
Hi, I'm new at using LibGDX and I'd like to write my games with Kotlin to learn both. In the dedicated [wiki page](https://github.com/libgdx/libgdx/wiki/Using-libGDX-with-Kotlin) it's indicated that it is not possible to export a game written in Kotlin for the web without TeaVM.
Is the information still valid? If yes, is there a guide to replace GWT with TeaVM?
Thanks!

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [X] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by EtK2000** [comment]
Don't post questions as issues, use the irc or the wiki.

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
