### ISSUE TITLE
OBB Patch Version ignored

### ISSUE THREAD

**Issue by alexMurz** [libgdx/libgdx#5437]
#### Issue details
```java
APKExpansionSupport.getAPKExpansionFiles(Context ctx, int mainVersion, int patchVersion)
```
lines 49-56
```java
if (patchVersion > 0) {
	String strPatchPath = expPath + File.separator + "patch."
			+ mainVersion + "." + packageName + ".obb";
	File main = new File(strPatchPath);
	if (main.isFile()) {
		ret.add(strPatchPath);
	}
}
```
in strPatchPath instead of patchVersion used mainVersion
is this intended behavior?

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
https://github.com/libgdx/libgdx/pull/5417/files
