### ISSUE TITLE
How to add Gradle AAR dependency to LibGDX?

### ISSUE THREAD

**Issue by RankoR** [libgdx/libgdx#5441]
I want to extend LibGDX to add AndroidX fragment support.

I've cloned Git repo (master) and imported it to IDEA (with Gradle).

It builds and tests are passed, but I don't know how to add `androidx.appcompat:appcompat` dependendency to `gdx-backend-android` module.

I've tried to add `compileOnly 'androidx.appcompat:appcompat:1.0.0'` to the `build.gradle` of this module (and synced gradle of course), it's added according to project details:

![image](https://user-images.githubusercontent.com/71142/47955896-c4deb280-dfaf-11e8-98f3-9f9cab980cac.png)

But I can't import class:

![image](https://user-images.githubusercontent.com/71142/47955900-cd36ed80-dfaf-11e8-97d0-2223511ed6bc.png)

I've also tried to add dependency like `compile 'androidx.appcompat:appcompat:1.0.0'` with no result.

I have no idea why it does not work. Did I miss something?

**Comment by EtK2000** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
