### ISSUE TITLE
Issue with GWT Html5 Deploy & gwtCompile

### ISSUE THREAD

**Issue by wdavies973** [libgdx/libgdx#5446]
Please ensure you have given all the following requested information in your report.

# Issue details
GWT compile fails with:
```
Compiling module com.prototype.mars.GdxDefinition
   [ERROR] Hint: Check that your module inherits 'com.google.gwt.core.Core' either directly or indirectly (most often by inheriting module 'com.google.gwt.user.User')
```

# Reproduction steps/code
## Relevant files
[HTML build.gradle](https://pastebin.com/LvKfvfdL)
[gwt.xml](https://pastebin.com/BYB3S4st)
From the project level `build.gradle`
```
project(":html") {
    apply plugin: "gwt"
    apply plugin: "war"

    dependencies {
        implementation project(":core")
        implementation "com.badlogicgames.gdx:gdx-backend-gwt:$gdxVersion"
        implementation "com.badlogicgames.gdx:gdx:$gdxVersion:sources"
        implementation "com.badlogicgames.gdx:gdx-backend-gwt:$gdxVersion:sources"
        implementation "com.badlogicgames.gdx:gdx-box2d:$gdxVersion:sources"
        implementation "com.badlogicgames.gdx:gdx-box2d-gwt:$gdxVersion:sources"
        implementation "com.badlogicgames.ashley:ashley:$ashleyVersion:sources"

    }
}
```
## Explanation
When I run `gradlew html:dist`, the error is produced. I can `Make Build` just fine (I'm using Android studio)

Android Studio actually auto suggests `inherits` packages in the gwt.xml, and as seen [here](https://imgur.com/a/ShobtSl), the 'Core' class isn't suggested in auto-suggestions which probably means the file isn't present.

Also, a side note for improving the gdx-setup program. The gdx-setup automatically generates the URL `http://google-web-toolkit.googlecode.com/svn/trunk/distro-source/core/src/gwt-module.dtd` for `GdxDefinition.gwt.xml` & `GdxDefinitionSuperdev.gwt.xml`. However, this URL returns a 404 request and appears to be inactive. I changed the URL to `http://www.gwtproject.org/doctype/2.8.0/gwt-module.dtd` (which I'm assuming is the right URL, correct me if I'm wrong)

I've tried removing annotations, using Java 1.7, and reworking all code to make sure it uses cross platform LibGDX code that's compatible with HTML5. Nothing has worked so far.

# Version of LibGDX and/or relevant dependencies
GWT: 2.8.0
GWT Gradle Plugin: 1.0.6
GDX: 1.9.8
Gradle: 4.7
Java: 1.6

# Stacktrace
Stacktrace doesn't look very helpful, but I'll include it anways:
[link](https://pastebin.com/3JhaRM4t)

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [x ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
Run on command line
`./gradlew html:dist --debug` and pastebin the entire log please.

**Comment by wdavies973** [comment]
https://pastebin.com/qLaErp9P

**Comment by MobiDevelop** [comment]
The libGDX GWT backend module inherits `com.google.gwt.user.User` inherits `com.google.gwt.core.Core`. You shouldn't need to inherit it yourself.

**Comment by wdavies973** [comment]
Tried it without any of those, with `com.google.gwt.user.User` and `com.google.awt.core.Core`. None of the above worked. @MobiDevelop @Tom-Ski

**Comment by Tom-Ski** [comment]
Can you generate a new project and run from there? Perhaps running with superDev may give better info, or just html:compileGWT itself.
