### ISSUE TITLE
Intermittent crashes using BitmapFontCache.addText

### ISSUE THREAD

**Issue by tomcashman** [libgdx/libgdx#5448]
#### Issue details
I've recently upgraded our game to use 1.9.8 and we're getting regular crashes using BitmapFontCache.addText. Stacktrace provided below. This may be related to #5346 ???

#### Version of LibGDX and/or relevant dependencies
1.9.8

#### Stacktrace
```java
IndexOutOfBoundsException: index can't be >= size: 5 >= 5
    at com.badlogic.gdx.utils.Array.get(Array.java:154)
    at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:158)
    at com.badlogic.gdx.graphics.g2d.BitmapFontCache.addText(BitmapFontCache.java:505)
    at com.badlogic.gdx.graphics.g2d.BitmapFontCache.addText(BitmapFontCache.java:480)
...
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x ] Windows
- [x ] Linux
- [x ] MacOS

**Comment by tomcashman** [comment]
We were previously using 1.9.6 with no issue.

**Comment by NathanSweet** [comment]
Do you get the problem with the nightly build? There have been some changes since 1.9.8. I'd guess #5346 is probably unrelated.

**Comment by Tom-Ski** [comment]
Pretty sure this is misuse of threading. You will never get here otherwise. Please post the full stacktrace, and code that can reproduce.

**Comment by Tom-Ski** [comment]
Please feel free to reopen when more info is provided.

**Comment by tomcashman** [comment]
I confirmed it was a threading issue. Thanks for responding and sorry for clogging the issue tracker!
