### ISSUE TITLE
Intersector.overlapConvexPolygon(a,b,mtv) - mtv.normal have wrong value when overlaping triangle and rectangle polygons

### ISSUE THREAD

**Issue by Mastercho321** [libgdx/libgdx#5461]
I have two rectangles - one at the left side of the screen and one at the right. The triangle starts in the center of the screen and I move it to left or right. Im also rotating the triangle to check if the collision detection work on all of its sides and edges. When I move the triangle to right and it contacts with the right rectangle the preventOverlap method works fine. But when I move the triangle to left and it contacts with the left rectangle the preventOverlap method works only if the triangle touches the wall with one of its edges, if it touches the wall with one of its sides(when im rotating the triangle and the sides are parallel) it moves through the wall fast.

This happens because mtv.normal.x == -1.0 (The direction of the separation) and the triangle is moved to the other side of the wall. But i cant understand why Intersector.overlapConvexPolygons(poly1,poly2,mtv) sets mtv.normal.x to -1.0 , which is wrong.

public boolean overlaps(MyActor other)
{
Polygon poly1 = this.getBoundaryPolygon();
Polygon poly2 = other.getBoundaryPolygon();

if(!poly1.getBoundingRectangle().overlaps(poly2.getBoundingRectangle()))
return false;

return Intersector.overlapConvexPolygons(poly1,poly2);
}

public Vector2 preventOverlap(MyActor other)
{
Polygon poly1 = this.getBoundaryPolygon();
Polygon poly2 = other.getBoundaryPolygon();

if(!poly1.getBoundingRectangle().overlaps(poly2.getBoundingRectangle()))
return null;

Intersector.MinimumTranslationVector mtv = new Intersector.MinimumTranslationVector();
boolean polygonOverlap = Intersector.overlapConvexPolygons(poly1,poly2,mtv);

if(!polygonOverlap)
return null;

this.moveBy(mtv.depth * mtv.normal.x,mtv.depth * mtv.normal.y);
return mtv.normal;
}
This is how I create boundry polygon for the triangle :

public void setBoundaryTriangle()
{
float[] vertices = new float[6];

vertices[0] = 0;
vertices[1] = 0;
vertices[2] = getWidth();
vertices[3] = 0;
vertices[4] = getWidth() / 2;
vertices[5] = getHeight();

boundaryPolygon = new Polygon(vertices);
}
and for the rectangle :

public void setBoundaryRectangle()
{
float w = getWidth();
float h = getHeight();
float[] vertices = {0,0,w,0,w,h,0,h};
boundaryPolygon = new Polygon(vertices);
}
This is the getBoundryPolygon method :

public Polygon getBoundaryPolygon()
{
boundaryPolygon.setPosition(getX(),getY());
boundaryPolygon.setOrigin(getOriginX(),getOriginY());
boundaryPolygon.setRotation(getRotation());
boundaryPolygon.setScale(getScaleX(),getScaleY());

return boundaryPolygon;
}

**Comment by kdenzel** [comment]
I think i know what @Mastercho321 means. I have an issue too with this function. I use this function as described. The vertices are in counter clockwise order and the Polygon is convex and the parameters are in correct order. Here is a graphic that explains the issue. If you try to move the yellow triangle out of the blue when it is overlapped like this ([see picture here](https://imagr.eu/up/7fqqd_unknown.png)), the yellow triangle gets pushed into the blue triangle.

[Here is the code. ](https://pastebin.com/15Pe1N3A)

**Comment by obigu** [comment]
Fixed in https://github.com/libgdx/libgdx/pull/6185
