### ISSUE TITLE
Can't increase max concurrent Gdx.net HTTP requests

### ISSUE THREAD

**Issue by costimuraru** [libgdx/libgdx#5462]
Please ensure you have given all the following requested information in your report.

#### Issue details
My app is triggering two HTTP requests, one of which might take a few seconds to load. I noticed however that the second request is not issued, until the first one completes. I would like for these HTTP calls to be made in parallel._Please provide the details of your issue_

#### Reproduction steps/code

Looking in the code, the `NetJavaImpl`  uses an `new AsyncExecutor(1);`, where 1 is the max concurrent requests. I would like to increase this (ie. to 2 or 3), however it doesn't seem to be possible since it is hard coded to 1.
https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/net/NetJavaImpl.java#L127
What would you recommend in order to make it possible to shoot multiple parallel HTTP requests to the server?

#### Version of LibGDX and/or relevant dependencies
1.9.6

#### Please select the affected platforms
- [x] Android
- [x] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by mgsx-dev** [comment]
Maybe a regression introduced here : https://github.com/libgdx/libgdx/commit/46eb90103f8b51ac5b90d74a47f3d577e7b17b91#diff-ead460e624940f939f21200edb7e5897R127

A solution could be revert back to `Executors.newCachedThreadPool(factory);` with factory setting threads as daemon.

**Comment by MobiDevelop** [comment]
It probably makes sense to allow for a limit to be specified, would it be preferred to default to 1 as it is today or go back to the unbounded newCachedThreadPool?

**Comment by mgsx-dev** [comment]
I would go for unbounded newCachedThreadPool which is IMO the common use case.
Only few edge cases need to limit thread pool.

**Comment by MobiDevelop** [comment]
Take a look at the commit on my fork and let me know if that's what you were thinking...

**Comment by mgsx-dev** [comment]
Sounds good to me.

I would add a note in changes.md to explain this is a breaking change : maybe some client code rely on the old thread limit.
