### ISSUE TITLE
Since PhysiX is 3-clause BSD now, why not have a libgdx module?

### ISSUE THREAD

**Issue by terefang** [libgdx/libgdx#5465]
Since PhysiX is 3-clause BSD now, why not have a libgdx module?

https://github.com/NVIDIAGameWorks/PhysX-3.4

**Comment by EtK2000** [comment]
It would be awesome to have one.
But it'll take much work to initially implement it, and more to maintain it.

**Comment by MobiDevelop** [comment]
I think this one is going to be on the community to create and maintain an extension if desired.
