### ISSUE TITLE
[Regression] GlyphLayout resulting in negative height

### ISSUE THREAD

**Issue by tomcashman** [libgdx/libgdx#5467]
#### Issue details
GlyphLayout.height is resulting in -3 when the font is flipped. However, when not flipped it works correctly. Attached SSCCE.

I was previously using 1.9.6 where this worked correctly when flipped (see output comparison below - can be reproduced by changing GDX version in build.gradle).

#### Reproduction steps/code
[fontHeightIssue.zip](https://github.com/libgdx/libgdx/files/2653574/fontHeightIssue.zip)

#### Version of LibGDX and/or relevant dependencies
1.9.9

#### Output Comparison
1.9.9
```
Line Height: 13.0
Cap Height: 10.0
Ascent: -1.0
Descent: -2.0
Glyph Layout Height: -3.0
```

1.9.6
```
Line Height: 13.0
Cap Height: 10.0
Ascent: -1.0
Descent: -2.0
Glyph Layout Height: 23.0
```

#### Please select the affected platforms
- [ x] Windows

**Comment by ilyaklyukin** [comment]
Height is broken on Android also.
https://github.com/libgdx/libgdx/blob/b9c9efd86070ed43baaf7770dd05a5fa93d9f0be/gdx/src/com/badlogic/gdx/graphics/g2d/GlyphLayout.java#L305

was changed here:
https://github.com/libgdx/libgdx/commit/f78d903329de901f5beaa92de124457b4e122271#diff-62b695b6c37ee8ddcab0d32c9821f62d

**Comment by obigu** [comment]
Fixed in https://github.com/libgdx/libgdx/pull/5550
