### ISSUE TITLE
LibGDX sees smaller resolution than actual phone resolution (iPhone XS Max)

### ISSUE THREAD

**Issue by costimuraru** [libgdx/libgdx#5473]
#### Issue details
Hey

Trying to figure out why the libgdx app is not taking advantage of the full screen on an iPhone XS Max.
The phone resolution is: **1242x2688** pixels
However libGDX sees and draws the app on: **1242x2208**, therefore losing some of the height.

It basically clips the height and two black bands are shown.
I replicated this on the libgdx sample app as well.

I'm guessing it has something to do with the fact that it's a newer iPhone, but how can we fix it?
**Any idea how to fix this, so that we leverage the whole screen?**

![xxx](https://user-images.githubusercontent.com/952836/49911083-c09a9480-fe8d-11e8-94e0-69485b0da9cc.jpg)

#### Reproduction steps/code
You can reproduce this in the iPhone Simulator.

```sh
./gradlew :ios:launchIPhoneSimulator
```

Make sure to run it (the libgdx sample app) on iPhone XS Max.

`com.badlogic.gdx.backends.iosrobovm.IOSApplication#getBounds` outputs:
`[debug] IOSApplication: Total computed bounds are w=1242.0 h=2208.0` (notice how the height is smaller 2208 vs 2688).

#### Version of LibGDX and/or relevant dependencies
1.9.6

#### Please select the affected platforms
- [ ] Android
- [x] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by julienvillegas** [comment]
have you tried with version 1.9.9?

**Comment by Tom-Ski** [comment]
Please reopen if you have tested with correct launch images.
