### ISSUE TITLE
Adding a flipped TextureRegion to TextureAtlas results in blank white Texture when drawn

### ISSUE THREAD

**Issue by GameplayJDK** [libgdx/libgdx#5484]
#### Issue details
Ok, so first some info on the context of this:
I'm currently generating a `Texture` at runtime, everything fine here.
A `TextureRegion` is created from that `Texture`. Due to some internal design decisions it happened to be flipped along the y-axis.
That `TextureRegion` is added to a previously loaded `TextureAtlas`, so I do not have to manage its disposal myself (call the dispose() method).
The texture turned blank white when drawn using `SpriteBatch`. When I remove the the code that flips the `TextureRegion`, the texture appears correctly rendered on screen.
I searched the sources and while I didn't find the exact reason, I suspect it to be the re-wrapping of the texture into an `AtlasRegion` inside `TextureAtlas` [(here)](https://github.com/libgdx/libgdx/blob/c31fe0ad74a35f4b1e898885615f5b91ee382953/gdx/src/com/badlogic/gdx/graphics/g2d/TextureAtlas.java#L278).

![image](https://user-images.githubusercontent.com/4069263/50179540-94589b00-0307-11e9-8ce8-d8ca5a213ed8.png)

#### Reproduction steps/code
```java
package de.gameplayjdk.test;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.graphics.g2d.TextureAtlas;
import com.badlogic.gdx.graphics.g2d.TextureRegion;

public class TextureAtlasAddFlippedTextureRegion extends ApplicationAdapter {
    private SpriteBatch batch;
    private Texture texture;
    private TextureAtlas atlas;

    public void create () {
        this.batch = new SpriteBatch();
        this.texture = new Texture(Gdx.files.internal("data/badlogic.jpg"));
        this.atlas = new TextureAtlas();

        TextureRegion region = new TextureRegion(this.texture);
        region.flip(false, true);
        this.atlas.addRegion("test", region);
    }

    public void render () {
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

        this.batch.begin();
        this.batch.draw(this.atlas.findRegion("test"), 100, 100);
        this.batch.end();
    }

    public static void main (String[] args) throws Exception {
        new LwjglApplication(new TextureAtlasAddFlippedTextureRegion());
    }
}

```

I solved the issue by removing the call to `region.flip(false, true)` for now. It would be nice though, if there would be an easier way. I had to change my texture generation code to adapt to the flipped orientation.

#### Version of LibGDX and/or relevant dependencies
I'm using LibGDX `1.9.8` and I used the `gdx-setup.jar` from 11/15/2018.

#### Please select the affected platforms
Until now I could only test this on Windows 10.

**Comment by NathanSweet** [comment]
The problem is an AtlasRegion is created without considering the TextureRegion UVs. Also these two TextureRegion methods could be implemented like this:
```
	public int getRegionX () {
		if (isFlipX())
			return Math.round(u2 * texture.getWidth());
		else
			return Math.round(u * texture.getWidth());
	}

	public int getRegionY () {
		if (isFlipY())
			return Math.round(v2 * texture.getHeight());
		else
			return Math.round(v * texture.getHeight());
	}
```
The easy fix is for AtlasRegion to be created from a TextureRegion using `setRegion`.

**Comment by NathanSweet** [comment]
BTW, thank you for providing an actual SSCCE! It's unbelievable how rare that is. Even asking directly usually gets code that doesn't compile. Even when it compiles I usually I have to add a damn `main` method!

**Comment by GameplayJDK** [comment]
Thank you, for your fast response and fix!

Well, I just tried to stick to the instructions for contributing and submitting issues :)
