### ISSUE TITLE
LibGDX 1.9.9: Box2D World ContactList always has 0 elements

### ISSUE THREAD

**Issue by EmilianFilip** [libgdx/libgdx#5486]
Hello,

I've been using LibGDX 1.9.9 for a while now along with Artemis ODB: https://github.com/junkdog/artemis-odb
I've implemented a system that iterates over the array of contacts given by world.getContactList(). However, whenever I run the program, the system never runs because the array it is iterating over always has 0 elements. Debugging (I'm using IntelliJ by the way) confirms this, as peeking into the array shows that "All elements are null."
I've searched around on the web for what could be causing this problem, to no avail.
Eventually, I decided to downgrade to LibGDX 1.9.8 and I'm happy to say that the iteration now works, as ContactList now actually has elements (although I am confused as to what is causing this).

This is my code:

@Override
    protected void processSystem() {
        Array<Contact> collisions = b2dworld.getContactList();
        
        for (Contact collision : collisions) {
            // get the fixtures of the contact, check userData, manipulate bodies, etc.
        }
    }

As I said, this issue occurred for LibGDX version 1.9.9 but not for 1.9.8. I'm using Artemis ODB version 2.1.0 and also Lombok version 1.18.4. My Java version is 1.8.0_181

The affected platforms:
- [    ] Android
- [    ] iOS (robovm)
- [    ] iOS (MOE)
- [    ] HTML/GWT
- [ V ] Windows
- [    ] Linux
- [    ] MacOS

I don't know if this is a bug with the latest version of LibGDX or a bug with the Box2D native library or something that I am doing wrong. For now I think I'll just stick with LibGDX 1.9.8. Some help would of course be appreciated.

**Comment by obigu** [comment]
Running Box2DTest of libGDX project with thye Box2DDebugRenderer enabled and drawing the contact points (which are obtained using `getContactList()` from `World` returns and displays the contact points correctly https://imgur.com/a/ah9tSvB.

**Comment by Tom-Ski** [comment]
Please post full code that reproduces your issue, as the issue template requests.
