### ISSUE TITLE
Issue with ScrollPane.scrollTo

### ISSUE THREAD

**Issue by bryanbrunt** [libgdx/libgdx#5488]
#### Issue details
If a large amount of content is loaded inside a ScrollPane, and you wish to scroll to the end of the content, multiple calls to ScrollPane.layout() are required. (You can find other examples of this issue on the web.)

#### Reproduction steps/code
ScrollPane created with the following code:

Table tblOuter = new Table();
Table tblInner = new Table();
lblChat = new Label("", skin, "small");
lblChat.setWrap(true);

tblInner.add(lblChat).width(chatWidth - 40f).padLeft(5f).top();
tblInner.add(new Label("", skin, "small")).fillX().right();
tblInner.row();

pneChat = new ScrollBarPane(tblInner, skin, "default");
tblOuter.add(pneChat).width(chatWidth - 20f).height(controlHeight - 30f).expand().row();

Then, if after a large amount of text is loaded in lblChat, layout() has to be called twice prior to scrollTo working:

pneChat.layout();
pneChat.layout();
pneChat.scrollTo(0, 0, 0, 0);

#### Version of LibGDX and/or relevant dependencies
1.9.9

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X ] Windows
- [X ] Linux
- [ ] MacOS

**Comment by NathanSweet** [comment]
Can you provide an SSCCE?
