### ISSUE TITLE
Sync error IntelliJ: minSdk version should not be declared in the android manifest file

### ISSUE THREAD

**Issue by Dalphat** [libgdx/libgdx#5498]
#### Issue details:
After updating IntelliJ 2018.3.2, there seems to be a sync error with libgdx:

> The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file." 

The solution was to remove the: (xml tags removed)
> "uses-sdk android:minSdkVersion="9" android:targetSdkVersion="28"

from the manifest file and invalidate caches/ restart. This solves the error.

#### Reproduction steps/code
Create a new project using "gdx-setup.jar" application. Create application using updated api.

Using IntelliJ 2018.3.2 and Gradle 4.6, use "open" in welcome screen and target "app.ipr". Unlinked gradle project event log occurs, and select import gradle project. A window will pop up and prompt for the basic import settings. I've set "auto-import" on and everything else default. After doing so, you will be shown 3 project resolve errors about 'compile' being obsolete and to use implements. I create a Desktop configuration using "Desktop Launcher", "assests", and class path "desktop". Then build the project. After building go to file, click sync and wait. After a minute, a sync tab will show up in the build logs. The sync log has three conflicts, two warnings and one error: 

First a warning:
> Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

Second an error:
> The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.
and third another warning:

Third another warning:
> The targetSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.

Double clicking on the error will open the "build.gradle" within the android folder. Android-main is highlighted. This being the gradle file where our error exists in the manifest file, so we open the android manifest file within the same directory.

Line 5: (xml tags removed)
> uses-sdk android:minSdkVersion="9" android:targetSdkVersion="28"

states that it is not used and is always overwritten (mouse on), so I've deleted the line. Save all, invalidate cache and restart. After restarting and indexing, the second (error) and third (warning) are gone.

#### Version of LibGDX and/or relevant dependencies

IntelliJ IDEA 2018.3.2 (Community Edition)
Build #IC-183.4886.37, built on December 17, 2018
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

Gradle 4.6
JDK: 1.8.0_181

#### Stacktrace
```java
//None, sync error
```

#### Please select the affected platforms
- [x] Android
- [x] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [ ] MacOS

#### User Notes
Hopefully this can be resolved without users having to do workarounds every time; to sync functioning.

On a side note, the warnings in messages still exist:
> Warning:<i><b>project ':android': Unable to resolve additional project configuration.</b>
Details: java.lang.IllegalStateException: Resolving configuration 'compileOnly' directly is not allowed</i>

But being warnings, I guess those are negligible.

**Comment by EtK2000** [comment]
I don't think it affects robovm, linux, or windows.
This is caused because the min and target sdk versions are set in both the manifest and gradle files.

I'd mention this as a comment on the upgrade towards newer gradle versions because imo it's related (it's only left in the manifest as compatibility with older gradle afaik).

I'll link from there to here in a sec.

**Comment by obigu** [comment]
You are using an old gdx Setup tool.

Since https://github.com/libgdx/libgdx/pull/5335 new projects don't declare minSDK on the manifest.
