### ISSUE TITLE
TexturePacker automatically strips parts of region name after an underscore, if it's a number

### ISSUE THREAD

**Issue by DracoOmega** [libgdx/libgdx#5499]
Per the description, if the region name you have specified for an image in an atlas you are building in the texture packer ends with an underscore followed by a number, the packer seems to strip the underscore and all following characters out of the name when it actually packs it, _despite_ what it claims in the UI is the region's name

(eg: "Convergence_48" becomes just "Convergence")

However, this does NOT happen if what is after the underscore is not a number (eg: "Convergence_Plus" remains "Convergence_Plus")

I could see no way to have it output names actually matching the original filenames without appending a superfluous letter after the underscore, which surely must be undesired behavior?

**Comment by Tom-Ski** [comment]
This is desired behavior, https://github.com/libgdx/libgdx/wiki/Texture-packer#image-indexes
