### ISSUE TITLE
AndroidLiveWallpaper does not call resume on first resume

### ISSUE THREAD

**Issue by alexhorsa** [libgdx/libgdx#5511]
#### Issue details
It seems very weird that AndroidLiveWallpaper.onResume() does not call AndroidGraphicsLiveWallpaper.resume() on first run. This results in the ApplicationListener.resume() method not called. If this is by design, how can we know that the live wallpaper has been resumed?

#### Reproduction steps/code
**AndroidLiveWallpaper**
```
	public void onResume () {
                ...

		if (!firstResume) {
			audio.resume();
			graphics.resume();
		} else
			firstResume = false;
	}
```

#### Version of LibGDX and/or relevant dependencies
1.9.6 -> latest

#### Stacktrace
N/A

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by EtK2000** [comment]
resume() gets called when the state is returned to running from paused, it won't get called on first run.

This is by design, not only in LibGDX, but also in Android in general.

**Comment by MrStahlfelge** [comment]
On Android it gets called on first run, in libGDX not. Hence the `if (!firstResume)` check in code above.

The Application Listener should get a `create()` call on first run and a `resume()` if the app is coming back to foreground.

**Comment by alexhorsa** [comment]
Ok I understand now. So what would be a good way to register a sensor listener inside ApplicationListener? Register in create() and in resume() and then unregister in pause()? I've seen that sometimes the pause() callback is not called if resume() wasn't called in the first place

**Comment by MrStahlfelge** [comment]
That's the way to go. I don't know about any problems with the pause() method, it is reliable for normal libgdx applications - if it is not for Live Wallpapers, that's a bug.
