### ISSUE TITLE
TemporalActions don't always end on ending value

### ISSUE THREAD

**Issue by thebnich** [libgdx/libgdx#5515]
Due to floating point arithmetic, `TemporalAction`s that have an `end` argument aren't guaranteed to end on that state.

Arbitrary example (Kotlin):
```
val action = ColorAction()
action.color = Color(0xffffffff.toInt())
action.duration = 1f
action.interpolation = Interpolation.pow5Out
action.endColor = Color(0x444444ff)
```

After execution, I would expect the actor's color to be 0x444444ff; however, it's 0x434343ff.

Would it make sense override `end` and do the equivalent of `color.set(endColor)` for all affected actions?

**Comment by julienvillegas** [comment]
makes sense to me.. I cannot see a standard test in LibGDX project testing actions. Will this require a new test?

**Comment by obigu** [comment]
> Would it make sense override `end` and do the equivalent of `color.set(endColor)` for all affected actions?

Need to be careful as the action may be reversed in which case the final color on action complete is the start color. I think it's safer to deal with this inside the `update` for the special case where `percentage == 1f`.

**Comment by thebnich** [comment]
> Interpolation doesn't require output value to be 1 when it's input value is 1. So forcing end value to be set could give unwanted results.

I believe this behavior would already be broken since on `complete`, `percent` is set to 1 and the interpolator is bypassed ([code](https://github.com/libgdx/libgdx/blob/bcb6bbed92448310a0e6c157fcfa157ad9b62f51/gdx/src/com/badlogic/gdx/scenes/scene2d/actions/TemporalAction.java#L54)).

**Comment by mgsx-dev** [comment]
@thebnich my bad, sorry.

**Comment by thebnich** [comment]
No problem -- I think you still have a valid point. I don't see why the interpolator couldn't also be applied for the final step for the reasons you mentioned.

**Comment by petoncle** [comment]
@thebnich I don't get it, like you said, the code of `TemporalAction.act()` is:
```java
complete = time >= duration;
if (complete)
	percent = 1;
update(reverse ? 1 - percent : percent);
```
So in your example, once complete is true, `ColorAction.update()` is called with 1 passed as argument.
The code of `ColorAction.update(float percent)` is:
```java
float r = startR + (end.r - startR) * percent;
```
which ends up being:
```java
float r = startR + (end.r - startR) * 1f;
```
How can there be a floating point accuracy issue here?

**Comment by NathanSweet** [comment]
Those two commits should improve all temporal actions a bit and allow for interpolation that doesn't end with 1.

**Comment by obigu** [comment]
@NathanSweet I believe ColorAction changes should be modified to:
```
[...]		
else if (percent == 0)
	color.set(startR, startG, startB, startA);
[...]
```

Actually, for consistency and completion, we should have a `start` Color instance the same way we have an `endColor` and a `getStartColor()` method instead of the individual float values.

In that case the change would be:
```
[...]		
else if (percent == 0)
	color.set(start);
[...]
```

**Comment by NathanSweet** [comment]
@obigu Good catch, fixed!

The thing about start color is that it isn't configurable -- it is set in `begin()`. It would be odd to have `get/setStartColor` and then have whatever the user provided smoked in `begin()`. It may also be annoying to have to set the start color, rather than it using whatever the color is in `begin()` (though many times I have to set the current color (or scale, position, etc) before applying actions). A number of actions work by storing the current value as the "start" value in `begin()` and then don't expose the start value (eg MoveToAction).

**Comment by obigu** [comment]
@NathanSweet My comment was more oriented to the fact that start and end Color should be either both Colors instances or both be stored as their float components more than about the necessity of exposing the getter for the start color. After some more thought, I think the argument for minimal memory allocation outweights the benefits of using Color instances and, imo, end Color should also be stored as its float components (maybe lazily created if `getEndColor()` is called)
