### ISSUE TITLE
Libgdx project fails to compile with 'Cannot change strategy of configuration ':android:natives'' after it has been resolved.

### ISSUE THREAD

**Issue by mattcorby** [libgdx/libgdx#5523]
Please don't mark this as a duplicate!  Issues #5303 and #5305 have been closed, but the fix no longer works.  Android studio has changed, and the option " Settings -> Build, Execution, Deployment -> Gradle Android Compiler -> Configure on Demand" is no longer present.  I have researched alternative ways to turn off "configure on demand", and from what I have read, it appears that it is off by default.

I am trying to target Android 28 using the latest version of Android Studio on Linux Mint.

The rest is copied from #5303:

Steps
1. Using latest libgdx project creator (gdx-setup.jar) create android project (no other platforms).

2. add following to the root gradle file under build script/dependencies

classpath 'com.google.gms:google-services:4.0.0'
Then add following to the gradle file or android module

apply plugin: 'com.google.gms.google-services'

3. When sync and compile follwoing error is thrown.

Cannot change strategy of configuration ':android:natives' after it has been resolved.

If I comment out apply plugin: 'com.google.gms.google-services' I can compile and run but this causes issues with fire base.

**Comment by obigu** [comment]
If Android Studio has removed the Configure on Demand and you are seeing this error everything points that they are enabling it by default.

In any case, please run your project on IDEA (and set the Configure on Demand to false) to confirm if it's an IDE issue.

Also try updating the Google Services plugin to `4.2.0`.

**Comment by cypherdare** [comment]
I can confirm this issue running Google Services 4.2.0 with Android Build Tools 3.4.1 in Android Studio 3.4.1 (all are the latest). 

I'm working around it by commenting out the task. You can create a separate bare bones project to copy the `libs` directory out of if you update the gdx version.
