### ISSUE TITLE
localToActorCoordinates returning wrong result

### ISSUE THREAD

**Issue by maltaisn** [libgdx/libgdx#5525]
There's clearly a typo in the Actor class in the method [`localToActorCoordinates(Actor, Vector2)`](https://github.com/libgdx/libgdx/blob/a9ba018b333d567812eabb6d3cb06872aa073bfc/gdx/src/com/badlogic/gdx/scenes/scene2d/Actor.java#L929). Here's the method body:
```java
/** Converts coordinates for this actor to those of another actor, which can be anywhere in the stage. */
public Vector2 localToActorCoordinates (Actor actor, Vector2 localCoords) {
    localToStageCoordinates(localCoords);
    return actor.stageToLocalCoordinates(localCoords);
}
```
The return value of the `localToStageCoordinates(localCoords)` call is never used, which makes the method equivalent to the `stageToLocalCoordinates` method. The results I get are also clearly wrong, just look at this example:
```kotlin
val actor = Actor()
stage.addActor(actor)
actor.setPosition(100f, 100f)
println(actor.localToActorCoordinates(stage.root, Vector2(0f, 0f)))
```
This outputs `(0,0)` when it should output `(100,100)`.

The method body should be changed to:
```java
public Vector2 localToActorCoordinates (Actor actor, Vector2 localCoords) {
   return actor.stageToLocalCoordinates(localToStageCoordinates(localCoords));
}
```

**Comment by mgsx-dev** [comment]
cannot reproduce on master branch. It returns (100, 100) as expected.

note: localToStageCoordinates(localCoords); call actually modify localCoords.

Issue can be closed.

**Comment by maltaisn** [comment]
Yes I didn't realize the passed vector was modified and returned, not a new instance.
