### ISSUE TITLE
Image corrupts Table layout

### ISSUE THREAD

**Issue by RUSshy** [libgdx/libgdx#5526]
#### Issue details
In a table without parent, when images are added, the table layout is incorrect

#### Reproduction steps/code
```kotlin

        val root = Table()
        root.defaults().top().left().expand()

        val imga = Image(skin, "discord")
        val imgb = Image(skin, "youtube")
        val btn = Button(skin)

        root.add(imga)
        root.row()
        root.add(imgb)
        root.row()
        root.add(btn)

        stage.addActor(root)
```
![image](https://user-images.githubusercontent.com/18348637/51455621-c156fe00-1d4a-11e9-8ead-27389cc30703.png)

If i add

``root.setFillParent(true)`` then it works

![image](https://user-images.githubusercontent.com/18348637/51455648-d9c71880-1d4a-11e9-9627-71ee49d0197f.png)

#### Version of LibGDX and/or relevant dependencies
gdxVersion=1.9.9-SNAPSHOT

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by Tom-Ski** [comment]
This is the correct behavior, your root table has no size.
