### ISSUE TITLE
[Feature Request] Get access to game controller vendor and product id

### ISSUE THREAD

**Issue by GrantOjanen** [libgdx/libgdx#5528]
#### Issue details
GDX gives access to the names of controllers, but I couldn't find anyway to access the vendor and product ids of USB controllers.

This could be useful for people that want to connect to the SDL game controller database: https://github.com/gabomdq/SDL_GameControllerDB

Android has `InputDevice.getVendorId ()` and `InputDevice.getProductId()`.

HTML has `Gamepad.id`.

#### Version of LibGDX and/or relevant dependencies
GDX 1.9.9
controller extension 1.9.9

**Comment by PokeMMO** [comment]
Something worthwhile to note is that mappings vary between different controller backends. The SDL database might not be as useful as you might expect.

[Even on windows, jinput (lwjgl2) and glfw (lwjgl3) have noticeable differences.](https://github.com/libgdx/libgdx/blob/a4805d6a017b80622d6bfdd3a791352257a3c539/extensions/gdx-controllers/gdx-controllers/src/com/badlogic/gdx/controllers/mappings/Xbox.java)

**Comment by MrStahlfelge** [comment]
If you want to use the SDL database, you should check out [Jamepad for libGDX](https://github.com/MrStahlfelge/gdx-controllerutils/wiki/Jamepad-controller-implementation).

**Comment by GrantOjanen** [comment]
Okay. I felt like it would be nice to have in addition to their names for identifying controllers.

**Comment by GrantOjanen** [comment]
Also having access to a gamepad's InputDevice id (`InputDevice.getId()`) would be super useful, so I can find it with Android's APIs when I need. Same thing for the gamepad `index` on JavaScript. And if there are equivalents on other platforms.

**Comment by kennycason** [comment]
I would also like access to vendor/id if easily doable (I'm not sure what the controllers actually provide. But i'm looking to connect a playstation 4 controller and it's name is "Wireless Controller" It seems to vague for me to reasonably test the name to determine if it's a playstation 4 controller.

**Comment by GrantOjanen** [comment]
Since the vendor/product id isn't always available, I think having a way to get an array of buttons/axes the controller supports would be better. I've started using the button/axis count and display name of controllers in my previous games to identify unique controllers. I plan on letting players remap controls in my future games, but it'll still be useful.
