### ISSUE TITLE
[Feature Request] Documentation on all third-party code packaged into games.

### ISSUE THREAD

**Issue by GrantOjanen** [libgdx/libgdx#5530]
#### Issue details
It would be nice if there was an official comprehensive list of all third party libraries and scripts (with their licenses) that are packaged into games produced by libGDX. A separate list for each platform.

Also shouldn't LGPL licensed libraries be included externally when producing game files? When I run "./gradlew desktop:dist" in Android Studio it packages them all inside one jar.

#### Version of LibGDX and/or relevant dependencies
libGDX 1.9.9

**Comment by intrigus** [comment]
Which library is LGPL licensed and used by libGDX?

**Comment by GrantOjanen** [comment]
I may be mistaken. Jlayer and JOrbis. They are listed in desktop.iml.

Even if there are no LGPL libraries packaged into the games, it would be nice to have this documentation.

**Comment by crykn** [comment]
I don't think a list like that would be all that useful. Just using the `./gradlew desktop:dependencies` command already provides a comprehensive list of dependencies and has the additional advantages of always being up to date and also displaying the dependencies of other third-party libraries as well. While this wouldn't give a list of corresponding licenses, those are not that difficult to figure out, especially considering the small number of libraries libGDX itself depends on.

As for questions regarding LGPL & linking java libraries, our issue tracker is not the right place for advice. If you want a reliable answer, either ask the authors of those libraries or seek legal counsel.
