### ISSUE TITLE
Arial font is proprietary and should be replaced.

### ISSUE THREAD

**Issue by GrantOjanen** [libgdx/libgdx#5537]
#### Issue details
I believe Arial is a proprietary font. Doing a web search for "Arial license" comes up with places selling licenses for the font. It's [Wikipedia page](https://en.wikipedia.org/wiki/Arial) says it's proprietary, and that Liberation Sans is a "Metrically compatible" font.

Liberation Sans is licensed with SIL Open Font License v1.10. I think it would be OK to package into games. It can be downloaded from [fontsquirrel.com](https://www.fontsquirrel.com/fonts/liberation-sans). I tried it out with Hiero and libGDX and it looks pretty close to the same as Arial.

GitHub shows an error when I try to upload files, so here's a link to the Hiero project file and a screenshot comparing the results.

https://drive.google.com/drive/folders/1kzPyVWrpgerXjS2kCurI34VoUQbUz65N?usp=sharing

#### Version of LibGDX and/or relevant dependencies
libGDX 1.9.9
Hiero v5

#### Please select the affected platforms
- [x] Android
- [x] iOS (robovm)
- [x] iOS (MOE)
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by Zomby2D** [comment]
License-wise, wouldn't [Arimo](https://fonts.google.com/specimen/Arimo) be a better fit? Both fonts are virtually identical (Liberation Sans was originally a licensed version of Arimo from Ascender Corporation anyway) but the [Croscore fonts](https://en.wikipedia.org/wiki/Croscore_fonts) area actually licensed under an Apache 2.0 license.

**Comment by GrantOjanen** [comment]
> License-wise, wouldn't [Arimo](https://fonts.google.com/specimen/Arimo) be a better fit? Both fonts are virtually identical (Liberation Sans was originally a licensed version of Arimo from Ascender Corporation anyway) but the [Croscore fonts](https://en.wikipedia.org/wiki/Croscore_fonts) are actually licensed under an Apache 2.0 license.

Ya, a font licensed with Apache would be better. I'm already having a hard time figuring out what licenses are used by all the third-party libraries in libGDX (I want to have complete attribution in my games.)

**Comment by BenMcLean** [comment]
I like the [oldschool PC fonts](https://int10h.org/oldschool-pc-fonts/) and would make them the default if it were up to me. Might not be a popular suggestion though

**Comment by terefang** [comment]
@BenMcLean you can use bdf fonts with the freetype plugin
or you can look at this https://github.com/terefang/terefang-gdx-contrib/tree/master/contrib-gdf

**Comment by tommyettinger** [comment]
There's a bizarre property of US copyright law relating to typefaces -- the design of a typeface is not possible to copyright in the US, but almost any original work as a digital file has copyright apply by default to that digital file. This means that while a purchased or licensed TTF/OTF file of Arial would be copyrighted by its authors/owners and only usable subject to its license agreement, an image that contains the letters of the font (or just a sign with text in Arial) is not subject to that license agreement in the US. It's entirely likely that other countries are more consistent about this, and do enforce copyright on typefaces! Moreover, if the name 'Arial' is trademarked (it probably is), then usage of that name for an asset without following a usage agreement of some kind (for the trademark) is a trademark violation, even if it isn't a copyright violation. I am not a lawyer, but it doesn't take one to see that it makes sense to replace this font...

**Comment by terefang** [comment]
I have cobbled together possible alternatives:

The Google Fonts Github includes fonts of varying licenses (Apache, OFL, UFL)
https://github.com/google/fonts

The TeX-Gyre Collection is licensed under the LaTeX Project Public License.
http://www.gust.org.pl/projects/e-foundry/tex-gyre/index_html

The ADF Collection is licensed under GPLv2 with Font exception.
https://arkandis.tuxfamily.org/adffonts.html

The Liberation Collection is licensed under the SIL Open Font License.
https://pagure.io/liberation-fonts

The GNU Unifont is licensed under GPLv2. 
Since the font is already in bitmap (bdf) format it may make sense to use it as the default font.
https://unifoundry.com/unifont/

The UNGIF Library contains a 8x8 bitmap 7-bit Ascii Font that is licensed under MIT/X license.
Since the font is already in bitmap (.c) format it may make sense to use it as the default font.
https://github.com/Distrotech/libungif/blob/master/lib/gif_font.c

The LibGD Library contains the Tiny/Small/MediumBold/Large/Giant Fonts that are under Classic 2-Clause BSD-like license.
Since the fonts are already in bitmap (.c) format it may make sense to use them as the default fonts.
https://github.com/libgd/libgd/blob/master/src/gdfonts.c

hope that helps.

**Comment by MrStahlfelge** [comment]
Probably someone just have to do it :)

**Comment by terefang** [comment]
i can contribute a perl script that will generate fnt/png out of the GD library:

[libgdx-fonts.zip](https://github.com/libgdx/libgdx/files/5332069/libgdx-fonts.zip)

**Comment by terefang** [comment]
BitmapFont currently uses arial-15 as default

hmm ... should we add some static helper methods on BitmapFont ? (like the perl api did)

**Comment by terefang** [comment]
hello

following up on the discord chat

how about this code ?

```
public class CreateSans {
    public static void main(String[] args) throws IOException {
        BufferedImage _im = new BufferedImage(256, 256,BufferedImage.TYPE_BYTE_GRAY);
        Graphics2D _g = (Graphics2D) _im.getGraphics();
        _g.setRenderingHint(
                RenderingHints.KEY_TEXT_ANTIALIASING,
                RenderingHints.VALUE_TEXT_ANTIALIAS_ON);

        Font _fnt = new Font("sans", Font.ROMAN_BASELINE, 14);
        _g.setBackground(Color.BLACK);
        _g.setColor(Color.WHITE);
        _g.setFont(_fnt);

        PrintWriter _pw = new PrintWriter(new FileWriter("sans-15.fnt"));
        _pw.println("info face=\"Sans\" size=15 bold=0 italic=0 charset=\"latin1\" unicode=0 stretchH=100 smooth=1 aa=1 padding=1,1,1,1 spacing=0,0");
        _pw.println("common lineHeight=16 base=16 scaleW=256 scaleH=256 pages=1 packed=0");
        _pw.println("page id=0 file=\"sans-15.png\"");
        _pw.println("chars count=192");
        FontMetrics _fm = new Canvas().getFontMetrics(_fnt);
        for(int _y = 0; _y<16; _y++)
            for(int _x = 0; _x<16; _x++)
        {
            int _char = (32 + _x + (_y * 16));
            if(_char < 256)
            {
                if(_fnt.canDisplay(_char))
                {
                    String _s = Character.toString((char) _char);
                    LineMetrics _lm = _fm.getLineMetrics(_s, _g);

                    _g.drawString(_s, _x*16, 16+(_y*16)-_lm.getDescent());

                    _pw.println(MessageFormat.format("char id={0} x={1} y={2} width={3} height={4} xoffset=0 yoffset={5} xadvance={6} page=0 chnl=0 ",_char, _x*16, _y*16, (int)_fm.charWidth(_char), (int)_lm.getHeight(), (int)_lm.getDescent(),(int)_fm.charWidth(_char)+1));
                }
                else
                {
                    _pw.println(MessageFormat.format("char id={0} x={1} y={2} width=0 height=0 xoffset=0 yoffset=0 xadvance=16 page=0 chnl=0 ",_char, _x*16, _y*16));
                }
            }
        }

        ImageIO.write(_im,"png", new File("sans-15.png"));
        _pw.close();
    }
}
```

**Comment by tommyettinger** [comment]
So, that's desktop-specific because it uses AWT, so it would need to be run at compile-time -- why can't we just use Hiero and use a font that's exactly like the current one, but not called Arial, and with slightly different design (ideally same metrics)? I think there's lots of metric-compatible variants on Arial used by Linux distros.

**Comment by throwaway1037** [comment]
(Just giving this thread a bump.)

**Comment by PokeMMO** [comment]
PR's are welcome.
