### ISSUE TITLE
ScrollPane areaHeight/areaWidth error when fading and scrolling are disabled

### ISSUE THREAD

**Issue by raeleus** [libgdx/libgdx#5538]
#### Issue details
Using a ScrollPane with setFadeScrollBars(false) and setScrollingDisabled(false, true) results in  unnecessarily cropped contents. It appears that [scrollBarHeight is subtracted from the areaHeight](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ScrollPane.java#L428) even if fade is false. This also affects the width when setting setScrollingDisabled(true, false).

Source images:
![content](https://user-images.githubusercontent.com/12948924/51783558-7a715b80-20f0-11e9-87d2-0450f81d1a4e.png) ![scrollbar](https://user-images.githubusercontent.com/12948924/51783560-7d6c4c00-20f0-11e9-8ab9-bcc3c64833fb.png)

Result:
![cropped-images](https://user-images.githubusercontent.com/12948924/51783550-66c5f500-20f0-11e9-9f5a-7d9a65d4feba.png)

Notice that the green borders are cut off from the top and bottom of the images.

#### Reproduction steps/code
This issue can be reproduced with the following code.
```java
package com.ray3k.scrollbarareaissue;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.NinePatch;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Image;
import com.badlogic.gdx.scenes.scene2d.ui.ScrollPane;
import com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.ScrollPaneStyle;
import com.badlogic.gdx.scenes.scene2d.ui.Table;
import com.badlogic.gdx.scenes.scene2d.utils.Drawable;
import com.badlogic.gdx.scenes.scene2d.utils.NinePatchDrawable;
import com.badlogic.gdx.utils.Scaling;
import com.badlogic.gdx.utils.viewport.ScreenViewport;

public class Core extends ApplicationAdapter {
    private Stage stage;

    @Override
    public void create() {
        stage = new Stage(new ScreenViewport());
        Gdx.input.setInputProcessor(stage);
        
        Table root = new Table();
        root.setFillParent(true);
        stage.addActor(root);
        
        Table table = new Table();
        
        for (int i = 0; i < 10; i++) {
            Image image = new Image(new Texture(Gdx.files.internal("content.png")));
            image.setScaling(Scaling.none);
            table.add(image);
        }
        
        Drawable knob = new NinePatchDrawable(new NinePatch(new Texture(Gdx.files.internal("scrollbar.png"))));
        ScrollPaneStyle style = new ScrollPaneStyle(null, null, knob, null, knob);
        
        ScrollPane scrollPane = new ScrollPane(table, style);
        scrollPane.setFadeScrollBars(false);
        scrollPane.setScrollingDisabled(false, true);
        root.add(scrollPane).width(132);
    }

    @Override
    public void render() {
        Gdx.gl.glClearColor(0, 0, 0, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        
        stage.act();
        stage.draw();
    }

    @Override
    public void resize(int width, int height) {
        stage.getViewport().update(width, height, true);
    }

    @Override
    public void dispose() {
        stage.dispose();
    }
}
```

#### Version of LibGDX and/or relevant dependencies
1.9.10-SNAPSHOT

#### Please select the affected platforms
- [x] Android
- [x] iOS (robovm)
- [x] iOS (MOE)
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

Thank you for your assistance.

**Comment by darencius** [comment]
A temporary solution for this issue is adding padding to the Table inside the ScrollPane

**Comment by raeleus** [comment]
This issue has to do with preferred size and has nothing to do with disabling fading or scrolling.
