### ISSUE TITLE
Unable to resolve additional project configuration

### ISSUE THREAD

**Issue by iSynth** [libgdx/libgdx#5539]
Please ensure you have given all the following requested information in your report.

#### Issue details
I get an error when I open a project generated with gdx-setup.jar.

```
Warning: root project 'MyGame': Unable to resolve additional project configuration.
Details: java.lang.IllegalStateException: Resolving configuration 'compileOnly' directly is not allowed
```

#### Reproduction steps/code
Step 1: java -jar ./gdx-setup.jar
Step: select the following options in the gdx-setup configurator
- [x] Desktopd
- [x] Android
- [x] ios-moe

Step 3: Click "Generate" and wait
Step 4: Open build.gradle file in IntelliJ IDEA

#### Version of LibGDX and/or relevant dependencies
libgdx 1.9.9
Jetbrain IntelliJ IDEA 2018.3 Community Edition
macOS Mojave 10.14.1

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [x] Android
- [x] iOS (robovm)
- [x] iOS (MOE)
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by Tom-Ski** [comment]
Resolved in irc.
