### ISSUE TITLE
Align.isCenterVertical and Horizontal return wrong results

### ISSUE THREAD

**Issue by maltaisn** [libgdx/libgdx#5540]
[`Align`](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/Align.java)'s `isCenterVertical` and `isCenterHorizontal` return wrong results.

```java
int align = Align.top | Align.bottom | Align.left
System.out.println(Align.isCenterVertical(align))
>> false
```
```java
int align = Align.center
System.out.println(Align.isCenterVertical(align))
System.out.println(Align.isCenterHorizontal(align))
>> false
>> false
```
I think all of these should return true.

**Comment by NathanSweet** [comment]
I see:
```
false
true
true
```
I believe that is correct. I think setting alignment to both top and bottom doesn't make much sense. I'd rather keep it not making sense than to interpret it as centered vertically.
