### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.moe.natj.general.NatJ.initialize()V (iOS Multi-OS Engine)

### ISSUE THREAD

**Issue by iSynth** [libgdx/libgdx#5542]
Please ensure you have given all the following requested information in your report.

#### Issue details
I get an error when trying to launch iOS version of fresh generated project (see stacktrace bellow)

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.moe.natj.general.NatJ.initialize()V
```

#### Reproduction steps/code
Step 1: java -jar ./gdx-setup.jar
Step: select the following options in the gdx-setup configurator
- [x] Desktopd
- [x] Android
- [x] ios-moe

Step 3: Click "Generate" and wait
Step 4: Open build.gradle file in IntelliJ IDEA
Step 5: Right click on IOSMoeLauncher file in IntelliJ IDEA and select Run "IOSMoeLauncher.main()".

#### Version of LibGDX and/or relevant dependencies
_Please provide the version(s) affected._

#### Stacktrace
```java
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.moe.natj.general.NatJ.initialize()V
	at org.moe.natj.general.NatJ.initialize(Native Method)
	at org.moe.natj.general.NatJ.init(NatJ.java:195)
	at org.moe.natj.general.NatJ.register(NatJ.java:243)
	at apple.NSObject.<clinit>(NSObject.java:68)
Exception in thread "Thread-0" java.lang.UnsatisfiedLinkError: org.moe.natj.general.NatJ.handleShutdown()V
	at org.moe.natj.general.NatJ.handleShutdown(Native Method)
	at org.moe.natj.general.NatJ.access$000(NatJ.java:44)
	at org.moe.natj.general.NatJ$2.run(NatJ.java:159)

Process finished with exit code 1
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [x] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
You must install the plugin and run by making a MOE run configuration. You can't simply right click and run as a regular java application.

**Comment by iSynth** [comment]
@Tom-Ski

Thank you for your feedback.

 I know that, the MOE plugin is installed. All the necessary actions have been performed. But I still get an error. Please do not close this topic because the problem is not solved.

**Comment by Tom-Ski** [comment]
Please use the forum or irc if you need personal assistance. What you have written in this issue shows you have not performed required actions and therefore this is not a valid issue.

**Comment by Tom-Ski** [comment]
Also, I would personally recommend that you use MobiVM backend for targetting iOS.

**Comment by iSynth** [comment]
@Tom-Ski 

Thanks for the advice. Can you recommend fresh educational materials on this issue? The MOE official documentation is unfortunately outdated and I could not find the official LibGDX documentation on iOS targeting with all the latest updates. As for MobiVM, there is no option for it in the gdx-setup.jar utility to generate the properly project.

**Comment by Tom-Ski** [comment]
https://libgdx.badlogicgames.com/documentation/help/Documentation.html

MobiVM = robovm in the setup tool.

**Comment by iSynth** [comment]
@Tom-Ski 

MobiVM also does not work (((I installed the plugin, did everything according to the instructions and still the iOS build will be fixed with an error. But now the error is completely different but resembling an error that was MOE. What am I doing wrong?

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.robovm.rt.bro.Dl.open(Ljava/lang/String;)J
```

**Comment by Tom-Ski** [comment]
Please join the forum or irc and myself and others can help you out there, this is an issue tracker https://github.com/libgdx/libgdx/wiki/Issue-Tracker
