### ISSUE TITLE
Allow hiding of the mouse cursor.

### ISSUE THREAD

**Issue by raeleus** [libgdx/libgdx#5546]
#### Issue details
The LWJGL3 backend does not allow for fully transparent images to be set as the mouse cursor. We would like to be able to make the cursor invisible without capturing it within the window. The solution is to use the following LWJGL3 method:
`glfwSetInputMode(((Lwjgl3Graphics) Gdx.graphics).getWindow().getWindowHandle(), GLFW_CURSOR, GLFW_CURSOR_HIDDEN);` It would be nice to have a method to do this in Input such as the following: `Gdx.input.setCursorHidden(true)`

#### Reproduction steps/code
- Create an LWJGL3 project
-cursor.png is a fully transparent 32x32 image. Add the following line to the core project:
`Gdx.graphics.setCursor(Gdx.graphics.newCursor(new Pixmap(Gdx.files.internal("cursor.png")), 0, 0));`
-Run the game. Notice that the cursor is now an opaque black rectangle.

#### Version of LibGDX and/or relevant dependencies
1.9.10-SNAPSHOT

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by intrigus** [comment]
Do you have the issue (black rectangle cursor) on all 3 platforms?

**Comment by raeleus** [comment]
No, it seems to be Windows only. I can't test Mac. The suggested solution would still be a cleaner option for all three, however.

**Comment by julienvillegas** [comment]
If you provide a SSCCE I can test on Mac..
