### ISSUE TITLE
Table/Container padding issue

### ISSUE THREAD

**Issue by RUSshy** [libgdx/libgdx#5547]
#### Issue details
If the drawable background of a table/container has padding, or if i set manually the padding to a container/table that has a table/container parent, then padding values produce weird result, the content is OFF (cf: screenshot bellow)

![image](https://user-images.githubusercontent.com/18348637/52052078-b9bb0480-2555-11e9-824a-b2e4b36eaa4c.png)

#### Reproduction steps/code
``` kotlin
var lv = ListViewTest(skin)
lv.pad(8f)
lv.top().left()

for (i in 0..15)
{
    lv.addItem("Hi_$i");
}

lv.setPosition(50f,350f)
lv.setSize(300f,300f)

stage.addActor(lv)


class ListViewTest(val sk: Skin) : ListView<String>(sk)
{
    override fun buildItemView(item: String): Actor
    {
        var table = Table()
        table.add(TextButton(item, sk))
        return table
    }
}

abstract class ListView<T>(val s: Skin) : Container<ScrollPane>()
{
    private var content: Table
    private val itemList: MutableList<T>

    init
    {
        this.itemList = ArrayList()

        this.content = Table()
        this.content.pad(8f).left().top()

        val sp = ScrollPane(content)
        sp.setFillParent(true)

        setActor(sp)

        debugAll()
    }

    fun addItem(item: T)
    {
        itemList.add(item)
        val actor = buildItemView(item)
        content.add(actor).top().left().growX()
        content.row()
        super.validate()
    }

    abstract fun buildItemView(item: T): Actor

    fun rebuild()
    {
        content.clearChildren()
        for (item in itemList)
        {
            addItem(item)
        }
    }
}
```

#### Version of LibGDX and/or relevant dependencies
1.9.9-SNAPSHOT

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by RUSshy** [comment]
ping @NathanSweet

**Comment by Tom-Ski** [comment]
Container manages layout using a single cell, you are telling your scroll pane to fill the size of its parent, which is the container itself, not the cell. You should use the container methods for sizing the child widget.

**Comment by RUSshy** [comment]
Hmm thanks for the explanation, i think i understand it better now

i removed fillParent and i override layout method and put this:

```kotlin
            scrollPane.setWidth(getWidth() - getPadLeft() - getPadRight())
            scrollPane.setHeight(getHeight() - getPadTop() - getPadBottom())
```

It produce expected result

thanks !
