### ISSUE TITLE
Wrong rgba color

### ISSUE THREAD

**Issue by BonBonSlick** [libgdx/libgdx#5554]
Please ensure you have given all the following requested information in your report.

#### Issue details
rgba color is wrong.

#### Reproduction steps/code

```
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator;

  FreeTypeFontGenerator.FreeTypeFontParameter parameter2 = new FreeTypeFontGenerator.FreeTypeFontParameter();
            parameter2.size = 80;
            parameter2.color =  new Color(255, 155, 0, 1);
            parameter2.borderWidth = 4f;
            BitmapFont font2 = generator.generateFont(parameter2);
            font2.draw(batch, "TEST!!!", x, y);

```

Use any color picker to see color, it should be darker yellow. Between orange and yellow. 
But rendered always Color.YELLOW not rgba.

#### Version of LibGDX and/or relevant dependencies
Gdx version: 1.9.8

#### Stacktrace
No stack trace, justwrong color.

#### Please select the affected platforms
- [+] Windows

Not tested other platforms yet.

**Comment by Darkyenus** [comment]
Not a bug: you are using [this](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/Color.java#L89) constructor, which takes `float`s in the range [0-1], not bytes. What you want instead, is `new Color(1f, 0.61f, 0f, 1f)`.

Interestingly, your alpha channel is correct.

**Comment by Lestat** [comment]
I propose a new constructor that takes the first two arguments at 0-255 and the other two at 0f-1f.

**Comment by BonBonSlick** [comment]
Tell me please how to check or convert to 0-1f from 0-255? Is 0.5 equal to 127.5?

**Comment by yuripourre** [comment]
*Converting from 0~1 to 255*
```
r = 0.3333;
r*=255;
```
*Converting from 255 to 0~1*
```
r = 82;
r/=255f; // Please do not forget the f or Java will convert to int 
```

**Comment by BonBonSlick** [comment]
@yuripourre  thank you!

**Comment by yuripourre** [comment]
@BonBonSlick 
Just multiply each channel by 255

**Comment by BonBonSlick** [comment]
@yuripourre thank you :)
