### ISSUE TITLE
Newly created game is not runnable in iOS Simulator

### ISSUE THREAD

**Issue by MrStahlfelge** [libgdx/libgdx#5557]
A newly created game is not runnable in iOS simulator. It crashes without a message.

Device log gives the following explanation:

    IOSLauncher assertion failed: .... libxpc.dylib .... 

I was able to run the superjumper demo game. When comparing the two directories, I stumbled accross the following line in the build.gradle file:

https://github.com/libgdx/libgdx/blob/c1466dbe87f6cbe536b14a2b607dc2c611df4e66/extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/ios/build.gradle#L16

It was added to close #4198 and to have robovm build 64 bit, however, it prevents the template to run on the simulator. Deleting the lines made the game start.

**Comment by obigu** [comment]
I assume you are running it from Gradle command line (not the IDEA plugin) right?
From the plugin you can choose the target Architecture (either x86 or x86_64). 
I don't know if it should work out of the box from command line but my guess is that you'll need to pass it as a parameter (maybe ask on MobiVM Gitter?).

**Comment by MrStahlfelge** [comment]
No, I use the idea plugin and specify x86 for the Simulator. The setting is overruled by the build.gradle file. Just try it with an own project by adding the line.

**Comment by obigu** [comment]
That line is in all my projects. I have also created a new project with the latest Gdx Setup just to confirm. Are you on RoboVM 2.3.5? Have you confirmed the IDEA plugin version is also 2.3.5 (not just the version in the build.gradle file)?

**Comment by MrStahlfelge** [comment]
Thanks you for trying!

I had the problem with RoboVM 2.3.3. I updated in the meantime and now added the setting again, with 2.3.5 it works. My gdx-setup tool was a bit older from last year and generated the project with 2.3.3 and with the setting in the build.gradle, but with the latest gdx-setup 2.3.5 is used so new users should not face this problem. So I'm closing this.
