### ISSUE TITLE
Preferences behaviour differs on Android

### ISSUE THREAD

**Issue by JoelOtter** [libgdx/libgdx#5558]
#### Issue details
I notice that behaviour of `Preferences` is different on Android; a newly-written preference will not be readable until a flush has occurred. On other platforms, it can be read immediately, provided the same `Preferences` instance is used.

This is because of the use of the SharedPreferences Editor in the Android implementation. I am happy to make the change myself to bring the behaviour in-line with the other platforms; the reason this is an issue rather than a PR is that I would like input from contributors as to which behaviour is actually desired.

#### Minimal example
```java
import com.badlogic.gdx.*;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.graphics.GL20;

public class Barebones extends ApplicationAdapter {
	public void create () {
		Preferences preferences = Gdx.app.getPreferences(".pref");
                preferences.putString("flower", "tulip");
                Gdx.app.log("Flower", preferences.getString("flower", "daffodil"));
                // On Desktop and iOS this prints "tulip". On Android it prints "daffodil".
                preferences.flush();
                Gdx.app.log("Flower", preferences.getString("flower", "daffodil"));
                // This will now print "tulip" on all platforms.
	}

	public void render () {
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
	}

	public static void main (String[] args) throws Exception {
		new LwjglApplication(new Barebones());
	}
}
```

#### Version of LibGDX and/or relevant dependencies
Latest

#### Please select the affected platforms
- [X] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by obigu** [comment]
That's a really weird behaviour you describe but to confirm I've ran your code on a Pixel 3 and shows "tulip" before and after flush(). What device are you testing this on? OS version? Can you try with a different Prefernces file name?

**Comment by JoelOtter** [comment]
Thanks for the swift response @obigu.

I observed this behaviour on a Galaxy S8, and also in the simulator. I believe both are on Android Oreo. When I get home this evening I'll double check this specific example, as I wrote it from memory.

From reading the [AndroidPreferences](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidPreferences.java) source and the [SharedPreferences.Editor](https://developer.android.com/reference/android/content/SharedPreferences.Editor) documentation, it does seem like the behaviour I observed makes sense. Is it possible you executed the above example twice without clearing the preferences in between?

**Comment by obigu** [comment]
You're right, I've tested again and now I've reproduced, I have ran it twice to get the logs output. Interesting, I didn't consider it could work like this as the way I deal with state in my projects is with a POJO (or more) that that holds that state and it's serialized on `flush`.

**Comment by JoelOtter** [comment]
Ah, that's good to know I haven't gone entirely mad.

Do you think it's worth changing this behaviour, say to read from the Editor before the SharedPreferences? Otherwise, we should discourage this practice by adding something to the documentation, perhaps best practices for only reading Preferences at start time and storing them somewhere in memory.

**Comment by obigu** [comment]
The documentation of the `Preferences` interface could definitely improve by stating that there is no guarantee changes will be available until `flush` is called.
The current sentence:
> Changes to a preferences instance will be cached in memory until {@link #flush()} is invoked.
is not accurate imo as it implies that changes will be available in memory until persisted to disk, which is not the case on the Android implementation.

**Comment by MrStahlfelge** [comment]
When doing this change, tt should also be added that you should only use one instance of a `Preference` and hold it in your game class. Users had problems with using multiple instances on iOS.
