### ISSUE TITLE
Same Issue as closed with no answer

### ISSUE THREAD

**Issue by AugustasMacys** [libgdx/libgdx#5559]
https://github.com/libgdx/libgdx/issues/5454#issue-381977415

**Comment by Tom-Ski** [comment]
It was closed via a commit that fixes the issue. If you have the same issue on latest snapshot, please fill out the issue template fully and supply an example with stacktrace.

**Comment by AugustasMacys** [comment]
> It was closed via a commit that fixes the issue. If you have the same issue on latest snapshot, please fill out the issue template fully and supply an example with stacktrace.

I use gdxVersion = '1.9.9'. How to get those changes which you made on my local machine so that I wouldnt need to create a new project?

**Comment by SimonIT** [comment]
I think ```gdxVersion = '1.9.10-SNAPSHOT'``` should do it
