### ISSUE TITLE
PooledEffect not draw at the first time

### ISSUE THREAD

**Issue by bachtrong43** [libgdx/libgdx#5561]
```java
bombEffectPool = new ParticleEffectPool(bombEffect, 1, 2);
// Create effect:
PooledEffect effect = bombEffectPool.obtain();
```
Each time the PooledEffect obtain from ```newObject()``` of pool, it will be in wrong state and complete immediate after first ```update(float delta)```. After ```free()``` it will call ``` reset()``` on ```PooledEffect``` and later reused work as usual.
Fix:
```java
public class GdxParticleEffectPool extends com.badlogic.gdx.graphics.g2d.ParticleEffectPool {
    public GdxParticleEffectPool(ParticleEffect effect, int initialCapacity, int max) {
        super(effect, initialCapacity, max);
    }

    @Override
    protected PooledEffect newObject() {
        PooledEffect effect = super.newObject();
        effect.reset();// need to reset on new instance
        return effect;
    }
}
```

**Comment by obigu** [comment]
Please provide a full SSCCE (https://github.com/libgdx/libgdx/wiki/Getting-help) that reproduces the described issue.

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info
