### ISSUE TITLE
Drawing label causes java.lang.StringIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by mskurt** [libgdx/libgdx#5565]
Hello everyone,

I checked issues but it seems no one get this. Sorry if it is duplicate.

I am using **libgdx 1.9.8** and **some android devices** produce this error. 

My problem is getting out of bound exception on drawing label and its coming from low level of libgdx.
#### Here is my stacktrace
```java
Fatal Exception: java.lang.StringIndexOutOfBoundsException: String index out of range: 18
       at com.badlogic.gdx.utils.StringBuilder.charAt(SourceFile:195)
       at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(SourceFile:113)
       at com.badlogic.gdx.scenes.scene2d.ui.Label.layout(SourceFile:202)
       at com.badlogic.gdx.scenes.scene2d.ui.Widget.validate(SourceFile:88)
       at com.badlogic.gdx.scenes.scene2d.ui.Label.draw(SourceFile:209)
       at co.fourapps.aword.actor.de.gamescreen.Header.draw(SourceFile:649)
       at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(SourceFile:110)
       at com.badlogic.gdx.scenes.scene2d.Group.draw(SourceFile:57)
       at co.fourapps.aword.screen.MainScreen.com.badlogic.gdx.scenes.scene2d.Stage.draw(SourceFile:78)
       at com.badlogic.gdx.Game.render(SourceFile:46)
       at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(SourceFile:495)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1557)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1263)
```

#### Here is the Header.draw (Line 649) 
```java
@Override
public void draw(Batch batch, float parentAlpha) {
    //...some drawings
    topicLabel.draw(batch,parentAlpha); //line 649
    //...some drawings
}
```

#### How i initiate the label
```java
Label.LabelStyle labelStyle=new Label.LabelStyle(someBitmapFont,someColor);
Label topicLabel =new Label("Some text here",labelStyle);
topicLabel.setWidth(someWidth);
topicLabel.setHeight(someHeight);
topicLabel.setAlignment(Align.center);
```

Like i said, it is not constantly coming but it reduces our crash free user percentage. Very annoying.

Anyone who see anything like this? Or suggest a solving?

Thanks for your all help.

**Comment by Tom-Ski** [comment]
You are changing topicLabel's text where? And how? Are you doing async requests and updating? This issue is more than likely to be a misuse of mutlithreading.

**Comment by mskurt** [comment]
Hello Tom-Ski,

When user completes a level, i need to change header text so

```java
private void refreshHeaderInfos(Level level){
    int length=level.getSubject().replace("\n"," ").length();
    Label.LabelStyle labelStyle= topicLabel.getStyle();
    labelStyle.font=length>20?minBitmapFont:((length>=16&&length<=20)?midBitmapFont:maxBitmapFont);
    topicLabel.setStyle(labelStyle);
    topicLabel.setText(level.getSubject());
}
```

By the way i have static bitmapfont (different font sizes) objects which they are initialized on start and disposed on destroy. I select the best bitmapfont object to fit header text.

This method runs in the thread whereever libgdx works. I dont open any new thread.

Thanks.

**Comment by MrStahlfelge** [comment]
I use 1.9.8 for over a year now with heavy usage of static BitmapFonts and Scene2d labels. I never saw a crash like that.

**Comment by NathanSweet** [comment]
What thread calls `refreshHeaderInfos`?

**Comment by rdamiano** [comment]
I had trouble with GlyphLayout with periodic reported crashes from user analytics for a very long time, could never figure it out

Ended up being because threads, and it doesn't even have to involve the Label/GlyphLayout in question, since GlyphLayout utilizes (if I remember correctly) a static "Pool" class.

Since it's static it's shared among all GlyphLayout instances and accessing 2 Labels at the same time can *sometimes* cause stuff like this.

Solution for me was to just prevent the main thread (loading objects, text objects) from modifying said text objects while the other thread (showing loading percentage) was active. Then at the end I'd do the processing for the text objects real quick.

**Comment by NathanSweet** [comment]
Label uses a single, static GlyphLayout, so setting label text on any non-GL thread can cause a crash if _any_ label is also set on the GL thread at the same time. That is almost certainly what is happening in this issue, so I think we can close.
