### ISSUE TITLE
Graphical artefacts when using calculateScissors on WebGl target

### ISSUE THREAD

**Issue by TMTHY** [libgdx/libgdx#5570]
When scissorRect calculated by Stage.calculateScissors contains negative coordinates, some times different graphical artefacts can be seen - graphics that have to be cut off by scissors is displayed in random location.

For example, if you have a dialogue with a ScrollPane on it - when you try to "slide away" that dialogue to the bottom, out of viewport bounds, you can see some strange graphical effect when running in browser.  In desktop target everything is OK.

Tested on different versions Chrome.
- [ +] HTML/GWT

Can be fixed with the following hack, when creating your scene:
```
stage = new Stage(viewport, batch) {
            @Override
            public void calculateScissors(Rectangle localRect, Rectangle scissorRect) {
                super.calculateScissors(localRect, scissorRect);
                Utils.cutToScreenDimensions(scissorRect);
            }
        };

public static void cutToScreenDimensions(Rectangle rectangle) {
        if (rectangle.x < 0) {
            rectangle.width += rectangle.x;
            if (rectangle.width < 0) rectangle.width = 0;
            rectangle.x = 0;
        }

        if (rectangle.y < 0) {
            rectangle.height += rectangle.y;
            if (rectangle.height < 0) rectangle.height = 0;
            rectangle.y = 0;
        }
}
```

May be some solution like that has to be implemented in Scene.calculateScissors? 
Or may be I'm doing something wrong with the Scene?

**Comment by EtK2000** [comment]
https://github.com/libgdx/libgdx/wiki/Getting-help

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info
