### ISSUE TITLE
Can not run from IDEA a Desktop project using Kotlin

### ISSUE THREAD

**Issue by caillette** [libgdx/libgdx#5574]
I'm having hard times using libGDX with Kotlin under IntelliJ IDEA. This looks like a problem with Gradle defining 2 target directories (one for Java, one for Kotlin) and it configures IDEA so there is only one at runtime.

## Versions used

The `git rev-parse HEAD` of libGDX shows `f2ed6b4a365922964eb06538f486d9526d1803af` as last commit. 

IntelliJ IDEA says I am using:

```
IntelliJ IDEA 2018.3.3 (Community Edition)
Build #IC-183.5153.8, built on December 24, 2018
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3
```

## Reproduction path

Generate a libGDX project with gdx-setup. In order to achieve this, check out latest version of libGDX. Build and run the gdx-setup project as follows:

```
git clone https://github.com/libgdx/libgdx.git
cd libgdx/extensions/gdx-setup
git rev-parse HEAD
ant
java -jar gdx-setup
```

Check "Desktop" as subproject. Open "Advanced" dialog and check "Kotlin". Run the generation.

From IntelliJ IDEA, open the directory generated by gdx-setup. Open the main class. Its default name was `MyGdxGame` and it is the one inheriting from `ApplicationAdapter`. Replace everything (except package declaration at the top) by the code below:

```
import com.badlogic.gdx.ApplicationAdapter
import com.badlogic.gdx.Gdx
import com.badlogic.gdx.graphics.GL20
import com.badlogic.gdx.graphics.Texture
import com.badlogic.gdx.graphics.g2d.SpriteBatch

class MyGdxGameK : ApplicationAdapter(){
  internal var batch : SpriteBatch? = null 
  internal var img : Texture? = null 

  override fun create() {
    batch = SpriteBatch()
    img = Texture("badlogic.jpg")
    Gdx.app.log( "Classpath", System.getProperty( "java.class.path" ) )
  }

  override fun render() {
    Gdx.gl.glClearColor(1f, 1f, 0f, 1f)
    Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT)
    batch!!.begin()
    batch!!.draw(img, 0f, 0f)
    batch!!.end()
  }

  override fun dispose() {
    batch!!.dispose()
    img!!.dispose()
  }
}
```

(Please note that background color is yellow, it differs from the class generated by libGDX, which is red.)

Modify `DesktopLauncher` so it instantiates the Kotlin class.

Create a Run Configuration for `DesktopLauncher` with `android/assets` as working directory. Run the `DesktopLauncher`. 

There is a `NoClassDefFoundError`: the `MyGdxGameK` class is not in the classpath. IntelliJ logs the following the classpath in the console, among which we can see those:

```
<project root>/desktop/build/classes/java/main
<project root>/core/build/classes/java/main
```

Looking at `core/build/classes` directory we can see 2 directories, `java` and `kotlin`. The `MyGdxGameK.class` file is under the `kotlin` directory. So it does not appear in the classpath.

## Further details

This is the `build.gradle` in `core` project:

```
apply plugin: "kotlin"

sourceCompatibility = 1.6
sourceSets.main.java.srcDirs = [ "src/" ]

project.ext.mainClassName = "com.mygdx.game.desktop.DesktopLauncher"
project.ext.assetsDir = new File("../android/assets");

task run(dependsOn: classes, type: JavaExec) {
    main = project.mainClassName
    classpath = sourceSets.main.runtimeClasspath
    standardInput = System.in
    workingDir = project.assetsDir
    ignoreExitValue = true
}

task debug(dependsOn: classes, type: JavaExec) {
    main = project.mainClassName
    classpath = sourceSets.main.runtimeClasspath
    standardInput = System.in
    workingDir = project.assetsDir
    ignoreExitValue = true
    debug = true
}

task dist(type: Jar) {
    from files(sourceSets.main.output.classesDir)
    from files(sourceSets.main.output.resourcesDir)
    from {configurations.compile.collect {zipTree(it)}}
    from files(project.assetsDir);
 
    manifest {
        attributes 'Main-Class': project.mainClassName
    }
}

dist.dependsOn classes

eclipse {
    project {
        name = appName + "-desktop"
        linkedResource name: 'assets', type: '2', location: 'PARENT-1-PROJECT_LOC/android/assets'
    }
}

task afterEclipseImport(description: "Post processing after project generation", group: "IDE") {
  doLast {
    def classpath = new XmlParser().parse(file(".classpath"))
    new Node(classpath, "classpathentry", [ kind: 'src', path: 'assets' ]);
    def writer = new FileWriter(file(".classpath"))
    def printer = new XmlNodePrinter(new PrintWriter(writer))
    printer.setPreserveWhitespace(true)
    printer.print(classpath)
  }
}
```

The ``classpath = sourceSets.main.runtimeClasspath`` seems to resolve as a single directory from a list of 2 directories.

As a workaround I run the application through Gradle with `desktop:run` target but this is confusing and adds Gradle overhead.

**Comment by mgsx-dev** [comment]
this may help : https://kotlinlang.org/docs/reference/using-gradle.html#targeting-the-jvm

`sourceSets.main.kotlin.srcDirs...`

**Comment by caillette** [comment]
Thanks @mgsx-dev for the quick answer. I split my sources into `src/main/java` and `src/main/kotlin` and declared both as suggested. But the `sourceSets.main.runtimeClasspath` did not the magic I expected. The runtime classpath remains the same (with 2 directories ending by `build/classes/java/main`).

**Comment by caillette** [comment]
In fact it does, when running `desktop:run` (pure Gradle) I see the 2 directories in the classpath. So this may be a problem with IDEA that does not respect Gradle's behavior.

**Comment by caillette** [comment]
I found a proper workaround with `main.kotlin.outputDir = file('classes/java/main')`, so compiler puts every Java and Kotlin class in the directory used in the classpath. 

**I suggest to include this workaround in projects generated by gdx-setup.**

To summarize, this is the `build.gradle` of project `core`:

```
apply plugin: "kotlin"

sourceCompatibility = 1.6
[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

project.ext.mainClassName = "com.mygdx.game.desktop.DesktopLauncher"
project.ext.assetsDir = new File("../android/assets");

sourceSets {
    main.kotlin.srcDirs += 'src/main/kotlin'
    main.kotlin.outputDir = file('classes/java/main')
    main.java.srcDirs += 'src/main/java'
}

task run( dependsOn: classes, type: JavaExec ) {
    main = project.mainClassName
    classpath = sourceSets.main.runtimeClasspath
    standardInput = System.in
    workingDir = project.assetsDir
    ignoreExitValue = true
}

task debug(dependsOn: classes, type: JavaExec) {
    main = project.mainClassName
    classpath = sourceSets.main.runtimeClasspath
    standardInput = System.in
    workingDir = project.assetsDir
    ignoreExitValue = true
    debug = true
}
```

**Comment by mcol** [comment]
I had a similar issue (only I'm using kotlin only in the core module). After 2 days of failed attempts, I fixed it by adding this to the dependencies section in build.gradle:
```
compile files("build/classes/kotlin/main")
```

**Comment by xGnoSiSx** [comment]
Any update on this problem guys? I'm migrating my project over to use kotlin, would love to hear what happened with this. Cheers!

**Comment by crykn** [comment]
Closing this, as this should no longer be an issue after the setup tool was officially changed. In the meantime check out [gdx-liftoff](https://github.com/tommyettinger/gdx-liftoff) if you're still having trouble creating a runnable project.
