### ISSUE TITLE
AndroidFragmentApplication does not support onBackPressed or onKeyDown

### ISSUE THREAD

**Issue by patolax** [libgdx/libgdx#5578]
In order to skip the previous fragment on the back button press which loaded AndroidFragmentApplication , it should support onBackPressed. But I was not able to override it. Any ideas how to get this done?

`@Override
public void onBackPressed(){
    FragmentManager fm = getFragmentManager();
    if (fm.getBackStackEntryCount() > 0) {
        Log.i("MainActivity", "popping backstack");
        fm.popBackStack();
    } else {
        Log.i("MainActivity", "nothing on backstack, calling super");
        super.onBackPressed();  
    }
}`

**Comment by MobiDevelop** [comment]
Fragment doesn't have an `onBackPressed` method. You'd need to handle that at the activity.
