### ISSUE TITLE
Add travis badge

### ISSUE THREAD

**Issue by Glusk2** [libgdx/libgdx#5582]
Why not add a travis build status badge to `README.md`?
```
[![Build Status](https://travis-ci.org/libgdx/libgdx.svg?branch=master)](https://travis-ci.org/libgdx/libgdx)
```
[![Build Status](https://travis-ci.org/libgdx/libgdx.svg?branch=master)](https://travis-ci.org/libgdx/libgdx)

**Comment by NathanSweet** [comment]
Isn't the Jenkins badge sufficient?
```
[![Build Status](https://libgdx.badlogicgames.com/jenkins/buildStatus/icon?job=libgdx&.png)](https://libgdx.badlogicgames.com/jenkins/job/libgdx/)
```
[![Build Status](https://libgdx.badlogicgames.com/jenkins/buildStatus/icon?job=libgdx&.png)](https://libgdx.badlogicgames.com/jenkins/job/libgdx/)

**Comment by Glusk2** [comment]
It's an additional indicator of project health.

Besides, the builds differ:

- build on Jenkins is ran on Linux using Java 8 whereas Travis builds use Mac OS X and Java 10
- the build commands differ

I'm not an expert but isn't it possible that a Jenkins build passes and the one on Travis fails. You might accept a bad pull request if this isn't visible.
