### ISSUE TITLE
Problem with batch.draw() after LibGDX 1.9.9 update

### ISSUE THREAD

**Issue by denri11** [libgdx/libgdx#5584]
#### Issue details
After updating libgdx to version 1.9.9 or 1.9.10-SNAPSHOT, I had some problems rendering in the project. The problem is related to saving Color for SpriteBatch. I wrote a simple example to demonstrate the difference. In version 1.9.8 everything works logically. In the next versions I do not understand why everything broke. Thanks.

#### Version of LibGDX and/or relevant dependencies
1.9.9, 1.9.10-SNAPSHOT

#### Code example
```java
public void createResources() {
        texture = new Texture(Gdx.files.internal("tex/textures/Zombie.png"));

        image = new Image(new Texture(Gdx.files.internal("tex/textures/Human.png")));
        image.setPosition(700, 200);
        image.getColor().a = 0.3f;
}

public void present (float deltaTime) {
        batch.begin();

        batch.draw(texture, 500, 200);

        Color color = batch.getColor();
        image.draw(batch, 1f);
        batch.setColor(color);

        batch.end();
}
```

#### Result of version 1.9.8
![198](https://user-images.githubusercontent.com/11684789/53881885-dd2a1100-4025-11e9-8515-cea179385de7.jpg)

#### Result of version 1.9.9+
![199](https://user-images.githubusercontent.com/11684789/53881916-f337d180-4025-11e9-9ae0-eed3d64bdc0d.jpg)

#### Please select the affected platforms
- [x] Android
- [x] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by denri11** [comment]
The answer is that the getcolor method in SpriteBatch has changed. This method now returns a reference to the current color. In previous versions of LibGDX, it calculated color using tempColor.
#### The following line of code solves the problem:
```java
Color color = new Color(batch.getColor());
```

**Comment by NathanSweet** [comment]
Sorry about this gotcha!
