### ISSUE TITLE
A problem came out while using "TimerTask".

### ISSUE THREAD

**Issue by hanxuechen** [libgdx/libgdx#5585]
Please ensure you have given all the following requested information in your report.

#### Issue details
_Please provide the details of your issue_
"Update Server " is called in _render()_
```
    public void updateServer(float dt){
        timer += dt;

		if(timer >= UPDATE_TIME && player != null && player.hasMoved()){
        	//updated-to-Server Events putting here.
			//Player moved.
			Gdx.app.log("EVENTS", "move.");
			socketFreqLtd.schedule(movePosition, 500, 500);
        }
    }
```

and below is the _movePosition_
```
int emitFreq = 0; //for triple check of the emitted-data.
	public TimerTask movePosition = new TimerTask() {
		@Override
		public void run() {
			emitFreq++;
			Gdx.app.log("TIMER", "Timer Value: " + timer);
			JSONObject data = new JSONObject();
			try {
				data.put("x", player.getX());
				data.put("y", player.getY());
				String dataString = data.toString(4);
				//Gdx.app.log("SOCKET.IO", "JSONObject" + dataString);
				socket.emit("playerMoved", dataString);
			} catch (JSONException e) {
				Gdx.app.log("Class:UpdateServer/SOCKET.IO", "Error sending update data");
			}
			if (emitFreq == 3) {
				emitFreq = 0;
				socketFreqLtd.cancel();
			}
		}
	`};`
```
And the Problem i faced => below is the console .
[SocketIO] Connected
[SocketIO] My ID: VmXWBB1vRWrmdp69AABF
[EVENTS] move.
[EVENTS] move.
Exception in thread "LWJGL Application" java.lang.IllegalStateException: Task already scheduled or cancelled
	at java.util.Timer.sched(Timer.java:401)
	at java.util.Timer.schedule(Timer.java:248)
	at supermash.io.Supermash.updateServer(Supermash.java:72)
	at supermash.io.Supermash.render(Supermash.java:81)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

this came out after double move. what might be the problem? 
p.s. i'm trying to do is to limit the frequency of socket.emit/

#### Reproduction steps/code
_Even if you think your issue is trivial to reproduce, please supply a [SSCCE](http://sscce.org/) that demonstrates your issue.  This saves time on our end, and makes it much more likely that your issue will be fixed.
You can find barebones templates [here](https://github.com/libgdx/libgdx/wiki/Getting-help)_

#### Version of LibGDX and/or relevant dependencies
_Please provide the version(s) affected._
newest version.

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by NathanSweet** [comment]
I assume this was bad usage of java.util.Timer API. Note libgdx has a Timer class which fires tasks on the OpenGL thread.

**Comment by hanxuechen** [comment]
hi! NathanSweet, pretty thanks for replying. Currently, it has been switched to built-in Timer from libGDX. 
and i new a Timer inside create(). i called scheduleTask() inside render() function. in fact, there is 2 problems as the file attached shown.
![2019-03-09_034015](https://user-images.githubusercontent.com/31240078/54051578-19739200-421d-11e9-96ae-756b5fcd98e6.png)

**Comment by hanxuechen** [comment]
it is weird that when i emit position signal to server, the desktop application screen shutdown.

**Comment by Tom-Ski** [comment]
Please use the forum or irc for personal help. https://github.com/libgdx/libgdx/wiki/Issue-Tracker

**Comment by hanxuechen** [comment]
okay  thanks

**Comment by RUSshy** [comment]
BTW there is a headless backend for servers https://github.com/libgdx/libgdx/tree/master/backends/gdx-backend-headless
