### ISSUE TITLE
HTTP-PATCH isn't implemented on GWT

### ISSUE THREAD

**Issue by intrigus** [libgdx/libgdx#5595]
#### Issue details
_Please provide the details of your issue_

#### Reproduction steps/code
https://github.com/libgdx/libgdx/pull/4137 added support for HTTP-PATCH protocol, but the gwt network wrapper didn't get updated.
So GWT doesn't support it.
See https://github.com/libgdx/libgdx/pull/4137#issuecomment-452906866

#### Version of LibGDX and/or relevant dependencies
https://github.com/libgdx/libgdx/commit/f91105ebd4301423025e11f833bd1311f68f6b80

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [x] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by MrStahlfelge** [comment]
Can you provide a PR? I heated 1.9.10 release is near and maybe it will get merged into it.

**Comment by intrigus** [comment]
@MrStahlfelge normally yes, but I'm busy with exams. And setting up gwt in an ide can be a lengthy process :)
Could you write the PR?
I guess I'd also find some time to review the pr then.

**Comment by MrStahlfelge** [comment]
I still have an open PR, I am waiting for it to get processed before I throw in more efforts. ;-)

**Comment by shapcode** [comment]
GWT itself doesn't support PATCH while using RequestBuilder. Apart from a copy/paste/modify of GWT's RequestBuilder (not worth the effort in my opinion) or finding some other replacement, this isn't going to happen.

**Comment by MobiDevelop** [comment]
GWT itself doesn't support PATCH while using RequestBuilder. Apart from a copy/paste/modify of GWT's RequestBuilder (not worth the effort in my opinion) or finding some other replacement, this isn't going to happen.

**Comment by MrStahlfelge** [comment]
You are right. It looks like it is not supported on all browsers (yet), that's why it is missing.

**Comment by MrStahlfelge** [comment]
I close this as it is not possible for us to implement it at this time.
