### ISSUE TITLE
Port Libgdx project to Flutter

### ISSUE THREAD

**Issue by tpatikirikorala** [libgdx/libgdx#5598]
I implemented a puzzle game using libgdx for android. Is it possible to port this to Flutter and make it run on IOS and Android together?

**Comment by Darkyenus** [comment]
I am not familiar with Flutter, but I believe that you will have much better time if you port it via RoboVM ([MobiVM](http://robovm.mobidevelop.com/)).

However, unless you plan to contribute Flutter support yourself, this discussion is not a good fit for [issue tracker](https://github.com/libgdx/libgdx/wiki/Getting-Help).
