### ISSUE TITLE
@NonNull and @Nullable annotations on parameters and return types

### ISSUE THREAD

**Issue by maltaisn** [libgdx/libgdx#5599]
I think adding `@NonNull` and `@Nullable` annotations to the source code would be very helpful documentation. It would also allow better Kotlin interoperability, since the Kotlin compiler can [recognize these annotations](https://kotlinlang.org/docs/reference/java-interop.html#nullability-annotations). There are already a few places where the javadoc indicates that a parameter may be null but it's far from being widespread.

For example the Batch in draw method and the events in event listeners are never null. These are obvious, but there are many cases where all the usages of a method but be looked at to know whether the parameter type is nullable or not. Kotlin also marks the `Color` and `Interpolation` constants as potentially nullable.

I understand that adding these annotations to every public method would be a very big undertaking, but I think it would prove to be very useful.

**Comment by Darkyenus** [comment]
I have recently added them to [Spigot API](https://hub.spigotmc.org/jira/browse/SPIGOT-2540) (for Minecaft server mods). It took about 30 hours, but I did found some bugs and I think that their API is now better for it. I think that this would be a *good-first-issue* (especially if it is split up into multiple smaller PRs), but someone (=core contributor) must first decide, which annotations should be used, as there is a lot of options, and all have their pros and cons. I outlined some of the options in the issue linked above, and ended up using the Jetbrains flavored ones, but libGDX may have a different needs and decide differently.

**Comment by NathanSweet** [comment]
The way it _should_ be currently is all parameters and return values that can be null should have javadoc stating that. If the javadoc doesn't say it can be null, you can assume it can never be null. Of course no checking is enforced.

I've not personally added annotations for null to a large project. I'd want to try that on a smaller, personal project to get an idea of what I like and don't like about it before tackling libgdx.

**Comment by maltaisn** [comment]
Already having javadoc for all nullable parameters will make it easier to add the nullability annotations.

Another advantage of using the annotations is that an IDE like IntelliJ will issue warnings when dereferencing a nullable object or when making null checks on a non-null object for example.

If you want to try on a smaller project, maybe start by adding them to a single part of libgdx, like only scene2d? I think it would also be the part that benefits the most. I can make a pull request, I just need to know what annotations you want to use. I would recommend using JetBrains' like @Darkyenus said.

**Comment by maltaisn** [comment]
I added `@NotNull` and `@Nullable` annotations to base scene2d classes. I chose `org.jetbrains:annotations` but it can easily be changed.

Some nullable fields are annotated even though they are private, for lint warnings. Same thing for private methods. Parameters that I wasn't sure about have a `/* FIXME not sure */` comment next to them.

Should I remove `May be null` javadoc comments as I go, since they are redundant?

**Comment by Darkyenus** [comment]
> Should I remove `May be null` javadoc comments as I go, since they are redundant?

I personally would keep them, I see no harm in that, it's only extra work. But any new documentation doesn't have to add them, provided that javadoc shows them (it should).

**Comment by maltaisn** [comment]
I finished adding them to the scene2d package, see #5615.

**Comment by Blunderchips** [comment]
Can this issue be closed seeing that https://github.com/libgdx/libgdx/pull/5812 has been merged in?
