### ISSUE TITLE
How to fix these issues

### ISSUE THREAD

**Issue by elieobeid7** [libgdx/libgdx#5606]
```
Library Gradle: com.android.support:animated-vector-drawable:25.0.0@aar has broken classes path:   /home/elie/.gradle/caches/transforms-1/files-1.1/animated-vector-drawable-25.0.0.aar/1a6dfa53b9ab8de92a72cccb7dc2bae2/res [Fix]
Library Gradle: com.android.support:customtabs:25.0.0@aar has broken classes path:   /home/elie/.gradle/caches/transforms-1/files-1.1/customtabs-25.0.0.aar/359083314682f4eab3316c384adb77bd/res [Fix]
Library Gradle: com.android.support:support-compat:25.0.0@aar has broken classes path:   /home/elie/.gradle/caches/transforms-1/files-1.1/support-compat-25.0.0.aar/87eeceffa6919234da627719ef50911d/res [Fix]
Library Gradle: com.android.support:support-core-ui:25.0.0@aar has broken classes path:   /home/elie/.gradle/caches/transforms-1/files-1.1/support-core-ui-25.0.0.aar/66b92d870d225951f9fe03337db7e385/res [Fix]
Library Gradle: com.android.support:support-core-utils:25.0.0@aar has broken classes path:   /home/elie/.gradle/caches/transforms-1/files-1.1/support-core-utils-25.0.0.aar/a1b2bff8b5f6ecef916022b6828d1162/res [Fix]
Library Gradle: com.android.support:support-fragment:25.0.0@aar has broken classes path:   /home/elie/.gradle/caches/transforms-1/files-1.1/support-fragment-25.0.0.aar/6860e6276a7c0cab66d2c7bda5b82e2e/res [Fix]
Library Gradle: com.android.support:support-media-compat:25.0.0@aar has broken classes path:   /home/elie/.gradle/caches/transforms-1/files-1.1/support-media-compat-25.0.0.aar/c4824dd993ec5298b32898443f5fd124/res [Fix]
Library Gradle: com.android.support:support-v4:25.0.0@aar has broken classes path:   /home/elie/.gradle/caches/transforms-1/files-1.1/support-v4-25.0.0.aar/4066731790ba6cf7ffc5fd8cc52d8d4f/res [Fix]
Library Gradle: com.android.support:support-vector-drawable:25.0.0@aar has broken classes path:   /home/elie/.gradle/caches/transforms-1/files-1.1/support-vector-drawable-25.0.0.aar/58ee594a82f1e543aca821a63dfd1e98/res [Fix]
Library Gradle: de.tomgrill.gdxfacebook:gdx-facebook-android:1.4.1@aar has broken classes path:   /home/elie/.gradle/caches/transforms-1/files-1.1/gdx-facebook-android-1.4.1.aar/1eb131f4c8f1efa1565bd0e0ffb9478e/res [Fix]
```

And

`[options] bootstrap class path not set in conjunction with -source 1.6`

and

`Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.`

![libgdx](https://user-images.githubusercontent.com/660142/55671007-b7499380-5893-11e9-8566-d0c7dcc96ad2.png)

![Screenshot from 2019-04-06 17-50-36](https://user-images.githubusercontent.com/660142/55671062-8453cf80-5894-11e9-839f-6569246bb7dc.png)

Using Android sdk 27, the recommended one and the latest Libgdx jar, java 1.8, ubuntu, intellij.

I know that answering questions about plugins might be out  of the scope of support, if so please just answer the last 2 question.

**Comment by EtK2000** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker

**Comment by elieobeid7** [comment]
@EtK2000  My biggest fear is to fix most of these issues and some extensions like facebook be broken without me noticing it. For example, I solved this error 2 years ago, so I could solve it probably once again.

`[options] bootstrap class path not set in conjunction with -source 1.6`

My biggest fear is to fix these issues and stumble upon more issues when I'm releasing the game, since when you select extensions from libgdx generator, you'll notice that many of them is broken or not updated.

**Comment by EtK2000** [comment]
If that's the case contact the maintainers of those projects, LibGDX doesn't deal with many of the extensions.

**Comment by mgsx-dev** [comment]
@elieobeid7 

* Q1 as Etk2000 pointed it, it's out of libgdx scope.
* Q2 `[options] bootstrap class path not set in conjunction with -source 1.6` : it's just a warning telling you're not compiling with JDK6, nothing to worry about.
* Q3 `Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.` : again it's just a warning telling you "compile" scope might not be compatible with futur gradle versions. So if you stick to your current gradle version (highly recommended), you have nothing to worry about.

**Comment by elieobeid7** [comment]
Thank you so much.
