### ISSUE TITLE
[Android] Unable to use more than one AndrioidFragmentApplication View in a single Activity.

### ISSUE THREAD

**Issue by sourabhgupta811** [libgdx/libgdx#5607]
#### Issue details
When adding more than one AndroidFragmentApplication View in a single activity. Only the last added fragment is drawing on the screen. Does libgdx supports using more than one AndroidApplication View at the same time.

#### Reproduction steps/code
1.Create two Fragment extending AndroidFragmentApplication.
 2.Return a libgdx view from both.
3. Add these fragments into the Activity.
4. Only the last added fragment will draw on the screen.

#### Version of LibGDX and/or relevant dependencies
gdx version 1.9.9
gdx-backend-android version 1.9.9

#### Affected platforms-
- Android

**Comment by MrStahlfelge** [comment]
I suspect you are trying to achieve two independant animations here. libGDX is built around a lot of static fields, so that won't work. Just one libGDX instance per JVM instance.

**Comment by sourabhgupta811** [comment]
Thanks for replying.
