### ISSUE TITLE
build mac natives libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]

### ISSUE THREAD

**Issue by bigstupidx** [libgdx/libgdx#5608]
when build natives dylib on mac

> cd gdx/jni
> ant -f build-macosx64.xml

> link:
>      [exec] clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
>      [exec] ld: library not found for -lstdc++
>      [exec] clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> BUILD FAILED

ant 1.9.6
macosx 10.14.2
xcode Version 10.1 (10B61)

**Comment by PokeMMO** [comment]
Might be fixed in https://github.com/libgdx/libgdx/commit/ddf41a61cf1933e8e2a54f708961093ad3fee046 and https://github.com/libgdx/libgdx/commit/444387100e347797a299d114445871da9d1726bb

But I'm not entirely sure if 10.7 + libc++ is enough to prevent the error, or if we need 10.9+.

**Comment by badlogic** [comment]
It is resolved.
