### ISSUE TITLE
Controller listener + LwjglFrame causes crash

### ISSUE THREAD

**Issue by Schyfis** [libgdx/libgdx#5609]
#### Issue details
While controllers are connected, attempting to add a controller listener in an app that also uses a LwjglFrame causes the error:
```
Error creating joystick: Win32JoyStick::_initialize() >> failed to set cooperation level!
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000621c3e13, pid=31304, tid=0x00000000000027f4
#
# JRE version: Java(TM) SE Runtime Environment (8.0_141-b15) (build 1.8.0_141-b15)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.141-b15 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [gdx-controllers-desktop64.dll+0x3e13]
```

#### Reproduction steps/code
It's a little hard to isolate the code in my engine, but in a default project, start your game this way:
`new LwjglFrame(new MyGDXGame(), cfg); //the configuration doesn't matter`

At some point in your game's code, attempt to add a controller listener.
`Controllers.addListener(my_controller_listener);`

The app will crash at this point with the above error if any controllers are connected. Unplugging the controllers before starting the app will cause the app to work properly.

If you start your game using LwjglApplication instead of LwjglFrame, it will start normally with no other changes necessary:
`new LwjglApplication(new MyGDXGame(), cfg);`

#### Version of LibGDX and/or relevant dependencies
1.9.10. It may affect earlier versions but I'm not sure.

#### Stacktrace
Have to type this myself as it doesn't print out anywhere. I stepped through the GDX sources, and it crashes at OisJoystick.getButtonCount. The joystickPtr value of the OisJoystick is 0, which seems to me like it might be an invalid value but I'm not sure.
```java
OisJoystick.getButtonCount() line: 91
OisJoystick.<init>(long, String) line: 40
Ois.<init>(long) line: 33
OisControllers.<init>(DesktopControllerManager) line: 44
DesktopControllerManager.<init>() line: 32
NativeConstructorAccessorImpl.newInstance()(Constructor<?>, Object[]) line: not available [native method]
NativeConstructorAccessorImpl.newInstance(Object[]) line: not available
DelegatingConstructorAccessorImpl.newInstance(Object[]) line: not available
Constructor<T>.newInstance(Object...) line: not available
Class<T>.newInstance() line: not available
ClassReflection.newInstance(Class<T>) line: 93
Controllers.initialize() line: 118
Controllers.addListener(ControllerListener) line: 59
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Darkyenus** [comment]
Would using Lwjgl3 fix your problem?

**Comment by Schyfis** [comment]
I'm not sure, but it would cause me other issues. I'm using the LWJGL2 backend for performance and compatibility reasons, as I mentioned in this issue from a couple years back: https://github.com/libgdx/libgdx/issues/4785

**Comment by Schyfis** [comment]
> Would using Lwjgl3 fix your problem?

I updated my LWJGL3 test project and to answer your question, I'm still not sure to be honest! LwjglFrame only seems to exist in the LWJGL2 backend, and I don't think there's an equivalent in the LWJGL3 backend.

**Comment by Schyfis** [comment]
Doing some more digging, and found that the window handle is not being determined correctly by OisControllers when a LwjglFrame is in use.

Specifically, this code in `OisControllers.getWindowHandle` (annotated a bit):
```
if (Gdx.graphics.getType() == GraphicsType.LWJGL) {
	// We want this to happen! This will work for our LwjglFrame.
	if (Gdx.app.getClass().getName().equals("com.badlogic.gdx.backends.lwjgl.LwjglCanvas")) {
		Class canvasClass = Class.forName("com.badlogic.gdx.backends.lwjgl.LwjglCanvas");
		Object canvas = canvasClass.getDeclaredMethod("getCanvas").invoke(Gdx.app);
		return (Long)invokeMethod(invokeMethod(SwingUtilities.windowForComponent((Component)canvas), "getPeer"), "getHWnd");
	}

	// We DON'T want this to happen- This will not return the right value when using an LwjglFrame.
	Class displayClass = Class.forName("org.lwjgl.opengl.Display");
	Method getImplementation = displayClass.getDeclaredMethod("getImplementation", new Class[0]);
	getImplementation.setAccessible(true);
	Object display = getImplementation.invoke(null, (Object[])null);
	Field field = display.getClass().getDeclaredField(IS_WINDOWS ? "hwnd" : "parent_window");
	field.setAccessible(true);
	return (Long)field.get(display);
}
```

When a LwjglFrame is used, I don't think LWJGL is responsible for managing the window handle, so we definitely don't want this code to ask org.lwjgl.opengl.Display what the the window handle is... But it does anyway!

It should be handled by the earlier block of code, but it isn't. The reason is in LwjglFrame.java:
```
private void construct (ApplicationListener listener, LwjglApplicationConfiguration config) {
	lwjglCanvas = new LwjglCanvas(listener, config) {
		// various canvas methods defined here
	};
	// rest of the construct method
}
```

Due to the way the LwjglCanvas is constructed in LwjglFrame, its class name is no longer `com.badlogic.gdx.backends.lwjgl.LwjglCanvas`. So when OisControllers checks the class name, it will not match and will continue on to the method of getting the window handle we don't want to use.

Sure enough, replacing the lwjglCanvas assignment with this works just fine:
```
private void construct (ApplicationListener listener, LwjglApplicationConfiguration config) {
	lwjglCanvas = new LwjglCanvas(listener, config);
	// rest of the construct method
}
```
...But without the methods defined, of course.

So going back to OisControllers, I don't see why the relevant part of `OisControllers.getWindowHandle` couldn't be modified like so:
```
if (Gdx.graphics.getType() == GraphicsType.LWJGL) {
	if (Gdx.app instanceof com.badlogic.gdx.backends.lwjgl.LwjglCanvas) {
		Object canvas = ((com.badlogic.gdx.backends.lwjgl.LwjglCanvas)Gdx.app).getCanvas();
		return (Long)invokeMethod(invokeMethod(SwingUtilities.windowForComponent((Component)canvas), "getPeer"), "getHWnd");
	}

	Class displayClass = Class.forName("org.lwjgl.opengl.Display");
	Method getImplementation = displayClass.getDeclaredMethod("getImplementation", new Class[0]);
	getImplementation.setAccessible(true);
	Object display = getImplementation.invoke(null, (Object[])null);
	Field field = display.getClass().getDeclaredField(IS_WINDOWS ? "hwnd" : "parent_window");
	field.setAccessible(true);
	return (Long)field.get(display);
}
```

Is there a specific reason for the string-based class name check, and the `forName` / `getDeclaredMethod`?

**Comment by NathanSweet** [comment]
If `LwjglCanvas` is not on the classpath, that won't work. You can use `Class.forName` to get the `LwjglCanvas` class, then use `lwjglCanvasClass.isInstance(Gdx.app)`. If you implement and test a fix, please consider submitting a PR so we can merge! :)

**Comment by MrStahlfelge** [comment]
As an alternative, you can use the [Jamepad implementation](https://github.com/MrStahlfelge/gdx-controllerutils/wiki/Jamepad-controller-implementation). I would recommend it for Lwjgl2 anyway because it supports hotplugging.

**Comment by Schyfis** [comment]
> As an alternative, you can use the [Jamepad implementation](https://github.com/MrStahlfelge/gdx-controllerutils/wiki/Jamepad-controller-implementation). I would recommend it for Lwjgl2 anyway because it supports hotplugging.

Just wanted to update- I did end up moving to Jamepad. I'm very happy with it so far, and moving to it was painless. Rumble support and hotplugging is awesome, and I'd second your recommendation to use Jamepad for anyone running into this issue.

**Comment by MrStahlfelge** [comment]
Hi, please take a look at [gdx-controllers v2 prerelease snapshot](https://github.com/libgdx/gdx-controllers). It's powered by Jamepad.
