### ISSUE TITLE
Pools.java, static map lifecycle issue with Android

### ISSUE THREAD

**Issue by calanti** [libgdx/libgdx#5613]
As briefly discussed here; https://badlogicgames.com/forum/viewtopic.php?f=11&t=28938

The static ReflectionPool map in Pools.java is not cleared during the android soft exit lifecycle (not 100% on the terminology, but if you exit the app using the back key then re-open it). This means that any references in those objects are broken. The example below uses VisLabels for simplicity, you will notice the labels disappear if you re-open the app this way. I presume this is because the labels have reference to the previous font texture which no longer exists.

#### Reproduction steps/code
` 
public class LeakyPoolsTest extends ApplicationAdapter {

    private Stage stage;
    private VisLabel label1, label2;

    @Override
    public void create() {
        super.create();
        if(!VisUI.isLoaded()) VisUI.load();
        stage = new Stage();
        label1 = Pools.obtain(VisLabel.class);
        label2 = Pools.obtain(VisLabel.class);
        label1.getStyle().fontColor = Color.WHITE;
        label1.setText("Test Label 1");
        label2.getStyle().fontColor = Color.WHITE;
        label2.setText("Test Label 2");
        label1.setPosition(200, 200);
        label2.setPosition(200, 300);
        stage.addActor(label1);
        stage.addActor(label2);
    }

    public void render(){
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        stage.act();
        stage.draw();
    }

    public void dispose(){
        Pools.free(label1);
        Pools.free(label2);
    }
}
`

#### Version of LibGDX and/or relevant dependencies
Tested with;
1.9.10-SNAPSHOT
1.9.9
1.9.8

Sample test uses VisUI 1.4.2

#### Please select the affected platforms
- [ ] Android

**Comment by Tom-Ski** [comment]
Commented in forum. Tests must be using LibGDX purely to demonstrate any issue.
