### ISSUE TITLE
[LWJGL3+Linux] Graphics#setUndecorated(true) when maximized causes invisible window

### ISSUE THREAD

**Issue by Anuken** [libgdx/libgdx#5620]
#### Issue details
In the LWJGL3 backend, when a window is maximized and `Gdx.graphics.setUndecorated(true)` is called, the window becomes invisible. It can still be minimized and un-minimized, but this does not affect it visually. Windows behind this invisible window can be seen and interacted with.

Calling `Gdx.graphics.setUndecorated(true)` with a window that is in the foreground but *not* maximized will behave as expected.

This occurs reliably on my Linux Mint 18 system. I have not tested on other platforms.

#### Reproduction steps/code
```java
import com.badlogic.gdx.backends.lwjgl3.*;
import com.badlogic.gdx.*;

public class WindowTest{
    public static void main(String[] args){
        Lwjgl3ApplicationConfiguration config = new Lwjgl3ApplicationConfiguration();
        config.setMaximized(true);
        new Lwjgl3Application(new ApplicationAdapter(){
            @Override
            public void create(){
                Gdx.graphics.setUndecorated(true);
            }
        }, config);
    }
}
```

This example creates an invisible window immediately upon startup. Commenting out `Gdx.graphics.setUndecorated(true);` leads to an empty black window, as expected.

#### Version of LibGDX and/or relevant dependencies
1.9.9

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [X] Linux
- [ ] MacOS

**Comment by mgsx-dev** [comment]
@Anuken i tested on master branch, linux ubuntu 16.04, i don't have any issues : i get a black screen with or without setUndecorated true/false. Might be related to Mint?

**Comment by Anuken** [comment]
Probably is, because I get the same issue with SDL, which doesn't even use GLFW.

**Comment by crykn** [comment]
If this issue isn't even related to glfw, there is nothing we can do about it. Closing it for now.
