### ISSUE TITLE
 [FEATURE REQUEST] Fullscreen on mobile browsers (html5)

### ISSUE THREAD

**Issue by dizzersee** [libgdx/libgdx#5621]
#### Issue details
My function to toggle fullscreen:

```
public void toggleFullScreen() {

        if(!Gdx.graphics.isFullscreen())
            Gdx.graphics.setFullscreenMode(Gdx.graphics.getDisplayMode());
        else
            Gdx.graphics.setWindowedMode(App.WIDTH, App.HEIGHT);

    }
```
Works on desktop browser but not on mobile browser. As answered [here](https://stackoverflow.com/questions/55884972/fullscreen-libgdx-html5-not-working-on-mobile/55889509#55889509) this functionality is not supported by libgdx gwt backend. 

#### Version of LibGDX and/or relevant dependencies
gdxVersion = '1.9.8'
gwtVersion='2.8.0'

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [x ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by EtK2000** [comment]
I would recommend renaming to contain [FEATURE REQUEST].

**Comment by MrStahlfelge** [comment]
After checking the backend source code, I must change my statement on SO. The code is in the backend since 2015 and is working for me on all systems except iOS.
