### ISSUE TITLE
Android Studio - Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'. What do I need to change?

### ISSUE THREAD

**Issue by MBurr123** [libgdx/libgdx#5622]
I have used the most recent build of LibGDX to create a project that will only be for mobile devices. When I try to open the file that gdx.setup fileproduces it generates in Android Studio I get the message that compile is obsolete and should be replaced. It says the problem is in the 'android' module. 

I've looked on this site and others and the advice is to change all cases of compile to Implementation but I cannot work out what needs to change in this module or what needs to stay as it is. I've tried changing items where it says 'compile' to 'implemention' but I end up with more errors. Can someone tell me exactly which parts of this need changing.

The module is:
android {
    buildToolsVersion "28.0.3"
    compileSdkVersion 28
    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }

    }
    packagingOptions {
        exclude 'META-INF/robovm/ios/robovm.xml'
    }
    defaultConfig {
        applicationId "com.mygdx.game"
        minSdkVersion 9
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

// called every time gradle gets executed, takes the native dependencies of
// the natives configuration, and extracts them to the proper libs/ folders
// so they get packed with the APK.
task copyAndroidNatives {
    doFirst {
        file("libs/armeabi/").mkdirs()
        file("libs/armeabi-v7a/").mkdirs()
        file("libs/arm64-v8a/").mkdirs()
        file("libs/x86_64/").mkdirs()
        file("libs/x86/").mkdirs()

        configurations.natives.files.each { jar ->
            def outputDir = null
            if (jar.name.endsWith("natives-arm64-v8a.jar")) outputDir = file("libs/arm64-v8a")
            if (jar.name.endsWith("natives-armeabi-v7a.jar")) outputDir = file("libs/armeabi-v7a")
            if(jar.name.endsWith("natives-armeabi.jar")) outputDir = file("libs/armeabi")
            if(jar.name.endsWith("natives-x86_64.jar")) outputDir = file("libs/x86_64")
            if(jar.name.endsWith("natives-x86.jar")) outputDir = file("libs/x86")
            if(outputDir != null) {
                copy {
                    from zipTree(jar)
                    into outputDir
                    include "*.so"
                }
            }
        }
    }
}

tasks.whenTaskAdded { packageTask ->
    if (packageTask.name.contains("package")) {
        packageTask.dependsOn 'copyAndroidNatives'
    }
}

task run(type: Exec) {
    def path
    def localProperties = project.file("../local.properties")
    if (localProperties.exists()) {
        Properties properties = new Properties()
        localProperties.withInputStream { instr ->
            properties.load(instr)
        }
        def sdkDir = properties.getProperty('sdk.dir')
        if (sdkDir) {
            path = sdkDir
        } else {
            path = "$System.env.ANDROID_HOME"
        }
    } else {
        path = "$System.env.ANDROID_HOME"
    }

    def adb = path + "/platform-tools/adb"
    commandLine "$adb", 'shell', 'am', 'start', '-n', 'com.mygdx.game/com.mygdx.game.AndroidLauncher'
}

// sets up the Android Eclipse project, using the old Ant based build.
eclipse {
    // need to specify Java source sets explicitly, SpringSource Gradle Eclipse plugin
    // ignores any nodes added in classpath.file.withXml
    sourceSets {
        main {
            java.srcDirs "src", 'gen'
        }
    }

    jdt {
        sourceCompatibility = 1.6
        targetCompatibility = 1.6
    }

    classpath {
        plusConfigurations += [ project.configurations.compile ]
        containers 'com.android.ide.eclipse.adt.ANDROID_FRAMEWORK', 'com.android.ide.eclipse.adt.LIBRARIES'       
    }

    project {
        name = appName + "-android"
        natures 'com.android.ide.eclipse.adt.AndroidNature'
        buildCommands.clear();
        buildCommand "com.android.ide.eclipse.adt.ResourceManagerBuilder"
        buildCommand "com.android.ide.eclipse.adt.PreCompilerBuilder"
        buildCommand "org.eclipse.jdt.core.javabuilder"
        buildCommand "com.android.ide.eclipse.adt.ApkBuilder"
    }
}

// sets up the Android Idea project, using the old Ant based build.
idea {
    module {
        sourceDirs += file("src");
        scopes = [ COMPILE: [plus:[project.configurations.compile]]]        

        iml {
            withXml {
                def node = it.asNode()
                def builder = NodeBuilder.newInstance();
                builder.current = node;
                builder.component(name: "FacetManager") {
                    facet(type: "android", name: "Android") {
                        configuration {
                            option(name: "UPDATE_PROPERTY_FILES", value:"true")
                        }
                    }
                }
            }
        }
    }
}

**Comment by SimonIT** [comment]
See #5491 #5232

**Comment by DevAnlim** [comment]
Android Studio, unfortunately, is not suitable for libgdx projects, because it allows you to create projects for Android. Standard Java projects are not supported and it is not clear if this will ever be available.

The cross-platform nature does not give in Libgdx with Android Studio. This shouldn't be a big hindrance, as libgdx projects benefit little from Android Studios capabilities. For example. the layout preview does not matter for libgdx because they do not use native Android UI widgets. Built-in documentation support for Android APIs is also not required for libgdx app.

However, we will try to make libgdx application development a new Android Cradle system possible in the near future.

**Comment by DevAnlim** [comment]
Alternatively, you can use Intellij IDEA with libgdx, potentially with Maven.

**Comment by julienvillegas** [comment]
This is a warning, not an error. 
I use Android Studio and latest LibGDX version with my games, including the one in developement [Shooter](https://twitter.com/JulienVillegas/status/1124035985199849477?s=20) and I deploy to iOS / Android without problem.

**Comment by DevAnlim** [comment]
> This is a warning, not an error.
> I use Android Studio and latest LibGDX version with my games, including the one in developement [Shooter](https://twitter.com/JulienVillegas/status/1124035985199849477?s=20) and I deploy to iOS / Android without problem.

The fact is that libgdx even the gradle collector itself and then an outdated version , if you use an Android Studio then please let us know how you deploy the project in the Studio

**Comment by mgsx-dev** [comment]
@DevAnlim if you have trouble using libgdx with Android Studio, please use libgdx forum, IRC or discord.

**Comment by DevAnlim** [comment]
> @DevAnlim if you have trouble using libgdx with Android Studio, please use libgdx forum, IRC or discord.

Well, I use Intellij IDEA to work with libgdx

**Comment by mustii82** [comment]
A new Gradle Script System for LibGDX would be really nice to stay up to date

**Comment by Tom-Ski** [comment]
Yup. I have been working on produciton with latest updates, and will update our setup before next release. Seems to be Ok for the most part, but there are still some problems with IDE integration. And AS is almost non functional to use in any sensible way.
