### ISSUE TITLE
Bullet Wrapper Triangle callbacks

### ISSUE THREAD

**Issue by RolandWeil** [libgdx/libgdx#5625]
#### Issue details
I would like to create my own TriangleIndexCallback. However, in the callback function _internalProcessTriangleIndex(btVector3 triangle, int partId, int triangleIndex)_ I only get the first vector of the triangles. Is it possible to customize the bullet wrapper to pass an array (or a List) with all three vectors of the triangle? (e.g. _internalProcessTriangleIndex(btVector3[] triangle, int partId, int triangleIndex)_)

#### Reproduction steps/code
```java
public class MyInternalTriangleIndexCallback extends btInternalTriangleIndexCallback {

	@Override
	public void internalProcessTriangleIndex(btVector3 triangle, int partId, int triangleIndex) {
		Vector3 v0 = new Vector3(triangle.getFloats());
		System.out.println(triangleIndex + ": " + v0);
	}

	public static void main(String[] args) {
		LibGDXLoader libgdxLoader = new LibGDXLoader();
		libgdxLoader.loadAll();

		btTriangleMesh triangleMesh = new btTriangleMesh();
		triangleMesh.addTriangle(new Vector3(0, 0, 0), new Vector3(0, 1, 0), new Vector3(0, 2, 0));
		triangleMesh.addTriangle(new Vector3(1, 0, 0), new Vector3(1, 1, 0), new Vector3(1, 2, 0));
		triangleMesh.addTriangle(new Vector3(2, 0, 0), new Vector3(2, 1, 0), new Vector3(2, 2, 0));

		MyInternalTriangleIndexCallback callback = new MyInternalTriangleIndexCallback();
		Vector3 aabbMin = new Vector3();
		Vector3 aabbMax = new Vector3(2, 2, 2);
		triangleMesh.InternalProcessAllTriangles(callback, aabbMin, aabbMax);
	}

}
```
```js
0: (0.0,0.0,0.0)
1: (1.0,0.0,0.0)
2: (2.0,0.0,0.0)
```

#### Version of LibGDX and/or relevant dependencies
1.9.10

#### Please select the affected platforms
- [ x] Linux

**Comment by EtK2000** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker

**Comment by RolandWeil** [comment]
> https://github.com/libgdx/libgdx/wiki/Issue-Tracker

I'm not sure but I guess that means I should post my request in the forum: https://www.badlogicgames.com/forum/viewtopic.php?f=11&t=28971

Then maybe this section should be changed accordingly: https://github.com/libgdx/libgdx/wiki/Bullet-Wrapper---Using-the-wrapper#working-with-bullet-wrapper ?
