### ISSUE TITLE
LWJGL3 switch to fullscreen slow + unpredictable results

### ISSUE THREAD

**Issue by Schyfis** [libgdx/libgdx#5626]
#### Issue details
I'm testing out the LWJGL3 backend to see if the basics are usable yet, and I'm _still_ running into issues with fullscreen mode. Specifically, if the game starts in windowed mode and switches to fullscreen mode, it takes 5+ seconds and also does not position the fullscreen window correctly. The previous LWJGL3 backend I tested was libGDX 1.9.4, and while other game-breaking issues occurred I don't remember this specific issue ever occurring.

![Fullscreen window bug picture](https://i.imgur.com/Pw5gpUg.png)

**Expected result: The window should be all red and cover the entire desktop.
Current result: The window is misplaced and you can see my desktop and taskbar.**

Switching between windowed and fullscreen repeatedly sometimes fixes it, but it's not consistent.
Graphics info: Radeon RX 580 + Radeon R9 200

#### Reproduction steps/code
This is reproducible with a barebones project. In the following code, the game will start with a windowed resolution of 640x480. After about 3 seconds (assuming a 60Hz refresh rate), it will attempt to switch to fullscreen mode using whatever is reported by `Gdx.graphics.getDisplayMode()`.

DesktopLauncher.java:
```
package com.mygdx.game.desktop;

import com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application;
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration;
import com.mygdx.game.MyGdxGame;

public class DesktopLauncher {
	public static void main (String[] arg) {
		Lwjgl3ApplicationConfiguration config = new Lwjgl3ApplicationConfiguration();
		config.useVsync(true);
		config.setWindowedMode(640, 480); //start in windowed mode
		new Lwjgl3Application(new MyGdxGame(), config);
	}
}
```
MyGdxGame.java:
```
package com.mygdx.game;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.GL20;

public class MyGdxGame extends ApplicationAdapter {
	int n = 0;
	
	@Override
	public void create () {
		
	}

	@Override
	public void render () {
		Gdx.gl.glClearColor(1, 0, 0, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		
		n++;
		
		//after about 3 seconds at 60 FPS, change to fullscreen
		if(n == 180) {
			Gdx.graphics.setFullscreenMode(Gdx.graphics.getDisplayMode());
		}
	}
	
	@Override
	public void dispose () {
		
	}
}
```

#### Version of LibGDX and/or relevant dependencies
1.9.9

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
I can't reproduce this. What is your monitor setup? What GPU driver are you running?

**Comment by Schyfis** [comment]
Was running Radeon driver version 18.10.01.05 (23.20.150173010 as reported by Windows device manager).

Updated today to the latest version (19.4.1 as reported by Radeon Settings) to see if that would resolve the issue, and it did! Closing as I can no longer reproduce the issue.

**Comment by Tom-Ski** [comment]
Nice :)
