### ISSUE TITLE
Generics for Tree actor

### ISSUE THREAD

**Issue by Silobrlst** [libgdx/libgdx#5627]
Can be implemented generics support for Tree actor, so I can implement custom tree nodes?
Yes I can extend class Tree.Node, add to tree, get this from tree, and cast to my custom class.
But it would be very good with generics, because I very often use tree widget and implement custom nodes.

**Comment by EtK2000** [comment]
The best option is to implement it yourself and submit a pull request.

**Comment by NathanSweet** [comment]
It is a pain to make it nice in Java, eg:
https://www.sitepoint.com/self-types-with-javas-generics/

However, I also often use Node subclasses and agree it's not great having a mix of Node and CustomNode types. We can throw generics on it, with some quirks.

Subclassing a node is done using `CustomNode extends BaseNode<CustomNode>`, which is a little odd. When _not_ using a custom tree node, we need to avoid the type `Node` from being a raw type, else existing code would break and you'd need to use `Node<Node>`, which is stupid looking. So we'll need to use an abstract class and declare Node using `Node extends BaseNode<Node>`.

Unfortunately existing code will break, but at least it is minimal. You will need to change:
```
Tree tree = new Tree();
```
To:
```
Tree<Node> tree = new Tree();
```

This all kind of sucks, but it's certainly a lot nicer for UIs that subclass nodes.

**Comment by Silobrlst** [comment]
Thanks )
