### ISSUE TITLE
Content actor in Tree.Node not filling in full width

### ISSUE THREAD

**Issue by Silobrlst** [libgdx/libgdx#5628]
Actor doesn't filling full width of Tree.Node. Can't find solution for this.

Piece of code from my project (this is in the kotlin, but I think the meaning is clear):
```kotlin
fun addSection(name: String, table: Table, icon: Drawable? = null){
    val title = Tree.Node(VisLabel(name))
    title.icon = icon
    sections.add(title)

    val node = Tree.Node(table)
    title.add(node)
}
```

I also tried to change this line:
```kotlin
val node = Tree.Node(table)
```
to
```kotlin
val table = Table()
table.add(VisTextField()).growX()
val node = Tree.Node(table)
```
but no effect.

And the result is:
![tree](https://user-images.githubusercontent.com/8915999/57510320-e84c3680-731f-11e9-9e4d-59676715a1cb.png)
Node filling full width of Tree, but content doesn't do it.

Is there any solution?

Version of LibGDX - 1.9.9
VisUI is used.

**Comment by Darkyenus** [comment]
Please do not ignore the issue template and provide a [SSCCE](http://sscce.org/).

**Comment by Silobrlst** [comment]
```java
VisWindow window = new VisWindow("");
window.setWidth(600f);

VisTextField textField = new VisTextField();
Table table = new Table();
table.add(textField).growX();

VisTree tree = new VisTree();
Tree.Node node = new Tree.Node(table);
node.setExpanded(true);
tree.add(node);

window.add(tree).grow();

getStage().addActor(window);
```

**Comment by Tom-Ski** [comment]
Using external library. If you can reproduce with default LibGDX classes then please provide SSCCE.
