### ISSUE TITLE
[Feature Request] Focused font colors in TextButton

### ISSUE THREAD

**Issue by EtK2000** [libgdx/libgdx#5630]
Now that `Button` has an option to set the background if it's focused it would be nice to have the text color changeable in `TextButton`.

**Comment by NathanSweet** [comment]
Seems reasonable. Would you like to make a PR?

**Comment by EtK2000** [comment]
I can do that.
I'll be home in a week, so I'll do it then.

Should I also add any focused style elements to other Actors?
For example `SelectBox` which doesn't have yet.

**Comment by NathanSweet** [comment]
#5093 is for that, but I'm still a bit worried about making things more complicated than necessary.

**Comment by EtK2000** [comment]
Ok, so I won't touch `SelectBox`.
