### ISSUE TITLE
SnapshotArray not thread safe - multiple race conditions

### ISSUE THREAD

**Issue by davidgiga1993** [libgdx/libgdx#5632]
#### Issue details
The `add` method of `SnapshotArray` is not thread safe.
This causes issues when adding actors asynchronous to a stage while the rendering thread is iterating the actors.

#### Reproduction steps/code
A simple fuzzy test can reproduce the issue
```java
public class TestSnapshotArray
{
	private static final int TICKS = 100000;

	@Test
	public void testSynchronized() throws InterruptedException
	{
		final SnapshotArray<Integer> array = new SnapshotArray<>();

		Thread t1 = new Thread(new BeginEndFuzzy<>(array));
		Thread t2 = new Thread(new AddRemoveFuzzy(array));
		t1.start();
		t2.start();
		t1.join();
		t2.join();
	}

	private static class AddRemoveFuzzy implements Runnable
	{
		private final SnapshotArray<Integer> array;

		private AddRemoveFuzzy(SnapshotArray<Integer> array)
		{
			this.array = array;
		}

		@Override
		public void run()
		{
			int tick = 0;
			while (tick < TICKS)
			{
				tick++;
				for (int X = 0; X < 50; X++)
					array.add(X);

				for (int X = 0; X < 50; X++)
					array.removeValue(X, true);
			}
		}
	}

	private static class BeginEndFuzzy<T> implements Runnable
	{
		private final SnapshotArray<T> array;

		private BeginEndFuzzy(SnapshotArray<T> array)
		{
			this.array = array;
		}

		@Override
		public void run()
		{
			int tick = 0;
			while (tick < TICKS)
			{
				tick++;

				array.begin();

				T[] items = array.begin();
				for (int i = 0, n = array.size; i < n; i++)
				{
					assertNotNull(items[i]);
				}
				array.end();
			}
		}
	}
}
```

#### Version of LibGDX and/or relevant dependencies
1.9.8 / 1.9.9

#### Stacktrace
Not required as test case provided.
The issue is that the `size` field is not thread safe therefore the read loop will access the null entries of the snapshot or even worse get an out of bounds exception

#### Please select the affected platforms
- [X] Android
- [X] iOS (robovm)
- [X] iOS (MOE)
- [X] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by Darkyenus** [comment]
libGDX is not thread safe, unless specified otherwise. This is for performance reasons and because thread safety is much more complicated than just throwing `synchronized` everywhere.

This is not a bug. You should add necessary locking yourself.

**Comment by davidgiga1993** [comment]
I know that libgdx is not thread safe but according to the docstring of SnapshotArray it is thread safe. Otherwise using that data structure wouldn't make sense I guess.

**Comment by Tom-Ski** [comment]
Where does it say that?

**Comment by davidgiga1993** [comment]
The very first sentence implies it: 
https://libgdx.badlogicgames.com/ci/nightlies/docs/api/com/badlogic/gdx/utils/SnapshotArray.html

Also the sort methods are explicitly noted as not thread safe implying that the other methods are safe to use in parallel.
If that's not the case it would be cool to maybe add a short notice to it?

**Comment by Tom-Ski** [comment]
Nothing is thread safe unless explicitly said so. This does not emply it if you keep this in mind. 
That said if you think the documentation could use more clarifications, feel free to add in a PR.

**Comment by davidgiga1993** [comment]
Okay, will do. Thanks for your fast reply!

**Comment by Darkyenus** [comment]
The note about `sort` not being thread safe is actually an understatement - it is even less thread safe than other non-thread safe methods. To be more specific: you can have multiple `SnapshotArray`s on different threads and use them in parallel, as long as no two threads use the same array instance at the same time. This is the "standard" definition of thread safety. But `sort` is special as it uses a static field through `Sort.instance`, which means that even if two threads have different `SnapshotArray` instances, they must not `sort` at the same time.
