### ISSUE TITLE
gradle "compile" and .. is dead the project?

### ISSUE THREAD

**Issue by tesoner** [libgdx/libgdx#5639]
Is this project dead?
I've been seeing that there are commits, however, it has not been updated on the official page. I also do not see that it integrates well with Eclipse or IntelliJ, it always gives errors, I could only run it in Android Studio, I do not know what magic I used for that.
The project uses elements such as "compile" in Gradle, that is out of date. Now, the question
Is this project dead? Is it worth starting a long-term project with this library?

**Comment by Tom-Ski** [comment]
If you have issues importing the project, create issues for them. "compile" warnings are just that. If you are running recommended (and default) settings, you should have no problems in your IDE. If you are having problems, make an issue following the issue template so we can resolve them.

For everything else, please use irc or forums. https://github.com/libgdx/libgdx/wiki/Issue-Tracker
