### ISSUE TITLE
Unity asset animation data not applied as expected

### ISSUE THREAD

**Issue by catmanjan** [libgdx/libgdx#5643]
#### Issue details
I've attached the offending model and animation. They work fine in unity and blender - but when importing them into libgdx they do not work as expected. In particular, the right arm is stuck out straight.

[animations.zip](https://github.com/libgdx/libgdx/files/3241597/animations.zip)

Unity models are exported in a t-pose and then have animations applied to them after the fact. The animation models do not necessarily start from a t-pose, but rather any pose - I believe this is what is causing the issue. I think the copyAnimation code from #4972 may need to be enhanced to allow for animations to be copied between models which did not have the same initial pose.

#### Reproduction steps/code
* ensure you are running with the change from PR #4972 
* load the attached model
* load the attached animation
* apply the animation to the model
* the model animates as expected, except for the right arm which is pointing down, but straight

#### Version of LibGDX and/or relevant dependencies
1.9.9

**Comment by Tom-Ski** [comment]
PLease provide a test case to test. https://github.com/libgdx/libgdx/wiki/More-Info

**Comment by catmanjan** [comment]
Here you go, you need to make sure these assets are wherever internal assets are loading from...

[assets.zip](https://github.com/libgdx/libgdx/files/3241778/assets.zip)

![image](https://user-images.githubusercontent.com/137350/58714811-e8b08c80-8408-11e9-81dc-e721040779a7.png)

```package com.catmanjan;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.PerspectiveCamera;
import com.badlogic.gdx.graphics.g3d.Model;
import com.badlogic.gdx.graphics.g3d.ModelBatch;
import com.badlogic.gdx.graphics.g3d.ModelInstance;
import com.badlogic.gdx.graphics.g3d.loader.G3dModelLoader;
import com.badlogic.gdx.graphics.g3d.model.Animation;
import com.badlogic.gdx.graphics.g3d.model.Node;
import com.badlogic.gdx.graphics.g3d.model.NodeAnimation;
import com.badlogic.gdx.graphics.g3d.model.NodeKeyframe;
import com.badlogic.gdx.graphics.g3d.utils.AnimationController;
import com.badlogic.gdx.math.Quaternion;
import com.badlogic.gdx.math.Vector3;
import com.badlogic.gdx.utils.Array;
import com.badlogic.gdx.utils.UBJsonReader;

public class Issue5643 extends ApplicationAdapter {

    ModelInstance model;
    ModelBatch modelBatch;
    AnimationController animationController;
    PerspectiveCamera camera;

    public void create () {
        modelBatch = new ModelBatch();
        camera = new PerspectiveCamera(67, 800, 600);
        camera.near = 1f;
        camera.far = 10000f;
        camera.position.set(120,120, 120);
        camera.lookAt(0,0,0);
        camera.update();

        UBJsonReader jsonReader = new UBJsonReader();
        G3dModelLoader g3Loader = new G3dModelLoader(jsonReader);
        Model dude = g3Loader.loadModel(Gdx.files.internal("ToonSoldier_WW2_demo.g3db"));
        Model animation = g3Loader.loadModel(Gdx.files.internal("infantry_combat_idle.g3db"));

        model = new ModelInstance(dude);

        for (Animation sourceAnim : animation.animations) {
            copyAnimation(model, sourceAnim, false);
        }

        animationController = new AnimationController(model);
        animationController.animate(model.animations.first().id, -1, 1f, null, 0.2f);
    }

    public void render () {
        animationController.update(Gdx.graphics.getDeltaTime());
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT | GL20.GL_DEPTH_BUFFER_BIT);
        Gdx.gl.glEnable(GL20.GL_DEPTH_TEST);
        Gdx.gl.glClearColor(1.0f, 1.0f, 1.0f, 1.0f);
        modelBatch.begin(camera);
        modelBatch.render(model);
        modelBatch.end();
    }

    public static void main (String[] args) throws Exception {
        new LwjglApplication(new Issue5643());
    }

    // extracted from pr 4972 so it can be replicated in 1.9.9
    public void copyAnimation(ModelInstance model, Animation sourceAnim, boolean shareKeyframes){
        Animation animation = new Animation();
        animation.id = sourceAnim.id;
        animation.duration = sourceAnim.duration;
        for (final NodeAnimation nanim : sourceAnim.nodeAnimations) {
            final Node node = model.getNode(nanim.node.id);
            if (node == null) continue;
            NodeAnimation nodeAnim = new NodeAnimation();
            nodeAnim.node = node;
            if (shareKeyframes) {
                nodeAnim.translation = nanim.translation;
                nodeAnim.rotation = nanim.rotation;
                nodeAnim.scaling = nanim.scaling;
            } else {
                if (nanim.translation != null) {
                    nodeAnim.translation = new Array<NodeKeyframe<Vector3>>();
                    for (final NodeKeyframe<Vector3> kf : nanim.translation)
                        nodeAnim.translation.add(new NodeKeyframe<Vector3>(kf.keytime, kf.value));
                }
                if (nanim.rotation != null) {
                    nodeAnim.rotation = new Array<NodeKeyframe<Quaternion>>();
                    for (final NodeKeyframe<Quaternion> kf : nanim.rotation)
                        nodeAnim.rotation.add(new NodeKeyframe<Quaternion>(kf.keytime, kf.value));
                }
                if (nanim.scaling != null) {
                    nodeAnim.scaling = new Array<NodeKeyframe<Vector3>>();
                    for (final NodeKeyframe<Vector3> kf : nanim.scaling)
                        nodeAnim.scaling.add(new NodeKeyframe<Vector3>(kf.keytime, kf.value));
                }
            }
            if (nodeAnim.translation != null || nodeAnim.rotation != null || nodeAnim.scaling != null)
                animation.nodeAnimations.add(nodeAnim);
        }
        if (animation.nodeAnimations.size > 0) model.animations.add(animation);
    }
}```

**Comment by catmanjan** [comment]
Alright looks like the rotation component is missing from the animation because the initial pose contains the rotation, not the animation, if I modify `copyAnimation` like this it works (for this particular model)

```
if (nanim.rotation != null) {
	nodeAnim.rotation = new Array<NodeKeyframe<Quaternion>>();
	for (final NodeKeyframe<Quaternion> kf : nanim.rotation)
		nodeAnim.rotation.add(new NodeKeyframe<Quaternion>(kf.keytime, kf.value));
} else {
	nodeAnim.rotation = new Array<NodeKeyframe<Quaternion>>();
	for (int i = 0; i < 64; i++) {
		Node otherNode = animatedModel.getNode(node.id);
		nodeAnim.rotation.add(new NodeKeyframe<Quaternion>(i *0.00333333f, otherNode.rotation));
	}
}
```

At first I suspected that information was being lost through the blender export or by fbx-conv, but if I manually introduce rotation in blender into the animation, the rotation is applied as expected.

So it looks like the the animation is excluding the rotation component of each bone because from its point of view there is none - it is basing the keyframe rotation values based on a differential from the initial pose.

The fix I am proposing is to modify `ModelInstance.copyAnimation` such that if a `NodeAnimation` has a translation, rotation or scaling component and if any of the other components are null, the null values should be replaced with "fake" `NodeKeyframes` which take their value from the corresponding animation model node - this should ensure that external animations are correct regardless of their starting poses.

I would guess that there are a few people looking into using unity assets with its vast asset store, so maybe it is worth making a PR? Would like to hear from thoughts on this from maintainers.

**Comment by Tom-Ski** [comment]
@xoppa

**Comment by mgsx-dev** [comment]
@catmanjan Your proposal has some unwanted side effects and can't be generalized : sometimes you want to run several animations on the same model at the same time (eg. one animation for the lower body parts, one animation for the upper body parts). If we force initial pose keyframes for missing channels, there will be some conflicts. 

Maybe Unity doesn't provide this "multi-animations" feature and then can fix animations at runtime without undesirable effects.

With libGDX, the "recommended way" is to ensure at least one keyframe (at time zero) for all nodes/channels you animate (what you did in Blender).

I guess that in your case (pre-made assets), you'd prefer to fix your animations programmatically like this : 

```java
public void create () {
  ...
  Model animation = g3Loader.loadModel(Gdx.files.internal("issue5643/infantry_combat_idle.g3db"));
  addMissingKeyFrames(animation);
  ...
}
public static void addMissingKeyFrames(Model model) {
  for(Animation animation : model.animations){
    for(NodeAnimation nodeAnim : animation.nodeAnimations){
      if(nodeAnim.rotation == null){
        nodeAnim.rotation = new Array<NodeKeyframe<Quaternion>>();
        nodeAnim.rotation.add(new NodeKeyframe<Quaternion>(0, nodeAnim.node.rotation));
      }
      if(nodeAnim.translation == null){
        nodeAnim.translation = new Array<NodeKeyframe<Vector3>>();
        nodeAnim.translation.add(new NodeKeyframe<Vector3>(0, nodeAnim.node.translation));
      }
      if(nodeAnim.scaling == null){
        nodeAnim.scaling = new Array<NodeKeyframe<Vector3>>();
        nodeAnim.scaling.add(new NodeKeyframe<Vector3>(0, nodeAnim.node.scale));
      }
    }
  }
}
```

**Comment by catmanjan** [comment]
Thanks mgsx, it looks like Unity's animation system uses layers which can be mixed, you specify a default animation which would have the `addMissingKeyframe` functionality and other layers can then override it.

Do you think there is any room for a system like this in libgdx or is it more of an extension?

**Comment by mgsx-dev** [comment]
@catmanjan libgdx AnimationController already provides animation blending (animate + action) which perform a mix between 2 animations. I think it's enough for most of use cases. 

However, it would be nice to have a more flexible AnimationController API in order to implement more blending, non linear interpolations and more channels : i had to monkey patch it in one of my extension in order to implement shapeKeys (morphTargets). I think there is definitely a room for improvement here.

Anyway, this is another topic and we should discuss it on other community channels (you can found me on discord). Maybe we can close this issue if you think my workaround is fine.

**Comment by catmanjan** [comment]
Agreed, closing - hopefully this will come up in Google if anyone else is having problems with Unity animations and libgdx
