### ISSUE TITLE
 (java.lang.NumberFormatException) loading LayerImage from TiledMap software

### ISSUE THREAD

**Issue by thoced** [libgdx/libgdx#5651]
Hello

When loading an image layer from the Tiled software. An exception arises when the displacement values ​​x and y are not integers.

Tiled software allows positioning with float value.

The loadImageLayer method of the BaseTmxMapLoader class generates an exception "java.lang.NumberFormatException" because it tries to transform a string into an integer from possibly a string that can give a float value

**Comment by TCreutzenberg** [comment]
You should link your pull request here I guess.
