### ISSUE TITLE
kotlin - core code

### ISSUE THREAD

**Issue by hpn33** [libgdx/libgdx#5656]
why dont change core code to kotlin?

**Comment by EtK2000** [comment]
Firstly, this isn't an issue.
Secondly, this has bren answered countless times.
It's a lot of work that no one wants to do for little payoff.

It's already hard enough to maintain LibGDX, a whole rewrite is completely out of the question AFAIK.

If you want more descriptive or better answers Google, look in the forums, or closed issues about the same topic.

Requesting this to be closed.

**Comment by MrStahlfelge** [comment]
I want to add that it also has some enormous drawbacks to use Kotlin.

**Comment by mustii82** [comment]
@MrStahlfelge which one except of the Web part which is not usable with kotlin?

**Comment by MrStahlfelge** [comment]
Another drawback is that it enlarges the APK size on Android. And another one that it makes the framework harder to use for Java developers.

**Comment by RUSshy** [comment]
But it has many benefits:

Kotlin Multiplatform for example, why ? you'll now be able to target:

- Java Desktop
- Java Android
- JS Web
- Native Desktop
- Native iOS
- Native Android
- Native Web Assembly

**Comment by mustii82** [comment]
We could even have a good working iOS-Backend and many things like the target code is provided by jetbrains so we could be more focused about LibGDX itself

**Comment by MobiDevelop** [comment]
Rewriting the entire framework in another language is a huge undertaking which is unlikely to happen. If it is important enough to someone, they are free to start porting it themselves.

**Comment by intrigus** [comment]
LWJGL is NOT written in Kotlin.
It uses Kotlin to generate the glue code for interfacing with OpenGL, OpenCL etc but everything that is distributed is written in Java.

**Comment by SerVB** [comment]
Kotlin is great and if someone starts porting, please, call me ;) LibGDX 2.0?

For now, this looks extremely convenient: #5599.

**Comment by RUSshy** [comment]
I'm ready to start port to kotlin when kotlin native is more stable

**Comment by RUSshy** [comment]
I did it already in D, C# and C++
