### ISSUE TITLE
@ character inputted both on keyDown and keyUp in TextField (OS X, AZERTY layout)

### ISSUE THREAD

**Issue by LaP0573** [libgdx/libgdx#5660]
#### Issue details
On OS X, using AZERTY layout (@ key is just under Escape key), when writing into a TextField, the "@" character gets written both when the key is pressed and when it's released. It also happens with "#", which is on the same key (need to press the shift modifier to write it).

**Note : this doesn't happen with LWJGL 3, only with version 2, but I felt it would be worth creating an issue for it as it seems LWJGL isn't 100% supported yet for libgdx.**

The key is there : https://cdn.discordapp.com/attachments/348552152387551244/586096396021792768/20190606_093726.jpg

#### Reproduction steps/code
Will happen in any TextField on OS X using AZERTY layout.

#### Version of LibGDX and/or relevant dependencies
1.9.9
LWJGL version 2

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [X] MacOS

**Comment by intrigus** [comment]
I guess that this is a LWGL2 Problem and not related to how libGDX handles the received input.
If this is the case you are probably out of luck, since LWJGL2 is EOL.

**Comment by NathanSweet** [comment]
You will likely need to look into what you can do to fix this in the lwjgl2 backend. I don't use Mac and don't usually work on Mac specific bugs. If you provide a fix I can test that Windows is still working right.

**Comment by NathanSweet** [comment]
LWJGL2 is getting old and no longer maintained. Consider using LWJGL3, if possible.
