### ISSUE TITLE
Gradle 5.4 support

### ISSUE THREAD

**Issue by mr-gri3ves** [libgdx/libgdx#5664]
#### Issue details
Build fails with Java 12.
Uses of deprecated gradle api, like compile.

#### Reproduction steps/code
_Even if you think your issue is trivial to reproduce, please supply a [SSCCE](http://sscce.org/) that demonstrates your issue.  This saves time on our end, and makes it much more likely that your issue will be fixed.
You can find barebones templates [here](https://github.com/libgdx/libgdx/wiki/Getting-help)_

#### Version of LibGDX and/or relevant dependencies
The version from official site
#### Stacktrace
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: android

#### Please select the affected platforms
- [x] Android

**Comment by Andresnotch** [comment]
I got the same problem, it was solved by deleting gradlew and gradlew.bat, and the gradle wrapper folder, and then in the root directory of the project using the command `gradle wrapper`. It solved the version problem, but there is another thing that has to be solved before being able to compile the project:
At desktop/build.gradle, `sourceSets.main.output.classesDir` has to be changed to `sourceSets.main.output.classesDirs`(found the solution [here](https://discuss.gradle.org/t/could-not-get-unknown-property-classesdir-for-main-classes-of-type-org-gradle-api-internal-tasks-defaultsourcesetoutput/30570), and [here](https://discuss.gradle.org/t/could-not-get-unknown-property-classesdir-for-main-classes/30591)).
Now it gets to the compilation part, and in my case it throws an error, but probably its something in my code. Hope it helped :)

**Comment by hrant-nurijanyan** [comment]
Thanks for the hing @Andresnotch . BTW I changed the libGDX .jar file, now it downloads latest version of gradle and works with Java 12, also I changed to sourceSets.main.output.classesDirs. Tested on Android and Desktop.(Don't have MAC to test on iOS and don't know how to properly run gwt :) )

P.S. Download change the extension to .jar and start coding.
P.S.S Don't know is it legal or not, anyway I am not licensed to this product. I don't own this.
[new-gdx-setup.zip](https://github.com/libgdx/libgdx/files/3288722/new-gdx-setup.zip)

**Comment by mustii82** [comment]
did you do a pull request on the offical Gdx-Setup Repo?

**Comment by hrant-nurijanyan** [comment]
No I have not. I'll do that as soon as I sit in front of my laptop)

**Comment by hrant-nurijanyan** [comment]
I am sorry but libgdx have not given me the access rights to push on the repo(on another branch) to open the pull request. How can I ask them for the rights?

**Comment by Darkyenus** [comment]
@hrant-nurijanyan Don't ask for write rights, that is not how GitHub works. Fork the repository, create a branch there and GitHub will offer UI to create a pull request into this repo automatically. See https://help.github.com/en/articles/about-pull-requests for more info :)

**Comment by mr-gri3ves** [comment]
Thanks to all. Actually, that was the first time I was creating pull
request on an open source github project ;).

**Comment by mustii82** [comment]
@mr-gri3ves Congratulations :)

**Comment by mustii82** [comment]
@mr-gri3ves could you replace compile with implement as well in your PR? just to stay up to date with Gradle :)

**Comment by mr-gri3ves** [comment]
I'll do that on my branch and do a pull request)

**Comment by mr-gri3ves** [comment]
@mustii82 Do you know where I can change them??

**Comment by mustii82** [comment]
@mr-gri3ves do you mean in the code ? or where in the gradle file? in case of the gradle file its the main build.gradle

**Comment by itsabhiaryan** [comment]
Not able to include external library after updating existing project from `5.1.1` to `5.4.1`

How I'm including external library ?
1.  **abc** is the name of my external library 
2.  added `":abc"` in `settings.gradle` file 

```
include 'desktop', 'android', 'ios', 'core', ":abc"        //<-   added abc
project(":abc").projectDir = file("../abc")
```

3. In root `build.gradle` file added `abc`

```
project(":core") {
    apply plugin: "kotlin"

    dependencies {
        api project(':abc')                              //<-   added abc
        api "com.badlogicgames.gdx:gdx:$gdxVersion"
        api "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
    }
}
```
After Gradle syncing, I'm getting 
```
ERROR: Failed to resolve: project::abc
Affected Modules: core
```

Any external build script dependency that might be the cause : YES

```
classpath 'com.android.tools.build:gradle:3.4.2'
classpath 'com.google.gms:google-services:4.3.0'

```

GDXVersion : `1.9.10`
