### ISSUE TITLE
glutils.InstanceBufferObject; inherit a required module? "Solved"

### ISSUE THREAD

**Issue by amin3adel** [libgdx/libgdx#5671]
actually i no longer have this issue the full application is running now with particles , but i wanted to share what i've done to bypass it ,and maybe get a normal solution :)

#### Issue details
Error :
-Tracing compile failure path for type '**com.badlogic.gdx.graphics.Mesh**'
 -No source code is available for type **com.badlogic.gdx.graphics.glutils.InstanceBufferObject**; did you forget to inherit a required module?
-No source code is available for type **com.badlogic.gdx.graphics.glutils.InstanceData**; did you forget to inherit a required module?

#### Reproduction steps/code
1- I created new project using latest **gdx-setup.jar** , **GWT module ran normally** .
2- I changed gdxVersion in (project.gradle) to **1.9.10-SNAPSHOT** to use particleEffects fix , the error above occurred.
i didn't add any code or libs , just the project created via the tool.

#### Version of LibGDX and/or relevant dependencies

- 1.9.10-SNAPSHOT

#### Stacktrace

Add this
_**\<source path="com/badlogic/gdx/graphics/glutils" />**_
to .gwt.xml in core module , and error is gone

is this normal ? shouldn't those types be included automatically ?

---------------------------------------
Edit 1 : 
while running **SuperDev** whenever i try to compile by pressing **Dev Mode On** i get at the console  :
-Tracing compile failure path for type **com.badlogic.gdx.graphics.glutils**.
-[**ERROR**] Line 57: The method **newUnsafeByteBuffer(int)** is **undefined** for the type **BufferUtils**
-[**ERROR**] Line 95: The method **disposeUnsafeByteBuffer(ByteBuffer)** is undefined for the type **BufferUtils**
-[**ERROR**] Compiler returned false
-[**WARN**] recompile failed
-[**WARN**] continuing to serve previous version

i'm also bypassing that by ending **SuperDev** and relaunching it .

------------------------------------
Edit 2:
**html:dist** gives multiple errors : 
-  Methods mentioned @**Edit 1** and other methods are **undefined** or **not applicable** in another classes
com.badlogic.gdx.graphics.glutils.KTXTextureData
com.badlogic.gdx.graphics.glutils.FileTextureArrayData
com.badlogic.gdx.graphics.glutils.ETC1'
com.badlogic.gdx.graphics.glutils.InstanceBufferObject'

right now i'm thinking :
 adding _**\<source path="com/badlogic/gdx/graphics/glutils" />**_  **did that** 

i'll keep using the draftout for now 👍 

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [* ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
This should be fixed already by @MobiDevelop .

**Comment by amin3adel** [comment]
then ,do you have any clue why i'm getting it ?
should that fix be in the current "snapShot-1.9.10"
 , or i should download "libgdx-nightly-20190602.zip "  ? 
,or should i wait for a release :D ?

**Comment by Tom-Ski** [comment]
Yes, because there hasn't been a build since he fixed it! Will make sure we have one by end of today.
