### ISSUE TITLE
SpriteBatch::end causes NullPointerException after drawing new TextureRegion()

### ISSUE THREAD

**Issue by limbusdev** [libgdx/libgdx#5686]
#### Issue details
Using `batch.draw(...)` to draw a **TextureRegion** that was created with the default constructor, causes a NullPointerException. Since there is a default constructor `TextureRegion region = new TextureRegion()` I think this should not happen. If it should happen, the empty constructor should not be available.

#### Reproduction steps/code
Run this code:
```java
private TextureRegion region = new TextureRegion();
private SpriteBatch batch = new SpriteBatch();

private void draw()
{
  batch.begin();
  batch.draw(region, 0f, 0f, 1024f, 512f);
  batch.end();
}
```

This can be prevented by:

```java
private void draw()
{
  batch.begin();
  if(region.getTexture() != null) { batch.draw(region, 0f, 0f, 1024f, 512f); }
  batch.end();
}
```

#### Version of LibGDX and/or relevant dependencies
1.9.9

#### Stacktrace
```java
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.flush(SpriteBatch.java:960)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.end(SpriteBatch.java:185)
	at de.limbusdev.guardianmonsters.ui.AScreen.drawBackground(AScreen.kt:64)
	at de.limbusdev.guardianmonsters.ui.AScreen.render(AScreen.kt:80)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

#### Please select the affected platforms
I guess all.

**Comment by NathanSweet** [comment]
Please use the Java language when providing code in issues.

The Texture class does not have a zero argument constructor.

**Comment by limbusdev** [comment]
I'll change it to Java in a second. Texture does not, but TextureRegion does.

**Comment by limbusdev** [comment]
PS: I don't know why, but it kept changing back the edited stack trace, I hope the correct one stays now.

**Comment by intrigus** [comment]
This code will never reproduce the issue.
You didn't initialize `batch`.

**Comment by limbusdev** [comment]
Use any SpriteBatch, it will reproduce it. I add it to the example.

**Comment by NathanSweet** [comment]
The constructor creates a TextureRegion that cannot be used until a texture and texture coordinates have been set. This makes it easier to create and configure a texture region. The javadocs have been improved.

**Comment by limbusdev** [comment]
The fact that stunned me is, that the draw command did not fail. That made it a little bit hard, to find out what's happening. Thanks for improving the docs.
