### ISSUE TITLE
[Desktop] Music getPosition() not accurate on desktop for MP3s

### ISSUE THREAD

**Issue by thebnich** [libgdx/libgdx#5692]
`Music.getPosition()` lags behind the actual sound position on desktop. Using the code below, the sound is noticeably out of sync after just a few seconds. Everything works as expected on Android and iOS.

Using the latest GDX release (1.9.9).

```
package com.bnich.soundtest;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.audio.Music;
import com.badlogic.gdx.graphics.GL20;

public class Game extends ApplicationAdapter {
    Music music;

    @Override
    public void create() {
        // https://www.dropbox.com/s/foyn8lps7rihwkw/60bpm.mp3?dl=0
        music = Gdx.audio.newMusic(Gdx.files.internal("60bpm.mp3"));
        music.play();
    }

    @Override
    public void render() {
        float beat = music.getPosition() % 1;
        if (beat < 0.05f)
            Gdx.gl.glClearColor(1, 1, 1, 1);
        else
            Gdx.gl.glClearColor(0, 0, 0, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
    }
}

```

**Comment by thebnich** [comment]
After looking into solutions for the similar issue #5693, I was inspired to try a different audio format. As with #5693, using WAV/OGG does, in fact, fix the issue. Unlike #5693, however, this issue isn't triggered by doing a seek first; the music position loses accuracy simply while playing the MP3, which still seems like a bug. Updating title accordingly.

**Comment by MrStahlfelge** [comment]
Can you prefix the title with [Desktop]? Thanks

**Comment by mgsx-dev** [comment]
@thebnich i included your MP3 file in libgdx tests within my PR #5793. Please tell me if it's OK for you.

**Comment by thebnich** [comment]
Nice PR!

I don't own the license to the MP3 originally linked to above, so I just replaced it with a new one generated with Audacity ([link](https://www.dropbox.com/s/foyn8lps7rihwkw/60bpm.mp3?dl=0)). Feel free to include this in the tests.

**Comment by mgsx-dev** [comment]
@thebnich thank you, i replaced it. It's even better, it has different sounds on note / quarter note :-)
