### ISSUE TITLE
[Feature Request] Load TiledMap from Json

### ISSUE THREAD

**Issue by mguldner** [libgdx/libgdx#5707]
**Issue details**

With Libgdx, we can create a TiledMap from a TMX file.
Is it conceivable to create a TiledMap from a JSON file ?
This could be useful for people who want to serialize all their game in JSON.

**Version of LibGDX and/or relevant dependencies**
GDX 1.9.9

**Comment by Darkyenus** [comment]
Is there any good reason for serializing everything into Json?

**Comment by JasonMacKeigan** [comment]
@mguldner I can see why you would want this. That being said, it would probably take up more space due to JSON file structure. Nonetheless, this might be a fun project.
