### ISSUE TITLE
ShapePath: Triangulation problem

### ISSUE THREAD

**Issue by lzs1q0ni** [libgdx/libgdx#5708]
Description of the problem
When creating a polygon with constructPathShape.toShapes the order of the constructpathshapes commands plays a role which shouldn't be the case. (I think so)
I am adding a hole than the outer vertice then again a hole.
The last hole is not recognized.
https://www.diplomaclub.net/

The only thing which was changed is the order of the constructpathshape commands.
If I add the two holes at the beginning the polygon is rendered correctly.
https://www.diplomaclub.net/

Three.js version
[购买美国毕业证办理](购买美国毕业证办理-美国普林斯顿大学文凭Prince毕业证,学位证@ttps://www.diplomaclub.net/代办美国大学毕业证成绩单/美国学历认证书/美国回国人员证明)-美国普林斯顿大学文凭Prince毕业证,学位证@/代办美国大学毕业证成绩单/美国学历认证书/美国回国人员证明

**Comment by Darkyenus** [comment]
There is no method called `toShapes` in this whole repository. You may be on a wrong issue tracker.

If you are sure that this is a libGDX issue, please follow the issue template for your report.
