### ISSUE TITLE
TmxLoader Changed it's behavior

### ISSUE THREAD

**Issue by gagbaghdas** [libgdx/libgdx#5709]
Hi Guys.

I found a backward compatibality issue in the 1.9.10 regarding Tmxloader. 

I have 
```<tileset firstgid="2" source="untitled.tsx"/>```
In my tmx file and all cells that are active have a 2 value (otherwise they have 0 value).

So , my code worked great before 1.9.10 version, but now I found, that all cells in all layers are null.

So, after some debugging, I found that now

```<tileset firstgid="2" source="untitled.tsx"/>```

not working as expected. 

In this code.
```
protected void loadTileSet (Element element, FileHandle tmxFile, ImageResolver imageResolver) {
		if (element.getName().equals("tileset")) {
			String imageSource = "";
			int imageWidth = 0;
			int imageHeight = 0;
			FileHandle image = null;

			String source = element.getAttribute("source", null);
			if (source != null) {
				FileHandle tsx = getRelativeFileHandle(tmxFile, source);
				try {
					element = xml.parse(tsx);
					Element imageElement = element.getChildByName("image");
					if (imageElement != null) {
						imageSource = imageElement.getAttribute("source");
						imageWidth = imageElement.getIntAttribute("width", 0);
						imageHeight = imageElement.getIntAttribute("height", 0);
						image = getRelativeFileHandle(tsx, imageSource);
					}
				} catch (SerializationException e) {
					throw new GdxRuntimeException("Error parsing external tileset.");
				}
			} else {
				Element imageElement = element.getChildByName("image");
				if (imageElement != null) {
					imageSource = imageElement.getAttribute("source");
					imageWidth = imageElement.getIntAttribute("width", 0);
					imageHeight = imageElement.getIntAttribute("height", 0);
					image = getRelativeFileHandle(tmxFile, imageSource);
				}
			}

			String name = element.get("name", null);
			int firstgid = element.getIntAttribute("firstgid", 1);
			int tilewidth = element.getIntAttribute("tilewidth", 0);
			int tileheight = element.getIntAttribute("tileheight", 0);
			int spacing = element.getIntAttribute("spacing", 0);
			int margin = element.getIntAttribute("margin", 0);

			Element offset = element.getChildByName("tileoffset");
			int offsetX = 0;
			int offsetY = 0;
			if (offset != null) {
				offsetX = offset.getIntAttribute("x", 0);
				offsetY = offset.getIntAttribute("y", 0);
			}

			TiledMapTileSet tileSet = new TiledMapTileSet();

			// TileSet
			tileSet.setName(name);
			final MapProperties tileSetProperties = tileSet.getProperties();
			Element properties = element.getChildByName("properties");
			if (properties != null) {
				loadProperties(tileSetProperties, properties);
			}
			tileSetProperties.put("firstgid", firstgid);

			// Tiles
			Array<Element> tileElements = element.getChildrenByName("tile");

			addStaticTiles(tmxFile, imageResolver, tileSet, element, tileElements, name, firstgid, tilewidth, tileheight, spacing,
				margin, source, offsetX, offsetY, imageSource, imageWidth, imageHeight, image);

			for (Element tileElement : tileElements) {
				int localtid = tileElement.getIntAttribute("id", 0);
				TiledMapTile tile = tileSet.getTile(firstgid + localtid);
				if (tile != null) {
					addTileProperties(tile, tileElement);
					addTileObjectGroup(tile, tileElement);
					addAnimatedTile(tileSet, tile, tileElement, firstgid);
				}
			}

			map.getTileSets().addTileSet(tileSet);
		}
	}
```

the ```element ``` before this line ``` try {
					element = xml.parse(tsx);``` has an anttribute ```firstgid``` which value is 2, but after that line the element doesn't have the ```firstgid``` , so in the following line  ```int firstgid = element.getIntAttribute("firstgid", 1);``` the ```firstgid``` variable gets the 1 value instead of 2. 

So , i changed all 2's in my tmx to the 1, and it worked as expected. 

Could you please guys look into it before a stable release of the 1.9.10 version ?

Thanks a lot.

**Comment by TCreutzenberg** [comment]
Hey there, I will have a look but I'd need a little bit more information please.
- Are you using TmxMapLoader or AtlasTmxMapLoader? Or do you use a custom loader?
- Could you please post your original .tmx file (with the 2's)? I can understand the structure of the file  better then.

**Comment by TCreutzenberg** [comment]
The issue should be fixed with this pull request:
https://github.com/libgdx/libgdx/pull/5710
It worked fine when I was testing it.

**Comment by gagbaghdas** [comment]
@TCreutzenberg Hi. Thank you a lot.

**Comment by gagbaghdas** [comment]
BTW. When will be the 1.9.10 release guys?

**Comment by TCreutzenberg** [comment]
> BTW. When will be the 1.9.10 release guys?

I have no clue actually, I hope its coming soon.

**Comment by bachtrong43** [comment]
Just faced this issue. The line of code read firstgid should be moved to the first of the method because it is always 1.

**Comment by TCreutzenberg** [comment]
> Just faced this issue. The line of code read firstgid should be moved to the first of the method because it is always 1. In pull request, you moved all other like spacing,tilewidth,... to the first so you will get only 0 for these values because the external tileset element has only the source and firstgid.

Hey there @bachtrong43 , did I get something wrong?
In one of my .tmx files the tileset element looks like this:
<tileset columns="16" firstgid="1" name="default" tilecount="512" tileheight="30" tilewidth="30">
Actually tileheight, etc. are in the "tileset" element.
Can you please be more specific what is wrong in your opinion? Thank you!

**Comment by bachtrong43** [comment]
Hi @TCreutzenberg, because you used embeded tileset so your tileset infor is also embeded in tmx file. As you see above comment of @gagbaghdas, he used external shared tileset which is saved in tsx file so in tmx file, tileset element only has the source to tsx file and firstgid of this tileset. That is the reason we see the code parse infor after checking the source, but they forgot to read firstgid first.

**Comment by TCreutzenberg** [comment]
@bachtrong43 @gagbaghdas Hey guys, I'm super busy at the moment with various things, could you please create a new pull request that fixes your issues? You already know what's wrong and know how to fix it. That would really be great, thanks!

**Comment by bachtrong43** [comment]
@TCreutzenberg just created a new pull request.

**Comment by kdenzel** [comment]
I have the same Issue, it is really frustrating when you use multiple tilesets with different IDs. This will mess up your Map.
