### ISSUE TITLE
[Scene2D] clipBegin potential NullPointerException

### ISSUE THREAD

**Issue by obigu** [libgdx/libgdx#5711]
This may not be a bug but may be worth having a look (probably by @NathanSweet). Since https://github.com/libgdx/libgdx/commit/cd336d6b0deaecae629955290c910f88eacf8f3e I'm seeing very rare/infrequent crash reports:

```

Fatal Exception: java.lang.NullPointerExceptionAttempt to invoke virtual method 'void com.badlogic.gdx.g.a.h.a(com.badlogic.gdx.math.n, com.badlogic.gdx.math.n)' on a null object reference Raw Text
--
  | com.badlogic.gdx.scenes.scene2d.Actor.clipBegin + 818 (Actor.java:818)
  | com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.draw + 595 (ScrollPane.java:595)
  | com.badlogic.gdx.scenes.scene2d.Group.drawChildren + 123 (Group.java:123)
  | com.badlogic.gdx.scenes.scene2d.Group.draw + 57 (Group.java:57)
  | com.badlogic.gdx.scenes.scene2d.Group.drawChildren + 110 (Group.java:110)
  | com.badlogic.gdx.scenes.scene2d.Group.draw + 57 (Group.java:57)
  | com.badlogic.gdx.scenes.scene2d.Stage.draw + 128 (Stage.java:128)

```

which seems to indicate `stage` is `null` when executing the clipping (no idea how that's possible as this is executed under `Stage.draw`).

It may be my setup but, would it make sense to add a null check to `stage` on `Actor#clipBegin()` or stage Must be not null when calling `draw()` on an Actor?

#### Reproduction steps/code
Wasn't able to reproduce

#### Version of LibGDX and/or relevant dependencies
1.9.10-SNAPSHOT

**Comment by NathanSweet** [comment]
Stage null checks are a bit ugly, but it's the price we pay for not forcing actors to be tied to a specific stage. We already null check most of the stage access, so I suppose it's fine to check the few we don't. I would expect there to always be a stage in `draw`, unless someone wants to draw an actor without putting it in the stage for reasons (though they could put it in the stage, draw, then remove it). Other scenarios might be multi threading or removing the actor during `draw`, both of which should be avoided. It's not great that you don't have a reproduction case for the crashes you see.

Most actors are OK drawing without a stage except those that rely on clipping, which needs a stage to get the viewport for `calculateScissors`. Actors with that problem are any that call `clipBegin`, plus `SplitPane`. The best we can do if there is no stage is to skip clipped rendering (as if the clipping area was zero, eg return false from `clipBegin`). This isn't terribly useful but is probably better than crashing, doesn't impact existing code, and the ugliness it adds isn't too much, so I'm OK with it.

**Comment by obigu** [comment]
Just a heads up on thism I was able to reproduce the issue, it was a bug in my code. It was a multithreading issue caused when loading a game from the cloud.

**Comment by NathanSweet** [comment]
Ah well, doesn't hurt to be consistent with the stage null checks. Cheers!
