### ISSUE TITLE
Process freezes when put in the background on osx

### ISSUE THREAD

**Issue by Creeperface01** [libgdx/libgdx#5712]
#### Issue details
if I minimize the window or simply cover it with any other window then the program freezes and starts using 100% of CPU. If a few pixels of the window stay visible somewhere on the screen it won't happen, but when window completely disappear from the screen it starts. Tested on windows 10 and macOS Mojave 10.14.5 but this issue affects only macOS.

#### Reproduction steps/code
minimize a window, cover it with another one or simply switch to another desktop.

#### Version of LibGDX and/or relevant dependencies
1.9.9

#### Please select the affected platforms
- [x] MacOS

**Comment by MrStahlfelge** [comment]
For problems with desktop, it is important to know if you use Lwjgl2 or Lwjgl3.

**Comment by Creeperface01** [comment]
Lwjgl3

**Comment by Darkyenus** [comment]
I believe this was already mentioned in a different issue, it is caused by macOS's handling of Vsync of windows: it does not do any waiting when the surface is not visible.

**Comment by crykn** [comment]
This should no longer happen since glfw 3.3 (see [here](https://github.com/libgdx/libgdx/issues/3673#issuecomment-620511538)) and #6151 provides a setting to limit the fps manually.
