### ISSUE TITLE
Upgrade 1.9.8 to 1.9.9: only keyboard and scrolled event is triggered in input processor

### ISSUE THREAD

**Issue by klaus7** [libgdx/libgdx#5715]
#### Issue details
After upgrading from 1.9.8 to 1.9.9 (or 1.9.10 - doesn't matter) my input processor only retrieves keyboard events and the mouse `scrolled` event. No more mouse moved, touchDown, etc...

#### Reproduction steps/code
Can build a SSCCE later, but maybe something trivial happened in 1.9.9 I didn't notice?

#### Version of LibGDX and/or relevant dependencies

**LibGDX:** 1.9.9
**OS:** Ubuntu 18.04.2 LTS
**Backend:** gdx-backend-lwjgl

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [X] Linux
- [ ] MacOS

**Comment by Darkyenus** [comment]
In which backend?

**Comment by klaus7** [comment]
@Darkyenus Thank you for your question, I use LWJGL.

**Comment by Darkyenus** [comment]
Both backends use LWJGL. Do you use LWJGL2 or LWJGL3 backend?

**Comment by klaus7** [comment]
For the artifactId I use `gdx-backend-lwjgl` - I guess for LWJGL3 I'd have to use `gdx-backend-lwjgl3`. I will check if I can upgrade to LWJGL3 and if that solves the problem.

**Comment by klaus7** [comment]
Also no luck with LWJGL3. Same problem and a lot of additional graphics problems.

**Comment by MrStahlfelge** [comment]
I can say it is working for me on Ubuntu with Lwjgl2 and 1.9.10.

**Comment by MrStahlfelge** [comment]
Closed. Problem seems to be fixed in 1.9.10+
