### ISSUE TITLE
No Scrollbar inside Storybook 

### ISSUE THREAD

**Issue by qgfey0i2** [libgdx/libgdx#5717]
Describe the bug
i'm not getting scrollbar on the render side of the storybook

To Reproduce
[做澳洲文凭/办理澳洲硕士文凭【WX：jywenping】办理澳大利亚国立大学毕业证成绩单,制作ANU本科毕业证学位证,买硕士文凭,澳洲留信认证](www.diplomaclub.net) 

Load Storybook with content greater than the layout
Scrollbar won't show
Expected behavior
Scrollbar should appear if the content overflows the container

**Comment by NathanSweet** [comment]
Spam.
