### ISSUE TITLE
3d world coordiantes to screen coordinates returns wrong value

### ISSUE THREAD

**Issue by NasserTahani** [libgdx/libgdx#5726]
I have a simple project to render a 3D model (simple cube) using Perspective camera in android. The model is rendered fine but I need to get its coordinates on the device screen. Using project method of the perspective camera returns the wrong x value which is out of bounds of the viewport (2048*1536), but for the y value it works fine. How can I achieve the right x,y screen coordinate from 3d model?
```
Vector3 red_cube;
private void loadModel() {

	ModelInstance m1 = new ModelInstance(createPointModel(Color.RED));
	red_cube = new Vector3(516326, 423652, 1200);
	m1.transform.setToTranslation(node2);
	
	modelInstances.add(m1);
}

Vector3 loc = new new Vector3(516340, 423635, 1200);
Vector3 dir = new float[]{220, -80, 0};

@Override
public void render() {

	if (!isLoaded) {
		loadModel();
		isLoaded = true;
	}
	Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT | GL20.GL_DEPTH_BUFFER_BIT);
	Gdx.gl.glViewport(0, 0, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
	
	Vector3 v = camera.project(red_cube);
	Log.d("red_cube:", v.x + ", " + v.y);

	Vector3 pointing = OrientationSensorFusion.getDirection(dir);
	camera.position.set(loc);
	camera.direction.set(pointing);
	camera.update();
	
	modelBatch.begin(camera);
	modelBatch.render(modelInstances, environment);
	modelBatch.end();
	
}
```
The returned value by the project method is -2314.235, 767.8047.

**Comment by Tom-Ski** [comment]
Negative values are fine for screen coordinates. If you think there is a bug in core, please fill out the template as requested. That includes fully executable sample code, which this is not.

**Comment by NasserTahani** [comment]
The problem is not just the negative values. The absolute values are out of the x bounds for example I get 11400 on changing the camera's direction and the model placed in the left of the screen.

**Comment by Tom-Ski** [comment]
Values outside of screen 'bounds' are also fine.

**Comment by NasserTahani** [comment]
Thanks @Tom-Ski for quick reply. I think the projected coordinates for a model which is placed in the field of view of camera should be something in the range screen device. Please correct me if I'm wrong.

**Comment by Tom-Ski** [comment]
In theory, yes. the code you supplied does not suggest that, and wouldnt even compile into a test that others can run to verify the problem.  https://libgdx.badlogicgames.com/documentation/help/Issue%20Reporting.html

**Comment by NasserTahani** [comment]
Dear @Tom-Ski I've created a simplified version of my application which includes the problematic part. Regarding the project file size, I've included only the src folder of the Android project in the zip file. You can see the negative and out of bound values if you change the `orientationValues = new float[]{220, -80, 0};` in the Scene class. It would be gratefull if you could take a look at it. 
[src.zip](https://github.com/libgdx/libgdx/files/3439412/src.zip)

**Comment by Tom-Ski** [comment]
This does not fulfil what is required for reproducable code. I'm not going to spend time getting your project in some runnable state, and then debug code that is irrelevent to the issue.  

Please read the guides that i presented, specifically https://github.com/libgdx/libgdx/wiki/Getting-help#executable-example-code.

**Comment by NasserTahani** [comment]
You are right @Tom-Ski , but the complete version of the project is more than 10 MB which exceeds from the file uploading limitation in the issue page.

**Comment by Tom-Ski** [comment]
Im not requesting a complete project. As the links I provided you say, a single class is enough. AR has nothing to do with the problem, there is no need for 90% of the code in the thing you supplied. Write a single class that shows a model in 3d space, and uses project.

**Comment by NasserTahani** [comment]
Thanks again @Tom-Ski , I've included a simple and ready to run version of project to see the problem. 
[testLibgdx.zip](https://github.com/libgdx/libgdx/files/3487552/testLibgdx.zip)

**Comment by Tom-Ski** [comment]
Your test is _still_ not valid.

I changed the test to be conformant with what we require for issues, and there is no issue.
https://pix.asidik.com/tomski-wGxLyR.mp4

Updated valid test:
```

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application;
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.PerspectiveCamera;
import com.badlogic.gdx.graphics.VertexAttributes;
import com.badlogic.gdx.graphics.g3d.Environment;
import com.badlogic.gdx.graphics.g3d.Material;
import com.badlogic.gdx.graphics.g3d.Model;
import com.badlogic.gdx.graphics.g3d.ModelBatch;
import com.badlogic.gdx.graphics.g3d.ModelInstance;
import com.badlogic.gdx.graphics.g3d.attributes.ColorAttribute;
import com.badlogic.gdx.graphics.g3d.attributes.DirectionalLightsAttribute;
import com.badlogic.gdx.graphics.g3d.environment.DirectionalLight;
import com.badlogic.gdx.graphics.g3d.utils.FirstPersonCameraController;
import com.badlogic.gdx.graphics.g3d.utils.ModelBuilder;
import com.badlogic.gdx.math.Vector3;
import com.badlogic.gdx.utils.Array;

public class Scene extends ApplicationAdapter {

	PerspectiveCamera camera;

	ModelBatch modelBatch;
	Environment env;

	Vector3 redCubeTranslation = new Vector3();
	Array<ModelInstance> modelInstances = new Array<>();

	FirstPersonCameraController firstPersonCameraController;

	Vector3 temp = new Vector3();

	@Override
	public void create () {
		redCubeTranslation.set(10, 0, 10);

		cameraInit();
		modelBatch = new ModelBatch();


		loadModel();

		firstPersonCameraController = new FirstPersonCameraController(camera);
		Gdx.input.setInputProcessor(firstPersonCameraController);

		env = new Environment();
		env.set(new ColorAttribute(ColorAttribute.AmbientLight, 0.4f, 0.4f, 0.4f, 1f));
		env.add(new DirectionalLight().set(1f, 1f, 1f, 1, 1, 1));

	}


	private Model createPointModel (Color color) {
		Model pointModel;
		ModelBuilder modelBuilder = new ModelBuilder();
		int s = 1;
		Material material = new Material(ColorAttribute.createDiffuse(color));
		long attributes = VertexAttributes.Usage.Position | VertexAttributes.Usage.Normal;

		pointModel = modelBuilder.createBox(1f * s, 1f * s, 1f * s, material, attributes);
		return pointModel;
	}


	private void loadModel () {
		ModelInstance m1 = new ModelInstance(createPointModel(Color.RED));
		m1.transform.setToTranslation(redCubeTranslation);
		modelInstances.add(m1);
	}

	@Override
	public void render () {

		Gdx.gl.glClearColor(0.2f, 0.2f, 0.2f, 1f);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT | GL20.GL_DEPTH_BUFFER_BIT);
		Gdx.gl.glViewport(0, 0, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());

		temp.set(redCubeTranslation);
		camera.project(temp);
		System.out.println("Red cube screenspace position: "+ temp.x + "  " + temp.y + "  " + temp.z);


		firstPersonCameraController.update(Gdx.graphics.getDeltaTime());
		camera.update();

		modelBatch.begin(camera);
		modelBatch.render(modelInstances, env);
		modelBatch.end();
	}


	private void cameraInit () {

		camera = new PerspectiveCamera(67, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
		camera.near = 1f;
		camera.far = 500f;
		camera.update();

		camera.position.set(0, 0, 0);
		camera.lookAt(redCubeTranslation);
	}

	public static void main (String[] args) {
		Lwjgl3ApplicationConfiguration config = new Lwjgl3ApplicationConfiguration();
		config.setWindowedMode(1280, 720);
		new Lwjgl3Application(new Scene(), config);
	}

}

```

**Comment by harry-wilson** [comment]
I don't know why the test project is not valid, I've run it on Android Studio and it works fine. There are some differences with the code you supplied and my project. 

1. The camera position and direction will be updated in render() method, but the behavior is the same when the camera is fixed. 

1. I convert latitude and longitude of the model to x, y and z coordinates using proj4.j library which supplies big float values ( 5710000, -4250000, 1140). Considering this big values I've subtracted them with some values to make the result in the scale of (5032 and 3057). 

The others of your Scene class is the same as mine.

**Comment by harry-wilson** [comment]
@Tom-Ski I think your test code shed a light on me. I've set the translation of your _temp_ vector in the render method which previously was set in the _loadModel_ and seems works fine. But I get puzzled what's the difference between these two implementations.

**Comment by NasserTahani** [comment]
@Tom-Ski I think your test code shed a light on me. I've set the translation of your temp vector in the render method which previously was set in the loadModel and seems works fine. But I got puzzled what's the difference between these two implementations.
