### ISSUE TITLE
[Feature Request] Support for multiple keyboards at the same time

### ISSUE THREAD

**Issue by GrantOjanen** [libgdx/libgdx#5727]
#### Issue details
I'd like to have the ability in my games for the multiplayer to be playable with multiple keyboards. The Android APIs are setup really good for this. I don't know if this would work good on other platforms. I do know this is not possible on JavaScript.

#### Possible Setup

`InputProcessor.keyDown` and `InputProcessor.keyUp` could report a keyboard object in addition to the `keycode`. They keyboard object would have a deviceID and display name.

Their should be a way to get an array of all the connected keyboards.

There should also be a way to listen for when a keyboard is connected/disconnected.

#### Version of LibGDX and/or relevant dependencies
libGDX v1.9.9

**Comment by MrStahlfelge** [comment]
I would vote against this. It is not supported on any of the other platforms and a very niche feature request. To support this in your game, you should add your own event hook like the controller extension does.

**Comment by GrantOjanen** [comment]
I was hoping this would work on Lwjgl as well. I added this for Android to my [fork](https://github.com/GrantOjanen/libgdx) and will maintain it there. Now I'll need to add multi-mice support and capturing the cursor.
