### ISSUE TITLE
TmxMapLoader does not load correct

### ISSUE THREAD

**Issue by kdenzel** [libgdx/libgdx#5732]
I do not fully understand the Problem, but the behaviour in Version 1.9.8 of the TmxMapLoader changed. For some Reason, it loads my Tmx map incorrectly.

I also have animated Tiles in it which i created with the Editor Tiled. The Map and everything was loaded correctly in Version 1.9.8, even the animation was fine, but when i upgrade to 1.9.10, the Map is messed up. Some tiles are in the wrong position or the wrong tiles are shown. I don't know why, but it is a mess to see so i go with Version 1.9.8, where everything was fine.

`TmxMapLoader loader = new TmxMapLoader();
assetManager.setLoader(TiledMap.class, loader);
assetManager.load("levels/mymap.tmx", TiledMap.class);`

1.9.8 it worked
1.9.10 generates a mess

#### Stacktrace
no stacktrace

#### Please select the affected platforms
tested on Windows

**Comment by mgsx-dev** [comment]
PR #5722 might fix your issue

**Comment by kdenzel** [comment]
I got the Issue, i debuged the TmxMapLoader and there is a fatal Bug in it.
In the Meth
`protected` void loadTileSet (Element element, FileHandle tmxFile, ImageResolver imageResolver) {

**Comment by kdenzel** [comment]
Sorry my Mistake, so i got the issue: 
In `protected void loadTileSet (Element element, FileHandle tmxFile, ImageResolver imageResolver)`
there is this element Objekt. At first, it has the correct **firstgid**. Then in Line 555 this same Element Object becomes `element = xml.parse(tsx);`, at this moment it loses it's value for **firstgid**.

Because i use multiple tsx files in my tmx this is a big issue for me. Cause one tsx has the id 1 and the other the id 33. But the id 33 gets lost in line 577 'int firstgid = element.getIntAttribute("firstgid", 1);' cause the ***firstgid*** was lost and it defaults to 1.

Can someone pls witness this issue?

**Comment by Tom-Ski** [comment]
Did you read @mgsx-dev 's comment?

**Comment by kdenzel** [comment]
I did read it, but i don't know how this should help me. I tried to bring the solution branch into my project but i couldn't do it for some reason. Tried with "https://jitpack.io" to get this into my project but it failed. I wasn't able to manage it.

**Comment by Tom-Ski** [comment]
If that is describing the same issue as yours, then you should close this as its a duplicate. When that PR gets merged, you will be able to use that.

**Comment by kdenzel** [comment]
Okay thanks, yeah i rode that comment again, it seems like the same issue. I will use 1.9.8 of libgdx till this issue in 1.9.10 is fixed.
