### ISSUE TITLE
Label should take the background in LabelStyle to compute the prefSize

### ISSUE THREAD

**Issue by bachtrong43** [libgdx/libgdx#5736]
As above title, currently it's ok if the LabelStyle.background minSize smaller than the Label size. But when the LabelStyle.background minSize larger than the Label size, it will stretch the background. It is inconvenient if you want to create a Label is inside a large background, you have to create a layout like Table, setBackground to it and add Label.

**Comment by NathanSweet** [comment]
It seems Label already does this, eg:
https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/Label.java#L239
Closing for now, but please show what code changes you propose and we can reopen.

**Comment by bachtrong43** [comment]
It's incorrect. For example: the circle background has size 100x100 and label size 20x50 so the result is background stretch to 20x50. The code should be:
```java 
if (background != null) { 
width += background.getLeftWidth() + background.getRightWidth();
width = Math.max(width, background.getMinWidth());
```
Similar to height. Sorry for the format, I used mobile to comment.
