### ISSUE TITLE
crash when loading an animated map

### ISSUE THREAD

**Issue by electronstudio** [libgdx/libgdx#5744]
#### Issue details
GDX attempts to cast from AnimatedTiledMapTile to StaticTiledMapTile which causes an exception.

#### Reproduction steps/code
Load a map with animated tiles.

#### Version of LibGDX and/or relevant dependencies
1.9.10

#### Stacktrace
```java
Exception in thread "main" java.lang.ClassCastException: com.badlogic.gdx.maps.tiled.tiles.AnimatedTiledMapTile cannot be cast to com.badlogic.gdx.maps.tiled.tiles.StaticTiledMapTile
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.addAnimatedTile(BaseTmxMapLoader.java:656)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadTileSet(BaseTmxMapLoader.java:614)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadTiledMap(BaseTmxMapLoader.java:156)
	at com.badlogic.gdx.maps.tiled.TmxMapLoader.load(TmxMapLoader.java:81)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
Please post everything required to reproduce the issue. https://github.com/libgdx/libgdx/wiki/Getting-Help

**Comment by electronstudio** [comment]
To reproduce the issue you just need your game to load an animated map.  Sorry I can't post the source of my game.  But you can check the source code of LibGDX, it's doing an illegal type cast from AnimatedTiledMapTile to StaticTiledMapTile.  It worked fine in 1.9.9 with the same map so it's something that was introduced in 1.9.10.

```
BaseTmxMapLoader.java:656:
    staticTiles.add((StaticTiledMapTile)tileSet.getTile(firstgid + frameElement.getIntAttribute("tileid")));
```

**Comment by electronstudio** [comment]
Here is a minimal complete project that contains everything required to reproduce the issue:

https://github.com/electronstudio/GDX-map-test

**Comment by mgsx-dev** [comment]
i can reproduce it, i'm working on a fix.

**Comment by kennycason** [comment]
@mgsx-dev Thanks for the update. Sorry for not being familiar with the LibGDX release cycle, but is this released yet in 1.9.10? Or is there at "latest branch". I recently updated LibGDX to 1.9.10 and am having the same issue with all my maps. Thanks.

**Comment by mgsx-dev** [comment]
@kennycason it's only on master branch for now, you can use libgdx "1.9.11-SNAPSHOT" to have the fix.

**Comment by electronstudio** [comment]
Since 1.9.10 shipped with this major regression and it hasn't been fixed in a release I'm assuming 1.19.10 was some sort of 'unstable' release.  What is the next 'stable' release going to be that will be safe to upgrade to?

**Comment by MrStahlfelge** [comment]
Looks like it depends of the features you use what version is 'stable' or 'unstable'. For me, 1.9.9 was unstable and 1.9.10 is stable.

**Comment by electronstudio** [comment]
Then I guess what’s needed is an ‘Ubuntu LTS’ style branch that only receives bug fixes and no new features or regressions.
