### ISSUE TITLE
Neverending blinkTask in TextField

### ISSUE THREAD

**Issue by rojekabc** [libgdx/libgdx#5746]
#### Issue details
I'm using simple Stage, which contains TextField. I'm using non-continuous rendering. There's a blinkTask created for TextField, which is responsible for cursor blinking. When I close a stage (with dispose call) with focus on TextField, than blinkTask is not canceled. In new stage requestRender is still called.

**Workaround**
I saw, that cancel of this task is done, when you redraw field. Workaround is to unfocusAll + draw stage before dispose to disable this blinkTask.

**Proposed solution**
I'm not familiar with your code, but I suppose, that end() or clear() action of Actor should be overwritten and blinkTask.cancel() should be there.

#### Reproduction steps/code
Switch to non-continuous rendering.
Create stage.
Add actor TextField and Button.
Focus TextField (cursor is blinking).
On button click dispose stage and switch to another one (empty) and log every update.
Update shouldn't be done, but it's.

#### Version of LibGDX and/or relevant dependencies
1.9.9

#### Stacktrace
No stacktrace.

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [ ] MacOS
Those two verified, but I suppose it's on all of them.

**Comment by NathanSweet** [comment]
Note it's generally unnecessary to dispose the stage. Typically applications have one stage and use it for everything. In some cases an app may use two stages which have different viewports (eg a screen viewport for the UI, and a game world viewport for using stage for the actual game).
