### ISSUE TITLE
Incorrect resizing whilst discontinuous rendering

### ISSUE THREAD

**Issue by BinoManjesh** [libgdx/libgdx#5747]
# Issue details

The screen doesn't always update when resized if you set Gdx.setContinuousRendering(true); Works fine in the android backend but occasionally fails in the desktop backend. In the desktop  backend, it works every time the full screen button is pressed but doesn't always work if the screen is dragged. I only tested it on windows. 

# Reproduction / steps
Add :
`Gdx.graphics.setContinuousRendering(false);`
 at the create method

Exact code:-
```
package com.company.test;

import com.badlogic.gdx.Game;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.glutils.ShapeRenderer;
import com.badlogic.gdx.utils.viewport.FitViewport;
import com.badlogic.gdx.utils.viewport.Viewport;

class TestGame extends Game {
	
	private Viewport viewport;
	private ShapeRenderer renderer;
	
	@Override
	public void create() {
		viewport = new FitViewport(1, 1);
		renderer = new ShapeRenderer();
		Gdx.graphics.setContinuousRendering(false);
	}
	
	@Override
	public void resize(int width, int height) {
		viewport.update(width, height, true);
	}
	
	@Override
	public void render() {
		Gdx.gl.glClearColor(1, 1, 1, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		
		viewport.apply();
		renderer.setProjectionMatrix(viewport.getCamera().combined);
		
		renderer.begin(ShapeRenderer.ShapeType.Filled);
		renderer.setColor(Color.BLACK);
		renderer.rect(0, 0, 1, 1);
		renderer.end();
	}
}
```

- [x] Windows

**Comment by EtK2000** [comment]
Please supply code or a gif or something so we can see the problem in action for ourselves.

**Comment by NathanSweet** [comment]
I added to the above (LWJGL2 backend):
```
Then in LwjglApplication I added these printlns:
```
System.out.println("w " + Display.getWidth() );
if (graphics.resize || Display.wasResized()
	|| (int)(Display.getWidth() * Display.getPixelScaleFactor()) != graphics.config.width
	|| (int)(Display.getHeight() * Display.getPixelScaleFactor()) != graphics.config.height) {
	System.out.println("resized " + Display.getWidth() );
```
I see eg:
```
w 754
w 754
w 754
<I resize the window smaller, without mousing over the window>
w 754
w 754
w 754
w 754
<I mouse over the window>
w 646
resized 646
w 646
w 646
```
It seems that LWJGL2 doesn't give us the correct window size, nor does `Display.wasResized()` return true. It's either an LWJGL2 bug, or there is some different way we can use the LWJGL2 API to get what we want.

**Comment by crykn** [comment]
This seems to be an issue with LWJGL2 itself, which is no longer updated. Closing this.
