### ISSUE TITLE
Can't generate eclipse .project file

### ISSUE THREAD

**Issue by mokun** [libgdx/libgdx#5751]
#### Issue details

BUILD FAILED. Can't generate eclipse .project file

#### Reproduction steps/code

1. Run gdx-setup.jar 
2. Click on "Advanced" button
3. Check the Eclipse box.

#### Version of LibGDX and/or relevant dependencies

1.9.10 supposedly

#### Stacktrace

The following shows up in the text box :

> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Task 'eclipse' not found in root project 'MarsWorld'.
> 

#### Please select the affected platforms
- [x ] Android
- [x ] iOS
- [x ] HTML/GWT
- [x ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by mgsx-dev** [comment]
This is no longer an issue, Eclipse checkbox was removed in this commit : f4d60a94f073c337ba1ff9c16d169368581c4ab8. Importing into eclipse as gradle project is the only option now.
