### ISSUE TITLE
Empty Sprite with setRegion doesn't draw

### ISSUE THREAD

**Issue by danbraik** [libgdx/libgdx#5754]
Please ensure you have given all the following requested information in your report.

#### Issue details
When creating a fresh sprite without texture from the begining it will not draw even after setting a texture. To fix that , one way is to set the size once.
I think it is surprising behavior but is good for performance. Maybe it would be interesting to explicit that in the documentation.

#### Reproduction steps/code
```java
Sprite sp = new Sprite();   // no texture
sp.setRegion(new TextureRegion(myTex)); // set the region (from an animation in my case)
sp.draw(batch); // won't draw anythning
```
One way to fix that is:
```java
sp.setSize(10, 10); // or set to region size
// draw here
```

Thank you !

#### Version of LibGDX and/or relevant dependencies
libgdx 1.9.9

#### Please select the affected platforms
- [X ] Android

**Comment by Tom-Ski** [comment]
Using the empty constructor for Sprite doesn't just mean no texture, it also means no geometry as the documentation states.
`/** Creates an uninitialized sprite. The sprite will need a texture region and bounds set before it can be drawn. */`

**Comment by danbraik** [comment]
thank you ! ;)
