### ISSUE TITLE
Drawing example image crashes on Android 2.3.3

### ISSUE THREAD

**Issue by yerAWeeGit** [libgdx/libgdx#5755]
Please ensure you have given all the following requested information in your report.

#### Issue details
Pretty much the title. With the example script `gdx-setup.jar` produces, if `batch.draw(img, 0, 0);` is commented out, the app does not crash.

#### Reproduction steps/code
Import the example produced by `gdx-setup.jar` into Android Studio and run the app on a device with Android Froyo or Gingerbread. The issue is specifically occurring on the GT-S5830 with the latest stock ROM (rooted but otherwise unmodified). This issue does not occur using the same device with Android 4.2.2 (custom ROM).

#### Version of LibGDX and/or relevant dependencies
- LibGDX 1.9.10
- Android Studio 3.4.2
- Gradle 5.4.1
- SDK 29.0.2

#### Stacktrace
```java
09-09 15:19:55.649 2301-2309/my.app E/AndroidRuntime: FATAL EXCEPTION: GLThread 10
    java.lang.UnsupportedOperationException: glBlendFuncSeparate
        at android.opengl.GLES20.glBlendFuncSeparate(Native Method)
        at com.badlogic.gdx.backends.android.AndroidGL20.glBlendFuncSeparate(AndroidGL20.java:76)
        at com.badlogic.gdx.graphics.g2d.SpriteBatch.flush(SpriteBatch.java:970)
        at com.badlogic.gdx.graphics.g2d.SpriteBatch.end(SpriteBatch.java:185)
        at my.app.MyApp.render(MyApp.java:27)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:494)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1388)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1138)
09-09 15:19:59.849 2301-2301/my.app E/AndroidGraphics: waiting for pause synchronization took too long; assuming deadlock and killing
```

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by intrigus** [comment]
Is this a new issue, i.e. did this work in a prior gdx version?

**Comment by Anuken** [comment]
This is probably caused by the recent changes involving JNI removal, and subsequent use of `android.opengl.GLES20`. Some searching around has suggested that many blend function methods just aren't supported at API levels < 10.

In my opinion, libGDX should just raise its minimum API level up to 10, since [that version consitutes less than 0.3% of the market share.](https://developer.android.com/about/dashboards)

**Comment by obigu** [comment]
Less than 0.1% actually (`Any versions with less than 0.1% distribution are not shown.`)

**Comment by MobiDevelop** [comment]
Could probably make the minimum API 19 without any noticeable loss of userbase. I'd be interested to see what people are actually specifying in their manifests.

**Comment by MrStahlfelge** [comment]
I'm on 16 at the moment, but I wouldn't mind to raise to 19. However, in my opinion we shouldn't go below 14 with the framework if it is not really necessary.

**Comment by Anuken** [comment]
I use API 14; is there anything new in levels 15-19 that would make developing libGDX cleaner or easier?

**Comment by Tom-Ski** [comment]
No, not really.

**Comment by yerAWeeGit** [comment]
I'm not sure if this is a new issue as I haven't used LibGDX for Android development before. I'll see if I can find some older versions to try, though I'm not going to break my back for Gingerbread users (who would have to sideload my app anyway).

I think bumping up the API level required by LibGDX to 19 as mentioned above would be a bit much. I think continuing to support level 16 if feasible would be a good idea, since 3.2% of users are still on 16 to 18, which isn't nothing.

**Comment by Anuken** [comment]
Unless there's a good reason for it, I don't think the minimum API level should be raised past the range of 10-14. No sense unnecessarily excluding devices.

**Comment by MobiDevelop** [comment]
The minimum minimum for modern Android should be 14, so we should probably at least bump to that.

**Comment by yerAWeeGit** [comment]
@Anuken Just so we're clear, this is API level 10 that it's not working on, so if this is a problem that won't be fixed it would have to be raised to at least 11.

**Comment by PokeMMO** [comment]
> I use API 14; is there anything new in levels 15-19 that would make developing libGDX cleaner or easier?

There's various small bits here and there which would be able to be simplified/cleaned up. Such as the two GlSurfaceView classes.

https://github.com/libgdx/libgdx/blob/12e8b0c2d1a02f913b00b9698abd9129b4545f56/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGraphics.java#L142-L152

**Comment by noblemaster** [comment]
The https://github.com/libgdx/libgdx/pull/5787 pull request updates the minSDK to 14 as proposed here. Let's consider this closed. Thanks everyone for feedback! :)
