### ISSUE TITLE
Pixmap wrong dimensions pixels.put

### ISSUE THREAD

**Issue by feresr** [libgdx/libgdx#5761]
#### Issue details
Trying out LibGdx for the first time, playing around with it came across something weird

```

class Game : ApplicationAdapter() {
    lateinit var batch: SpriteBatch
    lateinit var img: Texture
    private lateinit var pixmap: Pixmap

    override fun create() {
        batch = SpriteBatch()
        pixmap = Pixmap(100, 100, Pixmap.Format.RGBA4444)
        for (i in 0 until (pixmap.height * pixmap.width * 2)) {
            pixmap.pixels.put(i, (0b0000111100001111).toByte())
        }
        img = Texture(pixmap)
    }

    override fun render() {
        Gdx.gl.glClearColor(0f, 0f, 0f, 1f)
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT)
        batch.begin()
        batch.draw(img, 0f, 0f)
        batch.end()
    }

    override fun dispose() { ... }
}

```

This draws a green square in the bottom left corner, as expected. But notice the ` * 2` in the `for` condition. 
Why is this needed? If I remove it, it'll only paint the top half of the square.

**Comment by mgsx-dev** [comment]
I think this is because your code is wrong, it should be something like :

```
        for (i in 0 until (pixmap.height * pixmap.width)) {
            pixmap.pixels.put(i * 2, (0b0000111100001111).toByte())
        }
```
You could notice it with a different color (different bits for each color components), eg. 0xA62F.

I think you can close this issue.

Feel free to use [community channels](https://libgdx.badlogicgames.com/community.html) if you have more questions about it.

**Comment by feresr** [comment]
> I think this is because your code is wrong
hah! it's very likely

I realized my mistake minutes after posting this, facepalm.
in the JVM 1 byte = 8 bits

Closing
