### ISSUE TITLE
Cordova plugins

### ISSUE THREAD

**Issue by cellcrowd** [libgdx/libgdx#5774]
While refactoring my app from Cordova to Libgdx, I'm having a hard time finding an exhaustive Firebase implementation, specifically for FCM.

https://github.com/mk-5/gdx-fireapp seems to be the most complete, but it's still in active development. For Cordova, I was using https://github.com/arnesson/cordova-plugin-firebase which has all the functionality I need.

This lead to my thinking of somehow creating a bridge between Libgdx and Cordova plugins. As far as I can tell, being standalone, they only need an application context so some kind of intermediate class that provides this context alongside an interface to libgdx might be enough to get them to work.

What do you guys think of this and is this even possible, considering the IOS counterparts of Cordova plugins are written in Objective-C instead of Java?

I think this would allow for a lot of extra features to libgdx apps as there are tons of plugins already, for different platforms: https://cordova.apache.org/plugins/

#### Please select the affected platforms
- [x] Android
- [x] iOS (robovm)
- [x] iOS (MOE)
- [x] HTML/GWT
- [x] Windows
- [ ] Linux
- [x] MacOS

**Comment by mgsx-dev** [comment]
better using firebase REST API, libgdx provides all you need to call any REST API.

**Comment by cellcrowd** [comment]
I am using the REST API to send notifications from my server, however on the client this plugin leverages the Firebase SDK to handle the incoming notifications, adding them to the notification bar, controlling the led, updating icon badges, etc.

**Comment by Tom-Ski** [comment]
Not something this project will take on, and is more fit for an external extension if someone wanted to. 

Typically you create cross platform compatible libraries, such as the one you linked, either outside of your project as some library, or inside as cross platform compatible code via interfaces as demonstrated in simple case here https://github.com/libgdx/libgdx/wiki/Interfacing-with-platform-specific-code.
