### ISSUE TITLE
Android 10 SoundPool bad performance

### ISSUE THREAD

**Issue by obigu** [libgdx/libgdx#5786]
On Android 10 (current build) playing multiple sounds may cause fps drops. Same apps that run smooth on previous Android versions lag heavily on Android 10.

The issue can be easily reproduced with this test on libGDX
https://pastebin.com/i8Hbv073

I'm pretty sure the issue is not on libGDX side but on Android. I've created the following issue on Android issue tracker which includes the same test wrapped as native Android app. https://issuetracker.google.com/issues/140579743.

No workaround has been found yet.

Affected versions and platforms:
Android 10
libGDX 1.9.10

**Comment by Anuken** [comment]
Can confirm that this is a real issue; many users on Android 10 have reported massive sound lag that disappears when sound is disabled.

**Comment by Tom-Ski** [comment]
https://issuetracker.google.com/issues/140579743
Marked as fixed, so closing this one out.
