### ISSUE TITLE
Strange text wrapping bug

### ISSUE THREAD

**Issue by TechlingerHons** [libgdx/libgdx#5794]
Hello!

There is a wrapping issue at libgdx verion 1.9.10. 

I set the label like this:

```
Label label = new Label()
label.setWrap(true)
label.setWidth(800)
label.setText("Automatisch aufgeben")
label.layout()
h = label.getPrefHeight()
label.setHeight(h)
```

Although there is enough space left, the text gets wrapped around the character "h". Also, the label.getPrefHeight() is wrong. (Screenshot 1) 

Very strange is that it works if I use the text "Automatische aufgeben". (Screenshot 2) 

Please help! :) 

![Screenshot 2019-09-13 at 18 02 27](https://user-images.githubusercontent.com/26793571/64906640-3798de00-d6e9-11e9-9e8a-d77f7a5b31b5.png)

**Comment by TechlingerHons** [comment]
Here is a project reproducing the bug:
https://github.com/TechlingerHons/wrap_bug

**Comment by Tom-Ski** [comment]
Seems to be caused by the scaling of the font that you are doing. Perhaps wrap is not taking this into account.

**Comment by MrStahlfelge** [comment]
Use .setFontScale on  the Label instead.
