### ISSUE TITLE
[Android] Loading of natives in static intializer makes it impossible to gracefully handle missing native libs

### ISSUE THREAD

**Issue by 00-Evan** [libgdx/libgdx#5795]
#### Issue details
Because GdxNativesLoader.load() is called in the static initializer of AndroidApplication, it's not possible to run any code before it. This means that if native libs are not present the app immediately crashes, with no way to check for missing natives and handle the situation more gracefully (such as by displaying an error popup and closing the app).

This is an issue because of Google's new app bundle functionality on Google Play. When app bundles are used, Google Play only distributes necessary resources to each device, including natives. This results in some nice space savings, but it also makes it very easy for someone to sideload the wrong APK and not get the natives they need.

I would think a better approach would be to load native libs in AndroidApplication.onCreate. This way code to check native libs could be run before calling super.onCreate. LibGDX could even perform the checking itself and display a standard error message, which a developer could then customize/override by manually checking earlier. This is much preferable to crashing as it won't affect an application's stability statistics on Google Play, and gives an opportunity to direct users to an APK which would work for them.

I'm not very familiar with the LibGDX codebase, so it's possible I'm missing something here, but if there is agreement that moving native initialization to AndroidApplication.onCreate is a good idea I'd be happy to submit a pull request.

#### Reproduction steps/code
Can be reproduced in any libgdx android project by simply removing native libraries and commenting out native dependencies in build.gradle

#### Version of LibGDX and/or relevant dependencies
Tested on 1.9.10 but should affect all versions.

#### Stacktrace
(Example stack trace from a user crash on my game: [Shattered Pixel Dungeon](https://github.com/00-Evan/shattered-pixel-dungeon))
```java
java.lang.ExceptionInInitializerError: 
  at java.lang.Class.newInstance (Class.java)
  at android.app.AppComponentFactory.instantiateActivity (AppComponentFactory.java:69)
  at androidx.core.app.CoreComponentFactory.instantiateActivity (CoreComponentFactory.java:43)
  at android.app.Instrumentation.newActivity (Instrumentation.java:1215)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3008)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3257)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:78)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1948)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7050)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: 
  at com.badlogic.gdx.utils.SharedLibraryLoader.load (SharedLibraryLoader.java:125)
  at com.badlogic.gdx.utils.GdxNativesLoader.load (GdxNativesLoader.java:33)
  at com.badlogic.gdx.backends.android.AndroidApplication.<clinit> (AndroidApplication.java:60)
  at java.lang.Class.newInstance (Class.java)
  at android.app.AppComponentFactory.instantiateActivity (AppComponentFactory.java:69)
  at androidx.core.app.CoreComponentFactory.instantiateActivity (CoreComponentFactory.java:43)
  at android.app.Instrumentation.newActivity (Instrumentation.java:1215)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3008)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3257)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:78)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1948)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7050)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)
Caused by: java.lang.UnsatisfiedLinkError: 
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1012)
  at java.lang.System.loadLibrary (System.java:1669)
  at com.badlogic.gdx.utils.SharedLibraryLoader.load (SharedLibraryLoader.java:119)
  at com.badlogic.gdx.utils.GdxNativesLoader.load (GdxNativesLoader.java:33)
  at com.badlogic.gdx.backends.android.AndroidApplication.<clinit> (AndroidApplication.java:60)
  at java.lang.Class.newInstance (Class.java)
  at android.app.AppComponentFactory.instantiateActivity (AppComponentFactory.java:69)
  at androidx.core.app.CoreComponentFactory.instantiateActivity (CoreComponentFactory.java:43)
  at android.app.Instrumentation.newActivity (Instrumentation.java:1215)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3008)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3257)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:78)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1948)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7050)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)
```

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by yuripourre** [comment]
As a workaround you can publish your app as .obb instead of .apk. It also reduces the app size to users.

**Comment by 00-Evan** [comment]
I've ended up working around this a bit with a separate activity in my project: https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/android/src/main/java/com/shatteredpixel/shatteredpixeldungeon/android/AndroidLauncher.java

Basically AndroidLauncher is now a vanilla android Activity which loads natives, launches AndroidGame (which extends AndroidApplication), and finishes. If an exception occurs it displays a text view with an error message instead.

**Comment by MrStahlfelge** [comment]
I think this request is very niche. The way the natives are loaded is not perfect, but changing a well-tested system is always dangerous. When someone downloads apks fetched from the Play Store to sideload them, the one should have enough knowledge to use the correct version or to check logcat and understand the problem. 
If you expect users not using the Play Store, I would recommend offering a universal apk on itch, GameJolt or your website for these people to use.

**Comment by 00-Evan** [comment]
Just to make a case for why this is less niche than you might think, based on my own use-case:

Shattered Pixel Dungeon is played by a large number of people both on Google Play and via direct universal APK download (github, F-droid, etc.). Upon switching to android app bundles there was a large uptick in crashes reported via Google Play and in negative user reviews stating that the game immediately crashed on launch on their devices. Because many 3rd party APK services repackage the Google play version without permission (and even spoof installing the game through Google Play), Google can't always tell the difference and so these crashes and negative reviews appear to be from regular users who downloaded the game through Google Play. Switching to the approach I'm using currently (warning message instead of crash) resolved both of these issues immediately. 

Additionally Android App Bundles are becoming mandatory for new apps on Google Play in the 2nd half of 2021, and Google not only [recognizes this as a known issue](https://developer.android.com/guide/app-bundle#known_issues) (See first bullet point), but also [provides functionality to try and address this via the play core library.](https://developer.android.com/reference/com/google/android/play/core/release-notes#1-6-0)

**Comment by MrStahlfelge** [comment]
Yep, you are right about that. The interesting question here is: do you want to take the time to change the current process and submit a PR, or do you recommend to use your second activity workaround?

**Comment by 00-Evan** [comment]
I don't have the time to work on a PR right now but I'd be happy to give it a shot soon. The second activity workaround is only there out of necessity at the moment, and I'd definitely prefer to just let it be handled through LibGDX's existing structure if possible.

I'll give the structure some thought but two questions pop up to me immediately:
- Should libgdx load natives in init, or onCreate (which currently isn't being overridden in AndroidApplication)?
- Should the default behavior be to crash with an exception, or should LibGDX try to handle things more gracefully and display some sort of message to the user?

If we want to crash it might be best to put the logic in onCreate as that should happen before almost any other code, and an implementer can stick super.onCreate in a try block and put their own logic in the catch. Otherwise putting things in init might make more sense as that means we can ensure that the application won't continue and subsequently crash. To preserve customization options LibGDX's own handling of the crash could be put in a method that could be overridden.

It's also worth noting that if an implementer does do something that uses natives in their own onCreate, they can always call GdxNativesLoader.load() on their own.

**Comment by MrStahlfelge** [comment]
My opinion on your questions:

> Should libgdx load natives in init, or onCreate (which currently isn't being overridden in AndroidApplication)?
That doesn't matter in my opinion, as long as (existing) game code needs no change.

> Should the default behavior be to crash with an exception, or should LibGDX try to handle things more gracefully and display some sort of message to the user?
Catchable crash with an exception, but a good message in logcat.

**Comment by 00-Evan** [comment]
(Oh my god I'm actually working on this now. Sorry for taking almost an entire year.)

I've done a bit of experimenting with this and have some more to go on now.

> Should libgdx load natives in init, or onCreate (which currently isn't being overridden in AndroidApplication)?

It seems to make the most sense to load natives right at the start of the the initialize methods, this is consistent with when they're loaded in the LWJGL backends, and avoids adding another method to AndroidApplication. I've done some basic tests with my own app and (if natives are loaded successfully) this results in no changes to behavior.

It is possible this might cause problems for any Android libGDX apps out there that do something that depends on natives in onCreate, But that seems extremely unlikely, and even in that case there's a simple fix of just calling the natives loader yourself.

The only main issue is the 'gracefully' part of this, so I wanted your input one more time @MrStahlfelge . With this change It's totally possible to surround initialize with a try-catch and handle the exception yourself, but the rest of init isn't called. Unless you immediately crash or finish the activity yourself, onResume() and onPause() can get called, and immediately crash due to variables like input and graphics being null.

I think there are two options here, one is to add some null checks to onResume() and onPause() so they're a bit more robust and don't crash in these cases (perhaps have them immediately call super and return if graphics is null?), or the developer should be expected to finish the libGDX activity if they don't want to crash. From my tests it is possible to immediately call finish and launch another activity which displays an error message to the user.

**Comment by MrStahlfelge** [comment]
You can't use the activity anyway and should display a second one with an explanation or download link to the user anyway, so I think that the null-checks aren't really needed.

> It is possible this might cause problems for any Android libGDX apps out there that do something that depends on natives in onCreate, But that seems extremely unlikely

I also think so.

**Comment by 00-Evan** [comment]
You can use Android UI classes (e.g. textview or alertdialog) to display errors in the libGDX activity just the same as a separate one. It's probably a bad idea to expect the libGDX classes to gracefully handle cases where initialization fails either way though. Will just move loading to init with no other changes and submit a pull request soon.

**Comment by obigu** [comment]
I don't think the risk/reward ratio is worth it in this case.

I'm curious about the following:

>Because many 3rd party APK services repackage the Google play version without permission (and even spoof installing the game through Google Play), Google can't always tell the difference and so these crashes and negative reviews appear to be from regular users who downloaded the game through Google Play. Switching to the approach I'm using currently (warning message instead of crash) resolved both of these issues immediately.

For Google to believe it has been downloaded from Google Play when in reality it has not, wouldn't that require deliberate APK manipulation to somehow mess with the `PackageManager`? It's probably possible to somehow bypass the check but, if somebody is manipulating the APK in such a way, I don't think we need to take care on how it crashes. In my experience, in the crash console I see many more crashes from apps downloaded from 3rd parties than from Google Play but that's ok as only the ones from Google Play are taken into account for the "Bad Behaviour" threshold.

**Comment by 00-Evan** [comment]
Afraid I don't have any proof or knowledge of the exact mechanisms, that comment I made was mainly from my own experience. After switching to App Bundles I observed these changes to user feedback:

- A significant number of people were leaving 1 star reviews claiming the app crashed on launch after the latest update. Obviously they could have gotten the crash elsewhere but it would seem weird to then install the app via GPlay just to leave a 1 star review and not even test it.
- More convincingly, these crashes were showing up in my play console as crashes from Google Play users. I have no idea how this occurs but they were impacting my performance metrics. It's much rarer but even now I see installation-related crashes that are apparently from Google Play devices (missing assets, etc).

After switching to an error message instead of a crash, the crashes and 1 star reviews immediately stopped. For a couple weeks I even got a good number of emails from users who admitted to using APK rehosters and who asked me how to get a working version.

Admittedly this was 2 years ago now so it's possible that the landscape has changed regarding this.

**Comment by obigu** [comment]
Interesting, thanks.

To be honest, with what we know, I feel that breaking backwards compatibility and risking issues on standard users just to bring a graceful failure to corner case users (such as the ones using APK rehosters to download the app) is not worth it IMO.

**Comment by tommyettinger** [comment]
Hm, does anything in https://github.com/libgdx/libgdx/pull/6590/files break backwards compatibility? I normally think of dependence on static initializer order as a potentially serious issue, so having initialization happen at a defined point in the application startup rather than an undefined one seems good. (Yes, static initialization happens in an undefined order if multiple classes have static init blocks, and yes, this has bitten me before.)

**Comment by obigu** [comment]
Not saying it's probable but it may, yeah, apps may have assumed natives were already loaded before `onCreate()` was called.

I don't like the static initialization either (even if it's how it's done on many examples online), but my point is that it's been like this for a long time and it works without known issues. We don't know if loading it on `onCreate()` may cause issues in some scenarios and when I evaluate the pros and cons of a change in such a key part of the framework, the risks outweight the benefits.

**Comment by 00-Evan** [comment]
It is worth noting that the possible app that does need natives in onCreate() can always just load natives itself within that method. This is basically what Shattered Pixel Dungeon does currently in a separate activity in order to test if natives are missing in an environment where it can catch an exception. Perhaps something could be added to CHANGES to highlight this for anyone it might affect?

**Comment by MrStahlfelge** [comment]
* We have a problem here
* We have code that we know is not good here
* We have no backwards compatiblity break for any games that doesn't tweak special parts of the Android implementation, so I would state there is no breaking change

Hence I think we should make a change and not switch to "never change a running system" mode just because changes might introduce new problems. If we know the static initializers are a problem, that should be changed. If the change introduces new problems, then it should be changed again.

**Comment by MrStahlfelge** [comment]
After discussion on the team, we decided together to merge the change but flag it with "Breaking change" label on the CHANGES file to make sure no one misses the change.
