### ISSUE TITLE
Shaders not working on Android

### ISSUE THREAD

**Issue by TheChocolateOre** [libgdx/libgdx#5796]
#### Issue details
I created a new project with the gdx-setup. After that, I created a pass through vertex shader and a simple fragment shader for negative color. I used ShaderProgram in the default code generated from the gdx-setup and applied the shader on the batch. The desktop application works as expected. The color of every pixel is replaced with its negative. When I run the same application on the android, I only get the background(clear) color, not its negative and also the libGDX logo at the bottom left is missing.
The same happens with other fragment shaders too, even with pass through fragments.

#### Reproduction steps/code
```java
@Override
public void create () {
	batch = new SpriteBatch();
	img = new Texture("badlogic.jpg");

	ShaderProgram.pedantic = false;
	this.shader = new ShaderProgram(Gdx.files.internal("shaders/passthroughV.glsl"),
			Gdx.files.internal("shaders/negativeF.glsl"));
	batch.setShader(this.shader);
}
```

```java
@Override
public void render () {
	Gdx.gl.glClearColor(1, 0, 0, 1);
	Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

	batch.begin();
	batch.draw(img, 0, 0);
	batch.end();
}
```

Vertext:
```glsl
attribute vec4 a_color;
attribute vec3 a_position;
attribute vec2 a_texCoord0;

uniform mat4 u_projTrans;

varying vec4 v_color;
varying vec2 v_texCoord0;

void main() {
    v_color = a_color;
    v_texCoord0 = a_texCoord0;
    gl_Position = u_projTrans * vec4(a_position, 1.0);
}
```

Fragment:
```glsl
varying vec4 v_color;
varying vec2 v_texCoord0;

uniform sampler2D u_sampler2D;

void main() {
    vec4 color = texture2D(u_sampler2D, v_texCoord0) * v_color;
    gl_FragColor = vec4(1.0 - color.x, 1.0 - color.y, 1.0 - color.z, 1.0);
}
```

#### Version of LibGDX and/or relevant dependencies
libGDX 1.9.10

#### Stacktrace
The application does not crush.

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
```
The fragment language has no default precision qualifier for floating point types. Hence for float, floating
point vector and matrix variable declarations, either the declaration must include a precision qualifier or
the default float precision must have been previously declared.
```

From the GLES spec https://www.khronos.org/registry/OpenGL/specs/es/2.0/GLSL_ES_Specification_1.00.pdf?#page=41
