### ISSUE TITLE
How to use Android OpenglES  EGL show right texture by libgdx? 

### ISSUE THREAD

**Issue by hymengbj** [libgdx/libgdx#5798]
Please ensure you have given all the following requested information in your report.

#### Issue details
_Please provide the details of your issue_

#### Reproduction steps/code
_Even if you think your issue is trivial to reproduce, please supply a [SSCCE](http://sscce.org/) that demonstrates your issue.  This saves time on our end, and makes it much more likely that your issue will be fixed.
You can find barebones templates [here](https://github.com/libgdx/libgdx/wiki/Getting-help)_

#### Version of LibGDX and/or relevant dependencies
_Please provide the version(s) affected._
![S90920-153945](https://user-images.githubusercontent.com/38975956/65310041-f6f50500-dbbf-11e9-873a-e1e63926668a.jpg)
![b676db6f6d964088b3aac1e44eb0d5e](https://user-images.githubusercontent.com/38975956/65310047-fbb9b900-dbbf-11e9-9304-4df1cd2e113f.jpg)
First jpg is right texture. I just use opengles EGL to show the g3db file. but the result is wrong. So How to use Android OpenglES  EGL show right texture by libgdx?  I try to beyond the AndroidGraphics and MyAndroidGraphics(implements SurfaceHolder.Callback) ,I can get unuse info. I use the example https://www.jianshu.com/p/9db986365cda.  In the example, I insert the show texture in GLRender.render(). Why is it wrong texture? GLSurfaceView  uses EGLContext.I can`t understand.
#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [ 1] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by intrigus** [comment]
Don't defeat the issue template!
I can't read your link which is in chinese.
This doesn't seem to be an issue with libgdx but a question.

Questions should go to the forums, irc or discord.
