### ISSUE TITLE
Cannot Import com.badlogic.gdx.backends

### ISSUE THREAD

**Issue by bsr126** [libgdx/libgdx#5799]
I have installed libGDX with the gdx-setup.jar for Android. Now when I open the build.gradle with Android Studio, everything works fine, but I cannot seems to import badlogic gdx backends for my project. In the dependency section of the gradle file there is api "com.badlogicgames.gdx:gdx-backend-android:$gdxVersion" but still can't manage to import them in project. Please help

**Comment by bsr126** [comment]
Ok so I partially solved the problem by implementing badlogic.gdx.backend into the "core" section of build.gradle. But now when I try to extend AndroiLiveWallpaperService it shows "can't access android.service.Wallpaperservice. Don't know whats wrong

**Comment by MobiDevelop** [comment]
Your core module should only contain platform agnostic code. If you need to implement something per platform, usually you'd define an interface in your core module, implement in each platform module and pass the implementation to the core via the *Launcher class.
