### ISSUE TITLE
JsonValue public fields

### ISSUE THREAD

**Issue by fredboy** [libgdx/libgdx#5803]
#### Issue details
```
package com.badlogic.gdx.utils;

public class JsonValue implements Iterable<JsonValue> {
    public String name;
    public JsonValue child, next, prev, parent;
    public int size;
```
Aren't those public fields supposed to be private? They have getters, so I think they should be encapsulated.

#### Version of LibGDX
libGDX 1.9.10

**Comment by NathanSweet** [comment]
It's not a problem for them to be public.
