### ISSUE TITLE
GWT module does not map the proper `Input.Buttons`

### ISSUE THREAD

**Issue by payne911** [libgdx/libgdx#5805]
#### Issue details
When trying to detect mouse clicks, the GWT module does not map the proper button clicks:

``if (Gdx.input.isButtonJustPressed(Input.Buttons.RIGHT))`` is actually triggered on left-click.

``if(Gdx.input.isButtonJustPressed(Input.Buttons.MIDDLE))`` is actually triggered on right-click.

``if(Gdx.input.isButtonJustPressed(Input.Buttons.LEFT))`` is not triggered through left-click, right-click, nor middle-click.

#### Reproduction steps/code
Try [this piece of code](https://pastebin.com/b5rWr7Qn) to reproduce the issue. Via the ``DesktopLauncher`` it will work as expected, but when tried via the browser (after using ``dist`` and ``superDev`` html build tasks), it will behave as described above.

#### Version of LibGDX and/or relevant dependencies
1.9.10

#### Please select the affected platforms
HTML/GWT is the only platform I've seen this bug occur on so far.

**Comment by tommyettinger** [comment]
This is a real bug; it looks easy enough to fix. GwtInput has a getButton() method that remaps a constant from [GWT's NativeEvent](https://gwt.googlesource.com/gwt/+/c639f8960617e97368a660f9c50828e0f6f2eaad/user/src/com/google/gwt/dom/client/NativeEvent.java#28) to the constants in libGDX's Input.Buttons. Take a look at https://github.com/libgdx/libgdx/blob/6ac58f6a3646f7af1258b34349babe3dcbea7638/backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtInput.java#L591-L592 ; one usage relating to the just-pressed buttons only uses the NativeEvent codes, and doesn't remap. This means @payne911 could either use NativeEvent's constants on GWT only (not any other platform), which seems bad but maybe necessary, or we could fix this by changing line 592 in GwtInput.java to call getButton() on the event's code from its own getButton() method (like on line 591).
