### ISSUE TITLE
LibGDX 1.9.10 Debug-Release Difference

### ISSUE THREAD

**Issue by ahgulum** [libgdx/libgdx#5808]
Hello,
I am the developer of Happy Can:
https://play.google.com/store/apps/details?id=com.happycenter.happycan.android

After August 1 2019, I developed Happy Can version 15 with 64-bit ABI support.
To do this, I updated LibGDX, Gradle, Android Studio etc.
And for the first time, the game does not run on some devices such as Samsung SM-T113 Tablet and some of Android 4.x devices.
My game is running in debug mode on all devices
but it is not running in release mode on some devices:
[https://imgbbb.com/image/LRjHD2](https://imgbbb.com/image/LRjHD2)
[https://imgbbb.com/image/LRj62G](https://imgbbb.com/image/LRj62G)

**Comment by EtK2000** [comment]
It would be benefits if you added more info.
What does "not running" mean?
Are there any exceptions?
Can you supply a minimal example in which this occurs so we can reproduce it?

**Comment by ahgulum** [comment]
I download the game from PlayStore, tab on the icon and it throws that error message:
"Happy Can has stopped":
https://imgbbb.com/image/LRj62G

Exception class: java.lang.verifyError

**Comment by Tom-Ski** [comment]
Get the error log.

Don't defeat the issue tracker template, its there for a reason. If you need personal assistance, please use the forum/irc.
