### ISSUE TITLE
Can't generate project

### ISSUE THREAD

**Issue by borsch** [libgdx/libgdx#5813]
#### Issue details
I can't generate project like it's described in [this tutorial](https://libgdx.badlogicgames.com/documentation/gettingstarted/Creating%20Projects.html)

1. project generate problem. see stack trace below
2. I can't see `ios-moe` project
this is my `seetings.gradle` content `include 'desktop', 'android', 'ios', 'core'`

#### Reproduction steps/code
follow steps from project [setup wiki ](https://libgdx.badlogicgames.com/documentation/gettingstarted/Creating%20Projects.html)
#### Version of LibGDX and/or relevant dependencies
from `build.gradle`
```
        appName = "my-gdx-game"
        gdxVersion = '1.9.10'
        roboVMVersion = '2.3.7'
        box2DLightsVersion = '1.4'
        ashleyVersion = '1.7.0'
        aiVersion = '1.8.0'
```

#### Stacktrace
```
Generating app in C:\workspace\game
Executing 'C:\workspace\game/gradlew.bat clean --no-daemon idea'
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.4.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

FAILURE: Build failed with an exception.

* What went wrong:
Task 'idea' not found in root project 'game'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Done!
To import in Eclipse: File -> Import -> General -> Existing Projects into Workspace
To import to Intellij IDEA: File -> Open -> YourProject.ipr
```

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [x] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

I've use following generator configuration
![setup](https://user-images.githubusercontent.com/7887777/66292826-ea75e980-e8ed-11e9-9be2-901037137fdd.PNG)

FYI:
**OS:** windows 10
**JAVA_HOME** points to openjdk 11
IDEA 2019.2

**Comment by borsch** [comment]
@badlogic could you please check this?

**Comment by SimonIT** [comment]
See #5781

**Comment by borsch** [comment]
@SimonIT thanks. this help me go generate project without error. but what about missed `ios-moe` project?

**Comment by MobiDevelop** [comment]
Please see https://github.com/libgdx/libgdx/pull/5700#issuecomment-514636568
