### ISSUE TITLE
iOS Splitscreen support?

### ISSUE THREAD

**Issue by davidgiga1993** [libgdx/libgdx#5814]
#### Issue details
When using split screen mode on iOS the app does not get called with the new dimensions of the screen.

#### Reproduction steps/code
Create a new libgdx app. Add `LaunchScreen.storyboard` and update the `Info.plist.xml` with the following
```xml
<key>UILaunchStoryboardName</key>
<string>LaunchScreen</string>

<!-- 
<key>UIRequiresFullScreen</key>
<true/>
 -->
```

#### Version of LibGDX and/or relevant dependencies
- Libgdx 1.9.11
- Robovm 2.3.7

#### Logging
I've added logging to the `public void resize(int width, int height)` callback
```
## App start
Resize 2388 1620
Planned content area: 0, 0, 2388, 1580
## Enter splitscreen with 50:50 split
Resize 2388 1620
Planned content area: 0, 0, 2388, 1580
```

I would expect that libgdx reports the smaller screen size after the screen has been split.
Any ideas about this issue or is this mode not even supported?

#### Please select the affected platforms
- [X ] iOS (robovm)

**Comment by davidgiga1993** [comment]
The root cause is `IOSApplication.getBounds()` returning the wrong value.
In swift the correct way of getting the actual view size in split screen would be
```
CGRect windowRect = self.view.window.frame;
CGFloat windowWidth = windowRect.size.width;
CGFloat windowHeight = windowRect.size.height;  
```
I think by simply replacing `UIScreen.getMainScreen().getBounds()` with that code the issue could be resolved

**Comment by MrStahlfelge** [comment]
Interesting topic with having the new iPadOS ahead. 

Did you try by changing and building the backend locally? I unfortunately don't have an iPad to check with. And what's the content of your LaunchScreen.storyboard file?

**Comment by davidgiga1993** [comment]
Yes I've already fixed it in my fork:
https://github.com/davidgiga1993/libgdx/commit/d00542f5fd4f3b7272c1a51dfa9f0db2614ab433

It's enough to check in the ios simulator. I can post the content later, ultimately it doesn't matter, you just need this file with the default xcode content so iOS enables splitscreen support.

**Comment by MrStahlfelge** [comment]
@davidgiga1993 do you want to review and test the referenced PR if it solves the problem for you?

**Comment by davidgiga1993** [comment]
Sure, I'll test it tomorrow. The code itself looks good

**Comment by davidgiga1993** [comment]
Looks good so far, I've tested it on ios 14. I still want to test it on ios 9 to make sure it's properly backwards compatible
