### ISSUE TITLE
MockGraphics.getFramesPerSecond should return fps

### ISSUE THREAD

**Issue by SebastianSchlegel** [libgdx/libgdx#5818]
#### Issue details
* MockGraphics.getFramesPerSecond always returns 0 even though fps is calculated correctly

#### Reproduction steps/code
* Create a HeadlessApplication
* Run it
* call Gdx.graphics.getFramesPerSecond()
* Expected result: current fps
* Actual result: 0

#### Version of LibGDX and/or relevant dependencies
gdxVersion: 1.9.9 (but I checked the latest sources)

#### Stacktrace
N/A

#### Please select the affected platforms
* Headless

**Comment by EtK2000** [comment]
If you created a pull request close this.

**Comment by intrigus** [comment]
Please close as your PR has been accepted.
