### ISSUE TITLE
Align class static methods errors on HTML (GWT :html:draftCompileGwt)

### ISSUE THREAD

**Issue by anbu93** [libgdx/libgdx#5820]
Please ensure you have given all the following requested information in your report.

#### Issue details
An error occurs when using static methods in the Align class for HTML.

#### Reproduction steps/code
Code:
```java
private GridPoint2 getNeighbourPos(int x, int y, int alignment) {
        if (Align.isTop(alignment) && Align.isCenterHorizontal(alignment)) { //Line 197 here
            return getTopNeighbourPos(x, y);
        } else if (Align.isBottom(alignment) && Align.isCenterHorizontal(alignment)) {
            return getBottomNeighbourPos(x, y);
        } else {
            int xoffset = 0;
            if (Align.isLeft(alignment)) {
                xoffset--;
            } else if (Align.isRight(alignment)) {
                xoffset++;
            }
            int yoffset = 0;
            if (Align.isTop(alignment)) {
                yoffset++;
            } else if (Align.isBottom(alignment)) {
                yoffset--;
            }
            return new GridPoint2(x+xoffset, y+yoffset);
        }
    }
```

#### Version of LibGDX and/or relevant dependencies
Libgdx 1.9.10
gwt-gradle-plugin:1.0.9

#### Stacktrace
Command: `./gradlew html:superDev --debug`
Console out: `[ERROR] Line 197: No source code is available for type com.badlogic.gdx.utils.Align; did you forget to inherit a required module?`

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [X] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

#### PS
Solved it creating specific Align class copied from `com.balogic.gdx.utils.Align` in my project.

**Comment by mgsx-dev** [comment]
for people using libgdx 1.9.10 and below, you can workaround it by adding this code to your GWT definition (eg. MyGame.gwt.xml) : 
```
<module>
	...
	<source path="com/badlogic/gdx">
		<include name="utils/Align.java"/>
	</source>
	...
</module>
```
