### ISSUE TITLE
Sound doesn't loop on Android

### ISSUE THREAD

**Issue by bachtrong43** [libgdx/libgdx#5822]
```java
Sound sound = Gdx.audio.newSound("Sounds/sound.wav");
long soundId = sound.play();
sound.setLooping(soundId, true);
```
Above code will not work on android because a bug of SoundPool. The sound will not loop if you set loop after play. So If you want to loop a sound on Android, you need to use ```java Sound.loop``` method. I think we should add some javadoc to warning this issue on setLooping method.

**Comment by yuripourre** [comment]
Have you tried other sound formats? Background music (with loops) is working for me with .mp3. I didn't try wav.

**Comment by MrStahlfelge** [comment]
He didn't say it does not work, he said it does not work if the sound is already playing.

**Comment by yuripourre** [comment]
@MrStahlfelge right, I misread that.

**Comment by Monarchis** [comment]
@MobiDevelop I'd recommend adding a isPlaying check if possible instead of blind calling pause / resume.

https://github.com/MobiDevelop/libgdx/blob/805476b6b0be5060667d550707169f6b0cda17ef/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidSound.java#L113

**Comment by MobiDevelop** [comment]
Unfortunately there is no such check, but pause and resume are no-ops in cases where it was not playing.
