### ISSUE TITLE
Lwjgl3 FPS oddities

### ISSUE THREAD

**Issue by Ktar5** [libgdx/libgdx#5826]
**Issue Details**
I'm using the LWJGL3 backend.

Previously, when using the LWJGL2 backend, I experienced similar experiences to #1386  and #3405. However, when in fullscreen, these issues would go away and I'd have a beautiful, smooth game. This was a constant bug over the course of time.

One of the above issues suggests moving to the LWJGL 3 backend. So I did, and have been testing it over the past week.

Instead of the odd stuttering, this time around I have FPS / delta time that goes wild, and stays below 60fps, even though my computer (a recent, expensive gaming laptop) is more than capable of hitting 60 fps. It's not only my game doing this, though, it seems all the LWJGL3 games running on my machine experience the same issue. HOWEVER, once again, in fullscreen, the issue doesn't exist at all, for all the games I've tried.

Here's an interesting gif showing some stats
https://i.imgur.com/9y9e1ZT.gifv

And another of someone else's game in LWJGL3 (same game in lwjgl2 gets smooth 60fps)
https://i.imgur.com/ftbOJ1R.gifv

Here is another of a LWJGL2 game, which shows the normal, expected behaviour
https://i.imgur.com/U0QzL5t.gifv

Here's a paste of a bit of deltaTime printout to show the variation
https://pastebin.com/tcxvSt5k

And heres the same printing out of deltaTime in fullscreen:
https://pastebin.com/eFiF3J51

When in fullscreen with vsync disabled and fps unlimited, I get over 2400 FPS, which is just something to show that my machine is more than capable of 60fps windowed.

We have tried vsync on, vsync off, Display.sync stuff from lwjgl2, manually setting vsync, profiling, and other countless efforts.

Is there any information you could possibly supply me on this topic?

**Expected results**
A smooth, consistent FPS in the range of 58-62

**Version of LibGDX**
1.9.11-SNAPSHOT, LWJGL3 backend

**Platforms tested on**
Windows

Yes i have the latest drivers.

**Comment by tommyettinger** [comment]
I want to add that @Ktar5 had found there's a sharp framerate difference between LWJGL2 and LWJGL3 on their machine when running [my game/demo CaveCops](https://github.com/tommyettinger/CaveCopshttps://github.com/tommyettinger/CaveCops), with no code changes other than adding a desktop/LWJGL2 module (core is unchanged). Even on integrated graphics, CaveCops can get over 200 FPS, so the LWJGL3 code running at 54 FPS on a high-end gaming machine is concerning to me. I think @Ktar5 can test with vsync enabled on a machine with a 144Hz monitor; if that goes from 144 FPS on LWJGL2 to 54FPS on LWJGL3, that sounds like a significant bug.

**Comment by Ktar5** [comment]
In response to @tommyettinger I have tested before on my 144hz monitor and got fps ranging from 80-130 so it seems like a very interesting bug that could be going on

**Comment by mgsx-dev** [comment]
possible duplicate of #4274

**Comment by Ktar5** [comment]
There is a possibility that the root cause could be the same as #4274 but I believe that my issue is a more focused and accurate description of a single bug, whereas the aforementioned issue seems to talk about fullscreen vsync issues, multi-window issues, and fps issues, whereas I am experiencing single-window fps issues (seemingly) regardless of vsync enabling or disabling and only in windowed mode.

**Comment by Ktar5** [comment]
It seems now that this bug only happens when I activate my second monitor and move the window onto that second, external monitor.

**Comment by Ktar5** [comment]
Can confirm that this is not a problem with LibGDX but with LWJGL3, I'll continue to post updates here as I learn more.

Here's a gif of a strictly LWJGL3 game running poorly with vsync enabled. https://i.imgur.com/J7hJq8n.gifv

**Comment by kennycason** [comment]
Just wanted to add that I am experiencing the same issue when upgrading from 1.9.9 -> 1.9.11-SNAPSHOT. I was unable to upgrade to 1.9.10 due to Tiled Map bug with animated tiles. I'll debug a big more and see if I can pinpoint any more helpful debugging information. For now I have reverted back to 1.9.9

**Comment by Ktar5** [comment]
@kennycason I can't believe I forgot to post here! I fixed it by disabling vsync whenever the game is in windowed mode, and limiting the FPS by using the Sync class outlined here: http://forum.lwjgl.org/index.php?topic=6582.0

Fixed the issue immediately.
It has to do with using two monitors with different refresh rates and vsync not playing nice with that.

**Comment by kennycason** [comment]
@Ktar5 thanks for the update, i'lll give it a try!
Also, is that an appropriate long term fix? I'm wondering if this issue should still stay open. :)

**Comment by Ktar5** [comment]
Yes it is the appropriate long term fix @kennycason however it _should_ at some point be implemented into libgdx or lwjgl so that the user doesn't even have to know about solving this issue

**Comment by kennycason** [comment]
@Ktar5 interestingly this did not seem to resolve the issue for me. I'll give it a more diligent try/test over the weekend.
