### ISSUE TITLE
Loading lots of point models using Android asynctask causes in black objects

### ISSUE THREAD

**Issue by NasserTahani** [libgdx/libgdx#5831]
#### Issue details

I've developed an Android application to render about 150 point models on the screen using Libgdx game engine. Points coordinates are stored in an SQLite database and after creating a simple sphere model using ModelBuilder, they are transformed according to their location on the scene. The problem is because I need to filter points based on some criteria from the database, I don't have an option to load models on the splash screen, and each time points retrieved from database and models are created. This process takes about 40 seconds which is not efficient for an application. I've used Android Asynctask to fetch data from the database and creating models, but it results in loading points one by one but related models and textures are rendered as black objects.

#### Reproduction steps/code
```
public class LoadModelsTest implements ApplicationListener {
 
    @Override
    public void create () {
        modelBatch = new ModelBatch();
		
        cam = new PerspectiveCamera(67, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
        cam.position.set(1f, 1f, 1f);
        cam.lookAt(0,0,0);
        cam.near = 1f;
        cam.far = 300f;
        cam.update();

        new PointAsync("").execute();
        camController = new CameraInputController(cam);
        Gdx.input.setInputProcessor(camController);
    }


@Override
public void render() {

	Gdx.gl.glViewport(0, 0, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
	Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT | GL20.GL_DEPTH_BUFFER_BIT);
	
	modelBatch.begin(camera);
	modelBatch.render(modelList);
	modelBatch.end();  

	}
}

private class PointAsync extends AsyncTask<Void, Void, Void>{

        String sql;

        public PointAsync(String sql){
            this.sql = sql;
        }

        @Override
        protected Boolean doInBackground(Void... voids) {
            featureModels = new ArrayList<>();
	    pointFeatures = dbSource.fetchPointData(layerName, sql);
		if (pointFeatures.size() > 0) {
		        Node node;
			Model m = createPointModel(style);
			for (PointFeature p : pointFeatures) {

				ModelInstance model = new ModelInstance(m);
				node = p.getNode();
				model.transform.setToTranslation(node.getEasting(), node.getHeight(), node.getNorthing());
				modelList.add(model);
			}
		}
            return null;
        }

    }
} 
```

**Comment by mgsx-dev** [comment]
As most of libgdx classes, Model, ModelInstance and ModelBuilder are not threadsafe.
Also, all GPU related resources (textures, meshes, etc) must be created in Rendering thread.

you can load your external data in a thread but createPointModel and new ModelInstance(m) should be done in rendering thread. You'll need some synchronization to have a threadsafe code (which is not the case here).

If you need more help, please use [community platforms](https://libgdx.badlogicgames.com/community.html)

**Comment by NasserTahani** [comment]
Thanks, @mgsx-dev for your clarification, but how can I create and load a large number of models or perhaps shorten its time?

**Comment by mgsx-dev** [comment]
@NasserTahani please use [community platforms](https://libgdx.badlogicgames.com/community.html) for help with your code, I regulary hangout on [libgdx discord server](https://discord.gg/7c6Wg8H).
