### ISSUE TITLE
BitmapFontCache.setColors(float,int,int) frequently exceeds array bounds

### ISSUE THREAD

**Issue by tommyettinger** [libgdx/libgdx#5834]
#### Issue details
Calling BitmapFontCache.setColors with either a Color or float argument followed by a start and end as ints is likely to result in an ArrayIndexOutOfBoundsException. It depends on the length of the text in the cache, I think also on whether that length modulo 4 is greater than 0 (so the majority of long-enough Strings throw an Exception), and only happens when end is close to the length of the text in the cache (it doesn't have to be equal to the length, and there can be crashes with length - 1 and length - 2 for end values). The Exception isn't thrown by BitmapFontCache.setColors(Color), and I think the logic has a bug in the overload that takes start and end. The simplest fix is to make sure the loop in the one-page case of setColors(float, int, int) doesn't have a termination condition that permits accessing indices larger than the size of the array. Possibly, other parts of that method may need a similar fix.

The BitmapFontCache code isn't something I can confidently understand at this point, but it's still incredibly annoying that so much of it is private and inaccessible to overriders in the case of a bug *such as this one* that would be pretty trivial to fix if I could modify the file or override that method with access to the important private variables in BitmapFontCache. Because BitmapFont is tied into BitmapFontCache, I would need to copy BitmapFontCache, potentially copy or subclass BitmapFont, and use my now-incompatible code to work around this issue.

#### Reproduction steps/code
```java
// just supplying render() here because the rest can be the defaults produced by the setup jar
public void render() {
        BitmapFont font = new BitmapFont(); // not production code; move to create() if you want
        SpriteBatch batch = new SpriteBatch(); // also not production code
        final String trogdor = "TROGDOR! TROGDOR! Trogdor was a man! Or maybe he was a... Dragon-Man!";
        font.getCache().clear();
        // the x, y, and width here don't matter; they may need to be in a visible area.
        font.getCache().addText(trogdor, 24, 37, 20, Align.center, true);
        font.getCache().setColors(Color.FOREST, 0, trogdor.length());
        font.getCache().draw(batch);
        //will be crashing at this point.
}
```
#### Version of LibGDX and/or relevant dependencies
I've only noticed it so far on 1.9.10, and haven't tested on nightly builds.

#### Stacktrace
```java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1362
	at com.badlogic.gdx.graphics.g2d.BitmapFontCache.setColors(BitmapFontCache.java:191)
	at com.badlogic.gdx.graphics.g2d.BitmapFontCache.setColors(BitmapFontCache.java:182)
	at com.github.tommyettinger.CaveCops.putMap(CaveCops.java:743)
	at com.github.tommyettinger.CaveCops.render(CaveCops.java:771)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at com.github.tommyettinger.lwjgl3.Lwjgl3Launcher.createApplication(Lwjgl3Launcher.java:14)
	at com.github.tommyettinger.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.java:10)
```

#### Please select the affected platforms
- [ ] Android <- possible, unknown, I'm not set up to develop Android apps
- [ ] iOS (robovm) <- possible, unknown, don't own a Mac
- [ ] iOS (MOE) <- possible, unknown, why is this even here
- [ ] HTML/GWT <- unclear, I can check if anyone wants
- [X] Windows <- definite
- [?] Linux <- probable; the code at fault is unchanged
- [?] MacOS <- probable; the code at fault is unchanged

**Comment by EtK2000** [comment]
My advice would be to download the source and include it as a library project instead of the LibGDX jar.
It should be easy enough to setup and switch back and forth.

**Comment by tommyettinger** [comment]
@EtK2000 Normally that's good advice, but I primarily work on a library, SquidLib, that can't very easily require users of the library to build a modified fork if they want colored text. If JitPack could build libGDX (which would allow it to build forks as well), I'd use that, but I believe the native code prevents that. FWIW, I think this bug surfaced between 1.9.9 and 1.9.10.

**Comment by EtK2000** [comment]
I meant that you can build against source and find the erroneous code and fix it and send a pull request.
