### ISSUE TITLE
Implementing gdx-box2d into non-libGDX project

### ISSUE THREAD

**Issue by Youseflapod** [libgdx/libgdx#5842]
Is the libGDX wrapper for the box2D C++ library possible to be implemented into a nonlibGDX Java project? As the only alternative for lwjgl developers is to use the inferior jbox2d physics engine, which is slower and less featured.

Would it involve also including the natives? I don't believe this is possible without modification due to the dependencies on libgdx features, such as in the debug renderer.

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [x ] HTML/GWT
- [x ] Windows
- [x] Linux
- [ x] MacOS

**Comment by EtK2000** [comment]
This isn't quite an issue, it's probably better for you to ask on the discord or irc.

**Comment by intrigus** [comment]
This should work, but you'd have to provide certain libgdx classes box2d-gdx uses e.g. GdxRuntimeException and probably some other classes.

**Comment by Youseflapod** [comment]
Oh ok, yeah I'll ask on there
