### ISSUE TITLE
[FEATURE REQUEST] Getting interpolation type by String

### ISSUE THREAD

**Issue by SpyceTewan** [libgdx/libgdx#5843]
#### Issue details
Requesting for feature addition to get interpolation instance by interpolation name.

Sometimes I'd like to be able to get an interpolation type from, for example, a text file. The Interpolation class doesn't feature a method to get an instance of Interpolation via String input. Current workaround would be something like 
```java
private Interpolation getInterpolationByName(String name) {
    try {

        Field field = Interpolation.class.getField(name);
        return (Interpolation) field.get(Interpolation.class);

    } catch (NoSuchFieldException | IllegalAccessException ex) {
        ex.printStackTrace();
        return Interpolation.linear;
    }
}
```
This is a feature request for a static function in the [Interpolation](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/math/Interpolation.java) class, that returns the appropriate instance of a [built in interpolation](https://github.com/libgdx/libgdx/wiki/Interpolation) type.

#### Version of LibGDX and/or relevant dependencies
1.9.10

#### Please select the affected platforms
- [x] Android
- [x] iOS (robovm)
- [x] iOS (MOE)
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by EtK2000** [comment]
Please add `[FEATURE REQUEST]` into the title.

**Comment by intrigus** [comment]
Until this is implemented you could use a Map<String, Interpolation> or a method with a big Switch-case.

**Comment by SpyceTewan** [comment]
Would be faster, but this approach doesn't require to change the method if the built in Interpolation types are changed

**Comment by Tom-Ski** [comment]
You can grab this for now. Might be handy to have in core also.
https://github.com/rockbite/talos/blob/bd668638f1ed197c6c1fa00fb7c37e0d7241aed4/runtimes/talos-libgdx/src/com/rockbite/tools/talos/runtime/utils/InterpolationMappings.java

**Comment by Darkyenus** [comment]
If something like this went into core, I'd want it to be extensible. Otherwise it would be easier to just put the interpolations into an enum.

**Comment by JasonMacKeigan** [comment]
To do this properly, the use of an enum would be best but there would be no backwards compatibility. Another solution would be to use Reflection, however the function used to create some Map of <String, Interpolation> would need to be referenced at the start of runtime for it to be at least fairly efficient and not constantly require reflection. The last approach would be to not use reflection and create a Map and use the static {} block, this would be even worse because it would have to be constantly maintained. I really can't see this being a simple or useful implementation.

**Comment by RUSshy** [comment]
bad idea to add it using reflection, it is slow, it increase startup time for nothing

**Comment by NathanSweet** [comment]
I'd suggest to use a map, populate it with the interpolations you need (using reflection or anything else). IMO this is application level code, it doesn't need to be in libgdx.
