### ISSUE TITLE
[LWJGL3 - Windows] Window does not maximized as expected

### ISSUE THREAD

**Issue by ghost** [libgdx/libgdx#5845]
#### Issue details
I am trying to maximized the window using LWJGL3 backend with no success. The windows starts at 
left up corner without title bar.

#### Screenshot
![image](https://user-images.githubusercontent.com/53366919/68932387-36dd0080-079b-11ea-98ab-c56c4dd373f4.png)

#### Reproduction steps/code

1. Just create a new project and change the version from lwjgl to lwjgl3

```java package com.mygdx.game.desktop;

import com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application;
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration;
import com.mygdx.game.MyGdxGame;

public class DesktopLauncher {
	public static void main (String[] arg) {
		Lwjgl3ApplicationConfiguration config = new Lwjgl3ApplicationConfiguration();
		config.setMaximized(true);
		new Lwjgl3Application(new MyGdxGame(), config);
	}
}
```

#### Version of LibGDX and/or relevant dependencies
1.9.10

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Anuken** [comment]
As far as I know, this is a GLFW bug: https://github.com/glfw/glfw/issues/1499

**Comment by PokeMMO** [comment]
I think this should be fixed in latest LWJGL available in libgdx's SNAPSHOT releases.

**Comment by cpepi001** [comment]
I used the latest libgdx version (1.9.11-SNAPSHOT) and the the window starts in maximize but the title bar is hidden as shown below.

![image](https://user-images.githubusercontent.com/53366919/69703585-632d4100-10fa-11ea-9a59-50cb73effca0.png)

**Comment by PokeMMO** [comment]
Calls to glfwSetWindowPos on Windows do not correctly position the window to include the offset required for the title bar. This is not limited to maximized windows and also occurs windows when setting `setWindowPosition(0, 0)`

This seems like it is correct according to glfw documentation.

Documentation: https://github.com/glfw/glfw/blob/2c519709be0dacc7af2908982a7ab80b889a8126/docs/window.dox#L802

Commenting out the following lines fix this, but removes the ability to control which monitor it is maximized to.

https://github.com/libgdx/libgdx/blob/55dd634c5d0412d77598a0e050b9fd3ea9fc326c/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java#L468-L473

Trying to work around by glfwGetWindowPosition to obtain the current x/y position and offsetting the position before calling glfwSetWindowPos results in slightly incorrect results.

![image](https://user-images.githubusercontent.com/2398581/69713700-e64f9680-10fc-11ea-89f4-8edaec251b84.png)

Correct result for context:

![image](https://user-images.githubusercontent.com/2398581/69713761-febfb100-10fc-11ea-9edd-914569aa0629.png)

This was done using latest master libgdx branch, compiled locally. glfwGetVersionString: 3.4.0
