### ISSUE TITLE
Support for CINEMA 4D

### ISSUE THREAD

**Issue by mbjgit** [libgdx/libgdx#5848]
Support for CINEMA 4D
#### Issue details
 I use CINEMA 4D tool to create fbx in cm. In fbx-converter, the fbx can be show, but in the code—desktop, it is no exist or alpha. when I use Blender tool to create ,it can be show. 
And my issue is why not support for CINEMA 4D!!!! 

#### Version of LibGDX and/or relevant dependencies
last version

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [1 ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by mbjgit** [comment]
the version(1.9.9, now 1.9.10? but I think even update, it can not change):
![图片](https://user-images.githubusercontent.com/20197609/69313641-20d4b180-0c6d-11ea-872a-ff0bb104c405.png)

the code I'm using to render the mode: 
![图片](https://user-images.githubusercontent.com/20197609/69313691-42359d80-0c6d-11ea-8d5f-728b35499332.png)
![图片](https://user-images.githubusercontent.com/20197609/69313726-58435e00-0c6d-11ea-9f73-66ab23b47bdd.png)
the fbxs(I try to use different size, you can open it to see ):
[blue9.zip](https://github.com/libgdx/libgdx/files/3873113/blue9.zip)

**Comment by mgsx-dev** [comment]
@mbjgit i think your FBX files are too recent for fbx-conv, i made a [PR](https://github.com/libgdx/fbx-conv/pull/117) that check file version. Current fbx-conv fail silently and output empty G3D files, i exported your files to G3DJ and it output an empty scene so i suspect your files are too recent. Current fbx-conv supports FBX 2014.2 and master supports FBX 2015.1.

If you can't choose a suitable format version in Cinema4D, a workaround is to re-export them from Blender.

**Comment by mbjgit** [comment]
Thank！But i already kown  that current fbx-conv supports FBX 2014.2 , and it can conv to g3db. finnaly, it can not show in java-desktop. 
Now I re-conv C4D-fbx to Blender-fbx. you kown, it is rather time-consuming and the compatibility is also one problem.

**Comment by mgsx-dev** [comment]
Yeah i understand your point. However, i suggest you to create a feature request in fbx-conv issue tracker and close this issue since it's not a libgdx issue.

**Comment by mgsx-dev** [comment]
feature request already exists actually, see https://github.com/libgdx/fbx-conv/issues/114
