### ISSUE TITLE
How to port libgdx to new OS ( Linux fork )

### ISSUE THREAD

**Issue by eix128** [libgdx/libgdx#5850]
Hi , 
We need to port libgdx to Tizen , Huawei Harmony OS and PureOS.
As we know , most OS's are based on linux.

How can we port libgdx to custom linux os's
is there any documentation?

**Comment by intrigus** [comment]
As a first step you have to check whether your target supports Java.
If not you have to find some way to run it.
Remember that you can always try to use the gwt output if your target supports some kind of webview.

**Comment by eix128** [comment]
I need a solution without webview.
webview makes so much penalty.
But IOS doesnt support Java and it can run with robovm ?

**Comment by julienvillegas** [comment]
Hi @eix128 
Better use the discord server for your question.
That said: Yes LibGDX does run on iPhone with RoboVm (MobiVM)

**Comment by NathanSweet** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
