### ISSUE TITLE
Stage.stageToScreenCoordinates returns incorrect value with y offset in viewport

### ISSUE THREAD

**Issue by jusw85** [libgdx/libgdx#5854]
#### Issue details
Stage.stageToScreenCoordinates returns incorrect value with y offset in viewport

#### Reproduction steps/code

Create a 100x100 window.
Setup a stage with a viewport in the top quarter of the window i.e. width 100, height 25, y=75
stage.stageToScreenCoordinates returns incorrect values.

   ```
 public void create() {
        Viewport viewport = new Viewport() {
            @Override
            public void update(int screenWidth, int screenHeight, boolean centerCamera) {
                assert screenWidth == 100 && screenHeight == 100;
                setScreenBounds(0, 75, 100, 25);
                setWorldSize(100, 25);
                apply(centerCamera);
            }
        };
        viewport.setCamera(new OrthographicCamera());
        Stage stage = new Stage(viewport);

        Vector2 tmpvec = new Vector2();

        tmpvec.set(0, 0);
        stage.getViewport().project(tmpvec);
        System.out.println(tmpvec); // prints (0, 75), correct so far

        tmpvec.set(0, 0);
        stage.stageToScreenCoordinates(tmpvec);
        System.out.println(tmpvec); // prints (0, -50), should be (0, 25)
    }
```

Due to the following line in Stage:

https://github.com/libgdx/libgdx/blob/c0c1f515df54092cb47717f43f022db02cf7e328/gdx/src/com/badlogic/gdx/scenes/scene2d/Stage.java#L738

After getting the result of camera.project (in absolute screen coordinates with origin at bottom left), it converts to top left origin using viewport.screenHeight instead of actual window height.

#### Version of LibGDX and/or relevant dependencies
1.9.10

**Comment by RUSshy** [comment]
why close without comment? @Tom-Ski

**Comment by jusw85** [comment]
This is unrelated to the #5853

**Comment by jusw85** [comment]
With reference to the example code:
```
     tmpvec.set(0, 0);
     stage.stageToScreenCoordinates(tmpvec);
     System.out.println(tmpvec);
```
(0,0) is within the bounds of the window. Why is it returning (0,-50) which is outside the window?

**Comment by Tom-Ski** [comment]
Yeah, this doesn't look right. Why do you expect 0,25 though?

**Comment by jusw85** [comment]
1. The window has width=100, height=100.
2. The viewport has screenWidth=100, screenHeight=25, screenX=0, screenY=75 i.e. top 1/4 of the window.
3. (0, 0) in world coordinates should correspond to (0, 75) in screen coordinates (origin at bottom left). This is verified by `stage.getViewport().project(tmpvec);`. This calls `camera.project`.

Relevant camera.project documentation:
```
The screen coordinate system has its origin in the <b>bottom</b> left, with the y-axis pointing <b>upwards</b> and the x-axis pointing to the right.
```

Relevant code:

https://github.com/libgdx/libgdx/blob/c0c1f515df54092cb47717f43f022db02cf7e328/gdx/src/com/badlogic/gdx/utils/viewport/Viewport.java#L82

https://github.com/libgdx/libgdx/blob/2161c43893a5769f0d557e485689dfca670bc273/gdx/src/com/badlogic/gdx/graphics/Camera.java#L239

4. `stage.stageToScreenCoordinates` has origin at top left. Therefore it should be (0,25) (or thereabouts), certainly not (0,-50).

**Comment by Tom-Ski** [comment]
stage.stageToScreenCoordinates shouldn't have origin at top left, so it shouldn't be 0,25. Screen _is_ bottom left unless otherwise specified, and project is sticking to this standard. As with the previous issue, the documentation probably needs improving here also. 

Anyway, this result seems wrong, so will have to do further testing.

**Comment by jusw85** [comment]
> stage.stageToScreenCoordinates shouldn't have origin at top left

I reasoned this from the way the source code and actual tests work, specifically this line `stageCoords.y = viewport.getScreenHeight() - stageCoords.y;`.

It works perfectly fine, returning correct result with origin top left if viewport has no offset.

**Comment by NathanSweet** [comment]
Didn't mean for this to get closed (happened via GH's autotomatic magicke).
