### ISSUE TITLE
IndexOutOfBounds in com.badlogic.gdx.controllers.desktop.ois.OisJoystick.buttonPressed

### ISSUE THREAD

**Issue by nonchip** [libgdx/libgdx#5857]
see https://github.com/libgdx/libgdx/blob/b036f0521c2e98a40fdc44f8224e18534a5a9f75/extensions/gdx-controllers/gdx-controllers-desktop/src/com/badlogic/gdx/controllers/desktop/ois/OisJoystick.java#L52 (plus probably the function following that one).

crashes in games like PokeMMO and (according to google) Slay the Spire (found this report when looking for the issue: https://steamcommunity.com/app/646570/discussions/1/1751232561619087220/), when tools like ckb-next (required for corsair input devices on linux) or xboxdrv are being used.

Error message I'm getting in PokeMMO:
```
[ERROR 2019-12-08 18-31-36 CET][LWJGL Application] f.Vv:? - Fatal render error.
java.lang.ArrayIndexOutOfBoundsException: 271
        at com.badlogic.gdx.controllers.desktop.ois.OisJoystick.buttonPressed(Unknown Source)
        at com.badlogic.gdx.controllers.desktop.ois.OisJoystick.update(Native Method)
        at com.badlogic.gdx.controllers.desktop.ois.OisJoystick.update(Unknown Source)
        at com.badlogic.gdx.controllers.desktop.ois.Ois.update(Unknown Source)
        at com.badlogic.gdx.controllers.desktop.OisControllers$1.run(Unknown Source)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.executeRunnables(Unknown Source)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(Unknown Source)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(Unknown Source)
```

**Comment by Monarchis** [comment]
Duplicate / Same Source affected: #2964

**Comment by nonchip** [comment]
@Monarchis then we should probably change that issue, because i don't have any A4Tech hardware.

**Comment by Monarchis** [comment]
@nonchip I refered to this Issue, because it also affects the same native library, that it returns wrong KeyCounts, in your case the array is also initialized with a wrong size.

Currently idk if it's a problem with the Hardware or the native library itself.

**Comment by nonchip** [comment]
i think it's probably an issue with the library (`(OIS::JoyStick*)->getNumberOfComponents(OIS::OIS_Button)` seems to return too small a value, which it gets from its internal `((JoyStickState)mState).mButtons`, initialized via a bunch of further abstraction, originally from `DeviceComponentInfo::getComponentInfo` in https://github.com/wgois/OIS/blob/master/src/linux/EventHelpers.cpp#L150).

maybe it's also somewhat related to the driver/hardware possibly skipping button IDs or something like that (e.g. i could imagine a device reporting `button 0, axis 1, axis 2, button 3`, resulting in a `buttons[2]` array trying to get indexed with `3`), but this is literally the first time i have an issue like that, so if it's the driver doing that it would mean everyone else expects that and initializes their arrays differently, which kiiinda makes me think it's OIS who's offspec here, not the hardware/driver.

**Comment by Monarchis** [comment]
@nonchip Yes that's exact the reason, why I marked it as duplicate, there are more Issues with the same Problem of the native implementation.

This Line is just wrong, also in other Issues ;)
https://github.com/libgdx/libgdx/blob/b036f0521c2e98a40fdc44f8224e18534a5a9f75/extensions/gdx-controllers/gdx-controllers-desktop/src/com/badlogic/gdx/controllers/desktop/ois/OisJoystick.java#L241

That leads to a wrong size initialization at:
https://github.com/libgdx/libgdx/blob/b036f0521c2e98a40fdc44f8224e18534a5a9f75/extensions/gdx-controllers/gdx-controllers-desktop/src/com/badlogic/gdx/controllers/desktop/ois/OisJoystick.java#L40

That the Exeption is thrown on Line:
https://github.com/libgdx/libgdx/blob/b036f0521c2e98a40fdc44f8224e18534a5a9f75/extensions/gdx-controllers/gdx-controllers-desktop/src/com/badlogic/gdx/controllers/desktop/ois/OisJoystick.java#L52

Maybe i'll try to fix it those days, else you or someone else  could also create a pr ;)

**Comment by nonchip** [comment]
well i don't know if the code to get the "button count" is wrong, or just you using the "count" as "max value of index".  
see also my observation of `ckb-next` starting those indices at a relatively high number. just because you have 5 buttons doesn't mean they *have* to be `button[0..4]`. `[234..238]` would still just be a "count" of 5.

**Comment by Monarchis** [comment]
@nonchip I observed, that OIS, works with offsets off buttons (mappings), so may there could be also be the problem...
OIS is mapping buttons down to a smaller array with the button count.
May there is any Problem with the version of OIS, a newer one is already released.

Actually I also don't know how to fix this.

**Comment by tatokis** [comment]
While this still remains an issue, I have pushed a workaround in ckb-next.
https://github.com/ckb-next/ckb-next/commit/afd0e19f1d198b3807d137be40cb845a28ccd2d5

**Comment by nonchip** [comment]
@tatokis i'm not sure ckb-next should be stripped of functionality just because libgdx doesn't manage to replace getButtonCount by KEY_MAX though... ckb was doing nothing wrong, and your change seems to prevent custom buttons.

**Comment by tatokis** [comment]
@nonchip  It's not stripping or removing any functionality.

For every physical device, it makes a virtual keyboard and a virtual mouse.
When you bind a keyboard key to a mouse, the key gets sent through the virtual keyboard, not the virtual mouse.

All that commit does is remove the keyboard keys from the virtual mouse, which were not being used in the first place.

Either way, this is off topic in this thread.

**Comment by nonchip** [comment]
@tatokis ok yeah just realized the `SCAN_MOUSE` part. still though, we shouldn't rely on a ckb workaround, pretty sure as soon as something else comes along using uinput there's a nonzero chance it will break down again.

**Comment by MrStahlfelge** [comment]
Hi, please take a look at [gdx-controllers v2 prerelease snapshot](https://github.com/libgdx/gdx-controllers). It should solve your issue.
