### ISSUE TITLE
LibGdx Class Ray : setting a new direction does not normalize the vector

### ISSUE THREAD

**Issue by Laurent1967** [libgdx/libgdx#5858]
When creating a ray, the direction vector is normalized as it should 
```
public Ray (Vector3 origin, Vector3 direction) {
	this.origin.set(origin);
	this.direction.set(direction).nor();
} 
```
but when a new direction is set, the vector is NOT normalized, which is an error

```
public Ray set (Vector3 origin, Vector3 direction) {
	this.origin.set(origin);
	this.direction.set(direction);
	return this;
}
```

these codes are extracted from LibGdx 1.9.11-SNAPSHOT but applies probably to all previous versions.
An obvious consequence is that Ray#getEndPoint(final Vector3 out, final float distance) may return a wrong distance because of a direction vector not normalized.

Laurent Crenier (gquark)

**Comment by noblemaster** [comment]
This needs further discussion. See discord.

**Comment by Laurent1967** [comment]
Happy to see that my little inconsistency bug report generates so much debate ;-)

**Comment by yuripourre** [comment]
It shows how much LibGDX is active.

**Comment by noblemaster** [comment]
PR integrated.
