### ISSUE TITLE
Overlaping rectangles

### ISSUE THREAD

**Issue by ks1c** [libgdx/libgdx#5861]
Rectangle r1 = new Rectangle(0.1f, 0f, 32f, 32f);
Rectangle r2 = new Rectangle(32f, 0f, 32f, 32f);
if (r2.overlaps(r1)) Gdx.app.log("", "true");

This two rectangles are not overlaping, but the function returns true.
The corner of r1 is 31.1f, and the x of r2 is 32f, so they are not overlaping, right?

**Comment by Anuken** [comment]
No, the corner of r1 is 32.1f. This is correct behavior.

**Comment by ks1c** [comment]
@Anuken Im sorry but Im confused. Look at this image:
![ss](https://user-images.githubusercontent.com/45995919/70854559-cc031000-1e93-11ea-99ce-631e889af9af.png)

**Comment by Anuken** [comment]
Your picture isn't relevant and does not display the values you posted in the issue. The corner of r1 is 32 + 0.1 = 32.1, so it overlaps the other rectangle at 32, 32.

**Comment by ks1c** [comment]
@Anuken Ok, sorry, that was foolish of me, I was confused because I was thinking in pixels. Thanks for your time.
