### ISSUE TITLE
MessageFormat libgdx escapes rules cause nested choice not work

### ISSUE THREAD

**Issue by bachtrong43** [libgdx/libgdx#5869]
```java
public class Test {
	public static void main(String[] args) {
		String pattern = "{0,choice, 1<hello|5<'{1,choice,1<more than one|4<more than four}'}";
		MessageFormat cf = new MessageFormat(pattern);
		System.out.println(cf.format(new Object[]{7, 5}));
		TextFormatter formatter = new TextFormatter(Locale.getDefault(), true);
		System.out.println(formatter.format(pattern, new Object[]{7, 5}));
	}
}
```
I used I18Bundle for localization. It uses TextFormatter which wraps MessageFormat and replaces escape chars before applies pattern. With nested pattern like above, MessageFormat prints ```more than four``` but TextFormatter throws exception.

**Comment by EtK2000** [comment]
Please supply more information:
• what version
• what backed
• exception stacktrace

**Comment by bachtrong43** [comment]
version: 1.9.11-snapshot
it throws invalid pattern exception. The reason is libgdx add custom escape rules: add ‘ before each single quote. so this pattern is converted to “{0,choice,1<hello|5<'’{1,choice,1<more than one|4<more than four}'’}” it is invalid pattern in MessageFormat

**Comment by crykn** [comment]
Hey @bachtrong43, you're right libGDX can't handle nested choices. However, in a lot of cases they are not really needed and can be replaced by two consecutive ChoiceFormats. For instance, the above example can be written as: 
```java
"{0, choice, 1<hello|5<}{1,choice,1<more than one|4<more than four}"
```
I know that that doesn't cover all use-cases, but there is no simple solution for this issue that doesn't break existing applications that rely on the escaping mechanic for single quotes.
