### ISSUE TITLE
Android Libgdx memory leak on creating multiple Textures

### ISSUE THREAD

**Issue by NasserTahani** [libgdx/libgdx#5879]
I've created an Android application to show about a hundred point objects using Libgdx modelBuilder. It works fine and models are rendered without any problem, but I needed to add a marker for every point model. To do that I've extended from Actor and in this class, I've created two textures representing the marker in normal and the selected mode when the user clicked the objects. The following is the LabelActor class which has been instantiated for each point model. 
```
public class LabelActor extends Actor {

    Texture texture;
    Texture selectedTexture;
    Sprite sprite;
    private Vector3 distVector = new Vector3();

    public LabelActor(Texture[] textures){

        texture = textures[0];
        selectedTexture = textures[1];
        sprite = new Sprite(texture);
        setBounds(sprite.getX(), sprite.getY(), sprite.getWidth(), sprite.getHeight());
    }

    @Override
    protected void positionChanged() {
        sprite.setPosition(getX(),getY());
        super.positionChanged();
    }

    @Override
    public void draw(Batch batch, float parentAlpha) {

         if (selected){
            batch.draw(selectedTexture, getX()-sprite.getWidth()/2, getY());
            infoWindow.draw(batch, parentAlpha);
        } else {
            batch.draw(texture, getX()-sprite.getWidth()/2, getY());
        }
    }
}
```
 I've used AssetManager to load textures and create HashMap of them in the main screen then pass an array of two textures to each LabelActor class.
```
@Override
public void create() {

    ...
    environment = new Environment();
    environment.set(new ColorAttribute(ColorAttribute.AmbientLight, 0.4f, 0.4f, 0.4f, 1.0f));
    pointLight = new PointLight().set(0.8f, 0.8f, 0.8f, 2f, 0f, 0f, 500f);
    environment.add(pointLight);

    assetManager =  new AssetManager();
    textureTitleList = new ArrayList<>();
    for (FileHandle f: Gdx.files.internal("markers").list()){
        assetManager.load("markers/" + f.name(), Texture.class);
        textureTitleList.add(f.name());
    }
}

private void loadModel() {

    textureMap = new HashMap<>();
    for (String fName: textureTitleList){
        textureMap.put(fName, assetManager.get("markers/" + fName, Texture.class));
    }
}

@Override
public void render() {

    if (!isLoaded && assetManager.update()) {
        loadModel();
        isLoaded = true;
    }
    ...
}
```
The problem will be arisen on using the marker for these objects which causes a huge amount of memory usage. Loading a sphere model for each point objects takes about 14M of graphics memory but loading texture markers take 500M of memory on the device. I've used png icons located in the asset folders to create my textures but not using a Libgdx atlas. How can I prevent the memory leak and create this number of textures? 

![32](https://user-images.githubusercontent.com/24411076/71719567-04af5d00-2e34-11ea-854d-7adcd325356b.png)

**Comment by Tom-Ski** [comment]
No leak is demonstrated here. If you are using too much vram, use smaller textures, or different texture formats.

**Comment by NasserTahani** [comment]
Is it an efficient method to create many textures using AssetManager? The leak is happened when I want to change the textures of point models.

**Comment by Tom-Ski** [comment]
Are you unloading the old textures after you are done with them?

**Comment by NasserTahani** [comment]
What do you mean by onloading? I dispose textures on creating new textures and clear list of textures.

**Comment by Awes0meM4n** [comment]
@NasserTahani I think that your problem is that you are loading the same texture for each marker readed. You have to load the texture once and reference that one on each marker (accordind with your example picture). This way only use the ram for one. Even you can color a texture for selected one.

**Comment by NasserTahani** [comment]
Thanks, @Awes0meM4n for your hint. Can you explain more about creating a reference texture for each marker? I've Created a HashMap of all textures and passed them to each marker but it seems differ from what you suggest.

**Comment by Awes0meM4n** [comment]
In `create()` you have to load texture only once, not one per marker. Then [you fetch the texture like in the wiki](https://github.com/libgdx/libgdx/wiki/Managing-your-assets#getting-assets). When you have your texture (or your array of texture required for your `LabelActor` constructor), you can instantiate all the markers you need using the same texture (improving the draw performance)
