### ISSUE TITLE
PixmapPacker is altering names of packed pixmaps by changing _003 => _03, etc.

### ISSUE THREAD

**Issue by michael-conrad** [libgdx/libgdx#5885]
Please ensure you have given all the following requested information in your report.

#### Issue details
When packing with pixmappacker I specify the name of the image as "Blocks_01_64x64_Alt_04_003" but the actual name stored becomes "Blocks_01_64x64_Alt_04_03" ???

#### Reproduction steps/code
```Java
FileHandle internal = Gdx.files.internal("9patch/Blocks_01_64x64_Alt_04_003.png");
Pixmap p = new Pixmap(internal);
packer.pack(internal.nameWithoutExtension(), p);
Gdx.app.log(this.getClass().getSimpleName(), "Added to pack: "+internal.path()+" as "+internal.nameWithoutExtension());
p.dispose();
for (AtlasRegion r: newAtlas.getRegions()) {
    Gdx.app.log(this.getClass().getSimpleName(), r.name);
}
```
#### Version of LibGDX and/or relevant dependencies
```groovy
 ext {
        appName = "Numbers Maze"
        gdxVersion = '1.9.10'
        roboVMVersion = '2.3.8'
        box2DLightsVersion = '1.4'
        ashleyVersion = '1.7.0'
        aiVersion = '1.8.0'
    }
```

#### Please select the affected platforms
- [x] Linux

**Comment by mgsx-dev** [comment]
this is an intented behavior with TextureAtlas. Typically used for animation frames. 

> If an image file name ends with underscore and then a number (eg animation_23.png), the number is considered the "index" and is stored separately.

see https://github.com/libgdx/libgdx/wiki/Texture-packer#image-indexes

You can workaround that by adding a suffix to your filenames though.

**Comment by michael-conrad** [comment]
Ah... so a "feature" that has been added since version something 4 years ago...
