### ISSUE TITLE
Libgdx, why can't I animate my sprites, what am I doing incorrectly here? 

### ISSUE THREAD

**Issue by AdvertiserM** [libgdx/libgdx#5886]
#### Issue details
All the info is below when it comes to do anything with animating the frames and also the "frames" 
https://www.youtube.com/watch?v=G44YMwBoJXM
Currently following that tutorial word by word but no luck. 

`Frame.add(new TextureRegion(region, i * frameWidth, 0, frameWidth, region.getRegionHeight()));`
Cannot resolve method 

`this.frameCount = frameCount;
        maxFrameTime = cycleTime / frameCount;
        frame = 0;`
Incompatible types. 

`if(Frame >= Frame)`
error: <identifier> expected

libgdx is latest version. 

```Windows

**Comment by Darkyenus** [comment]
This issue tracker is only for issues, not for general help. See [here](https://github.com/libgdx/libgdx/wiki/Getting-Help), people on IRC/Discord/Forums will be happy to help.

**Comment by Monarchis** [comment]
@AdvertiserM seems to be just an issue to promote this video ... look at the Name AdvertiserM and only 2 contributions with the same Video link ...
Thanks for Spamming.
