### ISSUE TITLE
Equalize log output of HeadlessApplicationLogger

### ISSUE THREAD

**Issue by Monarchis** [libgdx/libgdx#5894]
In my Eyes it would be nice or better if the HeadlessApplicationLogger would NOT print log outputs different from LwjglApplicationLogger.
That leads to differences in Log-Outputs on Desktop environments depending on Application-Type.

So my suggestion is that the HeadlessApplicationLogger also uses braces around the log tag.

#### Issue details
LwjglApplicationLogger: 
https://github.com/libgdx/libgdx/blob/9db77b1d5d390a86186baaf011d5915a8407f409/backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglApplicationLogger.java#L28

HeadlessApplicationLogger:
https://github.com/libgdx/libgdx/blob/9db77b1d5d390a86186baaf011d5915a8407f409/backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/HeadlessApplicationLogger.java#L28

#### Reproduction steps/code

Run a log output with HeadlessApplicationLogger and compare it to the log output of LwjglApplicationLogger.
The HeadlessApplication Logger does not use Braces around the tag it only uses a `:` after the tag.

#### Version of LibGDX and/or relevant dependencies
current latest version is affected.

#### Stacktrace
--

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by EtK2000** [comment]
Please don't create an issue for pull requests.
Ensure you have the information there and close this.
