### ISSUE TITLE
Starting April 2020, apps submitted to the App Store must use an Xcode storyboard.

### ISSUE THREAD

**Issue by itsabhiaryan** [libgdx/libgdx#5904]
#### Issue details
Starting April 2020, apps submitted to the App Store must use an Xcode storyboard to provide the app’s launch screen and must have an interface that supports any display size but currently by default we don't have any storyboard in iOS module.

Thread link : https://developer.apple.com/news/?id=01132020b

#### Version of LibGDX and/or relevant dependencies
LibGDX : 1.9.10
roboVM : 2.3.8

#### Please select the affected platforms
- [X] iOS (robovm)

**Comment by obigu** [comment]
Storyboard based launch screens work on MobiVM so it's just a matter of creating one for default project.
