### ISSUE TITLE
[Scene2D] Slider changes position/value on touchUp when knob has different size drawable styles

### ISSUE THREAD

**Issue by obigu** [libgdx/libgdx#5905]
This issue affects Sliders with a knob that changes size (usually larger) when dragging it and goes back to normal size on release. In Scene2D you can achieve this effect by setting the knobDown Drawable in `SliderStyle` to to be an upscaled version of the default knob Drawable.

The problem is that if you set such a `SliderStyle` to it, the value/position of the Slider changes the latest selected value on `touchUp()` event (it is different than the last `touchDragged()` reported value/position).

The reason is that the following lines of the method `boolean calculatePositionAndValue (float x, float y)` that determine the value/position of ther slider dependind on the user input position also depend on the active style knob Drawable size:
```
// Gets active style know Drawable
final Drawable knob = getKnobDrawable();
[...]
float knobWidth = knob == null ? 0 : knob.getMinWidth();
position = x - bg.getLeftWidth() - knobWidth * 0.5f;
``` 

So, while dragging the knob of the Slider to select a value, internally it keeps calling `calculatePositionAndValue()` and because the knob Drawable is always the large knobDown Drawable it keeps conistent.
The moment a `touchUp()` occurs, `calculatePositionAndValue()` is called again but this time the knob `Drawable` is smaller and the reported value/position changes making it inconsistent.

A simple way to observe this issue is by adding a `ChangeListener` to the `Slider` and print its `value` on the `onChange` implementation.

**Comment by NathanSweet** [comment]
Can you show code for reproducing? Maybe just an edit to UITest?

**Comment by obigu** [comment]
Sure @NathanSweet .

Just 2 edits required.
1. Edit the step size on `UITest` to 0.001f.
```
final Slider slider = new Slider(0, 10, 0.001f, false, skin);
```
2. Edit uiskin.json to add a knob-down style
```
SliderStyle: {
	default-horizontal: { parent: default-horizontal, "knobDown": tree-plus },
	default-vertical: { parent: default-vertical }
},
```

Now just run UITest and touch down the knob slider and then release without moving the mouse.

**Comment by NathanSweet** [comment]
Thanks! See if that works for you.

**Comment by obigu** [comment]
Works great, thanks!
