### ISSUE TITLE
[Bug] TextField Tab-Focus works different on Unix systems, reacts on ENTER-Button

### ISSUE THREAD

**Issue by Monarchis** [libgdx/libgdx#5908]
These 2 lines define not correctly the ENTER button of Desktop/Android systems:
https://github.com/libgdx/libgdx/blob/11a53e2d9d573e2a0a94457b309dbf7044623497/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextField.java#L67-L68
Unix: \n
Windows: \r\n (so \r is ok for windows)
Mac: \n (old Macs \r)
Android: \n

This Line needs an additional check if it's an android system:
https://github.com/libgdx/libgdx/blob/11a53e2d9d573e2a0a94457b309dbf7044623497/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TextField.java#L1027-L1028
otherwise, the ENTER button on Unix-Desktop systems will have the same behavior like the TAB button.
Something like:
`if ( (character == TAB || (isAndroid && character == ENTER_ANDROID)) ) && focusTraversal)`
would solve the problem.

**Comment by cpbeto** [comment]
This also affects `TextArea` which extends `TextField`.

On the Linux system I'm working on, pressing the ENTER key fails to add a new line (a hotfix I'm using is doing `setFocusTraversal(false)`). I'm guessing the same is true for all Unix systems, even Android.

Perhaps we could split up the conditional and distinguish between TAB and ENTER.`TextArea` constructor could disable focus traversal for the ENTER key.

**Comment by Monarchis** [comment]
#5910 continues this. /closed

**Comment by Monarchis** [comment]
Approved by #5910
