### ISSUE TITLE
Lack of information about obtaining nightly builds via gradle

### ISSUE THREAD

**Issue by thechubbypanda** [libgdx/libgdx#5911]
Please ensure you have given all the following requested information in your report.

#### Issue details
Lack of information about obtaining nightly builds via gradle.
I cannot find the sonatype nightly repo anywhere to put into a maven repository for gradle.
Perhaps we need to be building to a repository every day if we're not?

#### Version of LibGDX and/or relevant dependencies
Latest

#### Please select the affected platforms
- [x] Android
- [x] iOS (robovm)
- [x] iOS (MOE)
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by SimonIT** [comment]
Read here https://github.com/libgdx/libgdx/wiki/Updating-LibGDX#switching-libgdx-versions

**Comment by thechubbypanda** [comment]
I have read that page, it does not give any URLs of snapshot repositories or anything relating.
Attempting to obtain `1.9.11-SNAPSHOT` from maven central returns an error.

**Comment by Darkyenus** [comment]
I agree with this, the libgdx maven coordinates (and repo url for snapshots) should be more visible. I know that it is somewhere on the wiki (or at least it was), but it should be more visible. We could even add a maven badge to the readme or to the wiki.

Also it seems that the link in the README for "Working with the Source" is half dead - it points to https://github.com/libgdx/libgdx/wiki/Running-demos-%26-tests which is supposedly deprecated and links to https://libgdx.badlogicgames.com/documentation/hacking/Working%20from%20source.html. I didn't even know that there is documentation on badlogicgames.com.

**Comment by Monarchis** [comment]
You also could use (example from https://blog.gradle.org/introducing-source-dependencies):
```
dependencies {
    implementation 'org.gradle.cpp-samples:utilities:1.0'
}
```
and
```
sourceControl {
    gitRepository("https://github.com/gradle/native-samples-cpp-library.git") {
        producesModule("org.gradle.cpp-samples:utilities:1.0")
    }
}
```

**Comment by MobiDevelop** [comment]
Doesn't the project setup include the snapshot repo?

**Comment by Monarchis** [comment]
@MobiDevelop not anymore.

![gdx-setup](https://user-images.githubusercontent.com/2159235/74277232-71f9bc00-4d17-11ea-9f25-3276a058f11f.jpg)

**Comment by mgsx-dev** [comment]
it is, see [here](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-setup/src/com/badlogic/gdx/setup/DependencyBank.java#L40) and [here](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-setup/src/com/badlogic/gdx/setup/BuildScriptHelper.java#L38)

A badge in README is a good idea.

**Comment by Monarchis** [comment]
@mgsx-dev yes i mentioned that it isn't displayed on the gui anymore.

**Comment by noblemaster** [comment]
New badges have been merged.

**Comment by NathanSweet** [comment]
This issue comes up first in web search, so for fellow searchers this is what you need:
```
repositories {
    mavenCentral()
    maven {
        url 'https://central.sonatype.com/repository/maven-snapshots'
    }
}
dependencies {
    implementation group: 'com.badlogicgames.gdx', name: 'gdx', version: '1.13.6-SNAPSHOT'
}
```
