### ISSUE TITLE
[Feature] Ordered Texture Packer

### ISSUE THREAD

**Issue by abueide** [libgdx/libgdx#5913]
So I have a bunch of images structured like this:
assets/
    - unpacked/
        - 0.png/
        - 1.png
        - 3.png
        - 5.png

And I need to generate a sprite sheet where the sprite layout is as following: 
0,0 -> 0.png
0,1 -> 1.png
0,2 -> transparent fill
1,0 -> 3.png
1,1 -> transparent fill
1,2 -> 5.png

This is useful because it lets me create an ordered organized sprite sheet that I can import into tiled to make maps, and then later use the TiledMapPacker in order to create an optimized atlas for running the game with.

I want to implement this feature but I wanted to get your guys' thoughts about whether this is too specific to be included in main branch with a PR, or if I'm just missing something that would allow me to do this.

**Comment by mgsx-dev** [comment]
@abueide did you tried [TiledMapPacker](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-tools/src/com/badlogic/gdx/tiledmappacker/TiledMapPacker.java)?

For the "grid layout", I think you can use Gimp and such (maybe with plugins).

**Comment by MobiDevelop** [comment]
If you're going to use TiledMapPacker anyway, why not just use the image collection version of a tileset? No sense packing it into a grid if you're just going to process (and pack) it again.

**Comment by abueide** [comment]
I ended up just writing a script to fill in the missing images with blank png files, then using TexturePacker with grid enabled, alias & ignoreBlankImages to false. Maybe not the best solution, but it was becoming really time consuming to find a better way to do it.
