### ISSUE TITLE
gdx-setup in cli mode is trying to generate project using an incompatible Gradle version and fails. It succeds in GUI mode.

### ISSUE THREAD

**Issue by matkoniecz** [libgdx/libgdx#5917]
To summarize: you must include `--excludeModules "ios;iosmoe"` as even with excluded ios it will still want iosmoe that is needed only for ios. Quotes are necessary at least on Linux to prevent `;` from terminating the command.

-----

Please ensure you have given all the following requested information in your report.

#### Issue details
```
java -jar gdx-setup.jar --dir libgdxtest --name drop --package com.badlogic.drop --mainClass Drop --sdkLocation /home/mateusz/Android/Sdk --excludeModules ios
Executing '/home/mateusz/Downloads/libgdxtest/gradlew clean'

> Configure project :
Using already downloaded SDK: /home/mateusz/.moe/moe-sdk-1.4.0

FAILURE: Build failed with an exception.

* Where:
Build file '/home/mateusz/Downloads/libgdxtest/build.gradle' line: 84

* What went wrong:
A problem occurred evaluating root project 'libgdxtest'.
> 'void org.gradle.api.tasks.compile.CompileOptions.setBootClasspath(java.lang.String)'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
```

From looking at https://discuss.gradle.org/t/5-1-1-setbootclasspath-issue/30169 it seems to be caused by using an incompatible Gradle as in 5+ `setBootClasspath` is gone

Curiously, I run gdx setup jar in GUI mode previously and I hit much more smaller bug (#5916)

I now rerun it in the GUI mode

![screen03](https://user-images.githubusercontent.com/899988/75091285-f3e5b280-556b-11ea-8e3a-5046ccb14858.png)

and at least general generation worked. I suspect that somehow parameters are different but I am missing what is changed.

GUI generated repo is at https://github.com/matkoniecz/libgdx-fuller-crash-without-crash-because-GUI

#### Reproduction steps/code
`java -jar gdx-setup.jar --dir libgdxtest --name drop --package com.badlogic.drop --mainClass Drop --sdkLocation /home/mateusz/Android/Sdk --excludeModules ios`

https://github.com/matkoniecz/libgdx-fuller-crash

#### Version of LibGDX and/or relevant dependencies
https://github.com/libgdx/libgdx/wiki/Project-Setup-Gradle appears to generate projects with LibGDX 1.9.10 (`gdxVersion = '1.9.10'`)

#### Stacktrace
https://gist.github.com/matkoniecz/40b05052d72b970dc01a161f140bece7

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] MacOS

#### More platform info

```
mateusz@grisznak:~/Downloads/libgdx_test$ uname -a
Linux grisznak 5.3.0-40-generic #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
mateusz@grisznak:~/Downloads/libgdx_test$ java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu119.10.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu119.10.1, mixed mode, sharing)
```

**Comment by tommyettinger** [comment]
This is a legitimate bug in gdx-setup, but it's easy enough to work around. You exclude ios already from the generated project, but for some reason MOE (an outdated alternative to the working ios platform) is still enabled by default for command line builds only. It's enabled, but as you have seen, it's broken. Can you try this, maybe? You may need to change the dir to an empty one.
```
java -jar gdx-setup.jar --dir libgdxtest --name drop --package com.badlogic.drop --mainClass Drop --sdkLocation /home/mateusz/Android/Sdk --excludeModules ios;iosmoe
```
All I added was `;iosmoe` at the end.

**Comment by matkoniecz** [comment]
For some reason it wants `iosmoe` anyway

```
java -jar gdx-setup.jar --dir libgdxtest --name drop --package com.badlogic.drop --mainClass Drop --sdkLocation /home/mateusz/Android/Sdk --excludeModules ios;iosmoe
Executing '/home/mateusz/Downloads/libgdxtest/gradlew clean'
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
Using already downloaded SDK: /home/mateusz/.moe/moe-sdk-1.4.0

FAILURE: Build failed with an exception.

* Where:
Build file '/home/mateusz/Downloads/libgdxtest/build.gradle' line: 84

* What went wrong:
A problem occurred evaluating root project 'libgdxtest'.
> 'void org.gradle.api.tasks.compile.CompileOptions.setBootClasspath(java.lang.String)'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s
iosmoe: command not found
```

**Comment by tommyettinger** [comment]
Oh wow, they should not have used semicolons to delimit exclusions... the semicolon is acting as a signal to your terminal that the command is over and a new one is starting. That's why at the end, it says
```
iosmoe: command not found
```
You can try putting both of the exclusions in double quotes (or maybe single quotes), like `--excludeModules "ios;iosmoe"` , but I don't know enough about Linux terminals to offer much besides "there's probably a way to escape the semicolon."

**Comment by matkoniecz** [comment]
Yes, now at least generation worked! Not sure is it a good idea to close it or open, I will not close it for now.

**Comment by matkoniecz** [comment]
To summarize: you must include `--excludeModules "ios;iosmoe"` as even with excluded ios it will still want iosmoe that is needed only for ios. Quotes are necessary at least on Linux to prevent `;` from terminating the command.

**Comment by mgsx-dev** [comment]
as you can see [here](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetupUI.java#L530) IOS MOE is disabled in GUI mode, it was done during [gradle migration commit](https://github.com/libgdx/libgdx/commit/d01650da6c4910f1deb4263493708da6d02db751) but not in CLI mode, as you can see [here](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-setup/src/com/badlogic/gdx/setup/GdxSetup.java#L671).
In this end, i'm not sure if IOS MOE should be totally removed or not.
@Tom-Ski ?

**Comment by shatterblast** [comment]
iOS MOE is still needed.  Keep it, please.

**Comment by Tom-Ski** [comment]
Yes we should probably just remove moe at this point. But if people are still somehow using it, then there hsould be an option to target it. @shatterblast you are using moe? If so, how? With what versions? Last time I checked support was completely dropped and this was no longer functioning with latest ios and IDEs.

**Comment by shatterblast** [comment]
Honestly, no.  I am not using moe.  However, it seems only targeted at iOS at this point.

Is RoboVM totally independent from moe now?  I thought not, but I could be wrong.  I know RoboVM can act separate, but I was in the belief that RoboVM still draws from moe for reference?

Otherwise, you are right.  I don't need it myself.

**Comment by crykn** [comment]
iOS moe is discontinued. Closing this.
