### ISSUE TITLE
Incorrect loop conditions in hash-based collections

### ISSUE THREAD

**Issue by tommyettinger** [libgdx/libgdx#5928]
Please ensure you have given all the following requested information in your report.

#### Issue details
This is a continuation of #5919 , since the same commit that introduced that bug also introduced this one. In what was probably an attempt to simplify some nasty for loops in https://github.com/libgdx/libgdx/commit/a4646767699501745cdd44ae0e5946d9296a2ce6 , the code
```java
for (int i = valueTable.length; i-- > 0; )
```
in the containsValue() and findKey() methods across all hash-based sets and maps was changed to the non-equivalent and incorrect code
```java
for (int i = valueTable.length - 1; i > 0; i--)
```

The bug is that `valueTable[0]` never gets checked with this change, even though it's a valid location in the table. **The fix** is just changing the condition to `i >= 0` in the many files that have the bug. It would make sense to "Find in Files" for `for (int i = valueTable.length - 1; i > 0; i--)` to locate probable problems.

#### Reproduction steps/code
Reproducing an actual bug from this is hard; it would manifest as a mystery bug where some item might never be found by containsValue() despite being present. I found it using Apache Harmony's JUnit tests, which are quite old, quite ugly, and probably not optimal, but are license-compatible with libGDX and the Apache 2 license, unlike OpenJDK's tests. The specific test is https://github.com/tommyettinger/merry-ds/blob/master/src/test/java/ds/merry/ObjectMapTest.java#L156-L170 . All tests passed with a version of the hash-based data structures from before the earlier-mentioned commit, and only that test (and a similar one for OrderedMap) failed after. When I made the change to `i >= 0`, that let the tests pass.

#### Version of LibGDX and/or relevant dependencies
Current nightly, 1.9.11-SNAPSHOT .

#### Stacktrace
None, a test fails, it just isn't a libGDX test. That means any stack trace I could give would have incorrect line numbers. The fix is easy anyway.

#### Please select the affected platforms
- [x] Android
- [x] iOS (robovm)
- [x] iOS (MOE)
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by NathanSweet** [comment]
Ah, good find!
