### ISSUE TITLE
Sound and Music do not function on iPhone 11 in HTML5/GWT game.

### ISSUE THREAD

**Issue by raeleus** [libgdx/libgdx#5954]
#### Issue details
Sound and Music do not function on iPhone 11 when running an HTML5/GWT game. I am aware of the pitfalls of playing audio on mobile devices, and I'm careful to only play sounds when there is a touch interaction from the user. This technique works on older iOS devices. However, I received a new iPhone 11 for testing and I can't get any Music or Sound to play at all or it will play a sound once and nothing else afterwards.

#### Reproduction steps/code
Please consider this very basic test class:
```java
package com.mygdx.game;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.InputAdapter;
import com.badlogic.gdx.audio.Sound;
import com.badlogic.gdx.graphics.GL20;

public class MyGdxGame extends ApplicationAdapter {
	Sound sound;
	
	@Override
	public void create () {
		sound = Gdx.audio.newSound(Gdx.files.internal("correct.mp3"));
		
		Gdx.input.setInputProcessor(new InputAdapter() {
			@Override
			public boolean touchDown(int screenX, int screenY, int pointer, int button) {
				sound.play();
				return super.touchDown(screenX, screenY, pointer, button);
			}
		});
	}

	@Override
	public void render () {
		Gdx.gl.glClearColor(0, 1, 1, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
	}
}
```
Place the attached MP3 file into the assets folder and run the HTML5 project. Tap the game screen. It should play the sound every time you tap on all platforms. On an iPhone 11 and possibly other hardware, it may play the sound once and never again.

[correct.zip](https://github.com/libgdx/libgdx/files/4335503/correct.zip)

#### Version of LibGDX and/or relevant dependencies
1.9.10
1.9.11-SNAPSHOT

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [x] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by shatterblast** [comment]
I'm curious if this has anything to do with OpenAL. There is a generic switch towards that happening in the hardware ecosystem, and I think Apple tends to be super slow when updating their hardware in that regard.  I believe future Apple devices will handle the problem, but I'm not sure about now.

**Comment by crykn** [comment]
@raeleus Could you try whether the issue persist if you're using the web audio implementation in #5659? A jitpack dependency is linked in the first post there.

**Comment by raeleus** [comment]
I've tried that one and it still doesn't work. Thanks for mentioning it
though.

**Comment by MrStahlfelge** [comment]
You need to use WebAudio to get it working. #5659 or switch to the GWT backend mentioned there.

**Comment by MrStahlfelge** [comment]
New audio backend is now in place, closing sound related issues now. I made sure that Safari and Safari Mobile work with the new audio backend. If you still experience problems with it, please reopen with a full test environment (audio files included or public available on a web server)
