### ISSUE TITLE
difficulties in updating old projects [enhancement]

### ISSUE THREAD

**Issue by Rami-Majdoub** [libgdx/libgdx#5957]
It is very hard to tell what to update.
It would be very cool if there was a command to update the old projects to the newest version.
I was trying to update a project generated by libGDX v 1.9.9 (Gradle distribution 4.10.1) and I had many Gradle issues.

**Comment by Tom-Ski** [comment]
https://libgdx.badlogicgames.com/versions.html shows the versions that are used in the current snapshots and release verisons. These are known compatible versions, so you can use these with the Gradle version that is provided by the setup tool.

**Comment by Rami-Majdoub** [comment]
I have changed the versions and sync the project but it didn't compile.
there have been some changes in the Gradle files (deprecated methods and code that has been deleted)

**Comment by tommyettinger** [comment]
It's much, much easier to generate a new empty project and copy your old code/assets into that, making any changes to build files that your project needs. LibGDX is using an older version of Gradle than the current latest, to get better compatibility with Android build tools, but there are still necessary changes to the Gradle files that should be re-generated by setup. Because people generally customize their build.gradle scripts, I don't see any reasonable way to automatically update a Gradle project.

**Comment by Rami-Majdoub** [comment]
that's what I do, but I have older projects and it is frustrating to generate a new project, copy-paste all the code, to remember every modification and to do it again.

**Comment by RUSshy** [comment]
gradle sucks, but that is what Java world and Jetbrains choosed.. sadly

https://docs.gradle.org/current/userguide/upgrading_version_4.html#for_all_users

check this official guide for upgrading from old to newest version of gradle

**Comment by shatterblast** [comment]
Gradle 4.8 should be safe enough, and it support Java 11.

**Comment by tommyettinger** [comment]
Gradle 4.8 is pretty old, though if it works, it works. Most libGDX developers are using JDK 8 anyway unless they target desktop only. The concern is with Java 14 becoming the new LTS version (has this already happened?); Gradle 6.3 or higher is required to support Java 14, and there are actual new useful features in this Java version. Last I checked, Gradle 6.3 was still in a release candidate version.

IntelliJ Community does allow building GWT applications just fine; it doesn't debug them especially well (you can use superDev and step through in a browser though) and it doesn't recognize some GWT conventions out of the box (like the `super` folder for super-sourced code, which libGDX uses), but you can run the Gradle GWT tasks like you can from anywhere.

**Comment by shatterblast** [comment]
Java 14 is not LTS, and it was just announced.  Java 11 will continue as the standard for now, so Gradle 4.8 should be fine.

**Comment by brettdorrans** [comment]
If your project only targets desktop, then it is safe to upgrade to gradle 6.x and Java 14. I have done this on my project with minimal issues. Note that some dependencies may cause problems, but LibGDX itself compiles and works fine under Java 14 and gradle 6.x.

**Comment by NathanSweet** [comment]
I don't think we have time to create such an enhancement, sorry.
