### ISSUE TITLE
Question about removing "armeabi" and "x86" natives in Android

### ISSUE THREAD

**Issue by DavidPDev** [libgdx/libgdx#5958]
Hi, I was wondering if we still (in 2020) need to support "armeabi" and "x86" natives in Android.
Since 1 Ago 2019 Google Play only supports 64bits Apps.
https://developer.android.com/distribute/best-practices/develop/64-bit

So, do you think it's safe to remove both natives in the final "Generate Signed apk" build for a new game?

![image](https://user-images.githubusercontent.com/25801199/77106803-fa0e6800-6a1f-11ea-87e6-0692692f8dbd.png)

We benefit from a smaler .apk (1Mb less) and speed up the build time.
Maybe we could even remove it from the gdx-setup.jar
What do you think about this?

#### Version of LibGDX and/or relevant dependencies
libGDX 1.9.10 with freeType

#### Please select the affected platforms
- [X] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by obigu** [comment]
armeabi architectures are really old and totally safe to remove from your builds, specially considering the current min SDK is 14. I agree we could remove it from Gdx setup alltogether.

Regarding x86 the fact that Google Play requires support for 64 bits is different from "only" supports 64 bits. If you want to support x86 (not many devices) I think you will need both, 32 bit and 64 bits versions (see the table https://developer.android.com/distribute/best-practices/develop/64-bit#64-bit-libraries).

**Comment by MobiDevelop** [comment]
There are Chromebooks using x86 that support Android apps.

**Comment by yuripourre** [comment]
I do not have an opinion about removing x86 yet. Specially because is possible to run x86 Android emulators much faster than arm architectures.
Regarding the size, I've being using .obb instead of .apk to release apps, and Google takes care of distribute the right .so version for each user, and the app has the size diminished.
Let's see what others think about it.

**Comment by DavidPDev** [comment]
Thank you very much for your replies.
About the emulators for x86, I'm sure everyone uses (or should use) the x86_64 version of the emulator on modern OSs. Also the main goal is the final deployment to Play Store, maybe in debug phase we can still use the x86 native in case you have x86 emulators.

But, I need your help, now, I have a problem when trying to generate the signed .apk removing "armeabi" and "x86" natives.
I've done two changes in the files generates by the Gdx-setup.

1) build.gradle (main) -> Commented the following lines
![image](https://user-images.githubusercontent.com/25801199/77150487-4abfa880-6a94-11ea-89b8-b675dd023952.png)

2) build.gradle (Android) -> Commented the following lines
![image](https://user-images.githubusercontent.com/25801199/77150603-86f30900-6a94-11ea-9bcd-9a1efccc3887.png)

Next step: Clean project, invalidate caches+restart, rebuild project, and "Generate signed apk"
and the resulting .apk still contains the folders "armeabi" and "x86" in the lib folder.

Am I missing something?

Thank you in advance.

**Comment by EtK2000** [comment]
I actually build multiple APKs based off ABI, and that works well for me.

I don't know if they should be removed, but they should be ready to go within the next year imo.

**Comment by DavidPDev** [comment]
Please @EtK2000 can you explain (or a link) on how to generate the .apk without the "armeabi" and "x86". Thanks.

**Comment by obigu** [comment]
You probably have not manually deleted the folder from `android/libs`.

**Comment by shatterblast** [comment]
From my understanding, Android TV support for controllers leans better for those that use 64-bit.  You tend to not see good controller support on 32-bit versions, although it exists a little.

**Comment by DavidPDev** [comment]
> You probably have not manually deleted the folder from `android/libs`.

Thanks @obigu! That was the trick. I had to remove both folders from my local project.

**Comment by shatterblast** [comment]
I currently test the following code through the Google Play Console.  This should properly remove the armeabi natives.  It seemed to work fine on my Android 7.1.1 emulator, but I sent it up in my current game in an Alpha run to see how it would work.  The Crash Analytics should give me a decent response.

Please, note that the following code has the Allatori protection part removed.  It might not take into account other forms of protection.

`android {
    buildToolsVersion androidBuildTools
    compileSdkVersion androidCompileSdk
    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }
    }

    packagingOptions {
        exclude 'META-INF/robovm/ios/robovm.xml'
        pickFirst "META-INF/DEPENDENCIES"
    }

    defaultConfig {
        buildConfigField "int", "primaryApkExpansion", primaryApkExpansionVersion

        multiDexEnabled true
        applicationId "com.weslange"
        minSdkVersion androidMinSdk
        targetSdkVersion androidTargetSdk
        versionCode executableVersion

        //This matters for the Google Play Console when Publishing.
        versionName executableVersionAsString

        javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath = false
            }
        }

        testInstrumentationRunner "android.test.InstrumentationTestRunner"
        testOptions {
            unitTests.returnDefaultValues = true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}


//This takes the dependencies of configurations.natives and extracts them to the proper folders.
//It allows packing the necessary dependencies with the APK.
task copyAndroidNatives() {
    //file("libs/armeabi/").mkdirs();
    //file("libs/armeabi-v7a/").mkdirs();
    file("libs/arm64-v8a/").mkdirs();
    file("libs/x86_64/").mkdirs();
    //file("libs/x86/").mkdirs();

    configurations.natives.files.each { jar ->
        def outputDir = null
        if (jar.name.endsWith("natives-arm64-v8a.jar")) outputDir = file("libs/arm64-v8a")
        //if (jar.name.endsWith("natives-armeabi-v7a.jar")) outputDir = file("libs/armeabi-v7a")
        //if (jar.name.endsWith("natives-armeabi.jar")) outputDir = file("libs/armeabi")
        if (jar.name.endsWith("natives-x86_64.jar")) outputDir = file("libs/x86_64")
        //if (jar.name.endsWith("natives-x86.jar")) outputDir = file("libs/x86")
        if (outputDir != null) {
            copy {
                from zipTree(jar)
                into outputDir

                include "*.so"
            }
        }
    }
}


task run(type: Exec) {
    def path
    def localProperties = project.file("../local.properties")
    if (localProperties.exists()) {
        Properties properties = new Properties()
        localProperties.withInputStream { instr ->
            properties.load(instr)
        }
        def sdkDir = properties.getProperty('sdk.dir')
        if (sdkDir) {
            path = sdkDir
        } else {
            path = "$System.env.ANDROID_HOME"
        }
    } else {
        path = "$System.env.ANDROID_HOME"
    }

    def adb = path + "/platform-tools/adb"
    commandLine "$adb", 'shell', 'am', 'start', '-n', 'com.weslange/com.weslange.AndroidLauncher'
}


//This sets up the Android module.
idea {
    module {
        sourceDirs += file("src");
        scopes = [COMPILE: [plus: [project.configurations.compile]]]

        iml {
            withXml {
                def node = it.asNode()
                def builder = NodeBuilder.newInstance();
                builder.current = node;
                builder.component(name: "FacetManager") {
                    facet(type: "android", name: "Android") {
                        configuration {
                            option(name: "UPDATE_PROPERTY_FILES", value: "true")
                        }
                    }
                }
            }
        }
    }
}


dependencies {
}`

**Comment by shatterblast** [comment]
The tests came back successful.  I had no problems with APIs 16 through 28.  The AndroidX code seems to work, and the armeabi code should not be required by default.  Please, note that this will likely still affect APIs 14 and 15 more, but I no longer target them.

**Comment by DavidPDev** [comment]
Thank for your reply and tests @shatterblast !

Have you verified that in the resulting .apk (you can rename it to .zip) are actually removed the three folders you have commented ("libs/armeabi-v7a","libs/armeabi","libs/x86") ?

I had to mnually remove them in my local project before generating the signed apk.

**Comment by shatterblast** [comment]
No.  They were still in the APK.  I will re-try that.

**Comment by obigu** [comment]
Guys please, move this discussion to Discord, I think @DavidPDev your "issue" is resolved.

**Comment by DavidPDev** [comment]
Ok, I close the "Issue", was more a question, and maybe a hint to remove old natives in future libGDX versions. Thank you!

**Comment by DavidPDev** [comment]
@shatterblast : Any updates about your tests with the new .apk (removing old natives)?

**Comment by shatterblast** [comment]
Yes.  I got it to work successfully, but Android still needs it.

**Comment by DavidPDev** [comment]
Ok, Thank you! but maybe all those 6000 devices are ver low-specs devices and users will have a poor game experience anyways, so I think that not targeting all that devices is not so bad.

**Comment by shatterblast** [comment]
It's very common for a low-spec device to have 500 MB of available RAM.  My own game still caters to that.  Now, if your own game targets API 24 and above, then that might work out better for you.  Otherwise, there were only about 4,000 devices that could run the game without the Armeabi natives.

It may take two years minimum or more for LibGDX as a whole to not need Armeabi.  For the moment, it should definitely stay.

**Comment by obigu** [comment]
What does RAM have to do with this? What performance increase are talking about on 1.9.11-SNAPSHOT that is related to this issue?

Your claims are wrong. I've just tested adding a removing armeabi architecture on an app with min SDK 15 and there are 0 devices that don't support Armeabi v7 architecture that require the older v5 or v6 (armeabi). So it doesn't make a difference to remove armeabi libraries in terms of device supported.

It's 100% safe to remove armeabi architecture support from libGDX right now.

**Comment by shatterblast** [comment]
No.  It's not safe.  What tests did you run?

**Comment by obigu** [comment]
Tested on Google Play console. Why would you remove v7?? If you do remove v7 of course you will not support lots of devices.

It doesn't make a difference on SDK 14 or 15, that's not a valid point either. I won't discuss this any further here.

**Comment by shatterblast** [comment]
I will try again later.

**Comment by DavidPDev** [comment]
Thanks both!, Yes, as @obigu said, I was only thinking on removing the "armeabi" natives, an maybe the "x86" too. Of course **we can't** remove the "armeabi-v7" as there are still many devices with that specs.

**Comment by DavidPDev** [comment]
Just for documentation:
@obigu commited (https://github.com/libgdx/libgdx/pull/5982) an update on the build template removing "armeabi" natives.

**Comment by PokeMMO** [comment]
A much cleaner solution without requiring you to manually delete/remove any natives (including from other dependencies) is to use the [abiFilters](https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.NdkOptions.html) option in your gradle config.

**Comment by yuripourre** [comment]
@PokeMMO Nice catch! That would be interesting to exclude x86 for example.

**Comment by EtK2000** [comment]
That's what I've been doing.
