### ISSUE TITLE
AttributeError: 'CellVariables' object has no attribute 'getOld', fipy and Ipython

### ISSUE THREAD

**Issue by Minjun-Bae** [libgdx/libgdx#5972]
Hello all,

I am a python beginner, who is using window10. 

I have been trying to practice some examples from the article, 'FiPy: Partial Differential Equation with Python'. 

In an attempt to reproduce their simulations, I found that every time I try to get access an attribute by using the attribute reference syntax form, AttributeError: 'CellVariable' object has no attribute '___' error. 

Below is my code, which I followed the exact same procedure with the code the article provided. 

****`from fipy import *
dx = dy = 0.025
nx = ny = 500
mesh = Grid2D(dx=dx, dy=dy, nx=nx, ny=ny)
dt = 5e-4
phase = CellVariable(name=r’$\phi$’, mesh=mesh, hasOld=True)
dT = CellVariable(name=r’$\Delta T$’,mesh=mesh, hasOld=True)
DT = 2.25
heatEq = (TransientTerm() == DiffusionTerm(DT) + (phase - phase.getOld()) / dt)`****

And I am getting error such as:

`AttributeError                            Traceback (most recent call last)
<ipython-input-10-349410194f2e> in <module>
----> 1 heatEq = (TransientTerm() == DiffusionTerm(DT) + (phas - phas.getOld()) /dt)

AttributeError: 'CellVariable' object has no attribute 'getOld''

I thought the problem might come from the way anaconda installs things. For this reason, I uninstall and reinstalled the ipython and related files by using pip. 
The problem still remains existent. 

If anybody could help me with this issue, it would be very much appreciated.

Please let me know if I could provide more information regarding this.

Thanks in advance.

**Comment by Minjun-Bae** [comment]
> Hello all,
> 
> I am a python beginner, who is using window10.
> 
> I have been trying to practice some examples from the article, 'FiPy: Partial Differential Equation with Python'.
> 
> In an attempt to reproduce their simulations, I found that every time I try to get access an attribute by using the attribute reference syntax form, AttributeError: 'CellVariable' object has no attribute '___' error.
> 
> Below is my code, which I followed the exact same procedure with the code the article provided.
> 
> ****`from fipy import * dx = dy = 0.025 nx = ny = 500 mesh = Grid2D(dx=dx, dy=dy, nx=nx, ny=ny) dt = 5e-4 phase = CellVariable(name=r’$\phi$’, mesh=mesh, hasOld=True) dT = CellVariable(name=r’$\Delta T$’,mesh=mesh, hasOld=True) DT = 2.25 heatEq = (TransientTerm() == DiffusionTerm(DT) + (phase - phase.getOld()) / dt)`****
> 
> And I am getting error such as:
> 
> `AttributeError Traceback (most recent call last)
> in 
> ----> 1 heatEq = (TransientTerm() == DiffusionTerm(DT) + (phas - phas.getOld()) /dt)
> 
> AttributeError: 'CellVariable' object has no attribute 'getOld''
> 
> I thought the problem might come from the way anaconda installs things. For this reason, I uninstall and reinstalled the ipython and related files by using pip.
> The problem still remains existent.
> 
> If anybody could help me with this issue, it would be very much appreciated.
> 
> Please let me know if I could provide more information regarding this.
> 
> Thanks in advance.

**Comment by SimonIT** [comment]
How is this related to libgdx?

**Comment by EtK2000** [comment]
Unrelated to libGDX.
Request for closure.
