### ISSUE TITLE
Cherrydaniels21@gmail.com

### ISSUE THREAD

**Issue by johnnydoe2020** [libgdx/libgdx#5973]
Issue details 

Your camera needs to be updated ,we are having a lot of malfunctions on Google due to the corona19 virus,please help us assist you 
Even if you think your issue is trivial to reproduce,  This saves time on our end, and makes it much more likely that your issue will be fixed.

Thank you ,
 **@Google.com**

****

**Comment by Tom-Ski** [comment]
Dear google, we have fixed all the virus related issues.
