### ISSUE TITLE
I'm affected on libgdx 1.9.6. It happens with chrome while it works fine with firefox.

### ISSUE THREAD

**Issue by SWITCHAccess** [libgdx/libgdx#5974]
I'm affected on libgdx 1.9.6. It happens with chrome while it works fine with firefox.

_Originally posted by @smelc in https://github.com/libgdx/libgdx/issues/5134#issuecomment-385496568_

**Comment by shatterblast** [comment]
Then update to 1.9.9 or higher.

**Comment by EtK2000** [comment]
If it's related to another issue, please choose this issue.
If it's unique, please edit the title to reflect such.
