### ISSUE TITLE
Unable to initialize main class com.mygdx.game.desktop.DesktopLauncher

### ISSUE THREAD

**Issue by hires** [libgdx/libgdx#5977]
#### Issue details
I'm trying to use libgdx on Linux with Eclipse 2019-12 but it doesn't work. I used the setup tool to make a desktop-only application and imported it into Eclipse by importing a Gradle project. When trying to run the DesktopLauncher main class I get the following error:

`Error: Unable to initialize main class com.mygdx.game.desktop.DesktopLauncher
Caused by: java.lang.NoClassDefFoundError: com/badlogic/gdx/ApplicationListener`

I would expect since this is a new project that I didn't mess with that it would at least run properly. I just want to see something work in my dev environment so I can experiment with it. I'm using Java: openjdk 11.0.6 2020-01-14

#### Version of LibGDX and/or relevant dependencies
Whatever is the version the tool downloaded for me... some of the dependencies say 1.9.10.

_Please provide the version(s) affected._

- [X ] Linux

**Comment by hires** [comment]
Further to the previous post, it seems like the Gradle build is broken due to missing files. Is there a maven solution to this? It would be a whole lot easier.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':desktop:compileJava'.
> Could not resolve all files for configuration ':desktop:compileClasspath'.
   > Could not find gdx-platform-natives-desktop.jar (com.badlogicgames.gdx:gdx-platform:1.9.10).
     Searched in the following locations:
         file:/home/andrew/.m2/repository/com/badlogicgames/gdx/gdx-platform/1.9.10/gdx-platform-1.9.10-natives-desktop.jar
   > Could not find gdx-box2d-platform-natives-desktop.jar (com.badlogicgames.gdx:gdx-box2d-platform:1.9.10).
     Searched in the following locations:
         file:/home/andrew/.m2/repository/com/badlogicgames/gdx/gdx-box2d-platform/1.9.10/gdx-box2d-platform-1.9.10-natives-desktop.jar
   > Could not find gdx-controllers-platform-natives-desktop.jar (com.badlogicgames.gdx:gdx-controllers-platform:1.9.10).
     Searched in the following locations:
         file:/home/andrew/.m2/repository/com/badlogicgames/gdx/gdx-controllers-platform/1.9.10/gdx-controllers-platform-1.9.10-natives-desktop.jar
   > Could not find gdx-freetype-platform-natives-desktop.jar (com.badlogicgames.gdx:gdx-freetype-platform:1.9.10).
     Searched in the following locations:
         file:/home/andrew/.m2/repository/com/badlogicgames/gdx/gdx-freetype-platform/1.9.10/gdx-freetype-platform-1.9.10-natives-desktop.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
3 actionable tasks: 1 executed, 2 up-to-date

**Comment by mgsx-dev** [comment]
it sounds like an issue with your setup, maybe not related to libgdx. Better ask for help in Discord or Stackoverflow.

**Comment by hires** [comment]
I'm not sure how missing files from the gdx setup tool could be a problem with my setup... all the other requires files appear to be there, but it seems to have failed to download everything. Thanks anyway.

**Comment by mgsx-dev** [comment]
yeah, sometimes there are some conflicts between local .m2 (maven) and gradle cache. Removing .m2 may fix it.
