### ISSUE TITLE
Desktop launches no window but has no errors.

### ISSUE THREAD

**Issue by TheSwerik** [libgdx/libgdx#5978]
#### Issue details
I have a new PC:
* Windows 10 Pro 64bit
* RTX 2060 super
* Ryzen 7 3700X

and on this PC none of my projects will start (it doesn't matter if LWJGL3 or 2).
No window opens and the console instantly displays:
> Task execution finished 'DesktopLauncher.main()'.

It runs perfectly fine on my Laptop (Intel CPU and integrated graphics).

#### Reproduction steps/code
Any Projects, just try and run the desktop application.

#### Version of LibGDX and/or relevant dependencies
I tried both: Standard LibGDX Projects and liftoff ones.
One Project doesn't really have dependencies besides LibGDX.

#### Stacktrace
I don't have a stacktrace besides 'Executing tast' and 'Task finished' 

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by shatterblast** [comment]
Can you share some example source code, please?  Also, when did this start happening?  It sounds like your projects worked before on your same machine, so something must have changed.

**Comment by TheSwerik** [comment]
As I said, it happens to completely blank projects aswell

started happening on my new PC, on my old one and my laptop its fine


After installing and trying various Java versions, I got it to display this error: 

> Could not open cp_init remapped class cache for v1eg43rs95hl9ydtght0qmiw (C:\Users\Erik\.gradle\caches\6.0\scripts-remapped\ijresolvers1_dj2kz0kn6adrhyczr4bmflx11\v1eg43rs95hl9ydtght0qmiw\cp_initeb9c0c7311919d66379f4a07d16b802d).
> Could not open cp_init generic class cache for initialization script 'C:\Users\Erik\AppData\Local\Temp\ijresolvers1.gradle' (C:\Users\Erik\.gradle\caches\6.0\scripts\v1eg43rs95hl9ydtght0qmiw\cp_init\cp_initeb9c0c7311919d66379f4a07d16b802d).
   > Could not initialize class org.codehaus.groovy.classgen.Verifier


And I got that fixed by just deleting the Chache folder that is stated in the first line of the stacktrace.
