### ISSUE TITLE
BinaryHeap bug

### ISSUE THREAD

**Issue by windmeup** [libgdx/libgdx#5984]
I think the com.badlogic.gdx.utils.BinaryHeap.remove() method has bug.
I am sorry i have no time to write a test class, but I list the actions below, look at the last line:
version:1.9.10
add 44.683983
pop 44.683983
add 160.47682
add 95.038086
add 396.49918
add 835.0006
add 439.67096
add 377.55692
add 373.29028
pop 95.038086
add 926.524
pop 160.47682
add 189.30789
remove 926.524
add 924.88995
add 700.856
add 342.5846
add 313.3819
pop 189.30789
add 407.9829
add 1482.5394
add 1135.7894
add 362.44937
pop 313.3819
add 725.86615
add 1656.2006
add 490.8201
pop 342.5846
remove 725.86615
add 723.18396
add 716.36115
remove 490.8201
add 474.9852
add 379.61304
pop 362.44937
add 465.81775
add 440.83838
add 1690.9901
add 1711.5605
add 1795.7483
add 388.60376
add 2119.6921
pop 373.29028
add 1040.5143
add 1018.3097
add 1039.8417
add 1142.326
add 1045.692
add 820.3383
remove 474.9852
add 430.27383
add 506.89728
pop 377.55692
add 973.9379
remove 723.18396
add 619.83624
remove 1656.2006
add 1547.9089
pop 379.61304
remove 1018.3097
add 930.3666
remove 1039.8417
add 950.749
remove 1142.326
add 1055.636
remove 1045.692
add 958.5852
remove 820.3383
add 771.37115
remove 506.89728
add 417.02042
pop 388.60376
remove 930.3666
add 864.04517
remove 950.749
add 879.2704
remove 958.5852
add 894.9335
add 1534.2864
pop 396.49918
remove 619.83624
add 548.92786
remove 924.88995
add 905.3478
pop 407.9829
remove 440.83838
add 436.48087
pop 417.02042
remove 1040.5143
add 950.6953
add 992.51624
add 808.5153
pop 430.27383
add 876.47845
add 472.963
pop 436.48087
remove 465.81775
add 461.85135
add 1552.4479
pop 439.67096
pop 461.85135
remove 950.6953
add 862.6192
remove 992.51624
add 900.9059
remove 808.5153
add 716.3565
remove 876.47845
add 610.04565
add 598.95935
add 487.93192
remove 864.04517
add 852.66907
remove 879.2704
add 867.3523
remove 894.9335
add 884.0505
pop 472.963
pop 487.93192
add 548.7671
pop 548.7671
add 1437.1154
add 1934.038
add 2401.7002
pop 548.92786
remove 973.9379
add 903.2409
remove 1547.9089
add 1481.2589
pop 598.95935
add 1430.7216
pop 700.856 ---------------------- the correct value is 610.04565

**Comment by tommyettinger** [comment]
Confirmed in a test and via step debugging. [Code for a test is here](https://github.com/SquidPony/SquidLib/blob/master/squidlib-util/src/test/java/squidpony/squidmath/BinaryHeapTest.java); it will need some extra code to be runnable with just libGDX. The only method it needs, I think, is `Maker.makeHM(K, V, Object...)`, in squidlib-util's squidpony package; I could copy it into the test if anyone wants.

**Comment by tommyettinger** [comment]
It's possible that this change set is all that's needed to fix this: https://github.com/SquidPony/SquidLib/commit/6eb882f62ba5f092837bf4ae40957c7f743cd054 . I hope there's a way to run the added code conditionally, but I don't really understand heaps that well.

What my code does is run part of `up()` near the end of `down()`, because in the current libGDX code, methods like `remove()` swap the last node with the removed node *even if* the new position for the last node isn't valid by the heap property. Filtering up as well as down ensures it's in the right place, but can probably be optimized.

**Comment by windmeup** [comment]
Thank you, tommey!
I found this when I use the IndexedAStarPathFinder class in gdx AI, some times it gots a wrong path.
I fix the finder up with use setValue() instead of remove() and add() to update heap node.

**Comment by NathanSweet** [comment]
Good find @windmeup! I use BinaryHeap in a few projects, but I only remove the root.

Thanks for the test @tommyettinger! I gdxified it and put it in CollectionsTest.

`remove` was using the logic for removing the root (first) node. When removing any other node, we need to fix up the heap using `up` or `down` based on the values.

**Comment by tommyettinger** [comment]
Hooray, it is fixed!
