### ISSUE TITLE
Discord Music bot, ytdl cannot access Problem 

### ISSUE THREAD

**Issue by kubenzet** [libgdx/libgdx#5991]
const {
    Client,
    Attachment
} = require('discord.js');
const bot = new Client();

const ytdl = require(ytdl-core);
const fs = require('fs');
// TypeScript: import ytdl from 'ytdl-core'; with --esModuleInterop
// TypeScript: import * as ytdl from 'ytdl-core'; with --allowSyntheticDefaultImports
// TypeScript: import ytdl = require('ytdl-core'); with neither of the above

const token = ''

const PREFIX = '!';

var version = '1.2';

var servers = {};

bot.on('ready', () => {
    console.log('Kamil jest online!' + version);

})

bot.on('message', message => {

    let args = message.content.substring(PREFIX.length).split('');

    switch (args[0]) {
        case 'play':

            function play(connection, message){
                var server = servers[message.guild.id];

                server.dispatcher = connection.playstream(ytdl(server.queue[0], {filter: "audioonly"}));

                server.queue.shift();

                server.dispatcher.on("end", function(){
                    if(server.queue[0]){
                        play(connection, message);
                    }
                    
                });
                    
                
                
                
            }

             if(!args[1]){
                 message.channel.send('musisz podac link do piosenki którą mam zagrać');
                 return;
             }

             if(!message.member.voiceChannel){
                 message.channel.send('musisz byc na disko kanale');
                 return;
             }

             if(!servers[message.guild.ud]) servers[message.guild.id] = {
                 queue: []
             }

             var server = servers[message.guild.id];

             server.queue.push(args[1]);

             if(!message.guild.voiceConnection) message.member.voiceChannel.join().then(function(connection){
                 play(connection, message)
             })

        break;
    }

});

bot.login(token);

And this error

const ytdl = require(ytdl-core);
                     ^

ReferenceError: Cannot access 'ytdl' before initialization
    at Object.<anonymous> (C:\Program Files (x86)\discord bot\index.js:7:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

someone help me pls. I don't know how to run this. i install ytdl-core and discors.js.

**Comment by intrigus** [comment]
This is the wrong issue tracker.
Please close this issue.

**Comment by tommyettinger** [comment]
What is with all of this new-user spam? This has got to be copied from another issue tracker. Get a life...

**Comment by muskangupta08** [comment]
This is wrong way ... Error and issue will come

**Comment by zach7332** [comment]
is there a way you can just terminate the account i already cant login

**Comment by Tom-Ski** [comment]
> What is with all of this new-user spam? This has got to be copied from another issue tracker. Get a life...

Not sure..
