### ISSUE TITLE
Graphical artifacts on OnePlus 6 phone

### ISSUE THREAD

**Issue by funkyfourier** [libgdx/libgdx#5993]
#### Issue details
On OnePlus 6 phones, and possibly other models, there are graphical artifacts similar to low quality JPEG compression in images. It is especially obvious if there are large single colored areas. It is not equally obvious with all colors, and I have found that the color `#2c2c2c` reveals the issue well. 

Interestingly, the artifact does not show up in screenshots, so I have tried to photograph it using another phone. It is barely visible in the photos, but on the screen of the OnePlus phone they are clearly obvious. I have marked where the issue occurs, you can (barely) see lines across the screen.

https://i.imgur.com/E8rccLa.png
https://i.imgur.com/ONtum3B.png 

In the test project there are lines, but in my app they are more like cubes like in badly compressed JPEG images.

The phone runs on Android 10. I have also tried on the Pixel emulator with Android 10 and Google services and have not been able to reproduce it on that. On a Sony XZ1, Samsung S5, Nexus 5, Honor 7 as well as the desktop version it runs fine.

Now I guess if none of you have a OnePlus 6 it will be hard to debug this. If someone would give me an idea of where to begin to look that would be greatly appreciated.

#### Reproduction steps/code
1. Generate a blank LibGDX project
2. Replace the code of the main ApplicationAdapter with this:
```
public class MyGdxGame extends ApplicationAdapter {
	SpriteBatch batch;
	Color bgColor;
	
	@Override
	public void create () {
		batch = new SpriteBatch();
		bgColor = Color.valueOf("2c2c2c");
	}

	@Override
	public void render () {
		Gdx.gl.glClearColor(bgColor.r, bgColor.g, bgColor.b, bgColor.a);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
	}
	
	@Override
	public void dispose () {
		batch.dispose();
	}
}
```
3. Run on a OnePlus 6 
4. If the issue does not occur, try exiting and entering the app a couple of times. Maybe also kill and restart it.

#### Version of LibGDX and/or relevant dependencies
gdxVersion = '1.9.10'

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by funkyfourier** [comment]
I discovered something. If I do `Gdx.gl.glDisable(GL20.GL_DITHER)` the problem goes away, except now there is a kind of red tone to colors which are supposed to be gray. On desktop it still is fine, but on phones those gray colors are clearly too red.

**Comment by MobiDevelop** [comment]
I think it is odd that we still use RGB565 by default.

**Comment by crykn** [comment]
@funkyfourier do the color artifacts appear, when you _don't_ change the dithering setting and only change your color configuration (RGBA_8888)?

**Comment by mgsx-dev** [comment]
@crykn 16 bits mode with or without dithering can cause artifacts like this. The remaining question is, as @MobiDevelop  highlighted, should we change Android default to 32 bits. I don't know why it was like this (compatibility ? performances ?), but i think it'd be better to have consistency across backends as much as possible.

**Comment by crykn** [comment]
[This](https://stackoverflow.com/questions/5666287/is-it-possible-to-render-in-rgb888-with-opengl) stackoverflow post seems to suggest that RGB565 was the default for GLSurfaceView. However, that doesn't seem to be the case [anymore](https://developer.android.com/reference/android/opengl/GLSurfaceView#setEGLConfigChooser(int,%20int,%20int,%20int,%20int,%20int)): 
> If no setEGLConfigChooser method is called, then by default the view will choose an **RGB_888** surface with a depth buffer depth of at least 16 bits.

**Comment by obigu** [comment]
Fixed in https://github.com/libgdx/libgdx/pull/6291
