### ISSUE TITLE
Not possible to deselect in a multi-select tree with more than one node selected

### ISSUE THREAD

**Issue by timewasteGames** [libgdx/libgdx#5997]
#### Issue details
It is not possible to deselect nodes in a tree configured for multi-select after more than one node has been selected. You can if only one is selected so behaviour feels inconsistent at least. Seems to be related to [this commit](https://github.com/libgdx/libgdx/commit/74c6955a5745d7d141e3bdfe41f3ead688dc4e82#diff-91e1a1e4b6c5d3184d16accc0dee8983) to the Selection class.

I'm not entirely sure what behaviour the Selection logic is trying to achieve so am hesitant to suggest a fix. I am happy to try to deconstruct it if would help.

FTR, I've worked around this by replacing the ClickListener in Tree with one that doesn't use Selection.choose for deselect, which is fine for my needs.

#### Reproduction steps/code
Run the below, you can select and deselect one node at a time using touch (click) only. However, once both nodes are selected it is not possible to deselect any using touch only.

```
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Label;
import com.badlogic.gdx.scenes.scene2d.ui.Skin;
import com.badlogic.gdx.scenes.scene2d.ui.Table;
import com.badlogic.gdx.scenes.scene2d.ui.Tree;
import com.badlogic.gdx.utils.viewport.ScreenViewport;

public class BarebonesStage extends ApplicationAdapter {
  Stage stage;
  Skin skin;

  class Node extends Tree.Node<BarebonesStage.Node, String, Label> {
    public Node(String text) {
      super(new Label(text, skin));
      setValue(text);
    }
  }

  @Override
  public void create() {
    stage = new Stage(new ScreenViewport());
    Gdx.input.setInputProcessor(stage);
    skin = new Skin(Gdx.files.internal("data/uiskin.json"));

    Table table = new Table();
    table.setFillParent(true);
    stage.addActor(table);

    Tree<Node, String> tree = new Tree<>(skin);
    tree.add(new Node("One"));
    tree.add(new Node("Two"));

    tree.getSelection().setMultiple(true);
    tree.getSelection().setToggle(true);

    table.add(tree).fill().expand();
  }

  @Override
  public void render() {
    Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
    stage.draw();
  }

  public void resize(int width, int height) {
    // Pass false to not modify the camera position.
    stage.getViewport().update(width, height, true);
  }

  public static void main(String[] args) {
    new LwjglApplication(new BarebonesStage());
  }
}
```

#### Version of LibGDX and/or relevant dependencies
1.9.10

#### Please select the affected platforms
All

**Comment by NathanSweet** [comment]
Thanks for the runnable code! Toggle should work like ctrl is down, not sure why it was trying to handle the "required" logic in the outer if.
