### ISSUE TITLE
i am following the second edition of your book Mr. , but it seems out dated and i shouldn't keep on using it ? 

### ISSUE THREAD

**Issue by this-AA** [libgdx/libgdx#6000]
Please ensure you have given all the following requested information in your report.

#### Issue details
_Please provide the details of your issue_

#### Reproduction steps/code
_Even if you think your issue is trivial to reproduce, please supply a [SSCCE](http://sscce.org/) that demonstrates your issue.  This saves time on our end, and makes it much more likely that your issue will be fixed.
You can find barebones templates [here](https://github.com/libgdx/libgdx/wiki/Getting-help)_

#### Version of LibGDX and/or relevant dependencies
_Please provide the version(s) affected._

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Lestat** [comment]
The forums is a better medium to ask this kind of question. This issue tracker is just for well... libgdx code issues. :p

But we're already here aren't we? libgdx is far superior than the framework in Mario's book. So you should be using it instead.

**Comment by NathanSweet** [comment]
The book explains the concepts that go into making a game, and those are still relevant. Building your own game toolkit from scratch is just for learning, otherwise use libgdx.
