### ISSUE TITLE
Reopening game exception/bug

### ISSUE THREAD

**Issue by ara2am** [libgdx/libgdx#6001]
I need to run libgdx game after javafx button click.
And after closing the game to add ability of reopening the game using button.

My code for button's callback:
```
public void showGame ()
{
    LwjglApplicationConfiguration config = new LwjglApplicationConfiguration ();
    config.forceExit = false;
    new LwjglApplication (new Game (this), config);
}
```

And it work for first opening.
But opening game 2-3 times cause the exception:
```
Exception in thread "LWJGL Application" java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glViewport(GL11.java:3261)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glViewport(LwjglGL20.java:839)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setWindowedMode(LwjglGraphics.java:526)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:199)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:146)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)
```

I tried to fix it and understand that the causes of this are the static fields in LibGDX code.
So i wrote hack:
```
public void showGame ()
{
    if (Gdx.app != null)
    {
        Gdx.app.exit ();
        LwjglNativesLoader.load = true;
        Gdx.app = null;
        Gdx.audio = null;
        Gdx.files = null;
        Gdx.gl = null;
        Gdx.gl20 = null;
        Gdx.gl30 = null;
        Gdx.graphics = null;
        Gdx.input = null;
        Gdx.net = null;
    }

    LwjglApplicationConfiguration config = new LwjglApplicationConfiguration ();
    config.forceExit = false;
    new LwjglApplication (new Game (this), config);
}
```

And it works. I dont have any exception now.
But i have nasty bag. I can't change game window size after second opening the game.

![image](https://user-images.githubusercontent.com/12220551/79467056-075e4880-8006-11ea-9d1d-7d00a45767e8.png)

I can't find any static fields that is connected with window's size and etc. How i can fix it7

#### Version of LibGDX and/or relevant dependencies
gdxVersion = '1.9.10'

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Darkyenus** [comment]
Combining JavaFX with libGDX is not, as far as I know, officially supported, and neither is restarting the game by creating multiple `*Application` instances. Since the info you gave is very sparse, the likelihood of anyone being able to help is low. I'd suggest you take this issue to IRC or Discord.
