### ISSUE TITLE
Android implementation is missing regular immersive mode

### ISSUE THREAD

**Issue by Betalord** [libgdx/libgdx#6006]
By using AndroidApplicationConfiguration.useImmersiveMode, one can achieve the sticky immersive mode as described here:
https://developer.android.com/training/system-ui/immersive.html
However, the type of immersive mode used here is "sticky", not "regular". There is no way to achieve "regular immersive" mode. This should be a trivial modification to the code, and I believe a necessary one. Note that the difference between the two is that app does not register a swipe when in regular immersive mode, in sticky immersive mode instead it registers it (which can be very annoying in some cases).

**Comment by Betalord** [comment]
I also found a stackoverflow post about it, posted ~5 years ago:
https://stackoverflow.com/questions/32154485/using-immersive-mode-on-libgdx

**Comment by obigu** [comment]
Being a games framework it makes sense that default immersive mode is sticky due to games having a lot of interaction with the screen and gestures that could trigger the display of the status bar. It would be possible to add the option to set it to "regular" but I can't think of use cases in which that would be preferrable. Do you have a specific use case for this feature?

**Comment by Betalord** [comment]
Well, the docs say this: 

> While in sticky immersive mode, if the user swipes from an edge with a system bar, system bars appear but they're semi-transparent, and the touch gesture is passed to your app so it app can also respond to the gesture.

So, I assumed that in normal mode the touch gesture is not passed to the game, which is exactly what I desire. The thing is, on my game, in order to exit from current screen you need to press BACK button, which only appears when you do the swipe from an edge gesture. However, currently, when user does that, it also moves the in-game map (panning is done by touching and moving your finger), which moves the entire map every time you want for the system bar to appear, which is annoying. I was hoping that with regular immersive mode this would be gone, as explained in the quotation from the docs, however I've overridden libgdx's sticky immersive mode with regular one and the panning still persists, so there's not much difference. I guess I misunderstood the concept. That, or the docs are not clear, or my phone is treating this gesture differently.

Still, I think adding a flag to use regular immersive mode makes sense, if someone wants to use it.

**Comment by obigu** [comment]
Yes, actually for your use case you Must use sticky mode because your game uses swipe gestures anywhere on the screen (have a look at this guide https://medium.com/androiddevelopers/gesture-navigation-handling-gesture-conflicts-8ee9c2665c69 including the section on Immersive mode).

Unless a use case is provided I don't see the need to add non-sticky/regular immersive mode as an option.

**Comment by shatterblast** [comment]
@Betalord 
I tried using this, and it works for me.  I'm not sure if it will work for what you want.

`public class AndroidLauncher extends AndroidApplication {

    //data ... and main method

    //todo  Test code for immersive mode.
    @Override
    public void onWindowFocusChanged( boolean hasFocus ) {
        super.onWindowFocusChanged( hasFocus );
        if ( hasFocus && Build.VERSION.SDK_INT >= 19 ) {
            getWindow().getDecorView().setSystemUiVisibility(
                    View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                    | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                    | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                    | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
                    | View.SYSTEM_UI_FLAG_FULLSCREEN
                    | View.SYSTEM_UI_FLAG_IMMERSIVE);
        }
    }

}`

**Comment by NathanSweet** [comment]
Closing as there seems to be a workaround above.
