### ISSUE TITLE
How to use  gl30 pbo ？

### ISSUE THREAD

**Issue by wlonglee** [libgdx/libgdx#6008]
I tried many ways and all failed，help me

**Comment by wlonglee** [comment]
I looked up a lot of documents，They all refer to the same function--->glMapBufferRange，But I didn't find it GDX

**Comment by Darkyenus** [comment]
That methods seems to be [commented out](https://github.com/libgdx/libgdx/search?q=glMapBufferRange&unscoped_q=glMapBufferRange) since the beginning of libGDX, for some reason. ([Possibly because it is not available on the web?](https://github.com/libgdx/libgdx/pull/2527#issuecomment-74588121)

You can still use the underlying GL calls directly - see the implementation of your backend to see how. (For example call [`org.lwjgl.opengl.GL30.glMapBufferRange`](https://javadoc.lwjgl.org/org/lwjgl/opengl/GL30.html#glMapBufferRange(int,long,long,int,java.nio.ByteBuffer)) on lwjgl3 backend, etc.)

**Comment by wlonglee** [comment]
First of all, thank you，I want to dynamically load textures in real time，When I use AssetManager load large images，The game will be stuck，I found out because com.badlogic.gdx.graphics.GLTexture.uploadImageData It took a lot of time，So I wanted to use pbo.
This is my code

private void initPixelBuffer(int width, int height) {
        this.width = width;
        this.height = height;
        int align = 4;
        pboSize = width * height*align;

        pboIds = new IntArray(2);
        int one = Gdx.gl.glGenBuffer();
        int two = Gdx.gl.glGenBuffer();
        pboIds.add(one);
        pboIds.add(two);

        Gdx.gl.glBindBuffer(GL30.GL_PIXEL_PACK_BUFFER, pboIds.get(0));
        Gdx.gl.glBufferData(GL30.GL_PIXEL_PACK_BUFFER, pboSize, null, GL30.GL_STREAM_DRAW);

        Gdx.gl.glBindBuffer(GL30.GL_PIXEL_PACK_BUFFER, pboIds.get(1));
        Gdx.gl.glBufferData(GL30.GL_PIXEL_PACK_BUFFER, pboSize, null, GL30.GL_STREAM_DRAW);

        Gdx.gl.glBindBuffer(GL30.GL_PIXEL_PACK_BUFFER, 0);
    }

private void bindPixelBuffer(TextureData data) {

        Gdx.gl.glBindBuffer(GL30.GL_PIXEL_PACK_BUFFER, pboIds.get(pboIndex));

        Pixmap pixmap = data.consumePixmap();
        Gdx.gl.glPixelStorei(GL20.GL_UNPACK_ALIGNMENT, 1);
        Gdx.gl.glReadPixels(0, 0, width, height, GL20.GL_RGBA, GL20.GL_UNSIGNED_BYTE, pixmap.getPixels());
        pixmap.dispose();

        Gdx.gl.glBindBuffer(GL30.GL_PIXEL_PACK_BUFFER, pboIds.get(pboNextIndex));
        Gdx.gl30.glFlushMappedBufferRange(GL30.GL_PIXEL_PACK_BUFFER, 0, pboSize);
        Gdx.gl30.glUnmapBuffer(GL30.GL_PIXEL_PACK_BUFFER);

        Gdx.gl.glBindBuffer(GL30.GL_PIXEL_PACK_BUFFER, 0);

        pboIndex = (pboIndex + 1) % 2;
        pboNextIndex = (pboIndex + 1) % 2;
    }
Something went wrong while I was running：
Exception in thread "LWJGL Application" org.lwjgl.opengl.OpenGLException: Cannot use Buffers when Pixel Pack Buffer Object is enabled
	at org.lwjgl.opengl.GLChecks.ensurePackPBOdisabled(GLChecks.java:107)
	at org.lwjgl.opengl.GL11.glReadPixels(GL11.java:2449)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glReadPixels(LwjglGL20.java:535)

1. code is use 
 pboIds = new IntArray(2);
int one = Gdx.gl.glGenBuffer();
int two = Gdx.gl.glGenBuffer();
If I use 
 pboIds = IntBuffer.allocate(2);
 Gdx.gl.glGenBuffers(2,pboIds);
Exception in thread "LWJGL Application" java.lang.IllegalArgumentException: IntBuffer is not direct
	at org.lwjgl.BufferChecks.checkDirect(BufferChecks.java:127)
	at org.lwjgl.opengl.GL15.glGenBuffers(GL15.java:107)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glGenBuffers(LwjglGL20.java:320)
