### ISSUE TITLE
An error about GL30.GL_PIXEL_PACK_BUFFER

### ISSUE THREAD

**Issue by wlonglee** [libgdx/libgdx#6011]
LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
config.width = 1600;
config.height = 900;
config.vSyncEnabled = true;
config.useGL30=true;
new LwjglApplication(new FantasyEntrance(), config);

ByteBuffer pixels = BufferUtils.newByteBuffer(1600*900*3);
Gdx.gl.glBindBuffer(GL30.GL_PIXEL_PACK_BUFFER, bufferID);
Gdx.gl.glReadPixels(0, 0, 1600, 900, GL20.GL_RGB, GL20.GL_UNSIGNED_BYTE, pixels);

The code runs to report an error：
Exception in thread "LWJGL Application" org.lwjgl.opengl.OpenGLException: Cannot use Buffers when Pixel Pack Buffer Object is enabled
	at org.lwjgl.opengl.GLChecks.ensurePackPBOdisabled(GLChecks.java:107)
	at org.lwjgl.opengl.GL11.glReadPixels(GL11.java:2449)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glReadPixels(LwjglGL20.java:535)

**Comment by wlonglee** [comment]
@mgsx-dev sorry，I don't have community links,could you please give me one?Besides,I really need PBO so when the textures is loaded it is dynamic in real time.For now,I use AssetManager to load textures,although it supports asynchronous mode,it is still synchronous when uploading textures in the end.This will result in the game FPS drop from 60 to 40.
As for the source of uploading synchronous textures please refer to com.badlogic.gdx.graphics.GLTexture.uploadImageData

**Comment by mgsx-dev** [comment]
@wlonglee here : https://libgdx.badlogicgames.com/community.html
preferably Discord

**Comment by wlonglee** [comment]
@mgsx-dev  Thank you so much

**Comment by shatterblast** [comment]
Close this, please.  Thank you.
