### ISSUE TITLE
Add getTiles in TileMapTileSet

### ISSUE THREAD

**Issue by nelsonrpn** [libgdx/libgdx#6012]
Im doing methods to map my game maps searching for "collisionable"  tiles.
By TiledMap I can iterate through the TiledMapTileSet collection in it, but in a tile set I cant iterate in the tiles collection, I can only get one through his id and the iterator. 
But a simple getTiles could change this
```
for(TiledMapTileSet tileSet : map.getTileSets()) {
	Iterator<TiledMapTile> tileIterator = tileSet.iterator();
	
	while(tileIterator.hasNext()) {
		TiledMapTile tile = tileIterator.next();
		
		for(MapObject tileObject : tile.getObjects()) {
			//Do whatever it needs
		}
	}
}
```
To this

```
for(TiledMapTileSet tileSet : map.getTileSets()) {
	for(TiledMapTile tile : tileSet.getTiles()) {
		//Do whatever it needs
	}
}
```
I know this sounds silly, but the use of iterators has become very little used lately , more in legacy code, just because it adds a certain complexity, and I don't know what could be of future java updates

**Comment by mgsx-dev** [comment]
Actually, TiledMapTileSet implements Iterable<TiledMapTile> so you can write it like this : 
```java
for(TiledMapTileSet tileSet : map.getTileSets()) {
	for(TiledMapTile tile : tileSet)) {
		//Do whatever it needs
	}
}
```

**Comment by crykn** [comment]
This seems to be resolved. @nelsonrpn do you mind closing this?

**Comment by mgsx-dev** [comment]
yeah, existing code already allow requested concise syntax, so i'm closing it now.
