### ISSUE TITLE
AndroidAttribute Compatibility in Android API lower than Lollipop.

### ISSUE THREAD

**Issue by decepticlown** [libgdx/libgdx#6022]
#### Issue details
Running LibGDX project in Android 4.4.2 (and possibly all APIs lower than Lollipop) produces error:

`04-27 14:55:43.157 7183-7183/com.mygdx.test442 E/dalvikvm: Could not find class 'android.media.AudioAttributes$Builder', referenced from method com.badlogic.gdx.backends.android.AndroidAudio.<init>
`

I googled it and possibly found solution.  [This answer](https://stackoverflow.com/a/30262940) explains why this error is popping up. I didn't get it properly but I know you guys are the masterminds here.

#### Reproduction of issue
Running LibGDX project in Android 4.4.2? Error is produced from LibGDX package class AndroidAudio. I thought it might be related to my code so to verify I created a new GDX project and ran the apk wihthout changing a single word. It works fine but logcat in Android Studio shows the same error.

#### Version of LibGDX and/or relevant dependencies
LibGDX version : 1.9.10

#### Stacktrace
```java
04-27 14:55:43.157 7183-7183/com.mygdx.test442 E/dalvikvm: Could not find class 'android.media.AudioAttributes$Builder', referenced from method com.badlogic.gdx.backends.android.AndroidAudio.<init> 
```

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by shatterblast** [comment]
It could be just linking to a different API hook than what LibGDX offers.  An Error from Android does not necessarily mean a crash from LibGDX.  You might try Firebase Crashlytics.  It's no longer in Beta form now.

**Comment by PokeMMO** [comment]
It looks like that api should only be used on Lolipop or higher.

https://github.com/libgdx/libgdx/blob/gdx-parent-1.9.10/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidAudio.java#L52-L57

Does 4.4.2 require reflection to handle this? T5787 seems to imply we don't need reflection here?

**Comment by shatterblast** [comment]
It's better to raise the minimum SDK requirement in my opinion.

**Comment by MobiDevelop** [comment]
I think the short answer is "it's complicated", but the longer answer seems to be described here:
https://stackoverflow.com/a/30262940/416549

**Comment by SimonIT** [comment]
I ran the AudioDeviceTest on an Android 4.0.4 emulator and I get also the error, but I can hear the annoying tone (which it should produce), too.
Do you have the actual problem that audio is not played? Or is this only a hint that there could be a problem? @decepticlown 
Because if everything is working, in my opinion we shouldn't change anything for the decreasing group of Android 4 users.

**Comment by decepticlown** [comment]
@SimonIT I didn’t test anything I was just working on my project decided to test it on my old htc. Project doesn’t crash, it works fine (I haven’t tested audio though). I’ll quickly check it on my phone report back.

**Comment by decepticlown** [comment]
@SimonIT I can successfully play mp3 file. So I guess error is like just a reminder?
