### ISSUE TITLE
GWT not possible to download images into pixmap

### ISSUE THREAD

**Issue by IlyaGazman** [libgdx/libgdx#6023]
#### Issue details
When compiling WEB with `gradlew.bat html:dist` getting an exception:

`The constructor Pixmap(byte[], int, int) is undefined`

How can I load an image from a URL on WEB/GWT/HTML5?
Also, there is a warning there, is it safe to ignore?

#### Reproduction steps/code
OS: Windows 10
IDE: Intellij
Executing command: `gradlew.bat html:dist`
#### Version of LibGDX and/or relevant dependencies
_Please provide the version(s) affected._

#### Stacktrace
Compiling error
```
> Task :html:compileGwt
Apr 27, 2020 7:54:12 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
Compiling module com.gazman.stories.GdxDefinition
   Tracing compile failure path for type 'my.file.java'
      [ERROR] Errors in 'file:/C:/my.file.java'
         [ERROR] Line 62: The constructor Pixmap(byte[], int, int) is undefined
   [ERROR] Aborting compile due to errors in some input files
```

Java source code:
```java
    byte[] bytes = ...
    Pixmap pixmap = new Pixmap(bytes, 0, bytes.length);
```
#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ *] HTML/GWT
- [ *] Windows
- [ ] Linux
- [ ] MacOS

**Comment by shatterblast** [comment]
The standard way includes using an InputStream with some REST protocols.  The Google HTTP Client can help some.  You might check StackOverflow for some references.

**Comment by Darkyenus** [comment]
As you can see [here](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/graphics/Pixmap.java), `Pixmap` on GWT has constructors which take libGDX's `FileHandle` (which could work for what you need) or HTML `ImageElement`. I haven't worked with it personally, but it seems that it should be possible to create an HTML `<image>` and load it from that.

As this isn't really a libGDX issue, please close it and check [Discord or IRC](https://github.com/libgdx/libgdx/wiki/Getting-Help).

Regarding the warning: I have never seen it, but it looks like Java's `Preferences` are for some reason trying to write into Windows registry. I don't know why would it do that. You will probably have to investigate that yourself, or, again, check Discord/IRC.

**Comment by shatterblast** [comment]
GWT / HTML could probably use some extra methods for simplicity's sake that help this.  Other wise, I am not using GWT at the moment.  I would add it my self if so.

**Comment by IlyaGazman** [comment]
@Darkyenus tnx for the tip, I found a working solution using an Image. 
I actually had many problems with it

 - Net.HttpRequest [didn't work for me](https://stackoverflow.com/questions/61447184/libgdx-net-httprequest-get-request-is-not-working) so I used okHttp for handling Desktop and Android
 - I had cross-origin issues with loading the image, solved it by calling to 
    ` image.getElement().setAttribute("crossOrigin", "anonymous");`

I ended up building a library for loading images on Android, Desktop, and Web(don't have an iOS to test it on). Can you please guide me on how I can submit a pool request for it?

**Comment by Darkyenus** [comment]
@IlyaGazman For info on pull requests, see [this](https://yangsu.github.io/pull-request-tutorial/) (or any other) general info tutorial and [this](https://github.com/libgdx/libgdx/wiki/Contributing) libGDX specific page for contributors. You don't have to get it right the first time - that is what code review is for, so don't worry about it too much.

@shatterblast: By warning, I meant this line:  
`WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.`,
which has nothing to do with any networking and everything to do with [windows registry](https://docs.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regcreatekeyexa).

**Comment by MrStahlfelge** [comment]
This is a long-standing problem that comes up from time to time. In my opinion, we need a `Gdx.net.downloadImageToPixmap` helper method with two different implementations for GWT and all other backends. It is an easy task using code from GWT backend, but the needed classes and methods are not visible to the core.
Everyone is invited to submit PRs.
