### ISSUE TITLE
Textarea cursor/selection misaligned if line starts with a space

### ISSUE THREAD

**Issue by d01010101** [libgdx/libgdx#6033]
## Issue details
Textarea cursor/selection misaligned if line starts with a space.

#### Reproduction steps/code
Type a space at the beginning of a line. Then type a black character, the cursor line will be off about a half character width to the right.

#### Version of LibGDX and/or relevant dependencies
Fairly recent, gdx-setup has just been downloaded but it says nothing about the version.

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [x] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] MacOS

**Comment by NathanSweet** [comment]
I haven't needed TextArea in my projects, it's one of the few widgets I don't typically maintain. PRs for fixes are welcome! Maybe @anserran or @rgarcia or @Ralph or @Gekk0r are interested.

**Comment by d01010101** [comment]
It is more complicated. Sometimes the cursor is half a character to the left, sometimes half a character to the right, and it does not necessarily seem to be connected with leading spaces.

**Comment by crykn** [comment]
This may have been fixed by #6133.

**Comment by raeleus** [comment]
I can't seem to reproduce this problem with the latest TextArea fix. I experienced lots of problems with it beforehand, which didn't really have any correlation with spaces necessarily. Feel free to open this issue again if it persists with the latest SNAPSHOT. Thank you.
