### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by hoijui** [libgdx/libgdx#6034]
https://libgdx.badlogicgames.com/ gives me an 502 error

**Comment by intrigus** [comment]
That's something for @badlogic

**Comment by NathanSweet** [comment]
@SimonIT did things happen?

**Comment by SimonIT** [comment]
What do you mean? If you look at the [my build](https://travis-ci.com/github/SimonIT/libgdx-site/builds/163524021), it seem to work. I can also run everything on my computer. But I can't say which Node.JS runs on the server. Maybe @Tom-Ski can update the version to Node.JS 12 (the latest LTS)?

**Comment by badlogic** [comment]
The changes that were merged require a node.js update. I appreciate the work everyone is putting into this, but please inform me before pushing changes that require infrastructure updates.

**Comment by badlogic** [comment]
Fixed.
