### ISSUE TITLE
Box2D setTransform angle not persisting 

### ISSUE THREAD

**Issue by Blunderchips** [libgdx/libgdx#6043]
#### Issue details

When the angle of a [Box2D Body](https://libgdx.badlogicgames.com/ci/nightlies/docs/api/com/badlogic/gdx/physics/box2d/Body.html) is set using `setTransform` the angle does not persist when the call is not made. If the `setTransform` is not called the angle will snap back to 0, if `setTransform` is called every frame with the target angle set the body's rotation remains correct. 

Click [here](https://youtu.be/ckv7NiEuNJE) for a short video demonstrating the bug (the texture won't rotate, only the box drawn by a Box2D debug render should). The snippet below is used to move the body to the target location on click.

#### Reproduction steps/code

`targetPosition` is a `Vector2` and `bodyPosition` is equal to `body.getPosition()` .

```java

// https://stackoverflow.com/a/23482465/3833743
Vector2 direction = targetPosition
    .sub(bodyPosition) 
    .nor(); 

body.setTransform(bodyPosition, direction.angleRad());
body.setLinearVelocity(direction.scl(target.speed));

```

The desired state is that the body points to and move towards and the target position. The above snippet is run until the body arrives at the target location as which point the body remains at the location angle snaps to 0.

#### Version of LibGDX and/or relevant dependencies

libGDX: `1.9.10`

#### Please select the affected platforms

- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux (Pop!_OS 20.04)
- [ ] MacOS

**Comment by MobiDevelop** [comment]
Given the fact libgdx simply passes the transform to the underlying box2d native code, I'm not sure there's actually a bug here - it appears to just be how box2d works.

**Comment by Blunderchips** [comment]
@MobiDevelop are there any plans to fix this bug and if not are there any other ways to set the rotation of a body?

**Comment by intrigus** [comment]
(Applying Ockham's Razor I'd assume that the problem is in your code)

Can you add a minimal testcase that reproduces your issue?
Also, what exactly does your video show?
The body seems to rotate properly doesn't it?

**Comment by Blunderchips** [comment]
@intrigus No, it does not rotate correctly. See how the body snaps at the end of travel. If `setTransform` is not called every frame the rotation defaults to 0.

**Comment by mgsx-dev** [comment]
for people facing this issue, setTransform should only be used to "teleport" bodies (rarely used).
In order to manually control position and/or rotation, you should use setLinearVelocity and/or **setAngularVelocity** instead.
