### ISSUE TITLE
App music continues to play (with choppy audio) in iOS 13.2, 13.3, and 13.5 simulators when app is put into background

### ISSUE THREAD

**Issue by elohanlon** [libgdx/libgdx#6050]
I don't currently have a real iOS device to test on, so I haven't yet confirmed whether this affects real devices as well.  If anyone reading this issue is able to test, I'd appreciate the confirmation.

#### Issue details

When running a libgdx app in the iOS 13.3 simulator:  If the app has music playing and you swipe the app to the background, the music unexpectedly continues to play and sounds very choppy.  This problem exists for brand new, minimally-configured libgdx apps.  Please see the "Reproduction steps/code" section for more info.

I'm using Eclipse with the RoboVM plugin to run the app, and this error message appears when the app is sent to the background:

`2020-05-14 11:46:37.815 IOSLauncher[91140:2360202] Can't end BackgroundTask: no background task exists with identifier 1 (0x1), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.`

And then when you bring it to the foreground and send it to the background again:

`2020-05-14 11:47:09.100 IOSLauncher[91140:2360202] Can't end BackgroundTask: no background task exists with identifier 4 (0x4), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.`

This background music behavior didn't exist in the past (e.g. testing on iOS 11.3).  Normally, putting the app in the background silenced any playing music.

#### Reproduction steps/code
- Create new app using latest gdx-setup.jar (as of this writing, 2020-05-14)
- Import into Eclipse
- Install version 2.3.9 of the RoboVM plugin for Eclipse (because it seems that you can't build/run for the iOS 13 simulator with earlier releases)
- Add an mp3 file called "music.mp3" at `android/assets/music.mp3`
- Update the `create()` method in `core/src/com/mygdx/game/MyGdxGame.java` (or wherever your app entry point is -- the class that extends ApplicationAdapter) so it looks like this:
```
public void create () {
		batch = new SpriteBatch();
		img = new Texture("badlogic.jpg");
		music = Gdx.audio.newMusic(Gdx.files.internal("music.mp3"));
		music.setLooping(true);
		music.play();
	}
```
- Run the game via RoboVM Eclipse plugin Run Configuration, selecting project `my-gdx-game-ios`, device type `iPhone 11 ..., 13.3` and arch `64-bit (x86_64)`.

One thing to note, for the above instructions, is that the current gdx-setup.jar creates an app with a top level build.gradle robovm version of 2.3.8.  You can leave that version as is or update to 2.3.9, but it doesn't change the problem I'm describing.  Both cases build for the iOS 13 simulator as long as your RoboVM **Eclipse plugin** is 2.3.9.

#### Version of LibGDX and/or relevant dependencies
Tested with:
- libgdx 1.9.8 and 1.9.10
- RoboVM 2.3.9 Eclipse plugin
- Gradle RoboVM version of 2.3.8 or 2.3.9 (but Eclipse plugin must be 2.3.9)
- iOS Simulator - iPhone 11 with iOS 13.2 or 13.3
- Xcode 11.3.1

#### Stacktrace
No relevant stacktrace.

#### Please select the affected platforms
- [ ] Android
- [x] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by obigu** [comment]
Even if I can't reproduce on my setup:
- IntelliJ
- RoboVM 2.3.10-SNAPSHOT
- libGDX 1.9.10
- Device iOS 13.4.1 and Simulator 13.2.

I have been able to reproduce different behaviour between Simulator and device when app is backgrounded. When the app is backgrounded on simulator, even if the music stops, when the app is resumed the music is not resumed where it was left but as if it has continued playing in the background with volume 0. That doesn't happen on the device, music resumes on foreground where previously paused.

I think the issue you describe is also too critical not to have been noticed previously so my guess is that it's an issue on your environment using the Simulator.

Regarding the error/warning message, it also occurs when running on the device and is independent of playing any music (happens on a totally empty app).

**Comment by elohanlon** [comment]
Thank you for the reply and testing, @obigu !  Your mention of `RoboVM 2.3.10-SNAPSHOT` made me want to try that plugin version instead of the latest 2.3.9 release (still in Eclipse, in my case) and I'm happy to say that it solved the audio problem in the simulator.  Though as you also noted, I do still see the `Can't end BackgroundTask` error/warning.

If it wouldn't be a pain to try, would you mind another test on your side?  In both the simulator and with a physical device, could you see if you're able to reproduce the audio issue with the latest 2.3.9 IntelliJ plugin release instead of the unreleased snapshot?

**Comment by obigu** [comment]
If you want to follow up on the issue it is you who should run those tests :)
1. Test again on Eclipse and RoboVM 2.3.9 to confirm the issue is linked plugin version.
2. Try on IntelliJ both 2.3.10-SNAPSHOT and 2.3.9 on Simulator.
This way you'll cover all combinations of IDE and platforms and we can further investigate if it's a RoboVM issue.

**Comment by elohanlon** [comment]
I already tested (1) before posting my last comment, to make sure it was accurate, but I'm glad to do it again for good measure.  Just did and confirmed the same results as last time.  Problem appears for me with the Eclipse 2.3.9 plugin and doesn't occur with the Eclipse 2.3.10-SNAPSHOT plugin.

For (2), I haven't used IntelliJ before but I'll give it a go and will report back.  That's a good suggestion, testing to see if the RoboVM plugins are behaving differently in different IDEs.  Verification would reduce the likelihood of things just being off about my Eclipse setup.

I'm still unable to test RoboVM plugin builds on physical device though, sorry.  That's why I was asking if you could in my previous comment.

**Comment by elohanlon** [comment]
I just finished testing the two plugin versions in a fresh install of the latest version of IntelliJ (Community 2020.1).

First, the good news:

IntelliJ + RoboVM 2.3.10-SNAPSHOT plugin + Simulator behaves the same way as Eclipse + RoboVM 2.3.10-SNAPSHOT plugin + Simulator.  It works, and the background-app music issue doesn't occur.

Now the bad news:

I wasn't able to build and run the app with the RoboVM 2.3.9 release IntelliJ plugin.  I'm getting the same NullPointerException `at org.robovm.idea.running.RoboVmRunProfileState.executeRun(RoboVmRunProfileState.java:57)` mentioned in this issue (https://github.com/MobiVM/robovm/issues/242#issuecomment-598698156).  Based on dkimitsa's comment in that issue, it sounds like 2.3.9 IntelliJ plugin incompatibility is a known problem, so I don't think I have a good way of comparing the 2.3.9 plugin behavior in Eclipse vs. IntelliJ after all.

What's the best way to proceed now?  Thanks for your help with this.

**Comment by Monarchis** [comment]
How about
```
@Override
public void pause() {
    music.setVolume(0f);
    //or stop() / pause()
}
@Override
public void resume() {
    music.setVolume(1f);
    //or play()
}
```
in the class extending ApplicationListener?
Those Methods allow you to implement silent music / paused music.

The choppy noise could lead from low fps execution when the app is in background, but thats just a theroy from me.

**Comment by obigu** [comment]
@elohanlon Yep, the issue you are facing is https://github.com/MobiVM/robovm/issues/242 and affects versions older that 2.3.1-0-SNAPSHOT. There's a workaround explained in one of the comments, you need to remove/comment the Android Facet config on `ios.iml`.

**Comment by elohanlon** [comment]
@obigu With the workaround in https://github.com/MobiVM/robovm/issues/242 I was able to run IntelliJ + RoboVM 2.3.9, thanks -- and I'm seeing the same problem with IntelliJ as Eclipse with RoboVM 2.3.9.  Still not sure if it affects a real device, but hopefully this additional info helps!

@Monarchis I tried your workaround in the test app and it does hide the problem, thanks!  Even if I can stop the audio from being noticeable though, I'm hesitant to release a version of the app with audio output still theoretically open (just in case there are other related issues with things like several-second-long sound effects, and also because I may end up having to silence a bunch of things in various places), so maybe I'll play it safe and wait until 2.3.10 is officially released so I can reference it in my build.gradle file when creating a standalone signed IPA.

Or...if there's a way to reference the snapshot build for a `./gradlew ios:createIPA` operation, I can try that instead? @obigu, do you know if there's a way to reference 2.3.10-SNAPSHOT in the top level `build.gradle` file?  Or is that not possible because it's not hosted on maven? (https://mvnrepository.com/artifact/com.mobidevelop.robovm/robovm-gradle-plugin)

**Comment by elohanlon** [comment]
Just updated the ticket title because I also tested this on the iOS 13.5 Simulator.

**Comment by obigu** [comment]
Ok, so the bug is confirmed to happen on 2.3.9 simulator independentñy of the IDE and doesn't happen on 2.3.10-SNAPSHOT in simulator or device. I'm almost sure it doesn't happen on devices on 2.3.9 either because we would have noticed but, in any case, I would recommend using 2.3.10-SNAPSHOT not just for this bug but because it fixes several other ones. I don't expect this is investigated further considering it's fixed on 2.3.10.
 
You should be able to depend on the SNAPSHOT adding:
`maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }`

**Comment by elohanlon** [comment]
Great, then I'll stick with 2.3.10-SNAPSHOT and use the sonatype repo.  And I'll bet you're right about the devices.

Thanks for your help!

**Comment by Harvtronix** [comment]
I tested 2.3.9 yesterday on my iPhone 6 and it did not exhibit the glitchy sound behavior. Simulator did, but not the real device.

**Comment by elohanlon** [comment]
@Harvtronix Thank you for confirming!

**Comment by MrStahlfelge** [comment]
Can this get closed? Seems to be solved.

**Comment by elohanlon** [comment]
@MrStahlfelge Yes, I'll close now.
