### ISSUE TITLE
Could not find or load main class after conversion to kotlin

### ISSUE THREAD

**Issue by VladoCC** [libgdx/libgdx#6052]
#### Issue details
I'veconverted my project form java to kotlin. And now I can't find any way to run my DesktopApplication.
It says: 
> Error: Could not find or load main class ru.myitschool.dcrawler.desktop.DesktopLauncherKt

#### Reproduction steps/code
It's very old project from 2017, so it may lack some important fixes. I've used many guides and issues to make it work even to this state.
So I can't clearly describe steps to reproduce.
But I'll add that when only core was converted to kotlin, desktop application worked, but couldn't find any classes from core.
And after I converted DesktopApplication it's seems that some issues with classpath occured.
I changed configuratio of course and set it to one from kotlin.
The last thing I did was that I moved main out of object scopes. But this didn't change anything.

#### Version of LibGDX and/or relevant dependencies
kotlinVersion = '1.3.61'
gdxVersion = '1.9.10'

#### Stacktrace
Error: Could not find or load main class ru.myitschool.dcrawler.desktop.DesktopLauncherKt

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Darkyenus** [comment]
This is not a libGDX issue. Please take your question to [Discord or IRC](https://github.com/libgdx/libgdx/wiki/Getting-Help), we will be happy to help you there.
