### ISSUE TITLE
Low frame rate lead to higher duration of actions.

### ISSUE THREAD

**Issue by danhallin** [libgdx/libgdx#6054]
#### Issue details
Stage has a hard coded minimum frame rate leading to actions being performed slower than expected when the frame rate is below 30 FPS.

```
/** Calls {@link #act(float)} with {@link Graphics#getDeltaTime()}, limited to a minimum of 30fps. */
public void act () {
    act(Math.min(Gdx.graphics.getDeltaTime(), 1 / 30f));
}
```

#### Reproduction steps/code

**Expected:**
Should take 1 second for cube to move.

**Actual:**
Takes 3 seconds for cube to move.

**Suggested solution:**
Make Stage use the lower of 30 and current FPS instead of 30 or make it configurable.

```
import com.badlogic.gdx.*;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.Pixmap;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.actions.Actions;
import com.badlogic.gdx.scenes.scene2d.ui.*;
import com.badlogic.gdx.utils.viewport.*;

public class BarebonesStage extends ApplicationAdapter {
    Stage stage;

    public void create () {
        stage = new Stage(new ScreenViewport());

        Gdx.input.setInputProcessor(stage);

        Pixmap pixmap = new Pixmap(1, 1, Pixmap.Format.RGBA8888);
        pixmap.setColor(Color.CYAN);
        pixmap.fill();
        pixmap.drawRectangle(0, 0, 1, 1);
        Texture texture = new Texture(pixmap);
        pixmap.dispose();
        Image image = new Image(texture);
        image.setSize(30, 30);

        stage.addActor(image);

        image.addAction(
                Actions.forever(
                        Actions.sequence(
                                Actions.moveTo(200, 200, 1f),
                                Actions.moveTo(0, 0, 1f)
                        )
                )
        );
    }

    public void render () {
        stage.act();
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        stage.draw();
    }

    public void resize (int width, int height) {
        // Pass false to not modify the camera position.
        stage.getViewport().update(width, height, true);
    }

    public static void main (String[] args) throws Exception {
        LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
        config.foregroundFPS = 10;
        new LwjglApplication(new BarebonesStage(), config);
    }
}
```

#### Version of LibGDX and/or relevant dependencies
1.9.10

#### Please select the affected platforms
- [X] Android
- [X] iOS (robovm)
- [X] iOS (MOE)
- [X] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by obigu** [comment]
This is by design to protect against the so called "spiral of death". If your fps drops from a certain amount it means the device is struggling to keep up and it may be that processing the next frame takes even longer due to the amount of processing needed for such a large delta (for example if you have a fixed time-step physics engine). This could lead to a situation where fps would keep dropping until a non recoverable point. To avoid this we clamp the delta and the consequence is the slowing down of the game (in real time) which is a better alternative to a crash/freeze.
There may be some very specific cases in which this is not desirable in which case you can easily override `act()`.

**Comment by Darkyenus** [comment]
Or, instead of overriding, just call it with an explicit delta time: `act(Gdx.graphics.getDeltaTime());`

**Comment by danhallin** [comment]
Thanks! Fixed by calling directly. 

One specific case is when you purposefully set your FPS to less than 30, we run at 10 and 15 in our applications since we need the CPU for other things than graphics updates.

I think it would make sense to use the lower of 30 and purposefully set lower FPS to not surprise the user.

**Comment by NathanSweet** [comment]
`Graphics` doesn't know about a backend specific target FPS. The `act()` method javadoc says it's limited to 30fps, so I think it's OK as is.
