### ISSUE TITLE
Wrong scale SelectBox

### ISSUE THREAD

**Issue by taluks** [libgdx/libgdx#6058]
#### Issue details
![image](https://user-images.githubusercontent.com/20488327/82739179-30c96d00-9d46-11ea-9f29-93059ec02335.png)
List of selectbox without scale

#### Reproduction steps/code
```java
Skin skin = manager.get(fileSkin);

Window window = new Window("Window", skin);
window.setSize(250, 150);
window.setScale(2);

SelectBox<String> sb = new SelectBox<String>(skin);
sb.setItems(new String[] { "one", "two" });
window.add(sb);

stage.addActor(window);
```

#### Version of LibGDX and/or relevant dependencies
1.9.10

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by NathanSweet** [comment]
The select box's scrollpane and list are not descendants of the window, so don't inherit the window's scale. SelectBoxList is not exposed by SelectBox, but you could do:
```
selectBox.getList().getParent().setScale(2);
```
The SelectBoxList will be scaled, but won't show up in quite the right place, as the scale is not taken into consideration when it is placed. In general, when using scale or rotation, not all widgets will respect the transforms:
https://github.com/libgdx/libgdx/wiki/Scene2d.ui#rotation-and-scale
Generally it's better to scale the entire Stage using a Viewport:
https://github.com/libgdx/libgdx/wiki/Scene2d#viewport
