### ISSUE TITLE
I18NBundle locale bug

### ISSUE THREAD

**Issue by Asidert** [libgdx/libgdx#6060]
Can't change I18NBundle Locale.

#### Issue details
_Build on android works fine, but deskop version (Windows 10 Single Language) cannot change language_

#### Reproduction steps/code
_`bundle=I18NBundle.createBundle(Amfus.getFile(name+"/lang/lang",internal),new Locale(main.getSettings().getLang()));`<br>
`getLang()` returns "en", for example, but if you check the `Bundle `language later, it will be equal to the system language_

#### Version of LibGDX and/or relevant dependencies
_1.9.10_

#### Please select the affected platforms
- [x] Windows
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Linux
- [ ] MacOS

**Comment by NathanSweet** [comment]
@davebaol

**Comment by Asidert** [comment]
A week later I decided to check something...
Desktop needs lang_<locale>.properties for each language, but Android loads lang.properties if the one that is specified does not exist.
