### ISSUE TITLE
Set keepWithinStage for DragAndDrop isn't aware of dragActor scale

### ISSUE THREAD

**Issue by fgnm** [libgdx/libgdx#6062]
#### Issue details
As title, in `DragAndDrop` utils class the check that ensures that the `dragActor` position does not exceed the stage bounds isn't aware of `dragActor` scale factor.
Exactly at this point [#L134](https://github.com/libgdx/libgdx/blob/43c5a9c32bbe3398d5c27ed2e002e6c3a661960d/gdx/src/com/badlogic/gdx/scenes/scene2d/utils/DragAndDrop.java#L134):
```Java
if (keepWithinStage) {
	if (actorX < 0) actorX = 0;
	if (actorY < 0) actorY = 0;
	if (actorX + actor.getWidth() > stage.getWidth()) actorX = stage.getWidth() - actor.getWidth();
	if (actorY + actor.getHeight() > stage.getHeight()) actorY = stage.getHeight() - actor.getHeight();
}
```

#### Reproduction steps/code
As you can test `actor.getWidth()` and `actor.getHeight()` return the real actor size, but if you set a scale factor with `actor.setScale(...)`, those function always return the real actor size.
A quick fix could be to multiply real `width` and `height` by `scale`.
```Java
if (keepWithinStage) {
	if (actorX < 0) actorX = 0;
	if (actorY < 0) actorY = 0;
	if (actorX + actor.getWidth() * actor.getScaleX() > stage.getWidth()) actorX = stage.getWidth() - actor.getWidth();
	if (actorY + actor.getHeight() * actor.getScaleY()  > stage.getHeight()) actorY = stage.getHeight() - actor.getHeight();
}
```

#### Version of LibGDX and/or relevant dependencies
LibGDX `1.9.10`

#### Please select the affected platforms
Not a specific platform, but it's a `Scene2D` bug.

**Comment by NathanSweet** [comment]
Most of scene2d.ui does not attempt to handle scaled or rotated actors:
https://github.com/libgdx/libgdx/wiki/Scene2d.ui#rotation-and-scale
To scale the entire UI it's better to use the stage's viewport:
https://github.com/libgdx/libgdx/wiki/Scene2d#viewport

**Comment by fgnm** [comment]
Okay, I've understand, but in my use case I cannot use viewport scaling, so I'll disable `keepWithinStage` and check limit for my own, I don't know that this was an intended behavior.
Thanks for clarification

**Comment by NathanSweet** [comment]
Aye, the reasoning is that it would complicate the scene2d.ui widgets to support scale/rotation quite a bit. The simplicity is most of its charm! :)
