### ISSUE TITLE
Latest Commit on Label#setText breaks a lot of Libraries

### ISSUE THREAD

**Issue by Snehks** [libgdx/libgdx#6063]
#### Issue details
Hi, I have been using 1.9.11-SNAPSHOT version and the commit https://github.com/libgdx/libgdx/commit/43c5a9c32bbe3398d5c27ed2e002e6c3a661960d which update the return type of `Label#setText` breaks everything which extends Label and overrides setText method.  
I personally think a breaking update should not be happening in a patch version. The change is very painful as a lot of libraries like (VisUI and TypingLabel depend on Label and the commit breaks that).

#### Reproduction steps/code
Using Libgdx version 1.9.11-SNAPSHOT

#### Version of LibGDX and/or relevant dependencies
1.9.11-SNAPSHOT

#### Stacktrace
N/A

#### Please select the affected platforms
- [x ] Android
- [x ] iOS (robovm)
- [x ] iOS (MOE)
- [ x] HTML/GWT
- [x ] Windows
- [x ] Linux
- [x ] MacOS

**Comment by Mr00Anderson** [comment]
To think about is depreciation as well leaving the legacy system in for time to change.

**Comment by NathanSweet** [comment]
Ah, true it wrecks binary compatibility, sorry. It was nice but we can change it back for now.
