### ISSUE TITLE
Link from banner on website in some places is broken

### ISSUE THREAD

**Issue by Rybski** [libgdx/libgdx#6066]
#### Issue details
Clicking banner "libGDX" redirects to 404 error page. It only occurs in some places. (all sim)
 
#### Reproduction steps/code
10/10 reproduction rate

1. Go to main page (https://libgdx.badlogicgames.com/index.html)
2. Click “Documentation”
3. Click “Setting up”
4. Click on "libGDX" banner on the top
5. 404 error should appear

#### Environment 
Brave (Version 1.9.76 Chromium: 81.0.4044.138 64-bit)
Firefox (76.0.1 64-bit)

#### Affected platforms
-Windows 10 (10.0.18362)
Probably all platforms are affected.

**Comment by obigu** [comment]
Still not working after the fix unfortunately

**Comment by MobiDevelop** [comment]
Are we sure that the site was redeployed?

**Comment by obigu** [comment]
Good question, how can we know?

**Comment by NathanSweet** [comment]
The fix should work. I don't know how to redeploy.

**Comment by Tom-Ski** [comment]
It was missing in another place. Redeployed, should be good now. @obigu you can check Jenkins for last time that job ran
