### ISSUE TITLE
Bug with color in label with wrap

### ISSUE THREAD

**Issue by Totalexx** [libgdx/libgdx#6070]
#### Issue details
I need to draw the text in different colors using the label, but part of the word "commodo" goes to a new line. I think it splits the word "commodo" into two words and therefore moves part of it to a new line.

#### Reproduction steps/code

Create a label and use" Color Markup Language "to change the color in the middle of the word"commodo". We see that the word "commodo" is split into two and moved to a new line.

![bug](https://user-images.githubusercontent.com/34839111/83774854-b1219380-a69f-11ea-8f4b-409c230dd310.jpg)
Code:
```java
  label = new Label("...ea com[#000000]modo consequat. ...", new LabelStyle(font, Color.WHITE)); 
```
So draws in one color:
![withoutbug](https://user-images.githubusercontent.com/34839111/83778015-8e917980-a6a3-11ea-990a-85c31ca19bf9.jpg)
Code:
```java
  label = new Label("...ea commodo consequat. ...", new LabelStyle(font, Color.WHITE)); 
```

#### Version of LibGDX and/or relevant dependencies
LibGDX 1.9.10 and gdx-freetype 1.9.10

#### Stacktrace
```java
public class GameScreen implements Screen{
	 
	Background background;
	GUI gui;

	Stage stage;
	
	FreeTypeFontParameter parameters;
	BitmapFont font;
	Label label;
	
	final String FONT_CHARS = "абвгдеёжзийклмнопрстуфхцчшщъыьэюяabcdefghijklmnopqrstuvwxyzАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮ"
			+ "ЯABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789][_!$%#@|\\/?-+=()*&.;:,{}\"´`'<>";
	
	@Override
	public void show() {
		Assets.loadBackground("background.jpg");
		Assets.loadGUITexture("novelGUI.png");
		Assets.waitLoadAsset();
		
		stage = new Stage(new FitViewport(1066f, 600f, GameManager.camera));
		
		parameters = new FreeTypeFontParameter();
		parameters.characters = FONT_CHARS;
		parameters.size = 18;
		parameters.magFilter = TextureFilter.Linear;
		parameters.minFilter = TextureFilter.Linear;
		parameters.genMipMaps = true;
		
		FreeTypeFontGenerator fontGenerator = new FreeTypeFontGenerator(Gdx.files.internal("gui/fonts/Montserrat-Regular.ttf"));
		font = fontGenerator.generateFont(parameters);
		font.getData().markupEnabled = true;
		fontGenerator.dispose();
		
		label = new Label("Lorem ipsum dolor sit amet, consectetur adipiscing elit, "
				+ "tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim "
				+ "veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex "
				+ "ea com[#000000]modo consequat. Duis aute irure dolor in reprehenderit in voluptate "
				+ "velit esse cillum dolore eu fugiat nulla pariatur.", 
				new LabelStyle(font, Color.WHITE));
		label.setBounds(53.3f, 30f, 959.4f, 90f);
		label.setWrap(true);
		
		background = new Background("background.jpg");
		gui = new GUI("GUI.png", 0, 0, 100, 30);
	
		stage.addActor(background);
		stage.addActor(gui);
		stage.addActor(label);
		stage.setDebugAll(Config.DEBUG);
	}
 
	@Override
	public void render(float delta) {
		stage.act(delta);
		stage.draw();
	}
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by NathanSweet** [comment]
GlyphLayout currently wraps "glyph runs" to the next line. I think it would take some significant reworking to have it wrap before `com` in the case you show.

**Comment by Totalexx** [comment]
Will you fix it?

**Comment by NathanSweet** [comment]
I'd like to fix it, but it's a big enough change that I'm unlikely to be able to find time to do so any time soon. Sorry!

**Comment by Totalexx** [comment]
Okay, please fix this when you're free, it's important to us

**Comment by NathanSweet** [comment]
Is it common to change color mid-word?

**Comment by Totalexx** [comment]
No longer, we don't need to change the color in the mid-word, but thank you for responding :)
