### ISSUE TITLE
Creating a window uses dpi scaling while getting display dimensions doesn't

### ISSUE THREAD

**Issue by TheGoldenProof** [libgdx/libgdx#6071]
There may be a simple fix for this but I've been searching the internet for a while and haven't been able to find any solutions. Maybe I'm just not searching the right things.
I'm trying to make a window half the size of the display centered in the screen.
```java
public static void main (String[] arg) {
	LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
	DisplayMode dm = LwjglApplicationConfiguration.getDesktopDisplayMode();

	config.x = dm.width/4;
	config.y = dm.height/4;
	config.width = dm.width/2;
	config.height = dm.height/2;
	
	new LwjglApplication(new Main(), config);
}
```
The problem is that getting the dimensions from the DisplayMode gives my monitor's actual resolution (3840x2160) while the creation scales the coordinate up based on my dpi scaling (175%), making things incorrectly positioned and sized.
If I try to set x and y to 0, it places it a pixel to the right and its dimensions are actually 3360x1890 instead of 1920x1080.
From what I gather, this problem can get really complicated, so here's my simple solution that shouldn't break anybody else's stuff: add an option to the LwjglApplicationConfiguration that lets you specify whether to use scaled coordinates or not. I would like my game to be scaled by my scaling factor, I don't want to have to turn off dpi awareness for the whole game, but I would also like to be able to make it the size I want.

A similar problem happens when I enter fullscreen mode, it chops everything off because it tries to make the window's size 6720x3780

libgdx 1.9.10

- [x] Windows

EDIT:
I see [here](https://github.com/libgdx/libgdx/wiki/Querying-%26amp%3B-configuring-graphics-%28monitors%2C-display-modes%2C-vsync%29) that there was some way to deal with this but I don't have an Lwjgl3ApplicationConfiguration class and the regular LwjglApplicationConfiguration class doesn't have the setHdpiMode function. I also changed to libgdx 1.9.11-SNAPSHOT just to be sure it wasn't there, and I did see a useHDPI field but it doesn't seem to do anything (I'm not sure if this field was there in 1.9.10)

**Comment by TheGoldenProof** [comment]
found [this](https://www.badlogicgames.com/wordpress/?p=3870)

**Comment by NathanSweet** [comment]
For LWJGL2 you can try using `setProperty("sun.java2d.uiScale", "1");` or  `-Dsun.java2d.uiScale=1`.
