### ISSUE TITLE
Add api to programmatically change the style of status bar for ios

### ISSUE THREAD

**Issue by varrav** [libgdx/libgdx#6076]
#### Issue details
If an app draws under the status bar then it could be very useful to be able to change the style of the status bar (f.e. if app background is light then programmatically set the status bar style as Dark). 

There is a deprecated method `UIApplication.setStatusBarStyle()` but Apple [suggests](https://developer.apple.com/documentation/uikit/uistatusbarmanager/3213942-statusbarstyle) to override `UIViewController.getPreferredStatusBarStyle()` to change the style. Seems the same thing is already done in LibGDX to change the visibility of status bar via overriding`UIViewController.prefersStatusBarHidden()` in `IOSGraphics.IOSUIViewController` to return 'visibility' value from `IOSApplicationConfiguration.statusBarVisible`.

Is it possible to add a field `public UIStatusBarStyle statusBarStyle` into `IOSApplicationConfiguration` and override `UIViewController.getPreferredStatusBarStyle()` in `IOSGraphics.IOSUIViewController` to return `app.config.statusBarVisible` value?

#### Version of LibGDX and/or relevant dependencies
1.9.10

#### Please select the affected platforms
- [x] iOS (robovm)

**Comment by MrStahlfelge** [comment]
I think this is an edge case, so instead of a change to libgdx you can inject your own UIViewController overriding the method.

In IosLauncher:

       IOSApplication app = new IOSApplication(game, config) {
            @Override
            protected IOSGraphics.IOSUIViewController createUIViewController(IOSGraphics graphics) {
                return new MyUIViewController(this, graphics);
            }


And new file:

```
public class MyUIViewController extends IOSGraphics.IOSUIViewController {
    protected MyUIViewController(IOSApplication app, IOSGraphics graphics) {
        super(app, graphics);
    }

   // override here
```

**Comment by MrStahlfelge** [comment]
Closing this. If you think you cannot use my given solution, please reopen.
