### ISSUE TITLE
Issue with Widget Visibility

### ISSUE THREAD

**Issue by kali-gandaki** [libgdx/libgdx#6081]
## Issue details

I have this weird issue in my android game where toggling widget visiblitiy ( ImageButton and ImageTextButton in my case ) does not draw the widget (sometimes). I am not able to reproduce the issue as it only happens sometimes. My game is completely in scene2d.

I have render code like below 

```java
@Override
public void render(float delta) {
    doSomeUpdate();
    backGroundStage.getViewport().apply();
    backGroundStage.draw();
    stage.getViewport().apply();
    stage.act(delta);
    stage.draw();
}
```
A ImageButton Widget is present in the stage and its default visibility state is set to false. In doSomeUpdate function, If certain conditions are met, I turn on the visibility of that ImageButton. 
So here is the catch, the setVisible(true) call works as the widget can receive click events, i.e: If I press on the location where the button should be present, a click event is triggered. But the actual button is not rendered ( or drawn ) on the screen. My game is available in both IOS and Android platform but No users from IOS platform has complained about the issue yet so I believe this issue is only relevant to android.  

#### Please select the affected platforms
- [ ] Android

**Comment by NathanSweet** [comment]
Without repro, we can't investigate or fix the bug: 
https://github.com/libgdx/libgdx/wiki/More-Info

You'll have to debug. You can do `button.debug()`, maybe it's not positioned in the right place. Breakpoint in the widget draw method, make sure it's drawn, etc.
