### ISSUE TITLE
Incorrect Gdx.graphics.getDensity() value on iOS Simulator

### ISSUE THREAD

**Issue by cellcrowd** [libgdx/libgdx#6083]
#### Issue details
Gdx.graphics.getDensity() is returning different values between the iOS simulator and the physical device. For instance on a physical iPhone XS Max the function returns 2.8625 whereas on the XS Max simulator it returns 1.65

#### Reproduction steps/code
Log Gdx.graphics.getDensity() on a physical device and on a simulator of same model

#### Version of LibGDX and/or relevant dependencies
1.9.11-SNAPSHOT

#### Please select the affected platforms
- [ ] Android
- [X] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by cellcrowd** [comment]
In addition, Gdx.graphics.getWidth() and Gdx.graphics.getHeight() don't seem to be consistent. iPhone 8 Plus returns 1242x2208 on the simulator and 1080x1920 on the physical device. As obviously it is not taking the downsampling into account as seen here https://www.paintcodeapp.com/news/ultimate-guide-to-iphone-resolutions, this seems to be a simulator issue? If so, how to make the simulator behave as the actual device?

**Comment by MrStahlfelge** [comment]
In general, the simulator just is not the real device and thus performing a bit different.
Best is if you step through the code, by debugger and with your IDE. The code you are searching for is distributed on IOSApplication.java and IOSGraphics.java, and it is hard to tell which values are set without debugging. If you find a problem with the implementation, please reopen the issue stating what exactly is wrong or providing a PR fixing it.
