### ISSUE TITLE
Window resize on Windows only updates after a render

### ISSUE THREAD

**Issue by guichazan** [libgdx/libgdx#6085]
This issue was tested on Windows 10, but i believe it occurs in all Windows versions.

Steps to reproduce:
1. Launch any application with LwjglApplicationConfiguration.resizable=true
2. Drag the window decreasing its size. Be careful to not let the mouse cursor get inside the cliente area to prevent a refresh.

If you release the mouse button, the window is not resized. It will be resized if you move the mouse into the client area, because then a refresh will be issued.

Problem: the Display.update(false) is called only in a refresh in LwjglApplication

			if (shouldRender) {
				graphics.updateTime();
				graphics.frameId++;
				listener.render();
				Display.update(false); // <<<<<<
                        }

How to fix: move the Display.update(false) to outside the if condition, calling it every loop.

Workaround:  add a dummy postRunnable to make the window refresh happen constantly (not good!)

... In my DesktopLauncher class:

      new LwjglApplication(loader, config);
      Gdx.app.postRunnable(this); // this implements Runnable

      public void run()
      {
          Gdx.app.postRunnable(this);
      }

**Comment by NathanSweet** [comment]
I verified this using LwjglTestStarter and UISimpleTest modified to have `Gdx.graphics.setContinuousRendering(false);`. The LWJGL2 Display methods getWidth, getHeight, wasResized, etc do not see that the window is resized until the mouse enters the window. I doubt there is anything we can do, it seems like an LWJGL2 bug. LWJGL2 is not active anymore, so I doubt they will fix it. They may accept a fix we provide, but we probably should ask if that is the case before making the effort.

**Comment by guichazan** [comment]
Thanks for the feedback. You are right: i'm using LWJGL2 because it gives less problems when running in Mac OS, and also it has a wider support (for old desktop computers). I'll close it for now.
