### ISSUE TITLE
Clean up issue tracker

### ISSUE THREAD

**Issue by crykn** [libgdx/libgdx#6089]
Over the last few weeks, I had a look at most of the issues in the libGDX issue tracker. There are quite a few that should have been closed long ago or have since resolved themselves.

This is a list of issues I identified, where closing them may be warranted to clean up the tracker. Discussion is very welcome!

- #3335: seems to be resolved according to two comments
- #3559: the issue seems to be related to specific hardware, so there’s nothing libGDX can do on its end; the Mac issue mentioned in the last post is a separate problem (only core profile support on Mac)
- #3795: no-one seems to have had this issue since 2016; a commenter couldn’t reproduce it on Windows, I couldn’t reproduce it on Mac OS 10.15.5 either
- #4802: not enough information
- #5224: not enough information
- #5357: not enough information?
- (#5529: was resolved on fbx-conv’s end; it seems that adding a note to CHANGES (as suggested in the first post) wasn’t wanted) _-- may require a new fbx-conv release_
- #5667: not a problem on libGDX’s end
- #5827: duplicate
- #5850: not an actual issue
- #5957: no fix planed, as far as I can see
- #6006: no fix required, as there doesn’t seem to be valid use case/another solution was suggested
- #6027: duplicate
- #6064: duplicate
- #6065: no fix needed/planned, as this is not part of the Bitmap Font Generator spec

The following issues are all related to LWJGL 2, which isn't maintained anymore. So it probably would be best to set the LWJGL 3 backend as the default one and close those issues.
- #3813: seems to be fixed in LWJGL 3
- #4479
- #4686: is fixed in LWJGL 3
- #5660
- #5996: doesn’t happen with LWJGL 3

**Comment by mgsx-dev** [comment]
about #5529 i think it requires a new fbx-conv release with the fix prior to be closed, devs still have the issue with latest fbx-conv so i think it's better to have it opened.

**Comment by yuripourre** [comment]
#4510 can be closed also, it doesn't apply anymore.

**Comment by NathanSweet** [comment]
Thanks for making this list! I believe I got all of them except for #5529. It's not clear if it can be closed.

I'll go ahead and close this one, since the goal was to close issues! If people find more post them here and we'll reopen.
