### ISSUE TITLE
LibGdx - How to create a Screen for Game-Preferences? Example?

### ISSUE THREAD

**Issue by alexanderKoltman** [libgdx/libgdx#6090]
I am new in the "LibGdx - game development" topic and try to implement a small game. I would like first to start with a "preferences"-screen, similar like:

https://www.gamedevelopment.blog/wp-content/uploads/2017/01/perfdone.png

or like:

https://img.degreed.com/image/fetch/pg_1/w_564,h_175,c_fill,g_faces:center,f_auto,q_auto,dpr_2.0/http%3A%2F%2F4.bp.blogspot.com%2F-0704s6KBqxk%2FT1gak1cbNVI%2FAAAAAAAAA-4%2F5T0dgHWBYfA%2Fs400%2FOptionsScreen.png

I was also searching in google, but those examples does not help for me as a starter with less knowledge.

I would be happy, if someone could help me with that.

Thanks

**Comment by yuripourre** [comment]
For this kind of issue, I suggest you to try the libgdx Discord: https://discord.gg/6pgDK9F

**Comment by EtK2000** [comment]
Requesting this be closed
