### ISSUE TITLE
Default Actions does not render frames as expected if continuous rendering is not enabled

### ISSUE THREAD

**Issue by PROSKEY** [libgdx/libgdx#6095]
#### Issue details
As per the docs default actions should call `requestRendering()` but in android it is not working as expected. 

#### Reproduction steps/code
- I've a scene2d `Button` on which i've set `ClickListener` using `addListener` method 
- on `touchDown()` i'm creating a ScaleTo with value 0.9 and duration of 0.1 seconds. I'm using Action Pool to obtain the object of the action and then applying it to the button
- if continuous rendering is not enabled action gets applied directly i.e. button gets scaled to 0.9 without any intermediate values
- I've tried to call `requestRendering()` after applying action and also 
- if action is applied in `Gdx.app.postRunnable()` it does not scale directly to the final value but it is little bit choppy. like when action needs 5-6 frames to finish the animation, it takes only 3 frames(static) and between 1st render and the 2nd render of the frame there is huge delay of 100ms(average) and i'm not doing anything heavy that may take more time to render a single frame.this happens in the fresh libgdx generated code too. 
Version of LibGDX - 1.9.10

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by NathanSweet** [comment]
You can see in Actor#act that it calls requestRendering. Likely your action has no duration. Otherwise:
https://github.com/libgdx/libgdx/wiki/More-Info
