### ISSUE TITLE
Memory leak in ModelBatch.render()

### ISSUE THREAD

**Issue by JackRainy** [libgdx/libgdx#6096]
While profiling my Android application I have noticed that every frame the number of allocated objects is increasing (see the white line on the screenshot below).

#### Issue details
Preliminary investigation has shown that every call of `ModelBatch.render()` creates an instance of `ArrayList` iterator.

![Screenshot 2020-07-05 12-28-43](https://user-images.githubusercontent.com/27405436/86530497-d0d7f180-bec1-11ea-89fc-c6cdfd439699.png)
As I understand, while there is a `forEach()` call, `Iterable<T>` create the iterator on every call, every frame.
```
for (final RenderableProvider renderableProvider : renderableProviders)
     render(renderableProvider, environment);
```
I know there is a flag `Collections.allocateIterators` which could be a reason for that (by default it is "false", which is good). Even when I have set it to "false" explicitly, it did not help.

#### Reproduction steps/code
My code which call the render is quite trivial:
```java
modelBatch.begin(camera)
modelBatch.render(modelList1, environment) // modelList1 - ArrayList<ModelInstance>
modelBatch.render(modelList2, environment) // modelList2 - ArrayList<ModelInstance>
modelBatch.end()
```

#### Version of LibGDX and/or relevant dependencies
gdxVersion = '1.9.10'
        roboVMVersion = '2.3.8'
        box2DLightsVersion = '1.4'
        ashleyVersion = '1.7.0'
        aiVersion = '1.8.0'

KotlinVersion = "1.3.72"
Java version = "1.8.0_251"

#### Stacktrace
```java
iterator:806, ArrayList (java.util)
render:272, ModelBatch (com.badlogic.gdx.graphics.g3d)
render:76, MySceneRenderer (com.mysupergame.game.ui)
...
```

#### Please select the affected platforms
I have experienced that for **Android** platform, and did not check for others, assuming it is not related to the platform.

**Comment by intrigus** [comment]
How do you know that this is a memory leak?
Is your app crashing if you let it run for a long time?

To me it looks like every frame a new object is created which will be garbage collected when there is enough memory pressure.

**Comment by JackRainy** [comment]
@intrigus , yes, most probably, it will be released by GC at some point.
>  every frame a new object is created which will be garbage collected when there is enough memory pressure.

And that is a problem. I don't want my application reaches a "memory pressure" and runs GC quite often since it will affect the performance. Especially, when it happens for no good reason, while the app is idle and no user actions are performed.

I assume it's a well-known fact, that creation of the objects within a render call is a bad idea from performance point of view, and here it happens all the time.

**Comment by JackRainy** [comment]
Currently, I see the only workaround: not using that `render()` method, but move out the calls into my code:
```java
modelBatch.begin(camera)
for (i in 0 until modelList1.size) // iteration without allocation memory for the iterator
    modelBatch.render(modelList1[i], environment)
for (i in 0 until modelList2.size) // iteration without allocation memory for the iterator
    modelBatch.render(modelList2[i], environment)
modelBatch.end()
```

**Comment by obigu** [comment]
The memory issue you describe is not a memory leak nor the problem is in the `render()` implementation. 
Use an `Iterable` implementation that doesn't allocate by making `modelList` a `com.badlogic.gdx.utils.Array` instead of a `java.uitil.ArrayList`.

**Comment by JackRainy** [comment]
@obigu , thank you for the advice using the `com.badlogic.gdx.utils.Array` instead of `java.uitil.ArrayList`. It has helped.
Now I would say it is an imperfection of `ArrayList` implementation.
Anyway, it is not related to `render()` method now. I close the issue.
