### ISSUE TITLE
Kotlin backend for HTLM platform

### ISSUE THREAD

**Issue by hovi** [libgdx/libgdx#6106]
I saw mention of possible usage of kotlin as backend here:
https://github.com/libgdx/libgdx/wiki/Using-libGDX-with-Kotlin

Kotlin is still quite fresh, but looking good. Are there any considerations or plans of implementing it?

**Comment by tommyettinger** [comment]
Long story short, no, the libGDX devs already rejected one alternative HTML backend and getting Kotlin to work on HTML would require another (TeaVM, ByteCoder, or maybe Dragome). To produce HTML output, libGDX uses Google Web Toolkit (GWT), which can only translate Java source code, no Kotlin. You might want to look into [Arc](https://github.com/Anuken/Arc), which is a fork of libGDX that uses TeaVM to target HTML, or [korge](https://korge.org/), which is an unrelated engine that's pure-Kotlin. I'm not strictly opposed to Kotlin personally, but I am unlikely to ever write a game in it because of how much work it would be to get the result on the web.

**Comment by NathanSweet** [comment]
Nice summary @tommyettinger!

**Comment by hovi** [comment]
Thanks for reply. Yeah I get the situation. However I've been using gwt in past and I know fairly well multiplatform kotlin with javascript. I don't mind doing kotlin backend implementation, it's definitely still less (and more pleasant) work than rewriting my project from kotlin to java. I believe it should be fairly straightforward, just implementing required interfaces and coppying code form gwt/java backends, no big challenge.
What do you think? Is there some guideline to implementing custom backend?

**Comment by tommyettinger** [comment]
Well, [TeaVM](http://teavm.org/) is a solid enough option; there's an Arc backend that uses TeaVM (and none that uses GWT). [Bytecoder](https://github.com/mirkosertic/Bytecoder) is still in an early-ish stage, but it looks like it has great potential, supporting some of the more troublesome parts of Java or Kotlin via a WASM target (but if I remember it right, the WASM needs manual garbage collection; I don't know if this is still the case). You can have backends that are independent of the libGDX repo;  [I have this one to support GWT 2.9.0](https://github.com/tommyettinger/gdx-backends).

I feel like most of the interesting libGDX development going on these days happens outside of this repo; the sluggish pace for any feature to actually merge into the official repo is rendering it mostly irrelevant. I would normally volunteer and ask for some permission to close garbage/spam/duplicate issues, or merge PRs, but I doubt I would get it, and there's a bit of a sinking-ship feeling right now associated with libGDX. I think the soul-crushing experience of submitting my last big PR to libGDX has made me much less likely to contribute directly to this repo; I could barely muster a smile when #5900 was actually merged, about 2 weeks after I had submitted the PR but about 5 months after I first tried to solve the relevant bugs. @hovi , I'd encourage you to look at the code in my (and MrStahlfelge's, originally) [gdx-backends repo](https://github.com/tommyettinger/gdx-backends) for how to handle backends that are compatible with libGDX but not at all dependent on the mercurial approval process.

**Comment by julienvillegas** [comment]
"_and there's a bit of a sinking-ship feeling right now associated with libGDX_". Why do you think that is?

**Comment by CoenRijsdijk** [comment]
@tommyettinger I'm currently working on a project which can be used to compile a native app to web, using [Bytecoder](https://github.com/mirkosertic/Bytecoder) I'm working on it until 30 january 2021(my traineeship for Computer Science Bsc degree). Check my project and latest findings here: https://github.com/squins/libgdx-wasm-with-bytecoder
We really would like to have a LibGDX backend for web that can be used with Kotlin. That is the goal 😄. 
I am now working on getting audio and WebGl in the right way. It is really a lot of research work and if people want to help, help is welcome :)
