### ISSUE TITLE
Lwjgl20.toIntBuffer copies the wrong data from the array

### ISSUE THREAD

**Issue by Komposten** [libgdx/libgdx#6112]
#### Issue details
`LwjglGL20.toIntBuffer(int[], int, int)` does not work because it passes the parameters to `BufferUtils.copy(int[], int, int, Buffer)` in the wrong order. Namely, it passes the `offset` value to the `numElements` parameter and the `count` value to the `srcOffset` parameter. This means that it copies the wrong data over to the buffer.

From `toIntBuffer`:
```java
com.badlogic.gdx.utils.BufferUtils.copy(v, count, offset, intBuffer);
```

Signature of `BufferUtils.copy`:
```java
public static void copy (int[] src, int srcOffset, int numElements, Buffer dst)
```

#### Version of LibGDX and/or relevant dependencies
LibGDX 1.9.10 with with the LWJGL backend

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by Darkyenus** [comment]
Interestingly, while `toIntBuffer` exists in [LWJGL3 as well, it does not use `BufferUtils` at all](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3GL20.java#L50).

I am not sure what is going on in the [reported code](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglGL20.java#L61) nor in [`BufferUtils`](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/BufferUtils.java). The order of parameters is all over the place.

**Comment by tommyettinger** [comment]
Wow, BufferUtils is incredibly strange... it mixes measurements in bytes with measurements in array items, typically has multiple overloads for copy() so you can put the Buffer wherever (but as this issue notes, the other `int` parameters are not interchangeable), and in general is pretty inscrutable. I encourage switching to LWJGL3. This definitely looks like a legitimate issue with the LWJGL (2) backend. @PokeMMO , do you have any background on why BufferUtils looks so... sloppy? Most of it seems like it was written 10 years ago, according to `git blame`.

**Comment by PokeMMO** [comment]
I have no idea, sorry. This would probably take some investigation to verify what is calling it correctly and what is not. Or making a breaking change and making everything consistent.

I don't know if the change is good unless we somehow also break the method signature so users don't assume it's fine because it compiles.
