### ISSUE TITLE
Outdated build.gradle file for newest release

### ISSUE THREAD

**Issue by payne911** [libgdx/libgdx#6115]
https://github.com/libgdx/libgdx/blob/master/build.gradle#L22

Shouldn't this now be `'1.9.11-SNAPSHOT'` ?

**Comment by tommyettinger** [comment]
1.9.12-SNAPSHOT. It has been outdated for a full year.

**Comment by payne911** [comment]
I'm not even sure what this line of code even does.

**Comment by Tom-Ski** [comment]
We don't build with gradle (yet), so this isn't really a big deal

**Comment by Tom-Ski** [comment]
closed via 86cbcf5f4ae0a14e5aa062d2234d7c3398a542dd
