### ISSUE TITLE
SelectBox is not visible items of list

### ISSUE THREAD

**Issue by taluks** [libgdx/libgdx#6116]
I have the game with one UI for all resolution, I use FillViewport class for scale. In some cases SelectBox is located at the bottom of the window and then the list items are not visible
#### Issue details
original size: 1024x576
![image](https://user-images.githubusercontent.com/20488327/88162823-858c4580-cc1a-11ea-88bc-6b3b3de88afe.png)

honor 8a: 1560x720
![image](https://user-images.githubusercontent.com/20488327/88162744-6c839480-cc1a-11ea-8457-1002da60e4ea.png)

in my game:
![image](https://user-images.githubusercontent.com/20488327/88164673-1bc16b00-cc1d-11ea-8637-f8ce9c1076b0.png)

#### Reproduction steps/code
```java
public class SelectBoxTest extends ApplicationAdapter {

	public static void main(String[] args) {
		LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
		config.width = 1560;
		config.height = 720;
		new LwjglFrame(new SelectBoxTest(), config);
	}

	private Stage stage;
	@Override
	public void create() {
		stage = new Stage(new FillViewport(1024, 576));
				
	
		String fileSkin = "skin.json";

		AssetManager manager = new AssetManager();
		manager.load(fileSkin, Skin.class);
		manager.finishLoading();

		Skin skin = manager.get(fileSkin);
		Dialog dialog = new Dialog("test", skin);
		
		SelectBox<String> selectBox = new SelectBox<String>(skin);
		selectBox.setItems(new String[] {"one", "two", "three", "four", "five"});
		
		
		dialog.getContentTable().add(selectBox);
		dialog.show(stage);	
		
		Gdx.input.setInputProcessor(stage);
	}

	@Override
	public void resize(int width, int height) {
		stage.getViewport().update(width, height, true);
	}

	@Override
	public void render() {
		Color color = Color.LIGHT_GRAY;
		Gdx.gl.glClearColor(color.r, color.g, color.b, color.a);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		
		stage.act();
		stage.draw();
	}

}
```

#### Version of LibGDX and/or relevant dependencies
all

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by NathanSweet** [comment]
SelectBox only tries to keep the list within the stage, not within the screen. Some of your stage is offscreen. See FillViewport:

> A ScalingViewport that uses {@link Scaling#fill} so it keeps the aspect ratio by scaling the world up to take the whole screen (some of the world may be off screen).

You probably want FitViewport.

**Comment by taluks** [comment]
FitViewport makes interfaces too small, is it possible to manually specify the alignment to the top?
