### ISSUE TITLE
Snapshots

### ISSUE THREAD

**Issue by rdamiano** [libgdx/libgdx#6123]
Apologies as I know this isn't an "issue"-issue, but I'm curious as to the snapshot schedule, mainly when is the next one for 1.9.12-SNAPSHOT

In the final 1.9.11 release and subsequent 1.9.12-SNAPSHOT, GlyphLayout was borked and many labels are overflowing and just looking off. I see a fix was committed almost immediately after  #(8937bde60bf6ffe9a582996c67917d9861fb0801) but there has not been a Snapshot since July 22 with this fix in place. Seems somewhat critical, mainly for UI apps.

![Image](https://i.imgur.com/MkjGyBJ.png)

**Comment by Tom-Ski** [comment]
Slave went down, you should see one within the next hour.
