### ISSUE TITLE
Help with Intersector

### ISSUE THREAD

**Issue by AkashaP** [libgdx/libgdx#6124]
Gdx version '1.9.10'

I need help understanding the Intersector class in com.badlogic.gdx.math.Intersector

I'm using the current line

Intersector.intersectLines(Vector2(0f, 0f), Vector2(0f, 295.53336f), Vector2(191.92181f, 100f), Vector2(40f, 230f), x)

It is drawn with shaperenderer as so:

![image](https://user-images.githubusercontent.com/12569560/89404109-caf15c80-d75c-11ea-916b-c5827517c896.png)

but it's returning true. Why is that?

curiously Vector2(1f, 1f), Vector2(1f, 1.1f), Vector2(191.92181f, 100f), Vector2(40f, 230f) also returns true but Vector2(1f, 1f), Vector2(1f, 1f), Vector2(191.92181f, 100f), Vector2(40f, 230f) returns false

**Comment by julienvillegas** [comment]
Hello 
you should go onto the Discord server for this kind of help..
That said, looking at the code for this method, I think **Intersector.intersectLines** checks whether the two inifinite lines defined by the vectors passed as argments intersects or not (i.e.: Whether the two lines are parallel or not).
If you provide the parameter intersection, and if the two infinite line do intersect, it also tells you where it intersects.
You should use **Intersector.intersectSegments** instead.

intersectSegments
--




intersectSegments
--


 

intersectSegments
--
