### ISSUE TITLE
Petition to reconsider recent change to Gdx.files.external

### ISSUE THREAD

**Issue by rdamiano** [libgdx/libgdx#6134]
So I updated my Snapshot and found my app could no longer find files saved on the device, turns out because Gdx.files.external now points to a different location (on Android).

This commit (a73cfa012eec5a647bc52274c5557948bad67aa3)

I understand the reasoning, but I feel like with already-established apps like mine and many others, Gdx.files.external has been understood to point to the root of the external storage since, basically forever.

My app is very user-generated-files based and I have a /AppName/ folder on the root directory with subfolders and all that, filled with saved data from my users. My app taps into these folders in many different areas of the UI. Right now all of my calls to Gdx.files.external(projectsFolder) for example no longer find anything because since this latest Snapshot it's pointing elsewhere (now to the /data/ folder of the app).

**Which again I understand but, I feel like this should be made to be either a separate function at this point to avoid breaking existing apps or at least have some kind of setting to change desired behavior.** I'd like external to refer to external storage as it has before. Not to mention I have 2 apps that access and share the same /AppName/ folder and is of massive convenience for my Android users (iOS users not so much, as iOS cannot have this functionality - speaking of, the fact the /data/ is cleared when app is uninstalled is also a detriment to many of my Android users, again an issue only my iOS users were plagued with).

Any chance of making this optional behavior and/or reverting to old behavior for Gdx.files.external? I see the reason for this commit was to fix issue #5633 but it seems as long as you request proper permissions and set up the FileProvider you're good - which seems reasonable?

**Comment by rdamiano** [comment]
Hm, I didn't realize Android 11 was gonna bork things up so bad. Oh well I suppose if that's the case this is inevitable.

For anyone reading this this seems to discuss it: https://developer.android.com/preview/privacy/storage
If I understand correctly, as long as you don't target Android 11 and use requestLegacyExternalStorage flag in Manifest, your app will continue to behave as normal and be able to access directories as it has been. But you will have to target Android 11 next year.

So I suppose the advice from @MrStahlfelge is the way to go, and just migrate the data of users from root directory area to the new Gdx.files.external location with my app's next update. Actually, since Gdx.files.external no longer points to root, I need to figure out what call to make to actually access that location since I was relying on that this whole time lol.

Since people here are smarter than me and have more experience, does anyone know if it's possible to access another app's data folder? Since File Explorer apps can access the /data/ folder of all apps installed, can my app A access my other app B's folder as well?

**Comment by MrStahlfelge** [comment]
Wouldn't say I am smarter than you, but if you need to share files between your app, we are back at FileProviders!

You find the external files root with `Environment.getExternalStorageDirectory()`. File Explorer apps will still have read and write access to this directory in the future because they are allowed to ask for the access permission.

**Comment by xGnoSiSx** [comment]
Totally with ModiDev on this one, by perhaps we can have a legacy class left there? Just for people who recompile old apps on old devices with newest libgdx changes and fixes. So preserving some semblance of old behaviour should be there.

With the changes in android 10 & 11, if we need our apps to work on older devices we must be careful.

**Comment by rdamiano** [comment]
Does seem to just be a simple call to "Environment.getExternalStorageDirectory()" and using that path in a Gdx.files.absolute call to basically perfectly mimic old Gdx.files.external() behavior on Android

I had to refactor my code and replace all external calls with absolute, and fetch the proper path on a platform-specific basis. Works quite normally now and once I'm ready to switch over I can just replace the "Environment.getExternalStorageDirectory()" call to "Gdx.files.getExternalStoragePath()" in the Android platform.

I'll close this for now since it does seem this is the required path forward for Android.

**Comment by kairusds** [comment]
> Does seem to just be a simple call to "Environment.getExternalStorageDirectory()" and using that path in a Gdx.files.absolute call to basically perfectly mimic old Gdx.files.external() behavior on Android
> 
> I had to refactor my code and replace all external calls with absolute, and fetch the proper path on a platform-specific basis. Works quite normally now and once I'm ready to switch over I can just replace the "Environment.getExternalStorageDirectory()" call to "Gdx.files.getExternalStoragePath()" in the Android platform.
> 
> I'll close this for now since it does seem this is the required path forward for Android.

Just a quick question, does it work for files on the SD Card too?
