### ISSUE TITLE
StackOverflowError exception in the AnimationController when actions are used

### ISSUE THREAD

**Issue by asu-talk** [libgdx/libgdx#6136]
Hi,
Thank you for developing and supporting this great framework.

I've faced some interesting issue and was able to make it stable reproducible.
Please see details below:

#### Reproduction steps/code

```java
        AssetManager assets = new AssetManager();
        assets.load("3d-models/animation-transition-in-details.g3db", Model.class);
        assets.finishLoading();
        Model model = assets.get("3d-models/animation-transition-in-details.g3db");
        ModelInstance modelInstance = new ModelInstance(model);
        AnimationController animationController = new AnimationController(modelInstance);
        animationController.setAnimation("Suzanne|init", -1);
        animationController.update(animationController.current.duration);
        animationController.action("Suzanne|first", 1, 1f, null, 1f);
        animationController.update(animationController.current.duration);
        animationController.update(0.001f);
        // This invocation throws
        animationController.action("Suzanne|second", 1, 1f, null, 1f);
```

Related model file: [animation-transition-in-details.zip](https://github.com/libgdx/libgdx/files/5111920/animation-transition-in-details.zip)

#### Version of LibGDX and/or relevant dependencies
1.9.11

#### Stacktrace
```java
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.StackOverflowError
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:134)
Caused by: java.lang.StackOverflowError
	at com.badlogic.gdx.graphics.g3d.utils.AnimationController.queue(AnimationController.java:425)
	at com.badlogic.gdx.graphics.g3d.utils.AnimationController.animate(AnimationController.java:363)
	at com.badlogic.gdx.graphics.g3d.utils.AnimationController.queue(AnimationController.java:425)
	at com.badlogic.gdx.graphics.g3d.utils.AnimationController.animate(AnimationController.java:363)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [ ] MacOS
_Have not tested on other platforms but think it can be reproducible as well_

**Comment by mgsx-dev** [comment]
@asu-talk I was able to reproduce the issue thanks to your neat test case :heart: 

I think i found a better fix which fixes your current test case, let me know if you think i missed something or if it doesn't fix some other test cases of yours.

**Comment by asu-talk** [comment]
Thank you! Could you please take a look at the comment I've left in the PR?
