### ISSUE TITLE
A Box2D dependent GWT module fails to build

### ISSUE THREAD

**Issue by metaphore** [libgdx/libgdx#6137]
#### Issue details

After upgrading my projects to LibGDX 1.9.11 (from 1.9.10) the GWT modules fail to build if they include Box2D dependencies.

This is the error message from `./gradlew html:superDev`

```
Loading inherited module 'com.mygdx.game.GdxDefinitionSuperdev'
   Loading inherited module 'com.badlogic.gdx.physics.box2d.box2d-gwt'
      [ERROR] Unable to find 'com/badlogic/gdx/physics/box2d/box2d-gwt.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?
```

Apparently the `box2d-gwt.gwt.xml` file is missing in [`com.badlogicgames.gdx:gdx-box2d-gwt:1.9.11:sources`](https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-box2d-gwt/1.9.11/gdx-box2d-gwt-1.9.11-sources.jar)

This issue is most likely a regression from #5956

#### Reproduction steps/code
1. Generate a clean project using the setup app with HTML backend and Box2D dependency.
2. Issue `./gradlew html:superDev`

#### Version of LibGDX and/or relevant dependencies
- 1.9.11
- Box2D
- GWT

#### Please select the affected platforms
- [x] HTML/GWT
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by MacCode7110** [comment]
Exact same issue I'm encountering right now, thanks for posting it!
