### ISSUE TITLE
Ashley compile error on HTML/GWT

### ISSUE THREAD

**Issue by kevinbaptist** [libgdx/libgdx#6157]
#### Issue details
I am not able to run `./gradlew html:dist`... Not sure what is the issue. 

#### Reproduction steps/code
[Source code](https://github.com/kevinbaptist/TicTacToe)

#### Version of LibGDX and/or relevant dependencies
* gdxVersion = '1.9.10'
* roboVMVersion = '2.3.8'
* ashleyVersion = '1.7.3'

#### Stacktrace
```java
Compiling module pt.ladon.games.GdxDefinition
   Tracing compile failure path for type 'com.badlogic.ashley.utils.ImmutableArray'
      [ERROR] Errors in 'jar:file:/Users/.../.gradle/caches/modules-2/files-2.1/com.badlogicgames.ashley/ashley/1.7.3/2ce2174d32be41a7ebaa50aeb97183fda4ef3171/ashley-1.7.3-sources.jar!/com/badlogic/ashley/utils/ImmutableArray.java'
         [ERROR] Line 74: Type mismatch: cannot convert from capture#1-of ?[] to V[]
   [ERROR] Aborting compile due to errors in some input files

```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [x] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

If you need any more information, please let me know. Many thanks

**Comment by mgsx-dev** [comment]
it was fixed in Ashley repository (not a libgdx issue), you need to compile Ashley version 1.7.4 locally though because this version is not released yet.
see https://github.com/libgdx/ashley/pull/279
