### ISSUE TITLE
Rendering freezed due to OS power saving setting

### ISSUE THREAD

**Issue by Hangman** [libgdx/libgdx#6158]
#### Issue details
When a Lwjgl3 application is running in windowed mode and the OS turns off the monitor to save power, the app doesn't continue rendering when the monitor is back on again. Resizing the window or switching the focus to another app wakes it up and rendering continues as usual. Not tested on Linux & Mac.
Setup: Windows 10, NVIDIA Titan Xp running latest driver (452.06)

#### Reproduction steps/code
- create a new project
- add a line in the render method to move the badlogic image so you're able to notice a frozen screen
- run it
- wait until the OS turns off the monitor (you might want to reduce the time until this happens, go to settings => system => power settings => set it to 1min)
- move your mouse to activate it again
- see

#### Version of LibGDX and/or relevant dependencies
1.9.11

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by crykn** [comment]
Hey @Hangman, I can't reproduce your issue on Windows 10, GTX 1070, Driver 452.06. Are `pause()`  and `resume()`  called, when your monitor turns off (they aren't on my system)?

The code I used for testing this:

```
public class Issue6158 {
	public static void main(String[] args) {
		Lwjgl3ApplicationConfiguration config = new Lwjgl3ApplicationConfiguration();
		config.setWindowedMode(1280, 720);

		new Lwjgl3Application(new ApplicationAdapter() {
			@Override
			public void pause () {
				System.out.println("PAUSE");
			}

			@Override
			public void resume () {
				System.out.println("RESUME");
			}

			float f = 0;

			public void render(){
				Gdx.gl.glClearColor(f % 1, 1, 0.7F, 1);
				Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

				f += Gdx.graphics.getDeltaTime() / 2.5F;

				if(Math.abs(2 - (f % 2) ) < 0.003)
					System.out.println("RENDERING");
			}
		}, config);
	}
}
```

**Comment by Hangman** [comment]
Nope, they're not called.
But I had the possibility to quickly test it on another computer and also couldn't reproduce the issue there.
A good sign that this is caused by my driver/setup maybe? Never experienced it in other applications though.

**Comment by raeleus** [comment]
Is resize called when you turn off your monitor?

**Comment by Hangman** [comment]
And just to mention it: the game code was running just fine for me, so your test method isn't really applicable to test this.
I was able to give inputs, got visual feedback after "wake up like I described above" etc. that everything was running fine. 
As only the rendered output was never pushed to the window. 

@raeleus 
Yes resize is called. Do you need to know when it's called exactly? It's only called once.

**Comment by Hangman** [comment]
Just tested if the problem occurs if I switch off the monitor manually and it doesn't.

**Comment by crykn** [comment]
@Hangman my test changes the background color of the screen, so you will notice when no changes are pushed to the screen.

**Comment by Hangman** [comment]
Oh yeah sure, hard to see. I looked for something to render.
Well, due to 3 other computers not having this issue, I guess it's just my driver or something.
So should we close this?

**Comment by mgsx-dev** [comment]
yeah, we could reopen later if it's really a libGDX issue.
