### ISSUE TITLE
New Wiki Page  - Update JDK Recommendations - FAQs

### ISSUE THREAD

**Issue by Mr00Anderson** [libgdx/libgdx#6166]
Please ensure you have given all the following requested information in your report.

#### Issue details
Officially opening an issue to document recommended JDK usage.

##### Key points
- Short history of the JDK and the recent licensing changes
- The benefits of using JDK 8 vs JDK 11 vs JDK 14
- How to use two or three (JDK 8 for code, JDK 11 for Hot swapping and 14 for packaging.

Example: I write in and compile for language 8, use DECVM 11 on my dev machine and then JDK 14 on a CI server to package.

##### Generally
-  JDK 8 is the most comparable and as well as the most supported in the Java echo system
-  JDK 11 (DECVM) version can do better hot swapping
-  JDK 14 has jpackage a way to make platform specific executable/installer with self contained JDK

**Comment by Mr00Anderson** [comment]
Please assign me to this issue. I will take care of it within a week or so.

**Comment by Mr00Anderson** [comment]
From Discord:

Lyze Today at 11:29 AM
If you're doing android/ios: 8
If you're doing gwt: up to 11 (with gdx-liftoff and different gwt backend)
If you're doing desktop: up to 14

**Comment by piotr-j** [comment]
It is also important to make a clear distinction that JDK version and language level are not the same. You can use lambda expressions on iOS (java 8 feature) but some APIs from that version are not available. That same caveat applies to Android and GWT. Many APIs are not available but language features are.

**Comment by MrStahlfelge** [comment]
All in all as a general recommendation for beginners wanting an easy recommendation that fits all targeted platforms: OpenJDK8 with language level 7 is safe to use.

**Comment by tommyettinger** [comment]
@MrStahlfelge well... AdoptOpenJDK, yes, but some vendors are broken when running LWJGL2 apps (it seems like a lot of vendors, including whoever supplies to some Linux distros). AdoptOpenJDK also has a very beginner-friendly installer :grin:

**Comment by Mr00Anderson** [comment]
I was not thinking about which distro to write about. Now that this has been brought up though it is very valid to talk about the distributions that are available. Fortunately we have all of the various people here to discuss this. Just to make sure I understand this right. The first recommended JDK distro would be Adopt, Or make no recommendations and just list out the pros and cons of each distro?

**Comment by Mr00Anderson** [comment]
Just a in the works preview https://gist.github.com/Mr00Anderson/727ea38026125207c4d53b9b04b67f53
Still working on this.

**Comment by MrStahlfelge** [comment]
Any news on this?

**Comment by Mr00Anderson** [comment]
> Just a in the works preview https://gist.github.com/Mr00Anderson/cfe4c59482ffb10dc6381932130d1bcb
> Still working on this.
> 
> Fixed the LTS indications.

Ok - Will finish this up by this weekend then and put in the change.

**Comment by raeleus** [comment]
This is a very detailed article and it reads well. Very nice!

**Comment by Mr00Anderson** [comment]
Updated. 
![image](https://user-images.githubusercontent.com/1356935/102216379-09d0b500-3ea9-11eb-9e85-ebf97d61a8c9.png)

**Comment by crykn** [comment]
Hey @Mr00Anderson thanks for the article! Just FYI: I moved the article to a different place in the table of contents, because as of now all articles in the section "Getting Started" link to the new website and this could otherwise be a source of unnecessary confusion.
