### ISSUE TITLE
Incoherence between files created by setup and API

### ISSUE THREAD

**Issue by la-urre** [libgdx/libgdx#6197]
I just downloaded gdx-setup jar today (I can't find any version info anywhere).

I created a new project with all boxes ticked for sub-projects. The html sub-project does not compile, because of the use of a very recently introduced API. The problem is in HtmlLauncher.java, where a constructor from `com.badlogic.gdx.backends.gwt.GwtApplicationConfiguration` (recent addition in #6169) is called. I supposed this change has not been released yet (the lib in use in the generated project is gdx-backend-gwt-1.9.11).

I don't know what exactly happened. A new release of gdx-setup maybe went out with up-to-date resources while the API is not released yet. The consequence is that the experience for a new user like me is not as straightforward as I would expect. 

Maybe one way to improve the situation in the future is to make sure the release of gdx-setup and libs are synced ?

**Comment by MrStahlfelge** [comment]
The problem is that the templates are already for 1.9.12-SNAPSHOT, while the dependencies are still 1.9.11.

Best is if you merge your HTML directory against the template version from 1.9.11 tag.

We are currently talking about a new setup and that should address this kind of problem.

**Comment by crykn** [comment]
@MrStahlfelge was a bit quicker, but yes, @la-urre, unfortunately you're right. The setup tool is pulling its template files from the repo, which out-of-the-box is not compatible with gdx 1.9.11. If you want to create a new project without copying folders, I would suggest using [gdx-liftoff](https://github.com/tommyettinger/gdx-liftoff), which also has some qol improvements for gwt projects. 

Regarding the setup tool in general: there is currently a major overhaul of the setup tool under way. We also want to extend the number of offered templates as well as the support for third-party libraries created by the community. If everything works out, we should have a web-based tool (inspired by [spring-initializr](https://start.spring.io/)) for our next libGDX release, but no promises yet.

**Comment by la-urre** [comment]
Thanks for the quick answers! I am looking forward the next version of the setup tool then. Keep up the good work!

**Comment by crykn** [comment]
I changed the [wiki link](https://github.com/libgdx/libgdx/wiki/Project-Setup-Gradle) to an older (working) version of the setup tool.
