### ISSUE TITLE
Build failure for html sub-project when Box2D is enabled

### ISSUE THREAD

**Issue by la-urre** [libgdx/libgdx#6198]
I just generated a new project, with a HTML sub-project and Box2D enabled.

When invoking `./gradlew :html:superDev` I get the following error:

```
Loading inherited module 'com.mygdx.game.GdxDefinitionSuperdev'
   Loading inherited module 'com.badlogic.gdx.physics.box2d.box2d-gwt'
      [ERROR] Unable to find 'com/badlogic/gdx/physics/box2d/box2d-gwt.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?
```

Is it a configuration problem on my side ?

**Comment by crykn** [comment]
Hey @la-urre, this bug was introduced with 1.9.11, see #6137. Either use the 1.9.12-SNAPSHOT, or (better) apply [this fix](https://github.com/libgdx/libgdx/pull/6138#issuecomment-680503361) yourself.
