### ISSUE TITLE
Scene2d. ScrollPane glitch when scroll bars fade out.

### ISSUE THREAD

**Issue by DavidPDev** [libgdx/libgdx#6204]
#### Issue details
Glitch of an non-updated area behind scroll bars.
In previous versions of libGDX (1.9.10 and earlier)  this "bug" didn't happen.

#### Reproduction steps/code
Very simple to reproduce. Just run the standard test "ScrollPaneTest" from the test suite.
When the scroll bars fade out the text behind gets 'invisible'.

![image](https://user-images.githubusercontent.com/25801199/95368318-434bd980-08d6-11eb-8921-9f9ffa38bdc4.png)

When the scroll bars disappear -> Note that the text behind is not updated. On previous LibGDX versiones didn't happen.

![image](https://user-images.githubusercontent.com/25801199/95368354-4e066e80-08d6-11eb-95ef-c0b11697d01d.png)

When the flag "scroll bars on top" is active seems to work as expected.
Maybe this is the intended working mode, but from my point of view the effect seems strange...

#### Version of LibGDX and/or relevant dependencies
1.9.11
1.9.12-SNAPSHOT

#### Please select the affected platforms
- [x] Android
- [x] Windows

**Comment by NathanSweet** [comment]
It is working as expected. "Scrollbars on top" is what controls if the scrollpane's contents is visible underneath the scrollbars. It's more flexible to have them as separate settings, ie not to tie "scrollbars on top" to "fade scrollbars".

**Comment by DavidPDev** [comment]
Thank you! Yes, I think setScrollbarsOnTop(true); solves the issue.
