### ISSUE TITLE
androidx.multidex support

### ISSUE THREAD

**Issue by CaramelAds** [libgdx/libgdx#6221]
#### Issue details

I have android project with libgdx 1.9.2
and need update it to androidx but after updating (only one lib - multidex) appears error 
"Cannot change resolution strategy of dependency configuration ':android:natives' after it has been resolved."
Also, I updated libgdx to newest version 1.9.11 which supports androidx according to changelog but it didn't help me
If you didn't encounter with that problem while using androidx and multidex please tell me because I assume it's inner project problem
#### Reproduction steps/code
-
#### Version of LibGDX and/or relevant dependencies

libdgdx 1.9.11
multidex 2.0.0

#### Stacktrace

"Cannot change resolution strategy of dependency configuration ':android:natives' after it has been resolved."
```

#### Please select the affected platforms
- [ ] Android

**Comment by SimonIT** [comment]
Does making the change of #6120 maybe fix the problem? If not #5303 seem to be the same problem. There were also some solutions

**Comment by CaramelAds** [comment]
Ok, I found solution by changing one string in the build.gradle
Before
![image](https://user-images.githubusercontent.com/45758839/95792380-13447200-0cec-11eb-9069-65224eeb2589.png)
After
![image](https://user-images.githubusercontent.com/45758839/95792329-f3ad4980-0ceb-11eb-86af-0c592e26cdd5.png)

**Comment by kaloyanhlebarov** [comment]
That worked for me also. TY!
