### ISSUE TITLE
Jnigen does not have compiler suffix, and resets it every build

### ISSUE THREAD

**Issue by Dunnysoft** [libgdx/libgdx#6224]
When using a fresh download of the latest build of Jnigen (with and without the template), it gives the following error on the Windows build:

`Property "env.PATH" has not been set`

It then searched the global path for this:
`[available] Unable to find x86_64-w64-mingw32-g++`

If you manually add '.exe' to the compiler-suffix in the XML files, it removes it every build and is then unable to actually run the compiler (which exists and is in the path).

Which then leads to the following string of errors:

```
Property "compiler-found" has not been set
create-build-dir:
Skipped because property 'has-compiler' not set.

compile:
Skipped because property 'has-compiler' not set.

link:
Skipped because property 'has-compiler' not set.

strip:
Skipped because property 'should-strip' not set.

````

And then ant cannot run.

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by PokeMMO** [comment]
Looks like I never finished the compilerSuffix support. The ant files being replaced every run is normal, all contents should be generated dynamically based on the content of the BuildTargets (in gradle or java).

Could you open this ticket on the https://github.com/libgdx/gdx-jnigen repo and I'll see about finishing the support soon?

**Comment by Dunnysoft** [comment]
Done!  Thanks for your quick response and action
