### ISSUE TITLE
[Feature Request] Binary Space Partition (BSP) structure

### ISSUE THREAD

**Issue by yuripourre** [libgdx/libgdx#6227]
I am creating this issue so people can contribute to this idea. This is a must-have feature for many 3d games.

BSP allows developers to work with just a subset of geometries at a given moment, it can be used to improve rendering and/or check collisions.

Draft interface:
```
public interface BSP {
    void insert(Object userObject, BoundingBox bounds);
    void insert(Object userObject, Sphere sphere);
    void insert(Object userObject, Triangle triangle);
    void insert(Object userObject, Vector3 point);
    /...

    void remove(Object userObject);

    // methods to query geometries
    Set<Object> queryNear(Frustum frustum);
    Set<Object> queryNear(Ray ray);
    Set<Object> queryNear(BoundingBox aabb);
}
```

What do you think?

**Comment by mgsx-dev** [comment]
I think it would be a great addition, but i think maintainers have to state if they want to accept a feature like this (i don't know how large it could be). @Tom-Ski @NathanSweet ?

My first quick thoughts about the design : 

Ii think we need to attach both a shape (BBox, triangle, Vector3, Sphere, etc) and a user object (eg. ModelInstance, Light, etc). Insert method could be like this : `void insert(BoundaryBox bounds, Object userObject)` and we also need some remove methods obviously : maybe something like `void remove(Object userObject)`.

Querying Ray and BBox is good, we would also need OBB and AABB (BBbox).

I'm not sure if we need to retrieve root Node, i guess Node class should stay private and not exposed to use code.

Let see what others think about it.

**Comment by yuripourre** [comment]
@mgsx-dev Thank you so much for the ideas, updated the draft code.

I have a working sketch that can handle Vector3 I can publish here as soon as I do some clean up.

**Comment by NathanSweet** [comment]
I'm open to adding it, though I probably won't maintain it personally unless I can find a use for it in my projects. That means @yuripourre or others who do use it would need to maintain it.

**Comment by yuripourre** [comment]
@NathanSweet That's a fair point, I can be the mantainer for this feature.

**Comment by mgsx-dev** [comment]
I'll surely use it in my 3D projects (i already need it actually), so I can help to maintain it. @yuripourre yes, let create an initial PR with minimum features (marking it as draft) then we could work on it to refine the design. Since Nathan is OK with it, i'm closing the request now.
