### ISSUE TITLE
The "3D Tank Battle Video" youtube link from the 3D-Particle-Effects page is private and can't be viewed.

### ISSUE THREAD

**Issue by travisfw** [libgdx/libgdx#6237]
The [3D-Particle-Effects wiki page](https://github.com/libgdx/libgdx/wiki/3D-Particle-Effects ) was mentioned in Discord recently. I clicked through on [the "Tank Battle" link](https://www.youtube.com/watch?v=lt9kYDb9p78 ) and the video was private. Maybe there's a public version someone knows of? Or maybe just delete the broken link?

**Comment by crykn** [comment]
Hey @travisfw, I just had a look and couldn't find a public or archived version of the video. But according to Wayback Machine, it was uploaded by [John Renner](https://www.youtube.com/user/rennerjc/), so if you're interested in the video maybe you could contact him. For the time being I will remove the link from the wiki and close this issue.
