### ISSUE TITLE
Problem with org.lwjgl.Sys on Raspberry

### ISSUE THREAD

**Issue by LucasFebatis** [libgdx/libgdx#6249]
The problem happens when I try to run the application on the Raspberry Pi 3 so it seems to be a problem with the compilation for the ARM architecture. Although on Android it works

I've used lwjgl 3 on raspberry pi 3 and it works well

Follow the stack:

```
Exception in thread "LWJGL Application" java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.Sys
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setVSync(LwjglGraphics.java:617)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:125)
```

Project created with gdx-setup

gdxVersion = '1.9.11'

- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [X] Linux
- [ ] MacOS

**Comment by MrStahlfelge** [comment]
You have to use 1.9.12-SNAPSHOT for arm support.

**Comment by LucasFebatis** [comment]
Same Error with 1.9.12-SNAPSHOT

**Comment by SimonIT** [comment]
You also are not using lwjgl3. Else the package in the stacktrace would be `com.badlogic.gdx.backends.lwjgl3` and the classes would be `Lwjgl3Graphics` and `Lwjgl3Application`

**Comment by LucasFebatis** [comment]
Wow, Replacing

`api "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"`

with

`api "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"`

Works well

Thanks

**Comment by LucasFebatis** [comment]
Remembering that for MacOS requires the VM Option -XstartOnFirstThread
