### ISSUE TITLE
ProgressBar is not displaying properly without knob

### ISSUE THREAD

**Issue by Daniikk1012** [libgdx/libgdx#6259]
ProgressBar and Slider-s do not properly display values if there is no knob. When showing minimal value it shows ProgressBar filled by half, but touch works as it should: when you press to the left side, the value is set to the minimal.

#### Screenshot

![a](https://user-images.githubusercontent.com/49123959/97888017-d69cf100-1d54-11eb-9a65-cc634415e7b1.png)

#### Reproduction steps/code

To reproduce that bug you should create a ProgressBar or Slider and set it's value to minimal:
```java
ProgressBar progressBar = new ProgressBar(0f, 100f, 1f, game.skin, "loading"); //'loading' style has no knob
progressBar.setValue(0f);
table.add(progressBar);
```

#### Workaround

Issue is gone when you assign ProgressBar's knob to an empty drawable:
```java
game.skin.get("loading", ProgressBar.ProgressBarStyle.class).knob = new BaseDrawable();
ProgressBar progressBar = new ProgressBar(0f, 100f, 1f, game.skin, "loading"); //'loading' style has no knob
progressBar.setValue(0f);
table.add(progressBar);
```

#### LibGDX versions

The bug is present in LibGDX versions 1.9.11 and 1.19.12 (Others not tested)

**Comment by obigu** [comment]
I have been able to reproduce. The issue happens when you use a `knobBefore` drawable that has has a "large size" (the issue is not visible when using a 1px pixmap for solid colors for instance) and the `knob` drawable is `null`. In my case what I see is that the `knobBefore` drawable is displayed on the progressBar and it takes a larger or smaller portion of it depending on its size (not always half of it, you can try with a differently sized `knobBefore` drawable). I've used the following code for reference:
```
ProgressBar.ProgressBarStyle progressBarStyle = new ProgressBar.ProgressBarStyle(bgDrawable, null);
        progressBarStyle.knobBefore = knobBeforeDrawable;
//        progressBarStyle.knob = new BaseDrawable();
        ProgressBar progressBar = new ProgressBar(0f, 100f, 0.001f, false, progressBarStyle);
        progressBar.setSize(600f, 30f);
        progressBar.setValue(0f);
        stage.addActor(progressBar);
```

**Comment by tommyettinger** [comment]
In trying to solve a different issue that appears to have been introduced a version after this one, I noticed this commit might be related to this issue: https://github.com/libgdx/libgdx/commit/7f0a97f092b513572afa86432c3b949c0d6f32e9 . This does still seem to be a problem, but it also seems possible to work around by setting `knob` to an empty `Drawable`.

**Comment by NathanSweet** [comment]
Need runnable code showing the problem. I tried modifying UITest:
```
slider.getStyle().knob = null;
slider.getStyle().knobBefore = new TextureRegionDrawable(skin.getRegion("white"));
slider.setValue(0);
```
Works fine.

**Comment by NathanSweet** [comment]
Ahh seems like #6533 describes it better.
