### ISSUE TITLE
How to add video texture to a mesh 

### ISSUE THREAD

**Issue by vaaneeunbnd** [libgdx/libgdx#6260]
Hello, 

I am new to libgdx and wanted to know how we can implement a video texture to mesh for Android Devices. I would be grateful if someone could please help me with that.

Thanks :)

**Comment by SimonIT** [comment]
You maybe wanna try out [gdx-video](https://github.com/libGDX/gdx-video). Sadly, it isn't yet deployed to sonatype. If you got more questions, I'm on the the discord server
