### ISSUE TITLE
Are they any options to do software rendering with LWJGL3?

### ISSUE THREAD

**Issue by Coder246** [libgdx/libgdx#6268]
Especially on older PCs LWJGL3 wont't run...
So my Question is can we render the game with the cpu?
I know that the performance won't be so good. But it is better than nothing.

**Comment by crykn** [comment]
Hey @Coder246!

The only resources I could find on LWJGL and software rendering were for LWJGL2 ([Software Rendering](http://forum.lwjgl.org/index.php?topic=3270.0), [Disable OpenGL temporarily for testing](http://forum.lwjgl.org/index.php?topic=3730.0)). It seems to work there and libGDX offers a corresponding setting for this in [`LwjglApplicationConfiguration#allowSoftwareMode`](https://github.com/libgdx/libgdx/blob/3485b16e8979c0141421bc80cb8831b7a0403f67/backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglApplicationConfiguration.java#L99). 

To figure out whether software rendering also works with LWJGL3, [their issue tracker](https://github.com/LWJGL/lwjgl3/issues) is probably a better place to ask. However, regarding libGDX you should also keep [this](https://github.com/libgdx/libgdx/issues/3711#issuecomment-266269077) in mind. 

For now, I'm closing this, as it is not really a libGDX issue.
