### ISSUE TITLE
Posting lazy runnables

### ISSUE THREAD

**Issue by cypherdare** [libgdx/libgdx#6270]
If you call `Gdx.app.postRunnable()`, all the backends also call `Gdx.graphics.requestRendering()` (except Lwjgl3Application for some reason, and GwtApplication which doesn't support non-continuous rendering). 

If you're using non-continuous rendering, this means you need to create your own solution for lazily doing something the next time rendering occurs, such as your own Runnable manager that is called at the beginning of `render()`. If you have a multi-window application (or an Android live wallpaper / screen saver), then you can't simply make this manager static either. You have to pass it around everywhere or do[ weird workarounds like this](https://github.com/libgdx/libgdx/blob/45a5f24fa5b1228919008c973d85f82332b71fac/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/TooltipManager.java#L151) or [this](https://github.com/libgdx/libgdx/blob/45a5f24fa5b1228919008c973d85f82332b71fac/gdx/src/com/badlogic/gdx/utils/Timer.java#L193).

I ran into this problem because I was trying to set some things to be freed to pools at the end of the frame. But that triggers the next call to `render()`, so everything is needlessly drawn again, and new items need to be returned to the pool again, and we now have a continuous rendering cycle.

So I'm proposing either:

1) Remove  `Gdx.graphics.requestRendering()` calls from the backends that automatically call it when you post a runnable. This breaks current behavior, but it was already inconsistent behavior between backends. People using non-continuous rendering are probably a minority, but will probably also appreciate the extra control given by having the choice of whether a runnable should also trigger rendering.

2) Add `Gdx.app.postLazyRunnable(Runnable runnable)`.

**Comment by MrStahlfelge** [comment]
I am in favor of solution 1. 

Which one do you prefer btw?

**Comment by cypherdare** [comment]
I also favor 1. I'd prefer not to pollute the library solely for backward compatibility. Most libGDX releases have a few minor breaking changes, right?

**Comment by obigu** [comment]
On the java docs of `setContinuousRendering` on `Graphics` it says there are 3 events that trigger a redraw:

```
In case rendering is performed non-continuously, the following events will trigger a redraw:
	 - A call to {@link #requestRendering()}
	 - Input events from the touch screen/mouse or keyboard
	 - A {@link Runnable} is posted to the rendering thread via {@link Application#postRunnable(Runnable)}
```

I think at least some `Input` related stuff uses `postRunnable()` internally. Wouldn't removing the `requestRendering()` from `postRunnable()` break the triggering on some Input events as well? 

If we go for option 2, IMO we have to check all internal uses of `postRunnable()`. Do we know why it was added in the first place?

**Comment by cypherdare** [comment]
You mean if we go for option 1, right?

Doing a where-used search in the library shows that it is used all over the place in the various backends, and usually in response to events where you would want to trigger a render when using non-continuous rendering.

That kind of makes me lean towards option 2 (and fixing the Lwjgl3 backend to behave correctly). Maybe I underestimated how often people would rely on this feature, since we've used it extensively in the backends.

If we went with option 1, we would need to carefully add manual calls to `requestRendering` almost everywhere libGDX calls `postRunnable`.

**Comment by obigu** [comment]
Yeah, I meant 1.

I think we need to better understand the use case for this to consider adding a new interface method. If I've understood correctly you need to free unused objects to return them to the pool, why can't you do that on the end of the current frame? Maybe we can better discuss it on Discord if you prefer.

**Comment by cypherdare** [comment]
I think I'll be on Discord later today. But this is long so I'll put it here.

I ran into the issue while trying to make an AutomaticReturnPool utility class. A class that lets you obtain temporary objects that are automatically returned to the pool after you're done with them (in between frames). More detail below.

As I see it, there are two different reasons to post a runnable. The first is if you're doing something on a non-GL thread and need to go back to it. 

The second is if you're wanting to "fire and forget" something that should be deferred until after what you're currently doing. It's always possible to manually perform this code, but it can be messy, and is not pretty to have utility classes that require you to remember to call some cleanup method in the right place.

To be fair, I searched libGDX, and there are zero examples of the second reason.

The AutomaticReturnPool concept could be implemented in libGDX directly (rather than a third party library) without using the `postRunnable` hook, but instead by calling its cleanup method in each backend's Graphics implementation.

----

About the AutomaticReturnPool: The intent of my tool is that you can get temporary vectors and color instances to use during calculations. I find it tedious and error-prone to manage reusable vectors and colors in every class that needs them. If you need multiple intermediate vectors in a big calculation, and you're using reusable instances, it's difficult to keep track of which is which. I was going to put this in my personal library or CoveTools library, but it might be a functionality that should be in libGDX itself. The Vector classes used to expose reusable temporary instances for calculations, but they were removed for being error prone. I think this is a better solution.

I have lots of places in my projects with calculations like this. Classes that perform calculations like this have several reusable vector instances that are used in the calculations.

```
tmpV.set(leftPoint).add(tmpV4.set(downUpVector).scl(SPAWN_INSET)); //first point of spawn polyline
tmpV3.set(topPoint).add(tmpV5.set(leftRightVector).scl(-SPAWN_INSET)); //third point of spawn polyline
tmpV2.set(intersection).add(tmpV4).add(tmpV5);//second point of spawn polyline
float angleBreakPoint = tmpV4.set(tmpV).sub(tmpV2).len();
float totalLength = angleBreakPoint + tmpV4.set(tmpV2).sub(tmpV3).len();
```

It can become less error-prone and not require any reusable member variables with this:
```
Vector3 firstPoint = Arp.temp(leftPoint).add(Arp.temp(downUpVector).scl(SPAWN_INSET));
Vector3 thirdPoint = Arp.temp(topPoint).add(Arp.temp(leftRightVector).scl(-SPAWN_INSET));
Vector3 secondPoint = Arp.temp(intersection).add(firstPoint).add(thirdPoint);
float angleBreakPoint = Arp.temp(firstPoint).sub(secondPoint).len();
float totalLength = angleBreakPoint + Arp.temp(secondPoint).sub(thirdPoint).len();
```
Or if the team is open to adding to the core classes:
```
Vector3 firstPoint = leftPoint.tempCopy().add(downUpVector.tempCopy().scl(SPAWN_INSET));
Vector3 thirdPoint = topPoint.tempCopy().add(leftRightVector.tempCopy().scl(-SPAWN_INSET));
Vector3 secondPoint = intersection.tempCopy().add(firstPoint).add(thirdPoint);
float angleBreakPoint = firstPoint.tempCopy().sub(secondPoint).len();
float totalLength = angleBreakPoint + secondPoint.tempCopy().sub(thirdPoint).len();
```

The utility would pass out objects from its internal pool, and use `postRunnable` to free the objects in between frames. The utility would be reusing the same runnable instance to avoid generating garbage.

**Comment by cypherdare** [comment]
After further discussion with Obigu, I agree this feature raises too many risks.
