### ISSUE TITLE
Asset Manager does not load Sounds in nested subdirectories from the assets folder.

### ISSUE THREAD

**Issue by shawkym** [libgdx/libgdx#6275]
#### Issue details
Problem loading sounds in nested paths using Assets Manager resulting in FileNotFoundException.

#### Reproduction steps/code

- Create a libgdx android project using the guide
- Create the following folder tree in assets folder
 assets/path1/path2/path3
- Place the sound file in the path3 directory 
- Load the sound file using Assets Manager

#### Version of LibGDX and/or relevant dependencies
1.9.11
1.9.13

#### Please select the affected platforms
- [X] Android

**Comment by MobiDevelop** [comment]
Does the same occur without using AssetManager (e.g.` Gdx.audio.newSound(Gdx.files.internal("path1/path2/path3/sound.ogg"))`)

**Comment by shawkym** [comment]
> Does the same occur without using AssetManager (e.g.` Gdx.audio.newSound(Gdx.files.internal("path1/path2/path3/sound.ogg"))`)

I'm sorry, the code base is huge, I cannot run this test. you can try this in your project maybe.

**Comment by Tom-Ski** [comment]
You can easily just put this code in a new launcher to test. You don't need to run within your codebase.

Please see https://github.com/libgdx/libgdx/wiki/Getting-Help, your report does not contain enough info for it to be suitable on the tracker. There are no logs, reproduction steps are not complete and you have already shot away someone that has asked you to test trivial code to diagnose you issue. 

Please feel free to reopen when the info as requested in the link and issue template have been fulfilled.

**Comment by obigu** [comment]
Just tested it and can't reproduce.
