### ISSUE TITLE
How to unlock 90/120 FPS on Android?

### ISSUE THREAD

**Issue by F0RIS** [libgdx/libgdx#6279]
The amount of phones that supports fps higher than 60 is more and more. 
Imho 120 FPS gaming on a phone looks amazing.
 
So how can I unlock high fps in my LibGDX android game? Haven't found that in docs
And when I launch my project it runs only at 60fps.

Does LibGDX support this at all? 
I use version 1.9.11 of the engine

#### Please select the affected platforms
- [x] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by obigu** [comment]
Are you reporting that you've tested running a project on an Android device that supports 120 fps and that the fps is limited to 60 fps when running on it?

**Comment by F0RIS** [comment]
@obigu yes

**Comment by obigu** [comment]
I'm not aware of any fps cap on Android, I think we need to make sure the limit is not coming from the device itself. What device are you using? How are you measuring fps? Have you confirmed other games running on that device run at 120Hz?

**Comment by MobiDevelop** [comment]
API 30 adds an API to set the desired frame rate on surfaces, not sure if that's what you're looking for?

https://developer.android.com/guide/topics/media/frame-rate

Exposing that in the api would require us to update the Android backend to compile against API 30 (#6273).

**Comment by F0RIS** [comment]
I already build my project with API 30, its a native android app that uses LibGdx as dependency, not a cross-platform project

I found these methods too but haven't tested them yet. Don't have persistent access to a phone with high refresh rate

**Comment by obigu** [comment]
I will close this as the reported issue happens on a non libGDX project and no tests with an empty libGDX project using the device with high refresh rate can be made.

**Comment by F0RIS** [comment]
I did some tests on other phones and my game was running 120fps successfully, also I got laptop with 240Hz screen and tested my game inside Blustack and got 240fps. So I can confirm that everyting is ok with high fps in LibGdx!
