### ISSUE TITLE
How to load assets dynamically

### ISSUE THREAD

**Issue by SAOMDVN** [libgdx/libgdx#6280]
#### Issue details
I have many assets with around hundred of folders, now I want to load them dynamically (ideally from user input with the help of JSNI, and security issues set aside), I want to be able to add more assets later without having to recompile or creating new assets.txt file.

#### Version of LibGDX and/or relevant dependencies
LibGDX 1.9.12
GWT 2.8.2

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [x] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by MrStahlfelge** [comment]
Please ask your questions on some of the support channels, for example the discord server.
