### ISSUE TITLE
Unexpected behaviour with InputProccesor's scrolled

### ISSUE THREAD

**Issue by SAOMDVN** [libgdx/libgdx#6281]
#### Issue details
The `amountY` value of `InputProcessor`'s `scrolled` produces an undesirable output, ranging from -4 to 2 when expected value is only -1 or 1. This behaviour happens when both scrolling in one direction and when scrolling in two direction. Happened on 1.9.11 too with `amount` value.

#### Reproduction steps/code
```
public class MyClass extends ApplicationAdapter implements InputProcessor {
    //...
    @Override
    public boolean scrolled(float amountX, float amountY) {
        System.out.println(amountY);
        return false;
    }
}
```
Values encountered are -4, -2, -1, 1, 2
#### Version of LibGDX and/or relevant dependencies
LibGDX 1.9.12

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [x] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by crykn** [comment]
Hey @SAOMDVN, I can't reproduce your issue. However, the fact that it happens on desktop and GWT as well as with 1.9.11 and 1.9.12 leads me to believe that this could be a hardware problem.

**Comment by SAOMDVN** [comment]
I've asked two friends to test it on GWT, one experienced this issue, the other did not. The scrolling behaviour in other aspects show no error (web surfing, Photoshop zooming). If my hardware is indeed the problem, how can I inspect it?

**Comment by MrStahlfelge** [comment]
Interesting here is what is the same with you and the friend experiencing the problem and the friend that does not. What browsers do you use, what input device?

**Comment by SAOMDVN** [comment]
Both 3 of us are using Chrome, about input device, are you asking for a specific model or just generic like a mouse/touchpad stuff? In my case I am using a mouse

**Comment by MrStahlfelge** [comment]
Is your testapplication live anywhere?

**Comment by SAOMDVN** [comment]
This problem only appears on some small number of machines so I guess the fault is of the machines, and I chose to settle with it. Close
