### ISSUE TITLE
(Box2D) Physics Filter Bug on > 1.9.10

### ISSUE THREAD

**Issue by TypeOverride** [libgdx/libgdx#6283]
#### Issue details
Something wrong on applied filters on physic objects.

#### Reproduction steps/code
Cant tell. Only updating an old project to a later version and saw that on creation of my objects sometimes the filters are not working or applied. So my bullets went through some of my enemies. I went back to 1.9.10 and everything fine. 
It will not be difficult to see what is different between 1.9.1 until 1.9.12. So something has to be changed on Box2D implementation or something.

#### Version of LibGDX and/or relevant dependencies
1.9.12

#### Stacktrace
no available

#### Please select the affected platforms
Only tested on Windows

**Comment by crykn** [comment]
Hey @TypeOverride, yes, this is a know issue with version 1.9.12, see [here](https://libgdx.com/news/2020/10/gdx_1_9_12#other-notable-changes). A [fix is being worked on](https://github.com/libgdx/libgdx/pull/6262) at the moment. For the time being, we advise people using Box2D Filters to stay on 1.9.11/1.9.10.
