### ISSUE TITLE
`IntMap.containsValue()` returns true for values that have been removed.

### ISSUE THREAD

**Issue by nickswebsite** [libgdx/libgdx#6285]
`IntMap.containsValue()` returns true for stale values. This creates problems with the Gwt backend on touch screens when trying to determine if a touch identifier has been seen before as it thinks that there are multiple touches on the screen. This causes the pinch handlers to be called rather than the pan handler.

#### Reproduction steps/code

* Add an item to an `IntMap<>`.
* Remove the item.
* Call `containsValue()` with the value.
* `containsValue()` returns true.

#### Version of LibGDX and/or relevant dependencies
_Please provide the version(s) affected._

1.9.12

#### Test Case
The following test fails:

```java
class IntMapTest {
    @Test
    void test_contains_value_returns_false_after_removal() {
        IntMap< Integer > map = new IntMap<>();
        Integer value = 123;
        map.put( 1, value );
        map.remove( 1 );

        assertFalse( map.containsValue( value, false ) );
    }
}
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [x] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by tommyettinger** [comment]
Looking into it; I think I saw a recent-ish change that seemed like a likely culprit, but it could be older. Also I'm guessing you just used Integer as the value type as an example placeholder type, but most cases mapping ints to ints would be better with an IntIntMap.

**Comment by nickswebsite** [comment]
Checking for a non-zero key didn't work for me when I tried it, though I tried something a little kludgy using `findKey()`. Setting the removed value to `null` worked so I didn't investigate the key check any further. It also allows GC to collect the object.

I used `Integer` because that is how the `IntMap<>` is used in `DefaultGwtInput` for keeping track of pointer identifiers.

Thanks for the quick fix!

**Comment by tommyettinger** [comment]
Indeed, DefaultGwtInput does use IntMap... it looks like it would be another PR to make it use IntIntMap, though I don't know if Integer and int are so significantly different for performance on GWT. Glad the fix works!

**Comment by nickswebsite** [comment]
I should probably note that it looks like this bug probably occurs in `IntIntMap`, `IntFloatMap`, `ObjectIntMap`, `ObjectLongMap`, and `ObjectFloatMap` as those don't null out the `valueTable[i]` in `remove()` either. I'm not familiar enough with the code base to know what other classes it might be applied to, or if there is any code generation going on.

**Comment by tommyettinger** [comment]
You can't null out an int, float, or long, @nickswebsite -- that's part of using primitive-backed collections, those types aren't references. The values there are assigned `0` before they have a key, and maybe this same bug with containValue() would affect searching for a 0 value; I can test.
