### ISSUE TITLE
DAE is the 3D standard 

### ISSUE THREAD

**Issue by Duna** [libgdx/libgdx#6287]
DAE is the 3D standard why do you use a custom standard G3DB?

Please get rid of G3DB, all devs are complaining about it.

DAE is the official Standard

**Comment by tommyettinger** [comment]
This is a joke, right? DAE files are way too big in terms of filesize and the XML spec as written is unparseable by conforming tools. The current official Khronos standard is GLTF, I suggest you look into it. Also, consider using punctuation.

**Comment by Duna** [comment]
Seriously? Why iOS are using them, doesn't ring the bell? Make a good
converter. G3db resulting from maya->fbx>fbx-convert>g3db is always
trashing in longed at runtime.

The blender 2.8 and 2.8 plugin import export lunges g3db is not working.

Why are making custom formats and do not keep up with the new software?

**Comment by Duna** [comment]
Seriously? Why iOS are using them, doesn't ring the bell? Make a good converter. G3db resulting from maya->fbx>fbx-convert>g3db is always trashing in longed at runtime.

The blender 2.8 and 2.8 plugin import export lunges g3db is not working.

Why are making custom formats and do not keep up with the new software?

**Comment by mgsx-dev** [comment]
Maybe GLTF format is what you looking for, it's both standard and modern. You can use this libgdx extension : https://github.com/mgsx-dev/gdx-gltf

**Comment by Duna** [comment]
https://www.donmccurdy.com/2017/06/27/exporting-gltf-2-0-from-maya-lt-2/ all converters are or in alpha/beta or experimental, so a big NO

**Comment by PokeMMO** [comment]
Feel free to create and contribute support for any format you wish to support.

**Comment by Duna** [comment]
It seems GLTF is much more convenient, but as a converter I tried to use Maya plugin, but is not working. Then I switched to https://modelconverter.com/convert.html and seems the textures are imported as well

**Comment by Duna** [comment]
Can you point me out the Discord channel in order to make some questions there related to dae conversions and load into libgdx at runtime.
It seems it still having issues:
`java.lang.NumberFormatException: For input string: "=��᾵�e?di<�'2���7?T��=��,���:?�v�>�A�?-?kB�Hj��Z�?���r�����G?SB@��E?ZEc����N�>�|c�(~��V�>�;�X��=?t$��Tö���L?�W?�����7���2?��)�"`

```
        ModelLoader loader = new ObjLoader();
        Model model = loader.loadModel(Gdx.files.internal("character.glb"));

[Here](https://drive.google.com/drive/folders/1E26i-sFTIHHggwPa8fzp2huXKa7cjRk6?usp=sharing) it is the DAE and the converted one GLB used
```

**Comment by yuripourre** [comment]
@Duna you are trying to load glb using the .obj loaders, I suggest you to search on Google or ask on discord how to do it properly.

If you are having trouble with dae, you can try to use blender to convert from .dae to .gltf and use https://github.com/mgsx-dev/gdx-gltf

**Comment by SimonIT** [comment]
https://libgdx.com/community/ for Discord
