### ISSUE TITLE
cant run multiple libgdx instances intelji idea

### ISSUE THREAD

**Issue by lastpeony** [libgdx/libgdx#6292]
run in parallel option does not work. only one libgdx can run at the same time.after 1st one others just hold and they dont launch. other apps run fine only libgdx has this problem. desktop

tested with 2019 intelji 2.4 and 2020 intelji community editions.

**Comment by Tom-Ski** [comment]
Don't have an issue with this. Perhaps provide minimal example and fill out the template appropriately.
