### ISSUE TITLE
When .AAB support

### ISSUE THREAD

**Issue by Duna** [libgdx/libgdx#6293]
It seems APK files may be rejected from the store. When do we have support for a full gradle project?
"You can't roll out this release because it doesn't allow any existing users to upgrade to the newly added APKs." - uploading Play Store new version of the app

Blocked on old APK format

**Comment by SimonIT** [comment]
Why do you think that app bundles aren't supported? I use them for more than a year with libGDX successfully

**Comment by Duna** [comment]
It could be supported but in the bundle will be included all platforms .so files, even if not needed

**Comment by SimonIT** [comment]
If you look at https://developer.android.com/guide/app-bundle#aab_format an aab has to contain all natives. Google Play generates the apks for the different architectures so every native code must be included inside the aab file.
How do you know that the natives aren't stripped? https://developer.android.com/studio/build/shrink-code#strip-native-libraries says that they get stripped by default

**Comment by Duna** [comment]
Yes this Play Store does with apps, but what about libgdx apps? Check the
size of the app at install time. Check the number of methods after R8

**Comment by SimonIT** [comment]
> Yes this Play Store does with apps, but what about libgdx apps?

Every app store has to split the aab into individual apks because you can't install aab's on android

Can you provide some numbers to proof that it doesn't strip them?

**Comment by Duna** [comment]
R8

**Comment by obigu** [comment]
Please see https://github.com/libgdx/libgdx/wiki/Getting-Help, your issue is not suitable for this tracker. It lacks reproduction steps or an example to show the problem and you have failed to provide a reasonable answer when somebody has tried to assist you. 

Please feel free to reopen with an issue with the template properly filled and all the requested information provided.

**Comment by Duna** [comment]
I'll come back with the metrics

**Comment by demoth** [comment]
Hello! Sorry for bumping the old thread but this is the most relevant I could find..
I'm having an issue with this `.aab` (assets cannot be located) format despite the fact that same app runs quite good (on many devices) via `.apk` format. I need some help specifically with `.aab` and libgdx
