### ISSUE TITLE
InputListener corrupt input from QR scanner

### ISSUE THREAD

**Issue by doit-ceo** [libgdx/libgdx#6295]
#### Issue details
We are trying to use QR code scanner, we found that LibGDX change the input text ! (1D scanner works fine)
#### Reproduction steps/code
Generate any simple JSON qr code ({data:100}), reading this from QR scanner will be " [data;100] "

Also note scanner works normal in all apps 

Any workaround to get the raw input data ?

#### Version of LibGDX and/or relevant dependencies
1.9.8
#### Stacktrace
```java
	stage.addCaptureListener(new InputListener() {
		@Override
		public boolean keyTyped(InputEvent event, char character) {
			//Data here is WRONG from QR scanner
			return super.keyTyped(event, character);
		}
	});
```

#### Please select the affected platforms
- [x] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Darkyenus** [comment]
libGDX uses [character data as reported by the system](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/DefaultAndroidInput.java#L577). With so little information and without the QR scanner hardware/software at hand, it is hard to say what is the problem.

I'd suggest you to put a breakpoint on the linked code and check up the call stack, whether there is something weird going on there. If you don't find anything, you will probably have to implement a custom vanilla android Activity which works (as you say that all other apps work correctly) and continue from there.

**Comment by MrStahlfelge** [comment]
Closed, not enough info and no reaction
