### ISSUE TITLE
Confirmation dialog before closing window

### ISSUE THREAD

**Issue by danielbe1** [libgdx/libgdx#6297]
I am currently using the lwjgl3 backend, and I was wondering if it is possible to intercept and disalbe closing the window (when pressing the X on the right corner in windows for example), and instead show a confirmation dialog and only then close the application.

**Comment by crykn** [comment]
Hey @danielbe1, take a look at `Lwjgl3WindowListener#closeRequested()`. A corresponding listener can be set via `Lwjgl3ApplicationConfiguration#setWindowListener(Lwjgl3WindowListener )`.
