### ISSUE TITLE
[Request] Compatibility with Compose

### ISSUE THREAD

**Issue by pakoito** [libgdx/libgdx#6302]
Opening this ticket just to track progress! I'd like to use Compose for my GUI in [Desktop](https://www.jetbrains.com/lp/compose/) and [Mobile](https://developer.android.com/jetpack/compose), and I was hoping it could be laid out on top of a libgdx surface.

**Comment by MrStahlfelge** [comment]
libgdx is open source, as is compose, so just do it. I would suggest you to create it as 3rd party extension lib because this is beyond the scope of this framework and out of the wanted scope for the typical games.
