### ISSUE TITLE
3D Particle Effects Documentation Updates

### ISSUE THREAD

**Issue by winrid** [libgdx/libgdx#6310]
#### Issue details
I was reading the documentation here: https://github.com/libgdx/libgdx/wiki/3D-Particle-Effects

And it mentions a "tank demo" later in the page, which doesn't seem to be there. Are we missing a link?

Also, the "full usage example" at the bottom points to a broken link.

**Comment by crykn** [comment]
See [here](https://github.com/libgdx/libgdx/issues/6237). Seems like I missed one sentence mentioning the demo.

**Comment by winrid** [comment]
@crykn Okay, I updated the page to still be useful and less confusing.
