### ISSUE TITLE
Hiero tool generates glyphs of wrong size

### ISSUE THREAD

**Issue by PauliusLiekis** [libgdx/libgdx#6314]
#### Issue details

Generating Bitmap fonts for Inter font results in glyphs of the wrong size.

The font:
[Inter Bold.ttf.zip](https://github.com/libgdx/libgdx/files/5701383/Inter.Bold.ttf.zip)

This is the size of glyphs of Arial at size 32:
![Arial](https://user-images.githubusercontent.com/6169962/102326533-30681c00-3f8d-11eb-962f-8d18612778d6.png)

This is the size of glyphs of Inter at size 32 - it's clearly too big:
![Inter](https://user-images.githubusercontent.com/6169962/102326546-33fba300-3f8d-11eb-9715-05d697266f61.png)

#### Reproduction steps/code
* Open Hiero tool
* Load Inter font
* Set rendering to Java and add Color rendering in the Effects

#### Version of LibGDX and/or relevant dependencies
The latest version of Hiero tool from here: https://github.com/libgdx/libgdx/wiki/Hiero

#### Please select the affected platforms
- Windows
- MacOS

**Comment by tommyettinger** [comment]
Uh... no? I just tried Arial and Inter in Hiero (with an outline, as you appear to have added as well) and got a much smaller difference in size.

Inter:
![Inter](https://user-images.githubusercontent.com/160684/102605375-0a03c700-40da-11eb-8d5e-fb8e4ef015b4.png)

Arial:

![Arial](https://user-images.githubusercontent.com/160684/102605377-0a9c5d80-40da-11eb-8165-76169a806183.png)

The outlines are pretty ugly where I tried them, but they look fine in yours. Double-check the size field in Hiero, I guess. Inter seems to have a visible glyph where it shouldn't, which shows as the horizontal bars in the glyph cache, and that messes up other fonts rendered in Hiero afterwards by putting that glyph in their caches too.

**Comment by PauliusLiekis** [comment]
Thanks for checking it out.

I tried it again - the same result. I tried the nightly build - same.

Turns out I needed to update my Java version. The update also suggested to remove old versions, which I did, so maybe that fixed it. So it exports it correctly now.

I'll update Java on all of my machines now :D
