### ISSUE TITLE
Screen quarter size on iOS

### ISSUE THREAD

**Issue by WillCalderwood** [libgdx/libgdx#6315]
Please ensure you have given all the following requested information in your report.

#### Issue details
The screen when running the iOS version is a quarter of the size it should be when first starting the app

#### Reproduction steps/code
I first noticed this in my app and tried to reproduce in a newly created app with success. This can be reproduced easily using the libGDX setup app. Just create a new project and launch in iOS. The problem occurs in both the simulator and on the device.
Change the line that draws the logo to 
`batch.draw(img, 0, 0, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());`
The logo will only fill half the screen. If you draw the logo with double dimentions then it's clipped to the bottom left quarter.

![image](https://user-images.githubusercontent.com/6973062/102411480-e5c8bd00-3fe9-11eb-9ca2-876ba6bc6736.png)

#### Version of LibGDX and/or relevant dependencies
1.9.13-SNAPSHOT and 1.9.12

#### Please select the affected platforms
- [ ] Android
- [x] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by crykn** [comment]
Hey @WillCalderwood, that is expected behaviour. The methods you should be using in this case are `Gdx.graphics.getBackBufferWidth()` & `getBackBufferHeight()`. Alternatively, use a viewport. Specifically for iOS, this was changed in 1.9.12, see the corresponding [changelog](https://libgdx.com/news/2020/10/gdx_1_9_12#breaking-changes).

**Comment by WillCalderwood** [comment]
@crykn  Thanks. I thought I must be missing something obvious but a quick Google didn't reveal anything. I'll look at updating the new project template to use a viewport so it behaves the same on both Android & iOS.
