### ISSUE TITLE
Hiero tool is flashing

### ISSUE THREAD

**Issue by PauliusLiekis** [libgdx/libgdx#6318]
#### Issue details

The panel where the rendered font is supposed to be displayed is blinking, the font is not rendered. See the video (with reproduction steps):

https://user-images.githubusercontent.com/6169962/102610980-cc815700-4136-11eb-89be-480d457bb8e2.mov

Although if I save the font it is exported correctly - it's just the preview that is not working (and causing seizures :))

#### Reproduction steps/code

* Open Hiero tool
* Pick Java Rendering
* Select "Glyph cache"
* Switch back to "Sample text"
* Select again "Glyph cache"

Blinking usually starts after these steps. And even if blinking doesn't start the preview on the rendered font is just black then.

It's happening on the latest stable and nightly builds of Hiero font tool.

#### Please select the affected platforms
OSX only. It works fine on Windows.

**Comment by erdinc09** [comment]
Assuming MacOS Big Sur, this is known bug.
#6247

**Comment by crykn** [comment]
Thanks for the detailed bug report! @erdinc09 is right. This is a known bug with macOS and LwjglAwtCanvas (which the tools are using). If you have to use Hiero on macOS, try the mentioned PR. It should be fully functional and there are only some minor (technical) things keeping it from being merged.
