### ISSUE TITLE
[Feature Request] Allow setting the properties on AnimatedTiledMapTile

### ISSUE THREAD

**Issue by bryanbrunt** [libgdx/libgdx#6324]
AnimatedTiledMapTile has a private member of properties.

private MapProperties properties;

Those properties are gettable, but not settable. Why?

Without settable properties on a tile, to set properties for a tile, I'll need to create to copy the gdx implementation of tile map, or create my own associated data layer for each tile.

Is it possible for libgdx to make this change in a future version?

**Comment by MobiDevelop** [comment]
You can set values on the returned MapProperties object.

**Comment by MobiDevelop** [comment]
Will assume that the ability to get the MapProperties and put values into it is sufficient for your needs. If this is not the case we can discuss, but I can't imagine why it wouldn't be.
