### ISSUE TITLE
Problem with the calculation of the internal offset in SpriteCache#draw(cacheID, offset, length)

### ISSUE THREAD

**Issue by pcfreak9000** [libgdx/libgdx#6334]
``draw(int cacheID, int offset, int length)`` in the SpriteCache ([Here](https://github.com/libgdx/libgdx/blob/793372025c94abfa6b4fa28a6b8543ff54033ead/gdx/src/com/badlogic/gdx/graphics/g2d/SpriteCache.java#L912)) seems to be broken. More precisely, the calculation of the internal offset. 
#### Issue details
Using that method to draw a cache which is not the first one, e.g. ``draw(2, 0, imagecount)`` where imagecount is a manual count of how many images i added earlier, nothing is shown, but i would expect the same result as when calling ``draw(2)`` which is working correctly. Also, if ``cacheID`` is zero (meaning the internal cache offset is also zero), the method works as expected, further pointing to an issue with the offset.

Looking into the SpriteCache, i found the line ``int offset = cache.offset / (verticesPerImage * VERTEX_SIZE) * 6;`` in ``draw(int cacheID)`` and  the line ``offset = offset * 6 + cache.offset;`` in ``draw(int cacheID, int offset, int length)``. In the first one (which is the one correctly working), there is a division by some factor which i didn't find in the second method, so i suppose there's the problem.

#### Reproduction steps/code
```java
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application;
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.Pixmap;
import com.badlogic.gdx.graphics.Pixmap.Format;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.SpriteCache;

public class DesktopLauncher {
    public static void main(String[] arg) {
        Lwjgl3ApplicationConfiguration config = new Lwjgl3ApplicationConfiguration();
        config.useOpenGL3(true, 3, 3);
        config.setTitle("Problem");
        config.enableGLDebugOutput(true, System.out);
        new Lwjgl3Application(new ReproduceBug(), config);
    }
    
    private static class ReproduceBug extends ApplicationAdapter {
        
        private SpriteCache cache;
        private Texture texture;
        
        private static final int MAX_COUNT = 30;
        
        @Override
        public void create() {
            this.cache = new SpriteCache(1000, false);
            Pixmap p = new Pixmap(100, 100, Format.RGB888);
            p.setColor(1, 1, 1, 1);
            p.fill();
            p.setColor(Color.CORAL);
            p.fillCircle(50, 50, 50);
            this.texture = new Texture(p);
            p.dispose();
        }
        
        @Override
        public void render() {
            Gdx.gl.glClearColor(1, 0, 0, 1);
            Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
            cache.clear();
            for (int i = 0; i < 5; i++) {
                cache.beginCache();
                for (int j = 0; j < MAX_COUNT; j++) {
                    cache.add(texture, i * 40, j * 10);
                }
                int id = cache.endCache();
                cache.begin();
                //***** Problem here: 
                cache.draw(id, 0, MAX_COUNT); //<- does only work for the first cache (offset and the internal cache.offset are both zero then)
                //cache.draw(id); //<- Works as expected
                //*****
                cache.end();
            }
        }
        
        @Override
        public void dispose() {
            this.cache.dispose();
            this.texture.dispose();
        }
        
    }
}
```

#### Version of LibGDX and/or relevant dependencies
LibGDX 1.9.12

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] MacOS

But I suppose the bug is independent of platform.

**Comment by NathanSweet** [comment]
Thanks for the nice repro code!
