### ISSUE TITLE
StringBuilder#hashCode will produce different hash codes depending on the internal 'chars' size

### ISSUE THREAD

**Issue by lucas-kakele** [libgdx/libgdx#6339]
#### Issue details
I was trying to use `StringBuilder` as keys of an `ObjectMap` and I found out that `StringBuilder#hashCode` will produce different hash codes depending on the internal `chars` size, since it is using `Arrays.hashCode(size)`. This will cause undefined behavior on the map and I'm not sure if this is intended.

#### Reproduction steps/code
```java
StringBuilder a = new StringBuilder();
a.append("test");
StringBuilder b = new StringBuilder(a);
System.out.println(a.hashCode() + " " + b.hashCode());
```

#### Version of LibGDX and/or relevant dependencies
1.9.12

#### Please select the affected platforms
- [X] Android
- [ ] iOS -> not sure
- [ ] HTML/GWT -> not sure
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by lucas-kakele** [comment]
Note: I replaced the `Arrays.hashCode` call with the following method, adapted from that code, so it would hash only the actual string chars:

```java
private int hashCodeChars() {
  int result = 1;
  for (int index = 0; index < length; ++index) {
    result = 31 * result + chars[index];
  }
  return result;
}
```

And it is working now.

**Comment by NathanSweet** [comment]
Yikes, good find!

**Comment by lucas-kakele** [comment]
Thanks Nathan!
