### ISSUE TITLE
Ellipse contains method is incorrect

### ISSUE THREAD

**Issue by cfogrady** [libgdx/libgdx#6344]
#### Issue details
Ellipse contains method is incorrect.

I was attempting to use the Ellipse to check for mouse clicks on Elliptical buttons and realized the contains method is incorrect.
```
x = x - this.x;
y = y - this.y;

return (x * x) / (width * 0.5f * width * 0.5f) + (y * y) / (height * 0.5f * height * 0.5f) <= 1.0f;
```
I believe the issue is that the x and y of the ellipse are the bottom left coordinate you would get if you drew a rectangle exactly encompassing the ellipse when the formula here is for an x and y at the center of the ellipse 

#### Reproduction steps/code
```
Ellipse ellipse = new Ellipse(0, 0, 50, 50);
Assert.assertFalse(ellipse.contains(0, 0)); // Should not be within the ellipse, but the formula currently marks it as such.
Assert.assertTrue(ellipse.contains(25, 25)); // Should be contained as this is the center of the ellipse, but the formula currently marks it as outside.
```

#### Version of LibGDX and/or relevant dependencies
ALL (according to git)
But I'm currently using 1.9.11

#### Stacktrace
N/A

#### Please select the affected platforms
- [x ] Android
- [ x] iOS
- [ x] HTML/GWT
- [ x] Windows
- [ x] Linux
- [ x] MacOS

**Comment by cfogrady** [comment]
FYI Doing the following override fixes the issue for me:
```
public class FixedEllipse extends Ellipse {
	@Override
	public boolean contains(float x, float y) {
		float halfWidth = this.width*.5f;
		float halfHeight = this.height*.5f;
		x = x - (this.x + halfWidth);
		y = y - (this.y + halfHeight);
		return (x * x) / (halfWidth * halfWidth) + (y * y) / (halfHeight * halfHeight) <= 1.0f;
	}
}
```
This code essentially tests relative to the center of the ellipse instead of relative to the bottom left. Should be simple enough for anybody with the repo already cloned to do a copy past job for a PR.

**Comment by yuripourre** [comment]
@cfogrady 
Do you mind open a PR with your solution?

I am really looking forward to have better math algorithms in libGDX.

**Comment by cfogrady** [comment]
If cloning down the repo, and PR submission doesn't have too much red tape, happy to submit one in the next couple of days as time allows.

**Comment by MobiDevelop** [comment]
It's entirely possible there are inconsistencies. The class in the math package states it is based on the Circle class, and the implementation jives with the (x,y) being the center based on how it handles construction with or setting to a Circle as well as with contains implementation. I agree it should be better documented.

The drawing method in ShapeRenderer has little to do with the Ellipse class (it doesn't even take an Ellipse). Should they be consistent? Maybe, it might be hard to change that now.

**Comment by obigu** [comment]
Looks like Implementation is correct, the issue can be closed. If you believe documentation can be improved, please feel free to open a PR.
