### ISSUE TITLE
Touch event pointer numbering on GWT

### ISSUE THREAD

**Issue by quicksilver89** [libgdx/libgdx#6352]
#### Issue details
When touchdown is called it does not always use the lowest pointer number available.
This is an issue because GestureDetector ignores all pointer numbers above 1.

#### Reproduction steps/code
* The supplied [PointerNumberTest.txt](https://github.com/libgdx/libgdx/files/5778607/PointerNumberTest.txt) class can be used to test. Create a new project with it as the ApplicationListener.
* Create a new html build and open the app in the web browser on a multi touch capable device (phone).
* Tap the device with 2 fingers, it will display touchdowns and touchups for pointers 0 & 1 (as it should).
* Again, tap the device with 2 fingers, it now displays touchdowns and touchups for pointers 0 & 2. This is a problem for the Gesture detector as it will not detect this as a pinch or zoom event.
* If we repeat this two finger tap, we will see it consistently alternate between pointers 0 & 1 and 0 & 2.

Additional Notes:
* This was tested on a Samsung Galaxy S4 using Firefox.
* I also tested it very briefly on another person's 2 year old iphone (sorry I don't have any more details about that environment) and the pointer values were even stranger, it seemingly used random values getting up into the teens and there were even negative pointer values coming through.
* When two finger tapping and pointer 0 & 2 are used, Gdx.input.isTouched(1) returns false on touchdown of pointer 2.
* If we add in more fingers at once and go back to two fingers, the number of the second finger can be anywhere between 1 (inclusive) and the max number of fingers touched with at any point (inclusive). Example: touch with 5 fingers at once, subsequent 2 finger taps alternate between 0 & 4 and 0 & 5.

I wrote a quick workaround which can be used by changing the InputMultiplexer constructor call to the included InputPointerNormalizer.
It maps all touchdowns to the lowest unused pointer value and maintains that mapping for drags and until touchup is called for that pointer.
This seems to work well and fix my problems so that pinch to zoom is always working, but I do not know how robust it is and if there are corner cases I did not think of.

#### Version of LibGDX and/or relevant dependencies
1.9.11

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [X] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by MrStahlfelge** [comment]
This reads as if the mapping for 1 is not removed from the touchmap, therefore `getAvailablePointer` not returning 1 any more. 
It should get removed when the touchup happens, and it is reported as you state.

Maybe you can check with debug output what happens exactly here. Check every access of touchMap in 'DefaultGwtInput` class.

**Comment by MrStahlfelge** [comment]
Tested on a Windows multitouch device with Chrome and Firefox. Everything working as expected.

**Comment by MrStahlfelge** [comment]
No further reaction
