### ISSUE TITLE
3D particles do not work on Mac OS Catalina 10.15.7

### ISSUE THREAD

**Issue by fgermane** [libgdx/libgdx#6354]
#### Issue details
Hi, the 3D Particle Editor does work on Mac OS 10.15.7. The viewport is black.

#### Reproduction steps/code
Download the editor from: https://libgdx.badlogicgames.com/nightlies/runnables/runnable-3D-particles.jar
Launch Java command: java -jar runnable-3D-particles.jar

#### Version of LibGDX and/or relevant dependencies
gdxVersion = '1.9.10'

#### Stacktrace
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/Users/fredericgermane/Dev/libgdx/particles/runnable-3D-particles.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS

**Comment by fgermane** [comment]
May the PR 6247 solve the bug?

**Comment by crykn** [comment]
Hi @fgermane, yes, this is a known bug on macOS and #6247 is intended to fix that. If you need to use the particle editor on macOS, then try [cloning](https://libgdx.com/dev/from_source/) the PR and building the editor locally.

**Comment by fgermane** [comment]
Ok Thank you very much @crykn :-)
