### ISSUE TITLE
SVG

### ISSUE THREAD

**Issue by karelantonio** [libgdx/libgdx#6362]
Hola pudieran agregar soporte para SVG para crear imágenes escalables y con una mejor calidad al ser pintadas. Saludos de @karelantonio

**Comment by yuripourre** [comment]
@karelantonio Hola, no tengo ni idea del estado de la biblioteca. ¿lo has probado?

https://github.com/Longri/libgdx-svg

**Comment by karelantonio** [comment]
Que biblioteca?

**Comment by karelantonio** [comment]
No la he probado ya la voy a probar

**Comment by MrStahlfelge** [comment]
The linked repo is the best one I found, too. SVG support is at the moment beyond libGDX abilities, so check it out.
