### ISSUE TITLE
Auto-Center on window resize shall be selectable (need to disable it)

### ISSUE THREAD

**Issue by Grisgram** [libgdx/libgdx#6364]
in 1.9.12 a feature was introduced, that a window gets automatically centered on screen when the size is changed programmatically.

please make this selectable with a boolean parameter (true as default) whether the window shall be centered.
In case, I work with an undecorated window in windowed mode (launcher/setup utility) and want to implement resizing "by hand" this creates awful flickering effects upon resize.

could be done with a new signature:
Gdx.graphics.setWindowedMode(size.x, size.y); // centers as default
Gdx.graphics.setWindowedMode(size.x, size.y, false); // no centering, please

The reason for this issue:
i have a borderless (undecorated) window where i have my sizing grip in the bottom right and i want to resize in code based on drag
but it keeps centering the window creating awful flickering effects
i am working on my launcher app currently - shall look like battle net or epic launcher

**Comment by crykn** [comment]
To give some context: This functionality was introduced in https://github.com/libgdx/libgdx/pull/6178.

A workaround is manually calling the GLFW methods:
```java
Lwjgl3Window window = ((Lwjgl3Graphics) Gdx.graphics).getWindow()
GLFW.glfwSetWindowMonitor(window.getWindowHandle(), 0, window.getPositionX(),  window.getPositionY(), width, height, refreshRate);
```

I'm not really sure whether it makes sense to introduce a toggle for this behaviour (and make Lwjgl3Graphics/Lwjgl3ApplicationConfiguration  even more complicated), since this seems to be such a narrow use case (a borderless window, which simulates the 'drag on an edge to resize' behaviour).

**Comment by MrStahlfelge** [comment]
I also think if someone is implementing such a special behaviour, he is better of calling Lwjgl3 methods himself or overriding the setWindowedMode method/adding an own one to the platform implementation.

**Comment by Grisgram** [comment]
It's ok for me. Thanks to @crykn I have a way how it works now.
I just thought this change might result in unexpected behavior as it is very unusual that things center themselves without any options.
But if you think, it's the way to go, it's ok and you can close this
