### ISSUE TITLE
HttpResponseListener.handleHttpResponse is called if no internet connection on gwt

### ISSUE THREAD

**Issue by anbu93** [libgdx/libgdx#6372]
#### Issue details
If client no internet connection, method `Gdx.net.sendHttpRequest(request, listener)` not call failed or cancelled. Exception not thrown.
Only for GWT. On desktop and android failed method called.

#### Reproduction steps/code
Send request multiple time (every 5 sec).
Turn off internet, responce listener not called failed or cancelled. Exception print in console.

#### Version of LibGDX and/or relevant dependencies
1.9.10

#### Stacktrace
```java
net::ERR_INTERNET_DISCONNECTED
```
of infinity time with timeout.

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [x] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by tommyettinger** [comment]
I'm not sure I understand. What do you mean by `of infinity time with timeout` ? If you give an infinite amount of time to attempt to make a connection, I think it will attempt to connect until the internet is enabled again, and it can make the request. The console here is the JavaScript console in the browser, right? That would explain why it doesn't give a typical Java stacktrace. I know @MrStahlfelge is great with GWT, but I don't know how much networking he does with GWT. I think someone will be able to answer if you can wait.

**Comment by MrStahlfelge** [comment]
I do HTTP requests, but they work for me. I just tested with `HttpRequestExample` (a hidden test), and indeed failed/cancelled is not called, but handleHttpResponse with status code 0 and I handle that in my game as a fail.

I didn't debug if we could handle this better (`GwtNet` uses code provided by GWT which looked sophisticated), but I doubt the browser will report detailed errors to the request callback.

**Comment by anbu93** [comment]
> I do HTTP requests, but they work for me. I just tested with `HttpRequestExample` (a hidden test), and indeed failed/cancelled is not called, but `handleHttpResponse` is called with status code 0 and I handle that in my game as a fail.
> 
> I didn't debug if we could handle this better (`GwtNet` uses code provided by GWT which looked sophisticated), but I doubt the browser will report detailed errors to the request callback. So if there is no error/exception to handle, one could argue if `failed` should be called

Do you think this is normal behavior? Maybe then it is worth adding at least a warning to the java-doc in HttpResponceListener?
Or add specific status code in HttpStatus? But https://tools.ietf.org/html/rfc2616#page-39 not say anything about 0 status.

**Comment by MrStahlfelge** [comment]
It says nothing about 0 because 0 does not exist, so if you get a return of 0 it is an error.
Did you check if you get this callback?

**Comment by anbu93** [comment]
> It says nothing about 0 because 0 does not exist, so if you get a return of 0 it is an error.
> Did you check if you get this callback?

Yes, if not internet connection i have success response with code 0

**Comment by MrStahlfelge** [comment]
Okay, so you can check for that for your game. 

I'll look into the backend if it makes sense to call `failed` instead in the future.

**Comment by MrStahlfelge** [comment]
According to the [GWT documentation](http://www.gwtproject.org/javadoc/latest/com/google/gwt/http/client/Response.html), `onResponseReceived` may get called for failed requests with status code 0:

> public abstract int getStatusCode()
> 
> Returns the HTTP status code that is part of this response.
> 
> The value will be 0 if the request failed (e.g. network error, or the server disallowed the request) or has been aborted (this will generally be the case when leaving the page).

We could handle this and call failed() from here with an own exception:

https://github.com/libgdx/libgdx/blob/bc314368a18e0c916437f3dd7b4172714e6abf8b/backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/GwtNet.java#L163

It would be "more correct", but a behaviour change. I am not familiar if other platforms might not call handleHttpResponse with status code 0 though - @MobiDevelop @Tom-Ski what's your opinion on this?

**Comment by MobiDevelop** [comment]
It's very odd behavior for GWT to call onResponseReceived when no response was, in fact, received. I wouldn't think that other platforms treat this scenario the same way as they'd likely hit an IOException and call `failed`.
