### ISSUE TITLE
Box2d - Fixture has wrong filter data after being created from pool

### ISSUE THREAD

**Issue by astetyn** [libgdx/libgdx#6374]
Fixture has wrong filter category and mask when created from FixtureDef. This happens always when there is available fixture (with the different filter data) in the pool.

```
// assuming you have already created and destroyed a Fixture with filter.category = 1 (so it is available in the fixture pool)

FixtureDef def = new FixtureDef();

def.filter.categoryBits = 2;
def.shape = someRandomShape;
Fixture f = body.createFixture(def);

System.out.println(def.filter.categoryBits+" "+f.getFilterData().categoryBits);

// expected output: 2 2
// real output: 2 1
```

(body is a random Body object)

I know this can be easily fixed with setting filter data after the fixture creation, but this is a bug and should be fixed.

libGDX version: `1.9.12`
box2D verson: `com.badlogicgames.gdx:gdx-box2d:1.9.12`

- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [ ] MacOS

**Comment by crykn** [comment]
This is a [known issue](https://libgdx.com/news/2020/10/gdx_1_9_12#other-notable-changes) with gdx 1.9.12. Please update to 1.9.13.

**Comment by obigu** [comment]
Even better, please also try 1.9.14-SNAPSHOT that has the following final fix applied https://github.com/libgdx/libgdx/pull/6262.

**Comment by astetyn** [comment]
Great! Thanks and sorry for taking your time, I read 1.9.13 changelog but did not notice this change.
