### ISSUE TITLE
Android openURI(...) not working on Android 11

### ISSUE THREAD

**Issue by noblemaster** [libgdx/libgdx#6377]
#### Issue details
Android's [openURI](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidNet.java#L73) is not working on Android 11 anymore. Calling `openURI(...)` does nothing. There is no error thrown. 

#### Version of LibGDX and/or relevant dependencies
Latest stable release 1.9.13. The Android project has to be set to Android 11 (30).

#### Suggestion for Code Fix
A quick test showed the following code works. The live wallpaper flag needs to be set. Also, does this really need to run via UI thread as in libGDX's example? 
```java
try {
   // open with the correct activity if any 
   startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse(url)));
   return true;
}
catch (Exception e) {
   // ... log error...
   return false;
}
```

#### Please select the affected platforms
- [x ] Android 11
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by MrStahlfelge** [comment]
Just tested on an R emulator, it still works for me. The only difference in your code and the backend code I spotted is the check if there is a handler for the URI.

You mention something about live wallpapers, how does that relate to opening an URI?

**Comment by noblemaster** [comment]
I updated the comment. I believe this happens only if the libGDX project is set to Android 11 (30). I didn't have the problem before but changing to SDK 30 makes the problem occur. Unless there is something else bad happening in my project.

**Comment by MrStahlfelge** [comment]
Checked it, it is working for me with targetSdk 30

**Comment by MobiDevelop** [comment]
What type of uri is it? Just a normal web url?

**Comment by noblemaster** [comment]
Yes, it's normal `http://...` URL. It was working fine before with targetSdk 29. One of the players reported it on Android 11 (30) after I used targetSdk 30 for the build. The URLs still open on my Android 9 with targetSdk 30. 

Maybe the `PackageManager.MATCH_DEFAULT_ONLY` could cause problems if there is no default browser set? Maybe there is something else I did that makes `openURL` not work anymore?

I was able to reproduce it on a fresh emulator for Nexus 6P and SDK 30. 

![image](https://user-images.githubusercontent.com/2363626/106372297-abf12180-63b1-11eb-9ee0-e084ac91a4ff.png)

**Comment by MrStahlfelge** [comment]
Can you check by stepping through it with the debugger? You should be able to see if the command is not executed or if it fails.

**Comment by MobiDevelop** [comment]
With a Pixel emulator on Android 11, with the Android tests set to target API 30, this is reproducible via NetAPITest.

Android 11 added some 'privacy' around [package visibility](https://developer.android.com/about/versions/11/privacy/package-visibility), which requires specifying in the AndroidManifest.xml the type of intent queries you will perform - the backend code performs a query to see if any activity can resolve. Adding this to the AndroidManifest.xml makes openURI work:

```
	<queries>
		<intent>
			<data android:scheme="http" />
		</intent>
	</queries>
```

The reason it works with the proposed solution is that you are not querying for installed packages and the system makes an exception in the case where you just fire off a startActivity call - this is not without some trouble though as there is some very strange behavior that comes along with this for some types of URIs.

**Comment by noblemaster** [comment]
@MobiDevelop Thanks, I wasn't aware of that! I guess this works. Also, I am using `mailto` for email which I probably would have to add as well.  What side effects of directly calling `startActivity` are you referring to? 

@MrStahlfelge Good point, I should have debugged that further myself.

Adding `<queries>` to the AndroidManifiest.xml is doable. But what about other libGDX users that forget to do that? Are there other URIs besides `http` and `mailto` that might be needed? I think the simple solution is to simply call `startActivity` directly and return the results depending if we get an exception or not.

**Comment by MobiDevelop** [comment]
The system behaves oddly, at least it did for me with a `geo` uri in the app I work on at my day job - it never offered the chooser despite multiple apps being installed until I added the queries element. Whichever the last app was that could handle that uri was chosen (in our case, it was Uber) automatically. Not sure if other types of uris behave the same way.

**Comment by MrStahlfelge** [comment]
I was able to reproduce this with a fresh emulator, too. The code @noblemaster gave in the OP works for me, too, or a slightly different variant:

```
	public boolean openURI (String URI) {
		final Uri uri = Uri.parse(URI);
		try {
			Intent intent = new Intent(Intent.ACTION_VIEW, uri);
			// LiveWallpaper and Daydream applications need this flag
			if (!(app.getContext() instanceof Activity)) {
				intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
			}
			app.startActivity(intent);
			return true;
		} catch (ActivityNotFoundException e) {
			return false;
		}
	}
```

According to stackoverflow, using the `queries` is needed when you need to know if there are applications, but not start them. We don't have the situation here, and I am sure runOnUiThread is not needed.

**Comment by MrStahlfelge** [comment]
Ah found it, it is not precaution but to make openUri threadsafe: https://github.com/libgdx/libgdx/pull/59#issuecomment-9296572
I don't see much benefit in having a UI operation threadsafe though.
