### ISSUE TITLE
TextureArray

### ISSUE THREAD

**Issue by imcasper** [libgdx/libgdx#6380]
#### Issue details
After create `TextureArray`
I change the parameters  (UV-wrapping and texture-filtering)
The texture is not working (I see a black box)
If I don't change the parameters after creation, everything is fine.
I think the texture is incorrectly invalidated then I use the setFilter function (and maybe setWrap)

#### Reproduction steps/code
Create instance 
`new TextureArray(useMipMaps=true,...)`
or
`new TextureArray(useMipMaps=true,...)`

See what works correctly.

Create an instance again.
And change the property 
`setFilter(MipMapLinearLinear, Linear)`

Now I only see black (I believe the textures are invalid and some are broken, then I use the mip-map filter) 

#### Version of LibGDX and/or relevant dependencies
1.9.13

#### Please select the affected platforms
+ Linux

**Comment by mgsx-dev** [comment]
I was able to reproduce the issue, mipmap generation was missing for TextureArray.
