### ISSUE TITLE
I got gradle error when I try to work from java source.

### ISSUE THREAD

**Issue by game-libgdx-unity** [libgdx/libgdx#6383]
#### Issue details
I got gradle error when I try to work from java source.
OS: Mac OS Big Sur 11.0.1
Gradle 6.7.1
JDK/JRE 10
* What went wrong:
I followed the guide: https://libgdx.badlogicgames.com/documentation/hacking/Working%20from%20source.html
git clone git://github.com/libgdx/libgdx.git
cd libgdx
./gradlew fetchNatives

I got this error 
Execution failed for task ':ant-task-fetch'.
> The following error occurred while executing this line:
  /Users/macbookpro/libgdx/fetch.xml:50: 
  java.net.ConnectException: Operation timed out (Connection timed out)
  java.net.ConnectException: Operation timed out (Connection timed out)
  java.net.ConnectException: Operation timed out (Connection timed out)
  java.net.ConnectException: Operation timed out (Connection timed out)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by tommyettinger** [comment]
Looks like a network timeout for something libGDX needs to download to build. If this is the current source, which it looks like it is, then fetch.xml line 50 timed out for you downloading the Linux OpenAL natives for LWJGL3. That's likely a temporary issue with Sonatype, where the LWJGL3 files are downloaded from. I just ran `gradlew fetchNatives`, and got this:

```
$ gradlew fetchNatives
Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1m 38s
4 actionable tasks: 4 executed
```

So, it works now, at least some of the time. You can try to run `./gradlew fetchNatives` again, it shouldn't take more than a few minutes.

**Comment by game-libgdx-unity** [comment]
Yes It worked but when I built the gdx-test-android project, i tried this command 
./gradlew tests:gdx-tests-android:installDebug

Then it shows this error and build failed
![image](https://user-images.githubusercontent.com/5079800/106383367-09a85c80-63f8-11eb-8c6b-bad46d7cb9a9.png)

**Comment by game-libgdx-unity** [comment]
nvm it's resolved by updating the ndk
