### ISSUE TITLE
TextField / TextArea - textChanged Listener not fired on Ctrl-X / Ctrl-V

### ISSUE THREAD

**Issue by Grisgram** [libgdx/libgdx#6385]
Hi,

using libGdx 1.9.13 (latest)
when watching for text change in an input field, the callback gets not invoked when Ctrl-X oder Ctrl-V is pressed, but the text still changes.
This causes in some of my dialogs that the "ok" button stays disabled (because it gets enabled when text is not empty but if only ctrl-V is pressed to insert text from clipboard, the event does not trigger).
It also makes it hard to display the text length (like in "45/1024 characters") when Ctrl-X/V does not trigger a change.

kind regards,
Gris

**Comment by adhithiyan** [comment]
Hi Grisgram

I am able to get your requirements  by using ChangeListener ( below code snippet) . Is this what you are looking for or Did i totally miss the point ?

```java
		text1.addListener(new ChangeListener() {
			@Override
			public void changed(ChangeEvent event, Actor actor) {
				TextArea b = (TextArea) actor;
				System.out.println(b.getText().length());
				if(b.getText().length()==0)
					button1.setTouchable(Touchable.disabled);
				else
					button1.setTouchable(Touchable.enabled);

			}
		});
```

**Comment by NathanSweet** [comment]
OP ghosted.

**Comment by Grisgram** [comment]
Hi Nathan,
sorry i am not ghosted :-) but what @adhithiyan wrote is exactly the problem. Ctrl-V does not trigger that change event.
Sorry for not responding in time.

But when I read his post, it seems, the event is working on his end... not on mine.
I will dig deeper, maybe there is a side-effect in my code that keeps the event from triggering.

**Comment by NathanSweet** [comment]
Pasting goes through the `paste` method for me and fires a change event. If you can figure out how we can reproduce what you see, we are happy to take a look!
