### ISSUE TITLE
Duplicate symbol libgdx 1.9.14 on Robovm 2.3.12

### ISSUE THREAD

**Issue by Tonielro** [libgdx/libgdx#6402]
Please ensure you have given all the following requested information in your report.

#### Issue details
I updated from 1.9.13 to 1.9.14 stable.
When deploying  to iOS device it failed with duplicate symbol error. But when i switched back to version 1.9.13, everything works well.
I cleaned Robovm Global cache and Build folder but the error persists.

#### Reproduction steps/code
Setup project based on 1.9.13 with robovm 2.3.12. Ensure that your project runs well on 1.9.13 before updating to 1.9.14.
Update to 1.9.14 and try deploying iOS project to a device.

#### Version of LibGDX and/or relevant dependencies
libgdx 1.9.14 stable.

#### Stacktrace

[ERROR] 11:14:51.908 duplicate symbol '_Java_com_badlogic_gdx_graphics_g2d_Gdx2DPixmap_drawRect' in:
[ERROR] 11:14:51.908     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.o)
[ERROR] 11:14:51.908     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_g2d_Gdx2DPixmap.o)
[ERROR] 11:14:51.908 duplicate symbol '_Java_com_badlogic_gdx_graphics_g2d_Gdx2DPixmap_fillRect' in:
[ERROR] 11:14:51.908     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.o)
[ERROR] 11:14:51.908     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_g2d_Gdx2DPixmap.o)
[ERROR] 11:14:51.908 duplicate symbol '_Java_com_badlogic_gdx_graphics_g2d_Gdx2DPixmap_clear' in:
[ERROR] 11:14:51.908     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.o)
[ERROR] 11:14:51.908     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_g2d_Gdx2DPixmap.o)
[ERROR] 11:14:51.908 duplicate symbol '_Java_com_badlogic_gdx_graphics_g2d_Gdx2DPixmap_newPixmap' in:
[ERROR] 11:14:51.908     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.o)
[ERROR] 11:14:51.908     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_g2d_Gdx2DPixmap.o)
[ERROR] 11:14:51.908 duplicate symbol '_Java_com_badlogic_gdx_graphics_g2d_Gdx2DPixmap_drawPixmap' in:
[ERROR] 11:14:51.908     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.o)
[ERROR] 11:14:51.908     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_g2d_Gdx2DPixmap.o)
[ERROR] 11:14:51.908 duplicate symbol '_Java_com_badlogic_gdx_graphics_g2d_Gdx2DPixmap_getFailureReason' in:
[ERROR] 11:14:51.908     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.o)
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_g2d_Gdx2DPixmap.o)
[ERROR] 11:14:51.909 duplicate symbol '_Java_com_badlogic_gdx_graphics_g2d_Gdx2DPixmap_setPixel' in:
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.o)
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_g2d_Gdx2DPixmap.o)
[ERROR] 11:14:51.909 duplicate symbol '_Java_com_badlogic_gdx_graphics_g2d_Gdx2DPixmap_getPixel' in:
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.o)
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_g2d_Gdx2DPixmap.o)
[ERROR] 11:14:51.909 duplicate symbol '_Java_com_badlogic_gdx_graphics_g2d_Gdx2DPixmap_drawLine' in:
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.o)
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_g2d_Gdx2DPixmap.o)
[ERROR] 11:14:51.909 duplicate symbol '_Java_com_badlogic_gdx_graphics_g2d_Gdx2DPixmap_fillTriangle' in:
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.o)
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_g2d_Gdx2DPixmap.o)
[ERROR] 11:14:51.909 duplicate symbol '_Java_com_badlogic_gdx_graphics_g2d_Gdx2DPixmap_drawCircle' in:
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.o)
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_g2d_Gdx2DPixmap.o)
[ERROR] 11:14:51.909 duplicate symbol '_Java_com_badlogic_gdx_graphics_g2d_Gdx2DPixmap_fillCircle' in:
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.o)
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_g2d_Gdx2DPixmap.o)
[ERROR] 11:14:51.909 duplicate symbol '_Java_com_badlogic_gdx_graphics_g2d_Gdx2DPixmap_setScale' in:
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.o)
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_g2d_Gdx2DPixmap.o)
[ERROR] 11:14:51.909 duplicate symbol '_Java_com_badlogic_gdx_graphics_g2d_Gdx2DPixmap_free' in:
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.o)
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_g2d_Gdx2DPixmap.o)
[ERROR] 11:14:51.909 duplicate symbol '_Java_com_badlogic_gdx_graphics_g2d_Gdx2DPixmap_setBlend' in:
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.o)
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_g2d_Gdx2DPixmap.o)
[ERROR] 11:14:51.909 duplicate symbol '_Java_com_badlogic_gdx_graphics_g2d_Gdx2DPixmap_load' in:
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.o)
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_g2d_Gdx2DPixmap.o)
[ERROR] 11:14:51.909 duplicate symbol '_Java_com_badlogic_gdx_graphics_glutils_ETC1_formatHeader' in:
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.glutils.ETC1.o)
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_glutils_ETC1.o)
[ERROR] 11:14:51.909 duplicate symbol '_Java_com_badlogic_gdx_graphics_glutils_ETC1_getCompressedDataSize' in:
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.glutils.ETC1.o)
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_glutils_ETC1.o)
[ERROR] 11:14:51.909 duplicate symbol '_Java_com_badlogic_gdx_graphics_glutils_ETC1_encodeImage' in:
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.glutils.ETC1.o)
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_glutils_ETC1.o)
[ERROR] 11:14:51.909 duplicate symbol '_Java_com_badlogic_gdx_graphics_glutils_ETC1_decodeImage' in:
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.glutils.ETC1.o)
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_glutils_ETC1.o)
[ERROR] 11:14:51.909 duplicate symbol '_Java_com_badlogic_gdx_graphics_glutils_ETC1_getHeightPKM' in:
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.glutils.ETC1.o)
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_glutils_ETC1.o)
[ERROR] 11:14:51.909 duplicate symbol '_Java_com_badlogic_gdx_graphics_glutils_ETC1_getWidthPKM' in:
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.glutils.ETC1.o)
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_glutils_ETC1.o)
[ERROR] 11:14:51.909 duplicate symbol '_Java_com_badlogic_gdx_graphics_glutils_ETC1_encodeImagePKM' in:
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.glutils.ETC1.o)
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_glutils_ETC1.o)
[ERROR] 11:14:51.909 duplicate symbol '_Java_com_badlogic_gdx_graphics_glutils_ETC1_isValidPKM' in:
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.glutils.ETC1.o)
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_graphics_glutils_ETC1.o)
[ERROR] 11:14:51.909 duplicate symbol '_Java_com_badlogic_gdx_utils_BufferUtils_freeMemory' in:
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.utils.BufferUtils.o)
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_utils_BufferUtils.o)
[ERROR] 11:14:51.909 duplicate symbol '_Java_com_badlogic_gdx_utils_BufferUtils_getBufferAddress' in:
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.utils.BufferUtils.o)
[ERROR] 11:14:51.909     /Users/tonielro/.robovm/cache/ios/arm64/release/Users/tonielro/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.14/c7d0536467112c5313c7da6d34a2c1229192623f/gdx-platform-1.9.14-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com_badlogic_gdx_utils_BufferUtils.o)

#### Please select the affected platforms
The affected platform is iOS.

**Comment by Tom-Ski** [comment]
Try the latest snapshot 1.9.15-SNAPSHOT or revert back to 13. This was a regression
