### ISSUE TITLE
MacOS Lwjgl3: ctrl+click is not detected as right-click

### ISSUE THREAD

**Issue by MarcinSc** [libgdx/libgdx#6405]
#### Issue details
When running LWJGL3 - a ctrl+click (on a laptop with touch pad) is not detected as right-click. Instead the button returned is 0 (LEFT).

#### Reproduction steps/code
Create any actor with touchUp listener and print out the button. On Desktop (legacy) - ctrl+click on laptop returns 1, on LWJGL3 - it returns 0;

#### Version of LibGDX and/or relevant dependencies
1.9.13 and 1.9.14

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS

**Comment by MrStahlfelge** [comment]
On MacOS touchpads, right click is tapping with two fingers - at least on mine.

**Comment by MarcinSc** [comment]
I'm used to ctrl+click on pretty much any other application - as a replacement for the right-click... maybe should be added as an alternative to two-finger-click?

**Comment by MrStahlfelge** [comment]
Okay, TIL ctrl+click works, too. Did you test if the two finger click works in Lwjgl3?

**Comment by crykn** [comment]
I never heard about the CTRL+click shortcut either, but it is even recommended by the [macOS User Guide](https://support.apple.com/en-gb/guide/mac-help/mh35853/mac). @MarcinSc maybe you could raise this issue with the LWJGL3 team, as for LWJGL2 this behaviour was [(re)implemented manually](https://github.com/LWJGL/lwjgl/commit/43a6a8bfbb1b55fe49ccbcb82997ddad51ce809b) after it lead to problems for Minecraft users (https://github.com/LWJGL/lwjgl/issues/37).

**Comment by MrStahlfelge** [comment]
Nice research work, please link the issue you open on lwjgl3 here @MarcinSc

**Comment by MarcinSc** [comment]
I've created an issue on lwjgl:
https://github.com/LWJGL/lwjgl3/issues/621

**Comment by MarcinSc** [comment]
I was sent to GLFW project:
https://github.com/glfw/glfw/issues/1846

**Comment by crykn** [comment]
I think ViRb3 raised some valid concerns [in the GLFW issue](https://github.com/glfw/glfw/issues/1846#issuecomment-988787270). There are legitimate use cases where one wouldn't want this behaviour and if we decided to implement this in libGDX, those users would have to jump through considerable hoops to avoid this. On the other hand, it should be rather easy to implement this on the application side.

If no one has any objections, I'm voting to close this.
