### ISSUE TITLE
Error creating FrameBuffer in latest version

### ISSUE THREAD

**Issue by bladecoder** [libgdx/libgdx#6407]
#### Issue details
The creation of a Framebuffer is failing in v1.9.14 in the lwjgl 2 backend. The same code works well in v1.9.13.

Digging in the changes, I think that error is produced by the next commit created by @mgsx-dev

https://github.com/libgdx/libgdx/commit/1cfb4a8b5b6fdd8275ef7962a107f6b81166865b

#### Reproduction steps/code
Try to create a Framebuffer:

```java
		FrameBuffer fbo = new FrameBuffer(Format.RGB565, w, h, false);
```

#### Version of LibGDX and/or relevant dependencies
This only happens in v1.9.14.

#### Stacktrace
```java
Exception in thread "LWJGL Application" org.lwjgl.opengl.OpenGLException: Cannot use offsets when Pixel Unpack Buffer Object is disabled
	at org.lwjgl.opengl.GLChecks.ensureUnpackPBOenabled(GLChecks.java:125)
	at org.lwjgl.opengl.GL11.glTexImage2D(GL11.java:2899)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glTexImage2D(LwjglGL20.java:598)
	at com.badlogic.gdx.graphics.glutils.GLOnlyTextureData.consumeCustomData(GLOnlyTextureData.java:78)
	at com.badlogic.gdx.graphics.GLTexture.uploadImageData(GLTexture.java:270)
	at com.badlogic.gdx.graphics.GLTexture.uploadImageData(GLTexture.java:257)
	at com.badlogic.gdx.graphics.Texture.load(Texture.java:159)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:147)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:142)
	at com.badlogic.gdx.graphics.glutils.FrameBuffer.createTexture(FrameBuffer.java:81)
	at com.badlogic.gdx.graphics.glutils.FrameBuffer.createTexture(FrameBuffer.java:42)
	at com.badlogic.gdx.graphics.glutils.GLFrameBuffer.build(GLFrameBuffer.java:174)
	at com.badlogic.gdx.graphics.glutils.FrameBuffer.<init>(FrameBuffer.java:75)
	at com.badlogic.gdx.graphics.glutils.FrameBuffer.<init>(FrameBuffer.java:57)
	at com.bladecoder.engine.model.World.takeScreenshot(World.java:824)```
```
#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
This has been fixed in the latest snapshot.

**Comment by hasen6** [comment]
> This has been fixed in the latest snapshot.

Which can be found where? All I could find is the latest version 1.9.14 of LibGDX which is strangely the non working version https://libgdx.com/dev/project-generation/ Where can I get the 1.9.15 SNAPSHOT or any other versions of the project creation tool?

**Comment by Tom-Ski** [comment]
You don't need to download a new project generator, just change the version in a generated project build.gradle file

**Comment by tommyettinger** [comment]
Yeah, just change `1.9.14` to `1.9.15-SNAPSHOT` in any place it appears in the topmost build.gradle . You will need to change it again shortly after 1.9.15 is released as stable, but that is just taking away the `-SNAPSHOT` part to leave `1.9.15`.

**Comment by hasen6** [comment]
> Yeah, just change `1.9.14` to `1.9.15-SNAPSHOT` in any place it appears in the topmost build.gradle . You will need to change it again shortly after 1.9.15 is released as stable, but that is just taking away the `-SNAPSHOT` part to leave `1.9.15`.

Ok that fixed the errors. But it has the number 1.9.14 all kinds of other places in the project too - that doesn't matter?

**Comment by tommyettinger** [comment]
The version typically isn't hard-coded anywhere but the assignment to gdxVersion in the root build.gradle, specifically so it's easier to upgrade. Extensions may also be version 1.9.14, and those should probably be updated too (probably in the same file). Where a version has a replacement-string like `"com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"`, the `$gdxVersion` gets replaced by 1.9.14 or 1.9.15-SNAPSHOT or whatever else it is assigned to in build.gradle (or gradle.properties, an alternative location to set these properties). You may want to ask further questions on the Discord: https://discord.gg/8TC7H2v .

**Comment by JideaGit** [comment]
Hello, it seems like this issue appears in 1.10.0 again. Reverting to 1.9.15 still fixes it for me.

**Comment by Frosty-J** [comment]
1.9.15 doesn't exist. 1.9.15-SNAPSHOT disappeared when 1.9.14's successor released, which turned out to be 1.10.0. Do you mean 1.9.13?

**Comment by JideaGit** [comment]
Hi, you're right, I was wondering about that too. But I actually did go from 1.10.0 to 1.9.15-SNAPSHOT and it fixed the issue.
I guess 1.9.15-SNAPSHOT automatically refers to something else now?
1.9.13 works as well, just tested it. But with 1.9.14 or 1.10.0 I get the error.
Statement is:
`FrameBuffer fbo = new FrameBuffer(Format.RGBA8888, Gdx.graphics.getWidth(), Gdx.graphics.getHeight(), false);`
I'm doing nothing else with that object, just creating it in the create() or any other method. Instantly crashes with the same error message as OP.

BR

**Comment by tommyettinger** [comment]
I just tested this with 1.10.0, as you said, @Xjidea , by adding `FrameBuffer fbo = new FrameBuffer(Pixmap.Format.RGBA8888, Gdx.graphics.getWidth(), Gdx.graphics.getHeight(), false);` to the start of my create() method. There is no difference with that line in or out; both work fine. This is true for LWJGL 2 and 3. Check your dependencies for anything that might be pulling 1.9.14, which is the release that has the bug, and don't use snapshot releases after the following stable release is out, because the snapshot could cease to exist anytime. This bug is **fixed**, so any other issues are related to something else in your code, and should be discussed further [in the Discord](https://discord.gg/nVT3Xgh). Be prepared to paste relevant code, answer questions, etc. if you want your problem solved.
