### ISSUE TITLE
Padding of TextButton doesn't work

### ISSUE THREAD

**Issue by galloj** [libgdx/libgdx#6415]
#### Issue details
When TextButton is rendered and isn't added to table, then the padding have no effect on it.

#### Reproduction steps/code
```Java
package com.mygdx.game;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Skin;
import com.badlogic.gdx.scenes.scene2d.ui.TextButton;
import com.badlogic.gdx.utils.ScreenUtils;

public class MyGdxGame extends ApplicationAdapter {
	Stage stage;
	
	@Override
	public void create () {
		stage = new Stage();
		TextButton textButton = new TextButton("TEST", new Skin(Gdx.files.internal("uiskin.json")));
		textButton.pad(50);
		stage.addActor(textButton);
	}

	@Override
	public void render () {
		ScreenUtils.clear(0, 0, 0, 1);
		stage.draw();
	}
}
```
When the code of `create` method is replaced with this, then the padding works fine:
```Java
stage = new Stage();
TextButton textButton = new TextButton("TEST", new Skin(Gdx.files.internal("uiskin.json")));
textButton.pad(50);
Table table = new Table();
table.setFillParent(true);
table.add(textButton);
stage.addActor(table);
```
#### Version of LibGDX and/or relevant dependencies
Tested on 1.9.10 and 1.9.14.

#### Please select the affected platforms
- [?] Android
- [?] iOS
- [?] HTML/GWT
- [?] Windows
- [x] Linux
- [?] MacOS

I have tested the issue only on linux.

**Comment by NathanSweet** [comment]
When the TextButton is created, the size is set to the pref size. Setting the padding doesn't change the TextButton size. If you want that, call `pack()` (which sets the width and height to the pref width and pref height).

**Comment by galloj** [comment]
Thank you a lot for fast solution
