### ISSUE TITLE
Intersector intersectSegmentRectangle , function return true if start of segment is inside rectangle

### ISSUE THREAD

**Issue by fabiitch** [libgdx/libgdx#6416]
Hi,  i was looking  intersectSegmentRectangle function in Intersector class. 

com.badlogic.gdx.math.Intersector#intersectSegmentRectangle(float, float, float, float, com.badlogic.gdx.math.Rectangle)

	public static boolean intersectSegmentRectangle (float startX, float startY, float endX, float endY, Rectangle rectangle) {
		float rectangleEndX = rectangle.x + rectangle.width;
		float rectangleEndY = rectangle.y + rectangle.height;

		if (intersectSegments(startX, startY, endX, endY, rectangle.x, rectangle.y, rectangle.x, rectangleEndY, null)) return true;

		if (intersectSegments(startX, startY, endX, endY, rectangle.x, rectangle.y, rectangleEndX, rectangle.y, null)) return true;

		if (intersectSegments(startX, startY, endX, endY, rectangleEndX, rectangle.y, rectangleEndX, rectangleEndY, null))
			return true;

		if (intersectSegments(startX, startY, endX, endY, rectangle.x, rectangleEndY, rectangleEndX, rectangleEndY, null))
			return true;

		return rectangle.contains(startX, startY);
	}

The last line seems wrong `return rectangle.contains(startX, startY);,`  it should be a return false no ?.
The contains of the point don't mean he intersect the rectangle.
Maybe i missed something ...

Thanks for reading

**Comment by mgsx-dev** [comment]
It's intended, most of Intersector methods consider shapes as solid (eg. intersectRectangles, intersectPolygons), so rectangle is considered as a polygon.
There are "edges" variants for some methods (eg. intersectPolygonEdges). 
What you want would be a new intersectSegmentRectangleEdges method, you can make a PR if you think it could be helpful.

**Comment by fabiitch** [comment]
Oh ok , sry i should have look other methods in Intersector before post issues.
Thanks you for answer
