### ISSUE TITLE
LWJGL3 should be the default

### ISSUE THREAD

**Issue by Frosty-J** [libgdx/libgdx#6426]
This issue seems to be making the rounds. If someone linked you to it but didn't state how to switch an existing project to LWJGL3, please see https://gist.github.com/crykn/eb37cb4f7a03d006b3a0ecad27292a2d. It's a painless process.  :)

#### Issue details
The number of Java 8 users is dwindling by the day. Picture this: You're just getting into Java development. Which version of Java do you download? Probably 11 (LTS) or 15 (the latest). Or 16 by the time you're reading this.

But then you go and create your very first libGDX project and it goes "aN iLlEgAl ReFlEcTiVe AcCeSs OpErAtIoN hAs OcCuRrEd". Off-putting, right? A fair few people have asked about this message in the [libGDX Discord server](https://discord.gg/6pgDK9F) this year alone. And if you're a Linux user who installed OpenJDK from the repositories, it probably won't even work at all.

Even if you get this far, LWJGL2 might screw up somewhere. LWJGL2 stuff fails to launch for me if running my screen at 50Hz (maybe because it's a custom xrandr mode?), which I sometimes use for 50fps games and PAL videos. I hear that it might not get along with certain graphics cards either, and if it does have any issues with newer cards it won't get updated to fix those issues.

Then there's better support for high pixel density displays in LWJGL3... probably. I've not really tested that yet. But if that works better in LWJGL3, that's kinda important due to the large number of laptops and those weird Windows tablet things that cram lots of pixels into a small space. And something something better support for multiple monitors.

The LWJGL3 backend isn't perfect, I get that. But it's made some real strides lately with LWJGL2 features added such as hiding the mouse cursor and capping the frame rate. I think the LWJGL3 backend is the better choice for most developers, and this gap is only going to widen with time due to LWJGL2 being abandonded for 6 years now. Yeah, just think about that - it's never had an update during the existence of Windows 10.

If we make LWJGL3 the default, anyone who knows what they're doing will still be able to use LWJGL2 in new projects by changing the Gradle file and DesktopLauncher class. At least, until something breaks it, at which point it can honestly bog off forever and anyone who really wants it can remain on an old libGDX version.

#### Reproduction steps/code
1. Create a project using the official setup tool (found at https://libgdx.com/dev/project-generation/).
2. Ensure you're using Java 9 or newer, and if possible ensure your computer is abnormal in some way (if it runs Arch, you are also abnormal).
3. Watch the world burn.

#### Version of LibGDX and/or relevant dependencies
All versions. All of them.

##### Example of running a LWJGL2 libGDX project with Java 9 or newer:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/C:/Users/tommy/Downloads/Groxar/desktop/desktop/app/desktop-1.0.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

##### Example of running a LWJGL2 libGDX project with my 50Hz problem:
```
Exception in thread "LWJGL Application" java.lang.ExceptionInInitializerError
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setVSync(LwjglGraphics.java:625)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:125)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.lwjgl.opengl.XRandR.findPrimary(XRandR.java:326)
	at org.lwjgl.opengl.XRandR.ScreentoDisplayMode(XRandR.java:315)
	at org.lwjgl.opengl.LinuxDisplay$3.run(LinuxDisplay.java:746)
	at org.lwjgl.opengl.LinuxDisplay$3.run(LinuxDisplay.java:743)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:743)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
	... 2 more
AL lib: (EE) alc_cleanup: 1 device not closed
```

##### Example of running a LWJGL2 libGDX project with Java 11:
```
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

##### Example of running a LWJGL2 libGDX project with Java 15:
```
[LwjglApplication] Couldn't initialize audio, disabling audio
java.lang.UnsatisfiedLinkError: /tmp/libgdxjames/dd5c1a65/liblwjgl64.so: /usr/lib/jvm/java-15-oracle/lib/libjawt.so: version `SUNWprivate_1.1' not found (required by /tmp/libgdxjames/dd5c1a65/liblwjgl64.so)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2407)
	at java.base/java.lang.Runtime.load0(Runtime.java:747)
	at java.base/java.lang.System.load(System.java:1857)
	at org.lwjgl.Sys$1.run(Sys.java:70)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:87)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at org.lwjgl.openal.AL.<clinit>(AL.java:59)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALLwjglAudio.<init>(OpenALLwjglAudio.java:71)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.createAudio(LwjglApplication.java:278)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:90)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:71)
	at com.javacakegames.countingthonks.desktop.DesktopLauncher.main(DesktopLauncher.java:19)
Exception in thread "LWJGL Application" java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.Sys
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setVSync(LwjglGraphics.java:625)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:125)
```

**NONE OF THE ABOVE ISSUES HAPPEN WITH LWJGL3!**

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by tommyettinger** [comment]
I agree, and this is why gdx-liftoff has defaulted to LWJGL3 for pretty much as long as it has existed. The ld.so bug in particular is a problem because only specific OpenJDK vendors make an OpenJDK that works with LWJGL2 (AdoptOpenJDK works, not sure who else. Corretto fails on ld.so.). The illegal reflection warning should go away once Java 16 becomes more common, since it actually goes ahead and makes the illegal reflection fail, and LWJGL 2 and 3 both work around that case. There's some complaints that can be registered about LWJGL3, especially on MacOS where it needs `-XstartOnFirstThread`, but @crykn 's Guacamole can provide that... maybe that feature should be merged into libGDX? There's actually quite a lot of Java 8 users because Android and iOS don't really support much of anything higher than 8. I currently have just Java 15 and Java 8 installed on this machine. It seems like the LWJGL2 problems are much worse on Linux than other platforms, but LWJGL3 also can have intermittent, sometimes serious issues on some Linux machines. I think enough large strides have been made recently to bring LWJGL3 up to compatibility with LWJGL2's features here in GDX-land, and LWJGL3 may be ready to become the default.

**Comment by mgsx-dev** [comment]
i think we need to address #5960 before, since Lwjgl3 + GLES3 doesn't work on MacOS right now.

**Comment by crykn** [comment]
#5960 happens with both LWJGL 2 and 3, so I think we can just go forward with making the LWJGL 3 backend the default.

**Comment by mgsx-dev** [comment]
@crykn my bad, i thought Lwjgl3 backend only support core profile, but it's MacOS that only support core profile when using OpenGL 3.2+.

**Comment by phu54321** [comment]
On apple silicon, LWJGL3 should be updated to 3.3.0+ to work correctly. Or it'll get this dreaded error.

```
> Task :desktop:DesktopLauncher.main()
[LWJGL] GLFW_PLATFORM_ERROR error
	Description : Cocoa: Failed to find service port for display
	Stacktrace  :
		org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:830)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:85)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:92)
		com.trgksoft.dodgepuzzle.desktop.DesktopLauncher.main(DesktopLauncher.java:19)
```

https://github.com/LWJGL/lwjgl3/issues/601#issuecomment-792343084

**Comment by mgsx-dev** [comment]
@phu54321 thank you, we're all set (see https://github.com/libgdx/libgdx/commit/7ac239c81f7d126c3be5ad18c25bcdb2ff811fd5), just need LWJGL 3.3.0 to be out. I don't think it's related to this issue because i don't think LWJGL2 backend will work neither.

**Comment by phu54321** [comment]
Lwjgl2 works (on rosetta) but lwjgl3 never works. IDK why.

**Comment by wtsiamruk** [comment]
> Lwjgl2 works (on rosetta) but lwjgl3 never works. IDK why.

Actually, lwjgl3 works on m1 chips here is the issue: https://github.com/LWJGL/lwjgl3/issues/601
And the exact comment with their CI: https://github.com/LWJGL/lwjgl3/issues/601#issuecomment-792071363

**Comment by tommyettinger** [comment]
I think I should mention the discussion re: LWJGL 2 and 3 in the packr project: https://github.com/libgdx/packr/issues/205#issuecomment-879508300

What Walker has found (through building many, many .app and .jar combinations) is that LWJGL2 has basically stopped working when used with Packr and run on MacOS Catalina, while LWJGL3 at least has a way that it can work normally. He also, importantly, noticed that the JavaDocs for libGDX include `lwjgl` but not `lwjgl3`. The JavaDocs seem out of date in other ways, too.

**Comment by crykn** [comment]
I think in the wake of this we should expedite our migration to the LWJGL 3 backend and merge #6463. The one big remaining issue, which is the missing Lwjgl3AwtCanvas (#6247), shouldn't stop us from this if we are already losing backwards-compatibility. 

Regarding the javadocs: the LWJGL 3 ones were apparently never published (#4667) and the outdatedness is probably a side effect of #6445.

**Comment by PokeMMO** [comment]
#5802 is another issue with lwjgl3's backend that should be merged/fixed, but is admittedly a low priority.

**Comment by IgorApplications** [comment]
Does LWJGL3 work on MacOS?

**Comment by crykn** [comment]
Yes. However, if you are on a M1 mac, be sure to use the `1.10.1-SNAPSHOT` of libGDX, as only the latest version of LWJGL 3 is compatible.
