### ISSUE TITLE
Html module fails to run task superDev

### ISSUE THREAD

**Issue by lyze237** [libgdx/libgdx#6427]
#### Issue details
Html task `superDev` fails due to gretty not being fetchable from maven.

Fix: https://stackoverflow.com/questions/66304743/getting-error-on-gretty-when-building-html-project-for-libgdx

#### Reproduction steps/code
Create a new project via the setup app and try to run gradle taks `superDev`

#### Version of LibGDX and/or relevant dependencies
1.9.14

#### Stacktrace
```java
 ./gradlew.bat superDev
> Task :html:beforeRun FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':html:beforeRun'.
> Could not resolve all files for configuration ':html:grettyRunnerJetty94'.
   > Could not find org.gretty:gretty-runner-jetty94:3.0.2.
     Searched in the following locations:
       - file:/C:/Users/lyze/.m2/repository/org/gretty/gretty-runner-jetty94/3.0.2/gretty-runner-jetty94-3.0.2.pom
       - https://repo.maven.apache.org/maven2/org/gretty/gretty-runner-jetty94/3.0.2/gretty-runner-jetty94-3.0.2.pom
       - https://dl.google.com/dl/android/maven2/org/gretty/gretty-runner-jetty94/3.0.2/gretty-runner-jetty94-3.0.2.pom
       - https://oss.sonatype.org/content/repositories/snapshots/org/gretty/gretty-runner-jetty94/3.0.2/gretty-runner-jetty94-3.0.2.pom
       - https://oss.sonatype.org/content/repositories/releases/org/gretty/gretty-runner-jetty94/3.0.2/gretty-runner-jetty94-3.0.2.pom
     Required by:
         project :html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See **https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings**
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [x] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by obigu** [comment]
Probably caused by https://github.com/libgdx/libgdx/pull/6393.

Yesterday I also came across with a `trove4j` missing dependency error when running build on a new machine on a newly generated project. I think `maven { url 'https://plugins.gradle.org/m2/' }` is also required on `repositories`. Will make a quick PR.

**Comment by MobiDevelop** [comment]
I think it is technically more correct to use `gradlePluginPortal()` instead of the direct maven repo entry.

**Comment by obigu** [comment]
Good point, I'll replace all the references on this PR.

**Comment by MrStahlfelge** [comment]
>  I think `maven { url 'https://plugins.gradle.org/m2/' }` is also required on `repositories`

Yep it is. Somehow the needed plugins are cached differently from the normal cache, so the problem typically occurs on freshly set up machines or CI.

**Comment by fabiitch** [comment]
@lyze237 you can add jcenter() in repositories inside build.gradle for fix temporarily.
