### ISSUE TITLE
calculateBoundingBox unnecessarily dirties the vertex and index buffers

### ISSUE THREAD

**Issue by neilccbrown** [libgdx/libgdx#6430]
#### Issue details
Calling Mesh.calculatingBoundingBox (and related functions like Mesh.extendBoundingBox, Mesh.calculateRadius) calls VertexData.getBuffer() and IndexData.getBuffer().  The implementations of these methods mark the buffer as dirty (for the general case where the user has called them and may modify the data) and on the next call to VertexData.bind() the data is reuploaded to the GPU using glBufferData or similar.

This means that calculating the bounding box is made into an expensive GPU operation even though it doesn't need to go near the GPU.  I have problems with this where I am animating a small part of a big model and recalculating the bounding box, which causes my whole model to be reuploaded to the GPU.  The test case below shows that while the bounding box calculation is quite quick (5 microseconds), the reupload is much more expensive if the GPU is saturated (740 microseconds).

I suggest that VertexData should have some kind of access mechanism specifically for the Mesh bounding box methods that allows it to access the data without marking it as dirty, whether that's a getBufferReadOnly() method or some kind of instanceof check for the built-in buffer types.  It's a pain to work around as a library user - you either need to hold a duplicate copy of the mesh for the bounding box checks, or you have to duplicate the calculateBoundingBox code yourself and hack into the vertex buffer internals to get the data without marking it as dirty.

#### Reproduction steps/code
Here is a complete test case showing the times involved:
```java
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.Mesh;
import com.badlogic.gdx.graphics.VertexAttribute;
import com.badlogic.gdx.graphics.g3d.model.MeshPart;
import com.badlogic.gdx.graphics.glutils.ShaderProgram;
import com.badlogic.gdx.math.collision.BoundingBox;

public class MyGdxGame extends ApplicationAdapter {
    public static final int LOOP_AMOUNT = 1000;
    public static final int FRAME_AMOUNT = 10;
    ShaderProgram shaderProgram;
	Mesh bigMesh;
	MeshPart meshPart;
	BoundingBox boundingBox = new BoundingBox();
	int frames = 0;
	
	long nanosJustBox;
	long nanosDirtyBind;
        long nanosCleanBind;
	
	@Override
	public void create () {
		bigMesh = new Mesh(true, 30_000, 100, VertexAttribute.Position(), VertexAttribute.Normal(), VertexAttribute.Tangent(), VertexAttribute.TexCoords(0));
		// Vertex values not important here:
		float[] vertices = new float[30_000 * 11];
        short[] indices = new short[bigMesh.getMaxIndices()];
        for (int i = 0; i < bigMesh.getMaxIndices(); i++)
        {
            indices[i] = (short)i;
        }
        bigMesh.setVertices(vertices);
        bigMesh.setIndices(indices);
        meshPart = new MeshPart("", bigMesh, 0, 100, GL20.GL_TRIANGLES);
        String vs = "attribute vec4 a_position; void main(){ gl_Position = a_position;}";
        String fs = "void main(){ gl_FragColor = vec4(1.0, 1.0, 1.0, 1.0); }";
        shaderProgram = new ShaderProgram(vs, fs);
	}

	@Override
	public void render () {
	    if (frames < FRAME_AMOUNT)
        {
            long t0 = System.nanoTime();
            for (int i = 0; i < LOOP_AMOUNT; i++)
                meshPart.mesh.calculateBoundingBox(boundingBox, meshPart.offset, meshPart.size);
            long t1 = System.nanoTime();
            for (int i = 0; i < LOOP_AMOUNT; i++)
            {
                // Calls vertices.getBuffer(), which does the dirty marking without the work of calculateBoundingBox:
                meshPart.mesh.getVerticesBuffer();
                bigMesh.bind(shaderProgram);
                bigMesh.unbind(shaderProgram);
            }
            long t2 = System.nanoTime();
            for (int i = 0; i < LOOP_AMOUNT; i++)
            {
                bigMesh.bind(shaderProgram);
                bigMesh.unbind(shaderProgram);
            }
            long t3 = System.nanoTime();
            
            nanosJustBox += (t1 - t0);
            nanosDirtyBind += (t2 - t1);
            nanosCleanBind += (t3 - t2);
        }
	    else if (frames == FRAME_AMOUNT)
        {
            System.out.println("Nanos on box: " + (nanosJustBox / (FRAME_AMOUNT * LOOP_AMOUNT)));
            System.out.println("Nanos on dirty bind: " + (nanosDirtyBind / 10000L));
            System.out.println("Nanos on clean bind: " + (nanosCleanBind / 10000L));
        }
        frames += 1;
	}
	
	@Override
	public void dispose () {
		bigMesh.dispose();
	}
}

```

#### Version of LibGDX and/or relevant dependencies
The above used libGDX 1.9.14

#### Output
On an Nvidia GTX 1080 I got the following output:
```
Nanos on box: 5383
Nanos on dirty bind: 739774
Nanos on clean bind: 1469
```
The difference between dirty bind and clean bind is equivalent to the effect of calculateBoundingBox unnecessarily marking the mesh as dirty.

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by mgsx-dev** [comment]
@twistedsquare nice catch! if needed you can give a try with my PR #6431, it should fix your issue.
