### ISSUE TITLE
Font bounds different for FNT files

### ISSUE THREAD

**Issue by HeinousGames** [libgdx/libgdx#6441]
#### Issue details
Making a label with a TTF font sets correct bounds for the label. Using an FNT font will set the bounds below the actual label.

#### Reproduction steps/code
Clone the project located here: https://github.com/HeinousGames/LibGdxFontBug
Running a desktop configuration will show a label using a TTF font with correct bounds using debug options. Comment line 48 and uncomment line 49 to run the same code with the FNT label. The bounds are drawn below the label, not surrounding the text like with the TTF label.

#### Version of LibGDX and/or relevant dependencies
1.9.11, 1.9.12, 1.914

#### Stacktrace
No stack trace

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [X] MacOS

**Comment by NathanSweet** [comment]
<details>
  <summary>Code that can be pasted into gdx-tests-lwjgl</summary>

```
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.OrthographicCamera;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Label;
import com.badlogic.gdx.scenes.scene2d.ui.Table;
import com.badlogic.gdx.utils.viewport.ScreenViewport;

public class Main extends ApplicationAdapter {

	private OrthographicCamera camera;
	private Stage stageUI;

	@Override
	public void create () {
		FreeTypeFontGenerator generator = new FreeTypeFontGenerator(Gdx.files.internal("data/arial.ttf"));
		FreeTypeFontGenerator.FreeTypeFontParameter parameter = new FreeTypeFontGenerator.FreeTypeFontParameter();
		parameter.color = Color.BLACK;
		parameter.size = 32;
		BitmapFont ttfFont = generator.generateFont(parameter);
		generator.dispose();

		Label.LabelStyle ttfStyle = new Label.LabelStyle();
		ttfStyle.font = ttfFont;

		Label.LabelStyle fntStyle = new Label.LabelStyle();
		fntStyle.fontColor = Color.BLACK;
		fntStyle.font = new BitmapFont(Gdx.files.internal("data/arial-32.fnt"));

		Label ttfLabel = new Label("Test Text (ttf)", ttfStyle);

		camera = new OrthographicCamera();
		camera.setToOrtho(false, 288, 208);
		camera.position.set(288 / 2, 208 / 2, 0);
		camera.update();
		stageUI = new Stage(new ScreenViewport());

		Label fntLabel = new Label("Test Text (fnt)", fntStyle);

		Table table = new Table();
		table.setFillParent(true);
		//table.add(ttfLabel).row();
		table.add(fntLabel).row();
		stageUI.addActor(table);

		table.debug();
	}

	@Override
	public void render () {
		Gdx.gl.glClearColor(1, 1, 1, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		stageUI.act();
		stageUI.draw();
		camera.update();
	}

	@Override
	public void dispose () {
		stageUI.dispose();
	}

	static public void main (String[] args) throws Exception {
		new LwjglApplication(new Main());
	}
}
```
</details>

I see a difference with Arial 32, but neither looks wrong.
![](http://n4te.com/x/8609-amOS.png)
![](http://n4te.com/x/8610-bNzU.png)

**Comment by tommyettinger** [comment]
Your .fnt file has some issues. You can fix the line height by changing the second line to start with 
```
common lineHeight=10 base=16
```
(base was 26 before, which is too much). You might also see a benefit from calling
```java
fntStyle.font.setUseIntegerPositions(false);
```

With both of those changes, my output looks like
![Screenshot of fix](https://i.imgur.com/Vl82YQa.png)
What program did you use to generate this .fnt file? I didn't think Hiero produced a `letter="!"` (or some other char) at the end of each glyph line.

**Comment by HeinousGames** [comment]
@tommyettinger I retrieved the file from here, somebody else made it themselves and knew it wasn't perfect: https://opengameart.org/content/good-neighbors-pixel-font-starlingunity-version-updated

Thanks for figuring out what was causing the issue. All of my labels were off in my menus and it was making me so mad lol

**Comment by tommyettinger** [comment]
I might have gotten the line-height wrong if you used that font in a multi-line text field, but it's editable in the same way. If 10 is too small, line height might need to be in the 14-19 range. I've noticed that most .fnt writing software has subtle quirks, and it's pretty hard to have a .fnt generate and be immediately usable without tweaking some of those settings. That is a nice font though; it probably will look best if it isn't getting stretched much by the viewport, or is stretched at integer multiples (300% is great, 137% is not so great).

I think this is resolved now? NathanSweet tried with Arial and that worked, and with some changes to the .fnt, Good Neighbors seems to work now for you, so I think I can close this.
