### ISSUE TITLE
Extract loop() out of Lwjgl3Application constructor so app may be exited programmatically

### ISSUE THREAD

**Issue by calvertdw** [libgdx/libgdx#6442]
#### Issue details
When creating an Lwjgl3Application, the loop is in the constructor, so the created object is never returned, so you can't call exit() on it.

I suggest to extract a start method out of the constructor so we may call it separately. Other options include and alternate constructor for this and launching the loop in a thread so the constructor can return.

```
public Lwjgl3Application(ApplicationListener listener, Lwjgl3ApplicationConfiguration config)
{
   initializeGlfw();
	
   [...]

   windows.add(window);
}

public void start() {
   try {
      loop();
      cleanupWindows();
   } catch(Throwable t) {
   if (t instanceof RuntimeException)
      throw (RuntimeException) t;
   else
      throw new GdxRuntimeException(t);
   } finally {
      cleanup();
   }
}
```

#### Version of LibGDX and/or relevant dependencies
1.9.14

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by mgsx-dev** [comment]
calling `Gdx.app.exit()` in your game loop is the right way to exit the app.
