### ISSUE TITLE
Outdated links in Bullet documentation.

### ISSUE THREAD

**Issue by edgarssilva** [libgdx/libgdx#6449]
As the title says there's outdated links in the Bullet section of the documentation [here](https://github.com/libgdx/libgdx/wiki/Bullet-Wrapper---Contact-callbacks) is an example.

**Comment by mgsx-dev** [comment]
yeah i made a PR to @xoppa blog about it recently : https://github.com/xoppa/xoppa.github.io/pull/5

Bullet 2 docs can be found here : https://github.com/TheJosh/bullet2

feel free to fix broken links int the wiki :-)

**Comment by edgarssilva** [comment]
I don't know what the previous link looked like and I don't what else It can be linked to maybe just the method doc? Not sure if that's usefull.
But if anything I would be happy to make thoose changes, never played around with open projects in github before :P

**Comment by mgsx-dev** [comment]
fixed, i found a mirror wiki on github
