### ISSUE TITLE
OpenAL Music Crashes on LWJGL3

### ISSUE THREAD

**Issue by noblemaster** [libgdx/libgdx#6450]
#### Issue details
Playing music on LWJGL3 crashes sometimes possibly due to synchronization issues. 

#### How to reproduce
Based on my assessment, it's possible for [OpenALMusic.fill(...)](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/OpenALMusic.java#L251) to be called from multiple threads causing a buffer exception if 2+ threads manipulate `tempBuffer` at the same time. Attached is a player-submitted crash report. An example would be calling `play` from a non-render thread while the render-thread updates the audio at the same time.

#### Proposed solution
Maybe the easiest solution is to simply make the method synchronized:
```
private synchronized boolean fill (int bufferID) {
  ...
}
```

#### Version of LibGDX and/or relevant dependencies
libGDX 1.9.14 with LWJGL 3.2.3
 
#### Stacktrace
```java
java.nio.BufferOverflowException
	at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:362)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALMusic.fill(OpenALMusic.java:269)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALMusic.update(OpenALMusic.java:237)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALLwjgl3Audio.update(OpenALLwjgl3Audio.java:250)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:133)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Desktop with LWJGL3

**Comment by mgsx-dev** [comment]
@noblemaster i don't think libGDX audio is thread safe at all, so i don't think it's a good idea to call it from other thread than GLThread.

**Comment by noblemaster** [comment]
It doesn't appear to be thread-safe at the moment at least on LWJGL3. I haven't had any problems so far on Android/iOS (although it looks the same for LWJGL.v2). 

Wasn't there a discussion to move audio out of the render-loop? I can't find it. Does everyone run the background music from the main thread for example? Also, it certainly would be better for performance to have audio on a separate thread besides the render-thread.

**Comment by mgsx-dev** [comment]
libGDX code not marked as "thread-safe" is not thread safe, maybe it works by miracle for some backends but you can't rely on this.

There are TODOs in the code about moving audio update to another thread but if we do so, that doesn't mean that it should be thread safe from user code (eg. user code calling play/stop from random threads).

Moving update (and fill) to a thread would be better for sure but i don't know how much gain we would have since you rarely play more than 2 music at once. Maybe we would need a bit of profiling/measurements to see if it worth it.

**Comment by noblemaster** [comment]
It's not just about render performance. I notice audio stutters when loading OpenGL assets. Those have to be passed in via render-thread and depending on image size, this can be a bit slow, causing slight audio stutters at times.

Based on this [LWJGL Thread](http://forum.lwjgl.org/index.php?topic=6084.0) OpenAL isn't restricted to the render-thread. From the libGDX point of view, I don't see any problems besides synchronizing the few functions properly.

This seems easy enough to move audio onto a separate thread in libGDX. I can do testing too on Windows/Mac. However, if everyone is happy how it is now, I'd rather not spend time on it.

**Comment by mgsx-dev** [comment]
@noblemaster ah yeah, you're right about the loading case. I'd be happy to have music update/fill in a separated thread.
+1 for that change.

**Comment by noblemaster** [comment]
Pull Request is here: https://github.com/libgdx/libgdx/pull/6452
