### ISSUE TITLE
iOS app displays in half width and height

### ISSUE THREAD

**Issue by JojoIce** [libgdx/libgdx#6453]
#### Issue details
libgdx v 1.9.12 - 1.9.15-SNAPSHOT will produce apps that renders in half width and half height on iOS devices.

#### Reproduction steps/code
Using latest liftoff, create for example the super-koalio app and deploy to an iOS device, and the game will render in the lower left quarter of the display. Touch input seems to be scaled to the rendered area, so touch at top right corner of screen is handled like a touch top right of the visible app (which is actually middle of the screen). It also clips the area so any graphics that would be rendered in any of the other quarters of the screen (like a sprite at the right/top edge of the screen) is not visible, and just background colour shows.

Using Gdx.graphics.getWidth() will indeed return 1/2 of the actual screen resolution.

Tested on iPhone 8 and iPad, with same result.

Using the liftoff generated project and setting gdx version to 1.9.11 will make it render normal.

#### Version of LibGDX and/or relevant dependencies
v 1.9.12 - 1.9.15-SNAPSHOT

#### Stacktrace
Everything executes normally, it is the rendering that is affected.

#### Please select the affected platforms
- [ ] Android
- [x] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by crykn** [comment]
Hey @JojoIce, that is intentional. The examples should be adapted accordingly.

The methods you should be using in this case are `Gdx.graphics.getBackBufferWidth()` & `getBackBufferHeight()`. Alternatively, use a viewport. Specifically for iOS, this was changed in 1.9.12, see the corresponding [changelog](https://libgdx.com/news/2020/10/gdx_1_9_12#breaking-changes). Or you can change the used HdpiMode in `1.9.15-SNAPSHOT` (#6366).

**Comment by JojoIce** [comment]
Hey @crykn! Thanks for the feedback!

I was trying to read the changelog and am still confused. Do we need to change how iOS apps are initiated as well. If you use liftoff with ios and the "classic" template (the gdx-setup one), you will have a very plain configuration, basically using new IOSApplicationConfiguration(). It seems like one should not have to configure something specific even if the app runs on different types of resolutions or?

The classic rendering code then looks like this:
`

	public void render() {
		Gdx.gl.glClearColor(1, 1, 1, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		batch.begin();
		batch.draw(image, 165, 180);
		batch.end();
	}
`

No complicated things or getters of size BUT on a norrowish iOS display, where the image will reach past the middle of the screen, the image will be clipped in the middle. See below (mostly white but wanted to use the plain classic template).

![IMG_3397](https://user-images.githubusercontent.com/3921475/111039928-06f64980-8431-11eb-9c34-d5f265232a9f.PNG)

See how only about half the image is displayed. I do not quite follow how the code should look like here to avoid the clipping.

Is it possible to find some documentation on how one should do from now on?

**Comment by obigu** [comment]
@JojoIce You should probably open an issue on Liftoff issue tracker, the official libGDX project setup app is Gdx-Setup (https://libgdx.com/dev/project-generation/)

**Comment by JojoIce** [comment]
Hi @obigu! If you go to the github page for gdx-setup you can read the following right at the top:
[gdx-setup](https://github.com/czyzby/gdx-setup)
`Please use gdx-liftoff instead, which is an updated fork of this project.`

That is why I named liftoff since it seems to be the way to do things, even though the gdx site hasn't really caught up it seems. (Ticket for update?). I really like liftoff and have tried to help with issues for iOS since that still needs some polishing as the dev doesn't have direct access to it. Otherwise it it looking to be a great improvement over gdx-setup and is actively developed as opposed to gdx-setup that has been dead for about 2 years.

I would imagine that exactly the same problem would appear if you use gdx-setup if you update project to 1.9.12+.

I already had created an issue on liftoff, but more so that maybe to drop the default gdx version to the last smoothly working for iOS. I think one aim for the setup tools is to let the user have a smooth start in creating new project, and if most of the templates that you can select in liftoff fail or behave in a very strange way, it will quite probably scare away any new person wanting to get into gdx development, which would be really sad, as liftoff otherwise really helps a nobie getting started.

The real problem seems to be with Libgdx in my view. A bugfix level release (depending on how you count releases) breaks many (most?) existing ios application and there is no clear way of how to fix them as it seems, so I really think this deserves to be a very open ticket! Either to "fix" or better explain migration to mere mortals.

But then again I cannot follow all the chatter after discussions move away from the forums, since it is almost impossible to jump in and find relevant information in discord and other feeds, so maybe it is just me who missed the obvious part, I don't know. 

Still this in ios project:

`
		return new IOSApplication(new GameStarter(), new IOSApplicationConfiguration());
`

followed by this in core

`

		batch.begin();
		batch.draw(image, 165, 180);
		batch.end();

`

That has worked since beginning of times and it no longer works in a very unexpected way. That should really be given a bit more attention than "replace getWidth() with getBackBufferWidth()", since none of that exist in the above code!

All work with gdx is generally stellar, but the above gave me many, many hours of confusion and I am still confused. Why does the code above clip the image? How do I (and all other) fix it? 

Maybe just un updated version of the "classic template" can be created and it will solve the issue quite easily?

**Comment by obigu** [comment]
The link you've posted is a fork. The official Gdx Setup tool from the link provided is part of the libGDX project (https://github.com/libgdx/libgdx/tree/master/extensions/gdx-setup) and is mantained to ensure it works with the most recent libGDX changes. 

For questions related to the recent iOS changes on hdpi screens, please use any of the dedicated channels like Discord (https://github.com/libgdx/libgdx/wiki/Getting-help).

**Comment by JojoIce** [comment]
OK, this is closed, but I anyway updated issue to state to use gdx-setup **or** liftoff, just to make it clear. Doesn't really matter. I guess I can create a new issue on the gdx-setup since you asked to open one on liftoff and they behave the same.
