### ISSUE TITLE
Wont Open

### ISSUE THREAD

**Issue by AdansWorkshop** [libgdx/libgdx#6458]
# Platform
Windows
# Issue
cmd cant access the gdx-setup_latest.jar file
# Attempts
I've done everything i can think of and it wont work

**Comment by yuripourre** [comment]
@AdansWorkshop When you have trouble, you can always downloaded from the [nightlies](https://libgdx.badlogicgames.com/ci/nightlies/dist/):

https://libgdx.badlogicgames.com/ci/nightlies/dist/gdx-setup.jar

**Comment by AdansWorkshop** [comment]
![Screenshot 2021-03-18 150336](https://user-images.githubusercontent.com/74674130/111682804-2b6c7000-87fb-11eb-9e9c-961416605f8e.png)
dont work

**Comment by yuripourre** [comment]
@AdansWorkshop can you please try `java -jar gdx-setup.jar`? 

Removing the `./` helps?

**Comment by AdansWorkshop** [comment]
it found the file but not the JAM. Thanks anyways for getting me one step closer

**Comment by mgsx-dev** [comment]
@AdansWorkshop please use discord if you have question instead : https://libgdx.com/community/discord/
