### ISSUE TITLE
TiledMap tile property "Type" doesn't get loaded

### ISSUE THREAD

**Issue by lyze237** [libgdx/libgdx#6464]
#### Issue details
The `Type` property on tiles gets skipped [during loading](https://github.com/libgdx/libgdx/blob/bc314368a18e0c916437f3dd7b4172714e6abf8b/gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java#L635) and therefore isn't available in libgdx.

![image](https://user-images.githubusercontent.com/11274700/111917908-a98e7800-8a82-11eb-849a-ac3244562c6b.png)

```xml
<tileset firstgid="1" name="Test" tilewidth="256" tileheight="256" tilecount="4" columns="0">
  <tile id="0" type="AAAA"> 
    <image width="32" height="32" source="Start.bmp"/>
```

#### Reproduction steps/code
* Create a new Tilemap in Tiled
* Add a Tileset
* Assign a Type on one of the Tiles
* Load the map into libgdx
* Type isn't available

![image](https://user-images.githubusercontent.com/11274700/111918003-35080900-8a83-11eb-96ea-df83d3921a9b.png)

#### Version of LibGDX and/or relevant dependencies
1.9.14

#### Please select the affected platforms
- [x] Android
- [x] iOS
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by mgsx-dev** [comment]
no need to create both an issue and a PR for the same thing ;-)
