### ISSUE TITLE
AndroidMusic Null Pointer onCompletion

### ISSUE THREAD

**Issue by jim808** [libgdx/libgdx#6477]
Please ensure you have given all the following requested information in your report.

#### Issue details
I noticed a NPE when running android in an emulator:

W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'void com.badlogic.gdx.audio.Music$OnCompletionListener.onCompletion(com.badlogic.gdx.audio.Music)' on a null object reference
        at com.badlogic.gdx.backends.android.AndroidMusic$1.run(AndroidMusic.java:198)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:464)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)

Here's the relevant code:

```
@Override
public void onCompletion (MediaPlayer mp) {
    if (onCompletionListener != null) {
        Gdx.app.postRunnable(new Runnable() {
            @Override
            public void run () {
                onCompletionListener.onCompletion(AndroidMusic.this);
            }
        });
    }
};
```

The null check at the beginning of the onCompletion method is fine, but you really need to check for null in the run() method.
Since run() is invoked later on a different thread, it could easily be the case that the listener is nullified before run() is executed.

For example:

```
@Override
public void onCompletion (MediaPlayer mp) {
    if (onCompletionListener != null) {
        Gdx.app.postRunnable(new Runnable() {
            @Override
            public void run () {
                if (onCompletionListener != null) {   // <-- need to check here.
                    onCompletionListener.onCompletion(AndroidMusic.this);
                }
            }
        });
    }
};
```

#### Reproduction steps/code
I'm not sure. I upgraded to libgdx 1.9.14 and fired up my game in the android emulator to see if there were any problems.  I noticed this stack trace in the console.  I don't know if I did anything special to make this happen, but that null check should still be added, in my opinion.

#### Version of LibGDX and/or relevant dependencies
1.9.14

#### Stacktrace
W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'void com.badlogic.gdx.audio.Music$OnCompletionListener.onCompletion(com.badlogic.gdx.audio.Music)' on a null object reference
        at com.badlogic.gdx.backends.android.AndroidMusic$1.run(AndroidMusic.java:198)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:464)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
```

#### Please select the affected platforms
- [x ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by obigu** [comment]
Good find, there's a null check missing there. Do you want to do the PR yourself?

**Comment by jim808** [comment]
Thanks!  Sorry, but I'm not really setup to the PR.

**Comment by obigu** [comment]
No problem, I've added the fix to https://github.com/libgdx/libgdx/pull/6472
