### ISSUE TITLE
Libgdx HTML project serialize problem

### ISSUE THREAD

**Issue by dDevTech** [libgdx/libgdx#6478]
Please ensure you have given all the following requested information in your report.

#### Issue details
I have a shared module i created to serialize to json oobjects by client (core) and a module server. With the server it works fine and desktop and android. But with the HTML when is compiling it dont detect that shared classes. What can I do?

#### Version of LibGDX and/or relevant dependencies
Last version

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [x] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by tommyettinger** [comment]
You probably need to add classes to your reflection cache; see here: https://github.com/libgdx/libgdx/wiki/Reflection#gwt . I am pretty sure you can add shared module classes to the reflection cache from the html module's .gwt.xml file, but it's also possible the shared module might benefit from its own .gwt.xml file, if it doesn't already have one.

**Comment by crykn** [comment]
If @tommyettinger's link doesn't help, please ask on our [Discord](https://libgdx.com/community/discord/) server, which is the appropriate channel for such questions.
