### ISSUE TITLE
Tiled 1.5 Parallax Layer Support

### ISSUE THREAD

**Issue by Quillraven** [libgdx/libgdx#6480]
This is not an issue, it is a question and if possible I would like to contribute.

The latest version of Tiled (1.5) officially support parallax scrolling: https://thorbjorn.itch.io/tiled/devlog/206681/parallax-scrolling-is-here

![image](https://user-images.githubusercontent.com/93260/113514538-79a99f00-956f-11eb-83fb-8c86af0a7127.png)

In my opinion it would be great if LibGDX supports that as well. Reading the property values is most likely not that difficult and could become part of the `TiledMapTileLayer` class or whatever it is called.

But maybe also the `TiledMapTileRenderer` should support it correctly? But how do you achieve the exact same result as in Tiled?

I personally always achieved a parallax effect by multiplying the camera position with a specific value to move that layer faster/slower, meaning that before rendering a layer I would modify the camera position temporarily, render the layer, and reset the camera position to its original values.

Is this the correct way to do it? What is the exact formula for the camera position modification because a simple "camera.position.x *= parallaxFactor.X" will most likely not be sufficient.

If someone could give me a little bit feedback I am happy to prepare a PR for it, if it is something useful.

What do you think?

**Comment by crykn** [comment]
Hey @Quillraven, as you have probably noticed by the lack of responses, there isn't really anyone in the team responsible for the whole tilemap stuff. There are also a bunch of other open issues/PRs related to tile maps which could use someone looking at them. 

If you still want to go ahead and create a PR for parallax support that would be appreciated, but you should be prepared that it might not be reviewed anytime soon. Nonetheless, general information on working from source can be found on the [official website](https://libgdx.com/dev/from-source/).

**Comment by Quillraven** [comment]
@crykn thank you for the response :) I am happy to help and will prepare a PR in the next couple of weeks but would be interesting for me to understand, what is a good approach for the parallax effect.

As mentioned, I always temporarily adjust the camera position but I am not sure if this is a good way to do it. If someone has an advice I appreciate it.

Otherwise, I will look in more detail into this topic and see what I can come up with.
