### ISSUE TITLE
Never ending deserialize

### ISSUE THREAD

**Issue by dDevTech** [libgdx/libgdx#6481]
Please ensure you have given all the following requested information in your report.

#### Issue details
Never ending deserialize 
Client send object to server correctly 
In server:
`
try {
					String str=new String(message.array(), "UTF-8");
					System.out.println(str);
					System.out.println("New object kk");
					o = new Json().fromJson(null, str);
					System.out.println("New object kk2");
				} catch (UnsupportedEncodingException e) {
					e.printStackTrace();
				}`
```
Console:
New object 2
java.nio.HeapByteBuffer[pos=0 lim=36 cap=36]
{class:"dDev.tech.SpaceLoader",x:15}
New object kk

As you can see never prints new object kk2

Class of Space Loader
`public class SpaceLoader {
    public  int x=0;

   /* public SpaceLoader(){
        x=6;

    }*/
    public SpaceLoader(int x){
        this.x=x;
    }


    public int getX() {
        return x;
    }

    public void setX(int x) {
        this.x = x;
    }
}`

EDIT: If i put the commented constructor it works. It's weird

#### Reproduction steps/code


#### Version of LibGDX and/or relevant dependencies
Last verison

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [ x] Android
- [x] iOS
- [x ] HTML/GWT
- [x ] Windows
- [ x] Linux
- [x ] MacOS

**Comment by tommyettinger** [comment]
OK, looking past the sloppy issue report, you tried to deserialize an object where the class did not have a zero-argument constructor. That's never been supported (by pretty much any automatic serialization library); the documentation on this is not great, but an exception should be thrown if you try to deserialize an object that can't be constructed: https://github.com/libgdx/libgdx/blob/c981d375463126f18f13a62e3aadd98da1b8352d/gdx/src/com/badlogic/gdx/utils/Json.java#L1220

I don't know why in your case that exception isn't thrown. I'm not sure why there's a HeapByteBuffer mentioned in the output, but it looks like it's from before the affected code. Saying the affected version of libGDX is "Last verison" only tells me that either a) you don't know what version you're using, or b) you know what version you're using and you're choosing to waste everyone's time. I'll assume it's the former; the libGDX version can be seen in any of: the External Dependencies part at the bottom of the Project view in IntelliJ IDEA or Android Studio, in either your root build.gradle or gradle.properties file (depending on how your project was created) as `gdxVersion`, or by running `gradlew core:dependencies`.

The infinite loop during deserialization may be a problem, but only because the case it happens should instead throw an exception, and the deserialization will never work without a zero-argument constructor.

I'm not closing this currently because @NathanSweet may want to know about this property of Json, and he may have an idea why the exception isn't handled.

**Comment by dDevTech** [comment]
Sorry for not writing the libgdx version but i think that is was not a bug and was a problem of my implementation. So i thought is was not relevant.
org.gradle.daemon=true
org.gradle.jvmargs=-Xms512M -Xmx1G -XX:MaxPermSize=1G -XX:MaxMetaspaceSize=1G
org.gradle.configureondemand=false
box2dlightsVersion=1.5
aiVersion=1.8.2
visUiVersion=1.4.9
shapeDrawerVersion=2.4.0
websocketSerializationVersion=1.9.10.3
websocketVersion=1.9.10.3
gdxVfxEffectsVersion=0.5.0
gdxVfxCoreVersion=0.5.0
gwtFrameworkVersion=2.8.2
gwtPluginVersion=1.0.13
androidPluginVersion=4.0.2
robovmVersion=2.3.12
gdxVersion=1.9.13
gdxPayVersion = 1.3.1

**Comment by NathanSweet** [comment]
For me to take a look, you'll need to provide code that I can copy/paste and run to see the problem.

**Comment by dDevTech** [comment]
Ok

**Comment by dDevTech** [comment]
In websocket client
`@Override
    public void create() {
        super.create();
        WebSocket socket = WebSockets.newSocket(WebSockets.toWebSocketUrl("localhost",25001));
        System.out.println("Created");
        Gdx.app.setLogLevel(Application.LOG_INFO);
        socket.addListener(new AbstractWebSocketListener() {
            @Override
            public boolean onOpen(WebSocket webSocket) {
                Gdx.app.log("INFO SERVER","Connected to server");
                webSocket.send("hola");
                webSocket.send(new SpaceLoader(5));
                return false;
            }

            @Override
            protected boolean onMessage(WebSocket webSocket, Object packet) throws WebSocketException {
                return false;
            }
        });
        socket.setSerializer(new JsonSerializer());
        socket.connect();

    }
`



Server
`public class ServerLauncher {
	public static void main(String[] args) {
		// TODO Implement server application.
		Connection conn =null;
		Properties connectionProps = new Properties();
		connectionProps.put("user", "root");
		connectionProps.put("password", "XXXX");
		try {
			conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/spacegame",connectionProps.getProperty("user"),connectionProps.getProperty("password"));


		} catch (SQLException throwables) {
			throwables.printStackTrace();
		}
		if(conn!=null){
			System.out.println("Connected to database");
		}
		System.out.println("Server running");
		WebSocketServer server = new WebSocketServer(new InetSocketAddress("localhost",25001)) {

			@Override
			public ServerHandshakeBuilder onWebsocketHandshakeReceivedAsServer(WebSocket conn, Draft draft, ClientHandshake request) throws InvalidDataException {
				System.out.println("Status: "+conn.getReadyState());
				ServerHandshakeBuilder builder = super
						.onWebsocketHandshakeReceivedAsServer(conn, draft, request);
				return builder;
			}

			@Override
			public void onOpen(WebSocket conn, ClientHandshake handshake) {
				System.out.println("Openned connection");

				System.out.println(handshake.getResourceDescriptor());
				for (Iterator<String> it = handshake.iterateHttpFields(); it.hasNext(); ) {
					String s = it.next();
					System.out.println(s+"-> "+handshake.getFieldValue(s));

				}

			}

			@Override
			public void onClose(WebSocket conn, int code, String reason, boolean remote) {

			}

			@Override
			public void onMessage(WebSocket conn, String message) {
				System.out.println("new messsage");
			}

			@Override
			public void onMessage(WebSocket conn, ByteBuffer message) {
				System.out.println("New object");
				Serializer s=new JsonSerializer();
				System.out.println("New object 2");
				System.out.println(message);
				Object o = null;
				try {
					String str=new String(message.array(), "UTF-8");
					System.out.println(str);
					System.out.println("New object kk");
					o = new Json().fromJson(null, str);
					System.out.println("New object kk2");
				} catch (UnsupportedEncodingException e) {
					e.printStackTrace();
				}
				System.out.println("New object 3");
				System.out.println(o.getClass());
				if(o instanceof SpaceLoader){
					System.out.println(((SpaceLoader)o).x);
				}

				Json json = new Json();
				String str=json.prettyPrint(o);
				System.out.println(str);

			}

			@Override
			public void onError(WebSocket conn, Exception ex) {

			}

			@Override
			public void onStart() {

			}
		};

		server.run();

	}
}`

I know my code is a mess but is just for testing purposes before I start to develop my planned game

**Comment by lyze237** [comment]
And the most important part, what's the json?

**Comment by dDevTech** [comment]
`package dDev.tech.serialized;



public class SpaceLoader {
    public  int x=0;

    public SpaceLoader(int x){
        this.x=x;

    }


}
`

**Comment by dDevTech** [comment]
What is the problem with the code with '' how do you attach code in gihub>?

**Comment by dDevTech** [comment]
If you have intellij i can share my project if you want

**Comment by lyze237** [comment]
3 ticks for block codes: https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code

E.g:
\```java
public SpaceLoader(int x){
    this.x=x;
}
\```

**Comment by dDevTech** [comment]
```
package dDev.tech.serialized;



public class SpaceLoader {
    public  int x=0;

    public SpaceLoader(int x){
        this.x=x;

    }


}
```

**Comment by dDevTech** [comment]
```java
package dDev.tech.serialized;



public class SpaceLoader {
    public  int x=0;

    public SpaceLoader(int x){
        this.x=x;

    }


}
```

**Comment by tommyettinger** [comment]
You can also edit your previous messages, if you want, to change the single ` to the three; you wouldn't need to post new messages. I'm somewhat wondering if this might be related to creating so many Json parsers.

**Comment by dDevTech** [comment]
Do you want i share my project with intellij collaboration system?

**Comment by tommyettinger** [comment]
It looks like you're using some kind of user/password authentication and I'd double-check that none of your passwords are in anything you share publicly, but sure, a whole project might help. I would probably copy your project, remove any build folders from the copy (because they are large), and zip up the copy so you can just upload it to a Github comment.

**Comment by dDevTech** [comment]
That is not the problem. I added later that code

**Comment by dDevTech** [comment]
I insist, do you want i share the intellij project

**Comment by dDevTech** [comment]
https://code-with-me.jetbrains.com/BesQvRm2nGK5rNyEpDjOGw#p=IU&fp=A004DA964337E050348DF2F77C623CCDD3AA3BC45EED59EE52CA4BDA340DDE44

**Comment by tommyettinger** [comment]
I don't think I'm going to be able to anything but verify that the infinite loop is there. Maybe I could debug it.

**Comment by dDevTech** [comment]
Yes you will be able. You will be able to see the same project as me and i will give access to you to everytool (its just a test project)

**Comment by dDevTech** [comment]
UPDATE: Know it is magically working. I dont know why.

But i come with another issue:
Referring to the serialize topic. I see another problem/bug
When I am using this:
```java
String s=new JsonSerializer().serializeAsString(new SpaceLoader());
```

With the space loader class:
```java
public class SpaceLoader {
    public  int x=0;
    private String hi="tete";

    public SpaceLoader(){

    }
    public SpaceLoader(int x){
        this.x=x;


    }


}

```
The output doesnt print the x and hi variables:
```{class:"dDev.tech.serialized.SpaceLoader"}````


However if i use the SpaceLoader(int x) constructor and not the default one, it prints the x value. `
````java 
  String s=new JsonSerializer().serializeAsString(new SpaceLoader(5));```
```{class:"dDev.tech.serialized.SpaceLoader",x:5}```

**Comment by dDevTech** [comment]
UPDATE: the previous problem was magically solver.
However I came up with another bug/problem:
This is my serializable class
```java
public class SpaceLoader {
    public  int x=0;
    private String hi="tete";

    public SpaceLoader(){

    }
    public SpaceLoader(int x){
        this.x=x;


    }


}
```
If I use:
 String s=new JsonSerializer().serializeAsString(new SpaceLoader());
 It prints: {class:"dDev.tech.serialized.SpaceLoader"}

However if I use the int constructor and not the default
 String s=new JsonSerializer().serializeAsString(new SpaceLoader(5));
 It prints: {class:"dDev.tech.serialized.SpaceLoader",x:5}


This is strange, right?

**Comment by Tom-Ski** [comment]
That is completely expected, you are using different constructors that populate the fields with different values, so the serialized representation of those instances would be different. 

I suggest you use the discord if you need assistance, this is an issue tracker. 

https://github.com/libgdx/libgdx/wiki/Getting-help
