### ISSUE TITLE
Scale and Size Actions do not effect Label

### ISSUE THREAD

**Issue by haz8989** [libgdx/libgdx#6490]
#### Issue details
The following `Action`s do not effect the `Label` Actor
- `ScaleByAction`, `ScaleToAction`, `SizeByAction`, `SizeToAction`

#### Reproduction steps/code
This is because the respective methods in the Label class actually have no visual effect,
You have to use `Lable.setFontScale()`

#### Solutions:
- add extra actions such as: `FontScaleByAction`
- Edit Label.setScale() so it changes the font scale?

#### Please select the affected platforms
- [X] Android
- [X] iOS
- [X] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by haz8989** [comment]
#### Temporary Workaround
```kotlin
class FontScaleToAction : ScaleToAction() {

    override fun update(percent: Float) {
        super.update(percent)
        if (target is Label) {
            (target as Label).setFontScale(target.scaleX, target.scaleY)
        }
    }
    
}
```

**Comment by haz8989** [comment]
Could this be due to the fact that the Label is inside a `Table`?

**Comment by NathanSweet** [comment]
You need to enable transform:
https://github.com/libgdx/libgdx/wiki/Scene2d.ui#rotation-and-scale
I don't remember off the top of my head, but may need to put the label in a container, as described there.
