### ISSUE TITLE
Support layer tint color for TiledMap 

### ISSUE THREAD

**Issue by thcrock** [libgdx/libgdx#6503]
Tiled, in version 1.4, added an option called Tint Color ( https://doc.mapeditor.org/en/stable/manual/layers/#tinting-layers ). This allows mapmakers to add a color that is multiplied into all tiles in the layer. Supporting this would be useful in libgdx.

It is stored as an attribute on the layer, not as a property, so both the map loader and renderers need to be made aware of it. As far as I can tell, the implementation as it's done within the Tiled editor itself would be as easy as multiplying by this tint color in this line in each renderer: https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/maps/tiled/renderers/OrthogonalTiledMapRenderer.java#L69

I haven't tested this out yet but that's the first thing I'm going to try. I plan on opening a PR when I get around to this but I wanted to open this issue to track it and give anybody the chance to weigh in before I do so.

**Comment by tommyettinger** [comment]
It might make sense to change MapLayer's internal `opacity` float to be a full tint `Color`, using the Color's alpha as the actual opacity in the getter and setter. This would avoid an odd duplication of alpha variables, unless that duplication is also present in Tiled. It does seem useful to be able to tint layers.

(I don't currently use Tiled, so feel free to disregard any suggestions I make.)

**Comment by thcrock** [comment]
The duplication seems to be present in Tiled. There is an opacity float and a tint color, and they appear to be combined with multiplication within the editor.

The original author of the tint color PR did propose replacing the (older) opacity option with tint, but that's not how it's implemented as of now.  You can read the original discussion if interested: https://github.com/mapeditor/tiled/issues/2683

**Comment by SimonIT** [comment]
Implemented by #7076
