### ISSUE TITLE
GL20.GL_SCISSOR_TEST does not work correctly on iOS

### ISSUE THREAD

**Issue by clydebarrow** [libgdx/libgdx#6511]
#### Issue details
Using 
````
        Gdx.gl.glEnable(GL20.GL_SCISSOR_TEST);
        Gdx.gl.glScissor(x, y, width, height);
````
results in an incorrect region being clipped in GDX 1.9.13 and 1.10.0 on iOS. It works correctly in 1.9.5 on iOS, and correctly on Android with 1.10.0.

#### Reproduction steps/code
Create a bare-bones GDX project and use this code for the `ApplicationAdapter`:
````
package com.mygdx.game;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.glutils.ShapeRenderer;


public class MyGdxGame extends ApplicationAdapter {
    SpriteBatch batch;
    Texture img;
    int width = 0, height = 0;
    ShapeRenderer sr;

    @Override
    public void create () {
        batch = new SpriteBatch();
        img = new Texture("badlogic.jpg");
        sr = new ShapeRenderer();
    }

    @Override
    public void resize(int width, int height) {
        this.width = width;
        this.height = height;
    }

    @Override
    public void render () {
        batch.begin();
        batch.draw(img, 0, 0);
        batch.end();
        Gdx.gl.glEnable(GL20.GL_SCISSOR_TEST);
        Gdx.gl.glScissor(0, 0, width, height);
        sr.begin(ShapeRenderer.ShapeType.Filled);
        sr.setColor(Color.YELLOW);
        sr.rect(0, 0, width, height);
        sr.end();
        Gdx.gl.glDisable(GL20.GL_SCISSOR_TEST);
    }

    @Override
    public void dispose () {
        batch.dispose();
        img.dispose();
    }
}
````

Run this on iOS. It should show the entire screen as yellow. With the failing versions either there is no yellow, or only part of the screen is yellow (varies randomly.)

The result is the same on either simulator or device.

#### Version of LibGDX and/or relevant dependencies
* 1.10.0: Fails on iOS
* 1.9.14: Will not build for iOS (duplicate symbols at link time)
* 1.9.13: Fails on iOS
* 1.9.5: Works correctly

Other versions were not tested.

#### Please select the affected platforms
- [ ] Android
- [x] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

![Screenshot 2021-04-27 at 10 19 46 am](https://user-images.githubusercontent.com/2366188/116167772-532ced00-a744-11eb-888f-fd97aadd71c9.png)

**Comment by obigu** [comment]
`glViewport()` and `glScissor()` expect backbuffer coordinates. Logical coordinates are default since libGDX 1.9.12. Recommended solution would be to use `HdpiUtils.glScissor`. Alternatively you can configure the iOS backend to use backbuffer coordinates by setting `IosApplicationConfiguration` `hdpiMode` to `Physical`.

**Comment by clydebarrow** [comment]
A patch-level release introduced a silently breaking API change? Ouch.

`HdpiUtils.glScissor` is at least an easy fix, but a deprecation notice or other warning would have saved me several hours work.

Are there any other landmines I'm likely to stumble over?

**Comment by obigu** [comment]
I understand the furstration. Versioning has not been great in the past. At least the `CHANGES` file now tags Breaking changes but future release should have better versioning in any case. Notifications on changes between versions have also improved with detailed posts on the new website (that expand on the `CHANGES` info). No deprecation needed in this case though, it's a change of default behaviour.
