### ISSUE TITLE
LibGDX app renders incorrectly on iOS after device rotation

### ISSUE THREAD

**Issue by clydebarrow** [libgdx/libgdx#6514]
Please ensure you have given all the following requested information in your report.

#### Issue details
LibGDX app renders incorrectly on iOS after device rotation

#### Reproduction steps
Create a boilerplate LibGDX app, ensure that the Info.plist.xml file permits all device orientations.

Capture screen size in `resize()`. Do some drawing in `render()` that is dependent on the aspect ratio of the screen. Check that the result is the same if the app is started in portrait vs starting in landscape then rotating to portrait.

#### Code
````
public class MyGdxGame extends ApplicationAdapter {
    int width = 0, height = 0;
    ShapeRenderer sr;

    @Override
    public void create() {
        super.create();
        sr = new ShapeRenderer();
    }

    @Override
    public void resize(int width, int height) {
        super.resize(width, height);
        this.width = width;
        this.height = height;
    }

    @Override
    public void render () {
        super.render();
        Gdx.gl.glClearColor(0.6f, 0.1f, 0.1f, 1f);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        sr.begin(ShapeRenderer.ShapeType.Filled);
        sr.setColor(Color.YELLOW);
        sr.rect(width/4f, height/4f, width/2f, height/2f);
        sr.end();
    }

    @Override
    public void dispose () {
        super.dispose();
        sr.dispose();
    }
}
````
#### Version of LibGDX and/or relevant dependencies
Tested with 1.9.5 and 1.10.0 - same results

#### Expected result

There should be no difference in the display whether the app starts in one orientation then rotates, vs starting in the final orientation.

#### Actual result

As expected on Android. Not as expected on iOS. Although `resize()` is called correctly with the new screen size, the image drawn is wrong, as though the backend is unaware of the rotation.

#### Please select the affected platforms
- [ ] Android
- [X] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

#### Screenshots

![gdx](https://user-images.githubusercontent.com/2366188/116491598-98385700-a8dd-11eb-8970-2b9ca99913d3.jpg)

**Comment by tommyettinger** [comment]
I'm not at all knowledgeable about iOS, but your example doesn't use a Viewport (unless ShapeRenderer uses one internally). There have been some issues noted about iOS apps without a viewport, that are hard to reproduce in actual games because almost all games wind up using a Viewport. I think the default behavior is to stretch a fixed-size region of the screen to fit the window or rotated-screen size. This does look like a bug, but it may just be a bug in the default iOS Launcher, or it may be fixed as soon as a Viewport is introduced.

**Comment by obigu** [comment]
Yeah, @tommyettinger is right,`glViewport()` is not being called on device rotation which is not necessary when using a Viewport, that's a bug. You can workaround calling it on `resize()` (use `HdpiUtils.glViewport(0, 0, width, height)`). 

Independently from that, if you want the rectangle to have the same shape on both orientations you need to update the projection matrix of the `ShapeRenderer`:

```
matrix.setToOrtho2D(0, 0, Gdx.app.getGraphics().getWidth(), Gdx.app.getGraphics().getHeight());				
sr.setProjectionMatrix(matrix);
```

**Comment by Tom-Ski** [comment]
Its due to to the changes here https://github.com/libgdx/libgdx/issues/6453 as ShapeRenderer by default uses a 2d ortho projection that uses getWidth and getHeight instead of backbuffer width/height.

Changing this projection yourself, or using the config to 'restore' the previous behavior would fix this. (You' re also not updating the projection matrix in the resize method in your sample which is a point of error too). 

That said, ShapeRenderer should probably use backbuffer methods by default, but we are not doing that in other places like SpriteBatch.

**Comment by clydebarrow** [comment]
I did look at the Viewport docs, but my eyes glazed over with the other topics (like Camera) that apparently needed to be covered to figure out how to use one. If you have some simple boilerplate to implement a Viewport that maps 1:1 to the screen that would be helpful.

In any case it sure seems like a bug - the fact that it works correctly on Android reinforces that notion.

**Comment by Tom-Ski** [comment]
> I did look at the Viewport docs, but my eyes glazed over with the other topics (like Camera) that apparently needed to be covered to figure out how to use one. If you have some simple boilerplate to implement a Viewport that maps 1:1 to the screen that would be helpful.
> 
> In any case it sure seems like a bug - the fact that it works correctly on Android reinforces that notion.

https://github.com/libgdx/libgdx/blob/305be140b7fd6087b92b6ded24564454a1c11f68/tests/gdx-tests/src/com/badlogic/gdx/tests/ViewportTest1.java 
ScreenViewport for 1:1, the wiki also has a good article that goes over the different ones

**Comment by obigu** [comment]
> Its due to to the changes here #6453 as ShapeRenderer by default uses a 2d ortho projection that uses getWidth and getHeight instead of backbuffer width/height.
> 

I think that's not the issue, the problem reproduces on older libGDX versions, it has to do with the fact that `IOSGraphics` doesn't call `glViewport()` on rotation as it should.

**Comment by clydebarrow** [comment]
> You can workaround calling it on `resize()` (use `HdpiUtils.glViewport(0, 0, width, height)`).

Yes, that fixes the behaviour, thanks.
