### ISSUE TITLE
X and Y offset of bitmapfonts does not work for single-character strings.

### ISSUE THREAD

**Issue by Bjohnson131** [libgdx/libgdx#6519]
Please ensure you have given all the following requested information in your report.

#### Issue details
In bitmapFont.java, lines 850-854 (https://github.com/libgdx/libgdx/blob/e60a3937d31670602d5cdf3aca1ccffc7b7b08f9/gdx/src/com/badlogic/gdx/graphics/g2d/BitmapFont.java#L850-L853), the xAdvances of a string are set.  If the string only consists of one character, however, the offset isn't applied properly. This is improper for the kerning of characters, and how they should appear relative to input coordinates.

For example, here is a box printed using the box-drawing characters in single-string characters:
![Image of bug](https://camo.githubusercontent.com/05636aac062fecd6beb6cf6ef2ddf85d8345b7947c13f117f163d83133b7c331/68747470733a2f2f692e696d6775722e636f6d2f6372454c4b36452e706e67)

#### Reproduction steps/code
https://gist.github.com/Bjohnson131/3686d7461dc3a4d85dca560bfe812455

#### Version of LibGDX and/or relevant dependencies
Master as of 5/4/21

#### Stacktrace
N/A

#### Please select the affected platforms
 All / platform agnostic.
- [x] Android
- [x] iOS
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by Bjohnson131** [comment]
The workaround for this bug is to print a no-break space (a special space character that is in the quotes: " "), which will bypass the check and allow the text to be printed properly.

**Comment by tommyettinger** [comment]
Are you setting the chars you use in the font to be fixed-width? That is, with `bmpFont.setFixedWidthGlyphs(String);` . This is mentioned in the linked code, as `isFixed`, and generally fixed-width implies there is no kerning in the font. There is a complex bug in Hiero that affects the creation of fixed-width fonts with the Java renderer, but Hiero's FreeType renderer should make fixed-width fonts correctly. There's also alternatives like the original AngelCode BMFont tool.

**Comment by Bjohnson131** [comment]
I'm using the angelcode exporter. 

You're right in that I think setting the characters to fixed width may fix the issue, but when I have 3400 code points, it becomes impractical. That said, I've tried it with the box-drawing chars only, and I didn't notice a difference.

**Comment by tommyettinger** [comment]
I use cmapToFile when I need to generate all the code points in a font, though it will be a pain to track down the actual site again. It probably isn't too hard to write this type of application for someone already familiar with the internals of the TTF format.. but I don't know any of those people... So here's the zipped .exe : [cmaptofile.zip](https://github.com/libgdx/libgdx/files/6425364/cmaptofile.zip) On windows, you can drag and drop a .ttf font onto this and it will place a .txt file next to it with all glyphs. You can possibly just read that file in as a String with FileHandle, and pass that to setFixedWidthGlyphs(). I have no real idea on the licensing of cmaptofile other than it isn't linked with or distributed with your game, and it was on a personal site that basically dumped utilities that person had made.

**Comment by Bjohnson131** [comment]
> You can possibly just read that file in as a String with FileHandle, and pass that to setFixedWidthGlyphs()

Oh boy! This one's gonna be a funny-looking PR. 😆 

Also: Updated original post with some code to help reproduce the bug. You'll need a bitmap font to plug into it, but it creates a beautiful color spread.

**Comment by tommyettinger** [comment]
I ran your code, only changing the font for a monospaced one I had available:
![java_IWbutXZCyT](https://user-images.githubusercontent.com/160684/117107981-5f620d00-ad37-11eb-838e-aa7be47a0761.png)
Doesn't seem to be a problem here, with a different font. This appears to be a font configuration issue. My code changes to make your repro code runnable are here: https://github.com/yellowstonegames/SquidLib/blob/master/squidlib/src/test/java/squidpony/gdx/tests/issues/Issue6519.java (I don't actually use SquidLib there, just the assets for the font and the LWJGL3 test dependency.)

**Comment by tommyettinger** [comment]
So, I was able to get the full font fixed-width using no external dependencies. It looks like 
![java_3BAE4q9vVz](https://user-images.githubusercontent.com/160684/117109291-478b8880-ad39-11eb-95b9-a227d3433831.png) now. The code I used is:
```java
        public static void setAllFixedWidth(BitmapFont font) {
            BitmapFont.BitmapFontData data = font.getData();
            int maxAdvance = 0;
            for (int index = 0, end = 65536; index < end; index++) {
                BitmapFont.Glyph g = data.getGlyph((char) index);
                if (g != null && g.xadvance > maxAdvance) maxAdvance = g.xadvance;
            }
            for (int index = 0, end = 65536; index < end; index++) {
                BitmapFont.Glyph g = data.getGlyph((char) index);
                if (g == null) continue;
                g.xoffset += (maxAdvance - g.xadvance) / 2;
                g.xadvance = maxAdvance;
                g.kerning = null;
                g.fixedWidth = true;
            }
        }
```
It simply does what setFixedWidthGlyphs(CharSequence) does, but for all of the Unicode BMP (every Java `char`, ignoring any that aren't in the font).

**Comment by tommyettinger** [comment]
OK, what we've found so far is (I think) documented a little better at https://github.com/libgdx/libgdx/wiki/Bitmap-fonts#fixed-width-fonts . Closing, thanks for this colorful journey through the magical world of fonts.
