### ISSUE TITLE
Websocket GWT support

### ISSUE THREAD

**Issue by ange-black69** [libgdx/libgdx#6530]
Hello everyone,
I create a multiplayer game and my server is using TooTallNate/Java-WebSocket server side and it worked great
As for now my client used czyzby/websocket and it worked great at least for client, because when I try to use it on gwt, after correctly loading the modules in the xml and iniate the gwt factory, I got a error message "unable to send packet"... 
So as far as I see, the project was abandonned, So I just wanted to know which websocket library is working and updated for libgdx GWT implementation ?
I try right now to make TooTallNate/Java-WebSocket 's version working at least for desktop but can he run on GWT ?
if yes how ?
Thank you for your help !

**Comment by tommyettinger** [comment]
You probably want https://github.com/MrStahlfelge/gdx-websockets , which is an updated fork of czyzby's websocket library.

In the future, there's [the official Discord server](https://discord.gg/Tje9EbwUhe) where you are more likely to receive answers to questions like this.
