### ISSUE TITLE
The ImGui wiki page is not linked on the Wiki home page

### ISSUE THREAD

**Issue by Amityville-DE** [libgdx/libgdx#6532]
The ImGui wiki page (https://github.com/libgdx/libgdx/wiki/ImGui) is not linked on the Home wiki page (https://github.com/libgdx/libgdx/wiki), only in the TOC.

The ImGui link should be added to the wiki Home page for consistency.

**Comment by crykn** [comment]
That sounds like a good idea! While doing this, I think we should also consider merging the [ImGUI](https://github.com/libgdx/libgdx/wiki/ImGui) page and the (considerably more recent) [ImGui Bindings And 3D Graphics](https://github.com/libgdx/libgdx/wiki/ImGui-Bindings-And-3D-Graphics) page.

**Comment by Amityville-DE** [comment]
Maybe it should also be mentioned that:
https://github.com/libgdx/libgdx/wiki/ImGui-Bindings-And-3D-Graphics
and
https://github.com/libgdx/libgdx/wiki/ImGui
are referencing two different ImGui ports?
https://github.com/SpaiR/imgui-java
https://github.com/kotlin-graphics/imgui

**Comment by crykn** [comment]
Done, see [here](https://github.com/libgdx/libgdx/wiki/ImGui).
