### ISSUE TITLE
JavaDocs: Expired Url

### ISSUE THREAD

**Issue by haz8989** [libgdx/libgdx#6538]
There is an old url on this page
https://libgdx.badlogicgames.com/ci/nightlies/docs/api/com/badlogic/gdx/graphics/g2d/ParticleEffect.html

**Comment by crykn** [comment]
I replaced it with a link to the archived version of the blog post. If we want to replace it with the wiki link (https://github.com/libgdx/libgdx/wiki/2D-ParticleEffects), we should first make sure that it contains all the old information as well.
