### ISSUE TITLE
Ghosting when dragged a scaled "window" actor

### ISSUE THREAD

**Issue by chrisplak71** [libgdx/libgdx#6540]
Please ensure you have given all the following requested information in your report.

#### Issue details
There are 2 separate issues.  Not sure if they are related, but I believe they are.

(1) I have a very simple Stage where I create 2 movable "actor" windows.  One of the windows has .setScale set to 0.5f.  When I drag that window around it creates a ghost/shadow of itself.  Dragging the other window has no issue.    The more I drag the window, especially if I drag it in a circle, the distance between the ghosted version of the window grows.   

(2) If you attempt to drag the small window to the upper right hand corner it is not allowed to.  Not sure how else to describe it other than you cannot drag the small scaled window to the upper right corner of the app.

#### Reproduction steps/code
The attached code will reproduce the problem.  In addition I put up a 20 second clip on youtube.  Here is the link  https://youtu.be/bzRSY8IJeOw

#### Version of LibGDX and/or relevant dependencies
gdxVersion = '1.9.14'

#### Stacktrace
Not relevant

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [X ] Windows
- [ ] Linux
- [ ] MacOS

And here is the sample code.  The UI skin used is the default that ships with libgdx

package com.mygdx.game;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Skin;
import com.badlogic.gdx.scenes.scene2d.ui.TextButton;
import com.badlogic.gdx.scenes.scene2d.ui.Window;
import com.badlogic.gdx.utils.viewport.FitViewport;

public class MyGdxGame extends ApplicationAdapter {
    Stage stage;
    Skin skin;
    Window window, window2;

    @Override
    public void create() {
        stage = new Stage(new FitViewport(300,300));
        skin = new Skin(Gdx.files.internal("default_skin/uiskin.json"));

        window = createWindow(25,50);
        stage.addActor(window);

        window2 = createWindow(125,150);
        window2.setScale(1f / 2f);
        stage.addActor(window2);

        Gdx.input.setInputProcessor(stage);
    }

    public Window createWindow(float x, float y) {
        Window wnd;

        wnd = new Window("Debug Dialog", skin);
        wnd.getTitleTable().add(new TextButton("X", skin)).height(wnd.getPadTop());
        wnd.row();
        wnd.add("mx:");
        wnd.row();
        wnd.add("my:");
        wnd.setMovable(true);
        wnd.setTransform(true);
        wnd.setPosition(x,y);
        wnd.pack();

        return wnd;
    }

    @Override
    public void render() {
        Gdx.gl.glClearColor(1, 0, 0, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

        stage.act();
        stage.draw();
    }

    @Override
    public void dispose() {

    }
}

**Comment by chrisplak71** [comment]
Thanks for responding.  What you said makes sense and it works in that I don't get ghosting and the window successfully can be moved to the borders.  But.......

So there is no way to scale an actor?   The reason I want to scale is if I run my app on one phone that is 852x480 and a low pixel density and then on another that is 1920x1080 with a very high density I have very different sized "window" actors.  I want these actors to be approximately sizes (identical would be ideal).   It seemed like setScale was the solution.  By changing the size, it graphically takes up the same space but now the layout of the elements within that "window" are completely different.  When I did setScale everything looked like it was supposed to, but dragging and boundaries were broken.  

Is there any way to make an actor with fixed content (say 10 labels) a consistent size across multiple device resolutions and pixel densities?

Side question - I guess the purpose of setScale is only for static items?

**Comment by isoteriksoftware** [comment]
What you need is a **Viewport**. Instead of using fixed scale, let the viewport do the scaling for you. It will automatically adjust the scales of actors depending on the screen size (or density).

Choose a target resolution (like 1920x1080), then use that to create an appropriate viewport. I said **appropriate** here because there are different built-in viewports and they work differently. It is your responsibility to size your actors to look good on your target resolution, then the viewport will decide how it looks on other resolutions (depending on the type of viewport you use).

And yes, `setScale()` makes static changes, the scale your pass will be used as a fixed scale unless you change it later, it will automatically adjust at runtime unless you use a viewport. Also note that the viewport will work with any fixed scale that you set, so if you want everything to be controlled by the viewport only, don't bother setting the scale yourself.

**Comment by chrisplak71** [comment]
I actually am using a ExtendViewport, and using a viewport is the source of the problem.  From the libgdx wiki (https://github.com/libgdx/libgdx/wiki/Viewports) they state that you have to use setScale.  Before I started using a viewport everything was fine, but then I ran into display problems on different devices - exactly what viewport was designed to fix.


(Copied from the wiki)
```
then set the size of the actors using the 2 lines

   //****SETTING ACTORS SIZE****//
   //When using FitViewport in Stage,  the actors can be scaled really large.  The below allows you to rescale it to
   //more visual appealling.
   final float scaleValue = 1f/3.5f;//set this to whatever you want
   gameButton.setTransform(true);
   gameButton.setScale(scaleValue);

```
The easiest way for you to see this is to set the application w/h to 1920x1080 and your viewport to, say 192x108 (1/10th of the screen size).  In DesktopLauncher, depending on lwjgl version use one of the following 		
//lwjgl3 config.setWindowedMode(APP_WIDTH, APP_HEIGHT);
or 
//lwjgl2		config.width = 1920;
//lwjgl2		config.height = 1080;

Then set your viewport to 192x108.  Now your "window" actors are HUGE - 10x larger to be exact.  If you now set the scale factor to 1/10 on that window actor it shows as it is supposed to do.  

The wiki specifically mentions FitViewport as being a problem, but the "scaled really large" happens with any viewport other than ScreenViewport.  I would really prefer to not to use a ScreenViewport as that completely negates having World Coordinates. 


Summarizing, and this is why I filed the bug.  
1) If you are using an actor....
2) If viewport does not match screen size then your actor will be drawn at an incorrect scaling.
3) The wiki says to use setScale to fix this.
4) But using setScale causes drawing problems (the ghosting) and screen edge detection (not able to move window to full width of app)

**Comment by isoteriksoftware** [comment]
Alright. I hope a contributor sees this soon enough and fix the bug. For the time being, you can try using an older version of libGDX and see if the big persists or not.

**Comment by mgsx-dev** [comment]
@chrisplak71 i think you get misguided by this wiki paragraph. Actor scale shouldn't be used to "fix" viewport setting. (we'll probably remove it)

> Then set your viewport to 192x108. Now your "window" actors are HUGE - 10x larger to be exact.

This is actually how some viewports (eg. FitViewport) works : you define a virtual area (192x108) and everything will be scaled to match the screen whatever the real screen size is. If this virtual zone is too small for your actors, that mean you need a bigger one.

**Comment by mgsx-dev** [comment]
FYI i removed the wiki paragraph.

**Comment by chrisplak71** [comment]
It is not just FitViewport that has the problem.  It is any viewport (other than screen viewport).  In the example I posted, just change the app size to 1920x1080 and the viewport size to 192x108.  Then try the different viewports.  You'll see in all situations that the actor his 10x larger (except for screenviewport).  It is also not just a "window" actor.  It is any actor.  

Does that mean then that the viewport size should ALWAYS be the exact same as the screen size if we are attempting to use actors?  For items like fonts and sprites I can apply my scaling factor and it works.  For actors I cannot.

While I used an exaggarated scaling factor of 1/10.  Even a simple slight aspect change would result in odd and inconsistent stretching of the actors, ie viewport of 1920x1080 to display size of 2088x1154.

I guess I'm missing something here.  My understanding is that the viewport world size should have nothing to do with the display size (until final rendering).  It sounds like this is only true for my internal code.  If  I use any of the built in actors/stage then it won't work.  Let me ask it another way, are there features of libgdx that "do the right thing" based upon the world size?  


(I'm sorry, I'm struggling and trying to ask the question more clearly).

Let me ask it this way.  What is the purpose of having an "Actor" that is unusable in in any viewport (other than screenviewport)?  I thought the purpose of the viewport was so that I could work in my units.  Are you saying that when using any of the libgdx features, that I either (a) must scale everything from world to display size or (b) I have to also have a screenviewport and always do the translation from my world to the screen and back?  IE, i want to have a 10x10 viewport on a 1920x1080 display.  I want the window actor at viewport 5x5 so I'd have to pass this through some transform routine to get from 5x5 viewport to x=1920/2, y=1080/2 on the screen and then use that newly transformed 960,540 position for the window actor (and that window actors stage is a screenviewport)?


I looked, and could not find, any examples in libgdx with using an actor where the viewport size was different than the screen and doing whatever is needed to get an actor to display properly in a mismatched viewport/display size scenario.  IE display is 1920x1080 and viewport is 192x108.  Can you point me to an example of this?


An aside, I think you should either leave that paragraph in the wiki or at least describe it.  I was pulling my hair out trying to figure out why the window actor took up the entire screen.  When i saw the mention of setScale (and the accompanying comment), at least it allowed me to scale and see the actor properly.

**Comment by obigu** [comment]
Haven't tested your code but on a first look it doesn't look like you are updating the Viiewport size.

Add a call to stage.getViewport().update(width, height, true); on `resize(int width, int height)`.

**Comment by mgsx-dev** [comment]
@chrisplak71 that's somehow what i'm saying. All viewports (except ScreenViewport) works like you describe : it uses a virtual area (world) and will adapt to any screen resolution/density in order to display the same thing "stretched".
Your game should only rely on this virtual area (world coordinates).

Example : 
* let say your viewport has a world size of 300x200 units
* you have an actor with size 30x20 units
* then your actor will take 1/10 the screen size at any resolution : it will be 300px by 200px on a 3000px by 2000px and so on...

for any other questions and help with your code, please use our Discord server instead, it'll be easier : https://libgdx.com/community/

**Comment by isoteriksoftware** [comment]
@chrisplak71 The reason it's scaled 10x bigger is because your viewport dimension is very small (192x108) compared to the screen resolution (1920x1080).

So this is what happened:
- You created a viewport and gave it a size of 192x108
-  You ran the game with a resolution of 1920x1080
- The viewport saw that the resolution is larger than the original viewport size. Then it scaled up your actors.

Actually this isn't a bug, that's how it should behave. I'll advise you to choose a suitable target resolution for your viewport (and don't scale manually). 192x108 is way too small. Personally, I usually choose a reasonable resolution like 800x480, then design my assets to work well with that resolution. Then the viewport will handle scaling when required.

**Comment by chrisplak71** [comment]
@mgsx-dev  The second bullet point of yours is what I see as the problem.  There is no way to create an actor in size of units.  The actor (appears) to always gets created in screen pixels.

The behavior I want is what you detail in bullet point 3, but that is not what is happening.  For a fit/extended/fill viewport, the size of the actor does not take up 1/10th of the viewport, it actually takes up 10X the intended size.  And if I happened to use a view port size of 1920/5, 1080/5 on a screen size of 1920,1080 the actor will now take up 5x the intended size.  It's only when the viewport size == the screen size that the actor takes up the space it is supposed to.  on the flip side if I have a viewport size of 1920*2, 1080*2 then the actor is now 1/2 the size it was in a 1920 viewport size.

Putting it another way, it appears that the actor is being scaled incorrectly at an inverse of the worldsize/screensize ratio.


FWIW - I have asked on discord and got no real responses.  A few questions asking for videos to show the issue, which I uploaded but no responses.  I posted on discord on 5/20,5/21

> 
> 
> @chrisplak71 that's somehow what i'm saying. All viewports (except ScreenViewport) works like you describe : it uses a virtual area (world) and will adapt to any screen resolution/density in order to display the same thing "stretched".
> Your game should only rely on this virtual area (world coordinates).
> 
> Example :
> 
>     * let say your viewport has a world size of 300x200 units
> 
>     * you have an actor with size 30x20 units
> 
>     * then your actor will take 1/10 the screen size at any resolution : it will be 300px by 200px on a 3000px by 2000px and so on...
> 
> 
> About the wiki paragraph removed, it was wrong and misleading, it's better without it, trust me :-) .
> 
> for any other questions and help with your code, please use our Discord server instead, it'll be easier : https://libgdx.com/community/

**Comment by mgsx-dev** [comment]
please ask again on Discord and ping me `@mgsx`, i'm sure we will find a solution to your issue.

**Comment by NathanSweet** [comment]
I'm late to the party, but here I am.

> There is no way to create an actor in size of units. The actor (appears) to always gets created in screen pixels.
Stage coordinates don't know they are pixels or something else. It's up to the viewport to map them. That said, for a UI usually you want stage coordinates to be pixels, so your UI graphics aren't scaled.

You can see it work by editing UITest eg:
```
stage = new Stage(new FitViewport(1000, 1000));
```
The units the UI is built with remain the same, but the viewport will show the UI scaled. All the UI input still works.
![](http://n4te.com/x/1900-9mVW.png)
