### ISSUE TITLE
macOS/LWJGL3: Gdx net uses deprecated APIs

### ISSUE THREAD

**Issue by kyu-n** [libgdx/libgdx#6542]
#### Issue details
The [Lwjgl3Net](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Net.java) class uses [deprecated, macos-specific APIs](https://openjdk.java.net/jeps/272) which are scheduled for removal from the JDK. The `com.apple.*` packages were deprecated in Java 9, and as-of [Java 16](https://openjdk.java.net/jeps/396), the JDK will throw an `IllegalAccessError` when calling (if using default settings).

These APIs are scheduled to become completely unusable in [JDK17](https://openjdk.java.net/jeps/403).

While OpenJDK offers the AWT-based Desktop API to replace this functionality, it's not usable for the lwjgl3 backend on macos. Calling `Desktop.getDesktop()` is enough to initialize the AWT event thread and causes any lwjgl3-based application to instantly hang, The LWJGL project often suggests using the [awt headless property](https://github.com/LWJGL/lwjgl3/issues/306#issuecomment-300481571) to workaround this issue, but this is nonsensical for the Desktop API's usage.

#### Version of LibGDX and/or relevant dependencies
1.9.10+

#### Stacktrace
```
java.lang.IllegalAccessError: class com.badlogic.gdx.backends.lwjgl3.Lwjgl3Net (in unnamed module @0x1f3f4916) cannot access class com.apple.eio.FileManager (in module java.desktop) because module java.desktop does not export com.apple.eio to unnamed module @0x1f3f4916
```

#### Please select the affected platforms
- [x] MacOS

**Comment by crykn** [comment]
[This thread](http://forum.lwjgl.org/index.php?topic=6872.0) on the LWJGL forum mentions some possible solutions.

**Comment by tommyettinger** [comment]
And the StackOverflow answer linked from that looks quite practical for libGDX, though I'm not sure what exactly Runtime is in this situation. https://stackoverflow.com/a/28807079/786740 (The comments seem vital, `xdg-open` on Linux and `start` on Windows should be good options, especially since I don't like listing all known browsers or using a particular name of a particular DLL that might change in some Windows 10 update.)

**Comment by kyu-n** [comment]
> And the StackOverflow answer linked from that looks quite practical for libGDX, though I'm not sure what exactly Runtime is in this situation.

`Runtime.exec()` is a JRE system method which spawns a subprocess. It's equivalent to creating a new terminal then firing `open url://target.com`

My only concern is that we've observed macOS's GateKeeper being fussy when handling spawned processes like this. I'll have to test whether #6543 requests new permissions. We've seen issues where users can permanently deny an application a permission with no way to change that decision.

> https://stackoverflow.com/a/28807079/786740 (The comments seem vital, `xdg-open` on Linux and `start` on Windows should be good options, especially since I don't like listing all known browsers or using a particular name of a particular DLL that might change in some Windows 10 update.)

I don't think it's really necessary for Linux/Windows platforms. `Desktop.getDesktop()` doesn't break games there and we've never seen an issue with the JDK's determination that something is/isn't a desktop platform.

**Comment by kyu-n** [comment]
@crykn I'm not seeing any issues with gatekeeper, so once the security issue of #6543 has been resolved, this can be regarded as fixed.
