### ISSUE TITLE
Implement a way to invert Camera control

### ISSUE THREAD

**Issue by Timvisser1994** [libgdx/libgdx#6544]
#### Issue details
Currently, there is no way to set the `CameraInputController`s inversion of controls.

#### Reproduction steps/code
```java
...
Camera cam = new PerspectiveCamera(67, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
CameraInputController camController = new CameraInputController(cam);
...
```
While it would be great to have something like:
```java
...
Camera cam = new PerspectiveCamera(67, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
CameraInputController camController = new CameraInputController(cam);
camController.setInvertedControls(true);
...
```

#### Version of LibGDX and/or relevant dependencies
`1.10.0` (latest greatest at time of writing)

#### Please select the affected platforms
- [x] Android
- [x] iOS
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by metaphore** [comment]
Can you please elaborate on the reason for such a feature?

Don't really understand the application, but it seems to me like you can get away with a custom `CameraInputController` on your end.
