### ISSUE TITLE
Siero tool has a issue

### ISSUE THREAD

**Issue by Aiden-L** [libgdx/libgdx#6560]
When choose the font, there is no way to change from choosing file to choosing from the system fonts.
![图片](https://user-images.githubusercontent.com/51192494/121664851-7f28e580-cada-11eb-93b3-3e9c9cd19e5c.png)

**Comment by tommyettinger** [comment]
You appear to be using a very, very old version. Download the current Hiero from where it says "download the .jar file here" on the wiki, https://github.com/libgdx/libgdx/wiki/Hiero#running-hiero . I just tested the current Hiero jar (which is version v5, not your v3.0), and it let me pick files and system fonts at will. **Please download the current Hiero** and close this issue if it works. If the current Hiero has some other issue, you can continue that here.

It is always possible there is an issue with the Unicode characters in the file path; that is an issue with many tools, and I don't know if Hiero is affected. Another thing to try could be moving your Cylburn.ttf file into a path with only English characters.
