### ISSUE TITLE
Preferences order

### ISSUE THREAD

**Issue by GniLudio** [libgdx/libgdx#6565]
Please ensure you have given all the following requested information in your report.

#### Issue details
It would be nice if the order of preferences could be manipulated.
Now when adding key value pairs, the order is mixed,
but sometimes/often it is useful to group some settings.

#### Example
So in this configuration it would be nice to group width and height together, aswell as fps and vSync.
So this display configuration
```java
Preferences displayConfig = Gdx.app.getPreferences("myGame/displayConfig.txt");
displayConfig.putBoolean("fullscreen", false);
displayConfig.putInteger("width", 1280);
displayConfig.putInteger("height", 720);
displayConfig.putInteger("fps", 60);
displayConfig.putBoolean("vSync", true);
displayConfig.flush();
```
could result in this config file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
<entry key="fullscreen">false</entry>
<entry key="vSync">true</entry>
<entry key="width">1280</entry>
<entry key="fps">60</entry>
<entry key="height">720</entry>
</properties>
```

#### Version of LibGDX and/or relevant dependencies
- LibGDX:: 1.10.0
- Java: 1.8

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [ ] MacOS

**Comment by crykn** [comment]
Hey @GniLudio!

Since we are using platform specific implementations for saving preferences (for example, on Desktop we are using `java.util.Properties`) this is not as easy as it sounds. 

However, if you want to sort the values alphabetically, you could copy [Lwjgl3Preferences](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Preferences.java) and change its `flush()` method to something like this:

```
@Override
public void flush () {
  Properties tmp = new Properties() {
    @Override
    public Set<Object> keySet() {
      return Collections.unmodifiableSet(new TreeSet<Object>(super.keySet()));
    }
  };
  tmp.putAll(properties);

  OutputStream out = null;
	try {
		out = new BufferedOutputStream(file.write(false));
		tmp.storeToXML(out, null);
	} catch (Exception ex) {
		throw new GdxRuntimeException("Error writing preferences: " + file, ex);
	} finally {
		StreamUtils.closeQuietly(out);
	}
}
```
