### ISSUE TITLE
Read "Type" and "Probability" as first-class citizens for a Tile (.tmx)

### ISSUE THREAD

**Issue by Timvisser1994** [libgdx/libgdx#6566]
#### Issue details
Currently, `type` is not being read by `BaseTmxMapLoader`, even though it is a base property of a `Tile`. Furthermore, `probability` _is_ being read, but simply put in the tiles' `Properties`. It would be a good idea to 'promote' these base fields to `Tile`.

#### Reproduction steps/code
In [Tiled](https://www.mapeditor.org/), configure a tile map:
![image](https://user-images.githubusercontent.com/2553764/121943084-80177c80-cd51-11eb-83f0-e42c2c00a340.png)

Notice that this will produce some output like:
```xml
...
<tileset firstgid="1" name="grass-tiles-2-small" tilewidth="32" tileheight="32" tilecount="72" columns="12">
  <image source="grass-tiles-2-small.png" width="384" height="192"/>
  <tile id="13" type="Grass" probability="0.5"/>
</tileset>
...
```

#### Version of LibGDX and/or relevant dependencies
All versions.

#### Notice that they are not first-class citizens in **`BaseTmxMapLoader.java` lines 608 - 620:**
```java
for (Element tileElement : tileElements) {
	int localtid = tileElement.getIntAttribute("id", 0);
	TiledMapTile tile = tileSet.getTile(firstgid + localtid);
	if (tile != null) {
		AnimatedTiledMapTile animatedTile = createAnimatedTile(tileSet, tile, tileElement, firstgid);
		if (animatedTile != null) {
		        animatedTiles.add(animatedTile);
			tile = animatedTile;
		}
		addTileProperties(tile, tileElement);
		addTileObjectGroup(tile, tileElement);
	}
}
```

#### Please select the affected platforms
- [x] Android
- [x] iOS
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by lyze237** [comment]
Type is going to be supported in the upcoming version: #6534 and is already in the snapshot.

Probability is already supported: https://github.com/libgdx/libgdx/blob/e31c86dad4056fb2972145cb2d92ae915359e689/gdx/src/com/badlogic/gdx/maps/tiled/BaseTmxMapLoader.java#L640

**Comment by Timvisser1994** [comment]
@lyze237 Thank you for the quick response!

Indeed, `probability` is already supported by putting it in the `MapProperties`. I'm of the opinion that they (`probability` and `type`) should _also_ live as a first-class citizen. This way, you don't have (potentially) expensive lookup calls in your `MapProperties`...

Please feel free to comment! Maybe I don't get the full context of it 😊

**Comment by lyze237** [comment]
It's best to either create an issue or to create a pull request, and not both. As now there are two comment sections for the same thing.

I'll reply to you in the pull request. Feel free to close the issue and keep the PR open. :)

**Comment by Timvisser1994** [comment]
Closing Issue

**Comment by Timvisser1994** [comment]
@lyze237 Whoops... still a bit of a noob, sorry 😌
I will close the Issue now.

But I don't really get why the route via `getProperties()` is better? To me that feels cumbersome and... slow. Is that not so?

**Comment by Timvisser1994** [comment]
@lyze237 Should I open up another Issue to also support `type`?
