### ISSUE TITLE
GlyphLayout: Reference to font

### ISSUE THREAD

**Issue by GniLudio** [libgdx/libgdx#6570]
# GlyphLayout: Reference to font

#### Issue details
When creating `GlyphLayout`s, it is necessary to remember for each which font was used,
since the font is needed for rendering the glyph later.

#### Reproduction steps/code
```java
// creating fonts (in constructor)
glyph = new GlyphLayout(Main.game.fonts.defaultFont, "This is the best game.");
glyph2 = new GlyphLayout(Main.game.fonts.largeFont, "Hello WOrld");

// rendering later
Main.game.fonts.defaultFont.draw(Main.game.spriteBatch, glyph, 0, 1080);
Main.game.fonts.largeFont.draw(Main.game.spriteBatch, glyph2, 333, 540);
```

### Suggestions
It would be nice if each `GlyphLayout` just stores a reference to its font, 
so it would be possible to:
```java
// creating fonts (in constructor)
glyphs = new GlyphLayout[2];
glyphs[0] = new GlyphLayout(Main.game.fonts.defaultFont, "This is the best game.");
glyphs[1] = new GlyphLayout(Main.game.fonts.largeFont, "Hello WOrld");

// rendering
glyphs[0].getFont().draw(Main.game.spriteBatch, glyphs[0], 0, 1080);
glyphs[1].getFont().draw(Main.game.spriteBatch, glyphs[1], 333, 540);
```
Even more comfortable would be to implement a shortcut to the draw GlyphLayout method:
```java
glyphs[0].draw(batch, 0, 1080);
```

#### Version of LibGDX and/or relevant dependencies
- Java: 1.8
- LibGDX: 1.10.0

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [ ] MacOS

**Comment by NathanSweet** [comment]
A single GlyphLayout can be used for multiple fonts. I don't see any benefit to coupling GlyphLayout to a single font. That your use case happens to use one GlyphLayout for one font is not a good enough reason. You can easily extend GlyphLayout and remember the font. Then you could have:
```
yourLayout.draw("text");
```
Note you may want to be using BitmapFontCache instead.
