### ISSUE TITLE
2D Particle Editor freezes after Window loses then regains focus

### ISSUE THREAD

**Issue by satori87** [libgdx/libgdx#6584]
My environment:
Intel Core i7-7700 CPU, 32.0 GB RAM, Windows 10 Pro 19041.1052 with Java(TM) SE Runtime Environment (build 1.8.0_291-b10)

This also occurs on team member's Windows 10 machine with Java build 1.8.0_291-b10 and also on my machine with Java 11.0.10.

When running the latest downloadable jar of the 2D particle editor, the program becomes unresponsive after the windows loses focuses and then regains it. No log output occurs so there is no stack trace to show.

To reproduce: Launch the jar from command-line or double-clicking. Click on a different window, click on editor again.

**Comment by satori87** [comment]
I have tracked the issue down to the ParticleEditor.java:
`public boolean touchUp (int x, int y, int pointer, int button) {
    ParticleEditor.this.dispatchEvent(new WindowEvent(ParticleEditor.this, WindowEvent.WINDOW_LOST_FOCUS));
    ParticleEditor.this.dispatchEvent(new WindowEvent(ParticleEditor.this, WindowEvent.WINDOW_GAINED_FOCUS));
    ParticleEditor.this.requestFocusInWindow();    
    return false;
}`
Furthermore, the issue is only caused by clicking on the Window. All other forms of focusing the window e.g. alt+tab, clicking taskbar are working without issue.

**Comment by tommyettinger** [comment]
I can reproduce, though it only freezes when both windows (particle editor and task manager, in my case) are on-screen at the same time. I have essentially no experience with particles and the editor, so I probably won't be able to help much.
