### ISSUE TITLE
Help! My NinePatch ProgressBar background is not appearing when the slice values are set

### ISSUE THREAD

**Issue by siauderman** [libgdx/libgdx#6594]
I need help! What am I doing wrong? When I remove the 4 integer slice values, the background is displayed (of course, stretched very weirdly). However, when I put in the 4 slice values, the NinePatch doesn't display at all.

progressBar, progressBarStyle and background are defined elsewhere in the class.

````
add(progressBar=new ProgressBar(
	0f,
	100f,
	0.1f,
	false,
	progressBarStyle=new ProgressBar.ProgressBarStyle(
		background=new NinePatchDrawable(new NinePatch(
			TextureRegionFinder.findTextureRegion(
				arena.tuxFight.assetManager,
				"barbackground.png"
			),
			11,
			11,
			11,
			11
		)),
		null
	)
));
progressBar.setRound(false);
progressBar.setBounds(0,0,width,height);
progressBar.setValue(MathUtils.clamp(value,0f,100f));
progressBar.setAnimateDuration(1f);
background.setMinSize(width,height);
background.tint(endColor);

progressBarStyle.knobBefore=new BaseDrawable(){
	{
		setMinHeight(progressBar.getHeight());
	}
	ShapeRenderer shapeRenderer=new ShapeRenderer();
	@Override
	public void draw(Batch batch,float x,float y,float width,float height){
		batch.end();
		shapeRenderer.setProjectionMatrix(batch.getProjectionMatrix());
		shapeRenderer.begin(ShapeRenderer.ShapeType.Filled);
		shapeRenderer.rect(x+7f,y+7f,(width-14f)*0.25f,height-14f,zeroColor,midColor,midColor,zeroColor);
		shapeRenderer.rect(x+7f+(width-14f)*0.25f,y+7f,(width-14f)*0.75f,height-14f,midColor,endColor,endColor,midColor);
		shapeRenderer.end();
		batch.begin();
	}
};

**Comment by tommyettinger** [comment]
Please use the Discord for help requests; the #scene2d, #help-1 or #help-2 topics would all be appropriate avenues. If you don't have Discord, [the libGDX server link is here](https://discord.gg/GTmwWD9PR9). This doesn't look like a bug or other issue in libGDX, but I'm not comfortable enough with 9patches to say that with confidence, so I'll leave this open for now.

As an aside, you may want [ShapeDrawer](https://github.com/earlygrey/shapedrawer) rather than ShapeRenderer, to avoid frequently ending and beginning the batch.

**Comment by MrStahlfelge** [comment]
Closed because this seems to be a question not an issue.

**Comment by siauderman** [comment]
Hi I'm so sorry, I think this is actually a bug.

I have just tried it out with an Image and it appears that all of the corners and sides of the NinePatch are **not** drawn.

Here is my test code:

````
Image img=new Image(new NinePatch(
	TextureRegionFinder.findTextureRegion(
		tuxFight.assetManager,
		"barbackground.png"
	),
	11,
	11,
	11,
	11
));
img.setBounds(100f,100f,100f,100f);
stage.addActor(img);
````
If I understand the constructor correctly, the 4 int arguments are supposed to be the "slice" values. But basically, the corners and sides do not appear at all when the 4 values are passed.
If I omit the slice values entirely, the image is drawn correctly.

**Comment by tommyettinger** [comment]
Well, if it is a bug, we can't reproduce it without `barbackground.png`. The slice values look like they could be incorrect to me, at first glance. It would depend on the exact image you're using. You should ask on the Discord about the right values for those 4 slices, or create a 9-patch image (a `.9.png`) using any of the techniques at https://github.com/libgdx/libgdx/wiki/Ninepatches .

**Comment by siauderman** [comment]
Hi, I found out the problem. The NinePatch simply doesn't work when the TextureRegion is flipped (vertically).

See https://github.com/siauderman/NinePatchTest

I believe this is a bug. Surely NinePatches should work even when the TextureRegion is flipped.
