### ISSUE TITLE
Fullscreen not using fullscreen

### ISSUE THREAD

**Issue by siauderman** [libgdx/libgdx#6596]
Hi, when I call setFullscreenMode(Gdx.graphics.getDisplayMode()), the entire viewport ends up taking up only a small portion of the screen.

![IMG_20210714_023110.jpg](https://user-images.githubusercontent.com/14951259/125506118-4a88a1dd-f67c-48c4-b223-40f8e023e56f.jpg)

I notice that Gdx.graphics.getWidth() and Gdx.graphics.getHeight() also do not return the actual width and height of the screen but a far smaller value.

**Comment by crykn** [comment]
Hey @siauderman! If you are not already using the LWJGL 3 backend, could you try, whether the issue occurs with it as well? Instructions to switch can be found [here](https://gist.github.com/crykn/eb37cb4f7a03d006b3a0ecad27292a2d). And what OS are you using?

**Comment by yuripourre** [comment]
@siauderman can you please check what values `Gdx.graphics.getBackBufferWidth()` and `Gdx.graphics.getBackBufferHeight()` return?

**Comment by siauderman** [comment]
@crykn @yuripourre It works after I switched to LWJGL3, thanks!
