### ISSUE TITLE
Changing the logo in gdx-setup

### ISSUE THREAD

**Issue by Frosty-J** [libgdx/libgdx#6602]
gdx-setup hasn't changed a great deal since the good old days of libGDX 1.0.0. Even so, I want to float the idea of replacing the logo used in it with the one we see today. Here is what I've done:

- Replace the old logo with the new one. It is the same height - 70 pixels. (Side note: Why's there no dark SVG download on the website? It's trivial to create with a text editor - replace `#000000` with `#ffffff`)
- Update the red text to match the new shade found in the logo. A side effect of this is those headings become easier to read, though it's still not enough to pass the Web Content Accessibility Guidelines (not that gdx-setup would be accessible otherwise, and I know it's not a webpage but they're still pretty good guidelines).

You can see a comparison of what these changes look like here:

Before|After
-|-
![](https://user-images.githubusercontent.com/60154347/126065623-09bb74b7-af18-41e2-a46f-a2c86573416f.png)|![](https://user-images.githubusercontent.com/60154347/126065631-ad1b6cce-a870-464e-80aa-cd9a3f48beb2.png)

I'm unhappy with it for these three reasons:

- Despite the height remaining the same, it is wider and overall ends up much larger than the old logo, throwing the proportions off.
- The "PROJECT SETUP" subtitle's font no longer matches the logo. I've heard the current libGDX logo is a custom design (i.e. not an existing font) so I don't know what to do about this.
- It's a pretty significant change to how things look. Someone might have a meltdown.

Mainly I find it too in-your-face. So I've come here to ask your opinions on the matter, namely whether you like this and what can (easily) be done to improve it. I'm by no means a graphical designer and I fear the GitHub dwellers aren't either.

**Comment by raeleus** [comment]
I like the new look.

**Comment by crykn** [comment]
I agree, it makes sense to update the setup tool to the "new" look. The corresponding changes are already part of #6463.

**Comment by Frosty-J** [comment]
Oh, righto. The 50px tall logo in that one will probably look less extreme than what we have here.
