### ISSUE TITLE
RoboVM won't include gdx into classpath when using libGDX compiled from source

### ISSUE THREAD

**Issue by Berstanio** [libgdx/libgdx#6608]
#### Issue details
When libGDX is compiled from source using ```mvn install``` (https://libgdx.com/dev/from-source/) everything works fine except the robovm-backend. When trying to use the manually compiled robovm-backend it won't work. The gdx module won't get included in the classpath (can be seen in the building log). Therefor the app isn't running because the gdx core is missing.

#### Reproduction steps/code
I've forked a simple libGDX App.
1. clone this repository: https://github.com/Berstanio/chigginblazzder
2. run the ios module with the IntelliJ mobivm plugin (newest official version)
3. The App will run normally. (This means the configuration of the game is correct)
4. clone libGDX and run ```mvn install``` 
5. checkout the "error" branch
6. clear all caches and do a gradle sync (It was important for reproducing when I tested it)
7. run the ios module with the IntelliJ mobivm plugin (newest official version)
8. It will produce a NoClassDefFound error when running but the reason is that the gdx module won't get included into the classpath (can be seen in the logs)

I hope it can be reproduced!

#### Version of libGDX and/or relevant dependencies
Build from source.

#### Stacktrace
Not relevant. But if the build logs are needed I can provide them.

#### Please select the affected platforms
- [ ] Android
- [x] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by obigu** [comment]
I've just tested building a libGDX version from Master and your demo project works ok with it.

I'd suggest you test with a named version (such as 1.10.1.TEST), SNAPSHOT are not always updated and becaue of the Maven cache policies them are not ideal for this kind of testing. You can just find/replace in files from IDEA on all `pom.xml` files and if you need to test again use TEST2, etc...

Also, when building libGDX do a `mvn clean install` (be aware of the CLEAN).

I've tested with MobiVM 2.3.12 plugin, don't think it's related but just as disclosure.

**Comment by Berstanio** [comment]
Today I tried it again (without rebuild of libGDX) and it worked. The only thing I changed was setting the "MAVEN_REPOSITORY" environment variable because Android Studio said it wasn't set. But other dependencies that were in the local maven repository were picked up correctly. So could this missing variable still lead to the issue?
