### ISSUE TITLE
Can Interface InputProcessor's method be optional?

### ISSUE THREAD

**Issue by wangdong20** [libgdx/libgdx#6620]
I tried to use screen handle TouchUp and TouchDown event in libgdx. When I inplement InputProcessor to Screen, I have to deal all the functions like keyup, keydown, mousemoved, scrolled, etc. Many functions from interface InputProcessor are not required for my project. So if the methods in InputProcessor are optional then it will be better I guess.

**Comment by Tom-Ski** [comment]
InputAdapter is the class you want
