### ISSUE TITLE
Matrix4 class setToOrtho is wrong

### ISSUE THREAD

**Issue by younggam** [libgdx/libgdx#6623]
Please ensure you have given all the following requested information in your report.

#### Issue details
math on setToOrtho is wrong

#### Reproduction steps/code
In libgdx/gdx/src/com/badlogic/gdx/math/Matrix4.java
573th line.
```
public Matrix4 setToOrtho (float left, float right, float bottom, float top, float near, float far) {
		float x_orth = 2 / (right - left);
		float y_orth = 2 / (top - bottom);
		float z_orth = -2 / (far - near);

		float tx = -(right + left) / (right - left);
		float ty = -(top + bottom) / (top - bottom);
		float tz = -(far + near) / (far - near);

		val[M00] = x_orth;
		val[M10] = 0;
		val[M20] = 0;
		val[M30] = 0;
		val[M01] = 0;
		val[M11] = y_orth;
		val[M21] = 0;
		val[M31] = 0;
		val[M02] = 0;
		val[M12] = 0;
		val[M22] = z_orth;
		val[M32] = 0;
		val[M03] = tx;
		val[M13] = ty;
		val[M23] = tz;
		val[M33] = 1;
		return this;
	}
```

according to this, I assume that left=0, right=100, bottom=0, top=100, near=0, far=100
then orthographic matrix should be

```
0.02, 0,       0,      -1
0,      0.02,  0,      -1
0,      0,      -0.02, -1
0,      0,      0,       1
```

and lets multiply two vector below that corresponds to two-end edges of frustum
```
100      0
100  ,   0
100      0
1        1
```
then
```
2 + 0 + 0 - 1 = 1
0 + 2 + 0 - 1 = 1
0 + 0 -  2 - 1 = -3
0 + 0 + 0 + 1 = 1
```
,
```
0 + 0 + 0 - 1 = -1
0 + 0 + 0 - 1 = -1
0 + 0 + 0 - 1 = -1
0 + 0 + 0 + 1 = 1
```

the two edges are transformed to (1,1,-3) and (-1,-1,-1) not (1,1,-1) and (-1,-1,1)
so I suggest ` tz` to be just `(far + near) / (far - near)`

#### Version of libGDX and/or relevant dependencies
on master branch

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by tommyettinger** [comment]
Have you encountered any actual bugs relating to setToOrtho() ? Is anything behaving incorrectly, throwing Exceptions, or otherwise looking wrong? Have you tested your proposed change? Have you considered whether existing code would break as a result of changing setToOrtho(), which is a pretty central part of the 2D graphics code? If all of the above are "yes," then I'll look into this, otherwise I think this should be closed.

**Comment by younggam** [comment]
ok all the above are "no". But I don't think this should be closed.
but did you also look into calculation? If result in issue is incorrect, I'll close my issue.

**Comment by tommyettinger** [comment]
I am not deeply familiar with Matrix4's code, but I can tell that for all of the tests I ran, changing tz from negative to positive made no apparent change in the tests' behavior. That's not to say that it wouldn't break something, somewhere, if this was changed, and there remains no cause-and-effect reason to change it. I'll leave this open for other devs to speak up, but I doubt anyone is willing to make changes to Matrix4 without a good reason. I mean, it could be wrong in some sense, but for orthographic cameras, the actual z values for the near and far plane don't matter other than the difference between the two (I could easily be wrong, but it would explain the behavior here).

**Comment by younggam** [comment]
thanks, I get it.

**Comment by megalithic3** [comment]
> "and lets multiply two vector below that corresponds to two-end edges of frustum"
> 
> ```
> 100      0
> 100  ,   0
> 100      0
> 1        1
> ```

@younggam
Depends on what you mean by "end edge" of frustum. If you compare two vectors with same Z value like (100, 100, 100, 1) and (0,0,100,1), then you will get results 1,1,-3,1 and -1,-1,-3,1.

Also, the top search internet search results agree with how it is implemented in libgdx exactly, so check that out.

https://www.scratchapixel.com/lessons/3d-basic-rendering/perspective-and-orthographic-projection-matrix/orthographic-projection-matrix

https://blog.demofox.org/2017/03/31/orthogonal-projection-matrix-plainly-explained/

**Comment by younggam** [comment]
what I couldn't understand was that far-plane was projected to z=-1 plane and near-plane was prejected to z=-3 plane.

I got the answer by tommyettinger that theirs relative z-depth difference affects dominately on opengl otherwise absolute z-depth don't.

my unsloved curious is why they should be prjected to -1 and -3  not 1 and -1. 
currently, I accept tommyettinger as answer that  only relative z-depth difference is important on opengl.

**Comment by obigu** [comment]
There doesn't seem to be an actual issue. If you can provide a test that shows a wrong behaviour please feel free to reopen.
