### ISSUE TITLE
Binding to ReactPhysics3D

### ISSUE THREAD

**Issue by ghost** [libgdx/libgdx#6625]
Hello community!

Could you provide binding to ReactPhysics3D physics engine? The engine is open source and has good documentation. API is simple and codebase looks clean (I don't know C++). Of course the engine is not advanced as Bullet but there are all major features. The engine located at: https://www.reactphysics3d.com

Please consider supporting this engine.

**Comment by crykn** [comment]
Supporting another physics library is outside the scope of libGDX - we already have trouble keeping the Box2D and Bullet wrappers up to date. FWIW there already seems to be a Java library based on ReactPhysics3D: https://github.com/flowpowered/react
