### ISSUE TITLE
ProgressBar never empty

### ISSUE THREAD

**Issue by CrisN4N** [libgdx/libgdx#6636]
#### Issue details
I want to create simple health bar using NinePatch for ProgressBar 's background.
I have this now:
![изображение](https://user-images.githubusercontent.com/89037905/130453311-091dd51e-595b-45b0-80b3-13a4a455487b.png)
I spent 2 days trying to fix this pixel... I search any issues connected with ProgressBar in this repo. Search any info with same situation in google.

The only solution that work is to use dirty hack. (https://stackoverflow.com/questions/36682421/libgdx-scene2d-progress-bar-never-empty)
![изображение](https://user-images.githubusercontent.com/89037905/130453826-9a9bd040-4625-436c-8060-817ecbad112f.png)

How i can fix it without hacks?

#### Reproduction steps/code
I create simple example of this behaviour:
**MyGdxGame.java** - https://pastebin.com/bFgSsEzf
**skin.json** - https://pastebin.com/pgatCEKu
**textures.atlas** - https://pastebin.com/qxbS37x3
**texture_0.png** -
![texture_0](https://user-images.githubusercontent.com/89037905/130455073-2752aa94-58df-462b-a378-143baa2a2869.png)

#### Version of libGDX and/or relevant dependencies
gdxVersion = '1.10.0'

#### Please select the affected platforms
- [X] Android
- [X] iOS
- [X] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by BoBIsHere86** [comment]
I came across this issue awhile ago. It should be resolved in the latest snapshot version. You could give that a try until the next release comes out.
Here is the related issue that was closed. #6533

**Comment by CrisN4N** [comment]
@BoBIsHere86, I used 1.10.1-SNAPSHOT for test. You are right, This bug is fixed in snapshot.
