### ISSUE TITLE
AssetManager async thread waste a lot of time on loading 

### ISSUE THREAD

**Issue by jetzack** [libgdx/libgdx#6642]
#### Issue details
I load my assets using AssetManager. I have the loading screen where I do AssetManager.update() in the render loop to move tasks in manager and get the moment all will be loaded and I will be able to begin the level. This approach is described here https://github.com/libgdx/libgdx/wiki/Managing-your-assets#actually-loading-the-assets .

But it takes 25 seconds to complete loading of all assets. 
I began to profile it and found that the async thread created by AssetManager just wait on locks for 19 seconds, and do useful work only 6 seconds. I made the hack from comment below and got 6 secs.  AssetManager.update drives the load queue - start the load of next task. Seems like the rate of calls from render loop too low. 

Is there the way to start loading of all tasks without demand to move tasks manually by assetManager.update? 
#### Reproduction steps/code

![profileResult](https://user-images.githubusercontent.com/47293117/131251973-aecaa0ee-031d-4f40-a69a-71046966d396.png)
` @Override
    public void render(float delta) {
        if (!assetManager.update()) {
            ThreadUtils.yield();
            return;
        }
        GameScreen gameScreen = new GameScreen(level);
        ((MyGame) Gdx.app.getApplicationListener()).setScreen(gameScreen);
    }`
#### Version of libGDX and/or relevant dependencies
libGDX version = '1.10.0'
#### Please select the affected platforms
- [+] Android
- [ ] iOS
- [ ] HTML/GWT
- [+] Windows
- [+] Linux
- [+] MacOS

**Comment by jetzack** [comment]
Actually seems like the rate of calls assetManager.update in render loop too low. I made this hack and got 6 seconds result: 

`    @Override
    public void render(float delta) {
          for (int i = 0; i < 20000; ++i) {
              if (!AssetsRegistry.getInstance().getAssets().update()) {
                  ThreadUtils.yield();
              } else {
                  GameScreen gameScreen = new GameScreen(level);
                  ((ParkManGame) Gdx.app.getApplicationListener()).setScreen(gameScreen);
                  return;
              } 
    }
`

**Comment by obigu** [comment]
Please check https://github.com/libgdx/libgdx/wiki/Managing-your-assets#optimize-loading. Using `update(float millis)` is the way to go, you should get close to the 6 seconds optimal time by using around 15ms without affecting fps much.

**Comment by jetzack** [comment]
Sorry, got it. Thanks a lot
