### ISSUE TITLE
getNativeOrientation() on iOS returns the current device orientation, not the native one

### ISSUE THREAD

**Issue by muratmat** [libgdx/libgdx#6643]
On iOS backend ( see https://git.io/JEFzU ) `getNativeOrientation()` returns the current device orientation, not the native one. So when you handle device rotations (e.g. within the `ApplicationAdapter`'s resize method), you cannot know exactly what situation the device is in. BTW, on Android `getNativeOrientation()` always report the correct value (i.e. the same value independently from the current device rotation).

I would suggest a tricky code, in order to precalculate (on iOS) the native orientation:

```
int screenWidth = Gdx.graphics.getBackBufferWidth();
int screenHeight = Gdx.graphics.getBackBufferHeight();
int deviceRotation = Gdx.input.getRotation();

if (((deviceRotation == 0  deviceRotation == 180) && (screenWidth >= screenHeight)) 
    ((deviceRotation == 90 || deviceRotation == 270) && (screenWidth <= screenHeight))) {
    _nativeDeviceOrientation = Input.Orientation.Landscape;
}
else {
    _nativeDeviceOrientation = Input.Orientation.Portrait;
}
```

Feedback would be appreciated. Thanks for your hard work!

**Comment by muratmat** [comment]
On iOS `getNativeOrientation` returns Portrait if the current rotation (i.e. the value returned by `getRotation`) is 90 or 270, else it returns Landscape. So, imagine to handle device rotation within the resize method: how can I handle the event correctly if:

- I can get the current rotation using `getRotation()`
- But I cannot know the native device orientation

For example, lets say `getRotation` has returned 90. How can I know if the device is a native portrait device being rotated by 90 degrees or if the device is a portrait device being rotated by 90 degrees? In the general case the behavior that the application must have can be different.

Thanks!

**Comment by obigu** [comment]
You don't need to worry about how the device is normally held (the "natural or native orientation"), the iOS API tells you how it's being currently held that's what you want to know.

If you check `getRotation()` implementation, iOS doesn't return an angle but an orientation and on iOS "Portrait" always means width < height and "Landscape" width > height (it's also how we generally define portrait and landscape when we talk). So, following your example, if `getRotation()` has returned `90` you know for sure the device is in `Landscape` and that `width > height`.
