### ISSUE TITLE
setPosition gets wrong position after rotate rectangle shape sprite

### ISSUE THREAD

**Issue by wangdong20** [libgdx/libgdx#6645]
Currently I use libgdx to write a game using rectangle shape sprite to rotate and update new position. There are some rectangle shape sprite like 1 * 2, 1 * 3, 1 * 4, 1* 5 size. I want to rotate the sprite with 90 degree but not based on the center itself all. If sprite length is even like 1 * 2, it will based on (0.5, 1.5) as origin point. But if sprite length is odd like 1 * 3, it will based on (0.5, 1.5) as origin point the same as its center.
When I rotate the sprite with 180 degree such as 1 * 2 size sprite, the origin point doesn't change, the position doesn't change neither. But when I try to move the sprite to new position, unexpected result happened. I still try to move sprite to new position when is based on the left bottom corner, but the sprite is already rotate with 180 degree and it origin point is not the center of the sprite, the sprite looks like go up one more block when I set it to new position. I don't how to solve this. I want to set the position based on the origin point but origin point doesn't change even it is after rotate.

**Comment by mgsx-dev** [comment]
please use [Discord](https://libgdx.com/community/) to ask questions and get some help.
Next time, please don't bypass the issue template, thank you.
