### ISSUE TITLE
Github actions broken due to expired 16.04 environment.

### ISSUE THREAD

**Issue by PokeMMO** [libgdx/libgdx#6657]
https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/

We should migrate to 18.04. This will raise the minimum supported platform for linux natives, but lwjgl3 has already done this change.

**Comment by Frosty-J** [comment]
September 20 sounds pretty soon! I saw TEt link to https://github.com/LWJGL/lwjgl3/commit/307ebed6ef6ba420b2165ddb2ec21dd9a37479df on Discord a while back. Don't know what to make of it but it might be useful to reference.

**Comment by tommyettinger** [comment]
No no, it is, JAmes. LWJGL3 probably took steps we can also take, maybe identical ones in some places. Also, September 20 is over for the planet as a whole in less than 8 hours.
