### ISSUE TITLE
[Question] OpenGL 4+ Support

### ISSUE THREAD

**Issue by calvertdw** [libgdx/libgdx#6666]
Is it just that nobody has added GL4+ support? Or maybe that it wouldn't add anything majorly new?

In Lwjgl3ApplicationConfiguration there's `useOpenGL3` and in `com.badlogic.gdx.Gdx` we have `gl`, `gl20`, `gl30`, etc.

I also see that LWJGL has all the way up to `org.lwjgl.opengl.GL46`.

So, would it make sense to add things such that GL4+ is setup similar to how you can enable GL30?

Thanks!

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [X] Windows
- [X] Linux
- [X] macOS

**Comment by Frosty-J** [comment]
I believe those version numbers are based on OpenGL ES, and there is no OpenGL ES 4.

**Comment by calvertdw** [comment]
Okay, I see.

`com.badlogic.gdx.graphics.GL30` != `org.lwjgl.opengl.GL30`

Maybe it should be called `GLES30`.

I suppose that using functionality past ES for use on desktop systems with OpenGL 4.6 installed is sort of just supported in that libGDX doesn't really have to do anything in order to support that.

**Comment by Frosty-J** [comment]
It can definitely be confusing, but renaming it now would break a lot of existing stuff.

I don't really know anything about using OpenGL stuff directly, but if you don't care about mobile and web I don't see anything wrong with using OpenGL 4.6 features, bearing in mind hardware support for that version is limited.

**Comment by calvertdw** [comment]
Whoa, I don't use Mac, but given your previous comment that OpenGL ES 3.0 requires OpenGL 4.3, that is quite alarming. My app with a color and depth sensor simulator for robotics definitely doesn't support OpenGL ES 2.0. I thought I was supporting Mac but I guess I need to check on that.
```
Multiple render targets not available on GLES 2.0
```

**Comment by Frosty-J** [comment]
I think some ES 3.0 features work in pre-GL 4.3, but it's something you'd have to investigate yourself unless someone here knows their stuff.

OpenGL ES 3.0 support is present in the libGDX iOS backend but is considered experimental. I don't see this changing either.

https://github.com/libgdx/libgdx/blob/79cf00af53b7f38667291fbacf544d3074a811bd/backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSApplicationConfiguration.java#L69-L72

**Comment by mgsx-dev** [comment]
Guys, please use discord to continue your conversation if needed.
