### ISSUE TITLE
ArrayIndexOutOfBoundsException in scene2d.Actor.setZIndex (int index)

### ISSUE THREAD

**Issue by denri11** [libgdx/libgdx#6667]
#### Issue details
If `children.size = 0`, then method `scene2d.Actor.setZIndex` causes an `ArrayIndexOutOfBoundsException`.
`index` is assigned the value `-1` in the line of code:
```java
 index = Math.min(index, children.size - 1);
```

#### Reproduction steps/code
```java
public boolean setZIndex (int index) {
    if (index < 0) throw new IllegalArgumentException("ZIndex cannot be < 0.");
    Group parent = this.parent;
    if (parent == null) return false;
    Array<Actor> children = parent.children;
    if (children.size == 1) return false;
    index = Math.min(index, children.size - 1);
    if (children.get(index) == this) return false;
    if (!children.removeValue(this, true)) return false;
    children.insert(index, this);
    return true;
}
```

#### Version of libGDX and/or relevant dependencies
gdxVersion = **1.10.0**

#### Stacktrace
```java
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 42
```

#### Please select the affected platforms
- [x] Android
- [x] iOS
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] macOS

**Comment by tommyettinger** [comment]
That should only happen if `children` already has size 0, in which case there's no way the next line could run either. I'm guessing the solution is to change `if (children.size == 1) return false;` to `if (children.size <= 1) return false;`, above the line in question.
`
