### ISSUE TITLE
Failed to send onVsync Android

### ISSUE THREAD

**Issue by daimonkor** [libgdx/libgdx#6676]
Hello, please help, I got randomly loop
`E/android.hardware.graphics.composer@2.3-service: failed to send onVsync: Status(EX_TRANSACTION_FAILED): 'FAILED_TRANSACTION:` only at Android 11. Only reboot device/emulator help, What is the problem? Android 10 or prev works good.
I use Libgx fragment and problem reproduced when native android dialog closing (for example, review dialog). 
`kotlinVersion = '1.5.21'
libgdxVersion = '1.10.0'`
Thanks for help.

**Comment by obigu** [comment]
Please check https://github.com/libgdx/libgdx/wiki/Getting-help.
