### ISSUE TITLE
Android Better Mouse support

### ISSUE THREAD

**Issue by Vixeliz** [libgdx/libgdx#6677]
#### Issue details
Hello! I am curious if android could potentially get better keyboard and mouse support?  Since android oreo you are able to capture the mouse cursor(https://developer.android.com/training/gestures/movement#pointer-capture). Is there any way for libgdx to support this? It would be nice to allow people on android to use keyboard and mouse for games. 

#### Please select the affected platforms
- [ x] Android

**Comment by Zomby2D** [comment]
Keyboard and mouse is already supported on Android. Is there anything specific that's missing in the current implementation?

**Comment by Vixeliz** [comment]
Was i wrong? I didnt seem to be able to get the mouse captured on android.

**Comment by Zomby2D** [comment]
You just need to implement [InputProcessor](https://libgdx.badlogicgames.com/ci/nightlies/docs/api/com/badlogic/gdx/InputProcessor.html). If you have a USB or Bluetooth mouse and/or keyboard plugged in your Android device, you will be able to use them the same way you do with other platforms.

You can have a look at the InputTest demo from [/tests/gdx-tests/src/com/badlogic/gdx/tests/InputTest.java](https://github.com/libgdx/libgdx/blob/master/tests/gdx-tests/src/com/badlogic/gdx/tests/InputTest.java) for an example.

**Comment by Vixeliz** [comment]
Ok thank you! Sorry for the ignorance
