### ISSUE TITLE
How in NVIDIA 1660 Ti set high FPS

### ISSUE THREAD

**Issue by xcocean** [libgdx/libgdx#6686]
My graphics card is 1660 ti

In LwjglApplication.

 I set the FPS 90 is invalid, still 60
```
	public static void main (String[] arg) {
		LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
		// 默认帧率 60
		config.foregroundFPS=90;
		// 切出时帧率为30
		config.backgroundFPS=30;
		config.useGL30=true;
		new LwjglApplication(new MyGdxGame(), config);
	}
```
How do I set high FPS?

thanks!

in libgdx ：
![image](https://user-images.githubusercontent.com/45192548/138499562-115cfc96-95e8-40b0-a02f-516c45b224ef.png)

in other game：
![image](https://user-images.githubusercontent.com/45192548/138500075-d930c230-06e8-4dc0-8489-7bb3a2ff66ca.png)

**Comment by xcocean** [comment]
ok

**Comment by tommyettinger** [comment]
Why was this closed and then reopened? I would have closed it a month ago but I didn't notice @Frosty-J 's edits on the wiki, which should resolve this. @xcocean This doesn't appear to be an issue with libGDX anymore, so if you have more questions, you can [ask them on the Discord](https://discord.gg/PRpTjA68MN).
