### ISSUE TITLE
drawing 3d model. What should I do?

### ISSUE THREAD

**Issue by wuao** [libgdx/libgdx#6689]
i have many  json
    "OutLine": "[[[{\"X\":226954.42,\"Y\":129900,\"Z\":0},{\"X\":226954.42,\"Y\":128499.98,\"Z\":0},{\"X\":229304.42,\"Y\":128499.98,\"Z\":0},{\"X\":229304.42,\"Y\":129900,\"Z\":0},{\"X\":226954.42,\"Y\":129900,\"Z\":0},{\"X\":226954.42,\"Y\":129900,\"Z\":0}]]]",

i hope craete a 3d model and model is not rule

What should I do?

**Comment by mgsx-dev** [comment]
better asking on Discord : https://libgdx.com/community/
