### ISSUE TITLE
How can I check if the font file contains certain font?

### ISSUE THREAD

**Issue by mingmoe** [libgdx/libgdx#6702]
I use the `libgdx-freetype` extension to load .ttf font file.

I have multiple fonts files. And I want to load different fonts from different files.(For example,loading Japanese fonts from a Japanese font file,loading English fonts from a English font file)

But I did not find a way for libgdx-freetype to check whether the font glyph exists.

How can I do it? Thanks.

**Comment by lyze237** [comment]
Adding to that it would be cool if the generator could  support fallback fonts on its own for this reason.

**Comment by Frosty-J** [comment]
So, this is definitely hacky, but...

```java
GlyphLayout glyph = new GlyphLayout(font, char);
if (glyph.width > 0) exists = true;
else exists = false;
```

**Comment by tommyettinger** [comment]
I've written some code before to iterate something similar; it used this type of thing:
```java
public static boolean exists(BitmapFont font, char c) {
  return font.getData().getGlyph(c) != null;
}
```
Fair warning, I don't know how well this behaves if there is a non-null missingGlyph set in the font's data. This would require the BitmapFont to already have been generated by gdx-freetype, so that might be an issue in your case (not sure).

Regarding the earlier answer, `glyph.width` can be 0 in some cases, but I'm not sure if gdx-freetype correctly handles them anyway. Combining marks generally have zero width, as do the appropriately-named zero-width space, zero-width joiner, etc.

**Comment by mingmoe** [comment]
> I've written some code before to iterate something similar; it used this type of thing:
> 
> ```java
> public static boolean exists(BitmapFont font, char c) {
>   return font.getData().getGlyph(c) != null;
> }
> ```
> 
> Fair warning, I don't know how well this behaves if there is a non-null missingGlyph set in the font's data. This would require the BitmapFont to already have been generated by gdx-freetype, so that might be an issue in your case (not sure).
> 
> Regarding the earlier answer, `glyph.width` can be 0 in some cases, but I'm not sure if gdx-freetype correctly handles them anyway. Combining marks generally have zero width, as do the appropriately-named zero-width space, zero-width joiner, etc.

I noticed that the `FreeTypeFontParameter` has a `characters` field with comment "The characters the font should contain". (ref: https://github.com/libgdx/libgdx/wiki/Gdx-freetype#how-to-use-gdx-freetype-in-code)

And "generator.generateFont(parameter);" will only return the font specified in "characters" field.

It is still impossible to know whether a font file contains a glyph.

**Comment by tommyettinger** [comment]
If you want all characters present in a .ttf file, long ago in the distant past I found a Windows utility called cmaptofile. The cmap table is part of a TTF font (maybe OTF too, not sure) that stores all glyphs present in the font. The tool is easy to use; extract the one .exe file and drag+drop a .ttf font on it. It will output a .txt file in the same folder with the full contents, which you can paste directly into Hiero or the `characters` field. I am sure a similar tool could be written in Java, but no one has yet to my knowledge. Here's the zipped Windows .exe for cmaptofile:
[cmaptofile.zip](https://github.com/libgdx/libgdx/files/7575799/cmaptofile.zip)
I'd like to find the author's site again, but if I remember it right, this file was no longer linked from the main page, and was just in an unsorted pile of binaries useful for font manipulation. I also think I found the author's site from a typography forum that no longer is online.

**Comment by mingmoe** [comment]
I noticed that freetype privodes `FT_Get_Char_Index` function to check whether the font exists.

I also found the `com.badlogic.gdx.graphics.g2d.freetype` provides `getCharIndex` method.

This may only require a small modification.

Should I fix it? @Frosty-J @tommyettinger @lyze237

**Comment by Frosty-J** [comment]
Sure, why not? This isn't an informed opinion - I just like to see things happen, both good and bad.

**Comment by mingmoe** [comment]
I noticed [that](https://libgdx.com/dev/contributing/#api-changes--additions) I need modify change file.

How do I modify this file? What's the version number?

Thanks. @Frosty-J

**Comment by Frosty-J** [comment]
You can just write a brief description of your change in there when making the rest of the pull request. New changes are being written under the 1.10.1 section.

The next version should be 1.11.0 due to breaking changes, but there doesn't seem to be any rhyme or reason to libGDX version numbers for the most part so just go with 1.10.1.

**Comment by mingmoe** [comment]
Fixed. #6703 

Geart :->
