### ISSUE TITLE
Wrong exception type thrown in GWT backend ReflectionCache.forName

### ISSUE THREAD

**Issue by nojus297** [libgdx/libgdx#6708]
Documentation for `reflect.ClassReflection.forName` states that it throws `ReflectionException` and does so in native java implementation
https://github.com/libgdx/libgdx/blob/0acff984c84cf7a8765603865dadbe7ba987c8cd/gdx/src/com/badlogic/gdx/utils/reflect/ClassReflection.java#L29-L31
However, the GWT implementation throws a `RuntimeException`
 https://github.com/libgdx/libgdx/blob/0acff984c84cf7a8765603865dadbe7ba987c8cd/backends/gdx-backends-gwt/src/com/badlogic/gwtref/client/ReflectionCache.java#L49-L51

This is an inconsistency and GWTs implementation should follow the doc.

This can probably be fixed by gwt reflection cache throwing a `ClassNotFoundException`, which would get caught by 
https://github.com/libgdx/libgdx/blob/0acff984c84cf7a8765603865dadbe7ba987c8cd/backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/emu/com/badlogic/gdx/utils/reflect/ClassReflection.java#L30-L34

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [x] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by tommyettinger** [comment]
Good catch! I don't trust myself to edit reflection-related code, so I'll leave it to someone else to take a look. This seems straightforward, though, even if the internal structure of IReflectionCache (2) and ClassReflection is not straightforward.

**Comment by MobiDevelop** [comment]
I'm not sure that ClassCastException is available in the GWT java emulation, so we might just change it to catch the RuntimeException and rethrow as a ReflectionException.

**Comment by MobiDevelop** [comment]
Actually, I guess it must be if we're already catching it.

**Comment by MrStahlfelge** [comment]
This should be an easy change, do you want to file a PR @nojus297

**Comment by nojus297** [comment]
I can, PR incoming sometime then.
