### ISSUE TITLE
add the suggestion for the wiki-reader for them to add the stage.viewport.update to their resize function if things arent showing

### ISSUE THREAD

**Issue by logicminimal** [libgdx/libgdx#6710]
this is a problem that i often come by when creating a new problem, and as i dont have stage stuff properly memorized i most often cant do it, coming up with this **again** took me a hour or so.

**Comment by mgsx-dev** [comment]
it's already documented, see [wiki](https://github.com/libgdx/libgdx/wiki/Scene2d#viewport).

and please, use only discord for help (you already asked about it today on discord)
