### ISSUE TITLE
Update box2d rope joint

### ISSUE THREAD

**Issue by HAL9000Thomas** [libgdx/libgdx#6711]
The rope joint on box2d has few more features which are not available in libgdx. For example using rope tuning to modify the bending of a rope. Is it possible to get the latest box2d changes into libgdx?

#### Issue details
Update rope joint. Provide methods for setting stiffness of a rope.

#### Reproduction steps/code
1. Create a box2d rope in libgdx
2. Create a box2d rope in https://github.com/erincatto/box2d/
3. Compare rope joint possibilities 

### Comparison
current libgdx box2d: https://github.com/libgdx/libgdx/blob/master/extensions/gdx-box2d/gdx-box2d/jni/Box2D/Rope/b2Rope.cpp
latest original box2d: https://github.com/erincatto/box2d/blob/master/src/rope/b2_rope.cpp

#### Paths on libgdx
libgdx/extensions/gdx-box2d/gdx-box2d-gwt/src/com/badlogic/gdx/physics/box2d/gwt/emu/com/badlogic/gdx/physics
/libgdx/extensions/gdx-box2d/gdx-box2d/jni/Box2D

**Comment by crykn** [comment]
Duplicate of #5948.

**Comment by ice1000** [comment]
https://github.com/erincatto/box2d/blob/main/CHANGELOG.md says rope has been removed, please use distance. So we should switch to distance joints?

**Comment by ice1000** [comment]
Looks like they're different things...

**Comment by ice1000** [comment]
Fixed in my own fork, please stay tuned for an uploaded version

https://github.com/ice1000/gdx-box2d
