### ISSUE TITLE
Libgdx starts and reports an error on the Ubuntu platform

### ISSUE THREAD

**Issue by tangxiaolu0405** [libgdx/libgdx#6715]
Please ensure you have given all the following requested information in your report.

#### Issue details
The system platform is popos, the compiler is vscode, and the Java version is 11. The following exceptions will be reported at runtime
```
Inconsistency detected by ld.so: dl-lookup.c: 105: check_ match: Assertion `version->filename == NULL || ! _ dl_ name_ match_ p (version->filename, map)' failed!
```
But I have no problem using the same environment under windows

#### Version of libGDX and/or relevant dependencies
Current master (version 1.10.0).

#### Stacktrace
```java
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/home/tyq/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl/2.9.3/3df168ac74e4a8c96562cdff24ad352e255bf89c/lwjgl-2.9.3.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/home/tyq/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl/2.9.3/3df168ac74e4a8c96562cdff24ad352e255bf89c/lwjgl-2.9.3.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
Inconsistency detected by ld.so: dl-lookup.c: 105: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

#### Please select the affected platforms

- [x] Linux

**Comment by lyze237** [comment]
Either create a project with lwjgl3 or use java 8 from adoptium jdk.

Lwjgl2 is not updated anymore since years so it doesn't work with newer bundled java version in some linux repos.

**Comment by Frosty-J** [comment]
OpenJDK 8 from the repositories also works (`sudo apt install openjdk-8-` then Tab for options). Since it's not clear how to install JDKs and JREs from Adoptium (they only have Windows and macOS installers). But yeah, newer versions of at least OpenJDK on Linux don't work with LWJGL2. The nightly release of gdx-setup and the stable release of gdx-liftoff use LWJGL3, or you can upgrade an existing project as linked above.

**Comment by tangxiaolu0405** [comment]
Thanks, Use ljwgl3 to solve problems
