### ISSUE TITLE
Update lwjgl3 to 3.3.0 for M1 Mac support

### ISSUE THREAD

**Issue by piotr-j** [libgdx/libgdx#6716]
LWJGL 3.3.0 was released on Nov 15 and required changes seem to already be in, just commented out via https://github.com/libgdx/libgdx/commit/7ac239c81f7d126c3be5ad18c25bcdb2ff811fd5
Perhaps it's time to uncomment them? Upgrade seems to work as expected for me and it not working on new Macs is quite a poor look.

**Comment by tommyettinger** [comment]
I don't have an M1 Mac, so I can't test myself, but I have produced some alpha JARs of gdx-liftoff that use LWJGL 3.3.0 with 1.10.1-SNAPSHOT -- no complaints so far.
