### ISSUE TITLE
Could not resolve com.badlogicgames.gdx:gdx-backend-lwjgl3:1.10.1-SNAPSHOT

### ISSUE THREAD

**Issue by TCreutzenberg** [libgdx/libgdx#6737]
#### Issue details
Since about 15:00 GMT(+1) I cannot build my project any more with  gdxVersion '1.10.1-SNAPSHOT'.
It worked just a few minutes before that.
I already tried to clear caches, etc.

#### Reproduction steps/code
Try to build project with gdxVersion '1.10.1-SNAPSHOT'

#### Version of libGDX and/or relevant dependencies
1.10.1-SNAPSHOT

#### Stacktrace
```java
Execution failed for task ':desktop:compileJava'.
> Could not resolve all files for configuration ':desktop:compileClasspath'.
   > Could not resolve com.badlogicgames.gdx:gdx-backend-lwjgl3:1.10.1-SNAPSHOT.
     Required by:
         project :desktop
      > No matching variant of com.badlogicgames.gdx:gdx-backend-lwjgl3:1.10.1-SNAPSHOT:20211220.104956-137 was found. The consumer was configured to find an API of a library compatible with Java 7, preferably in the form of class files, and its dependencies declared externally but:
          - Variant 'apiElements' capability com.badlogicgames.gdx:gdx-backend-lwjgl3:1.10.1-SNAPSHOT declares an API of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 8 and the consumer needed a component compatible with Java 7
          - Variant 'javadocElements' capability com.badlogicgames.gdx:gdx-backend-lwjgl3:1.10.1-SNAPSHOT declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 7)
                  - Doesn't say anything about its elements (required them preferably in the form of class files)
          - Variant 'runtimeElements' capability com.badlogicgames.gdx:gdx-backend-lwjgl3:1.10.1-SNAPSHOT declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 8 and the consumer needed a component compatible with Java 7
          - Variant 'sourcesElements' capability com.badlogicgames.gdx:gdx-backend-lwjgl3:1.10.1-SNAPSHOT declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 7)
                  - Doesn't say anything about its elements (required them preferably in the form of class files)
 ```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by Trurl101** [comment]
Same error here, but on Mac OS.

**Comment by Tom-Ski** [comment]
Doing some work that is making the snapshots a bit volatile at the moment, should be fixed shortly, but if not we will revert to get snapshots alive again.

**Comment by PokeMMO** [comment]
What is the java level of your desktop project?

**Comment by Trurl101** [comment]
sourceCompatibility = 1.7

**Comment by PokeMMO** [comment]
Update that to 1.8 and try again

**Comment by Trurl101** [comment]
Same error as above.

**Comment by Tom-Ski** [comment]
Are you running from command line? If not can you try? ./gradlew desktop:run

**Comment by PokeMMO** [comment]
Try to also change `hasidesktop/build.gradle`

**Comment by TCreutzenberg** [comment]
I tried updateing to sourceCompatibility = 1.8 in all gralde files, it works now

**Comment by Trurl101** [comment]
Where did you do the change? I changed (hasi)desktop/build.gradle to 1.8 already but it did not change anything?

**Comment by Trurl101** [comment]
Ok now it works. For some reason the sourceCompatibility change in the desktop build.gradle didn't stick at first.

**Comment by TCreutzenberg** [comment]
I did a search/replace on "sourceCompatibility = 1.7" and then I did another search for only "sourceCompatibility" revealing another "sourceCompatibility = '1.7'" where it was '1.7' (with apostrophe) instead of 1.7 (without apostrophe)

**Comment by TCreutzenberg** [comment]
Should we leave this issue open for some time so other people with the same problem can find the solution?

**Comment by TCreutzenberg** [comment]
Btw guys, thanks for the quick solution! 👍

**Comment by crykn** [comment]
This behaviour is now documented [here](https://libgdx.com/news/2022/05/gdx-1-11#lwjgl-3).
