### ISSUE TITLE
Crazy resize callback in Windows OS

### ISSUE THREAD

**Issue by fgnm** [libgdx/libgdx#6785]
#### Issue details
Hey @badlogic sorry to bother you again, but I'm having troubles with this recent commit too https://github.com/libgdx/libgdx/commit/a0e584f160042d355b51558f3d43f143cb17fc84#diff-040a0bcb5d798c1906e75ea04d512d8a2ce33b694b8b1c4fe8edd6e6ffd9a2c5R73

In brief the `GLFWFramebufferSizeCallback` is called outside the main loop, this is very useful becuase the application can render and update its view when window is resized (otherwise the window content will look frozen). However with this change you post all the updates to the main loop and this will destory all benefits coming from the callback. Moreover, this create a crazy behavior becuase after the mouse is released `ApplicationListener#resize` function is called hundred times at same time which create a very bad experience. I usually get a `not responding` window while resizing becuase of this.

#### Reproduction steps/code
The issue can be reproduced easly in Windows OS with a very basic application:
```Java
    private static class TestApp implements ApplicationListener {

        @Override
        public void create() {

        }

        @Override
        public void resize(int width, int height) {
            System.out.println("Resize");
        }

        @Override
        public void render() {

        }

        @Override
        public void pause() {

        }

        @Override
        public void resume() {

        }

        @Override
        public void dispose() {

        }
    }
```
During window resize the rendering is froozen and the resize function is not called until you release the mouse. After, the resize method will be invoked hundred of times. It might produce a `no responding` window.

#### Version of libGDX and/or relevant dependencies
latest libGDX 1.10.1-SNAPSHOT

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by tommyettinger** [comment]
I confirmed this in gdx-liftoff, which also has a low FPS (about 16) and uses non-continuous rendering while minimized. I get progressively more messages printed the longer I hold down the mouse button while dragging to resize; eventually I got 250 or more on one resize. I didn't get a non-responsive window, but it was taking longer and longer for it to respond, so it could have gotten there after not many more resizes.

**Comment by fgnm** [comment]
https://user-images.githubusercontent.com/5543339/155684717-34898ba7-71c8-403c-a652-4deefeb327e2.mp4

@NathanSweet This is how looks like with latest changes

**Comment by NathanSweet** [comment]
You didn't explain what that is trying to show. If the point is that it doesn't render while resizing, that appears (having not dug into it) to be a GLFW issue.

**Comment by fgnm** [comment]
I mean, the benefit to have the `GLFWFramebufferSizeCallback` is that since the `GLFW.glfwPollEvents()` blocks the main thread we can continue rendering even during resize. If the callback is posted in the main thread we loose the ability to have a responsive window when resize (both in Windows OS and in macOS). Of course this isn't a very critical issue, but I think that also details matters in some use cases :)
For instance, this is how looks like the resize until `1.10.0` release:

https://user-images.githubusercontent.com/5543339/155725751-8a0018a4-d2a6-4b47-b9cc-2738e8c6713c.mp4
