### ISSUE TITLE
Fullscreen Mode is not set correctly with the LWJGL3 backend.

### ISSUE THREAD

**Issue by Leshy-YA** [libgdx/libgdx#6800]
#### Issue details
On a 4k screen I'm trying to set the resolution of the app to 1080p. However the result is an app with resolution of 1920x2160 - with the height doubled and only top half of the app on the screen.

On app startup Gdx.graphics returns 1920x1080 for the width and height as well as back buffer width and height. However if the same are checked in the main loop the result is 1920x2160. 

Screenshots from within the app and from the OS both result in 1920x2160.

#### Reproduction steps/code
```
public static void main(String[] args)
{		
	Lwjgl3ApplicationConfiguration config = new Lwjgl3ApplicationConfiguration();

	try
	{
		for (Graphics.DisplayMode mode : Lwjgl3ApplicationConfiguration.getDisplayModes(Lwjgl3ApplicationConfiguration.getPrimaryMonitor()))
		{
			if (mode.width == 1920 && mode.height == 1080)
			{
				config.setFullscreenMode(mode);
				break;
			}
		}

		ApplicationAdapter adapt = new ApplicationAdapter()
		{
			SpriteBatch batch;
			BitmapFont font;

			@Override
			public void create()
			{
				batch = new SpriteBatch();
				font = new BitmapFont();

				// Here resolution is 1920x1080.
				System.out.println("Resolution: " + Gdx.graphics.getWidth() + " x " + Gdx.graphics.getHeight());
			}

			@Override
			public void render()
			{
				Gdx.gl.glClearColor(.25f, .25f, .25f, 1);
				Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
				
				batch.begin();
				
				// Here resolution is 1920x2160.
				font.draw(batch, "Resolution: " + Gdx.graphics.getWidth() + " x " + Gdx.graphics.getHeight(), Gdx.graphics.getWidth() / 2, Gdx.graphics.getHeight() / 2);

				batch.end();
			}

			@Override
			public void dispose()
			{
				batch.dispose();
				font.dispose();
			}
		};
		
		new Lwjgl3Application(adapt, config);
	}
	catch(Throwable err)
	{
		err.printStackTrace();
	}		
}
```

#### Version of libGDX and/or relevant dependencies
Checked on 1.10.0, 1.10.1-SNAPSHOT as well a number of older releases.

#### Please select the affected platforms
- [ ] Windows - haven't tried yet on Windows
- [x] Linux - using X11, haven't tried yet with Wayland
- [ ] macOS

**Comment by crykn** [comment]
I can't reproduce your issue on my 1080p monitor. If someone with a 4k monitor could pinpoint this issue and find out where the wrong value comes from, that would be much appreciated. My guess would be, that it is a problem with GLFW and not libGDX itself.

**Comment by Leshy-YA** [comment]
I just checked in LWJGL 3.3.1 Hello World example. Same thing. I request fullscreen window of 1920x1080 and get 1920x2160.
It seems indeed it's a problem with GLFW. I will look there.

**Comment by crykn** [comment]
Thanks for checking it out! If you create a new issue in the LWJGL 3 or the GLFW repo, please also post the link back here.
