### ISSUE TITLE
MD5Mesh/Animation serializable + MD5 pingpong wraptype + clear-stage

### ISSUE THREAD

**Issue by badlogic** [libgdx/libgdx#681]
_From [thomas.t...@googlemail.com](https://code.google.com/u/110759639387810803479/) on January 11, 2011 00:03:43_

Hola here a patch for the 3 different issues.

1) Serialization. 
Just added 'implements Serializable' and a default serialVersionUID
2) Ping Pong + AnimationDirection
I modified the Animator-Class. Now there are 3 different WRAPMODES:
WRAPTYPE_LOOP,WRAPTYPE_CLAMP,WRAPTYPE_PINGPONG 
LOOP and CLAMP were implemented before I added PINGPONG which changes the direction back to the start where it changes again (framecount like this: 1234321234...)

And as I needed it for the pingpong you now can change the animation-direction as well! Don't have a real usecase for this know, but some creative people might need it ;D. You can change the direction with setAnimationDirection(ANIMDIR_FORWARD/ANIMDIR_BACKWARD). I hope there are no sideeffect with die KeyframedModel. I didn't know exactly what it is for but it should be fine.

3) I need a way to clear the whole stage! there for I added in Group a method removeActors() which clears groups and actors list. This method is called by the clearStage() method in stage!

Hope, the changes are ok for you and sry for creating one issue for actually three...ToM

_Original issue: http://code.google.com/p/libgdx/issues/detail?id=93_

**Comment by elect86** [comment]
Hi, 

I'm working on an Assimp porting [here](https://github.com/kotlin-graphics/assimp).. may be of interest?
