### ISSUE TITLE
use activityResultRegistry in libgdx for android

### ISSUE THREAD

**Issue by CoderoidAcademy** [libgdx/libgdx#6834]
hi, how i can use `activityResultRegistry` in activity that extend from` AndroidApplication`?

#### problem is:
my class (activity) is

`class InAppBlillingBazaar: AndroidApplication() {}`

`AndroidApplication` class extend from `Activity`, but `activityResultRegistry` exist in `AppCompatActivity`. and i cant edit `AndroidApplication` because its part of libgdx libs.

`public class AndroidApplication extends Activity implements AndroidApplicationBase {}`

Can anyone solve this?

**Comment by MobiDevelop** [comment]
I think you can instead use AndroidFragmentApplication to drop the libgdx app into an AppCompatActivity.

**Comment by MobiDevelop** [comment]
Closing this out, if using AndroidFragmentApplication didn't work, feel free to reopen it.
