### ISSUE TITLE
[GWT] Java heap exception during compilation

### ISSUE THREAD

**Issue by yuripourre** [libgdx/libgdx#6848]
#### Issue details
It's not possible to have big assets in the assets folder for html. GWT throws a Java heap exception during compilation.

@mgsx-dev was very kind and found the problem, it is happening during md5 calculation, specifically this line: 
https://github.com/libgdx/libgdx/blob/665f920902e543856fdd7d496f6ec422affd46d1/backends/gdx-backends-gwt/src/com/badlogic/gdx/backends/gwt/preloader/PreloaderBundleGenerator.java#L170

#### Reproduction steps/code
Create a libGDX project and add a huge asset to the assets folder (I tried with a 300MB gltf file with 4k textures) and run `./gradlew html:dist`

#### Version of libGDX and/or relevant dependency 
1.10.0 and probably older versions too

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [X] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by yuripourre** [comment]
One possible solution mentioned by @mgsx-dev on Discord is buffering the file: https://stackoverflow.com/questions/9321912/very-slow-to-generate-md5-for-large-file-using-java

**Comment by tommyettinger** [comment]
Having very large files in an HTML project seems like a recipe for sky-high server bills. I think even GitHub Pages restricts bandwidth past some point (and I know I've hit the limit for a repo size before, which is not that much higher than that file's size). Buffering seems like a solution, but I'm not really sure it's a problem that we need to solve. Just the amount of time it takes for users to download a 300MB asset could be, depending on connection, hours...

**Comment by yuripourre** [comment]
@tommyettinger I am testing a lot of examples running it locally, I point my Oculus to localhost. I know that it's a very specific use-case but if you think that worth improving it I can think about fixing it.

**Comment by yuripourre** [comment]
@tommyettinger good to know that, thanks for the tip. As I mentioned is mostly local tests but I will keep that in mind.

**Comment by MobiDevelop** [comment]
Is it possible to use a DigestInputStream while copying the files from /assets to the output directory, then just rename the file afterward to include the hash?

**Comment by MobiDevelop** [comment]
I just tried it... I dropped a 6.5GB file into assets and ran a build with no issues (aside from it being exceedingly slow to copy a 6.5GB file multiple times but I wanted to try a ridiculously large file, because why not. I can put up a PR for review, it's pretty simple.
