### ISSUE TITLE
Rich Text

### ISSUE THREAD

**Issue by jootnet** [libgdx/libgdx#6856]
Have any plan to build a rich text display widget, like Color Markup Language, but also have underline/super link.

**Comment by Frosty-J** [comment]
There's https://github.com/tommyettinger/textratypist which offers underline, superscript and more. I don't think it has anything for hyperlinks specifically, @tommyettinger?

**Comment by jootnet** [comment]
thanks, I'll get a look.

**Comment by jootnet** [comment]
I also have a suggest that the property 'markupEnabled' should bind to Widget like Label/TextField/TextArea.

Currently on BitmapFontData, if using one BitmapFont(same .fnt) in two widget(one for input, no colouration), then ugly...

**Comment by tommyettinger** [comment]
@Frosty-J Hyperlinks would be... interesting. They're defined by their behavior on a click, and behavior would either have to be quite limited (only open a link in the browser, for instance) or very complicated and configured with more than just the text markup.

**Comment by raeleus** [comment]
I usually fake those with a blue TextButton style that adds an underline background when the mouse is over it:
![image](https://user-images.githubusercontent.com/12948924/165000593-b232403b-22a8-4575-9411-1ef77b802fed.png)
