### ISSUE TITLE
1.11.0 can't be found on gradlePluginPortal()

### ISSUE THREAD

**Issue by Adriankhl** [libgdx/libgdx#6865]
The following message appears when I did `./gradlew clean test` on my project after upgrading libgdx to 1.11.0:

```
Execution failed for task ':gdx-android:compileFreeDebugKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':gdx-android:compileFreeDebugKotlin'
   > Could not resolve all files for configuration ':gdx-android:freeDebugCompileClasspath'.
      > Failed to transform gdx-backend-android-1.11.0.jar (com.badlogicgames.gdx:gdx-backend-android:1.11.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=7, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
         > Could not find gdx-backend-android-1.11.0.jar (com.badlogicgames.gdx:gdx-backend-android:1.11.0).
           Searched in the following locations:
               https://plugins.gradle.org/m2/com/badlogicgames/gdx/gdx-backend-android/1.11.0/gdx-backend-android-1.11.0.jar
```

I did try to remove `~/.gradle` and `~/.m2` and rebuild the project but got the same error message. Therefore I suspect that the jar itself is corrupted.

**Comment by tommyettinger** [comment]
I don't really target Android, so I could be way off, but a snippet of that error contains `org.gradle.jvm.version=7` . This looks very similar to a Gradle error that can happen to LWJGL3 projects that are using JVM version 7, and I'm wondering if the Android backend may have been built with compatibility for 8 (like LWJGL3).

**Comment by Adriankhl** [comment]
Hi @tommyettinger, unfortunately it doesn't help. Actually, my compatibility java version for android has always been 11 (latest android gradle plugin support that):
```
    compileOptions {
        sourceCompatibility(JavaVersion.VERSION_11)
        targetCompatibility(JavaVersion.VERSION_11)
    }
```

And it works well for `1.10.0`, that's why I suspect that something is wrong in the jar files at the maven repository.

**Comment by tommyettinger** [comment]
I'm not sure what could be wrong with the JAR files that I just downloaded as well and successfully built with...

Oh.

It's only searching one repo for the backend, which it definitely won't find at gradlePluginPortal(). It seems to only check:
```
               https://plugins.gradle.org/m2/com/badlogicgames/gdx/gdx-backend-android/1.11.0/gdx-backend-android-1.11.0.jar
```
Which is Gradle's plugin distribution site, and only hosts Gradle plugins (not libGDX). Can you paste any `repositories` sections of your root and Android `build.gradle` files?

**Comment by Adriankhl** [comment]
Here is my `repositories`

```
allprojects {
    repositories {
        gradlePluginPortal()
        mavenLocal()
        mavenCentral()
        google()
        maven { url = uri("https://oss.sonatype.org/content/repositories/snapshots/") }
        maven { url = uri("https://oss.sonatype.org/content/repositories/releases/") }
    }
}
```

In principle, it should search in `mavenCentral()`

**Comment by tommyettinger** [comment]
I don't think gradlePluginPortal() is needed at all for the allprojects repositories. It should only be needed by the buildscript repositories, and might not even be needed there. I've had all kinds of weird issues with Gradle checking only one repository and abruptly stopping its search, though mostly that happens when it has found part of a dependency in mavenLocal(), but not enough. I'd try removing or commenting out gradlePluginPortal() there, then if that doesn't work, removing mavenLocal() too.

**Comment by Frosty-J** [comment]
For what it's worth, gdx-setup puts `gradlePluginPortal()` after `mavenCentral()`, which I reckon should attempt to download from [Maven/gdx-backend-android-1.11.0.jar](https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-backend-android/1.11.0/gdx-backend-android-1.11.0.jar) instead. I'm unsure why [Gradle/gdx-backend-android-1.10.0.jar](https://repo.gradle.org/ui/native/jcenter/com/badlogicgames/gdx/gdx-backend-android/1.10.0/gdx-backend-android-1.10.0.jar) is a perfectly valid download but [Gradle/gdx-backend-android-1.11.0.jar](https://repo.gradle.org/ui/native/jcenter/com/badlogicgames/gdx/gdx-backend-android/1.11.0/gdx-backend-android-1.11.0.jar) isn't. Mine seems happy regardless of order, but something's probably cached now.

**Comment by Adriankhl** [comment]
Thanks a lot. It now working after removing `gradlePluginPortal()` from `allprojects`, putting `gradlePluginPortal()` after `mavenCentral()` also works too. I will change the title and close this issue.
