### ISSUE TITLE
JAR files of 1.11.0 Android libraries are missing from Jcenter

### ISSUE THREAD

**Issue by yairm210** [libgdx/libgdx#6867]
#### Issue details
Cannot build Android app with gdx version 1.11.0 due to missing jar in jcenter

```
Execution failed for task ':android:copyAndroidNatives'.
> Could not resolve all files for configuration ':android:natives'.
   > Could not find gdx-platform-1.11.0-natives-arm64-v8a.jar (com.badlogicgames.gdx:gdx-platform:1.11.0).
     Searched in the following locations:
         https://plugins.gradle.org/m2/com/badlogicgames/gdx/gdx-platform/1.11.0/gdx-platform-1.11.0-natives-arm64-v8a.jar
   > Could not find gdx-platform-1.11.0-natives-x86.jar (com.badlogicgames.gdx:gdx-platform:1.11.0).
     Searched in the following locations:
         https://plugins.gradle.org/m2/com/badlogicgames/gdx/gdx-platform/1.11.0/gdx-platform-1.11.0-natives-x86.jar
   > Could not find gdx-platform-1.11.0-natives-x86_64.jar (com.badlogicgames.gdx:gdx-platform:1.11.0).
     Searched in the following locations:
         https://plugins.gradle.org/m2/com/badlogicgames/gdx/gdx-platform/1.11.0/gdx-platform-1.11.0-natives-x86_64.jar


  > Could not resolve all files for configuration ':android:debugCompileClasspath'.
      > Failed to transform gdx-backend-android-1.11.0.jar (com.badlogicgames.gdx:gdx-backend-android:1.11.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=7, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
         > Could not find gdx-backend-android-1.11.0.jar (com.badlogicgames.gdx:gdx-backend-android:1.11.0).
           Searched in the following locations:
               https://plugins.gradle.org/m2/com/badlogicgames/gdx/gdx-backend-android/1.11.0/gdx-backend-android-1.11.0.jar
 ```
That last URL, for example, redirects to [this one](https://repo.gradle.org/ui/native/jcenter/com/badlogicgames/gdx/gdx-backend-android/1.11.0/gdx-backend-android-1.11.0.jar) which throws a 404 error.

Oddly enogh the [folder](https://repo.gradle.org/ui/native/jcenter/com/badlogicgames/gdx/gdx-backend-android/1.10.0/) does exist, and contains a link to the JAR file, which means it knows it's supposed to be there but just can/t find the file. MAybe there was a problem with uploading it?

[1.10.0 version of that url](https://repo.gradle.org/ui/native/jcenter/com/badlogicgames/gdx/gdx-backend-android/1.10.0/gdx-backend-android-1.10.0.jar) returns a jar as expected.

Not sure if [this line](https://github.com/libgdx/libgdx/runs/6394775540?check_suite_focus=true#step:9:893) in actions is relevant but it's the closest I found

Gradle looks like:

```kotlin
project(":android") {
    apply(plugin = "com.android.application")
    apply(plugin = "kotlin-android")

    val natives by configurations.creating

    dependencies {
        "implementation"(project(":core"))
        "implementation"("com.badlogicgames.gdx:gdx-backend-android:$gdxVersion")
        natives("com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-armeabi-v7a")
        natives("com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-arm64-v8a")
        natives("com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-x86")
        natives("com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-x86_64")
    }
}
```

and worked fine for 1.10.0

#### Reproduction steps/code
I assume any Android project won't build with 1.11.0, and if that's not the case I'm interested in seeing how they work so I can adapt :)

#### Version of libGDX and/or relevant dependencies
1.11.0

#### Please select the affected platforms
- [x] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by tommyettinger** [comment]
JCenter has been offline for almost a year now, and Gradle has warned if you use it for about as long. Please remove any occurrence of `jcenter()` in your repositories, since libGDX is uploaded (and always has been) to mavenCentral() . This issue looks like it is exactly the same as #6865 , and you should follow the same steps there -- either remove gradlePluginPortal(), or move it to the end of the repositories block. I don't know why we have had multiple projects encounter gradlePluginPortal() being first in the list, but it's some kind of mistake somewhere.

I'm closing because this looks identical to #6865 ; if it isn't and the steps at the end of that thread don't help, please comment again or reopen.
