### ISSUE TITLE
Linux audio issues on flatpak intellij build

### ISSUE THREAD

**Issue by ltade** [libgdx/libgdx#6875]
#### Issue details
Running fresh libgdx project in IntelliJ IDEA Community seems to have some issues with audio. After following guide from https://libgdx.com/wiki/start/a-simple-game audio does not work.
note that fedora, by default, ships with pipewire instead if pulseaudio, and that _may_ be the main problem.

#### Reproduction steps/code
1. Install all system updates
2. Install IntelliJ IDEA Community from flatpak
3. [download](https://libgdx.com/wiki/start/project-generation) gdx-setup.jar
4. Install java-18-openjdk and use it run gdx-setup.jar (built in jdk doesnt work for some reason)
5. unmark Android platform and click Generate
6. open the generated project with intellij, wait for setup process
7. Add Configuration > Add new > Application
8. JRE > java 17 corretto-17 (can also use jre 18, no difference)
9. module classpath > [name].desktop.main
10. Main class > com.mygdx.game.DesktopLauncher
11. Apply, OK
12. Shift-10 (Run) (The error messages appears)
13. follow https://libgdx.com/wiki/start/a-simple-game guide fully (The audio doesn't work)

#### Version of libGDX and/or relevant dependencies
[Gdx version] 1.11.0

#### Stacktrace
```java
Executing ':desktop:DesktopLauncher.main()'...

> Task :core:compileJava UP-TO-DATE
> Task :core:processResources NO-SOURCE
> Task :core:classes UP-TO-DATE
> Task :core:jar UP-TO-DATE
> Task :desktop:compileJava UP-TO-DATE
> Task :desktop:processResources UP-TO-DATE
> Task :desktop:classes UP-TO-DATE

> Task :desktop:DesktopLauncher.main()
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
ALSA lib ../../pulse/pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

```

#### Please select the affected platforms
- [x] Linux Fedora 36 VM
- [ ] Linux MInt VM (Not tested yet)
- [ ] Linux Ubuntu VM (Not tested yet)

**Comment by lyze237** [comment]
Just note that Fedora now comes with Pipewire and not Pulseaudio.

**Comment by Frosty-J** [comment]
We concluded on Discord that Ubuntu and Manjaro have the following output in 1.11.0, as I noted in December (#6728), but otherwise work fine:

```
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
```

That doesn't help determine why PulseAudio fails to connect on Fedora, but I thought it's relevant to this thread.

**Comment by tommyettinger** [comment]
I just tested this on Manjaro Linux, with the attached project. I get audio just fine, and I also get the two "Failed to set real-time priority" messages mentioned earlier. I'm not terribly experienced with Manjaro, despite using it for a few years, so I don't know if I'm using PulseAudio or something else.
[AudioTest.zip](https://github.com/libgdx/libgdx/files/8748194/AudioTest.zip)

**Comment by lyze237** [comment]
I just tried with a default fedora workstation 36 installation on my laptop and it works fine without install any other packages:

* Install fedora
* Install jdk 17 via yum
* Setup a project with liftoff
* Play music in create: [Test.zip](https://github.com/libgdx/libgdx/files/8748273/Test.zip)
* Run it with gradle

By default those packages were installed (Related to PA/PW):
```
[lyze@fedora Java]$ yum list --installed | grep pipe
libpipeline.x86_64                                   1.5.5-2.fc36                        @anaconda    
pipewire.x86_64                                      0.3.49-1.fc36                       @anaconda    
pipewire-alsa.x86_64                                 0.3.49-1.fc36                       @anaconda    
pipewire-gstreamer.x86_64                            0.3.49-1.fc36                       @anaconda    
pipewire-jack-audio-connection-kit.x86_64            0.3.49-1.fc36                       @anaconda    
pipewire-libs.x86_64                                 0.3.49-1.fc36                       @anaconda    
pipewire-pulseaudio.x86_64                           0.3.49-1.fc36                       @anaconda    
pipewire-utils.x86_64                                0.3.49-1.fc36                       @anaconda    
[lyze@fedora Java]$ yum list --installed | grep pulse
gvncpulse.x86_64                                     1.3.0-2.fc36                        @anaconda    
pipewire-pulseaudio.x86_64                           0.3.49-1.fc36                       @anaconda    
pulseaudio-libs.x86_64                               15.0-5.fc36                         @anaconda    
pulseaudio-libs-glib2.x86_64                         15.0-5.fc36                         @anaconda    
[lyze@fedora Java]$ 
```

**Comment by Frosty-J** [comment]
I found a few other instances of this online.

* Fedora: [https://redd.it/j0euno](https://www.reddit.com/r/libgdx/comments/j0euno/unable_to_connect_to_pulseaudio_error/)
* Majaro: [https://stackoverflow.com/q/71892472](https://stackoverflow.com/questions/71892472/libgdx-in-manjaro-linux-pulseaudio-unable-to-connect-connection-refused)
* Pop!_OS: [https://stackoverflow.com/q/71407944](https://stackoverflow.com/questions/71407944/pulseaudio-unable-to-connect-connection-refused-in-libgdx)

However, none of these people ever responded to say if they got it fixed. Two answers say to install the `libpulse-dev`, `pulseaudio` and `apulse` packages.

**Comment by lyze237** [comment]
Yeah from debugging a bit in discord, this seems to be a general issue with flatpack and it seems like that there's some missing configs for it to work.

Basically from what I can see the PA client tries to connect too the PA server socket in a wrong location and you'd need to tell it to connect to the proper one. No clue how though.
