### ISSUE TITLE
isPointInTriangle returning true when it shouldn't

### ISSUE THREAD

**Issue by tylerhasman** [libgdx/libgdx#6882]
#### Issue details

[Intersector#isPointInTriangle](https://github.com/libgdx/libgdx/blob/8ead46fa94c9467138dc9edf0f0a2c04831fcb99/gdx/src/com/badlogic/gdx/math/Intersector.java#L48) fails for points lying on the plane of the triangle but not within it due to a floating-point rounding error in some cases.

The last check if the function:

`if (ab * bc - ac * bb < 0) return false;`

is sometimes having its arithmetic being rounded to 0.0 causing the function to return true even though the answer should be false.

#### Reproduction steps/code

```
Intersector.isPointInTriangle(
                new Vector3( -5120.8345f,8946.126f,-3270.5813f),

                new Vector3(50.008057f, 22.20586f, 124.62208f),

                new Vector3( 62.282288f, 22.205864f, 109.665924f),

                new Vector3(70.92052f, 7.205861f, 115.437805f))
```
will return true even though the point is clearly not in the triangle.

#### Version of libGDX and/or relevant dependencies
Tested on version 1.10.0 however should still be failing on all versions

**Comment by tylerhasman** [comment]
I've created a more accurate function which can I've confirmed works for larger numbers:
```

    public static boolean SAFE_isPointInTriangle(Vector3 point, Vector3 t1, Vector3 t2, Vector3 t3){

        Vector3 a = t1.cpy();
        Vector3 b = t2.cpy();
        Vector3 c = t3.cpy();

        a.sub(point);
        b.sub(point);
        c.sub(point);

        Vector3 u = b.cpy().crs(c);
        Vector3 v = c.cpy().crs(a);
        Vector3 w = a.cpy().crs(b);

        if(u.dot(v) < 0f){
            return false;
        }

        if(u.dot(w) < 0f){
            return false;
        }

        return true;
    }

```

**Comment by tommyettinger** [comment]
Nice, I can confirm it works for the original input as well. Your code allocates 6 Vector3 instances on each call, which isn't terrible but is avoidable. Here's a rearrangement of your code that I believe uses the same exact algorithm, but reuses the three temporary Vector3 instances that Intersector has for this purpose.

```java
    // These are declared in Intersector, and can be used by any code put into that class.
    private final static Vector3 v0 = new Vector3();
    private final static Vector3 v1 = new Vector3();
    private final static Vector3 v2 = new Vector3();

    // This is a non-allocating version of tylerhasman's code; it uses the same algorithm.
    public static boolean SAFE_isPointInTriangle(Vector3 point, Vector3 t1, Vector3 t2, Vector3 t3){
        v0.set(t1).sub(point);
        v1.set(t2).sub(point);
        v2.set(t3).sub(point);

        v1.crs(v2);
        v2.crs(v0);

        if(v1.dot(v2) < 0f) return false;
        v0.crs(v2.set(t2).sub(point));
        return (v1.dot(v0) >= 0f);
    }
```

I'm not 100% I got this correct, so if anyone wants to try this on more example points, that would be great! It could be really good to know an approximate safe range for points to pass to this method.

**Comment by tylerhasman** [comment]
@tommyettinger Thanks for cleaning up my code! That looks good to me. I like the tiny optimization you made of not calculating w until its needed. 

Later today I might check some more values to see how well this works in my game engine.

**Comment by tylerhasman** [comment]
Looks like this new function that @tommyettinger created is working well.
