### ISSUE TITLE
Incorrect viewport size after window resizing on macOS with HDPIMode.Logical

### ISSUE THREAD

**Issue by 00-Evan** [libgdx/libgdx#6888]
Seems to be caused by commit a5286e70f1ee279859ee8e8cc798b8444d458aaf , specifically where:
`gl20.glViewport(0, 0, width, height);`
was replaced with
`gl20.glViewport(0, 0, getWidth(), getHeight());`

This results in the viewport size being set to logical pixels and not true pixels, which results in incorrect dimensions if display scaling is not 1. Some gl operations (viewport, scissor, etc) require true pixels in all cases.

I can reproduce this on my M1 mac (display scale of 2), the viewport renders in the bottom-left quadrant of the window. As a temporary workaround I can call `Gdx.gl.glViewport(0, 0, Gdx.graphics.getBackBufferWidth(), Gdx.graphics.getBackBufferHeight());` in my application's resize method.

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [X] macOS

**Comment by tommyettinger** [comment]
I don't have any machines that I could encounter this on, but maybe @NathanSweet could take a look at the changes he committed and explain what's happening in that code? It used `width, height` before, changed to `getWidth(), getHeight()`, and maybe should use the back buffer's width and height instead?

**Comment by crykn** [comment]
https://github.com/libgdx/libgdx/commit/a5286e70f1ee279859ee8e8cc798b8444d458aaf fixes one of the issues introduced by https://github.com/libgdx/libgdx/commit/76a4e18e5120c8c8e0198707d68101c543b3a2c4, but in turn breaks not only viewport sizes with display scaling, but rendering during resizing as well (see #6808). We need to figure out what the cause for badlogics original bug is (and whether it happens on all platforms and even without the glfw-awt-macos extension). Then we could ideally revert both of those commits.

**Comment by obigu** [comment]
Maybe `HdpiUtils.glViewport()` is what we're looking for once we know what motivated the change in the first place.

**Comment by 00-Evan** [comment]
Use of HdpiUtils is possible here, but it seems unnecessary when LWJGL3 is already providing the width and height in true pixels as part of the resize callback, here's the method header comment for GLFWFramebufferSizeCallback.invoke:

```
Will be called when the framebuffer of the specified window is resized.
Params:
window – the window whose framebuffer was resized
width – the new width, in pixels, of the framebuffer
height – the new height, in pixels, of the framebuffer
```

**Comment by obigu** [comment]
True, that should work if we execute `resize()` on every callback but what I guess happened here is that after the change to only call `resize()` once on current frame (skipping any other calls with updated sizes) and delay it with a Runnable to next frame, the size provided by `width` and `height` could be wrong in some cases so the way to be consistent was to abotain it from `getWidth()` and `getHeight()`. If the fix to skip callback calls is good (I don't know about that) I think the solution is to use `HdpiUtils`.

**Comment by NathanSweet** [comment]
Sorry I'm a bit late. The runnable is only posted once (the first time) so we need to get the latest width/height rather than use the method parameters.

`getWidth` and `getHeight` return the logical size depending on `window.getConfig().hdpiMode`. We can use `backBufferWidth` and `backBufferHeight` instead:
```
gl20.glViewport(0, 0, backBufferWidth, backBufferHeight);
```

**Comment by crykn** [comment]
@00-Evan did Nate's commit fix this for you?

**Comment by 00-Evan** [comment]
Just tested with 1.11.1-SNAPSHOT and the issue seems to be resolved, thanks.
