### ISSUE TITLE
[iOS] OpenGL backend not working on arm64 simulator (silicon)

### ISSUE THREAD

**Issue by Berstanio** [libgdx/libgdx#6895]
The OpenGLES iOS backend is not working on arm64 simulators. The following message gets spammed:
`'cyclone' is not a recognized processor for this target (ignoring processor)`
and after the launch the App crashes (at least in my test app, I tried this one: https://github.com/Berstanio/chigginblazzder)
This is also not libGDX related, so unfortunately it looks like there is no way to fix this: https://developer.apple.com/forums/thread/658330

As a workaround either the MetalANGLE backend can be used or running the simulator with rosetta. 
This should be probably documented somewhere, but I wouldn't know where to do this best.

**Comment by crykn** [comment]
The Importing & Running docs may be a good place to mention this: https://github.com/libgdx/libgdx.github.io/blob/dev/wiki/start/import-and-running.md#ios
