### ISSUE TITLE
mouseOverActor and pointerOverActors are not cleared in Stage#clear()

### ISSUE THREAD

**Issue by Azzurite** [libgdx/libgdx#6910]
I would assume that when I call [`Stage#clear()`](https://github.com/libgdx/libgdx/blob/bf32f0fbebeab7df0b0f257ea0fd3d9fbc549eff/gdx/src/com/badlogic/gdx/scenes/scene2d/Stage.java#L591-L595) or [`Stage#dispose()`](https://github.com/libgdx/libgdx/blob/bf32f0fbebeab7df0b0f257ea0fd3d9fbc549eff/gdx/src/com/badlogic/gdx/scenes/scene2d/Stage.java#L841-L845), that all references to `Actor`s in the `Stage` are cleared. 

However, that is not the case. If the fields [`private final Actor[] pointerOverActors = new Actor[20];`](https://github.com/libgdx/libgdx/blob/bf32f0fbebeab7df0b0f257ea0fd3d9fbc549eff/gdx/src/com/badlogic/gdx/scenes/scene2d/Stage.java#L75) or [`private @Null Actor mouseOverActor;`](https://github.com/libgdx/libgdx/blob/bf32f0fbebeab7df0b0f257ea0fd3d9fbc549eff/gdx/src/com/badlogic/gdx/scenes/scene2d/Stage.java#L80) contain a reference to an `Actor`, those persist until the next call of [`Stage#act(float)`](https://github.com/libgdx/libgdx/blob/bf32f0fbebeab7df0b0f257ea0fd3d9fbc549eff/gdx/src/com/badlogic/gdx/scenes/scene2d/Stage.java#L193-L227).

I think `Stage#clear()` should set these fields to `null`.

---

Context: I had the problem that I called `Stage.dispose`, assuming that its children would get garbage-collected. However, that didn't happen as long as I kept a reference to the `Stage` itself. Only when I let go of the reference to the stage (or called `act()` one last time) did the memory the children used actually become available.

**Comment by tommyettinger** [comment]
This sounds like a real issue. @NathanSweet , master and commander of scene2d.ui, do you see any problems with assigning `null` to stored references in `clear()`, and maybe calling `dispose()` and nullifying references in `dispose()`? This seems like it could be a source of leaks, and `pointerOverActors` and `mouseOverActor` are both private, so the fix would need to be in libGDX code.

**Comment by NathanSweet** [comment]
Can give the PR a little time to see if anyone finds issues with it.
