### ISSUE TITLE
config.useHaptics can't be referenced in IOSLauncher

### ISSUE THREAD

**Issue by wangdong20** [libgdx/libgdx#6912]
Please ensure you have given all the following requested information in your report.

#### Issue details
config.useHaptics can't reference in IOSLauncher after I installed the MobiVM.

#### Reproduction steps/code
Install the MobiVM, add RoboVM iOS configuration.
Open IOSLauncher, can't reference config.useHaptics

#### Version of libGDX and/or relevant dependencies
1.11.0

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
iOS

**Comment by obigu** [comment]
Haptics feature will be available on next release. You can use the `1.11.1-SNAPSHOT` version if you need it now.

**Comment by wangdong20** [comment]
> Haptics feature will be available on next release. You can use the `1.11.1-SNAPSHOT` version if you need it now.

I just start libgdx with gdx-setup jar, the IOSLauncher code just write as a template code, why it use unavailable feature based on the gdx version in gradle file.

**Comment by obigu** [comment]
Oh! right, should not be on Gdx Setup (at least not yet). You can safely remove it. I'll make a PR with a fix. Thanks!
