### ISSUE TITLE
fix https://libgdx.badlogicgames.com/ci/nightlies

### ISSUE THREAD

**Issue by itsPrime3** [libgdx/libgdx#6923]
I needed to download gdx.jar (not sources). The link i knew was https://libgdx.badlogicgames.com/ci/nightlies , but now gives "503 Service Temporary Unavailable" . Please fix the link .

**Comment by crykn** [comment]
The jar files can be downloaded here: https://repo1.maven.org/maven2/com/badlogicgames/gdx/

**Comment by itsPrime3** [comment]
> The jar files of released versions can be downloaded here: https://repo1.maven.org/maven2/com/badlogicgames/gdx/

Thanks .

**Comment by itsPrime3** [comment]
> The jar files of released versions can be downloaded here: https://repo1.maven.org/maven2/com/badlogicgames/gdx/

can you also send links of all .so files , please ?

**Comment by Frosty-J** [comment]
`.so`s are in the `gdx-platform` section of that.
