### ISSUE TITLE
Text Tooltip width is invalid.

### ISSUE THREAD

**Issue by Leshy-YA** [libgdx/libgdx#6925]
#### Issue details
TextTooltip doesn't scale properly to the text contained.
It will either have always the size of the **wrapWidth** set in the style (with a lot of white space if text is too small).
Or the tooltip will cover the whole width of the screen if **wrapWidth** not set.

![v_10](https://user-images.githubusercontent.com/3486589/178849308-fa601d20-bdfb-4b96-b5de-96e8c2b82306.png)
![v_11_a](https://user-images.githubusercontent.com/3486589/178849311-535d97c7-d732-4c4a-bc5c-96477b05d7c7.png)
![v_11_b](https://user-images.githubusercontent.com/3486589/178849313-cc503539-2b8d-43e0-adb4-9ac88d9774b8.png)

#### Reproduction steps/code
```
// Create tooltip style.
TextTooltip.TextTooltipStyle tooltip_style = new TextTooltip.TextTooltipStyle();

// Boilerplate for setting up the style.
tooltip_style.label = label_style;
tooltip_style.background = region;

// This value has an impact. This will the width of the tooltip background. If not set it will cover the whole screen.
tooltip_style.wrapWidth = 100.0f;

// Some actor created earlier.
button.addListener(new TextTooltip("TOOLTIP", tooltip_style)));
```

#### Version of libGDX and/or relevant dependencies
Broken in 1.11. 1.10 works fine.
Probably the change that causes this: https://github.com/libgdx/libgdx/commit/c4cd28f15bc85639695739ce522cdd10ac33fd1c

#### Please select the affected platforms
- [x] Windows
- [x] Linux

**Comment by tommyettinger** [comment]
This sure looks like a bug. I am guessing there's some intended way to use Tooltips and wrapWidth that I don't know of... @NathanSweet , do you have any ideas on why Tooltip behavior changed in 1.10.0 ? I know I made changes in my code to match 1.11.0's different behavior, but that was a while ago, and I don't recall specifics.

**Comment by subchannel13** [comment]
Hi! I'd like to get the benefit of this bug fix but the version has not been released yet (for almost a year). For now the moment manually unsetting wrap and container fill seems to work:
```
addListener(TextTooltip("Test", app.skin.tooltip).apply {
    container.actor.wrap = false
    container.fill(false, false)
})
```
