### ISSUE TITLE
Hiero run fails on linux

### ISSUE THREAD

**Issue by pistolparody** [libgdx/libgdx#6926]
I'm trying to run Hiero and I get this:
```
─$ java -jar runnable-hiero.jar 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Inconsistency detected by ld.so: dl-lookup.c: 105: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

**Comment by crykn** [comment]
Since @maxqxam doesn't seem to be complaining, I suppose this is fixed. Apart from that, the behaviour is documented [in the wiki](https://libgdx.com/wiki/tools/hiero#running-hiero) and caused by #6088 and ultimately #6190.
