### ISSUE TITLE
Tiled 1.9 "type" converted to "class"

### ISSUE THREAD

**Issue by Quillraven** [libgdx/libgdx#6934]
I am just wondering if anyone else is facing a similar issue. When upgrading to Tiled 1.9 the previous "type" information of a MapObject is no longer loaded in LibGDX. I guess it is related to this change:

![image](https://user-images.githubusercontent.com/93260/180390794-e3ec8e3b-7d88-49e2-b616-356439302029.png)

I notice that the .tmx file now stores a "class" information instead of a type but it seems like LibGDX is not loading this info at all? At least I cannot find it.

Is this simply not supported at the moment and we have to work with Tiled <1.9 or am I doing something wrong?

**Comment by tommyettinger** [comment]
I'd use that compatibility option if you use Tiled 1.9 or higher. This is tricky since we might need to parse both "class" and "type" to be compatible with existing Tiled maps.

**Comment by Quillraven** [comment]
Okay thanks. I could not figure out how to set the first time but I will look into it again. I guess since I only have a map without a project I couldn't set it. Guess I need a project as well :D

**Comment by LuoiZQ** [comment]
You can replace the class in the exported tmx file with type. This method solves the problem that the gdx program cannot read the class, but note that the class will be changed back to the class after editing with tiled again.

**Comment by SimonIT** [comment]
There is already #7007

**Comment by Quillraven** [comment]
There was a discussion also in Tiled repo because this change broke a couple of things also for non LibGDX users. I cannot remember if Björn wanted to revert this change or if he keeps it.

I would check that once more before merging the linked PR because maybe the PR is not needed.

**Comment by MobiDevelop** [comment]
Here's the discussion on the Tiled repo, for reference: https://github.com/mapeditor/tiled/issues/3492
