### ISSUE TITLE
Updated Info: This game runs quite well for most, however it still suffers from a %36 performance tax compared to **Windows which gives 75fps under 4k while Linux only provides 55fps**. To resolve this (assuming you have less then 60fps) you may need to run at a slightly lower resolution such as 1800p.

### ISSUE THREAD

**Issue by Ghoai171** [libgdx/libgdx#6950]
Updated Info: This game runs quite well for most, however it still suffers from a %36 performance tax compared to **Windows which gives 75fps under 4k while Linux only provides 55fps**. To resolve this (assuming you have less then 60fps) you may need to run at a slightly lower resolution such as 1800p.

The game can also experience performance drops in certain areas of hectic combat and explosions which affect proton more then windows in comparison. At present MIC or voice chat may not work for you which hopefully is resolved in the future_. (there is no voice chat indicator for yourself ingame, you must ask other players if it works)_ 

My Configuration: 4k (1800p ingame) with a second 1080p monitor on the side for reference. 

System Information: [Pop_OS Specs.txt](https://github.com/ValveSoftware/Proton/files/3614897/Pop_OS.Specs.txt)

No special configurations have been attempted at this stage except for setting permissions correctly to my userid and groupid on the NTFS drive this game is installed on. Also ensuring Proton is installed correctly into the .steam folder (don't try and run it via ntfs), and compatdata is symlinked also correctly (refer to documentation).

NOTE: Some users are having issues getting this running correctly, this could be due to incorrect or corrupt proton install, I've encountered this many times myself, its a very easy trap to fall into!

__Originally posted by @jarrard in https://github.com/ValveSoftware/Proton/issues/284__

**Comment by yuripourre** [comment]
@Ghoai171 common, please stop spamming. We are only a few people here at libgdx.

What you are doing is not nice.

**Comment by Frosty-J** [comment]
What a title.

> please stop spamming

Issa bot. If there was a real person at the other end I'd be more inclined to write something unpleasant towards @Ghoai171.

Similar bot issues:  
https://github.com/libgdx/libgdx/issues?q=%22originally+posted+by%22

**Comment by yuripourre** [comment]
@Frosty-J Yeah, I do remember that one, too. I am reporting those users but the GitHub team seems to be too busy to block them.
