### ISSUE TITLE
Add a way to force OpenGL 3.2 core profile on Windows, not just Mac

### ISSUE THREAD

**Issue by soundasleep** [libgdx/libgdx#6953]
#### Issue details
Currently in `Lwjgl3Application`, when using OpenGL 3.x, we [force GLFW to create the next window](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java#L492) with the OpenGL set to the Core profile (this behaviour was added in #3932):

```java
if (SharedLibraryLoader.isMac) {
  // hints mandatory on OS X for GL 3.2+ context creation, but fail on Windows if the
  // WGL_ARB_create_context extension is not available
  // see: http://www.glfw.org/docs/latest/compat.html
  GLFW.glfwWindowHint(GLFW.GLFW_OPENGL_FORWARD_COMPAT, GLFW.GLFW_TRUE);
  GLFW.glfwWindowHint(GLFW.GLFW_OPENGL_PROFILE, GLFW.GLFW_OPENGL_CORE_PROFILE);
}
```

As a result, I've written some shaders that work fine on Windows (as my development environment) that are happy to work without the Core profile being set, but crash immediately on Mac.

I'd like to force OpenGL on Windows to use the core profile, too - if that would cause shaders to fail in my dev environment, rather than a poor players' or testers' Mac down the line. (Of course I'm assuming here that my Windows machine has the core profile/extension available, I'm not sure if it does!)

But because all of the GLFW hints are done in a package-private `Lwjgl3Application#createGlfwWindow`, I've not been able to find a way to hook into setting these hints before the `CreateWindow` call is eventually called.

Would it be possible to perhaps add a field to Lwjgl3ApplicationConfig, something like `forceGL30CoreProfile` or `forceGL30Compatibility`, that would allow me to force all environments - not just Mac - to use this OpenGL profile? e.g.:

```java
if (config.forceGL30Compatibility || SharedLibraryLoader.isMac) {
  // hints mandatory on OS X for GL 3.2+ context creation, but fail on Windows if the
  // WGL_ARB_create_context extension is not available
  // see: http://www.glfw.org/docs/latest/compat.html
  GLFW.glfwWindowHint(GLFW.GLFW_OPENGL_FORWARD_COMPAT, GLFW.GLFW_TRUE);
  GLFW.glfwWindowHint(GLFW.GLFW_OPENGL_PROFILE, GLFW.GLFW_OPENGL_CORE_PROFILE);
}
```

Alternatively, you could create a `protected Lwlgl3Application#setupAnyOtherGlfwWindowHints()` that you can call as part of `createGlfwWindow()`, that subclasses could extend. (Related: #6900)

#### Version of libGDX and/or relevant dependencies
1.10+

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [x] macOS

**Comment by crykn** [comment]
We could definitely add a flag like that to `Lwjgl3ApplicationConfiguration`, but I don't think that solves your problem. I just enabled the core profile on my Windows computer and shaders that fail to compile on macOS still continue to work. So this might be related to the shader compiler on macOS.

However, there are a couple of ways to work around those compatibility issues. Check out #5960 which is dicsussing the exact same problem regarding libGDX's own shaders. Personally, I use the simple regex solution provided [here](https://github.com/crykn/guacamole/blob/d90e8939d22708e1c4a395f3cf55b7f99f0592e3/gdx/src/main/java/de/damios/guacamole/gdx/graphics/ShaderCompatibilityHelper.java#L46-L65).

**Comment by soundasleep** [comment]
Wow, #5960 is great! Very clever. I've ended up doing something similar, too - checking that any shaders I try to compile don't have `attribute`, `varying`, `texture2D` etc. Thank you for checking that the core profile didn't work.
