### ISSUE TITLE
Camera's getPickRay doesn't create a new Ray like it specifies which is misleading

### ISSUE THREAD

**Issue by tylerhasman** [libgdx/libgdx#6961]
Please ensure you have given all the following requested information in your report.

#### Issue details

The method getPickRay in Camera uses a static Ray and returns it which is misleading because the methods descriptor specifies that it creates a Ray. I propose we add a new Ray parameter that this method outputs into instead of the current way it is being done.

I had a problem with code like this:

```java
Ray ray1 = camera.getPickRay(x1, y1);
Ray ray2 = camera.getPickRay(x2, y2);
```

because in actuality these two rays point to the same object and the 2nd ray overwrites the first ray.

#### Recommendation

I propose we change the two getPickRay methods into something like this.

```java
public Ray getPickRay (float screenX, float screenY, float viewportX, float viewportY, float viewportWidth, float viewportHeight, Ray outRay) {
	unproject(outRay.origin.set(screenX, screenY, 0), viewportX, viewportY, viewportWidth, viewportHeight);
	unproject(outRay.direction.set(screenX, screenY, 1), viewportX, viewportY, viewportWidth, viewportHeight);
	outRay.direction.sub(outRay.origin).nor();
	return outRay;
}

public Ray getPickRay (float screenX, float screenY, Ray outRay) {
	return getPickRay(screenX, screenY, 0, 0, Gdx.graphics.getWidth(), Gdx.graphics.getHeight(), outRay);
}

```
#### Version of libGDX and/or relevant dependencies
All versions

**Comment by mgsx-dev** [comment]
It is actually stated in the doc : 
> The returned instance is not a new instance but an internal member only accessible via this function.

but i agree it's confusing : 
> Creates a picking Ray

I think it'd be good to have some changes : 
* remove the ambiguity in the javadoc.
* keep the actual methods to not break existing code.
* add 2 new methods with an outRay parameter as suggested.

We usually propose changes via pull requests. So if you don't mind closing this issue and create a PR, it would be nice.

**Comment by tylerhasman** [comment]
Sounds good!
