### ISSUE TITLE
Game is run 2x faster in frame rate 120Hz

### ISSUE THREAD

**Issue by newMemberHub** [libgdx/libgdx#6967]
#### Issue details
- When I run my game on samsung galaxy s22 ultra 5G, the game is run very fast than normal. After switching to frame rate 60Hz, the game is run normally.

#### Reproduction steps/code
- This issue is always reproduce with 120hz on samsung galaxy s22  ultra 5G. I haven't tested on another phone supported frame rate 120Hz.

#### Version of libGDX and/or relevant dependencies
- My game used the latest libgdx 1.11.0.

#### Stacktrace
- After checking the traces, no error or warning trace is showed.

#### Please select the affected platforms
-  Samsung is run latest Android.

**Comment by Frosty-J** [comment]
Sounds like your game doesn't use delta times (e.g. `Gdx.graphics.getDeltaTime()`). You'll also fine your game runs too slowly on some (older, usually) devices if you update everything by a fixed amount each frame.

**Comment by newMemberHub** [comment]
Hi @Frosty-J,
Thank for your quick reply. It's reasonable.
I am checking and testing again and will inform you soon.

**Comment by fabiitch** [comment]
If you use box2d,  check world.step delta time, I got same problem with 30hz screen (game 2x slower),
You can look this article https://saltares.com/games/fixing-your-timestep-in-libgdx-and-box2d/

**Comment by newMemberHub** [comment]
Hi @fabiitch , hi @Frosty-J ,

Thank for your suggestion.
After checking my code again, I found that I have used the fixed time, not use deltaTime. The issue on framerate 120Hz is fixed.

But I have faced the new issue when using the deltaTime. Although applying the method of @fabiitch , but some first deltaTimes aren't stable, then my game is laggy at that time. After some minutes, the game is stable. I think some frames or some deltaTimes in beginning aren't stable and it's just stable after some minutes.

So could you please give me some ideas to optimize it ?

**Comment by crykn** [comment]
You can try to set some sensible upper and lower limits for the delta time via `Math#min` and `Math#max`.

**Comment by Frosty-J** [comment]
If doing both, `MathUtils#clamp` is a neat method! I only set an upper limit, in case crazy deltas (game paused, lag spikes...) screw everything up. But a lower limit also sounds sensible to avoid the possibility of bugs such as from dividing by zero.

**Comment by newMemberHub** [comment]
Hi @Frosty-J, hi @crykn, hi @fabiitch,

Sorry for late reply.

After checking on Samsung Galaxy S22 Ultra 5G, I captured the following result :
- With configuration in 60Hz, the delta time is on range from 0.001373333 to 0.12434755
- With configuration in 120Hz, the delta time is on range from 6.98385E-4 to 0.096214525
-> I am not clear why the delta time is too big with ~0.12 in 60Hz. And in 120Hz, the delta time also big with ~0.1, it make my game laggy although I applied the method of @fabiitch.

Besides, I also test with Samsung Galaxy S8, the delta time is on range 0.006356654 to 0.03526346. This range is better than in Galaxy S22 Ultra 5G. In this Samsung Galaxy S8, my game run smoothly without laggy.
--> So until now, I still don't have any idea to fix it because I can't control the delta time. It depended on Phone and maybe on libgdx.
Do you think this issue need to be fixed from my side or get support from libgdx's side to improve the delta time ?

**Comment by Frosty-J** [comment]
So performance is better on the S8 than the S22? I've had issues on my S5 (LineageOS) when the power setting in the battery settings isn't set correctly. I move it to Balanced then back to Performance after each reboot to iron out jitters. Strange stuff, but I think that one's just a "me" problem.

If you can't get smooth frame rates out of it (the actual delta times can be weird - what's important is how it looks to the eye) it's quite possible there's something wrong in GDX land. After all, these S21/22 devices seem to have live wallpaper and Daydream crashes, so what's one more problem on the pile?

**Comment by newMemberHub** [comment]
Hi @Frosty-J ,

Thank for quick reply.

About the performance between S8 and S22 Ultra 5G, I make sure S22 is better than S8 because it's is the flagship phone at the moment of Samsung. I just think the issue related to monitor support 120Hz. This point affect to delta time and maybe need improve from libgdx's side. 

About fixing this issue from my side, do you have any idea or just wait for the new version of libgdx for completely support on 120Hz ?

**Comment by Frosty-J** [comment]
I thought libGDX already did support 120Hz, but as far as mobile is concerned I only have 60Hz devices to test on. I wouldn't hold my breath for anything to change, if I were you.

**Comment by obigu** [comment]
libGDX doesn't cap fps on Android backend by default which means you need to handle it on your game logic. You can ask for advice on how to handle it on your side on the libGDX Discord channel.

**Comment by ks1c** [comment]
In my research I found that delta time is not reliable/constant. Its a problem many engines/frameworks have. When you try to achieve framerate independence using delta time to move things, you will have stuttering.

Take a look at [The Elusive Frame Timing](https://medium.com/@alen.ladavac/the-elusive-frame-timing-168f899aec92). [Unity](https://blog.unity.com/technology/fixing-time-deltatime-in-unity-2020-2-for-smoother-gameplay-what-did-it-take) tried to solve this too. [This guy](https://frankforce.com/frame-rate-delta-buffering/) tries to smooth delta time in order to solve this problem.
