### ISSUE TITLE
Gdx.files.internal root file become different when delete the .idea folder

### ISSUE THREAD

**Issue by Ryuu-64** [libgdx/libgdx#6969]
Please ensure you have given all the following requested information in your report.

#### Issue details
I use IDEA to develop libgdx.
I move my project to svn directory and delete the .idea folder and open the project, cause I want to make sure other developers have no trouble when they develop after svn update.

But there is trouble after I delete the .idea folder, the internal root become the father of the assets folder
![image](https://user-images.githubusercontent.com/61548752/184567134-105a27dc-0ace-4a9f-8f8b-81441cf95aeb.png)

Before that, the internal root is the assets folder
![image](https://user-images.githubusercontent.com/61548752/184567905-89370744-ff94-498f-a635-073a6b22ffcc.png)

Anyone who can help me to know why this happens?
(I think the asset root path should not be controlled by the file in .idea folder, but why I can't run the desktop build after I delete the .idea folder)

#### Reproduction steps/code
This is part of my asset load code, it will recursively load all assets in the specific path.

```java
    public static void load(String assetPath) {
        FileHandle handle = Gdx.files.internal(assetPath);
        if (!handle.exists()) {
            throw new RuntimeException("asset path not exist: " + assetPath);
        }

        loadFileOrPushDirectoryIntoStack(handle);
        while (!directoryStack.isEmpty()) {
            handle = directoryStack.pop();
            FileHandle[] handles = handle.list();
            for (FileHandle fileHandle : handles) {
                loadFileOrPushDirectoryIntoStack(fileHandle);
            }
        }
    }

    private static void loadFileOrPushDirectoryIntoStack(FileHandle fileHandle) {
        if (!fileHandle.isDirectory()) {
            String path = fileHandle.path();
            Class<?> type = getTypeBySuffix(path);
            if (type == null) {
                throw new RuntimeException("there is no type for path : " + path);
            }
            AssetManager.INSTANCE.load(path, type);
        } else {
            directoryStack.push(fileHandle);
        }
    }
```

#### Version of libGDX and/or relevant dependencies
libGDX version 1.11.0

#### Stacktrace
```java
Exception in thread "main" java.lang.RuntimeException: there is no type for path : texture
	at pers.ryuu.libgdx_library.asset.AssetLoader.loadFileOrPushDirectoryIntoStack(AssetLoader.java:40)
	at pers.ryuu.libgdx_library.asset.AssetLoader.load(AssetLoader.java:25)
	at com.coolstudios.air_hockey.AirHockey.create(AirHockey.java:85)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:416)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:366)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at com.coolstudios.air_hockey.DesktopLauncher.main(DesktopLauncher.java:15)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [√] Windows
- [ ] Linux
- [ ] macOS

**Comment by Ryuu-64** [comment]
And the texture is a folder, not a file.
![image](https://user-images.githubusercontent.com/61548752/184568841-558563ec-bfc5-4639-b6a9-b1a70e3e1433.png)
The desktop run will when the .idea folder is not deleted.

**Comment by Tom-Ski** [comment]
You should follow the .gitignore that comes with the project and make an equivalent svn ignore instead of deleting those directories.

Gdx.files.internal resolves to the working directory set from the IDE in the run configuration when you are running from the IDE, and when the app is packaged it will automatically resolve to assets directory inside the bundle/jar.  
Solution is to make sure your working directory is aligned with this assets directory by setting the correct folder in the run configuration, or run from gradle which automatically does this.

**Comment by Ryuu-64** [comment]
Thank you for your reply.
I choose to run from Gradle: desktop -> other -> run, and it will be ok.
![image](https://user-images.githubusercontent.com/61548752/184835465-62fbe58d-f6a7-40f9-8504-e4988b0a1bc9.png)

But build jar by Gradle (desktop -> other -> dist).
The jar already has assets in it. But Gdx.files API can't find it.
How is it happen?
I'm looking forward to your reply.

**Comment by Tom-Ski** [comment]
Whats your error? You might want to try the discord for questions/problems as these are not suitable for github issue tracker.
