### ISSUE TITLE
iOS black frames after launch screen

### ISSUE THREAD

**Issue by CoderBaron** [libgdx/libgdx#6971]
#### Issue details
I'm using a storyboard launch screen in my app that then should transition into a Scene2D launch screen which looks the same but with animation. There is almost a second of black screen after the storyboard launch screen disappears and my Scene2D launch screen appears, which is not acceptable (Apple review does reject such glitches).
By using static images for the iOS launch screen the issue goes away with the RoboVM backend.

1. Static images, robovm backend: seamless transition
2. Static images, metalangle backend: 1 frame of half rendered half black screen on simulator
3. Storyboard, robovm backend: several black frames
4. Storyboard, metalangle backend: about 1 second of black screen on simulator

#### Probable cause
By design the iOS splash screen fades out once the method didFinishLaunching() of the app delegate returned. At this time the next view controller needs to be setup already. 
With libGDX this means that the OpenGL/Metal view needs to have started drawing its content **before** didFinishLaunching is complete.

Currently the way the iOS backend is setup makes this impossible. The ApplicationListener.create() method as well as the completion of the OpenGL setup are called **after** didFinishLaunching().

#### Version of libGDX and/or relevant dependencies
1.11.1-SNAPSHOT

#### Please select the affected platforms
- [ ] Android
- [X] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by Berstanio** [comment]
I can't really reproduce the error, for me it opens without any really noticable delay with MetalANGLE + launch storyboard. Maybe my mac is faster? I have a Mac mini M1 2020. Do you maybe have any minimal reproducer project?

> At this time the next view controller needs to be setup already.
Is this documented somewhere? Haven't found anything in the apple docs.

Anyhow, by looking through the docs it seems like there would be nothing speaking against hooking up the controller initialization in the willFinishLaunching event (https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623032-application?language=objc). Would you be able to test, whether this fixes the issue for you?

> The ApplicationListener.create() method as well as the completion of the OpenGL setup are called **after** didFinishLaunching().

As far as I understand it, not precisly. They are called during the "didFinishLaunching" callback. Also, according to the docs, "This method is called after state restoration has occurred but before your app’s window and other UI have been presented. At some point after this method returns, the system calls another of your app delegate’s methods to move the app to the active (foreground) state or the background state." 
https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622921-application?language=objc
So the app seems to be not expected to have something already drawn, at this point.

But interesting in the code is also this:
```java
	public void viewWillAppear (boolean arg0) {
		super.viewWillAppear(arg0);
		// start GLKViewController even though we may only draw a single frame
		// (we may be in non-continuous mode)
		setPaused(false);
	}
```
So maybe "setPaused" was working different in GLKit than in MGLKit? But thats also just a random idea, can't test around without being able to reproduce it.

**Comment by CoderBaron** [comment]
The ApplicationListener.create() method is called during the first draw call of the view controller:

IOSGraphics.java
```
	public void draw (GLKView view, CGRect rect) {
		...
		if (!created) {
			// OpenGL glViewport() function expects backbuffer coordinates instead of logical coordinates
			gl20.glViewport(0, 0, screenBounds.backBufferWidth, screenBounds.backBufferHeight);

			String versionString = gl20.glGetString(GL20.GL_VERSION);
			String vendorString = gl20.glGetString(GL20.GL_VENDOR);
			String rendererString = gl20.glGetString(GL20.GL_RENDERER);
			glVersion = new GLVersion(Application.ApplicationType.iOS, versionString, vendorString, rendererString);

			updateSafeInsets();
			app.listener.create();
			app.listener.resize(getWidth(), getHeight());
			created = true;
		}
		...
```
I managed to move all that stuff into the didFinishLaunching method in a local fork to make:

IOSApplication.java
```
	final boolean didFinishLaunching (UIApplication uiApp, UIApplicationLaunchOptions options) {
		...
		this.uiWindow.setRootViewController(this.graphics.viewController);
		this.graphics.updateSafeInsets();
		
		Gdx.app.debug("IOSApplication", "created");

		// make sure the OpenGL view has contents before displaying it
		this.graphics.view.display();

		return true;
	}
```

This entirely removes the black/empty frames after the launch screen. The bigger the app is the longer this "blackout" was, in my case over 500ms. However it is still noticeable in the default libGDX app. 
I'm providing a PR with this fix.

**Comment by CoderBaron** [comment]
> Maybe it is cleaner to move the view initialization code into a callback like view[Will/Did]Appear, if this works too?
Those callbacks are called too late. We need to have it within the constructor so everything is setup once ApplicationListener.create() is called.
