### ISSUE TITLE
I wanted to make a libgdx game, but when i launch it, i get an "NSException"

### ISSUE THREAD

**Issue by Gamer069** [libgdx/libgdx#6990]
#### Issue details
repo for this -> https://github.com/Gamer069/illialibgdxproj

#### Reproduction steps/code
1. make a libgdx project with maven on macos and maybe this will happen, idk, if it doesn't happen, then i'm probably stupid or something

#### Version of libGDX and/or relevant dependencies
LibGDX Version: 1.9.13
Java Version: 11

#### Stacktrace
```java
2022-09-20 16:01:57.821 java[29664:1006508] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1575.405/Foundation/Misc.subproj/NSUndoManager.m:361
2022-09-20 16:01:57.821 java[29664:1006508] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff4faa4035 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff7a30ca17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff4fabed52 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff51d64171 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   Foundation                          0x00007fff51c971ee +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 473
	5   AppKit                              0x00007fff4cfdbd6d -[NSApplication run] + 916
	6   libglfw.dylib                       0x000000013317aa85 libglfw.dylib + 68229
	7   libglfw.dylib                       0x0000000133174416 libglfw.dylib + 42006
	8   ???                                 0x0000000118ea1a10 0x0 + 4712962576
)
libc++abi.dylib: terminating with uncaught exception of type NSException

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

#### Please select the affected platforms
- [ ] macOS

**Comment by Frosty-J** [comment]
I think you need to launch your game with -XstartOnFirstThread`. Alternatively, you can add the `gdx-lwjgl3-glfw-awt-macos` extension (libGDX 1.11.0+ only).

https://libgdx.com/news/2021/07/devlog-7-lwjgl3#do-i-need-to-do-anything-else
https://libgdx.com/news/2022/05/gdx-1-11#lwjgl-3

libGDX 1.11.0 is also the first version to support Apple Silicon chips (with mixed success, inevitably).

**Comment by tommyettinger** [comment]
I'd strongly recommend using a setup tool, such as [gdx-setup](https://libgdx.com/wiki/start/project-generation) or [gdx-liftoff](https://github.com/tommyettinger/gdx-liftoff) to generate a Gradle project that uses the current libGDX version and has the files it needs. If you want to use Maven, you should look for some template project to copy configuration from -- just know that it is a harder route to get help with. 1.9.13 was a good release, but it's a bit behind the times now. If you have an M1 Mac, or think users might use them, then definitely switch to 1.11.0 .

**Comment by Gamer069** [comment]
thanks, @Frosty-J, that worked
