### ISSUE TITLE
NPE in com.badlogic.gdx.scenes.scene2d.ui.Cell

### ISSUE THREAD

**Issue by Ryuu-64** [libgdx/libgdx#6991]
Since uniformX, uniformY fields are wrapper boolean classes and getUniformX(), getUniformY() return non-wrapper boolean, cell.getUniformX and cell.getUniformY methods may result in NPE instead of returning null.

``` java
Boolean uniformX, uniformY;

public boolean getUniformX () {
	return uniformX;
}

public boolean getUniformY () {
	return uniformY;
}
```

**Comment by NathanSweet** [comment]
True, I suppose these methods would be better returning `@Null Boolean`.
