### ISSUE TITLE
Issues with window resizing and closing on MacOS

### ISSUE THREAD

**Issue by kopolop** [libgdx/libgdx#6992]
Please ensure you have given all the following requested information in your report.

#### Issue details
We encountered two issues related to application windows on MacOS:
- When the app window is resized, the app very often (but not always) crashes
- When the app window is closed, sometimes the app does not quit, but the window cannot be reopened. WindowListener's closeRequested is not triggered.
- 
#### Reproduction steps/code
- Resize an app window, the app crashes with exception "failed assertion `A command encoder is already encoding to this command buffer"
- Move the app window around a little bit, minimize, reopen the app window, then close the app window (by clicking the X button, or press Command Q). Observe that the app is not quit, but the window cannot be reopened.

#### Version of libGDX and/or relevant dependencies
libgdx = 1.11.0
roboVM version = 2.3.16
com.badlogicgames.gdx:gdx-lwjgl3-glfw-awt-macos extension is used.

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ x] macOS

**Comment by crykn** [comment]
Probably related to #6987.

**Comment by Thakor-Yashpal** [comment]
#2322

**Comment by tommyettinger** [comment]
@Thakor-Yashpal You are not being helpful right now. I also have some suspicions that you are a bot, or are acting in an atypical way for a legitimate human user. Please send a picture of a cute cat to confirm that you are human. I also just like cats.

**Comment by MobiDevelop** [comment]
Unable to reproduce on my Intel Mac, #6987 suggests that these issues may only exist on ARM Macs.

**Comment by Thakor-Yashpal** [comment]
@tommyettinger
![image](https://github.com/user-attachments/assets/bc4d8541-22ed-40ad-a2c4-130400fde3b4)
