### ISSUE TITLE
libgdx FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by Bradboyee** [libgdx/libgdx#6996]
I'm new in libgdx i follow the Youtube guide but I got this problem how can I solve this problem.
#### Issue details

* What went wrong:
A problem occurred evaluating root project 'test'.
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

#### Please select the affected platforms
- [x] Android
- [x] iOS
- [x] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] macOS

**Comment by Frosty-J** [comment]
Android now requires Java 11 or newer. Either configure your IDE to use that or remove the Android module from your project if you don't need it. I know this is basically what the error message says, but what more can I say? Both Android Studio and IntelliJ IDEA come with a suitable JDK, but if you're not using either then follow whatever instructions you used to install JDK 8 but do it for 11 or 17 instead.

**Comment by crykn** [comment]
I've adapted the setup guide accordingly: https://github.com/libgdx/libgdx.github.io/pull/125.
