### ISSUE TITLE
Support Java Color constructor (int r, int g, int b, int a)

### ISSUE THREAD

**Issue by HydrolienF** [libgdx/libgdx#7008]
#### Issue details
Create a new Color as we can do in Java cause issues
```java
new Color(8, 194, 0, 255)
```
Java developpers, knowing that they use int args think that they will get a dark green with fiew blue.
Insted it create a color full Red, full Green 0 Blue.
I don't get why but there is no error, int are used in the float constructor.

#### Reproduction steps/code
```java
package com.test;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.glutils.ShapeRenderer;
import com.badlogic.gdx.graphics.glutils.ShapeRenderer.ShapeType;
import com.badlogic.gdx.utils.ScreenUtils;

public class ColorTest extends ApplicationAdapter {
    private ShapeRenderer shapeRenderer;

	@Override
	public void create () {
		shapeRenderer = new ShapeRenderer();
		shapeRenderer.setColor(new Color(8, 194, 0, 255));
	}

	@Override
	public void render () {
		ScreenUtils.clear(1, 1, 1, 1);
		shapeRenderer.begin(ShapeType.Filled);
		shapeRenderer.circle(100, 100, (float) 100);
		shapeRenderer.end();
	}
	
	@Override
	public void dispose () {}
}

``

#### Version of libGDX and/or relevant dependencies
libGDX 1.11.0
Java 17

#### Please select the affected platforms
- [x] Android
- [x] iOS
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] macOS

**Comment by Frosty-J** [comment]
This or a bounds check sounds like a good idea to me. Using 0-255 ints instead of 0-1 floats is a common mistake. My favourite approach in this case would be `new Color(0x08c200ff)` - it isn't obvious you can use hex codes like that!

Related PR (since you didn't link them together): #7009

**Comment by HydrolienF** [comment]
Is something like
```java
public Color(int r, int g, int b, int a){
  if(r>1 || g>1 || b>1 || a>1){
    this(r/255f, g/255f, b/255f, a/255f);
  }else{
    this(r,g,b,a);
  }
}
```
a good way to solve it without breaking any current code as
```java
new Color(1,1,0,1)
```
?

Or people that try to use int will finaly check the javadoc and understand why the int color constructor don't work as the Java one ?

**Comment by mgsx-dev** [comment]
> Is something like ... a good way to solve it

No, for many reasons.

> Or people that try to use int will finaly check the javadoc

That's the other way around: People should read the documentation at the first place before calling a method.

Setting RGBA as 8-bits components is counter-intuitive and breaks separation of concern (even if some old API still have that). Defining a color is a thing, decoding/encoding it is another thing. If you need to define a color as 8 bit components, you can still use `Color.valueOf(hexString)` or simply decode it in your own code : `new Color(8/255f, 194/255f, 0/255f, 255/255f)`.

If you guys really want that, i think the best solution would be a new method in Color class: `public static Color rgba8888ToColor (int r, int g, int b, int a)`
