### ISSUE TITLE
[iOS/robovm] Callbacks from native iOS SDK (Appodeal) don't work

### ISSUE THREAD

**Issue by nkarulin** [libgdx/libgdx#7012]
I am not sure, this in 100% libgdx issue, but there is a chance that problem is in different scopes of game thread and objective-c runtime. Hope you guys could help me to figure out.

I have encapsulated Ads SDK (Appodeal in my case) in separate iOS _.framework_ with rather simple interface:

```objective-c
@interface AdsCallback : NSObject
-(void)callback;
@end

@interface LibgdxAdsAdapter : NSObject
+(void)initialize:(nonnull NSString *)apiKey :(bool)isTesting :(bool)verbose;
+(void)showInter:(UIViewController*_Nonnull)viewController :(nonnull AdsCallback*)callback;
@end
```
That was done to simplify robovm-bro-gen binding to Java (up-to-date robo pods for Appodeal do not exist). Implementation of .framework is pretty straight-forward. Everything works fine (SDK is initializing, Ads are loading and being shown) except one thing: Delegate callbacks. Even with simplest implementation:

```objective-c
@interface MyIntDeligate : NSObject <AppodealInterstitialDelegate>
@end

@implementation MyIntDeligate
- (void)interstitialDidLoadAdIsPrecache:(BOOL)precache { [self foo]; }
- (void)interstitialDidFailToLoadAd { [self foo]; }
- (void)interstitialDidFailToPresent { [self foo]; }
- (void)interstitialWillPresent { [self foo]; }
- (void)interstitialDidDismiss { [self foo]; }
- (void)interstitialDidClick { [self foo]; }

- (void) foo {
    NSLog(@"!Appodeal: KEKE"); //Even incrementing of a static int property doesn't work here
}

@implementation LibgdxAdsAdapter

+(void)initialize:(nonnull NSString *)apiKey :(bool)isTesting :(bool)verbose {
    [Appodeal initializeWithApiKey:apiKey types: AppodealAdTypeInterstitial | AppodealAdTypeRewardedVideo];
    MyIntDeligate* deleg = [[MyIntDeligate alloc] init];
    // [deleg foo]; will work here
    [Appodeal setInterstitialDelegate:deleg];
}

+(void)showInter:(UIViewController*)viewController :(nonnull AdsCallback*)callback {
    [Appodeal showAd:AppodealShowStyleInterstitial rootViewController:viewController];
}
@end
```

Appodeal documentation tells that all callbacks are called on the main thread. And in the log you could find lines which hint a delegate is set and some callbacks should be triggered. But result of `foo` method of MyIntDeligate is never seen (I tried BlockingQueue, throwing of an exception, stopping a thread, nothing happens).

```
[Appodeal 2.11.1] [debug] [api] Set interstitial delegate : <MyIntDeligate: 0x283e804a0>
[Appodeal 2.11.1] [debug] [api] [Callback] [Interstitial] Did load precache : NO
[Appodeal 2.11.1] [debug] [api] [Callback] [Interstitial] Did appear
```

I am wondering could it be connected to the fact that SDK callbacks and gdx rendering could live in different threads? Or do you guys have any other thought what is happening here? Thank you

#### Version of libGDX and/or relevant dependencies
gdxVersion = '1.10.0'
roboVMVersion = '2.3.19-SNAPSHOT'
ktxVersion = '1.9.9-b2'
Appodeal SDK 2.11.1

#### Please select the affected platforms
- iOS only

**Comment by obigu** [comment]
May it have to do with the delegate being garbage collected? Is ` setInterstitialDelegate` marked as `strongRef`?

**Comment by nkarulin** [comment]
> May it have to do with the delegate being garbage collected? Is ` setInterstitialDelegate` marked as `strongRef`?

You are so right! The delegate was indeed being allocated in a static method and apparently being garbage collected just after the method returns. Keeping reference to the delegate object solve the problem.

Libgdx has nothing to do with it.

Thank you so much, man!

P.S.: The last version of Appodeal iOS SDK is smoothly integrated into libgdx/robovm(iOS) game
