### ISSUE TITLE
ModelBuilder Invalid overflow

### ISSUE THREAD

**Issue by imcasper** [libgdx/libgdx#7016]
https://github.com/libgdx/libgdx/blob/31ac4d900bffe10c4b194a912a1289fa1e42ad3c/gdx/src/com/badlogic/gdx/graphics/g3d/utils/ModelBuilder.java#L53

In my case 
lastIndex == 65535
mb.lastIndex() == -1 (as Short) 
mb.lastIndex() < Short.MAX_VALUE / 2 == true

**Comment by mgsx-dev** [comment]
Confirmed. I PRed a fix proposal.
