### ISSUE TITLE
[LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.

### ISSUE THREAD

**Issue by BoodyZedan** [libgdx/libgdx#7019]
so i'm just starting on libgdx and i use ubuntu 20.04 and this error pop's up in the console [LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.

this is my code

```
public class DesktopLauncher {
    public static void main(String[] args) {
        Lwjgl3ApplicationConfiguration cfg = new Lwjgl3ApplicationConfiguration();
        cfg.setIdleFPS(60);
        cfg.setTitle("PONG");
        cfg.useVsync(true);

        cfg.setWindowedMode(960, 640);

        new Lwjgl3Application(new Boot(), cfg);
    }
}

```
and boot extends Game

i'm also using libgdx1.9.13

**Comment by Frosty-J** [comment]
Does this affect the current version of libGDX? LWJGL3 was updated in version 1.11.0, so the warning might have gone away in the newer version.

**Comment by Frosty-J** [comment]
Maybe you're using Java 19? I'd advise against using cutting-edge versions if you are. If it's to do with https://github.com/LWJGL/lwjgl3/pull/799 then we'll get that fix in due course.

**Comment by kawaii-clorthax** [comment]
nice

**Comment by Frosty-J** [comment]
Did you find out what the issue was? There's a solid chance someone else might run into the same problem.

**Comment by devonhume** [comment]
I ran into this issue as well. I was able to resolve the error by changing my sdk from 19 to 17. 

Thank you Frosty-J for your replies on this thread!

**Comment by Pyanda6991** [comment]
This is still very much an issue. However, I am using Java 19. So, I will be changing to Java 17. Just thought I would update you.
