### ISSUE TITLE
clicklistener exit() not called when actor is placed near screen edge

### ISSUE THREAD

**Issue by HAL9000Thomas** [libgdx/libgdx#7027]
#### Issue details
The exit() method of ClickListener is not being called when the actor is placed at the very top or bottom of iPhone screen. Touching the actor will trigger touchDown(), but not exit() once actor touch is ended. Placing the actor away from the device screen edge will solve the issue.

#### Reproduction steps/code
1. Create an actor / image button
2. Place the actor at the very top or bottom of the screen
3. Set ClickListener on the actor with overriding method touchDown() and exit()
4. Start your app on real iPhone device
5. Tap and release the actor (tap close as possible to screen edge)
6. Notice issue: exit() was not called

#### Version of libGDX and/or relevant dependencies

libGDX 1.11.0
RoboVM Version: 2.3.16
RoboVM Gradle Plugin Version: 2.3.16

IPhone XR iOS 16.1.1, but also observed on iOS 15.x

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [ ] Android
- [x] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by obigu** [comment]
Set `IOSApplicationConfiguration.screenEdgesDeferringSystemGestures` to `All`. This is now defauilt on latest SNAPSHOT but you need to set it explicitly on older libGDX versions.

**Comment by HAL9000Thomas** [comment]
That worked!. Thank you so much for your help. Much appreciated.

**Comment by HAL9000Thomas** [comment]
@obigu Just noticed similar behaviour on my Android device. Do you know if there is a config option for enabling exit() calls at screen edges on Android?

**Comment by obigu** [comment]
Nope, never come across this issue on Android, there's nothing on libGDX for that, you may want to check the official Android docs.
