### ISSUE TITLE
Creating WindowStyle from another WindowStyle causes missing stageBackground in the new WindowStyle, possible typo

### ISSUE THREAD

**Issue by Bombbird2001** [libgdx/libgdx#7031]
#### Issue details
WindowStyle created from another WindowStyle with a non-null stageBackground will have a null stageBackground. From the source code, it seems like there may be a typo.

```java
Class: com.badlogic.gdx.scenes.scene2d.ui.Window.WindowStyle

public WindowStyle (WindowStyle style) {
	background = style.background;
	titleFont = style.titleFont;
	if (style.titleFontColor != null) titleFontColor = new Color(style.titleFontColor);
	background = style.background; // Typo here, should be stageBackground = style.stageBackground?
}
```

#### Reproduction steps/code
```java
WindowStyle windowStyle = new WindowStyle();
windowStyle.stageBackground = new TextureRegionDrawable(); // Set stageBackground
WindowStyle windowStyleCopy = new WindowStyle(windowStyle); // Call the constructor above
System.out.println(windowStyleCopy.stageBackground); // -> null
```

#### Version of libGDX and/or relevant dependencies
1.11.0

#### Stacktrace
NA

#### Please select the affected platforms
- [x] Android
- [x] iOS
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] macOS

**Comment by tommyettinger** [comment]
Definitely looks like a copy-paste mistake, good catch. @NathanSweet is there anything that we should be careful about when fixing this? scene2d.ui is your area of expertise.

**Comment by NathanSweet** [comment]
Just a missing assignment for the copy constructor!

**Comment by Frosty-J** [comment]
Why is `background` being assigned twice, though?
