### ISSUE TITLE
Potential bug in WebGL (Typed Arrays)

### ISSUE THREAD

**Issue by JamesTKhan** [libgdx/libgdx#7033]
#### Issue details
I am working on a WebGL2 implementation and as such, I am referencing the WebGL1 implementation quite a bit. I am learning as I go so maybe I am just misunderstanding but I think its worth checking. When I implemented glTexImage3D and glTexSubImage3D on my WebGL2 branch, I based it heavily off the 2D method equivalents in WebGL1 (glTexSubImage2D, glTexImage2D). Once I started testing the 3D methods, I was getting an error:

```
RangeError: Invalid typed array length: 8192
    at new Uint8Array (<anonymous>)
    at Tyk_g$ (com.badlogic.gdx.tests.gwt.GdxTestsGwt-0.js:232884:10)
    at Ow_g$.py_g$ [as glTexImage3D_1_g$] (com.badlogic.gdx.tests.gwt.GdxTestsGwt-0.js:11865:23)
    at dFq_g$.eFq_g$ [as consume3DData_0_g$] (com.badlogic.gdx.tests.gwt.GdxTestsGwt-0.js:45708:25)
    at LEq_g$.WEq_g$ [as load_46_g$] (com.badlogic.gdx.tests.gwt.GdxTestsGwt-0.js:18102:13)
    at new LEq_g$ (com.badlogic.gdx.tests.gwt.GdxTestsGwt-0.js:18017:8)
```

After doing some digging, it seems that it is a common mistake to provide a byte value, rather than a length value into the third argument for the typed array (https://stackoverflow.com/a/42684877/9436750). When I changed my code (which was based off the WebGL1.0 2D methods) to use a length rather than byte value the error went away. This makes me wonder if this is an error on the WebGL1.0 implementation.  

Here is the WebGL1.0 code in question (within two different places in GwtGL20.java):
```java
int remainingBytes = pixels.remaining() * 4;
int byteOffset = webGLArray.byteOffset() + pixels.position() * 4;
buffer = Uint8ArrayNative.create(webGLArray.buffer(), byteOffset, remainingBytes);
```

The third parameter to Uint8ArrayNative.create() is a length value but here we seem to be passing in a byte value. To resolve the issue on my WebGL2 branch I have removed the * 4 from the end of pixels.remaining() for the 3D versions of the methods and no longer get the error. Is this a mistake in WebGL1.0 or is converting the pixel remaining value to bytes valid here?

#### Reproduction steps/code
Nothing to reproduce at this moment. I tried removing the * 4 value in the WebGL1.0 implementation and stepping through the tests, I did not step through every test, the ones I did try worked as expected.

#### Version of libGDX and/or relevant dependencies
1.11.0

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [x] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by intrigus** [comment]
Very nice to see someone continue my initial WebGL2 PR :tada: 

Regarding your issue, I've looked at the history and the part of code you mentioned has been added with this commit:
https://github.com/libgdx/libgdx/commit/b2508bdeab072970c382c97ec2e834f1d67d4663
>  Support sending float data to a texture. Floats should not be unpacked into a byte array, but rather send on directly.

I _think_ this commit only added support for float data and I would assume that you are now using something that is not float data, but should _also_ not be unpacked into a byte array.

Maybe this part of the code is missing a special case for `ShortBuffer`s or something like that?

**Comment by JamesTKhan** [comment]
Thanks for the quick reply. This might be a case of me getting in over my head, but based on your suggestion I dug a little deeper and did some debugging in to the scenario where I am getting the error `RangeError: Invalid typed array length: 8192` for WebGL2.0 (its when running the GL30Texture3DTest in GWT). 

From what I am seeing, the pixels buffer is a ByteBuffer in this scenario and the glType is GL_UNSIGNED_BYTE when the error is thrown. The original length of that buffer is 2048, so remaining bytes ends up being 8192 which leads to that error.

So now I am wondering if it is a ByteBuffer should we not perform the ` * 4` operation on the length..
