### ISSUE TITLE
applyLinearImpulse API为何无效

### ISSUE THREAD

**Issue by lewic1987** [libgdx/libgdx#7038]
很奇怪的现象，我用下面代码applyLinearImpulse API 无效，使用注释掉的代码applyLinearImpulse API是有效果的
<img width="364" alt="截屏2022-11-29 20 16 16" src="https://user-images.githubusercontent.com/27275977/204526753-0619cfae-fee1-4678-99b6-92bee8da2b0c.png">

<img width="617" alt="截屏2022-11-29 20 16 31" src="https://user-images.githubusercontent.com/27275977/204526809-37564e6a-19d5-4bf2-908e-da5aaed42d08.png">

完整代码如下：
package com.tech9.emaoer.gdxdemo.game.box2d_demo;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.math.Vector2;
import com.badlogic.gdx.physics.box2d.Body;
import com.badlogic.gdx.physics.box2d.BodyDef;
import com.badlogic.gdx.physics.box2d.BodyDef.BodyType;
import com.badlogic.gdx.physics.box2d.Box2DDebugRenderer;
import com.badlogic.gdx.physics.box2d.CircleShape;
import com.badlogic.gdx.physics.box2d.EdgeShape;
import com.badlogic.gdx.physics.box2d.FixtureDef;
import com.badlogic.gdx.physics.box2d.World;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.utils.viewport.StretchViewport;

import javax.microedition.khronos.opengles.GL10;

public class Demo02 extends Stage {
	protected final static float STAGE_W = 800f;
	protected final static float STAGE_H = 600f;
	protected final static float BALL_RADIUS = 40f;
//	protected final static float STAGE_W = 40f;
//	protected final static float STAGE_H = 30f;
//	protected final static float BALL_RADIUS = 2f;

	private World world;
	private Body ball, groundBody;
	private Box2DDebugRenderer renderer; // 测试用绘制器

	public Demo02() {
		super(new StretchViewport(
				STAGE_W,
				STAGE_H
		));

		world = new World(new Vector2(0, 0f), true);
		renderer = new Box2DDebugRenderer();

		BodyDef bd = new BodyDef();
		bd.position.set(0, 0);
		groundBody = world.createBody(bd);
		EdgeShape edge = new EdgeShape();
		FixtureDef boxShapeDef = new FixtureDef();
		boxShapeDef.shape = edge;
		edge.set(new Vector2(0f, 0f), new Vector2(STAGE_W, 0f));
		groundBody.createFixture(boxShapeDef);
		edge.set(new Vector2(0f, 0f), new Vector2(0f, STAGE_H));
		groundBody.createFixture(boxShapeDef);
		edge.set(new Vector2(STAGE_W, 0f), new Vector2(STAGE_W, STAGE_H));
		groundBody.createFixture(boxShapeDef);
		edge.set(new Vector2(STAGE_W, STAGE_H), new Vector2(0f, STAGE_H));
		groundBody.createFixture(boxShapeDef);

		BodyDef ballBodyDef = new BodyDef();
		ballBodyDef.type = BodyType.DynamicBody;
		ballBodyDef.position.set(STAGE_W / 2, STAGE_H / 2);
		ball = world.createBody(ballBodyDef);
		CircleShape circle = new CircleShape();
		circle.setRadius(BALL_RADIUS);
		FixtureDef ballShapeDef = new FixtureDef();
		ballShapeDef.shape = circle;
		ballShapeDef.density = 1.0f;
		ballShapeDef.friction = 0f;
		ballShapeDef.restitution = 1.0f;
		ball.createFixture(ballShapeDef);

		//设置速度
		//ball.setLinearVelocity(new Vector2(500f, 500f));

		//施加力
		//ball.applyForceToCenter(500f, 500f, true);

		//脉冲
		//ball.applyLinearImpulse(new Vector2(500f, 500f), ballBodyDef.position,true);
		ball.applyLinearImpulse(new Vector2(500f * 20, 500f * 20), ballBodyDef.position,true);
	}

	@Override
	public void draw() {
		Gdx.gl.glClear(GL10.GL_COLOR_BUFFER_BIT);
		world.step(Gdx.app.getGraphics().getDeltaTime(), 8, 8);
		renderer.render(world, getCamera().combined);
		super.draw();
	}

	@Override
	public void dispose() {
		renderer.dispose();
		world.dispose();
		super.dispose();
	}
}

**Comment by lewic1987** [comment]
ball.applyLinearImpulse(new Vector2(500f * 200000, 500f * 200000), ballBodyDef.position,true);

**Comment by lewic1987** [comment]
@Frosty-J 大佬，看下这个问题呗

**Comment by Frosty-J** [comment]
I'm unclear what the question is, but Box2D bodies have a speed limit. The units are measured in metres. A stage size of 8 by 6 and a ball radius of 0.4 would be a more reasonable starting point.

Additionally:

* The `javax.microedition.khronos.opengles.GL10` import is unusual - I haven't seen that before. libGDX has a `ScreenUtils.clear()` method nowadays that's a bit simpler (albeit less flexible) than the `glClear()` stuff but even without that you can use libGDX's `GL20` (libGDX hasn't supported OpenGL ES 1.0 since prior to libGDX 1.0's release in 2014 - whatever you're basing this off is frightfully out-of-date).
* Stepping by `Gdx.app.getGraphics().getDeltaTime()` is a bit verbose. In most cases I do something like `float delta = Math.min(1/5f, Gdx.graphics.getDeltaTime())` then use that variable to avoid really huge deltas (such as when the game is suspended) causing issues. But for Box2D, many people scream at the thought of such dynamic steps, as they can add an element of unpredictability to the simulation. A simple example of using an accumulator for stepping is available at https://libgdx.com/wiki/extensions/physics/box2d#stepping-the-simulation

**Comment by lewic1987** [comment]
@Frosty-J 我可以将Stage的宽高设置的小一些，比如设置成8x6 但是 Stage里所有的 Actor就也是基于这个尺寸的，那么在设置字体大小时候 就需要设置成很小 ，这样会有问题，比如之前设置的是：
 FreeTypeFontGenerator.FreeTypeFontParameter para = new FreeTypeFontGenerator.FreeTypeFontParameter();
para.size = 20;

因为舞台基准变小了，就要改成：
 FreeTypeFontGenerator.FreeTypeFontParameter para = new FreeTypeFontGenerator.FreeTypeFontParameter();
para.size = 2;

这样会报一个错误：
![Uploading 截屏2022-12-02 14.39.42.png…]()

并且如果舞蹈大小设置成8x6 那么所有子View的宽高给的值都很小，不太方便和设计稿标注保持一致。

**Comment by lewic1987** [comment]
@Frosty-J 我可以将Stage的宽高设置的小一些，比如设置成8x6 但是 Stage里所有的 Actor就也是基于这个尺寸的，那么在设置字体大小时候 就需要设置成很小 ，这样会有问题，比如之前设置的是：
 FreeTypeFontGenerator.FreeTypeFontParameter para = new FreeTypeFontGenerator.FreeTypeFontParameter();
para.size = 20;

因为舞台基准变小了，就要改成：
 FreeTypeFontGenerator.FreeTypeFontParameter para = new FreeTypeFontGenerator.FreeTypeFontParameter();
para.size = 2;

这样会报一个错误：
![Uploading 截屏2022-12-02 14.39.42.png…]()

并且如果舞蹈大小设置成8x6 那么所有子View的宽高给的值都很小，不太方便和设计稿标注保持一致。

**Comment by tommyettinger** [comment]
![opera_dSOTEcaYzA](https://user-images.githubusercontent.com/160684/205232161-8bd25add-89c2-496c-b2cb-0d2cfb4cc820.png)

Can you try to upload again?

**Comment by lewic1987** [comment]
> 

你好，报如下这个错误，这个不是重点，重点是如果我把舞台大小设置小了，所有的大小都得基于舞蹈大小尺寸标准设置，和设计稿的像素大小标注不一致，也很不方便，是我使用方式上有什么问题吗？谢谢

FATAL EXCEPTION: GLThread 1334
Process: com.tech9.emaoer.gdxdemo, PID: 27186
com.badlogic.gdx.utils.GdxRuntimeException: No cap character found in font
at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateData(FreeTypeFontGenerator.java:339)
at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:161)
at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:152)

**Comment by lewic1987** [comment]
@tommyettinger 麻烦看下上面的回复

**Comment by lewic1987** [comment]
> 

@tommyettinger 也可以看下这块的问题描述吗，谢谢

**Comment by Frosty-J** [comment]
> 我我可以将Stage的宽高设置的小一些，比如设置成8x6 但是 Stage里所有的 Actor就也是基于这个尺寸的，那么在设置字体大小时候 就需要设置成很小 ，

Either use multiple viewports (one for Box2D, one for your UI) or set the font scale (`font.getData().setScale(0.01f); font.setUseIntegerPositions(false);`).

**Comment by HydrolienF** [comment]
Can this issues be close ?

**Comment by crykn** [comment]
I think this can be closed for now. Regardless, it sounds more like a help request than an issue, which is better suited for the [Discord](https://libgdx.com/community/discord/) anyway.
