### ISSUE TITLE
Post runnable exceptions get omitted on Android and iOS backends

### ISSUE THREAD

**Issue by metaphore** [libgdx/libgdx#7046]
#### Issue details
Runtime exceptions originated from the post runnables' code get "muted" (`printStackTrace()` and ignore) on Android and RoboVM backends. Unlike on the other platforms, where those exceptions result in a hard crash or could be intercepted with the thread's default exception handler.

This is also a rather bad behavior as it tends to mask runtime issues and left developers unaware of something is broken (unless they lucky enough to spot the message in the log).

I wonder if this could be due to some technical specifics of the mobile platforms or somehow related to multithreading. But as far as I can see, there's no plain reason.

#### Reproduction steps/code
Run it on LWJGL3 or GWT backend and you get an obvious crash.
But try it on Android or iOS and magically nothing is going wrong...

```java
import com.badlogic.gdx.*;

public class PostRunnableCrash extends ApplicationAdapter {
    public void create () {
        Gdx.app.postRunnable(new Runnable() {
            @Override
            public void run() {
                throw new RuntimeException("You won't see me on mobile.");
            }
        });
    }
}
```

#### Version of libGDX and/or relevant dependencies
`1.11.0`

#### Please select the affected platforms
- [x] Android
- [x] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by PokeMMO** [comment]
Default or not default, we should have an option to "install" an exception handler. Printing to stderr doesn't really provide a useful way to log and fix exceptions.
