### ISSUE TITLE
渲染图片不清晰有锯齿

### ISSUE THREAD

**Issue by shumaosi** [libgdx/libgdx#7049]
Android 上渲染图片后不清晰有锯齿，需要什么配置吗

**Comment by shumaosi** [comment]
怎么关闭了

**Comment by mgsx-dev** [comment]
this is an issue tracker, use discord instead if you need help : https://libgdx.com/community/

**Comment by shumaosi** [comment]
网络原因， https://libgdx.com/community/进不去，能帮忙解决下图片模糊有锯齿的问题吗

**Comment by Frosty-J** [comment]
Perhaps a screenshot of the issue could help us understand? One thing to try might be to change your texture filtering, e.g. `texture.setFilter(TextureFilter.Linear, TextureFilter.Linear)` or to `Nearest` (default) but if it's being scaled by more than about 0.5-2x it'll look bad no matter what you do (except for pixel art where you actually might want to upscale by a large amount).

**Comment by LuoiZQ** [comment]
> 网络原因， [https://libgdx.com/community/进不去，能帮忙解决下图片模糊有锯齿的问题吗 ](https://libgdx.com/community/%E8%BF%9B%E4%B8%8D%E5%8E%BB%EF%BC%8C%E8%83%BD%E5%B8%AE%E5%BF%99%E8%A7%A3%E5%86%B3%E4%B8%8B%E5%9B%BE%E7%89%87%E6%A8%A1%E7%B3%8A%E6%9C%89%E9%94%AF%E9%BD%BF%E7%9A%84%E9%97%AE%E9%A2%98%E5%90%97)

这个链接现在用不了了

**Comment by Frosty-J** [comment]
https://libgdx.com/community/ without a sentence mashed onto the end of it should work, but Discord most likely can't be accessed in your country. Alternatives include:

* https://www.reddit.com/r/libgdx (English)
* https://stackoverflow.com/questions/tagged/libgdx (English)
* https://gamedev.stackexchange.com/questions/tagged/libgdx (English)
* https://t.me/libgdx (Russian)

Out of those, Reddit is the only one I visit with any regularity.
