### ISSUE TITLE
Image rotation 问题

### ISSUE THREAD

**Issue by shumaosi** [libgdx/libgdx#7050]
Image 旋转的问题，同一张图片，设置 rotation 后图片不清晰
代码：
override fun draw(batch: Batch, parentAlpha: Float) {

        parking1.apply {
            draw(batch, parentAlpha)
        }
        parking2.apply {
            setOrigin(Align.center)
            rotation = 92f
            draw(batch, parentAlpha)
        }

    }

![图片](https://user-images.githubusercontent.com/29273545/207760132-578cf7c6-818a-4a7a-9606-0d8af2e0daa4.png)

**Comment by mgsx-dev** [comment]
please use stackoverflow or reddit.
again, github issue tracker is not the right place to get help.
