### ISSUE TITLE
[gdx-setup] Add support for Gradle Kotlin DSL

### ISSUE THREAD

**Issue by bartekpacia** [libgdx/libgdx#7056]
#### Issue details

`gdx-setup` generates the libGDX project which uses Gradle's Groovy DSL.

It's also possible to write Gradle buildscripts in Kotlin DSL, which:

> provides an alternative syntax to the traditional Groovy DSL with an enhanced editing experience in supported IDEs, with superior content assist, refactoring, documentation, and more.

I'd like to be able to which Gradle DSL to use when creating a new libGDX project: Groovy or Kotlin.

See also:
- [Gradle Kotlin DSL Primer](https://docs.gradle.org/current/userguide/kotlin_dsl.html)

If not in the official `gdx-setup` app, this could be added to an alternative, _less conservative_ project generator such as [gdx-liftoff](https://github.com/tommyettinger/gdx-liftoff).

#### Please select the affected platforms

All or none - depends on how you look at it :)

**Comment by tommyettinger** [comment]
Oh goody, platform fragmentation! This was IMO a bad idea for Gradle to add and would be a bad idea for us to include. We would need help provided for two languages, with translations for each and people fluent in both to be able to help. I personally can barely read Gradle help as-is, and I find .kts scripts even less legible because they are completely unfamiliar. There's already enough help issues from just the folder differences in gdx-liftoff and gdx-setup, and where configuration goes... We really don't want to have to specify,
> In your root build.gradle file ~~or build.gradle.kts file~~, you'll need to add a plugin in the buildscript section ~~or wherever it goes in the Kotlin DSL~~ for GWT support.

**Comment by bartekpacia** [comment]
Thanks for fast response!

> This was IMO a bad idea for Gradle to add

Honestly, I thought the same, but in the recent weeks I've finally learnt Gradle, and its Kotlin DSL, and I have to say that the Kotlin DSL makes it much, much better experience. If you haven't tried it out, I highly recommend it!

<details>
<summary>Quick comparison</summary>

Here's `android/build.gradle`: IDE has problems with go-to-definition and good autocompletion

<img width="1066" alt="Screenshot 2023-01-01 at 9 55 54 PM" src="https://user-images.githubusercontent.com/40357511/210184376-a41700e5-336d-4bf6-8852-4049a3c5ee98.png">

And here's `android/build.gradle.kts` - you can see the type of every closure's _receiver_  (I believe it's called _delegate_ in Groovy's terminology):

<img width="1066" alt="Screenshot 2023-01-01 at 9 56 28 PM" src="https://user-images.githubusercontent.com/40357511/210184392-fc9e3de4-0769-4156-bf62-0a5a8f6894d3.png">


</details>

That said, I understand your worries. It's not that hard to replace `build.gradle` with `build.gradle.kts` when you have a working project to copy from (plug: I've recently fully migrated [my Spitfire game](https://github.com/bartekpacia/spitfire) to Kotlin DSL, feel free to look at it and get inspired, future wanderer).

PS Radical idea: you could make Gradle Kotlin DSL _the default_ in `gdx-setup`, much like Groovy DSL is the implicit default now.

**Comment by ice1000** [comment]
One bright side of Kotlin DSL is static typing, so you actually have IntelliJ to perform completion for you, and you'll be able to see all available configuration options.

Not a fan though.

**Comment by crykn** [comment]
gdx-setup was retired in favour of [gdx-liftoff](https://github.com/libgdx/gdx-liftoff). If you're still interested in this and think you can convince @tommyettinger, consider opening an issue over there.

**Comment by bartekpacia** [comment]
I see, thanks for an update!

btw is there some official announcement about gdx-setup being deprecated and gdx-liftoff being new? I'm just curious, I've not been using libGDX for years now - sad :(

**Comment by crykn** [comment]
There isn't an announcement about this as of yet, but maybe @tommyettinger wants to write a status report on the website about it?

**Comment by tommyettinger** [comment]
I don't want to write things other than code! The status announcement could be a paragraph like,

> Gdx-Liftoff has replaced gdx-setup as the new official setup tool! Link here. GWT works again. You have a choice of languages you can add. TeaVM is available to allow Kotlin web apps. You can choose from several templates, including some meant for Kotlin apps, and one template is a playable sample (Super Koalio). Many third-party extensions are readily available. Folders are structured differently, but are easier to add unit tests to, if you want. It's `lwjgl3`, not `desktop`, now, because it uses LWJGL3. LWJGL2 is also available if you need it. Raeleus made a video about it. Hooray!
