### ISSUE TITLE
Libgdx IOS Black Bars

### ISSUE THREAD

**Issue by aliyildiz1980** [libgdx/libgdx#7065]
I am developing an application using libgdx for both android and ios. I am using SceneUI with ExtendViewport. Although everyting seems to be perfect for android, there is an interesting black bar problem for ios. In android, the scene is extended to upper and lower parts successfully and covers all screen. But, for iOS, black bars appear.  You can see the screenshots for both platforms. The first one is for android and the second one is for iOS. As you can see there are black bars at the top and bottom screen.

gdxVersion version: 1.11.0
roboVM version: 2.3.19-SNAPSHOT
![android](https://user-images.githubusercontent.com/60661329/212679842-dd5dd8ba-4fe6-494e-a164-de375ce3c130.png)
![ios](https://user-images.githubusercontent.com/60661329/212679848-9da906f4-5d34-4e34-b259-ba42009a3af5.png)

**Comment by aliyildiz1980** [comment]
Apperantly, this problem is not related with ViewPort usage because in Android, it works perfect. There seems to be a problem in IOSApplication** classes. Will anybody be be able to provide a workarund for this problem?

**Comment by obigu** [comment]
To ask for help please use the libGDX Discord community channel (https://libgdx.com/community/). Closing the issue, feel free to reopen if you think this is a libGDX issue and provide a SSCSE (short, self contained, correct example) that reproduces it.
