### ISSUE TITLE
NullPointer Exception when using modelInstance constructor with nodeid other than root node

### ISSUE THREAD

**Issue by TomerconDevelopers** [libgdx/libgdx#7079]
code:
![image](https://user-images.githubusercontent.com/62302722/216016688-b89d3f36-8a93-43a0-92bc-28bbc6d02742.png)

Output:
![image](https://user-images.githubusercontent.com/62302722/216016478-4ed0981e-59cc-43cd-a718-8137a031c1b1.png)

**Comment by mgsx-dev** [comment]
please use discord instead for support requests : https://libgdx.com/community/

It sounds like you're instancing a skinned node without its bones (armature)
