### ISSUE TITLE
RenderContext error in blendSFactor, blendDFactor (GL_ZERO BlendingAttributes not working properly)

### ISSUE THREAD

**Issue by MikOfClassX** [libgdx/libgdx#7085]
RenderContext at this line is using:

`cullFace = blendSFactor = blendDFactor = 0;`

https://github.com/libgdx/libgdx/blob/79cf00af53b7f38667291fbacf544d3074a811bd/gdx/src/com/badlogic/gdx/graphics/g3d/utils/RenderContext.java#L51

But 0 is definitely a valid GL_ZERO value for blending equations.
I the aim is to invalidate  blendSFactor and blendDFactor, they must be set to -1

This will fix problem with GL_ZERO BlendingAttributes .

**Comment by mgsx-dev** [comment]
these values are not used when blending is false (see few lines below). Resetting them to zero is not necessary but i think it has been done to keep the context clean (the same state as when it was created).

**Comment by MikOfClassX** [comment]
I'm not getting the "context clean" meaning.  I just point out that blendFactor is set to a valid GL blend value.
Anyway, again I'll PR the fix.

**Comment by mgsx-dev** [comment]
@MikOfClassX Now i understand the issue. Because we only set values when they have changed, GL_ZERO will never be set. My bad.
