### ISSUE TITLE
DefaultShader disregards BlendingAttribute blended status

### ISSUE THREAD

**Issue by MikOfClassX** [libgdx/libgdx#7086]
Hello!

looking this code I noticed that the DefaultShader is not respecting the _blended_ flag.

https://github.com/libgdx/libgdx/blob/8b0f2b470e3966272f591670b5aa9c7008a1e30c/gdx/src/com/badlogic/gdx/graphics/g3d/shaders/DefaultShader.java#L831

Basically the presence of a BlendingAttribute is enabling blending even if blended is false.

I suppose the above line should be:

`context.setBlending(((BlendingAttribute)attr).blended , ((BlendingAttribute)attr).sourceFunction, ((BlendingAttribute)attr).destFunction);`

**Comment by mgsx-dev** [comment]
Apparently (as per javadoc and code), this field (BlendingAttribute.blended) is only use for sorting (RenderableSorter) and not for enabling/disabling blending.
I know it sounds weird and misleading but i guess some blending situation doesn't need to be sorted back to front...

If you're OK, i would keep it as is to avoid breaking things and then close the issue.

**Comment by MikOfClassX** [comment]
While we already fixed this misbeavior in our fork, i think the best thing is PR the fix so you can see if it's worth accepting it or not.

**Comment by mgsx-dev** [comment]
this is not a misbehavior, let continue the discussion in your PR : https://github.com/libgdx/libgdx/pull/7095#discussion_r1113561234 :-)
