### ISSUE TITLE
Problem rendering a tile map.

### ISSUE THREAD

**Issue by LuciusCouto** [libgdx/libgdx#7098]
Why when I render my block map a lot of black lines appear? 
Those lines that I showed in the image appear.

![Captura de tela 2023-02-24 200621](https://user-images.githubusercontent.com/97913684/221322689-89000548-ca7a-4f5e-9fe8-d1d63c9ecc64.png)

My code is this

`
  package com.libgdx.game;
  
  import com.badlogic.gdx.graphics.OrthographicCamera;
  import com.badlogic.gdx.maps.tiled.TiledMap;
  import com.badlogic.gdx.maps.tiled.TiledMapTileLayer;
  import com.badlogic.gdx.maps.tiled.TmxMapLoader;
  import com.badlogic.gdx.maps.tiled.renderers.OrthogonalTiledMapRenderer;
  
  public class MapRender {
	  TiledMap tiledMap;
      private OrthogonalTiledMapRenderer tiledMapRenderer;
      private float unitScale;
      public TiledMapTileLayer solidLayer;
      public boolean[][] collisionMap;
      
      
      public MapRender(String mapFilePath, float unitScale) {
          this.unitScale = unitScale;
          tiledMap = new TmxMapLoader().load(mapFilePath);
          tiledMapRenderer = new OrthogonalTiledMapRenderer(tiledMap, unitScale);
      }
  
      public void render(OrthographicCamera camera) {
          tiledMapRenderer.setView(camera);
          tiledMapRenderer.render();
      }
      
      public void dispose() {
    	  tiledMap.dispose();
    	  tiledMapRenderer.dispose();
      }
  }
`

- [ ] Android
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by tommyettinger** [comment]
You already got an answer in the Discord. This is not a bug in libGDX; this is a problem with your tileset, and you have been given several solutions already. You should try what Lyze suggested first:

> Replace your OrthogonalTiledMapRenderer with this one: https://github.com/lyze237-gamejams/FishOffSloth/blob/main/core/src/main/java/dev/lyze/fishoffsloth/utils/OrthogonalTiledMapRendererBleeding.java

I'm closing this because this is a problem on the user's side, not the library's side.

**Comment by LuciusCouto** [comment]
> Você já obteve uma resposta no Discord. Isso não é um bug na libGDX; este é um problema com seu conjunto de peças e você já recebeu várias soluções. Você deve tentar o que Lyze sugeriu primeiro:
> 
> > Substitua seu OrthogonalTiledMapRenderer por este: https://github.com/lyze237-gamejams/FishOffSloth/blob/main/core/src/main/java/dev/lyze/fishoffsloth/utils/OrthogonalTiledMapRendererBleeding.java
> 
> Estou fechando porque é um problema do lado do usuário, não da biblioteca.

Eu tentei colocar isso mas não deu certo
