### ISSUE TITLE
Incorrect value of angular velocity value from body object

### ISSUE THREAD

**Issue by Sanysvo** [libgdx/libgdx#7114]
#### Issue details
Hi, i cant understand, why method "getAngularVelocity" on a body object return incorrect value. After update world this method return max value 94,3 (wheelRPM). But if i set angular velocity manual, body mooved correct with my angular speed. How i can get actual angular velocity? In my code if i put "System.out,println" after angular velocity set i get correct value (wheelRPM). This code call every world step.

#### Reproduction steps/code
`float wheelRPM = this.rearWheel.getBody().getAngularVelocity();
System.out.println(wheelRPM + "  RPM eng: " + engine.getRpm());
this.rearWheel.getBody().setAngularVelocity(-3000);`

#### Version of libGDX and/or relevant dependencies
gdxVersion = '1.11.0'
roboVMVersion = '2.3.12'
box2DLightsVersion = '1.5'
ashleyVersion = '1.7.3'
aiVersion = '1.8.2'
gdxControllersVersion = '2.2.2'

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [x] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] macOS

**Comment by Frosty-J** [comment]
-3000 is an insane angular velocity. That would be 4712 revolutions per second. Box2D has its limitations on how fast things can rotate, as well as how fast they can travel within the world.

**Comment by Sanysvo** [comment]
@Frosty-J 
but it's not crazy at all. the wheel of the car makes about 1000-1200 revolutions per second at a speed of 150 kilometers per hour. and most importantly: my car is accelerating in box2d, and the wheel is gaining linear speed, which means that the angular velocity is increasing, but the method does not show this, resting on the limitation.

**Comment by Sanysvo** [comment]
So that you understand what I need and what my perplexity is. I am writing a physical car simulator. My most powerful engine runs at 9,000 rpm. The shortest transmission transmission is 0.6, and the shortest main pair is 3.1. Hence it turns out that under these conditions, 9000/3.1/0.6 = 4838.71 revolutions per minute will appear on the wheels. And this is 507.2 radians per second. And these are very real figures from the real world.

**Comment by obigu** [comment]
Box2d sets limits to the amont of angular rotation and angular correction per time step.

The default angual speed limit/time step is 0.5 * PI radians. If your time step is 1/60 the limit would be 30 * PI rad/s. You can find them on Box2d documentation https://box2d.org/documentation/b2__common_8h.html#a823e4f9a6fa4b9de3c97da696571400a. I don't know if the constants are exposed but I don't think it's a great idea to mess with them as they're there for a reason. If you can afford it you can always reduce your time step.

**Comment by Frosty-J** [comment]
I think it might be exposed on GWT only.

Fudging the units in some way could also work if you don't have the CPU time for more steps (though you probably do - Box2D is light under most circumstances). Have everything on a smaller scale, make the physics wheel size larger at fast speeds or even not simulated at all (static wheels with low friction - increase their friction to brake, add horizontal force to accelerate). Not ideal, but that's how it is with Box2D's finite accuracy.

**Comment by Sanysvo** [comment]
@obigu 
I understand what you mean. Yes, if I make a world step of 1/240, then I get the desired angular velocity accuracy. But that's just my whole world now looks in slow motion. How to fix it, because the game is in 60 frames

**Comment by Sanysvo** [comment]
Yes, it is solve my problem!
