### ISSUE TITLE
Rotation drawing Texture around X

### ISSUE THREAD

**Issue by Sanysvo** [libgdx/libgdx#7118]
#### Issue details
I want create effect of push my pedal, and rotate it forward (along Z axis) around X axis. Rotation is correct, but my pedal not draw full. I think it caused depth drawing.

![image](https://user-images.githubusercontent.com/54953072/230008075-e0f3c54c-d831-4f00-9ded-f17f73bfe46b.png)
![image-1](https://user-images.githubusercontent.com/54953072/230008083-f9cdb301-26c0-42b5-95a6-86ccb35af893.png)
#### Reproduction steps/code

```
if (this.isHold) {
            this.matrix4 = batch.getTransformMatrix().cpy();
            Matrix4 copy = new Matrix4(matrix4);
            copy.rotate(new Vector3(1,0,0), -40);
            batch.setTransformMatrix(copy);
        }

        batch.draw(texture, getX(), getY(), texture.getRegionWidth()/scale, texture.getRegionHeight()/scale);
        if(isHold) {
            batch.setTransformMatrix(matrix4);
        }
```

#### Version of libGDX and/or relevant dependencies
gdxVersion = '1.11.0'
roboVMVersion = '2.3.12'
box2DLightsVersion = '1.5'
ashleyVersion = '1.7.3'
aiVersion = '1.8.2'
gdxControllersVersion = '2.2.2'

#### Please select the affected platforms
- [ x] Android
- [ ] iOS
- [ ] HTML/GWT
- [ x] Windows
- [ ] Linux
- [ ] macOS

**Comment by Sanysvo** [comment]
Nobody have ideas?

**Comment by Tom-Ski** [comment]
You are most likely using an orthographic projection, which will not have any perspective effect, and also you will be hitting a clipping plane that is clipping your triangles when it gets out of bounds which is why it disappears. 

That said,
This question is better suited to the discord, rather than the issue tracker.
