### ISSUE TITLE
Release 1.11.1 (or call it 1.12.0)?

### ISSUE THREAD

**Issue by noblemaster** [libgdx/libgdx#7158]
There is no official libGDX release for 1+ years (last official release was in May 2022). I think it might be time to release a new version?There are several changes that would be kind of nice to have:
- LWJGL 3.3.2: fixes some bugs on Mac OS.
- Misc. Audio Bugfixes, especially for LWJGL3.
- MobiVM 2.3.19: Support for latest iOS builds.
- many other improvements & fixes over the past year.

I'd probably propose to call it 1.12.0 as it has some breaking changes?

**Comment by HydrolienF** [comment]
Calling 1.12.0 will be more conventional. I also think it's a better idea.

I think we are waiting for https://github.com/libgdx/libgdx/milestone/4 to be done.

**Comment by noblemaster** [comment]
I guess it's just about the window resizing issue resolved (LWJGL 3) as the other pull requests are more or less ready.

**Comment by TCreutzenberg** [comment]
What happened to this plan: https://libgdx.com/news/2020/09/devlog_2_release_schedule

Are there just not enough changes for a full release each month or is it too much work to create a proper release?
I don't have any negative feelings, I'm just curious about the reasons.

**Comment by Frosty-J** [comment]
This was discussed on Discord. More to do with work than a lack of changes.

> IIRC we have stated quite a few times that our initial plan of releasing new versions every month was too ambitious. On the other hand, I know that our current release schedule can be pretty frustrating for users and is exactly what we were complaining about ourselves when we joined the team a couple of years ago. 
> 
> So, what is taking us so long? I think “time” describes it quite well. We need to test and review new PRs and finding spare time for that isn’t always easy. I know I’ve stated this in the past, but I think it bears repeating: if you want libGDX to release faster, this is where you can chime in. Just take a look at open PRs, test them, and write a short review. I’ve also tried using the milestones to make more transparent, which PRs I’d like to get into new releases.
> 
> Also, at the moment there aren’t that many people left on the team who can “press the button”, but I think they don’t have that much free time on their hands. Maybe we should look into expanding that circle of people, but that isn’t my call. 
> 
> There probably is a good middle-ground to be found here: IMO a release every three to four months sounds pretty reasonable and should help get new PRs merged faster. Also, I don’t think there is any reason to fear that libGDX is being abandoned: we all care about the framework, otherwise we wouldn’t be here; also we recently took on two new team members to help get things done quicker.

**Comment by noblemaster** [comment]
> We need to test and review new PRs and finding spare time for that isn’t always easy. I know I’ve stated this in the past, but I think it bears repeating: if you want libGDX to release faster, this is where you can chime in. Just take a look at open PRs, test them, and write a short review. I’ve also tried using the milestones to make more transparent, which PRs I’d like to get into new releases.

I agree, testing all the PR take time. Maybe we could take a different approach? We release new features anyway and declare all `*.*.0` releases as ALPHA/BETA. That way, the users will test and we release `*.*.1`, `*.*.2` etc. versions to fix stability issues?

**Comment by crykn** [comment]
We could also try to do "release candidate" releases before every version. So we could test things out in 1.13.0-RC1 first and then release 1.13.0 once we're sure everything works.
