### ISSUE TITLE
GLX: Failed to load GLX

### ISSUE THREAD

**Issue by 0312birdzhang** [libgdx/libgdx#7163]
#### Issue details
As asked on [lwjgl3](https://github.com/LWJGL/lwjgl3/issues/891), i found maybe it's not their fault.

Minecraft java edition is working well on my orangepi 5 dev board.

And the native glfw examples runs very well too.

#### Reproduction steps/code

Run [flowpilot ](https://github.com/flowdriveai/flowpilot) on linux aarch64 x11 desktop, they have a [wiki ](https://github.com/flowdriveai/flowpilot/wiki/Installation#installing-on-desktop)how to install it.

#### Version of libGDX and/or relevant dependencies
1.10.0 and 1.11.0, both not working

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
[main] INFO ai.flow.launcher.FlowInitd - Connected to the FlowInit daemon
110110110
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[LWJGL] GLFW_API_UNAVAILABLE error
        Description : GLX: Failed to load GLX
        Stacktrace  :
                org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2024)
                org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2197)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:524)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:462)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:448)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:162)
                ai.flow.app.lwjgl3.Lwjgl3Launcher.createApplication(Lwjgl3Launcher.java:52)
                ai.flow.app.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.java:25)
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't create window
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:527)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:462)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:448)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:162)
        at ai.flow.app.lwjgl3.Lwjgl3Launcher.createApplication(Lwjgl3Launcher.java:52)
        at ai.flow.app.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.java:25)

```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] macOS

**Comment by tommyettinger** [comment]
Just looked at their wiki, and there is no way on God's green Earth that I am installing this on hardware. I am not doing Java gamedev to have to look at wiring diagrams! I have no idea what a "red and black panda" or "giraffe" is, nor do I really want to know. I don't have a disposable car to mess with its wiring, either...

Your error most likely has to do with graphics drivers on your... whatever hardware this is. You may have working drivers that aren't getting picked up for some reason. Other tools like https://github.com/ptitSeb/gl4es showed up when I searched for OpenGL and OrangePi, which suggests the OrangePi only runs OpenGL ES and not desktop OpenGL. I don't know if you're running on an OrangePi. The version of Minecraft you ran may use a shim such as gl4es to be compatible with mobile-like Linux hardware.

You'll really have to provide... a lot more information, and hope that someone who happens to have comparable hardware is out there and is willing to go through the significant amount of steps to test this if you suspect there actually is a bug in libGDX.

**Comment by 0312birdzhang** [comment]
Java core dump files: 
[hs_err_pid41828.log](https://github.com/libgdx/libgdx/files/11714362/hs_err_pid41828.log)

Seems it crashed after load `/tmp/libgdxorangepi/8c18a7e6/libgdxarm64.so`

**Comment by tommyettinger** [comment]
That is a lot of information that mostly doesn't help. The important things are mainly:

 - What type of machine it is important (is it actually an OrangePi? what model?). 
 - What kind of graphics hardware that machine has is also important.

Crashing after loading a library doesn't mean it crashed in that library, or that the loading somehow caused the crash. The stack always ends at GLFW and then bare JNI code. I have yet to see any sign that there is a bug in libGDX that causes your mystery crash.

**Comment by Berstanio** [comment]
> Java core dump files: [hs_err_pid41828.log](https://github.com/libgdx/libgdx/files/11714362/hs_err_pid41828.log)
> 
> Seems it crashed after load `/tmp/libgdxorangepi/8c18a7e6/libgdxarm64.so`

Can you try to find out, what `org.lwjgl.glfw.GLFW.Functions.CreateWindow` contains as a value (if it is non 0)?

**Comment by 0312birdzhang** [comment]
> * What type of machine it is important (is it actually an OrangePi? what model?).
> * What kind of graphics hardware that machine has is also important.


1.  Ok, so spam it here again as i posted on [lwjgl](https://github.com/LWJGL/lwjgl3/issues/891)
## System info
```
orangepi@orangepi5:~$ uname -a
Linux orangepi5 5.10.110-rockchip-rk3588 #1.1.4 SMP Wed Mar 8 14:50:47 CST 2023 aarch64 aarch64 aarch64 GNU/Linux
orangepi@orangepi5:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```
It is [Orangepi 5](http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-5.html), rk3588 platform.

2. It has ARM Mali-G610 GPU

**Comment by tommyettinger** [comment]
According to ARM ( https://developer.arm.com/documentation/102849/0400/?lang=en ), the Mali-G510 and Mali-G710 both support OpenGL ES, but not (desktop) OpenGL. I'd guess the 610 is between the two of those. I don't know if GLFW, libGDX, LWJGL3, or any of this mix run on desktop platforms without desktop OpenGL. Most testing people do with 64-bit ARM PCs happens on the more-mainstream Raspberry Pi.

**Comment by 0312birdzhang** [comment]
I changed to [ubuntu 22.04](https://github.com/Joshua-Riek/ubuntu-rockchip) with panfork hack, and it's working now.

So, i close this issue as it's should be not related to libgdx.
