### ISSUE TITLE
Android GL30 Deprecated/Experimental

### ISSUE THREAD

**Issue by JamesTKhan** [libgdx/libgdx#7182]
#### Issue details
This issue came up after a discussion in discord. In `AndroidApplicationConfiguration.java` useGL30 is marked as deprecated. Based on the comments in the code, reason it was marked as deprecated was to warn the user that is was experimental. The deprecation tag also can make it a bit confusing to the end user (as was the case in Discord). Android GLES 3.0 support along with the deprecated tag was added in 2016.

```
/** Experimental, whether to enable OpenGL ES 3 if supported. If not supported it will fall-back to OpenGL ES 2.0. When GL ES
 * 3* is enabled, {@link com.badlogic.gdx.Gdx#gl30} can be used to access its functionality. Requires at least Android 4.3 (API
 * level 18).
 * @deprecated this option is currently experimental and not yet fully supported, expect issues. */
@Deprecated public boolean useGL30 = false;
```

**Should we still consider GL30 on Android devices experimental?** Based on this distribution dashboard it looks like 87% of devices support GLES 3.0 (https://developer.android.com/about/dashboards#OpenGL).

That being said, GWT is in the same boat. I followed the same pattern as Android and marked it deprecated in GwtApplicationConfiguration with a similar experimental warning. The GWT GL30 implementation is much newer so there could be a argument for keeping the deprecated tag there for the time being.

#### Reproduction steps/code
N/A

#### Version of libGDX and/or relevant dependencies
1.12.0

#### Stacktrace
N/A

#### Please select the affected platforms
- [x] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by mgsx-dev** [comment]
IMHO, deprecation should only be set for things that will be removed in the future. I removed them from shadow maps some time ago. Generally, experimental things could be in branches/PRs, another way would be to have a different annotation. But TBH, if it's too experimental, maybe it shouldn't be there at the first place.
So, a big +1 for me.
