### ISSUE TITLE
DefaultAndroidInput: delta is always zero for dragging events

### ISSUE THREAD

**Issue by little-brother** [libgdx/libgdx#7187]
Gdx.input.getDeltaX(pointer) and Gdx.input.getDeltaY(pointer) return 0 for pointer = 0.
It's a new behaviour appearing in version 1.12. I think the reason is [these 4 lines](https://github.com/libgdx/libgdx/blob/75612dae1eeddc9611ed62366858ff1d0ac7898b/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/DefaultAndroidInput.java#L392). I don't understand for what kind of problems they should solve. 
Another pointers don't have a similar reset and drag works correctly for them. 

The demo project is attached. Run it  and check LogCat from a connected device,
[inputbug.zip](https://github.com/libgdx/libgdx/files/12033015/inputbug.zip)

Libgdx v1.12, Android

**Comment by tommyettinger** [comment]
This definitely looks like a bug; I ran the demo project, and it only receives drag x and y input as 0 and 0. The only change I made was switching to Gdx.app.log() instead of System.out.println(), just because I am not very experienced with Android and I wasn't sure how to view various things. @Frosty-J , any thoughts on this catchy situation?

**Comment by Frosty-J** [comment]
Did this work on desktop? I added those lines in Android because it seems equivalent to desktop.

https://github.com/libgdx/libgdx/blob/75612dae1eeddc9611ed62366858ff1d0ac7898b/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/DefaultLwjgl3Input.java#L207-L208

**Comment by tommyettinger** [comment]
It does produce non-zero coordinates on Desktop. They seem to be relative; they're often small negative or positive values in my limited testing.

**Comment by little-brother** [comment]
> Did this work on desktop?

Yes, it does.

> I added those lines in Android when implementing cursor-catching because it seems equivalent to desktop.

I'm not sure but touches and mouse should have different behaviours (and therefore event handlers). I don't think that the cursor catching for touches is needed (I didn't go deep in it, so maybe I'm wrong).

**Comment by Frosty-J** [comment]
Hmm, yeah. I'm not sure if there's a good way to detect whether someone is using the touchscreen on an Android device or a mouse (more common on Chromebooks).

**Comment by obigu** [comment]
What's the plan to fix this? I'm not too bothered about cursor catching on Chromebooks but quite a bit on the regression bug. Shall we revert in the meantime?

**Comment by tommyettinger** [comment]
I am definitely in favor of reverting the cursor-catching change on Android; I'm surprised this hasn't come up more often.

**Comment by Frosty-J** [comment]
If we don't know why the other backends set delta to 0, reverting is probably the easiest course of action. Be sure to update the changelog to say the feature has been removed.
