### ISSUE TITLE
Runnable particle editor jar can't open pfx file

### ISSUE THREAD

**Issue by wangdong20** [libgdx/libgdx#7188]
#### Issue details
I just download the runnable particle editor jar file on libgdx website. I can open the jar file but all ui components are empty. I can't open pfx file neither.

#### Reproduction steps/code
1. Run the particle editor jar file
2. Open pfx file
3. Nothing happens but with error log in my terminal

#### Version of libGDX and/or relevant dependencies
Mac Pro

#### Stacktrace
```java
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/Users/***/Downloads/runnable-2D-particles.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: OpenGL is not supported by the video driver.
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.createDisplayPixelFormat(LwjglGraphics.java:413)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:291)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:145)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)
Caused by: org.lwjgl.LWJGLException: Parent.isDisplayable() must be true
	at org.lwjgl.opengl.Display.createWindow(Display.java:301)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.createDisplayPixelFormat(LwjglGraphics.java:404)
	... 3 more
Warning: the fonts "Times" and "Times" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning.
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] macOS

**Comment by Frosty-J** [comment]
You could try with Java 8, but I'm not hopeful. If you have access to Windows, Linux, or an Intel Mac, I'd try that instead for the time being. It may be easier to keep this in #7183. gdx-tools and LWJGL2 in general is in a state of decay.

**Comment by crykn** [comment]
Hey @wangdong20, can you try whether this issue still persists with the new particle editor over at https://github.com/libgdx/gdx-particle-editor?

**Comment by wangdong20** [comment]
> Hey @wangdong20, can you try whether this issue still persists with the new particle editor over at https://github.com/libgdx/gdx-particle-editor?

Hi, I am so glad you made a new version particle editor. I tried it, it works when open .p file but it seems doesn't support open .pfx file yet and I found a bug which is the editor will crash when click cancel when choose file prompt showed.

**Comment by raeleus** [comment]
> Hi, I am so glad you made a new version particle editor. I tried it, it works when open .p file but it seems doesn't support open .pfx file yet and I found a bug which is the editor will crash when click cancel when choose file prompt showed.

Can you give me the crash log? It's likely in your user folder >> .particleparkpro or .gdxparticleeditor. You can also open up the particle editor, click on settings in the lower right, and click "Open Log Directory".

**Comment by wangdong20** [comment]
> > Hi, I am so glad you made a new version particle editor. I tried it, it works when open .p file but it seems doesn't support open .pfx file yet and I found a bug which is the editor will crash when click cancel when choose file prompt showed.
> 
> Can you give me the crash log? It's likely in your user folder >> .particleparkpro or .gdxparticleeditor. You can also open up the particle editor, click on settings in the lower right, and click "Open Log Directory".

[hs_err_pid89886.log](https://github.com/libgdx/libgdx/files/13466794/hs_err_pid89886.log)
[hs_err_pid89936.log](https://github.com/libgdx/libgdx/files/13466795/hs_err_pid89936.log)

**Comment by raeleus** [comment]
I'm thinking that means it's a crash in Tiny File Dialogs which will be really hard to work around. I'll have to get my hands on a Mac to do some serious testing.
Is there any chance you can give me your PFX file that isn't working, @wangdong20? Thanks for helping me out.

**Comment by tommyettinger** [comment]
I'm trying to answer this TFD issue in the particle editor repo, here https://github.com/libgdx/gdx-particle-editor/issues/3 . If you want to continue it here, feel free to close my issue over there.

**Comment by wangdong20** [comment]
> I'm thinking that means it's a crash in Tiny File Dialogs which will be really hard to work around. I'll have to get my hands on a Mac to do some serious testing. Is there any chance you can give me your PFX file that isn't working, @wangdong20? Thanks for helping me out.

The pfx files are from same folder with p files. I have checked those files, they are in same format but with different suffix. I have no idea why there are also pfx files in the same folder, I am guessing particle editor supports pfx files as well long time ago, so they provided pfx files.

[effects.zip](https://github.com/libgdx/libgdx/files/13470340/effects.zip)

**Comment by raeleus** [comment]
Thanks for uploading those. There was no established extension for particle files back then, so anyone can name them anything. In any case, these files actually worked for me on windows. You can deselect "presume file extension is .p" in the settings. There is nothing special about the pfx files provided.
As for the file dialog issues: it might have to do with mac security settings. Try these steps here which made a difference for one of my testers: https://github.com/libgdx/gdx-particle-editor/wiki#how-to-run-gdx-particle-editor.
I think the original question this issue is in reference to is no longer a problem. This new issue should be addressed in the gdx-particle-editor repo.

**Comment by tommyettinger** [comment]
OK, I'm closing this, and linking https://github.com/libgdx/gdx-particle-editor/issues/3 again. That's where future issues for the new particle editor should be addressed. Thanks for your cooperation!
