### ISSUE TITLE
[Feature Request] Can we have simple animation functions for sprites (like CCAction)

### ISSUE THREAD

**Issue by rv4cgvfx** [libgdx/libgdx#7197]
Can we have simple animation functions like we have in Cocos2d-x (CCAction) ?

Currently we need to create animation frame-by-frame in another application for a simple sprite animation and then import all frames.
Instead of that we can just import our Sprite and use this built in simple animation function.

This would allow developers to bring in sprite and use animations like fade-in/out, move-up/down/right/left, transition effects and all instead of animating simple animations of fade-in/out etc.

**Comment by tommyettinger** [comment]
What you're asking about isn't really clear. There are such functions already in [scene2d's Actor and Actions system](https://libgdx.com/wiki/graphics/2d/scene2d/scene2d#actions). To "import all frames" or import a Sprite isn't a thing in libGDX, unless you mean copying the files into your assets and maybe merging into an atlas. You might also consider Spine, the commercial skeletal animation program from some authors of libGDX, if you need a visual way of editing animations.

**Comment by rv4cgvfx** [comment]
This is a simple fadeout animation in Cocos2dx -

CCSprite* sprite = CCSprite::create("your_sprite.png");
sprite->setPosition(ccp(320, 240));
addChild(sprite);

// Create a fade-out action with duration
CCAction* fadeOut = CCFadeOut::create(2.0f); // 2 seconds duration
sprite->runAction(fadeOut);

You simply load sprite and have an action on it. No need to create fade out animation in other software and load all those frames in your game.

**Comment by tommyettinger** [comment]
> There are such functions already in [scene2d's Actor and Actions system](https://libgdx.com/wiki/graphics/2d/scene2d/scene2d#actions).

They're even called Actions. If you don't want to read responses to your requests, then you don't have to make them.
