### ISSUE TITLE
Where is the data folder?

### ISSUE THREAD

**Issue by wangdong20** [libgdx/libgdx#7198]
#### Issue details
I want to find the data/test.p and the picture files in ParticleEmitterTest.java code. But I couldn't find it.

#### Reproduction steps/code
1. Open ParticleEmitterTest.java 
2. Find the line of code where use Gdx.internal("data/test.p")

#### Version of libGDX and/or relevant dependencies
Current version

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] macOS

**Comment by Frosty-J** [comment]
https://github.com/libgdx/libgdx/blob/master/tests/gdx-tests-android/assets/data/test.p

The test assets are in there because funny old reasons. All good file managers have a search function.

**Comment by tommyettinger** [comment]
Thanks @Frosty-J , that was fast. I think this can be closed now.
