### ISSUE TITLE
Block Maximized Button

### ISSUE THREAD

**Issue by isaidElectro** [libgdx/libgdx#7226]
The problem occurs when I set config.setWindowSizeLimits(100, 100, 200, 200); and then when I maximized it, it goes to the upper-left of the screen

I want it to be resizable but with the maximized button blocked.

Example names:
config.setMaximized(boolean maximized, boolean maximizedButton);
or
config,setResizable(boolean resizable, boolean maximizedButton)

- [ ] Windows

**Comment by crykn** [comment]
Without upstream support there isn't really anything we can do here. 

As a workaround, you can either try the hack proposed by @SomeTroglodyte or disable window decoration completely and just draw what you still need (window title & close button) yourself.
