### ISSUE TITLE
Intersector.intersectPolygons calculates incorrect overlap polygon

### ISSUE THREAD

**Issue by thelsing** [libgdx/libgdx#7228]
#### Issue details
I got and issue where I think that the intersector produces an incorrect clipped polygon. 
#### Reproduction steps/code
```
import com.badlogic.gdx.*;
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.math.Intersector;
import com.badlogic.gdx.math.Polygon;

public class Test extends ApplicationAdapter {
    public void create () {
        // your code here
    }
    private boolean written = false;
    public void render () {
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        var clip = new Polygon(new float[] {94.5f, 0.0f, 94.5f, 63.0f, 189.0f, 63.0f, 189.0f, 0.0f});
        var toClip = new Polygon(new float[] {0.0f, 0.0f, 0.0f, 200.0f, 310.0f, 200.0f, 310.0f, 0.0f, 210.0f, 0.0f, 210.0f, 100.0f, 100.0f, 100.0f, 100.0f, 0.0f});
        var intersect = new Polygon();
        Intersector.intersectPolygons(toClip, clip, intersect);
        // intersect is [94.5, 0.0, 94.5, 63.0, 189.0, 63.0, 100.0, 63.0, 100.0, 0.0] instead of
        // [94.5, 0.0, 94.5, 63.0, 100.0, 63.0, 100.0, 0.0]
        if(written)
            return;

        var verts = intersect.getVertices();
        for(int i = 0; i<verts.length; i+=2)
        {
            written = true;
            System.out.println("(" + verts[i] + ", " + verts[i+1] + ")" );
        }
    }

    public static void main (String[] args) throws Exception {
        new Lwjgl3Application(new Test());
    }
}
```

#### Version of libGDX and/or relevant dependencies
1.12

Polygons to intersect:
<img width="186" alt="image" src="https://github.com/libgdx/libgdx/assets/20617946/8046868e-d218-4187-9731-1e58311750a1">

Result I get:
<img width="69" alt="image" src="https://github.com/libgdx/libgdx/assets/20617946/14adf830-19e6-4659-b9b6-d3f867096bc2">

**Comment by tommyettinger** [comment]
[Docs](https://github.com/libgdx/libgdx/blob/bb799a9cd0a92cadb0425acd6064654cd7a4d6c8/gdx/src/com/badlogic/gdx/math/Intersector.java#L149) specify that the polygons must be [convex](https://en.wikipedia.org/wiki/Convex_polygon). Your green polygon is concave, not convex. You can subdivide it into squares, rectangles, or triangles, which would be convex.

This is not an issue with libGDX (it behaves exactly as documented, and as is supported by the algorithm it uses), so I'll close this. You can ask further questions on the [Discord](https://libgdx.com/community/discord/), preferably in quick-help, a topic in help, or box2d for any physics-related questions.
