### ISSUE TITLE
Triple clicks on the screen disrupt the very state of pressing the screen

### ISSUE THREAD

**Issue by SheunOleg** [libgdx/libgdx#7256]
#### Issue details
_The problem arose when switching from the previous version of the library 1.11.0 to 1.12.0_

#### Reproduction steps/code
All you have to do is quickly press three fingers on the screen at the same time, and then libjx will record the extra press. More precisely, the fact that the finger was not removed.
And then if you move with one single finger, it will be considered that “pinching” is happening, and instead of moving, make a "zoom" here
![image](https://github.com/libgdx/libgdx/assets/12183149/6abfac3b-efb2-41d8-a4fd-5c4ddd40da2f)
And all because here the check is incorrectly verified, mistakenly believing that the finger was not released.
![image](https://github.com/libgdx/libgdx/assets/12183149/243fad4b-864e-4735-b451-e74e09eb75dd)
If you then press with two fingers at the same time, everything will return to normal.
We use libgdx in different modules, and each one has this problem, regardless of the screen.

#### Version of libGDX and/or relevant dependencies
_Version 1.12.0_

#### Please select the affected platforms
- [ ] Android

**Comment by obigu** [comment]
Haven't been able to reproduce on current master. Tested on `GestureDetectorTest` and `MultiTouchTest` on a Galaxy S7 with Android 8. Can you try 1.12.1-SNAPSHOT?

**Comment by SheunOleg** [comment]
I completely forgot. We reproduced the problem on Android 12 and 13 version. And I checked on the 1.12.1-SNAPSHOT, the problem is still there.
https://drive.google.com/file/d/1z_EF3bTqL9abR_Ly16b0E0A4spWaapRF/view?usp=sharing
Here is a recording of the problem, which clearly shows that there were 3 taps on the screen. And then there was a zoom with one finger
As I wrote when rolling back the version, everything is correct. And here, working with one finger, in checking the queue which finger is pressed, almost 10 values are true
![image](https://github.com/libgdx/libgdx/assets/12183149/a8d73c1e-5fb8-48ac-ab5e-ab8dba4a00e5)

**Comment by SheunOleg** [comment]
1. POCO F3, Android 12
OnePlus Nord CE 2, Android 13
2. Yes https://drive.google.com/file/d/1MQM8ZZEQdt2sjy8S_vSunlPP6enxbu5m/view?usp=sharing
3. At the moment it is not possible

**Comment by obigu** [comment]
Ok, it's consistent with the discussion on Discord #android. It seems it affects some specific devices that intercept 3 finger gestures for stuff such as taking a screenshot. The behaviour doesn't reproduce when that setting is disabled. I'll try to work on a PR because I think I know what the problem is. If I manage to set up a Pixel device to do a 3 finger system action I'll be able to test it, otherwise I'll submit it blindly and wait for your feedback.

**Comment by obigu** [comment]
I've made an attempt to fix it here https://github.com/libgdx/libgdx/pull/7259 but needs testing. Can you please test it locally?
