### ISSUE TITLE
Overlaps of Rectangle could not work properly when the width or height is negative

### ISSUE THREAD

**Issue by voidvvv** [libgdx/libgdx#7257]
#### Issue details
the overlap works well when the width and height of the rectangle is positive,
but is doesn't work when we got the negative width and height.

#### Reproduction steps/code
like this code: 
```java
    public static void main(String[] args) {
        Rectangle r1 = new Rectangle();
        r1.set(5,5,-10,-10);

        Rectangle r2 = new Rectangle();
        r2.set(0,0,10,10);

        System.out.println(r1.overlaps(r2));
        System.out.println(r2.overlaps(r1));

    }
in this way ,we can see the console print: false.
it seems like this method need to be fix: 
	public boolean overlaps (Rectangle r) {
		return x < r.x + r.width && x + width > r.x && y < r.y + r.height && y + height > r.y;
	}


```

#### Version of libGDX and/or relevant dependencies
1.10.0

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by HydrolienF** [comment]
Maybe we should throw an IllegalArgumentException when user try to create a negative width or height rectangle.

**Comment by crykn** [comment]
IMO if we add an IllegalArgumentException to Rectangle, we'd also need to add one to Circle, Ellipse, etc., which seems kinda overkill for such a niche issue. I'd vote to just close this as – at its core – its a problem of incorrect usage.

**Comment by obigu** [comment]
> IMO if we add an IllegalArgumentException to Rectangle, we'd also need to add one to Circle, Ellipse, etc., which seems kinda overkill for such a niche issue. I'd vote to just close this as – at its core – its a problem of incorrect usage.

If we had to design the API from 0 we could decide on how we want shapes to deal with negative dimensions but this is not the case anymore and I agree it's not worth introducing a breaking change for this. Some people may be using `Rectangle` (or other shapes) negative widths/heights/radios on their projects, maybe they have a rectangle to which the add and substract sizes and some dimension is temporary negative or other easy to imagine scenarios. I'll close as Won't fix.
