### ISSUE TITLE
is atlas.findRegions method work error ?

### ISSUE THREAD

**Issue by helloworq** [libgdx/libgdx#7262]
Please ensure you have given all the following requested information in your report.

#### Issue details
i am using the lib creating anmation. when i called the method atlas.findRegions() it only return one AtlasRegion object. and then i checked then method , i thing it is acturally return only one frame.

please see the method findRegions(), when i pass a param to it. the equals function acturally just match the result that have the same name. i mean the method will not return more than one element . so why it called regions .

![微信截图_20231024171806](https://github.com/libgdx/libgdx/assets/26016637/be868396-e108-46e1-85b4-00e5f7b09acc)

addition:
i will return more than one element when you have same name png. but it is will confused for same name pngs. will it support to divied it by indexes? i checked the doc and the answer is yes. but i can not find how to do it;

#### Version of libGDX and/or relevant dependencies
1.12.0

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ~] Windows
- [ ] Linux
- [ ] macOS

**Comment by tommyettinger** [comment]
https://libgdx.com/wiki/tools/texture-packer#image-indexes

**Comment by helloworq** [comment]
> https://libgdx.com/wiki/tools/texture-packer#image-indexes

i am sorry for not describing the issue clearly. I mean the method only return multiple result with same name but not with the suffix addition indexes. So i have to call the getRegions() method and do it on my own.amd i have checked the doc, it also write that each png should have a diff suffix.
