### ISSUE TITLE
Back swipe gesture triggers longPress

### ISSUE THREAD

**Issue by SakiiCode** [libgdx/libgdx#7263]
#### Issue details
Android's gesture-based navigation interferes with GestureDetector. Swiping to go back triggers a longPress event after the longPress delay.

https://github.com/libgdx/libgdx/assets/13037299/08cb49ea-3f4d-4b65-9904-82e62cf0209d

#### Reproduction steps/code
1. Enable gesture based system navigation
2. Set libGDX to catch back key
3. Implement longPress in a GestureListener and set it as input processor

```
        Gdx.input.setCatchKey(Keys.BACK, true);
		Gdx.input.setInputProcessor(new GestureDetector(this));
```

#### Version of libGDX and/or relevant dependencies
Tried 1.11.0 and 1.12.0, both has this issue

#### Stacktrace
```
dalvik.system.VMStack.getThreadStackTrace(Native Method)
java.lang.Thread.getStackTrace(Thread.java:1841)
************.longPress(********)
com.badlogic.gdx.input.GestureDetector$1.run(GestureDetector.java:58)
com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:498)
android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
```

#### Please select the affected platforms
- [x] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by obigu** [comment]
Can you please try 1.12.1-SNAPSHOT?

**Comment by obigu** [comment]
Can you please test https://github.com/libgdx/libgdx/pull/7265?

**Comment by SakiiCode** [comment]
It works! Thank you!
