### ISSUE TITLE
on iOS game looks stretched

### ISSUE THREAD

**Issue by ollyde** [libgdx/libgdx#7268]
Using iPhone 14, upgrading a 8 year old game.

Works fine on Android and Desktop. iPhone it looks distorted and small.

With `config.hdpiMode = HdpiMode.Pixels;`
![IMG_0600](https://github.com/libgdx/libgdx/assets/6940726/c677aba5-c66a-4800-b551-d2e5ff822ee8)

Without 
![Screenshot 2023-11-01 at 16 33 45](https://github.com/libgdx/libgdx/assets/6940726/3a6fbd05-3b43-419a-a3c8-a244741f0244)

```
appName = "---"
gdxVersion = '1.12.0'
roboVMVersion = '2.3.20'
box2DLightsVersion = '1.5'
ashleyVersion = '1.7.4'
aiVersion = '1.8.2'
gdxControllersVersion = '2.2.1'
```

Does anyone have any ideas here?

**Comment by ollyde** [comment]
I upgraded to using `Gdx.graphics.getBackBufferHeight()` but I face the issue where the width is stretched now. 🙈

**Comment by ollyde** [comment]
![IMG_0602](https://github.com/libgdx/libgdx/assets/6940726/04a0c27f-bd35-4a4a-b9f7-adbb08789ce9)

So on Android and Desktop it's working fine, is there an issue with iOS?

**Comment by obigu** [comment]
This is an issue tracker, you can ask for help on our Discord channel or the othercommunities https://libgdx.com/community/.

**Comment by ollyde** [comment]
@obigu no worries, I've asked the community; this does seem like an issue on iOS GDX library though since Desktop and Android are working 100%.
