### ISSUE TITLE
Please identify commit for 1.12.0 changelog entry "Fixed incorrect ScrollPane#scrollTo"

### ISSUE THREAD

**Issue by SomeTroglodyte** [libgdx/libgdx#7272]
#### Issue details
[git blame](https://github.com/mgsx-dev/libgdx/blame/master/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ScrollPane.java#L837) on the cited function is entirely over 3 years old, way older than [1.11.0](https://github.com/libgdx/libgdx/releases/tag/1.11.0); and [a search](https://github.com/libgdx/libgdx/issues?q=ScrollPane+scrollTo) only turns up #5488, older too. So what is that changelog entry referring to?

**Comment by Frosty-J** [comment]
I don't know why it's not in blame, but I think it must be https://github.com/libgdx/libgdx/commit/a0544c9378706a42a6a64b1c22ca00d03f8c743a. There were also [a couple other commits](https://github.com/libgdx/libgdx/commits/e688cf718d56048bd9ab3e61180b93ee46f399d7/gdx/src/com/badlogic/gdx/scenes/scene2d/ui/ScrollPane.java) on the same day.
