### ISSUE TITLE
gdx-backend-lwjgl3 lost textures after window minimized

### ISSUE THREAD

**Issue by Peter-Warlock** [libgdx/libgdx#7279]
#### Issue details
Some textures (especial BitmapFonts) lost after minimize - restore application on Windows 10.

#### Reproduction steps/code
1. Using gdx-backend-lwjgl3 build desktop app rendering on screen some text by using BitmapFont and some SpriteBatch. 
2. Run it on Windows 10. 
![image](https://github.com/libgdx/libgdx/assets/11406464/f7f0bcc6-3f25-431d-9c12-051efee795ce)

3. Press a "minimize" button on the window of app.
4. Restore app. All text and some textures gone. 
![image](https://github.com/libgdx/libgdx/assets/11406464/4bfbf7e9-4521-43d1-b6b8-e8b3f9d82a47)

Rebuild project with old gdx-backend-lwjgl - all works fine. Nothing lost after minimize/restore sequence.

#### Version of libGDX and/or relevant dependencies
gdxVersion = '1.12.1'

#### Please select the affected platforms
- [X ] Windows

**Comment by Tom-Ski** [comment]
Can you post the minimal code sample to reproduce your issue?

**Comment by Frosty-J** [comment]
`resize()` returns a size of 0 when the window is minimised on LWJGL3. This can cause problems, especially if you're generating fonts based on this size (though my memory is it just crashes if you try to generate a 0-size font).

I agree we'd need to know more about your code, but my money's on you not handling window resizes of 0 dimensions. A quick hack you can try is enclosing your resize logic in `if (width > 0 && height > 0)`.
