### ISSUE TITLE
[BUG] cant attach junit 5 to libgdx project

### ISSUE THREAD

**Issue by paramidon** [libgdx/libgdx#7282]
cant attach junit 5 jupiter to lib gdx project.
steps to reproduce:
- jdk 17, windows 11. intellij idea 2023.1.2
- create fresh project. I used some tool to create fresh project, I am sure you know about this tool. from the official libgdx site.
- open ROOT build.gradle.
- find project(":core")  section
- insert next to dependencies block:
         testImplementation(platform("org.junit:junit-bom:5.10.1"))
         testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
- wait to allow gradle to import every shit it needs.
- open external libraries section in your inllij idea. I see that IDE imported EVRY shit it needs:
![image](https://github.com/libgdx/libgdx/assets/55555207/9c8ce8cd-9e52-4d6e-9d3e-d3338f9a418a)

**_### But I CANT import classes from these packages._**

**Comment by tommyettinger** [comment]
This isn't a bug with libGDX. Follow the instructions for JUnit 5: https://junit.org/junit5/docs/current/user-guide/#running-tests-build-gradle

I'm closing this because if it's a bug with anything, it's a Gradle bug or JUnit bug, and that's pretty unlikely compared to "docs currently unread."

**Comment by paramidon** [comment]
> This isn't a bug with libGDX. Follow the instructions for JUnit 5: https://junit.org/junit5/docs/current/user-guide/#running-tests-build-gradle
> 
> I'm closing this because if it's a bug with anything, it's a Gradle bug or JUnit bug, and that's pretty unlikely compared to "docs currently unread."

thank you very much for nothing

**Comment by paramidon** [comment]
> This isn't a bug with libGDX. Follow the instructions for JUnit 5: https://junit.org/junit5/docs/current/user-guide/#running-tests-build-gradle
> 
> I'm closing this because if it's a bug with anything, it's a Gradle bug or JUnit bug, and that's pretty unlikely compared to "docs currently unread."

Thanks for nothing bro. I didn’t even understand where the changes needed to be made.

**Comment by paramidon** [comment]
> You are most welcome; nothing is precisely what you get when you report a bug to the wrong place. This is not a help channel, this is a bug tracker. Keep up the bad attitude and I'll block you from further interaction with the repo.

It’s immediately obvious that you haven’t worked on serious projects

**Comment by paramidon** [comment]
> You are most welcome; nothing is precisely what you get when you report a bug to the wrong place. This is not a help channel, this is a bug tracker. Keep up the bad attitude and I'll block you from further interaction with the repo.

how scary
