### ISSUE TITLE
Full replacement for libGDX Particle Editor

### ISSUE THREAD

**Issue by raeleus** [libgdx/libgdx#7285]
It has come to my attention that the libGDX Particle Editor is not compatible with M1 Mac computers. This is due to it being a Swing app using an embedded libGDX overlay to preview the particle effect which is a known incompatibility on that platform. In testing the particle editor, I've noticed it is horribly broken and unmaintained. That has inspired me to make a replacement.

Particle Park Pro is a comprehensive replacement for the libGDX Particle Editor and is now feature complete. It has the following goals:
* Target all desktop platforms including M1 Macs.
* Disallow any use of Swing, AWT, or similar toolkits. Particle Park Pro is solely a Scene2D.UI project.
* Improve the workflow and interface for maximum efficiency and attractiveness.
* Export libGDX compatible particle effects. Extra features requiring a separate runtime library will not be supported.
* Include all features available in the current Particle Editor.

I have met and exceeded all of these goals. I spent many months working tirelessly creating custom widgets, bug fixing, and fine tuning to make what I consider the ideal revision of the particle editor. To be specific, I have solved these existing problems in the current particle editor:
* Not M1 compatible
* The editor properties don't work at all. PPM, Zoom, Grid, Background Image, etc. are completely broken currently.
* Scrolling with the mouse wheel is too sensitive to the point of being unusable
* Tint is hard to work with because it doesn't provide a full color dialog with options.
* Input with number spinners alone is not great when you're trying to modify an emitter dynamically.
* It's using the Metal look and feel. Icky yucky!
* There are outstanding issues that go back years.
* It's in the main libGDX repo, bounding its releases with the main library. An issue of growing concern across the board.

I propose that we discontinue the use of the old Particle Editor entirely. The source code can exist in the main libGDX repo where it currently resides for posterity. However, libgdx.com, wiki, and all documentation will now point to the new particle editor. The source for my app will be copied to a new repo under the libGDX organization. I will maintain the project and it will have its own release cycle separate from libGDX. "Particle Park Pro" is the working title and so it will be rebranded as the "libGDX Particle Editor".

Please take a look at the app here: https://github.com/raeleus/Particle-Park-Pro
I have a wiki that guides users on running the app on Mac: https://github.com/raeleus/Particle-Park-Pro/wiki
My in-depth guide reviews all functionality of my app in great detail: https://github.com/raeleus/Particle-Park-Pro/wiki/In%E2%80%90Depth-Guide

I would appreciate it if libGDX leadership can make a decision on this soon. If it's a "no", then that's fine. I just want it to be a comprehensive "no" so I can proceed accordingly. I plan on making very thorough videos on YouTube for my channel and the official libGDX channel regarding particle effect development. I will not be able to do this until I know the decision on rebranding it as the official app. Images for my in-depth guide and rewriting of the libgdx.com wiki will follow after that. Thank you for reading this.

**Comment by obigu** [comment]
This is awesome news, thanks a lot for your work! I think there will be consensus about Particle Park Pro replacing the current one in the libGDX organization.

I've tested Particle Park Pro 0.4 (looks like latest version) and it looks great. I've tried to open a random particle effects I use in one of my games and have found a bug which prevents from loading it (I will report in the issue tracker later) which is not a big deal as we'll have time to do proper testing once we move it to the libGDX umbrella but it shows it may still need some final polish before full replacement.

I'd do this migration step by step.

We can start by moving it to the libGDX organization for a testing period. Once we fix bugs and are confident it's stable enough then we can change all links/wiki, etc... Finally we can remove the old one from the libGDX project itself.

I'll happily help with testing and bug hunting :)

**Comment by Tom-Ski** [comment]
Really nice contribution! 
I think there is no need for this to be in the main repo, and gives us a nice opportunity to remove an extension that is best suited outside of the repo too. So it can have its own cycle of release and be managed a bit more dynamically than the core.  

Perhaps the runtime can also be moved in time (but for another discussion).

**Comment by tommyettinger** [comment]
I say "**yes**" to this. I've only worked with the old particle editor a little, but even cursory usage finds that every nook and cranny has another bug. Even if PPP only could export 50% of the possible features, that's substantially more than what an ARM64 Mac could export, which is 0% of the features. Just in terms of professionality, having the very-broken particle editor in the main repo and implicitly recommended looks bad.

*Disclaimer*

I don't currently use particle effects, probably because the old editor was so unwieldy. I am not sure I am the best judge of usability for the new editor, but it is pretty clear that Swing needs to go.

**Comment by raeleus** [comment]
Thank you all for the feedback and approving this development. I have moved everything to the new repo here: https://github.com/libgdx/gdx-particle-editor

My main focus now will be to resolve any bugs that you may find now. Thanks.

**Comment by NathanSweet** [comment]
This is really cool, kudos! I'm good with this replacing the spine-tools particle editor and the old code being removed.

I know this is not the ideal place, but some quick feedback since I'm here:
* I love that the little charts survived!
* If I click up on a spinner it goes up over time by 10 or so. If it's going to change over time, it should be quite fast. Actually something weird is happening: if I click and don't move the mouse, it keeps going up. If I double click, it goes up forever.
* Nice color chooser! I know that's a lot of effort. There's quite a long delay when it opens (clicked from `Tint`, no delay clicked from `Background color`). I usually prefer very little delay on opening, while closing can have a slower/fancier animation.
* Nice animation adding/removing properties.
* View options, even shaders, cool! Plus UI scale, hotkeys, templates, etc. It's great!

**Comment by raeleus** [comment]
Thanks @NathanSweet! I really value your feedback when it comes to anything Scene2D related. It means a heck of a lot to me.
* I increased the spinner increment when you hold the button. Good suggestion.
* I couldn't replicate the spinner double click issue, but I added a fix that would hopefully prevent that.
* The reason for the delay to show the color chooser was to allow for double click detection. Double click is an accessibility option for folks who won't right-click to delete nodes. I decreased the delay and it feels good now. People who can't double click fast enough will just have to right click.

This all can be seen in the 1.0.2 release.

**Comment by raeleus** [comment]
Hello. Here is an update on where we're at with this. GDX Particle Editor has survived two game jams so I'm pretty satisfied with where it's at right now. I created the in-depth tutorial video: https://youtu.be/8WlCWzoJEeY It's currently unlisted until I update the wiki articles. That shouldn't take too long. After that, we can start talking about removing the old editor. Thank you so much for this opportunity!

**Comment by raeleus** [comment]
Final version of video has been made public: https://youtu.be/OlPg6C6O-Cg
The wiki has also been updated. I guess the last thing is to create a PR to remove the old editor from the main project. I'll get to that when I have a chance to look things over.
