### ISSUE TITLE
TiledMap can be loaded only in xml format and not json.

### ISSUE THREAD

**Issue by patton73** [libgdx/libgdx#7291]
Basically this is a request for new features. 

I would like to have the chance to load a map in json (.tmj) format from TILED. Right now only .tmx formats are loaded. 
More i would like to have in the loader also a method to load a defined Tileset file (both formats as well) directly into a TiledMapTileSet. 

Thanks a lot for your efforts.
Keep up the incredible good work.

**Comment by Kevin-Garnier** [comment]
Hi, I'll try to add it.

**Comment by Kevin-Garnier** [comment]
Hi @patton73, I'm not sure to fully undestand what you mean by having in the loader a method to load a defined Tileset file directly into a TiledMapTileSet. Isn’t it already the case with the TmxMapLoader, which loads a map with the associated tilesets from the given file?

**Comment by patton73** [comment]
Hi @Kevin-Garnier thanks for the question.
Basically is not the same. Right now you can only load a predefined Map (made with Tiled). So you can load the entire map with tilesets included. But what if i would like to generate a random map using those tilesets?
Right now you cannot do it. You can only load a complete map but not a complete tileset.

According to me this is a cool upgrade to the library.
At least make those methods public, so you can use them to load a fully functional tileset to generate a random map.

Thanks anyway for your effort.
For any question please ask.

**Comment by mgsx-dev** [comment]
> But what if i would like to generate a random map using those tilesets? Right now you cannot do it.

@patton73 right now you can load an empty map references those tilesets and use them to generate your maps : `map.getTileSets().getTileSet("awesome-tileset");` which is an OK workaround IMHO.

About JSON format, i'm not sure what the benefits using this format but assuming you get a tilemap/tileset from someone else, you could re-export them as XML from Tiled.

I can understand that it could be nice to have full support at some point but those are easily workaround-able until then.

**Comment by mgsx-dev** [comment]
> Since in Tiled i can have tileset files outside the map.

@patton73 actually you can load TMX maps with libGDX which has separated TSX files, in this case tilesets are not embeded into the TMX map, it only references them. So your code doesn't need to know if tilesets are embeded or referenced by the tilemap, which could be a plus in term of assets organization for some people. That said, i can understand it could be more handy for some people to directly load TSX files, no doubt.

**Comment by Kevin-Garnier** [comment]
I've already done the json format on my fork, I can do that too

**Comment by Quillraven** [comment]
@Kevin-Garnier : I saw you opened a PR with some Tiled enhancements which is great.

Can you please also include a fix that the loader does not crash with properties of type file? It crashes in a castProperty method of the loader because it does not support that type.

Imo it should not crash and simply load it as a string (no cast necessary). 

Also, imo text objects are also not loaded correctly. They don't contain any of the text prooerties that Tiled stores.

If you have time and motivation it would be great if you can add the support for this as well ☺️

**Comment by Kevin-Garnier** [comment]
Sorry for the delayed response. Is the issue only with the JSON part, or does it also affect the XML part? If it's both, I think it would be best to create a new issue, as it may require more extensive modifications.

**Comment by Quillraven** [comment]
It is a general issue of the original loader. But seeing how slowly (never?) PR are merged I think we can simply ignore that. I have implemented a custom loader that overrides the problematic method and fixes it for my own needs.

Thanks anyway for your response 😊

**Comment by patton73** [comment]
> It is a general issue of the original loader. But seeing how slowly (never?) PR are merged I think we can simply ignore that. I have implemented a custom loader that overrides the problematic method and fixes it for my own needs.
> 
> Thanks anyway for your response 😊

Please can you share the code since it seems like having a PR that closes the bug? 
Thanks.
