### ISSUE TITLE
Class cannot be created (missing no-arg constructor) in gradle 8.1.4 and libgdx 1.12.1

### ISSUE THREAD

**Issue by newMemberHub** [libgdx/libgdx#7296]
#### Issue details
Class cannot be created due to missing no-arg constructor

#### Reproduction steps/code
- Build the application
- Run and the app is crashed due to the error "Class cannot be created (missing no-arg constructor)".
- The function made it crashed in file ReflectionPool.java of libgdx: 
	public ReflectionPool (Class<T> type, int initialCapacity, int max) {
		super(initialCapacity, max);
		constructor = findConstructor(type);
		if (constructor == null)
			throw new RuntimeException("Class cannot be created (missing no-arg constructor): " + type.getName());
	}
- I think the updated in gradle and  R8 from Google that make this libgdx's source code isn't valid. In the old gradle, I haven't yet seen this error. 

#### Version of libGDX and/or relevant dependencies
- I used the latest version 1.12.1

#### Please select the affected platforms
- [x] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by tommyettinger** [comment]
You can add `android.enableR8.fullMode=false` to your gradle.properties file (either one, I would suggest the root folder's gradle.properties) to stop R8 from erasing generated no-arg constructors. This is the default in new gdx-liftoff projects, and I think is also the default produced by gdx-setup (or will be soon). Unfortunately, there's no way to automatically update older projects to Gradle 8.5 and Android Gradle Plugin 8.1.4, so it has to be done piecemeal like this.

**Comment by obigu** [comment]
That's right, the change was made here `https://github.com/libgdx/libgdx/pull/7247` and is available on latest Gdx Setup but requires the manual change on existing projects.
