### ISSUE TITLE
Java 21 is not supported with the gradle version libgdx setup uses

### ISSUE THREAD

**Issue by lyze237** [libgdx/libgdx#7300]
I haven't found an issue in github about this so here's one:

#### Issue details
Setup app uses gradle 7.5.1 which is outdated and doesn't support java 21.

See here for gradles compatibility matrix: https://docs.gradle.org/current/userguide/compatibility.html

#### Reproduction steps/code
Install a java 21 JDK, try and generate a new project with the setup app, it'll fail with `Unsupported class file major version 63`

#### Version of libGDX and/or relevant dependencies
1.12.1

#### Stacktrace
```java
Generating app in C:\Users\xxx\Downloads\test
Executing 'C:\Users\xxx\Downloads\test/gradlew.bat clean --no-daemon'
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.5.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 

FAILURE: Build failed with an exception.

What went wrong:
Could not open settings generic class cache for settings file 'C:\Users\xxx\Downloads\test\settings.gradle' (C:\Users\xxx.gradle\caches\7.5.1\scripts\13dbo4zft16dyvv6xki9uzovd).
BUG! exception in phase 'semantic analysis' in source unit 'BuildScript' Unsupported class file major version 63

Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.

Get more help at https://help.gradle.org/

BUILD FAILED in 6s
Done!
To import in Eclipse: File -> Import -> Gradle -> Existing Gradle Project
To import to Intellij IDEA: File -> Open -> build.gradle
To import to NetBeans: File -> Open Project...
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by SimonIT** [comment]
Am I missing something, or didn't we just update the gradle version in #7247?

**Comment by lyze237** [comment]
Ah nice I only looked through the issues but not the PRs! Glad that's in!

**Comment by tommyettinger** [comment]
8.4 isn't fully compatible with Java 21. I didn't make the PR, I have no say in it, but I did push to update to 8.4 when it was most recent, and now 8.5 is most recent. You can read the history of that one for a rationale of why we're perpetually a version behind. Some Java 21 things may work with Gradle 8.4, but you can't run Gradle 8.4 with Java 21 and expect it to work. This should probably be reopened, I'm not sure why it was closed.

**Comment by pan3793** [comment]
I confirmed that the combination of Gradle 8.5, libgdx 1.12.1, and Java 21 works well on Windows 11 23H2.

**Comment by obigu** [comment]
Thanks! https://github.com/libgdx/libgdx/pull/7302 should fix it
