### ISSUE TITLE
SNAPSHOT build no longer works on Android 4.1

### ISSUE THREAD

**Issue by Frosty-J** [libgdx/libgdx#7307]
The next version of libGDX will be built with AGP 8 (#7246). A side effect of this is we will go from NDK 23 to 25, which drops support for Android Jelly Bean (API levels 16, 17, 18).

In my testing with the emulator, libGDX 1.12.2-SNAPSHOT crashes on API 16. Interestingly, it actually seems fine on API 18, but I haven't extensively tested (just because badlogic.jpg loads doesn't mean other code won't cause a crash).

As gdx-setup still supports API 14, we need to decide how to proceed. Possible options I see are:

1. Set `minSdkVersion` to 19 in gdx-setup. This is the easiest solution. Google pretty much killed Jelly Bean in 2021 and I'm not sure it can even access the Play Store anymore. It's certainly no longer listed in the version distribution. I don't think this is an unreasonable increase, though it does set a precedent for further increases in future (the latest NDK also drops support for KitKat, API 19 & 20...).
2. Specify `ndkVersion` so we can continue using an older NDK with newer AGP versions. 17.2.4988734 is the last version to support API 14, which would actually be a downgrade from what recent libGDX releases would've used. 23.2.8568313 would let us keep Jelly Bean support. I don't really see an immediate issue with this, but it's probably not a long-term solution.

References:

* https://developer.android.com/ndk/downloads/revision_history
* https://developer.android.com/studio/projects/install-ndk#default-ndk-per-agp

**Comment by obigu** [comment]
Option 1 seems the way to go, anybody that needs to support legacy devices can use 1.12.1.

I've set the milestone on the issue to make sure we have a PR ready by the time we release.

**Comment by 00-Evan** [comment]
It's worth mentioning that these really old devices can still connect to Google Play and there are still people who use them. My game is admittedly a pretty specific case, but I've still got active installs on about 50 Android 4.0 (API 15) devices and one and a half thousand Android 4.1-4.3 (API 16-18) devices,

I agree that bumping the minimum to API 19 is very reasonable though, and I can always stick around on 1.12.1 for a bit until those 4.1-4.3 numbers drop some more.

**Comment by Berstanio** [comment]
1.12.0 also doesn't work on 4.1 anymore because of https://github.com/libgdx/libgdx/pull/7005, [which upgraded the provided NDK to r25](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2004-Readme.md), and everything below [android 19 got killed in r24](https://github.com/android/ndk/wiki/Changelog-r24).

So I think we should downgrade to r23 again, or adjust the min required API level (also in gdx-setup I would assume)
