### ISSUE TITLE
"Extension string retrieval is broken" when trying to run generated project with JDK 21 on linux

### ISSUE THREAD

**Issue by krzyk** [libgdx/libgdx#7308]
Please ensure you have given all the following requested information in your report.

#### Issue details
I generated project from https://libgdx.com/wiki/start/project-generation, selected only desktop and no extensions.
After project was generated it didn't build at first (because core has source set to 1.7, which is not supported by JDK 21) - I set both core and desktop modules to 21 source level.

After that I did `./gradlew desktop:run` and got following errors:
```
[LWJGL] GLFW_PLATFORM_ERROR error
        Description : Extension string retrieval is broken
        Stacktrace  :
                org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2058)
                org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2229)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:527)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:463)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:449)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:163)
                com.mygdx.game.DesktopLauncher.main(DesktopLauncher.java:13)
[LWJGL] GLFW_PLATFORM_ERROR error
        Description : Extension string retrieval is broken
        Stacktrace  :
                org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2058)
                org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2229)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:527)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:463)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:449)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:163)
                com.mygdx.game.DesktopLauncher.main(DesktopLauncher.java:13)
[LWJGL] GLFW_PLATFORM_ERROR error
        Description : Extension string retrieval is broken
        Stacktrace  :
                org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2058)
                org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2229)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:527)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:463)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:449)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:163)
                com.mygdx.game.DesktopLauncher.main(DesktopLauncher.java:13)
Exception in thread "main" java.lang.NullPointerException
        at org.lwjgl.system.Checks.check(Checks.java:188)
        at org.lwjgl.system.MemoryUtil.memLengthNT1(MemoryUtil.java:2406)
        at org.lwjgl.system.MemoryUtil.memASCII(MemoryUtil.java:2673)
        at org.lwjgl.opengl.GL.createCapabilities(GL.java:442)
        at org.lwjgl.opengl.GL.createCapabilities(GL.java:311)
        at org.lwjgl.opengl.GL.createCapabilities(GL.java:295)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:572)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:463)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:449)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:449)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:163)
        at com.mygdx.game.DesktopLauncher.main(DesktopLauncher.java:13)
```

#### Reproduction steps/code
This is uploaded code (generated from the official web page with only desktop mode and changed build.gradle in core and desktop to have source code level set to 21) - https://github.com/krzyk/libgdx-test

Linux, with Xorg, iGPU with unused nvidia GPU (everything runs on intel one).
Maybe there is issue with selecting the correct GPU?
Other applications that use OpenGL/Vulcan are working fine (e.g steam games).

I also tried the maven setup, which after I migrated to lwjgl3 gave exactly the same error/stacktraces (with the default lwjgl2 it breaks in missing native link).

#### Version of libGDX and/or relevant dependencies
1.12.1

#### Stacktrace
```java
                org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2058)
                org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2229)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:527)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:463)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:449)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:163)
                com.mygdx.game.DesktopLauncher.main(DesktopLauncher.java:13)
Exception in thread "main" java.lang.NullPointerException
        at org.lwjgl.system.Checks.check(Checks.java:188)
        at org.lwjgl.system.MemoryUtil.memLengthNT1(MemoryUtil.java:2406)
        at org.lwjgl.system.MemoryUtil.memASCII(MemoryUtil.java:2673)
        at org.lwjgl.opengl.GL.createCapabilities(GL.java:442)
        at org.lwjgl.opengl.GL.createCapabilities(GL.java:311)
        at org.lwjgl.opengl.GL.createCapabilities(GL.java:295)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:572)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:463)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:449)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:449)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:163)
        at com.mygdx.game.DesktopLauncher.main(DesktopLauncher.java:13)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] macOS

**Comment by tommyettinger** [comment]
This looks to me like an Intel driver issue. This is more common on older Windows installations, but can happen on if your integrated graphics are either too old hardware-wise to support some common OpenGL feature, or they use newer hardware that hasn't had the drivers updated and so is using some barebones driver meant to work even on extremely old devices. I'm guessing other graphical applications are using the Nvidia GPU, and I'm not sure if Java has any way of suggesting to a Linux OS that it should run on the discrete GPU, if one is available. I don't know what distro/version you're using, nor your CPU/GPU versions. This is probably going to take some googling for your specific hardware situation -- but if you use Linux, you're probably used to that by now. My only Linux machine just had its battery nearly explode, so I can't do anything to reproduce right now.

**Comment by krzyk** [comment]
No, other apps don't use nvidia (I don't have drivers for it) - I'm using purely Intel.
Quite new kernel (6.6.8) and mesa+intel drivers compiled from sources a week or two ago.

Intel CPU is not that old (11th Gen Intel(R) Core(TM) i7-11850H).

As for distro: Ubuntu 20.04, but as I mentioned I keep kernel and graphics drivers up to date on my own.

I didn't notice such issues in any other apps, so I was quite surprised.

Googling unfortunately doesn't bring any useful data (almost nothing is there) :(

**Comment by krzyk** [comment]
I did some tests and the app works on libgdsx 1.11.0 and is broken on 1.12.x (with the error above).

**Comment by crykn** [comment]
IMO the most likely culprits are the LWJGL 3 updates in 1.12.0 and 1.12.1. Instructions for building libGDX locally can be found [here](https://libgdx.com/dev/from-source/).

**Comment by krzyk** [comment]
I'm curious, is there a way to build just the desktop part of libgdx?
Version 1.11.x allowed to build without the Android SDK, but in 1.12 it is required to provide the SDK location
It is a PITA to download that SDK (considering that now it is a bit hard to download just that, AFAIR one has to download Android Studio) if I do just the desktop part.

**Comment by krzyk** [comment]
Nevermind, went with Android Studio.

So the commit that broke the example app is b23419c535cd2b462087c1009c256ac279f66863

**Comment by crykn** [comment]
I guess we can close this on our end.
