### ISSUE TITLE
GWT requests unnecessary microphone permission

### ISSUE THREAD

**Issue by Frosty-J** [libgdx/libgdx#7348]
#### Issue details
The SNAPSHOT build of libGDX appears to try to access the microphone for GWT. I am uncomfortable with releasing anything that requests microphone access unnecessarily.

1.12.1 on left; 1.12.2-SNAPSHOT on right. All that is different is `gdxVersion`:

![Comparison screenshot](https://github.com/libgdx/libgdx/assets/60154347/08531c3d-c88e-4f91-923d-10d0c49f9aad)

#### Reproduction steps/code
`html:superDev`

#### Version of libGDX and/or relevant dependencies
1.12.2-SNAPSHOT

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [X] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by SimonIT** [comment]
That's because of my PR #7243. The permission is needed to fetch the available output devices.

**Comment by Frosty-J** [comment]
Could this behaviour be made optional? Such as by only performing the query when doing `Gdx.audio.getAvailableOutputDevices()` rather than each second.

**Comment by SimonIT** [comment]
It can be optional with a flag, but we can't do it in the method itself, because the JS API is async (at least I don't know how) and the method is sync

**Comment by Hyperion2400** [comment]
> That's because of my PR #7243. The permission is needed to fetch the available output devices.

This should definitely not be made the default behaviour. Please consider a different solution.
