### ISSUE TITLE
performance: unnecessary window.makeCurrent() in LWJGL3 backend

### ISSUE THREAD

**Issue by McMurat** [libgdx/libgdx#7360]
Please ensure you have given all the following requested information in your report.

#### Issue details
In the main loop of a Lwjgl3Application there is a loop which iterates over all Lwjgl3Windows and calls window.makeCurrent() which triggers an OpenGL context switch using glfwMakeContextCurrent(). This is unnecessary to call repeatedly when there is only one single window. Optimizing this will cause my application to run around 10% faster.

I suggest a simple change:

```java
                if (currentWindow != window) {
                    window.makeCurrent();
                    currentWindow = window;
                }
```

This is sufficient because currentWindow is null initially. So glfwMakeContextCurrent() will be called at least once.

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [x] macOS

**Comment by crykn** [comment]
Good catch! I think `currentWindow` would need to be set [here](https://github.com/libgdx/libgdx/blob/3d8cfb8ce3d86cdf0909ce298c38ecca53d50ea0/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java#L560) as well, so that the right context is active in the first render pass after a second window is created. Do you want to submit a PR for this?

**Comment by McMurat** [comment]
> Good catch! I think `currentWindow` would need to be set [here](https://github.com/libgdx/libgdx/blob/3d8cfb8ce3d86cdf0909ce298c38ecca53d50ea0/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java#L560) as well, so that the right context is active in the first render pass after a second window is created. Do you want to submit a PR for this?

Yes, setting `currentWindow` to the created window and also calling `makeCurrent()` on the it [here](https://github.com/libgdx/libgdx/blob/3d8cfb8ce3d86cdf0909ce298c38ecca53d50ea0/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java#L464) is also necessary for multi-window support. The additional call to `makeCurrent()` is only needed to update Gdx.graphics, Gdx.input, Gdx.gl, ... for the new active window (currently this is not happening ant therefore a bug in the current implementation).

I don't have a fork. As these are just a few lines it would probably be easier if someone else pushes/PRs this.

**Comment by McMurat** [comment]
> you can edit file and submit a PR automatically using the github interface, go on the file, then click **edit**, it'll do the work for you

I opened a PR: https://github.com/libgdx/libgdx/pull/7362

**Comment by crykn** [comment]
Taken care of by #7362.
