### ISSUE TITLE
Add arm64 capabilities to Info.plist.xml

### ISSUE THREAD

**Issue by psj505** [libgdx/libgdx#7363]
#### Issue details
As 32 bit (armv7) builds are no longer supported, arm64 capabilities need adding to Info.plist.xml for successful delivery to the App Store / Test Flight.

#### Code

```
<key>UIRequiredDeviceCapabilities</key>
    <array>
        <string>opengles-2</string>
	<string>arm64</string>
    </array>
```

#### Version of libGDX and/or relevant dependencies
1.12.0 >

#### Please select the affected platforms
- [ ] Android
- [X] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by obigu** [comment]
Good catch, thanks, I've created a PR
