### ISSUE TITLE
Using multiple textures in a single shader

### ISSUE THREAD

**Issue by wangchen11** [libgdx/libgdx#7396]
#### Issue details
我想要实现水下画面折射效果，尝试在单个着色器中使用多个纹理，这似乎无法正常工作。水下的纹理无法渲染出来。
I want to achieve underwater scene refraction effect, trying to use multiple textures in a single shader, but it doesn't seem to work properly. The underwater textures cannot be rendered.

#### Reproduction steps/code
``` kotlin
package com.mygdx.game

import com.badlogic.gdx.ApplicationAdapter
import com.badlogic.gdx.Gdx
import com.badlogic.gdx.graphics.GL20
import com.badlogic.gdx.graphics.Texture
import com.badlogic.gdx.graphics.g2d.SpriteBatch
import com.badlogic.gdx.graphics.glutils.ShaderProgram
import java.lang.IllegalStateException

class UnderWaterEffectTest: ApplicationAdapter() {
    private lateinit var batch: SpriteBatch
    private lateinit var underWater: Texture
    private lateinit var waterSurface: Texture
    private lateinit var underWaterEffectShaderProgram: ShaderProgram
    private var deltaTime = 0f

    override fun create() {
        super.create()
        batch = SpriteBatch()
        underWater = Texture("test/under_water.png")
        waterSurface = Texture("test/water_surface.png")
        underWaterEffectShaderProgram  = ShaderProgram(
            """
        #version 100

        attribute vec4 a_position;
        attribute vec2 a_texCoord0;
        
        varying vec2 v_texCoords;
        
        uniform mat4 u_projTrans;

        void main() {
            gl_Position = u_projTrans * a_position;
            v_texCoords = a_texCoord0;
        }
            """.trimIndent(),
            """
        #version 100
        
        #ifdef GL_ES
        precision mediump float;
        #endif

        uniform sampler2D u_texture;
        uniform sampler2D u_texture_under_water;
        uniform vec2 u_resolution;
        uniform float u_time;

        varying vec2 v_texCoords;

        void main() {
            // 定义波动频率和振幅
            float frequency = 2.0;
            float amplitude = 0.02;
            float tansX = -mod(u_time / 30.0, 1.0);
            float tansY = mod(u_time / 30.0, 1.0);
            
            // 根据纹理坐标计算波动效果
            vec2 uv = v_texCoords;
            uv.y += sin(uv.x * 3.1415 * 2.0 * frequency + u_time) * amplitude;// + tansY;
            uv.x += sin(uv.y * 3.1415 * 2.0 * frequency + u_time) * amplitude;// + tansX;
            
            vec4 color = texture2D(u_texture, uv);
            vec4 colorUnderWater = texture2D(u_texture_under_water, vec2(uv.y, uv.x));
            // 获取纹理颜色并输出
            vec4 texColor = color * 0.5 + colorUnderWater * 0.5;
            gl_FragColor = texColor;
        }
            """.trimIndent()).assertCompiled()
    }

    override fun render() {
        super.render()
        deltaTime += Gdx.graphics.deltaTime
        if (deltaTime > 50f) {
            deltaTime = 0f
        }
        batch.begin()
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT)
        Gdx.gl.glClearColor(1f,1f,1f,1f)
        batch.shader = underWaterEffectShaderProgram
        underWaterEffectShaderProgram.setUniformf("u_time", deltaTime)
        underWaterEffectShaderProgram.setUniformi("u_texture_under_water", 2)
        underWater.bind(2)
        batch.draw(waterSurface, 0f, 0f, Gdx.graphics.width.toFloat(), Gdx.graphics.height.toFloat())
        batch.end()
    }
}

fun <T: ShaderProgram> T.assertCompiled(): T {
    val log = this.log
    if (!isCompiled) {
        throw IllegalStateException("Shader compilation failed \n:$log")
    }
    if (this.log.isNotBlank()) {
        Gdx.app.applicationLogger.error("ShaderHelper", "shader log:$log")
    }
    return this
}
```
![under_water](https://github.com/libgdx/libgdx/assets/19342774/6e7b9b62-67e1-4144-940e-571382fd91d7)

![water_surface](https://github.com/libgdx/libgdx/assets/19342774/1829b268-7f10-4d02-b2e8-4b078f955cbd)

#### Version of libGDX and/or relevant dependencies
1.12.1

#### Screencap
![image](https://github.com/libgdx/libgdx/assets/19342774/3d239caa-eecd-45ce-afc8-94aae27106da)

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] macOS

**Comment by CodeSimcoe** [comment]
This is what I did to use multiple textures :
my main texture + a dissolve texture

```java
shader.bind();

batch.setShader(shader);
    
dissolveTexture.bind(1);
shader.setUniformi("u_dissolveTexture", 1);

texture.bind(0);
shader.setUniformi(Uniforms.TEXTURE, 0);

shader.setUniformf("u_dissolveValue", this.dissolve);

batch.setShader(null);
```

**Comment by tommyettinger** [comment]
My code that uses multiple textures in a shader is similar to CodeSimcoe's version; I also had to bind in the order from highest to lowest, ending with `bind(0)`, and use the same number in the uniform. `SpriteBatch` automatically takes the current `Texture` and binds it to 0, which can be unexpected if you have multiple `Texture`s in use. [My relevant code is here, with a link to the highlighted lines](https://github.com/tommyettinger/previews/blob/main/cg/core/src/main/java/com/github/tommyettinger/cg/MainOld.java#L144-L148).

I haven't seen any official docs on why this is how it is, so I'm leaving this open for now. I don't know why it needs the bind order high-to-low, or exactly when it is best to set the uniforms.

**Comment by wangchen11** [comment]
重新绑定waterSurface可以正常工作了。
It works fine after rebinding the waterSurface。
before：
```
        underWaterEffectShaderProgram.setUniformi("u_texture_under_water", 2)
        underWater.bind(2)
```
after:
```
        underWaterEffectShaderProgram.setUniformi("u_texture_under_water", 1)
        underWater.bind(1)
        waterSurface.bind(0)
```

**Comment by mgsx-dev** [comment]
@tommyettinger 

> I haven't seen any official docs on why this is how it is, so I'm leaving this open for now. I don't know why it needs the bind order high-to-low.

This is because OpenGL is a state machine and we don't restore active texture unit to zero (for performance reasons i guess).
Alternatively, you could bind texture in any order and finally restore active texture manually with this code `Gdx.gl.glActiveTexture(GL20.GL_TEXTURE0)` (libgdx assumes unit zero to always be the active one)

> or exactly when it is best to set the uniforms.

You can set uniforms at any time after binding the shader and before drawing with it.

So the right code is : 

```java
// bind all your textures
Gdx.gl.glActiveTexture(GL20.GL_TEXTURE0);

shader.bind();
// set uniforms

// draw
```

Note that you can bind textures after or before shader binding as long as you do both before using them for drawing.
