### ISSUE TITLE
Duplicate points returned in polygon intersection

### ISSUE THREAD

**Issue by streamsoftdev** [libgdx/libgdx#7408]
The following code intersects a square with a triangle, where one of the triangle edges passes directly over a corner of the square. The overlap polygon is returned with 5 vertices, one of them duplicated, whereas the expected overlap is a square with 4 vertices (the lower left sub-square of the original square). The code then continues to intersect the overlap with two triangles. Neither of these intersections return any overlap, though they clearly do overlap and the expected overlaps are two triangles. The erroneous overlap with the duplicate vertex causes further intersection issues.

```
Polygon p1 = new Polygon(new float[]{1,-1,2,-1,2,-2,1,-2});
Polygon p2 = new Polygon(new float[]{0.5f,-1.5f,1.5f,-1.5f,1.5f,-2.5f});
Polygon overlap = new Polygon();
Intersector.intersectPolygons(p1,p2,overlap);
System.out.println("Number of overlap vertices: "+overlap.getVertexCount());
tmpSB.setLength(0);
VectorMath.poly2String(overlap,tmpSB);
System.out.println(tmpSB.toString());
Polygon p3 = new Polygon(new float[]{1,-1,2,-1,1,-2});
Polygon p4 = new Polygon(new float[]{2,-1,2,-2,1,-2});
Polygon overlap2 = new Polygon();
Polygon overlap3 = new Polygon();
Intersector.intersectPolygons(p3,overlap,overlap2);
Intersector.intersectPolygons(p4,overlap,overlap3);
System.out.println("Number of overlap2 vertices: "+overlap2.getVertexCount());
System.out.println("Number of overlap3 vertices: "+overlap3.getVertexCount());
```

The output of the code fragment is shown below:

```
Number of overlap vertices: 5
 1.0,-2.0 1.0,-1.5 1.5,-1.5 1.5,-2.0 1.0,-2.0
Number of overlap2 vertices: 0
Number of overlap3 vertices: 0
```

**Comment by streamsoftdev** [comment]
Here is a drop in replacement for the `intersectPolygons` method, that adds extra tests to ensure that points added to the result are never equal to the first point added. The existing test to omit duplicates did not work when the duplicate points were the first and last points. Another way is to inspect the final overlap region and eliminate the last vertex if it is a duplicate of the first one.

```
public static boolean intersectPolygons (Polygon p1, Polygon p2, Polygon overlap) {
    if (p1.getVertices().length == 0 || p2.getVertices().length == 0) {
        return false;
    }
    Vector2 ip = Intersector.ip, ep1 = Intersector.ep1, ep2 = Intersector.ep2, s = Intersector.s, e = Intersector.e;
    FloatArray floatArray = Intersector.floatArray, floatArray2 = Intersector.floatArray2;
    floatArray.clear();
    floatArray2.clear();
    floatArray2.addAll(p1.getTransformedVertices());
    float[] vertices2 = p2.getTransformedVertices();
    for (int i = 0, last = vertices2.length - 2; i <= last; i += 2) {
        ep1.set(vertices2[i], vertices2[i + 1]);
        // wrap around to beginning of array if index points to end;
        if (i < last)
            ep2.set(vertices2[i + 2], vertices2[i + 3]);
        else
            ep2.set(vertices2[0], vertices2[1]);
        if (floatArray2.size == 0) return false;
        s.set(floatArray2.get(floatArray2.size - 2), floatArray2.get(floatArray2.size - 1));
        for (int j = 0; j < floatArray2.size; j += 2) {
            e.set(floatArray2.get(j), floatArray2.get(j + 1));
            // determine if point is inside clip edge
            boolean side = Intersector.pointLineSide(ep2, ep1, s) > 0;
            if (Intersector.pointLineSide(ep2, ep1, e) > 0) {
                if (!side) {
                    Intersector.intersectLines(s, e, ep1, ep2, ip);
                    if (floatArray.size < 2 || !(floatArray.get(floatArray.size - 2) == ip.x
                        && floatArray.get(floatArray.size - 1) == ip.y) && !(floatArray.get(0)==ip.x
                        && floatArray.get(1)==ip.y)) {
                        floatArray.add(ip.x);
                        floatArray.add(ip.y);
                    }
                }
                if(floatArray.size<2 || !(floatArray.get(0)==e.x && floatArray.get(1)==e.y)){
                    floatArray.add(e.x);
                    floatArray.add(e.y);
                }
            } else if (side) {
                Intersector.intersectLines(s, e, ep1, ep2, ip);
                if(floatArray.size<2 || !(floatArray.get(0)==ip.x && floatArray.get(1)==ip.y)){
                    floatArray.add(ip.x);
                    floatArray.add(ip.y);
                }
            }
            s.set(e.x, e.y);
        }
        floatArray2.clear();
        floatArray2.addAll(floatArray);
        floatArray.clear();
    }
    if (floatArray2.size != 0) {
        if (overlap != null) {
            if (overlap.getVertices().length == floatArray2.size)
                System.arraycopy(floatArray2.items, 0, overlap.getVertices(), 0, floatArray2.size);
            else
                overlap.setVertices(floatArray2.toArray());
        }
        return true;
    }
    return false;
}
```

**Comment by tommyettinger** [comment]
I was having a hard time visualizing the example code, so I made this on Desmos in case anyone else wants to see why a pentagon could happen if there was some small error: https://www.desmos.com/geometry/czyu2wi5s0

As for the fix code, I worry about using `==` on float values, but I don't know if the problem vertex would be created via some calculation (in which case, `==` might be a problem) or by an exact copy (in which case it isn't a problem at all). MathUtils has ways to see if floats are equal within some tolerance for error, and I think `MathUtils.isEqual()` might be good to consider.

**Comment by obigu** [comment]
I think the suggested alternative of validating and, if necessary, modifying the final overlapping polygon is preferrable. We are already doing this in master branch (your code doesn't include a required fix for another float precision issue) so adding the extra check of `first point not equal to last point` there makes sense imo. We will also need to add a test in `IntersectorTest`.

**Comment by streamsoftdev** [comment]
The problem vertex exists in cases when the polygon to be clipped has its final vertex that sits on an edge of the clipping polygon. The existing code removes duplicates in all other cases since it was checking if a vertex to add was equal to the last vertex added, which happens if you have corners on the polygon to be clipped that sit on a clip edge; but in the problem case the final vertex of the polygon to be clipped will be added at the start (because it forms the "previous" point on the first edge) and at the end (it forms the last point of the last edge), and the existing check therefore fails to catch it.
