### ISSUE TITLE
Petition for new API: Color.set(Color rgb, float a)

### ISSUE THREAD

**Issue by angelickite** [libgdx/libgdx#7411]
Hello.

I constantly find myself writing code like this:
```Java
color.set(DB32.black);
color.a = <desired alpha>;
```

Ideally libgdx would offer `Color.set(Color rgb, float a)`. Setting a color is generally a unit operation. In this case the unit operation needs to be split into two distinct lines like above. Doing it here and there is no biggy, but I encounter this operation constantly.

> You can use a constant

Constants like `Color myBlack = new Color(DB32.black.r, DB32.black.g, DB32.black.b, <desired alpha>);` do not help the issue. The alpha value often is dynamic in nature, e.g. an interpolated value.

> You can create your own subclass of Color

No! We know the mess that leads to. Also it doesn't solve the problem neatly as the libgdx API delivers `Color` not `T extends Color`.

> You can use your own Utility

Thats what I do. It does its job but a method calls turns into a function call. Nothing beats native support.

Wonder how everyone feels about this.

Thank you!

**Comment by tommyettinger** [comment]
It's been merged! We can close now.
