### ISSUE TITLE
No suitable manifest in .jar package 2 (Eclipse)

### ISSUE THREAD

**Issue by Ir3nicuz** [libgdx/libgdx#7418]
After fiddeling around with Eclipse to get Eclipse working for a whole day the issue stays the same.

#### Issue details
For a first build and deploy test I started gdx-setup.jar on windows. I didn't change the name and class settings from default. I selected the desktop platform only. I selected all official extensions and clicked "generate". After generating I opened the project with Eclipse like mentioned in the tutorial and build the desktop project.

Within the IDE the project launches and runs fine.
But without the IDE the project .jar does not run. Not on Windows and not on Linux.

I double clicking "...\desktop\build\libs\desktop-1.0.jar" to launch on windows and nothing happend. Running this package on linux with "sudo java -jar desktop-1.0.jar" gives the error "no main manifest attribute".

In the attached .zip package is the generated project. In the "desktop/build.gradle" file is the "dist" task present but the manifest file in the "...\desktop\build\libs\desktop-1.0.jar" package seems to have no content.

Gradle says: To build a project with Eclipse click "Gradle Tasks - build". As I do so the .jar packe still stays empty.
Eclipse does the exact same as Netbeans. There is something odd with the Gradle configuration or the discribed setup steps in the libgdx tutorial. 

#### Reproduction steps/code
[testEclipse.zip](https://github.com/user-attachments/files/16215897/testEclipse.zip)

#### Version of libGDX and/or relevant dependencies
libGDX Project Generator 1.12.1
Eclipse Version: 2024-06 (4.32.0)

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [ ] macOS

**Comment by lyze237** [comment]
Hey there! To build a running jar, please run gradle task "dist" instead of "build": https://libgdx.com/wiki/deployment/deploying-your-application#deploy-to-windowslinuxmac-os-x

And then report back please.

**Comment by Ir3nicuz** [comment]
Hi lyze,

I saw this wiki and searched for "dist", too. But there is no "dist" task in the configured task list,
where the Eclipse-Gradle tutorial mentioned to call the tasks:
![tasks](https://github.com/user-attachments/assets/b907da78-e3d3-4b17-bb5f-4646b974381c)

But after with your hint I tried to call the "dist" task manually in a Gradle Run as configuration and it worked! Thanks!

**Comment by lyze237** [comment]
For whatever reason Eclipse hides most tasks by default, you need to click on the 3 dots in the tab, then enable "Show all tasks". After that you should be able to see the "dist" task in the "other" folder.

**Comment by Ir3nicuz** [comment]
After ticking "show all Tasks" I had to look twice again.
The "most essentiell" dist task is buried in a bunch of task in the subfolder other:
![tasks](https://github.com/user-attachments/assets/e22eefbf-2d0d-41a6-8b4b-8c45fec84558)

I don't get the reason this "modern" Eclipse IDE has such a over complicated, overloaded and unintuitive running and building concept.... I want to write code and not build script configurations shortcuts.....

**Comment by lyze237** [comment]
libGDX is currently in the progress of switching to [gdx-liftoff](https://github.com/libgdx/gdx-liftoff) as setup tool and that also allows either the "jar" or "dist" task for creating a runnable jar, so that should hopefully improve the eclipse workflow a bit.

**Comment by angelickite** [comment]
I have created https://github.com/libgdx/gdx-liftoff/issues/187 in an attempt to make a positive dent.

**Comment by angelickite** [comment]
> libGDX is currently in the progress of switching to [gdx-liftoff](https://github.com/libgdx/gdx-liftoff) as setup tool [...]

Could you link me to the related issue of the switch? Some time ago I read https://github.com/libgdx/libgdx/issues/7283#issuecomment-1820132961 and got the impression that gdx-setup is here to stay.

If there is currently an ongoing process for replacing gdx-setup, I can see how it would go, but would love to read about it more.

**Comment by Ir3nicuz** [comment]
@angelickite 
After digging deeper and deeper into Gradle, Gradle-Tasks, Build-Scripts, Eclipse Tabs, Eclipse Plugins, Eclipse Marketplace, Eclipse external Software ..... I slowly get the idea....but what for? I just want to run my code in the IDE to debug and I want to build a .jar package to deploy....not more and not by drilling through tons of windows and menus... 

Thats the reason I avoided Eclipse and use Netbeans. Though, Netbeans has its problems, too. But the liftoff for a new project is really straight forwarded. In eclipse i have to write half of a book to even create a launchable project.

Thanks for opening the issue to improve the libGDX bundle for Eclipse!

**Comment by tommyettinger** [comment]
> @lyze237
> 
> > libGDX is currently in the progress of switching to [gdx-liftoff](https://github.com/libgdx/gdx-liftoff) as setup tool [...]
> 
> Could you link me to the related issue of the switch? Some time ago I read [#7283 (comment)](https://github.com/libgdx/libgdx/issues/7283#issuecomment-1820132961) and got the impression that gdx-setup is here to stay.
> 
> If there is currently an ongoing process for ~replacing~ removing gdx-setup, I can see how it would go, but would love to read about it more.

https://github.com/libgdx/libgdx.github.io/pull/198 the only things that are left to change are docs, so the changes are in the website's repo. gdx-liftoff is part of the libgdx org now, and has been for several months.
