### ISSUE TITLE
Support 'class' Tiled/Tmx MapProperty

### ISSUE THREAD

**Issue by silas-hw** [libgdx/libgdx#7432]
#### Issue details
LibGDX currently does not support the 'class' type for custom properties in Tiled maps (see [here](https://doc.mapeditor.org/en/stable/manual/custom-properties/#custom-types)). These are useful for having reusable sets of properties within Tiled. However, when trying to load a map with a class type property with `TmxMapLoader` the following error is produced:

```
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Wrong type given for property customProperty, given : class, supported : string, bool, int, float, color
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.castProperty(BaseTmxMapLoader.java:509)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadProperties(BaseTmxMapLoader.java:487)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadObject(BaseTmxMapLoader.java:450)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadObject(BaseTmxMapLoader.java:354)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadObjectGroup(BaseTmxMapLoader.java:287)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadLayer(BaseTmxMapLoader.java:211)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadTiledMap(BaseTmxMapLoader.java:174)
	at com.badlogic.gdx.maps.tiled.TmxMapLoader.load(TmxMapLoader.java:81)
	at com.badlogic.gdx.maps.tiled.TmxMapLoader.load(TmxMapLoader.java:59)
	at com.mygdx.game.GameTest.create(GameTest.java:15)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:416)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:366)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
	at com.mygdx.game.DesktopLauncher.main(DesktopLauncher.java:13)
```

#### Reproduction steps/code
map.tmx:

```XML
<?xml version="1.0" encoding="UTF-8"?>
<map version="1.10" tiledversion="1.10.2" orientation="orthogonal" renderorder="right-down" width="30" height="20" tilewidth="32" tileheight="32" infinite="0" nextlayerid="3" nextobjectid="2">
 <objectgroup id="2" name="Object Layer 1">
  <object id="1" type="MyCustomType" x="256" y="160" width="96" height="96">
   <properties>
    <property name="customProperty" type="class" propertytype="MyCustomProperty">
     <properties>
      <property name="value1" type="int" value="1"/>
      <property name="value2" type="int" value="2"/>
     </properties>
    </property>
   </properties>
  </object>
 </objectgroup>
</map>
```
core game class:

```java
package com.mygdx.game;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.maps.tiled.TiledMap;
import com.badlogic.gdx.maps.tiled.TmxMapLoader;

public class GameTest extends ApplicationAdapter {
	TiledMap map;
	
	@Override
	public void create () {
		map = new TmxMapLoader().load("map.tmx");
	}

	@Override
	public void render () {
	}
	
	@Override
	public void dispose () {
		map.dispose();
	}
}
```

#### Version of libGDX and/or relevant dependencies
LibGDX version `1.12.1`

#### Please select the affected platforms
- [x] Android
- [x] iOS
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] macOS

**Comment by Quillraven** [comment]
Loading a class is not trivial imo because it can have multiple properties and I think it can even have nested classes?

Easiest way would be to load them as a Map<String,Object> where the key is the name of the class property.

That way we can also support nested classes because the key would the simply map to another map.


However, imo it would also be great if the loader can directly create correct class instances of you have a class implementation for a Tiled class.
I am thinking towards the Maploader properties where you can pass class factories.

Most likely a Map<String, Function<Map<String, Object>, Object>. The key is the name of the Tiled class. If the MapLoader finds a class property and the class name is part of the factory map then the loader calls the function by passing the property map explained at the beginning and returning the class instance created inside the factory method.

An alternative would be to work with reflection but I am not a big fan of reflection.

The only problem that I'd see is LibGDX's compatibility. I am not sure if the like 10 years old Java.util.function is supported on all possible backends 😅 I think LibGDX uses Java 7 still? java.util.function would be Java 8.

**Comment by silas-hw** [comment]
> Loading a class is not trivial imo because it can have multiple properties and I think it can even have nested classes (property of Type class)?
> 
> Easiest way would be to load them as a Map<String,Object> where the key is the name of the class property.
> 
> That way we can also support nested classes because the key would then simply map to another map.
> 
> 
> However, imo it would also be great if the loader can directly create correct class instances if you have a class implementation for a Tiled class.
> I am thinking towards the Maploader properties where you can pass class factories.
> 
> Most likely a Map<String, Function<Map<String, Object>, Object>. The key is the name of the Tiled class. If the MapLoader finds a class property and the class name is part of the factory map then the loader calls the function by passing the property map explained at the beginning and returning the class instance created inside the factory method.
> 
> An alternative would be to work with reflection but I am not a big fan of reflection.
> 
> The only problem that I'd see is LibGDX's compatibility. I am not sure if the like 10 years old Java.util.function is supported on all possible backends 😅 I think LibGDX uses Java 7 still? java.util.function would be Java 8.

To me a class property would make most sense itself to be a `MapProperties` object, since it holds a set of properties. This should also account for nested classes, since you just hold another MapProperties object.

You could something like

```java
MapProperties classProperty = mapObject.getProperties().get("myClassBasedProperty", MapProperties.class)
```

**Comment by silas-hw** [comment]
Of course, this loses the class name of the property, but this could be included in the MapProperties object similarly to how its included as a property of a MapObject itself.

**Comment by Quillraven** [comment]
I did a quick&dirt implementation which works fine for a simple test scenario. It might be useful to the guy making the real PR. I used a `Map` for the class properties but as @silas-hw mentions, it can also be a `MapProperties` instance. Note, I am not supporting nested classes here:

```kotlin
package io.github.masamune.tiledmap

import com.badlogic.gdx.assets.loaders.FileHandleResolver
import com.badlogic.gdx.graphics.Color
import com.badlogic.gdx.maps.MapProperties
import com.badlogic.gdx.maps.tiled.TmxMapLoader
import com.badlogic.gdx.utils.XmlReader.Element
import ktx.app.gdxError
import ktx.log.logger

class TiledMapLoader(fileHandleResolver: FileHandleResolver) : TmxMapLoader(fileHandleResolver) {

    // this should be part of the map loader properties to optionally register class factories
    private val classFactories = mapOf(
        "Stats" to { classProps: Map<String, Any?> ->
            Stats(
                agility = classProps.getOrDefault("agility", 0f) as Float,
                armor = classProps.getOrDefault("armor", 0f) as Float,
                intelligence = classProps.getOrDefault("intelligence", 0f) as Float,
                magicalDamage = classProps.getOrDefault("magicalDamage", 0f) as Float,
                physicalDamage = classProps.getOrDefault("physicalDamage", 0f) as Float,
                resistance = classProps.getOrDefault("resistance", 0f) as Float,
                strength = classProps.getOrDefault("strength", 0f) as Float,
            )
        }
    )

    override fun loadProperties(mapProperties: MapProperties, xmlElement: Element?) {
        super.loadProperties(mapProperties, xmlElement)

        // this should be done directly in TmxMapLoader's loadProperties method. It is
        // the special handling for class properties
        if (xmlElement?.name == "properties") {
            xmlElement.getChildrenByName("property")
                .filter { it.getAttribute("type", null) == "class" }
                .forEach { loadClassProperty(mapProperties, it) }
        }
    }

    // this method should be directly called by "castProperty" of TmxMapLoader to return
    // the result object for the mapProperties instance.
    private fun loadClassProperty(mapProperties: MapProperties, xmlElement: Element) {
        val name = xmlElement.getAttribute("name") // class property name in Tiled
        val className = xmlElement.getAttribute("propertytype")
        log.debug { "Loading class property $name with class $className" }

        val classResult = mutableMapOf<String, Any?>()
        xmlElement.getChildrenByName("properties")
            .flatMap { it.getChildrenByName("property") }
            .forEach { classPropXmlElement ->
                val classPropName = classPropXmlElement.getAttribute("name")
                val classPropValue = classPropXmlElement.getAttribute("value")
                val classPropType = classPropXmlElement.getAttribute("type")
                classResult[classPropName] = castProperty(classPropName, classPropValue, classPropType)
            }

        val factory = classFactories[className]
        if (factory != null) {
            // create correct class instance directly
            mapProperties.put(name, factory(classResult))
        } else {
            // just store a generic map
            mapProperties.put(name, classResult)
        }
    }

    override fun castProperty(name: String?, value: String?, type: String?): Any? {
        when (type) {
            null -> return value
            "int" -> return value?.toInt()
            "float" -> return value?.toFloat()
            "bool" -> return value?.toBoolean()
            "color" -> {
                // Tiled uses the format #AARRGGBB
                val opaqueColor = value?.substring(3)
                val alpha = value?.substring(1, 3)
                return Color.valueOf(opaqueColor + alpha)
            }

            // don't crash for class property types. This should return the result of the loadClassProperty method from above
            "class" -> return ""

            else -> throw gdxError("Unsupported type for property $name: $type")
        }
    }

    companion object {
        private val log = logger<TiledMapLoader>()
    }
}

```

**Comment by BoBIsHere86** [comment]
This Issue can now be closed as completed. PR #7534 was merged 2 weeks ago.
