### ISSUE TITLE
Need .jar and/or .dll

### ISSUE THREAD

**Issue by anonimo82** [libgdx/libgdx#7460]
#### Issue details
I'd like to use LibGDX with something different, and I need either .jar or .dll to do so
I tried various ways with LiftOff, but no luck. I'm trying with Windows 11.
I also downloaded Android Studio, Gradle and JDK.
Nothing, I can't find neither .JARs nor .DLLs in the project tree (which I browsed thoroughly) 

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] macOS

**Comment by angelickite** [comment]
LibGDX uses Gradle for dependency management. Most Gradle setups do not deal with jars directly, declarative depedency management and all that jazz, so by default there is no built-in solution to your problem (that I am aware of at least).

Your use case is not uncommon though, even my most current project has specific accomodations to gather all dependet-on Jars into a directory.

Without knowing your use case, it is hard to tell which parts of libGDX you actually require. So here a quick summary for collecting all dependencies into a directory as a starting point:

First of all, you should try listing all dependencies of the gradle subproject you require via `./gradlew <subproject>:dependencies` e.g. `./gradlew lwjgl3:dependencies` for the desktop backend that gdx-liftoff creates. This should give you an idea of which classpaths are available and what they look like.

To then collect the dependencies into a directory, you can create your own Gradle task in the desired subproject targeting the desired classpath, something along the lines of:

```
tasks.register("copyDependencies", Copy) {
    into("dependencies")
    from(project.configurations.runtimeClasspath)
}
```

Putting this task into the lwjgl3 subproject, you run it as `.\gradlew.bat lwjgl3:copyDependencies`. The output is then in the directory `lwjgl3/dependencies`.

I have to clarify again: this is not directly related to libGDX but Gradle instead, so support in that regard is not to be expected from the libGDX folks here (IMO). I am merely a passer by.

@tommyettinger might such a task be a candidate for the gradle files generated by gdx-liftoff?

**Comment by anonimo82** [comment]
Thanks so much for your reply.
You're right, I didn't mention the modules I'm interested in.
They are:
- LibGDX
- GDX-AI
- Bullet
- Box2D
- FreeType
- Controllers

I'll try your instructions tough

**Comment by tommyettinger** [comment]
@angelickite I don't see too much reason to add it, since the majority of users who can't or won't use Gradle to get JARs will similarly be in the "can't or won't" group for running any Liftoff Gradle task. Usually that's because they're trying to build with some Android-based IDE that doesn't have a working Gradle implementation. It can also be because they're doing desktop development and are stubbornly refusing to use Gradle, or any number of other reasons. My reasoning is that if they aren't using Liftoff's generated projects, they probably won't be running Gradle tasks in those projects... Since if they were using the generated project with all the deps selected, they wouldn't need the JARs.

**Comment by angelickite** [comment]
@tommyettinger I expressed my thoughts a bit too directly, sorry about that. What I meant to stimulate was a quick thought about whether this use case is common enough to warrant some sort of acting, like a side chapter in the libGDX documentation.

Overall I agree with you that libGDX is a somewhat opiniated framework and any divergence shifts the responsibilty more towards the consumer side.

Thinking out loud a bit: I might have to actually start a sort of website / blog which could be discoverable via a search engine search, might cover these one-offs that I have personal experience with quite well.
