### ISSUE TITLE
Module org.objectweb.asm.tree not found, required by org.objectweb.asm.util

### ISSUE THREAD

**Issue by Foodust** [libgdx/libgdx#7463]
Please ensure you have given all the following requested information in your report.

#### Issue details
lwjgl3.construo.packageWinX64 failed

#### Reproduction steps/code
just click  lwjgl3.construo.packageWinX64

#### Version of libGDX and/or relevant dependencies
org.gradle.daemon=false
org.gradle.jvmargs=-Xms512M -Xmx1G -Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8
org.gradle.configureondemand=false
groovyVersion=4.0.22
ashleyVersion=1.7.4
graalHelperVersion=2.0.1
enableGraalNative=false
gdxVersion=1.12.1
projectVersion=1.0.0

Gradle 8.10.1
------------------------------------------------------------

Build time:    2024-09-09 07:42:56 UTC
Revision:      8716158d3ec8c59e38f87a67f1f311f297b79576

Kotlin:        1.9.24
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.14 compiled on August 16 2023
Launcher JVM:  17 (Oracle Corporation 17+35-2724)
Daemon JVM:    C:\Program Files\jdk-17 (no JDK specified, using current Java home)
OS:            Windows 10 10.0 amd64

#### Stacktrace
```java
Exception in thread "main" java.lang.module.FindException: Module org.objectweb.asm.tree not found, required by org.objectweb.asm.util
	at java.base/java.lang.module.Resolver.findFail(Resolver.java:893)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:192)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:141)
	at java.base/java.lang.module.Configuration.resolve(Configuration.java:421)
	at java.base/java.lang.module.Configuration.resolve(Configuration.java:255)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:564)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:603)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:557)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:533)
	at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lwjgl3:createRuntimeImageWinX64'.
> Process 'command 'C:\Program Files\jdk-17\bin\jdeps.exe'' finished with non-zero exit value 1
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ o] Windows
- [ ] Linux
- [ ] macOS

**Comment by tommyettinger** [comment]
So construo depends on the command built into newer JDKs, `jdeps`. But `jdeps` sometimes gives very strange output that nothing else can use, depending on what your app needs from modules in the JDK and sometimes other libraries. This would be good to try to debug on the Discord server, if possible: https://libgdx.com/community/discord/ It may be good to start a topic in the Help forum, since I expect this may need some big pastes of lots of text. @fourlastor is the author of construo, and he may be interested in this issue.

Otherwise, seeing the output of the lwjgl3:dependencies task (in the tasks list, it's under lwjgl3 -> help -> dependencies) would help, since there's lots of ways a dependency on objectweb ASM stuff could have gotten in. I don't know why that ASM library would break the jdeps code though; I think it's used often.

**Comment by Foodust** [comment]
I added "lombok" if dependency is a problem.
  compileOnly 'org.projectlombok:lombok:1.18.34'
  annotationProcessor 'org.projectlombok:lombok:1.18.34'

**Comment by tommyettinger** [comment]
I can reproduce with just Groovy added; I'll see if Lombok without Groovy acts differently, too. This is an odd bug...

**Comment by Foodust** [comment]
main gradle
```
buildscript {
  repositories {
    mavenCentral()
    maven { url 'https://s01.oss.sonatype.org' }
    gradlePluginPortal()
    mavenLocal()
    google()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
    maven { url 'https://s01.oss.sonatype.org/content/repositories/snapshots/' }
  }
  dependencies {

  }
}

allprojects {
  apply plugin: 'eclipse'
  apply plugin: 'idea'

  // This allows you to "Build and run using IntelliJ IDEA", an option in IDEA's Settings.
  idea {
    module {
      outputDir file('build/classes/java/main')
      testOutputDir file('build/classes/java/test')
    }
  }
}

configure(subprojects) {
  apply plugin: 'java-library'
  apply plugin: 'groovy'
  sourceCompatibility = 11

  // From https://lyze.dev/2021/04/29/libGDX-Internal-Assets-List/
  // The article can be helpful when using assets.txt in your project.
  tasks.register('generateAssetList') {
    inputs.dir("${project.rootDir}/assets/")
    // projectFolder/assets
    File assetsFolder = new File("${project.rootDir}/assets/")
    // projectFolder/assets/assets.txt
    File assetsFile = new File(assetsFolder, "assets.txt")
    // delete that file in case we've already created it
    assetsFile.delete()

    // iterate through all files inside that folder
    // convert it to a relative path
    // and append it to the file assets.txt
    fileTree(assetsFolder).collect { assetsFolder.relativePath(it) }.each {
      assetsFile.append(it + "\n")
    }
  }
  processResources.dependsOn 'generateAssetList'

  compileJava {
    options.incremental = true
  }
}

subprojects {
  version = '$projectVersion'
  ext.appName = 'Tamagotchi'
  repositories {
    mavenCentral()
    maven { url 'https://s01.oss.sonatype.org' }
    // You may want to remove the following line if you have errors downloading dependencies.
    mavenLocal()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
    maven { url 'https://s01.oss.sonatype.org/content/repositories/snapshots/' }
    maven { url 'https://jitpack.io' }
  }
}

eclipse.project.name = 'YourProjectName' + '-parent'

```
core gradle
```
[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  api "com.badlogicgames.ashley:ashley:$ashleyVersion"
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  api "org.apache.groovy:groovy-all:$groovyVersion"

  compileOnly 'org.projectlombok:lombok:1.18.34'
  annotationProcessor 'org.projectlombok:lombok:1.18.34'

  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
}

```

**Comment by tommyettinger** [comment]
Yeah, this is incredibly strange, but even Java 22's `jdeps` command, not involving Gradle at all, can't print the deps for a jar built containing Groovy. I can't find any info why from Googling (and using DDG for good measure). This was also the case for Java 17's `jdeps`.

**Comment by Foodust** [comment]
I just copied https://libgdx.com/wiki/start/a-simple-game this.
😂😂

**Comment by tommyettinger** [comment]
The difference is that your Languages somehow have Groovy selected, and that (until someone figures out what on Earth Groovy does to jdeps) seems to break construo builds. You can try removing the line: 

```gradle
  api "org.apache.groovy:groovy-all:$groovyVersion"
```

(Or you can comment it out.) That works for me, and I can build an exe with construo then. However, it means Groovy won't be usable if you wanted that for any reason.

**Comment by fourlastor** [comment]
I this this happens because `groovy-all` [depends on a lot of things](https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-all/3.0.22), I think most of these aren't required (and I think what's enabling using groovy is the groovy gradle plugin, so you should still be able to use the language if you want to). Maybe depending on `groovy` is a better approach https://mvnrepository.com/artifact/org.codehaus.groovy/groovy/3.0.22

**Comment by Foodust** [comment]
Very good. It's settled
Tinning Groovy

**Comment by tommyettinger** [comment]
I might post an issue report on Groovy's issue tracker myself... their library should not (be able to) crash jdeps just from having it in a fat jar.
