### ISSUE TITLE
A help how to use the backend classes in a project

### ISSUE THREAD

**Issue by ambastos** [libgdx/libgdx#7481]
Please ensure you have given all the following requested information in your report.

#### Issue details
Actually, it's not a bug, it's only I need a help. I saw in a Stackoverflow post that there is a way to use a backend/headless to just load a Gdx class for example without need to create a full game or something. And I came to here in the libgdx github, and there is a folder called 'gdx-backend-headless', but how can I use it in my project? There is a way that just in a build.gradle download it as a dependency for example? 

#### Reproduction steps/code
I just have a class that extends Table in a project, and I want to use it in another project without need to create another libgdx project just to load this class.

#### Version of libGDX and/or relevant dependencies
1.12.1
#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] macOS

**Comment by nulldoubt** [comment]
I'm not really sure what you want and I think that you're talking about obtaining an instance of a gdx-based class without initiating an actual game.

Well it depends on what you actually want to achieve, some gdx classes are regular Java objects that don't access native code nor rely on an OpenGL context being active. That said, if you want a regular class, just instantiate it with the `new` keyword. If you need a class that relies on native code, you'll need to load the native libraries via the `SharedLibraryLoader`. If the class you're trying to instantiate requires a full OpenGL context (`SpriteBatch`, `Texture`, `FrameBuffer`, etc...), then you're better of launching an application.

Note that the class you want to instantiate has to _not_ rely on the static references in `Gdx`, e.g. `graphics`, `app`, `input`, etc. if you don't have a running application.

And if the class isn't in the scope of the project but is guaranteed to be injected in the final build, then you'll have to get through with either some abstractions :) or regular old reflection :/

Hope this helps!

**Comment by ambastos** [comment]
I just have heard in another forum, that there is a "way" on of some folder of this github project to create a 'headless' app, but I'am not sure how to do that, and those files doesn't appear in a gradle project. If there is a away to have access to these class put some other gdx dependency that I don't know about it. I try to resist to workaround it, but what I need is very simple. I need just for de Gdx.files should be not null. Because I use only a libgdx table(cell, rows, etc), and there is a line that use these class/properties during creating a cell. I probably could create a Gdx object before and put a fileHandler in the file property, but it's very workaround, if there is these another possibility...

**Comment by ambastos** [comment]
I discovery it! It's very easy actually. it's just to create in gradle(I am using a gradle project, maven should be almost same), to put a dependency:
 ` implementation 'com.badlogicgames.gdx:gdx-backend-headless:1.12.1' //headless version
   implementation "com.badlogicgames.gdx:gdx-platform:1.12.1:natives-desktop" //necessary to have a native files
`
and in our class just need to do this:
 `new HeadlessNativesLoader().load()`
and it loads Gdx and many other files. Thanks!
