### ISSUE TITLE
How would a new SDL3 backend benefit this project?

### ISSUE THREAD

**Issue by nulldoubt** [libgdx/libgdx#7482]
**Hey, I hope I'm not polluting this repo as this isn't a bug report.**

I've been working with libGDX for a while and really enjoy it. I'd love to contribute more to this awesome project. I’ve also worked extensively with SDL, and I'm wondering:

**_How could a new SDL3 backend benefit libGDX?_**

I’m thinking of a backend for handling window input, OpenGL context, audio, and controllers—not porting the current LWJGL3 backend to use the `SDL_Renderer` stuff.

Would this be beneficial to the project, or would it be redundant? Could it bring us closer to console support?

I know that the [Arc](https://github.com/Anuken/Arc) framework has an SDL2 backend, but it's quite different from libGDX.

Looking forward to hearing your thoughts!

**Comment by Frosty-J** [comment]
SDL might mean wider compatibility, possibly in conjunction with transpiling like [SwitchGDX](https://github.com/TheLogicMaster/switch-gdx) does. That's all I can think of. I'm generally wary of cases where a solution (make another desktop backend) is thought up before the corresponding problem (whatever this would solve).

**Comment by crykn** [comment]
FrostyJ is right, the main advantage would be (possible) wider compatibility. In particular this could prove useful for console support, see the info [here](https://libgdx.com/wiki/articles/console-support).
