### ISSUE TITLE
Libgdx 1.13.0 crashes setting window position and icon in Wayland

### ISSUE THREAD

**Issue by langurmonkey** [libgdx/libgdx#7495]
#### Issue details
Libgdx 1.13.0 uses LWJGL 3.3.4 (updated from 3.3.3), which uses GLFW 3.4 (updated from 3.3.8). When running on a Wayland session, the new GLFW version selects a native Wayland backend instead of going through xWayland. The Wayland protocol does not support setting window positions nor icons, so it produces a crash. The crash points are `Lwjgl3Application#542,544` for `GLFW.glfwSetWindowPos(...)`, and `Lwjgl3Window#351` for `GLFW.glfwSetWindowIcon(...)`. I hope I did not miss any. The crashes are 'benign' and allow the application to continue running.

Down below are the stack traces.

#### Reproduction steps/code
Create an empty Libgdx application and do not forget to set a window icon (i.e. `Lwjgl3ApplicationConfiguration#setWindowIcon(...)`).

#### Version of libGDX and/or relevant dependencies
- Libgdx: 1.13.0
- LWJGL: 3.3.4
- GLFW: 3.4

I'm currently using Hyprland. I'm also seeing some pretty bad performance degradation with LWJGL 3.3.4/GLFW 3.4 compared to the previous versions in Wayland, but I need more time to investigate.

#### Possible fixes
It is possible to bypass the window icon issue in user code by just detecting the session type and avoiding setting the icon if in Wayland. The window position is trickier, as it seems Libgdx sets it no matter what when the app is not in fullscreen mode. One could detect the GLFW backend and avoid using those calls in the case of Wayland:

```java
var waylandBackend = glfwGetPlatform() == GLFW_PLATFORM_WAYLAND;
```
Looks like jMonkeyEngine is considering doing the same (PR still open, see [here](https://github.com/jMonkeyEngine/jmonkeyengine/pull/2314)).

#### Stacktrace
Window position:
```java
libdecor-gtk-WARNING: Failed to initialize GTK
Failed to load plugin 'libdecor-gtk.so': failed to init
[LWJGL] GLFW_FEATURE_UNAVAILABLE error
	Description : Wayland: The platform does not support setting the window position
	Stacktrace  :
		org.lwjgl.glfw.GLFW.glfwSetWindowPos(GLFW.java:2536)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:542)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:451)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:437)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:149)
		gaiasky.desktop.GaiaSkyDesktop.runGaiaSky(GaiaSkyDesktop.java:623)
		gaiasky.desktop.GaiaSkyDesktop.launchMainApp(GaiaSkyDesktop.java:545)
		gaiasky.desktop.GaiaSkyDesktop.init(GaiaSkyDesktop.java:416)
		gaiasky.desktop.GaiaSkyDesktop.main(GaiaSkyDesktop.java:263
```

Window icon:
```java
[LWJGL] GLFW_FEATURE_UNAVAILABLE error
	Description : Wayland: The platform does not support setting the window icon
	Stacktrace  :
		org.lwjgl.glfw.GLFW.nglfwSetWindowIcon(GLFW.java:2435)
		org.lwjgl.glfw.GLFW.glfwSetWindowIcon(GLFW.java:2467)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.setIcon(Lwjgl3Window.java:351)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.setIcon(Lwjgl3Window.java:319)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:552)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:451)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:437)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:149)
		gaiasky.desktop.GaiaSkyDesktop.runGaiaSky(GaiaSkyDesktop.java:621)
		gaiasky.desktop.GaiaSkyDesktop.launchMainApp(GaiaSkyDesktop.java:543)
		gaiasky.desktop.GaiaSkyDesktop.init(GaiaSkyDesktop.java:416)
		gaiasky.desktop.GaiaSkyDesktop.main(GaiaSkyDesktop.java:263)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] macOS

**Comment by langurmonkey** [comment]
Right, the crashes do not stop the world, but I would argue these methods should not be called at all in Wayland ;)

**Comment by SimonIT** [comment]
Hey, can you try whether this #7497 fixes your issue? I justz made the same changes as jmonkey

**Comment by langurmonkey** [comment]
I just realised that getting the window position is also not allowed in Wayland, so [`Lwjgl3Graphics#339`](https://github.com/libgdx/libgdx/blob/d02e69bfbff171b1ffc3c1fa601895e9511c6463/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Graphics.java#L339) also produces this benign crash. 
And also the methods in `getPositionX()` and `getPositionY()` in `Lwjgl3Window` (see [here](https://github.com/libgdx/libgdx/blob/d02e69bfbff171b1ffc3c1fa601895e9511c6463/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Window.java#L250)).

**Comment by langurmonkey** [comment]
Libgdx 1.13.1 defaults to lwjgl 3.3.3/glfw 3.3.8, and this still uses xWayland, so not an issue yet unless someone bumps the lwjgl version in their config.
