### ISSUE TITLE
In the extension "Hiero", unable to generate specific font if the font name ends with "Bold" or number, etc.

### ISSUE THREAD

**Issue by FrenkYang0918** [libgdx/libgdx#7502]
According to the code and the document of `java.awt.Font.decode(String str)` :
https://github.com/libgdx/libgdx/blob/1ba527c9968a2fa8ec022a64ac2dcce6574ee8dd/extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/Hiero.java#L298
If a font name ends with `"plain"`, `"bold"`, `"italic"`, `"bolditalic"`, or number, it will not be able to parse correctly. For example, "Bauhaus 93" is recognized as a font named "Bauhaus" and pointsize is 93.
To solve the problem, the `str` in `Font.decode(String str)` should end with `-PLAIN-12`. ("plain" is the default style and "12" is the default pointsize)
The modification code is below:
Line 298: `unicodeFont = new UnicodeFont(Font.decode(String.format("%s-PLAIN-12", fontList.getSelectedValue())), fontSize, boldCheckBox.isSelected(),`

**Comment by tommyettinger** [comment]
I sent a PR 10 days ago that fixes this. It is an extremely easy PR to review for anyone who has read this issue. Guess what? No one has reviewed or even commented on it! Hooray! In short, use [AngelCode BMFont](https://www.angelcode.com/products/bmfont/) in most cases, or in some specific cases [FontWriter](https://github.com/tommyettinger/fontwriter) (mainly for distance field fonts or [TextraTypist](https://github.com/tommyettinger/textratypist/); it uses [different code to load](https://github.com/tommyettinger/textratypist/tree/main/src/test/java/com/github/tommyettinger/fontwriter) in plain libGDX, which may move into its own library soon). It just seems like Hiero is unmaintainable if simple fixes get ignored, so you might as well use software that works.
