### ISSUE TITLE
Gdx.net.openURI not working on iOS 18.1 Simulator

### ISSUE THREAD

**Issue by keesvandieren** [libgdx/libgdx#7509]
Please ensure you have given all the following requested information in your report.

#### Issue details
Gdx.net.openURI is expected to open https url. Is no longer working on iOS 18.1

#### Reproduction steps/code

Use iOS 18.1 similator, and open an url like this:

```Kotlin

        Gdx.net.openURI("https://libgdx.com")

```

#### Workaround

There is a workaround which works:

```Kotlin
        UIApplication.getSharedApplication().openURL(NSURL("https://libgdx.com"), UIApplicationOpenURLOptions()) {}
```

#### Proposed fix

Update IOSNet to use the new openURL method.

#### Version of libGDX and/or relevant dependencies
* libgdx version:  1.13.0 (also 1.12.1)
* Robovm version: 2.3.22

It works on iOS 17, it is not working on iOS 18.1

#### Stacktrace
```java
// N/a
```

#### Please select the affected platforms
- [ ] Android
- [X] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by obigu** [comment]
Thanks for reporting. It doesn't work on Simulator but does work on Device. I'll change the title of the issue to reflect that and create a PR for it.

**Comment by keesvandieren** [comment]
Thanks for the fix. My app update was rejected by Apple with this message:

```Bug description: App did not produce further action when we tapped on Privacy policy and Term of Use.```

So I think most app developers will face this issue, as most apps are required to have a link to privacy policy and terms of use in their app
