### ISSUE TITLE
Animations speeding up and stopping eventually

### ISSUE THREAD

**Issue by Sesu8642** [libgdx/libgdx#7536]
#### Issue details
Someone left my game running for several days and noticed that the animations stopped. I simulated this by setting a high state time. I found out that the animations first speed up more and more after a few days and eventually stop completely after exactly 2¹⁹ seconds.

#### Reproduction steps/code
```java
package de.sesu8642.bugdemo;

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.Animation;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.graphics.g2d.TextureRegion;
import com.badlogic.gdx.utils.ScreenUtils;

/** {@link com.badlogic.gdx.ApplicationListener} implementation shared by all platforms. */
public class Main extends ApplicationAdapter {
    private SpriteBatch batch;
    private Texture frame1;
    private Texture frame2;
    private Animation<Texture> animation;
    
    float stateTime1 = 0;
    float stateTime2 = 8 * 24 * 24 * 60F; // after 8 days
    float stateTime3 = 16 * 24 * 24 * 60F; // after 16 days
    float stateTime4 = (float) Math.pow(2, 19) - 5; // just before 2¹⁹ seconds

    @Override
    public void create() {
        batch = new SpriteBatch();
        frame1 = new Texture("baron_1.png");
        frame2 = new Texture("baron_2.png");
        animation = new Animation<>(0.5F, frame1, frame2);
    }

    @Override
    public void render() {
    	ScreenUtils.clear(0.15f, 0.15f, 0.2f, 1f);
    	stateTime1 += Gdx.graphics.getDeltaTime();
    	stateTime2 += Gdx.graphics.getDeltaTime();
    	stateTime3 += Gdx.graphics.getDeltaTime();
    	stateTime4 += Gdx.graphics.getDeltaTime();
    	Texture animation1Frame = animation.getKeyFrame(stateTime1, true); // moves at the expected speed
    	Texture animation2Frame = animation.getKeyFrame(stateTime2, true); // moves very fast
    	Texture animation3Frame = animation.getKeyFrame(stateTime3, true); // no longer moves at all
    	Texture animation4Frame = animation.getKeyFrame(stateTime4, true); // moves very fast for 5s and then stops
        batch.begin();
        batch.draw(animation1Frame, 0, 400);
        batch.draw(animation2Frame, 100, 400);
        batch.draw(animation3Frame, 200, 400);
        batch.draw(animation4Frame, 300, 400);
        batch.end();
    }

    @Override
    public void dispose() {
        batch.dispose();
        frame1.dispose();
        frame2.dispose();
    }
}

```
[demo.zip](https://github.com/user-attachments/files/17952531/demo.zip)

#### Version of libGDX and/or relevant dependencies
1.12.1, 1.13.0

#### Please select the affected platforms
- [x] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [ ] macOS

probably others too

**Comment by Frosty-J** [comment]
This isn't directly a libGDX issue. That's just the limitations of single-precision floating-point. Since you know your animation is 1 second long, you can modulo your `stateTime` by this to avoid the precision loss (or subtract 1 if >= 1).

**Comment by Sesu8642** [comment]
I understand what's causing the problem but it certainly looks like a libGDX issue from the user's perspective. It's also not a rare use case that affects my game specifically but is likely to happen in most games using the Animation class.

Since the Animation class also knows the length of the animation, is there any reason the modulo operation can't be done within?

**Comment by MobiDevelop** [comment]
It's not really a problem unique to Animation, allowing your state time to get that high is probably not the best in general.

I'd say you might consider limiting your state time to a reasonable maximum and when you hit it, subtract that amount and start over (keeping track of how many times you've hit it if for some reason you need to know the full amount)

```java
class StateTime {

  private static final float MAX_VALUE = 3600f;
  private int cycles = 0;

  private float time = 0f;

  void accrueTime(float deltaTime) {
    time += deltaTime;
    if (time >= MAX_VALUE) {
      time -= MAX_VALUE;
      cycles += 1;
    }
  }

  float getTime() {
    return time;
  }

  float getFullTime() {
    return cycles * MAX_VALUE + time;
  }

}
```

**Comment by Frosty-J** [comment]
> Since the Animation class also knows the length of the animation, is there any reason the modulo operation can't be done within?

There already is a modulo done within for looping animations. The issue stems from the value being passed into it, as `float` lacks the precision required for accumulating delta to work without noticeable rounding errors once hundreds of thousands of seconds have elapsed.

If we take your 8 days example, we can calculate that the minimum increment it will be able to perform at this stage is 31.2ms. If your game is running at 60fps, the 16.67ms you'd expect will get rounded up. Likewise, at 16 days it'll get rounded down to 0.

Input a decimal value and click the `1` and `-1` buttons at https://www.h-schmidt.net/FloatConverter/IEEE754.html to simulate this.

**Comment by Sesu8642** [comment]
I understand the limitation is with frameTime being a float. It might be a good idea to update [this wiki page](https://libgdx.com/wiki/graphics/2d/2d-animation). I would at least add some warning. Ideally, there could be some generic solution for long running animations. While the workaround works fine for me, it only does so because all my animations have the same duration. Other games with many animations of different durations might need multiple frameTime variables. But that doesn't sound like a very elegant solution either.

**Comment by Frosty-J** [comment]
^ I've opened an issue for it.
