### ISSUE TITLE
NullPointerException on AndroidXKeyboardHeightProvider.start on version 1.13.0

### ISSUE THREAD

**Issue by DavidPDev** [libgdx/libgdx#7537]
#### Issue details
Hi, after updating from libGDX 1.12.1 to 1.13.0 and published a couple of games some errors have appeared in the Google Play Console and firebase crashlytics:
```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnApplyWindowInsetsListener(android.view.View$OnApplyWindowInsetsListener)' on a null object reference
  at androidx.core.view.ViewCompat$Api21Impl.setOnApplyWindowInsetsListener (ViewCompat.java:4840)
  at androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener (ViewCompat.java:2537)
  at com.badlogic.gdx.backends.android.keyboardheight.AndroidXKeyboardHeightProvider.start (AndroidXKeyboardHeightProvider.java:33)
  at com.badlogic.gdx.backends.android.AndroidApplication$2.run (AndroidApplication.java:298)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:233)
  at android.os.Looper.loop (Looper.java:344)
  at android.app.ActivityThread.main (ActivityThread.java:8248)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:589)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1071)
```

#### Reproduction steps/code
This is not happening to all users, just "some" of them, I can't identify a common pattern...
Happens to different device brands and OSs:
![image](https://github.com/user-attachments/assets/8ab85a51-253e-4105-9387-cd56937c8331)

#### Version of libGDX and/or relevant dependencies
> libGDX 1.13.0

Of course I have added on build.gradle file the line:
`implementation 'androidx.core:core:1.13.1' `

And the gradle.properties file has the line:
`android.useAndroidX=true`

#### Please select the affected platforms
- [X ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by Frosty-J** [comment]
I don't know why this might be happening. Hopefully #7485 can fix it, but it's hard to say if you don't own an afflicted device to test on.

**Comment by DavidPDev** [comment]
Thank you for the quick reply!
Seems that #7485 can fix it!!!
How can I update it?
Maybe a quick 1.13.1 version this some bugfixes...

**Comment by Frosty-J** [comment]
It hasn't been merged, so if you wanted this right now it might be a case of building that branch locally à la https://libgdx.com/dev/from-source/#building-and-publishing (add `mavenLocal()` to the top of the `repositories` Gradle block if this is a gdx-liftoff project).

**Comment by DavidPDev** [comment]
Thank you!
I think I can wait some days until it is merged to the SNAPSHOT branch...
I will share more stats when I have more info about this issue.

**Comment by DavidPDev** [comment]
Finally I have downgraded to libGDX v.1.12.1 until I have more information about the error or a new gdx version is published.

**Comment by DavidPDev** [comment]
Thank you @Berstanio!
Well, I am not sure if I am doing some "special" setup... What I am sure is that upgrading to 1.13.0 crashes sometimes (for some users), but I have not been able to reproduce it myself...

I left one game (with a small user base) with the 1.13.0 version on release (published on Goole Play) and some users are crashing...
I will try to share all the info I can so we can fix this "bug":

![image](https://github.com/user-attachments/assets/9b9eb06c-9897-427a-8dd2-583c1dbd3b98)
![image](https://github.com/user-attachments/assets/838c7966-61bf-458b-9412-9aefc8c87600)
![image](https://github.com/user-attachments/assets/b97e9d28-07fc-4c68-87cb-4d6d159440df)

My main activity just extends from AndroidApplication:
```
           requestWindowFeature(Window.FEATURE_NO_TITLE);
            getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);
            getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FORCE_NOT_FULLSCREEN);

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                try {
                    getWindow().getAttributes().layoutInDisplayCutoutMode =
                        WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES;
                }
                catch (Exception e) { }
            }
```

For the progress load splash screen I use the following code (from an old blog post):
```
                platformParametersAndroid.SplashProgressEventSet (splashProgressEventAndroid);

                FrameLayout baseLayout = new FrameLayout(this);
                FrameLayout.LayoutParams frameParams =  new FrameLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.MATCH_PARENT);
                baseLayout.setLayoutParams(frameParams);

                { // GAME
                    View gameView = null;
                    try {       // Try to avoid the java.lang.ClassCastException on some Android 5.0 and 5.1 devices when using the immersive mode
                        gameView = initializeForView(myGame, config);
                    }
                    catch (Throwable e) {   // Changed ClassCastException to Throwable to try to avoid useInmersive crash reports
                        config.useImmersiveMode=false;
                        gameView = initializeForView(myGame, config);
                    }
                    FrameLayout.LayoutParams params = new FrameLayout.LayoutParams(WindowManager.LayoutParams.MATCH_PARENT, WindowManager.LayoutParams.MATCH_PARENT);
                    gameView.setLayoutParams(params);
                    baseLayout.addView(gameView);
                }
                { // SPLASH
                    LinearLayout linearLayout= (LinearLayout)getLayoutInflater().inflate(parameters.layout.splash, null);
                    baseLayout.addView(linearLayout);
                    splashProgressEventAndroid.SetViews(baseLayout,linearLayout, (ProgressBar)linearLayout.findViewById(parameters.id.progressBar1));
                }
                setContentView(baseLayout);

```

Other "relevant code": I do the following code the ask for the players name (Only Android):
```
public class UtilGdx {
    public static void GetTextInput (final Activity context, final Input.TextInputListener listener, final String title, final String text, final String hint)
    {
        try {
            context.runOnUiThread(new Runnable() {
                public void run() {
                    final AlertDialog.Builder alert = new AlertDialog.Builder(context);
                    alert.setTitle(title);
                    final EditText input = new EditText(context);
                    input.setHint(hint);
                    input.setText(text);
                    input.setSingleLine();
                    input.requestFocus();
                    alert.setView(input);
                    if (listener!=null) {
                        alert.setPositiveButton(context.getString(android.R.string.ok), new DialogInterface.OnClickListener() {
                            public void onClick(DialogInterface dialog, int whichButton) {
                                Gdx.app.postRunnable(new Runnable() {
                                    @Override
                                    public void run() {
                                        listener.input(input.getText().toString());
                                    }
                                });
                            }
                        });
                        alert.setNegativeButton(context.getString(android.R.string.cancel), new DialogInterface.OnClickListener() {
                            public void onClick(DialogInterface dialog, int whichButton) {
                                Gdx.app.postRunnable(new Runnable() {
                                    @Override
                                    public void run() {
                                        listener.canceled();
                                    }
                                });
                            }
                        });
                        alert.setOnCancelListener(new DialogInterface.OnCancelListener() {
                            @Override
                            public void onCancel(DialogInterface arg0) {
                                Gdx.app.postRunnable(new Runnable() {
                                    @Override
                                    public void run() {
                                        listener.canceled();
                                    }
                                });
                            }
                        });
                    }

                    final AlertDialog alertToShow = alert.create();
                    try {
                        alertToShow.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_VISIBLE);
                    } catch (Exception e) {
                    }
                    alertToShow.show();
                }
            });
        }
        catch (Exception e) { }
    }
}

```

Maybe the simple fix inside the AndroidXKeyboardHeightProvider class  should be checking if some value is null to avoid this crash.

**Comment by DavidPDev** [comment]
Just a few more insights...
There are also some more crashes related to this issue:

The first one is the main crash issue:

![image](https://github.com/user-attachments/assets/fd19a679-474e-4562-9874-40d9aa64c826)

Stacktrace of this 4 crashes:

```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnApplyWindowInsetsListener(android.view.View$OnApplyWindowInsetsListener)' on a null object reference
  at androidx.core.view.ViewCompat$Api21Impl.setOnApplyWindowInsetsListener (ViewCompat.java:5214)
  at androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener (ViewCompat.java:2899)
  at com.badlogic.gdx.backends.android.keyboardheight.AndroidXKeyboardHeightProvider.start (AndroidXKeyboardHeightProvider.java:33)
  at com.badlogic.gdx.backends.android.AndroidApplication$2.run (AndroidApplication.java:298)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:233)
  at android.os.Looper.loop (Looper.java:344)
  at android.app.ActivityThread.main (ActivityThread.java:8249)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:589)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1071)
```

```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.IBinder android.view.View.getWindowToken()' on a null object reference
  at com.badlogic.gdx.backends.android.keyboardheight.StandardKeyboardHeightProvider.start (StandardKeyboardHeightProvider.java:98)
  at com.badlogic.gdx.backends.android.AndroidApplication$2.run (AndroidApplication.java:298)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:8161)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)
```

```
Exception : java.lang.NullPointerException	Attempt to invoke virtual method 'void android.view.View.setOnApplyWindowInsetsListener(android.view.View$OnApplyWindowInsetsListener)' on a null object reference
  at androidx.core.view.ViewCompat$Api21Impl.setOnApplyWindowInsetsListener (ViewCompat.java:5214)
  at androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener (ViewCompat.java:2899)
  at com.badlogic.gdx.backends.android.keyboardheight.AndroidXKeyboardHeightProvider.start (AndroidXKeyboardHeightProvider.java:33)
  at com.badlogic.gdx.backends.android.AndroidApplication$2.run (AndroidApplication.java:298)
  at android.os.Handler.handleCallback (Handler.java:1013)
  at android.os.Handler.dispatchMessage (Handler.java:101)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:328)
  at android.app.ActivityThread.main (ActivityThread.java:9237)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:594)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1099)
```

```
Exception java.lang.NullPointerException:
  at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.longPress (ActorGestureListener.java:57)
  at com.badlogic.gdx.input.GestureDetector$1.run (GestureDetector.java:58)
  at com.badlogic.gdx.utils.Timer$TimerThread.runPostedTasks (Timer.java:322)
  at com.badlogic.gdx.utils.Timer$TimerThread$1.run (Timer.java:272)
  at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame (AndroidGraphics.java:497)
  at android.opengl.GLSurfaceView$GLThread.guardedRun (GLSurfaceView.java:1591)
  at android.opengl.GLSurfaceView$GLThread.run (GLSurfaceView.java:1286)
```

**Comment by Berstanio** [comment]
```java
                platformParametersAndroid.SplashProgressEventSet (splashProgressEventAndroid);

                FrameLayout baseLayout = new FrameLayout(this);
                FrameLayout.LayoutParams frameParams =  new FrameLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.MATCH_PARENT);
                baseLayout.setLayoutParams(frameParams);

                { // GAME
                    View gameView = null;
                    try {       // Try to avoid the java.lang.ClassCastException on some Android 5.0 and 5.1 devices when using the immersive mode
                        gameView = initializeForView(myGame, config);
                    }
                    catch (Throwable e) {   // Changed ClassCastException to Throwable to try to avoid useInmersive crash reports
                        config.useImmersiveMode=false;
                        gameView = initializeForView(myGame, config);
                    }
                    FrameLayout.LayoutParams params = new FrameLayout.LayoutParams(WindowManager.LayoutParams.MATCH_PARENT, WindowManager.LayoutParams.MATCH_PARENT);
                    gameView.setLayoutParams(params);
                    baseLayout.addView(gameView);
                }
                { // SPLASH
                    LinearLayout linearLayout= (LinearLayout)getLayoutInflater().inflate(parameters.layout.splash, null);
                    baseLayout.addView(linearLayout);
                    splashProgressEventAndroid.SetViews(baseLayout,linearLayout, (ProgressBar)linearLayout.findViewById(parameters.id.progressBar1));
                }
                setContentView(baseLayout);

```

Where does this code happen? In `onCreate`?

**Comment by DavidPDev** [comment]
> Where does this code happen? In `onCreate`?

Yes.

I'm planning on changing the "Loading resources" progress bar and remove all FrameLayouts, so I can check if the crash has something to do with that "trick".

**Comment by DavidPDev** [comment]
Quick Update.
After removing all FrameLayout code the crash is still happening.
Now i just do in OnCreate:
```
...
  View gameView = initializeForView(myGame, config);
  setContentView(gameView);
...
```
And I dont use fragments, the main game class extends from AndroidAplication.
Any ideas of what can I do next?

**Comment by Berstanio** [comment]
>  Any ideas of what can I do next?

Could you try just doing:
```java
...
  initialize(myGame, config);
...
```
If that works, then it is probably the `setContentView` command that creates a race or something

**Comment by DavidPDev** [comment]
Thank you!
I have just tried it and on my emulator + physical devices and seems to work...
I will publish a release on Google Play and check it...
So? What is the point of doing setContView () instead of directly initialize() ?

**Comment by obigu** [comment]
Using `initialize` takes care of initializing verything for you and sets the libGDX as the content view for the Activity. If you have a custom `Layout` where libGDX `View` is not the only `View` like for example if you want to add a `View` with an AdMob banner you have the option to call `initializeForView` instead in which case you would need to initialize stuff on your end set the ContentView you want to the Activity (like a custom Layout). 

You can check the code that is executed in `AndroidApplication`

```
if (!isForView) {
			try {
				requestWindowFeature(Window.FEATURE_NO_TITLE);
			} catch (Exception ex) {
				log("AndroidApplication", "Content already displayed, cannot request FEATURE_NO_TITLE", ex);
			}
			getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);
			getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FORCE_NOT_FULLSCREEN);
			setContentView(graphics.getView(), createLayoutParams());
		}
```

In both cases `setContentView()` is called so it's not the root of the issue itself. I myseld use ìnitializeForView` in my games and haven't seen the issue in production.

**Comment by DavidPDev** [comment]
Thanks you too @obigu !
And what about this other case I have in a game with banners?
```
        View gameView = initializeForView(myGame, config);
        //setupAds();
        RelativeLayout layout = new RelativeLayout(this);
        layout.addView(gameView, ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.MATCH_PARENT);
        RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.WRAP_CONTENT);
        params.addRule(RelativeLayout.ALIGN_PARENT_BOTTOM);
        layout.addView(bannerAd, params);

        bannerAd.setVisibility(View.VISIBLE);
        AdRequest.Builder builder = new AdRequest.Builder();
        AdRequest ad = builder.build();
        bannerAd.loadAd(ad);

        setContentView(layout);
        startAdvertising(bannerAd, this);
```

I have tried removing the setContentView and obviously i get a black screen... I will check wiki and docs...

**Comment by obigu** [comment]
It's correct, when you use `initializeForView` you need to call `setContentView` and pass the `Layout`

**Comment by DavidPDev** [comment]
Well I have some conclusions after a few days in poduction (published on Google Play) with many users usage:

1) On the Game1 (with no banners) replacing
```
...
  View gameView = initializeForView(myGame, config);
  setContentView(gameView);
...
```
with
```
...
  initialize(myGame, config);
...
```
Fixed the crash totally. No more exceptions in AndroidXKeyboardHeightProvider.
Good!



2) On the Game2, with banners:

Following the structure in the link : https://libgdx.com/wiki/third-party/admob-in-libgdx
```
RelativeLayout layout = new RelativeLayout(this);
...
View gameView = initializeForView(new HelloWorld(), false);
...
layout.addView(adView, adParams);
...
setContentView(layout);
````
Still crashes (null exceptions) in the AndroidXKeyboardHeightProvider class.
Diving a bit in the setContentView function:
<img width="719" alt="image" src="https://github.com/user-attachments/assets/b1839f17-f2de-4734-ae23-35eb046e4c4e" />

GREEN: When !isForView the setContentView is done before creating the AndroidXKeyboardHeightProvider(this) -> Works!

RED: But if you use the structure initializeForView () and after setContentView() the creation of the AndroidXKeyboardHeightProvider is done before seting up the contentView. -> Crashes sometimes!

So.
I have created a banner view with the following structure:
![image](https://github.com/user-attachments/assets/dcec36e1-68c4-4f15-9c70-f05878204d14)

Seems anti-intuitive... 1st create the layout, 2nd setContentView and 3rd initializeForView... but works...
And no more crashes.

Conclusion:
I think the problem is that sometimes (maybe a race case) the init() or initializeForView() crashes because of the keyboard not been initialized properly...

**Comment by Berstanio** [comment]
Thank you very much for the analysis.

While `KeyboardHeightProvider#start` (the method that is crashing) is correctly called after everything has been setup properly:
https://github.com/libgdx/libgdx/blob/e67b29de18ee225bf53792b7f6909f2c6b7e581a/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidApplication.java#L298
, I totally failed to realises that the `View` it operates is calculated on creating the HeightProvider:
https://github.com/libgdx/libgdx/blob/e67b29de18ee225bf53792b7f6909f2c6b7e581a/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/keyboardheight/AndroidXKeyboardHeightProvider.java#L27

So we should just defer getting the content view to the call of `start` and it should fix your crashes

**Comment by Berstanio** [comment]
@DavidPDev A new 1.13.1-SNAPSHOT has been released, that should resolve the issues.
Could you give it a try?

**Comment by DavidPDev** [comment]
Thank you @Berstanio! Those changes make a lot of sense fo me.
Yes I will check if 1.13.1-SNAPSHOT resolves the issue, after changing my code again (the order of calls) and making setContentView() the last call, as stated if the wiki...

**Comment by DavidPDev** [comment]
Hi, after 3 days in production, I can assure that the #7553 fixes the crash in all cases.  👍

In my opinion a new update (1.13.1) should be released to production ASAP.

But it is true that only projects using the structure `initializeForView(myGame, config);` +  `setContentView(gameView);` are afected... all games with banners may crash...

**Comment by obigu** [comment]
> But it is true that only projects using the structure `initializeForView(myGame, config);` + `setContentView(gameView);` are afected... all games with banners may crash...

Well, not even that, none of my games crash and I use this same Layout for banners. I wonder if the difference may be you are loading the banner ads before setting the content view.
