### ISSUE TITLE
Right-To-Left Text Rendering Support

### ISSUE THREAD

**Issue by ashrafsa** [libgdx/libgdx#787]
We need to support rendering bitmap fonts for languages such as Arabic, Hebrew which  the rendering of a text starts from right to left.

For that I can contribute but I need some help from the graceful stuff of this framework.

**Comment by EtK2000** [comment]
I'm working on a game in LibGdx and I have added support for RTL text.

**Comment by intrigus** [comment]
Would be nice if you could create a PR or a diff or upload your code somewhere, so it doesn't get lost :)

**Comment by EtK2000** [comment]
I'll upload it as a gist.<br />I have a few TODOs remaining, but overall it is usable.

**Comment by EtK2000** [comment]
Here is the gist:<br />https://gist.github.com/EtK2000/9be88488d70e9bf399b18cff444a9036

**Comment by CrowniAPIs** [comment]
RTL languages like Arabic not just direction from RIGHT to LEFT, but how connect their letters with each other and some letters as a block with 2 or more letters.
So, I do it with fully supporting RTL language. 
https://github.com/CrowniAPIs/libGDX-RTL-Language

**Comment by xGnoSiSx** [comment]
@CrowniAPIs that's fantastic work!

I really hope this will be added in.. it would also help for ajapanese and chinese since those languages also have glyphs transforming as you type.

**Comment by NathanSweet** [comment]
@CrowniAPIs that is very interesting! Can you explain how it works?

**Comment by CrowniAPIs** [comment]
@NathanSweet 

**There is four types of Arabic letters:**
**1X.** No connection with any glyphs. _(one letter has 1 connection shape)._
**2X.** Connection with previous glyph only. _(one letter has 2 connection shapes)._
**3X.** Connection with previous and next glyph with change it into new glyph as block of two or more letters. _(one letter has 2 connection shapes)._
**4X.** Connection with previous and next glyph.  _(one letter has 4 connection shapes)._
### So, 
I created [ArCharCode](https://github.com/CrowniAPIs/libGDX-RTL-Language/blob/master/core/src/com/crowni/gdx/rtllang/support/ArCharCode.java) which contains all char integer code and own case for each one.
In [ArFont](https://github.com/CrowniAPIs/libGDX-RTL-Language/blob/master/core/src/com/crowni/gdx/rtllang/support/ArFont.java) which is logic, I checked every char input what is its case. Then according to its case I added correct glyph into array. Finally glyphs array converts to string after reverse it.

.... Sorry for my bad English ....

**Comment by EtK2000** [comment]
@CrowniAPIs does this have support for other languages that combine letters, or only Arabic?

**Comment by CrowniAPIs** [comment]
@EtK2000 In fact I don't know about other RTL languages like Japanese and Chinese cases. So, If I know these languages cases, I think its easy to support them.

**Comment by NathanSweet** [comment]
@CrowniAPIs Thanks. BitmapFont has a `getGlyphs` method, which is used by GlyphLayout. This allows the font to specify the glyphs for a string. Maybe you can extend BitmapFont and put the logic there?

CJK languages can be displayed as LTR and are already supported.

**Comment by CrowniAPIs** [comment]
@NathanSweet Good to hear that. I will add new branch as a default branch instead of master and put new code with my logic to do that with inheritance of `BitmapFont` directly. I think your hint is better than my thinking in exist code. Thanks.
I hope that will be added into libGDX as a default support.

**Comment by CrowniAPIs** [comment]
@NathanSweet THANK YOU VERY MUCH. I will do it soon. THANK YOU AGAIN.

**Comment by ybeapps** [comment]
@CrowniAPIs hi, are you still working on it? I need this too... thx

**Comment by nightblade9** [comment]
@CrowniAPIs I see your repository from December 2017. Are you still working on this / planning to merge it in?
