### ISSUE TITLE
JsonValue.remove() removes all childs to the left of target

### ISSUE THREAD

**Issue by desertkun** [libgdx/libgdx#877]
Hello!

I've updated to nightly version of Libgdx (27-Oct-2013 18:58) and found issue with JsonValue class.

Please take a look for this code:

```
Json json = new Json();
JsonValue val = json.fromJson(null, "{\"x\":7,\"y\":7,\"c\":\"cat\",\"clazz\":\"zz\"}");
val.remove("c");
```

But instead of removing the "c" object JsoneValue removes whole items to the left from it.

```
String s = val.toString();
// s = {"clazz":"zz"}
```

Is this behavior is intended?
Thank you!

**Comment by cellcrowd** [comment]
Has there been a regression? I am hitting this in 1.9.11-SNAPSHOT

**Comment by NathanSweet** [comment]
@cellcrowd Don't think so, works for me:
```
static public void main (String[] args) throws Exception {
	Json json = new Json();
	JsonValue val = json.fromJson(null, "{\"x\":7,\"y\":7,\"c\":\"cat\",\"clazz\":\"zz\"}");
	System.out.println(val);
	val.remove("c");
	System.out.println(val);
}
```
