### ISSUE TITLE
Ogg support for IOS devices (RoboVM Backend)

### ISSUE THREAD

**Issue by jpienbro** [libgdx/libgdx#963]
Could ogg support be included in the IOS/RoboVM Backend? 
For a game that I'm porting from Android to IOS I need to be able to play ogg files (or convert them on runtime), because users can add their own files (including ogg files) to the game to generate a gameplay track. 
It's a rhythm game, so music is really important.

I found this page about precompiled ogg libraries, maybe it can be useful.
http://iosdeveloperzone.com/2012/08/07/precompiled-ogg-vorbis-libraries-for-ios/

**Comment by dzungpv** [comment]
I post here for preference if anyone want ogg support: http://www.shlzero.com/wordpress/?page_id=205. Can use HekkusSoundSystem static lib and call from java. It not free but you can pay a very small fee.
