### ISSUE TITLE
Calling native NewDirectByteBuffer with size 0 causes crash when using ART runtime

### ISSUE THREAD

**Issue by terryhau** [libgdx/libgdx#976]
When creating a Mesh, I'm passing in 0 for maxIndices. This eventually leads to a native call NewDirectByteBuffer(ptr, numBytes) with numBytes = 0. This causes a crash when using Android 4.4's ART runtime with the following error:

JNI DETECTED ERROR IN APPLICATION: capacity must be greater than 0: 0
in call to NewDirectByteBuffer
from java.nio.ByteBuffer com.badlogic.gdx.utils.BufferUtils.newDisposableByteBuffer(int)
...

Replacing all the maxIndicies with 1 instead of 0 allows my game to run perfectly on on ART.

Note:
Some classes in libGDX (such as ImmediateModeRenderer20) create meshes with maxIndices = 0, so they can't be used in ART without modification due to the above.

**Comment by CrandellWS** [comment]
Yes 4.4.4 Art ... @n3o59hf https://github.com/libgdx/libgdx/issues/976#issuecomment-30218089 simply changed the font and it works... but either font it works with Dalvik... just leaving a note...
