### ISSUE TITLE
Backspace and del key doesn't work in the HTML5 text input box on Mac OS X

### ISSUE THREAD

**Issue by Andrej1A** [libgdx/libgdx#990]
Hi,
the backspace and del key doesn't work in the HTML5/GWT text input box on Mac OS X. You can't delete a character that you typed in the text input box. In iOS and the desktop project works it well. I tested the nightly build from today and the 0.9.9 version. Works it at someone?

```
Gdx.input.getTextInput(new TextInputListener(){
                @Override
                public void input(String text) {

                }

                @Override
                public void canceled() {

                }

            }, "What is your name?", "");
```

**Comment by doit-ceo** [comment]
I'm facing the same problem (somehow) , because of the problem of predictive text, I'm using an HTML overlay input box (I just copy the value from html->LibGDX). Now, the backspace will not come in HTML field, but it's in the LibGDX one ! this is the only key is being filter out. So any way to disable all text input listener in GWT/LibGDX, I need the touch events only and let the HTML handles the keys !

**Comment by Vkrun** [comment]
@MobiDevelop  Same here. I Find something and can reproduce with the exists sample:
1. Change your browser size to small size(fit the game view, make sure the popup dialog will cover on the game view).
2. Open the links bellow: (From your discusses, every link will get the same result).
 a. http://qfrog.de/libgdx/gwt-textbox-test-html-old/
 b. http://qfrog.de/libgdx/gwt-textbox-test-html-new/
 c. http://qfrog.de/libgdx/gwt-textbox-test-html-new-gwt2.6.0/
3. Type something and press backspace, then nothing will happed.

BUT if you change the browser size(the window size) to bigger one(or max), then refresh the page, the popup dialog is out of the game view(It's in center of your browser), and now the backspace is working.

------------------------------------------
Small window, Backspace is not working. The input dialog covering on game view.
![not_working](https://user-images.githubusercontent.com/4045607/39405527-15a995ce-4bd9-11e8-80b0-1737870bd5b8.png)

------------------------------------------
Big window, Backspace is working. The input dialog not covering on game view.
![working](https://user-images.githubusercontent.com/4045607/39405528-16156074-4bd9-11e8-9644-37d13547255b.png)

I test with LibGdx(1.9.8) and Chrome(64.0.3282.186 64bit) and Windows 10.
@Trurl101 Thanks for your research, Your test is cool. I get same result as you.

BTW, I use https://sweetalert2.github.io/ as my input dialog, and everything is same as "Gdx.input.getTextInput".

**Comment by Frosty-J** [comment]
Regarding the comments from after this issue was closed, `Gdx.input.setCatchKey(Input.Keys.BACKSPACE, false)` is often needed so that libGDX doesn't swallow backspace. That is the only key it catches by default.
